src/SolutionTemplate/UnoSolutionTemplate.Wizard.2019/UnoSolutionWizard.cs
GitHub Issue (If applicable): closes #9572
- Bugfix
When template is created via the wizard, the iOS project is not deployable when targeting iOS devices via MacHost
Marked deployable by default.
=> fix: Ensure Xamarin.iOS target is deployable when Mac Host is connected

src/SamplesApp/SamplesApp.UITests/Microsoft_UI_Xaml_Controls/RefreshContainerTests/Given_RefreshContainer.cs, src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/RefreshContainerTests/RefreshContainerHorizontalScroll.xaml, src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/RefreshContainerTests/RefreshContainerHorizontalScroll.xaml.cs, src/SamplesApp/UITests.Shared/UITests.Shared.projitems, src/Uno.UI/Microsoft/UI/Xaml/Controls/PullToRefresh/Native/NativeRefreshControl.Android.cs
GitHub Issue (If applicable): closes #https://github.com/unoplatform/uno.extensions/issues/789
- Bugfix
- Horizontal scrolling in `RefreshContainer` is not reliable
- Reliable, fix based on https://github.com/nventive/Nventive.View/blob/master/src/View.Uno/Controls/SwipeRefresh/NativeSwipeRefresh.Android.cs
=> fix: Android `RefreshContainer` horizontal scrollable content

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Media/ImageBrushTests/ImageBrush_Stretch.cs, src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Media/Transform_Tests/Basics_Automated.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media/Given_BasicAutomatedTransformation.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media/Transform/Basics_Automated.xaml, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media/Transform/Basics_Automated.xaml.cs
GitHub Issue (If applicable): #9811
The Basic automated transformation tests are in the Sample App test for all platforms.
This test will be on runtime tests for most platform except for Wasm  that does not have the equivalent of `Take Screenshot` and probably MacOs that does not interpret colors the same way.
=> chore(test): Move BasicAutomated transformation tests to runtime

doc/articles/features/windows-ui-xaml-xbind.md, src/SourceGenerators/Uno.UI.SourceGenerators.Tests.Shared/Given_XBindRewriter.cs, src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/Utils/XBindExpressionParser.cs, src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_TypeCast.xaml, src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_TypeCast.xaml.cs, src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_TypeCast_DataTemplate.xaml, src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_TypeCast_DataTemplate.xaml.cs, src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Given_xBind_Binding.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/8208, closes https://github.com/unoplatform/uno/issues/5061
- Feature
Adds enhanced support for `x:Bind` cast.
=> feat(xBind): Enhanced support for x:Bind casting expressions

src/Uno.UI-iOS-hotreload-vsix-only.slnf, src/Uno.UI-macOS-only.slnf
- Bugfix
Slnf for macOS is referencing Logging.Extensions instead of Extensions.Logging
Fixed
=> fix: slnf referencing non-existing project

doc/articles/get-started-dotnet-new.md
Running `dotnet new -i Uno.ProjectTemplates.Dotnet` now produces a warning:
> Warning: use of 'dotnet new --install' is deprecated. Use 'dotnet new install' instead.
> For more information, run:
>    dotnet new install -h
Switch to  `dotnet new install Uno.ProjectTemplates.Dotnet` in the docs
=> docs: Update deprecated 'dotnet new -i' usage

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ImageTests/UnoSamples_Tests.Image.cs, src/SamplesApp/UITests.Shared/Assets/InvalidImage.jpg, src/SamplesApp/UITests.Shared/UITests.Shared.projitems, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/Image_Invalid.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/Image_Invalid.xaml.cs, src/Uno.UI/UI/Xaml/Controls/Image/HtmlImage.wasm.cs, src/Uno.UI/UI/Xaml/Controls/Image/Image.wasm.cs, src/Uno.UI/WasmCSS/Uno.UI.css
- Bugfix
When `Image` source is invalid, it does display "broken image" icon on WASM. If empty, it shows border.
When `Image` source is invalid, it does not display at all.
=> fix: Invalid `Image` should not display

.config/dotnet-tools.json, .gitignore, build/Uno.UI.Build.csproj, src/Uno.UI/MixinGeneration.targets
When building `Uno.UI.Skia` for net7.0 and netstandard2.0 in parallel, `_InnerGenerateMixins` runs twice in parallel, and can cause the following failure:
```
Could not write output file 'D:\a\1\s\src\Uno.UI\Mixins\DependencyPropertyMixins.g.cs':
System.IO.IOException: The process cannot access the file 'D:\a\1\s\src\Uno.UI\Mixins\DependencyPropertyMixins.g.cs' because it is being used by another process.
at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
at …
```
=> build: Fix race condition when generating mixins

build/Uno.WinUI.MSAL.nuspec, build/Uno.WinUI.nuspec, build/uno.winui.targets, build/uno.winui.winappsdk.targets, doc/articles/get-started-wizard.md
- Bugfix
- Reverts https://github.com/unoplatform/uno/pull/10193 as it's a common case when using Uno UI libraries, to avoid breaking changes. This change removes all Uno.UI/Uno.WinUI references from the compilation to avoid incorrect references.
- Removes Uno.UI.MSAL dependency on Uno.UI for net6.0-windows targets
=> fix: Don't fail when Uno.UI is included in an WinAppSDK app

src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/BorderTests/Border_CornerRadius_BorderThickness.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/BorderTests/Border_CornerRadius_BorderThickness.xaml.cs, src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.skia.cs, src/Uno.UI/UI/Xaml/CornerRadius.skia.cs
- Bugfix
Borders on Skia did not render correctly
Borders render correctly
=> fix: Adjust corner-radius border rendering on Skia

build/ci/.azure-devops-android-tests.yml, build/ci/.azure-devops-package-net6-win.yml, build/ci/.azure-devops-project-template-tests.yml, build/ci/.azure-devops-winui-convert.yml, build/ci/templates/dotnet6-mobile-install-mac.yml, build/ci/templates/dotnet6-mobile-install-windows.yml, build/ci/templates/dotnet7-mobile-install-mac.yml, build/ci/templates/dotnet7-mobile-install-windows.yml, src/Uno.CrossTargetting.props, src/netcore-build.props, src/uno.mobile-cross-targeting-disable.props
Avoids the following message:
```
CSC : error CS1705: Assembly 'Uno.UI' with identity 'Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' uses 'Microsoft.iOS, Version=16.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' which has a higher version than referenced assembly 'Microsoft.iOS' with identity 'Microsoft.iOS, Version=15.4.300.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' [/Users/runner/work/1/s/src/Calculator.Mobile/Calculator.Mobile.csproj]
```
=> ci: Split net6mobile and net7mobile

src/SamplesApp/SamplesApp.UITests/Constants.cs, src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TextBoxTests/TextBoxTests.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_Selection.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_Selection.xaml.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/MultilineTextBoxDelegate.iOS.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/SinglelineTextBoxDelegate.iOS.cs
GitHub Issue (If applicable): closes #9908 
- Bugfix
When a TextBox is set as `Readonly` Text is not selectable.
=> fix(iOS): Text Selection on ReadOnly TextBox

build/uno.winui.winappsdk.targets
The current change removes all binaries from the net5.0-windows target, which is incorrect as it also removes uno.toolkit.ui (as it includes ElevatedView and VisibleBoundsPadding).
The proper fix is to specifically modify Uno.WindowsCommunityToolkit, which does not include a Windows target. This causes netstandard2.0 binaries to incorrectly show up in the build.
Related to https://github.com/unoplatform/uno/issues/10182 and https://github.com/unoplatform/uno/pull/10193
=> fix(reg): Remove invalid removal of uno.ui files when building with WinAppSDK

src/Uno.UI.Runtime.Skia.Gtk/UI/Xaml/Controls/TextBoxViewExtension.cs, src/Uno.UI.Runtime.Skia.Wpf/Extensions/UI/Xaml/Controls/TextBoxViewExtension.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/TextBox_Focus_Leak.xaml, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/TextBox_Focus_Leak.xaml.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement_And_Leak.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ContentDialog.cs, src/Uno.UI/UI/Xaml/Controls/ContentDialog/ContentDialog.cs
GitHub Issue (If applicable): closes #10135, closes #8980, closes #10342
- Bugfix
`ContentDialog` does not get focused
It does!
=> fix: `ContentDialog` does not receive focus

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement_And_Leak.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/AnimatedIcon/AnimatedIcon.Uno.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/AnimatedIcon/AnimatedIcon.cs
GitHub Issue (If applicable): closes #10309 
- Bugfix
`AnimatedIcon` always subscribed to its `Foreground` brush changes, but did not unsubscribe.
Unsubscribing on `Unload` correctly.
=> fix: `AnimatedIcon` leaks

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
The generation tooling may crash with:
```
at <unknown> <0xffffffff>
at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator:BuildResourceLoaderFromFilePath <0x007ca>
at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator:GenerateResourceLoader <0x001e2>
at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator:BuildApplicationInitializerBody <0x0014a>
at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator:BuildInitializeComponent <0x00432>
at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator:InnerGenerateFile <0x009da>
at Uno.UI.SourceGenerators.XamlGenerator.XamlFileGenerator:GenerateFile <0x003aa>
at <>c__DisplayClass42_0:<Generate>b__2 <0x0037a>
at System.Func`2:invoke_TResult_T <0x000ad>
at SelectQueryOperatorResults:GetElement <0x00070>
at …
```
=> fix(reg): don't dispose AssemblyDefinition on mono

src/SamplesApp/SamplesApp.Shared/Samples/UnitTests/UnitTestsPage.xaml.cs, src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Media/GeometryTests/UnoSamples_Tests.ClosedFigurePage.cs, src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.cs, src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Controls/SampleChooserContent.cs, src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Controls/SampleControlInfoAttribute.cs, src/SamplesApp/UITests.Shared/Toolkit/ElevatedView_Dimensions.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ComboBox/ComboBox_DropDownPlacement.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/CommandBar_Native_With_AppBarButton_With_Foreground.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/Geometry/ClosedFigurePage.xaml.cs
GitHub Issue (If applicable): closes #4684
- Feature
SamplesApp `Page` samples are instantiated using `Activator`.
`Page` samples are navigated to using a `Frame`. This ensures their `Page.Frame` property is not `null` and `OnNavigatedTo` method is called.
=> Load Samples app Pages within Frame

src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props, src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/GenerationInfoManager.cs, src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGenerator.cs
- Bugfix
Ensures that metadata update use the latest generation regardless of separate processes building the source.
=> fix: don't reset runinfos on full builds as generations are no longer ignored

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ImageTests/UnoSamples_Tests.Image.cs, src/SamplesApp/UITests.Shared/UITests.Shared.projitems, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/Image_Source_Nullify.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/Image_Source_Nullify.xaml.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Image.cs, src/Uno.UI/UI/Xaml/Controls/Image/Image.skia.cs
GitHub Issue (If applicable): closes #10048
- Bugfix
When `Image.Source` is set to `null` on Skia, the image stays displayed.
Should not be displayed.
=> fix: `Image.Source` nullify

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement_And_Leak.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/Breadcrumb/BreadcrumbBar.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/Breadcrumb/BreadcrumbBarItem.cs
GitHub Issue (If applicable): closes #10309 
- Bugfix
`BreadcrumbBar` leaks
`BreadcrumbBar` does not leak
=> fix: `BreadcrumbBar` leaks

build/test-scripts/run-template-tests.ps1, src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props, src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- Bugfix
Ensures that C# 7.3 can still be used as a compilation target (for older Xamarin)
=> fix(reg): Adjust hot reload generation for C# 7.3

src/crosstargeting_override.props.sample
- Bugfix
.NET 7 mobile targets are not listed correctly in crosstargeting sample file
Listed
=> fix: List .NET 7 mobile targets in crosstargeting sample

src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.Xaml.cs
We have no control over how this variable is set outside of Uno E.g. https://github.com/xamarin/xamarin-android/pull/6027/files
- Bugfix
Only `debug` (all lowercase) is accepted. E.g. `Debug` as used by `net6.0-android` would be `false`.
Any case insensitive variation of `debug` is accepted. E.g. `Debug` as used by `net6.0-android` would be `true` instead of `false`.
=> fix: ignore case when comparing environment variable

build/PackageDiffIgnore.xml, src/Uno.UI.BindingHelper.Android/Uno/UI/UnoViewGroup.java, src/Uno.UI/Controls/BindableView.Android.cs, src/Uno.UI/UI/Xaml/Controls/Border/Border.Android.cs, src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.Android.cs, src/Uno.UI/UI/Xaml/Controls/Panel/Panel.Android.cs, src/Uno.UI/UI/Xaml/FrameworkElement.Android.cs
GitHub Issue (If applicable): #8597 
This change reduces the invocations of IsLayoutRequested in OnLayout as OnLayoutCore can already provide the native value.
=> perf: Adjust IsLayoutRequested interop on arrange

doc/articles/features/using-skia-gtk.md, src/Directory.Build.targets, src/SamplesApp/SamplesApp.Skia.Gtk/SamplesApp.Skia.Gtk.csproj
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/9269
- Feature
With recent builds of GtkSharp, NativeAOT is now supported. This PR adds some documentation for it and a GtkSharp bump.
=> feat(gtk): Add support for .NET Native AOT

build/Uno.WinUI.nuspec, build/uno.winui.winappsdk.targets
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/10463
- Bugfix
Fixes the referenced assemblies when building with WinAppSDK. Uno.UI.Toolkit.dll is the only reference needed in this case.
=> fix(winappsdk): Ensure that only the ui.toolkit assemby is referenced

src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.Xaml.cs
- Bugfix
RemoteControl fails with a `NullReferenceException` when `DOTNET_MODIFIABLE_ASSEMBLIES` is not set.
No exception.
Issue introduced with my previous commit 607da54f69f3886d3aa25ba19dffcea262f7b188
=> fix: avoid NRE when DOTNET_MODIFIABLE_ASSEMBLIES is not set

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBlock.cs, src/Uno.UI/UI/Xaml/Documents/InlineCollection.skia.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/10494
- Bugfix
Prevents invalid operation when measuring a wrapped TextBlockwithout sufficient measure space.
=> fix(skia): support inline rendering for constrained measure size

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Flyout.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBlock.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/PullToRefresh/ScrollViewerIRefreshInfoProviderAdapter/ScrollViewerIRefreshInfoProviderAdapter.cs, src/Uno.UI/UI/Xaml/Controls/Flyout/Flyout.cs, src/Uno.UI/UI/Xaml/Controls/Flyout/FlyoutBase.cs, src/Uno.UI/UI/Xaml/Controls/MenuBar/MenuBarItem.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/10400
- Bugfix
- Fix propagation during `ShowAttachedFlyout`
- Fix propagation when used in `MenuBarItem`
- Adjusts WinUI duplicate namespace when using auto-generated WinUI branch
=> Fix multiple Flyout DataContext propagation issues

src/AddIns/Uno.UI.Lottie/LottieVisualSource.iOSmacOS.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/10312
- Bugfix
Enhanced support for ms-appx broke non-automatic playback. This PR restores this feature.
=> fix(lottie): Lottie animation using ms-appx source fails to manually start

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_MenuFlyout.cs, src/Uno.UI/UI/Xaml/Controls/MenuFlyout/MenuFlyoutItem.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/10479
- Bugfix
Fixes CanExecute refresh on flyout loaded.
=> fix(MenuFlyoutItem): synchronize can execute on loaded

src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/Shared/App.xaml.cs, src/SolutionTemplate/UnoSolutionTemplate.netcore/Shared/App.xaml.cs, src/SolutionTemplate/UnoSolutionTemplate/Shared/App.xaml.cs
- Bugfix
A Uno app built for MacCatalyst logs differently than the same app built for macOS.
A Uno app running on macOS (AppKit or Catalyst) both logs, by default, to stdout.
=> fix(templates): Have MacCatalyst apps logs just like macOS apps do

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TextBoxTests/TextBoxTests.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.Android.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.Overrides.Android.cs
GitHub Issue (If applicable): closes #9908
- Feature
TextBox Readonly will disable the control preventing the users from selecting and copying Text
=> feat(droid): Enable Text Selection on ReadOnly TextBox

build/PackageDiffIgnore.xml, src/SolutionTemplate/UnoSolutionTemplate/Shared/App.xaml.cs, src/Uno.UI.RuntimeTests/IntegrationTests/dxaml/controls/calendarview/CalendarViewIntegrationTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/NavigationView/NavigationViewTests.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_Window.cs, src/Uno.UI.Tests/Windows_UI_Xaml/Given_Window.cs, src/Uno.UI/UI/Xaml/Window.Android.cs, src/Uno.UI/UI/Xaml/Window.Desktop.cs, src/Uno.UI/UI/Xaml/Window.cs, src/Uno.UI/UI/Xaml/Window.iOS.cs, src/Uno.UI/UI/Xaml/Window.macOS.cs, src/Uno.UI/UI/Xaml/Window.skia.cs, src/Uno.UI/UI/Xaml/Window.wasm.cs
- Bugfix
- Feature
Window constructor should not be available in UWP based solutions
Window constructor should not be currently used in Uno targets
Fixed
=> feat: Warn when Window constructor is used in Uno Platform targets

src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/10547
- Bugfix
Xamarin projects explicit set LangVersion to 7.3, regardless of the VS version, causing lambda parameters shadowing to fail, this change restores the original behavior.
=> fix(reg): Don't use C# 8.0 lambda parameter shadowing for xamarin projects

src/Uno.UI/FeatureConfiguration.cs, src/Uno.UI/UI/Xaml/Controls/ListViewBase/NativeListViewBase.Android.cs, src/Uno.UI/UI/Xaml/Controls/ListViewBase/NativeListViewBase.SnapPoints.Android.cs, src/Uno.UI/UI/Xaml/Controls/ListViewBase/NativeListViewBase.cs, src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.Android.cs, src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.SnapPoints.cs, src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.cs
GitHub Issue (If applicable): closes unoplatform/nventive-private#421
- Bugfix
On Android when scrolled, ListView with snapping will oscillate forever between the different snap-points resulted from uno and native implementations.
Add a `FeatureConfiguration` to toggle the implementation.
unoplatform/nventive-private#42
=> fix(droid): LV oscillating snapping

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs, src/Uno.UI/UI/Xaml/Controls/ItemsControl/ItemsControl.cs, src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.cs
GitHub Issue (If applicable): closes #9620
- Bugfix
When an item of type `FrameworkElement` is removed from `ListView.Items`, it is not being properly removed and remains in the visual tree.
When removed, the item is detached from the visual tree.
=> fix(ListView): fe item removal cleanup

src/SourceGenerators/Uno.UI.Tasks/Assets/RetargetAssets.cs
Currently build logs for Uno apps output "Retargeting UWP assets to Android", etc.
Build logs output "Retargeting assets to Android", etc., as technically the assets are in shared project anyway, so they are not "UWP" nor "WinAppSDK" specific, the task is just adjusting them for the target platform.
=> chore: Avoid using UWP naming while retargeting assets

src/AddIns/Uno.UI.Lottie/LottieVisualSourceBase.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/Repeater/RepeaterTests.cs, src/Uno.UI.Tests/Uno.UI.Tests.csproj, src/Uno.UI.Tests/Windows_UI_Xaml/Controls/ThemeResource_When_Setter_Override_From_Visual_Parent.xaml, src/Uno.UI.Tests/Windows_UI_Xaml/Controls/ThemeResource_When_Setter_Override_From_Visual_Parent.xaml.cs, src/Uno.UI.Tests/Windows_UI_Xaml/Controls/ThemeResource_When_Setter_Override_State_From_Visual_Parent.xaml, src/Uno.UI.Tests/Windows_UI_Xaml/Controls/ThemeResource_When_Setter_Override_State_From_Visual_Parent.xaml.cs, src/Uno.UI.Tests/Windows_UI_Xaml/Given_ThemeResource.cs, src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/Given_XamlReader.cs, src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/When_Setter_Override_From_Visual_Parent.xamltest, src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/When_Setter_Override_State_From_Visual_Parent.xamltest, src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/When_ThemeResource_Inherited_multiple.xamltest, src/Uno.UI/UI/Xaml/Controls/Control/Control.cs, src/Uno.UI/UI/Xaml/Controls/Control/Control.net.cs, src/Uno.UI/UI/Xaml/DependencyObjectStore.cs, src/Uno.UI/UI/Xaml/Markup/Reader/XamlObjectBuilder.cs, src/Uno.UI/UI/Xaml/ResourceResolver.cs
GitHub Issue (If applicable): closes #10551, closes https://github.com/unoplatform/uno/issues/10131
- Bugfix
- Ensures that setters applied via ThemeResource get refreshed when entering the visual tree
- Ensures that VisualState.Setters get properly updated when entering the visual tree
=> fix(resources): Use visual parent search for style setters and visual states

src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/SvgImageSource_Icons.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/SvgImageSource_Icons.xaml.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_MenuFlyout.cs, src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePickerFlyout_Partial.cs, src/Uno.UI/UI/Xaml/Controls/Flyout/FlyoutBase.cs, src/Uno.UI/UI/Xaml/Controls/MenuFlyout/MenuFlyout.cs
GitHub Issue (If applicable): closes #10554
- Bugfix
Previously items added to `MenuFlyout` during `Opening` event execution were not considered for icon display.
Works correctly.
=> fix: Delayed `MenuFlyout` item with icon

src/Uno.UI.Tests/DependencyProperty/Given_DependencyProperty.cs, src/Uno.UI/UI/Xaml/DependencyPropertyDetails.cs
- Bugfix
Fix potential memory leak in `DependencyObject` when local value override fails to clear cached field value.
=> fix(dp): Don't keep a strong reference to the last local value

doc/articles/uno-development/Uno-UI-XAML-ResourceTrimming.md, src/SourceGenerators/Uno.UI.SourceGenerators/BindableTypeProviders/DependencyObjectAvailabilityGenerator.cs, src/SourceGenerators/Uno.UI.Tasks/LinkerHintsGenerator/LinkerHintGeneratorTask.cs, src/SourceGenerators/Uno.UI.Tasks/Uno.UI.Tasks.csproj, src/Uno.Foundation/Diagnostics/CodeAnalysis/AdditionalLinkerHintAttribute.cs, src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/Given_XamlReader.cs, src/Uno.UI/AssemblyInfo.cs, src/Uno.UI/DataBinding/BindingPropertyHelper.MemberBinder.cs, src/Uno.UI/DataBinding/BindingPropertyHelper.cs, src/Uno.UI/UI/Xaml/Controls/RichEditBox/RichEditBox.cs, src/Uno.UI/UI/Xaml/Input/FocusManager.mux.cs, src/Uno.UI/Uno.UI.Wasm.csproj
- Feature
- Adjust RichTextBox, MenuFlyout and TextBox trimming
- Add support for `AdditionalLinkerHint` to remove some create weak unconditional uses of `ExpandoObject`.
=> Misc trimming, conditionally exclude ExpandoObject binding

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Flyout.cs, src/Uno.UI/UI/Xaml/Controls/Flyout/FlyoutBase.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/10591
- Bugfix
Not working according to UWP/WinAppSDK.
Behaving correctly.
=> fix: `Flyout.Opening` cancellation

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.skia.cs
GitHub Issue (If applicable): closes #10621
- Bugfix
`TextBox` appears empty on first load even though there is content
Content loaded correctly.
=> fix(Skia): Initialize `DisplayBlock` text in `TextBoxView`

src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.iOSmacOS.cs, src/Uno.UI/UI/Xaml/Shapes/Shape.cs, src/Uno.UI/UI/Xaml/Shapes/Shape.iOSmacOS.cs
closes https://github.com/unoplatform/uno/issues/10283
Attempt to fix possible crash when using CGColor
We get some crash reports when changing the `FillColor` of an `CALayer`.
We are flaggimg the native `CGColor` instances with `GC.KeepAlive` to make sure the ref remains active long enough.
=> fix: Attempt to fix possible crash when using CGColor

src/Uno.UI/UI/Xaml/DragDrop/DragDropExtension.wasm.cs, src/Uno.UI/Uno.UI.Wasm.csproj, src/Uno.UWP/ApplicationModel/Contacts/Internal/WasmContact.wasm.cs, src/Uno.UWP/ApplicationModel/Contacts/Internal/WasmContactAddress.wasm.cs, src/Uno.UWP/Helpers/Serialization/JsonHelper.wasm.cs, src/Uno.UWP/Storage/Internal/NativeStorageItemInfo.wasm.cs, src/Uno.UWP/Storage/Pickers/Internal/NativeFilePickerAcceptType.wasm.cs, src/Uno.UWP/Storage/Pickers/Internal/NativeFilePickerAcceptTypeItem.wasm.cs, src/Uno.UWP/Uno.Wasm.csproj
Remove dependency to DataContractSerializers
Use DataContract serializer for internal complex object marshaling. This has the incinvenient to bring lot of dependencies like `System.Xml` and reduces linker efficiency.
Use `System.Text.Json`.
=> perf: Remove dependency to DataContractSerializers

src/SourceGenerators/System.Xaml/Uno.Xaml.csproj, src/Uno.UI.Dispatching/Core/CoreDispatcher.wasm.cs, src/Uno.UI.RuntimeTests/MUX/Utilities/IdleSynchronizer.cs, src/Uno.UI.RuntimeTests/MUX/Utilities/RunOnUIThread.cs, src/Uno.UI/UI/Xaml/DragDrop/DragDropManager.cs, src/Uno.UWP/System/DispatcherQueue.cs, src/Uno.UWP/System/DispatcherQueueTimer.wasm.cs, src/Uno.UWP/UI/Core/CoreDispatcher.wasm.cs
GitHub Issue (If applicable): closes #10677
- Bugfix
Returns correct values when using `DispatcherQueue.CheckThreadAccess`/`HasThreadAccess`.
=> [Wasm][Threading] Use proper `CheckThreadAccess`/`HasThreadAccess` behavior, raise DispatcherQueueTimer on proper thread

doc/articles/features/lightsensor.md
GitHub Issue (If applicable): closes #10710
The Examples code throws `Cannot use local variable 'LightSensor' before it is declared.`
Used camelCase formatting on the `var LightSensor`, so the code doesn't throw the error.
=> Fixed the #10710 LightSensor documentation bug

src/SourceGenerators/Uno.UI.Tasks/LinkerHintsGenerator/LinkerHintGeneratorTask.cs
- Bugfix
Adjusts XAML trimming process to include nuget packages built before uno 4.6 which don't include the target framework in the uno-runtime folder.
=> fix(reg): Adjust for XAML Trimming cross-runtime libraries built before Uno 4.6

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Media_Animation/DoubleAnimation_Tests.FinalState_Opacity.cs
Related to https://github.com/unoplatform/uno/issues/9080
- CI
These test can generally work when run grouped with other tests but fail when running alone in CI.
=> test: Disable all flaky DoubleAnimation_Tests for android

src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/FrameBufferDevice.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/10474
- Bugfix
Restores correct pixel format for 32 bits framebuffer mode.
=> fix(framebuffer): Restore 32 bits color format

src/Uno.UI.Composition/Composition/CoreAnimation.iOSmacOS.cs, src/Uno.UI/UI/Xaml/Media/Animation/Animators/GPUFloatValueAnimator.iOSmacOS.cs, src/Uno.UI/UI/Xaml/Window.cs, src/Uno.UWP/UI/Core/VisibilityChangedEventArgs.cs
GitHub Issue (If applicable): closes #10627
- Bugfix
On-going animation bricks after alt-tabbing out and back.
The animation now continues to play.
ninja-fix: CoreWindow.VisibilityChanged's event-args always passing `Visible` as false.
=> fix(ios): animation stopped when app resumes from background

src/SourceGenerators/SourceGeneratorHelpers/Helpers/PlatformHelper.cs, src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/DependencyObjectGeneratorTests/Given_DependencyObjectGenerator.cs, src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/ImplementedRoutedEventsGeneratorTests/Given_ImplementedRoutedEventsGenerator.cs, src/SourceGenerators/Uno.UI.SourceGenerators/DependencyObject/DependencyObjectGenerator.cs, src/SourceGenerators/Uno.UI.SourceGenerators/ImplementedRoutedEvents/ImplementedRoutedEventsGenerator.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/10556
- Bugfix
Source generators will not run if compiler visible properties are not set properly.
=> fix(uap): Fix generators should not run under uap library builds

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media_Animation/Given_DoubleAnimation.cs, src/Uno.UI/DataBinding/BindingPropertyHelper.cs, src/Uno.UI/UI/Xaml/Media/Animation/Timeline.animation.cs
GitHub Issue (If applicable): closes #2498
- Bugfix
Animation on repeat=forever would be stuck animating between end-value to end-value after 2 iterations.
Animation will repeat with non-animated value as starting value.
=> fix(animation): forever animation not repeating from default value

src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/Given_XamlReader.cs, src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/When_ResourceDictionary_With_Theme_And_No_Static.xamltest, src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/When_ResourceDictionary_With_Theme_And_Static.xamltest, src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/When_ThemeResource_With_StaticResource.xamltest, src/Uno.UI/UI/Xaml/Markup/Reader/XamlObjectBuilder.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/10800
- Bugfix
Ensures that XamlReader can load top-level ResourceDictionary instances with Theme and Merged dictionaries.
=> fix(xamlreader): Process members on top-level resource dictionaries

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Flyout.cs, src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls.Primitives/FlyoutBase.cs, src/Uno.UI/UI/Xaml/Controls/Flyout/FlyoutBase.cs
GitHub Issue (If applicable): closes #n/a
- Bugfix
FlyoutBase::XamlRoot is not implemented.
^ implemented.
=> fix(flyout): XamlRoot not implemented

src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/Views/UnoQuickStart.csproj
GitHub Issue (If applicable): closes #10888
- Bugfix
Project created from new template does not restore on macOS
Project can be restored on macOS
=> fix(templates): Only build net6.0-windows10.0.18362 on Windows

src/SamplesApp/UITests.Shared/Windows_ApplicationModel/PackageTests.xaml, src/SamplesApp/UITests.Shared/Windows_ApplicationModel/PackageTests.xaml.cs, src/Uno.UI.Runtime.Skia.Gtk/GtkHost.cs, src/Uno.UI.Runtime.Skia.Wpf/WpfHost.cs, src/Uno.UI/UI/Xaml/Media/Imaging/BitmapImage.skia.cs, src/Uno.UWP/ApplicationModel/Package.Android.cs, src/Uno.UWP/ApplicationModel/Package.Other.cs, src/Uno.UWP/ApplicationModel/Package.cs, src/Uno.UWP/ApplicationModel/Package.iOSmacOS.cs, src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel/Package.cs, src/Uno.UWP/Storage/StorageFile.skia.cs
GitHub Issue (If applicable): closes #10876
- Bugfix
- Feature
- `InstalledLocation` is not always correct.
- Use the executing app's assembly location as the path
- Support for `InstalledPath` property
=> `InstalledLocation` and `InstalledPath` improvements

src/SourceGenerators/Uno.UI.SourceGenerators/BindableTypeProviders/BindableTypeProvidersGenerationTask.cs
GitHub Issue (If applicable): closes #10724
- Bugfix
Crash for some iOS applications (arm64/devices) ~~possibly due to the high number of local variables (more than 2000) inside generated code~~.
Edit: _this reduce the number of fields for the type, the number of locals is still over 2000 due to how the C# compiler optimize the generated `switch`._
No crash
=> fix(gen): generate less fields BindableMetadataProvider

src/SamplesApp/SamplesApp.Shared/Embedded/SubFolder1/SubFolder2/SharedProjectEmbeddedFile.txt, src/SamplesApp/SamplesApp.Shared/SamplesApp.Shared.projitems, src/SamplesApp/SamplesApp.macOS/SamplesApp.macOS.csproj, src/SourceGenerators/Uno.UI.Tasks/Content/Uno.UI.Tasks.targets, src/Uno.UI.RuntimeTests/Tests/Windows_ApplicationModel_Resources/Given_EmbeddedResources.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/10696
- Bugfix
Restores proper EmbeddedResource LogicalName metadat for Android targets.
=> fix(embeddedresources): Restore proper AssignTargetPaths/AssignLinkMetadata for EmbeddedResource LogicalName metadata

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs, src/Uno.UI.Tests/App/Xaml/Test_MarkupExtension.xaml, src/Uno.UI.Tests/Windows_UI_Xaml/MarkupExtensionTests/Given_MarkupExtension.cs
GitHub Issue (If applicable): closes #10962
- Feature
Not supported
Supported
=> Support for custom markup extensions in `Setter`

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement_EffectiveViewport.cs, src/Uno.UI/Extensions/ViewExtensions.visual-tree.cs, src/Uno.UI/UI/Xaml/FrameworkElement.EffectiveViewport.Interface.cs, src/Uno.UI/UI/Xaml/FrameworkElement.EffectiveViewport.cs
closes https://github.com/unoplatform/uno.chefs/issues/99
fix: EffectiveViewport does not goes through native only elements
EVP propagation was not going through native only elements driving sub-elements to not receive their valid viewport
EVP propagation assumes that native elements are stretching their element and propagate the viewport of native elements only directly to their children.
This also workaround the issue https://github.com/unoplatform/uno.toolkit.ui/issues/449
=> fix: EffectiveViewport does not goes through native only elements

src/Uno.UI.RemoteControl.Server.Processors/HotReload/MetadataUpdates/CompilationWorkspaceProvider.cs
- Bugfix
Don't override the intermediate path to avoid concurrency issues between metadata update builds.
=> fix(remotecontrol): Don't force InterdemediateOutputPath for metadata updates

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs, src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/10990
- Bugfix
The change ensure that backward compatibility code path is not used when UnoHasLocalizationResources has been added to the assembly. This reverts the behavior where all assemblies containing a `GlobalStaticResources` type were considered candidates for resources lookups.
This change is validated using canaries.
=> fix(reg): Adjust UnoHasLocalizationResources metadata

src/SourceGenerators/Uno.UI.Tasks/Assets/RetargetAssets.Fonts.cs, src/SourceGenerators/Uno.UI.Tasks/Assets/RetargetAssets.cs, src/SourceGenerators/Uno.UI.Tasks/Content/Uno.UI.Tasks.targets, src/Uno.UI/Controls/UIFontHelper.iOS.cs
- Bugfix
Restores backwards compatibility for iOS/Catalyst `Info.plist` containing existing font files.
=> fix(reg): Include explicitly specified fonts in info.plist for backward compatibilty

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Flyout.cs, src/Uno.UI/UI/Xaml/Controls/Popup/PopupPanel.cs
GitHub Issue (If applicable): closes #10959
- Bugfix
- Native `DatePicker` is showing up in wrong position
- Showing up correctly at the bottom
=> fix(reg): Native `DatePicker` flyout positioning regression

src/Uno.Foundation/Uno.Core.Extensions/Uno.Core.Extensions/StreamExtensions.cs, src/Uno.UI/ts/Windows/ApplicationModel/DataTransfer/DragAndDropExtension.ts
fixes https://github.com/unoplatform/kahua-private/issues/40
[WASM] Fix support of D&D multiple files.
When dropping multiple files in the browser only the first one is accessible.
This is due to an invalid marshaling (method was invoked with only the first item id) + the data package from the browser is being cleared as soon as the event has being dispatched. As file loading is made async, sequentially, only the first item was valid.
🙃
=> fix(dragdrop): [WASM] Fix support of D&D multiple files.

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs, src/SourceGenerators/Uno.UI.Tasks/Content/uno.ui.tasks.assets.targets, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBlock.cs, src/Uno.UI/FeatureConfiguration.cs, src/Uno.UI/UI/Xaml/ResourceResolver.cs
- Bugfix
Ensures a stable lookup of the symbol fontfamily resources, as the location may change when merged dictionaries are included in App.Resources.
=> fix(reg): Adjust lookup for symbol resources

src/SamplesApp/SamplesApp.Droid/SamplesApp.Droid.csproj
- Bugfix
NuGet restore fails due to incompatible version of `AppCompatResources`
Not failing.
=> chore: Avoid NuGet restore error by updating `AppCompatResources`

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement.cs, src/Uno.UI/FeatureConfiguration.cs, src/Uno.UI/UI/Xaml/FrameworkElement.iOS.cs
linked https://github.com/unoplatform/uno.chefs/issues/99
Possible layout cycle when a sub-child invalidate its layout while being arranged
On iOS when an element invalidate its layout while being arranged, it will also invalidate all its parents, driving to a possible layout cycle.
Invalidation stops on the first layer that is currently being arranged.
=> fix: [iOS] Possible layout cycle when a sub-child invalidate its layout while being arranged

build/ci/.azure-devops-skia-tests.yml, src/SamplesApp/SamplesApp.Skia.Linux.FrameBuffer/SamplesApp.Skia.Linux.FrameBuffer.csproj, src/SourceGenerators/Uno.UI.Tasks/Content/uno.ui.tasks.assets.targets
- Bugfix
Ensures that transitive files are included on `dotnet publish`.
=> fix(assets): Include transitive and nuget assets in publish output

src/Uno.UI/Controls/Window.iOS.cs
GitHub Issue (If applicable): closes #3460 
- Bugfix
When using a MultiLine TextBox on iOS and an External Keyboard, the TextBox presents a weird scroll behaviour.
=> fix(iOS): Multiline TextBox with external keyboard

src/Uno.UWP/UI/Color.cs, src/Uno.UWP/UI/Colors.cs
```
Colors.FromInteger(int) ->
Colors.FromARGB(byte, byte, byte, byte) ->
Color.FromArgb(byte, byte, byte, byte) ->
new Color(uint)
```
```
BenchmarkDotNet=v0.13.4, OS=macOS 13.0.1 (22A400) [Darwin 22.1.0]
Apple M1, 1 CPU, 8 logical and 8 physical cores
.NET SDK=7.0.100
[Host]     : .NET 7.0.0 (7.0.22.51805), Arm64 RyuJIT AdvSIMD
DefaultJob : .NET 7.0.0 (7.0.22.51805), Arm64 RyuJIT AdvSIMD
|      Method |     Mean |   Error |  StdDev |
|------------ |---------:|--------:|--------:|
| FromInteger | 327.9 us | 0.80 us | 0.71 us |
```
```
FromInteger(int) -> new Color(uint)
```
```
BenchmarkDotNet=v0.13.4, OS=macOS 13.0.1 (22A400) [Darwin 22.1.0]
Apple M1, …
```
=> perf: avoid intermediate calls for Colors.FromInteger

src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/CoreWindowExtension.cs
When using it on a device with no input, very common in headless applications, an exception is thrown preventing the program from running. A workround would ask to always have a mouse or keyboard connected, which is not feasible in some use cases. So, let's just check if the directory exists before trying to open it and life goes on.
Signed-off-by: Matheus Castello <matheus.castello@toradex.com>
- Bugfix
`System.IO.DirectoryNotFoundException` looking for `/dev/input`
The program runs, even without any input device connected 😌
=> fix: System.IO.DirectoryNotFoundException looking for /dev/input

build/PackageDiffIgnore.xml, build/Uno.UI.Build.csproj
- Bugfix
- BREAKING CHANGE: This PR removes unavailable types and members from the WinUI variant of Uno. Those members were present in early versions of WinAppSDK, and are not implemented in Uno.
- Enable PackageDiff on WinUI variant
=> fix(winappsdk): Run package diff on winui build

src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp/.template.config/template.json, src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/Mobile/UnoQuickStart.Mobile.csproj, src/SolutionTemplate/UnoSolutionTemplate.Wizard.2022/Forms/UnoOptions.Designer.cs
GitHub Issue (If applicable): related to #626 
- Bugfix
Uno templates won't create AppKit heads until https://github.com/xamarin/xamarin-macios/issues/16401 is fixed.
=> fix: Disable appkit template creation until fixed in .NET

doc/articles/guides/solution-building-single-targetframework.md, doc/articles/toc.yml, doc/articles/uno-app-solution-structure.md
=> docs: Add an article to enable faster single-targetframework builds in VS 2022

src/Uno.UWP/UI/Colors.cs
Input string is checked twice for null.
There was also a nullability warning in the method.
> /xxxsrc/Uno.UWP/UI/Colors.cs(57,39): warning CS8605: Unboxing a possibly null value. [/xxx/benchmarks/Colors_FromInteger/Colors_FromInteger.csproj]
Single null check.
Fixed warning.
Performance change is unmeasurable, but it’s less code :-)
=> chore: reorder Colors.Parse code to avoid dupe null checks

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Repeater/Given_ItemsRepeater.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/FlowLayoutAlgorithm.uno.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/StackLayout.cs
closes https://github.com/unoplatform/uno.chefs/issues/183
Fix only first item visible when IR is out of range on load
On load, as the viewport is empty, the IR's layout realized only the first item. But when updating VP on scrolling, we where validating the changes only on the scrolling axis (mainly for perf considerations). So if the IR is nested into another SV that scrolls among the other axis, the IR would never realize items (unless windows get resized).
When we detect that we have realized only 1 item, we make sure to validate VP changes on all axis and trigger a re-layout only when needed (i.e. when the IR becomes visible, no matter the scrolling axis)
=> fix(itemsRepeater): Fix only first item visible when IR is out of range on load

src/Uno.UWP/Storage/CreationCollisionOption.cs
BREAKING CHANGE: Values of `CreationCollisionOption` weren't matching UWP. This is now fixed.
GitHub Issue (If applicable): Related to https://github.com/unoplatform/uno/discussions/10630 and https://github.com/unoplatform/uno/issues/8339
=> fix!: Correct values of `CreationCollisionOption` enum

src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp/.vscode/launch.json
Following the [Get Started with VSCode](https://github.com/unoplatform/uno/blob/ab2ee2a26e160fb73db358d84ce780a895dae413/doc/articles/get-started-vscode.md) guide, which specifically mentions to install .NET 7, I was unable to run/debug the example using `Skia.GTK (Debug)`, because it was still referencing the .NET 6.0 dll.
While I was looking at the `launch.json`, I saw the message _replace pwa-chrome with chrome_. Seems `pwa_chrome` is no longer necessary https://stackoverflow.com/a/64261636.
With .NET 7 installed and following the guide, one is now correctly able to debug the example Skia.GTK application.
There are other `launch.json` files in …
=> fix: Skia.GTK VSCode launch config to use .NET 7 in template

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.skia.cs
GitHub Issue (If applicable): closes #6289
- Bugfix
=> Avoid changing native view in `TextChanged`, trigger `TextChanging` more reliably

doc/articles/get-started-dotnet-new.md
GitHub Issue (If applicable): closes #10352 
- Documentation content changes 
On macOS running dotnet new install Uno.ProjectTemplates.Dotnet will fail.
But using dotnet new --install Uno.ProjectTemplates.Dotnet will work.
Added --install since it works on both windows and macOS.
Also, removed a broken link.
=> macOS doesn't accept dotnet install but --install, and Broken Link

src/Uno.UI.Tests/Extensions/Given_Deque.cs, src/Uno.UI/UI/Xaml/Controls/ListViewBase/Deque.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/10248
- Bugfix
This fixes dependent locations when manipulating ListView items, by ensuring that clearing a `Deque` properly releases memory.
=> fix(deque): Fix memory leak on clear

src/Uno.UI.Tests/DependencyProperty/Given_DependencyProperty.Propagation.cs, src/Uno.UI/UI/Xaml/DependencyObjectStore.Binder.cs, src/Uno.UI/UI/Xaml/DependencyObjectStore.cs, src/Uno.UI/UI/Xaml/DependencyProperty.cs, src/Uno.UI/UI/Xaml/DependencyPropertyDetails.cs, src/Uno.UI/UI/Xaml/DependencyPropertyDetailsCollection.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/10248
- Bugfix
This change ensures that the DependencyProperty value precedence changes do not keep references to instances into inaccessible precedence levels.
This change also introduces more flags to get states of `DependencyProperty` and avoid type casts.
=> perf(memory): Fix datacontext propagation on precedence level change

src/Uno.UI.Runtime.Skia.Gtk/GtkHost.cs
GitHub Issue (If applicable): closes #11249
- Bugfix
=> fix: Avoid processing GTK events before dispatching

src/Uno.UWP/UI/Colors.cs
`Colors.FromArgb` is allocating several strings while parsing.
```
BenchmarkDotNet=v0.13.4, OS=macOS 13.0.1 (22A400) [Darwin 22.1.0]
Apple M1, 1 CPU, 8 logical and 8 physical cores
.NET SDK=7.0.100
[Host]     : .NET 7.0.0 (7.0.22.51805), Arm64 RyuJIT AdvSIMD
DefaultJob : .NET 7.0.0 (7.0.22.51805), Arm64 RyuJIT AdvSIMD
|   Method |    Mean |    Error |   StdDev |
|--------- |--------:|---------:|---------:|
| FromARGB | 5.724 s | 0.0118 s | 0.0110 s |
```
`Colors.FromArgb` does not allocate any temporary string while parsing.
```
BenchmarkDotNet=v0.13.4, OS=macOS 13.0.1 (22A400) [Darwin 22.1.0]
Apple M1, 1 CPU, 8 logical and 8 physical cores
.NET …
```
=> perf: Remove string allocations from method Colors.FromArbg

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs, src/Uno.UI/UI/Xaml/Controls/ItemsControl/ItemsControl.cs, src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.cs, src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.iOS.cs, src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelGenerator.managed.cs, src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.managed.cs, src/Uno.UWP/Devices/Enumeration/Internal/Providers/Midi/MidiDeviceClassProviderBase.Android.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/10248
**Note: This PR depends on https://github.com/unoplatform/uno/pull/11237 and https://github.com/unoplatform/uno/pull/11234**
- Bugfix
This change ensures that `ItemsControl.CleanUpContainer` mirrors the behavior of `PrepareContainerForItemOverride` to avoid memory leaks.
=> fix(ItemsControl): Ensure containers are properly cleaned up in ItemsControl

src/SamplesApp/UITests.Shared/Windows_Devices/Midi/MidiDeviceEnumeration.xaml.cs
- Bugfix
Removes MidiDeviceEnumerationTests from snapshots tests temporarily to troubleshoot potential stack overflow with Android 28 in `resetResolvedLayoutDirection`.
=> ci: Remove MidiDeviceEnumerationTests from snapshot tests

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_GridView_Items.cs, src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBaseSource.iOS.cs, src/Uno.UI/UI/Xaml/FrameworkElement.iOS.cs, src/Uno.UI/UI/Xaml/UIElement.iOS.cs
GitHub Issue (If applicable): closes #10901
- Bugfix
On iOS, scrolling through ListView may show some LVI "rendering" partially.
It should no longer happens.
this also reverts #9753
=> fix(ios): LVI layouting

src/SourceGenerators/Uno.UI.SourceGenerators/BindableTypeProviders/BindableTypeProvidersGenerationTask.cs
by using a `HashSet`, where `Add` tells you if the value was present.
The time spent under the lock is smaller, so it should have a positive, if minimal, performance impact (but only in debug builds).
Code calls `Contains` and, if negative, calls `Add` on a collection.
Code calls `Add` on `HashSet` and the results tells us if it was already present (or not). Shorten the time spent under the lock.
=> chore: Avoid calling Contains+Add inside BindableTypeProvidersGenerationTask

src/SamplesApp/SamplesApp.Skia.Linux.FrameBuffer/Program.cs, src/Uno.UI.Runtime.Skia.Gtk/GtkHost.cs, src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/FramebufferHost.cs
=> fix!: Remove constructor overloads that takes an unused `args` parameter

build/PackageDiffIgnore.xml, src/Uno.UWP/UI/Core/ICoreWindowEvents.cs, src/Uno.UWP/UI/Core/ICoreWindowsEvents.iOS.cs
BREAKING CHANGE: `ICoreWindowEvents` is no longer public.
=> fix!: `ICoreWindowEvents` is made internal.

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_GridView_Items.cs, src/Uno.UI/UI/Xaml/Controls/ItemsWrapGrid/ItemsWrapGrid.cs
GitHub Issue (If applicable): closes #11055
- Bugfix
Setting the ItemWidth for the GridViewItem is not respecting the size
=> fix Gridview dynamic item width is not respected

src/Directory.Build.props, src/Uno.UWPSyncGenerator/Generator.cs
**Thanks @Youssef1313 for finding this!**
- Bugfix
- Feature
Currently Sync generator does not take into account global usings. which can cause trouble.
Bumped C# version to 11.
=> feat: Bump UWPSyncGenerator version

src/SamplesApp/SamplesApp.Droid/Properties/AndroidManifest.xml, src/SamplesApp/SamplesApp.Droid/Properties/AssemblyInfo.cs, src/SamplesApp/UITests.Shared/UITests.Shared.projitems, src/SamplesApp/UITests.Shared/Windows_Media/CameraCaptureUISample.xaml, src/SamplesApp/UITests.Shared/Windows_Media/CameraCaptureUISample.xaml.cs, src/Uno.UWP/Media/Capture/CameraCaptureUI.Android.cs
GitHub Issue (If applicable): closes #9397
- Bugfix
CameraCaptureUI crashes on Android when using net6.0+
Works properly.
`photoUri.Path` looks similar to this `"/external/images/media/50"`
On MonoAndroid, `new Uri(photoUri.Path, UriKind.RelativeOrAbsolute)` will create an absolute uri prefixed with `file:///`. This is not the case for net6.0+
Then, `LocalPath` will fail on net6.0+ because it works only for absolute paths, and throws for relative paths.
The behavior on MonoAndroid ends up that `new Uri(photoUri.Path, UriKind.RelativeOrAbsolute).LocalPath` is just the same as `photoUri.Path`, so I used that directly.
Either way, this path doesn't have any extension and the …
=> fix(CameraCaptureUI): Fix crash on net6.0+

src/Uno.UI.Runtime.Skia.Gtk/GtkHost.HarfbuzzPreload.cs, src/Uno.UI.Runtime.Skia.Gtk/GtkHost.cs, src/Uno.UI/UI/Xaml/Documents/Inline.skia.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/9793
- Bugfix
Eagerly load libharbuzz.so.0 to avoid incorrect binding with system provided versions.
=> fix(gtk): Ensure that harfbuzz is eagerly loaded to avoid system versions interference

src/Uno.UI/UI/Xaml/DependencyObjectStore.cs, src/Uno.UI/UI/Xaml/DependencyPropertyDetails.cs
GitHub Issue (If applicable): #8597
Avoid the creation of a callback manager on event raising, when no callbacks are registered.
Credit to @ebariche for finding it :)
=> perf(do): Reduce CallbackManager allocations when no callbacks are registered

src/SamplesApp/UITests.Shared/UITests.Shared.projitems, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_Snap_Rubberband.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_Snap_Rubberband.xaml.cs, src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.cs
GitHub Issue (If applicable): closes #10892
- Bugfix
On iOS, while flipping/scrolling in a ListView, it would sometimes randomly fail to snap to the item in the direction of scroll and rubber-band back to the starting place.
The rubber-banding snap should not happen anymore.
The bug occurs when the user rapidly scrolls twice within the `_snapPointsTimer.Interval`(250ms). The 2nd scrolling should begin before that 250ms interval, but not complete until `_snapPointsTimer` has proc'd. When these specific conditions are met, uno would attempt to snap towards the target location of the 1st snap. (_There will be a 2nd snap due to the 1st, but it will be canceled as the target location is a …
=> fix(ListView): ios lv snap rubber-banding

src/Uno.UI.Tests/BinderTests/Given_Binder.Indexer.cs, src/Uno.UI/DataBinding/BindingPropertyHelper.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/11446
- Bugfix
Ensures that binding to types which contain multiple indexers is using the proper overload, given the expression type.
Fixes binding to a `DataTable`'s `DataRow`.
=> fix(Binding): Adjust binding to indexer based on expression parameter

src/Uno.UI/UI/Xaml/DependencyProperty.cs, src/Uno.UI/UI/Xaml/DependencyPropertyCacheEntry.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/8597
Reduce DependencyProperty search allocations with non-reentrant `PropertyCacheEntry` mutations.
Credit to @ebariche for finding it!
=> perf(dp): Reduce property search allocations

src/SourceGenerators/SourceGeneratorHelpers/Helpers/RoslynMetadataHelper.cs, src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs, src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.Reflection.cs, src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
Two changes made:
1. Move getting symbols to XamlCodeGeneration instead of XamlFileGenerator. So we now have less calls.
2. Using `Lazy<T>` instead of `AsLockedMemoized`. Here is a benchmark for `AsLockedMemoized` vs `Lazy<T>`
```csharp
using System;
using System.Collections.Concurrent;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
public class Program
{
public static void Main(string[] args)
{
_ = BenchmarkRunner.Run(typeof(Program).Assembly);
}
}
public static class Funcs
{
public static Func<TParam, TResult> Create<TParam, TResult>(Func<TParam, TResult> function) {
return function;
}
}
[MemoryDiagnoser]
public class Benchs
{
private Func<string, ITypeSymbol> _findTypeByFullName;
private Compilation …
```
=> perf: Faster symbol lookup

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_AutoSuggestBox.cs, src/Uno.UI/UI/Xaml/Controls/AutoSuggestBox/AutoSuggestBox.cs
- Bugfix
- Does not take SIP overlay into account
- Does not properly size the popup if it does not fit above/below
- Fixed
=> fix: `AutoSuggestBox` popup positioning improvements

build/PackageDiffIgnore.xml, src/Uno.UI.Tests/Windows_UI_XAML_Controls/CanvasTests/Given_Canvas.cs, src/Uno.UI/UI/Xaml/Controls/Canvas/Canvas.Android.cs, src/Uno.UI/UI/Xaml/Controls/Canvas/Canvas.Layout.cs, src/Uno.UI/UI/Xaml/Controls/Canvas/Canvas.cs
BREAKING CHANGE: `GetLeft`, `GetTop`, `SetLeft`, `SetTop`, `GetZIndex`, and `SetZIndex` overloads that take DependencyObject are now removed. The UIElement overloads should be used instead.
=> fix!: Remove `[Get|Set][Left|Top|ZIndex]` methods that take DependencyObject from `Canvas`

src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/Given_XamlReader.cs, src/Uno.UI/UI/Xaml/Markup/Reader/XamlObjectBuilder.cs
GitHub Issue (If applicable): closes #11502
- Bugfix
Applied too late.
Applied before `ElementName` gets evaluated.
=> `XamlReader` should apply `StaticResources` before `ElementName` gets evaluated

src/SolutionTemplate/UnoLibraryTemplate.netcore/CrossTargetedLibrary.csproj, src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/Views/UnoQuickStart.csproj
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/11462
- Bugfix
New project template does not contain PRIResource itemgroup for localization.
=> fix: Add missing PRIResource in default template

src/Uno.UI/FeatureConfiguration.cs, src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.cs
GitHub Issue (If applicable): re: #10891
- Bugfix
Uno ScrollViewer snapping trigger delay can now be customized via FeatureConfiguration.
n/a
=> chore(ScrollViewer): customizable snapping delay

src/Uno.UI.Tests/Windows_UI_Xaml/Given_AdaptiveTrigger.cs, src/Uno.UI/UI/Xaml/AdaptiveTrigger.cs, src/Uno.UI/UI/Xaml/StateTriggerPrecedence.cs, src/Uno.UI/UI/Xaml/VisualStateGroup.cs
GitHub Issue (If applicable): closes #2662
- Bugfix
The first AdaptiveTrigger satisfying MinWindowWidth (if none then MinWindowHeight) is active.
This behavior is now aligned with windows. The first satisfying AdaptiveTrigger ranked by MinWindowWidth, then by MinWindowHeight, and finally by declaration order is active.
n/a
=> fix(AdaptiveTrigger): AdaptiveTriggers precedence

src/Uno.UI.BindingHelper.Android/Uno/UI/UnoViewGroup.java
- Bugfix
This change avoids relying on interning to find the `_setFrameMethod`.
=> fix(android): Rely on actual string comparison and not string reference

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/Utils/StringBuilderBasedSourceText.cs, src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs, src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGenerator.Tracing.cs, src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs, src/Uno.Foundation.Runtime.WebAssembly/Helpers/IndentedStringBuilderExtensions.cs, src/Uno.Foundation/Uno.Core.Extensions/Uno.Core.Extensions.Compatibility/Extensions/IndentedStringBuilder.cs
Found LOH string allocations in a trace:
So now, we are not allocating these large strings and letting Roslyn do the right thing with `CopyTo` and `ToString(TextSpan)` overrides.
closes #11515
=> perf: Optimize LOH string allocations in Xaml generator

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ToolTip.cs, src/Uno.UI/UI/Xaml/Controls/ToolTip/ToolTip.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/11526
- Bugfix
Ensures initial propagation of the DataContext on tooltip opening.
=> fix(tooltip): Adjust initial propagation of the DataContext

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/GenerationInfo.cs, src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/GenerationRunFileInfo.cs, src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
GitHub Issue (If applicable): closes #11465
=> perf: Avoid holding into symbols

src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/Given_XamlReader.cs, src/Uno.UI/DataBinding/BindingPropertyHelper.FastConvert.cs
- Bugfix
XamlReader.LoadXaml throws exception when attempting to parse property of type Rect:
System.ArgumentOutOfRangeException: No strategy registration for conversion 'String' to 'Rect' Arg_ParamName_Name, extensionPoint
ninja-fix: LoadXaml<T> would throw on self-closing root element, since it would inject xmlns between the `/` and `>`.
=> fix(XamlReader): parsing of Rect type property

src/Directory.Build.props, src/Uno.UI.Composition/Composition/SkiaCompositionSurface.skia.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media_Imaging/Given_RenderTargetBitmap.cs, src/Uno.UI/UI/Xaml/Controls/Image/Image.skia.cs, src/Uno.UI/UI/Xaml/Controls/ItemsControl/ItemsControl.cs, src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.DragDrop.cs, src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.cs, src/Uno.UI/UI/Xaml/Controls/ListViewBase/NativeListViewBase.iOS.cs, src/Uno.UI/UI/Xaml/Media/ImageDataKind.cs, src/Uno.UI/UI/Xaml/Media/ImageSource.Android.cs, src/Uno.UI/UI/Xaml/Media/ImageSource.iOS.cs, src/Uno.UI/UI/Xaml/Media/ImageSource.iOSmacOS.cs, src/Uno.UI/UI/Xaml/Media/ImageSource.net.cs, src/Uno.UI/UI/Xaml/Media/ImageSource.netstd.cs, src/Uno.UI/UI/Xaml/Media/Imaging/RenderTargetBitmap.Android.cs, src/Uno.UI/UI/Xaml/Media/Imaging/RenderTargetBitmap.cs, src/Uno.UI/UI/Xaml/Media/Imaging/RenderTargetBitmap.iOS.cs, src/Uno.UI/UI/Xaml/Media/Imaging/RenderTargetBitmap.macOS.cs, src/Uno.UI/UI/Xaml/Media/Imaging/RenderTargetBitmap.skia.cs, src/Uno.UI/UI/Xaml/Media/Imaging/SvgImageSource.iOSmacOS.cs, src/Uno.UI/UI/Xaml/Media/Imaging/WriteableBitmap.iOSmacOS.cs
closes https://github.com/unoplatform/uno.extensions/issues/997
Fix reordering issue on iOS
1. Pointer events are not bubbling correctly through `ListView` up to the root
2. `ListView` does not render properly after after the first collection changed
3. `RenderTargetBitmap` cannot be used a `Image.Source` to display it on canvas
1. `ListView` does the same trick as `UIScrollView` to ensure proper events bubbling
2. We make sure to clean container only **after** it has been removed by the native `UICollectionView`.
3. `RenderTargetBitmap` makes sure to read it buffer as RGBA8
==> Some feature cannot be tested with current tools. Tests will be added as demo of the pointer injection in runtime tests
=> fix(dragdrop): Fix reordering issue on iOS

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ItemsControl.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TreeView.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/TreeViewTests/When_Open_Close_Twice.xaml, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/TreeViewTests/When_Open_Close_Twice.xaml.cs, src/Uno.UI/UI/Xaml/Controls/ItemsControl/ItemsControl.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/11587
- Bugfix
Following proper ItemsControl container cleanup, ContentControl at the DataTemplate root should keep bindings.
=> fix(ItemsControl): ContentControl at the DataTemplate root should keep bindings

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TreeView.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/TreeViewTests/When_Open_Close_Twice_Grid.xaml, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/TreeViewTests/When_Open_Close_Twice_Grid.xaml.cs, src/Uno.UI/UI/Xaml/Controls/ItemsControl/ItemsControl.cs
- Bugfix
Fixes invalid Content property reset on non-ContentPresenter template root (found in TreeViewItem).
=> fix(ItemsControl): Don't clear content on IsContainerFromTemplateRoot

src/SourceGenerators/System.Xaml/System.Xaml/XamlXmlReader.cs, src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/Windows_UI_Xaml_Controls/ParserTests/Controls/When_Invalid_Element_Property.xaml, src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/Windows_UI_Xaml_Controls/ParserTests/Controls/When_Invalid_Element_Property.xaml.cs, src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/Windows_UI_Xaml_Controls/ParserTests/Given_Parser.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/discussions/11619
- Bugfix
Ensures that parsing invalid XAML does not fall into an infinite loop.
=> fix(xamlreader): Ensure adding properties on an explicit property reports an error

build/Uno.WinUI.nuspec, src/Uno.WinUIRevert/Program.cs
- fixes #11399
- Bugfix
Generated Uno.WinUI nuget does not specify any dependencies for the windows target
Generated Uno.WinUI nuget will specify the version of `Microsoft.WindowsAppSDK` & `Microsoft.Windows.SDK.BuildTools` that is used by Uno.UI.Toolkit
=> fix: adding WinUI dependencies for windows target

src/Uno.UI.Runtime.Skia.Gtk/GLRenderSurfaceBase.cs
Reverts unoplatform/uno#11497 as it causes visual rendering issues on Windows.
=> Revert "fix: Remove GuardBand on GTK HW renderers to avoid visual glitches around clipping"

.editorconfig, src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/StackLayout.cs
GitHub Issue (If applicable): closes #https://github.com/unoplatform/uno.chefs/issues/259
IR not visible on intiial load might not materialize enough items
On initial load, if IR's viewport is empty it loads only one ** OR TWO** items and won't load more items until a SV is scrolled in the major direction.
Scrolling on the minor axis also trigger materialization of items if the major axis is not yet full.
=> fix(itemsRepeater): IR not visible on intiial load might not materialize enough items

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ScrollViewer.cs, src/Uno.UI/UI/ViewManagement/InputPane/InputPane.Android.cs, src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.mux.cs
GitHub Issue (If applicable): closes unoplatform/nventive-private#190
- Bugfix
With `SoftInput.AdjustNothing`, when focused, TextBox or PasswordBox inside a ScrollViewer would be brought into view, but behind the keyboard.
^ should not happen.
=> fix(droid): BringIntoView blocked behind keyboard

src/Uno.UI.Tests/ResourceLoader/Given_ResourceLoader.cs, src/Uno.UWP/ApplicationModel/Resources/ResourceLoader.cs
GitHub Issue (If applicable): closes #5815
- Bugfix
`ResourceLoader` constructor cannot be used to retrieve an existing loader.
`ResourceLoader` constructor can be used to retrieve an existing loader.
=> fix: Retrieve existing `ResourceLoader` via constructor

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.Measure.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs, src/Uno.UI/UI/Xaml/Controls/ListViewBase/NativeListViewBase.iOS.cs, src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.iOS.cs
GitHub Issue (If applicable): closes #7754
- Bugfix
On iOS, ListView fails to re-measure itself when:
1. an item was first added to an empty source; OR
2. an item was removed from the source
The ListView will always re-measure on these two scenarios.
=> fix(ios): ListView not resizing as items change

src/Uno.UI/UI/Xaml/Application.wasm.cs, src/Uno.UI/UI/Xaml/WindowManagerInterop.wasm.cs, src/Uno.UI/ts/CoreDispatcher.ts, src/Uno.UI/ts/Interop/IUnoDispatch.ts, src/Uno.UI/ts/Interop/_global.ts, src/Uno.UI/ts/WindowManager.ts, src/Uno.UI/ts/Windows/Storage/StorageFolder.ts, src/Uno.UI/tsBindings/WindowManagerInitParams.ts
Issue: unoplatform/uno#11769
- Other... Please describe: Remove broken feature
WPF hosting mode was used to help debug WASM apps. We're removing it because WASM debugging has improved significantly since then, the feature has been broken for a while and it is getting in the way of supporting CSP (https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP).
=> chore: Remove WPF hosting mode

src/SamplesApp/SamplesApp.netcoremobile/Android/AssemblyInfo.Android.cs, src/Uno.UWP/Media/Capture/CameraCaptureUI.Android.cs, src/Uno.UWP/Media/Capture/CameraCaptureUI.cs
GitHub Issue (If applicable): closes #11787
- Bugfix
We ask for `WRITE_EXTERNAL_STORAGE` permission, which has no effect on Android 11 and later, hence, we throw exception because the permission is not granted (this is a breaking change from Android).
`WRITE_EXTERNAL_STORAGE` is only needed on Android 9 and lower. See https://developer.android.com/training/data-storage/shared/media#request-permissions
=> fix: Fix CameraCaptureUI on Android 11 and later

src/Uno.UI.RuntimeTests/Tests/Windows_Globalization/Given_ApplicationLanguages.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_DatePicker.cs, src/Uno.UI/UI/Xaml/Application.cs, src/Uno.UWP/Globalization/ApplicationLanguages.cs, src/Uno.UWP/WinRTFeatureConfiguration.cs
GitHub Issue (If applicable): closes #6880, partial improvement to #11257
- Bugfix
- `PrimaryLanguageOverride` default value is null
- `PrimaryLanguageOverride` setter allows null
- `PrimaryLanguageOverride` not persisted.
- Default value is now string.Empty matching UWP
- Null isn't allowed.
- Value is persisted (not sure if UWP does it the same way)
=> fix: Align PrimaryLanguageOverride behavior with UWP

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.Measure.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/TestsResources.xaml, src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBaseSource.iOS.cs
GitHub Issue (If applicable): closes unoplatform/nventive-private#459
- Bugfix
On iOS while scrolling through a ListView, sometimes LVItems can appear to be clipped at the bottom.
^ should no longer happen.
This issue happens inside ListView with items of different size, when a LVI is reused for content requiring larger size and its ClippedFrame was somehow not updated during the arrange phase.
=> fix(ios): LVI is sometimes clipped

build/Uno.WinUI.MSAL.nuspec, src/AddIns/Uno.UI.MSAL/AbstractApplicationBuilderExtensions.cs, src/AddIns/Uno.UI.MSAL/Uno.UI.MSAL.Reference.csproj, src/AddIns/Uno.UI.MSAL/Uno.UI.MSAL.Skia.csproj, src/AddIns/Uno.UI.MSAL/Uno.UI.MSAL.Wasm.csproj, src/AddIns/Uno.UI.MSAL/Uno.UI.MSAL.csproj, src/AddIns/Uno.UI.MSAL/Uno.UI.MSAL.netcoremobile.csproj, src/SamplesApp/SamplesApp.Droid/SamplesApp.Droid.csproj, src/SamplesApp/SamplesApp.Skia/SamplesApp.Skia.csproj, src/SamplesApp/SamplesApp.UWP.Design/SamplesApp.UWP.Design.csproj, src/SamplesApp/SamplesApp.UWP/SamplesApp.UWP.csproj, src/SamplesApp/SamplesApp.Wasm/SamplesApp.Wasm.csproj, src/SamplesApp/SamplesApp.iOS/SamplesApp.iOS.csproj, src/SamplesApp/SamplesApp.macOS/SamplesApp.macOS.csproj, src/SamplesApp/SamplesApp.netcoremobile/SamplesApp.netcoremobile.csproj, src/SamplesApp/UnoIslands.Skia/UnoIslands.Skia.csproj
GitHub Issue (If applicable): closes #11825 
- Feature
MSAL doesn't work on net6+ ios/android
MSAL works on net6+ ios/android
MSAL (Microsoft.Identity.Client) has been updated to 4.47.0 which is the first version that has support for net6 ios/android. 
=> feat: Enabling net6 support for msal on ios/android

src/AddIns/Uno.UI.Lottie/LottieVisualSource.Skottie.cs, src/SamplesApp/UITests.Shared/Lottie/LottieProgressPage.xaml, src/SamplesApp/UITests.Shared/Lottie/LottieProgressPage.xaml.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/11785
- Bugfix
Restores transparent state of underlying skia surface on every load event.
=> fix(lottie): Ensure that opaque state is adjusted on any Loaded event

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TreeView.cs, src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/11821
- Bugfix
When manipulating its internal ListView, the TreeView control handles TreeViewItem datacontext changes so remove items in a recursive way. Removal of items in a ListView was incorrectly repairing indices after cleaning up containers, causing containers to be incorrectly reused.
=> fix(ListViewBase): Adjust indices repairing considering recursive list manipulation

src/SourceGenerators/Uno.UI.Tasks/Content/Uno.UI.Tasks.targets
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno.resizetizer/issues/106
cc @pictos @nickrandolph @jeromelaban 
=> fix: Make sure we add `AndroidResouce`s before `_ComputeAndroidResourcePaths` is run

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/ContentPresenter/ContentPresenter_Content_DataContext.xaml, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/ContentPresenter/ContentPresenter_Content_DataContext.xaml.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ComboBox.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ContentPresenter.cs, src/Uno.UI.Tests/Windows_UI_XAML_Controls/ComboBoxTests/Given_ComboBox.cs, src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/11022
- Bugfix
This change fixes a visible effect of TwoWay binding on ComboBox.SelectedValue being reset to null when being loaded.
=> fix(ContentPresenter): Avoid DataContext temporary reset

src/Uno.UI.Composition/Composition/ContainerVisual.cs, src/Uno.UI.Composition/Composition/ContainerVisual.skia.cs, src/Uno.UI.Composition/Composition/VisualCollection.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Composition/Given_ContainerVisual.cs, src/Uno.UI/UI/Xaml/UIElement.skia.cs
GitHub Issue (If applicable): closes #11851
- Bugfix
=> fix: `VisualCollection` changes should influence `IsChildrenRenderOrderDirty`

src/SamplesApp/SamplesApp.Droid/Properties/AssemblyInfo.cs, src/SamplesApp/SamplesApp.netcoremobile/Android/AssemblyInfo.Android.cs, src/Uno.UWP/Media/SpeechRecognition/SpeechRecognizer.Android.cs
GitHub Issue (If applicable): closes #11819
- Bugfix
Currently, the SpeechRecognizer does not ask for permission before trying to recognize speech and throws the same error as if the permission has been denied.
The SpeechRecognizer now verifies if the RECORD_AUDIO permission has been granted. If it has not been granted, the SpeechRecognizer displays an appropriate dialog to request permission.
If the user declines to grant permission, an error with proper message is thrown.
I couldn't try if the same issue is present on iOS also. 
=> fix: make the SpeechRecognizer ask before recognition

src/Uno.UI.RuntimeTests/Helpers/ImageAssert.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media_Imaging/Given_BitmapSource.cs, src/Uno.UI/UI/Xaml/Media/Brush.iOSmacOS.cs
closes #11712
Match the Brush subscription logic from the other platforms and invoke the callback for brush changes when setting an ImageBrush on an element
There are cases, such as when using a WriteableBitmap as the ImageSource, where the image data may have already been loaded prior to the ImageBrush being set on the element (ex: setting Rectangle.Fill to an ImageBrush whose ImageSource is a WriteableBitmap that has already had its data set)
=> fix: Ensure imagebrush's source is updated when set

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs, src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.managed.cs
GitHub Issue (If applicable): closes #11809
- Bugfix
ListView would miss the top most 1st or 2nd items when scrolling from the bottom to the top quickly (in `VirtualizingPanelLayout`'s term, `isLargeScroll == true`).
ListView correct layouts the 1st item after scrolling from bottom to top quickly.
I don't mind contributing a UI Test as well if it's not too hard/time-consuming. Having pointers to existing list view tests would be ideal.
N/A
=> app: Fix ListView missing top elements when flinging #11809

src/Uno.UWP/Globalization/ApplicationLanguages.iOS.cs
The Windows.Globalization.ApplicationLanguage were not properly initialized on iOS with languages from the OS.
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/11837
The system were using NSBundle.Localizations
The system is now using NSLocales.PreferredLanguages
=> Fixed ApplicationLanguages initialization on iOS

src/Uno.UI.RuntimeTests/Extensions/StoryboardExtensions.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media_Animation/Given_DoubleAnimation.cs, src/Uno.UI/DataBinding/BindingPath.cs, src/Uno.UI/Extensions/TimelineExtensions.iOSmacOS.cs, src/Uno.UI/FeatureConfiguration.cs, src/Uno.UI/UI/Xaml/Media/Animation/Animators/AnimatorFactory.Android.cs, src/Uno.UI/UI/Xaml/Media/Animation/Timeline.animation.cs
- closes unoplatform/nventive-private#464, 
- closes unoplatform/nventive-private#452
- closes #11896
- Bugfix
Currently animations with omitted `From` infers their starting value from the non-animated value.
On windows, you are allow to starting a new animation from the animated value, be mid animation or the `HoldEnd` value of a completed animation.
Aligned behavior with windows:
=> fix(animation): not defaulting starting value from animated value

src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/ColorPicker/ColorPickerTests.cs
- Bugfix
On macOS, ValidateFractionalWidthDoesNotCrash can get randomly stuck and drags the macOS runtime tests task for an hours (vs 10ish min normally):
```
info: Uno.UI.Samples.Tests.UnitTestsControl[0]
Running test ValidateFractionalWidthDoesNotCrash()
##[error]Bash exited with code '124'.
Finishing: Run macOS Runtime Tests
```
It will now time out after 10s.
In this build: https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=75309&view=results
2 out of 4 attempts at macOS runtime tests failed:
- https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=75309&view=logs&j=87167d63-bc8f-50a3-6dc5-c09ef976ffcd&s=b15d9 …
=> test: fix ValidateFractionalWidthDoesNotCrash dragging for 1hr

src/Uno.UWP/Graphics/Display/DisplayInformation.Android.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/11944
On Android api >= 30, the calculation for the Density were done using an integer result instead of a float, leading to a wrong result (density=2 instead of 2.625, for example).
=> fix(android_scaling): Fixed the calculation of the pixel density on Android

src/Uno.UI/UI/Xaml/UIElement.RoutedEvents.cs
Avoid native call to get parent while bubbling events
When bubbling routed events, on iOS and Android, we are getting the parent using native API
Use the managed clone
=> perf: Avoid native call to get parent while bubbling events

src/Uno.UI/UI/Xaml/XamlFilePathHelper.shared.cs
GitHub Issue (If applicable): #8597
=> perf: GetWinUIThemeResourceUrl shouldn't format a string

src/Uno.UI.RuntimeTests/Extensions/TimelineExtensions.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media_Animation/Given_DoubleAnimation.cs, src/Uno.UI/DataBinding/BindingPath.cs, src/Uno.UI/DataBinding/BindingPropertyHelper.cs, src/Uno.UI/UI/Xaml/DependencyPropertyDetails.cs, src/Uno.UI/UI/Xaml/DependencyPropertyValuePrecedences.cs, src/Uno.UI/UI/Xaml/Media/Animation/Timeline.animation.cs, src/Uno.UI/UI/Xaml/Media/Animation/Timeline.cs
GitHub Issue (If applicable): closes #631
- Bugfix
=> fix(animation): setting Local value should clear Animation value in filling state

src/Uno.UI/UI/Xaml/Window.Android.cs
GitHub Issue (If applicable): closes #11974 
- Feature
Android application ui displays prior to Window.Activate being called
Splashscreen stays visible until Window.Activate is called at which point the application ui is shown.
=> feat: Delaying paint until Activation

doc/articles/get-started-dotnet-new.md, doc/articles/get-started-rider.md, doc/articles/get-started-with-linux.md, doc/articles/guides/azure-static-webapps.md, doc/articles/guides/silverlight-migration/01-create-uno-solution.md
The "getting started" instructions for both Linux and Rider currently point to the deprecated Uno.ProjectTemplates.Dotnet [0] package. The instructions should be updated to use Uno.Templates [1].
[0] https://www.nuget.org/packages/Uno.ProjectTemplates.Dotnet/
[1] https://www.nuget.org/packages/uno.templates/
=> docs: update Linux/Rider templates package name

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml/DragAndDropTests/DragDrop_ListViewReorder_Automated.cs, src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/Nested_Sequence_Tests.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs, src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.cs, src/Uno.UI/UI/Xaml/Controls/Primitives/SelectorItem.cs
GitHub Issue (If applicable): closes #11971
- Bugfix
ListView with SelectionMode=Multiple doesnt show items with the multi-select check.
^ fixed.
It was too early to apply MultiSelectStates in ListViewBase::PrepareContainerForItemOverride, as LVI doesnt even have its Control::Template, which defines the visual-states, applied yet.
=> fix(ListViewItem): multi-select check missing

src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.Xaml.cs, src/Uno.UI/UI/Xaml/Application.Components.cs, src/Uno.UI/UI/Xaml/Media/VisualTreeHelper.iOSmacOS.cs
- Bugfix
Fixes Page hot reload on targets which are using native `Frame` presenters, which can cause the Frame to become empty.
=> fix(hr): Adjust Page reload for custom frame presenter

src/Uno.UWP/UI/Core/CorePhysicalKeyStatus.cs, src/Uno.UWP/UI/Input/Preview.Injection/InjectedInputPoint.cs, src/Uno.UWP/UI/Input/Preview.Injection/InjectedInputPointerInfo.cs, src/Uno.UWP/UI/Input/Preview.Injection/InjectedInputRectangle.cs
Updated some structs to follow CA1815 [0].
[0] https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1815
=> chore: fix CA1815 violations in Uno.UWP/Uno.Skia

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_RadioButton.cs, src/Uno.UI/UI/Xaml/Controls/Primitives/ToggleButton.cs, src/Uno.UI/UI/Xaml/Controls/Primitives/ToggleButton.mux.cs
=> fix: Ensure Commands are executed when RadioButton is toggled through AutomationPeer

src/SolutionTemplate/UnoUITestTemplate/TestBase.cs, src/SolutionTemplate/UnoUITestTemplate/UnoUITestsLibrary.csproj
- unoplatform/uno.templates#28
- Refactoring
UI Test project targets net48
UI Test project targets net7.0 as is the default for the other templates
=> Update UI Test project to net7

src/Uno.UI/WasmCSS/Uno.UI.css
GitHub Issue (If applicable): related to https://github.com/unoplatform/Uno.Wasm.Bootstrap/pull/707
- Bugfix
The splash screen image would not stretch correctly, especially on small screens. 
This removes the unnecessary override to bootstrapper splash styling and applies the exact same style to the "application-level" splash
=> fix: Remove bootstrapper splash override, apply same styling

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs, src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Given_xBind_Binding.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/10164
- Bugfix
Restore proper testing of When_xLoad_StaticResource, adjusting for pooling sensitivity and incorrect materialized component lookup.
=> Restore When_xLoad_StaticResource test

doc/import_external_docs.ps1, doc/import_external_docs_test.ps1
Minor fixes to *import_external_docs.ps1* and *import_external_docs_test.ps1*
Related: https://github.com/unoplatform/uno.extensions/pull/1412
=> chore: Reset dir and trace on error, and open browser when served

src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.DragDrop.cs
Fix support of items re-ordering support of ICollectionView
`ICollectionView` are not being reordered by the `ListView` when used as `ItemsSource`.
🙃
=> fix(ListView): Fix support of items re-ordering support of ICollectionView

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media_Animation/Given_DoubleAnimationUsingKeyFrames.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media_Animation/TestPages/QuickMultiTransitionsPage.xaml, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media_Animation/TestPages/QuickMultiTransitionsPage.xaml.cs, src/Uno.UI/UI/Xaml/Media/Animation/ColorAnimationUsingKeyFrames.cs, src/Uno.UI/UI/Xaml/Media/Animation/DoubleAnimationUsingKeyFrames.cs, src/Uno.UI/UI/Xaml/Media/Animation/ObjectAnimationUsingKeyFrames.cs, src/Uno.UI/UI/Xaml/Media/Animation/Storyboard.cs
GitHub Issue (If applicable): closes #8636, shadowing #12050, closes #11979
- Bugfix
Animation cannot be stopped/deactivated while it being scheduled for start.
Animation stopped/deactivated while it is scheduled for start, will be properly prevented from running.
Various `Timeline` implementations/derived `Begin`s on the dispatcher, and when asked to `Deactivate`/`Stop`, we rely on the associated animator to do so. So when you attempt to cancel an animation right after having started it, the canceling won't go through as the animator is still unassigned.
And, we ended up with situation like in ToggleSwitch where both DraggingToOffTransition+OffToOnTransition are both running, instead …
=> fix(animation): anomalies when quickly transitioning between multiple VisualStates of same VSGroup

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ScrollViewer.cs, src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml/UIElement.cs, src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.cs, src/Uno.UI/UI/Xaml/UIElement.cs, src/Uno.UI/UI/Xaml/UIElement.skia.cs
GitHub Issue (If applicable): closes #8932, closes #11066, closes #7514
Related to #7544
- Bugfix
Applies to Material TextBoxes, Flyouts, Popups, other stuff - in general - anything that used ScrollViewer in some specific cases. Layout rounding not supported anywhere except Skia - and there it is supported only very partially - and that is a big problem - for example Grid does tap into this for its layout, but things like Measure and Arrange don't. As a result, what did happen was that ScrollViewer was checking the ScrollContentPresenter's ActualHeight which was layout rounded, because the child Grid underneath made it so, but on the other hand it used ViewportHeight which was not rounded - as a result, it assumed the content is scrollable …
=> fix: Dancing Skia `ScrollViewers`

build/PackageDiffIgnore.xml, src/Uno.UI/UI/Xaml/Controls/WebView/WebView1/WebViewExtensions.cs, src/Uno.UI/UI/Xaml/Controls/WebView/WebView1/WebViewNavigationCompletedEventArgs.cs, src/Uno.UI/UI/Xaml/Controls/WebView/WebView1/WebViewNavigationFailedEventArgs.cs, src/Uno.UWP/Generated/3.0.0.0/Windows.Web/WebErrorStatus.cs, src/Uno.UWP/Web/WebErrorStatus.cs
Namespace should be Windows.Web
=> [Breaking] fix!: Change WebErrorStatus namespace

src/Uno.UI.Tests/DependencyProperty/Given_DependencyProperty.cs, src/Uno.UI/UI/Xaml/DependencyObjectStore.cs
- Bugfix
If a callback removes another one, which is scheduled to be invoked, `ObjectDisposedException` is thrown.
Does not happen
=> fix: Do not throw for already disposed callbacks

doc/articles/get-started-vscode.md
URLs points to the old templates (in this repo).
URLs points to the new templates (in the new repo).
=> docs: Fix URL to the new templates repo

src/SourceGenerators/Uno.UI.SourceGenerators/RoslynMetadataHelper.cs, src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.Reflection.cs, src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
GitHub Issue (If applicable): closes #12001
- Performance
- We query the same XamlType to get an ISymbol multiple times, each requires a dictionary lookup.
- We use `AsLockedMemoized` even when the function is accessed in a single thread.
-Figure out places where it is easy to store the ISymbol in a variable and/or pass it around instead of doing a dictionary lookup.
- Switch to AsMemoized
=> perf: Reduce dictionary lookups of repeated FindType call on the same XamlType

build/PackageDiffIgnore.xml, src/Uno.UI/UI/Xaml/Window.cs
BREAKING CHANGE: The property is read-only in UWP/WinUI
=> fix!: `Window.Visible` setter should not be public

src/Uno.UI/UI/Xaml/Controls/ComboBox/ComboBox.cs
GitHub Issue (If applicable): closes #7651 
- Feature
Many visual states of `ComboBox` are not supported
Add support for supportable visual states (`IsEditable` and related not supported as features yet, so those are missing for now)
=> feat: Support more `ComboBox` visual states

src/Uno.UI.RuntimeTests/Tests/Uno_UI_Xaml_Core/Given_RootVisual.cs, src/Uno.UI/UI/Xaml/Application.cs, src/Uno.UI/UI/Xaml/ApplicationActivity.Android.cs, src/Uno.UI/UI/Xaml/ApplicationTheme.cs, src/Uno.UI/UI/Xaml/Internal/CoreServices.cs, src/Uno.UI/UI/Xaml/NativeApplication.cs, src/Uno.UI/UI/Xaml/ThemingHelper.cs, src/Uno.UI/UI/Xaml/Window.Android.cs, src/Uno.UI/UI/Xaml/Window.Desktop.cs, src/Uno.UI/UI/Xaml/Window.cs, src/Uno.UI/UI/Xaml/Window.iOS.cs, src/Uno.UI/UI/Xaml/Window.macOS.cs, src/Uno.UI/UI/Xaml/Window.wasm.cs, src/Uno.UI/WasmCSS/Uno.UI.css, src/Uno.UI/ts/Interop/IAppManifest.ts, src/Uno.UI/ts/WindowManager.ts
GitHub Issue (If applicable): part of #10178, closes #10820, closes #6393
- Bugfix
White background flickers if Window is activated with a delay.
In tandem with https://github.com/unoplatform/Uno.Wasm.Bootstrap/pull/699 this should ensure no flickering of white color will show up on Android, iOS, macOS and WASM. This does not help on Skia yet unfortunately, as there is no splash screen yet.
=> Dismiss splash screen after initial `Window.Activate`, themed `RootVisual` background

src/Uno.UI.RuntimeTests/Helpers/StyleHelper.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/ProgressRing/ProgressRingTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/ToggleSplitButton/ToggleSplitButtonTests.cs, src/Uno.UI.RuntimeTests/MUX/Windows_UI_Xaml_Controls/DropDownButtonTests.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_ThemeResource.cs, src/Uno.UI/UI/Xaml/Application.cs, src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.cs, src/Uno.UI/UI/Xaml/Controls/Icons/BitmapIcon.cs, src/Uno.UI/UI/Xaml/Controls/Icons/FontIcon.cs, src/Uno.UI/UI/Xaml/Controls/Icons/IconElement.cs, src/Uno.UI/UI/Xaml/Controls/Icons/PathIcon.cs, src/Uno.UI/UI/Xaml/Controls/Icons/SymbolIcon.cs, src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.cs, src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.skia.cs, src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.wasm.cs, src/Uno.UI/UI/Xaml/Documents/TextElement.cs, src/Uno.UI/UI/Xaml/Documents/TextElement.wasm.cs, src/Uno.UI/UI/Xaml/FrameworkElement.cs, src/Uno.UI/UI/Xaml/Media/DefaultBrushes.cs, src/Uno.UI/UI/Xaml/UIElement.cs
GitHub Issue (If applicable): closes #3482
- Feature
- Missing support for `DefaultTextForegroundThemeBrush`
- Added support for `DefaultTextForegroundThemeBrush`
=> Support for `DefaultTextForegroundThemeBrush`

src/SamplesApp/SamplesApp.Shared/App.xaml.cs, src/Uno.UI/UI/Xaml/Application.cs, src/Uno.UI/UI/Xaml/Window.cs
GitHub Issue (If applicable): closes #12194
- Bugfix
`OnWindowCreated` is called immediately after a `Window` is created.
In UWP, `OnWindowCreated` is delayed just before `OnLaunched`
=> fix: Raise OnWindowCreated after Application.Current is set

src/Uno.Foundation/Uno.Core.Extensions/Uno.Core.Extensions.Compatibility/Reflection/TypeExtensions.cs, src/Uno.UI.RuntimeTests/Helpers/ViewModelBase.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ContentControl.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase_Items.cs, src/Uno.UI/UI/Xaml/Controls/ItemsControl/ItemsControl.cs
GitHub Issue (If applicable): closes unoplatform/nventive-private#457, closes unoplatform/nventive-private#472
- Bugfix
When ListView.ItemsSource is assigned/bound to a non-observable/notifying collection, like List<T>,
adding/removing item to the collection will cause the LV to update and the items' data-context to desync.
Like on UWP, adding/removing item to the non-observable/notifying collection will NOT update the LV.
=> fix(ItemsControl): desync from modifying ItemsSource of non-INCC/IObservableVector source

build/PackageDiffIgnore.xml, src/Uno.UWP/Devices/Sensors/SimpleOrientationSensor.Android.cs
BREAKING CHANGE: Avoid directly implementing `ISensorEventListener` on `SimpleOrientationSensor` on Android
=> fix!: Avoid directly implementing `ISensorEventListener` on `SimpleOrientationSensor` on Android

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- Bugfix
Add support for net8+ android resources constants
=> fix(android): Add support for resource resolution for net8+

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_UIElement.cs, src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml/UIElement.cs, src/Uno.UI/UI/Xaml/UIElement.cs
GitHub Issue (If applicable): closes #12238
- Feature
No support for `ActualOffset` property
Supported.
=> feat: Support for `UIElement.ActualOffset`

src/SamplesApp/SamplesApp.Shared/App.xaml.cs, src/Uno.UI/UI/Xaml/Application.Android.cs, src/Uno.UI/UI/Xaml/Application.cs, src/Uno.UI/UI/Xaml/Application.iOS.cs, src/Uno.UI/UI/Xaml/Application.macOS.cs, src/Uno.UI/UI/Xaml/Application.net.cs, src/Uno.UI/UI/Xaml/Application.netstdref.cs, src/Uno.UI/UI/Xaml/Application.skia.cs, src/Uno.UI/UI/Xaml/Application.wasm.cs, src/Uno.UI/UI/Xaml/Documents/TextElement.cs, src/Uno.UI/UI/Xaml/UIElement.cs
GitHub Issue (If applicable): closes #12255
- Bugfix
Previously the active application theme was initialized when first requested, which meant the theme for default foreground could be set to default (light in case of Uno)
Active theme is set explicitly after app initialization is completed.
=> fix: Ensure theme is initialized before UI

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ScrollViewer.cs, src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.Native.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/tradezero-private/issues/4
- Bugfix
Fast scrolling on Android returned the wrong location for a scroll child.
=> fix(ScrollView): Android FastScrolling wrong Offsets

doc/import_external_docs.ps1
which contained the fix for the broken doc links
GitHub Issue (If applicable): closes unoplatform/uno.toolkit.ui#456
updated toolkit doc commit hash reference
which contained the fix for the broken doc links
=> chore: update toolkit doc commit hash reference

build/PackageDiffIgnore.xml, src/Uno.UI/UI/Xaml/Controls/Control/Control.FocusMixins.cs
=> fix!: Remove focus-related properties from `Control` on WinUI-flavored builds

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs, src/Uno.UI/UI/Xaml/Controls/ItemsControl/ItemsControl.cs
GitHub Issue (If applicable): closes #12059
- Bugfix
LV.ItemsSource in certain binding setup can trigger ItemsTemplateSelector.SelectTemplateCore unnecessarily on INotifyCollectionChanged reset events.
^ doesnt happen anymore.
When we clean up the container, we cleared the DataContext value first, before other properties like Content. And, if Content property is data-bound (without explicit source), the binding will be re-evaluated as its DataContext is changing from a specific item to the now inherited items-source. This often result in SelectTemplateCore being called with the items-source as parameter.
=> fix(ListView): unnecessary SelectTemplate call on collection reset

build/PackageDiffIgnore.xml, src/Uno.UI/UI/Xaml/Controls/Primitives/ToggleButton.cs
=> fix!: Remove `ToggleButton.OnIsCheckedChanged`

build/PackageDiffIgnore.xml, src/Uno.UI/UI/Xaml/Documents/TextElement.cs, src/Uno.UI/UI/Xaml/Documents/TextElement.wasm.cs, src/Uno.UI/UI/Xaml/FrameworkElement.netstdref.cs, src/Uno.UI/UI/Xaml/FrameworkElement.skia.cs, src/Uno.UI/UI/Xaml/FrameworkElement.wasm.cs, src/Uno.UI/UI/Xaml/UIElement.netstdref.cs, src/Uno.UI/UI/Xaml/UIElement.skia.cs, src/Uno.UI/UI/Xaml/UIElement.wasm.cs
=> fix!: Move `Name` and `NameProperty` from `UIElement` to `FrameworkElement`

src/Uno.UI.Runtime.Skia.Gtk/GtkCoreWindowExtension.Keyboard.cs
GitHub Issue (If applicable): closes #12302
- Bugfix
UIElement.KeyDown firing twice per input.
^ no more.
regression from: https://github.com/unoplatform/uno/pull/12105
both OnKeyPressEvent & OnKeyReleaseEvent are calling RaiseNativeKeyDownReceived
likely we should be calling RaiseNativeKeyUpReceived for release, and looking at other platforms' impl confirms that
=> fix(skia): UIElement.KeyDown firing twice per input

build/PackageDiffIgnore.xml, src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/Given_XamlReader.cs, src/Uno.UI/UI/Xaml/Controls/ItemsControl/ItemsControl.cs, src/Uno.UI/UI/Xaml/Controls/ItemsPanelTemplate.cs, src/Uno.UI/UI/Xaml/DataTemplate.cs, src/Uno.UI/UI/Xaml/FrameworkTemplate.cs, src/Uno.UI/UI/Xaml/FrameworkTemplatePool.cs, src/Uno.UI/UI/Xaml/IFrameworkTemplateInternal.cs
=> fix!: LoadContent should be on DataTemplate rather than FrameworkTemplate

build/PackageDiffIgnore.xml, src/Uno.UI/UI/Xaml/FrameworkElement.cs, src/Uno.UI/UI/Xaml/FrameworkElement.net.cs, src/Uno.UI/UI/Xaml/UIElement.cs, src/Uno.UI/UI/Xaml/UIElement.net.cs
GitHub Issue (If applicable): Part of #8339 
=> fix!: Change `Measure`/`Arrange` to not be virtual

src/Uno.UWP/System/Profile/AnalyticsInfo.Android.cs
GitHub Issue (If applicable): closes #12045, part of #8339
=> fix(android)!: Fix AnalyticsInfo.DeviceForm returning mobile instead of tablet

src/Uno.UWP/UI/Color.iOS.cs, src/Uno.UWP/UI/Color.macOS.cs
GitHub Issue (If applicable): closes #https://github.com/unoplatform/uno/issues/12339
- Bugfix
`System.EntryPointNotFoundException` when trying to convert colors (on iOS or macOS) when running iOS 12.x or earlier (or before macOS 10.15).
No exception.
https://developer.apple.com/documentation/coregraphics/3042355-cgcolorcreatesrgb
=> fix: avoid calls to CGColorCreateSRGB before iOS13

src/AddIns/Uno.UI.Lottie/WasmScripts/uno-lottie.d.ts, src/AddIns/Uno.UI.Lottie/WasmScripts/uno-lottie.js, src/AddIns/Uno.UI.Lottie/ts/Uno.UI.Lottie.ts
The Lottie library was not loading properly on Wasm when the application was using the _embedded mode_.
=> fix(lottie): Improved the loadeability of Lottie library on Wasm

src/SamplesApp/SamplesApp.UITests/RuntimeTests.cs, src/Uno.UI.RuntimeTests/Tests/Uno_UI_Toolkit/Given_VisibleBoundsPadding.cs, src/Uno.UI/Behaviors/VisibleBoundsPadding.cs, src/Uno.UI/Extensions/InsetsExtensions.Android.cs, src/Uno.UI/Extensions/ViewHelper.Android.cs, src/Uno.UI/LayoutProvider.Android.cs, src/Uno.UI/UI/Xaml/ApplicationActivity.Android.cs, src/Uno.UI/UI/Xaml/Window.Android.cs
closes https://github.com/unoplatform/uno/issues/12007
- Bugfix
=> fix: dispatch setting of visibleboundspadding insets

src/AddIns/Uno.UI.MediaPlayer.WebAssembly/MediaPlayerPresenterExtension.cs, src/Uno.UI/UI/Xaml/Controls/MediaPlayerElement/MediaPlayerElement.cs
GitHub Issue (If applicable): closes #12330 
- Bugfix
MediaPlayerElement full screen not working properly on Wasm
MediaPlayerElement full screen working properly on Wasm
=> MediaPlayerElement fullscreen working properly

src/SamplesApp/SamplesApp.Wasm/SamplesApp.Wasm.csproj
- Build or CI-related changes
Building and deploying the Wasm Samples App take around 10 / 15 min
Disable linker in debug for the Wasm Samples App to have a faster build (down to less than a minute)
=> chore: Disable linker in debug for the Wasm Samples App to have a faster build

src/AddIns/Uno.UI.MediaPlayer.WebAssembly/HtmlMediaPlayer.cs, src/AddIns/Uno.UI.MediaPlayer.WebAssembly/HtmlVideo.cs, src/AddIns/Uno.UI.MediaPlayer.WebAssembly/MediaPlayerExtension.cs, src/SamplesApp/UITests.Shared/UITests.Shared.projitems, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MediaPlayerElement/MediaPlayerElement_Multiple.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MediaPlayerElement/MediaPlayerElement_Multiple.xaml.cs, src/Uno.UI/UI/Xaml/Controls/MediaPlayerElement/MediaTransportControls.cs
GitHub Issue (If applicable): closes: #12350 
Reference: https://github.com/unoplatform/uno/issues/11967
- Bugfix
Today when we have two media player on the UI just the last one works.
Now we can get as many MediaPlayer as we want
=> Multiple MediaPlayerElement controls on the same page

build/ci/.azure-devops-unit-tests.yml, src/Uno.Analyzers.Tests/Uno.Analyzers.Tests.csproj
Add missing test sdk reference to fix issue related to https://github.com/microsoft/vstest/issues/4467
=> ci: Restore 17.6 test runners

src/Uno.UI/UI/Xaml/Controls/MediaPlayerElement/MediaTransportControls.MediaPlayer.cs, src/Uno.UI/UI/Xaml/Controls/MediaPlayerElement/MediaTransportControls.cs
~NOTE: This should be merged only once https://github.com/unoplatform/uno/pull/12198 has been merged !~
Clipping of transport control of `MediaPlayerElement`
When fade in/out the `MediaTransportControl`, it appears out of the bounds of the `MediaPlayerElement`
It's now clipped
=> fix(mediaPlayer): Fix clipping of transport control

doc/articles/controls/MediaPlayerElement.md
GitHub Issue (If applicable): closes #12437
MediaPlayerElement do not supports Wasm and Skia platforms
Update the Documentation for MediaPlayerElement that now supports Wasm and Skia platforms
=> MediaPlayerElement - Update Documentation

build/PackageDiffIgnore.xml, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_ResourceDictionary.cs, src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePicker.cs, src/Uno.UI/UI/Xaml/Documents/Hyperlink.wasm.cs, src/Uno.UI/UI/Xaml/ResourceResolver.cs, src/Uno.UI/UI/Xaml/ResourceResolverSingleton.cs
=> fix!: Cleanup ResourceResolverSingleton

build/PackageDiffIgnore.xml, src/Uno.UI/UI/Xaml/Controls/Image/Image.cs
=> fix!: Make OnImageOpened `private` instead of `protected virtual`

src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault/MediaTransportControls_themeresources.xaml, src/Uno.UI.FluentTheme.v2/themeresources_v2.xaml, src/Uno.UI/UI/Xaml/Controls/MediaPlayerElement/MediaPlayerElement.cs
- Bugfix
In wasm the full screen does not come back.
In wasm the fullscreen does come back.
=> Update when back from fullscreen for wasm

src/AddIns/Uno.UI.Lottie/ts/Uno.UI.Lottie.ts
When the `<WasmShellWebAppBasePath />` was used in the csproj, the loading was not done properly because the denpendencies where using extensions (`.js`) to load them.
Now support both with and without the extension.
=> fix(lottie): Fixed a regression with lottie module loadingon WASM

src/Uno.UI/UI/Xaml/Controls/MediaPlayerElement/MediaTransportControls.MediaPlayer.cs, src/Uno.UI/UI/Xaml/Controls/MediaPlayerElement/MediaTransportControls.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/11967
- Bugfix
-->
Nulllable refs enabled for mediaplayer transport controls
=> fix(media): Enable nullable for Transport controls

doc/articles/controls/MediaPlayerElement.md
The 
Playlists support and 
Pause media when headphones unplugged
is mark on wasm and skia
The 
Playlists support and 
Pause media when headphones unplugged
is not mark on wasm and skia
=> Update docs playlist

src/Uno.UI/UI/Xaml/Controls/MediaPlayerElement/MediaTransportControls.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/11967
- Bugfix
Don't show the transport controls on touch move, only for other pointer types.
=> fix(media): Only show transport controls on mouse move

src/Uno.UI/UI/Xaml/Controls/MediaPlayerElement/MediaTransportControls.cs
GitHub Issue (If applicable): closes #12335
- Bugfix
`...` more button is not hidden when it is supposed to.
^ no more
regression from #12440
In that pr, the event subscription has been delay after the MTC is loaded. In doing so, the Loaded event of course won't trigger anymore due to how late it was subscribed.
=> fix(media): more button not hidden

src/Uno.UI/UI/Xaml/Controls/MediaPlayerElement/MediaTransportControls.cs
GitHub Issue (If applicable): closes #12509
=> [MPE][Skia] The fluent style for transport controls is clipping at the top

src/AddIns/Uno.UI.MediaPlayer.Skia.Gtk/MediaPlayerExtension.cs, src/Uno.UI/UI/Xaml/Controls/MediaPlayerElement/MediaTransportControls.MediaPlayer.cs
GitHub Issue (If applicable): closes #12497 
- Bugfix
When Stopping the video and starting multiple times may not stop the playback
When you stop the video and start playing several times, stop or play correctly
=> When Stopping the video and starting multiple times may not stop the playback

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls_Primitives/Given_Popup.cs
GitHub Issue (If applicable): closes #1809
Test
No test
Test added
=> test: `Popup` closes on visual tree removal

doc/docfx.json, doc/gulpfile.js, doc/package.json, doc/templates/uno/partials/scripts.tmpl.partial, doc/templates/uno/service/search.scss, doc/templates/uno/styles/docfx.js, doc/templates/uno/styles/main.css, doc/templates/uno/styles/main.js, doc/templates/uno/toc.html.tmpl
UNO Docs search is not working as expected in some scenarios. Sometimes we get empty results even though there should have been some matches.
ie: Looking for `IFileSavePickerExtension` returns nothing.
The default DocFx search engine has been replaced with Algolia's DocSearch to improve the docs search.
N/A
As discussed with @jeromelaban the DocSearch ID/ApiKey are committed directly into the code as they are public information that will be in the actual DOM of the documentation page.
#272655
=> chore(docsearch): Implement DocSearch by Algolia

doc/import_external_docs.ps1
This PR replaces pull with reset --hard and adds --force to checkout to avoid errors if branch was force pushed or if a different brach was previously checked out when generating docs and brach/commit was changed.
=> chore: Add --force option and reset

src/AddIns/Uno.UI.MediaPlayer.Skia.Gtk/GTKMediaPlayer.cs, src/AddIns/Uno.UI.MediaPlayer.Skia.Gtk/GTKMediaPlayer.events.cs, src/AddIns/Uno.UI.MediaPlayer.Skia.Gtk/MediaPlayerExtension.cs, src/AddIns/Uno.UI.MediaPlayer.Skia.Gtk/MediaPlayerExtension.events.cs, src/AddIns/Uno.UI.MediaPlayer.WebAssembly/MediaPlayerExtension.cs, src/SamplesApp/UITests.Shared/UITests.Shared.projitems, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MediaPlayerElement/MediaPlayerElement_Mp3_Extension.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MediaPlayerElement/MediaPlayerElement_Mp3_Extension.xaml.cs, src/Uno.UI/UI/Xaml/Controls/MediaPlayerElement/MediaPlayerElement.cs, src/Uno.UWP/Media/Playback/IMediaPlayerExtension.cs, src/Uno.UWP/Media/Playback/MediaPlayer.Android.cs, src/Uno.UWP/Media/Playback/MediaPlayer.iOSmacOS.cs, src/Uno.UWP/Media/Playback/MediaPlayer.others.cs
GitHub Issue (If applicable): closes #12332 
- Bugfix
MediaPlayerElement does not display PosterSource
MediaPlayerElement properly displays PosterSource:
- When a valid source is not set.
- While media is loading.
- When the media is audio only.
=> fix: Properly display PosterSource for MediaPlayerElement

src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.MetadataUpdate.cs, src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.Xaml.cs
GitHub Issue (If applicable): closes #12805
- Feature
Hot reloading of updated types doesn't work
Hot reloading updated types will trigger a walk of the visual tree looking for items to be replaced. 
This update also includes 
- [N/A] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [N/A] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [N/A] Validated PR `Screenshots Compare Test Run` results.
This PR only …
=> feat: Adjusting updating of visual tree

doc/import_external_docs_test.ps1
[Updates to docs toc test automation - auto open browser to correct address](chore: Updates to docs toc test automation - ensure latest tools and auto open browser to correct address)
When test is done the website open, but need to navigate and manually rename the `_site` route to reach the docs website.
1. Ensures the latest docfx and dotnet-serve are installed
2. Utilizes the [new feature](https://github.com/natemcmaster/dotnet-serve/issues/141) of specifying a path to open from dotnet-serve and opens the generated docs site
=> chore: Updates to docs toc test automation - ensure latest tools and auto open browser to correct address

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media/Given_BasicAutomatedTransformation.cs
GitHub Issue (If applicable): #9080
Test is failing on Android. The reason is that `SUT` already has a parent, and then we try to set it to ContentControl.Content. The test actually already fails on Windows, so I didn't attempt to gracefully handle this case in `ContentControl.RegisterContentTemplateRoot`.
A little test hack to remove the parent to allow the test to run successfully.
=> test: Unskip `Basics_AutomatedTransformation` on Android

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml/DragAndDropTests/DragDrop_ListViewReorder_Automated.cs, src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/Nested_Sequence_Tests.cs
It was failing in CI many months ago. Let's see if something changed
=> chore: enable When_Reorder_To_Last_2 on WASM

src/Uno.Foundation/Uno.Core.Extensions/Uno.Core.Extensions.Compatibility/Collections/ImmutableList.cs
Benchmark:
```csharp
private static readonly object[] s_arr = new object[] { new(), new(), new(), new(), new(), new(), new() };
private static readonly object s_obj = new();
[Benchmark(Baseline = true)]
public void WithoutSpan()
{
var arr = new object[s_arr.Length + 1];
Array.Copy(s_arr, arr, s_arr.Length);
arr[s_arr.Length] = s_obj;
}
[Benchmark]
public void WithSpan()
{
var arr = new object[s_arr.Length + 1];
Span<object> arrSpan = MemoryMarshal.CreateSpan(ref MemoryMarshal.GetArrayDataReference(arr), arr.Length);
Span<object> span = MemoryMarshal.CreateSpan(ref MemoryMarshal.GetArrayDataReference(s_arr), s_arr.Length);
span.CopyTo(arrSpan);
arrSpan[s_arr.Length] = s_obj;
}
```
|      Method |     Mean |    Error |   StdDev |   Median | Ratio | RatioSD |  Gen 0 | Gen 1 | Gen 2 | …
=> perf: Faster ImmutableList.Add

src/Uno.UI/UI/Xaml/DependencyPropertyDetails.cs
Benchmark:
```csharp
private static object UnsetValue = new();
private static object[] _unsetStack = new object[10] { UnsetValue, UnsetValue, UnsetValue, UnsetValue, UnsetValue, UnsetValue, UnsetValue, UnsetValue, UnsetValue, UnsetValue };
[Benchmark(Baseline = true)]
public void ArrayCopy()
{
var arr = new object[10];
Array.Copy(_unsetStack, arr, 10);
}
[Benchmark]
public void SpanCopyToSpan()
{
var arr = new object[10];
MemoryMarshal.CreateSpan(ref MemoryMarshal.GetArrayDataReference(_unsetStack), 10).CopyTo(MemoryMarshal.CreateSpan(ref MemoryMarshal.GetArrayDataReference(arr), 10));
}
[Benchmark]
public void ArrayFill()
{
var arr = new object[10];
Array.Fill(arr, UnsetValue);
}
```
Outcome:
|         Method |     Mean |    Error |   StdDev | Ratio | RatioSD |  Gen 0 | Gen 1 | Gen 2 | …
=> perf: Use Span CopyTo instead of Array CopyTo for better performance

src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Media.Animation/RepositionThemeAnimation.cs, src/Uno.UI/UI/Xaml/Controls/ToggleSwitch/ToggleSwitch.cs, src/Uno.UI/UI/Xaml/Controls/ToggleSwitch/ToggleSwitch.mux.cs, src/Uno.UI/UI/Xaml/Media/Animation/RepositionThemeAnimation.cs
GitHub Issue (If applicable): closes #13303
=> fix: Fix animation setters not executed if a transition contains RepositionThemeAnimation

doc/import_external_docs.ps1
Update Uno.Themes and Uno.Toolkit docs to have the latest migration/breaking changes 4.10 related doc:
- Uno.Themes: https://github.com/unoplatform/Uno.Themes/tree/530204ba38264e66478eebdd2abc9ce05df3b0b9
- Uno.Toolkit: https://github.com/unoplatform/uno.toolkit.ui/tree/a0a15f56d1ba4f496a42a678ff981b41bde6396a
=> docs: Update Uno.Themes and Uno.Toolkit docs

build/ci/templates/dotnet-mobile-install-windows.yml, global-net8.json, src/Directory.Build.props, src/Uno.UI.RemoteControl.Host/Config/global-net8.0.json, src/Uno.UI.RemoteControl.Server.Processors/Uno.UI.RemoteControl.Server.Processors.csproj, src/Uno.UI/Controls/Window.iOS.cs, src/Uno.UWP/Storage/MimeTypeService.cs, src/Uno.UWP/Storage/Pickers/Internal/UTTypeMapper.iOSmacOS.cs
Update to 8.0.100 RTM, Roslyn 4.8.0-3.final.
Rolsyn update fixes error like this one: 
```
ERROR]System.TypeLoadException: Could not load type 'Enumerator' from assembly 'Microsoft.CodeAnalysis, Version=4.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
at Microsoft.CodeAnalysis.ExternalAccess.RazorCompiler.HostOutputNode`1.AppendOutputs(IncrementalExecutionContext context, CancellationToken cancellationToken)
at Microsoft.CodeAnalysis.GeneratorDriver.UpdateOutputs(ImmutableArray`1 outputNodes, IncrementalGeneratorOutputKind outputKind, Builder generatorRunStateBuilder, CancellationToken cancellationToken, Builder driverStateBuilder)
at Microsoft.CodeAnalysis.GeneratorDriver.RunGeneratorsCore(Compilation compilation, DiagnosticBag diagnosticsBag, CancellationToken …
```
=> chore: update to 8.0.100

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs, src/Uno.Foundation/Uno.Core.Extensions/Uno.Core.Extensions/StringExtensions.cs
closes #14527
Benchmark:
```csharp
[Params("Abc", "muxc:Abc", "(muxc:Abc)", "M(muxc:Abc.A, muxc:Abc.B)")]
public string xamlString { get; set; }
[Params("muxc")]
public string nsPrefix { get; set; }
[Params("using:Microsoft.UI.Xaml.Controls")]
public string nsNamespace { get; set; }
[Benchmark(Baseline = true)]
public string RegexBench()
=> Regex.Replace(xamlString, $@"(^|[^\w])({nsPrefix}:)", "$1global::" + nsNamespace.TrimStart("using:") + ".");
[Benchmark]
public string WithSpanSlicingAndCopying()
{
if (nsNamespace.StartsWith("using:", StringComparison.Ordinal))
{
while (xamlString.Length > nsPrefix.Length)
{
var index = xamlString.IndexOf($"{nsPrefix}:", StringComparison.Ordinal);
if (index == 0 || (index > 0 && !char.IsLetterOrDigit(xamlString[index - 1])))
{
var nsGlobalized = …
```
=> perf(xamlgen): Reduce allocations in RewriteNamespaces

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/CommandBarPages/CommandBarFirstPage.xaml, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/CommandBarPages/CommandBarFirstPage.xaml.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/CommandBarPages/CommandBarSecondPage.xaml, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/CommandBarPages/CommandBarSecondPage.xaml.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_CommandBar.cs, src/Uno.UI/Controls/CommandBar/CommandBarNavigationItemRenderer.iOS.cs, src/Uno.UI/Controls/CommandBar/CommandBarRenderer.iOS.cs, src/Uno.UI/Controls/CommandBar/NativeCommandBarPresenter.iOS.cs, src/Uno.UI/Controls/Renderer.cs
- Bugfix
Avoid a crash when navigating from and then back to a page with a native CommandBar on it
=> fix: avoid creating disconnected native commandbars on load

src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.cs, src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Controls/SampleChooserControl.xaml, src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Controls/SampleChooserControl.xaml.cs
GitHub Issue (If applicable): part of #13446, closes #14664
- Feature
Added support for quicky opening searched Sample in SamplesApp when there is only one found item.
=> feat: Add support for quicky opening searched Sample in SamplesApp

src/Uno.UI/Controls/CommandBar/CommandBarNavigationItemRenderer.iOS.cs
=> fix(commandbar): Avoid NSObject_Disposer:Drain with custom AppBar content (bp #14695)

src/Uno.UI/Controls/CommandBar/CommandBarNavigationItemRenderer.iOS.cs
- Bugfix
Fixes possible `NSObject_Disposer:Drain` crashes when UINavigationBar is natively collected. This ensures that any possible interaction with the `Superview` of `TitleView` will not corrupt memory when using a dangling pointer.
Related to https://github.com/xamarin/xamarin-macios/issues/19493#issuecomment-1820591127.
=> fix(commandbar): Avoid NSObject_Disposer:Drain with custom AppBar content

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_MediaPlayerElement.cs
GitHub Issue (If applicable): related to https://github.com/unoplatform/uno/issues/14735
Fixes unstable mediaplayer tests.
=> fix: Workaround MPE tests with MTC not enabled

src/Uno.UI/UI/Xaml/Media/Animation/EntranceThemeTransition.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/14422
- Bugfix
Sets the proper `DependencyProperty` default value type for `EntranceThemeTransition`.
=> fix: Adjust default values types for `EntranceThemeTransition` DPs

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ContentControl.cs, src/Uno.UI.Tests/App/App.xaml, src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/XBind_ResourceDictionary.xaml, src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/XBind_ResourceDictionary.xaml.cs, src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/XBind_ResourceDictionary_Control.cs, src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Given_xBind_Binding.cs, src/Uno.UI/UI/Xaml/IFrameworkElement.cs
GitHub Issue (If applicable): closes #13550, closes #14286
- Bugfix
=> x:Bind to event in `ResourceDictionary`

doc/articles/create-an-app-vscode.md
https://github.com/unoplatform/uno/issues/12506#issuecomment-1852886135
The debug instructions for Wasm and Skia/Gtk refers to code that is not part of the latest templates.
The last 2 steps for Wasm and Skia/Gtk were removed. This match the mobile (iOS, Android, Catalyst) documentation for VS Code.
This also match the documents for VS 2022 and Rider.
=> docs: sync vscode debug with new templates

doc/articles/features/windows-networking.md
GitHub Issue (If applicable): closes https://github.com/unoplatform/Uno.Gallery/issues/33
Improved the `NetworkInformation` docs page with more details and samples for implementation.
=> docs: Improve `NetworkInformation` page

src/Uno.UI.RemoteControl/buildTransitive/Uno.UI.DevServer.targets
- Feature
Add net7 backward compatibility for msbuild CLI `--getProperty` for vscode.
=> feat: Add net7 backward compatibility for msbuild getProperty

doc/articles/uno-development/uno-internals-hotreload.md, src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.MetadataUpdate.cs, src/Uno.UI.RemoteControl/HotReload/MetadataUpdater/ElementUpdaterAgent.cs, src/Uno.UI.RuntimeTests/Tests/HotReload/Frame/HRApp/Tests/Given_Frame.cs, src/Uno.UI.RuntimeTests/Tests/HotReload/Frame/HRApp/Tests/TestingUpdateHandler.cs, src/Uno.UI.RuntimeTests/Tests/HotReload/Frame/HRApp/Uno.UI.RuntimeTests.HRApp.Skia.Gtk.csproj
- Feature
Currently there's no callback that's called every time the UI update method is attempted (in other words every time UpdateApplication is invoked by HotReload). This makes it difficult to await a hot reload pass in the scenario that ui updates have been paused
A new ReloadCompleted callback has been added which can be awaited in order to confirm that a hot reload pass (ie a call to UpdateApplication) has been invoked. In addition to providing the array of modified types, there is a second bool parameter on this callback that reflects whether the UI has been updated or not (this would be false in the scenario where ui updates have been paused)
=> feat: Adding reloadcompleted callback

src/SourceGenerators/SourceGeneratorHelpers/Helpers/SymbolExtensions.cs, src/SourceGenerators/Uno.UI.SourceGenerators/RoslynMetadataHelper.cs, src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlConstants.cs, src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.Reflection.cs, src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs, src/SourceGenerators/XamlGenerationTests/MarkupExtension_ParserContext.xaml, src/Uno.UI.Tests/Windows_UI_Xaml_Markup/MarkupExtensionTests/Controls/Attachable.cs, src/Uno.UI.Tests/Windows_UI_Xaml_Markup/MarkupExtensionTests/Controls/DebugMarkupExtension.cs, src/Uno.UI.Tests/Windows_UI_Xaml_Markup/MarkupExtensionTests/Controls/When_AttachedDP_Markup_Setup.xaml, src/Uno.UI.Tests/Windows_UI_Xaml_Markup/MarkupExtensionTests/Controls/When_AttachedDP_Markup_Setup.xaml.cs, src/Uno.UI.Tests/Windows_UI_Xaml_Markup/MarkupExtensionTests/Controls/When_DP_Markup_Setup.xaml, src/Uno.UI.Tests/Windows_UI_Xaml_Markup/MarkupExtensionTests/Controls/When_DP_Markup_Setup.xaml.cs, src/Uno.UI.Tests/Windows_UI_Xaml_Markup/MarkupExtensionTests/Given_MarkupExtension.cs
GitHub Issue (If applicable): closes #14719, closes #14749
- Bugfix
- custom `MarkupExtension` are now supported on attached properties
- fixed `ProvideValueTargetProperty` not providing the correct property info:
- `.Type` were always of type `object`
- `.DeclaringType` were the type of where the dp was assigned on, instead of the class that declared the dp
^ `Button.Content={...}` previously returned `Button` instead of `ContentControl`
=> fix(xamlgen): MarkupExtensions parser context

doc/articles/features/windows-storage-pickers.md, src/Uno.UWP/Storage/Pickers/FileOpenPicker.Android.cs
GitHub Issue (If applicable): closes #14658
- Bugfix
On android, FileOpenPicker.SuggestedStartLocation has no effect.
On android, setting FileOpenPicker.SuggestedStartLocation to PicturesLibrary or VideosLibrary now adds the relevant filter for the picker.
=> fix(droid): FileOpenPicker ignoring suggested PicturesLibrary

doc/import_external_docs.ps1
Update the Workshops documentation to fix the SimpleCalc modules links
(Related changes: https://github.com/unoplatform/workshops/pull/152)
=> docs: Update the Workshops documentation to fix the SimpleCalc modules links

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBlock.cs, src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/TextBlock.cs, src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.Android.cs, src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.cs, src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.iOS.cs, src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.skia.cs, src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.wasm.cs, src/Uno.UI/UI/Xaml/WindowManagerInterop.wasm.cs, src/Uno.UI/ts/WindowManager.ts
GitHub Issue (If applicable): closes #14266
- Feature
implemented TextBlock.IsTextTrimmed & .IsTextTrimmedChanged for skia,ios,droid,wasm
=> feat(textblock): IsTextTrimmed & IsTextTrimmedChanged

src/Uno.UI.RuntimeTests/Tests/Microsoft_UI_Xaml_Controls/Given_TabView.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/TabView/TabView.cs
GitHub Issue (If applicable): closes #4925
=> chore: uncomment a Uno-specific commented line in TabView

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- Bugfix
For a code like this:
https://github.com/unoplatform/uno/blob/93823c188af968aa6ed25ac7a7f2032f060b9c94/src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/ProgressBar/WinUIProgressBarPage.xaml#L113
We get:
>       The name [UpdatePaddingButton] already exists in the current XAML scope
No longer produces that warning.
=> fix: Call `NameScope.RegisterName` only for `x:Name`

src/Uno.UI.RuntimeTests/Tests/Microsoft_UI_Xaml_Controls/Given_RatingControl.cs, src/Uno.UI/Generated/3.0.0.0/Microsoft.UI.Xaml.Automation.Peers/AutomationPeer.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/RatingControl/RatingControl.cs, src/Uno.UI/UI/Xaml/Automation/Peers/AutomationPeer.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno.extensions/issues/2113
- Bugfix
`RatingControl` detaches events on unload, but they are not re-attached afterwards.
Events are re-attached.
=> fix: RatingControl events re-attachment

src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewMode.Commands.cs, src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewMode.Properties.cs, src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.cs, src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Controls/SampleChooserContent.cs, src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Controls/SampleChooserControl.xaml, src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Controls/SampleInfoControl.xaml, src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Controls/SampleInfoControl.xaml.cs, src/SamplesApp/SamplesApp.UnitTests.Shared/SamplesApp.UnitTests.Shared.projitems
- Feature
Previously the dialog was a non-interactive `MessageDialog`
- Flyout
- Interactive copy buttons for type name and query string
=> Improve samples app info dialog

src/Uno.UI/UI/Xaml/Controls/ListViewBase/Deque.cs, src/Uno.UI/UI/Xaml/SpecializedResourceDictionary.cs, src/Uno.UWP/Buffers/DefaultArrayPool.cs
GitHub Issue (If applicable): closes #13136
=> perf: Use Array.Clear(arr) instead of Array.Clear(arr, 0, arr.Length)

src/SamplesApp/UITests.Shared/Windows_Devices/GeolocatorTests.xaml.cs, src/Uno.UWP/Devices/Geolocation/Geolocator.Android.cs
GitHub Issue (If applicable): closes #14725 
- Bugfix
Geolocator throws when subscribing to `PostitionChanged` events and GPS is not available.
- Geolocator does NOT crash when subscribing to `PostitionChanged` event and GPS/Location is not enabled.
- `RequestAccessCore()` method returns `Denied` when no GPS/Location provider is available regardless of the permission. Mathing WinUI specs.
=> fix(droid): Geolocator listener crash

src/Uno.UI.Runtime.Skia.Gtk/Input/GtkCorePointerInputSource.cs
Seems like #14404 only works on Windows. Gtk returns very different numbers on Linux. `GetOrigin` should hopefully behave well everywhere.
=> chore: fix GetWindowCoordinates on Linux

src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/FlipView/FlipView_Images.xaml.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_FlipView.cs, src/Uno.UI/UI/Xaml/Controls/FlipView/FlipView.Android.cs, src/Uno.UI/UI/Xaml/UIElement.Android.cs
GitHub Issue (If applicable): closes #14551 
- Bugfix
FlipVIew NativeView is not clipping correctly to its parent, causing more than one FlipViewItem to be displayed simultaneously.
=> fix(droid): Flipview Native View clipping

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs, src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.cs, src/Uno.UI/UI/Xaml/Controls/Primitives/Selector.cs, src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.cs, src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.wasm.cs, src/Uno.UI/UI/Xaml/Input/FocusManager.wasm.cs
GitHub Issue (If applicable): closes #14832, closes #14965
Fixes multiple problems:
1. ScrollBar not moving as the ScrollViewer gets scrolled with keyboard on WASM (#14832)
2. ListView scrolling instead of changing selection when arrow keys are pressed (regression from #13850).
3. Keyboard scrolling on WASM scrolling incorrectly when arrow keys are held longer than needed due to discrepancy between the native ScrollContentPresenter scrolling and the managed keyboard scrolling. I've decided to turn managed keyboard scrolling off for WASM as matching the numbers precisely isn't worth the hassle.
4. On WASM, the scrollbars would freeze in place if a long scroll occurs (either violent pointer wheel scrolling or arrow key held) until the end of the scrolling duration. This is due to event …
=> Miscellaneous scrolling fixes

src/Uno.UWP/Generated/3.0.0.0/Windows.Networking.Connectivity/NetworkInformation.cs, src/Uno.UWP/Networking/Connectivity/NetworkInformation.cs
GitHub Issue (If applicable): closes 
- Feature
Adds support for GetConnectionProfiles in NetworkInformation class.
Internal Teams discussion with @MartinZikmund
=> feat: Implement `GetConnectionProfiles`

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Repeater/Given_ItemsRepeater.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/ItemsRepeater.cs
closes https://github.com/unoplatform/uno.extensions/issues/2123
Fix `ItemsRepeater` might not listening on collection changed when re-loaded
We re-subscribe only of the `ItemsSource` is a `ItemsSourceView`.
We use the private cached field of the collection wrapper (which is the expected implementation of the `ItemsSourceView`)
=> fix: Fix ItemsRepeater might not listening on collection changed when re-loaded

src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.cs
- Bugfix
When the FilteredSamples is null on enter when searching for a sample, the app throws an error. 
=> fix: SamplesApp error when FilteredSamples null

src/Uno.UI/Generated/3.0.0.0/Microsoft.UI.Xaml.Automation.Peers/AutoSuggestBoxAutomationPeer.cs, src/Uno.UI/UI/Xaml/Controls/AutoSuggestBox/AutoSuggestBox.cs, src/Uno.UI/UI/Xaml/Controls/AutoSuggestBox/AutoSuggestBoxAutomationPeer.cs
GitHub Issue (If applicable): part of #14344
- Feature
The `AutoSuggestBoxAutomationPeer` is implemented
=> chore: Implement `AutoSuggestBoxAutomationPeer`

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_MenuFlyout.cs, src/Uno.UI/UI/Xaml/Controls/MenuFlyout/ToggleMenuFlyoutItem.cs
GitHub Issue (If applicable): closes #15080
- Bugfix
Currently `ToggleMenuFlyoutItem` does not report as `HasToggle`
Fixed!
=> fix: Ensure `ToggleMenuFlyoutItem` is reported as toggle

src/Uno.Analyzers.Tests/UnoNotImplementedTests.cs, src/Uno.Analyzers/UnoNotImplementedAnalyzer.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/14702
Not implemented events are now flagged properly.
=> fix: ensure that not implemented events raise Uno0001

src/Uno.UI/UI/Xaml/UIElement.wasm.cs
GitHub Issue (If applicable): https://github.com/unoplatform/kahua-private/issues/93
- Bugfix
Ensures that uninitialized GC handle don't raise exceptions and are handled gracefully. This change also removes an unused version of `GetElementFromHandle` which was needed before `int`->`nint` was implicitly allowed.
=> fix: [wasm] Don't fail on uninitialized GC handle

global-net8.json, global.json, src/Uno.Sdk/Sdk/Sdk.props, src/Uno.Sdk/Sdk/Sdk.targets, src/Uno.Sdk/Uno.Sdk.csproj, src/Uno.Sdk/targets/winappsdk-workaround.targets
n/a
- Feature
Projects using Uno.Sdk do not apply the winappsdk workarounds and may have issues with the PRI resources
We now include the winappsdk workarounds when SingleProject is not true, and the target framework is windows10
=> Include winappsdk-workaround for non-Single Project

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Repeater/Given_ItemsRepeater.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/ItemsRepeater.cs
closes https://github.com/unoplatform/uno.extensions/issues/2123
Fix IR not reflecting CollectionChanged.Update raised while being unloaded
Add and Remove changes raised while being unloaded are detected, but not update.
We mark all containers as recyclable on unload, driving the IR to assign all containers on reload.
=> fix: Fix IR not reflecting CollectionChanged.Update raised while being unloaded

src/Uno.Sdk/Sdk/Sdk.props, src/Uno.Sdk/Sdk/Sdk.targets, src/Uno.Sdk/targets/Uno.CrossTargetting.targets, src/Uno.Sdk/targets/Uno.SingleProject.Skia.targets, src/Uno.Sdk/targets/Uno.SingleProject.Wasm.targets, src/Uno.Sdk/targets/Uno.SingleProject.WinAppSdk.targets
- n/a
- Feature
Project must provide includes for Pages, file nesting for XAML files 
The Sdk now automatically provides correct default includes matching what WinUI does. Also adds the Cross Targeting includes.
n/a
n/a
=> Adding Cross Targeting and default Includes

src/Uno.Sdk/Sdk/Sdk.props, src/Uno.Sdk/Sdk/Sdk.targets, src/Uno.Sdk/Uno.Sdk.csproj
- n/a
- Bugfix
Targets are imported from within a Choose block
The Choose block has been removed and the targets are now imported based on the Platform variable set in the props
=> Fixes Targets Imports

src/Uno.Sdk/Sdk/Sdk.targets
- n/a
- Feature
A number of properties for the Manifest and setting the default platforms, etc all exist within the project head.
We now provide default values for this in the SDK
=> Adding Manifest defaults for WinUI

src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.PartialReload.cs, src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.Xaml.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/discussions/15044
- Bugfix
Restores support for C# HotReload for builds after 8.0.101
=> feat: Restore support for C# Hot Reload for XAML for mobile targets

build/nuget/Uno.WinUI.Lottie.nuspec
Related https://github.com/unoplatform/uno.templates/pull/510
- Bugfix
Including the uno lottie package in windows and uap heads win't fail with invalid uno references.
=> fix: Don't include uno binaries in netx.y-windows and uap builds

src/Uno.Sdk/Sdk/Sdk.props, src/Uno.Sdk/Sdk/Sdk.targets, src/Uno.Sdk/Uno.Sdk.csproj, src/Uno.Sdk/targets/Uno.Build.targets, src/Uno.Sdk/targets/Uno.Common.Android.targets, src/Uno.Sdk/targets/Uno.Common.MacCatalyst.targets, src/Uno.Sdk/targets/Uno.Common.MacOS.targets, src/Uno.Sdk/targets/Uno.Common.Skia.targets, src/Uno.Sdk/targets/Uno.Common.Wasm.targets, src/Uno.Sdk/targets/Uno.Common.WinAppSdk.targets, src/Uno.Sdk/targets/Uno.Common.iOS.targets, src/Uno.Sdk/targets/Uno.Common.targets, src/Uno.Sdk/targets/Uno.CrossTargeting.targets, src/Uno.Sdk/targets/Uno.DefaultItems.targets, src/Uno.Sdk/targets/Uno.Import.SolutionConfig.props, src/Uno.Sdk/targets/Uno.IsPlatform.props, src/Uno.Sdk/targets/Uno.ProjectCapabilities.WinAppSdk.targets, src/Uno.Sdk/targets/Uno.ProjectCapabilities.targets, src/Uno.Sdk/targets/Uno.Sdk.After.targets
- n/a
- Refactoring
Uno.Sdk matches the Microsoft.NET.Sdk behavior in 8.0.10x by loading the Directory.Build.props
We now match the behavior of the 8.0.200 preview
=> Refactor for 8.0.200

build/nuget/uno.winui.single-project.targets, src/Uno.Sdk/Sdk/Sdk.props, src/Uno.Sdk/targets/Uno.ProjectCapabilities.targets
- n/a
- Bugfix
Project capabilities are defined by both Uno.WinUI and the Uno.Sdk
Uno.WinUI targets will not add additional capabilities when using the Uno.Sdk. Capabilities are aligned with each other.
=> Align Project Capabilities

src/Uno.UI.RuntimeTests/Helpers/FeatureConfigurationHelper.cs, src/Uno.UI.Tests/Windows_UI_XAML_Controls/ItemsControlTests/Given_ItemsControl.cs, src/Uno.UI.Tests/Windows_UI_XAML_Controls/ListViewBaseTests/Given_ListViewBase.cs, src/Uno.UI.Tests/Windows_UI_XAML_Controls/ListViewBaseTests/Given_ListViewBase_CustomContainer.cs, src/Uno.UI.Tests/Windows_UI_Xaml/Given_FrameworkTemplate.cs, src/Uno.UI/UI/Xaml/FrameworkTemplatePool.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/13969
- Bugfix
Force disable `FrameworkTemplatePool` to avoid race condition effects introduced recently.
=> fix: Force disable template pooling for all platforms

doc/articles/features/working-with-xaml-hot-reload.md, src/Uno.UI.RemoteControl.VS/EntryPoint.cs, src/Uno.UI.RemoteControl.VS/Helpers/DTEHelper.cs, src/Uno.UI.RemoteControl.VS/IDEChannel/IDEChannelClient.cs, src/Uno.UI.RemoteControl.VS/Uno.UI.RemoteControl.VS.csproj
- Bugfix
Reduce devserver logging verbosity, make it configurable.
=> fix: Configure devserver log level, reduce verbosity

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_DatePicker.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TimePicker.cs, src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePicker.Flyout.cs, src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePicker.cs, src/Uno.UI/UI/Xaml/Controls/DatePicker/NativeDatePickerFlyout.Android.cs, src/Uno.UI/UI/Xaml/Controls/DatePicker/NativeDatePickerFlyout.iOS.cs, src/Uno.UI/UI/Xaml/Controls/Flyout/FlyoutBase.cs, src/Uno.UI/UI/Xaml/Controls/TimePicker/NativeTimePickerFlyout.Android.cs, src/Uno.UI/UI/Xaml/Controls/TimePicker/NativeTimePickerFlyout.iOS.cs, src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePicker.partial.mux.cs, src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerSelector.iOS.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/15256, fixes https://github.com/unoplatform/uno/issues/15267
- Bugfix
- App crashes when the `DatePicker` is unloaded
- Behavior of `TimePicker` and `DatePicker` native flyouts is more aligned with managed flyouts
- Pickers do not throw when the control has open flyout and is unloaded
- Unloading controls automatically closes associated flyouts
=> fix: `TimePicker` and `DatePicker` native flyouts closing and unload

build/PackageDiffIgnore.xml, src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePicker.partial.mux.cs
Restores the original value for TIMEPICKER_MINUTEINCREMENT_MAX from WinUI's sources
=> fix: Invalid TIMEPICKER_MINUTEINCREMENT_MAX

src/Uno.UI/UI/Xaml/Media/Imaging/RenderTargetBitmap.cs, src/Uno.UI/UI/Xaml/Media/Imaging/RenderTargetBitmap.iOS.cs, src/Uno.UI/UI/Xaml/Media/Imaging/RenderTargetBitmap.macOS.cs, src/Uno.UI/UI/Xaml/Media/Imaging/RenderTargetBitmap.skia.cs
GitHub Issue (If applicable): closes #14955
=> perf: Avoid LOH allocations in RenderTargetBitmap

src/AddIns/Uno.UI.Lottie/LottieVisualSource.Skottie.cs, src/SamplesApp/SamplesApp.netcoremobile/SamplesApp.netcoremobile.csproj
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/15247
- Bugfix
Ensures the LottieVisualPlayer on Catalyst has a transparent background.
=> fix: [Catalyst] Ensure LottieVisualSource is transparent

src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/NativeScrollContentPresenter.iOS.cs, src/Uno.UI/UI/Xaml/UIElement.cs
GitHub Issue (If applicable): Related to https://github.com/unoplatform/uno/issues/15254
- Bugfix
Avoids a crash when the `ScrollContentPresenter` content returns a negative size
=> fix: [iOS] Avoid crash when content size is negative

doc/articles/features/PasswordVault.md
loginCredential variable used while vault.Retrieve() is set in the variable credential
Updated loginCredential to credential
=> docs: Adujust PasswordVault

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ThumbTests/Tumb_CapturePreventScroll_Tests.cs, src/SamplesApp/UITests.Shared/UITests.Shared.projitems, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ThumbTests/Thumb_CapturePreventScroll.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ThumbTests/Thumb_CapturePreventScroll.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ThumbTests/Thumb_DragEvents.xaml.cs, src/Uno.UI/UI/Xaml/Controls/Primitives/Thumb.mux.cs, src/Uno.UI/UI/Xaml/Internal/InputManager.Pointers.Managed.cs, src/Uno.UI/UI/Xaml/Internal/PointerCapture.Android.cs, src/Uno.UI/UI/Xaml/Internal/PointerCapture.cs, src/Uno.UI/UI/Xaml/Internal/PointerCapture.iOS.cs, src/Uno.UI/UI/Xaml/Internal/PointerCaptureOptions.cs, src/Uno.UI/UI/Xaml/UIElement.Pointers.cs
closes https://github.com/unoplatform/kahua-private/issues/106
Thumb does not prevent scroll
`Thumb` on windows captures the pointer, but this does not prevent the OS to "stole" the pointer (usually when it detects a scroll gesture)
When capturing pointer, uno controls are able to also request to prevent the OS to "stole" the pointer.
=> fix: Thumb does not prevent scroll

src/Uno.Sdk/targets/Uno.Common.WinAppSdk.targets, src/Uno.Sdk/targets/winappsdk-workaround.targets
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno.templates/issues/547
- Bugfix
Disable WinAppSDK Workaround for wasdk project heads.
Also, only set EnableMsixTooling to true on wasdk project heads
=> fix: Don't run PRI workaround for WinUI on the head project

src/Uno.UI/BaseActivity.Android.cs, src/Uno.UWP/Microsoft/UI/Windowing/AppWindow.cs, src/Uno.UWP/UI/ViewManagement/ApplicationView.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/15289
- Bugfix
- `ApplicationView` cannot be retrieved until window is activated
- Error is not descriptive
- Both adjusted
=> fix: Make it possible to retrieve instance of `ApplicationView` earlier

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_DatePicker.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TimePicker.cs, src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePickerFlyout_Partial.cs, src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerFlyout.partial.mux.cs
GitHub Issue (If applicable): closes #15409 
- Bugfix
=> fix: `TimePickerFlyout` is not visible if not opened from `TimePicker`

src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.Android.cs, src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.Managed.cs, src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.cs, src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.iOS.cs, src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.reference.cs, src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.unittests.cs, src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.wasm.cs
Reduces allocations for ScrollViewer constructor:
=> perf: Move Loaded/Unloaded to use OnLoaded/OnUnloaded to avoid delegate combine

src/Uno.UI/UI/Xaml/DependencyObjectStore.Binder.cs
- Performance
- Some insertions happen that have no effect because we end up skipping them in `ApplyChildrenBindable`
- Hashtable and List are created for each DependencyObject.
- Only insert things that we will use in `ApplyChildrenBindable`.
- With the limited insertions, it's now common to end up with `DependencyObjectStore`s with empty hash tables and lists. So, it now makes sense to make these lazy. This not only reduces allocation, but reduces pressure on the ArrayPool used by HashtableEx.
=> perf: Make `_childrenBinable` lazy and avoid unnecessary insertions

doc/articles/features/windows-storage-pickers.md, src/Uno.UWP/Storage/Pickers/FileOpenPicker.Android.cs
GitHub Issue (If applicable): closes #14658
- Bugfix
When selecting a Video or Image on Android the Picker selector will also include related application to these type of content.
=> fix(droid):  FileOpenPicker to display related applications

src/SamplesApp/SamplesApp.Shared/App.xaml.cs, src/Uno.UI.RuntimeTests/Tests/Microsoft_UI_Xaml_Controls/Given_WebView2.cs, src/Uno.UI/UI/Xaml/Controls/WebView/Native/Android/InternalWebClient.Android.cs, src/Uno.UI/UI/Xaml/Controls/WebView/Native/Android/NativeWebViewWrapper.Android.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/nventive-private/issues/508
- Bugfix
=> fix: Make Android `WebView2.NavigationStarting` more reliable

src/Uno.Sdk/targets/Uno.Common.WinAppSdk.targets
- fixes #15492
- Bugfix
We will always default setting EnableCoreMrtTooling to false when we set it
We now set EnableCoreMrtTooling to true when building for a library
=> Fix issue with libraries not getting correct resource path

src/Uno.UI.RuntimeTests/Tests/Uno_UI_Xaml_Input/Given_UnoFocusInputHandler.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Input/Given_FocusManager.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs, src/Uno.UI/UI/Xaml/Input/Internal/UnoFocusInputHandler.cs, src/Uno.UI/UI/Xaml/Internal/InputManager.cs, src/Uno.UI/ts/WindowManager.ts
GitHub Issue (If applicable): https://github.com/unoplatform/uno.chefs/issues/998
=> Fix WASM changing scroll position on focus changing + fix keyboard focus not bringing the new focus target into view

src/Uno.UWP/Storage/Pickers/FileOpenPicker.iOS.cs, src/Uno.UWP/Storage/Pickers/FolderPicker.iOS.cs
GitHub Issue (If applicable): closes #15504 
- Bugfix
Getting: **UIKit Consistency error: you are calling a UIKit method that can only be invoked from the UI thread** when using FolderPicker and FileOpenPicker.
=> fix(Catalyst): File and folder Picker UIThread issue

doc/articles/features/windows-storage-pickers.md, src/SamplesApp/UITests.Shared/Windows_Storage/Pickers/FileOpenPickerTests.xaml.cs, src/Uno.UWP/Storage/Pickers/FileOpenPicker.iOS.cs
- Bugfix
- When picking multiple images is requested, it is not possible on iOS
Possible on iOS
=> fix: Use `UIDocumentPickerViewController` if multiple files are picked

build/nuget/uno.winui.single-project.targets, src/Uno.CrossTargetting.targets, src/Uno.Sdk/targets/Uno.ProjectCapabilities.targets
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/15517
- Bugfix
Hints VS at the fact that an Uno project uses WinUI XAML to get intellisense working even if there's no WinUI project available.
=> fix: Ensures that Uno projects enable intellisense even if no wasdk project is present

src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.Xaml.cs
- Bugfix
Adjust iOS/Catalyst hot reload using C# hotreload based on 8.0.200 workload version.
=> fix: Adjust iOS min version for using hot reload

src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Controls/SampleChooserControl.xaml, src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Styles/SampleControl.xaml
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/14586
The sample control contains the description, but when the sample is wrapped in a `Frame` this is not visible.
The description is always visible.
=> refactor: Make description part of `SampleChooserControl`

src/SamplesApp/SamplesApp.Shared/App.Assertions.cs, src/SamplesApp/SamplesApp.Shared/App.xaml.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_ViewManagement_ApplicationView/Given_Control.cs, src/Uno.UI/UI/Xaml/Window/Implementations/BaseWindowImplementation.cs, src/Uno.UI/UI/Xaml/Window/Native/NativeWindowWrapper.Android.cs
closes #15521 
closes #15520
`ViewCompat.GetRootWindowInsets` returns `null` if the view is not yet attached to the Android `Window`.
If you try and access the `ApplicationView.GetForCurrentView().VisibleBounds` early on in the app startup it can result in the window insets not being properly calculated.
The only other way to grab the `WindowInsets` is to use the `WindowMetrics` from the `Activity.WindowManager`, so we do that if the current root view is not attached to the `Window`
=> fix: initialize visiblebounds earlier on android

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_DatePicker.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TimePicker.cs, src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePickerSelector.iOS.cs, src/Uno.UI/UI/Xaml/Controls/DatePicker/NativeDatePickerFlyout.iOS.cs, src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerSelector.iOS.cs
GitHub Issue (If applicable): closes #15263 
- Bugfix
- `TimePicker`	 and `DatePicker` always use system theme
- `TimePicker` and `DatePicker` switch theme along with application
=> [iOS] fix: `TimePicker` and `DatePicker` should follow application theme

.github/workflows/uwp-autoconvert.yml, .vsts-ci.yml, build/ci/.azure-devops-android-tests.yml, build/ci/.azure-devops-ios-tests-run.yml, build/ci/.azure-devops-ios-tests.yml, build/ci/templates/dotnet7-mobile-install-mac.yml, build/nuget/Uno.WinUI.Lottie.nuspec, build/nuget/Uno.WinUI.Svg.nuspec, build/test-scripts/ios-uitest-run.sh, doc/articles/features/Lottie.md, doc/articles/features/using-skia-gtk.md, doc/articles/features/using-skia-wpf.md, global.json, src/AddIns/Uno.UI.Lottie/buildTransitive/Uno.UI.Lottie.targets, src/AddIns/Uno.UI.Svg/buildTransitive/Uno.UI.Svg.targets, src/Directory.Build.targets, src/SamplesApp/SamplesApp.Shared/App.xaml.cs, src/SamplesApp/SamplesApp.UITests/SampleControlUITestBase.cs, src/SamplesApp/SamplesApp.UITests/SamplesApp.UITests.csproj, src/SamplesApp/UnoIslandsSamplesApp.Skia.Wpf/UnoIslandsSamplesApp.Skia.Wpf.csproj, src/SolutionTemplate/UnoAppWinUI/UnoAppWinUI.Skia.Gtk/UnoAppWinUI.Skia.Gtk.csproj, src/SolutionTemplate/UnoAppWinUI/UnoAppWinUI.Skia.Linux.FrameBuffer/UnoAppWinUI.Skia.Linux.FrameBuffer.csproj, src/SolutionTemplate/UnoAppWinUI/UnoAppWinUI.Skia.WPF/UnoAppWinUI.Skia.WPF.csproj, src/SolutionTemplate/UnoAppWinUILinuxValidation/UnoAppWinUILinuxValidation.Skia.Gtk/UnoAppWinUILinuxValidation.Skia.Gtk.csproj, src/SolutionTemplate/UnoAppWinUILinuxValidation/UnoAppWinUILinuxValidation.Skia.Linux.FrameBuffer/UnoAppWinUILinuxValidation.Skia.Linux.FrameBuffer.csproj, src/Uno.UI.RuntimeTests/Tests/HotReload/Frame/HRApp/Uno.UI.RuntimeTests.HRApp.Skia.Gtk.csproj
The SkiaSharp update is possible since 5.1, as Uno for net7-ios is depending on Microsoft 16.4 after a forced workloads update, and SkiaSharp for net7-ios is depending on Microsoft 16.2.
We're still dependent on https://github.com/dotnet/sdk/issues/30103 for future updates, if the workloads end up changing on SkiaSharp's end.
=> chore: Bump SkiaSharp to 2.88.7

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Grid.cs, src/Uno.UI/UI/Xaml/Controls/Grid/Grid.Properties.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/15753
- Bugfix
The original assumption was that `Column`, `Row`, `ColumnSpan` and `RowSpan` only affect arrange of the `Grid`
They can and should also affect measure of the `Grid`
=> fix: `Grid` `Column`, `Row`, `ColumnSpan` and `RowSpan` can affect measure

src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media_Imaging/PickImageFromFile.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media_Imaging/PickImageFromFile.xaml.cs
GitHub Issue (If applicable): closes #15737 , part of #15664
- Bugfix
Fixes crashing of the `PickImageFromFile` sample and adds a proper description
=> fix: NRE on `PickImageFromFile `cancellation in SamplesApp

src/Uno.UI.Runtime.Skia.MacOS/MacOSWindowHost.cs
- Bugfix
On macOS non-handled key down events will make the Mac beep. 
However for WinUI compatibility the `Handled` property cannot be used to signal the actual key being handled (or not).
This replace PR https://github.com/unoplatform/uno/pull/15780
We always tell macOS that the key down event was handled.
=> fix: tell macOS we handled all keydown events

src/Uno.UI.Runtime.Skia.MacOS/UnoNativeMac/UnoNativeMac/UNOCursor.m
- Feature
Many `CoreCursorType` are not mapped to macOS cursors, most of them exists but are not available with AppKit NSCursor API.
Directly use macOS cursor files for `CoreCursorType.Help`, `.SizeAll`, `.SizeNortheastSouthwest`, `.SizeNorthwestSoutheast` and `.Wait`.
=> feat: handle more macOS cursors

build/test-scripts/ios-uitest-run.sh
Not very sure but looks like there is a race condition. Sometimes, test runs fail with logs like:
```
Starting tests in mode RuntimeTests
uno.platform.samplesdev: 5456
App PID: 5456
Waiting for /tmp/TestResult-20240311063700.xml to be available...
The app is not running anymore
The file /tmp/TestResult-20240311063700.xml is not available, the test run has timed out.
cp: /Users/runner/work/1/s/build/TestResult-original.xml: No such file or directory
```
Looking at Device Logs, the tests actually executed to completion successfully, then the app exited:
```
2024-03-11 06:44:04.134189+0000  localhost SamplesApp[6112]: (libSystem.Native.dylib) \^[[40m\^[[32minfo\^[[39m\^[[22m\^[[49m: …
```
=> ci: iOS Wait 2 seconds if test results file isn't found

src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.Xaml.cs
GitHub Issue (If applicable): closes 
- Bugfix
For mobile platforms only Android works with C# hot-reload.
iOS and Catalyst should work too for C# hot-reload.
Versions were inverted inside https://github.com/unoplatform/uno/pull/15582/files
https://github.com/unoplatform/uno.vscode/issues/638
=> fix(hotreload): inverse Android and iOS/Catalyst versions

src/Uno.UI.Runtime.Skia.MacOS/MacOSWindowHost.cs, src/Uno.UI.Runtime.Skia.MacOS/NativeUno.cs, src/Uno.UI.Runtime.Skia.MacOS/UnoNativeMac/UnoNativeMac/UNOWindow.h, src/Uno.UI.Runtime.Skia.MacOS/UnoNativeMac/UnoNativeMac/UNOWindow.m
- Bugfix
Some keys (e.g. `.`) were not processed correctly since there was no unicode mapping for the scan code.
A unicode value is always provided for key events.
=> fix: set unicode value on KeyEventArgs for macOS/skia

src/Uno.UI/Extensions/UIElementExtensions.Debug.cs, src/Uno.UI/UI/Xaml/Internal/UnoRootElementLogic.cs, src/Uno.UI/UI/Xaml/UIElement.Pointers.cs, src/Uno.UI/UI/Xaml/UIElement.RoutedEvents.cs
closes https://github.com/unoplatform/uno/issues/15384
Ensure to raise up/exit/capture-lost events in the right order
* On iOS, _CaptureLost_ event is raised before the pointer _Up_ reached the top of the visual tree.
* On iOS and Android, if _Up_ is not handled, but _CaptureLost_ is, the _Exit_  is raised twice.
Those drive the `RatingControl` to clear it's internal pointer state in wrong order so it skips UI refresh after value update.
🙃
=> fix(pointers): [iOS] Ensure to raise up/exit/capture-lost events in the right order

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media/Given_Geometry.cs, src/Uno.UI/Media/StreamGeometry.cs
This PR fixes the issue of ineffective FillRule setting for StreamGeometry on the Skia platform. The root cause is that the FillRule of StreamGeometry was not assigned to SKPath on the Skia platform, which resulted in SKPath always maintaining the default value. This would cause the Path's Data corresponding to the XAML code like `<Path Data="xxxxx"/>` used on the Skia platform to use the Nonzero FillRule method, instead of maintaining the default EvenOdd FillRule method consistent with WinUI.
GitHub Issue (If applicable): closes #15889, closes #15539
- Bugfix
The Path's Data corresponding to the XAML code like `<Path Data="xxxxx"/>` used on the Skia platform to use the Nonzero FillRule method, instead of maintaining the default EvenOdd FillRule …
=> fix(Skia): Fix ineffective FillRule setting for StreamGeometry

doc/articles/features/svg.md
Added missing details about the Svg.Skia package needed for the Skia Head
GitHub Issue (If applicable): closes #15864
https://github.com/unoplatform/uno/issues/15864
There is no information about the required package and you get an error when compiling.
There is no error when compiling.
- [ x] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
=> docs: Added missing details about the Svg.Skia package needed for the Skia Head

README.md
By default contrib.rocks has a max of 100. I have augmented the number in order to display all the contributors list.
=> chore: Update README.md to include the entire list of Uno Platform Contributors

src/Uno.Sdk/ImplicitPackagesResolver.cs, src/Uno.Sdk/ImplicitPackagesResolverBase.cs
- n/a
- Bugfix
You can specify Mvvm or Mvux but will only get one of the two
You can now specify both Mvvm and Mvux as UnoFeatures
=> Adjustment to Implicit Packages

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ContentDialog.cs, src/Uno.UI/UI/Xaml/Controls/ContentDialog/ContentDialogPopupPanel.cs
closes https://github.com/unoplatform/uno/issues/15712
- Bugfix
With a forced VisibleBounds "unsafe" area of `Thickness(27, 38, 14, 72)`, you can see the `LayoutRoot` panel of the `ContentDialog` (red) still bleeds into the unsafe area:
Offsets are respected:
=> fix: ensure ContentDialog arrange respects visiblebounds

src/Uno.Sdk/Sdk/Sdk.props, src/Uno.Sdk/targets/Uno.ProjectCapabilities.Wasm.targets, src/Uno.Sdk/targets/Uno.ProjectCapabilities.targets
- related unoplatform/Uno.Wasm.Boostrap#831
- Feature
Project capabilities come from the Bootstrapper
We set the Project capabilities as early as possible for the Wasm target
=> Load Wasm Project Capabilities from Sdk

src/Uno.Sdk/targets/Uno.ProjectCapabilities.SingleProject.targets
This restores hot reload for desktop target on windows
=> fix: Make maui caps conditional to mobile targets

src/Uno.Sdk/Sdk/Sdk.props, src/Uno.Sdk/targets/Uno.Common.Desktop.targets, src/Uno.Sdk/targets/Uno.Common.Wasm.targets
- unoplatform/uno-private#354
- Feature
browserwasm sets output type of Exe for Library
desktop adds Windows Desktop Framework Reference for Library build
Resets the OutputType on browserwasm to counter the Web ProjectSystem Sdk
Removes the Windows Desktop Framework Reference for for Library builds
=> Adding better support for Libraries

src/Uno.Sdk/targets/Uno.SingleProject.MacCatalyst.targets
- Bugfix
Current Catalyst builds do not link against the real (only the stub) library for the mono component `hot_reload`.
Logs shows that the process has no capabilities 
```
default	17:10:11.369868-0400	unoapp.Mobile	trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
Metadata Updates runtime capabilities:
```
Catalyst builds now links against the real library for the mono component `hot_reload`.
`<UseInterpreter>True</UseInterpreter>` is needed, like it's already present for iOS and Android.
`<MtouchInterpreter>True</MtouchInterpreter>` is a bit odd, when setting `UseInterpreter` to true the logic sets `MtouchInterpreter` to `all` …
=> fix(catalyst): load required mono component for HR

doc/articles/features/windows-storage-pickers.md, src/Uno.UWP/Storage/Pickers/FileOpenPicker.Android.cs, src/Uno.UWP/Storage/Pickers/FilePickerHelper.Android.cs, src/Uno.UWP/Storage/Pickers/FileSavePicker.Android.cs, src/Uno.UWP/Storage/Pickers/FolderPicker.Android.cs, src/Uno.UWP/Storage/Pickers/FolderPickerHelper.Android.cs
GitHub Issue (If applicable): closes #10550
- Feature
Currently it is not possible to access the intent for Android pickers.
It is now possible to address the intent that is called by the picker user-defined before execution. As an example, the setting of the flag 'GrantPersistableUriPermission'.
```csharp
FileOpenPicker fileOpenPicker = new FileOpenPicker
{
SuggestedStartLocation = PickerLocationId.ComputerFolder
};
FilePickerHelper.RegisterOnBeforeStartActivity(fileOpenPicker, (intent) =>
{
// your code...
// for example
intent.AddFlags(Android.Content.ActivityFlags.GrantPersistableUriPermission);
});
var result = await fileOpenPicker.PickSingleFileAsync();
```
Of course, you could …
=> feat: Provide Intent access for Android pickers

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/Nested_Exit_Tests.cs, src/SamplesApp/UITests.Shared/UITests.Shared.projitems, src/SamplesApp/UITests.Shared/Windows_UI_Input/PointersTests/Nested_Exit.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Input/PointersTests/Nested_Exit.xaml.cs, src/Uno.UI.RuntimeTests/UITestsImport.props, src/Uno.UI/ts/Windows/UI/Xaml/UIElement.Pointers.ts
closes https://github.com/unoplatform/uno/issues/15968
Fix pointer exit not raised on wasm if intermediate element is larger than parent and not hit-testable
We stop exit event bubbling on wasm if we determine that pointer is still over current element or a child.
We make sure to validate that child can raise pointer events.
=> fix(pointers): Fix pointer exit not raised on wasm

src/SamplesApp/UITests.Shared/ItemExclusions.props, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Repeater/FlowLayout_Simple.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Repeater/StackLayout_Simple.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Repeater/UniformGridLayout_Simple.xaml.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/Repeater/TestUI/Samples/AnimationSamples/DefaultElementAnimator.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Repeater/Given_ItemsRepeater.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/StackLayout.cs
closes https://github.com/unoplatform/uno/issues/15939
Fix an issue where IR might re-position first items if items below are significantly higher
When an item is significantly higher than previous ones, when recycling old items the the average size changes causing items being re-positioned.
We make sure to never consider a negative original point.
=> fix(itemsRepeater): Fix an issue where IR might re-position first items if items below are significantly higher

src/Uno.UI.Runtime.Skia.MacOS/UnoNativeMac/UnoNativeMac/UNOMetalViewDelegate.m
We ask for the view's `currentRenderPassDescriptor` but we never use it afterward. This allocated enough memory to _draw_ my attention (while using Instruments).
We do the null check on the `currentDrawable` before calling managed code to draw.
=> perf(macOS): reduce memory usage of metal backend

src/Uno.UI.Tests/Windows_UI_XAML_Controls/ComboBoxTests/Given_ComboBox.cs, src/Uno.UI/UI/Xaml/Controls/Primitives/Selector.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/15881
- Bugfix
This change allows for keeping a SelectedIndex that was set out of bounds before the itemssource was set
=> fix(combobox): Don't reset SelectedIndex when changing the itemsource

src/Uno.Sdk/Tasks/ImplicitPackagesResolver.cs
- closes unoplatform/uno-private#415
- Bugfix
Uno.WinUI.WebAssembly is excluded as a direct reference for the BrowserWasm class library
Uno.WinUI.WebAssembly is now included regardless of whether we are building an Executable or Class Library
=> Include uno.ui.websassembly for wasm class lib

src/Uno.Sdk/packages.json
- unoplatform/uno.extensions#2223
- Bugfix
```
error NU1605: Warning As Error: Detected package downgrade: Xamarin.AndroidX.Collection from 1.4.0.1 to 1.3.0.1. Reference the package directly from the project to select a different version. 
error NU1605:  TestNewProjectMauiEmbeddingVsixVersion108 -> Xamarin.AndroidX.Activity 1.8.2.1 -> Xamarin.AndroidX.Collection (>= 1.4.0.1) 
error NU1605:  TestNewProjectMauiEmbeddingVsixVersion108 -> Xamarin.AndroidX.Collection (>= 1.3.0.1)
```
Package Downgrade will not occur.
=> bump AndroidX versions used for MAUI Embedding

src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.cs
=> fix: Adjust SamplesApp WinUI launch to avoid using `XamlRoot` too early

src/Uno.UI/UI/Xaml/ResourceDictionary.cs
- Performance
Current numbers gathered with @ebariche (numbers are from Wasm interpreted build):
GetFromMerged: 314ms
GetFromThemeMerged: 457ms
GetActiveThemeDictionary: 517ms
GetFromTheme: 1.07s
New numbers:
GetFromMerged: 265ms
GetFromThemeMerged: 299ms
GetActiveThemeDictionary: 144ms
GetFromTheme: 299ms
=> perf: Misc perf improvement to ResourceDictionary

build/cSpell.json, doc/articles/uno-build-error-codes.md
The Uno extension for VS Code error codes are not included in the existing list of build errors.
Added both errors to the documentation.
=> docs: add vscode error codes

src/Uno.Sdk/Tasks/ImplicitPackagesResolver.cs
- unblocks unoplatform/uno.extensions#2223
- unblocks unoplatform/uno.templates#608
- Bugfix
Xamarin.Google.Android.Material is provided as a top level package all the time. This causes a conflict with the AndroidX packages for MAUI Embedding.
We let Xamarin.Google.Android.Material come through transitively with MAUI Embedding.
=> Don't specify Google Android Material with MAUI Embedding

src/SolutionTemplate/5.1/uno51blank/Directory.Build.props, src/SolutionTemplate/5.1/uno51blank/Directory.Packages.props, src/SolutionTemplate/5.1/uno51blank/uno51blank/uno51blank.csproj, src/SolutionTemplate/5.1/uno51recommended/Directory.Build.props, src/SolutionTemplate/5.1/uno51recommended/Directory.Packages.props, src/SolutionTemplate/5.1/uno51recommended/uno51recommended/uno51recommended.csproj, src/SolutionTemplate/5.2/uno52Lib/uno52Lib.csproj, src/SolutionTemplate/5.2/uno52SingleProjectLib/uno52SingleProjectLib.csproj, src/SolutionTemplate/5.2/uno52blank/Directory.Build.props
- n/a
Build Warnings are treated normally
Build Warnings in the 5.1/5.2 templates are now set to treat Warnings as Errors to help prevent regressions that result in build warnings.
=> Enable warnings as errors

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_CalendarView.cs
Related to https://github.com/unoplatform/uno/issues/16123 and https://github.com/unoplatform/uno/pull/16136
Temporarily disables test for:
```
Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException: Assert.Fail failed. The bitmaps are not the same
at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.HandleFail(String assertionName, String message, Object[] parameters)
at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.Fail(String message, Object[] parameters)
at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.Fail(String message)
at Uno.UI.RuntimeTests.Helpers.ImageAssert.AreEqualAsync(RawBitmap actual, RawBitmap expected)
at Uno.UI.RuntimeTests.Tests.Windows_UI_Xaml_Controls.Given_CalendarView.When_ReMeasure_After_Changing_MaxDate()
at …
```
=> chore: Disable flaky test When_ReMeasure_After_Changing_MaxDate

src/SourceGenerators/Uno.UI.Tasks/Content/Uno.UI.Tasks.targets
GitHub Issue (If applicable): https://github.com/unoplatform/uno.resizetizer/issues/232
- Bugfix
Ensures that assets items are filled at design time, in order to avoid file to be deleted incorrectly.
=> fix: Run UnoAssetsGeneration at design time

doc/articles/toc.yml
These articles are already under the Themes section and it causes an annoying behavior where opening the article from beneath the Themes section will cause the navigation bar on the left to jump to the other section where this article is referenced
=> docs: remove duplicate references to themes articles

src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault/ColorPicker.xaml, src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault/Slider_themeresources.xaml
GitHub Issue (If applicable): related to #15448
- Bugfix
Square around thumbs
No square around thumbs
=> fix: Square around `ColorPicker` `Thumb`

src/Uno.Sdk/Tasks/ImplicitPackagesResolver.cs, src/Uno.Sdk/UnoFeature.cs, src/Uno.Sdk/packages.json, src/Uno.Sdk/targets/Uno.Implicit.Packages.ProjectSystem.Uno.targets, src/Uno.Sdk/targets/Uno.Implicit.Packages.ProjectSystem.WinAppSdk.targets
- unoplatform/uno-private#455
- Bugfix
- Feature
Uno.WinUI.Svg is never included
SkiaSharp packages are always included for Non-Windows/WASM heads
SVG and SkiaSharp packages are only included when building non-Windows/WASM projects when the `Skia` UnoFeature has been specified. The SVG package is only included on a Head project and is not included for libraries.
=> Fix Skia / SVG package references

doc/articles/features/Lottie.md, doc/articles/features/using-the-uno-sdk.md, src/Uno.Sdk/Sdk/Sdk.props.buildschema.json, src/Uno.Sdk/Tasks/ImplicitPackagesResolver.cs, src/Uno.Sdk/UnoFeature.cs, src/Uno.Sdk/targets/Uno.Extensions.Implicit.Packages.ProjectSystem.targets, src/Uno.Sdk/targets/Uno.Implicit.Packages.ProjectSystem.Uno.targets
- unoplatform/uno#16317
- Bugfix
Lottie and the associated Skia packages are only brought in if you add the Lottie UnoFeature
Lottie will be brought in automatically if you have `Material` or `Cupertino` defined in your UnoFeatures. as Uno.WinUI.Lottie is a transitive dependency of the themes packages.
- Removes Maps UnoFeature (public API only - this will still work as a feature)
- Fixes renamed references from `Skottie` to `Lottie` UnoFeature
- Changes behavior of `Extensions` feature to only include Hosting, Configuration, Logging and the ExtensionsCore
=> [SDK] Uno Theme transitive deps on Lottie

src/Uno.Sdk/packages.json
- n/a 
- Sdk Dependencies
Sdk adds a reference to MSAL 4.60.2 which was marked with a Security vulnerability this morning.
https://github.com/advisories/GHSA-x674-v45j-fwxw
The version provided by the SDK now targets the latest patched version
=> Bump MSAL version due to Security issue

src/Uno.UI/UI/Xaml/Controls/Primitives/SelectorItem.cs
Fix SelectorItem remains in pressed state when srcolling kicks-in on mobile targets using touch
=> fix(reg): Fix SelectorItem remains in pressed state when srcolling kicks-in

src/SolutionTemplate/5.2/uno52blank/uno52blank/uno52blank.csproj, src/SourceGenerators/Uno.UI.Tasks/Content/Uno.UI.Tasks.targets, src/SourceGenerators/Uno.UI.Tasks/Content/uno.ui.tasks.assets.targets
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/463
- Bugfix
- Ensures that PublishFolderType is set to avoid `The file XXX does not specify a 'PublishFolderType' metadata, and a default value could not be calculated. The file will not be copied to the app bundle.`
- Ensures that assets generation properly sets and uses the `TargetPath` property to avoid HotRestart to write incorrect file paths
=> Hot Restart fixes

src/Uno.UI.Runtime.Skia.Wpf/Input/WpfCorePointerInputSource.cs
GitHub Issue (If applicable): #14393
- Feature
In the current WPF platform, if multi-touch is used, only the touch message from one finger touching the screen will be received.
We can receive the multi-touch events message.
Reference https://github.com/unoplatform/uno/pull/15543
Cc: @MartinZikmund
=> feat(wpf): Add Multi-Touch support on WPF platform

src/Uno.Sdk/targets/Uno.SingleProject.Desktop.targets
Avoids this particular visual glitch:
=> fix: Adjust sdk invalid globbing

src/Uno.Sdk/targets/Uno.Implicit.Packages.ProjectSystem.targets
- Teams discussion
- Bugfix
Uno.Toolkit.Skia.WinUI is not brought in
Uno.Toolkit.Skia.WinUI is now brought in with the Skia and Toolkit UnoFeatures
=> Add missing Uno.Toolkit.Skia.WinUI reference

src/Uno.Sdk/targets/Uno.Implicit.Packages.ProjectSystem.targets
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno.templates/issues/653
- Bugfix
Themes Markup should be included for all themes when markup is used.
=> fix: Include Uno.Themes.WinUI.Markup for all themes

src/Uno.Sdk/targets/Uno.Implicit.Packages.ProjectSystem.targets
GitHub Issue (If applicable): related to https://github.com/unoplatform/uno.templates/issues/653
=> fix: Markup toolkit dependency must always be included with markup

build/cSpell.json, doc/articles/features/using-the-uno-sdk.md, src/SolutionTemplate/5.2/uno52blank/uno52blank/Platforms/iOS/PrivacyInfo.xcprivacy, src/Uno.Sdk/targets/Uno.SingleProject.iOS.targets
GitHub Issue (If applicable): https://github.com/unoplatform/uno/discussions/16257, https://github.com/unoplatform/uno.templates/issues/639
Updates the SDK to automatically include a `PrivacyInfo.xcprivacy` file in the iOS platform folder.
=> feat(sdk): Add support for Apple Privacy Manifest

src/SourceGenerators/Uno.UI.Tasks/Content/Uno.UI.Tasks.targets, src/SourceGenerators/Uno.UI.Tasks/Content/uno.ui.tasks.assets.targets
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/14852
Improves file locking on the Uno.UI.Tasks.
=> fix: use TaskHost in VS to force unloading of tasks binaries

src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_BringIntoView.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_BringIntoView.xaml.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs, src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.managed.cs
GitHub Issue (If applicable): #15971, follow up to #15916
=> Listview.ScrollIntoView for non-virtualizing panels

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/documentation-request.yml, .github/ISSUE_TEMPLATE/enhancement.yml, .github/ISSUE_TEMPLATE/samples-request.yml
Dropping macOS (AppKit) from the list and moving Skia (GTK) to the bottom. Replicating the list on all issue templates.
- The platform list was not consistent everywhere
- macOS AppKit is not really supported
Adjusted
=> ci: Adjust issue templates

doc/articles/samples-tutorials-overview.md, doc/articles/toc.yml
GitHub Issue (If applicable): closes #16427
Add `Samples & Tutorials` Overview Page in the documentation
=> docs: Add Samples & Tutorials Overview Page

src/Uno.UI.RemoteControl/HotReload/MetadataUpdater/ElementUpdaterAgent.cs, src/Uno.UI.RemoteControl/HotReload/MetadataUpdater/HotReloadAgent.cs
This change ensures that delta updates do not fail on missing assemblies, which can happen when performing HR reload on linux and HR picks up WPF assemblies that are not loaded in the current process.
=> fix: Adjust desktop hot load under linux

src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestMethodInfo.cs, src/Uno.UI.RuntimeTests/Helpers/ConditionalTestAttribute.cs
=> test: Add ConditionalTestAttribute for more control on conditionally-ignored runtime tests

src/SamplesApp/UITests.Shared/ItemExclusions.props, src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/ItemsViewTests/ItemsViewSummaryPage.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Repeater/FlowLayout_Simple.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Repeater/StackLayout_Simple.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Repeater/UniformGridLayout_Simple.xaml.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/Repeater/TestUI/Samples/AnimationSamples/DefaultElementAnimator.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Repeater/Given_ItemsRepeater.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/StackLayout.cs
closes https://github.com/unoplatform/uno/issues/16176
Restore https://github.com/unoplatform/uno/pull/15946 that was reverted by https://github.com/unoplatform/uno/pull/16253 due to the regression reported by https://github.com/unoplatform/uno/issues/16176
This adds a patch over the previous patch to workaround the found regression: https://github.com/unoplatform/uno/pull/16472/commits/5538eea0774a122d8cf3b938997148134680aaae
- [?] Contains **NO** breaking changes
=> fix(itemsRepeater): Fix an issue where IR might re-position first items if items below are significantly taller

src/Uno.UI.Composition/Composition/ContainerVisual.skia.cs
The scenario being profiled is rapid window resizing, which will keep invalidating render.
Previously, this caused a lot of boxing and also SetMatrixDirty is taking up a lot of CPU time.
Boxings are gone completely, and SetMatrixDirty is taking much less CPU time.
=> perf: Avoid boxing in ContainerVisual.SetMatrixDirty

src/SolutionTemplate/5.2/uno52AppWithLib/uno52AppWithLib/uno52AppWithLib.csproj, src/SolutionTemplate/5.2/uno52AppWithLib/uno52emptylib/uno52emptylib.csproj, src/Uno.Sdk/targets/Uno.Common.Wasm.targets
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/16524
- Bugfix
Ensures that a library without any eligible `Content` builds properly.
=> fix: Don't fail build on an empty library

src/Uno.UI.Composition/Composition/CompositionViewBox.skia.cs, src/Uno.UI.Composition/Composition/ShapeVisual.skia.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Composition/Given_CompositionNineGridBrush.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement.cs, src/Uno.UI/UI/Xaml/Controls/Canvas/Canvas.Layout.cs, src/Uno.UI/UI/Xaml/Controls/Image/Image.crossruntime.cs, src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.cs, src/Uno.UI/UI/Xaml/FrameworkElement.Layout.crossruntime.cs, src/Uno.UI/UI/Xaml/Media/VisualTreeHelper.cs, src/Uno.UI/UI/Xaml/UIElement.Layout.crossruntime.cs, src/Uno.UI/UI/Xaml/UIElement.skia.cs
GitHub Issue (If applicable): closes #16501
=> fix: Improve Skia clipping

src/Uno.UI/Generated/3.0.0.0/Microsoft.UI.Xaml.Automation.Peers/ItemsControlAutomationPeer.cs, src/Uno.UI/Generated/3.0.0.0/Microsoft.UI.Xaml.Automation.Peers/SelectorAutomationPeer.cs, src/Uno.UI/UI/Xaml/Automation/Peers/ComboBoxAutomationPeer.cs, src/Uno.UI/UI/Xaml/Automation/Peers/ItemsControlAutomationPeer.cs, src/Uno.UI/UI/Xaml/Automation/Peers/SelectorAutomationPeer.cs
GitHub Issue (If applicable): part of #14344 
- Feature
Ported the `ComboBoxAutomationPeer` from WinUI.
=> feat: Port `ComboBoxAutomationPeer`

src/Uno.UI.Composition/Composition/CompositionObject.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Composition/Given_ExpressionAnimation.cs
GitHub Issue (If applicable): closes #16570
=> fix: Fix ExpressionAnimation not working well with CompositionPropertySet

doc/articles/features/working-with-xaml-hot-reload.md
Current documentation mentions details regarding RemoteControl.g.cs but it's not visible anymore as that file only exists in memory now because it's generated by Roslyn C# generators.
Remove RemoteControl.g.cs details as it is not visible anymore
=> docs(HotReload): Remove RemoteControl.g.cs details as it is not visible anymore

src/Uno.UI/UI/Xaml/Window/Native/Window.iOS.cs
GitHub Issue (If applicable): related to private issue
- Bugfix
The BypassCheckToCloseKeyboard behavior defaulted to false, which meant the keyboard would close on each native window hit test, which is not in line with other targets
Aligned
=> fix: Bypass keyboard closing behavior on iOS

src/Uno.Sdk/Uno.Sdk.csproj
- n/a
- Bugfix
Schema File is missing from the generated nuget package
Schema File is added to the pack files.
=> Pack missing schema file

src/Uno.UI/UI/Xaml/Controls/ItemsControl/ItemsPresenter.cs
GitHub Issue (If applicable): closes #16441
- Bugfix
GridView would fail to render 1st item in the collection.
^ no more.
=> fix(GridView): 1st item fails to render

src/Uno.UWP/Storage/Pickers/FileOpenPicker.iOS.cs
- Bugfix
When selecting multiple files from iOS, users are able to tap over the "add" button multiple times, causing an exception and subsequently making the app crash.
=> fix(iOS): multiple files selection

doc/articles/feature-flags.md, src/Uno.UI/FeatureConfiguration.cs
GitHub Issue (If applicable): related to https://github.com/unoplatform/uno/issues/10791
- Feature
Tooltips are disabled on Skia by default
Enabled
=> feat: Enable `ToolTips` on Skia by default

src/Uno.Sdk/targets/Uno.Sdk.After.targets
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/16507
- Bugfix
Ensures that a active selected `TargetFramework` is removed from the `TargetFrameworks`, it's not getting reused by `_UnoSelectedTargetFramework` from the `.csproj.user` file.
=> fix(sdk): Don't reorder using a non-existing TargetFramework

src/Uno.UI.Runtime.Skia.Wpf/Input/WpfKeyboardInputSource.cs
- Refactoring
We have to do Reflection on every keyboard event in wpf.
We will call the win32 method the get the scan code.
Reference https://github.com/unoplatform/uno/pull/14371#discussion_r1404625891 and https://github.com/dotnet/wpf/issues/8473#issuecomment-2084878655
=> perf(wpf): Replace Reflection with PInovke win32 in WpfKeyboardInputSource

src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/FlipView/FlipView_Buttons.xaml.cs, src/Uno.UI/UI/Xaml/Controls/FlipView/FlipView.managed.cs, src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.wasm.cs
GitHub Issue (If applicable): closes #15277
=> fix: Fix FlipView SelectedIndex not changing with touch swipes on Wasm

src/Uno.UI.Runtime.Skia.Gtk/Input/GtkKeyboardInputSource.cs, src/Uno.UI/Helpers/InputHelper.cs
- Bugfix
Now the GtkKeyboardInputSource will use the [InputHelper.TryConvertKeyCodeToScanCode](https://github.com/unoplatform/uno/blob/292e14b3f933dba83d78363d0729d488908c6a8d/src/Uno.UI/Helpers/InputHelper.cs) to convert the key code to scan code which will always return false. It means the scan code same as the key code.
The GtkKeyboardInputSource will use the gtk to get the scan code
See https://docs.gtk.org/gdk3/method.Event.get_scancode.html
Reference https://github.com/unoplatform/uno/pull/16670
Origin commit : 98c965a794b058541cafe6756c46f021b1017d5c
Cc @ramezgerges
=> fix(gtk): Fix get scan code in GtkKeyboardInputSource

build/test-scripts/run-netcore-mobile-template-tests.ps1, src/Uno.Sdk/targets/Uno.Common.Wasm.targets
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/16657
- Bugfix
Restores the ability to disable implicit usings
=> fix: Validate disable implicit using

src/Uno.UI.Runtime.Skia.X11/X11ApplicationHost.cs, src/Uno.UI.Runtime.Skia.X11/X11_Bindings/X11Helper.cs, src/Uno.UI.Runtime.Skia.X11/X11_Bindings/x11bindings_Glx.cs, src/Uno.UI.Runtime.Skia.X11/X11_Bindings/x11bindings_XLib.cs
GitHub Issue (If applicable): closes #16554
=> perf: Update X11 bindings to LibraryImport

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/When_XBind_TargetDisposed.xaml, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/When_XBind_TargetDisposed.xaml.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_xBind.cs, src/Uno.UI/UI/Xaml/Controls/ItemsControl/ItemsControl.cs
GitHub Issue (If applicable): (linked from private issue)
- Bugfix
Leaked ItemsControl.ItemsSource subscription can cause ObjectDisposedException to be thrown when the said source is updated.
The exception is prevented.
=> fix(droid): workaround for ItemsControl's ObjectDisposedException

build/test-scripts/run-netcore-mobile-template-tests.ps1, src/SolutionTemplate/5.1/uno51blank/Directory.Build.targets, src/SolutionTemplate/5.1/uno51recommended/Directory.Build.targets, src/SolutionTemplate/5.2/uno52AppWithLib/Directory.Build.targets, src/SolutionTemplate/5.2/uno52Lib/uno52Lib.csproj, src/SolutionTemplate/5.2/uno52NuGetLib/Class1.cs, src/SolutionTemplate/5.2/uno52NuGetLib/global.json, src/SolutionTemplate/5.2/uno52NuGetLib/uno52NuGetLib.csproj, src/SolutionTemplate/5.2/uno52blank/Directory.Build.targets, src/Uno.Sdk/Models/PackageReference.cs, src/Uno.Sdk/Sdk/Sdk.props, src/Uno.Sdk/Tasks/ImplicitPackagesResolver.cs, src/Uno.Sdk/targets/Uno.Common.targets, src/Uno.Sdk/targets/Uno.Implicit.Packages.ProjectSystem.targets, src/Uno.Sdk/targets/Uno.Implicit.Packages.targets
- fixes #16572
- Bugfix
We set the value of IsPackable to false by default 
We wait until the props have / csproj are loaded and evaluate IsPackable in the targets. This allows us to further evaluate whether `GeneratePackageOnBuild` has been set. If it has we will provide the value of that property or a default of `false`.
=> SDK ignores GeneratePackageOnBuild

src/SamplesApp/UITests.Shared/UITests.Shared.projitems, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ToolTip/ToolTip_Nested.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ToolTip/ToolTip_Nested.xaml.cs, src/Uno.UI/UI/Xaml/Controls/ToolTip/ToolTip.cs, src/Uno.UI/UI/Xaml/Controls/ToolTip/ToolTipService.cs
GitHub Issue (If applicable): closes #15792 
- Bugfix
Hovering nested elements with ToolTipService.ToolTip display multiple overlapping tooltips at once
Aligned the behavior to windows: only the inner-most under-cursor element's tooltip is displayed.
=> fix(tooltip): prevent multiple nested tooltips from displaying all at once

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ContentDialog.cs, src/Uno.UI/UI/Xaml/Controls/Popup/PopupRoot.cs, src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.MuxInternal.cs
GitHub Issue (If applicable): closes #16358
=> fix: Fix ScrollViewer logic for handling focus and adjust for missing RootScrollViewer

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/When_Transition_Modifies_SubProperty.xaml.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/When_Transition_Modifies_Subproperty.xaml, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_VisualStateManager.cs, src/Uno.UI/DataBinding/BindingPath.BindingItem.cs, src/Uno.UI/DataBinding/BindingPath.cs, src/Uno.UI/UI/Xaml/VisualStateGroup.cs
=> fix(visualstates): fix rolling back properties when the next state doesn't modify a property, but modifies one of its subproperties

src/SamplesApp/SamplesApp.netcoremobile/SamplesApp.netcoremobile.csproj
- Bugfix
VS Automatic provisioning for iOS fails when `<ApplicationId>` is missing
Added
=> fix: Add `ApplicationId` to allow for VS Automatic Provisioning of Samples app

src/Uno.Sdk/targets/Uno.SingleProject.Desktop.targets, src/Uno.Sdk/targets/Uno.SingleProject.Wasm.targets, src/Uno.Sdk/targets/Uno.SingleProject.WinAppSdk.targets
- #16618
- Bugfix
We do not set the version based on the ApplicationDisplayVersion
We now mimic the behavior of the Android, iOS, & MacCatalyst SDK's in their handling of the ApplicationDisplayVersion in setting the Version.
=> Set the Version

src/Uno.Sdk/Sdk/Sdk.props.buildschema.json, src/Uno.Sdk/packages.json
- #16618
- Other... Please describe: Package update
Uno.Resizetizer 1.4 does not properly handle ApplicationDisplayVersion and ApplicationVersion
Uses Uno.Resizetizer 1.5 dev which has been updated to properly handle the ApplicationDisplayVersion, ApplicationVersion, ApplicationId and a few other commonly used MSBuild properties to update the appxmanifest.
=> Bump uno.resizetizer

src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/ScrollPresenter/ScrollPresenterViewChangeTests.cs
Seems to be fine for me locally. let's see if it was accidently fixed.
GitHub Issue (If applicable): closes #16559
=> chore: reenable SetOffsetsBeforeLoading on X11

src/Uno.UI.Runtime.Skia.MacOS/UnoNativeMac/UnoNativeMac/UNOWindow.m
GitHub Issue (If applicable): closes #16820
- Bugfix
The skia/macOS code knows which `pointerDeviceType` is being used but this is not copied back to the managed structure. This means the default `0` value is used and that means a `Touch` event. Any code that depends on this value could misbehave.
The correct value is shared with the managed code.
=> fix(macos): Let the managed side know about the pointerDeviceType

src/SamplesApp/UITests.Shared/UITests.Shared.projitems, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Input/Pointers/PointerEventArgsTests.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Input/Pointers/PointerEventArgsTests.xaml.cs, src/Uno.UI.Runtime.Skia.Wpf/Input/WpfCorePointerInputSource.cs
GitHub Issue (If applicable): #14393
- Bugfix
We can receive the pointer event with IsLeftButtonPressed is true when touch release.
We can receive the pointer event with IsLeftButtonPressed is false when touch release.
See https://github.com/unoplatform/uno/pull/16378/files#r1575262313
Cc @dr1rrb , and I will add more information about the barel button and the eraser status later.
=> fix(wpf): Fix IsLeftButtonPressed status on WPF platform

.github/workflows/labeler.yml, .github/workflows/uwp-autoconvert.yml
Hey! 🙂
I want to contribute the following changes to your workflow:
- Stop running workflows when there is a newer commit in branch
- Use commit hash instead of tags for action versions
- Use names for run steps
- Steps should only perform a single command
These changes are part of a research Study at TU Delft looking at GitHub Action Smells. [Find out more](https://ceddy4395.github.io/research/gha-smells.html)
=> Fix potential github action smells 

src/Uno.Sdk/targets/Uno.SingleProject.Desktop.targets
- fixes #16905 
- Bugfix
When launching a Skia Desktop app a console is launched
We now build as a WinExe to prevent this behavior
=> Desktop target should not launch console

src/Uno.Sdk/packages.json
- related unoplatform/uno.templates#697
- Other... Please describe: update package versions
Maui group is undefined as we typically relied on the MAUI Sdk to provide this
Maui group is now defined with versions including override so that when developing for net9.0 you will get the net9 version of MAUI.
Additional packages have been updated as updates for several packages are available.
=> chore: bump dependencies

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/When_TwoWay_Text_Binding.xaml, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/When_TwoWay_Text_Binding.xaml.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs
GitHub Issue (If applicable): closes #16951
=> fix(TextBox): Fix TwoWay binding on TextBox.Text not updating properly when unfocused

build/ci/.azure-devops-docs.yml, build/ci/templates/docfx-intermediary-assets.yml
GitHub Issue: closes #15077
The intermediary assets for docfx are built manually
The intermediary assets for docfx are built automatically by the pipeline.
=> ci: build docfx intermediary assets

src/Uno.UI/UI/Xaml/Media/Imaging/RenderTargetBitmap.Android.cs
GitHub Issue (If applicable): closes unoplatform/kahua-private#146
- Bugfix
On android, ListView drag-n-drop re-ordering would sometimes randomly crash the app with:
> [libc] Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xadd00000 in tid 32079 (yname.UnoSample), pid 32079 (yname.UnoSample)
Should no longer crash for the same reason.
=> fix(droid): RenderTargetBitmap SIGSEGV

src/Uno.UI.RemoteControl/buildTransitive/Uno.UI.DevServer.targets
- Bugfix
RemoteControlHost.config is not used when building from VS, which can happen when a solution was previously opened from VS Code.
=> fix: Don't use RemoveControlHost.config in VS

doc/articles/features/windows-ui-xaml-window.md
=> docs: Fix table markdown formatting in Windowing docs

src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.cs
GitHub Issue (If applicable): closes #15805 
- Other... Please describe: Performance
In a textblock, when the inlines are being invalidated, there's a projection made using LINQ, causing unnecessary allocations.
This simply replaces the Select.ToList instruction to a foreach based one.
=> perf(TextBlock): Removed LINQ when invalidating inlines

src/Uno.UI/UI/Xaml/Media/AcrylicBrush/AcrylicBrush.skia.cs
Workaround for https://github.com/unoplatform/uno/issues/16853
- Bugfix
On macOS/arm64 when using the Metal renderer the AcrylicBrush (used for Fluent) gives a pinkish background to several UI elements.
On macOS/arm64 we instead use, **as a workaround**, the `FallbackColor` to create the color brush.
=> fix: workaround for AcrylicBrush pink background on macOS/arm64

src/Uno.UI.Runtime.Skia.MacOS/MacOSWindowNative.cs
GitHub Issue (If applicable): closes #17002
- Bugfix
If the exact icon (file) is not found we try to look for a scale version - but still try to load the original file name (copy/paste error).
If the exact icon (file) is not found we try to look for a scale version and load that scaled version.
https://github.com/unoplatform/uno/issues/17002
=> fix: use the correct path for a scale icon

src/Uno.UI.Runtime.Skia.MacOS/UnoNativeMac/UnoNativeMac/UNOMetalViewDelegate.m
Related to https://github.com/unoplatform/uno/issues/16853
- Other... Please describe: extra logging on debug builds
Current logging for Metal rendering do not show the status, logs and errors.
Under `DEBUG` (native lib) Metal logging now includes status, logs and errors.
Even more logging can be enabled by defining `DEBUG_METAL`
=> chore: add extra native logging for macOS/metal rendering

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_AutoSuggestBox.cs, src/Uno.UI/UI/Xaml/Controls/AutoSuggestBox/AutoSuggestBox.cs, src/Uno.UI/UI/Xaml/Controls/Icons/SymbolIcon.cs
GitHub Issue (If applicable): closes #15662
=> fix: Fix AutoSuggestBox QueryIcon size

src/Uno.UI.RemoteControl.VS/EntryPoint.ActiveProfileSync.cs, src/Uno.UI.RemoteControl.VS/Helpers/VsHierarchyExtensions.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/17029
- Bugfix
When the active project is reloaded to adjust the first TFM, this change avoids closing opened files that are related to that project.
=> fix(vsix): Don't close opened files when reloading the project

src/Uno.UI.Composition/Composition/CompositionSurfaceBrush.skia.cs
GitHub Issue (If applicable): #17033
Let's see if this is the problem. My guess is that we might try to render the image right before a needed layout cycle. Looking at SkiaSharp's source, it returns null if you try to resize to a zero rectangle.
=> fix(surfacebrush): check that the final size isn't empty before resizing images.

src/Uno.Sdk/packages.json, src/Uno.Sdk/targets/Uno.Common.Android.targets, src/Uno.Sdk/targets/Uno.Common.Wasm.targets, src/Uno.Sdk/targets/Uno.Common.WinAppSdk.targets, src/Uno.Sdk/targets/Uno.Common.iOS.targets, src/Uno.Sdk/targets/Uno.Extensions.Implicit.Packages.ProjectSystem.targets
- unoplatform/uno.templates#743 - Build Failure
- Bugfix
We do not add Microsoft.Identity.Client.Extensions.MSAL
We add MSAL packages across all TFMs when the `AuthenticationMSAL` UnoFeature is present
We now also provide the top level dependency for Microsoft.Identity.Client.Extensions.MSAL
We exclude the MSAL packages but not the Extensions package from unsupported targets.
=> fix: builds fail with latest MSAL updates

src/Uno.Sdk/targets/Uno.Implicit.Packages.ProjectSystem.Uno.targets
- fixes #17023
- Bugfix
There are several conditions which will bring in SkiaSharp.Views.Uno.WinUI which includes adding them for WASM. This results using Emscripten when it wouldn't otherwise be needed.
SkiaSharp.Views.Uno.WinUI is now excluded on WASM unless the Skia UnoFeature is explicitly added.
=> Exclude SkiaSharp Views on WASM unless you explicitly use Skia

src/AddIns/Uno.UI.Lottie/LottieVisualSourceBase.wasm.cs
GitHub Issue (If applicable): closes #17090
- Bugfix
on wasm, Lottie animation would sometime be unproperly disposed, and spam the console with:
> No UIElement found for htmlId "118674"
no more.
=> fix(wasm): lottie animation event leak

src/Uno.Sdk/targets/Uno.Implicit.Packages.ProjectSystem.Uno.targets
- closes #17024
- Bugfix
Lottie is not always included for the Desktop target
Lottie is now included always for the Desktop target
=> feat: always include Lottie on Desktop

src/Uno.UI.Tests/DependencyProperty/Given_DependencyProperty.DefaultValueProvider.cs, src/Uno.UI/UI/Xaml/DependencyPropertyDetailsCollection.cs
It can happen the collection changes while the default value is being created, hence changing the ref we were originally working with.
- Bugfix
=> fix: Handle cases where `_entries` change while default value is retrieved

src/SamplesApp/UITests.Shared/UITests.Shared.projitems, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/SvgHighDPIBlur.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/SvgHighDPIBlur.xaml.cs, src/Uno.UI.Composition/Composition/CompositionSurfaceBrush.skia.cs
GitHub Issue (If applicable): closes #16697
=> fix(imagebrush): prevent blurring when dpi scaling > 1

src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault/Slider_themeresources.xaml, src/Uno.UI.FluentTheme.v2/themeresources_v2.xaml
GitHub Issue (If applicable): closes #16484, closes #16900
- Bugfix
=> fix: Undo custom `Margin` on `Slider` `Thumb`

src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.Common.Status.cs, src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.MetadataUpdate.cs, src/Uno.UI.RemoteControl/HotReload/HotReloadStatusView.cs, src/Uno.UI.RemoteControl/HotReload/HotReloadStatusView.xaml, src/Uno.UI.RemoteControl/HotReload/WindowExtensions.cs, src/Uno.UI.RemoteControl/RemoteControlClient.Status.cs, src/Uno.UI.RemoteControl/RemoteControlClient.cs, src/Uno.UI.RemoteControl/RemoteControlStatus.cs, src/Uno.UI.RemoteControl/RemoteControlStatusView.cs, src/Uno.UI/Diagnostics/DiagnosticView.Factories.cs, src/Uno.UI/Diagnostics/DiagnosticViewManager.TView.TState.cs, src/Uno.UI/Diagnostics/DiagnosticViewManager.TView.cs
* Merge dev-server status into HR status
* Make sure to always have a valid status
Dev-server status might appear separated from the HR status
Merged into a single indicator
=> feat(hrui): Merge dev-server status into HR status + make sure to always have a valid status

src/Uno.UI.RemoteControl.Server.Processors/HotReload/ServerHotReloadProcessor.MetadataUpdate.cs, src/Uno.UI.RemoteControl.Server.Processors/HotReload/ServerHotReloadProcessor.cs, src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.Agent.cs, src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.Common.Status.cs, src/Uno.UI.RemoteControl/HotReload/HotReloadStatusView.cs, src/Uno.UI.RemoteControl/HotReload/HotReloadStatusView.xaml, src/Uno.UI.RemoteControl/HotReload/Messages/AssemblyDeltaReload.cs, src/Uno.UI.RemoteControl/RemoteControlStatus.cs
* Fix file change detection
* Process all changed files in a single update
* An empty buffer of file is sent every 250 ms causing lot of messages for nothing
* Once we detect changes, we process each file individually instead of compiling only once with all update files
* No more empty file lists processed
* We wait effectively for 250ms without any file change (instead of processing a buffer of changed file during a random 250ms window)
* Once detected all changed files are processed in a single compilation
=> fix(hr): Mix updates of HR

src/Uno.UI.Runtime.Skia.MacOS/UnoNativeMac/UnoNativeMac/UNOMetalViewDelegate.m, src/Uno.UI/UI/Xaml/Media/AcrylicBrush/AcrylicBrush.skia.cs
GitHub Issue (If applicable): closes #16853
- Bugfix
When using Material some background have a pinkish colour instead of the expected grey.
The correct colour is used.
The fact that this worked on `x86_64` really threw me off.
So it was not (now removed) the Uno `Color.cs` parsing an invalid string, nor was it something from the MS SDK, nor was it a bad RGBA to ARGB conversion inside Uno (or Skia) code.
The pink colour comes from the uninitialized texture as Metal defaults to red and some transparency was applied (over the normal grey colour). Sadly this does not report any error in the Metal API (even when special debugging/performance-affected code is used).
Internal Issue (If …
=> fix(macOS): Let the Metal texture be used for sampling

src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.Common.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/17237
- Bugfix
DataContext is being set to null on the new instance, despite code that clones properties correctly updating the DataContext
ApplyDataContext method has been removed to avoid incorrectly setting the DataContext
=> fix: Remove ApplyDataContext method (deprecated) that's causing invalid data context

src/Uno.UI/Controls/PaintPool.Android.cs, src/Uno.UI/TypefaceStyleHelper.Android.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.Android.cs, src/Uno.UI/UI/Xaml/Extensions/FontHelper.Android.cs, src/Uno.UI/UI/Xaml/Extensions/FontHelper.Lookup.Android.cs
=> feat(android): Proper variable font support

src/Uno.UI.RemoteControl.Server.Processors/HotReload/ServerHotReloadProcessor.cs, src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.Common.Status.cs, src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.cs, src/Uno.UI.RemoteControl/HotReload/Messages/HotReloadState.cs, src/Uno.UI.Toolkit/Uno.UI.Toolkit.Windows.csproj
Remove reference to IMessage (and some other messages) from toolkit (windows)
Some types from `Uno.RemoteControl.Messaging` assembly are referenced in the toolkit on windows, noticeably `IMessage`. This prevent app to reference both assemblies.
Only required internal types are referenced in the toolkit.
=> chore: Remove reference to IMessage (and some other messages) from toolkit (windows)

doc/articles/uno-community-toolkit-v7.md, doc/articles/uno-community-toolkit-v8.md, doc/articles/uno-community-toolkit.md
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/16872
Add additional details for non-Windows platform compatibility and troubleshooting for Windows Community Toolkit documentation based on the [current discussion on Discord](https://discord.com/channels/372137812037730304/550416151172087808/1258070247496220752) with @Arlodotexe and @michael-hawker.
=> docs(WCT): Add additional details for non-Windows platform compatibility and troubleshooting for Windows Community Toolkit

doc/templates/uno/partials/scripts.tmpl.partial
- Bugfix 
The Algolia search box for the documentation is no longer visible in canary browsers, and a similar behavior is expected in upcoming stable browser versions when using the deprecated `DOMNodeInserted`.
The Algolia search box for the documentation is visible for all browser versions using `MutationObserver` as a replacement for the deprecated `DOMNodeInserted`.
> [!IMPORTANT]
> Currently, `DOMNodeInserted` is deprecated and triggers a warning in stable browser versions (126.0.x.x) but has already been disabled and throws an error in the latest canary versions (127.0.x.x and above). 
> Mutation event support will be disabled by default starting in Chrome 127, around **July 30, 2024**.
> For more information: [Chrome …
=> fix: Replace deprecated DOMNodeInserted with MutationObserver for Algolia DocSearch initialization

src/Uno.UI/UI/Xaml/VisualStateGroup.cs
Fix Visual transition not applied properly
We are ignoring transitions that does not have both `From` and `To` set
🙃
=> fix: Fix Visual transition not applied properly

src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.Common.Status.cs, src/Uno.UI.RemoteControl/HotReload/HotReloadStatusView.Entries.cs, src/Uno.UI.RemoteControl/HotReload/HotReloadStatusView.cs, src/Uno.UI.Toolkit/Diagnostics/DiagnosticsOverlay.xaml, src/Uno.UI/UI/Xaml/VisualStateGroup.cs
closes https://github.com/unoplatform/uno-private/issues/507
Note: This is based on https://github.com/unoplatform/uno/pull/17425, and includes https://github.com/unoplatform/uno/pull/17436. This current PR is expected to be merged only once those both PR has been merged.
Only this commit https://github.com/unoplatform/uno/commit/b49756b0d1d3c9e047b68d1465c86e4a0c01a868 is relevent
Animate entrance and exit of notification from HR UI
No anim
Animated
=> Dev/dr/hr UI update

src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.DragDrop.cs
GitHub Issue (If applicable): closes #17464
=> fix: Fix ListView dragging not reverting back to NotDragging state

build/cSpell.json, doc/articles/common-issues-ioscatalyst.md
There might be a error message coming related to loading IOS devices
This PR gives an documentation update how to troubeshoot in case if we get a error message in loading IOS devices.
=> docs: ios retrive device error message

src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.Xaml.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/521
- Bugfix
XamlReader HR can be used on iOS/Catalyst/
=> fix: Ensure XamlReader HR can run on iOS

doc/articles/debugging-wasm.md
- Bugfix
The image in the Debugging WASM was previously replaced by `![IIS express settings](Assets/quick-start/![alt text](image.png))`.
=> docs: Fix missing image on Debugging WASM

src/Uno.UI.RemoteControl.VS/EntryPoint.cs, src/Uno.UI.RemoteControl.VS/GlobalJsonObserver.cs, src/Uno.UI.RemoteControl.VS/Notifications/InfoBar.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/17495
- Bugfix
Provide a banner to restart VS in place when the uno.sdk has changed.
=> feat: Notify for VS restore on uno.sdk change

src/Uno.UI.Toolkit/Diagnostics/DiagnosticsOverlay.Notification.cs, src/Uno.UI.Toolkit/Diagnostics/DiagnosticsOverlay.Placement.cs, src/Uno.UI.Toolkit/Diagnostics/DiagnosticsOverlay.cs, src/Uno.UI.Toolkit/Diagnostics/DiagnosticsOverlay.xaml, src/Uno.UI.Toolkit/Diagnostics/RelativePlacement.cs, src/Uno.UI.Toolkit/RectExtensions.cs
closes https://github.com/unoplatform/uno-private/issues/511
closes https://github.com/unoplatform/uno-private/issues/512
closes https://github.com/unoplatform/uno-private/issues/513
Improve placement strategies of the HR indicator 
Basic drag and drop of the indicator
* Enforce window edges + safe area
* Persist location and restore on app restart
* Move the anchor at the right and display notification on the left when to close for the right edge of the window
=> feat(hrui): Improve HR indicator placement strategies

src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.Xaml.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/15918, closes https://github.com/unoplatform/uno-private/issues/525
- Bugfix
Restore XAML hot reload for android until lambda adjustments can be used.
=> fix: Use XAML reader hot reload for android

build/test-scripts/run-net7-template-linux.ps1, src/SolutionTemplate/5.2/uno52blank/uno52blank/uno52blank.csproj, src/SourceGenerators/Uno.UI.Tasks/RuntimeAssetsSelector/RuntimeAssetsSelectorTask.cs
- Bugfix
Ensures that net7.0 cross-runtime libraries can still be referenced.
=> fix: Ensure compatibility with SkiaSharp 3 targeting net7.0

src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/FramebufferHost.cs
- Bugfix
Fix Framebuffer rendering regression after windowing changes.
=> fix(fb): Force an initial refresh

src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.Common.Status.cs, src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.Xaml.cs
closes https://github.com/unoplatform/uno-private/issues/574#top
Add notification for XAML reader based HR
Note: This only fixes the missing notifications, but the HR on save is by design and will remain as is
=> fix(hrui): Add notification for XAML reader based HR

src/Uno.UI/XmlnsDefinitionAttribute.cs
- Bugfix
Add Windows.UI to the list of known namespaces for resource dictionaries for intellisense to recognize types.
=> fix: Add Windows.UI to known namespaces for intellisense

doc/articles/Uno-UI-Performance.md
We can not find any animation log after `builder.AddFilter("Windows.UI.Xaml.Media.Animation", LogLevel.Debug);`
We can find the animation log after `builder.AddFilter("Microsoft.UI.Xaml.Media.Animation", LogLevel.Debug);`
I test the code in my demo project, and I can find the log message of animation in console.
```csharp
builder.AddFilter("Windows.UI.Xaml.Media.Animation", LogLevel.Debug);
builder.AddFilter("Microsoft.UI.Xaml.Media.Animation", LogLevel.Debug);
```
See my demo code: https://github.com/lindexi/lindexi_gd/blob/72617d0df7ae8e54548ce217dd50d5bfa5054133/UnoDemo/WernujarlerhelkayFebairleewel/WernujarlerhelkayFeba …
=> docs: Fix the document of Animation output log filter.

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/ThemeResource_Refresh_On_Loading.xaml, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/ThemeResource_Refresh_On_Loading.xaml.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_ThemeResource.cs, src/Uno.UI.Tests/Windows_UI_Xaml/Given_xLoad.cs, src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePicker.cs, src/Uno.UI/UI/Xaml/FrameworkElement.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/17637, closes https://github.com/unoplatform/uno/issues/6700
- Bugfix
In WinUI `ThemeResources` are refreshed when the element is loading, as that's the time when the parent tree is valid and it is possible to properly gather the applicable resource dictionaries.
Refresh explicitly
=> fix: Refresh theme resources on `Loading`

src/Uno.UI.RuntimeTests/IntegrationTests/common/TestServices.InputHelper.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ScrollViewer.cs, src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.MuxInternal.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/17384
- Bugfix
Currently the first focusable element gets focused on pointer release on `ScrollViewer`.
Ported fix from WinUI 3 1.6
=> fix: `ScrollViewer` focus behavior on pointer release

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs, src/Uno.UI/Extensions/ViewExtensions.visual-tree.cs, src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.managed.cs, src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.cs
GitHub Issue (If applicable): closes #17695
- Bugfix
ListView fails to render all items that should be in the viewport when the items-source and the selection are modified in quick succession.
^ should no longer happen.
=> fix(listview): managed listview doesnt render all items inside viewport

src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props, src/Uno.Foundation/Diagnostics/DiagnosticViewRegistry.cs, src/Uno.UI.RemoteControl.VS/EntryPoint.cs, src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.Agent.cs, src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.Common.Status.cs, src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.cs, src/Uno.UI.RemoteControl/HotReload/HotReloadStatusView.Entries.cs, src/Uno.UI.RemoteControl/RemoteControlClient.Status.cs, src/Uno.UI.RemoteControl/RemoteControlClient.cs, src/Uno.UI.RemoteControl/buildTransitive/Uno.UI.DevServer.targets, src/Uno.UI/Diagnostics/DiagnosticView.Factories.cs
closes https://github.com/unoplatform/uno/issues/17753
closes https://github.com/unoplatform/uno/issues/17756
linked https://github.com/unoplatform/uno/issues/17757
closes https://github.com/unoplatform/uno/issues/17846
Improve dev-server reliability
* Dev-Server is restarted only after build, driving the built app to not have the updated port to use
* When dev-server uses a new port, app needs to be manullay rebuilt
* Connection cannot be restore
* Dev-server is automatically restarted 5sec after it's being closed
* Dev-server attempts to re-use the same port when possible, allowing apps to restore connection automatically
* On re-connection, the client will make sure to re-configure the server (discover processors)
=> fix(devSrv): Improve dev-server reliability

src/Uno.UWP/Extensions/Matrix3x2Extensions.cs
Benchmark:
```csharp
[MemoryDiagnoser]
public partial class Benchs
{
public struct Point
{
public double X { get; set; }
public double Y { get; set; }
public Point(double x, double y)
{
X = x;
Y = y;
}
}
public static Point TransformBaseline(Matrix3x2 matrix, double x, double y)
{
if (matrix.IsIdentity)
{
return new Point(x, y);
}
return new Point(
(x * matrix.M11) + (y * matrix.M21) + matrix.M31,
(x * matrix.M12) + (y * matrix.M22) + matrix.M32);
}
public static Point TransformUpdated(Matrix3x2 matrix, double x, double y)
{
if (matrix.IsIdentity)
{
return new Point(x, y);
}
var transformed = Vector2.Transform(new Vector2((float)x, (float)y), matrix);
return new Point(transformed.X, transformed.Y);
}
private static Matrix3x2 _doubleScale = Matrix3x2.CreateScale(2.0f);
[Benchmark]
public …
```
=> perf: Improve matrix transformation performance

src/Uno.Sdk/targets/Uno.ProjectCapabilities.SingleProject.targets, src/Uno.Sdk/targets/Uno.ProjectCapabilities.targets
- fixes #16490
- Bugfix
When selecting the project properties in Visual Studio an exception is encountered
We now always provide the required MAUI capability which seems to resolve the problem in Visual Studio without adjustments to the csproj.
=> Project capabilities should always be present for SingleProject

src/Uno.Sdk/targets/Uno.Implicit.Packages.targets
- fixes #17865
- Bugfix
There is a typo when we remove the temporary Implicit Package group
This is fixed
=> Typo in implicit packages remove item

src/SamplesApp/SamplesApp.netcoremobile/SamplesApp.netcoremobile.csproj, src/SamplesApp/UITests.Shared/Msal/MsalLoginAndGraph.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MediaPlayerElement/MediaPlayerElement_Original_MsAppdataSource.xaml.cs
- Bugfix
Workaroud for https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2617
Runs
=> fix: Workaround `Microsoft.Graph` for local iOS build

src/Uno.Sdk/targets/Uno.ProjectCapabilities.targets
- fixes #17530
- Bugfix
We conditionally set the DefaultXamlRuntime when not building for WinUI
We now explicitly set this all the time if the DefaultXamlRuntime has not been set.
=> Force setting DefaultXamlRuntime on all platforms

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media_Imaging/Given_BitmapSource.cs, src/Uno.UI/UI/Xaml/Controls/Image/Image.skia.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/17540
- Bugfix
Setting `UriSource` to `null` previously kept the image displayed
Not showing the image anymore
=> Setting `BitmapImage.UriSource` to `null`

doc/import_external_docs.ps1
GitHub Issue (If applicable): partially related to https://github.com/unoplatform/private/issues/504 (with additional latest docs fixes)
Update external documentation to the latest to fix broken links and add latest other doc fixes
=> docs: Update external documentation to latest

src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Out/TPXBRXLE/XamlCodeGenerator_MainPage_d6cd66944958ced0c513e0a04797b51d.cs, src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Out/TXBRXLE/XamlCodeGenerator_MainPage_d6cd66944958ced0c513e0a04797b51d.cs, src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_xLoad.cs, src/Uno.UI/UI/Xaml/Data/ElementNameSubject.cs
=> fix: Ensure deferred loaded elements are nulled out when unloaded

src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.cs, src/Uno.UI.RemoteControl/RemoteControlClient.cs, src/Uno.UI.Toolkit/Diagnostics/DiagnosticsOverlay.Context.cs, src/Uno.UI.Toolkit/Diagnostics/DiagnosticsOverlay.cs
linked https://github.com/unoplatform/uno.rider/issues/101
closes https://github.com/unoplatform/uno/issues/17836
This is the backport of https://github.com/unoplatform/uno/pull/17981
Fix indicator not showing in rider
When we create a new project using latest version of rider's plugin the dev-server is not started and port is not published to app. This drives the app to not even try to connect, causing the HR indicator to be stuck in an invalid state.
The indicator is read (until https://github.com/unoplatform/uno.rider/issues/101 is being fixed)
=> fix(hr): Fix indicator not showing in rider

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.skia.cs, src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml
GitHub Issue (If applicable): part of https://github.com/unoplatform/uno/issues/9063
- Bugfix
Our generic.xaml applies `MinWidth` and `MinHeight` in the default style
As per WinUI sources, `MinWidth` and `MinHeight` should only be applied to the border inside of the control, not as properties on the control directly. This way, setting 0 width and height should make the `TextBox` invisible. On the other hand, the default fluent text box style should apply these properties directly.
=> fix: `MinWidth` and `MinHeight` should not be applied by default on `TextBox`

src/Uno.UI.Runtime.Skia.Wpf/Rendering/OpenGLWpfRenderer.cs, src/Uno.UI.Runtime.Skia.Wpf/UI/Controls/UnoCompositeWindowHost.cs, src/Uno.UI.Runtime.Skia.Wpf/UI/Controls/UnoWpfWindow.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/18000
- Bugfix
WPF always chooses software renderer
Adjusted so that the OpenGL renderer initializes properly
=> fix: Ensure Renderer is initialized when HWND is already available

src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.Agent.cs, src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.PartialReload.cs, src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.cs
fixes https://github.com/unoplatform/uno/issues/18037
=> fix: Fix dev-server connection wrongly reported as failed

build/ci/.azure-devops-ios-tests.yml, src/SamplesApp/SamplesApp.netcoremobile/SamplesApp.netcoremobile.csproj, src/targetframework-override-netprevious.props, src/targetframework-override.props
- Bugfix
Trying to build and deploy Samples app via remote connected Mac ends with https://github.com/xamarin/xamarin-macios/issues/21093
- Using iOS 17.5 and Mac Catalyst 17.5.
- .NET iOS 17.5 includes the fix for https://github.com/xamarin/xamarin-macios/issues/21093
=> fix: Use ios17.5 and maccatalyst17.5 for SamplesApp

src/Uno.CrossTargetting.targets, src/Uno.UI/Runtime/BrowserPointerInputSource.wasm.cs, src/Uno.UI/UI/Xaml/UIElement.Pointers.cs
closes https://github.com/unoplatform/uno/issues/16928#issuecomment-2301899200
WASM Fix possible unrelted pointer entered
Browser raises unattended pointer over
We ignore such events
=> fix(pointers): WASM Fix possible unrelated pointer entered

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs
GitHub Issue (If applicable): closes #18040
=> fix(reg): Fix TextBox focus regression

src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault/ProgressRing_themeresources.xaml, src/Uno.UI.FluentTheme.v2/themeresources_v2.xaml, src/Uno.UI/Microsoft/UI/Xaml/Controls/ProgressRing/ProgressRing.xaml
GitHub Issue (If applicable): closes #18011
- Bugfix
The `ProgressRing` uses old styles to render with Fluent design.
The `ProgressRing` is matching the fluent style.
=> fix: Update `ProgressRing` styles to match WinUI

doc/articles/controls/WebView.md
GitHub Issue (If applicable): https://github.com/unoplatform/uno/discussions/17990
Currently this is a bit confusing between mac desktop and mac catalyst in WebView docs. 
=> docs: Specify macOS support for WebView2

doc/articles/guides/status-bar-theme-color.md
GitHub Issue (If applicable): internal discussion
Prompt users to use the StatusBar extension from Toolkit
=> docs: Add Tip for Toolkit StatusBar Extensions

doc/articles/uno-build-error-codes.md, src/Uno.Sdk/targets/Uno.Build.targets
Adjusts error message for global.json sdk version change, when visual studio or other enfironments may not have properly reloaded the solution.
=> fix: Adjust error message for global.json sdk version change

src/Uno.UI/WasmCSS/Uno.UI.css
GitHub Issue (If applicable): closes #17640
- Bugfix
Safari sometimes causes blank content to show up temporarily until a user action when scrolling, especially when the window is not active. See https://stackoverflow.com/q/9807620 for detailed discussion.
The issue is not Uno side - I have exported raw HTML of the state with blanked out content and after it appeared again and there was not actual difference, so it is all on the rendering side of the browser.
Applying `-webkit-transform3d` to the direct child of `ScrollContentPresenter` seems to resolve this issue, pending further testing. Setting this should not collide with `transform` set from managed code, where we set it directly on the individual elements.
Please check if your PR fulfills …
=> fix: Scrolling on WebKit randomly produces blank content temporarily

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Border.cs, src/Uno.UI/UI/Xaml/Controls/Border/Border.cs
GitHub Issue (If applicable): closes #1046
- Bugfix
Re-setting `Border.Child` to the same reference does not do anything.
Measure/Arrange are triggered on the `Child` as it is temporarily removed and re-added
=> fix: Ensure `Border.Child` is measured/arranged when reset

doc/articles/migrating-from-previous-releases.md
GitHub Issue: https://github.com/unoplatform/private/issues/504
Update migrating-from-previous-releases.md for older 4.1 migration notes to remove a link that does not exist anymore
=> docs: Update migrating-from-previous-releases.md for 4.1 migration notes by removing a non-working link

src/SamplesApp/UITests.Shared/Windows_System/LauncherTests.xaml, src/SamplesApp/UITests.Shared/Windows_System/LauncherTests.xaml.cs, src/Uno.UWP/System/Launcher.Android.SpecialUris.cs
GitHub Issue (If applicable): closes #18080
- Bugfix
The special Uri never launches correctly:
The intended Settings page is launched as the package name is provided:
=> fix: ActionAppNotificationSettings `Launcher` missing package reference

doc/import_external_docs.ps1
GitHub Issue (If applicable): related to https://github.com/unoplatform/private/issues/504
Update documentation to the latest including more fixes for broken links for https://github.com/unoplatform/private/issues/504 and more Uno Extensions documentation changes
=> docs: Update documentation to latest including more fixes for broken links

src/Uno.UI/UI/Xaml/Media/VisualTreeHelper.cs
GitHub Issue (If applicable): related to internal issue
- Bugfix
Throws NRE trying to access `VisualTree`
Throws `ArgumentNullException` to provide clarity that `XamlRoot` is required
=> feat: Throw `ArgumentNullException` if `XamlRoot` is not provided

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ItemsPresenter.cs, src/Uno.UI/UI/Xaml/Controls/ItemsControl/ItemsPresenter.cs, src/Uno.UI/UI/Xaml/Controls/ItemsStackPanel/ItemsStackPanel.cs, src/Uno.UI/UI/Xaml/Controls/ItemsWrapGrid/ItemsWrapGrid.cs, src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.cs, src/Uno.UI/UI/Xaml/UIElement.mux.cs
GitHub Issue (If applicable): https://github.com/unoplatform/kahua-private/issues/176
=> fix: Adjust ScrollContentPresenter measure to prevent infinite available size when necessary

doc/articles/features/windows-devices-geolocation.md
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/18152
Missing required permission for Android.
=> docs: Add Android platform specific for `RequestAccessAsync`

src/Uno.Sdk/Tasks/ImplicitPackagesResolver.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/18141
- Bugfix
Setting `MauiVersion` effectively changes the used version by the app.
=> fix: Ensure that MauiVersion override is always applied

doc/articles/features/unhandled-exceptions.md, src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs, src/Uno.Sdk/targets/Uno.Common.targets
- Feature
Previously the debugger break happened on `UnhandledException` by default.
The behavior is now opt-in, part of the Uno.Sdk
=> feat: Make breaking on unhandled exceptions opt-in

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Shapes/Given_Rectangle.cs, src/Uno.UI/UI/Xaml/Shapes/Shape.iOSmacOS.cs
Previously we have thrown Application.UnhandledException when an unsupported brush was used, even though we still had FallbackColorWithOpacity available
- Bugfix
`UnhandledException` is thrown when acrylic brush is used as `Fill` of a `Shape` on iOS
No exception
=> fix: Use `FallbackColor` for unsupported brushes on iOS

src/Uno.UI.RuntimeTests/Tests/Uno_Helpers/Given_DependencyPropertyHelper.cs, src/Uno.UI/UI/Xaml/DependencyObjectStore.cs, src/Uno.UI/UI/Xaml/Internal/DependencyPropertyHelper.cs
=> feat: New DependencyPropertyHelper class

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_UIElement.cs, src/Uno.UI/Extensions/ViewExtensions.Android.cs, src/Uno.UI/UI/Xaml/ILayouterElement.cs, src/Uno.UI/UI/Xaml/Media/VisualTreeHelper.cs, src/Uno.UI/UI/Xaml/UIElement.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/Uno.Gallery/issues/1167
=> fix(reg): Workaround Gallery measure issue on Android

doc/import_external_docs.ps1
When I updated the commit hashes for the documentation two weeks ago in this [PR](https://github.com/unoplatform/uno/pull/18110/files), I mistakenly used the latest commit hash for the workshops. However, I had previously left a comment in the related doc PR ([workshops PR #167](https://github.com/unoplatform/workshops/pull/167#issuecomment-2313616822)) to remind myself that these changes should only be released together with the upcoming MVUX updates.
This PR reverts to the previous commit hash for the workshops to ensure that the latest workshop changes are not pushed prematurely, and we maintain consistency with the release schedule for MVUX-related changes.
Please check if your PR fulfills the following …
=> docs: Revert to previous commit hash as latest workshops doc changes are not ready for release

src/Uno.UI.Runtime.Skia.MacOS/MacOSWindowHost.cs, src/Uno.UI.Runtime.Skia.MacOS/UnoNativeMac/UnoNativeMac/UNOMetalViewDelegate.m
https://github.com/ScottPlot/ScottPlot/issues/4257
- Bugfix
Metal-based rendering was using `Bgra888` and copying `Rgba888` memory surface into it is swapping the `R` and `B` channels.
Metal-based rendering was using `Rgba888`
=> fix: Use Rgba8888 for Skia/macOS/metal

build/ci/.azure-devops-publish-nuget-dev.yml, build/ci/.azure-devops-publish-nuget-prod-dev.yml, build/ci/.azure-devops-publish-nuget-prod.yml
Related to https://github.com/microsoft/azure-pipelines-tasks/issues/17207
=> ci: Apply workaround for https://github.com/microsoft/azure-pipelines-tasks/issues/17207

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ContentControl.cs, src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/17470
Conditionally disables `TemplatedParent` automatic propagation to specific properties when the `TemplatedParent` itself is already in the visual tree.
=> fix: Adjust ContentPresenter automatic propagation

src/Uno.UI/UI/Xaml/Documents/Hyperlink.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/18229
=> fix(hyperlink): clicking wasn't working on WASM

src/Uno.UI.RemoteControl.Server.Processors/HotReload/ServerHotReloadProcessor.cs, src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.ClientApi.cs, src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.Common.Status.cs, src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.cs, src/Uno.UI.RemoteControl/HotReload/Messages/UpdateFile.cs, src/Uno.UI.RuntimeTests/Tests/HotReload/Frame/HRApp/Tests/FrameworkElementExtensions.cs, src/Uno.UI.RuntimeTests/Tests/HotReload/Frame/HRApp/Tests/Given_TextBlock.cs, src/Uno.UI.RuntimeTests/Tests/HotReload/Frame/HRApp/Uno.UI.RuntimeTests.HRApp.Skia.Gtk.csproj
closes https://github.com/unoplatform/uno-private/issues/611
Add UpdateFile API
No easy / reliable way to update a file on the server and wait for HR
🙃
=> feat(hr): Add UpdateFile API

src/Uno.UI.RemoteControl.Server.Processors/HotReload/ServerHotReloadProcessor.cs, src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.ClientApi.cs, src/Uno.UI.RemoteControl/HotReload/Messages/UpdateFile.cs
Add ability to send null old content to overwrite file
We need to know the content of the file to update prior to update it
We can forcefully override the content
=> feat: Add ability to send null old content to overwrite file

src/Uno.Sdk/targets/Uno.SingleProject.WinAppSdk.targets
- Feature
No way to tell if app was build packaged/unpackaged
Two additional constants defined.
=> feat: Define constants for packaged vs. unpackaged WinAppSDK

src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/Renderer.cs, src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/UI/FrameBufferWindowWrapper.cs, src/Uno.UI/UI/Xaml/Window/Native/NativeWindowWrapperBase.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/672
- Bugfix
Restores the use of the Window after https://github.com/unoplatform/uno/pull/16535, adds a debug message when the top-level XamlRoot is not available to render frames.
=> fix(fb): Ensure that FB has a Window to render to

src/SolutionTemplate/5.2/uno52AppWithLib/uno52AppWithLib/uno52AppWithLib.csproj, src/SolutionTemplate/5.3/uno53net9blank/uno53net9blank/uno53net9blank.csproj, src/Uno.Sdk/targets/Uno.Common.Wasm.targets
- Bugfix
Adjust for net9 publishing of wwwroot assets.
=> fix: Ensure wwwroot assets are copied properly

src/Uno.UI.Runtime.Skia.X11/X11PointerInputSource.cs
closes https://github.com/unoplatform/uno-private/issues/519
closes https://github.com/unoplatform/uno-private/issues/633
Fix pointer events timestamp being in ms instead of ticks on X11
Pointer events timestamp is in ms instead of ticks on X11, causing the inertia processor to start with a crazy speed
🙃
This PR deprecates https://github.com/unoplatform/uno/pull/18187
=> fix: Fix pointer events timestamp being in ms instead of ticks on X11

doc/articles/create-an-app-rider.md, doc/articles/features/working-with-xaml-hot-reload.md, doc/articles/migrating-from-previous-releases.md
Related to https://github.com/unoplatform/private/issues/519
- Fix details for 5.4 Migration documentation
- Remove the "preview" term in the documentation in regard to Rider plugin
- Fix HotReload Tab content issues for the Troubleshooting section
https://github.com/user-attachments/assets/8f3c3a69-baf8-479e-b58b-c99c3dafc04a
=> docs: Miscellaneous documentation fixes

src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Out/TDBMIDTIRD/XamlCodeGenerator_MyResourceDictionary_92716e07ff456818f6d4125e055d4d57.cs, src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- Bugfix
Not prefixed
Prefixed
=> fix: Prefix type in `x:Bind` codegen with `global::`

src/SamplesApp/SamplesApp.UITests/SamplesApp.UITests.csproj
- Bugfix
When targeting .NET 8 tfm override VS complains that the project targets .NET 9
Adjusted.
=> fix: Avoid TFM error on SamplesApp.UITests

src/Uno.UI/UI/Xaml/Controls/Popup/PopupPanel.cs
closes #17656
- Bugfix
App freezes when moving slider with tooltip
Avoid freeze by ignoring extra ArrangeElement from a workaround added for an Android case
=> fix: adjust workaround for android popuppanel layout

src/Uno.UI/UI/Xaml/Controls/ItemsControl/ItemsPresenter.cs, src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.cs, src/Uno.UI/UI/Xaml/FrameworkElement.Layout.crossruntime.cs, src/Uno.UI/UI/Xaml/UIElement.Layout.crossruntime.cs, src/Uno.UI/UI/Xaml/UIElement.mux.cs
GitHub Issue (If applicable): Part of https://github.com/unoplatform/kahua-private/issues/205
=> fix: Port "non-clipping subtree" logic from WinUI

src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Controls/SampleChooserControl.xaml
- Other... Please describe: sample app & ci screenshot tests improvement
In the SampleApp's top bar, there is a more `...` button that contains a background transition. It seems to affect screenshot comparison tests result in unintended way.
Said button style was changed to avoid such problem.
=> test: remove sampleapp more button's transition

src/Uno.Sdk/targets/Uno.Common.targets, src/Uno.Sdk/targets/Uno.Implicit.Packages.ProjectSystem.targets, src/Uno.Sdk/targets/Uno.SingleProject.Desktop.targets
- closes #17719
- Bugfix
We limit the WinEXE Output Type to when we are building a release
We always use WinEXE for the Output Type of the Desktop Target for an Uno Head project.
cc: @jeromelaban
=> Adjust devserver inclusion when WinExe is selected

src/Uno.Foundation/Uno.Core.Extensions/Uno.Core.Extensions.Compatibility/Threading/AsyncLock.cs, src/Uno.UI.RemoteControl.Server.Processors/HotReload/ServerHotReloadProcessor.cs, src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.ClientApi.cs, src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.Common.Status.cs, src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.MetadataUpdate.cs, src/Uno.UI.Toolkit/Uno.UI.Toolkit.Windows.csproj
Fix UpdateFileAsync requesting HR before VS detects file change
HR is requested before VS detects file update
We wait hopefully long enough after file change to trigger HR on VS, *AND* if a no-changes is reported, we re-trigger a second HR on VS.
=> fix: Fix UpdateFileAsync requesting HR before VS detects file change

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Button.cs, src/Uno.UI/UI/Xaml/Controls/Primitives/ButtonBase/ButtonBase.mux.cs
GitHub Issue (If applicable): closes unoplatform/kahua-private#199
- Bugfix
If Button::Command binding produces an ICommand value that throws Exception in its CanExecute, this value will be canceled and replaced by the Binding::FallbackValue. This does not happen on windows.
^ should not happen anymore.
=> fix(Button): Command binding resetting on CanExecution exception

src/SamplesApp/UITests.Shared/Microsoft_UI_Windowing/SingleWindowClose.xaml, src/SamplesApp/UITests.Shared/Microsoft_UI_Windowing/SingleWindowClose.xaml.cs, src/SamplesApp/UITests.Shared/UITests.Shared.projitems, src/Uno.UI/UI/Xaml/Window/Implementations/BaseWindowImplementation.cs
GitHub Issue (If applicable): closes #18325, closes https://github.com/unoplatform/kahua-private/issues/213
- Bugfix
=> fix: Do not destroy the singleton Window for single-window targets

build/test-scripts/run-netcore-mobile-template-tests.ps1, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_UIElement.cs, src/Uno.UI/Extensions/ViewExtensions.Android.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.Android.cs, src/Uno.UI/UI/Xaml/ILayouterElement.cs, src/Uno.UI/UI/Xaml/Media/VisualTreeHelper.cs, src/Uno.UI/UI/Xaml/UIElement.cs
Backport #18193 and #18377 for android layout issues
=> Backport #18193 and #18377

src/Directory.Build.props, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_UIElement.cs, src/Uno.UI/Extensions/ViewExtensions.Android.cs, src/Uno.UI/UI/Xaml/DependencyObjectStore.cs, src/Uno.UI/UI/Xaml/ILayouterElement.cs, src/Uno.UI/UI/Xaml/Media/VisualTreeHelper.cs, src/Uno.UI/UI/Xaml/UIElement.cs
Related to https://github.com/unoplatform/uno/pull/18381, https://github.com/unoplatform/uno/pull/18193 and https://github.com/unoplatform/uno/pull/18377
=> Revert #18381 for layout android issues

build/PackageDiffIgnore.xml, src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.MetadataUpdate.cs, src/Uno.UI.RemoteControl/HotReload/HotReloadStatusView.cs, src/Uno.UI.RuntimeTests/Tests/HotReload/Frame/HRApp/Tests/Given_Frame.cs, src/Uno.UI.RuntimeTests/Tests/HotReload/Frame/HRApp/Tests/Given_TextBlock.cs, src/Uno.UI/Helpers/TypeMappings.cs
HotReload was waiting for _Type Mappings_ to be resumed to know if changes should be applied or not. That feature has been removed because it was deadlocking with the possibility to pause type mappings while sending a file update from the client app.
=> Removed the waiting for TypeMappings to be resumed during HR

src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.cs
- Bugfix
When tests are run manually, the last input type would be dependent on whether the user uses touch, mouse, or keyboard to execute the button.
Always consistent
=> fix: Reset last input type before test execution

doc/import_external_docs.ps1
Update extensions docs with latest changes:
- [docs: fix MVUX dead links (backport 2581)](https://github.com/unoplatform/uno.extensions/pull/2592)
- [docs: Note on VisualStateGroup.StateTriggers usage (backport 2580)](https://github.com/unoplatform/uno.extensions/pull/2593)
- [docs: Reactive FeedView updates (backport 2577)](https://github.com/unoplatform/uno.extensions/pull/2594)
=> docs: Update extensions docs with latest changes

src/Uno.UI/UI/Xaml/Controls/Grid/Grid.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/17997, closes https://github.com/unoplatform/uno/issues/14013
- Bugfix
Focusing a text input on iOS causes the framework to temporarily add a non-UIElement child to the parent's `Grid`, which is then surfaced to the `Grid` as a `null`
No longer crashing. This is a workaround, ideally we would want to ensure that `Children` as a `UIElementCollection` only reflects the actual `UIElements` in the `ChildrenShadow`. This however means more complex logic to properly handle indexes, etc. This workaround seems to be sufficient for now to handle the cases we encountered. Created https://github.com/unoplatform/uno/issues/18474 to track this
Please check if your PR fulfills the …
=> fix: Workaround non-UIElement UIViews in Grid layout

doc/articles/controls/CommandBar.md, doc/articles/features/native-frame-nav.md
GitHub Issue (If applicable): closes #18494
minor typo
^ no more
=> docs: simple typo fix

src/Uno.UI.Runtime.Skia.Gtk/Uno.UI.Runtime.Skia.Gtk.csproj, src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/Uno.UI.Runtime.Skia.Linux.FrameBuffer.csproj, src/Uno.UI.Runtime.Skia.MacOS/Uno.UI.Runtime.Skia.MacOS.csproj, src/Uno.UI.Runtime.Skia.Wpf/Uno.UI.Runtime.Skia.Wpf.csproj, src/Uno.UI.Runtime.Skia.X11/Uno.UI.Runtime.Skia.X11.csproj
@jeromelaban I noticed SkiaSharp.Views being a dependenct in the wpf runtime project. It doesn't seem to be necessary at all. Can we remove it?
=> chore: remove SkiaSharp.HarfBuzz and SkiaSharp.Views dependencies when unnecessary

doc/articles/uno-build-error-codes.md, src/Uno.Sdk/targets/Uno.Sdk.After.targets
- Bugfix
In VS 17.12, only reload projects from/to browserwasm target. Other targets support reordering properly, except for desktop which needs still be first for the WSL debugger to be enabled, only when mobile targets are also present.
=> fix: Adjust tf reordering for VS 17.12 or later

src/Uno.UI.RemoteControl.VS/EntryPoint.cs, src/Uno.UI.RemoteControl.VS/IDEChannel/IDEChannelClient.cs
GitHub Issue (If applicable): closes: #18448
We have several messages and events on the IDEChannelClient.
Now we only have one, and the messages are being handled by the EntryPoint.
=> IDE Channel Client: Have a generic OnMessageReceived 

src/Uno.UWP/Web/Http/HttpRequestMessage.cs
- Bugfix
A `NullReferenceException` occurs when setting headers when the default constructor of `HttpRequestMessage` is used.
`Headers` is initialized for the default constructor. Also avoid allocating a `HttpMethod` for each instance since we can reuse the one from `HttpMethod.Get`
Partial for for SampleApp's `Webview[2]_WithHeaders` tests
https://github.com/unoplatform/uno-private/issues/479
=> fix: Ensure HttpRequestMessage.Headers are assigned when default ctor is used

src/Uno.UI.RuntimeTests/Tests/Microsoft_UI_Xaml_Controls/Given_TabView.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/TabView/TabView.cs, src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.managed.cs, src/Uno.UI/UI/Xaml/Controls/Primitives/Selector.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/ziidms-private/issues/23
- Bugfix
Using TabView with bound items and changing the SelectedItem is causing the TabView Tabs to display incorrectly.
=> fix(ios): Tabview Selection when Bindings items

src/SourceGenerators/Uno.UI.Tasks/Content/Uno.UI.Tasks.targets, src/SourceGenerators/Uno.UI.Tasks/LinkerHintsGenerator/LinkerHintGeneratorTask.cs
- Bugfix
Align linker hints generation parameters for net9, ensuring that linker descriptors are passed to the xaml trimming tooling.
=> fix: Align trimming with net9 options

src/Uno.Sdk/Sdk/Sdk.targets, src/Uno.Sdk/targets/Uno.PropertyCaptures.targets
=> chore(sdk): Add ApplicationVersion capture

src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/CommandBar_Native_With_AppBarButton_Binding.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ContentControlTestsControl/ContentControl_ComboBoxSetNull.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/FlipView/FlipView_Background.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_DataContext_Reference.xaml.cs
related to https://github.com/unoplatform/uno/issues/16953
Some ManualTests in the SampleApp are missing descriptions.
=> test: add manual tests descriptions

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Data/Given_CollectionView.cs, src/Uno.UI.Tests/Windows_UI_XAML_Controls/ItemsControlTests/Given_ItemsControl.cs, src/Uno.UI/UI/Xaml/Data/CollectionView.cs, src/Uno.UI/UI/Xaml/Data/CollectionViewSource.cs
- Bugfix
Grouped collection view does not enumerate correctly in some scenarios
Enumeration works
=> Grouped `CollectionView` enumeration

src/Uno.UI.RuntimeTests/Tests/Microsoft_UI_Xaml_Controls/Given_NumberBox.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/NumberBox/NumberBox.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/18308
- Bugfix
NumberFormatter is not working on a number of platforms. The methods are not properly called. 
The behavior is brought closer to WinUI3 source, which fixes the issue. Source for reference https://github.com/microsoft/microsoft-ui-xaml/blob/f31293f4227cd3b4f7c151106528b8e1367bda11/src/controls/dev/NumberBox/NumberBox.cpp#L496
=> fix: Ensure Custom NumberFormatter is applied in `NumberBox` validation

doc/articles/features/svg.md
GitHub Issue (If applicable): related issue: #18418
=> docs: fix path for single proj

src/Directory.Build.targets
- Bugfix
- Feature
Ensure that Microsoft.Win32.SystemEvents dependency uses the right version with net9.
=> fix: Adjust Microsoft.Win32.SystemEvents dependency for net9

src/Uno.Sdk/targets/Uno.ProjectCapabilities.targets
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/18577
- Bugfix
Restores the publish under when ios/android/catalyst are not present. If present, the VS issue is still active.
=> fix: Restore publish menu for some scenarios

src/Uno.UI.RemoteControl.Messaging/IDEChannel/CommandRequestIdeMessage.cs
related to #18591
- Feature
The name of the message is WindowId
message was WindowId and now ProcessID.
=> Settings app opening on top - Change to ProcessID for message

src/Uno.UI.RemoteControl.Messaging/IDEChannel/CommandRequestIdeMessage.cs, src/Uno.UI.RemoteControl.VS/Commands/UnoMenuCommand.cs, src/Uno.UI.RemoteControl.VS/EntryPoint.cs
Related to [PR](https://github.com/unoplatform/uno.licensing/pull/163/files) 
Before, this is a extra change. 
https://github.com/unoplatform/uno/pull/18592
- Feature
We are passing the MainWindowHandle as int64
Now we are passing the ProcessID
=> Settings app opening on top - Change to ProcessID

doc/articles/uno-community-toolkit-v8.md
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/18215
=> chore: Bump WCT versions

src/Uno.UI.Runtime.Skia.X11/X11WindowWrapper.cs
GitHub Issue (If applicable): #18620
=> fix(x11): Window.Activate() should immediately raise the window

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ContentDialog.cs, src/Uno.UI/UI/Xaml/Controls/ContentDialog/ContentDialog.cs
GitHub Issue (If applicable): closes #18609
- Bugfix
Cancelling the click handler prevents `Hide()`
After cancelling click handler, it is possible to still `Hide()`
=> fix: Closing `ContentDialog` after event cancellation

src/Uno.UI.Runtime.Skia.MacOS/MacOSWindowWrapper.cs, src/Uno.UI.Runtime.Skia.MacOS/NativeUno.cs, src/Uno.UI.Runtime.Skia.MacOS/UnoNativeMac/UnoNativeMac/UNOWindow.h, src/Uno.UI.Runtime.Skia.MacOS/UnoNativeMac/UnoNativeMac/UNOWindow.m
Partial (macOS) fix for https://github.com/unoplatform/uno/issues/18620
- Bugfix
Calling `Window.Activate` does not bring the window on top of other windows in the desktop.
Calling `Window.Activate` brings the window to the top.
=> fix(macos): Bring window to top when activated

src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/WebView2Tests/WebView2_WithHeaders.xaml, src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/WebView2Tests/WebView2_WithHeaders.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/WebView/WebView_WithHeaders.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/WebView/WebView_WithHeaders.xaml.cs
- Other... Please describe: Test update
The site `requestb.in` has been updated (and renamed) and now requires an account and authentication, which is not very test friendly.
The tests also required additional manual steps to confirm the results were valid.
Now using `httpbin.org` which works unauthenticated and also sends back the request so we can detect, in code, if the custom headers are correct.
https://github.com/unoplatform/uno-private/issues/479
=> chore: Update WebView[2]_WithHeaders tests to use httpbin.org

src/Uno.UI.Runtime.Skia.MacOS/MacOSWindowHost.cs, src/Uno.UI.Runtime.Skia.MacOS/MacOSWindowWrapper.cs, src/Uno.UI.Runtime.Skia.MacOS/NativeUno.cs, src/Uno.UI.Runtime.Skia.MacOS/UnoNativeMac/UnoNativeMac/UNOWindow.h, src/Uno.UI.Runtime.Skia.MacOS/UnoNativeMac/UnoNativeMac/UNOWindow.m, src/Uno.UI.RuntimeTests/Tests/Microsoft_UI_Windowing/Given_AppWindow.cs
GitHub Issue (If applicable): closes #18638
- Feature
`netXX-desktop` does not support AppWindow positioning and sizing for macOS
`netXX-desktop` now support AppWindow positioning and sizing on macOS
New user API are using physical, not logical, pixels as mentioned in https://github.com/unoplatform/uno/issues/18638
=> feat(macOS): Add AppWindow positioning and sizing support

src/SourceGenerators/Uno.UI.SourceGenerators/BindableTypeProviders/BindableTypeProvidersGenerationTask.cs
=> fix: Fix regression in XAML Trimming

build/PackageDiffIgnore.xml, src/Uno.Foundation/Diagnostics/DiagnosticViewRegistry.cs, src/Uno.Foundation/Diagnostics/IDiagnosticView.cs, src/Uno.UI.RemoteControl/RemoteControlClient.cs, src/Uno.UI.RemoteControl/RemoteControlStatus.cs, src/Uno.UI.Toolkit/Diagnostics/DiagnosticsOverlay.cs, src/Uno.UI/Diagnostics/DiagnosticView.Factories.cs, src/Uno.UI/Diagnostics/DiagnosticView.TView.TState.cs, src/Uno.UI/Diagnostics/DiagnosticView.TView.cs, src/Uno.UI/Diagnostics/DiagnosticView.cs, src/Uno.UI/Diagnostics/DiagnosticViewManager.TView.TState.cs
Added the ability to specify a positionning to the item being registered to the Diagnostic View Overlay.
=> DiagnosticView Ordering

src/Uno.Sdk/packages.json, src/Uno.Sdk/targets/Uno.SingleProject.Wasm.targets
- Bugfix
Fixes the ability to disable the PWA manifest
=> fix: Don't include non-existing pwa manifest

src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.skia.cs
- Bugfix
`Copy` and `Select All` requires the use of `Control`, instead of `Command`, on `TextBlock`s
Using the _expected_ `Command` will simply have the Mac beep.
`Copy` and `Select All` now use `Command` on `TextBlock`s.
This match what the `TextBox` is already doing on macOS/skia.
=> fix(textblock): Use the correct Command+C|A for copy/select all on macOS/skia

src/Uno.UI.Runtime.Skia.Wpf/UI/Controls/WpfWindowWrapper.cs, src/Uno.UI/UI/Xaml/Window/Native/NativeWindowWrapperBase.cs
GitHub Issue (If applicable): part of #18638
- Bugfix]
=> fix: Ensure WPF adheres to physical `Position` and `Size` on `AppWindow`

doc/articles/features/dialogs.md
updated the link-address to be now working as expected
- Bugfix
Link directs to no where, not useable
fixed the Link-Address to the official wiki to HowTo-ShowDialog on plattform.uno, checked functionallity, works on my side
- [ x ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ x ] Contains **NO** breaking changes
- [ x ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.
Marked as …
=> docs(dialogs): Fixed Link in dialogs.md documenation: Link to HowTo-ShowDialog was broken

src/Uno.UI/UI/Xaml/Window/Native/NativeWindowWrapper.Android.cs, src/Uno.UI/UI/Xaml/Window/Native/NativeWindowWrapper.iOS.cs, src/Uno.UI/UI/Xaml/Window/Native/NativeWindowWrapper.unittests.cs, src/Uno.UI/UI/Xaml/Window/Native/NativeWindowWrapper.wasm.cs
=> fix: `AppWindow` on non-Skia targets should use physical units

src/Uno.UI.RemoteControl.Host/Extensibility/AddInsExtensions.cs, src/Uno.UI.RemoteControl.Host/Extensibility/Uno.Utils.DependencyInjection/ServiceAttribute.cs, src/Uno.UI.RemoteControl.Host/Extensibility/Uno.Utils.DependencyInjection/ServiceCollectionExtensionAttribute.cs, src/Uno.UI.RemoteControl.Host/Extensibility/Uno.Utils.DependencyInjection/ServiceCollectionServiceExtensions.cs, src/Uno.UI.RemoteControl.Host/Helpers/AssemblyHelper.cs, src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.ClientApi.cs, src/Uno.UI.RemoteControl/RemoteControlStatus.cs
Enhance support of add-ins in dev-server
* We throw if we fail to load an add-in assembly
* All services has to be explicitly exposed using the `ServiceAttribute`
* We only log if the load of an add-in fails (improve stability of the dev-server and user experience)
* Add-ins are able to get complete access to the `IServiceCollection` to register their services.
=> feat: Dev-server add-in improvements

src/Uno.UI.RemoteControl/RemoteControlClient.cs, src/Uno.UI.RemoteControl/RemoteControlStatus.cs
The first ping to dev server was done 30 seconds after the connection. Since some checks are only done during ping response, it was causing potential unwanted delay.
An initial ping is sent immediately after the connection has been established.
=> Improved the way pings are done to the remote control / dev server

src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Out/TDBMIDTIRD/XamlCodeGenerator_MyResourceDictionary_92716e07ff456818f6d4125e055d4d57.cs, src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs, src/Uno.UI.RuntimeTests/Tests/BindingTests/BindingTests.cs, src/Uno.UI.RuntimeTests/Tests/BindingTests/XBindConstControl.xaml, src/Uno.UI.RuntimeTests/Tests/BindingTests/XBindConstControl.xaml.cs, src/Uno.UI.RuntimeTests/Tests/BindingTests/XBindConstPage.xaml, src/Uno.UI.RuntimeTests/Tests/BindingTests/XBindConstPage.xaml.cs
GitHub Issue (If applicable): closes #18404
- Bugfix
=> fix: Apply `x:Bind` expressions in control template

src/SamplesApp/SamplesApp.Shared/App.Tests.cs, src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.cs, src/Uno.UI.Runtime.Skia.Gtk/UI/Controls/GtkWindowWrapper.cs, src/Uno.UI.Runtime.Skia.MacOS/MacOSWindowWrapper.cs, src/Uno.UI.Runtime.Skia.Wpf/UI/Controls/WpfWindowWrapper.cs, src/Uno.UI.Runtime.Skia.X11/X11WindowWrapper.cs, src/Uno.UI/UI/Xaml/Window/Implementations/BaseWindowImplementation.cs, src/Uno.UI/UI/Xaml/Window/Native/INativeWindowWrapper.cs, src/Uno.UI/UI/Xaml/Window/Native/NativeWindowWrapper.iOS.cs, src/Uno.UI/UI/Xaml/Window/Native/NativeWindowWrapper.wasm.cs, src/Uno.UI/UI/Xaml/Window/Native/NativeWindowWrapperBase.cs, src/Uno.UWP/Generated/3.0.0.0/Microsoft.UI.Windowing/AppWindow.cs, src/Uno.UWP/Microsoft/UI/Windowing/AppWindow.cs
GitHub Issue (If applicable): closes #18620
- Bugfix
Activate does not actually activate the window if not shown yet.
Activated.
=> fix: Always activate window on `Activate()`

src/Uno.UI.Runtime.Skia.MacOS/UnoNativeMac/UnoNativeMac/UNOWindow.m
GitHub Issue (If applicable): closes #16400
- Bugfix
Normal (PC) mouse does not send as much events when the scroll wheel is used, making it appear slow.
Detect when a high precision mouse is used and, if not, multiply the scrolling delta. This makes up for the lower number of events being generated.
=> fix(macOS): adjust scrollwheel speed for normal/PC mouses

src/Uno.Sdk/targets/Uno.Build.targets, src/Uno.UI.RemoteControl.Host/Extensibility/AddIns.cs, src/Uno.UI.RemoteControl/buildTransitive/Uno.WinUI.DevServer.targets
closes https://github.com/unoplatform/uno/issues/18732
Use temp file for AddIn discovery instead of output parsing
We rely on some XML like tags in build output to discover add-ins
We now dump values in a temp file that we read at the end of the build. This makes sure we are not impacted by encoding issues in output.
=> fix: Use temp file for AddIn discovery instead of output parsing

src/Uno.UI/UI/Xaml/Controls/WebView/Native/iOSmacOS/UnoWKWebView.iOSmacOS.cs, src/Uno.UWP/ApplicationModel/Calls/PhoneCallManager.iOS.cs, src/Uno.UWP/System/Launcher.iOS.SpecialUris.cs, src/Uno.UWP/System/Launcher.iOSmacOS.cs
GitHub Issue (If applicable): closes #18621
- Bugfix
=> fix: Deprecated iOS `Launcher` methods

build/cSpell.json, doc/articles/features/windows-ui-storecontext.md, doc/articles/toc.yml
GitHub Issue (If applicable): closes #18583 
=> docs: Add in Store Context page

src/Uno.UI.RemoteControl.Host/RemoteControlServer.cs, src/Uno.UI.RemoteControl/RemoteControlClient.Status.cs
Add support for multi server processors discovery frames
=> fix: Fix the discovered processor list additive

src/Uno.UI.RemoteControl.VS/EntryPoint.cs
Avoid duplicated logs and prevent error bubbling
* Errors might logged twice
* Once logged, error are re-thrown driving to unknown behavior
* Errors logged only once
* Once logged, errors are discarded
=> chore: Avoid duplicated logs and prevent error bubbling

src/SamplesApp/UITests.Shared/UITests.Shared.projitems, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/Image_ScrollView_ChangeView.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/Image_ScrollView_ChangeView.xaml.cs
related to https://github.com/unoplatform/uno/issues/2618
- Other... Please describe: Manual test
=> test: Image inside scroll manual test

src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault/TabView.xaml, src/Uno.UI.FluentTheme.v2/themeresources_v2.xaml, src/Uno.UI.RuntimeTests/Tests/Microsoft_UI_Xaml_Controls/Given_TabView.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/ziidms-private/issues/31
- Bugfix
TabView header not showing on Android.
=> fix(droid): TabView header not showing

build/test-scripts/run-net7-template-linux.ps1, build/test-scripts/run-netcore-mobile-template-tests.ps1, src/SolutionTemplate/5.3/uno53net9Lib/Class1.cs, src/SolutionTemplate/5.3/uno53net9Lib/global.json, src/SolutionTemplate/5.3/uno53net9Lib/uno53net9Lib.csproj, src/Uno.Sdk/targets/Uno.Common.Wasm.targets
Related to https://github.com/dotnet/runtime/pull/109866
=> fix(wasm): workaround for invalid net9-browserwasm library detection

build/PackageDiffIgnore.xml, build/Uno.UI.Build.csproj
GitHub Issue (If applicable): https://github.com/unoplatform/uno/pull/18613 build
=> build: Update PackageDiff

src/Uno.UI.Runtime.Skia.MacOS/README.md
Building the native dylib for Mac needs an extra step - the build instruction mentions this but on a different page. 
This change highlights a bit what needs to be done before building succeeds.
=> doc: Add info how to get libSkiaSharp.dylib

build/test-scripts/wasm-run-automated-uitests.sh
=> test: Remove test-related workaround

src/Uno.Sdk/targets/Uno.Extensions.Implicit.Packages.ProjectSystem.targets, src/Uno.Sdk/targets/Uno.Implicit.Packages.ProjectSystem.targets
Also found a probable typo
GitHub Issue (If applicable): closes #18700
You have to add the NuGet package manually
It adds it automatically to the main project
- [x [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
Number of tests passed and failed didn't change
Internal Issue (If applicable): #18700
=> fix(implicit packages):Adding MAUI and C# markup packages when enabled

src/SamplesApp/UITests.Shared/UITests.Shared.projitems, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Input/Keyboard/Keyboard_Modifiers.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Input/Keyboard/Keyboard_Modifiers.xaml.cs, src/Uno.UI/ts/WindowManager.ts, src/Uno.UWP/UI/Core/Internal/KeyboardStateTracker.cs
GitHub Issue (If applicable): closes #18617
=> fix(wasm): key tracking when no one is subscribing to Key<Down|Up>

build/test-scripts/run-netcore-mobile-template-tests.ps1, src/Uno.Sdk/Sdk/Sdk.targets, src/Uno.Sdk/targets/Uno.Wasm.UnsupportedRid.targets
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/18796
- Bugfix
Ensures that nuget targets can still be called when a RID is not matching wasm.
=> fix(net9): Allow for builds to happen even if a RID is explicitly set

src/SourceGenerators/Uno.UI.Tasks/Content/Uno.UI.Tasks.targets, src/SourceGenerators/Uno.UI.Tasks/ResourcesGenerator/UpriSubstitutionsGeneratorTask.cs, src/Uno.UI/Uno.UI.Skia.csproj, src/Uno.UI/Uno.UI.Wasm.csproj
=> feat: Add XAML resources UPRI trimming

doc/articles/features/windows-ui-markup-extensions.md
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/18493
=> docs: Adjust MarkupExtension sample

src/Uno.UI.Composition/Composition/CompositionGeometricClip.skia.cs, src/Uno.UI.Composition/Composition/CompositionSpriteShape.skia.cs, src/Uno.UI.Composition/Composition/SkiaGeometrySource2D.skia.cs, src/Uno.UI.RuntimeTests/Helpers/ImageAssert.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Shapes/Given_Path.cs, src/Uno.UI/UI/Xaml/Media/Geometry.skia.cs, src/Uno.UI/UI/Xaml/Media/PathGeometry.skia.cs, src/Uno.UI/UI/Xaml/Shapes/Path.skia.cs, src/Uno.UI/UI/Xaml/Shapes/Shape.layout.crossruntime.cs, src/Uno.UI/UI/Xaml/Shapes/Shape.skia.cs
GitHub Issue (If applicable): closes #18694
=> fix(Path): add support for Path.Data being a PathGeometry with some Figures having IsFilled = false

src/Uno.UI.Toolkit/Diagnostics/DiagnosticsOverlay.cs
closes https://github.com/unoplatform/ziidms-private/issues/15
HRI not draggable on Android
Transform is not applied because the `DiagnosticOverlay` is `ActualWidth = 0`.
We force an invalidation of the `DiagnosticOverlay` to force re-computation of the `ActualSize`, driving the `RanderTransform` to be applied properly
=> fix: Fix HRI not being draggable

src/Uno.UI.Runtime.Skia.Wpf/Extensions/WpfDragDropExtension.cs, src/Uno.UI.Runtime.Skia.X11/X11DragDropExtension.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_UIElement.cs, src/Uno.UI/UI/Xaml/DragDrop/DragDropExtension.macOS.cs, src/Uno.UI/UI/Xaml/DragDrop/DragDropManager.cs, src/Uno.UI/UI/Xaml/DragDrop/DragOperation.cs, src/Uno.UI/UI/Xaml/UIElement.Pointers.cs, src/Uno.UWP/ApplicationModel/DataTransfer/DragDrop/Core/CoreDragDropManager.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/18770
=> fix(dragdrop): don't fire Drop if AcceptedOperation is None

src/SamplesApp/SamplesApp.Shared/App.xaml.cs, src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.cs, src/Uno.UI.RuntimeTests/IntegrationTests/common/CalendarHelper.h.cs, src/Uno.UI.RuntimeTests/IntegrationTests/dxaml/Event.cs, src/Uno.UI.RuntimeTests/MUX/Helpers/EventTester.cs, src/Uno.UI.RuntimeTests/MUX/Utilities/TestHelpers.cs, src/Uno.UI.RuntimeTests/Tests/UnitTestsTests/Given_UnitTest.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Image.cs, src/Uno.UI/FeatureConfiguration.cs, src/Uno.UI/UI/Xaml/Controls/AppBar/AppBar.Partial.cs, src/Uno.UI/UI/Xaml/DependencyObjectStore.cs, src/Uno.UI/UI/Xaml/UIElementCollection.cs, src/Uno.UI/UI/Xaml/Window/Implementations/BaseWindowImplementation.cs, src/Uno.UWP/Buffers/DefaultArrayPoolBucket.cs, src/Uno.UWP/UI/Core/Internal/KeyboardStateTracker.cs
GitHub Issue (If applicable): closes #18715
=> Make skia runtime tests green locally on Debug

src/Uno.Sdk/packages.json
GitHub Issue (If applicable): part of https://github.com/unoplatform/uno/issues/18840
- Bugfix
The latest version of Build Tools is unsupported by Microsoft Store and block users from publishing their apps
Downgraded until support is added
=> fix: Downgrade BuildTools

src/Uno.UI/UI/Xaml/Window/WindowManagerInterop.wasm.cs, src/Uno.UI/ts/WindowManager.ts
- Bugfix
Move to jsimport for getBBox to improve wasm performance
=> fix: Move to jsimport for bbox

src/SamplesApp/SamplesApp.Shared/App.xaml.cs, src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.cs, src/Uno.UI.RuntimeTests/IntegrationTests/common/CalendarHelper.h.cs, src/Uno.UI.RuntimeTests/IntegrationTests/dxaml/Event.cs, src/Uno.UI.RuntimeTests/MUX/Helpers/EventTester.cs, src/Uno.UI.RuntimeTests/MUX/Utilities/TestHelpers.cs, src/Uno.UI.RuntimeTests/Tests/UnitTestsTests/Given_UnitTest.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Image.cs, src/Uno.UI/FeatureConfiguration.cs, src/Uno.UI/UI/Xaml/Controls/AppBar/AppBar.Partial.cs, src/Uno.UI/UI/Xaml/DependencyObjectStore.cs, src/Uno.UI/UI/Xaml/UIElementCollection.cs, src/Uno.UI/UI/Xaml/Window/Implementations/BaseWindowImplementation.cs, src/Uno.UWP/Buffers/DefaultArrayPoolBucket.cs, src/Uno.UWP/UI/Core/Internal/KeyboardStateTracker.cs
Reverts unoplatform/uno#18659, as it causes performance regressions: https://github.com/unoplatform/uno/issues/18908
=> chore: Revert "Make skia runtime tests green locally on Debug"

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_DependencyObjectCollection.cs, src/Uno.UI/UI/Xaml/DependencyObjectCollection.cs
This change avoids the high cost of multicast delegates, particularly on mono-AOT environments. ~We also do not need the thread safety guarantees~.
Example:
=> perf: Don't use multicast delegates for DependencyObjectCollection.VectorChanged

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_UIElement.cs, src/Uno.UI/UI/Xaml/Input/PointerRoutedEventArgs.Android.cs, src/Uno.UI/UI/Xaml/UIElement.Pointers.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/brain-products-private/issues/7
=> fix(dragdrop): fire DragEnter and DragOver when firing DragStarting

src/Uno.UI.Runtime.Skia.X11/X11DisplayInformationExtension.cs, src/Uno.UI.Runtime.Skia.X11/X11OpenGLRenderer.cs, src/Uno.UI.Runtime.Skia.X11/X11SoftwareRenderer.cs
GitHub Issue (If applicable): closes #18884
=> fix(x11): fix rendering when DPI scaling is less than 1

src/Uno.UI.Runtime.Skia.MacOS/UnoNativeMac/UnoNativeMac/UNOWindow.m
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno.hotdesign/issues/3010
=> fix(macos): add key modifiers to pointer event args

src/Uno.UI/Controls/RootViewController.iOS.cs
GitHub Issue (If applicable): closes #17529
=> feat: Listen to trait changes on iOS 17+

src/SamplesApp/UITests.Shared/UITests.Shared.projitems, src/SamplesApp/UITests.Shared/Windows_UI_Xaml/DragAndDrop/DragDrop_Wasm_Selection.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml/DragAndDrop/DragDrop_Wasm_Selection.xaml.cs, src/Uno.UI/ts/Windows/ApplicationModel/DataTransfer/DragAndDropExtension.ts
GitHub Issue (If applicable): closes #18854, closes unoplatform/kahua-private#228
- Bugfix
On WebAssembly, when there is selection underneath or around a control that typically uses drag gesture (eg: ScrollBar or Slider), the drag gesture will only work for the 1st frame/tick/delta, subsequent pointer capture events are lost, and there is an undesired browser dragging preview that follows the cursor.
The browser dragstart event are globally blocked. Note that doesn't affect the DragEventArgs.DragUIOverride preview as that is rendered on the uno side, nor the control's ability to receive drop (handled via dragenter & dragleave).
=> fix(wasm): unwanted preview shown when dragging over existing selection

src/Uno.UI/UI/Xaml/Application.skia.cs, src/Uno.UWP/Globalization/ApplicationLanguages.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/18283
- Bugfix
Fixes the support for InvariantCulture mode.
=> fix: Adjust support for InvariantCulture mode support

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/StyleFlowToPopup.xaml, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/StyleFlowToPopup.xaml.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_Style.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls_Primitives/Given_Popup.cs, src/Uno.UI/UI/Xaml/Controls/Popup/Popup.Base.cs, src/Uno.UI/UI/Xaml/Controls/Popup/PopupPanel.cs, src/Uno.UI/UI/Xaml/Controls/Popup/PopupRoot.cs, src/Uno.UI/UI/Xaml/DependencyObjectStore.cs, src/Uno.UI/UI/Xaml/Media/VisualTreeHelper.cs
GitHub Issue (If applicable): closes #18943
- Bugfix
- `Popup.Child` visual and logical parent hierarchy included `PopupPanel`, which is internal only
- Logical `Parent` of `Popup.Child` was not the `Popup` itself
- `ResourceDictionary` search for a popup in the visual tree did not include its actual parent
- `Popup.Child` parent hierarchy skips `PopupPanel`
- Logical `Parent` of `Popup.Child` is `Popup`
- We prefer logical parent for `ResourceDictionary` search when available
- [x Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
=> fix: `Popup.Child` parent hierarchy, `ResourceDictionary` resolution

doc/articles/guides/profiling-applications.md
=> docs: add instructions for gcdumps

src/Uno.UI.RemoteControl.Host/Extensibility/AddIns.cs, src/Uno.UI.RemoteControl.Host/Program.cs
linked https://github.com/unoplatform/uno.hotdesign/issues/2986#top
Fix logging of add-in discovery
Logging uses  `NullLoggger`
Use temp console log during statup of dev-server
=> fix: Fix logging of add-in discovery

doc/articles/features/using-the-uno-sdk.md
GitHub Issue (If applicable): https://github.com/unoplatform/uno/discussions/18866#discussioncomment-11371911
=> docs: Add tip for excluding pages with Uno.Sdk

src/Uno.UI/FeatureConfiguration.cs, src/Uno.UI/UI/Xaml/Controls/TextBlock/JavaStringCache.Android.cs, src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.Android.cs
GitHub Issue (If applicable): closes #18951
=> perf: limit JavaStringCache entries to deal with excessive GREF counts

src/SamplesApp/SamplesApp.Shared/App.xaml.cs, src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.cs, src/Uno.UI.RuntimeTests/IntegrationTests/common/CalendarHelper.h.cs, src/Uno.UI.RuntimeTests/IntegrationTests/dxaml/Event.cs, src/Uno.UI.RuntimeTests/MUX/Helpers/EventTester.cs, src/Uno.UI.RuntimeTests/MUX/Utilities/TestHelpers.cs, src/Uno.UI.RuntimeTests/Tests/UnitTestsTests/Given_UnitTest.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Image.cs, src/Uno.UI/FeatureConfiguration.cs, src/Uno.UI/UI/Xaml/Controls/AppBar/AppBar.Partial.cs, src/Uno.UI/UI/Xaml/DependencyObjectStore.cs, src/Uno.UI/UI/Xaml/UIElementCollection.cs, src/Uno.UI/UI/Xaml/Window/Implementations/BaseWindowImplementation.cs, src/Uno.UWP/Buffers/DefaultArrayPoolBucket.cs, src/Uno.UWP/UI/Core/Internal/KeyboardStateTracker.cs
It doesn't seem like #18909 was the culprit after all, so let's try again.
=> Revert "chore: Revert "Make skia runtime tests green locally on Debug""

src/Uno.UI.RuntimeTests/Tests/TemplatedParent/TemplatedParentTests.cs, src/Uno.UI/UI/Xaml/Controls/CalendarView/CalendarViewBaseItemChrome.cs, src/Uno.UI/UI/Xaml/Controls/Control/Control.cs, src/Uno.UI/UI/Xaml/FrameworkElement.cs
GitHub Issue (If applicable): closes unoplatform/add-private#18
- Bugfix
Setting a value to Control.Template has no effect once the template materialization had occured.
^ no more.
This regression was introduced with the life cycle refactor(ac1b54c35564027bfab3645b674aa905366c5322) that was bundled into templated-parent refactor (#17645).
=> fix(netstd): late template application is ignored

src/Uno.UI.RemoteControl.Host/Extensibility/AddIns.cs
linked https://github.com/unoplatform/uno.hotdesign/issues/2986
Attempt to define the working directory
Command fails for some user with:
```
[DEBUG][19:09:17.92]       Failed to get target frameworks of solution 'C:\Temp\Counter\Counter.sln'. This usually indicates that the solution is in an invalid state (e.g. a referenced project is missing on disk). Please fix and restart your IDE (command used: `dotnet build "C:\Temp\Counter\Counter.sln" --target:UnoDumpTargetFrameworks "-p:UnoDumpTargetFrameworksTargetFile=C:\Users\lcaze\AppData\Local\Temp\tmpint0b0.tmp" --verbosity quiet`). (cf. inner exception for more details.)
[DEBUG][19:09:17.92]       System.Exception: Unhandled exception. Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: The switch name extracted …
```
=> fix: Define the working directory for add-in discovery

doc/articles/guides/creating-custom-controls.md
> defining own ResourceDictionary I stumbled over this detail:
> https://platform.uno/docs/articles/guides/creating-custom-controls.html
> in the text the generic.xaml is lowercase and in the code sample its uppercase. I read somewhere (might be another uno doc page?) that especially for mobile devices the casing is important detail, because if its uppercase, they would not be able to use it. if thats true, this doc page should be updated to recommend lowercase instead in my opinion
unified the casing of "Themes/Generic.xaml" mentioned in this page.
https://discord.com/channels/1182775715242967050/1182775715729526908/1314 …
=> docs: Update creating-custom-controls.md

src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewMode.Properties.cs, src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Controls/SampleChooserControl.xaml, src/Uno.UWP/Devices/Input/PointerDevice.cs, src/Uno.UWP/FeatureConfiguration/WinRTFeatureConfiguration.cs
- Feature
No way to at least partially test touch input without a touch device.
An optimistic implementation of touch simulation is added in Samples app
=> feat: Allow simulating touch input in Samples app

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ImageTests/UnoSamples_Tests.Image.cs
Images displayed on the ImageStretch_None page are coming from the uno-assets.platform.uno site, and may not have loaded yet when the sample runs
- Bugfix
=> fix: Make `ImageStretch_None` wait for images to actually load

src/Uno.UI.Runtime.Skia.MacOS/MacOSWindowNative.cs, src/Uno.UI.Runtime.Skia.MacOS/NativeUno.cs, src/Uno.UI.Runtime.Skia.MacOS/UnoNativeMac/UnoNativeMac/UNOApplication.h, src/Uno.UI.Runtime.Skia.MacOS/UnoNativeMac/UnoNativeMac/UNOApplication.m, src/Uno.UWP/Storage/StorageFile.skia.cs
- Feature
Resource files are always looked up from the same directory where the executables are present. 
if the app is bundled (macOS `.app`) then we look under `Resources` for data files, while executables are inside the `MacOS` directory.
```
bundle.app/
Contents/
Info.plist
MacOS/
Resources/
```
=> feat(macOS): override ms-appx location when app is bundled

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Frame.cs, src/Uno.UI/UI/Xaml/Controls/Frame/Frame.legacy.cs, src/Uno.UI/UI/Xaml/Controls/Frame/Frame.partial.mux.cs
…avigateGitHub Issue (If applicable): closes #
- Bugfix
In WinUI, exceptions thrown on `Page` instances propagate to corresponding `Frame.Navigate`, but this is not the case in Uno Platform targets
Exceptions bubble up
=> `Frame` should throw on page exceptions

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_UIElement.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs, src/Uno.UI.Tests/Windows_UI_Input/Given_GestureRecognizer.cs, src/Uno.UI/UI/Input/GestureRecognizer.Gesture.cs, src/Uno.UI/UI/Input/GestureRecognizer.Manipulation.cs, src/Uno.UI/UI/Input/GestureRecognizer.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.pointers.skia.cs, src/Uno.UI/UI/Xaml/UIElement.Pointers.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/18765
=> fix(drag&drop): when a child and a parent subscribe to dragging, only fire on the child

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ScrollViewer.cs
- Bugfix
Test was there but not marked as `[TestMethod]`
Marked
=> test: Enable missing test on `ScrollViewer`

src/Uno.UI/FeatureConfiguration.cs, src/Uno.UI/UI/Xaml/Shapes/Ellipse.wasm.cs, src/Uno.UI/UI/Xaml/Shapes/Line.wasm.cs, src/Uno.UI/UI/Xaml/Shapes/Path.wasm.cs, src/Uno.UI/UI/Xaml/Shapes/Polygon.wasm.cs, src/Uno.UI/UI/Xaml/Shapes/Polyline.wasm.cs, src/Uno.UI/UI/Xaml/Shapes/Rectangle.wasm.cs, src/Uno.UI/UI/Xaml/Shapes/Shape.wasm.cs, src/Uno.UWP/Collections/LruCache.cs
=> refactor: shape perf

src/Uno.UI.RemoteControl.Server.Processors/HotReload/ServerHotReloadProcessor.cs, src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.ClientApi.cs, src/Uno.UI.RemoteControl/HotReload/Messages/UpdateFile.cs
Improve retry logic when using UpdateFile in case of NoChanges
We might get a NoChnages when there are actual changes pending
We retry more and longer ... and app can customize the retry logic if needed
=> fix(hr): Improve retry logic when using UpdateFile in case of NoChanges

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ScrollViewer.cs, src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.Managed.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/703
- Bugfix
`ScrollContentPresenter` was duplicating its touch event subscriptions. Because of that it caused various issue - e.g. scrolling twice as fast as finger movement.
We make sure to unsubscribe when a new subscription is requested.
=> fix: Avoid subscribing to touch scroll events twice

.github/workflows/codeql.yml, .github/workflows/labeler.yml, .github/workflows/no-response.yml, .github/workflows/scorecard.yml, .github/workflows/uwp-autoconvert.yml
closes https://github.com/unoplatform/uno/issues/19072
=> chore: Filter scheduled actions to the main repo

doc/articles/features/windows-media-capture.md, doc/articles/toc.yml
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/18456
- [x ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
=> docs: Add `CameraCaptureUI` page

doc/articles/studio/Hot Design/hot-design-getstarted-guide.md
Added a remark that you must have the beta access. .
=> docs: Update hot-design-getstarted-guide.md

src/Uno.UI.RuntimeTests/Tests/Windows_Globalization/Given_DateTimeFormatter.cs, src/Uno.UWP/Globalization/DateTimeFormatting/DateTimeFormatter.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/18975
- Bugfix
Currently the returned values for Time are very off from what they are supposed to compared to WinUI.
The logic for DateTimeFormatter has been improved to prioritize keys by length, starting with the longest. Previously, the Lookup dictionary had to be manually ordered, which could lead to issues. Additional mapping values have been added based on Microsoft documentation, and the dictionary has been cleaned up for better readability. A runtime test has also been added.
=> fix: Improve DateTimeFormatter template matching and mappings

src/Uno.UI.Runtime.Skia.Gtk/Helpers/Dpi/DpiHelper.cs, src/Uno.UI.RuntimeTests/Tests/Uno_Helpers/Given_StartStopEventWrapper.cs, src/Uno.UWP/Devices/Geolocation/Geolocator.Android.cs, src/Uno.UWP/Devices/Geolocation/Geolocator.cs, src/Uno.UWP/Devices/Sensors/LightSensor.cs, src/Uno.UWP/Devices/Sensors/ProximitySensor.Android.cs, src/Uno.UWP/Gaming/Input/Gamepad.cs, src/Uno.UWP/Helpers/StartStopDelegateWrapper.cs, src/Uno.UWP/Helpers/StartStopEventWrapper.cs, src/Uno.UWP/Helpers/StartStopTypedEventWrapper.cs, src/Uno.UWP/Networking/Connectivity/NetworkInformation.cs, src/Uno.UWP/System/Power/PowerManager.cs
Each sensor class has its own implementation of event start/stop management.
Using shared start/stop infrastructure, which is covered by tests.
=> `StartStopEventWrapper`

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media/Given_GeometryData.cs, src/Uno.UI/UI/Xaml/Media/GeometryData.wasm.cs, src/Uno.UI/UI/Xaml/Media/GeometryGroup.wasm.cs, src/Uno.UI/UI/Xaml/Media/PointCollection.wasm.cs, src/Uno.UI/UI/Xaml/Shapes/Ellipse.wasm.cs, src/Uno.UI/UI/Xaml/Shapes/Line.wasm.cs, src/Uno.UI/UI/Xaml/Shapes/Polygon.wasm.cs, src/Uno.UI/UI/Xaml/Shapes/Polyline.wasm.cs, src/Uno.UI/UI/Xaml/Shapes/Rectangle.wasm.cs, src/Uno.UI/UI/Xaml/Shapes/Shape.wasm.cs, src/Uno.UI/UI/Xaml/Window/WindowManagerInterop.wasm.cs, src/Uno.UI/ts/WindowManager.ts, src/Uno.UWP/UI/Color.cs, src/Uno.UWP/UI/Color.wasm.cs
GitHub Issue (If applicable): closes #19048
- Other... Please describe: perf
todo
todo
=> refactor(shape): wasm shape perf round-2

src/Directory.Build.props, src/Directory.Build.targets, src/Uno.UI.Tests/Uno.UI.Unit.Tests.csproj
=> test: Switch to MSTest runner (Microsoft.Testing.Platform)

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/When_TwoWay_Text_Binding.xaml, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/When_TwoWay_Text_Binding.xaml.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/kahua-private/issues/249
=> fix(textbox): fix TextProperty change propagation in xBind

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Frame.cs, src/Uno.UI/NativeFramePresenter.Android.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/18951
=> fix(nativeframepresenter): fix !AndroidUnloadInactivePages optimizations

src/Uno.UI-Skia-only.slnf
=> fix: Remove Uno.UI.Reference from Skia slnf

src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.Agent.cs
closes https://github.com/unoplatform/uno.hotdesign/issues/3179
Update HR conditions
HR is not enabled properly considering last updates
HR will self enable itself properly considering last updates
=> fix(hr): Update HR conditions

src/SamplesApp/UITests.Shared/UITests.Shared.projitems, src/SamplesApp/UITests.Shared/Windows_UI_Xaml/DragAndDrop/DragDrop_Basics.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml/DragAndDrop/DragDrop_Nested.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Input/Pointers/PointerEvent_Timestamp.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Input/Pointers/PointerEvent_Timestamp.xaml.cs, src/Uno.UI.Runtime.Skia.Gtk/Input/GtkCorePointerInputSource.cs, src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/FrameBufferPointerInputSource.Mouse.cs, src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/FrameBufferPointerInputSource.Touch.cs, src/Uno.UI.Runtime.Skia.MacOS/MacOSWindowHost.cs, src/Uno.UI.Runtime.Skia.MacOS/UnoNativeMac/UnoNativeMac/UNOApplication.h, src/Uno.UI.Runtime.Skia.MacOS/UnoNativeMac/UnoNativeMac/UNOApplication.m, src/Uno.UI.Runtime.Skia.MacOS/UnoNativeMac/UnoNativeMac/UNOWindow.m, src/Uno.UI.Runtime.Skia.Wpf/Input/WpfCorePointerInputSource.cs, src/Uno.UI.Runtime.Skia.X11/X11PointerInputSource.CoreProtocol.cs, src/Uno.UI.Runtime.Skia.X11/X11PointerInputSource.XInput.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBlock.cs, src/Uno.UI.Tests/Windows_UI_Input/Given_GestureRecognizer.cs, src/Uno.UI/Runtime/BrowserPointerInputSource.wasm.cs, src/Uno.UI/UI/Input/GestureRecognizer.Gesture.cs, src/Uno.UI/UI/Input/GestureRecognizer.Manipulation.InertiaProcessor.cs, src/Uno.UI/UI/Input/GestureRecognizer.Manipulation.cs, src/Uno.UI/UI/Input/GestureRecognizer.cs, src/Uno.UI/UI/Input/PointerPoint.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.pointers.skia.cs, src/Uno.UI/UI/Xaml/Input/PointerRoutedEventArgs.Android.cs, src/Uno.UI/UI/Xaml/Input/PointerRoutedEventArgs.iOS.cs, src/Uno.UWP/UI/Input/Preview.Injection/InjectedInputMouseInfo.cs, src/Uno.UWP/UI/Input/Preview.Injection/InjectedInputPointerInfo.cs
GitHub Issue (If applicable): closes #14535
- Bugfix
=> Input event `Timestamp` should be in microseconds

Directory.Build.props, build/ci/.azure-devops-wasdk.yml, src/SamplesApp/SamplesApp.Windows/SamplesApp.Windows.csproj, src/Uno.CrossTargetting.targets
- Bugfix
Only .NET 8 is supported
Both 8 and 9 are supported
=> fix: Allow building Samples App WinUI for .NET 9

src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.cs, src/Uno.UI.RemoteControl/RemoteControlClient.cs
Do not fail connection if a client processor initialization fails
If a client processor fails (like HR client if not properly configured), then connection to the dev-server is not initialized properly.
* We are still listening for incoming frames if a client processor initialization fails.
* HR client processor init does not crash if config is invalid.
=> fix(devSrv): Do not fail connection if a client processor fails

src/Uno.UWP/Devices/Sensors/Accelerometer.Android.cs, src/Uno.UWP/Devices/Sensors/Accelerometer.cs, src/Uno.UWP/Devices/Sensors/Accelerometer.wasm.cs, src/Uno.UWP/Devices/Sensors/Barometer.Android.cs, src/Uno.UWP/Devices/Sensors/Barometer.cs, src/Uno.UWP/Devices/Sensors/Barometer.iOS.cs, src/Uno.UWP/Devices/Sensors/Compass.Android.cs, src/Uno.UWP/Devices/Sensors/Compass.cs, src/Uno.UWP/Devices/Sensors/Compass.wasm.cs, src/Uno.UWP/Devices/Sensors/Gyrometer.Android.cs, src/Uno.UWP/Devices/Sensors/Gyrometer.cs, src/Uno.UWP/Devices/Sensors/HingeAngleSensor.Android.cs, src/Uno.UWP/Devices/Sensors/Magnetometer.Android.cs, src/Uno.UWP/Devices/Sensors/Magnetometer.cs, src/Uno.UWP/Devices/Sensors/Pedometer.Android.cs, src/Uno.UWP/Devices/Sensors/Pedometer.cs, src/Uno.UWP/Devices/Sensors/ProximitySensor.Android.cs, src/Uno.UWP/Devices/Sensors/SimpleOrientationSensor.cs
GitHub Issue: closes #19131
Most sensors used an `TypedEventHandler` field and had duplicated logic on the event handling.
Refactoring to use `StartStopTypedEventHandler` that encapsulates the logic for event-handling. 
This is now used in the sensor classes instead.
=> Refactor: Use shared StartStopTypedEventHandler for Sensors

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Markup/Given_XamlReader.cs, src/Uno.UI/Helpers/XamlHelper.cs, src/Uno.UI/UI/Xaml/Markup/Reader/XamlConstants.cs, src/Uno.UI/UI/Xaml/Markup/Reader/XamlObjectBuilder.cs, src/Uno.UI/UI/Xaml/Markup/Reader/XamlTypeResolver.cs, src/Uno.UI/UI/Xaml/Markup/XamlServiceProviderExtensions.cs
GitHub Issue (If applicable): closes #3399
- Bugfix
- Feature
- XamlReader fully supports dynamic parsing of custom MarkupExtension:
- Markup's ProvideValue method will be evaluated and the return value will be insert in its document position.
- an IXamlServiceProvider will be injected for ProvideValue(IXamlServiceProvider).
- the `-Extension` suffix can be optionally omitted.
=> fix(xamlreader): add proper support for markup-extension parsing

doc/articles/features/working-with-xaml-hot-reload.md, doc/articles/studio/Hot Design/hot-design-getstarted-counter-tutorial.md, doc/articles/studio/Hot Design/hot-design-getstarted-guide.md, doc/articles/studio/Hot Design/hot-design-overview.md, doc/articles/studio/studio-overview.md
=> docs: Reviewing existing docs

src/Uno.UI/UI/Xaml/VisualStateGroup.cs
`VisualState` instances changes in `VisualStateGroup` won't trigger updates during XAML parsing, avoiding intermediate discarded animations.
=> perf(anim): Don't refresh triggers and transitions during parsing

src/SamplesApp/UITests.Shared/Windows_UI_Input/GestureRecognizerTests/Manipulation_Inertia.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Input/GestureRecognizerTests/Manipulation_Inertia.xaml.cs, src/Uno.UI.RuntimeTests/Helpers/UITestHelper.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Composition/Given_InteractionTracker.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Input/Given_GestureRecognizer.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Input/TestPages/Manipulation_Inertia.xaml, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Input/TestPages/Manipulation_Inertia.xaml.cs, src/Uno.UI/Generated/3.0.0.0/Microsoft.UI.Xaml.Controls/ScrollViewer.cs, src/Uno.UI/UI/Input/GestureRecognizer.cs, src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.Managed.cs, src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.Managed.cs, src/Uno.UWP/UI/Input/Preview.Injection/InjectedInputMouseInfo.cs, src/Uno.UWP/UI/Input/Preview.Injection/InjectedInputState.cs
linked https://github.com/unoplatform/uno-private/issues/626
Restore inertia
The inertia is cancelled right after having been started so we get at most one inertia event.
🙃
* Draft until a test is prevent any new regression.
* Linked to work done in https://github.com/unoplatform/uno/pull/18293
=> fix: Restore inertia

src/Uno.UI/UI/Xaml/Media/Animation/Animators/RenderingLoopAnimator.Interop.wasm.cs, src/Uno.UI/UI/Xaml/Media/Animation/Animators/RenderingLoopAnimator.wasm.cs, src/Uno.UI/ts/Windows/UI/Xaml/Animation/RenderingLoopAnimator.ts, src/Uno.UWP/UI/Core/WeakEventHelper.cs
Only register once to the native animationframe callback to reduce interop calls.
=> perf(anim): Register only once to the JS animationframe callback

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_DependencyObjectCollection.cs, src/Uno.UI/UI/Xaml/DependencyObjectCollection.cs
GitHub Issue (If applicable): closes #19253, closes unoplatform/kahua-private#256
- Bugfix
On Uno, `new BehaviorCollection()[2]` throws:
```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
```
It will return `null` like on WinUI.
=> fix: align DepObjCol indexer behavior with winui

src/Uno.UI.RemoteControl/buildTransitive/Uno.WinUI.DevServer.targets
linked to https://github.com/unoplatform/uno/issues/19226
Remove usage of the deprecated RemoteControl.config file
If a stale `RemoteControl.config` file remaining on the disk, it's being considered by uno an breaks configuration of the dev-server endpoint configuration in the application.
Files are ignored in new versions of uno.
Note, thanks to https://github.com/unoplatform/uno.vscode/pull/915 files will be deleted by extensions for older versions of uno.
=> fix(devSrv): Remove usage of the deprecated RemoteControl.config file

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs, src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlConstants.cs, src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.Reflection.cs, src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs, src/SourceGenerators/XamlGenerationTests/ContentPresenter_ContentBinding.xaml, src/Uno.UI.RuntimeTests/Extensions/StringExtensions.cs, src/Uno.UI.RuntimeTests/Helpers/TreeAssert.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/ContentPresenter/ContentPresenter_ContentBindings.xaml, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/ContentPresenter/ContentPresenter_ContentBindings.xaml.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ContentPresenter.cs
GitHub Issue (If applicable): closes unoplatform/ziidms-private#47
- Bugfix
Using ContentPresenter with Content binding currently lead to compilation error.
In certain cases where permitted, the compilation error is no longer thrown:
- `{Binding}` without implicit or explicit Path
- `{Binding}` used within a `<ControlTemplate>`
- `{Binding}` used with TemplatedParent or Self as the RelativeSource (it works before this pr as well)
=> fix(codegen): ContentPresenter.Content binding compilation error

build/nuget/Uno.WinUI.nuspec, src/Directory.Build.targets, src/SamplesApp/SamplesApp.Wasm/Program.cs, src/Uno.Sdk/packages.json
- Bugfix
- Feature
Some glyphs were missing including `InfoBar` warning icon and `PasswordBox` reveal icon
Glyphs added
=> feat: Update `Uno.Fonts.Fluent`

src/Uno.UWP/Devices/Sensors/Accelerometer.Android.cs, src/Uno.UWP/Devices/Sensors/Accelerometer.cs, src/Uno.UWP/Devices/Sensors/Accelerometer.iOS.cs, src/Uno.UWP/Devices/Sensors/Accelerometer.wasm.cs, src/Uno.UWP/Devices/Sensors/Barometer.Android.cs, src/Uno.UWP/Devices/Sensors/Barometer.cs, src/Uno.UWP/Devices/Sensors/Compass.Android.cs, src/Uno.UWP/Devices/Sensors/Compass.cs, src/Uno.UWP/Devices/Sensors/Compass.wasm.cs, src/Uno.UWP/Devices/Sensors/Gyrometer.Android.cs, src/Uno.UWP/Devices/Sensors/Gyrometer.cs, src/Uno.UWP/Devices/Sensors/Gyrometer.wasm.cs, src/Uno.UWP/Devices/Sensors/Magnetometer.Android.cs, src/Uno.UWP/Devices/Sensors/Magnetometer.cs, src/Uno.UWP/Devices/Sensors/Magnetometer.wasm.cs, src/Uno.UWP/Devices/Sensors/Pedometer.Android.cs, src/Uno.UWP/Devices/Sensors/Pedometer.cs, src/Uno.UWP/Devices/Sensors/SimpleOrientationSensor.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/19274
Most sensor classes use a static instance and track with an boolean if the instance is already created. This caused code duplication and wasn't implemented like the `LightSensor.cs` implementation.
Use a static `Lazy` instance for instance creation, which removes the object lock, as well as the boolean. This follows the implementation already in `LightSensor.cs`.
=> Refactor: Use static Lazy instance for all sensors

src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/ItemsRepeater.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/UniformGridLayout/UniformGridLayout.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/19181
- Bugfix
=> fix: `UniformGridLayout` and `ItemsRepeater` in nested layout

src/Uno.UI.Runtime.Skia.X11/LinuxSystemThemeHelper.cs, src/Uno.UI.Runtime.Skia.X11/X11ApplicationHost.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/19273
=> feat(linux): implement an ISystemThemeHelper based on the Settings portal

src/SourceGenerators/Uno.UI.SourceGenerators.Tests/MetadataUpdateTests/Given_HotReloadService.cs, src/SourceGenerators/Uno.UI.SourceGenerators.Tests/MetadataUpdates/HotReloadWorkspaceProvider.cs, src/Uno.UI.RemoteControl/buildTransitive/Uno.WinUI.DevServer.targets
=> chore: Restore HR tests

src/SourceGenerators/Uno.UI.SourceGenerators.Tests/MetadataUpdateTests/Scenarios/When_Simple_Xaml_xName_Reorder/0/p1/MainPage.xaml, src/SourceGenerators/Uno.UI.SourceGenerators.Tests/MetadataUpdateTests/Scenarios/When_Simple_Xaml_xName_Reorder/0/p1/MainPage.xaml.cs, src/SourceGenerators/Uno.UI.SourceGenerators.Tests/MetadataUpdateTests/Scenarios/When_Simple_Xaml_xName_Reorder/1/p1/MainPage.xaml, src/SourceGenerators/Uno.UI.SourceGenerators.Tests/MetadataUpdateTests/Scenarios/When_Simple_Xaml_xName_Reorder/1/p1/MainPage.xaml.cs, src/SourceGenerators/Uno.UI.SourceGenerators.Tests/MetadataUpdateTests/Scenarios/When_Simple_Xaml_xName_Reorder/Scenario.json, src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Out/SOSLIIOFDOTAFE/XamlCodeGenerator_MainPage_d6cd66944958ced0c513e0a04797b51d.cs, src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Out/TPXBRXLE/XamlCodeGenerator_MainPage_d6cd66944958ced0c513e0a04797b51d.cs, src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Out/TTIXLE/XamlCodeGenerator_MainPage_d6cd66944958ced0c513e0a04797b51d.cs, src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Out/TXBRXLE/XamlCodeGenerator_MainPage_d6cd66944958ced0c513e0a04797b51d.cs, src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
closes https://github.com/unoplatform/uno.hotdesign/issues/3251
Ensure to keep ordering of generated properties
Might get ENC1002 when changing order of named elements in XAML
Generated properties are order by name, preventing the ENC1002
=> fix(hr): Ensure to keep ordering of generated properties

build/Uno.UI.Build.csproj, build/nuget/Uno.WinUI.DevServer.nuspec, build/nuget/Uno.WinUI.Lottie.nuspec, src/Directory.Build.targets, src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props, src/SourceGenerators/Uno.UI.SourceGenerators/RemoteControl/RemoteControlGenerator.cs, src/Uno.UI.RemoteControl.Server.Processors/HotReload/MetadataUpdates/CompilationWorkspaceProvider.cs, src/Uno.UI.RemoteControl.Server.Processors/HotReload/ServerHotReloadProcessor.MetadataUpdate.cs, src/Uno.UI.RemoteControl.Server.Processors/Uno.UI.RemoteControl.Server.Processors.csproj, src/Uno.UI.RemoteControl/Uno.UI.RemoteControl.netcoremobile.csproj, src/Uno.UI.RemoteControl/buildTransitive/Uno.WinUI.DevServer.props, src/Uno.UI.RemoteControl/buildTransitive/Uno.WinUI.DevServer.targets
closes https://github.com/unoplatform/uno/issues/19293, closes https://github.com/unoplatform/uno/issues/15918
Dev-server HR support for mobile targets
HR does not work with dev-server on mobile targets
🙃
=> fix(hr): Dev-server HR support for mobile targets

doc/articles/includes/additional-linux-setup-inline.md, src/Uno.UI.Runtime.Skia.X11/X11XamlRootHost.XInput.cs, src/Uno.UI.Runtime.Skia.X11/X11_Bindings/x11bindings_XLib.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/private/issues/600
=> fix(linux): check for libXi before assuming XI2 support

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.skia.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.pointers.skia.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/19315
=> fix(textbox): right clicking inside TextBox selection should not clear the selection

src/Uno.UI.RemoteControl.Host/RemoteControlServer.cs, src/Uno.UI.RemoteControl.Host/Uno.UI.RemoteControl.Host.csproj, src/Uno.UI.RemoteControl/Helpers/WebSocketHelper.cs, src/Uno.UI.RemoteControl/RemoteControlClient.cs
Improve reliability of connection by catching generic errors (like a serilization issue)
Connection is dropped if there is a serilization (for instance due a the linker)
Log error and wait for next frame.
=> chore(devSrv): Improve reliability of connection by catching generic errors

src/Uno.UI.RemoteControl.Server.Processors/HotReload/MetadataUpdates/CompilationWorkspaceProvider.cs, src/Uno.UI.RemoteControl.Server.Processors/HotReload/ServerHotReloadProcessor.MetadataUpdate.cs
- Bugfix
Ensures that roslyn assemblies are loaded from the disk instead of using stream loading during devserver HR workspace initialization.
=> fix: Ensure the assembly loader is registered early

src/Uno.UI.RemoteControl.Host/RemoteControlServer.cs, src/Uno.UI.RemoteControl.Server.Processors/HotReload/MetadataUpdates/CompilationWorkspaceProvider.cs
- Bugfix
- Adjust assembly loading with proper loading of Roslyn assemblies in the appropriate ALC.
- Load assemblies using file loading, not stream loading in order to have Assembly.Location set properly
=> Fix ALC loading of HR workspace

src/Uno.UI.RuntimeTests/Helpers/UITestHelper.cs, src/Uno.UI.RuntimeTests/Tests/TemplatedParent/Setup/Uno19264.xaml, src/Uno.UI.RuntimeTests/Tests/TemplatedParent/Setup/Uno19264.xaml.cs, src/Uno.UI.RuntimeTests/Tests/TemplatedParent/TemplatedParentTests.cs, src/Uno.UI/Extensions/PrettyPrint.cs, src/Uno.UI/Extensions/ViewExtensions.visual-tree.cs, src/Uno.UI/UI/Xaml/ElementStub.cs, src/Uno.UI/UI/Xaml/VisualState.cs, src/Uno.UI/UI/Xaml/VisualTransition.cs
GitHub Issue (If applicable): closes #19264
- Bugfix
The descendants of a lazily loaded element (x:Load=False, x:DeferedLoadingStrategy=Lazy) don't receive the proper templated-parent.
They will now receive the correct templated-parent, on materialization.
regression from: #17645
=> fix: lazy element descendants not receiving correct templated-parent

src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props, src/SourceGenerators/Uno.UI.SourceGenerators/RemoteControl/RemoteControlGenerator.cs, src/Uno.UI.RemoteControl.Server.Processors/HotReload/ServerHotReloadProcessor.MetadataUpdate.cs
Fix HR not working on android with Rider
Rider does not specify the runtime identifier when building while we do in the hot-relaod processor. This drives the HR to not being able to produce value updates.
🙃
=> fix(hr): Fix HR not working on android with Rider

src/Uno.UWP/Globalization/DateTimeFormatting/DateTimeFormatter.cs
GitHub Issue (If applicable): closes #19346
@ajpinedam I'll let you verify if this actually fixes it. I made this change only by looking at code
=> fix(reg): Fix DateTimeFormatter for "day" only

src/Uno.UI/UI/Xaml/Controls/Frame/Frame.HotReload.cs, src/Uno.UI/UI/Xaml/Navigation/PageStackEntry.Uno.cs
closes https://github.com/unoplatform/private/issues/609
closes https://github.com/unoplatform/private/issues/548
Frame stack cache update on HR
=> fix(hr): Fix Frame stack cache update on HR

.github/workflows/stale-prs.yml
This PR will enable the flagging of stale PRs after 60 days of inactivity. Dry-run for now.
=> ci: Enable dry-run for stale PRs

doc/articles/uno-build-error-codes.md, src/Uno.Sdk/targets/Uno.Common.targets, src/Uno.Sdk/targets/Uno.Sdk.After.targets
GitHub Issue (If applicable): closes https://github.com/unoplatform/private/issues/555
See https://developercommunity.visualstudio.com/t/WSL-launch-profile-cannot-be-found-when/10776961#T-N10813979 for more details.
=> fix: Use newer project capability for WSL in VS 17.13

src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.MetadataUpdate.cs
- Fix possible null ref
- Don't skip elements without handlers
=> fix: Fix possible null ref

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.skia.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.skia.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/19327
=> fix(textbox): accurately clear pending selections even when they're equal to the current selection

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBlock.cs, src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.cs, src/Uno.UI/UI/Xaml/UIElement.crossruntime.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/19380
=> fix(TextBlock): [Wasm] Clear old text when setting text through inlines

src/SourceGenerators/Uno.UI.SourceGenerators.Tests/MetadataUpdateTests/Scenarios/When_Simple_Xaml_Delegates_Fuzzy_Matching_1/0/p1/MainPage.xaml, src/SourceGenerators/Uno.UI.SourceGenerators.Tests/MetadataUpdateTests/Scenarios/When_Simple_Xaml_Delegates_Fuzzy_Matching_1/0/p1/MainPage.xaml.cs, src/SourceGenerators/Uno.UI.SourceGenerators.Tests/MetadataUpdateTests/Scenarios/When_Simple_Xaml_Delegates_Fuzzy_Matching_1/1/p1/MainPage.xaml, src/SourceGenerators/Uno.UI.SourceGenerators.Tests/MetadataUpdateTests/Scenarios/When_Simple_Xaml_Delegates_Fuzzy_Matching_1/1/p1/MainPage.xaml.cs, src/SourceGenerators/Uno.UI.SourceGenerators.Tests/MetadataUpdateTests/Scenarios/When_Simple_Xaml_Delegates_Fuzzy_Matching_1/Scenario.json, src/SourceGenerators/Uno.UI.SourceGenerators.Tests/MetadataUpdateTests/Scenarios/When_Simple_Xaml_Delegates_Fuzzy_Matching_1_xBind/0/p1/MainPage.xaml, src/SourceGenerators/Uno.UI.SourceGenerators.Tests/MetadataUpdateTests/Scenarios/When_Simple_Xaml_Delegates_Fuzzy_Matching_1_xBind/0/p1/MainPage.xaml.cs, src/SourceGenerators/Uno.UI.SourceGenerators.Tests/MetadataUpdateTests/Scenarios/When_Simple_Xaml_Delegates_Fuzzy_Matching_1_xBind/1/p1/MainPage.xaml, src/SourceGenerators/Uno.UI.SourceGenerators.Tests/MetadataUpdateTests/Scenarios/When_Simple_Xaml_Delegates_Fuzzy_Matching_1_xBind/1/p1/MainPage.xaml.cs, src/SourceGenerators/Uno.UI.SourceGenerators.Tests/MetadataUpdateTests/Scenarios/When_Simple_Xaml_Delegates_Fuzzy_Matching_1_xBind/Scenario.json, src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Out/TIM/XamlCodeGenerator_MainPage_d6cd66944958ced0c513e0a04797b51d.cs, src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Out/WEOTLNDO/XamlCodeGenerator_MainWindow_c93db19a7202d9eb84ddc41d72fcb89b.cs, src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Out/WNWSRAE/XamlCodeGenerator_ResourceDictionary_When_Nested_With_Sibling_Ref_And_Event_6d62c5ee15120ed189e095faf6d37e20.cs, src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Verifiers/CSGenerator.cs, src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props, src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/BackingFieldDefinition.cs, src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/NameScope.cs, src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XBindEventInitializerDefinition.cs, src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XLoadScope.cs, src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs, src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlLazyApplyBlockIIndentedStringBuilder.cs
closes https://github.com/unoplatform/uno.hotdesign/issues/3289
closes https://github.com/unoplatform/uno.hotdesign/issues/3299
Potentially also fixes: 
https://github.com/unoplatform/uno.hotdesign/issues/3290
https://github.com/unoplatform/uno.hotdesign/issues/3281
Fix ENC1002 when dealing with event handlers
Get ENC1002 pretty easily when dealing with element that has event handlers (code behind or x:Bind)
HR
=> fix(hr): Fix ENC1002 when dealing with event handlers

doc/articles/create-an-app-vscode.md, doc/articles/features/working-with-xaml-hot-reload.md
Miscellaneous docs updates and improvements
=> docs: Miscellaneous docs updates and improvements

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
Works around https://github.com/xamarin/xamarin-macios/issues/22102
Fixes https://github.com/unoplatform/uno.hotdesign/issues/3281
=> fix(hr): Add dummy class at the end of the generated file

THIRD-PARTY-NOTICES.md, build/nuget/Uno.WinUI.DevServer.nuspec, src/Uno.UI.RemoteControl/Uno.UI.RemoteControl.Reference.csproj, src/Uno.UI.RemoteControl/Uno.UI.RemoteControl.Skia.csproj, src/Uno.UI.RemoteControl/Uno.UI.RemoteControl.Wasm.csproj, src/Uno.UI.RemoteControl/Uno.UI.RemoteControl.netcoremobile.csproj, src/Uno.UI.RemoteControl/external/Microsoft.IO.RecyclableMemoryStream/EventArgs.cs, src/Uno.UI.RemoteControl/external/Microsoft.IO.RecyclableMemoryStream/Events.cs, src/Uno.UI.RemoteControl/external/Microsoft.IO.RecyclableMemoryStream/RecyclableMemoryStream.cs, src/Uno.UI.RemoteControl/external/Microsoft.IO.RecyclableMemoryStream/RecyclableMemoryStreamManager.cs
This avoids importing this package into the running app and cause dependency issues if the package is updated by the user.
=> fix(hr): Don't import Microsoft.IO.RecyclableMemoryStream using nuget

build/test-scripts/run-net7-template-linux.ps1, build/test-scripts/run-netcore-mobile-template-tests.ps1, src/SourceGenerators/Uno.UI.Tasks/Content/Uno.UI.Tasks.targets
- Bugfix
Ensures that XamlTrimming works properly when `UseArtifactsOutput` is enabled.
=> fix(trim): Adjust linker generator input and output paths for `UseArtifactsOutput`

src/Uno.UI.Runtime.Skia.MacOS/UnoNativeMac/UnoNativeMac/UNOWindow.m
closes https://github.com/unoplatform/uno-private/issues/633
Fix invalid timestamp causing incredible inertia on macOS
Timestamp are rounded at the second level
Micro-second timestamps
=> fix(pointers): Fix invalid timestamp causing incredible inertia on macOS

src/Uno.UI.Toolkit/Diagnostics/DiagnosticsOverlay.Placement.cs
linked to https://github.com/unoplatform/uno-private/issues/633
Prevent HRI to move out of area by inertia
We can "launch" the HRI out of window's bounds
When HRI is manipulated by inertia, we clamp it in the bounds of the window.
=> feat: Prevent HRI to move out of area by inertia

src/SamplesApp/SamplesApp.netcoremobile/Android/AndroidManifest.xml, src/SamplesApp/UITests.Shared/UITests.Shared.projitems, src/SamplesApp/UITests.Shared/Windows_UI_Xaml/WindowTests/Window_Metrics.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml/WindowTests/Window_Metrics.xaml.cs, src/Uno.UI/UI/Xaml/Application.Android.cs, src/Uno.UI/UI/Xaml/Application.cs, src/Uno.UI/UI/Xaml/ApplicationActivity.Android.cs, src/Uno.UI/UI/Xaml/Window/Native/NativeWindowWrapper.Android.cs, src/Uno.UWP/UI/ViewManagement/StatusBar/StatusBar.Android.cs
GitHub Issue (If applicable): part of https://github.com/unoplatform/uno-private/issues/822
=> fix: Android 15 window insets calculation

src/Uno.UI/Runtime/BrowserPointerInputSource.wasm.cs, src/Uno.UI/UI/Xaml/Internal/InputManager.Pointers.Managed.cs, src/Uno.UI/ts/Runtime/BrowserPointerInputSource.ts, src/Uno.UWP/UI/Core/PointerEventArgs.cs
closes https://github.com/unoplatform/uno/issues/18599
Fix possible missing pointer exited event with touch using wasm on iOS/iPad
Browser does not raise the `pointerleave` event when the target lement is being removed from the screen.
We forcefully inject it when needed
=> fix(pointers): Fix possible missing pointer exited event with touch using wasm on iOS/iPad

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_CalendarDatePicker.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_DatePicker.cs, src/Uno.UI/UI/Xaml/Controls/CalendarView/CalendarView_Partial.cs, src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePicker.cs, src/Uno.UI/UI/Xaml/Controls/DatePicker/NativeDatePickerFlyout.Android.cs, src/Uno.UI/UI/Xaml/Controls/DatePicker/NativeDatePickerFlyout.iOS.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/19505
=> Default `Date`/`Calendar` picker dates

doc/articles/features/using-the-uno-sdk.md, src/Uno.Sdk/targets/Uno.CrossTargeting.targets
- Feature
All targets have a platform-specific C# suffix, except for WinUI
`.WinAppSDK.cs` files are only going to be included on WinAppSDK target
=> feat: Recognize `.WinAppSDK.cs` in Uno.SDK

src/Uno.UI.RuntimeTests/Tests/Uno_UI_Xaml_Core/Given_DragDrop.cs, src/Uno.UI/UI/Xaml/Internal/InputManager.cs, src/Uno.UI/UI/Xaml/Window/Window.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/19522
- Bugfix
Drag and drop is not initialized correctly on mobile
Initialized in line with Skia and WebAssembly
=> fix: Drag and Drop initialization on mobile

src/Uno.UI.RemoteControl.VS/GlobalJsonObserver.cs
Allow the global.json parser to accept trailing commas.
=> fix(vsix): Relax global.json parsing

src/Uno.UI.RuntimeTests/IntegrationTests/dxaml/controls/commandbar/CommandBarIntegrationTests.cs, src/Uno.UI/UI/Xaml/Application.iOS.cs, src/Uno.UI/UI/Xaml/Controls/Flyout/FlyoutBase.cs, src/Uno.UI/UI/Xaml/Controls/Flyout/FlyoutBase.iOSmacOS.cs, src/Uno.UI/UI/Xaml/Controls/TimePicker/NativeTimePickerFlyout.iOS.cs, src/Uno.UI/UI/Xaml/Internal/ContentManager/ContentManager.iOS.cs, src/Uno.UI/UI/Xaml/Window/Implementations/BaseWindowImplementation.cs, src/Uno.UI/UI/Xaml/Window/Implementations/IWindowImplementation.cs, src/Uno.UI/UI/Xaml/Window/Native/Factory/NativeWindowFactory.iOS.cs, src/Uno.UI/UI/Xaml/Window/Native/Factory/NativeWindowFactory.others.cs, src/Uno.UI/UI/Xaml/Window/Native/INativeWindowWrapper.cs, src/Uno.UI/UI/Xaml/Window/Native/NativeWindowWrapper.Android.cs, src/Uno.UI/UI/Xaml/Window/Native/NativeWindowWrapper.iOS.cs, src/Uno.UI/UI/Xaml/Window/Native/NativeWindowWrapper.macOS.cs, src/Uno.UI/UI/Xaml/Window/Native/NativeWindowWrapper.reference.cs, src/Uno.UI/UI/Xaml/Window/Native/NativeWindowWrapper.unittests.cs, src/Uno.UI/UI/Xaml/Window/Native/NativeWindowWrapper.wasm.cs, src/Uno.UI/UI/Xaml/Window/Native/NativeWindowWrapperBase.cs, src/Uno.UI/UI/Xaml/Window/Window.cs, src/Uno.UI/UI/Xaml/Window/Window.wasm.cs
=> refactor: Unsingleton window factory on iOS

src/SourceGenerators/Uno.UI.SourceGenerators/RemoteControl/RemoteControlGenerator.cs, src/Uno.UI.RemoteControl.Server.Processors/HotReload/ServerHotReloadProcessor.MetadataUpdate.cs, src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.Common.Status.cs
closes https://github.com/unoplatform/private/issues/630
Ignore bin and obj folders
cf. issue
`OutputPath` an `IntermediateOutputPath` are ignore by the HR workspace
=> fix(hr): Ignore bin and obj folders

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_AutoSuggestBox.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Icons/Given_IconSourceElement.cs, src/Uno.UI/UI/Xaml/Controls/Icons/SymbolIcon.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/19408
- Bugfix
This pull request includes changes to the `SymbolIcon` class in the `Uno.UI` library to improve how symbol values are converted to glyphs. The most important changes are the addition of a new method to handle this conversion and the update to the `SetSymbolText` method to use this new conversion method.
=> fix: Symbol glyph mapping to recommended Unicode points

build/nuget/Uno.WinUI.nuspec
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/19553
- Bugfix
Aligns the explicit dependency on android appcompat, when using Uno.UI/Uno.WinUI directly, without the Uno.SDK.
=> fix: Adjust explicit dependency to android appcompat

build/PackageDiffIgnore.xml, src/AddIns/Uno.UI.Svg/SvgProvider.cs, src/Uno.UI/UI/Xaml/Media/ImageBrush.cs, src/Uno.UI/UI/Xaml/Media/Imaging/Svg/ISvgProvider.cs, src/Uno.UI/UI/Xaml/Media/Imaging/SvgImageSource.provider.cs, src/Uno.UI/UI/Xaml/Media/Imaging/SvgImageSource.skia.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/19192
=> feat(skia): support ImageBrushes with svg URIs

src/Uno.UI.RuntimeTests/IntegrationTests/dxaml/controls/commandbar/CommandBarIntegrationTests.cs
Related issues: #9080, #19585
- Disable flaky test
`ValidateDynamicOverflowOrderBasic()` test is very flaky on Android  (cf. #9080, #19585)
Disable the flaky `ValidateDynamicOverflowOrderBasic()` test on Android
=> test: Disable flaky ValidateDynamicOverflowOrderBasic() test on Android (#9080, #19585)

doc/articles/toc.yml, src/Uno.UWPSyncGenerator/DocGenerator.cs
Some non-generated and generated doc TOC items are not properly alphabetized for the reference section
All non-generated and generated doc TOC items are properly alphabetized for the reference section
=> Ensuring items in the TOC are alphabetized for the reference section

src/Directory.Build.targets
- Bugfix
Samples app on WASM does not build locally due to `UnoGenerateAssetsManifestDependsOn` issue
Bring in up-to-date version with fix.
=> feat: Update `Uno.Wasm.Bootstrap`

src/Uno.UI/UI/Input/GestureRecognizer.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/19409, related to #7646
The gesture conflict is reported as error
Although still should be fixed, it is so far not causing any user-visible issues. Dropping the severity to avoid confusion.
=> chore: Log gesture conflict as information only

src/Uno.UI.RemoteControl.Messaging/IDEChannel/ForceHotReloadIdeMessage.cs, src/Uno.UI.RemoteControl.Messaging/IDEChannel/HotReloadRequestedIdeMessage.cs, src/Uno.UI.RemoteControl.Messaging/IDEChannel/IdeMessageWithCorrelationId.cs, src/Uno.UI.RemoteControl.Messaging/IDEChannel/IdeResultMessage.cs, src/Uno.UI.RemoteControl.Messaging/IDEChannel/UpdateFileIdeMessage.cs, src/Uno.UI.RemoteControl.Server.Processors/HotReload/ServerHotReloadProcessor.MetadataUpdate.cs, src/Uno.UI.RemoteControl.Server.Processors/HotReload/ServerHotReloadProcessor.cs, src/Uno.UI.RemoteControl.VS/AbsolutePathComparer.cs, src/Uno.UI.RemoteControl.VS/EntryPoint.cs, src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.ClientApi.cs, src/Uno.UI.RemoteControl/HotReload/Messages/UpdateFile.cs, src/Uno.UI.Tests/Helpers/Given_AbsolutePathComparer.cs, src/Uno.UI.Tests/Uno.UI.Unit.Tests.csproj
Closes https://github.com/unoplatform/uno.hotdesign/issues/3351
The way Visual Studio is dealing with Hot Reload is by using its _documents_ to compile and ship updated IL to the application. There is no requirement to save the file for _Hot Reload_ to work in this environment.
That means 2 things:
1. The file on disk may not reflect the last changes which only occurs in memory in Visual Studio. The user _may_ save the file, but it's not a requirement for HR.
2. If the file is opened in Visual Studio, a _silent_ change to the file on disk may not be picked up by HR, especially when VS is not focused. THIS IS THE PROBLEM THIS PR IS ADDRESSING. The other one will be addressed afterwards (soon).
=> HR: Changed the way code (XAML) is updated through Hot Reload

src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Controls/SampleChooserControl.xaml
=> fix: Avoid focusing `AutoSuggestBox` when switching tabs in Samples app

src/Uno.UI/UI/Xaml/Controls/ScrollBar/ScrollBar.uno.cs
=> fix: Ensure proper check for template root

src/SourceGenerators/Uno.UI.Tasks/Content/uno.ui.tasks.assets.targets
- Bugfix
Wasm Transitive assets may not be created properly after 9.0.102.
Transitive assets are available.
=> fix(wasm): Ensure proper dependents execution after 9.0.102

src/Uno.UI.RemoteControl.VS/DebuggerHelper/ProfilesObserver.cs, src/Uno.UI.RemoteControl.VS/EntryPoint.ActiveProfileSync.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/private/issues/619
- Bugfix
The first TFM/profile change is not ignored when the startup project list is asynchronously initialized.
=> fix(vs): don't reload the profile observer on initial solution open

src/Uno.UI.RuntimeTests/Tests/Microsoft_UI_Xaml_Controls/Given_NavigationView.cs, src/Uno.UI/FeatureConfiguration.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/NavigationView/NavigationView.cs
GitHub Issue (If applicable): closes #19516, closes unoplatform/ziidms-private#46
- Bugfix
after changing NavView::IsBackButtonVisible value, all NVItems would stop updating their layout/size when expanded/collapsed.
added a workaround for this issue
=> fix(droid): add workaround for NavView leaving blank on IsBackButtonVisible update

src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/SplitButton/SplitButtonTests_InteractionTests.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/SplitButton/SplitButton.cs
- Bugfix
When tapping (touchscreen) the flyout would open even if you don't click the chevron.
Tapping (touchscreen) now behaves like `Click` that only opens the flyout if the chevron is clicked.
- [] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
Based on Microsoft changes: https://github.com/microsoft/microsoft-ui-xaml/commit/69097129a853c65a16447aade4c82576d4724b1a#diff-26435cd7d5a1b50dca1fba8a84c5432c4941c8be555ba8d4ff8e34d99987fb9a
SplitButton.cs
https://github.com/microsoft/microsoft-ui-xaml/blob/69097129a …
=> fix: Make SplitButton click and tap behave the same

src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/ExpanderTests/Expander_Bindings_TemplatedControl.xaml, src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/ExpanderTests/Expander_Bindings_TemplatedControl.xaml.cs, src/SamplesApp/UITests.Shared/UITests.Shared.projitems
related https://github.com/unoplatform/uno/issues/17312
This PR adds a sample to the Sample App to reproduce the error reported on https://github.com/unoplatform/uno/issues/17312. This will help validate whether the Fix being worked on in PR https://github.com/unoplatform/uno/pull/17645 does indeed fix the problem.
=> Test: Add Sample Test for Expander header bindings

src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/ExpanderTests/Expander_Bindings_TemplatedControl.xaml.cs, src/SamplesApp/UITests.Shared/Windows_ApplicationModel/DataTransfer/DataTransferManagerTests.xaml, src/SamplesApp/UITests.Shared/Windows_ApplicationModel/DataTransfer/DataTransferManagerTests.xaml.cs, src/Uno.UWP/ApplicationModel/DataTransfer/DataTransferManager.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/911
- Bugfix
=> fix: Sharing should provide default options when none are provided

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Border.cs, src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.iOSmacOS.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/19505
- Bugfix
NRE in `BorderLayerRenderer`
No NRE
=> fix: Correctly render `CalendarDatePicker` on iOS

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_NativeFrame.cs, src/Uno.UI/Controls/NativeFramePresenter.Android.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/19574
=> fix(nativeframepresenter): animate pages depending on NavigationMode

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TimePicker.cs, src/Uno.UI/UI/Xaml/Controls/Popup/PopupPanel.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/add-private/issues/25
=> fix(popup): fall back to PlacementArrangeOverride when popup would otherwise be placed outside the window

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_WebView2.cs, src/Uno.UI/UI/Xaml/Controls/WebView/Native/Wasm/NativeWebView.Interop.wasm.cs, src/Uno.UI/UI/Xaml/Controls/WebView/Native/Wasm/NativeWebView.wasm.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/19635
- Bugfix
ExecuteStringAsync runs properly on Wasm.
=> fix(webview2): [wasm] Fix ExecuteScriptAsync

src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/WebView2Tests/WebView2_OuterSelection.xaml, src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/WebView2Tests/WebView2_OuterSelection.xaml.cs, src/SamplesApp/UITests.Shared/UITests.Shared.projitems, src/Uno.UI/WasmCSS/Uno.UI.css
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/19640
- Bugfix
The WebView2 controls is not selectable as text anymore.
=> fix(webview): Don't allow for the webview iframe to be selected

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs, src/Uno.UI/Extensions/ViewExtensions.visual-tree.cs, src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.managed.cs
GitHub Issue (If applicable): closes unoplatform/kahua-private#272
- Bugfix
On Wasm/Skia, when setting ListView::SelectedItem during the list refresh/rebuild will causes any item before the selected one to be render as blank.
^ not anymore.
=> fix(listview): setting SelectedItem during list refresh leaves blank in items on wasm/skia

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement_EffectiveViewport.cs, src/Uno.UI/UI/Xaml/DependencyObjectStore.cs, src/Uno.UI/UI/Xaml/FrameworkElement.EffectiveViewport.cs, src/Uno.UI/UI/Xaml/Internal/CustomEventManager.cs, src/Uno.UI/UI/Xaml/Internal/EventManager.cs
GitHub Issue (If applicable): closes #19751, closes unoplatform/kahua-private#276
- Bugfix
FE::EffectiveViewportChanged has extra calls with invalid EffectiveViewport values.
Those invalid calls are now blocked.
=> fix: block FE::EffectiveViewportChanged early procs with invalid values

src/Uno.UWP/Helpers/DrawableHelper.Android.cs, src/Uno.UWP/Storage/StorageFile.Android.cs
We're looking for fonts in actual asset manager as well as in known IDs, where there may not by an ID for that file, particularly those read from transitive assets.
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/1040
=> fix(android): Don't log font lookup failures

src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.MetadataUpdate.cs, src/Uno.UI.RuntimeTests/Tests/HotReload/Frame/HRApp/Tests/Given_UserControl.cs
- Bugfix
When elements are replaced during HR they get a DebugParseContext based on the source code for the control (since it's manually created in code). 
The DebugParseContext of the replacement element is set to be the same as the element it's replacing.
=> fix: Correcting DebugParseContext for replaced elements after HR

src/Uno.UI.Runtime.Skia.AppleUIKit/AppleUIKitPointerInputSource.cs, src/Uno.UI.Runtime.Skia.AppleUIKit/UI/Xaml/AppleUIKitWindow.cs, src/Uno.UI.Runtime.Skia.AppleUIKit/UI/Xaml/RootViewController.cs, src/Uno.UI.Tests/Windows_UI_Input/Given_GestureRecognizer.cs, src/Uno.UI/UI/Input/GestureRecognizer.Manipulation.cs, src/Uno.UI/UI/Xaml/Internal/InputManager.Pointers.ManagedDirectManip.cs
closes https://github.com/unoplatform/uno-private/issues/1061
closes https://github.com/unoplatform/uno-private/issues/1038
Misc fixes for pointers on skia
* All pointers have ID = 0
* Flick gesture on iOS 18 @ 120 fps start inertia with really small speed
* Pointers have valid IDs
* We ignore the last pointer event (release) to compute velocities values to start inertia
=> Misc fixes for pointers on skia

src/Uno.UI/Microsoft/UI/Xaml/Controls/ColorPicker/ColorSpectrum.cs, src/Uno.UI/UI/Input/GestureRecognizer.Manipulation.cs, src/Uno.UI/UI/Xaml/Internal/PointerCaptureOptions.cs
closes https://github.com/unoplatform/uno-private/issues/906
Fix ColorPicker does not prevent scrolling
ColorPicker does not prevent scrolling
We use our current internal patch to support this case
=> fix: Fix ColorPicker does not prevent scrolling

src/Uno.UI/UI/Xaml/Media/Animation/Animators/DispatcherAnimator.cs
closes https://github.com/unoplatform/uno-private/issues/1044
Increase frame rate for skia backend
Animations are running at 30 fps on skia backend
We run them at 60 fps
=> fix: Increase frame rate for skia backend

src/Uno.UI.Composition/Composition/Compositor.skia.cs
linked to https://github.com/unoplatform/uno-private/issues/1092
Remove double Idle re-scheduling of composition animations
Animations are scheduled twice (on idle dispatcher):
1. https://github.com/unoplatform/uno/blob/5d975dcc2517b9f4bb9ee7e59d7031d44d23b9b5/src/Uno.UI.Composition/Composition/Compositor.skia.cs#L138
2. https://github.com/unoplatform/uno/blob/5d975dcc2517b9f4bb9ee7e59d7031d44d23b9b5/src/Uno.UI/UI/Xaml/XamlRoot.crossruntime.cs#L47
We keep only the second scheduling.
=> fix(perf): Remove double Idle re-scheduling of composition animations

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.Android.cs
GitHub Issue (If applicable): unoplatform/ziidms-private#82
- Bugfix
AutoSuggestionBox default Foreground is not inherited by its TextBoxView. (note: explicit or late set value aren't imparted.)
AutoSuggestionBox default Foreground is applied.
=> fix(droid): TextBox default foreground not applied

src/Uno.UI/UI/Xaml/Internal/VisualTree.cs, src/Uno.UI/UI/Xaml/Window/Window.cs
=> fix: Disable `CoreWindow` in single-window targets

src/Uno.UI.RuntimeTests/Tests/Uno_UI/Given_ResourceResolver.cs, src/Uno.UI.RuntimeTests/Tests/Uno_UI/Resolve_Parent_Resources.xaml, src/Uno.UI.RuntimeTests/Tests/Uno_UI/Resolve_Parent_Resources.xaml.cs, src/Uno.UI/UI/Xaml/DependencyObjectStore.cs
GitHub Issue (If applicable): closes #19825 
- Bugfix
Style resolution only works from immediate parents. Any style at the Page level or above the direct parent is not being recognized.
=> fix(iOS): styles resolution

src/SamplesApp/SamplesApp.Skia.WebAssembly.Browser/Program.cs, src/SamplesApp/SamplesApp.Skia.netcoremobile/MacCatalyst/Main.MacCatalyst.cs, src/SamplesApp/SamplesApp.Skia.netcoremobile/iOS/Main.iOS.cs, src/SamplesApp/SamplesApp.Skia.netcoremobile/tvOS/Main.tvOS.cs, src/SolutionTemplate/5.6/uno56wasmskia/uno56wasmskia/Platforms/WebAssembly/Program.cs, src/Uno.UI.Runtime.Skia.Android/AndroidHost.cs, src/Uno.UI.Runtime.Skia.Android/Microsoft/UI/Xaml/Controls/BaseActivity.cs, src/Uno.UI.Runtime.Skia.Android/Microsoft/UI/Xaml/Controls/CurrentActivityChangedEventArgs.cs, src/Uno.UI.Runtime.Skia.Android/Microsoft/UI/Xaml/Controls/OnSystemUiVisibilityChangeListener.cs, src/Uno.UI.Runtime.Skia.Android/Microsoft/UI/Xaml/TextEditState.cs, src/Uno.UI.Runtime.Skia.Android/Microsoft/UI/Xaml/TextEditingDelta.cs, src/Uno.UI.Runtime.Skia.AppleUIKit/AppleUIKitHost.cs, src/Uno.UI.Runtime.Skia.AppleUIKit/UI/Xaml/RootViewController.cs, src/Uno.UI.Runtime.Skia.AppleUIKit/Uno.UI.Runtime.Skia.AppleUIKit.csproj, src/Uno.UI.Runtime.Skia.AppleUIKit/UnoSkiaAppDelegate.cs, src/Uno.UI.Runtime.Skia.WebAssembly.Browser/WebAssemblyBrowserHost.cs, src/Uno.UI.Runtime.Skia.Win32/Win32NativeElementHostingExtension.cs, src/Uno.UI/ActivityHelper.Android.cs, src/Uno.UI/DelegateActivity.Android.cs, src/Uno.UI/OnActivityResultArgs.Android.cs, src/Uno.UI/UI/Xaml/Controls/DatePicker/NativeDatePickerFlyout.Android.cs, src/Uno.UI/UI/Xaml/Controls/TimePicker/UnoTimePickerDialog.Android.cs, src/Uno.UI/UI/Xaml/Controls/WebView/Native/NativeWebView.unittests.cs, src/Uno.UI/UI/Xaml/Controls/WebView/Native/Wasm/HtmlWebViewElement.wasm.cs, src/Uno.UI/UI/Xaml/Controls/WebView/Native/Wasm/NativeWebView.wasm.cs, src/Uno.UI/UI/Xaml/Controls/WebView/Native/iOSmacOS/NativeWebView.iOSmacOS.cs, src/Uno.UI/UI/Xaml/Controls/WebView/Native/iOSmacOS/UnoWKWebView.iOSmacOS.cs, src/Uno.UI/UI/Xaml/NativeApplication.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/1090
=> fix: Adjust public APIs

src/SamplesApp/UnoIslandsSamplesApp.Skia.Wpf/MainWindow.xaml, src/Uno.UI.Runtime.Skia.AppleUIKit/UI/Xaml/UnoSKMetalView.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs, src/Uno.UI/UI/Xaml/Media/Animation/Animators/DispatcherAnimator.cs, src/Uno.UI/UI/Xaml/Media/Animation/Animators/DispatcherAnimator.skia.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/1097
Edit DR: This also closes https://github.com/unoplatform/uno-private/issues/1092
- Bugfix
Move dispatcher animator to use `CompositionTarget.Rendering`.
Adjust framerate for metal view
=> Adjust animations performance

src/Uno.UI.Runtime.Skia.AppleUIKit/UI/Xaml/Controls/TextBox/InvisibleTextBoxViewExtension.cs, src/Uno.UI.Runtime.Skia.AppleUIKit/UI/Xaml/Controls/TextBox/MultilineInvisibleTextBoxView.cs, src/Uno.UI.Runtime.Skia.AppleUIKit/UI/Xaml/Controls/TextBox/SinglelineInvisibleTextBoxView.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.skia.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/788, closes https://github.com/unoplatform/uno-private/issues/767, closes https://github.com/unoplatform/uno-private/issues/807, closes https://github.com/unoplatform/uno-private/issues/808
- Bugfix
Input handling is not consistent with other platforms
Consistent
=> fix: Adjust newline handling on iOS

src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.Managed.cs, src/Uno.UI/UI/Xaml/Internal/InputManager.Pointers.ManagedDirectManip.cs
closes https://github.com/unoplatform/uno-private/issues/1096
Inertia scrolling might not being stopped
If input source provides a different pointer ID for each touch, we do not abort previous inertial scrolling
Pending direct manipulation is being aborted on pointer pressed if processing inertia
=> fix(pointers): Fix inertia scrolling might not being stopped

src/Uno.UI/UI/Xaml/Controls/MediaPlayerElement/MediaPlayerPresenter.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/1051
- Bugfix
A bug is noticeable when rendering the MediaPlayer on Skia where we see the Control bouncing on the screen.
=> fix(skia): MediaPlayerElement rendering

src/Uno.UWP/Media/Playback/MediaPlayer.Apple.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/1052
- Bugfix
MediaPlayer on iOS does not keep the last frame and it resizes when the video ends.
=> fix(iOS): MediaPlayer resizing when video ends

src/Uno.UI.Runtime.Skia.WebAssembly.Browser/BrowserMediaPlayerExtension.cs, src/Uno.UI.Runtime.Skia.WebAssembly.Browser/BrowserMediaPlayerPresenterExtension.cs, src/Uno.UI.Runtime.Skia.WebAssembly.Browser/BrowserNativeElementHostingExtension.cs, src/Uno.UI.Runtime.Skia.WebAssembly.Browser/UI/Xaml/Controls/WebView/BrowserWebViewProvider.cs, src/Uno.UI.Runtime.Skia.WebAssembly.Browser/WebAssemblyBrowserHost.cs, src/Uno.UI.Runtime.Skia.WebAssembly.Browser/ts/Runtime/BrowserNativeElementHostingExtension.ts, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_BrowserHtmlElement.cs, src/Uno.UI/NativeElementHosting/BrowserHtmlElement.cs, src/Uno.UI/NativeElementHosting/BrowserHtmlElement.reference.cs, src/Uno.UI/NativeElementHosting/BrowserHtmlElement.skia.cs, src/Uno.UI/NativeElementHosting/BrowserHtmlElement.wasm.cs, src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.cs, src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.wasm.cs, src/Uno.UI/ts/WindowManager.ts
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/879
- Bugfix
Align the DOM embedding APIs.
=> fix: Adjust native embedding support

src/Uno.UI.Runtime.Skia.MacOS/MacOSMediaPlayerPresenterExtension.cs, src/Uno.UI.Runtime.Skia.MacOS/UnoNativeMac/UnoNativeMac/UNOMediaPlayer.m
related to https://github.com/unoplatform/uno-private/issues/1052
- Bugfix
When the video player ends, the player will keep the last frame. This will match with the current iOS behaviour.
=> fix(macOS): Desktop MPE when player ends

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Flyout.cs, src/Uno.UI/UI/Xaml/Controls/Popup/PopupPanel.Placement.cs
GitHub Issue (If applicable): closes unoplatform/uno.chefs#1438
- Bugfix
On skia-everywhere ios, the full flyout placement doesnt match the space available to the app which extends into the status bar.
For skia-everywhere, the full flyout placement will match the space available to the app.
=> fix: skia flyout placement

src/Uno.UI.Runtime.Skia.AppleUIKit/UI/Xaml/RootViewController.cs, src/Uno.UI.Runtime.Skia.MacOS/MacOSWindowHost.cs
The newer `SkiaRenderHelper.RenderRootVisualAndReturnNegativePath` API returns an empty path, not `null`, if there's not clipping required.
This means we're doing extra work (and allocations) that are not needed.
If the path is empty we do not execute any clipping code.
=> chore: check is path is not empty (instead of null)

src/Uno.UI.Runtime.Skia.MacOS/MacOSWindowHost.cs
- Bugfix
With the recent [change](https://github.com/unoplatform/uno/pull/19898/files#diff-e32a31a7bea84a6a58b25e8799bf8283a41248bbf7360d8ff6c4941ea8bf3c7fR75) to `FocusManager.GetFocusedElement` all keystrokes on a Mac will beep (like it's invalid).
All accepted keys will not beep.
=> fix: avoid beeps for valid keystrokes on macOS

src/Uno.UI.Runtime.Skia.MacOS/MacOSMetalRenderer.cs, src/Uno.UI.Runtime.Skia.MacOS/MacOSWindowHost.cs, src/Uno.UI.Runtime.Skia.MacOS/NativeSkia.cs
Before Skia 3.x if was not possible to create instance of `GRBackendRenderTarget`, without reflection, when using the `netX.X` TFM.
`GRBackendRenderTarget` can now be created without the use of reflection.
=> perf(macOS): remove some reflection for Skia/Metal

src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.MetadataUpdate.cs, src/Uno.UI.RuntimeTests/Tests/HotReload/Frame/HRApp/Tests/Given_Popup.cs
closes https://github.com/unoplatform/uno.hotdesign/issues/3931
Fix HR not working in Popups
We update the visual tree only from the `window.Content`
We start updates from the real content root of the application
=> fix(hr): Fix HR not working in Popups

src/Uno.UI/UI/Xaml/Documents/TextFormatting/FontDetailsCache.skia.cs, src/Uno.UI/UI/Xaml/FontFamilyHelper.skia.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/1102
- Bugfix
`.manifest` stream is kept open
In case of iOS this is a problem, as the system does not allow keeping streams outside of some allowed filesystem locations open when the application is backgrounded.
=> fix: Avoid keeping font manifest stream open forever

doc/articles/getting-started/counterapp/get-started-counter-csharp-mvvm.md
The path of the logo asset references a non existent folder in the C#/MVVM Counter documentation.
The updated path allow the asset to load properly.
Was already fixed in the other Counter tutorial variants.
=> docs: fixing the logo asset path for the C#/MVVM Counter documentation

src/Uno.UI.RuntimeTests/Helpers/UITestHelper.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ComboBox.cs, src/Uno.UI/UI/Xaml/Controls/ComboBox/ComboBox.custom.cs
GitHub Issue (If applicable): closes #20014
- Bugfix
An initially collapsed ComboBox stays "open" when light-dismissed, prevent it from being opened again, until the focus is lost from the ComboBox forcing it to finally "close".
No more of that shenanigans...
=> fix(combobox): dismissed combo cannot be reopened

src/Uno.UI.Runtime.Skia.MacOS/MacOSWindowHost.cs, src/Uno.UI.Runtime.Skia.MacOS/NativeUno.cs, src/Uno.UI.Runtime.Skia.MacOS/UnoNativeMac/UnoNativeMac/UNOWindow.h, src/Uno.UI.Runtime.Skia.MacOS/UnoNativeMac/UnoNativeMac/UNOWindow.m
GitHub Issue (If applicable): closes https://github.com/unoplatform/private/issues/719
- Bugfix
Resetting the clip was not propagated to the native code.
* Reset clipping when it's removed.
* Only call (native) clip when the clipping path has changed.
Processing the subviews should not be needed, IOW only apply the clip on the parent view but it does not work ([like it does on iOS](https://github.com/unoplatform/uno/pull/20087)). This might be due to differences in `CALayer`, e.g. `NSViewBackingLayer` is used on macOS.
=> fix: reset native clipping on macOS

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.skia.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.skia.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/19591
=> fix(TextBox): fix MaxLength to work correctly with paste

src/Uno.UI.Runtime.Skia.MacOS/UnoNativeMac/UnoNativeMac/UNOWindow.m, src/Uno.UI.RuntimeTests/Tests/Microsoft_UI_Windowing/Given_AppWindow.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/1201
- Bugfix
There were two resize events coming from native code. One for Metal and another for the software fallback. However both were called and the one for the software fallback did not consider the window's title bar height (which is something done by default for the Metal one).
Correctly resize the window so that the bottom is not _cut_ (because we're missing the titlebar's height).
=> fix(macOS): fix resizing windows (bottom)

src/Uno.UI.RuntimeTests/Tests/Microsoft_UI_Xaml_Controls/Given_RefreshContainer.cs, src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.Managed.cs, src/Uno.UI/UI/Xaml/Internal/InputManager.Pointers.ManagedDirectManip.cs
closes https://github.com/unoplatform/uno-private/issues/899
Adjust behavior between InteractionTracker and DirectManipualtion
`ListView` and `RefreshContainer` are scrolling twice ... and are globally non functional
Collaborates nicely
=> fix: Adjust behavior between InteractionTracker and DirectManipulation

src/SourceGenerators/Uno.UI.Tasks/Content/Uno.UI.Tasks.targets
Ensures that the xaml trimming pass provides the proper parameters to the linker.
=> fix: Adjust for linker dependency ordering

Directory.Build.props, src/Uno.UI.Composition/Composition/Compositor.skia.cs, src/Uno.UI.RuntimeTests/Helpers/UITestHelper.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ScrollViewer.cs, src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.Managed.cs, src/Uno.UI/UI/Xaml/Internal/InputManager.Pointers.ManagedDirectManip.cs
closes https://github.com/unoplatform/uno-private/issues/1212
Fix inertia not behaving properly on nested scroll viewers
SCP are all trying to manage inertia simultaneously
SCP sync nicely
=> fix(scrollViewer): Fix inertia not behaving properly on nested scroll viewers

src/Uno.UI.Runtime.Skia.Android/AndroidCorePointerInputSource.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_VisualStateManager.cs, src/Uno.UI/UI/Xaml/Controls/Control/Control.crossruntime.cs, src/Uno.UI/UI/Xaml/FrameworkElement.Layout.crossruntime.cs, src/Uno.UI/UI/Xaml/VisualStateGroup.cs, src/Uno.UI/UI/Xaml/VisualStateManager.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/19364
=> fix(statetriggers): evaluate StateTriggers before the first layout cycle

src/Uno.UI.Runtime.Skia.Android/Uno.UI.Runtime.Skia.Android.csproj, src/Uno.UI.sln
GitHub Issue (If applicable): closes n/a
- Bugfix
When performing nuget-override for android with skia-renderer, the generated assemblies are not copied to the nuget cache folder.
^ they are now copied as part of the build process.
=> build: fix android nuget override not copying assemblies files
