unoplatform/uno

doc/articles/migrating-from-previous-releases.md

Minor format changes to uniformize format

docs: Update migrating-from-previous-releases.md

---

.editorconfig
src/Uno.Foundation/Uno.Core.Extensions/Uno.Core.Extensions/StringExtensions.cs
src/Uno.UI.RemoteControl/RemoteControlClient.cs
src/Uno.UI.RuntimeTests/IntegrationTests/common/TestServices.KeyboardHelper.cs
src/Uno.UI.TestComparer/Comparer/TestFilesComparer.cs
src/Uno.UI/UI/Xaml/Controls/PersonPicture/InitialsGenerator.cs
src/Uno.UI/UI/Xaml/Controls/WebView/UnoWKWebView.iOSmacOS.cs
src/Uno.UWPSyncGenerator/SyncGenerator.cs

build: Enable CA1304 (Specify CultureInfo)

---

doc/articles/features/AdaptiveTrigger.md
doc/articles/toc.yml

This document outlines Adaptive Triggers in a UWP application vs. an Uno application, and presents an example scenario with XAML code.
closes #9927 
Modification request to path uno/tree/master/doc/articles/features
This PR adds new documentation to the features folder

docs: Adaptive Triggers

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ListViewTests/UnoSamples_Tests.ListView.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListViewItem_Click_Focus.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListViewItem_Click_Focus.xaml.cs
src/Uno.UI/UI/Xaml/Controls/Primitives/SelectorItem.cs

GitHub Issue (If applicable): closes #10320 

fix: `SelectorItem` focus

---

src/Directory.Build.props
src/SourceGenerators/System.Xaml/Uno.Xaml.netcoremobile.csproj
src/Uno.CrossTargetting.props
src/netcore-build.props
src/uno.mobile-cross-targeting-disable.props

build: fix warning MSB4011 (props cannot be imported again. It was already imported)

---

build/TestLocalBuild.CMD

- Feature
When run TestLocalBuild  using local culture
When run TestLocalBuild  using English culture

chore: Ensure TestLocalBuild using English

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/AutoSuggestBoxTests/AutoSuggestBoxChosenSuggestion.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/AutoSuggestBoxTests/AutoSuggestBoxTestData.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/AutoSuggestBoxTests/AutoSuggestBox_Keyboard.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/AutoSuggestBoxTests/AutoSuggestBox_Keyboard.xaml.cs
src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/Repeater/RepeaterTests.cs
src/Uno.UI/UI/Xaml/Controls/AutoSuggestBox/AutoSuggestBox.cs

- Bugfix
Various features in `AutoSuggestBox` do not behave correctly.
Adjusted.

fix: `AutoSuggestBox` behavior improvements

---

.editorconfig

GitHub Issue (If applicable): closes #10143

chore: Add naming styles in editorconfig

---

build/Uno.WinUI.nuspec

VS is randomly complaining that dev version is used.

chore: Use stable SourceGenerationTasks in nuspec

---

src/SolutionTemplate/UnoLibraryTemplate.netcore/CrossTargetedLibrary.Netcore.vstemplate
src/SolutionTemplate/UnoLibraryTemplate/CrossTargetedLibrary.vstemplate
src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/UnoApp.netcore.vstemplate
src/SolutionTemplate/UnoSolutionTemplate.netcore/UnoApp.netcore.vstemplate
src/SolutionTemplate/UnoSolutionTemplate/UnoApp.vstemplate

GitHub Issue (If applicable): closes N/A
- Feature
Uno Platform templates don't show up when filtering for "Linux" platform
Showing up

feat: Add platform tags for Linux and Cloud on Uno templates

---

src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.Android.cs

GitHub Issue (If applicable): #8597 
Use static references to static constant native property.

perf: Cache textblock static native properties

---

.vsts-ci.yml
build/ci/.azure-devops-package-reference.yml
build/ci/.azure-devops-package-skia.yml
build/ci/.azure-devops-package-wasm.yml
build/ci/.azure-devops-package.yml
build/ci/templates/copy-package-assets.yml
build/ci/templates/linux-install-zip.yml
src/SamplesApp/SamplesApp.Skia.Gtk/SamplesApp.Skia.Gtk.csproj

ci: Move nuget package and skia generation to linux containers

---

build/ci/templates/gitversion.yml
gitversion.yml

- Adjust pullrequest target to avoid arbitrary searching of all available targets for version increments. GitVersion will search for a specific commit in all branches (fast), but not parse all branches for version increments (slow).
- Rename `stable` to `release` to avoid getting configuration errors where release is always defined.

ci: Adjust gitversion config

---

src/Uno.UI/UI/Xaml/Media/Imaging/RenderTargetBitmap.cs

fix: Fix NotImplemented attribute platforms for RenderTargetBitmap

---

build/Uno.UI.Build.csproj
src/SourceGenerators/Uno.UI.SourceGenerators/Uno.UI.SourceGenerators.csproj
src/SourceGenerators/Uno.UI.Tasks/Uno.UI.Tasks.csproj
src/Uno.Analyzers.Tests/Uno.Analyzers.Tests.csproj
src/Uno.UI.RemoteControl.Server.Processors/Uno.UI.RemoteControl.Server.Processors.csproj
src/Uno.UI.Tests.Performance/Uno.UI.Tests.Performance.csproj
src/Uno.UI.Tests.ViewLibrary/Uno.UI.Tests.ViewLibrary.csproj
src/Uno.UI.Tests.ViewLibraryProps/Uno.UI.Tests.ViewLibraryProps.csproj
src/Uno.UI.Tests/Uno.UI.Tests.csproj
src/Uno.UWPSyncGenerator/Uno.UWPSyncGenerator.csproj

chore: Cleanup and simplify few csproj files

---

src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/WinUI/UnoQuickStart.Windows.csproj

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/10398

chore: Update winui template to use WinAppSDK 1.2.221109.1

---

src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/MetadataUpdateTests/Given_HotReloadService.cs
src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/MetadataUpdateTests/Scenarios/When_Simple_Xaml_Add_xBind_Simple_Property_Update/0/p1/MainPage.xaml
src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/MetadataUpdateTests/Scenarios/When_Simple_Xaml_Add_xBind_Simple_Property_Update/0/p1/MainPage.xaml.cs
src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/MetadataUpdateTests/Scenarios/When_Simple_Xaml_Add_xBind_Simple_Property_Update/1/p1/MainPage.xaml
src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/MetadataUpdateTests/Scenarios/When_Simple_Xaml_Add_xBind_Simple_Property_Update/1/p1/MainPage.xaml.cs
src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/MetadataUpdateTests/Scenarios/When_Simple_Xaml_Single_xName_Change/0/p1/MainPage.xaml
src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/MetadataUpdateTests/Scenarios/When_Simple_Xaml_Single_xName_Change/0/p1/MainPage.xaml.cs
src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/MetadataUpdateTests/Scenarios/When_Simple_Xaml_Single_xName_Change/1/p1/MainPage.xaml
src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/MetadataUpdateTests/Scenarios/When_Simple_Xaml_Single_xName_Change/1/p1/MainPage.xaml.cs
src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/MetadataUpdateTests/Scenarios/When_Simple_Xaml_With_ThemeResource_Add/0/p1/MainPage.xaml
src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/MetadataUpdateTests/Scenarios/When_Simple_Xaml_With_ThemeResource_Add/0/p1/MainPage.xaml.cs
src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/MetadataUpdateTests/Scenarios/When_Simple_Xaml_With_ThemeResource_Add/1/p1/MainPage.xaml
src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/MetadataUpdateTests/Scenarios/When_Simple_Xaml_With_ThemeResource_Add/1/p1/MainPage.xaml.cs
src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/MetadataUpdates/HotReloadWorkspaceProvider.cs
src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/Uno.UI.SourceGenerators.netcore.Tests.csproj
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/Uno.UI.RemoteControl.Server.Processors/Uno.UI.RemoteControl.Server.Processors.csproj
src/Uno.UI.RemoteControl/buildTransitive/Uno.UI.RemoteControl.targets

GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/10478

Misc metadata updates changes

---

src/Uno.UI.RemoteControl.Server.Processors/HotReload/MetadataUpdates/WatchHotReloadService.cs
src/Uno.UI.RemoteControl.Server.Processors/HotReload/ServerHotReloadProcessor.MetadataUpdate.cs
src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.MetadataUpdate.cs
src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.Xaml.cs
src/Uno.UI.RemoteControl/HotReload/Messages/AssemblyDeltaReload.cs
src/Uno.UI.RemoteControl/HotReload/MetadataUpdater/MetadataUpdaterAgent.cs
src/Uno.UI.RemoteControl/HotReload/MetadataUpdater/UpdateDelta.cs
src/Uno.UI.RemoteControl/Uno.UI.RemoteControl.Skia.csproj

- Feature
Ensures that metadata update handlers are invoked on remote control driven scenarios.

feat: Adjust metadata update agent for explicit updates

---

.github/workflows/winui-autoconvert.yml
src/Directory.Build.props

Restore automatic generation after msbuild update

ci: Adjust winui convert action

---

src/SourceGenerators/SourceGeneratorHelpers/Helpers/Nullable.cs
src/Uno.UI.RemoteControl.Host/RemoteControlExtensions.cs
src/Uno.UI.RemoteControl.Host/RemoteControlServer.cs
src/Uno.UI.RemoteControl.Host/ServiceLocatorAdapter.cs
src/Uno.UI.RemoteControl.Host/Uno.UI.RemoteControl.Host.csproj
src/Uno.UI.RemoteControl.Server.Processors/HotReload/MetadataUpdates/CompilationWorkspaceProvider.cs
src/Uno.UI.RemoteControl.Server.Processors/HotReload/ServerHotReloadProcessor.MetadataUpdate.cs
src/Uno.UI.RemoteControl.Server.Processors/HotReload/ServerHotReloadProcessor.cs
src/Uno.UI.RemoteControl.Server.Processors/Uno.UI.RemoteControl.Server.Processors.csproj
src/Uno.UI.RemoteControl.Server/Uno.UI.RemoteControl.Server.csproj
src/Uno.UI.RemoteControl/Helpers/WebSocketHelper.cs
src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.MetadataUpdate.cs
src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.Xaml.cs
src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.cs
src/Uno.UI.RemoteControl/HotReload/Messages/AssemblyDeltaReload.cs
src/Uno.UI.RemoteControl/HotReload/Messages/FileReload.cs
src/Uno.UI.RemoteControl/HotReload/Messages/XamlLoadError.cs
src/Uno.UI.RemoteControl/RemoteControlClient.cs
src/Uno.UI.RemoteControl/Uno.UI.RemoteControl.Reference.csproj
src/Uno.UI.RemoteControl/Uno.UI.RemoteControl.Skia.csproj
src/Uno.UI.RemoteControl/Uno.UI.RemoteControl.Wasm.csproj
src/Uno.UI.RemoteControl/Uno.UI.RemoteControl.csproj
src/Uno.UI.RemoteControl/Uno.UI.RemoteControl.netcoremobile.csproj

GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/10478
- Bugfix
- Enables NRT for remote control assemblies
- Fix invalid deserialization for changed types
- Run metadata updates on Dispatcher

Misc remote control updates

---

build/TestLocalBuild.CMD
build/Uno.UI.Build.csproj

GitHub Issue (If applicable): closes #10356
- Bugfix

chore:  fix TestLocalBuild error: MSB4044

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_MenuFlyout.cs

GitHub Issue (If applicable): #9282

test: Disable failing macOS flyout test

---

src/SamplesApp/Directory.Build.props
src/SamplesApp/Directory.Build.targets
src/SamplesApp/SamplesApp.UITests.Generator/Uno.Samples.UITest.Generator.csproj
src/SamplesApp/SamplesApp.UnitTests.Shared/SamplesApp.UnitTests.targets
src/Uno.UI.sln

Ensure that Uno.Samples.UITest.Generator build before SamplesApp.Droid when build from IDE
- Bugfix

chore: Ensure that Uno.Samples.UITest.Generator build before all SamplesApp projects

---

src/AddIns/Uno.UI.Lottie/AssemblyInfo.cs
src/AddIns/Uno.UI.Lottie/Uno.UI.Lottie.Wasm.csproj
src/SourceGenerators/Uno.UI.SourceGenerators/BindableTypeProviders/DependencyObjectAvailabilityGenerator.cs
src/Uno.UI/DataBinding/BindingPropertyHelper.FastConvert.cs
src/Uno.UI/FeatureConfiguration.cs
src/Uno.UI/UI/Xaml/Automation/AutomationProperties.cs
src/Uno.UI/UI/Xaml/FrameworkElementExtensions.cs
src/Uno.UI/UI/Xaml/Media/ImageSource.cs
src/Uno.WinUIRevert/Program.cs

Adds various pre-checks for linker hint substitutions to improve XAML trimming. 

perf: Misc linker hints updates

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs

- Bugfix
Fixes sourcegeneration tests project.

fix(reg): Adjust generation for missing x:Class

---

src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.Xaml.cs

GitHub Issue (If applicable): closes #10549

fix: Unwrap `TargetInvocationException`

---

src/SourceGenerators/SourceGeneratorHelpers/Helpers/SymbolExtensions.cs

If any caller intends to not include current, then `ITypeSymbol.AllInterfaces` should be used instead.

refactor: Remove unneeded parameter

---

src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props

- Bugfix
Fix preview support for C# LangVersion property.

fix(reg): adjust for C# preview support

---

doc/articles/features/working-with-cookies.md

docs: Explain WASM-specific namespace usage

---

src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/ImplementedRoutedEventsGeneratorTests/Given_ImplementedRoutedEventsGenerator.cs

test: Remove `UIElementGeneratedProxy` stub from test

---

build/cSpell.json
build/uno.winui.common.targets
doc/articles/features/using-il-linker-webassembly.md
src/SourceGenerators/Uno.UI.Tasks/Content/Uno.UI.Tasks.targets
src/Uno.Foundation/Extensions/LinkerAttributes.cs
src/Uno.UI/LinkerDefinition.Wasm.xml
src/Uno.UI/LinkerSubstitution.Wasm.xml
src/Uno.UI/UI/Xaml/DragDrop/DragDropExtension.wasm.cs
src/Uno.UI/Uno.UI.Wasm.csproj
src/Uno.UI/ts/Windows/ApplicationModel/DataTransfer/DragAndDropExtension.ts

- Feature
Provide the ability to disable external drag and drop support for size constraints.

perf(wasm): Enable trimming for external drag and drop

---

src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/Verifiers/CSGenerator.cs

test: Simplify generator tests

---

src/Uno.Foundation/Extensions/LinkerAttributes.cs

Addresses https://github.com/unoplatform/uno/pull/10561/files#r1033263443

chore: Remove unnecessary `#if`

---

src/SourceGenerators/Uno.UI.SourceGenerators.Internal/DependencyObject/DependencyPropertyGenerator.cs

GitHub Issue (If applicable): closes #10582

perf: Use records instead of record structs for large SG models

---

src/Uno.UI/UI/Xaml/IFrameworkElement.cs

Remove unconditional dependency on `FlyoutBase` to make it trimmable.

perf(trimming): Break static dependency on FlyoutBase

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs

- Bugfix
Includes top-level `ControlTemplate` as candidates for XAML trimming.

fix(xamltrim): Trim trop-level ControlTemplate as resource key

---

src/Uno.UWP/Helpers/ProtocolActivation.wasm.cs

perf: Reduce allocations in `RegisterCustomScheme`

---

build/cSpell.json
doc/articles/guides/community-tutorials.md

- Other... Please describe: Community Blog post for Advocacy Contribution
**For Hacktoberfest 2022**: Posted a blog, https://ronicasingh.hashnode.dev/introduction-to-uno-platform
Additional Comments: I have no idea if I'm doing this right, generally I know how to do pull requests, but the rules or instructions to follow to do a "PR" for an Advocacy Contribution is a little confusing.  I did go to the "Community Tutorials" link but I was not sure what I did was actually the correct procedure to follow.

docs: Created blog post for Uno beginners

---

doc/articles/guides/community-tutorials.md

- Other... Please describe: Blog article for Advocacy contribution
Well, I'm doing this right hopefully this time, went through the previous comments help, thank you to all who did try to assist me. 
Also, If this article is not permissible, it would be good for me to know as soon as possible so I can make sure I can complete my 4 PRs for Hacktoberfest before it ends.

docs: Adding Second blog article for Uno applications

---

doc/articles/guides/community-tutorials.md

- Other... Please describe: Blog article for Advocacy contribution 
For Hacktoberfest2022

docs: Adding blog article about fluent app design

---

src/UnoItemTemplate/TemplatedControl.UWP/CustomControl.cs
src/UnoItemTemplate/TemplatedControl.WinUI/CustomControl.cs

GitHub Issue (If applicable): closes #10565

fix: Add partial keyword to CustomControl.cs at TemplateControl

---

src/Uno.UWP/Networking/Connectivity/ConnectionProfile.Android.cs

fix(Android): `NetworkInformation` under VPN

---

src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/Mobile/Mobile.winui.netcore.vstemplate
src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/Mobile/UnoQuickStart.Mobile.csproj
src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/Mobile/iOS/Main.iOS.cs
src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/Mobile/macOS/Main.macOS.cs
src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/Shared/App.xaml.cs

* rename `Main[.macOS].cs` to match other platforms and make its content closer to iOS and Catalyst versions
* add missing tab inside `Main.iOS.cs`
* simplify cast inside `App.xaml.cs` to avoid IDE warnings
* set `TrimMode` to `link` for macOS to match the behavior of legacy Xamarin.Mac apps (and get extra optimizations)
- Compatibility (with legacy Xamarin.Mac apps)
There's some inconsistencies between templates.
Eliminate the inconsistencies.

chore: misc update templates for net6+ mobile

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Media_Animation/DoubleAnimation_Tests.FinalState_Opacity.cs

chore: Temporarily disable `When_Opacity_Paused_With_FillBehaviorHold`

---

src/Uno.UI.RuntimeTests/Tests/Microsoft_UI_Xaml_Controls/Given_NavigationView.cs
src/Uno.UI.RuntimeTests/Tests/Microsoft_UI_Xaml_Controls/Given_TreeView.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/When_ThemeResource_Binding_In_Template_UserControl.xaml
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/When_ThemeResource_Binding_In_Template_UserControl.xaml.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/When_xLoad_Visibility_While_Materializing.xaml
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/When_xLoad_Visibility_While_Materializing.xaml.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/FramePages/Page_With_AppBarButton_Visibility_Bound.xaml
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/FramePages/Page_With_AppBarButton_Visibility_Bound.xaml.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_AppBarButton.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_NavigationView.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/ListViewPages/ListViewBoundSelectionPage.xaml
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/ListViewPages/ListViewBoundSelectionPage.xaml.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/ListViewPages/ListViewCollectionViewSourcePage.xaml
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/ListViewPages/ListViewCollectionViewSourcePage.xaml.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/ListViewPages/ListViewTemplateOuterBindingPage.xaml
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/ListViewPages/ListViewTemplateOuterBindingPage.xaml.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media_Animation/Given_ObjectAnimationUsingKeyFrames.cs

GitHub Issue (If applicable): closes #10659
- Refactoring (no functional changes, no api changes))
Some classes have too long namespaces + names, which causes issues for source generators when trying to output the results

refactor: Shorten namespaces for long class names in runtime tests

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs

- Bugfix
Fixes a regression when using XAML event handlers and C# 7.3 (can be found in older templates with WPF.Host project)

fix(reg): Don't use shadow parameters for C# 7.3

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Border.cs
src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.skia.cs

GitHub Issue (If applicable): closes #10670, closes #10484

fix: Ensure clipping when corner radius is set

---

src/SourceGenerators/Uno.UI.Tasks/Content/Uno.UI.Tasks.targets

- Bugfix
Adjust linker path for updated targets file when building for net5.0

fix(reg): restore xaml trimming for net5 or below

---

doc/articles/cross-targeted-libraries.md
doc/articles/interop/wasm-javascript-1.md

Related to https://github.com/unoplatform/uno/discussions/10647

docs: Adjust Wasm-specific runtime features

---

doc/articles/get-started.md

docs: Update get started

---

src/SamplesApp/UITests.Shared/Windows_UI_Xaml/DeferLoadStrategy/DeferLoadStrategyWithTemplateBinding.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/StyleTests/Style_Inline.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CalendarView/CalendarView_Theming.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/DateTimePicker/DateTimePicker.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Flyout/Flyout_Content_ThemeResource.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/FontTests/DynamicFont.xaml.cs

- Duplicate categories
No duplicates

refactor: Adjust sample categories

---

build/test-scripts/run-netcore-mobile-template-tests.ps1
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/Uno.ProjectTemplates.Dotnet.csproj
src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/Wasm/UnoQuickStart.Wasm.csproj

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/10726
- Bugfix
Ensures that the server template is built and validated properly, which validates that the proper conditionals are used when building from dotnet new create template.

fix(dotnetnew): Adjust Server template compilation conditionals

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media_Animation/Given_ObjectAnimationUsingKeyFrames.cs

chore: Disable flaky When_RepeatDuration test on Skia

---

doc/articles/guides/azure-static-webapps.md

docs: Remove Preview mentions for Azure deployment

docs: Remove Preview mentions for Azure deployment

---

src/SolutionTemplate/UnoSolutionTemplate.VSIX.2019/source.extension.vsixmanifest

docs: Adjust 2019 VSIX description for 2022 availability

---

doc/articles/Uno-UI-Performance.md

doc: Fix link from performance to profiling

---

build/Uno.WinUI.nuspec

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/10286
- Bugfix
Adds workaround older ILLinker issue for custom debug information that slows down build time.

fix(perf): Disable generated source embedded for xamarin targets to avoid linker performance issue

---

src/Uno.UI/UI/Xaml/Markup/Reader/XamlTypeResolver.cs

Quite minor change. I was searching for all references of this property to revise something and turned out it's only used in this class

chore: Make property used only in the same class private

---

src/Uno.UI.Tests/BinderTests/Given_Binder.cs
src/Uno.UI.Tests/Windows_UI_Xaml/Controls/When_StaticResource_And_VisualState_Setter_ClearValue.xaml
src/Uno.UI.Tests/Windows_UI_Xaml/Controls/When_StaticResource_And_VisualState_Setter_ClearValue.xaml.cs
src/Uno.UI.Tests/Windows_UI_Xaml/Controls/When_TemplateBinding_And_VisualState_Setter_ClearValue.xaml
src/Uno.UI.Tests/Windows_UI_Xaml/Controls/When_TemplateBinding_And_VisualState_Setter_ClearValue.xaml.cs
src/Uno.UI.Tests/Windows_UI_Xaml/Given_ThemeResource.cs
src/Uno.UI/UI/Xaml/DependencyObjectStore.cs

GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/9640
- Bugfix
Ensures that `DependencyObject.ClearValue` is properly clearing any Binding done on the same property.

fix(dependencyobject): Clear binding on ClearValue

---

build/ci/.azure-devops-unit-tests.yml
src/Uno.UI/UI/Xaml/Markup/Reader/XamlConstants.cs

- Bugfix
Using the `Color` type is now properly supported for the WinUI targets.

fix(XamlReader): Fix invalid Windows.UI lookups

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.cs

test: Remove always-true `#if` directive

---

build/Uno.WinUI.nuspec

GitHub Issue (If applicable): closes #10835

fix: Remove unsupported TFMs from WinUI package

---

.github/dependabot.yml
doc/articles/contributing/guidelines/updating-dependencies.md

GitHub Issue (If applicable): closes #10843

chore(deps): Let dependabot handle Com.Airbnb.Android.Lottie

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Flyout.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBlock.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ToolTip.cs
src/Uno.UI/Extensions/DependencyObjectExtensions.mux.depends.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls.Primitives/FlyoutBase.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Documents/TextElement.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/NumberBox/NumberBox.Properties.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/SplitButton/SplitButton.properties.cs
src/Uno.UI/UI/Xaml/Controls/Flyout/FlyoutBase.XamlRoot.cs
src/Uno.UI/UI/Xaml/Controls/Flyout/FlyoutBase.cs
src/Uno.UI/UI/Xaml/Controls/Popup/Popup.WithPopupRoot.cs
src/Uno.UI/UI/Xaml/Controls/ToolTip/ToolTip.cs
src/Uno.UI/UI/Xaml/Documents/TextElement.XamlRoot.cs
src/Uno.UI/UI/Xaml/UIElement.Properties.cs
src/Uno.UI/UI/Xaml/XamlRoot.cs

GitHub Issue (If applicable): closes #10833
- Bugfix

fix: `Popup`, `Flyout`, and `TextElement` `XamlRoots`

---

src/SamplesApp/SamplesApp.UWP.Design/SamplesApp.UWP.Design.csproj
src/SamplesApp/SamplesApp.UWP/SamplesApp.UWP.csproj
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.UWP/BlankApp.Uwp.csproj
src/SolutionTemplate/UnoSolutionTemplate.netcore/UWP/UnoQuickStart.Uwp.csproj
src/SolutionTemplate/UnoSolutionTemplate/UWP/UnoQuickStart.Uwp.csproj
src/SourceGenerators/System.Xaml/System.Xaml-net_4_x.csproj
src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.csproj
src/Uno.UI.Tests.Performance/Uno.UI.Tests.Performance.csproj
src/Uno.UI.Tests.ViewLibrary/Uno.UI.Tests.ViewLibrary.csproj
src/Uno.UI.Tests.ViewLibraryProps/Uno.UI.Tests.ViewLibraryProps.csproj
src/Uno.UI.Tests/BinderTests/Given_Binder.TargetNullValue.cs
src/Uno.UI.Tests/DependencyProperty/Given_DependencyProperty.Propagation.cs
src/Uno.UI.Tests/Uno.UI.Tests.csproj
src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_Converter_DataTemplate.xaml.cs
src/Uno.UWPSyncGenerator.Reference/Uno.UWPSyncGenerator.Reference.csproj

build: Remove few `NoWarn`s

---

src/AddIns/Uno.UI.Lottie/Uno.UI.Lottie.csproj
src/AddIns/Uno.UI.Svg/Uno.UI.Svg.csproj
src/Directory.Build.props
src/Directory.Build.targets
src/PlatformItemGroups.props
src/SourceGenerators/XamlGenerationTests.Core/XamlGenerationTests.Core.csproj
src/SourceGenerators/XamlGenerationTests/XamlGenerationTests.csproj
src/Uno.CrossTargetting.props
src/Uno.Foundation/Uno.Foundation.csproj
src/Uno.UI.BindingHelper.Android/Uno.UI.BindingHelper.Android.csproj
src/Uno.UI.BindingHelper.Android/Uno.UI.BindingHelper.Android.netcoremobile.csproj
src/Uno.UI.Composition/Uno.UI.Composition.csproj
src/Uno.UI.Dispatching/Uno.UI.Dispatching.csproj
src/Uno.UI.FluentTheme.v1/Uno.UI.FluentTheme.v1.csproj
src/Uno.UI.FluentTheme.v2/Uno.UI.FluentTheme.v2.csproj
src/Uno.UI.FluentTheme/Uno.UI.FluentTheme.csproj
src/Uno.UI.Foldable/Uno.UI.Foldable.csproj
src/Uno.UI.Foldable/Uno.UI.Foldable.netcoremobile.csproj
src/Uno.UI.Maps/Uno.UI.Maps.csproj
src/Uno.UI.RemoteControl/Uno.UI.RemoteControl.csproj
src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.Wasm.csproj
src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.csproj
src/Uno.UI.Toolkit/Uno.UI.Toolkit.csproj
src/Uno.UI.XamlHost/Uno.UI.XamlHost.csproj
src/Uno.UI/MixinGeneration.targets
src/Uno.UI/Uno.UI.Skia.csproj
src/Uno.UI/Uno.UI.csproj
src/Uno.UI/Uno.UI.netcoremobile.csproj
src/Uno.UWP/Uno.csproj
src/Uno.UWP/Uno.netcoremobile.csproj

build: Simplify platforms MSBuild properties

---

src/PlatformItemGroups.props

chore: Cleanup `PlatformItemGroups`

---

src/AddIns/Uno.UI.Lottie/LottieVisualSource.iOSmacOS.cs
src/AddIns/Uno.UI.Lottie/LottieVisualSourceBase.Android.cs

chore: Remove unused properties

---

src/Uno.UI.TestComparer/Uno.UI.TestComparer.csproj

I'm seeing these warnings locally:
Let's see if these references are not needed.

build: Remove references from `Uno.UI.TestComparer` that cause build warnings

---

src/SourceGenerators/System.Xaml/Uno.Xaml.Reference.csproj
src/SourceGenerators/System.Xaml/Uno.Xaml.csproj
src/SourceGenerators/System.Xaml/Uno.Xaml.netcoremobile.csproj

chore: Cleanup Uno.Xaml csprojs

---

doc/articles/features/app-close-handler.md
doc/articles/features/windows-applicationmodel-datatransfer.md
doc/articles/features/windows-storage-pickers.md
src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/Base/App.xaml.cs
src/SolutionTemplate/UnoSolutionTemplate.netcore/Shared/App.xaml.cs
src/SolutionTemplate/UnoSolutionTemplate/Shared/App.xaml.cs
src/Uno.UI/WinRT/Interop/InitializeWithWindow.cs
src/Uno.UI/WinRT/Interop/WindowNative.cs

feat: Add WinRT interop methods

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs

chore: Cleanup unused `_forceGeneration` field

---

src/PlatformItemGroups.props
src/Uno.CrossTargetting.props

**Recommend review with hidden whitespace changes.**

build: Cleanup define constants

---

src/SolutionTemplate/UnoSolutionTemplate/Droid/UnoQuickStart.Droid.csproj

This was fixed in https://github.com/xamarin/xamarin-android/commit/99ec9f231bc52b4e9c451b955f2493517afc1fc2#diff-db39bf07b89b50eaab8ab2001546310cR495

chore: Remove workaround for a fixed issue

---

src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props

chore: Delete workaround for fixed issue

---

src/SolutionTemplate/UnoSolutionTemplate.VSIX/UnoSolutionTemplate.VSIX.projitems
src/SourceGenerators/SourceGeneratorHelpers/SourceGeneratorHelpers.projitems
src/SourceGenerators/Uno.UI.SourceGenerators.Tests.Shared/Uno.UI.SourceGenerators.Tests.Shared.projitems
src/TargetFrameworkSelection.targets
src/Uno.UI.BindingHelper.Android/Uno.UI.BindingHelper.Android.csproj
src/Uno.UI.BindingHelper.Android/Uno.UI.BindingHelper.Android.netcoremobile.csproj
src/Uno.UI.Composition/Uno.UI.Composition.csproj
src/Uno.UI.Dispatching/Uno.UI.Dispatching.csproj
src/Uno.UI.RemoteControl/Uno.UI.RemoteControl.csproj
src/Uno.UI.XamlHost/Uno.UI.XamlHost.csproj
src/Uno.UI/Uno.UI.Reference.csproj
src/Uno.UI/Uno.UI.Skia.csproj
src/Uno.UI/Uno.UI.csproj
src/Uno.UI/Uno.UI.netcoremobile.csproj
src/Uno.UWP/Uno.csproj
src/Uno.UWP/Uno.netcoremobile.csproj
src/netcore-build-windows.props

I think all our builds are 17.x.
Conditions that compare `MSBuildVersion` against 16.x or 15.x look dead to me (except for the source generators props file that ships to customers)

build: Cleanup MSBuildVersion usages

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement_LayoutSlot.cs
src/Uno.UI/UI/Xaml/Controls/CalendarView/CalendarViewBaseItemChrome.cs
src/Uno.UI/UI/Xaml/Controls/ContentControl/ContentControl.Layout.cs
src/Uno.UI/UI/Xaml/FrameworkElementExtensions.cs
src/Uno.UI/UI/Xaml/UIElement.skia.cs
src/Uno.UI/UI/Xaml/UIElement.wasm.cs

Avoid deflating layout slot by border thickness twice

---

src/SamplesApp/SamplesApp.UITests/SampleControlUITestBase.cs

GitHub Issue (If applicable): closes #10897
- Bugfix

fix(CI): TakeScreenshot on Android

---

src/SourceGenerators/Uno.UI.SourceGenerators/Uno.UI.SourceGenerators.csproj

build: Reduce source generator dependencies

---

build/Uno.WinUI.nuspec

This should be in `analyzers/dotnet/cs` instead of `analyzers`.
Currently, this works since the .NET SDK doesn't strictly adhere to the expected path. But it's a good idea to just pack it correctly.

fix: Pack analyzers in `analyzers/dotnet/cs`

---

doc/articles/features/svg.md

GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/10940

docs: Adjust SVG for WebAssembly

---

src/Uno.CrossTargetting.props

Already set in Directory.Build.props

build: Cleanup duplicate properties

---

build/uno.winui.win.targets
src/SourceGenerators/SourceGeneratorHelpers/Helpers/PlatformHelper.cs
src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props

See discussion in https://github.com/unoplatform/uno.extensions/pull/1039

fix(uap): Fix generators should not run under uap builds

---

src/SourceGenerators/Uno.UI.SourceGenerators/Uno.UI.SourceGenerators.csproj
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/Uno.UI.RuntimeTests/Resources/en-US/TopLevelNamedRuntimeTests.resw
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/When_xUid.xaml
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/When_xUid.xaml.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_xUid.cs

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/10812
- Bugfix
Fixes the resolution of resw-defined resources when located in a separate assemby.

fix(resw): Adjust resources resolution

---

src/SourceGenerators/Uno.UI.Tasks/Content/Uno.UI.Tasks.targets

- Bugfix
Disables XAML trimming on linux/macos when using mono+msbuild to avoid this:
```
/Users/runner/.nuget/packages/uno.ui/4.7.0-dev.900/buildTransitive/Uno.UI.Tasks.targets(156,3): 
error MSB4216: Could not run the "LinkerDefinitionMergerTask_v6233eb01169e7267991cb814d9262815cb867772" task 
because MSBuild could not create or connect to a task host with runtime "CLR4" and architecture "x64".  
Please ensure that (1) the requested runtime and/or architecture are available on the machine, and (2)
that the required executable 
"/Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/MSBuild.exe" 
exists and can be run. [/Users/runner/work/1/s/src/library/Uno.Cupertino/Uno.Cupertino.csproj]
```
Please check if your PR fulfills …

fix(trimming): Disable XAML trimming on mono+OSX/Linux

---

build/Uno.WinUI.nuspec

Reference was removed in https://github.com/unoplatform/uno/commit/7cb9abdc87a7180872125dc623943e56b0a7c575 but was left in nuspec. This cleans that up.

fix(nuspec): Remove Mono.Cecil

---

build/Uno.WinUI.Lottie.nuspec

GitHub Issue (If applicable): related to #10854

chore: Update Android Lottie dependency in nuspec

---

src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props
src/Uno.UI.RemoteControl.Host/Uno.UI.RemoteControl.Host.csproj
src/Uno.UI.RemoteControl.Server.Processors/HotReload/MetadataUpdates/CompilationWorkspaceProvider.cs
src/Uno.UI.RemoteControl.Server.Processors/HotReload/ServerHotReloadProcessor.MetadataUpdate.cs
src/Uno.UI.RemoteControl.Server.Processors/Uno.UI.RemoteControl.Server.Processors.csproj
src/Uno.UI.RemoteControl.Server/Uno.UI.RemoteControl.Server.csproj
src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.cs

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/10886
- Bugfix
Ensures that project references are considered during remote control sessions.

Misc remote control fixes

---

src/SourceGenerators/Uno.UI.SourceGenerators/BindableTypeProviders/BindableTypeProvidersGenerationTask.cs

Some generated code is not used at runtime. The linker cannot remove it since it's added to the main assembly, which is not linked by default.
Less code is generated.
Older Uno code base had references to the removed generated code while newer/existing code does not.
There might be some indirect usage that I missed... Hopefully automated tests will shine light on them - if they exists.
Follow up from work on https://github.com/unoplatform/uno/pull/10851

fix: Remove unused generated code

---

src/SamplesApp/SamplesApp.UITests/TestFramework/ImageAssert.Validations.cs
src/Uno.UI.RuntimeTests/Helpers/RawBitmap.cs
src/Uno.UI.RuntimeTests/Helpers/RelativeCoords.cs

chore: Remove duplicate usings

---

doc/articles/guides/uno-material-walkthrough.md

Closing tag in Section 2 example code is not closing.
Closing tag is fixed and codesection is correct.

docs: Fix closing tag in code example

---

src/Uno.UI.FluentTheme.v1/FluentMerge.targets

fix: Restore ProgressRing.xaml

---

src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/DependencyObjectGeneratorTests/Given_DependencyObjectGenerator.cs
src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/ImplementedRoutedEventsGeneratorTests/Given_ImplementedRoutedEventsGenerator.cs
src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/Verifiers/CSGenerator.cs
src/SourceGenerators/Uno.UI.SourceGenerators/DependencyObject/DependencyObjectGenerator.cs
src/SourceGenerators/Uno.UI.SourceGenerators/ImplementedRoutedEvents/ImplementedRoutedEventsGenerator.cs

Removes the property added in #10771 and replaces it with a test-only focused approach.

test: Remove test-specific property IsUnitTest from generators

---

src/crosstargeting_override.props.sample

chore: Remove unused `IsUnoUIProject` property

---

build/ci/.azure-devops-android-tests.yml
build/ci/.azure-devops-docs.yml
build/ci/.azure-devops-ios-tests-run.yml
build/ci/.azure-devops-ios-tests.yml
build/ci/.azure-devops-macos.yml
build/ci/.azure-devops-package-generic.yml
build/ci/.azure-devops-package-net6-win.yml
build/ci/.azure-devops-package-reference.yml
build/ci/.azure-devops-package-skia.yml
build/ci/.azure-devops-package-wasm.yml
build/ci/.azure-devops-package.yml
build/ci/.azure-devops-samplesapp-uitests-build.yml
build/ci/.azure-devops-screenshot-compare.yml
build/ci/.azure-devops-skia-tests.yml
build/ci/.azure-devops-uap.yml
build/ci/.azure-devops-unit-tests.yml
build/ci/.azure-devops-vs2022-vsix.yml
build/ci/.azure-devops-wasm-uitests.yml
build/ci/.azure-devops-winui-convert.yml
build/ci/templates/generate-changelog.yml

ci: Always retry publishing artifacts

---

src/AddIns/Uno.UI.Svg/Uno.UI.Svg.netcoremobile.csproj
src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.netcoremobile.csproj

Adjust incorrect Analyzers inclusion caused by Uno.UI package circular reference.

fix(winui): Adjust WinUI build

---

src/Uno.UI/UI/Xaml/Documents/Inline.skia.cs

- Download master 42bd1d9228a8c0af17a62767532046dc994fa1c1
- Open Inline.skia.cs with Notepad++
- Go to line 112
- You can see like this:

fix: Invisible invalid char

---

build/uno.winui.common.targets
doc/articles/get-started-wizard.md
doc/articles/toc.yml
doc/articles/uno-notimplemented-types.md
src/Uno.Foundation/Metadata/ApiInformation.cs
src/Uno.UWPSyncGenerator/Generator.cs

- Feature
Adjust not implemented error messages to include documentation and directions when finding not implemented members.

feat(notimplemented): Update error messages to include a link for not implemented APIs

---

src/Uno.UI.Runtime.Skia.Gtk/GtkHost.cs

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/10927

fix(gtk): Add more descriptive message on initialization failure

---

src/Uno.UI.FluentTheme.v1/themeresources_v1.xaml

chore: Missing theme change

---

doc/articles/get-started-wizard.md
doc/articles/use-uno-check-inline-windows-noheader.md
doc/articles/use-uno-check-inline.md

docs: Include uno-check in welcome page

---

src/Uno.UI.RemoteControl/RemoteControlClient.cs

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/10652
- Bugfix

fix(remotecontrol): Explicitly await all connection tasks to avoid unobserved tasks exceptions

---

src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/MetadataUpdateTests/Given_HotReloadService.cs
src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/MetadataUpdateTests/Scenarios/When_Empty/Scenario.json
src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/MetadataUpdateTests/Scenarios/When_Simple_Xaml_Add_xBind_Function_Property_Add/Scenario.json
src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/MetadataUpdateTests/Scenarios/When_Two_Projects_Single_Code_File_With_Code_Update/Scenario.json
src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/MetadataUpdates/HotReloadWorkspaceProvider.cs
src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props
src/SourceGenerators/Uno.UI.SourceGenerators/RemoteControl/RemoteControlGenerator.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/GenerationRunFileInfo.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.MetadataUpdate.cs
src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.Xaml.cs
src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.cs
src/Uno.UI/UI/Xaml/FrameworkElement.Debugging.cs
src/Uno.UI/UI/Xaml/FrameworkElement.cs

Adjust metadata updates behavior.

chore: Adjust metadata updates

---

src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/ImplementedRoutedEventsGeneratorTests/Given_ImplementedRoutedEventsGenerator.cs
src/SourceGenerators/Uno.UI.SourceGenerators/ImplementedRoutedEvents/ImplementedRoutedEventsGenerator.cs

chore: Minor cleanup in `ImplementedRoutedEventsGenerator`

---

src/SamplesApp/SamplesApp.Droid/SamplesApp.Droid.csproj
src/SamplesApp/SamplesApp.UWP/SamplesApp.UWP.csproj
src/SamplesApp/SamplesApp.Wasm/SamplesApp.Wasm.csproj
src/SamplesApp/SamplesApp.iOS/SamplesApp.iOS.csproj
src/SamplesApp/SamplesApp.macOS/SamplesApp.macOS.csproj
src/SamplesApp/SamplesApp.netcoremobile/SamplesApp.netcoremobile.csproj
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.Droid/BlankApp.Droid.csproj
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.UWP/BlankApp.Uwp.csproj
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.Wasm/BlankApp.Wasm.csproj
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.iOS/BlankApp.iOS.csproj
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.macOS/BlankApp.macOS.csproj
src/SolutionTemplate/UnoSolutionTemplate.netcore/Wasm/UnoQuickStart.Wasm.csproj
src/SolutionTemplate/UnoSolutionTemplate/Wasm/UnoQuickStart.Wasm.csproj

fix(templates): Remove dead import conditions

---

src/Uno.UI/MixinGeneration.targets

chore: Simplify MixinGeneration.targets

---

src/Uno.UI/UI/Xaml/SpecializedResourceDictionary.cs

Related to https://github.com/xamarin/xamarin-android/issues/7736

fix(android): Workaround IntPtr.Size intrinsics on 32/64 bits differences

---

doc/articles/uno-development/building-uno-ui.md
src/crosstargeting_override.props.sample

@mrlacey some hints for performance

ci: Add hints to `OptimizeImplicitlyTriggeredBuild` in cross targeting override

---

build/Uno.WinUI.Lottie.nuspec
build/Uno.WinUI.RemoteControl.nuspec
src/AddIns/Uno.UI.Lottie/ThemableLottieVisualSource.Android.cs
src/AddIns/Uno.UI.Lottie/Uno.UI.Lottie.Reference.csproj
src/AddIns/Uno.UI.Lottie/Uno.UI.Lottie.csproj
src/AddIns/Uno.UI.Lottie/Uno.UI.Lottie.netcoremobile.csproj
src/Directory.Build.targets
src/SamplesApp/Directory.Build.props
src/SolutionTemplate/UnoSolutionTemplate.VSIX.2019/UnoSolutionTemplate.VSIX.2019.csproj
src/SolutionTemplate/UnoSolutionTemplate.VSIX.2022/UnoSolutionTemplate.VSIX.2022.csproj
src/SolutionTemplate/UnoUITestTemplate/UnoUITestsLibrary.csproj
src/Uno.UI.RemoteControl.Host/RemoteControlServer.cs
src/Uno.UI.RemoteControl.Host/Uno.UI.RemoteControl.Host.csproj
src/Uno.UI.RemoteControl.Server.Processors/HotReload/ServerHotReloadProcessor.cs
src/Uno.UI.RemoteControl.Server.Processors/Uno.UI.RemoteControl.Server.Processors.csproj
src/Uno.UI.RemoteControl.Server/Uno.UI.RemoteControl.Server.csproj
src/Uno.UI.RemoteControl.VS/Uno.UI.RemoteControl.VS.csproj
src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.cs
src/Uno.UI.RemoteControl/Uno.UI.RemoteControl.Reference.csproj
src/Uno.UI.RemoteControl/Uno.UI.RemoteControl.Skia.csproj
src/Uno.UI.RemoteControl/Uno.UI.RemoteControl.Wasm.csproj
src/Uno.UI.RemoteControl/Uno.UI.RemoteControl.csproj
src/Uno.UI.RemoteControl/Uno.UI.RemoteControl.netcoremobile.csproj

build: Unify Newtonsoft.Json dependency version

---

src/Uno.UI/WasmCSS/Uno.UI.css

Reference: https://webhint.io/docs/user-guide/hints/hint-css-prefix-order/

fix(css): Minor adjustment to make browser DevTools happier

---

build/uno.winui.winappsdk.targets

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/11011
- Bugfix
This changes explicitly includes PRI files and related assets in the referencing app, so that `ElevatedView` works properly.

fix: Restore ElevatedView support for WinAppSDK

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_WebView.cs
src/Uno.UI/UI/Xaml/Controls/WebView/WebView.cs

GitHub Issue (If applicable): closes #11089

fix(WebView): Fix 'WebView.Source' being null when 'Navigate' is called

---

src/SamplesApp/SamplesApp.UITests/Microsoft_UI_Xaml_Controls/NumberBoxTests/Given_NumberBox.Uno.cs
src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/NumberBoxTests/NumberBoxPage.xaml
src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/NumberBoxTests/NumberBoxPage.xaml.cs
src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/NumberBox/NumberBoxTests.cs
src/Uno.UI/Helpers/WinUI/ResourceAccessor.ResourceKeys.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/NumberBox/NumberBox.cs

chore(NumberBox): Update from latest MUX sources

---

build/Uno.WinUI.nuspec
src/Directory.Build.targets

chore: Bump to latest stable for Uno.Fonts.Fluent

---

src/Uno.UI/UI/Xaml/Controls/Control/Control.cs

GitHub Issue (If applicable): closes #11064, closes #11053, closes #11058
- Bugfix
First open of `CalendarDatePicker` correctly shows the month and year but doesn't show the days to choose from at all.
Second open incorrectly shows January 1923, but with all days shown.
The control works properly now as in Windows.

fix(CalendarDatePicker): Correctly display the CalendarView

---

build/ci/.azure-devops-docs.yml
src/Uno.UWPSyncGenerator/DocGenerator.cs

GitHub Issue (If applicable): closes #11120

docs: Fix documentation for obsolete types

---

src/Uno.UI/Microsoft/UI/Xaml/Controls/NumberBox/NumberBox.Properties.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/NumberBox/NumberBox.cs

GitHub Issue (If applicable): closes #11150

fix(NumberBox): Show full keyboard when AcceptsExpression is true

---

build/PackageDiffIgnore.xml
src/Uno.UI.Toolkit/ElevatedView.cs
src/Uno.UI/UI/Xaml/Controls/Control/Control.cs

GitHub Issue (If applicable): Related to #8339

fix!: `ElevatedView` shouldn't have CornerRadius as it exists in the base Control class.

---

src/Uno.UWP/ApplicationModel/SuspendingDeferral.cs

BREAKING CHANGE: Removed `SuspendingDeferral` constructor that takes an `Action`

fix!: Removed `SuspendingDeferral` constructor that takes an `Action`

---

src/Uno.UWP/Helpers/DeviceHelper.macOS.cs

Existing code for macOS version of `DeviceHelper` can be simplified.
Simpler implementation for net6+
> Environment.OSVersion returns the actual OS version.
>
> Environment.OSVersion now returns the public-facing OS version (for instance 12.3.1 for macOS), instead of the version of the kernel (which would be 21.4.0.0 for macOS 12.3.1).
reference: https://github.com/xamarin/xamarin-macios/wiki/Breaking-changes-in-.NET#environmentosversion-returns-the-actual-os-version

chore(macOS): simplify `DeviceHelper` for net6+

---

src/Uno.UI.Runtime.Skia.Gtk/Uno.UI.Runtime.Skia.Gtk.csproj

chore: Remove unneeded import

---

build/ci/.azure-devops-package-generic.yml
build/ci/.azure-devops-package-net6-win.yml
build/ci/.azure-devops-package-reference.yml
build/ci/.azure-devops-package-skia.yml
build/ci/.azure-devops-package-wasm.yml
build/ci/.azure-devops-package.yml
build/ci/.azure-devops-unit-tests.yml

This should reduce the size to be downloaded by some `DownloadBuildArtifacts` steps.

ci: Split CI artifacts into UWP and WinUI

---

src/Uno.UI/Directory.Build.targets

chore(deps): Update BannedApiAnalyzer and mark it private

---

src/Uno.UI.Toolkit/Uno.UI.Toolkit.Reference.csproj
src/Uno.UI/Uno.UI.Reference.csproj

chore: Cleanup duplicate UnoRuntimeIdentifier properties

---

src/Uno.UI-Wasm-only.slnf
src/Uno.UI-iOS-hotreload-vsix-only.slnf
src/Uno.UI-iOS-only.slnf
src/Uno.UI-macOS-only.slnf

chore: Remove Uno.UI.BindingHelper.Android from non-Android filters

---

doc/articles/feature-flags.md
src/Uno.UI/FeatureConfiguration.cs
src/Uno.UI/UI/Xaml/Controls/ComboBox/ComboBox.cs
src/Uno.UI/UI/Xaml/Controls/Popup/Popup.Base.cs
src/Uno.UI/UI/Xaml/Controls/Popup/PopupPanel.cs

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/10339
- Bugfix

fix: Disallow `ComboBox` popup under translucent status bar

---

build/ci/.azure-devops-package-net6-win.yml

A `true`/`false` in the name is not clear enough. This uses `UWP`/`WinUI` instead.

ci: Use better name for binlog

---

src/Uno.UWP/Devices/Lights/Lamp.Android.cs

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/11177

feat(Lamp): Support setting Brightness on Android 13 and later

---

src/SamplesApp/SamplesApp.netcoremobile/MacOS/Info.plist

- Bugfix
SampleApp for macOS (net6+) fails to build since the minimum version of the `Info.plist` is much older than what the SDK supports.
```
MacOS/Info.plist : error : The LSMinimumSystemVersion value in the Info.plist (10.11) does not match the SupportedOSPlatformVersion value (10.14) in the project file (if there is no SupportedOSPlatformVersion value in the project file, then a default value has been assumed). Either change the value in the Info.plist to match the SupportedOSPlatformVersion value, or remove the value in the Info.plist (and add a SupportedOSPlatformVersion value to the project file if it doesn't already exist). [/xxx/uno/src/SamplesApp/SamplesApp.netcoremobile/SamplesApp.netcoremobile.c …
```

fix: bump minimum macOS version for SampleApp

---

doc/articles/guides/native-frame-nav-tutorial.md
doc/articles/uno-development/working-with-the-samples-apps.md

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/11236

docs: Adjust naming for new page wizard

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_CalendarDatePicker.cs

GitHub Issue (If applicable): closes #11186

test: Add test for CalendarDatePicker

---

.github/workflows/winui-autoconvert.yml

Hopefully, there will be no warnings.

ci: Update winui-autoconvert.yml

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/ResourceCollection.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.ResourceCacheKey.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.Reflection.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/SourceGenerators/Uno.UI.Tasks/Content/Uno.UI.Tasks.targets
src/SourceGenerators/Uno.UI.Tasks/ResourcesGenerator/ResourcesGenerationTask.cs
src/Uno.UI.RuntimeTests/Tests/Windows_ApplicationModel_Resources/Given_ResourceLoader.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/When_xUid.xaml
src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.Skia.csproj
src/Uno.UI.Tests/ResourceLoader/Given_ResourceLoader.cs
src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XUidTests/Given_xUid.cs
src/Uno.UI/DirectUI/DXamlCore.cs
src/Uno.UI/Helpers/WinUI/ResourceAccessor.cs
src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePicker.cs
src/Uno.UI/UI/Xaml/Controls/WebView/UnoWKWebView.iOSmacOS.cs
src/Uno.UWP/Storage/StorageProvider.cs

fix(resources): Adjust resources from separate assemblies

---

build/ci/.azure-devops-docs.yml
build/ci/.azure-devops-ios-tests.yml
build/ci/.azure-devops-macos.yml
build/ci/.azure-devops-package-generic.yml
build/ci/.azure-devops-package-net6-win.yml
build/ci/.azure-devops-project-template-tests.yml
build/ci/.azure-devops-skia-tests.yml
build/ci/.azure-devops-uap.yml
build/ci/.azure-devops-unit-tests.yml
build/ci/.azure-devops-vs2022-vsix.yml
build/ci/.azure-devops-wasm-uitests.yml

Try to consolidate the name of the jobs with following format
`action` `plattform` `job description` eg:
'macOS Samples App Build' -> 'Build macOS Samples App'

ci: Consolidate the name of the jobs

---

doc/import_external_docs.ps1

Update Uno.Themes documentation to include PipsPager details

docs: Update Uno.Themes documentation

---

build/uno.winui.common.targets
src/AddIns/Uno.UI.Svg/SvgProvider.cs
src/SamplesApp/SamplesApp.iOS/SamplesApp.iOS.csproj

GitHub Issue (If applicable): closes #10766
- Bugfix

Include System.Memory workaround for all Xamarin.iOS projects

---

doc/articles/features/custom-fonts.md

What kind of change does this PR introduce? 
- Documentation content changes 
Duplicated text
Removed duplicated Text

duplicated text at docs

---

src/Uno.UWP/UI/Color.cs

Helps the linker eliminate more code and metadata. E.g. the `A` property and the `get_A` method are not referenced by `IsTransparent` anymore.
Properties and `getter` methods cannot be removed by the linker since they are used in the code, e.g. `ToString` reference all of them
Fields are used, which means the `PropertyInfo` and `MethodInfo` associated with the fields can be removed by the linker (if not used outside the the type).

chore: use the fields, instead of getters, inside `Color` code

---

src/Uno.UWP/Microsoft/UI/DisplayId.cs
src/Uno.UWP/Microsoft/UI/IconId.cs
src/Uno.UWP/Microsoft/UI/WindowId.cs

Allow operator methods to be removed when `Equals` is used.
The linker has to include more code than what's really required.
`Equals(object)` is an override from `System.Object` so it will always be marked. `Equals(T)` is from `IEquatable<T>` and almost aways marked. 
Others should be trimmable by using the non-trimmable parts.

chore: make `[Display|Icon|Window]Id` more linker friendly

---

src/SamplesApp/UITests.Shared/Windows_Devices/Midi/MidiDeviceEnumeration.xaml
src/SamplesApp/UITests.Shared/Windows_Devices/Midi/MidiDeviceEnumeration.xaml.cs
src/Uno.UWP/Devices/Enumeration/Internal/Providers/Midi/MidiDeviceClassProviderBase.Android.cs

- Bugfix
Adjust MidiEnumeration sample to work around https://github.com/unoplatform/uno/issues/212

fix: restore midi enumeration sample

---

doc/articles/get-started-vsmac.md
doc/articles/toc.yml

GitHub Issue (If applicable): closes #11279

docs: Replace Visual Studio for Mac 2022 with Visual Studio 2022 for Mac

---

doc/articles/uno-development/contributing-intro.md

fix a broken link where a space in a file name hadn't been correctly URL encoded

doc: fix broken link

---

src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/MetadataUpdateTests/Given_HotReloadService.cs
src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/MetadataUpdateTests/Scenarios/When_Simple_Xaml_With_Three_Changes_And_Same_Hash/0/p1/MainPage.xaml
src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/MetadataUpdateTests/Scenarios/When_Simple_Xaml_With_Three_Changes_And_Same_Hash/0/p1/MainPage.xaml.cs
src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/MetadataUpdateTests/Scenarios/When_Simple_Xaml_With_Three_Changes_And_Same_Hash/1/p1/MainPage.xaml
src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/MetadataUpdateTests/Scenarios/When_Simple_Xaml_With_Three_Changes_And_Same_Hash/1/p1/MainPage.xaml.cs
src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/MetadataUpdateTests/Scenarios/When_Simple_Xaml_With_Three_Changes_And_Same_Hash/2/p1/MainPage.xaml
src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/MetadataUpdateTests/Scenarios/When_Simple_Xaml_With_Three_Changes_And_Same_Hash/2/p1/MainPage.xaml.cs
src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/MetadataUpdateTests/Scenarios/When_Simple_Xaml_With_Three_Changes_And_Same_Hash/Scenario.json
src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/Verifiers/XamlGenerator/CSGenerator.cs
src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props
src/SourceGenerators/Uno.UI.SourceGenerators/Uno.UI.SourceGenerators.csproj
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/GenerationInfo.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/GenerationInfoManager.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGenerator.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs

- Bugfix
Adjusts XAML generation to be idempotent in the context of metadata generation.

fix(xaml): Ensure generator idempotence

---

src/Uno.Foundation/ICommandExtensions.cs
src/Uno.UI.Toolkit/ElevatedView.cs

[feature/breaking-changes] chore: Add missing #endif

---

src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewMode.Commands.cs
src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewMode.Properties.cs
src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.cs
src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Controls/SampleChooserControl.xaml

fix: RecordAllTestsCommand

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBlock.cs
src/Uno.UI/UI/Xaml/Documents/InlineCollection.skia.cs

GitHub Issue (If applicable): closes #11322

fix(skia): Correctly handle SolidColorBrush opacity in inlines

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ComboBox.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelGenerator.managed.cs

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/11334
- Bugfix
Fixes incorrect parent panel when removed from the visual tree.

fix(VirtualizingPanel): Adjust for nullability constraints

---

build/PackageDiffIgnore.xml
src/Uno.UI/UI/Xaml/Style/Style.cs

BREAKING CHANGE: `RegisterDefaultStyleForType` methods were removed.

fix!: Remove unneeded `Style.RegisterDefaultStyleForType`

---

build/PackageDiffIgnore.xml
src/Uno.UI/Microsoft/UI/Xaml/Controls/PersonPicture/PersonPicture.cs
src/Uno.UI/UI/Xaml/Controls/Unsupported/PersonPictureAutomationPeer.cs

[feature/breaking-changes] chore: Fix error

---

src/Uno.UI/UI/Xaml/Controls/Popup/Popup.Legacy.cs
src/Uno.UI/UI/Xaml/Controls/Popup/Popup.cs

BREAKING CHANGE: `OnVerticalOffsetChanged` and `OnHorizontalOffsetChanged` are now private instead of virtual protected.

fix!: `OnVerticalOffsetChanged` and `OnHorizontalOffsetChanged` are no longer protected.

---

src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/WebView/WebView_WithHeaders.xaml.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_WebView.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/WebView.cs
src/Uno.UI/UI/Xaml/Controls/WebView/WebView.Android.cs
src/Uno.UI/UI/Xaml/Controls/WebView/WebView.cs
src/Uno.UI/UI/Xaml/Controls/WebView/WebView.iOSmacOS.cs

BREAKING CHANGE: WebView.NavigateWithHttpRequestMessage parameter type is now `Windows.Web.Http.HttpRequestMessage` instead of `System.Net.Http.HttpRequestMessage`
GitHub Issue (If applicable): #8339, closes #11099

fix!: Align WebView.NavigateWithHttpRequestMessage signature with UWP

---

src/Uno.UI/UI/Xaml/Controls/RelativePanel/RelativePanel.Properties.cs

fix!: Align RelativePanel methods parameter names

---

src/Uno.UI/UI/Xaml/ResourceDictionary.debugging.cs

build: Fix build failure regarding unused method

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement_EffectiveViewport.cs
src/Uno.UI/UI/Xaml/FrameworkElement.EffectiveViewport.cs

closes https://github.com/unoplatform/uno/issues/11333
Fix possible collection changed while enumerating in EVP propagation
Collection can be altered while enumerating it
A new collection is creating if an enumeration is pending

fix: Fix possible collection changed while enumerating in EVP propagation

---

src/Uno.UI/Extensions/ViewHelper.iOSmacOS.cs

BREAKING CHANGE: `ViewHelper.MainScreenScale` and `ViewHelper.IsRetinaDisplay` are removed in iOS and macOS

fix!: Remove `ViewHelper.MainScreenScale` and `ViewHelper.IsRetinaDisplay`

---

build/PackageDiffIgnore.xml

[feature/breaking-changes] chore: Update PackageDiffIgnore

---

src/Uno.UI.RuntimeTests/Helpers/RectAssert.cs

When `AssertRect.AreEqual()` fails, it will not specify which one of the measurements did not match.
| Before | After |
| :-----: | :------: |
|![image](https://user-images.githubusercontent.com/1900897/219876814-6bd53d73-3af7-4a71-bd4d-f8a928a3c41b.png) |![image](https://user-images.githubusercontent.com/1900897/219876831-48ddb01d-93d0-411b-88c7-00269bc2286e.png)|

chore: update RectAssert.AssertTrue() error message

---

src/Uno.UI.Tests/Windows_UI_XAML_Controls/BorderTests/Given_Border.cs
src/Uno.UI.Tests/Windows_UI_XAML_Controls/CanvasTests/Given_Canvas.cs
src/Uno.UI.Tests/Windows_UI_XAML_Controls/GridTests/GivenGrid_And_Alignment.cs
src/Uno.UI.Tests/Windows_UI_XAML_Controls/GridTests/GivenGrid_And_AutoSized.cs
src/Uno.UI.Tests/Windows_UI_XAML_Controls/GridTests/GivenGrid_And_Margin.cs
src/Uno.UI.Tests/Windows_UI_XAML_Controls/GridTests/Given_Grid.cs
src/Uno.UI.Tests/Windows_UI_XAML_Controls/StackPanelTest/Given_StackPanel.cs
src/Uno.UI.Tests/Windows_UI_Xaml/Input/Focus/Given_FocusSelection.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/ItemContainerHolderAdapter.Android.cs
src/Uno.UI/UI/Xaml/FrameworkElement.Android.cs
src/Uno.UI/UI/Xaml/FrameworkElement.Interface.net.cs
src/Uno.UI/UI/Xaml/FrameworkElement.Interface.netstdref.cs
src/Uno.UI/UI/Xaml/FrameworkElement.Interface.wasm.cs
src/Uno.UI/UI/Xaml/FrameworkElement.iOSmacOS.cs
src/Uno.UI/UI/Xaml/FrameworkElement.skia.cs

BREAKING CHANGE: `FrameworkElement` constructors are now protected instead of public

fix!: Make `FrameworkElement` constructors protected.

---

src/Uno.UI/UI/Xaml/DependencyObjectStore.cs

GitHub Issue (If applicable): #8597 
perf: Reduce allocations during inherited properties propagation, removing an unused class creation.

perf: Reduce allocations during inherited properties propagation

---

doc/articles/guides/localization.md

fix(localization): avoid using deprecated property

---

src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/Uno.ProjectTemplates.Dotnet.csproj

When creating a new app with `dotnet new unoapp` and creating a repo within Visual Studio, VS sometimes tries to change the encoding to UTF8 later and shows the following when viewing csproj diff:
Hopefully this fixes that.

fix(templates): Use UTF8 for template files

---

src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/Skia.Gtk/UnoQuickStart.Skia.Gtk.csproj
src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/Skia.Linux.FrameBuffer/UnoQuickStart.Skia.Linux.FrameBuffer.csproj
src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/Skia.WPF/UnoQuickStart.Skia.WPF.csproj
src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/Views/UnoQuickStart.csproj
src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/Windows/UnoQuickStart.Windows.csproj

This avoids a NuGet error "detected package downgrade" when a reference to Uno.Material.WinUI is added.

fix(templates): Update `Microsoft.WindowsAppSDK` in templates

---

doc/articles/features/svg.md

docs: Add more info on displaying SVG image

---

build/PackageDiffIgnore.xml
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Automation.Peers/PersonPictureAutomationPeer.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/PersonPicture.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/WebView.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Media/Shadow.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Media/ThemeShadow.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml/UIElement.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml/UIElementWeakCollection.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.UI.Core/CoreIndependentInputSourceController.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Web.Http.Headers/HttpRequestHeaderCollection.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Web.Http/HttpMethod.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Web.Http/HttpRequestMessage.cs

chore: Update package diff ignore

---

build/Uno.UI.Build.csproj
build/uno.winui.common.targets
build/uno.winui.winappsdk.targets
doc/articles/get-started-dotnet-new.md
doc/articles/guides/how-to-create-control-libraries.md
doc/articles/toc.yml
doc/articles/uno-build-error-codes.md
src/SourceGenerators/Uno.UI.Tasks/WinAppSDKValidations/ValidateWinAppSDKReferences.cs

fix: Show an error message when incompatible winappsdk to net7.0 with uno is found

---

doc/articles/features/using-skia-wpf.md
src/SamplesApp/SamplesApp.Shared/App.xaml.cs
src/SamplesApp/SamplesApp.Skia.WPF/App.xaml.cs
src/Uno.UI.Runtime.Skia.Wpf/RenderSurfaceType.cs
src/Uno.UI.Runtime.Skia.Wpf/Rendering/IWpfRenderer.cs
src/Uno.UI.Runtime.Skia.Wpf/Rendering/OpenGLWpfRenderer.NativeMethods.cs
src/Uno.UI.Runtime.Skia.Wpf/Rendering/OpenGLWpfRenderer.cs
src/Uno.UI.Runtime.Skia.Wpf/Rendering/SoftwareWpfRenderer.cs
src/Uno.UI.Runtime.Skia.Wpf/WpfHost.cs
src/Uno.UI.XamlHost.Skia.Wpf/UnoXamlHostBase.host.cs

GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/4309, fixes https://github.com/unoplatform/uno/issues/10461
- Feature
Enable OpenGL acceleration for WPF head.

feat: Add support for WPF OpenGL acceleration

---

src/SamplesApp/UnoIslands.Shared/MainPage.xaml
src/SamplesApp/UnoIslands.Shared/MainPage.xaml.cs
src/Uno.UI/UI/Xaml/Controls/ContentDialog/ContentDialog.Visuals.cs
src/Uno.UI/UI/Xaml/Controls/ContentDialog/ContentDialogPopupPanel.cs
src/Uno.UI/UI/Xaml/Controls/Popup/Popup.WithPopupRoot.cs

Add support for `ContentDialog` in Uno Islands

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.Reflection.cs
src/SourceGenerators/XamlGenerationTests/NonExistingNamespace.xaml
src/SourceGenerators/XamlGenerationTests/XamlGenerationTests.csproj

GitHub Issue (If applicable): closes #11434

fix: Fallback to fuzzy matching properly

---

src/SourceGenerators/SourceGeneratorHelpers/Helpers/RoslynMetadataHelper.cs

This doesn't look to be used. Maybe it used to be there for some historical reasons.

chore: Remove GenerateAdditionalTypesMap

---

doc/articles/guides/how-to-create-control-libraries.md

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/11436

docs: Adjust control library creation

---

src/SamplesApp/UnoIslands.WPF/MainWindow.xaml
src/SamplesApp/UnoIslands.WPF/MainWindow.xaml.cs
src/Uno.UI.Runtime.Skia.Wpf/Rendering/OpenGLWpfRenderer.cs
src/Uno.UI.XamlHost.Skia.Wpf/UnoXamlHostBase.host.cs

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/11431
- Bugfix
Ensure proper render surface initialization, also when the control is loaded and unloaded.

fix(xamlhost): Ensure proper render surface initialization

---

build/PackageDiffIgnore.xml
src/Uno.UI.Foldable/FoldableApplicationViewSpanningRects.Android.cs
src/Uno.UI.Runtime.Skia.Wpf/WpfHost.cs
src/Uno.UI/FeatureConfiguration.cs
src/Uno.UI/UI/Xaml/Controls/WebView/WebView.iOSmacOS.cs
src/Uno.UI/UI/Xaml/VisibilityExtensions.cs
src/Uno.UWP/Devices/Sensors/Helpers/INativeDualScreenProvider.cs

BREAKING CHANGE: Some obsolete members are now removed.
GitHub Issue (If applicable): closes #11371, closes #11372, closes #11373, closes #11374, closes #11375, part of #8339

fix!: Remove obsolete members

---

.editorconfig
build/PackageDiffIgnore.xml
build/nVentive-generic.ruleset
src/Uno.Foundation.Runtime.WebAssembly/Interop/Runtime.wasm.cs
src/Uno.UI/Controls/BindableDrawerLayout.Android.cs
src/Uno.UI/FeatureConfiguration.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/StackLayout.Properties.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/Legacy/GridView.Android.cs
src/Uno.UI/UI/Xaml/Documents/TextElement.cs
src/Uno.UI/UI/Xaml/Media/ImageSource.cs
src/Uno.UI/UI/Xaml/UIElement.ThemeShadow.skia.cs
src/Uno.UWP/Devices/Sensors/SimpleOrientationSensor.cs
src/Uno.UWP/Graphics/Display/DisplayInformation.iOS.cs
src/Uno.UWP/Media/Playback/MediaPlayer.iOSmacOS.cs

feat: Enable Rule CA2211

---

src/Uno.UI/Microsoft/UI/Xaml/Controls/AnimatedIcon/AnimatedIcon.cs
src/Uno.UI/UI/Xaml/Media/PointCollection.cs

GitHub Issue (If applicable): closes #11455

fix: Use culture invariant float parsing

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs

Avoids generating empty `#if __WASM__` if `_isWasm` is true.

refactor: Improve __WASM__ not propagating generated check

---

src/SourceGenerators/SourceGeneratorHelpers/Helpers/RoslynMetadataHelper.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs

chore: Minor generator cleanup

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs

Misc xaml generator fixes

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs

perf: Avoid calling `ToString` twice on the same `StringBuilder`

---

src/Directory.Build.targets

chore(deps): Update `NUnit3TestAdapter` to `4.4.0`

---

src/SourceGenerators/SourceGeneratorHelpers/Helpers/SymbolExtensions.cs

refactor: Remove unneeded `_fullNamesMaping`

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs

Cleanup always false parameter

---

src/Uno.UI.XamlHost.Skia.Wpf/UnoXamlHostBase.cs
src/Uno.UWP/ApplicationModel/Resources/ResourceLoader.cs

- Bugfix
- Adjust for infinite loop when current culture is invariant
- Gracefully close when current active app is removed

Uno Islands adjustments for .NET Framework

---

src/SamplesApp/UnoIslands.Shared/App.xaml.cs
src/SamplesApp/UnoIslands.Shared/MainPage.xaml
src/Uno.UI/UI/Xaml/Controls/ToolTip/ToolTip.cs

feat: Add support for `ToolTip` in Uno Islands

---

src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/CommonStyles/CommonStylesTests.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/Primitives/CornerRadiusFilterConverter.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/Primitives/CornerRadiusFilterKind.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/Primitives/CornerRadiusToThicknessConverter.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/Primitives/CornerRadiusToThicknessConverterKind.cs

GitHub Issue (If applicable): closes #11477 
- Feature
- Refactoring
Not supported
Supported

feat: Add support for `Scale` in `CornerRadiusFilterConverter`

---

src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_Snap_Rubberband.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/PasswordBoxTests/PasswordBoxPage.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/PasswordBoxTests/PasswordBox_AutoFill.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/PasswordBoxTests/PasswordBox_iOS_DuplicatingText.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media_Imaging/RenderTargetBitmaps.xaml.cs

refactor: Cleanup of Samples app categories

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileParser.cs

perf: Avoid unnecessary `TrimEnd` call

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.Reflection.cs

fix: Fix XamlType lookup to correctly consider PreferredXamlNamespace

---

src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/GenerationInfo.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/GenerationInfoManager.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGenerator.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs

- Bugfix
Restore LoadComponent based XAML reload to work around EnC limitation.

chore: Adjust XAML code generation

---

src/SourceGenerators/Uno.UI.SourceGenerators/BindableTypeProviders/DependencyObjectAvailabilityGenerator.cs

perf(DependencyObjectAvailabilityGenerator): Avoid calculating property names twice

---

src/Uno.Foundation/Uno.Core.Extensions/Uno.Core.Extensions.Collections/WeakAttachedDictionary.cs
src/Uno.Foundation/Uno.Core.Extensions/Uno.Core.Extensions.Compatibility/Extensions/FuncAsyncExtensions.cs
src/Uno.Foundation/Uno.Core.Extensions/Uno.Core.Extensions/FuncMemoizeExtensions.cs

chore: Cleanup dead conditionals

---

build/PackageDiffIgnore.xml
src/Uno.UWP/Devices/Geolocation/Geolocator.Android.cs

GitHub Issue (If applicable): closes #11480

fix: Fix ObjectDisposedException crash in Geolocator on Android

---

build/ci/.azure-devops-screenshot-compare.yml
src/Directory.Build.props
src/Directory.Build.targets
src/SamplesApp/SamplesApp.UITests/SamplesApp.UITests.csproj
src/SourceGenerators/System.Xaml.Tests/Uno.Xaml.Tests.csproj
src/SourceGenerators/System.Xaml/Uno.Xaml.netcoremobile.csproj
src/SourceGenerators/Uno.UI.Tasks/Uno.UI.Tasks.csproj
src/Uno.Foundation.Logging/Uno.Foundation.Logging.netcoremobile.csproj
src/Uno.UI.TestComparer/Uno.UI.TestComparer.csproj

I think what happened is Azure is now using newer .NET SDK that includes 1.0.3 reference, and we are referencing 1.0.2, so:
```
D:\a\1\s\src\SourceGenerators\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.csproj error NU1605: Warning As Error: Detected package downgrade: Microsoft.NETFramework.ReferenceAssemblies.net461 from 1.0.3 to 1.0.2. Reference the package directly from the project to select a different version. 
Uno.UI.SourceGenerators -> Microsoft.NETFramework.ReferenceAssemblies 1.0.3 -> Microsoft.NETFramework.ReferenceAssemblies.net461 (>= 1.0.3) 
Uno.UI.SourceGenerators -> Microsoft.NETFramework.ReferenceAssemblies.net461 (>= 1.0.2) [D:\a\1\s\src\Uno.UI-Windows-only.slnf]
```
The other error is:
```
Build started 3/3/2023 6:52:51 PM.
Included response file: C:\Program …
```

ci: Unify Microsoft.NETFramework.ReferenceAssemblies to latest to fix CI failure

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs

chore: Remove unused setter in Xaml generated code

---

src/Directory.Build.props

chore: Remove workaround

---

src/SourceGenerators/SourceGeneratorHelpers/Helpers/RoslynMetadataHelper.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs

perf: Avoid using `GetAllTypesAttributedWith`

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.Reflection.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs

refactor: More Xaml generator cleanup

---

src/SourceGenerators/SourceGeneratorHelpers/Helpers/SymbolExtensions.cs
src/SourceGenerators/Uno.UI.SourceGenerators/BindableTypeProviders/BindableTypeProvidersGenerationTask.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.Reflection.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs

refactor: Adopt lazy symbols more and simplify

---

.github/workflows/winui-autoconvert.yml

Fixes the failure in https://github.com/unoplatform/uno/actions/runs/4330163250/jobs/7561203807

ci: Use global.json in WinUI conversion workflow

---

.github/workflows/winui-autoconvert.yml

ci: Update uno.check for WinUI auto convert

---

build/PackageDiffIgnore.xml
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlConstants.cs

[feature/breaking-changes] chore: Fix build

---

src/SamplesApp/UITests.Shared/Windows_Media/CameraCaptureUISample.xaml
src/SamplesApp/UITests.Shared/Windows_Media/CameraCaptureUISample.xaml.cs
src/Uno.UWP/Media/Capture/CameraCaptureUI.Android.cs

GitHub Issue (If applicable): closes #11394

feat: Support CameraCaptureUIMode.Video on Android

---

src/Uno.UI.Runtime.Skia.Wpf/Extensions/Storage/Pickers/FileOpenPickerExtension.cs

GitHub Issue (If applicable): Fixes #11517

fix: Correctly default to "all files" in WPF FileOpenPicker

---

src/Uno.Analyzers.Tests/UnoNotImplementedTests.cs
src/Uno.Analyzers.Tests/Verifiers/CSCodeFix+Test.cs
src/Uno.Analyzers/UnoNotImplementedAnalyzer.cs

I moved the modified tests to use raw string literals, so hide whitespaces for easier diff.

refactor: Remove test-specific code from UnoNotImplementedAnalyzer

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_AutoSuggestBox.cs
src/Uno.UI/UI/Xaml/Controls/AutoSuggestBox/AutoSuggestBox.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs

GitHub Issue (If applicable): closes #11635
- Bugfix
See issue.
Fixd'!

fix(AutoSuggestBox): Ensure correct text change Reason

---

src/Uno.UI.Runtime.Skia.Gtk/UI/Xaml/Controls/GtkTextBoxView.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/OverlayTextBoxView/OverlayTextBoxViewExtension.skia.cs

fix: Overlay input on GTK regressions

---

src/Uno.UI/UI/Xaml/Window.WinAppSdk.cs

feat: Add support for `Window.Title` in Uno.WinUI

---

doc/import_external_docs.ps1

docs: Update Toolkit and Themes docs

---

src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/Mobile/Android/Resources/values/Strings.xml
src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/Server/Controllers/WeatherForecastController.cs
src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/Server/Program.cs
src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/Server/WeatherForecast.cs
src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/Windows/app.manifest
src/SolutionTemplate/UnoSolutionTemplate.netcore/Mobile/Android/AndroidManifest.xml
src/SolutionTemplate/UnoSolutionTemplate.netcore/Mobile/Android/Resources/values/Strings.xml

fix: Remove unintentional "UnoQuickStart" from templates

---

src/Uno.UI/DataBinding/BindingPropertyHelper.FastConvert.cs

refactor: Remove extra unused `ToLowerInvariant` call

---

.vsts-ci.yml

ci: Avoid build for cSpell.json changes

---

src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/Mobile/UnoQuickStart.Mobile.csproj

GitHub Issue (If applicable): closes #11641
For non-design-time builds, AndroidManifest is correctly set from here:
https://github.com/unoplatform/uno/blob/560a44980945eb8343025832fe0ea23941c99435/build/uno.winui.single-project.targets#L58

fix(templates): Specify `AndroidManifest` correctly so that design-time builds don't fail

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs

GitHub Issue (If applicable): closes #11682

fix: Fix geometry code generation on Wasm

---

doc/articles/get-started-dotnet-new.md
doc/articles/get-started-next-steps.md
doc/articles/toc.yml
doc/import_external_docs.ps1

docs: revert ps formatting change
docs: revert formatting change pt2

docs(extensions): Update linked content

---

src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/Views/UnoQuickStart.csproj

fix(templates): Don't include `SupportedOSPlatformVersion` for non-selected platforms

---

src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-uitest/.template.config/ide.host.json
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-uitest/.template.config/template.json
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-uwp-net6/.template.config/ide.host.json
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-uwp-net6/.template.config/template.json
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-uwp/.template.config/ide.host.json
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-uwp/.template.config/template.json
src/SolutionTemplate/UnoUITestTemplate/UnoUITestsLibrary.csproj

n/a
- Refactoring
- Dependencies
templates use vs2017.3.host.json
- templates use ide.host.json
- updates UI Test project dependencies

UWP / UI test template

---

doc/articles/toc.yml

GitHub Issue (If applicable): closes #11732
When clicking on Fundamentals > Development > Uno features > Uno.UI.Toolkit > **AdaptiveTrigger** menu option nothing happens.
AdaptiveTrigger should be clickable.

docs(AdaptiveTrigger): Fixing AdaptiveTrigger menu option in Docs

---

src/Uno.UI/Controls/RootViewController.iOS.cs
src/Uno.UI/UI/Xaml/ApplicationActivity.Android.cs
src/Uno.UI/UI/Xaml/Media/VisualTreeHelper.cs

GitHub Issue (If applicable): closes #11722
- Bugfix

fix: App deactivation should close only light dismiss popups

---

src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/RadioButtons/RadioButtonTests.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.Android.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.Overrides.Android.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.Android.cs

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/11665
- Bugfix
Fix `TextBoxView` selectability when not `ReadOnly`

fix: Selectability of Android `TextBoxView`

---

src/crosstargeting_override.props.sample

- It is necessary to scroll to change the platform override or to set up NuGet override.
- Move the commented out properties to the top to avoid the need to scroll to get to them
- Reorder properties based on their approximate usage frequency
- Update default override to .NET 7.0
- Put all property descriptions in a single comment

docs: Reorganize the `crosstargeting_override.props.sample`

---

src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/ProgressRing/ProgressRingHeightTest.xaml
src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/ProgressRing/ProgressRingHeightTest.xaml.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/ProgressRing/ProgressRingTests.cs
src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.Skia.csproj
src/Uno.UI/Microsoft/UI/Xaml/Controls/ProgressRing/ProgressRing.xaml
src/Uno.UI/UI/Xaml/Style/mergedstyles.xaml

GitHub Issue (If applicable): closes #11637, closes #11323

fix(ProgressRing): Fix `ProgressRing` being vertically stretched

---

src/Uno.UI/UI/Xaml/Controls/Canvas/Canvas.cs
src/Uno.UI/UI/Xaml/Controls/Canvas/Canvas.skia.cs
src/Uno.UI/UI/Xaml/Controls/Canvas/Canvas.wasm.cs

[feature/breaking-changes] chore: Fix Z-index type

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/GenerationInfo.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileDefinition.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlGlobalStaticResourcesMap.cs

chore: Remove dead code in XAML generator

---

src/Uno.UI/UI/Xaml/Internal/InputManager.Pointers.Managed.cs

chore: Fix pointers logging

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs

BREAKING CHANGE: `ShouldWriteErrorOnInvalidXaml` now defaults to true.
GitHub Issue (If applicable): #8339, closes #11476

fix!: Default `ShouldWriteErrorOnInvalidXaml` to true.

---

src/Uno.UI/UI/Xaml/UIElement.Pointers.wasm.cs
src/Uno.UI/UI/Xaml/UIElement.wasm.cs
src/Uno.UI/UI/Xaml/Window.wasm.cs
src/Uno.UI/UI/Xaml/WindowManagerInterop.wasm.cs
src/Uno.UI/ts/WindowManager.ts

perf: WindowManager bindings VI

---

build/PackageDiffIgnore.xml
src/Uno.UI/UI/Xaml/DependencyProperty.cs

BREAKING CHANGE: Renamed the `PropertyMetadata` parameter to `defaultMetadata`
GitHub Issue (If applicable): Part of #8339, closes #11754

fix!: Update DependencyProperty.RegisterAttached to match WinUI parameter names

---

src/Uno.UWP/WinRTFeatureConfiguration.cs

@jeromelaban @nickrandolph This avoids possible regressions.

fix: Change UseLegacyPrimaryLanguageOverride default value to true

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/Utils/XBindExpressionParser.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.Reflection.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs

perf: Fix few more occurrences of ToDisplayString

---

src/Uno.UI/UI/Xaml/Application.Interop.wasm.cs
src/Uno.UI/UI/Xaml/Application.wasm.cs
src/Uno.UI/UI/Xaml/Controls/FocusVisual/SystemFocusVisual.wasm.cs
src/Uno.UI/UI/Xaml/Controls/Image/Image.wasm.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.wasm.cs
src/Uno.UI/UI/Xaml/Input/FocusManager.wasm.cs
src/Uno.UI/UI/Xaml/Media/Imaging/WriteableBitmap.wasm.cs
src/Uno.UI/UI/Xaml/UIElement.wasm.cs
src/Uno.UI/UI/Xaml/WindowManagerInterop.wasm.cs
src/Uno.UI/ts/WindowManager.ts

perf: Misc bindings

---

src/Uno.UWP/System/Launcher.cs

This code is under `#if __ANDROID__ || __IOS__ || __MACOS__ || __SKIA__`, so `#if !_WASM_` is always true.

chore: Cleanup dead code

---

src/SamplesApp/SamplesApp.Skia.Gtk/SamplesApp.Skia.Gtk.csproj
src/SamplesApp/SamplesApp.Skia.Gtk/app.manifest
src/SamplesApp/SamplesApp.Skia.WPF/SamplesApp.Skia.WPF.csproj
src/SamplesApp/SamplesApp.Skia.WPF/app.manifest
src/SamplesApp/UnoIslands.WPF/UnoIslands.Skia.Wpf.csproj
src/SamplesApp/UnoIslands.WPF/app.manifest
src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/Skia.Gtk/SkiaGtk.winui.netcore.vstemplate
src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/Skia.Gtk/UnoQuickStart.Skia.Gtk.csproj
src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/Skia.Gtk/app.manifest
src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/Skia.WPF/SkiaWpf.winui.netcore.vstemplate
src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/Skia.WPF/UnoQuickStart.Skia.WPF.csproj
src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/Skia.WPF/app.manifest
src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/UnoSolutionTemplate.WinUI.netcore.csproj
src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/Windows/UnoQuickStart.Windows.csproj
src/SolutionTemplate/UnoSolutionTemplate.netcore/Skia.Gtk/SkiaGtk.netcore.vstemplate
src/SolutionTemplate/UnoSolutionTemplate.netcore/Skia.Gtk/UnoQuickStart.Skia.Gtk.csproj
src/SolutionTemplate/UnoSolutionTemplate.netcore/Skia.Gtk/app.manifest
src/SolutionTemplate/UnoSolutionTemplate.netcore/Skia.WPF/SkiaWpf.netcore.vstemplate
src/SolutionTemplate/UnoSolutionTemplate.netcore/Skia.WPF/UnoQuickStart.Skia.WPF.csproj
src/SolutionTemplate/UnoSolutionTemplate.netcore/Skia.WPF/app.manifest
src/SolutionTemplate/UnoSolutionTemplate/Skia.Gtk/SkiaGtk.vstemplate
src/SolutionTemplate/UnoSolutionTemplate/Skia.Gtk/UnoQuickStart.Skia.Gtk.csproj
src/SolutionTemplate/UnoSolutionTemplate/Skia.Gtk/app.manifest
src/SolutionTemplate/UnoSolutionTemplate/Skia.WPF/SkiaWpf.vstemplate
src/SolutionTemplate/UnoSolutionTemplate/Skia.WPF/UnoQuickStart.Skia.WPF.csproj
src/SolutionTemplate/UnoSolutionTemplate/Skia.WPF/app.manifest

Add `app.manifest` to Samples app and templates

---

src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.Xaml.cs
src/Uno.UI/UI/Xaml/Markup/Reader/XamlObjectBuilder.cs
src/Uno.UI/UI/Xaml/Markup/XamlReader.cs

- Bugfix (?)
Previously, after a XAML file had been updated via HotReload, the DebugParseContext would be lost.
With this change, the DebugParseContext is now applied to controls when a XAML file is reloaded as part of HotReload.
This is related to #11843 

chore: preserve DebugParseContext as part of XAML HotReload

---

src/SourceGenerators/Uno.UI.SourceGenerators/RemoteControl/RemoteControlGenerator.cs

GitHub Issue (If applicable): closes #11911
- Bugfix
Empty paths cause RemoteControl to fail silently
Don't pass Empty strings to RemoteControl to watch for file changes
I can't find any tests for this area fo the product and don't know where/how some should be added.

fix: XAML Hot reload mishandling empty paths

---

src/SourceGenerators/System.Xaml/System.Xaml/XamlXmlReader.cs
src/Uno.UI.Tests/Windows_UI_XAML_Controls/TextBlockTests/Given_TextBlock.cs
src/Uno.UI.Tests/Windows_UI_XAML_Controls/TextBlockTests/WhiteSpace_In_TextBlock_Inlines.xaml
src/Uno.UI.Tests/Windows_UI_XAML_Controls/TextBlockTests/WhiteSpace_In_TextBlock_Inlines.xaml.cs

GitHub Issue (If applicable): closes #11418
- Bugfix
https://github.com/unoplatform/uno/issues/11418

fix(TextBlock): [WASM] TextBlock.Inlines are not formatted correctly: spaces/blanks are removed #11418

---

build/Uno.UI.Build.csproj
build/uno.winui.common.props
build/uno.winui.common.targets
build/uno.winui.props

- Bugfix
Apply workaround for VS Code support, for omnisharp single-targetframework support.

fix: Adjust vscode support

---

build/PackageDiffIgnore.xml
src/Uno.UI/Generated/3.0.0.0/Microsoft.Web.WebView2.Core/CoreWebView2ContentLoadingEventArgs.cs
src/Uno.UI/Generated/3.0.0.0/Microsoft.Web.WebView2.Core/CoreWebView2DOMContentLoadedEventArgs.cs
src/Uno.UI/UI/Xaml/Controls/WebView/WebView1/WebViewExtensions.cs
src/Uno.UI/UI/Xaml/Controls/WebView/WebView1/WebViewNavigationCompletedEventArgs.cs
src/Uno.UI/UI/Xaml/Controls/WebView/WebView1/WebViewNavigationFailedEventArgs.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Web/WebErrorStatus.cs
src/Uno.UWP/Web/WebErrorStatus.cs

GitHub Issue (If applicable): closes https://github.com/unoplatform/nventive-private/issues/470

Undo `WebErrorStatus` breaking change

---

doc/import_external_docs.ps1

GitHub Issue (If applicable): none
This PR is updating the documentation for plugin 2.5.x
- ~~[ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).~~

docs: Update doc for Figma plugin 2.5.x

---

src/Uno.Foundation.Runtime.WebAssembly/Interop/JSObject.wasm.cs
src/Uno.UI/UI/Xaml/DragDrop/DragDropExtension.Interop.wasm.cs
src/Uno.UI/UI/Xaml/DragDrop/DragDropExtension.wasm.cs
src/Uno.UI/UI/Xaml/FontFamilyLoader.Interop.wasm.cs
src/Uno.UI/UI/Xaml/FontFamilyLoader.wasm.cs
src/Uno.UI/UI/Xaml/Input/PointerRoutedEventArgs.wasm.cs
src/Uno.UI/UI/Xaml/Media/Animation/Animators/RenderingLoopAnimator.Interop.wasm.cs
src/Uno.UI/UI/Xaml/Media/Animation/Animators/RenderingLoopAnimator.wasm.cs
src/Uno.UI/UI/Xaml/WindowManagerInterop.wasm.cs
src/Uno.UI/ts/Interop/ManagedObject.ts
src/Uno.UI/ts/WindowManager.ts
src/Uno.UI/ts/Windows/UI/Xaml/Animation/RenderingLoopAnimator.ts

perf: Misc bindings II

---

.vsts-ci.yml

- Bugfix
macos-11 seems to be experiencing unknown failures, moving to macos 12 works around it.

ci: Bump iOS test to macos-12 agents

---

build/Uno.WinUI.nuspec
build/uno.winui.common.props

- Bugfix
Adjust for incorrect nuspec inclusion of the .targets props

fix: Adjust for missing props file

---

src/Uno.UI.RuntimeTests/Tests/Microsoft_UI_Xaml_Controls/Given_WebView2.cs

chore: Temporarily disable `ExecuteScriptAsync` tests on iOS

---

src/AddIns/Uno.UI.Lottie/LottieVisualSource.Skottie.cs
src/AddIns/Uno.UI.Lottie/LottieVisualSourceBase.Android.cs
src/AddIns/Uno.UI.Lottie/LottieVisualSourceBase.cs
src/AddIns/Uno.UI.Lottie/LottieVisualSourceBase.wasm.cs
src/SamplesApp/SamplesApp.UITests/Microsoft_UI_Xaml_Controls/ProgressRingTests/Given_DeterminateProgressRings.cs
src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/ProgressRing/WinUIProgressRingPage.xaml
src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/ProgressRing/WinUIProgressRing_CustomSources.xaml
src/Uno.UI/Microsoft/UI/Xaml/Controls/AnimatedIcon/AnimatedVisuals/AnimatedAcceptVisualSource.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/AnimatedIcon/AnimatedVisuals/AnimatedBackVisualSource.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/AnimatedIcon/AnimatedVisuals/AnimatedChevronDownSmallVisualSource.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/AnimatedIcon/AnimatedVisuals/AnimatedChevronRightDownSmallVisualSource.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/AnimatedIcon/AnimatedVisuals/AnimatedChevronUpDownSmallVisualSource.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/AnimatedIcon/AnimatedVisuals/AnimatedFindVisualSource.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/AnimatedIcon/AnimatedVisuals/AnimatedGlobalNavigationButtonVisualSource.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/AnimatedIcon/AnimatedVisuals/AnimatedSettingsVisualSource.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/ProgressRing/ProgressRing.cs
src/Uno.UI/UI/Xaml/Controls/AnimatedVisualPlayer/IAnimatedVisualSource.cs

GitHub Issue (If applicable): closes #11672 
- Bugfix
- 
- ProgressRing is always in Indeterminate state (see the Issue  #11672) 
- ProgressRing sources were not update properly 
- ProgressRing IsIndeterminate  property behave as expected. 

fix(ProgressRing): IsIndeterminate property and (In)DeterminateSource behave now as expected.

---

src/Uno.Foundation.Runtime.WebAssembly/Interop/JSObjectMetadataProvider.wasm.cs

fix(JSObject): Marshal pointers instead of strings

---

src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/XamlCodeGeneratorTests/Verifiers/CSGenerator.cs

test: Add missing line in globalconfig in tests

---

src/Uno.UI/ts/Windows/Graphics/Display/DisplayInformation.ts
src/Uno.UWP/Graphics/Display/DisplayInformation.Interop.wasm.cs
src/Uno.UWP/Graphics/Display/DisplayInformation.wasm.cs

perf: Add DisplayInformation bindings

---

src/SamplesApp/SamplesApp.Skia.Gtk/SamplesApp.Skia.Gtk.csproj

> warning NETSDK1189: Prefer32Bit is not supported and has no effect for netcoreapp target

chore: Fix warning NETSDK1189 Prefer32Bit has no effect

---

doc/articles/native-styles.md

closes https://github.com/unoplatform/uno/issues/11677
Update documentation to point out that enabling native styles globally won't work if AppResources.xaml already includes implicit styles (such as XamlControlsResources or Uno.Material/Cupertino resources)

docs: update native styles docs

---

src/SourceGenerators/System.Xaml/System.Xaml/XamlXmlReader.cs
src/Uno.UI.Tests/Windows_UI_XAML_Controls/TextBlockTests/Given_TextBlock.cs
src/Uno.UI.Tests/Windows_UI_XAML_Controls/TextBlockTests/WhiteSpace_In_TextBlock_Inlines.xaml

GitHub Issue (If applicable): closes #11418
- Bugfix
https://github.com/unoplatform/uno/issues/11418
https://github.com/unoplatform/uno/issues/11418

bugfix(XAML): Fix the TextBlock.Inline space/blank missing issue

---

src/Uno.UI.RuntimeTests/Helpers/ImageAssert.cs
src/Uno.UI.RuntimeTests/Tests/Microsoft_UI_Xaml_Controls/Given_RefreshContainer.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/PullToRefresh/Native/NativeRefreshControl.Android.cs

GitHub Issue (If applicable): closes #11331

fix: `RefreshContainer` indicator is not centered

---

src/Uno.UI.Tests/DependencyProperty/Given_DependencyProperty.cs
src/Uno.UI/Mock/Border.net.cs
src/Uno.UI/UI/Xaml/DependencyObjectStore.cs

- Bugfix
In `DependencyObjectStore` we are going through callbacks via `for`. This can be a problem if any of the handlers, e.g. a callback modifies the list while it is being processed - as it can remove itself (moving the next callback, so it is then accidentally skipped), or add a new one which will then be processed immediately - causing potentially stack overflow.
Use a local copy of the list instead.

Ensure callbacks added in callback handlers are not processed in the same run

---

src/Uno.UI/UI/Xaml/Documents/InlineCollection.skia.cs

GitHub Issue (If applicable): closes #9541
- Bugfix
Previously `InvalidateMeasure` completely cleared layout info on `InlineCollection` in Skia, which meant if there was already a scheduled render, it could use zeroed out values for its rendering.
Mark invalidation as pending, so that the next measure pass can reset the calculated values, but keep the existing ones for the potential next frame.

[Skia] fix: Prevent icons from moving randomly

---

src/Uno.UI/UI/Xaml/Controls/CalendarView/Primitives/CalendarPanel.ModernCollectionBasePanel.cs

closes https://github.com/unoplatform/uno/issues/11694
Fix calendar header display first selectable month instead of current
When only the header of the `CalendarView` is visible, it displays the first selectable month instead of displaying the current one. This is because the header text is inferred from the current scrolling position of the date's SV, which is invalid when the whole SV is not visible.
We pause the viewport updates when it become hidden to avoid such behavior

fix: Fix calendar header display first selectable month instead of current

---

doc/articles/guides/profiling-applications.md

Correcting configuration element to enable AOT compilation

Correcting configuration element

---

src/Uno.Foundation.Runtime.WebAssembly/Interop/JSObject.wasm.cs
src/Uno.Foundation.Runtime.WebAssembly/Interop/JSObjectHandle.wasm.cs
src/Uno.Foundation.Runtime.WebAssembly/Uno.Foundation.Runtime.WebAssembly.csproj
src/Uno.UI/UI/Xaml/Media/Animation/Animators/RenderingLoopAnimator.Interop.wasm.cs
src/Uno.UI/UI/Xaml/Media/Animation/Animators/RenderingLoopAnimator.wasm.cs
src/Uno.UI/ts/ExportManager.ts
src/Uno.UI/ts/Interop/ManagedObject.ts
src/Uno.UI/ts/Windows/UI/Xaml/Animation/RenderingLoopAnimator.ts

perf(Animations): RenderingLoopAnimator bindings

---

src/Uno.UI.RemoteControl.Messaging/Messages/Frame.cs
src/Uno.UI.RemoteControl/ClientEventEventArgs.cs
src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.Xaml.cs
src/Uno.UI.RemoteControl/ReceivedFrameEventArgs.cs
src/Uno.UI.RemoteControl/RemoteControlClient.cs
src/Uno.UI/UI/Xaml/Application.Components.cs
src/Uno.UI/UI/Xaml/Markup/XamlReader.cs

- Other: tweaks HotReload behavior
HotReload treats Debug information differently depending on how it invokes.
Standardize the Debug information for all XAML HotReloaded elements. + Add an additional event for tracking this.

chore: enhance messaging around HotReload

---

src/Uno.UWP/Devices/Geolocation/Geolocator.Android.cs

GitHub Issue (If applicable): closes #11915 
- Bugfix
- when unsubscribing from events the continue to use the location.
-  Stop using location when unsubscribing  from events.

fix(geolocator): Stop using location when unsubscribing  from events.

---

src/Uno.UI.Tests/Windows_Globalization/When_Calendar.cs
src/Uno.UI/DirectUI/DateComparer.cs
src/Uno.UWP/Globalization/Calendar.cs

GitHub Issue (If applicable): closes #12118, closes #8680

fix: Fix CalendarView selecting next day due to not respecting current time zone

---

src/Uno.UI/ts/Windows/Storage/ApplicationDataContainer.ts

GitHub Issue (If applicable): closes #12068

fix: Detect availability of localStorage before using it

---

build/PackageDiffIgnore.xml
src/Uno.UI/UI/Xaml/Controls/WebView/WebView1/WebView.cs

This method does not exist in UWP

[Breaking] fix!: Remove Task-based `WebView.InvokeScriptAsync`

---

src/Uno.UWP/Storage/StorageFolder.native.Interop.wasm.cs
src/Uno.UWP/Storage/StorageFolder.native.wasm.cs

perf: Add StorageFolder bindings

---

doc/articles/get-started-vscode.md

Closes https://github.com/unoplatform/uno/issues/12138, https://github.com/unoplatform/uno/issues/12096

docs: Adjust vscode directions

---

build/PackageDiffIgnore.xml
src/Uno.UI/UI/Xaml/Controls/IconElement.cs

The IconElement constructor is only available for derived classes within WinUI itself, but not publicly.

[Breaking] fix!: IconElement constructor should be internal only

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.Reflection.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs

BREAKING CHANGE: Xaml generator now always uses strict search

fix!: Always use strict search

---

build/PackageDiffIgnore.xml
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Image.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media_Imaging/Given_BitmapSource.cs
src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.Android.cs
src/Uno.UI/UI/Xaml/Controls/Image/Image.Android.cs
src/Uno.UI/UI/Xaml/Controls/Image/Image.cs
src/Uno.UI/UI/Xaml/Controls/Image/Image.iOSmacOS.cs
src/Uno.UI/UI/Xaml/Media/Brush.Android.cs
src/Uno.UI/UI/Xaml/Media/ImageBrush.Android.cs
src/Uno.UI/UI/Xaml/Media/ImageBrush.cs
src/Uno.UI/UI/Xaml/Media/Imaging/BitmapImage.cs

GitHub Issue (If applicable): closes #11673, closes #7288, closes #9533

Fix image-related property changes not being detected

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_CalendarView.cs
src/Uno.UI/DirectUI/JoltCollections.h.cs
src/Uno.UI/DirectUI/TrackableDateCollection.cs
src/Uno.UI/UI/Xaml/Controls/CalendarView/CalendarView_Partial_Selection.cs

GitHub Issue (If applicable): closes #11830 
- Bugfix
https://github.com/unoplatform/uno/issues/11830

bugfix(CalendarView): Fix the CalendarView.SelectedDates issue

---

src/Uno.UWP/Storage/Streams/Internal/NativeReadStreamAdapter.wasm.cs
src/Uno.UWP/Storage/Streams/Internal/NativeWriteStreamAdapter.wasm.cs

perf: NativeStreamAdapter bindings

---

src/crosstargeting_override.props.sample

docs: Update crosstargeting_override.props.sample

---

doc/articles/features/windows-system.md

GitHub Issue (If applicable): closes #11862
The QueryUriSupportAsync docs doesn't mention the need to specify `<queries>` entries on newer versions of Android and iOS.
Added information about the platform-specific need to include URL schemes in manifests.

docs: QueryUriSupportAsync add platform-specific info

---

build/PackageDiffIgnore.xml
src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBaseScrollContentPresenter.iOS.cs
src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/IUIScrollView.iOSmacOS.cs

BREAKING CHANGE: Remove `SetContentOffset` and `SetZoomScale` from `IUIScrollView`

fix!: Remove `SetContentOffset` and `SetZoomScale` from `IUIScrollView`

---

src/Uno.UI.RuntimeTests/Tests/Windows_Storage/Streams/Given_RandomAccessStreamReference.cs
src/Uno.UWP/Storage/Streams/RandomAccessStreamReference.cs

GitHub Issue (If applicable): closes #12161

fix: Fix RandomAccessStreamReference.CreateFromUri crashing for ms-appdata Uri

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media_Animation/Given_DoubleAnimation.cs

GitHub Issue (If applicable): related to #9080

chore: Disable flaky `When_RepeatForever_ShouldLoop` test

---

src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Input/Keyboard/Keyboard_Events.xaml.cs
src/Uno.UI.Runtime.Skia.Gtk/GtkCoreWindowExtension.Keyboard.cs
src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/CoreWindowExtension.Keyboard.cs
src/Uno.UI.Runtime.Skia.Tizen/TizenCoreWindowExtension.Keyboard.cs
src/Uno.UI.Runtime.Skia.Wpf/WpfCoreWindowExtension.Keyboard.cs
src/Uno.UI/UI/Xaml/UIElement.Keyboard.skia.cs
src/Uno.UWP/UI/Core/CoreWindow.Pointers.Managed.cs
src/Uno.UWP/UI/Core/CoreWindow.skia.cs
src/Uno.UWP/UI/Core/ICoreWindowEvents.cs

GitHub Issue (If applicable): closes #11953
- Bugfix

fix: event ordering of KeyUp/KeyDown on Skia

---

src/Uno.UI.RuntimeTests/Tests/Windows_Storage/Given_StorageFile.cs
src/Uno.UWP/Storage/StorageFile.Android.cs
src/Uno.UWP/Storage/StorageFile.cs
src/Uno.UWP/Storage/StorageFile.iOSmacOS.cs
src/Uno.UWP/Storage/StorageFile.skia.cs
src/Uno.UWP/Storage/StorageFile.wasm.cs

GitHub Issue (If applicable): closes #12162

fix: Fix StorageFile.GetFileFromApplicationUriAsync crash when given appdata uri

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_BringIntoView.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_BringIntoView.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Models/ListViewViewModel.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.Android.cs

fixes https://github.com/unoplatform/nventive-private/issues/461
- Bugfix

fix(droid): bringintoview for not visible items

---

build/PackageDiffIgnore.xml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/Basic_Shapes.xaml.cs
src/Uno.UI.Tests/Windows_UI_XAML_Controls/GridTests/GivenGrid_And_Alignment.cs
src/Uno.UI.Tests/Windows_UI_XAML_Controls/GridTests/GivenGrid_And_AutoSized.cs
src/Uno.UI.Tests/Windows_UI_XAML_Controls/GridTests/GivenGrid_And_Margin.cs
src/Uno.UI.Tests/Windows_UI_XAML_Controls/GridTests/Given_Grid.cs
src/Uno.UI/UI/Xaml/Controls/Grid/GridExtensions.cs

BREAKING CHANGE: `GridExtensions` is made internal
GitHub Issue (If applicable): Part of #8339. **NOTE:** https://github.com/unoplatform/uno/issues/8339 states that this type should be moved to legacy namespace. I took a stronger step here and made this type internal as I don't think it's something that should be public.

fix!: Make GridExtensions internal

---

doc/articles/features/step-counter.md

GitHub Issue (If applicable): closes #12200

docs: Fix example being shown for iOS only

---

src/Uno.UI/UI/Xaml/Window.Android.cs

Duplicate using is making local builds to fail

chore(droid): remove duplicate using

---

src/Uno.UI/UI/Xaml/ApplicationActivity.Android.cs
src/Uno.UWP/Devices/Sensors/SimpleOrientationSensor.cs

BREAKING CHANGE: `SimpleOrientationSensor` should not schedule on `Dispatcher`
GitHub Issue (If applicable): closes #10905, Part of #8339

fix!: `SimpleOrientationSensor` should not schedule on `Dispatcher`

---

src/SamplesApp/SamplesApp.Shared/App.xaml.cs
src/Uno.UI.RuntimeTests/Helpers/FeatureConfigurationHelper.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ComboBox.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_FrameworkTemplatePool.cs
src/Uno.UI/UI/Xaml/Controls/Primitives/ToggleButton.cs
src/Uno.UI/UI/Xaml/Controls/Primitives/ToggleButton.mux.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs
src/Uno.UI/UI/Xaml/Controls/ToggleSwitch/ToggleSwitch.cs
src/Uno.UI/UI/Xaml/Controls/ToggleSwitch/ToggleSwitch.mux.cs
src/Uno.UI/UI/Xaml/FrameworkTemplatePoolDefaultPlatformProvider.cs

GitHub Issue (If applicable): closes #12182

fix: Avoid raising events when recycling TextBox, ToggleSwitch, and ToggleButton

---

src/Uno.UI/UI/Xaml/Controls/CalendarView/CalendarViewGeneratorHost.cs

GitHub Issue (If applicable): closes #11830

fix: Fix CalendarView going into an infinite loop

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/12015

perf: Use memoized FindType instead of SourceFindType

---

src/Uno.UI/ts/WindowManager.ts

- Bugfix
I fail at TypeScript.
I still fail at TypeScript, but fixed the bug I introduced.

fix: Properly resolve buildSplashScreen for new bootstrapper

---

build/PackageDiffIgnore.xml
src/Uno.UI/UI/Xaml/Media/Animation/ColorAnimation.cs
src/Uno.UI/UI/Xaml/Media/Animation/ColorAnimationUsingKeyFrames.cs
src/Uno.UI/UI/Xaml/Media/Animation/DoubleAnimation.cs
src/Uno.UI/UI/Xaml/Media/Animation/DoubleAnimationUsingKeyFrames.cs
src/Uno.UI/UI/Xaml/Media/Animation/ITimeline.cs
src/Uno.UI/UI/Xaml/Media/Animation/ObjectAnimationUsingKeyFrames.cs
src/Uno.UI/UI/Xaml/Media/Animation/Storyboard.cs
src/Uno.UI/UI/Xaml/Media/Animation/Timeline.cs

BREAKING CHANGE: Timeline shouldn't implement IDisposable
GitHub Issue (If applicable): Replaces https://github.com/unoplatform/uno/pull/12176

fix!: Timeline shouldn't implement `IDisposable`

---

doc/import_external_docs.ps1

A simple PR to update the Uno.Resizetizer docs.

Updated uno.resizetizer commit

---

src/Uno.UI/Microsoft/UI/Xaml/Controls/TabView/Strings/as-IN/Resources.resw
src/Uno.UI/Microsoft/UI/Xaml/Controls/TabView/Strings/bn-IN/Resources.resw
src/Uno.UI/Microsoft/UI/Xaml/Controls/TabView/Strings/ca-Es-VALENCIA/Resources.resw
src/Uno.UI/Microsoft/UI/Xaml/Controls/TabView/Strings/cy-GB/Resources.resw
src/Uno.UI/Microsoft/UI/Xaml/Controls/TabView/Strings/ga-IE/Resources.resw
src/Uno.UI/Microsoft/UI/Xaml/Controls/TabView/Strings/gd-gb/Resources.resw
src/Uno.UI/Microsoft/UI/Xaml/Controls/TabView/Strings/gu-IN/Resources.resw
src/Uno.UI/Microsoft/UI/Xaml/Controls/TabView/Strings/hy-AM/Resources.resw
src/Uno.UI/Microsoft/UI/Xaml/Controls/TabView/Strings/kok-IN/Resources.resw
src/Uno.UI/Microsoft/UI/Xaml/Controls/TabView/Strings/lb-LU/Resources.resw
src/Uno.UI/Microsoft/UI/Xaml/Controls/TabView/Strings/mi-NZ/Resources.resw
src/Uno.UI/Microsoft/UI/Xaml/Controls/TabView/Strings/mr-IN/Resources.resw
src/Uno.UI/Microsoft/UI/Xaml/Controls/TabView/Strings/mt-MT/Resources.resw
src/Uno.UI/Microsoft/UI/Xaml/Controls/TabView/Strings/ne-NP/Resources.resw
src/Uno.UI/Microsoft/UI/Xaml/Controls/TabView/Strings/or-IN/Resources.resw
src/Uno.UI/Microsoft/UI/Xaml/Controls/TabView/Strings/pa-IN/Resources.resw
src/Uno.UI/Microsoft/UI/Xaml/Controls/TabView/Strings/quz-PE/Resources.resw
src/Uno.UI/Microsoft/UI/Xaml/Controls/TabView/Strings/sr-Cyrl-BA/Resources.resw
src/Uno.UI/Microsoft/UI/Xaml/Controls/TabView/Strings/sr-Cyrl-RS/Resources.resw
src/Uno.UI/Microsoft/UI/Xaml/Controls/TabView/Strings/tt-RU/Resources.resw
src/Uno.UI/Microsoft/UI/Xaml/Controls/TabView/Strings/ug-CN/Resources.resw
src/Uno.UI/Microsoft/UI/Xaml/Controls/TabView/Strings/ur-PK/Resources.resw

chore: `TabView` strings update

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ComboBox.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Image.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/TestsResources.xaml
src/Uno.UI/Extensions/UIViewExtensions.iOSmacOS.cs
src/Uno.UI/UI/Xaml/UIElement.Android.cs
src/Uno.UI/UI/Xaml/UIElement.cs
src/Uno.UI/UI/Xaml/UIElement.iOS.cs
src/Uno.UI/UI/Xaml/UIElement.macOS.cs

GitHub Issue (If applicable): closes https://github.com/unoplatform/nventive-private/issues/449
- Bugfix
When loading a ComboBox on iOS from a Modal Page, the PopUp with the option does not respect the positioning of the ComboBox.

fix(iOS): ComboBox Popup location when displayed on a Modal

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Border.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Image.cs

chore: Disable flaky macOS tests

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/FlyoutPages/When_PlacementTarget_Binding.xaml
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/FlyoutPages/When_PlacementTarget_Binding.xaml.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Flyout.cs
src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.Skia.csproj
src/Uno.UI/UI/Xaml/Controls/Popup/Popup.cs

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/11602, closes https://github.com/unoplatform/uno/issues/11647, closes https://github.com/unoplatform/uno/issues/11835

fix: Don't propagate DataContext in PlacementTarget property

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.Reflection.cs

GitHub Issue (If applicable): closes #12180

fix: Fix a case where fuzzy matching was missing

---

build/PackageDiffIgnore.xml
src/AddIns/Uno.UI.Lottie/LottieVisualOptions.cs
src/AddIns/Uno.UI.Lottie/LottieVisualSource.Skottie.cs
src/AddIns/Uno.UI.Lottie/LottieVisualSource.cs
src/AddIns/Uno.UI.Lottie/LottieVisualSource.iOSmacOS.cs
src/AddIns/Uno.UI.Lottie/LottieVisualSourceBase.Android.cs
src/AddIns/Uno.UI.Lottie/LottieVisualSourceBase.cs
src/AddIns/Uno.UI.Lottie/LottieVisualSourceBase.wasm.cs
src/AddIns/Uno.UI.Lottie/LottieVisualSourceProvider.cs
src/AddIns/Uno.UI.Lottie/ThemableLottieVisualSource.Android.cs
src/AddIns/Uno.UI.Lottie/ThemableLottieVisualSource.Properties.cs
src/AddIns/Uno.UI.Lottie/ThemableLottieVisualSource.cs
src/SamplesApp/UITests.Shared/Lottie/LottieProgressPage.xaml
src/Uno.UI.Tests/Lottie/Given_DynamicReloadedLottieAnimatedVisualSource.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/AnimatedVisualPlayer/ILottieVisualSourceProvider.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/ProgressRing/ProgressRing.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/ProgressRing/ProgressRing.xaml
src/Uno.UI/UI/Xaml/Controls/AnimatedVisualPlayer/AnimatedVisualPlayer.cs
src/Uno.UI/UI/Xaml/Controls/AnimatedVisualPlayer/AnimatedVisualPlayer.wasm.cs
src/Uno.UI/UI/Xaml/Controls/AnimatedVisualPlayer/IAnimatedVisualSource.cs
src/Uno.UI/UI/Xaml/Controls/AnimatedVisualPlayer/IThemableAnimatedVisualSource.cs
src/Uno.UI/UI/Xaml/Style/mergedstyles.xaml
src/Uno.WinUIRevert/Program.cs

BREAKING CHANGE: Move `AnimatedVisualPlayer`, `IAnimatedVisualSource `, and `IThemableAnimatedVisualSource` from WUX to MUX
BREAKING CHANGE: Rename `CreateTheamableFromLottieAsset` to `CreateThemableFromLottieAsset`
BREAKING CHANGE: Rename `Microsoft.Toolkit.Uwp.UI.Lottie` namespace to `CommunityToolkit.WinUI.Lottie`
GitHub Issue (If applicable): Part of #8339, closes #11717

fix!: Lottie breaking changes

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ImageTests/UnoSamples_Tests.Image.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/WebViewTests/UnoSamples_Test_NavigateToString.cs
src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/WebView2Tests/WebView2_AnchorNavigation.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/BitmapImage_vs_SvgImageSource.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/WebView/WebView_AnchorNavigation.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/ImageBrushTests/Ellipse.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/ImageBrushTests/ImageBrush_StreamSource.xaml.cs
src/Uno.UI.RuntimeTests/Tests/Windows_Storage/Streams/Given_RandomAccessStreamReference.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Image.cs

- Bugfix
Move assets to stable hostname.

chore: Adjust assets location to stable hostname

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/SvgImageSource_FromMsAppData.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/SvgImageSource_FromMsAppData.xaml.cs
src/Uno.UI/UI/Xaml/Media/Imaging/SvgImageSource.wasm.cs
src/Uno.UWP/Helpers/AppDataUriEvaluator.cs

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/11703

feat(svg): [Wasm] Add support for ms-appdata

---

src/Uno.UI/UI/Xaml/Controls/MediaPlayerElement/MediaPlayerElement.cs

fix!: `MediaPlayerElement` shouldn't be `IDisposable`

---

src/Uno.CrossTargetting.targets

build: Add `__MACOS__` to DefineConstants

---

src/Uno.UWPSyncGenerator/Generator.cs

chore: Remove unneeded `RegisterGenericHelperTypes` in UWPSyncGenerator

---

src/Uno.UI.RuntimeTests/Tests/Microsoft_UI_Xaml_Controls/Given_WebView2.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_WebView.cs
src/Uno.UI/UI/Xaml/Controls/WebView/Core/CoreWebView2.cs

GitHub Issue (If applicable): closes https://github.com/unoplatform/nventive-private/issues/478
- Bugfix

fix: Ensure scroll is enabled by default on WebView

---

.editorconfig

This option is very problematic. See https://github.com/unoplatform/uno/pull/12276#discussion_r1193472767

chore: Don't set `trim_trailing_whitespace` to true.

---

src/Uno.UI.RuntimeTests/Tests/Uno_UI_Xaml_Core/Given_InputManager.cs

build: Fix local build failure due to duplicate using

---

src/Uno.UI.RuntimeTests/Tests/Windows_Storage/Given_StorageFile.cs
src/Uno.UWP/Storage/StorageFile.Base.cs

GitHub Issue (If applicable): closes #12325

fix: FileStorage.CopyAsync should open target stream for write

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_UIElement.TransformToVisual.cs
src/Uno.UI/UI/Xaml/UIElement.Android.cs

- Bugfix
TransformToVisual was returning results with improper xy coords

fix: [Android] fix android transformtovisual

---

build/Uno.Foundation.Logging.nuspec
build/Uno.WinUI.Lottie.nuspec
build/Uno.WinUI.MSAL.nuspec
build/Uno.WinUI.MediaPlayer.WebAssembly.nuspec
build/Uno.WinUI.RemoteControl.Messaging.nuspec
build/Uno.WinUI.RemoteControl.nuspec
build/Uno.WinUI.Skia.Gtk.nuspec
build/Uno.WinUI.Skia.Linux.FrameBuffer.nuspec
build/Uno.WinUI.Skia.Wpf.nuspec
build/Uno.WinUI.Svg.nuspec
build/Uno.WinUI.WebAssembly.nuspec
build/Uno.WinUI.nuspec
build/ci/.azure-devops-unit-tests.yml
doc/articles/faq.md
src/AddIns/Uno.UI.MSAL/Uno.UI.MSAL.Reference.csproj
src/AddIns/Uno.UI.MSAL/Uno.UI.MSAL.Windows.csproj
src/AddIns/Uno.UI.MSAL/Uno.UI.MSAL.netcoremobile.csproj
src/Common/GlobalAssemblyInfo.cs
src/Directory.Build.props
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/Uno.ProjectTemplates.Dotnet.csproj
src/Uno.Foundation.Runtime.WebAssembly/Uno.Foundation.Runtime.WebAssembly.csproj
src/Uno.UI.Foldable/Uno.UI.Foldable.netcoremobile.csproj
src/Uno.UI.Maps/Uno.UI.Maps.netcoremobile.csproj
src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/Uno.UI.Runtime.Skia.Linux.FrameBuffer.csproj
src/Uno.UI.Runtime.Skia.Wpf/Uno.UI.Runtime.Skia.Wpf.csproj
src/Uno.UI.Runtime.WebAssembly/Uno.UI.Runtime.WebAssembly.csproj

closing https://github.com/unoplatform/uno/issues/11242

ci: Adjust nuget authors and owners

---

src/Uno.UI/ts/ExportManager.ts

fix(ExportManager): Ensure Uno NET7 is used

---

src/Uno.UI/UI/Xaml/Input/Pointer.cs
src/Uno.UI/UI/Xaml/Input/PointerRoutedEventArgs.wasm.cs
src/Uno.UI/UI/Xaml/Internal/PointerCapture.wasm.cs
src/Uno.UI/UI/Xaml/Internal/RootVisual.cs
src/Uno.UI/UI/Xaml/UIElement.Pointers.wasm.cs
src/Uno.UWP/Devices/Input/PointerIdentifier.cs
src/Uno.UWP/Devices/Input/PointerIdentifierPool.cs

Fix pointer capture broken on Firefox
We are using managed pointer ID for capture
We use native IDs

fix(reg): Fix pointer capture broken on Firefox

---

build/Uno.WinUI.nuspec

GitHub Issue (If applicable): closes #12387
The nuspec change was missed to be made manually in https://github.com/unoplatform/uno/pull/12296

fix: Update Uno.Fonts.Fluent to get latest glyph fixes

---

src/Uno.UI.RemoteControl/IRemoteControlPreProcessor.cs
src/Uno.UI.RemoteControl/RemoteControlClient.cs
src/Uno.UI.RemoteControl/Uno.UI.RemoteControl.csproj

- other: Remote Control behavior extensibility
All received frames are processed by the RemoteControlClient
It's now possible to register a class to "pre-process" all frames received by the RemoteControlClient. This can do its own work with a received frame and, optionally, prevent the default processing of the frame too.

Allow controlling of processing of frames by RemoteControlClient

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_AutoSuggestBox.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.cs

GitHub Issue (If applicable): closes #9576
- Bugfix
https://github.com/unoplatform/uno/issues/9576

fix(AutoSuggestBox): Fix Suggestion Item not being selected

---

doc/articles/how-to-host-a-webassembly-app.md

GitHub Issue (If applicable): closes #12362

docs(ngnix): added fallback routes nginx example

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Image.cs
src/Uno.UI/UI/Xaml/Media/ImageSource.wasm.cs
src/Uno.UI/UI/Xaml/Media/Imaging/BitmapImage.wasm.cs
src/Uno.UI/UI/Xaml/Media/Imaging/SvgImageSource.wasm.cs

GitHub Issue (If applicable): closes #12385

feat(wasm): Support ms-appdata for Image

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/TestsResources.xaml

chore: remove reference unrelated comments

---

src/SamplesApp/SamplesApp.UITests/RuntimeTests.cs
src/Uno.UI.RuntimeTests/Tests/Uno_UI_Toolkit/Given_VisibleBoundsPadding.cs
src/Uno.UI/Behaviors/VisibleBoundsPadding.cs
src/Uno.UI/Extensions/InsetsExtensions.Android.cs
src/Uno.UI/Extensions/ViewHelper.Android.cs
src/Uno.UI/LayoutProvider.Android.cs
src/Uno.UI/UI/Xaml/ApplicationActivity.Android.cs
src/Uno.UI/UI/Xaml/Window.Android.cs

Revert "fix: dispatch setting of visibleboundspadding insets"

---

src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/ProgressBar/ProgressBarTest.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/ProgressBar/ProgressBar.cs

#12312 
- Bugfix
- Indeterminate state was not porperly working on android
- Indeterminate state behave as expected

fix(progressBar): IsIndeterminate don't trigger SetProgressBarIndicatorWidth when widths didn't change

---

doc/articles/uwp-vs-winui3.md

Updated references to .NET versions

docs: Update uwp-vs-winui3.md

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ContentControlTestsControl/ContentControlTestViewModel.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ContentControlTestsControl/ContentControl_ComboBoxSetNull.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ContentControlTestsControl/ContentControl_ComboBoxSetNull.xaml.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ContentControl.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/TestsResources.xaml
src/Uno.UI/UI/Xaml/Controls/Primitives/Selector.cs

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/12357
- Bugfix

fix(ContentControl): set Content null when using ComboBox

---

src/Uno.UWPSyncGenerator/Generator.cs

chore: Remove unused variable

---

build/Uno.UI.Build.csproj
build/Uno.WinUI.MediaPlayer.Skia.Gtk.nuspec
src/Directory.Build.props
src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault/MediaTransportControls_themeresources.xaml

GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/12240
- Bugfix
Adjust MediaPlayer Skia.Gtk packaging.

fix(media): adjust packaging for Skia.Gtk

---

src/Uno.UI.RuntimeTests/Tests/Uno_UI_Toolkit/Given_VisibleBoundsPadding.cs
src/Uno.UI/Behaviors/VisibleBoundsPadding.cs
src/Uno.UI/Extensions/InsetsExtensions.Android.cs
src/Uno.UI/Extensions/ViewHelper.Android.cs
src/Uno.UI/LayoutProvider.Android.cs
src/Uno.UI/UI/Xaml/ApplicationActivity.Android.cs
src/Uno.UI/UI/Xaml/Window.Android.cs

closes https://github.com/unoplatform/uno/issues/12007
- Bugfix

fix: Android Window/VisibleBounds calc

---

src/Uno.UI/UI/Xaml/Controls/MediaPlayerElement/MediaPlayerElement.cs
src/Uno.UI/UI/Xaml/Controls/MediaPlayerElement/MediaTransportControls.MediaPlayer.cs
src/Uno.UI/UI/Xaml/Controls/MediaPlayerElement/MediaTransportControls.Properties.cs
src/Uno.UI/UI/Xaml/Controls/MediaPlayerElement/MediaTransportControls.cs
src/Uno.UI/UI/Xaml/Controls/MediaPlayerElement/Strings/en-US/Resources.resw
src/Uno.UWP/Media/Playback/MediaPlaybackSession.cs

GitHub Issue (If applicable): closes #12333, closes #12335, closes #12344
- Bugfix
- Refactor
- fixed visual states
- added tooltips
- refactored event management
- refactored handling of IsXyzVisible & IsXYZEnabled properties (moved from binding+converter to property changed handler)

fix(MPE): MediaTransportControls visuals

---

src/Uno.UI.RuntimeTests/Tests/Microsoft_UI_Xaml_Controls/Given_WebView2.cs

- Bugfix
Adjust When_ExecuteScriptAsync_String for android instability

test: Adjust When_ExecuteScriptAsync_String for android/ios instability

---

src/Uno.UI/UI/Xaml/Controls/MediaPlayerElement/MediaTransportControls.cs

GitHub Issue (If applicable): closes #12499
- Feature
Show icons when feature is not implemented.
Do not show icons when not implemented.

Update validation for unimplemented icon

---

src/AddIns/Uno.UI.MediaPlayer.Skia.Gtk/GTKMediaPlayer.cs
src/AddIns/Uno.UI.MediaPlayer.Skia.Gtk/GTKMediaPlayer.events.cs
src/AddIns/Uno.UI.MediaPlayer.Skia.Gtk/MediaPlayerExtension.cs
src/AddIns/Uno.UI.MediaPlayer.Skia.Gtk/MediaPlayerExtension.events.cs
src/AddIns/Uno.UI.MediaPlayer.Skia.Gtk/VideoView.cs
src/Uno.UI/UI/Xaml/Controls/MediaPlayerElement/MediaPlayerElement.cs
src/Uno.UI/UI/Xaml/Controls/MediaPlayerElement/MediaPlayerPresenter.Others.cs
src/Uno.UI/UI/Xaml/Controls/MediaPlayerElement/MediaTransportControls.MediaPlayer.cs
src/Uno.UI/UI/Xaml/Controls/MediaPlayerElement/MediaTransportControls.cs
src/Uno.UWP/Media/Playback/MediaPlayer.Android.cs
src/Uno.UWP/Media/Playback/MediaPlayer.others.cs

GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/12240
- Bugfix
- Adjust delays in natural size reporting
- Adjust render surface sizing and positioning on slower devices
- Fix performance issue with the loading/buffering ProgressBar
- Adjust visual states on loading

Misc Skia MPE updates

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_SingleSelection_Focus.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_SingleSelection_Focus.xaml.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/ListViewBase.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.Properties.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.cs

GitHub Issue (If applicable): closes #12308 
- Feature
- Property is not supported
- Property is supported

feat: Support for `SingleSelectionFollowsFocus`

---

src/AddIns/Uno.UI.MediaPlayer.Skia.Gtk/VideoView.cs

GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/12240
- Bugfix
Fixed runtime tests on macos

fix(mpe): fix for macOS failure on not available player

---

doc/articles/features/working-with-themes.md

GitHub Issue (If applicable): closes #11544 
Discussed with @nickrandolph and @MartinZikmund 

docs(themes): Update working-with-themes.md

---

doc/articles/how-to-host-a-webassembly-app.md

docs(ngnix): added cache control and compression examples

---

src/Uno.UI.RuntimeTests/Helpers/TestHelper.cs
src/Uno.UI.RuntimeTests/Tests/Microsoft_UI_Xaml_Controls/Given_WebView2.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Repeater/Given_ItemsRepeater.cs

- Bugfix
Additional retries for flaky runtime tests

test: Adjust webview2 and items repeater retry for android

---

build/PackageDiffIgnore.xml
build/Uno.UI.Build.csproj
src/SourceGenerators/Uno.UI.SourceGenerators.netcore.Tests/DependencyObjectGeneratorTests/Given_DependencyObjectGenerator.cs
src/SourceGenerators/Uno.UI.SourceGenerators/DependencyObject/DependencyObjectGenerator.cs
src/Uno.UI/UI/Xaml/FrameworkElement.netstd.cs

BREAKING CHANGE: `DependencyObjectGenerator` no longer generated an empty ApplyCompiledBindings method.
GitHub Issue (If applicable): #8339, closes #11241

fix!: Remove ApplyCompiledBindings from code generated by `DependencyObjectGenerator`

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ToolTipTests/ToolTip_Tests.cs
src/Uno.UI/UI/Xaml/Controls/ToolTip/ToolTipService.cs

GitHub Issue (If applicable): closes #10979
- Bugfix

fix(ToolTip): add the missing part of fixing the issue #10979

---

build/ci/.azure-devops-winui-convert.yml
src/Uno.UWPSyncGenerator/Generator.cs

This reverts commit ec156b125fd679681e4826f1dfbf4cf8c5bd62d8.

ci: Restore net7 build for conversion

---

src/Uno.UI/UI/Xaml/Media/ImageBrush.Android.cs
src/Uno.UI/UI/Xaml/Media/ImageSource.Android.cs
src/Uno.UI/UI/Xaml/Media/ImageSource.cs
src/Uno.UI/UI/Xaml/Media/ImageSource.iOS.cs
src/Uno.UI/UI/Xaml/Media/ImageSource.iOSmacOS.cs
src/Uno.UI/UI/Xaml/Media/Imaging/SvgImageSource.Android.cs
src/Uno.UI/UI/Xaml/Media/Imaging/SvgImageSource.cs
src/Uno.UI/UI/Xaml/Media/Imaging/SvgImageSource.iOSmacOS.cs
src/Uno.UI/UI/Xaml/Media/Imaging/SvgImageSource.provider.cs

chore(ImageSource): enable nullable

---

src/Uno.UI.RuntimeTests/Tests/Microsoft_UI_Xaml_Controls/Given_WebView2.cs

Related to https://github.com/unoplatform/uno/issues/11997

ci: Disable flaky webview test on iOS

---

src/Uno.UI.Runtime.Skia.Gtk/GtkHost.cs
src/Uno.UI.Runtime.Skia.Gtk/UI/Controls/UnoGtkWindow.cs
src/Uno.UI.Runtime.Skia.Wpf/UI/Controls/UnoWpfWindow.cs
src/Uno.UI.Runtime.Skia.Wpf/WpfHost.cs

GitHub Issue (If applicable): closes #12737

fix: Fix Main window is not set yet exception on Skia

---

src/Uno.UI.RemoteControl.VS/EntryPoint.cs

GitHub Issue (If applicable): closes #12784

fix: Correcting event handler removal

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/AutoSuggestBoxTests/AutoSuggestBox_SoftKeboard.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/AutoSuggestBoxTests/AutoSuggestBox_SoftKeboard.xaml.cs
src/Uno.UI/UI/Xaml/Controls/AutoSuggestBox/AutoSuggestBox.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/MultilineTextBoxDelegate.iOS.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/SinglelineTextBoxDelegate.iOS.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.iOS.cs

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/11961
- Bugfix
Selection on an iOS AutoSuggestBox is not working. 
**Reason**: When selecting an option from the List, the `TextBox` sends an `EndEditing` notification that later ends in an `UnFocus()` event. This makes the `PopUp` associated with the `AutoSuggestBox` get dismissed before the PointerEvent is executed. 

fix(iOS): AutoSuggestBox Selection

---

doc/articles/migrating-from-previous-releases.md

Adjust position of migration text.

docs: Adjust migration

---

src/Uno.UI.Composition/Composition/SkiaCompositionSurface.skia.cs
src/Uno.UI.Composition/Composition/SkiaExtensions.skia.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media_Imaging/Given_RenderTargetBitmap.cs
src/Uno.UI/UI/Xaml/Media/Imaging/RenderTargetBitmap.Android.cs
src/Uno.UI/UI/Xaml/Media/Imaging/RenderTargetBitmap.cs
src/Uno.UI/UI/Xaml/Media/Imaging/RenderTargetBitmap.skia.cs

GitHub Issue (If applicable): #9080

fix: Fix rendering of RenderTargetBitmap

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media_Animation/Given_ObjectAnimationUsingKeyFrames.cs

GitHub Issue (If applicable): #9080
I've tried it over 20-30 times, it didn't fail a single time. 🤞Let's hope it isn't a CI-specific problem

chore: enable When_RepeatDuration on skia

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media_Animation/Given_ObjectAnimationUsingKeyFrames.cs

Revert "chore: enable When_RepeatDuration on skia"

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media_Animation/Given_DoubleAnimation.cs

These tests already work locally, but they had problem during CI. Let's see if they're still flaky

chore: enable When_RepeatForever_ShouldLoop and When_Render_Then_CanRenderOnCanvas on skia

---

.editorconfig
src/Directory.Build.props
src/Uno.UI.BindingHelper.Android/Uno.UI.BindingHelper.Android.netcoremobile.csproj
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel/IAppInfoStatics.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Gaming.UI/GameMonitor.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Gaming.UI/GameMonitoringPermission.cs

Let's see if that has an impact on https://github.com/unoplatform/uno/issues/12030

chore(deps): Update Microsoft.CodeAnalysis.NetAnalyzers

---

src/Uno.UI.BindingHelper.Android/Uno.UI.BindingHelper.Android.netcoremobile.csproj

build: Run `_CompileUnoJava` in design-time builds

---

src/Uno.UI.RuntimeTests/IntegrationTests/common/TestServices.InputHelper.cs
src/Uno.UI.RuntimeTests/IntegrationTests/dxaml/SafeEventRegistration.cs
src/Uno.UI.RuntimeTests/IntegrationTests/dxaml/controls/calendardatepicker/CalendarDatePickerIntegrationTests.cs

This is a followup to https://github.com/unoplatform/uno/pull/13056 and responds to some comments after the merge.

CalendarDatePickerIntegrationTests followup

---

build/ci/templates/nuget-cache.yml

Cherry-picked from https://github.com/unoplatform/uno/pull/13330

ci: Adjust nuget cache folder creation

---

src/Uno.UI/UI/Xaml/Media/Animation/Storyboard.cs

GitHub Issue (If applicable): closes #13354

fix: Fix possible race condition in animations

---

build/uno.winui.runtime-replace.targets
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs

Backport https://github.com/unoplatform/uno/pull/12247 and b709f737ff2f08836cbb89b3bd19ccca7d71253b

Backport #12247 and b709f73

---

src/Uno.UI.FluentTheme.v1/Resources/Version1/PriorityDefault/PersonPicture.xaml
src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault/PersonPicture.xaml
src/Uno.UI/Microsoft/UI/Xaml/Controls/PersonPicture/PersonPicture.xaml

GitHub Issue (If applicable): closes #10883
Currently the default style have a fix background and other properties for the ellipse control.
The background and other properties are now overwriteable.

PersonPicture update: Overwriteable properties for style

---

doc/articles/get-started-vscode.md

closes https://github.com/unoplatform/uno/issues/13472

docs: Adjust vscode debugging steps

---

doc/import_external_docs.ps1

Update Uno.Extensions docs to include the latest Maui Embedding related changes

docs: Update Uno.Extensions docs

---

src/Uno.UI/UI/Xaml/FrameworkElement.skia.cs

Not a lot of saving, but why not :)

perf: Remove unused InvalidateMeasureCallCount (saves 4 bytes per FrameworkElement instance)

---

doc/articles/features/windows-storage-pickers.md

Just a small PR that fixes the parameter name on the ctor.

♻️Fix FilePicker docs

---

doc/import_external_docs.ps1

docs: update themes and toolkit docs

---

doc/articles/features/working-with-xaml-hot-reload.md
doc/articles/get-started-vs-2022.md
doc/articles/guides/solution-building-single-targetframework.md

closes https://github.com/unoplatform/uno/issues/14195

docs: misc updates

---

doc/articles/toc.yml
doc/import_external_docs.ps1
doc/import_external_docs_test.ps1

feat: Adding workshops to docs

feat: Adding workshops to docs

---

doc/articles/toc.yml

docs: Update toc.yml for the workshops

docs: Update toc.yml for the workshops

---

doc/import_external_docs.ps1

chore: Update import_external_docs.ps1 for latest workshops doc

chore: Update import_external_docs.ps1 for latest workshops doc

---

src/Uno.UI/DataBinding/BindingPath.BindingItem.cs

Quick cleanup found while investigating another issue.

chore: Remove unused parameter

---

doc/articles/migrating-to-uno-5.md

closes https://github.com/unoplatform/uno/issues/14458

docs: Updating hot reload docs to mention new hot reload commands

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/CommandBarPages/CommandBarFirstPage.xaml
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/CommandBarPages/CommandBarFirstPage.xaml.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/CommandBarPages/CommandBarSecondPage.xaml
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/CommandBarPages/CommandBarSecondPage.xaml.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_CommandBar.cs
src/Uno.UI/Controls/CommandBar/CommandBarNavigationItemRenderer.iOS.cs
src/Uno.UI/Controls/CommandBar/CommandBarRenderer.iOS.cs
src/Uno.UI/Controls/CommandBar/NativeCommandBarPresenter.iOS.cs
src/Uno.UI/Controls/Renderer.cs

fix: avoid creating disconnected native commandbars on load

---

doc/articles/features/using-skia-gtk.md
doc/articles/get-started-vs-2022.md

related to https://github.com/unoplatform/uno/discussions/14680

docs: Update gtk setup

---

doc/articles/get-started-next-steps.md

docs: Fix broken links

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ComboBox.cs
src/Uno.UI/UI/Xaml/Controls/Primitives/Selector.cs

GitHub Issue (If applicable): closes #14661

fix(Selector): ItemsSource after SelectedItem

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Composition/Given_CompositionNineGridBrush.cs
src/Uno.UI/UI/Xaml/Media/LoadedImageSurface.skia.cs

GitHub Issue (If applicable): closes #14673

fix: Ensure LoadCompleted is fired on UI thread

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_RadioButton.cs

test: Don't instantiate EventTester on the UI thread

---

doc/articles/supported-features.md

docs: Update supported-features.md

---

doc/articles/features/working-with-strings.md

update the l12n doc with more info and links to relevant tutorials

docs: Update working-with-strings.md

---

doc/articles/features/windows-applicationmodel.md
doc/articles/features/windows-phone-devices-notification-vibrationdevice.md
doc/articles/features/windows-system-display.md
doc/articles/features/windows-system-power.md
doc/articles/features/windows-system-profile.md
doc/articles/features/windows-system-userprofile.md
doc/articles/features/windows-system.md
doc/articles/features/windows-ui-markup-extensions.md
doc/articles/features/windows-ui-notifications.md
doc/articles/toc.yml

docs: Improve feature docs and TOC

---

doc/articles/splash-screen.md

This PR adds information about `Uno.Resizetizer` to the old school SplashScreen docs.
- 

Update old school Splash screen docs

---

doc/articles/contributing/guidelines/pull-requests.md

docs: Update pull-requests.md

---

doc/articles/contributing/build-artifacts.md

docs: Update NuGet link to Uno.WinUI

---

build/Uno.UI.Build.csproj
build/convert-sourcetree-to-winui.cmd
build/run-doc-generation.cmd
doc/articles/toc.yml

chore: Move to docfx dotnet tool

---

doc/articles/get-started-dotnet-new.md

**NOTE: This will need further updates when https://github.com/unoplatform/uno/issues/14775 is resolved**

docs: Update get-started-dotnet-new

---

doc/articles/features/working-with-animations.md

docs: Update working-with-animations

---

doc/articles/feature-flags.md

docs: Update feature-flags

---

doc/articles/signalr.md

docs: Update signalr.md

---

doc/articles/how-uno-works.md

docs: Update how-uno-works

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Button.cs

GitHub Issue (If applicable): closes #14731

test: doubletapping a button should not trigger PointerPressed

---

doc/articles/platform-specific-csharp.md

docs: Update platform-specific-csharp.md

---

build/test-scripts/ios-uitest-run.sh
src/Directory.Build.targets
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_MediaPlayerElement.cs

chore: Bump Xamarin.UITests

---

src/Uno.UWP/Media/Capture/CameraCaptureUI.iOS.cs

GitHub Issue (If applicable): closes #14034 
- Bugfix
Dialog to pick a photo is not dismissing when hitting on "Cancel" button.

fix(iOS): CameraCaptureUI cancel action

---

doc/articles/features/compass.md

Updated the page to include more details about the Android implementation specific. MAUI suggested links for this are used.

docs: Update `Compass` to include more Android specifics

---

src/Uno.UI.RuntimeTests/Tests/Microsoft_UI_Xaml_Controls/Given_PipsPager.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/PipsPager/PipsPager.cs

Noticied an issue similar to #11795 while looking at #11068. Turns out that I forgot to account for orientation.

Pipspager  vertical scrolling

---

src/Uno.UI.FluentTheme.v2/themeresources_v2.xaml

chore: Add missing themeresources_v2.xaml changes

---

src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/Repeater/RepeaterFocusTests.cs

Tests out of date
Tests updated

test: Update `RepeaterFocusTests` to latest WinUI sources

---

doc/articles/common-issues-ioscatalyst.md
doc/articles/features/vscode-advanced-mobile-debugging.md
doc/articles/getting-started/wizard/platforms.md
doc/articles/getting-started/wizard/startup.md
doc/articles/uno-app-solution-structure.md

docs: update mac catalyst naming

---

doc/articles/common-issues-vs2022.md
doc/articles/features/using-linux-framebuffer.md
doc/articles/getting-started/counterapp/get-started-counter-csharp-mvux.md
doc/articles/getting-started/counterapp/get-started-counter-csharp-mvvm.md
doc/articles/getting-started/counterapp/get-started-counter-xaml-mvux.md
doc/articles/getting-started/wizard/presentation.md
doc/articles/guides/hotswap-app-language.md
doc/import_external_docs.ps1

Publishing extensions docs changes: https://github.com/unoplatform/uno.extensions/pull/2107

docs: update uno.extension docs

---

.vsts-ci.yml
build/Uno.UI.Build.csproj
build/ci/.azure-devops-wasm-uitests.yml
build/test-scripts/wasm-run-automated-uitests.sh
src/SamplesApp/SamplesApp.UITests/RuntimeTests.cs
src/SamplesApp/SamplesApp.UITests/SampleControlUITestBase.cs
src/SamplesApp/SamplesApp.Wasm/WasmScripts/TestRunner.js
src/Uno.NUnitTransformTool/Program.cs
src/Uno.UI.RuntimeTests/IntegrationTests/common/TestServices.cs
src/Uno.UI.RuntimeTests/MUX/Helpers/EventTester.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs

chore: Adjust wasm tests container shared memory

---

src/Uno.UI/FeatureConfiguration.cs

docs: Update doc comment for UseLegacyContentAlignment

---

doc/articles/features/using-winui2.md
doc/articles/toc.yml
doc/articles/using-uno-ui.md
doc/articles/uwp-vs-winui3.md

docs: Update Fluent styles docs

---

doc/articles/features/working-with-codespaces.md

chore: fix typo (missing space between words)

---

doc/articles/migrating-from-previous-releases.md

docs: fix migration document typos

---

build/cSpell.json
doc/articles/features/resources-trimming.md
doc/articles/migrating-from-net7-to-net8.md
doc/articles/migrating-from-previous-releases.md
doc/articles/migrating-to-uno-5.md
doc/articles/toc.yml

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/pull/14820

docs: .NET 8 upgrade

---

build/sign-package.ps1

- Bugfix
Ensure that the build fails when signing a file fails.

ci: Fail signing step on signing failure

---

src/SourceGenerators/Uno.UI.SourceGenerators.Tests/DependencyObjectGeneratorTests/Given_DependencyObjectGenerator.cs
src/SourceGenerators/Uno.UI.SourceGenerators.Tests/DependencyPropertyGeneratorTests/Given_DependencyPropertyGenerator.cs
src/SourceGenerators/Uno.UI.SourceGenerators.Tests/ImplementedRoutedEventsGeneratorTests/Given_ImplementedRoutedEventsGenerator.cs
src/SourceGenerators/Uno.UI.SourceGenerators.Tests/Uno.UI.SourceGenerators.Tests.csproj
src/SourceGenerators/Uno.UI.SourceGenerators.Tests/Verifiers/CSGenerator.cs
src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Given_AttachedPropertyWithNoFuzzyMatching.cs
src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Given_HotReloadEnabledInBuild.cs
src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Out/SOSLIOFRT/XamlCodeGenerator_MainPage_d6cd66944958ced0c513e0a04797b51d.cs

test: Get source gen tests to run in WinUI tree

---

build/cSpell.json
doc/articles/guides/localization.md

GitHub Issue (If applicable): closes #11713
Added more specifics on how to properly localize a WinUI 3 app 

docs: Update localization to include WinUI 3 specifics

---

.gitpod.yml
build/gitpod/.gitpod.Dockerfile
build/gitpod/build-skia.sh
build/gitpod/build-wasm.sh
src/SamplesApp/SamplesApp.Skia.Linux.FrameBuffer/SamplesApp.Skia.Linux.FrameBuffer.csproj
src/SamplesApp/SamplesApp.Skia/SamplesApp.Skia.csproj
src/SamplesApp/UnoIslands.Skia.Wpf/UnoIslands.Skia.Wpf.csproj
src/Uno.UI.FluentTheme.v1/FluentMerge.targets
src/Uno.UI.FluentTheme.v2/FluentMerge.targets
src/Uno.UI.RemoteControl.Server.Processors/Uno.UI.RemoteControl.Server.Processors.csproj
src/Uno.UI.TestComparer/Uno.UI.TestComparer.csproj

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/14899

Gitpod update

---

doc/import_external_docs.ps1

Related to this fix: https://github.com/unoplatform/uno.extensions/pull/2120

docs: Update Extensions to include MAUI embedding Documentation fixes

---

src/Uno.UWP/UI/ViewManagement/StatusBar/StatusBar.Android.cs

perf: StatusBar fixes

---

build/cSpell.json

Fixes failure `./doc/articles/faq.md:65:220 - Unknown word (Holo)`

chore: Update cSpell.json to fix CI failure

---

src/Uno.UI/UI/Xaml/ILayouterElement.cs

chore: Include `ILayouterElement` only on needed platforms

---

doc/articles/getting-started/counterapp/get-started-counter.md

fix: Correcting links

---

src/Uno.UI.RuntimeTests/Tests/Microsoft_UI_Xaml_Controls/Given_RatingControl.cs

**This change is needed to make the test pass in the lifecycle branch.**

test: Fix `When_Loaded_Then_Unloaded_Tap` test

---

src/Uno.UI/UI/Xaml/Documents/InlineCollection.skia.cs

perf: Use ArrayPool for very temporarily arrays in InlineCollection.Draw

---

src/Uno.UI/UI/Xaml/Documents/InlineCollection.skia.cs

perf: Access Color DP once in InlineCollection.Draw

---

src/Uno.UI/Uno.UI.Reference.csproj
src/Uno.UI/Uno.UI.Tests.csproj
src/Uno.UI/Uno.UI.netcoremobile.csproj

build: Remove <Nullable>disable</Nullable> from csprojs

---

src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Out/SOSLIIOFDOTAFE/XamlCodeGenerator_MainPage_d6cd66944958ced0c513e0a04797b51d.cs
src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Out/SOSLIOFPLR/XamlCodeGenerator_MainPage_d6cd66944958ced0c513e0a04797b51d.cs
src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Out/TDBMIDTIRD/XamlCodeGenerator_MyResourceDictionary_92716e07ff456818f6d4125e055d4d57.cs
src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Out/WBENIT/XamlCodeGenerator_Binding_ElementName_In_Template_66bf0a54f1801c397a6fa4930a237eca.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs

GitHub Issue (If applicable): closes #14889

chore(xamlgen): Add missing `EditorBrowsableAttribute`

---

src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.cs

It seems this is saving few minutes for Skia snapshot job in CI.

perf(SamplesApp): Avoid unnecessary expensive GC.Collect

---

doc/articles/getting-started/counterapp/get-started-counter-csharp-mvux.md
doc/articles/getting-started/counterapp/get-started-counter-csharp-mvvm.md
doc/articles/getting-started/counterapp/get-started-counter-xaml-mvux.md
doc/articles/getting-started/counterapp/get-started-counter-xaml-mvvm.md
doc/articles/getting-started/counterapp/get-started-counter.md

Counter sample C# Markup links are broken

docs: fix markup external links

---

doc/articles/features/working-with-xaml-hot-reload.md
doc/articles/what-is-uno.md

Some links for external resources are not working correctly

docs: fix broken external links

---

doc/articles/controls/ComboBox.md

docs: update combobox reference

---

src/Uno.UI.RuntimeTests/Tests/HotReload/Frame/HRApp/Tests/RemoteControlExtensions.cs

test: Ensure XAML change is reverted in HR tests even in case of failure

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Flyout.cs

GitHub Issue (If applicable): closes #14606

test: Fix conditional compilation of `When_LoadedAndUnloaded_Check_Binding`

---

src/Uno.UWPSyncGenerator/DocGenerator.cs

AppBarButton do not have link to Playground.
AppBarButton do have link to Playground.
https://unodocsprstaging.z13.web.core.windows.net/pr-14958/articles/implemented/microsoft-ui-xaml-controls-appbarbutton.html

[Docs] Add AppBarButton Playground link

---

build/nuget/Uno.WinUI.Skia.Gtk.props

chore: Cleanup Uno.WinUI.Skia.Gtk.props

---

src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault/AutoSuggestBox_themeresources.xaml

GitHub Issue (If applicable): closes #15004
- Bugfix

fix: `AutoSuggestBox` is not styled correctly on hover

---

doc/articles/faq.md

Moving commonly asked questions to general FAQ to preserve that content, ahead of refactoring our main doc page.

docs: Update faq.md

---

src/Uno.UI/UI/Xaml/Controls/MediaPlayerElement/MediaPlayerElement.cs

fix: Fix NaturalVideoDimensionChanged event subscription

---

src/Uno.UI.FluentTheme.v1/themeresources_v1.xaml
src/Uno.UI.FluentTheme.v2/themeresources_v2.xaml

chore: Add missing style changes

---

src/Uno.Foundation/Extensions/VectorExtensions.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/Expander/Expander.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/SwipeControl/SwipeControl.Uno.cs
src/Uno.UI/UI/Input/GestureRecognizer.Manipulation.cs
src/Uno.UI/UI/Xaml/Media/Brush.skia.cs
src/Uno.UI/UI/Xaml/Media/EllipseGeometry.skia.cs
src/Uno.UI/UI/Xaml/Media/Imaging/RenderTargetBitmap.Android.cs
src/Uno.UI/UI/Xaml/Media/LineGeometry.skia.cs
src/Uno.UI/UI/Xaml/Media/VisualTreeHelper.cs
src/Uno.UI/UI/Xaml/UIElement.skia.cs
src/Uno.UWP/UI/Input/GestureRecognizer.Manipulation.cs

GitHub Issue (If applicable): closes #14984 
- Bugfix
Not available.
Available.

feat: Re-add `VectorExtensions`

---

src/Uno.UI/UI/Xaml/FrameworkTemplatePool.cs

fix(FrameworkTemplatePool): Detach native view from parent when recycling

---

doc/articles/intro.md

docs: Update intro.md

---

src/Uno.UI.RuntimeTests/IntegrationTests/common/TestServices.KeyboardHelper.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ComboBox.cs
src/Uno.UI/Generated/3.0.0.0/Microsoft.UI.Xaml.Controls/ComboBox.cs
src/Uno.UI/UI/Xaml/Controls/ComboBox/ComboBox.cs
src/Uno.UI/UI/Xaml/Controls/ComboBox/ComboBoxItem.cs
src/Uno.UI/UI/Xaml/Input/KeyRoutedEventArgs.cs

feat: Implement ComboBox.IsTextSearchEnabled

---

src/Uno.UI/UI/Xaml/Controls/AppBar/AppBarAutomationPeer.cs
src/Uno.UI/UI/Xaml/Controls/AppBar/AppBarButtonAutomationPeer.cs
src/Uno.UI/UI/Xaml/Controls/AppBar/AppBarToggleButtonAutomationPeer.cs

GitHub Issue (If applicable): part of #14344
- Feature

chore: Update `AppBarAutomationPeer`s

---

src/Uno.UI.FluentTheme.v1/Resources/Version1/PriorityDefault/NavigationView_v1.xaml
src/Uno.UI.FluentTheme.v1/themeresources_v1.xaml
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement_And_Leak.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Repeater/Given_ItemsRepeater.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/NavigationView/NavigationView_v1.xaml
src/Uno.UI/UI/Xaml/Style/mergedstyles.xaml

GitHub Issue (If applicable): closes #10309

fix: Fix NavigationView memory leak [Different approach]

---

src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.cs

- Search occurs on the UI thread, blocking input
- The delay for search cancelation is very short
- The search is inefficient (results in a lot repeated `IEnumerable` enumerations)
- Running search on another thread
- Cancelation is now possible even during the search
- Perf improved

refactor: Improve samples app search

---

src/Uno.UI/UI/Xaml/Automation/Peers/ImageAutomationPeer.cs
src/Uno.UI/UI/Xaml/Controls/Image/Image.shared.cs

GitHub Issue (If applicable): part of #14344 
- Feature
Ported the `ImageAutomationPeer` from WinUI source

feat: Port `ImageAutomationPeer`

---

src/SamplesApp/UITests.Shared/Windows_UI_Xaml/Enability/BasicEnability.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/FocusManager/FocusManager_GetFocus_Automated.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_ObservableCollection_CreationCount.xaml.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/ListViewPages/ListView_ObservableCollection_CreationCount.xaml.cs

GitHub Issue (If applicable): closes #15055, closes #15056

perf(samplesapp): Fix SamplesApp leaks

---

build/ci/.azure-devops-skia-tests.yml

ci: Switch Skia snapshot tests to WinUI

---

src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Controls/SampleChooserContent.cs
src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/RatingControlTests/RatingControlPage.xaml
src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/RatingControlTests/RatingControlPage.xaml.cs

GitHub Issue (If applicable): closes #15059

perf: Fix RatingControlPage memory leak

---

build/ci/.azure-devops-wasm-uitests.yml

ci: Fix binlog file name

---

src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/RadioButtonsTests/RadioButtonsPage.xaml.cs

perf(samplesapp): Fix RadioButtonsPage memory leak

---

src/Uno.UI/Microsoft/UI/Xaml/Controls/NavigationView/NavigationView.cs

perf: Fix NavigationView memory leak

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_ResourceDictionary.cs

test: Switch test from `async void` to `async Task`

---

doc/articles/features/working-with-xaml-hot-reload.md

API reference link in https://platform.uno/docs/articles/features/working-with-xaml-hot-reload.html?tabs=vswin%2Cskia#hot-reload is broken.
| Link | Broken |
| :--: | :---: |
|<img width="654" alt="image" src="https://github.com/unoplatform/uno/assets/1900897/ddb8c2f9-9e70-42c8-99f7-e53dcae6b4f3">|<img width="869" alt="image" src="https://github.com/unoplatform/uno/assets/1900897/14fbb628-b5d2-42c6-a7d1-a827a6bb80db">|

docs: fix implemented views link

---

src/Uno.CrossTargetting.targets
src/Uno.UI.RuntimeTests/IntegrationTests/dxaml/controls/calendardatepicker/CalendarDatePickerIntegrationTests.cs
src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/NavigationView/NavigationViewTests.uno.cs
src/Uno.UI.RuntimeTests/Tests/Microsoft_UI_Xaml_Controls/Given_RatingControl.cs
src/Uno.UI.RuntimeTests/Tests/Microsoft_UI_Xaml_Controls/Given_TabView.cs
src/Uno.UI.RuntimeTests/Tests/Uno_UI_Xaml_Core/Given_InputManager.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Border.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Button.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ComboBox.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_CommandBar.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ScrollViewer.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Slider.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Documents/Given_Hyperlink.cs

test: Introduce HAS_INPUT_INJECTOR to ensure tests are run on Windows

---

src/Uno.UI/UI/Xaml/UIElement.Layout.crossruntime.cs

fix: dirty path invalidation for XamlIsland

---

src/Uno.UI.RemoteControl.Host/IDEChannel/IIdeChannelServerProvider.cs
src/Uno.UI.RemoteControl.Host/IDEChannel/IdeChannelServer.cs
src/Uno.UI.RemoteControl.Host/IDEChannel/IdeChannelServerProvider.cs
src/Uno.UI.RemoteControl.Host/Program.cs
src/Uno.UI.RemoteControl.Host/RemoteControlExtensions.cs
src/Uno.UI.RemoteControl.Host/RemoteControlServer.cs
src/Uno.UI.RemoteControl.Host/Uno.UI.RemoteControl.Host.csproj
src/Uno.UI.RemoteControl.Messaging/AssemblyInfo.cs
src/Uno.UI.RemoteControl.Messaging/IDEChannel/ForceHotReloadIdeMessage.cs
src/Uno.UI.RemoteControl.Messaging/IDEChannel/IIdeChannelServer.cs
src/Uno.UI.RemoteControl.Messaging/IDEChannel/IdeMessage.cs
src/Uno.UI.RemoteControl.Messaging/IDEChannel/KeepAliveIdeMessage.cs
src/Uno.UI.RemoteControl.Messaging/IRemoteControlServer.cs
src/Uno.UI.RemoteControl.VS/EntryPoint.cs
src/Uno.UI.RemoteControl.VS/Helpers/ILogger.cs
src/Uno.UI.RemoteControl.VS/IDEChannel/IDEChannelClient.cs
src/Uno.UI.RemoteControl.VS/Uno.UI.RemoteControl.VS.csproj
src/Uno.UI.RemoteControl/Helpers/WebSocketHelper.cs

- Feature
Adds the infrastructure for IDE communication with the DevServer.

feat: Add support for devserver IDE channel

---

src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewMode.Commands.cs
src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewMode.Properties.cs
src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Controls/SampleChooserControl.xaml
src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Controls/SampleChooserControl.xaml.cs

The header is cluttered
The weird padding on the left will be fixed by #15079

refactor: Simplify the Samples app header

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/FocusManager/Focus_WASM_Tab.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/FocusManager/Focus_WASM_Tab.xaml.cs
src/Uno.UI/UI/Xaml/Input/FocusManager.wasm.cs

GitHub Issue (If applicable): closes #14967

fix(textbox): fix textbox losing focus on WASM if alt-tabbed out then back in

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs

test: Disable flaky test `When_ThemeChange` on Wasm

---

src/Uno.UI.Runtime.Skia.Gtk/Extensions/GtkExtensionsRegistrar.cs
src/Uno.UI.Runtime.Skia.Gtk/Input/GtkCorePointerInputSource.cs

GitHub Issue (If applicable): closes #15075
Third round, followup to #14926.

fix: pointer coordinates shift on WSL

---

doc/articles/additional-windows-setup-inline.md

docs: Update Gtk setup on Windows

---

src/Uno.UI/UI/Xaml/Media/Animation/Animators/AnimatorFactory.skia.cs

The deleted overload is used instead of:
https://github.com/unoplatform/uno/blob/0dbdf7ef034a32c29021a919035391021527865e/src/Uno.UI/UI/Xaml/Media/Animation/Animators/AnimatorFactory.cs#L15
which would skip immediate animators in case of zero duration.

chore: Remove `AnimatorFactory.Create` on Skia in favor of the generic overload

---

src/SamplesApp/SamplesApp.Shared/App.xaml.cs

chore: enable skia-rendered TextBox instead of the native Gtk/Wpf overlays

---

doc/articles/get-started-dotnet-new.md

docs: Update dotnet new docs

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ScrollViewer.cs
src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.MuxInternal.cs
src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.cs

GitHub Issue (If applicable): https://github.com/unoplatform/Uno.Gallery/issues/985 https://github.com/unoplatform/Uno.Gallery/issues/1062

fix: scrollviewer grabbing focus on pointer up

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.skia.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.skia.cs
src/Uno.UI/UI/Xaml/Documents/InlineCollection.skia.cs
src/Uno.UI/UI/Xaml/Documents/Run.skia.cs

Minor Skia TextBox improvements + Tab rendering Support for TextBlock

---

build/ci/.azure-devops-skia-tests.yml
build/ci/templates/gtk-install-windows.yml
src/Directory.Build.targets
src/SamplesApp/SamplesApp.Shared/App.Tests.cs
src/SamplesApp/SamplesApp.Skia.Gtk/Program.cs
src/SamplesApp/SamplesApp.Skia/SamplesApp.Skia.csproj
src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.cs
src/SamplesApp/SamplesApp.netcoremobile/SamplesApp.netcoremobile.csproj
src/SamplesApp/UnoIslandsSamplesApp.Skia/UnoIslandsSamplesApp.Skia.csproj
src/Uno.CrossTargetting.targets
src/Uno.UI.RuntimeTests/Tests/HotReload/Frame/HRApp/Program.cs

ci: Split Skia snapshot tests into groups and run on Windows

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs

fix(textbox): raise paste on PasteFromClipboard

---

src/Uno.UI/UI/Xaml/FrameworkTemplatePool.cs

fix: Disable template pooling on Android

---

doc/articles/interop/MSAL.md
doc/articles/interop/wasm-javascript-1.md
doc/articles/interop/wasm-javascript-2.md

docs: Update interop documentation

---

src/Directory.Build.targets

chore: Remove unused package `Xamarin.Build.Download` from Directory.Build.targets

---

doc/articles/controls/ComboBox.md
doc/articles/controls/CommandBar.md
doc/articles/controls/ContentDialog.md
doc/articles/controls/ListViewBase.md
doc/articles/controls/MediaPlayerElement.md
doc/articles/controls/MenuFlyout.md
doc/articles/controls/Pivot.md
doc/articles/controls/Popup.md
doc/articles/controls/ScrollViewer.md
doc/articles/controls/TextBox.md
doc/articles/controls/ToggleSwitch.md
doc/articles/controls/WebView.md
doc/articles/controls/map-control-support.md

docs: Update controls documentation

---

doc/articles/concepts/overview/philosophy-of-uno.md
doc/articles/contributing/guidelines/breaking-changes.md
doc/articles/contributing/guidelines/code-style.md
doc/articles/contributing/guidelines/creating-tests.md
doc/articles/contributing/guidelines/implementing-a-new-winui-winrt-feature.md
doc/articles/contributing/guidelines/issue-triage.md
doc/articles/contributing/guidelines/pull-requests.md
doc/articles/contributing/guidelines/updating-dependencies.md

docs: Update contributing guide

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/Utils/XBindExpressionParser.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/When_xBind_With_Cast_Default_Namespace.xaml
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/When_xBind_With_Cast_Default_Namespace.xaml.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_xBind.cs

GitHub Issue (If applicable): closes #14582

fix: Fix x:Bind cast when type is in default namespace

---

src/Uno.UWP/ApplicationModel/Resources/Core/ResourceQualifier.cs

perf: Avoid HashSet linear search

---

README.md
doc/articles/features/windows-ui-xaml-xbind.md
doc/articles/getting-started/counterapp/include-mvvm.md
doc/articles/getting-started/requirements.md
doc/articles/getting-started/wizard/framework.md
doc/articles/guides/profiling-applications.md
doc/articles/guides/silverlight-migration/00-overview.md
doc/articles/guides/silverlight-migration/01-create-uno-solution.md
doc/articles/guides/silverlight-migration/02-considering-navigation.md
doc/articles/guides/silverlight-migration/03-review-app-startup.md
doc/articles/guides/silverlight-migration/04-migrate-home-page-xaml-and-styles.md
doc/articles/guides/silverlight-migration/05-string-resources.md
doc/articles/guides/silverlight-migration/07-dialogs.md
doc/articles/guides/silverlight-migration/08-data-access-overview.md
doc/articles/guides/silverlight-migration/09-client-auth-service.md
doc/articles/guides/silverlight-migration/12-migrate-auth-ui.md
doc/articles/guides/silverlight-migration/99-useful-resources.md
doc/articles/howto-consume-webservices.md
doc/articles/interop/MSAL.md
doc/articles/logging.md
doc/articles/uno-development/creating-ui-tests.md
doc/articles/uno-development/listviewbase-internals.md
doc/articles/uno-development/themeresource-internals.md
doc/articles/uwp-vs-winui3.md
doc/articles/wpf-migration.md
src/Uno.UI/UI/Xaml/Controls/WebView/README.md

docs: Update Microsoft links

---

doc/articles/get-started-dotnet-new.md

docs: Few more improvements in dotnet new article

---

.github/workflows/uwp-autoconvert.yml

ci: Fix missing step when generating uwp branch

---

doc/articles/features/working-with-xaml-hot-reload.md
doc/articles/guides/how-to-create-control-libraries.md
doc/articles/guides/silverlight-migration/12-migrate-auth-ui.md
doc/articles/uno-development/building-uno-ui.md
doc/articles/uno-development/docfx.md

Follow-up per the review comments on #15122

docs: Few more followup improvements

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_AutoSuggestBox.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.skia.cs

fix(autosuggestbox): fix AutoSuggestBox not opening/closing using the managed skia TextBox

---

src/Uno.Analyzers.Tests/Uno.Analyzers.Tests.csproj

build: Cleanup analyzer tests project

---

doc/articles/uno-development/building-uno-ui.md

docs: More improvements to building-uno-ui docs

---

src/Uno.UI/UI/Xaml/FrameworkElement.reference.cs
src/Uno.UI/UI/Xaml/FrameworkElement.unittests.cs
src/Uno.UI/UI/Xaml/UIElement.reference.cs
src/Uno.UI/UI/Xaml/UIElement.skia.cs
src/Uno.UI/UI/Xaml/UIElement.unittests.cs

chore: Minor cleanups in FrameworkElement and UIElement

---

src/Uno.UWPSyncGenerator/DocGenerator.cs
src/Uno.UWPSyncGenerator/Generator.cs
src/Uno.UWPSyncGenerator/Program.cs

Cleanup sync generator

---

doc/articles/getting-started/requirements.md

docs: Fix WPF/GTK links

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.skia.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.skia.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.skia.cs

fix: skia textbox overlay not disappearing on unfocus when FeatureConfiguration changes

---

build/ci/.azure-devops-package-netcoremobile.yml
build/ci/.azure-devops-package-reference.yml
build/ci/.azure-devops-package-skia.yml
build/ci/.azure-devops-package-wasm.yml
build/ci/.azure-devops-skia-tests.yml
build/ci/.azure-devops-stages.yml

ci: Avoid dependency on "UWP convert" for WinUI-only jobs

---

.github/workflows/uwp-autoconvert.yml
build/ci/templates/dotnet-mobile-install-windows.yml
build/ci/templates/dotnet7-mobile-install-mac.yml

ci: Bump to 7.0.405

---

src/SourceGenerators/Uno.UI.SourceGenerators.Tests/MetadataUpdateTests/Given_HotReloadService.cs

- Bugfix
Restores incorrectly disabled tests

fix: Restore hot reload tests

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBlock.cs
src/Uno.UI/Generated/3.0.0.0/Microsoft.UI.Xaml.Controls/TextBlock.cs
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.cs
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.skia.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/ContentMenuItem.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.skia.cs
src/Uno.UI/UI/Xaml/Documents/InlineCollection.skia.cs

GitHub Issue (If applicable): closes #14998

fix(textblock): clear selection on focus lost, copy/paste support and a simple context menu for skia

---

src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.skia.cs

GitHub Issue (If applicable): closes #15032

fix(passwordbox): use a larger bullet glyph to match WinUI

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_CalendarView.cs
src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.wasm.cs
src/Uno.UI/UI/Xaml/Controls/CalendarView/CalendarViewDayItem.Properties.cs
src/Uno.UI/UI/Xaml/Controls/CalendarView/CalendarViewDayItem.cs

GitHub Issue (If applicable): closes #15177

fix: Fix CalendarDatePicker day item corner

---

.globalconfig
src/Uno.UI.RemoteControl.Host/Uno.UI.RemoteControl.Host.csproj

ci: Build performance improvements related to analyzers

---

src/SamplesApp/SamplesApp.UITests/Extensions/UnoWorkItemAttribute.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_StackPanel.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Shapes/Given_Path.cs

GitHub Issue (If applicable): closes #1329

test: Add UnoWorkItem attribute

---

build/cSpell.json
doc/articles/migrating-to-uno-sdk.md
doc/articles/toc.yml
doc/articles/upgrading-nuget-packages.md

- n/a
Adding docs for Migrating to the Uno.Sdk

Adding migration docs

---

src/Uno.UI.RemoteControl.Messaging/IDEChannel/HotReloadRequestedIdeMessage.cs
src/Uno.UI.RemoteControl.VS/EntryPoint.cs
src/Uno.UI.RemoteControl.VS/IDEChannel/IDEChannelClient.cs

- Feature
Nothing happens when a `ForceHotReloadIdeMessage` is sent/received.
Now the VS DTE is used to act upon the received message and send an acknowledgement back to the caller.
🔥🎨

Have VS act on ForceHotReloadIdeMessage

---

src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePicker.cs

GitHub Issue (If applicable): closes #15224
- Bugfix

fix: Move `DatePicker` cleanup from destructor to `Unloaded`

---

src/Uno.Sdk/Sdk/Sdk.props
src/Uno.Sdk/Sdk/Sdk.targets

- n/a
- Bugfix
ProjectCapabilities are not imported
ProjectCapabilities are imported

import Project Capabilities

---

doc/articles/features/windows-system.md

docs: Added info on using LaunchUriAsync on WASM

---

doc/articles/features/windows-phone-devices-notification-vibrationdevice.md

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/10614

docs: Update `Vibration` to include Android specific requirements

---

doc/articles/features/flashlight.md

GitHub Issue (If applicable): part of #10614 

docs: Update Lamp to include Android specific requirements

---

src/Uno.UI.RuntimeTests/Tests/HotReload/Given_HotReloadWorkspace.cs

test: Make HR test cleanup `void` instead of `async Task`

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TextBlockTests/TextBlockTests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/GradientBrushTests/LinearGradientBrush_Width.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/GradientBrushTests/LinearGradientBrush_Width.xaml.cs
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.wasm.cs
src/Uno.UI/UI/Xaml/UIElement.TextHelper.wasm.cs

GitHub Issue (If applicable): closes #7206

fix: Fix TextBlock.Foreground LinearGradientBrush not taking exact text width

---

doc/articles/features/Lottie.md

docs: Fix outdated Lottie docs

---

doc/articles/uno-development/troubleshooting-source-generation.md

docs: Update `UnoEnableXamlFuzzyMatching` docs

---

src/Uno.UI.FluentTheme.v1/Resources/Version1/PriorityDefault/NavigationBackButton_v1.xaml
src/Uno.UI.FluentTheme.v1/themeresources_v1.xaml
src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault/NavigationBackButton.xaml
src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault/NavigationBackButton_rs1_themeresources.xaml
src/Uno.UI.FluentTheme.v2/themeresources_v2.xaml
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Button.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/NavigationView/NavigationBackButton_v1.xaml

GitHub Issue (If applicable): closes #14032
Styles ported from https://github.com/microsoft/microsoft-ui-xaml/blob/c4e32a2727e2cdcbf3bdf14f8dfe38282dcecd4f/dxaml/xcp/dxaml/themes/generic.xaml#L13374C19-L13374C50 and https://github.com/microsoft/microsoft-ui-xaml/blob/c4e32a2727e2cdcbf3bdf14f8dfe38282dcecd4f/dxaml/xcp/dxaml/themes/generic.xaml#L13446C19-L13446C49

fix: Fix navigation view back button styles

---

src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props

GitHub Issue (If applicable): closes #15303

fix: Include netstdref for net7.0 and net8.0 builds

---

src/Uno.UI.RemoteControl.Host/IDEChannel/IdeChannelServer.cs
src/Uno.UI.RemoteControl.Host/IDEChannel/IdeMessageSerializer.cs
src/Uno.UI.RemoteControl.Messaging/IDEChannel/IIdeChannelServer.cs
src/Uno.UI.RemoteControl.Messaging/IDEChannel/IdeMessageEnvelope.cs
src/Uno.UI.RemoteControl.VS/IDEChannel/IDEChannelClient.cs
src/Uno.UI.RemoteControl.VS/Uno.UI.RemoteControl.VS.csproj

- Bugfix
Adjust serializing of IDE messages because of the lack of inheritance serialization.

fix: Adjust IDE Channel message serialization

---

build/Uno.UI.Build.csproj
build/filters/Uno.UI-packages-netcoremobile-net8.slnf
src/Uno.UI.Foldable/Uno.UI.Foldable.netcoremobile.csproj
src/Uno.UI.Maps/Uno.UI.Maps.netcoremobile.csproj
src/targetframework-override-netprevious.props

GitHub Issue (If applicable): closes #13786
Packages produced supports either net8.0 or net7.0 randomly (CI race condition)
We build now for net7.0 only, which should be enough and is compatible with consumer projects targeting net8.0
Both packages don't have any net8-specific code.

fix: Build Maps and Foldable with NetPrevious (net7.0) only

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBlock.cs
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.skia.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.skia.cs

fix(textbox): stop infinite invalidations in TextBox on WPF

---

src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/RefreshContainerTests/RefreshContainerOnImagePage.xaml.cs
src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/RefreshContainerTests/RefreshContainerPage.xaml.cs

GitHub Issue (If applicable): closes #15062

perf(samplesapp): Make sure RefreshContainerPage timers are stopped

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_Style.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Flyout.cs
src/Uno.UI/UI/Xaml/DependencyObjectExtensions.cs
src/Uno.UI/UI/Xaml/FrameworkElement.cs
src/Uno.UI/UI/Xaml/Style/Style.cs

GitHub Issue (If applicable): closes #15131

fix: Swallow Style setter exceptions as in WinUI

---

src/SamplesApp/SamplesApp.UITests/Microsoft_UI_Xaml_Controls/RadioButtonsTests/Given_RadioButtons.cs
src/SamplesApp/UITests.Shared/Lottie/SampleLottieAnimation.xaml.cs
src/SamplesApp/UITests.Shared/Uno_Web/Http/CookieManagerTests.xaml.cs
src/SamplesApp/UITests.Shared/Windows_Storage/Pickers/FileOpenPickerTests.xaml.cs
src/SamplesApp/UITests.Shared/Windows_Storage/Pickers/FileSavePickerTests.xaml.cs
src/SamplesApp/UITests.Shared/Windows_Storage/Pickers/FolderPickerTests.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_ViewManagement/UISettingsTests.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/FocusManager/Focus_FocusVisual.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/Image_Stretch_Modes_Picker.xaml.cs
src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/NavigationView/NavigationViewTests.cs
src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/Repeater/FlowLayoutTests.cs
src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/Repeater/ViewportTests.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ContentPresenter.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_StackPanel.cs
src/Uno.UI/UI/Xaml/DependencyObjectExtensions.cs
src/Uno.UI/UI/Xaml/UIElement.macOS.cs
src/Uno.UWPSyncGenerator/AttributeGeneration/AttributeUsageAttributeDescription.cs

Refactoring (no functional changes, no api changes)

perf: leverage generic enum getvalues

---

src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Button/Button_Click_Verify_SynchronizationContext.xaml.cs

- Other... Please describe: Sample Test Grouping was wrong

chore: fix manual Sample grouping

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.skia.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.skia.cs

GitHub Issue (If applicable): closes #15307

fix(textbox): caret color should follow theme

---

doc/articles/features/windows-devices-haptics.md

GitHub Issue (If applicable): part of https://github.com/unoplatform/uno/issues/10614

docs: Update `VibrationDevice` to include platform specific requirements

---

build/ci/.azure-devops-wasm-uitests.yml

Both UWP and WinUI builds produce binlog with the same name. The last build that finishes is the winner.
The two binlogs will be published properly as now they have different names, so they won't overwrite each other.

ci: Fix Wasm binlog publishing

---

src/Uno.UI/UI/Xaml/UIElement.skia.cs
src/Uno.UI/UI/Xaml/UIElementCollection.cs

perf: reduce layout invalidations when clearing children when there're none

---

doc/articles/controls/RefreshContainer.md
doc/articles/toc.yml

docs: `RefreshContainer`

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_CalendarView.cs
src/Uno.UI.Tests/Windows_Globalization/When_Calendar.cs
src/Uno.UI/DirectUI/DateComparer.cs
src/Uno.UI/UI/Xaml/Controls/CalendarView/CalendarViewGeneratorHost.cs

fix: Fix CalendarView infinite loop

---

src/SamplesApp/UITests.Shared/Playground/Playground.xaml
src/SamplesApp/UITests.Shared/Playground/Playground.xaml.cs

fix: Playground is not always loading correctly

---

src/Uno.UI/DataBinding/BindingExpression.cs

perf: Avoid interpreter transition in SetTargetValueSafe

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs

This is a comment I added a while back that doesn't seem to make any sense.

chore: Remove wrong comment

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ComboBox.cs
src/Uno.UI/UI/Xaml/Controls/ComboBox/ComboBox.cs

GitHub Issue (If applicable): closes #15406

perf(combobox): Avoid materializing EditableText unnecessarily

---

src/AddIns/Uno.UI.MediaPlayer.Skia.Gtk/VideoView.cs
src/SamplesApp/SamplesApp.UITests/SampleControlUITestBase.cs
src/Uno.UI.RemoteControl.Server.Processors/Helpers/ProcessHelper.cs
src/Uno.UI.Runtime.Skia.Gtk/GtkHost.HarfbuzzPreload.cs
src/Uno.UI.Runtime.Skia.Gtk/Helpers/Dpi/DpiHelper.cs
src/Uno.UI.Runtime.Skia.Gtk/Helpers/Theming/GtkSystemThemeHelperExtension.cs
src/Uno.UI.Runtime.Skia.Gtk/Input/GtkKeyboardInputSource.cs
src/Uno.UI.Runtime.Skia.Gtk/Rendering/OpenGLESRenderSurface.cs
src/Uno.UI.Runtime.Skia.Gtk/Rendering/OpenGLRenderSurface.cs
src/Uno.UI.Runtime.Skia.Gtk/Rendering/SoftwareRenderSurface.cs
src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/ProgressBar/ProgressBarTest.cs
src/Uno.UI/Helpers/InputHelper.cs
src/Uno.UWP/Storage/ApplicationData.skia.cs
src/Uno.UWPSyncGenerator/Helpers/ProcessHelper.cs

refactor: Simplify OS checks

---

src/SourceGenerators/Uno.UI.Tasks/Content/Uno.UI.Tasks.targets
src/SourceGenerators/Uno.UI.Tasks/LinkerHintsGenerator/LinkerDefinitionMergerTask.cs

build: Fix build incrementality

---

src/SourceGenerators/Uno.UI.SourceGenerators.Internal/Analyzers/ObservableVectorAnalyzer.cs
src/Uno.UI.RuntimeTests/Tests/Microsoft_UI_Xaml_Controls/Given_TreeView.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/TreeView/SelectedItemsVector.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/TreeView/TreeViewViewModel.cs

GitHub Issue (If applicable): closes #15214

fix: Fix TreeView not selecting items properly

---

src/Uno.UI.Composition/Composition/CompositionObject.cs

fix: Adjust CompositionObject.SetProperty equality

---

src/Uno.UI/UI/Xaml/DependencyObjectExtensions.cs
src/Uno.UI/UI/Xaml/DependencyObjectStore.cs

perf: Early returns for inherited DP propagation

---

src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/TimePicker/TimePickerIntegrationTests.cs

GitHub Issue (If applicable): closes #15459

test: Fix TimePicker tests crash for 24h clock

---

src/Directory.Build.props

Go to `src/SamplesApp/SamplesApp.Skia.Gtk` and invoke `dotnet build`. The UnoTargetFrameworkOverride isn't picked up.
It's picked up properly.

build: Allow `crosstargeting_override` import to work with command-line builds

---

License.md

fix: Ensure license is recognized by GitHub

---

src/Uno.Sdk/Sdk/Sdk.props
src/Uno.Sdk/targets/Uno.DefaultItems.targets

- Fixes #15411
- Bugfix
We do not exclude existing items that the Wildcard may accidentally duplicate
Default Includes now provide an exclude for the existing items that have been added to prevent adding an item twice.

Updates for default includes

---

src/SourceGenerators/Uno.UI.Tasks/LinkerHintsGenerator/LinkerHintGeneratorTask.cs

fix: Specify root mode for root assembly

---

src/Uno.Sdk/Uno.Sdk.csproj

GitHub Issue (If applicable): closes #15468

fix: Add missing package icon

---

src/Uno.UI/UI/Xaml/Controls/MediaPlayerElement/MediaPlayerPresenter.cs

GitHub Issue (If applicable): closes #15254 
- Bugfix
MPE Sizing gets into an infinite loop calling OnMeasure().

fix(iOS): MPE size measure loops

---

src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/TreeView/TreeViewAlignment.xaml
src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/TreeView/TreeViewAlignment.xaml.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_Style.cs
src/Uno.UI/UI/Xaml/Style/Style.cs

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/15460

fix: Fix style application to consider only explicit style when applying default style

---

src/SourceGenerators/Uno.UI.SourceGenerators.Internal/DependencyObject/DependencyPropertyGenerator.cs
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.cs
src/Uno.UI/UI/Xaml/Documents/TextElement.cs
src/Uno.UI/UI/Xaml/Media/SolidColorBrush.cs

perf: Use GeneratedDependencyProperty for commonly read properties

---

src/Uno.UI.RuntimeTests/Tests/Microsoft_UI_Xaml_Controls/Given_ProgressBar.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/ProgressBar/ProgressBar.cs

GitHub Issue (If applicable): closes #15518

fix(android): Fix NullReferenceException in ProgressBar for custom templates

---

src/Uno.UI.RuntimeTests/Helpers/RawBitmap.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FlowDirection.cs
src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.skia.cs
src/Uno.UI/UI/Xaml/UIElement.skia.cs

fix: Adjust LayoutRound behavior

---

src/Uno.UI/UI/Xaml/DependencyProperty.cs
src/Uno.UI/UI/Xaml/ResourceBindingCollection.cs

perf: Use DP.UniqueId as its hash code

---

src/Uno.UI.Runtime.Skia.Wpf/Input/WpfCorePointerInputSource.cs

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/15542
- Feature

feat: Support for touch/pen input in WPF

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_UIElement.cs
src/Uno.UI/UI/Xaml/UIElement.cs

GitHub Issue (If applicable): closes #15439

fix(skia): Fix TransformToVisual and hit testing to consider Visual.Offset correctly

---

src/Uno.UI.RemoteControl/Uno.UI.RemoteControl.netcoremobile.csproj
src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.iOS.cs

fix: building sample from macos

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBlock.cs
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.skia.cs

fix(textblock): only open context menu on right tap when IsTextSelectionEnabled

---

doc/articles/features/svg.md

docs: Adjust wording in svg support

---

src/Uno.UWP/System/Launcher.cs

GitHub Issue (If applicable): closes #15532 
- Bugfix
Calling `Launcher.LaunchUriAsync()` from non-ui thread throws an error.
Matching with `Launcher.QueryUriSupportAsync()` method. Switching to UIThread whenever the method is called from non-UI Thread.

fix(catalyst): Launcher.LaunchUriAsync from not UI thread

---

src/Uno.UI.Runtime.Skia.Wpf/Input/WpfKeyboardInputSource.cs

fix(textbox): fix numberpad inputs on WPF

---

src/Uno.UI.RuntimeTests/Tests/Windows_System/Given_Launcher.cs

Removes test for behavior update by #15558

fix: Remove deprecated test

---

build/cSpell.json
doc/articles/platform-specific-csharp.md

[Teams](https://teams.microsoft.com/l/message/19:787ad1de1af24252b9041bcbd4ec1ca3@thread.tacv2/1708444612571?tenantId=a297d6c0-b635-41a3-b1e3-558efe71e413&groupId=f55cdec8-036b-4efa-8e1a-c4129ba9bf12&parentMessageId=1708444612571&teamName=Uno%20Platform&channelName=Docs%20and%20Getting%20Started&createdTime=1708444612571)

docs: Add video to Platform-specific C#

---

src/SamplesApp/SamplesApp.Shared/App.xaml.cs
src/SamplesApp/SamplesApp.UITests/UnoSamples_Tests.Keyboard.cs
src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewMode.Properties.cs
src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.cs
src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Controls/SampleChooserControl.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/Input_Test_InsideScrollerViewer_Automated.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/Input_Test_NoScrollViewer_Automated.xaml

- Feature
It is not possible to filter by manual tests

feat: Add manual tests only filter to Samples app

---

src/SamplesApp/SamplesApp.netcoremobile/Android/AndroidManifest.xml
src/Uno.UWP/System/Launcher.Android.cs

GitHub Issue (If applicable): closes #15589
- Bugfix
Outdated API
New API is used

fix: Avoid using unsupported `PackageManger` API on Android 33 and newer

---

doc/articles/controls/NavigationView.md
doc/articles/features/hardware-back-button.md
doc/articles/toc.yml

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/15566

docs: Add Hardware back button and `NavigationView` docs

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.Reflection.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs

chore: Better error messages in Xaml gen

---

build/test-scripts/run-netcore-mobile-template-tests.ps1
src/SourceGenerators/Uno.UI.Tasks/LinkerHintsGenerator/LinkerDefinitionMergerTask.cs

chore: Reenable XAML trimming test

---

doc/articles/getting-started/counterapp/get-started-counter-csharp-mvux.md
doc/articles/getting-started/counterapp/get-started-counter-csharp-mvvm.md

Updated the documentation with new binding updates.

chore: new binding updates

---

src/Uno.UI/UI/Xaml/DependencyObjectStore.AncestorsDictionary.cs

GitHub Issue (If applicable): closes #13110

perf: Make AncestorsDictionary a struct

---

src/Uno.UI/XmlnsDefinitionAttribute.cs

chore: Update XmlnsDefinitionAttribute.cs

---

src/Uno.UI.RuntimeTests/Tests/HotReload/Given_HotReloadWorkspace.cs

test: Enable `When_HotReloadScenario` on WinUI

---

src/Uno.UWP/Storage/Internal/StorageProviders.cs
src/Uno.UWP/Storage/Pickers/FileOpenPicker.iOS.cs
src/Uno.UWP/Storage/StorageFile.iOS.cs

feat(iOS): implement PHPicker for multi media selector

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Composition/VisualTranslationSample.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Composition/VisualTranslationSample.xaml.cs
src/Uno.UI.Composition/Composition/CompositionGetValueStatus.cs
src/Uno.UI.Composition/Composition/CompositionObject.cs
src/Uno.UI.Composition/Composition/ShapeVisual.skia.cs
src/Uno.UI.Composition/Composition/Uno/VisualExtensions.cs
src/Uno.UI.Composition/Composition/Visual.cs
src/Uno.UI.Composition/Composition/Visual.skia.cs
src/Uno.UI.Composition/Generated/3.0.0.0/Microsoft.UI.Composition/CompositionGetValueStatus.cs
src/Uno.UI.Composition/Generated/3.0.0.0/Microsoft.UI.Composition/CompositionObject.cs
src/Uno.UI/Generated/3.0.0.0/Microsoft.UI.Xaml.Hosting/ElementCompositionPreview.cs
src/Uno.UI/UI/Xaml/Hosting/ElementCompositionPreview.cs
src/Uno.UI/UI/Xaml/UIElement.cs

feat(skia): Support `ElementCompositionPreview.SetIsTranslationEnabled`

---

CONTRIBUTING.md
doc/articles/contributing/guidelines/issue-triage.md
doc/articles/faq.md
doc/articles/features/working-with-gitpod.md
doc/articles/get-started-next-steps.md
doc/articles/includes/getting-help.md
doc/articles/uno-development/building-uno-ui.md
doc/articles/uno-development/contributing-intro.md
doc/articles/uno-development/ways-to-contribute.md

GitHub Issue (If applicable): [internal](https://teams.microsoft.com/l/message/19:787ad1de1af24252b9041bcbd4ec1ca3@thread.tacv2/1708962255072?tenantId=a297d6c0-b635-41a3-b1e3-558efe71e413&groupId=f55cdec8-036b-4efa-8e1a-c4129ba9bf12&parentMessageId=1708962255072&teamName=Uno%20Platform&channelName=Docs%20and%20Getting%20Started&createdTime=1708962255072)

docs: Direct links to our Discord server

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Button.cs

GitHub Issue (If applicable): closes #15536

chore: make When_Enabled_Inside_Disabled_Control not flaky on WinUI

---

doc/articles/concepts/overview/why-uno-platform.md

docs: Update why-uno-platform.md

---

doc/articles/platform-specific-xaml.md

docs: Add Tech Bites video to Xaml specific code

---

src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Controls/SampleChooserControl.xaml
src/SamplesApp/UITests.Shared/MessageDialogTests/MessageDialogTest.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/AutoSuggestBoxTests/AutoSuggestBoxChosenSuggestion.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/AutoSuggestBoxTests/AutoSuggestBoxChosenSuggestion.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/AutoSuggestBoxTests/AutoSuggestBox_BitmapIcon.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/AutoSuggestBoxTests/AutoSuggestBox_Description.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/AutoSuggestBoxTests/AutoSuggestBox_Icons.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/AutoSuggestBoxTests/AutoSuggestBox_Keyboard.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/AutoSuggestBoxTests/AutoSuggestBox_Reason.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/AutoSuggestBoxTests/AutoSuggestBox_SoftKeboard.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/AutoSuggestBoxTests/BasicAutoSuggestBox.xaml.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Popups/Given_MessageDialog.cs

GitHub Issue (If applicable): part of #15664
- Feature
- Some samples app improvements
- Marked all ASB tests explicitly as manual/non-manual

test: Explicitly mark manual `AutoSuggestBox` tests

---

doc/import_external_docs.ps1

Update Workshop docs to latest.

docs: Update Workshop to latest version of docs

---

src/Uno.UI/UI/Xaml/DependencyProperty.cs

This will help troubleshoot https://github.com/unoplatform/uno/issues/15673 and providing a better error message for other users.

chore: Throw exception if DP system is accessed from non ui thread

---

src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.cs
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.wasm.cs

perf: Update IsTextTrimmed lazily on WASM

---

src/Uno.UI.Toolkit/Uno.UI.Toolkit.Windows.csproj

build: Remove dead import

---

src/Uno.UI.RuntimeTests/Helpers/UITestHelper.cs

test: Fix UITestHelper.Show

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Flyout.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls_Primitives/Given_Popup.cs
src/Uno.UI/UI/Xaml/Controls/Popup/PopupRoot.cs

GitHub Issue (If applicable): closes (private issue)
- Bugfix

fix: Avoid closing non-light-dismissable flyouts on window activation

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_DatePicker.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TimePicker.cs
src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePicker.Flyout.cs
src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePicker.cs
src/Uno.UI/UI/Xaml/Controls/DatePicker/NativeDatePickerFlyout.Android.cs
src/Uno.UI/UI/Xaml/Controls/DatePicker/NativeDatePickerFlyout.iOS.cs
src/Uno.UI/UI/Xaml/Controls/Flyout/FlyoutBase.cs
src/Uno.UI/UI/Xaml/Controls/TimePicker/NativeTimePickerFlyout.Android.cs
src/Uno.UI/UI/Xaml/Controls/TimePicker/NativeTimePickerFlyout.iOS.cs
src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePicker.partial.mux.cs
src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerSelector.iOS.cs

[Android] fix: TimePicker and DatePicker should follow application theme

---

src/Directory.Build.props

chore(deps): Update NetAnalyzers

---

src/Uno.UI.RuntimeTests/IntegrationTests/dxaml/controls/grid/GridIntegrationTests.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_MediaPlayerElement.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls_Primitives/Given_LayoutInformation.cs

test: Adjust `When_ElementInPaddedGrid_Then_LayoutSlot` to make it more stable

---

src/Uno.UI.Composition/Composition/ExpressionAnimation.cs

fix: Make ExpressionAnimation.Expression non-nullable

---

src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Out/SOSLIIOFDOTAFE/XamlCodeGenerator_MainPage_d6cd66944958ced0c513e0a04797b51d.cs
src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Out/SOSLIOFPLR/XamlCodeGenerator_MainPage_d6cd66944958ced0c513e0a04797b51d.cs
src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Verifiers/CSGenerator.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/NameScope.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/Subclass.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs

GitHub Issue (If applicable): closes #15695

fix: Correct `OriginalSourceLocation` for templates

---

build/ci/.azure-devops-package-netcoremobile.yml
build/ci/templates/dotnet-mobile-install-windows.yml
build/ci/templates/dotnet7-mobile-install-mac.yml
src/uno.mobile-cross-targeting-disable.props

chore: Rename `UnoDisableNet7Mobile` to `UnoDisableNetPreviousMobile`

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/Clipping/UIElement_Clip_Transform_Update.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/Clipping/UIElement_Clip_Transform_Update.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/Clipping/UIElement_Clip_Update.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/Clipping/UIElement_Clip_Update.xaml.cs
src/Uno.UI/UI/Xaml/FrameworkElement.Layout.crossruntime.cs
src/Uno.UI/UI/Xaml/Media/Geometry.cs
src/Uno.UI/UI/Xaml/Media/RectangleGeometry.cs
src/Uno.UI/UI/Xaml/UIElement.cs

fix: Fix clipping changes not applying

---

src/SourceGenerators/Uno.UI.SourceGenerators/BindableTypeProviders/BindableTypeProvidersGenerationTask.cs

GitHub Issue (If applicable): closes #15710
- Bugfix

fix: Avoid XAOBS001 in BindableMetadataGenerator

---

src/Uno.UWP/Microsoft/UI/Windowing/TitleBarHeightOption.cs

fix: Add missing TitleBarHeightOption.Collapsed

---

src/Uno.UI.Composition/Composition/CompositionObject.SubPropertyHelpers.cs

chore: Fix exception message in `TryGetFromProperties`

---

src/Uno.UI/FeatureConfiguration.cs
src/Uno.UI/UI/Xaml/DependencyProperty.cs

chore: Add `FeatureConfiguration.DependencyProperty.DisableThreadingCheck` flag

---

doc/articles/uwp-vs-winui3.md

Update WinUI 3 related article with the new discord link

docs: Update WinUI 3 related article with the new discord link

---

src/SourceGenerators/SourceGeneratorHelpers/Helpers/SymbolExtensions.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/Utils/XBindExpressionParser.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.Reflection.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs

refactor: Small cleanup to xaml generator

---

src/Uno.UI.Composition/Composition/ExpressionAnimationParser/AnimationBinaryExpressionSyntax.cs
src/Uno.UI.Composition/Composition/ExpressionAnimationParser/AnimationIdentifierNameSyntax.cs
src/Uno.UI.Composition/Composition/ExpressionAnimationParser/AnimationTernaryExpressionSyntax.cs
src/Uno.UI.Composition/Composition/ExpressionAnimationParser/ExpressionAnimationLexer.cs
src/Uno.UI.Composition/Composition/ExpressionAnimationParser/ExpressionAnimationParser.cs
src/Uno.UI.Composition/Composition/ExpressionAnimationParser/ExpressionAnimationTokenKind.cs
src/Uno.UI.Composition/Composition/InteractionTracker/InteractionTracker.cs
src/Uno.UI.Tests/CompositionTests/ExpressionAnimationParserTests.cs

feat: Support ternary operator and relational operators in ExpressionAnimation

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs

GitHub Issue (If applicable): closes #15093
- Bugfix
Test was not working
Test is working

fix: removing wasm specific instruction fix When_ThemeChange test in ListViewBase.

---

build/ci/.azure-devops-android-tests.yml
build/ci/.azure-devops-stages.yml

chore: Move android tests to linux scaled pool

---

doc/articles/getting-started/counterapp/includes/include-intro.md
doc/articles/getting-started/counterapp/includes/include-mainpage-layout.md

docs: Fix Counter app images

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs

test: Skip flaky `When_ThemeChange` test

---

src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBaseSource.iOS.cs

chore: Include exception info when ListViewBaseSource.Frame crashes

---

src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CalendarView/CalendarView_Basics.xaml.cs
src/Uno.UWP/Globalization/Calendar.cs

GitHub Issue (If applicable): closes #15761

fix: Workaround CalendarView crash on negative time zones

---

src/Uno.UI.Runtime.Skia.Wpf/UI/Controls/NativeOverlappedPresenter.cs

fix: WPF should honor `IsAlwaysOnTop` flag

---

src/Uno.UI.RuntimeTests/MUX/Helpers/DateTimePickerHelper.cs
src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerFlyoutPresenter.partial.mux.cs

test: fix SelectingTimeSetsSelectedTime to adhere to TimePickerFlyoutPresenter order

---

src/Uno.UI.Composition/Composition/InteractionTracker/IInteractionTrackerInertiaHandler.cs
src/Uno.UI.Composition/Composition/InteractionTracker/InteractionTracker.cs
src/Uno.UI.Composition/Composition/InteractionTracker/InteractionTrackerActiveInputInertiaHandler.AxisHelper.cs
src/Uno.UI.Composition/Composition/InteractionTracker/InteractionTrackerActiveInputInertiaHandler.cs
src/Uno.UI.Composition/Composition/InteractionTracker/InteractionTrackerCustomAnimationState.cs
src/Uno.UI.Composition/Composition/InteractionTracker/InteractionTrackerIdleState.cs
src/Uno.UI.Composition/Composition/InteractionTracker/InteractionTrackerInertiaState.cs
src/Uno.UI.Composition/Composition/InteractionTracker/InteractionTrackerInteractingState.cs
src/Uno.UI.Composition/Composition/InteractionTracker/InteractionTrackerPointerWheelInertiaHandler.cs
src/Uno.UI.Composition/Composition/InteractionTracker/InteractionTrackerState.cs
src/Uno.UI.Composition/Composition/VisualInteractionSource.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Composition/Given_InteractionTracker.cs
src/Uno.UI/UI/Xaml/Internal/InputManager.Pointers.Managed.cs

feat: InteractionTracker pointer wheel support

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_UIElement.cs
src/Uno.UI/UI/Xaml/UIElement.Layout.crossruntime.cs
src/Uno.UI/UI/Xaml/UIElement.Layout.cs
src/Uno.UI/UI/Xaml/UIElement.cs

GitHub Issue (If applicable): closes #15644

fix: explicit Measure calls should invalidate parents if DesiredSize changes

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/WebViewTests/UnoSamples_Test_NavigateToString.cs
src/SamplesApp/UITests.Shared/ItemExclusions.props
src/Uno.UI.RuntimeTests/Tests/Microsoft_UI_Xaml_Controls/Given_WebView2.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_WebView.cs
src/Uno.UI/UI/Xaml/Controls/WebView/WebView1/WebViewExtensions.cs

fix: Avoid NRE on `WebView` navigation

---

src/SamplesApp/SamplesApp.Skia.Generic/SamplesApp.Skia.Generic.csproj
src/Uno.UI.Runtime.Skia.MacOS/Uno.UI.Runtime.Skia.MacOS.csproj

Adjusts macOS binaries location

fix: copy libUnoNativeMac.dylib into Sample.Skia.Generic app

---

doc/import_external_docs.ps1

https://github.com/unoplatform/uno.toolkit.ui/pull/1064
https://github.com/unoplatform/uno.toolkit.ui/pull/1063

docs: update toolkit backported docs

---

src/Uno.UI/UI/Xaml/Documents/InlineCollection.skia.cs

perf: Reduce TextBlock SelectionDetails allocations on Skia

---

src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/NavigationViewTests/TopMode/NavigationViewTopNavOnlyPage.xaml.cs

chore: Fix NRE in NavigationViewTopNavOnlyPage

---

src/Uno.UI/DataBinding/BindingExpression.cs
src/Uno.UI/DataBinding/BindingPropertyHelper.cs
src/Uno.UI/UI/Xaml/DependencyObjectStore.cs
src/Uno.UI/UI/Xaml/Markup/Reader/XamlObjectBuilder.cs
src/Uno.UI/UI/Xaml/Markup/XamlBindingHelper.cs
src/Uno.UI/UI/Xaml/ResourceResolver.cs
src/Uno.UI/UI/Xaml/Setter.cs

perf: Avoid capturing lambdas for BindingPropertyHelper.Convert callsites

---

doc/articles/get-started-vscode.md

docs: docs: Minor adjustments to GS on VS Code

---

src/Uno.UI/UI/Xaml/UIElement.cs

perf: Reduce allocations in ShouldMirrorVisual

---

doc/articles/getting-started/wizard/includes/testing.md

docs: Fix image link

---

src/Uno.UI.Runtime.Skia.X11/X11ClipboardExtension.cs
src/Uno.UI.Runtime.Skia.X11/X11XamlRootHost.x11events.cs
src/Uno.UI.Runtime.Skia.X11/X11_Bindings/X11Helper.cs
src/Uno.UI.Runtime.Skia.X11/X11_Bindings/x11bindings_XLib.cs

chore: poll for events instead of spintwaiting

---

src/SourceGenerators/Uno.UI.SourceGenerators.Internal/DependencyObject/DependencyPropertyGenerator.cs

perf: Reduce memory used by DependencyPropertyGenerator

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ListViewTests/UnoSamples_Tests.ListView.cs

test: Skip `Check_ListView_Swallows_Measure` on Android

---

src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.Android.cs
src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.Uwa.cs
src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.cs
src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.iOS.cs
src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.macOS.cs
src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.skia.cs
src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.wasm.cs

GitHub Issue (If applicable): Alternative to #15822

test: Fix snapshot tests

---

src/AddIns/Uno.UI.Svg/SvgCanvas.cs
src/Uno.UI.Composition/Composition/CompositionClip.skia.cs
src/Uno.UI.Composition/Composition/CompositionMaskBrush.skia.cs
src/Uno.UI.Composition/Composition/CompositionNineGridBrush.skia.cs
src/Uno.UI.Composition/Composition/CompositionShape.skia.cs
src/Uno.UI.Composition/Composition/CompositionSpriteShape.skia.cs
src/Uno.UI.Composition/Composition/CompositionVisualSurface.skia.cs
src/Uno.UI.Composition/Composition/ContainerVisual.skia.cs
src/Uno.UI.Composition/Composition/ShapeVisual.skia.cs
src/Uno.UI.Composition/Composition/SpriteVisual.skia.cs
src/Uno.UI.Composition/Composition/Uno/CompositionConfiguration.cs
src/Uno.UI.Composition/Composition/Uno/DrawingSession.skia.cs
src/Uno.UI.Composition/Composition/Visual.skia.cs
src/Uno.UI.Composition/Composition/VisualCollection.cs
src/Uno.UI/UI/Xaml/Documents/InlineCollection.skia.cs

perf: Misc Skia performance improvements

---

build/ci/.azure-devops-skia-tests.yml
src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.cs

perf: Improve Skia snapshot tests performance
