unoplatform/uno

src/Uno.UI/UI/Xaml/Style/Generic/GenericStyles.cs
src/Uno.UI/Uno.UI.csproj

This works around a strange issue where the source generator, in the context of a VSTS VS15.6 hosted agent, would not pick up the Page item group.

Workaround for VS15.6 Hosted Agents source generation

---

src/Uno.UI.Tests/DependencyProperty/Given_DependencyProperty.Propagation.cs
src/Uno.UI/UI/Xaml/Media/Animation/Timeline.cs
src/Uno.UI/UI/Xaml/VisualTransition.cs

This fixes some transition issues in FlipView, where the drawer would not collapse in overlay mode.

Fix support for VisualTransition.Storyboard children lazy bindings

---

doc/articles/supported-features.md
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/SourceGenerators/XamlGenerationTests/DataTemplate_Events.xaml
src/SourceGenerators/XamlGenerationTests/DataTemplate_Events.xaml.cs
src/Uno.UI.Tests/DependencyProperty/Given_DependencyProperty.AttachedPropagation.cs
src/Uno.UI/UI/Xaml/DependencyObjectStore.cs
src/Uno.UI/UI/Xaml/DependencyPropertyDetailsCollection.cs
src/Uno.UI/UI/Xaml/XamlInfo.cs

This change adds the ability to observe changes of an inherited attached property using RegisterPropertyChangedCallback, and adds the ability to observe changes of an inherited attached property using RegisterPropertyChangedCallback.
This fixes #63.

Add support for Xaml file defined event handlers

---

src/Uno.UI.Tests/BitmapImageTests/Given_BitmapImage.cs
src/Uno.UI.Tests/ItemsControlTests/Given_ItemsControl.cs
src/Uno.UI.Tests/Uno.UI.Tests.csproj
src/Uno.UI.Tests/XamlReaderTests/Given_XamlReader.cs
src/Uno.UI.Tests/XamlReaderTests/When_StaticResource_Style_And_Binding.xamltest
src/Uno.UI/DataBinding/BindingPropertyHelper.FastConvert.cs
src/Uno.UI/UI/Xaml/Controls/ItemsControl/ItemsControl.cs
src/Uno.UI/UI/Xaml/DependencyObjectStore.cs
src/Uno.UI/UI/Xaml/Media/ImageSource.cs
src/Uno.UI/UI/Xaml/Media/ImageSource.net.cs
src/Uno.UI/UI/Xaml/Style/Style.cs
src/Uno.UI/UI/Xaml/UIElementCollection.Net.cs

- Add support for implicit bool to `Visibility` conversion  
- Fix default `Style` constructor does not set the proper property precedence
- Add more `DependencyObjectStore` logging 
- Align `ItemsControl.Items` behavior with UWP (#34)
- Fix invalid uri parsing when set through `BitmapImage.UriSource`

API Compatibility updates

---

src/SourceGenerators/Uno.UI.SourceGenerators/Uno.UI.SourceGenerators.csproj
src/Uno.UI.Wasm/WasmCSS/Uno.UI.css

This line breaks MSEdge pretty badly, where the composition engine freezes and keeps CPU at 100% on one thread. We're now measuring content differently, and this line is not used anymore.
Added nuget override copy for source generators for debugging purposes.

Remove unused css position for unarranged elements

---

src/Directory.Build.props
src/Uno.UI.Tests/BinderTests/Given_Binder.cs
src/Uno.UI.Tests/DependencyProperty/Given_DependencyProperty.ManualPropagation.cs
src/Uno.UI.Tests/DependencyProperty/Given_DependencyProperty.cs
src/Uno.UI/DataBinding/BindingExpression.cs
src/Uno.UI/DataBinding/BindingPath.cs
src/Uno.UI/DataBinding/BindingPropertyHelper.cs
src/Uno.UI/UI/Xaml/DependencyObjectStore.cs
src/Uno.UI/UI/Xaml/DependencyProperty.cs
src/Uno.UI/UI/Xaml/Media/Animation/Timeline.cs
src/Uno.UI/UI/Xaml/Setter.cs

- Use Portable symbols for Xamarin debugging stability
- Enable x:Name reference in x:Bind markup. This requires for a failed BindableMetadata lookup to fall through reflection lookup.
- Assume ".Value" binding path on a primitive is equivalent to self, to enable nullable bindings.
- Adjust unit tests logging
- Enables auto "LogicalChild" treatment to allow for DependencyObjectCollection members to be databound
- Enable parent reset for "LogicalChild" assignations

Misc binding engine alignments

---

src/Uno.UI/UI/Xaml/Controls/Pivot/Pivot.cs

This fixes an issue where the pivot items were not synchronized properly if the style of the control was applied after the items are set.
Fixes #112.

Fix initial pivot rendering

---

src/Uno.UI.BindingHelper.Android/Uno.UI.BindingHelper.Android.csproj

... resulting with an unrelated error message.

The <Error> task were not correctly initialized

---

src/SourceGenerators/System.Xaml/Uno.Xaml.csproj
src/Uno.CrossTargetting.props

It seems that both Xamarin.Android and .Net targets want to add the TargetFramework at the end of the output path when AppendTargetFrameworkToOutputPath is true, resulting in the NuGet pack not working as intending

Fixed android output paths

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/SourceGenerators/Uno.UI.Tasks/Content/Uno.UI.Tasks.targets
src/SourceGenerators/Uno.UI.Tasks/ResourcesGenerator/ResourcesGenerationTask.cs
src/Uno.UI/UI/Xaml/Application.iOS.cs
src/Uno.UI/UI/Xaml/Controls/WebView/UnoWKWebView.iOS.cs
src/Uno.UI/UI/Xaml/NativeApplication.cs
src/Uno.UI/UI/Xaml/ResourceHelper.cs
src/Uno.UWP/ApplicationModel/Resources/ResourceLoader.cs

- Projects no longer need to define `XamlCodeGenerationFiles` (fixes #144)
- Projects no longer need to define `ResourcesDirectory` (fixes #106)
- Projects no longer need to initialize `ResourceHelper.ResourcesService` (fixes #142)
- `ResourceLoader.GetString` is now supported (fixes #142)

Improve support for resources

---

src/SourceGenerators/Uno.UI.Tasks/Content/Uno.UI.Tasks.targets

Fixes ""ResourcesGenerationTask" task was not given a value for the required parameter TargetPlatform" when building cross-targeted libraries.

Fix invalid ResourceGenerationTask use in libraries

---

src/Uno.UI/UI/Xaml/FrameworkElement.Android.cs

Call OnLayoutUpdated from FrameworkElement.Android to reconsider calculations if there is more than one PaddingMask applied
Related issue on VSTS : https://nventive.visualstudio.com/Umbrella/_workitems/edit/131310

Fix not updated bounds

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/SourceGenerators/XamlGenerationTests/CollectionsTests.xaml
src/SourceGenerators/XamlGenerationTests/CollectionsTestsSubjects.cs

- Add ability to declare some properties *and*  items on an object which is a collection
- Add ability to declare the collection object of a `ContentProperty` instead of being forced declare only the items to add to the collection
Issue: #176 #177 
Bugfix
Generated code does not compile
It compiles ;)

Fix inline collection declaration

---

src/Uno.UI.Tests/ControlTests/Given_Control.cs
src/Uno.UI.Tests/DependencyProperty/Given_DependencyProperty.Propagation.cs
src/Uno.UI.Tests/ItemsControlTests/Given_ItemsControl.cs
src/Uno.UI/UI/Xaml/Controls/Control/Control.cs

Issue: #190 
- Bugfix
Templates of controls are loaded as soon as the `Template` property is set
We check if the control has a parent before loading its template.
_Note: for now we only check if the control has a parent, but we should also check if the control is in the visual tree. See the #190 for full behavior description._

Wait for a control to have a parent before loading its template

---

Doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UWP/Devices/Sensors/SimpleOrientationSensor.Android.cs

Updated Android SimpleOrientationSensor calculations based on SensorType.Gravity or based on single angle orientation when the device does not have a Gyroscope.
Issue: #129762
**Internal Work Item**: https://nventive.visualstudio.com/Umbrella/_workitems/edit/129762
- Bugfix
SimpleOrientationSensor for Android does not support correctly devices without gyroscopes
SimpleOrientationSensor for Android does the calculations based on SensorType.Gravity or based on single angle orientation when the device does not have a Gyroscope.

SimpleOrientationSensor.Android - Support devices without gyroscopes

---

src/Uno.UI/UI/Xaml/Controls/ListViewBase/BufferViewCache.Android.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBaseSource.iOS.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/NativeListViewBase.iOS.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.Android.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.iOS.cs

Issue: #
Bugfix
- ScrollIntoView works correctly on iOS when using fixed-height item templates defined inside an ItemTemplateSelector. It still has trouble with variable-sized items.
- ScrollIntoView leaves space to show sticky group headers (iOS and Android)
Feature
Support ScrollIntoViewAlignment.Leading on iOS
Issue 131768

Improve ListView.ScrollIntoView behaviour

---

src/Uno.UI.Tests/ControlTests/Given_Control.cs
src/Uno.UI.Tests/DependencyProperty/Given_DependencyProperty.Propagation.cs
src/Uno.UI.Tests/ItemsControlTests/Given_ItemsControl.cs
src/Uno.UI/UI/Xaml/Controls/Control/Control.cs

Fix bug where Control.ApplyTemplate() would only work when view was attached to the visual tree. UWP only requires that Template be non-null.
Restore correct behaviour of Control.CanCreateTemplateWithoutParent.
Issue: #133790

Control - fix ApplyTemplate()

---

src/Uno.UWP/UI/Core/CoreDispatcher.cs
src/Uno.UWP/UI/Core/CoreDispatcherSynchronizationContext.cs

Do not re-create a new instance of `CoreDispatcherSynchronizationContext` for each scheduled item.
This reduce pressure on the GC, and also allows the `Task` engine to run continuations synchronously instead of systematically post them to the sync ctx.
- Refactoring (no functional changes, no api changes) 
A new `CoreDispatcherSynchronizationContext` is created each time a scheduled item is being executed, and we run continuations synchronously if an item is post on this sync ctx from the UI thread.
We re-use a single instance of `CoreDispatcherSynchronizationContext` per priority. This allows the `Task` engine to validate by its own the needs to post the next continuation, or if it can run it synchronously.
As the `CoreDispatcherSynchronizationContext` already runs posted items …

Do not re-create a new instance of sync ctx for each item scheduled on dispatcher

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.Tests/BinderTests/Given_Binder.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/MultilineTextBoxView.iOS.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/SinglelineTextBoxView.iOS.cs
src/Uno.UI/UI/Xaml/DependencyObjectStore.cs

Issue: #
Bugfix
Fixes infinite 'pingpong' of changing Text values from TextBox in a very specific scenario. Brings us closer to permitting DPs to be changed while they are already changing (allowing features like TextBox.TextChanging to be correctly supported.)
Internal issue: https://nventive.visualstudio.com/Umbrella/_workitems/edit/134026

[iOS] Fix infinite sequence of changing TextBox.Text values

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.Toolkit/MenuFlyoutItemExtensions.cs

Bugfix
MenuFlyout does not load correctly on iOS. If a template contains a MenuFlyout at any level, the template is not loaded (what is displayed is the default TextBlock with DataContext.ToString()).
MenuFlyout is correctly loaded.
Internal work item: 134415

Fix MenuFlyoutItemExtensions being linked out in iOS

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/Image/Image.cs
src/Uno.UI/UI/Xaml/Controls/Image/Image.iOS.cs
src/Uno.UI/UI/Xaml/Media/ImageSource.iOS.cs

Internal issue https://nventive.visualstudio.com/Umbrella/_workitems/edit/133247
Image performance improvements on iOS:
- don't dispatch unnecessarily
- don't download images on UI thread in debug builds

[iOS] Improve Image performance with remote urls

---

doc/articles/working-with-commandbar.md
src/Uno.UI/Controls/CommandBarHelper.iOS.cs
src/Uno.UI/Controls/NativeFramePresenter.iOS.cs
src/Uno.UI/Extensions/UIViewExtensions.iOS.cs

- Feature
`CommandBar` are tightly coupled to the `Frame` and cannot be used without one.
We are now able to render a `CommandBar` using a `UINavigationController` not managed by a `Frame`.

Add a CommandBarHelper that allows apps to use CommanBar without using a Frame

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/IFrameworkElementImplementation.Android.tt
src/Uno.UI/UI/Xaml/Style/Generic/GenericStyles.Android.cs

Issue: # 135112
https://nventive.visualstudio.com/Umbrella/_workitems/edit/135112
Bugfix 
In InitFlipView(), ItemsPanel was set after Template, sometimes making ItemsPanel null in the UpdateItemsPanelRoot() method, causing some crashes on runtime, on Android.
Setting the ItemsPanel before the Template in GenericStyles on Android in order to prevent crashes. Added try-catch statements in IFrameworkElementImplementation for OnNativeLoaded() and OnNativeUnloaded().
- [x ] Tested code with current [supported SDKs](../README.md#supported)
- [x ] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)
- [x ] Tests for the changes have been added …

Fixed and prevented crash caused by a null ItemsPanel in ItemsControl.cs

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBaseSource.iOS.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/NativeListViewBase.iOS.cs

Fix sign error in IsMaterialized, call PrepareLayout() so that correct item sizes are set before target scroll offset is calculated.
Issue: #
https://nventive.visualstudio.com/Umbrella/_workitems/edit/131768

[iOS] ListView - improve ScrollIntoView when ItemTemplateSelector is set

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Media/ImageBrush.iOS.cs

[iOS] Fixed ImageBrush flash/flickering occurs when transitioning to a new page.
Issue: [https://nventive.visualstudio.com/Umbrella/_workitems/edit/135192](https://nventive.visualstudio.com/Umbrella/_workitems/edit/135192)
- Bugfix 
ImageBrush flash/flickering occurs when transitioning to a new page.
No more ImageBrush flash/flickering occurs when transitioning to a new page

[iOS] Fixed ImageBrush flash/flickering upon navigation

---

src/Uno.UI/UI/Xaml/Media/ImageBrush.iOS.cs

Related Issue: https://nventive.visualstudio.com/Umbrella/_workitems/edit/135192
Related PR : https://github.com/nventive/Uno/pull/275
Unnecessary async + await in the OpenImageAsync method in ImageBrush.iOS
Removed unnecessary async + await in the OpenImageAsync method in ImageBrush.iOS

[iOS] Removed unecessary async + await in ImageBrush.iOS

---

src/Uno.UI/UI/Xaml/DependencyObjectCollection.cs

Bugfix
Missing parameterless constructor in DependencyObjectCollection, which makes XamlBehaviors fail.
Restores the missing DependencyObjectCollection constructor

Restore DependencyObjectCollection parameterless constructor

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.Tests/DependencyProperty/Given_DependencyProperty.Weak.cs
src/Uno.UI/DataBinding/ManagedWeakReference.cs

Don't treat a weak-ref target as alive if it's a managed peer whose underlying object has been collected.
This prevents errors from attempting to apply bindings to a collected object, which seem to be particularly prevalent on Android 8 for ImplicitTextBlocks created by ContentPresenter.
Issue: #
[Android][ListView] Group headers can disappear when using ScrollIntoView behavior. https://nventive.visualstudio.com/Umbrella/_workitems/edit/135202
[Android] Contents of button can disappear after a refresh https://nventive.visualstudio.com/Umbrella/_workitems/edit/131884

ManagedWeakReference - ignore natively-collected targets

---

src/Uno.UI/UI/Xaml/Media/ImageSource.iOS.cs

When downloading remote urls and no external downloader is set, use NSUrlSession instead of NSData.FromUrl. This enables response caching, download interruption, etc.
Issue: #
Internal: https://nventive.visualstudio.com/Umbrella/_workitems/edit/133247
Feature
Improved performance with downloaded images on iOS.

[iOS] ImageSource - use NSUrlSession

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UWP/Media/Playback/MediaPlayer.Android.cs

Issue: #
https://nventive.visualstudio.com/Umbrella/_workitems/edit/135646
Bugfix
Video surface remains black on Android when Source is bound
Video plays as expected

Video surface remains black on Android when Source is bound

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UWP/Generated/3.0.0.0/Windows.Media.Playback/MediaPlayer.cs
src/Uno.UWP/Media/Playback/MediaPlayer.Android.cs
src/Uno.UWP/Media/Playback/MediaPlayer.iOS.cs

Feature implementation
MediaPlayer.Dispose() is wrongly marked as NotImplemented, which generates a warning in debug/an error in release at build time.
MediaPlayer.Dispose() can be called, in order to stop the video when you leave its page.
Internal work item: 135799

Implement MediaPlayer.Dispose()

---

src/Uno.UI/UI/Xaml/FrameworkTemplate.cs
src/Uno.UI/UI/Xaml/FrameworkTemplatePool.cs

Expose the option to manually release templates that are held by the FrameworkTemplatePool.
This permits a work around for https://bugzilla.xamarin.com/show_bug.cgi?id=54120 in a specific instance.
Issue: #
https://nventive.visualstudio.com/Umbrella/_workitems/edit/135822

FrameworkTemplatePool - expose manual scavenging

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/OnSystemUiVisibilityChangeListener.Android.cs
src/Uno.UI/UI/Xaml/Controls/Border/Border.Android.cs
src/Uno.UI/UI/Xaml/Controls/BorderLayerRenderer.Android.cs
src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.Android.cs
src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.cs
src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.iOS.cs
src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.net.cs
src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.netstd.cs
src/Uno.UI/UI/Xaml/Controls/Page/NativePage.Android.cs
src/Uno.UI/UI/Xaml/Controls/Panel/Panel.Android.cs
src/Uno.UI/UI/Xaml/Window.Android.cs
src/Uno.UI/UI/Xaml/Window.Desktop.cs
src/Uno.UI/UI/Xaml/Window.cs
src/Uno.UI/UI/Xaml/Window.iOS.cs
src/Uno.UI/UI/Xaml/Window.wasm.cs

On few devices, the navigation can be docked / undocked causing bad visible bounds calculation
https://nventive.visualstudio.com/Umbrella/_workitems/edit/132002
- Bugfix
The navigation bar height / visibility is ignored in the visible bounds
The navigation bar height / visibility is included in the visible bounds

Include navigation bar in the visible bounds calculation

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Media/ImageBrush.Android.cs

Issue: https://nventive.visualstudio.com/Umbrella/_workitems/edit/135258
- Bugfix 
ImageBrush flash/flickering occurs when transitioning to a new page for the first time on Android.
No more ImageBrush flash/flickering occurs when transitioning to a new page for the first time on Android.

[Android] Fixed ImageBrush flash/flickering upon first navigation

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/ListViewBase/NativeListViewBase.iOS.cs

Ensure any dispatched requests are cancelled when ScrollIntoView is called, this prevents stale scroll requests being applied over the top of more recent requests.
Issue: #
https://nventive.visualstudio.com/Umbrella/_workitems/edit/131768

[iOS] ScrollIntoView - cancel previous dispatched scrolls

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.iOS.cs

Ensure to only check for group header size when source is actually grouped. Fixes exception when calling ScrollIntoView().
Issue: #
https://nventive.visualstudio.com/Umbrella/_workitems/edit/136092

[iOS] ListView - fix ScrollIntoView for ungrouped lists

---

src/Uno.UI/UI/Xaml/Controls/MediaPlayer/MediaPlayerPresenter.cs
src/Uno.UWP/Media/Playback/MediaPlayer.iOS.cs

Issue: #
https://nventive.visualstudio.com/Umbrella/_workitems/edit/136063
Bugfix 
Network error does not raise MediaFailed event on iOS
Network error raises MediaFailed event on iOS

Player error on iOS

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/Popup/Popup.iOS.cs

Bugfix
ComboBox on iOS does not display its Popup
ComboBox on iOS now displays its Popup
Internal issues: 136093  & 136172

[iOS] Fix Popup bug where children lose TemplatedParent

---

src/Uno.UI/Controls/NativeCommandBarPresenter.iOS.cs
src/Uno.UI/Controls/RootViewController.iOS.cs
src/Uno.UI/UI/Xaml/Window.iOS.cs
src/Uno.UWP/UI/ViewManagement/ApplicationView.iOS.cs

The navigation bar can have different size depending of orientation and screen size, also impacting visible bounds
https://nventive.visualstudio.com/Umbrella/_workitems/edit/134573
Bugfix
Different sizes are not handled as it should be
Different sizes are handled as it should be

[iOS] Fix visible bounds calculation and Navigation bar size

---

doc/ReleaseNotes/_ReleaseNotes.md
doc/articles/MediaPlayerElement.md
src/Uno.UI/UI/Xaml/Controls/MediaPlayer/MediaTransportControls.cs
src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml
src/Uno.UI/UI/Xaml/Window.Android.cs
src/Uno.UI/UI/Xaml/Window.iOS.cs

None
Feature 
User needs to wait 3sec. before MTC fades out
User can tap on video player to dismiss MTC
None
https://nventive.visualstudio.com/Umbrella/_workitems/edit/136259

Allow tap to dismiss controls + reduce flickers

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Shapes/ArbitraryShapeBase.Android.cs

This prevents displayed path having one pixel cut off.
Internal issue:
https://nventive.visualstudio.com/Umbrella/_workitems/edit/136210

[Android] Path - round up measured size

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SolutionTemplate/UnoSolutionTemplate/UnoQuickStart.Droid/UnoQuickStart.Droid.csproj
src/SolutionTemplate/UnoSolutionTemplate/UnoQuickStart.iOS/UnoQuickStart.iOS.csproj

Enhancement
Android and iOS may fail to break on breakpoints in `.xaml.cs` if the debugging symbol type is Full in projects created from templates.
Breakpoints work in `.xaml.cs` files

Set Portable PDBs in Android and iOS project templates

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.Wasm/WasmCSS/Uno.UI.css

GitHub Issue (If applicable): #312 
Bugfix
The `line-height` in the CSS has been removed: it was causing the problem.

Fixed text is wrongly measured in wasm.

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/WebView/UnoWKWebView.iOS.cs

- Bugfix
WebView's NavigationFailed and NavigationCompleted events are raised when we cancel a navigation on iOS.
WebView doesn't raise NavigationFailed and NavigationCompleted when navigation is cancelled.
https://nventive.visualstudio.com/Umbrella/_workitems/edit/135839

Fix WebView raising too many events when cancelling navigation on iOS.

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/SourceGenerators/XamlGenerationTests/StyleTest.xaml

Bugfix
Can't apply a style on a root control that is not a UserControl. The generator writes a "," instead of a ";"
The generator properly writes a ";"
https://nventive.visualstudio.com/Umbrella/_workitems/edit/137081

Ensures the right closing punctuation is used when applying a style on a root xaml control.

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/KeyboardRectProvider.Android.cs
src/Uno.UI/UI/Xaml/Controls/Panel/Panel.Android.cs
src/Uno.UI/UI/Xaml/FrameworkElement.Android.cs
src/Uno.UI/UI/Xaml/Window.Android.cs
src/Uno.UI/UI/Xaml/Window.iOS.cs
src/Uno.UWP/UI/ViewManagement/ApplicationView.Android.cs
src/Uno.UWP/UI/ViewManagement/ApplicationView.iOS.cs

- Bugfix
On Android, if a PaddingMask is set inside an element contained by a ScrollViewer and the ScrollViewer Content is smaller than the screen size, the layout just get some weird measurements.
Everything is well measured when a PaddingMask is set
https://nventive.visualstudio.com/Umbrella/_workitems/edit/136188

[Android] Fix Bottom Padding Mask on an element inside a ScrollViewer

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/WebView/UnoWKWebView.iOS.cs

- Bugfix
1. Load a local html file in the iOS WebView on a device.
2. Load a second local html file in a different folder in the same WebView.
Result: Navigation Error.
Same steps, but no error.
https://nventive.visualstudio.com/Umbrella/_workitems/edit/103116

Fix local html navigation on iOS WebView.

---

src/Uno.UI/UI/Xaml/Controls/NavigationView/NavigationView.cs

- Bugfix
The ItemInvoked item is called after the SelectedItem event is called, which is different from the UWP implementation.
Align the behavior with UWP.

Adjust the NavigationView event ordering when selecting the settings

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.iOS.cs

- Bugfix
When a TexBlock is measured, it never have the same size due to the Math.Ceiling applied on the result
It also apply Math.Ceiling on the new size for comparison
https://nventive.visualstudio.com/Umbrella/_workitems/edit/138297

[iOS][TextBlock] Use Ceiling on new size when TextBlock is measured

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/Image/Image.netstd.cs

Bugfix
Images defined as follows: 
```
<Image Width="25" Source="http://myimage" />
```
will be displayed using the image's natural size instead of following the provided constraint.
The partial image constraint is now observed.

Adjust Wasm image when only one of Width or Height is specified

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBaseSource.iOS.cs

Ensure that the databound item is properly measured in the edge case where a view happens to be recycled that already has the same DataContext that it's about to be bound to.
Internal issue: https://nventive.visualstudio.com/Umbrella/_workitems/edit/137204

[iOS] ListView - fix bug where item view is clipped

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Media/RotateTransform.Android.cs
src/Uno.UI/UI/Xaml/Media/ScaleTransform.Android.cs
src/Uno.UI/UI/Xaml/Media/SkewTransform.Android.cs

When calculating offset for Rotate/Scale/SkewTransform, use Width/Height instead of MeasuredWidth/Height, since the view may have been arranged with different dimensions to its measured (ie desired) size.
Internal issue: https://nventive.visualstudio.com/Umbrella/_workitems/edit/137979

[Android] Fix bug when applying transform to stretched view

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/SourceGenerators/XamlGenerationTests/InternalObject.cs
src/SourceGenerators/XamlGenerationTests/ResourceDictionaryWithInternalItem.xaml

GitHub Issue (If applicable): #354
- Bugfix
If I create an `internal` object in a resource dictionary, a public property will be generated, so compilation fails.
- If the type of the declared object is not `public`, the property will be typed as `object`
- When we use a static resource using the public static property, we cast it to the target type even if we know the type of the source property.

Add ability to use internal objects in resource dictionaries

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/SourceGenerators/XamlGenerationTests/StyleTest.xaml

GitHub Issue (If applicable): #26 
The following is now supported:
````
<Style>
<Style.Setters>
....
````
Previously Setters had to be directly under `<Style>`.

XAML code gen - support explicit Style.Setters

---

.vsts-ci.yml
src/Uno.UI.Toolkit/Uno.UI.Toolkit.csproj
src/Uno.UI/Behaviors/VisibleBoundsPadding.cs
src/Uno.UI/UI/Xaml/Controls/NavigationView/NavigationView.cs
src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml

- Bugfix
- Feature
- Move `VisibleBoundsPadding` inside Uno.UI so Default Styles can use it
- Fix for `NavigationView` toggle button initial location on iOS
- Close the `NavigationView` pane when an item is selected
- Build Uno.UI.Toolkit for Xamarin.Mac

Multiple adjustments for Xaml Basics

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml
src/Uno.UWP/Media/Playback/MediaPlayer.Android.cs
src/Uno.UWP/Media/Playback/MediaPlayer.iOS.cs

Bugfix 
Player status is not updated properly on media end on Android
On iOS, subtitles are disabled by default. It should not.
Player status is properly updated on media end on Android
On iOS, default subtitles is displayed

MediaPlayerElement minor fixes

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/Slider/Slider.cs

GitHub Issue (If applicable): Fixes #388 
Bugfix 
NRE in Slider.OnDragStarted() when vertical template is not defined
No more NRE

Fix NRE issue on slider

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/KeyboardRectProvider.Android.cs
src/Uno.UI/UI/ViewManagement/InputPane/InputPane.Android.cs
src/Uno.UI/UI/ViewManagement/InputPane/InputPane.cs
src/Uno.UI/UI/Xaml/ApplicationActivity.Android.cs

> Bugfix
On android, `ListView` will scroll up when you tap an item at the bottom of the screen. This also happens if you just hold the press, and the scrolling will occur before you release.
The above described behavior should only happens when the soft input panel (keyboard) is shown and you focus an item that is blocked by the keyboard.
This issue started happening with 123bb68362e72c6c331991135fa471a163193f87 from #324
https://nventive.visualstudio.com/Umbrella/_workitems/edit/138099/
https://nventive.visualstudio.com/Umbrella/_workitems/edit/138463/

fixed list view scrolls up when tapping an item at the bottom of screen

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.Foundation/Runtime.wasm.cs
src/Uno.UI.Wasm/WasmScripts/Uno.UI.d.ts
src/Uno.UI.Wasm/WasmScripts/Uno.UI.js
src/Uno.UI.Wasm/ts/WindowManager.ts
src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelAdapter.wasm.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.wasm.cs
src/Uno.UI/UI/Xaml/UIElement.wasm.cs
src/Uno.UI/UI/Xaml/WindowManagerInterop.Wasm.cs

Bugfix
If a ListView has more space than its inner panel needs, the content will be centered, and each item will be left aligned.
If a ListView has more space than its inner panel needs, the panel will take all the available space, and each item is stretched to use the available space.
ListView logging is now moved to debug level.

[Wasm] Fix VirtualizingPanelAdapter measure and arrange

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs

- Bugfix
[Android] FontFamily, FontSize and FontWeight are not applied anymore on the TextBox's content.
[Android] FontFamily, FontSize and FontWeight are correctly applied on the TextBox's content.
Internal Issue (If applicable): https://nventive.visualstudio.com/Umbrella/_workitems/edit/137892

[Android] Fixed FontStyle is not applied anymore on the TextBox's content

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Directory.Build.props
src/SamplesApp/SamplesApp.Droid/SamplesApp.Droid.csproj
src/SamplesApp/SamplesApp.Wasm/SamplesApp.Wasm.csproj
src/SamplesApp/SamplesApp.iOS/SamplesApp.iOS.csproj
src/SamplesApp/SamplesApp.macOS/SamplesApp.macOS.csproj
src/SourceGenerators/Uno.UI.SourceGenerators/Uno.UI.SourceGenerators.csproj
src/SourceGenerators/Uno.UI.Tasks/Uno.UI.Tasks.csproj
src/SourceGenerators/XamlGenerationTests.Core/XamlGenerationTests.Core.csproj
src/SourceGenerators/XamlGenerationTests/XamlGenerationTests.csproj
src/Uno.Foundation/Uno.Foundation.csproj
src/Uno.UI.Maps/Uno.UI.Maps.csproj
src/Uno.UI.Tests.Performance/Uno.UI.Tests.Performance.csproj
src/Uno.UI.Tests/Uno.UI.Tests.csproj
src/Uno.UI.Toolkit/Uno.UI.Toolkit.csproj
src/Uno.UI.Wasm/Uno.UI.Wasm.csproj
src/Uno.UI/Uno.UI.csproj
src/Uno.UWP/Uno.csproj

- Expand Microsoft.CodeAnalysis to use individual packages
- Add UnoSourceGeneratorUseGenerationHost for all projects
- Enhancement
The source generation host runs in devenv.exe for android targets, creating additional memory stress.
The SourceGeneration tasks host is now used.

Enable SourceGeneratorHost build to reduce VS memory consumption

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UWP/ApplicationModel/DataTransfer/Clipboard.Android.cs
src/Uno.UWP/ApplicationModel/DataTransfer/Clipboard.iOS.cs
src/Uno.UWP/ApplicationModel/DataTransfer/Clipboard.wasm.cs
src/Uno.UWP/ApplicationModel/DataTransfer/DataPackage.cs
src/Uno.UWP/ApplicationModel/DataTransfer/DataPackage.wasm.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.DataTransfer/Clipboard.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.DataTransfer/DataPackage.cs

Feature
No implementation in Uno, other than for wasm.
`Clipboard.SetContent` is made available for uwp, ios, and android.
https://feedback.nventive.com/communities/1/topics/831-need-a-recipe-to-copy-to-clipboard
https://nventive.visualstudio.com/Umbrella/_workitems/edit/35178/

Add support for Windows.ApplicationModel.DataTransfer.Clipboard

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePicker.cs

Bugfix
`DatePicker` is broken on android devices:
- displaying jan 01, 0000
- unresponsive to click
-  `default(DateTimeOffset)` is pushed back to binding source (view-model's property)
`DatePicker` working properly on android.
Caused by https://github.com/nventive/Uno/commit/e7dd73100e7f23d4adf3fc0ce6cb92a7892a2518#diff-d4a82890a95f33d1c168f36da63a34e7
Use this to see change:
git show e7dd7310 -- src\Uno.UI\UI\Xaml\Controls\DatePicker\DatePicker.cs
https://nventive.visualstudio.com/Umbrella/_workitems/edit/138735/

fixed broken DatePicker on android devices

---

build/Uno.UI.nuspec

- Bugfix
Building an application fails with this error:
```
Generation failed: System.AggregateException: One or more errors occurred. 
---> System.InvalidOperationException: Generation failed for Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator. System.AggregateException: One or more errors occurred. 
---> System.IO.FileLoadException: Could not load file or assembly 'Mono.Cecil, Version=0.10.1.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) 
---> System.IO.FileLoadException: The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: …
```

Add missing Mono.Cecil dependency for the XAML source generator

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/FlipView/FlipView.Android.cs

- Bugfix
When navigating back to a page with a FlipView, it disappears. If you navigate to a new page again and go back to the FlipView page, it reappears.
The FlipView is always displayed
https://nventive.visualstudio.com/Umbrella/_workitems/edit/140721

[Android] Notify dataset changed when the current item changed

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.cs
src/Uno.UI/UI/Xaml/Controls/Primitives/SelectorItem.cs

GitHub Issue (If applicable): closes #403 
- Bugfix
ListViewItems show their multi-select checkbox briefly, even if the current mode does not allow multi-selection.
Checkboxes don't appear anymore.

Ensure the disabled ListViewItem multi-selection state is applied properly

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/Controls/CommandBarRenderer.iOS.cs

Bugfix
`CommandBar` showing *nothing* when it is on "home"(first) page, until the user navigates away and then back. This affects `iOS` only.
`CommandBar` now renders properly.
Regression from e35bf4e9 (#357)
AB#140548
https://nventive.visualstudio.com/Umbrella/_workitems/edit/140548

fixed command bar not rendering until reloaded

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/Configuration.cs
src/Uno.UI/UI/Xaml/WindowManagerInterop.Wasm.cs

- Feature
Provides the ability to disable the use of binary interop and fallback on Javascript eval when running in Wasm mode.
This is a workaround for issues similar to this one, in mono-wasm AOT mode: https://github.com/mono/mono/pull/12033

Add configuration flag for Wasm JS Eval vs binary interop

---

src/Uno.UI.Wasm/WasmScripts/Uno.UI.js
src/Uno.UI.Wasm/ts/WindowManager.ts

- Bugfix
Calling WindowManager.resetStyle in hosted mode fails to reset a style, having for effect to prevent collapsed nodes from being visible again.
Calling WindowManager.resetStyle works properly.

[Wasm] Fix hosted mode WindowManager.resetStyle

---

src/SamplesApp/SamplesApp.Wasm/SamplesApp.Wasm.csproj
src/SourceGenerators/Uno.UI.SourceGenerators/TSBindings/TSBindingsGenerator.cs
src/Uno.Foundation/Interop/TSInteropMarshaller.wasm.cs
src/Uno.UI.Wasm.Tests/Tests/TSBindingsTests.cs
src/Uno.UI.Wasm/Uno.UI.Wasm.csproj
src/Uno.UI.Wasm/WasmScripts/Uno.UI.js
src/Uno.UI.Wasm/tsBindings/WindowManagerAddViewParams.ts
src/Uno.UI.Wasm/tsBindings/WindowManagerCreateContentParams.ts
src/Uno.UI.Wasm/tsBindings/WindowManagerDestroyViewParams.ts
src/Uno.UI.Wasm/tsBindings/WindowManagerGetBBoxParams.ts
src/Uno.UI.Wasm/tsBindings/WindowManagerMeasureViewParams.ts
src/Uno.UI.Wasm/tsBindings/WindowManagerRegisterEventOnViewParams.ts
src/Uno.UI.Wasm/tsBindings/WindowManagerRemoveViewParams.ts
src/Uno.UI.Wasm/tsBindings/WindowManagerResetStyleParams.ts
src/Uno.UI.Wasm/tsBindings/WindowManagerSetAttributeParams.ts
src/Uno.UI.Wasm/tsBindings/WindowManagerSetContentHtmlParams.ts
src/Uno.UI.Wasm/tsBindings/WindowManagerSetNameParams.ts
src/Uno.UI.Wasm/tsBindings/WindowManagerSetPropertyParams.ts
src/Uno.UI.Wasm/tsBindings/WindowManagerSetStylesParams.ts
src/Uno.UI/UI/Xaml/WindowManagerInterop.Wasm.cs

- Properly lookup for nested types
- Ensure that arrays are marked using `[MarshalAs(UnmanagedType.LPArray)]`
- Added more logging in `TSInteropMarshaller.InvokeJS`
- Bugfix
Generated TS bindings do not work properly in wasm AOT mode.
Arrays in generated TS bindings need to have a MarshalAs attribute, and the generator is now enforcing this requirement.

TSBindingsGenerator improvements

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.Tests/ItemsControlTests/Given_ItemsControl.cs
src/Uno.UI/UI/Xaml/Controls/ItemsControl/ItemsControl.cs

Related with #382 
Bugfix 
ItemsControl in FlipView does not restore items properly
Items are properly materialized again
None
https://nventive.visualstudio.com/_workitems/edit/141522

Fix items reload in ItemsControl

---

src/Uno.UI/UI/Xaml/Controls/NavigationView/NavigationView.cs

Bugfix
NavigationView fails when PaneTitle is not set.
NavigationView displays properly when PaneTitle is not set.

NavigationView fails when PaneTitle is not set

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/Slider/Slider.cs

- Bugfix
The Slider may crash when the value is updated an no template is applied.
The Slider control does not crash.
https://nventive.visualstudio.com/Umbrella/_workitems/edit/142696

Fix NRE in Slider when no template is applied

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.Tests/Frame/Given_Frame.cs
src/Uno.UI/UI/Xaml/Controls/Frame/Frame.cs

- Bugfix
When a page goes out of the backstack, its `Page.Frame` property is not reset, leading to a potential memory leak.
`Page.Frame` is now set to null.

Fix Frame does not unset Page.Frame

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/Frame/Frame.cs

Feature
A unobserved navigation failure is not logged.
A unobserved navigation failure is raising `Application.UnhandledException` event on failed navigation.

Raise Application.UnhandledException event on failed navigation

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SolutionTemplate/UnoSolutionTemplate/UWP/UnoQuickStart.Uwp.csproj

GitHub Issue (If applicable): Fixes #446.
- Bugfix
Adjust the version of the `Microsoft.NETCore.UniversalWindowsPlatform` nuget package reference to avoid issues caused by versions mismatch when a project reference uses MSBuild Extras.
Also adjusts the msbuild version.

Match the default UniversalWindowsPlatform from MSBuild SDK Extras

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/ListViewBase/NativeListViewBaseAdapter.Android.cs

- Bugfix
Providing `ListViewItem` instances through `ItemsSource` makes the items visualy wrapped inside another `ListViewItem.
`ListViewItem` instances provided by an `ItemsSource` are now reused as-is.
or internal) -->

[Android] Add support for ListViewItem instances provided via the ItemsSource property

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.BindingHelper.Android/Uno/UI/UnoViewGroup.java
src/Uno.UI/Configuration.cs
src/Uno.UI/Controls/BindableNSView.macOS.cs
src/Uno.UI/Controls/BindableUIView.iOS.cs
src/Uno.UI/Controls/BindableView.Android.cs
src/Uno.UI/UI/Xaml/Controls/IShadowChildrenProvider.cs
src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.Android.cs
src/Uno.UI/UI/Xaml/FrameworkElement.Android.cs
src/Uno.UI/UI/Xaml/IFrameworkElementImplementation.Android.tt

- Performance
- Move OnNativeLoaded and OnNativeUnloaded from .tt to android specific FrameworkElement.
- Adjust IChildrenShadowProvider interface to expose List<View> to benefit from allocation less children enumerion
- Add `FeatureConfiguration.FrameworkElement.AndroidUseManagedLoadedUnloaded` to control the native or managed propagation performance of Loaded/Unloaded events through the visual tree.
In the Uno.Gallery application, the main page goes from 293 OnNativeLoaded interop invocations to 34, and the GridView sample from 457 to 83. OnNativeUnloaded calls from GridView sample are down from 247 to 116.
https://nventive.visualstudio.com/DefaultCollection/Umbrella/_workitems/edit/1 …

Improve Android FrameworkElement.Load and Unload propagation performance

---

src/Uno.UI/Helpers/WinUI/SharedHelpers.cs

- Bugfix
The NavigationView may fail when checking for XBox environment.
The NavigationView does not fail when checking for XBox environment.

Disable XBox checking in WinUI's SharedHelper.IsOnXbox

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePicker.cs

- Bugfix
Tap on a TimePicker on an Android device. No TimePicker Flyout is displayed.
By tapping on a TimePicker on an Android device the TimePicker Flyout is correctly displayed.
https://nventive.visualstudio.com/Umbrella/_workitems/edit/143527

Fixed broken TimePicker Flyout on android devices.

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.Wasm/Uno.UI.Wasm.csproj
src/Uno.UI.Wasm/WasmScripts/Uno.UI.d.ts
src/Uno.UI.Wasm/WasmScripts/Uno.UI.js
src/Uno.UI.Wasm/WasmScripts/setImmediate.js
src/Uno.UI.Wasm/ts/CoreDispatcher.ts
src/Uno.UI.Wasm/ts/MonoSupport.ts
src/Uno.UI.Wasm/ts/WindowManager.ts
src/Uno.UI.Wasm/tsBindings/WindowManagerInitParams.ts
src/Uno.UI.WpfHost/UnoHostView.cs
src/Uno.UI/UI/Xaml/Application.wasm.cs
src/Uno.UI/UI/Xaml/UIElement.wasm.cs
src/Uno.UI/UI/Xaml/Window.wasm.cs
src/Uno.UI/UI/Xaml/WindowManagerInterop.Wasm.cs
src/Uno.UWP/UI/Core/CoreDispatcher.wasm.cs

- Bugfix
iOS Applications do not start, caused by a stackoverflow.
iOS applications start, with a 5 second arbitrary delay, see https://github.com/mono/mono/issues/12357 for more details.
The CoreDispatcher implementation is now relying on a specialized typescript class that uses `setImmediate` polyfill, to avoid spending time in the `System.Threading.Timer` scheduler. This will make the UI Thread scheduling faster.
https://nventive.visualstudio.com/DefaultCollection/Umbrella/_workitems/edit/144038

Fix iOS support, improve CoreDispatcher performance

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/FrameworkElementTests/LoadEvents.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/FrameworkElementTests/LoadEvents.xaml.cs
src/Uno.UI.Wasm/WasmScripts/Uno.UI.d.ts
src/Uno.UI.Wasm/WasmScripts/Uno.UI.js
src/Uno.UI.Wasm/ts/WindowManager.ts
src/Uno.UI.Wasm/tsBindings/WindowManagerInitParams.ts
src/Uno.UI/Configuration.cs
src/Uno.UI/UI/Xaml/Application.wasm.cs
src/Uno.UI/UI/Xaml/FrameworkElement.Interface.wasm.cs
src/Uno.UI/UI/Xaml/FrameworkElement.wasm.cs
src/Uno.UI/UI/Xaml/UIElement.wasm.cs
src/Uno.UI/UI/Xaml/UIElementCollection.wasm.cs
src/Uno.UI/UI/Xaml/Window.wasm.cs
src/Uno.UI/UI/Xaml/WindowManagerInterop.Wasm.cs

- Other: Performance improvement on WASM, reduces interop
On WASM `Loading`, `Loaded` and `Unloaded` events are raised by the Javascript then marshaled to the managed code.
They are now raised directly by the managed code
Old behavior can be restored by setting to `false` the feature flag `FeatureConfiguration.FrameworkElement.WasmUseManagedLoadedUnloaded`
https://nventive.visualstudio.com/DefaultCollection/Umbrella/_workitems/edit/144039

Handle the load events from managed code to reduce interop

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SourceGenerators/Uno.UI.Tasks/Content/Uno.UI.Tasks.targets
src/SourceGenerators/Uno.UI.Tasks/Uno.UI.Tasks.csproj

- Bugfix
The Uno.UI.Task file gets locked very often by msbuild or devenv.
This PR attemps to limit the file locking by isolating the task inside of a inline task, and making sure the task is not referenced explicitly.
The Uno.UI.Tasks assembly is now copied properly in case of a nuget override, during development.

Use AppDomain isolation for Uno.UI.Tasks, copy file to override folder.

---

src/SourceGenerators/Uno.UI.Tasks/Content/Uno.UI.Tasks.targets

- Bugfix
The Uno.UI.Tasks msbuild tasks fail to run because of an invalid path.
The tasks now run properly, as the path is now fully qualified.

Adjust Uno.UI.Tasks package path through nuget deployment

---

doc/ReleaseNotes/_ReleaseNotes.md
doc/articles/debugging-uno-ui.md
src/SolutionTemplate/UnoSolutionTemplate/iOS/UnoQuickStart.iOS.csproj
src/Uno.UI/Behaviors/VisibleBoundsPadding.cs

- Bugfix
Adding the VisibleBoundsPadding behavior makes the instance and the underlying tree leak.
`VisibleBoundsPadding` does not leak anymore.

Fix VisibleBoundsPadding memory leak, improve profiling documentation

---

.github/PULL_REQUEST_TEMPLATE.md
doc/ReleaseNotes/_ReleaseNotes.md
doc/articles/debugging-uno-ui.md
doc/articles/working-with-the-samples-apps.md
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/FrameworkElementTests/XamlEvent_Leak.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/FrameworkElementTests/XamlEvent_Leak.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/FrameworkElementTests/XamlEvent_Leak_UserControl.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/FrameworkElementTests/XamlEvent_Leak_UserControl.xaml.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/Uno.UI/UI/Xaml/Controls/CommandBar/CommandBar.cs
src/Uno.UI/UI/Xaml/NameScope.cs

- Bugfix
- When defining an event handler in a XAML document, the control defining the handler, and the control it is being attached to are leaking memory on iOS.
- A XAML element marked with `x:Name` may leak memory
- A `CommandBar` instance may leak memory
- Attaching an event handler in XAML will not create memory leaks.
- `x:Name` elements will not create memory leaks.
- Using the `CommandBar` will not create memory leaks.

Fix multiple memory leaks

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/SourceGenerators/XamlGenerationTests/XamlEvents.xaml
src/SourceGenerators/XamlGenerationTests/XamlEvents.xaml.cs

- Bugfix
This code fails to compile `<Button Click="Button_Click" Loaded="OnLoadUnload" Unloaded="OnLoadUnload" />`
The above code build properly. This regression was introduced by the #497.

Fix invalid code generation for multiple event handlers

---

build/_HOW-TO-BUILD-AND-DEBUG-APPS.md
doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.Shared/SamplesApp.Shared.projitems
src/SamplesApp/SamplesApp.Shared/Strings/en-US/Resources.resw
src/SamplesApp/SamplesApp.Shared/Strings/en/Resources.resw
src/SamplesApp/SamplesApp.Shared/Strings/fr-CA/Resources.resw
src/SamplesApp/SamplesApp.Shared/Strings/fr/Resources.resw
src/SamplesApp/SamplesApp.Shared/Strings/sr-Cyrl-BA/Resources.resw
src/SourceGenerators/Uno.UI.Tasks/ResourcesGenerator/ResourcesGenerationTask.cs
src/Uno.UI.RuntimeTests/Tests/Windows_ApplicationModel_Resources/Given_ResourceLoader.cs
src/Uno.UI.Tests/ResourceLoader/Given_ResourceLoader.cs
src/Uno.UI.Tests/ResourceLoader/Strings/en/Resources.Designer.cs
src/Uno.UI.Tests/ResourceLoader/Strings/en/Resources.resw
src/Uno.UI.Tests/ResourceLoader/Strings/fr/Resources.Designer.cs
src/Uno.UI.Tests/ResourceLoader/Strings/sr-Cyrl-BA/Resources.resw
src/Uno.UWP/ApplicationModel/Resources/Core/ResourceQualifier.cs
src/Uno.UWP/ApplicationModel/Resources/ResourceLoader.cs

- Fix resources generation support for resources localized with region code
- Fix fallback mechanism of the Resource loader
GitHub Issue (If applicable): #493 
- Bugfix
1. If a resource file is added with a region code, the resource generator will either ignore it or place it in an invalid location for the Android localization file structure
2. When a resource is missing for the current UI culture, the `ResourceLoader` will not fallback properly on the `DefaultLanguage` (if the current UI culture is `fr-FR` and the default language is `en-US`, it tries only `fr-FR` and `fr`)
1. File structure is now valid so Android is able to load resources by itself
2. If the current UI culture is `fr-FR` and the default language is `en-US`, `ResourceLoader` …

Fix support of resources localized with region code

---

src/SourceGenerators/Uno.UI.Tasks/ResourcesGenerator/ResourcesGenerationTask.cs

Restore the ability to define resources (out of *.resw) using the simple structure (like "values-fr") when not using region code.
- Bugfix
On Android, if you want to define ressources out of a *.resw file **and** you already have some *.resw files for this language, you have to use the BCP 47 langage tag structure (as defined here https://developer.android.com/guide/topics/resources/providing-resources#AlternativeResources , eg: "values-b+fr")
If the language does not have a region code, you can now use the easier "values-fr"
If your langage have a region code (like "fr-CA", you still have to use the BCP 47 language tag, eg: "values-b+fr+3084" for "fr-CA")
To find your region code, cf. …

Restore the ability to define resources using the simple structure

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UWP/Media/Playback/MediaPlayer.Android.cs

None
Bugfix
Video not properly displayed when video metadata reports a width or height of 0
Video is shown as expected
https://nventive.visualstudio.com/NGL/_workitems/edit/144787

Fix issue when video metadata reports a width or height of 0

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TimePicker/Sample1.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TimePicker/Sample1.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TimePicker/Sample2.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TimePicker/Sample2.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TimePicker/Sample2_Styles.xaml
src/Uno.UI/UI/Xaml/Controls/Flyout/Flyout.cs
src/Uno.UI/UI/Xaml/Controls/TimePicker/Strings/en/Resources.resw
src/Uno.UI/UI/Xaml/Controls/TimePicker/Strings/fr/Resources.resw
src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePicker.md
src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerFlyout.iOS.cs
src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerSelector.iOS.cs
src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml
src/Uno.UI/Uno.UI.csproj

-  133813 [ios] Time picker missing "OK" confirmation button
- Time picker sample in SamplesApp
- TimePicker.md
In iOS, time picker is missing done, cancel buttons and related functionalities
In iOS, time picker now have working done, cancel button with related functionalities
-  Time picker flyout default styles has been changed to include done and cancel buttons 
-  https://nventive.visualstudio.com/Umbrella/_workitems/edit/133813/

fix - Time picker missing "OK" confirmation button

---

src/SourceGenerators/Uno.UI.Tasks/Content/Uno.UI.Tasks.targets

- Bugfix
The Uno.UI.Tasks could not override the DefaultLanguage property as it is being passed as a environment property.
See this for the reason of this workaround:
https://github.com/dotnet/project-system/issues/4494

Fix Uno.UI.Tasks default values cannot be overriden in sub-msbuild

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ComboBox/ComboBox_NoDataContext.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ComboBox/ComboBox_NoDataContext.xaml.cs
src/Uno.UI/UI/Xaml/Controls/Popup/PopupBase.cs

GitHub Issue (If applicable): #528 
ComboBoxes were not working properly when used without a `DataContext`.
Bug fixed.
- ~~[ ] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)~~

Combo Boxes were empty without a datacontext

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.Android.cs

* Item selection is now updated properly by checking  validating selected items when attaching the views to the layout.
Bugfix 
At the moment when the list view has selected items and the selection state is changed when the item/view is detached (Not visible), the item is not updated accordingly and when it comes back into view it remains with the previous selected state. The only way to refresh the selected state is by having the item leave the visible panel (Into it's caching buffer) so that it rebinds itself and updates the selected state.
When a view is being reattached into the Recycler view there is now a check to see if there is any discrepancy between selected items and the state of the attached view. If …

[Android] Listview Selected items update

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/ItemsControl/ItemsControl.cs

Bugfix
When a collection group is added, the group headers are messed up:
- newly added group[n] uses the header of the group[n+1] below
- if group[n+2] is in the view, the above effect will occur on group[n+1] also
The correct group header should be displayed.
[AB#144101](https://nventive.visualstudio.com/Umbrella/_workitems/edit/144101)

fixed ListView group headers messed up on item update

---

src/SamplesApp/SamplesApp.Droid/SamplesApp.Droid.csproj
src/SamplesApp/SamplesApp.Shared/Strings/en/Resources.resw
src/SourceGenerators/Uno.UI.Tasks/Content/Uno.UI.Tasks.targets
src/Uno.UI.RuntimeTests/Tests/Uno_UI_Services/Given_ResourceService.cs

- Bugfix
Native resources are not generated properly for iOS and Android, making `Uno.UI.Services.ResourceService` return empty strings, a regression introduced in https://github.com/nventive/Uno/pull/519
`Uno.UI.Services.ResourceService` works properly.
https://nventive.visualstudio.com/Umbrella/_workitems/edit/145484

Fix generated resources are not injected early enough

---

src/SourceGenerators/System.Xaml/System.Xaml/PrefixLookup.cs
src/SourceGenerators/System.Xaml/System.Xaml/XamlSchemaContext.cs
src/SourceGenerators/System.Xaml/Uno.Xaml.csproj
src/Uno.MonoAnalyzers/MonoNotSupportedAPIAnalyzer.cs

- Bugfix
Adjust Uno.Xaml for invalid string overloads found when building with VS 15.8

Adjust Uno.Xaml for invalid string overloads

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SourceGenerators/System.Xaml/System.Xaml/ParsedMarkupExtensionInfo.cs
src/Uno.Foundation/Uno.Foundation.csproj
src/Uno.MonoAnalyzers/MonoNotSupportedAPIAnalyzer.cs
src/Uno.UI.Tests/Windows_UI_XAML_Controls/ListViewBaseTests/Given_ListViewBase.cs
src/Uno.UI.Toolkit/Uno.UI.Toolkit.csproj
src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.cs
src/Uno.UI/Uno.UI.csproj
src/Uno.UWP/Uno.csproj

GitHub Issue (If applicable): #527 
- Bugfix
When an item is selected in Single selection mode, the `Selector.SelectionChanged` is raised twice.
- The event is now raised only once.
- Fixed NRE when clearing `ListViewBase.ItemsSource`

Fix for Selector.SelectionChanged is raised twice on updated selection

---

.gitignore

Build or CI related changes
The gitignore syntax currently causes the latest versions of LFS to fail.
The gitignore will be compatible with later version of LFS
https://dev.azure.com/nventive/_workitems/edit/146033

Updated gitignore to fix compatibility with LFS

---

src/SourceGenerators/System.Xaml/Uno.Xaml.csproj
src/SourceGenerators/Uno.UI.Tasks/Assets/RetargetAssets.cs

- Bugfix
Recent builds of visual studio seem to have lost the Link metadata, making assets retargeting incorrect.
The assets retargeting target now uses the `DefiningProjectDirectory` metadata to determine the relative path of an asset.

Fix support for assets retargeting

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.Tests/Windows_UI_XAML_Controls/SelectorTests/Given_Selector.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls.Primitives/Selector.cs
src/Uno.UI/UI/Xaml/Controls/Primitives/Selector.cs

- Feature
Adds support for `Selector.SelectedValuePath` and `Selector.SelectedValue`, to be used with `ComboBox`.

Add support for Selector.SelectedValuePath

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.Tests/Windows_UI_Xaml_Data/CollectionViewTests/Given_CollectionView.cs
src/Uno.UI/UI/Xaml/Data/CollectionView.cs

- Feature
`ICollectionView.CopyTo` is now supported in Uno's default implementation.

Add support for ICollectionView.CopyTo

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_OwnContainer_Virtualized.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_OwnContainer_Virtualized.xaml.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelAdapter.wasm.cs

- Bugfix
Manipulating the `NavigationView`'s left pane will fall into an infinite loop, caused by the `ListView` trying to recycle custom `ListView` containers.
Custom `ListView` containers are now ignored by the recycler.

[Wasm] Fixed ListView infinite loop when using custom containers

---

src/Uno.UI/Extensions/ViewHelper.Android.cs
src/Uno.UI/UI/Xaml/Media/Animation/Animators/AnimatorFactory.Android.cs
src/Uno.UI/UI/Xaml/Media/Animation/Animators/NativeValueAnimatorAdapter.Android.cs

Fix animations always using top-left center when using `Forever` repeat mode on Android (and fix invalid rounding).
- Bugfix
- When using the repeat mode `Forever` with `RenderTransform = (.5, .5)`, the animation use the right center only for the first time, then it will use `(0, 0)` as center
- If the animated control has an actual size like `(41.2, 34.8)` the center might be offseted by 1px compared to Windows
- Animations always use the right center
- Center is the same as Windows
https://nventive.visualstudio.com/Umbrella/_workitems/edit/146261
https://nventive.visualstudio.com/Umbrella/_workitems/edit/146326

Fix animations always using top-left center when using `Forever` repeat mode on Android

---

src/SourceGenerators/System.Xaml/System.Xaml/XamlType.cs
src/Uno.MonoAnalyzers/MonoNotSupportedAPIAnalyzer.cs

- Bugfix
Add an exclusion for `string.Contains(char)` for vs15.8 compatibility

Add string.Contains(char) as excluded method for vs15.9

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Markup/Reader/XamlTypeResolver.cs

This enables Wasm compatibility.
- Bugfix
The XamlReader fails to find types under Full AOT runtime
Framework and Uno Types are now explicitly qualified.

[Wasm] Use Uno.UI Assembly for namespace type lookup

---

src/SamplesApp/SamplesApp.Shared/Strings/en/Resources.resw
src/SourceGenerators/Uno.UI.Tasks/ResourcesGenerator/ResourcesGenerationTask.cs
src/Uno.UI.RuntimeTests/Tests/Uno_UI_Services/Given_ResourceService.cs

- Bugfix
The text resources generated from a `.resw` file are being overwritten by the `values/string.xml` from the head project if any defined.
The generated file now have a custom name so it does not conflict with any other file.
This issue might be also present on other resources types, like images. 
https://nventive.visualstudio.com/Umbrella/_workitems/edit/146273
https://nventive.visualstudio.com/Umbrella/_workitems/edit/146286
https://nventive.visualstudio.com/Umbrella/_workitems/edit/146288
https://nventive.visualstudio.com/Umbrella/_workitems/edit/146270
https://nventive.visualstudio.com/Umbrella/_workitems/edit/146592 …

Fix text resources not working on Android with latest Xamarin

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.Wasm/ts/CoreDispatcher.ts

- Feature
An unhandled exception raised in the context of the JS side of the CoreDispatcher don't show stack frames.
The JS debugger console now shows unhandled exceptions stacktraces.

Add a JS error handler for unhandled dispatcher exceptions

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/IFrameworkElementImplementation.iOS.tt

- Bugfix
When an exception happens in the callees of `FrameworkElement.WillMoveToSuperview` the app is terminated.
A fail safe has been added, this will avoid the app to crash, and log to the Application error handler.

Add fail-safe on FrameworkElement.WillMoveToSuperview

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/ObservableVectorWrapper.cs
src/Uno.UWP/UI/Core/CoreDispatcher.cs

- Bugfix
- LLVM AOT may fail for an unknown reason: https://github.com/mono/mono/issues/12987
- Adjust `CoreDispatcher` empty queue processing, there's no need for an exception.

[WASM] Misc stability fixes

---

src/Uno.Foundation/Rect.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media/Given_MatrixTranform.cs
src/Uno.UI.Tests/CustomPanelTests/Given_CustomPanel.cs
src/Uno.UI.Tests/Extensions/Given_Matrix3x2Extensions.cs
src/Uno.UI.Tests/Foundation/Given_Rect.cs
src/Uno.UI.Tests/Uno.UI.Tests.csproj
src/Uno.UI.Tests/Windows_UI_XAML_Controls/GridTests/Given_Grid.cs
src/Uno.UI.Tests/Windows_UI_XAML_Controls/PivotTests/Given_Pivot.cs
src/Uno.UI.Tests/Windows_UI_XAML_Controls/RelativePanelTests/Given_RelativePanel.cs
src/Uno.UI/UI/Xaml/Media/Transform.cs
src/Uno.UWP/Extensions/Matrix3x2Extensions.cs
src/Uno.UWP/Extensions/RectExtensions.cs

- Make sure that `Rect` properly calculate its `Width` and `Height` when created from 2 points
- Includes the 4 edges points when calculating the bounds of a transformed `Rect`
- Bugfix
The `Transform.TransformBounds` does not calculate the right bounds rectangle as soon as the transform includes a rotation without a lower than 1 scaling.
It works

Fix the `Transform.TransformBounds`

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media_Animation/DoubleAnimation_Cumulative.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media_Animation/DoubleAnimation_Cumulative.xaml
src/Uno.UI/UI/Xaml/Media/Animation/Animators/AnimatorFactory.Android.cs
src/Uno.UI/UI/Xaml/Media/Transform.Android.cs
src/Uno.UI/UI/Xaml/Media/Transform.cs

Use the `IsAnimating` flag instead of the DP precedence to determine when update the matrix of a transform. This ensure that the final value published by the animator (which is also published with the animation's precedence) effectively updates the matrix and is then properly applied by the render transform adapter
- Bugfix
When an animation completes, the animated property goes back to its original value until the transform is modified again.
The updated value is properly applied in the UI
https://nventive.visualstudio.com/Umbrella/_workitems/edit/146942 (TBD, not accessible)
https://nventive.visualstudio.com/Umbrella/_workitems/edit/146935 …

Use the `IsAnimating` flag instead of the DP precedence to udpate matrix

---

src/Uno.UI/UI/Xaml/Controls/NavigationView/NavigationView.Members.cs

- Bugfix
GetEnumerator on a null List<T> is causing https://github.com/mono/mono/issues/12998. This issue ensure that there's always an available list.

[Wasm] Fix AOT crash on null enumerator

---

src/Uno.UI/UI/Xaml/FrameworkElement.Layout.wasm.cs
src/Uno.UI/UI/Xaml/Shapes/Rectangle.wasm.cs

- Bugfix
Rectangles are clipped incorrectly.
Inner rectange SVG is now clipped properly since #594, but the rectangle needs a larger clipping area. The clipping property is now applied properly, if there's one.

[Wasm] Fix rectangle clipping regression

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelAdapter.wasm.cs

- Bugfix
The autosuggest box flyout only opens once.
The Wasm `ListView` recycler now is able to reuse items in the context of the `AutoSuggestBox`

[Wasm] Fix ListView recycling when the XamlParent is not available

---

src/Uno.UWP/ContextHelper.cs

`ContextHelper.Current` was throwing an exception when called before it's initialized.
The exception is: `System.InvalidOperationException: ContextHelper.Current not defined. For compatibility with Uno, you should ensure your 'MainActivity' is deriving from Windows.UI.Xaml.ApplicationActivity.`
The exception is replaced by a warning in the log.
- ~~[ ] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)~~
- ~~[ ] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)~~
- ~~[ ] Updated the [Release …

Replace an exception with a warning message

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ScrollViewerTests/Hosted_ScrollViewer.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ScrollViewerTests/Hosted_ScrollViewer.xaml.cs
src/Uno.UI/UI/Xaml/Controls/NavigationView/NavigationView.xaml
src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.cs
src/Uno.UI/UI/Xaml/Style/Generic/FlyoutPresenter.xaml

- Bugfix
Ensure ScrollViewer clears the Content's TemplatedParent before adding it to its ScrollContentPresenter. This ensure that the Content of the ScrollViewer does not add Tempate binding to itself in case it is using the Content property (such as a ContentPresenter).
Also updates `NavigationViewItem` flyout presenter, to add a name to the default style to it can be referenced in the context of #119.
https://nventive.visualstudio.com/Umbrella/_workitems/edit/146075/

Fix potential Scrollviewer add self view in its own children

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ScrollViewerTests/Hosted_ScrollViewer.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ScrollViewerTests/Hosted_ScrollViewer.xaml.cs
src/Uno.UI/UI/Xaml/Controls/NavigationView/NavigationView.xaml
src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.cs
src/Uno.UI/UI/Xaml/Style/Generic/FlyoutPresenter.xaml

Ensure ScrollViewer clears the Content's TemplatedParent before adding it to its ScrollContentPresenter. This ensure that the Content of the ScrollViewer does not add Tempate binding to itself in case it is using the Content property (such as a ContentPresenter)
https://nventive.visualstudio.com/Umbrella/_workitems/edit/146075/

Add to beta : Fix potential add self view in its own children

---

src/Uno.Foundation/FoundationFeatureConfiguration.cs
src/Uno.Foundation/Rect.cs
src/Uno.UI.Tests/Foundation/Given_Rect.cs

- Bugfix
`Rect` constructor will throw if built with a negative width or height ... which unfortunately seems to still be quite common in Uno layouting
It won't throw by default

Add feature flag (enabled by default) to allow negative width and height in Rect

---

doc/ReleaseNotes/_ReleaseNotes.md

Update Release Notes related to the breaking change for the use of "\n" in the XAML text/content properties.
- Other : Update release notes
Missing information in the breaking changes for the release notes
Update Release Notes related to the breaking change for the use of "\n" in the XAML text/content properties.
https://nventive.visualstudio.com/Umbrella/_workitems/edit/147003

Update Release Notes

---

src/Uno.UI.Wasm/ts/WindowManager.ts
src/Uno.UI/UI/Xaml/UIElement.wasm.cs

- Bugfix
The `UIElement.GotFocus` event receives a null `RoutedEventArgs`.
The `UIElement.GotFocus` event now has a proper `RoutedEventArgs` instance.

[Wasm] Fix support for GotFocus routed event

---

src/Uno.UI.Wasm/WasmScripts/Uno.UI.d.ts
src/Uno.UI.Wasm/WasmScripts/Uno.UI.js
src/Uno.UI/UI/Xaml/Controls/NavigationView/NavigationView.cs

- Bugfix
The Settings item in the navigation is not properly reacting to clicks.
The RoutedEvents PR added the Tap event support, the NavigationView is now using it.

Restore original NavigationView Settings events registrations

---

.vsts-ci.yml
doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.Droid/SamplesApp.Droid.csproj
src/SamplesApp/SamplesApp.Wasm/SamplesApp.Wasm.csproj
src/SamplesApp/SamplesApp.iOS/Info.plist
src/SamplesApp/SamplesApp.iOS/SamplesApp.iOS.csproj
src/SamplesApp/SamplesApp.macOS/SamplesApp.macOS.csproj
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MediaPlayerElement/MediaPlayerElement_Full.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MediaPlayerElement/MediaPlayerElement_Full.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MediaPlayerElement/MediaPlayerElement_Minimal.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MediaPlayerElement/MediaPlayerElement_Minimal.xaml.cs
src/Uno.UI/UI/Xaml/Controls/MediaPlayer/MediaTransportControls.MediaPlayer.cs

None
Bugfix
Some missing null check on some MediaTransportControl controls, which affect behavior if control is removed from style
MediaTransportControl controls can now be properly removed from style if unused
None
https://nventive.visualstudio.com/Umbrella/_workitems/edit/147405

Fix NRE on some MediaTransportControl controls + MPE Samples

---

src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media_Animation/DoubleAnimation_BeginTime.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media_Animation/DoubleAnimation_BeginTime.xaml.cs
src/Uno.UWP/UI/Composition/CoreAnimation.iOS.cs

[iOS] Fix transform animations which uses 'BeginTime' will wait the delay without any transform
- Bugfix
On iOS, when animating a `Transform` with a `BeginTime != TimeSpan.Zero` and the target property is not 0 (e.g. `TranslateTransform.Y == 150`), then while waiting for the delay, the current transform is not applied on the view (i.e. the view goes back to its original position like if `TranslateTransform.Y = 0`)
We wait for the first frame of the animation to disable the managed transform (cf. `RenderTransformAdapter.iOS.cs`)
https://nventive.visualstudio.com/Umbrella/_workitems/edit/147309

[iOS] Fix transform animations which uses 'BeginTime'

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SourceGenerators/Uno.UI.SourceGenerators/BindableTypeProviders/BindableTypeProvidersGenerationTask.cs

- Bugfix
A recent type addition makes application ending in `Uno` conflict with existing types.
The `BindableMetadataGenerator` now qualifies property types properly.
https://nventive.visualstudio.com/Umbrella/_workitems/edit/147530

Add a missing global:: qualifier in the BindableMetadataGenerator

---

src/SourceGenerators/System.Xaml/System.Xaml/XamlXmlReader.cs
src/Uno.MonoAnalyzers/MonoNotSupportedAPIAnalyzer.cs

- Bugfix
Used String.TrimStart/TrimEnd overload is incorrect
Analyzer is updated to avoid the use of those methods

Adjust for VS15.8 compatibility

---

src/Uno.UI/UI/Xaml/Controls/SplitView/SplitView.cs
src/Uno.UI/UI/Xaml/Controls/SplitView/SplitView.iOS.cs

- Other: Patch
In some applications it may occurs that the menu stay partially visible when closed
The menu is fully opened / closed
https://nventive.visualstudio.com/Umbrella/_workitems/edit/146335

Patch SplitView opening issue

---

src/Uno.UI.Tests/BinderTests/Given_BindingPath.cs
src/Uno.UI/Controls/Window.iOS.cs
src/Uno.UI/DataBinding/BindingPath.cs
src/Uno.UI/DataBinding/BindingPropertyHelper.cs
src/Uno.UI/UI/Xaml/Media/Animation/DoubleAnimation.cs

- Make sure to set the final value of an animated property, so if a frame is missing at the end (which may happend on iOS) we are sure to complete the animation
- Ensure to reset the value set using the `Animations` precendence, so are able to change it later from code
- Bugfix 
At the end of a `DoubleAnimation` we rely on the fact that the property was altered by the native animation.
Now we ensure to set the **expected** final value, using the `Local` precedence
https://nventive.visualstudio.com/Umbrella/_workitems/edit/147416
https://nventive.visualstudio.com/Umbrella/_workitems/edit/147515

Fix end of animations

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/SymbolIcon/SymbolIcon.cs

- Bugfix
```
6> Fatal error in Mono CIL Linker
6> Mono.Linker.MarkException: Error processing method: 'System.Void Microsoft.Toolkit.Uwp.UI.Controls.__Resources._SlidableListItem_1d281c723c2c9317e7ef2ea0816c3828_SlidableListItemRDSC0/<>c::<Build>b__0_4(Windows.UI.Xaml.Controls.SymbolIcon)' in assembly: 'Microsoft.Toolkit.Uwp.UI.Controls.dll'
---> Mono.Cecil.ResolutionException: Failed to resolve Windows.UI.Xaml.DependencyProperty Windows.UI.Xaml.Controls.SymbolIcon::get_SymbolProperty()
```
The original `SymbolIcon.SymbolProperty` definition is restored as a property, not a field.

Restore original SymbolIcon.SymbolProperty as a C# property

---

doc/ReleaseNotes/_ReleaseNotes.md
doc/articles/MediaPlayerElement.md
src/Uno.Foundation/Collections/ObservableVector.cs
src/Uno.Foundation/Collections/ObservableVectorEnumerableWrapper.cs
src/Uno.Foundation/Collections/ObservableVectorListWrapper.cs
src/Uno.Foundation/Collections/ObservableVectorWrapper.cs
src/Uno.UI/UI/Xaml/Controls/NavigationView/NavigationView.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Media.Playback/MediaPlaybackItem.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Media.Playback/MediaPlaybackList.cs
src/Uno.UWP/Media/Playback/IMediaPlaybackList.cs
src/Uno.UWP/Media/Playback/MediaPlaybackItem.cs
src/Uno.UWP/Media/Playback/MediaPlaybackList.cs
src/Uno.UWP/Media/Playback/MediaPlayer.Android.cs
src/Uno.UWP/Media/Playback/MediaPlayer.iOS.cs

- Feature
The `MediaPlaybackList` is now supported. The queued `MediaPlaybackItem`'s will play seamlessly one after the other.
Internal Issue: https://nventive.visualstudio.com/NGL/_workitems/edit/144487/

Add support for MediaPlaybackList

---

doc/articles/feature-flags.md
src/Uno.UI/Extensions/ViewHelper.Android.cs
src/Uno.UI/UI/Xaml/Extensions/FontHelper.Android.cs

- Bugfix
Setting FeatureConfiguration.Font.IgnoreTextScaleFactor on Android doesn't disable font scaling on some controls like TextBox and AppBarButton.
Setting FeatureConfiguration.Font.IgnoreTextScaleFactor on Android disables font scaling everywhere.
https://nventive.visualstudio.com/Umbrella/_workitems/edit/147422

Disabling font scaling on Android now works properly

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems

Fixed UITests.Shared.projitems in order to fix a merge issue related to TimePicker changes in SamplesApp.
- Other : Merge Issue related to a previous commit
Uno.UI CI build failed
Fix the Uno.UI CI build

Fixed UITests.Shared.projitems in order to fix a merge issue

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.Reflection.cs

- Feature
The Xaml generator can fail with cryptic messages like this one:
```
System.InvalidOperationException: An error occured when processing UserControl at line 1:2 (MyXamlFile.xaml) : Unable to resolve Control (SymbolKind is ErrorType) ---> System.InvalidOperationException: Unable to resolve Control (SymbolKind is ErrorType)
```
The error will now try to tentatively give the details for the `IErrorTypeSymbol` coming from Roslyn, for easier tracking of the problematic source code.

Improve the error logging for error type symbols

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_TransformsOnList.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_TransformsOnList.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ScrollViewerTests/ScrollViewer_Transforms.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ScrollViewerTests/ScrollViewer_Transforms.xaml.cs
src/Uno.UI.BindingHelper.Android/Uno/UI/UnoViewGroup.java
src/Uno.UI/UI/Xaml/Media/Transform.cs

- Bugfix
Touch events are not dispatched to `UIElement` which has a `RenderTransform`
We can also tap on the part of a `UIElement`  which does not overlap it original location
This is only a partial fix, cf. https://github.com/nventive/Uno/issues/649
https://nventive.visualstudio.com/Umbrella/_workitems/edit/147978
https://nventive.visualstudio.com/Umbrella/_workitems/edit/148298
https://nventive.visualstudio.com/Umbrella/_workitems/edit/148300
https://nventive.visualstudio.com/Umbrella/_workitems/edit/148303
https://nventive.visualstudio.com/Umbrella/_workitems/edit/148375
https://nventive.visualstudio.com/Umbrella/_workitems/edit/148521

Fix touch events not dispatched to UIElement that have a RenderTransform

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/LinkerDefinition.Wasm.xml

ListView implementation may fail with this error:
```
"System.ExecutionEngineException: Attempting to JIT compile method 
'Windows.Foundation.Collections.IObservableVector`1<object> Windows.UI.Xaml.ObservableVectorWrapper:Create (object)' while running 
in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information." but maybe just a warning
```
Added a linker exclusion to works around https://github.com/mono/mono/issues/12987

[WASM] Add workaround for mono linker issue in AOT mode

---

src/Uno.UI.BindingHelper.Android/Uno/UI/UnoViewGroup.java

- Bugfix
Z-Order is not respected, so if a control is over another one, it won't get the touch events if the lower control can handle them (eg. ScrollViewer)
It works
https://nventive.visualstudio.com/Umbrella/_workitems/edit/148375

Make sure to respect Z-Order for touch events

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.Wasm/ts/WindowManager.ts

- Bugfix
- Fixes an issue where items measured after being removed from their parent appear in the visual tree, on top of every other items.
- Fixes an issue where elements may not be removed form the global active DOM elements tracking map

[Wasm] Fix unarranged measuring, destroy items leak

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SolutionTemplate/UnoSolutionTemplate/Droid/Properties/AssemblyInfo.cs
src/SolutionTemplate/UnoSolutionTemplate/Droid/UnoQuickStart.Droid.csproj
src/SolutionTemplate/UnoSolutionTemplate/Shared/App.xaml.cs
src/SolutionTemplate/UnoSolutionTemplate/UWP/Package.appxmanifest
src/SolutionTemplate/UnoSolutionTemplate/UWP/Properties/AssemblyInfo.cs
src/SolutionTemplate/UnoSolutionTemplate/UWP/UnoQuickStart.Uwp.csproj
src/SolutionTemplate/UnoSolutionTemplate/UnoSolutionTemplate.csproj
src/SolutionTemplate/UnoSolutionTemplate/Wasm/UnoQuickStart.Wasm.csproj
src/SolutionTemplate/UnoSolutionTemplate/iOS/Info.plist
src/SolutionTemplate/UnoSolutionTemplate/iOS/Properties/AssemblyInfo.cs
src/SolutionTemplate/UnoSolutionTemplate/iOS/UnoQuickStart.iOS.csproj
src/SolutionTemplate/UnoSolutionTemplate/iOS/iOS.vstemplate

GitHub Issue (If applicable): fixes #668 
- Bugfix 
- Feature
- Added default console logging for all platforms
- Fixed invalid iOS assets folder. `ImageAsset` nodes must not be `<Visible>false</Visible>` to be copied to the generated project.
https://nventive.visualstudio.com/Umbrella/_workitems/edit/149207

VSIX updates for logging and iOS Assets

---

src/Uno.UI/UI/Xaml/FrameworkElement.Layout.wasm.cs
src/Uno.UI/UI/Xaml/UIElement.wasm.cs

- Bugfix
This changes forces an arrange pass to ensure the uno-unarranged CSS class is removed, so the element is displayed properly.

[Wasm] Fixed popups only appear once

---

src/Uno.UI/UI/Xaml/Media/Animation/DoubleAnimation.cs

Animation were missing in app.
The previous change were applied on both Android and iOS,
but only iOS was concerned with the original bug.
The fix has been rolled back for Android.
- ~~[ ] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)~~
* 148357 <https://nventive.visualstudio.com/Umbrella/_workitems/edit/148357> Android - Looping animation is missing in app.

Rollback animation ending changes

---

src/Uno.UI/UI/Xaml/UIElement.RoutedEvents.cs

- Bugfix
The runtime crashes when using Uno from a nuget package:
```
* Assertion at /mnt/jenkins/workspace/test-mono-mainline-wasm/label/ubuntu-1804-amd64/mono/mini/interp/transform.c:2856, condition `<disabled>' not met
```
Fixes #614 by adding a workaround for https://github.com/mono/mono/issues/12981

Add workaround for Mono issue #12981

---

src/Directory.Build.targets
src/SamplesApp/SamplesApp.Wasm/SamplesApp.Wasm.csproj
src/Uno.UI.Wasm.Tests/Uno.UI.Wasm.Tests.csproj
src/Uno.UI.Wasm/Uno.UI.Wasm.csproj
src/Uno.UI.Wasm/WasmScripts/Uno.UI.d.ts
src/Uno.UI.Wasm/WasmScripts/Uno.UI.js
src/Uno.UI.Wasm/ts/CoreDispatcher.ts
src/Uno.UI.Wasm/ts/WindowManager.ts
src/Uno.UI.Wasm/tsconfig.json

- Bugfix
The Uno.UI splash screen image is not appearing, it's only using the AppManifest background color.
The SplashScreen image is eagerly materialized to it appears even if the dispatcher loop is busy.

Fix SplashScreen image loading

---

doc/articles/working-with-animations.md
src/Uno.UI/UI/Xaml/Media/Animation/Animators/RenderingLoopFloatAnimator.wasm.cs
src/Uno.UI/UI/Xaml/Media/Animation/DoubleAnimationUsingKeyFrames.cs
src/Uno.UI/UI/Xaml/Media/Animation/DoubleAnimationUsingKeyFrames.wasm.cs

* Enabled `DoubleAnimationUsingKeyFrames`
* Fix support of `BeginTime`
- Bugfix
- Feature
* `DoubleAnimationUsingKeyFrames` does nothing
* An animation with a `BeginTime` will remove this delay from the `Duration` when starting the animation. So if `Duration < BeginTime`, the animation will reach its final state immediately at the end of the wait delay (a.k.a. `BeginTime`).
* `DoubleAnimationUsingKeyFrames` are now supported on WASM
* Animation will wait for the 'BeginTime` and then animate properly using the right `Duration`.

Enhance animation for WASM

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/Uno.UI.Tests/BinderTests/Given_Binder.cs
src/Uno.UI.Tests/Uno.UI.Tests.csproj
src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Given_StaticResource.cs
src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Given_StaticResource_Control.xaml
src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Given_StaticResource_Control.xaml.cs
src/Uno.UI/DataBinding/BindingExpression.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml/FrameworkElement.cs
src/Uno.UI/UI/Xaml/FrameworkElement.Interface.net.cs
src/Uno.UI/UI/Xaml/FrameworkElement.net.cs

- Feature
It is now possible to use the following construct:
```xaml
<Page.Resources>
<CollectionViewSource x:Name="mySource" Source="{x:Bind MyProperty}" />
</Page.Resources>
<ListView ItemsSource="{StaticResource mySource}" />
```

Support for x:Bind and x:Name late binding in Resources

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.Wasm/WasmScripts/Uno.UI.js
src/Uno.UI.Wasm/ts/WindowManager.ts
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs

- Feature
Touch and key events are not handled as windows does
* `PointerRelease` events are now marked as handled by the `TextBox`
* `KeyDown` events that are changing the cursor position (left/right/top/bottom/home/end) are now marked as handled by the `TextBox`
https://nventive.visualstudio.com/Umbrella/_workitems/edit/149028

Align TextBox events handling behavior with Windows

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Automation.Peers/AutomationPeer.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Input/PointerRoutedEventArgs.cs
src/Uno.UI/UI/Xaml/Automation/Peers/AutomationPeer.cs
src/Uno.UI/UI/Xaml/Input/PointerRoutedEventArgs.cs
src/Uno.UI/UI/Xaml/UIElement.wasm.cs

- Bugfix
- Feature
* `RoutedEventArgs.IsGenerated` throws `NotImplementedException`
* `AutomationPeer.ListenerExists` throws `NotImplementedException`
* `KeyUp` event throws `InvalidCastException`
* `RoutedEventArgs.IsGenerated` returns `false` as we cannot generate events with Uno
* `AutomationPeer.ListenerExists` returns `false` as we cannot generate events with Uno
* `KeyUp` event properly sends `KeyEventArgs` to the controls
https://nventive.visualstudio.com/Umbrella/_workitems/edit/149028

Misc fixes for events support

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.Tests/Windows_UI_XAML_Controls/ItemsControlTests/Given_ItemsControl.cs
src/Uno.UI.Tests/Windows_UI_Xaml_Data/CollectionViewTests/Given_CollectionView.cs
src/Uno.UI.Tests/Windows_UI_Xaml_Data/CollectionViewTests/Given_CollectionViewSource.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Data/CollectionViewSource.cs
src/Uno.UI/UI/Xaml/Controls/ItemsControl/ItemsControl.cs
src/Uno.UI/UI/Xaml/Data/CollectionView.cs
src/Uno.UI/UI/Xaml/Data/CollectionViewGroup.cs
src/Uno.UI/UI/Xaml/Data/CollectionViewSource.cs

- Bugfix
- Feature
Using a `CollectionViewSource` in ItemsControl does not work properly.
- Using `CollectionViewSource` directly now works properly, and updating the source property updates observer properly.
- Added support for the `CollectionViewSource.ItemsPath` property

CollectionViewSource updates

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/SourceGenerators/XamlGenerationTests/GlobalStaticResources02.xaml

- Bugfix
Fixed support for dots in resource names (#700)

Fixed support for dots in resource names

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.Tests/BinderTests/Given_Binder.cs
src/Uno.UI/DataBinding/BindingExpression.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Data/BindingExpression.cs

- Feature
NotImplemented
The `BindingExpression.UpdateSource` is implemented
https://nventive.visualstudio.com/Umbrella/_workitems/edit/149028

Add support for `BindingExpression.UpdateSource()`

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/Pivot/Pivot.cs

- Bugfix
You **can't** use the native default style of Pivot for both Android and iOS.
You **can** use the native default style of Pivot for both Android and iOS.
https://nventive.visualstudio.com/Umbrella/_workitems/edit/149965

Fix nullref in Pivot when using native default style

---

build/Uno.UI.Lottie.nuspec
build/Uno.UI.nuspec
doc/ReleaseNotes/_ReleaseNotes.md
src/AddIns/Uno.UI.Lottie/Uno.UI.Lottie.csproj
src/Directory.Build.targets
src/SamplesApp/SamplesApp.Droid/SamplesApp.Droid.csproj
src/SolutionTemplate/UnoLibraryTemplate/CrossTargetedLibrary.csproj
src/SolutionTemplate/UnoSolutionTemplate/Droid/UnoQuickStart.Droid.csproj
src/SourceGenerators/System.Xaml/Uno.Xaml.csproj
src/SourceGenerators/Uno.UI.SourceGenerators/DependencyObject/DependencyObjectGenerator.cs
src/SourceGenerators/XamlGenerationTests.Core/XamlGenerationTests.Core.csproj
src/SourceGenerators/XamlGenerationTests/XamlGenerationTests.csproj
src/TargetFrameworkSelection.targets
src/Uno.Foundation/Uno.Foundation.csproj
src/Uno.UI.BindingHelper.Android/Uno.UI.BindingHelper.Android.csproj
src/Uno.UI.Maps/Uno.UI.Maps.csproj
src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.csproj
src/Uno.UI.Toolkit/Uno.UI.Toolkit.csproj
src/Uno.UI/BaseFragment.Android.cs
src/Uno.UI/Controls/BindableFragment.Android.cs
src/Uno.UI/Extensions/FragmentManagerExtensions.Android.cs
src/Uno.UI/IFragmentTracker.Android.cs
src/Uno.UI/Uno.UI.csproj
src/Uno.UWP/Uno.csproj
src/Uno.UWPSyncGenerator/Generator.cs

Upgraded the Android target from Android 8.0 to Android 9.0. As a first step before also updating support librairies
Uno Targets Android 8.0
Uno Targets both Android 8.0 and Android 9.0 using CI Pipelines
Uno Targets Android 9.0 when building locally
You will not be able to debug projects targeting Android 8.0 locally anymore. Change your Android target to Android 9.0 or replace MonoAndroid90 by MonoAndroid80 in the TargetFrameworks of your uno projects files.
Internal Issue :
132095 - [Target MonoAndroid90](https://nventive.visualstudio.com/Umbrella/_workitems/edit/132095)

Adds support for Android 9

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Popup/Popup_Simple.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Popup/Popup_Simple.xaml.cs
src/Uno.UI/Media/GeometryConverter.cs
src/Uno.UI/Media/Parsers.cs
src/Uno.UI/UI/Xaml/Media/Geometry.cs

The PR #698 introduced a bug on Wasm where "Data Path" were not properly translated to `DataGeometry` (a type used to hold a path data instead on parsing it).
The parsing of the _Data Path_ was not working properly on Wasm.
Old behavior has been restored, but only on Wasm.
- ~~[ ] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)~~
- ~~[ ] Updated the [Release Notes](https://github.com/nventive/Uno/tree/master/doc/ReleaseNotes)~~
- ~~[ ] Associated with an issue (GitHub or internal)~~

Paths were broken in Wasm

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/ComboBox/ComboBox.cs

- Bugfix
Using Popover in a ComboBox style doesn't work.
Using Popover in a ComboBox style works.
https://nventive.visualstudio.com/Umbrella/_workitems/edit/150156

Fix ComboBox not working when using Popover on iOS.

---

.vsts-ci.yml
build/PackageDiffIgnore.xml
build/Uno.UI.proj
doc/ReleaseNotes/_ReleaseNotes.md
doc/articles/debugging-uno-ui.md
src/Uno.Foundation/Collections/ObservableVector.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/TimePicker.cs
src/Uno.UWP/Media/Playback/MediaPlaybackItem.cs
src/Uno.UWP/Media/Playback/MediaPlaybackList.cs

- Feature
API breaking changes are not visible, ending breaking tooling such as the IL Linker.
A [new check is added in the CI](https://github.com/nventive/Uno.PackageDiff) that validates the presence of API breaking changes. 

Add breaking changes validation

---

.vsts-ci.yml

GitHub Issue (If applicable): Fixes #712 
Remove workaround for https://developercommunity.visualstudio.com/content/problem/284991/public-vsts-previouw-cant-set-build-number-of-pr-b.html

Restore git version for PRs from forks

---

build/uno.ui.targets
doc/ReleaseNotes/_ReleaseNotes.md

- Bugfix
Including the Uno.UI package adds the `HAS_UNO` define in `uap10.0.x` targets.
The `HAS_UNO` is only available for netstandard 2.0, Xamarin mac/iOS/Android.

Don't set HAS_UNO for uap10.0.x

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/MediaPlayer/MediaTransportControls.MediaPlayer.cs
src/Uno.UI/UI/Xaml/Controls/MediaPlayer/MediaTransportControls.cs

MediaElement Buttons are not working.
MediaElement buttons trigger the right action when tapped
Internal Issue 
[https://nventive.visualstudio.com/Umbrella/_workitems/edit/150083](https://nventive.visualstudio.com/Umbrella/_workitems/edit/150083)

Fixed MediaElementButtons not working properly on iOS

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_IsReadOnly.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_IsReadOnly.xaml.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.Android.cs

Bugfix
If a TextBox has IsReadOnly = true, setting IsReadOnly = false will not restore the cursor. This makes it impossible to remove or add text in a different position.
Setting TextBox.IsReadOnly = false restores the cursor.
150143

Fix TextBox.IsReadOnly on Android

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/UIElement.cs
src/Uno.UI/UI/Xaml/UIElement.iOS.cs

On iOS, when manipulating a slider, the pointer is not properly captured, resulting in unpredictable behavior when releasing your finger outside of the slider bounds.
The pointer is properly captured and you can keep manipulating it as long as you don't release your finger.
Internal Issue :
[https://nventive.visualstudio.com/Umbrella/_workitems/edit/150453](https://nventive.visualstudio.com/Umbrella/_workitems/edit/150453)

Set IsPointerCaptured flag on iOS accordingly to the Pointer capture state

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.Shared/Samples/UnitTests/HttpUnitTests.xaml
src/SamplesApp/SamplesApp.Shared/Samples/UnitTests/HttpUnitTests.xaml.cs
src/SamplesApp/SamplesApp.Shared/Samples/UnitTests/UnitTestsPage.xaml.cs
src/SamplesApp/SamplesApp.Shared/SamplesApp.Shared.projitems
src/Uno.UI.Wasm/WasmHttpHandler.cs

This was due to access to an internal method through reflection. A better pattern has been implemented.
Recent changes in Mono were causing null reference for a method got
using reflection.
Reflection is no more used to assign headers from _native_ (browser) http response.

Fixed potential null-ref in custom http handler.

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePicker.cs
src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePickerFlyout.iOS.cs
src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePicker.cs
src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerFlyout.iOS.cs

- Bugfix
- Feature
Loading a page containing multiple `DatePicker` or `TimePicker` controls is very slow.
Loading a page containing multiple `DatePicker` or `TimePicker` controls is not slow.
`UIDatePicker` is the slow native control used under the hood. We now wait until we open the DatePickerFlyout/TimePickerFlyout before initializing it.
https://nventive.visualstudio.com/Umbrella/_workitems/edit/149377

Improve performance of DatePicker and TimePicker on iOS

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ToggleSwitchControl/Models/ToggleSwitchViewModel.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ToggleSwitchControl/Native_ToggleSwitch.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ToggleSwitchControl/Native_ToggleSwitch.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ToggleSwitchControl/ToggleSwitchUnloadReload.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ToggleSwitchControl/ToggleSwitchUnloadReload.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ToggleSwitchControl/ToggleSwitch_Custom.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ToggleSwitchControl/ToggleSwitch_Custom.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ToggleSwitchControl/ToggleSwitch_Default_Style.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ToggleSwitchControl/ToggleSwitch_Default_Style.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ToggleSwitchControl/ToggleSwitch_IsOn.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ToggleSwitchControl/ToggleSwitch_IsOn.xaml.cs
src/Uno.UI.Tests/RoutedEventTests/Given_TappedRoutedEvent.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/ToggleSwitch.cs
src/Uno.UI/UI/Xaml/Controls/ToggleSwitch.cs
src/Uno.UI/UI/Xaml/UIElement.RoutedEvents.cs

Unregistrering a routed event handler wasn't doing anything.
It works now.
Internal Issues:
* https://nventive.visualstudio.com/Umbrella/_workitems/edit/150172

Fix RoutedEvent handler unregistration

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.BindingHelper.Android/Uno/UI/UnoViewGroup.java

Use StaticTransformation special case even for ACTION_CANCEL, because ViewGroup's touch logic needs to handle the gesture from the very beginning of the touch or not at all.
Bugfix
https://nventive.visualstudio.com/Umbrella/_workitems/edit/150489

[Android] Fix PointerCanceled not called for views with a RenderTransform

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/Extensions/ViewHelper.Android.cs

Ensure this is converted correctly to physical pixels (eg when calling ScrollViewer.ChangeView(double.MaxValue,...)
Bugfix
https://nventive.visualstudio.com/Umbrella/_workitems/edit/145203

[Android] Fix overflow when using double.MaxValue

---

src/Uno.UI.Tests/Windows_UI_XAML_Controls/GridTests/Given_Grid.cs
src/Uno.UI/UI/Xaml/Controls/Grid/Grid.Layout.cs

Use SliceClamped (as elsewhere in Grid layouting), fixes bug when a Grid child has a RowSpan that would exceed # of rows.
Bugfix
https://nventive.visualstudio.com/Umbrella/_workitems/edit/150798
https://nventive.visualstudio.com/Umbrella/_workitems/edit/150799

Grid - fix ArgOOREx from Span

---

doc/ReleaseNotes/_ReleaseNotes.md
doc/articles/toc.yml
doc/articles/wasm-custom-events.md
src/AddIns/Uno.UI.Lottie/LottieVisualSource.wasm.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Wasm/Wasm_CustomEvent.xaml
src/SamplesApp/UITests.Shared/Wasm/Wasm_CustomEvent.xaml.cs
src/Uno.UI.Wasm/WasmScripts/Uno.UI.d.ts
src/Uno.UI.Wasm/WasmScripts/Uno.UI.js
src/Uno.UI.Wasm/ts/WindowManager.ts
src/Uno.UI/UI/Xaml/HtmlCustomEventArgs.cs
src/Uno.UI/UI/Xaml/UIElement.wasm.cs
src/Uno.UI/UI/Xaml/UIElementExtensions.Wasm.cs
src/Uno.UI/Uno.UI.csproj

You can now add event listener for HTML's `CustomEvent` and get a string payload.

WASM: Added support for DOM's CustomEvents

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/SourceGenerators/XamlGenerationTests/ResourceKeyTest.xaml

- Bugfix
Using `<StaticResource ResourceKey="" />` results in a compilation error.

Adjust support for StaticResource.ResourceKey

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.Android.cs

On Android, the virtual Keyboard does not always disappear when we unfocus a TextBox while the view changes simultaneously.
The Keyboard is always dismissed 
Internal Issue :
[https://nventive.visualstudio.com/Umbrella/_workitems/edit/151081](https://nventive.visualstudio.com/Umbrella/_workitems/edit/151081)

Dismiss android virtual keyboard when a textbox is losing focus

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/Media/NativeRenderTransformAdapter.Android.cs
src/Uno.UI/Media/NativeRenderTransformAdapter.cs
src/Uno.UI/Media/NativeRenderTransformAdapter.iOSmacOS.cs
src/Uno.UI/Media/NativeRenderTransformAdapter.wasm.cs

When view.Layer.AnchorPoint is set on initializing a transform, reapply the Frame to correct for the offset potentially introduced. This fixes a spurious visual offset when a RenderTransform is set after a view is already visible.
Bugfix 
https://nventive.visualstudio.com/Umbrella/_workitems/edit/150882

[iOS] Fix incorrect offset when setting RenderTransform

---

doc/ReleaseNotes/_ReleaseNotes.md
doc/articles/using-uno-ui.md
src/Uno.UI/UI/Xaml/Style/Generic/Generic.Native.xaml
src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml

- Feature
No default `NativeXXX` style on wasm
`NativeXXX` styles aliases over their corresponding `XamlXXX` styles.
- [] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
https://nventive.visualstudio.com/_workitems/edit/151526

Add pseudo Native styles for WASM

---

build/PackageDiffIgnore.xml
src/Uno.Foundation/Runtime.wasm.cs

- Feature
All JavaScript method must return a string
Method can now don't have any return type (a.k.a. void)

Allow to invoke JS methods which has no return value

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UWP/Media/Playback/MediaPlayer.iOS.cs

- Bugfix
Add ability to replay an ios video by reintializing the source
Video that ended can't be replayed
A video can be replayed when ended
https://nventive.visualstudio.com/Umbrella/_workitems/edit/151674

[iOS] Add ability to replay a finished video from media player

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/SourceGenerators/XamlGenerationTests/VSM.Test.xaml
src/SourceGenerators/XamlGenerationTests/XamlGenerationTests.csproj
src/SourceGenerators/XamlGenerationTests/xNameResources.xaml

- Bugfix
Using `x:Name` on a style results in invalid generated code.
The generated code is now valid.

Fix invalid code generation for `x:Name` entries on `Style` in resources

---

doc/ReleaseNotes/_ReleaseNotes.md
doc/articles/using-uno-ui.md
src/Uno.UI/Controls/Window.iOS.cs

Bugfix
On iOS, the keyboard closes even if we set NeedsKeyboard to true on the current view.
The keyboard stays open when we set that it's needed.
Internal Issue (If applicable): https://nventive.visualstudio.com/Umbrella/_workitems/edit/151676

[iOS] Browse Superviews for NeedsKeyboard

---

src/Uno.UI/Extensions/NSDateExtensions.iOS.cs
src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePicker.cs
src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePickerSelector.iOS.cs
src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePicker.cs
src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerFlyout.iOS.cs
src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerSelector.iOS.cs

- Bugfix
When you open a TimePicker flyout on a binded value, it displays the default value instead of the binded one
Open a TimePicker flyout shows the binded value
https://nventive.visualstudio.com/Umbrella/_workitems/edit/151655
https://nventive.visualstudio.com/Umbrella/_workitems/edit/151656
https://nventive.visualstudio.com/Umbrella/_workitems/edit/151657

[BETA][iOS][DatePicker / TimePicker] Fix multiple issues on flyout and selection

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/Extensions/NSDateExtensions.iOS.cs
src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePicker.cs
src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePickerSelector.iOS.cs
src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePicker.cs
src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerFlyout.iOS.cs
src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerSelector.iOS.cs

- Bugfix
When you open a TimePicker flyout on a binded value, it displays the default value instead of the binded one
Open a TimePicker flyout shows the binded value
https://nventive.visualstudio.com/Umbrella/_workitems/edit/151655
https://nventive.visualstudio.com/Umbrella/_workitems/edit/151656
https://nventive.visualstudio.com/Umbrella/_workitems/edit/151657

[iOS][DatePicker / TimePicker] Fix multiple issues on flyout and selection

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.Tests/Windows_UI_XAML_Controls/GridTests/Given_Grid.cs
src/Uno.UI/UI/Xaml/Controls/Grid/Grid.Layout.cs

- Bugfix
Overflow in `Grid.Row`/`Column` and `Grid.RowSpan` may fail in the `Grid` layouter.
https://nventive.visualstudio.com/Umbrella/_workitems/edit/151919

Fixed Span.Slice overflow errors in Grid layouting

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ComboBox/ComboBox_ScrollViewer.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ComboBox/ComboBox_SelectedIndex.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ComboBox/ComboBox_SelectedIndex.xaml.cs
src/Uno.UI.Tests/Windows_UI_XAML_Controls/SelectorTests/Given_Selector.cs
src/Uno.UI/UI/Xaml/Controls/Primitives/Selector.cs

GitHub Issue (If applicable): #803
Setting the `.SelectedValue` on a `Selector` wasn't doing anything.
Same behavior as UWP: the index will be updated.
- ~~ Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)~~
* <https://nventive.visualstudio.com/Umbrella/_workitems/edit/151779>

Selector .SelectedIndex & .SelectedValue

---

.github/ISSUE_TEMPLATE.md

Maintenance
Added `VS 2019` in the options, removed `VS 2017 Preview`.

Update issue template to add "VS2019"

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/ItemsControl/ItemsControl.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.wasm.cs

Fixes bug where list doesn't appear when dimensions are not stretch and ItemsSource goes from empty => non-empty.

[WASM] Remeasure panel when ListView.ItemsSource changes

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Flyout/Flyout_ButtonInContent.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Flyout/Flyout_ButtonInContent.xaml.cs
src/Uno.UI/UI/Xaml/Controls/Flyout/FlyoutPresenter.cs
src/Uno.UI/UI/Xaml/Controls/Popup/Popup.wasm.cs
src/Uno.UI/UI/Xaml/Controls/Primitives/ButtonBase/ButtonBase.cs

A flyout will dismiss too fast.
The routed event "pointer pressed" will close the flyout popup before
any content can process it.
The flyout now requires a full _pressed_ + _released_ sequence
(non-handled events) before closing.
* https://nventive.visualstudio.com/Umbrella/_workitems/edit/152477

WASM: flyout is dismissing too fast

---

build/Uno.UI.nuspec
doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.Droid/Properties/AndroidManifest.xml
src/SourceGenerators/XamlGenerationTests.Core/XamlGenerationTests.Core.csproj
src/SourceGenerators/XamlGenerationTests/XamlGenerationTests.csproj
src/Uno.UI.BindingHelper.Android/Uno.UI.BindingHelper.Android.csproj
src/Uno.UI.Maps/Uno.UI.Maps.csproj
src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.csproj
src/Uno.UI.Toolkit/Uno.UI.Toolkit.csproj
src/Uno.UI/Uno.UI.csproj
src/Uno.UWP/Uno.csproj

Compiling for Android 9 uses support libraries for API 26 (26.1.0.1)
Compiling for Android 9 uses support libraries for API 28 (28.0.0.1)
[132095](https://nventive.visualstudio.com/Umbrella/_workitems/edit/132095)

Update the support libraries for Android 9

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/Controls/CommandBarRenderer.Android.cs

GitHub Issue (If applicable): #N/A
Bugfix
Currently on android, the keyboard stays open when the user clicks on any `CommandBar` item
`CommandBar` item on-click handler will attempt to clear focus from the current focused view, in turn causing the keyboard to be closed.
https://nventive.visualstudio.com/Umbrella/_workitems/edit/145374

fixed android keyboard stays open on AppBarButton click

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/ForcedTextWithCarriageReturn_MaxLines_One.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/ForcedTextWithCarriageReturn_MaxLines_One.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/ForcedTextWithCarriageReturn_MaxLines_Two.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/ForcedTextWithCarriageReturn_MaxLines_Two.xaml.cs
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.iOS.cs

Bugfix 
iOS Carriage returns would not take the MaxLines Textblock property into consideration
Fixed: Carriage Returns follow MaxLines Property
https://nventive.visualstudio.com/Umbrella/_workitems/edit/148896
UserEcho
https://feedback.nventive.com/communities/1/topics/3424-ios-textblockmaxlines-doesnt-work-with-carriage-returns

iOS CarriageReturns follow MaxLines Textblock Property

---

.dependabot/config.yml

Humans need to manually track security updates or new releases of dependencies that Uno depends upon.
This pull-request wires up the configuration `.dependabot/config.yml` and activates the https://dependabot.com robot. The behaviour is documented at https://dependabot.com/docs/config-file/ and there is a config validator at https://dependabot.com/docs/config-file/validator/
The configuration shipped in this pull-request will subscribe to the nuget.org package feed and when updates are pushed there will automatically raise PRs on this repository. These PR's will, of course, trigger CI and then humans can decide if we do or do not want to bump the dependency. Instructions on how to use the bot are included in the …

configure dependabot to automatically bump dependencies

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/Services/AndroidResourceNameEncoder.cs

GitHub Issue : [#902](https://github.com/nventive/Uno/issues/902)
If a resw resource key starts by a number or contains a dash, the build fails because those are used as is in the generated Resource file for Android and are invalid in C#.
Those characters are "escaped" in the intermediate file generated by Uno.

Add invalid caracters checks and replacements in resources generation

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml

- Feature
`Overlay` mode of `SPlitView` (`NavigationView`) is not possible using default styles
It's possible
Internal Issue (If applicable): https://nventive.visualstudio.com/_workitems/edit/154530

Enable Overlay mode of SplitView on WASM as it's now supported

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.Tests/Windows_UI_Xaml/Given_AdaptiveTrigger.cs
src/Uno.UI.Tests/Windows_UI_Xaml/VisualStateManagerTests/Given_VisualStateManager.cs
src/Uno.UI/UI/Xaml/AdaptiveTrigger.cs
src/Uno.UI/UI/Xaml/StateTriggerBase.cs
src/Uno.UI/UI/Xaml/StateTriggerPrecedence.cs
src/Uno.UI/UI/Xaml/VisualState.cs
src/Uno.UI/UI/Xaml/VisualStateGroup.cs

_State Triggers_ used in a `VisualStateManager` will now follow the precedenced as
documented by Microsoft.
The following precedence is now applied:
<https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.visualstategroup#remarks>
> When using StateTriggers to control visual states, the trigger engine uses the following precedence
> rules to score triggers and determine which trigger, and the corresponding VisualState, will be active:
>
> 1. Custom trigger that derives from StateTriggerBase
> 2. AdaptiveTrigger activated due to MinWindowWidth
> 3. AdaptiveTrigger activated due to MinWindowHeight
>
> If there are multiple active triggers at a time that have a conflict in scoring (i.e. two active custom
> triggers), then the first one declared in the markup file takes precedence.
Please …

 Implement StateTrigger precedence as documented by Microsoft

---

.dependabot/config.yml

GitHub Issue (If applicable): #912 
See https://github.com/nventive/Uno/issues/912
Dependabot will now automatically add the label `do-not-merge/work-in-progress`

do not merge dependabot PR's until issue #912 is resolved

---

src/Common/GlobalAssemblyInfo.cs

2009-2018
2009-2019
MSDN - https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assemblycopyrightattribute?redirectedfrom=MSDN&view=netframework-4.8

bumped copyright date from 2018 to 2019

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_System/Display/DisplayRequest.xaml
src/SamplesApp/UITests.Shared/Windows_System/Display/DisplayRequest.xaml.cs
src/SamplesApp/UITests.Shared/Windows_System/Power/PowerManager.xaml
src/SamplesApp/UITests.Shared/Windows_System/Power/PowerManager.xaml.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.System.Display/DisplayRequest.cs
src/Uno.UWP/System/Display/DisplayRequest.Android.cs
src/Uno.UWP/System/Display/DisplayRequest.cs
src/Uno.UWP/System/Display/DisplayRequest.iOS.cs

GitHub Issue (If applicable): #907 
- Feature -->
`Windows.System.Display.DisplayRequest` is not implemented
`Windows.System.Display.DisplayRequest` is implemented on iOS and Android. Its behavior matches UWP and it allows creating multiple instances as well as throws when release is attempted when there is no active request.

Windows.System.Display.DisplayRequest

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/ListViewBase/BufferViewCache.Android.cs

Fixes crash/corrupt views when using explicitly defined ListViewItems.
#881 

[Android] ListView - don't reuse non-generated container

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/UIElement.wasm.cs
src/Uno.UI/UI/Xaml/UIElementCollection.wasm.cs
src/Uno.UWP/Collections/MaterializableList.cs

Avoid producing "Collection was modified" when the UI is modified during the "loaded" event.
This was mostly caused by the x:Load option.
Using `x:Load` was causing this kind of problems on Wasm.
A new `MaterializableList` collection has been create to cache the
materialized version of the list. And this materialized version is used
for enumeration.
This way, the annoying exception _Collection was modified_ won't
be pushed again.

Avoid producing "Collection was modified"

---

src/Uno.UI.Tests/Windows_UI_Xaml/Given_AdaptiveTrigger.cs
src/Uno.UI/UI/Xaml/AdaptiveTrigger.cs

- Bugfix
As soon as width constraint is set and passed on a visual state trigger, the sate is flagged as active no matter the height constraint
The trigger is activated only if both constraints are met
https://nventive.visualstudio.com/_workitems/edit/154711

Fix VisualStateTrigger ignoring height constraints if width constraint passed

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.Shared/App.xaml.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/TextBlock_MeasurePeformance.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/TextBlock_MeasurePeformance.xaml.cs
src/Uno.UI.Tests/Windows_UI_Xaml_Controls/TextBlockTests/Given_TextBlockMeasureCache.cs
src/Uno.UI/FeatureConfiguration.cs
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.wasm.cs
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlockMeasureCache.MeasureEntry.cs
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlockMeasureCache.MeasureKey.cs
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlockMeasureCache.MeasureSizeEntry.cs
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlockMeasureCache.cs
src/Uno.UI/Uno.UI.csproj

- Feature
Add basic TextBlock measure caching to reduce the number of JS measureView invocations.
Same text measure time is divided by 2 using the interpreter.

[Wasm] Add TextBlock measure caching

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Popup/MessageDialog.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Popup/MessageDialog.xaml.cs

GitHub Issue (If applicable): Progresses #678 but does not resolve it.
- Feature
`MessageDialog` examples missing from the SampleApp
`MessageDialog` examples added to the SampleApp

added MessageDialog to the sample application

---

.dependabot/config.yml

dependabot raises PR's as soon as packages are published.
dependabot raises PR's once a week, if a package is published.

change dependabot to raise PR's once a week, if a package is published instead of live

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/GridTestsControl/GridTestViewModel.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs

Crash during code generation from XAML.
Some strings were not properly escaped and were interpreted as `.Format()` format, causing a `FormattingException` error.
Some of the strings are now properly escaped.
- ~~[ ] Tested code with current [supported SDKs](../README.md#supported)~~
- ~~[ ] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)~~
- ~~[ ] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)~~ (CI is enough to test this)
- ~~[ ] [Wasm UI Tests](doc/articles/working-with-the-samples-apps.md#running-the-webassembly- …

Xaml Generator crashing because of formatting exception

---

src/Uno.UI.BindingHelper.Android/Uno.UI.BindingHelper.Android.csproj

- Bugfix
Incremental builds may fail with an error similar to `Missing UnoViewGroup`.
Generated files are unconditionally added to avoid this issue.

Tentative fix for transient missing UnoViewGroup build error

---

src/Uno.UI/Controls/BindableUIButton.iOS.cs
src/Uno.UI/Controls/BindableUISwitch.iOS.cs
src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.iOSmacOS.cs
src/Uno.UI/UI/Xaml/Controls/Panel/Panel.iOS.cs
src/Uno.UI/UI/Xaml/Controls/Panel/Panel.macOS.cs
src/Uno.UI/UI/Xaml/Shapes/Rectangle.iOS.cs

GitHub Issue (If applicable): #985
- Bugfix
Compilation fail in VS16.2 preview
Compilation does not fail, as System.Drawing.Brush is now available in Xamarin and conflicts with UWP type.

Adjust namespaces for VS16.2 support

---

src/Uno.UI.BindingHelper.Android/Uno.UI.BindingHelper.Android.csproj

GitHub Issue (If applicable): #986
- Bugfix
The binding helpers target ordering is not stable enough to work consistently with some VS versions,
Some more explicit target dependences have been added to avoid being in a condition where the `_CompileUnoJava` target is executed too early.

Adjust _CompileUnoJava dependencies for #986

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.Tests/Windows_UI_XAML_Controls/GridTests/Given_Grid.cs
src/Uno.UI/UI/Xaml/Controls/Grid/Grid.cs

GitHub Issue (If applicable): fixes #1006 
- Bugfix
Calling Grid.ColumnDefintions.Clear() throws an exception.
The Columns are cleared.

Enumerate a copy of the grid row/column subscriptions

---

src/SamplesApp/SamplesApp.Shared/MainPage.xaml

- Bugfix
The sample chooser in the samples app does not appear.
The samples chooser is restored

Fix samples app invisible chooser

---

src/Uno.UI.Tests/Windows_UI_Xaml/VisualStateManagerTests/Given_VisualStateManager.cs
src/Uno.UI/UI/Xaml/Setter.cs
src/Uno.UI/UI/Xaml/VisualStateGroup.cs

- do not re-apply same visual state on each windows size changed
- clear only setters that won't  be updated by the target visual state
- Other: Perf optimisations
- Each time the window is resized, the state triggers are re-evaluated and the target state is re-applied no matter if it has changed or not
- When we go from a state to another state, we clear the value of all  `Setters` of the current state before applying the `Setters` of the target state
- We do not re-apply the `VisualState` if it's already the current one
- We clear only `Setters` that won't be affected by the target state.
This is part of a bigger changes set that will add Unit test for this feature …

Visual state perf

---

src/Uno.UI/UI/Xaml/Controls/MenuFlyout/MenuFlyout.cs

- Bugfix
Debugging an application that uses `MenuFlyout.Items` fails with :
```
System.InvalidOperationException: The Dependency Property [Items] is owned by [Windows.UI.Xaml.Controls.MenuFlyoutItem] and cannot be used on [Windows.UI.Xaml.Controls.MenuFlyout]
```
The application does not fail.

Adjust owner type of MenuFlyout.Items property

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/Behaviors/VisibleBoundsPadding.cs
src/Uno.UI/UI/Xaml/Window.wasm.cs

GitHub Issue (If applicable): Fixes #1015
- Bugfix
Resizing the browser window could result in invalid calculations that use `ApplicationView.VisibleBounds` and `Window.Bounds` simultaneously while being in a `ApplicationView.VisibleBoundsChanged` handler. 
This makes the `VisibleBoundsPadding` behavior fail when resizing the window, making controls such as the `NavigationView` appear blank.
The ordering of the `Window.SizeChanged` and `ApplicationView.VisibleBoundsChanged` is now aligned with UWP.

[Wasm] Align Window.SizeChanged and ApplicationView.VisibleBoundsChanged ordering with UWP

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI-Android-only.slnf
src/Uno.UI-UnitTests-only.slnf
src/Uno.UI-Wasm-only.slnf
src/Uno.UI-Windows-only.slnf
src/Uno.UI-iOS-only.slnf

- Build or CI related changes 
Loading the Uno.UI can take a significant time, which ever the current task at hand.
Added a set of `slnf` solution filters to speed up visual studio's loading time for known tasks (iOS, Android, Wasm, etc...). See [this for more details](https://docs.microsoft.com/en-us/visualstudio/ide/filtered-solutions?view=vs-2019).

Add known solution filters to ease the devloop

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UWP/Media/Playback/MediaPlayer.iOS.cs

#1022 
Bugfix
iOS MediaPlayer not breaking at applystretch -> videolayer is null when changing gravity
iOS Mediaplayer works
#154969

Fix to iOS MediaPlayer breaking from nullref

---

build/PackageDiffIgnore.xml
build/Uno.UI.Build.csproj
doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.Tests/Windows_UI_XAML_Controls/GridTests/Given_Grid.cs
src/Uno.UI.Tests/Windows_UI_Xaml/FrameworkElementTests/Given_FrameworkElement.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml/FrameworkElement.cs
src/Uno.UI/UI/Xaml/Controls/Layouter/Layouter.cs
src/Uno.UI/UI/Xaml/FrameworkElement.Android.cs
src/Uno.UI/UI/Xaml/FrameworkElement.cs
src/Uno.UI/UI/Xaml/FrameworkElement.iOS.cs
src/Uno.UI/UI/Xaml/FrameworkElement.macOS.cs
src/Uno.UI/UI/Xaml/IFrameworkElementImplementation.Android.tt
src/Uno.UI/UI/Xaml/IFrameworkElementImplementation.iOS.tt
src/Uno.UI/UI/Xaml/IFrameworkElementImplementation.macOS.tt
src/Uno.UI/UI/Xaml/Shapes/ArbitraryShapeBase.iOSmacOS.cs

- Bugfix
`FrameworkElement.LayoutUpdated` is not raised on all elements being arranged, and is not available on Wasm.
`FrameworkElement.LayoutUpdated` is invoked on all arranged elements.

Ensure FrameworkElement.LayoutUpdated is invoked properly

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/SourceGenerators/XamlGenerationTests/EnumValueNamespaceTest.xaml
src/SourceGenerators/XamlGenerationTests/EnumValueNamespaceTest.xaml.cs

Bugfix
Source generator doesn't prefix enum value with `global::`.
Source generator now prefixes enum value with `global::`.
Given this xaml file:
```xaml
<Page x:Class="XamlGenerationTests.Shared.NamespaceClashPoint.EnumValueNamespaceTest"
xmlns:example="using:NamespaceClashPoint.Example">
<Grid example:GridAsdHelper.Asd="A" />
```
The source generator would output:
```cs
namespace XamlGenerationTests.Shared.NamespaceClashPoint {
public sealed partial class EnumValueNamespaceTest : Windows.UI.Xaml.Controls.Page {
private void InitializeComponent() {
Content = new global::Windows.UI.Xaml.Controls.Grid { } …
```

fixed xaml generated enum value not being globalized

---

CODE_OF_CONDUCT.md

The CoC defers to the .NET foundation and does not specify contact details for the Uno project.

make the code of conduct more specific

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/Controls/CommandBarRenderer.Android.cs

Bugfix
On **android**, using the back button on the `CommandBar` with the soft keyboard closed will cause the keyboard to flicker.
No flickering.
This is a regression from #847. In that PR, I attempted to forced close the keyboard when an `AppBarButton` is pressed by clearing focus from the currently focused view. In doing so, we gave chance to other view on that page to take the focus. This causes the keyboard to open, only to be closed immediately because we are navigating away from that page.
https://nventive.visualstudio.com/Umbrella/_workitems/edit/155161

fixed keyboard flicker when backing from a page with CommandBar

---

src/Uno.UI/UI/Xaml/Controls/MenuFlyout/MenuFlyout.cs

Bugfix
Bindings in menuflyoutitems aren't set in its commands/parameters
MenuFlyoutItems can now receive DataContext
https://nventive.visualstudio.com/Umbrella/_workitems/edit/155170
https://nventive.visualstudio.com/Umbrella/_workitems/edit/155327

MenuFlyoutItems can now receive DataContext

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/ComboBox/ComboBox.cs
src/Uno.UI/UI/Xaml/Controls/Picker/Picker.iOS.cs
src/Uno.UI/UI/Xaml/Controls/Picker/PickerModel.iOS.cs
src/Uno.UI/UI/Xaml/Controls/Popup/PopupPanel.cs

- Remove dependency to a "Background" template part which is unnecessary and not required on UWP
- Make sure that the `PopupPanel` hides itself if collapsed (special cases as it's at the top of the `Window`)
- [iOS] Add support of `INotifyCollectionChanged` in the `Picker`
- [iOS] Remove the arbitrary `null` item added at the top of the `Picker`
- [iOS] Fix infinite layouting cycle in the iOS picker (Removed workaround which is no longer necessary as the given method is invoked properly on each measure/arrange phases)
- Bugfix
The opposite to what is described in commit comment above
What is described in commit comment above …

Misc fixes for the ComboBox

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.TestComparer/Program.cs
src/Uno.UI.Wasm/WasmCSS/Uno.UI.css
src/Uno.UI.Wasm/ts/WindowManager.ts

GitHub Issue (If applicable): #808 
Text measurement refactoring.
Sometimes a TextBlock were wrapping even if the parent were provinding enough space to prevent it.
The problem was caused by a parent element containing a _transform_ in the HTMLDOM. The cause
is directly in the spec itself:
<https://www.w3.org/TR/css-transforms-1/>
> For elements whose layout is governed by the CSS box model, any value other than none
> for the transform property also causes the element to establish a containing block for all
> descendants. Its padding box will be used to layout for all of its absolute-position
> descendants, fixed-position descendants, and descendant fixed background attachments.
**BONUS**: The investigations also revealed another one, never reported: a TextBlock width was hard limited to …

[Wasm] Text measurement bug when ancestor contains a RenderTransform

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/Control/Control.wasm.cs
src/Uno.UI/UI/Xaml/Input/FocusManager.wasm.cs

GitHub Issue (If applicable): Fixes #973, fixes #826
- Bugfix
The focus state of a control is not set properly, leading to incorrect focus cues or invalid TextBox bindings updates.
The FocusManager now sets the FocusState property correctly, by handling the bubbling of the GotFocus event properly.

[Wasm] Fix the processing of the GotFocus event FocusManager

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/Picker/Picker.iOS.cs

- Bugfix
The iOS Picker doesn't display the lines above and below the selected item.
The iOS Picker displays the lines above and below the selected item.
https://nventive.visualstudio.com/Umbrella/_workitems/edit/116098

Fix selection indicator not working on iOS Picker

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/GridTestsControl/Grid_MinWidth_MaxWidth.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/GridTestsControl/Grid_MinWidth_MaxWidth.xaml.cs
src/Uno.UI.Tests/Windows_UI_XAML_Controls/GridTests/Given_Grid.cs
src/Uno.UI.Tests/Windows_UI_XAML_Controls/GridTests/Given_Grid_And_Min_Max.cs
src/Uno.UI/Extensions/MathEx.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/ColumnDefinition.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/RowDefinition.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml/FrameworkElement.cs
src/Uno.UI/UI/Xaml/Controls/Grid/ColumnDefinition.cs
src/Uno.UI/UI/Xaml/Controls/Grid/Grid.Layout.cs
src/Uno.UI/UI/Xaml/Controls/Grid/Grid.cs
src/Uno.UI/UI/Xaml/Controls/Grid/RowDefinition.cs
src/Uno.UI/UI/Xaml/FrameworkElement.net.cs

GitHub Issue (If applicable): #1032 
Feature
Adds support for supports `ColumnDefinition.MinWidth` and `MaxWidth` and `RowDefinition.MinHeight` and `MaxHeight`.
This is not a complete implementation, for example we don't currently attempt to match UWP in the case that the sum of MinWidths exceeds the available width.

Grid - support Min/Max-Width/Height on Column/Row-Definitions

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBaseSource.iOS.cs

- Bugfix
The ListView's DataContext is propagated to the temporary item created when estimating the size of listview item templates, creating invalid binding errors.
Temporary items are created with a null DataContext.

[iOS] Fix invalid DataContext propagation when estimating ListView item size

---

src/Uno.UWPSyncGenerator/Generator.cs

- Refactoring (no functional changes, no api changes) 
```
public static DependencyProperty PlaceholderValueProperty { get; } =
DependencyProperty.Register(
"PlaceholderValue", typeof(double),
typeof(RatingControl),
new FrameworkPropertyMetadata(-1.0, OnStaticPropertyChanged));
```
```
public static DependencyProperty PlaceholderValueProperty { get; } =
DependencyProperty.Register(
nameof(PlaceholderValue), typeof(double),
typeof(RatingControl),
new FrameworkPropertyMetadata(-1.0, OnStaticPropertyChanged));
```
I did this edit in the GitHub editor, so critique it accordingly.

use nameof(backingproperty) so that references show up in visual studio

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Pivot/PivotSimpleTest.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Pivot/PivotSimpleTest.xaml.cs
src/Uno.UI/UI/Xaml/Controls/Primitives/PivotPanel.cs
src/Uno.UI/UI/Xaml/Controls/ScrollBarVisibility.cs

GitHub Issue (If applicable): https://github.com/nventive/calculator/issues/116
Implement measure/arrange of the `PivotPanel` in order to allow text wrapping in `PivotItem`
`PivotItem` are measured with an infinite width
`PivotItem` are measured with the view port width of the parent `ScrollViewer`

Make sure that the PivotPanel allows text wrapping

---

src/Uno.UI/UI/Xaml/Documents/UIElementTextHelper.wasm.cs

GitHub Issue (If applicable): https://github.com/nventive/calculator/issues/116
Word wrapping on WASM does not behaves as UWP
Words longer than the viewport overflows instead of wrapping
Long words are wrap in the middle of the word if needed
This feature is tested by the tests of  https://github.com/nventive/Uno/pull/1053

Fix text wrapping does not wrap words longer than the viewport

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/PathIcon.cs

- Feature
`PathIcon` is now supported for Wasm.

[Wasm] Add PathIcon support

---

build/PackageDiffIgnore.xml
doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/TextWrapping.cs

Remove the invalid value `WordEllipsis` from the `TextWrapping` enum as it's not a valid value for UWP (And it was actually supported only on WASM)
- ~~[ ] Contains **NO** breaking changes~~
**This is a breaking change**

Remove `TextWrapping.WordEllipsis`

---

src/Uno.UI.BindingHelper.Android/Uno.UI.BindingHelper.Android.csproj

GitHub Issue (If applicable): #986
The Uno.UI.BindingHelper assembly may not contain the proper classes leading to errors involving `UnoViewGroup`, when incremental compilation is involved.
A temporary file is tentatively deleted to force the generation of android bindings.

Tentative workaround for invalid incremental build of Android binding helper

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/AutoSuggestBoxTests/BasicAutoSuggestBox.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/AutoSuggestBoxTests/BasicAutoSuggestBox.xaml.cs
src/Uno.UI/UI/Xaml/Controls/AutoSuggestBox/AutoSuggestBox.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/BufferViewCache.Android.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.Android.cs
src/Uno.UI/UI/Xaml/Controls/Popup/Popup.Android.cs
src/Uno.UI/UI/Xaml/Controls/Popup/PopupPanel.cs

- fix hangs, crashes
- ensure user can keep typing after suggestions appear. This is still somewhat limited relative to UWP, eg trying to change the position of the cursor will close the suggestions dropdown.
GitHub Issue (If applicable): fixes #1012 
Bugfix

AutoSuggestBox works on Android

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/SimpleText_MaxLines_One.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/SimpleText_MaxLines_One.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/SimpleText_MaxLines_Two_With_Wrap.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/SimpleText_MaxLines_Two_With_Wrap.xaml.cs
src/Uno.Foundation/Size.cs
src/Uno.UI.Tests/Windows_UI_Xaml_Controls/TextBlockTests/Given_TextBlockMeasureCache.cs
src/Uno.UI/FeatureConfiguration.cs
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.wasm.cs
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlockMeasureCache.MeasureEntry.cs
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlockMeasureCache.MeasureKey.cs
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlockMeasureCache.MeasureSizeEntry.cs
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlockMeasureCache.cs
src/Uno.UI/UI/Xaml/FontFamily.cs
src/Uno.UI/UnoMetrics.cs

GitHub Issue (If applicable): #1062 
A cached value was hit even when it was the result of a constrained sized.
With this bug, a textblock with the same properties would be the same constrains
even if it's not asked anymore.
This was causing textblock measured to availableSize=[0, 0] to disappear completely.
Cache are now hit only when appropriate.

[Wasm] Fix TextBlock measure cache algorithm

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Slider/Slider_Inside_ListViewHeader.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/SimpleText_MaxLines_One.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/SimpleText_MaxLines_Two_With_Wrap.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/TextBlock_ConstrainedByContainer.xaml
src/Uno.UI.Tests/Windows_UI_Xaml_Controls/TextBlockTests/Given_TextBlockMeasureCache.cs
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlockMeasureCache.MeasureEntry.cs
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlockMeasureCache.MeasureKey.cs
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlockMeasureCache.cs

GitHub Issue (If applicable): #1062
PR #1063
Il previous PR, the bug was still present if the text was clipping.
When the clipping is activated, it will behave like it's wrapping.
- ~~[ ] Updated the [Release Notes](https://github.com/nventive/Uno/tree/master/doc/ReleaseNotes)~~

[Wasm] Fixed measure cache when text clipping is used

---

build/PackageDiffIgnore.xml
doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/ComboBox/ComboBox.cs
src/Uno.UI/UI/Xaml/Controls/ItemsControl/ItemsControl.cs
src/Uno.UI/UI/Xaml/Controls/ItemsStackPanel/IVirtualizingPanel.cs
src/Uno.UI/UI/Xaml/Controls/ItemsStackPanel/ItemsStackPanelLayout.cs
src/Uno.UI/UI/Xaml/Controls/ItemsStackPanel/ItemsStackPanelLayout.iOS.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.Stub.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.iOS.cs
src/Uno.UI/UI/Xaml/Controls/Primitives/CarouselPanel.cs
src/Uno.UI/UI/Xaml/Controls/Primitives/CarouselPanel.wasm.cs
src/Uno.UI/UI/Xaml/Controls/Primitives/OrientedVirtualizingPanel.cs
src/Uno.UI/UI/Xaml/Controls/VirtualizingPanel.cs
src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml

GitHub Issue (If applicable): fixes #555 
Feature
- Inherit CarouselPanel from VirtualizingPanel (for now borrows layouting logic from ItemsStackPanel)
- Fixes to measure properly on iOS
- Ensure selected item is always in view when dropdown opens
ComboBox dropdown isn't virtualized. Extremely slow for large numbers of items.
Now it's virtualized.
Breaking change:
* If `ComboBox` has a modified template (eg from overriding the default `Style`), then the `ScrollViewer` hosting the `ItemsPresenter` needs to have its `Style` set to `StaticResource ListViewBaseScrollViewerStyle` (as [here](https://github.com/nventive/Uno/blob/21c49fd1d6136352f71a894686a9b4130e300b95/src/Uno.UI/UI/Xaml/Style …

Virtualize ComboBox dropdown

---

.mergify.yml

- Maintainers need to babysit builds and wait for them to pass before merging.
- Maintainers need to remember to delete branches after they are merged.
- When a pull-request to `master` has 2 or more approvals and no requests for change it will be automatically merged if the CI passes, is labelled with `ready-to-merge` unless it has been labelled with `do-not-merge/breaking-changes` or `do-not-merge/work-in-progress`
See https://github.com/digital-asset/daml/blob/master/.mergify.yml for comparison.
See https://doc.mergify.io/configuration.html for documentation

delete branches after merge, enable automatic merging of prs

---

src/Uno.UI/UI/Xaml/Controls/ComboBox/ComboBox.cs
src/Uno.UI/UI/Xaml/Controls/Popup/PopupBase.cs
src/Uno.UI/UI/Xaml/Controls/Popup/PopupPanel.cs

+ Fix bottom padding of picker on iPhone X*
App crashes when closing the picker on iOS
The `visibleBounds` are not constrained by the `available` / `finalSize` so the `ICustomPopupLayouter` receive unexpected values when the popup is being closed, especially since we make sure sure to set those  `available` / `finalSize` to `0,0` when closing popup.
`visibleBounds` are "at most" the `available` / `finalSize`

Fix infinite loop when closing a "FullScreenDropDown"

---

src/Uno.UWPSyncGenerator/DocGenerator.cs

Remove debugging code, put filter in the correct place
GitHub Issue (If applicable): #267

Docs - filter event handlers from implemented views

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/documentation-issue.md
.github/ISSUE_TEMPLATE/documentation-request.md
.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/feedback.md
.github/ISSUE_TEMPLATE/samples-issue.md
.github/ISSUE_TEMPLATE/samples-request.md
.github/ISSUE_TEMPLATE/success-story.md

- Other
It turns out GitHub requires multiple labels to be separated by commas:
https://raw.githubusercontent.com/ghuntley/cccccchnfddrftgubenfebrvtduutuvtfvtgdtidj/master/.github/ISSUE_TEMPLATE/bug_report.md
https://help.github.com/en/articles/creating-issue-templates-for-your-repository
When someone uses the `new issue` button the labels are not automatically applied.
Labels are automatically applied.

GitHub labels will now be automatically applied when people use the new issue button

---

SECURITY.md

GitHub Issue (If applicable): Fixes #919
No guidance provided for security researchers.
See https://github.com/TryGhost/Ghost/blob/master/SECURITY.md

add explicit instructions for security researchers how to responsibly disclose security related matters

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UWP/Graphics/Display/DisplayInformation.wasm.cs

GitHub Issue (If applicable): Fixes #385
- Feature
Add support for `DisplayInformation` properties `LogicalDpi`, `ResolutionScale`, `ScreenWidthInRawPixels`, `RawPixelsPerViewPixel` , and `ScreenHeightInRawPixels`¸

[Wasm] Add support for `DisplayInformation` properties

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls.Primitives/PickerFlyoutBase.cs
src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePickerFlyout.Android.cs
src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePickerFlyout.iOS.cs
src/Uno.UI/UI/Xaml/Controls/Primitives/PickerFlyoutBase.cs
src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerFlyout.Android.cs
src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerFlyout.iOS.cs
src/Uno.UI/Uno.UI.csproj

Bugfix
Refactor
App may crash on clicking flyout buttons
Flyout button are working
https://nventive.visualstudio.com/Umbrella/_workitems/edit/156490

Fix to Date/Time Pickers crashing from no content

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_Inside_ListView.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_Inside_ListView.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Models/ListViewSelectionsViewModel.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Models/TwoLevelListItem.cs
src/Uno.UI.BindingHelper.Android/Uno/UI/UnoViewGroup.java

Displaying a ListView inside another ListView sometimes makes the Android app freeze then crash with an endless loop.
Displaying a ListView inside another ListView is properly supported on Android.
https://nventive.visualstudio.com/Umbrella/_workitems/edit/156620

Fix layout issue with a ListView inside another ListView

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs

- Build or CI related changes 
Others solutions not building correctly because generated x:uid setters not globalized for: 
- Uno.UI.Helpers.MarkupHelper.SetXUid
- Uno.UI.FrameworkElementHelper.SetRenderPhase
Generated x:uid setters are now globalized
https://nventive.visualstudio.com/Umbrella/_build/results?buildId=114277&_a=summary

Fixed generated x:uid setter not globalized for Uno.UI.Helpers.MarkupHelper.SetXUid and Uno.UI.FrameworkElementHelper.SetRenderPhase

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.Tests/BinderTests/Given_BindingPath.cs
src/Uno.UI/DataBinding/BindingPath.cs

Bugfix
If a two-way binding is activated at a time when the DataContext has the wrong datatype, it will remain invalid even after the DataContext changes - the source will not be updated.
After a two-way binding's DataContext is set to the correct DataType, it will update its source correctly.
Internal Issue:
https://nventive.visualstudio.com/Umbrella/_workitems/edit/155331

Fix Two-Way binding

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.Tests/BinderTests/Given_BindingPath.cs
src/Uno.UI/DataBinding/BindingPath.cs

Bugfix 
If a two-way binding is activated at a time when the DataContext has the wrong datatype, it will remain invalid even after the DataContext changes - the source will not be updated.
After a two-way binding's DataContext is set to the correct DataType, it will update its source correctly.
https://nventive.visualstudio.com/Umbrella/_workitems/edit/155331

Fix Two-Way binding when DataContext has wrong datatype

---

.github/topissuebot.yml

- Votes on issues are meaningless.
Provides the community with a way to influence the backlog, though we would prefer folks shipped PR's and talked to us about becoming regular contributors.
Anyway when this PR lands a bot will run every 25 minutes, labeling top issues and unlabeling issues that are no longer top issues. Top issues are issues with the most "+1" emoji reactions on the issue description. "+1" emoji reactions on issues comments are not considered.
Opening early. Should this be top 10 or top 25?
See https://github.com/adamzolyak/gh-vote-bot for documentation

automation: automatically triage/label the most voted issues by the community

---

.github/no-response.yml

- Maintainers need to manually nag someone
Once per hour, it searches for issues that are:
* Open
* Have a label named the same as the `responseRequiredLabel` value in the configuration
* The `responseRequiredLabel` was applied more than `daysUntilClose` ago
For each issue found, it:
1. If `closeComment` is not `false`, posts the contents of `closeComment`
1. Closes the issue
When an `issue_comment` event is received, if all of the following are true:
* The author of the comment is the original author of the issue
* The issue has a label named the same as the `responseRequiredLabel` value in the configuration
It will:
1. Remove the `responseRequiredLabel`
1. Reopen the issue if it was closed by someone other than the …

automation: close issues marked with 'triage/needs-information' if no reply in 20 days.

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_TextBox.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_TextBox.xaml.cs

https://github.com/unoplatform/private/issues/20
- Sample for textbox in a listview
No sample with a textbox in a listview
New sample "ListView_TextBox" in Listview

add sample for textbox in a listview

---

src/SamplesApp/SamplesApp.UITests/UnoSamples_Tests.Keyboard.cs
src/Uno.UI/UI/Xaml/Input/FocusManager.cs

- Bugfix
iOS Infinite loop
BugFix - Adds check to onFocusChanged unfocusing when setting focus causing loop
https://nventive.visualstudio.com/Umbrella/_workitems/edit/157061

BugFix - Adds check to onFocusChanged unfocusing when setting focus causing loop

---

doc/ReleaseNotes/_ReleaseNotes.md
doc/articles/api-differences.md
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/ThemeResources/BasicThemeResources.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/ThemeResources/BasicThemeResources.xaml.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/SourceGenerators/XamlGenerationTests/GlobalStaticResources02.xaml
src/SourceGenerators/XamlGenerationTests/ThemeResourcesTest.xaml
src/SourceGenerators/XamlGenerationTests/XBindUserControl.xaml
src/SourceGenerators/XamlGenerationTests/XamlGenerationTests.csproj
src/Uno.UI/UI/Xaml/ApplicationHelper.cs

GitHub Issue (If applicable): #935 #1047 
First support for ThemeResources
* Using `{ThemeResource xxx}` were already working as an alias to `{StaticResource}`
* Declaring a _Theme Dictionary_ were leading to missing resources at runtime and/or
compilation errors for duplicated members.
* You can now declare a _Theme Dictionary_ in your XAML dictionaries
* _Themed resources_ will now resolve to right theme (`Light` or `Dark`)
* **Custom Themes Supported**! You can trigger themes like `HighContrast` or
totally custom themes.
* [154631](https://nventive.visualstudio.com/Umbrella/_workitems/edit/154631)

Initial support for ThemeResources

---

.github/CODEOWNERS

No clear responsibilities of who should review a PR
GitHub will pattern match the contents and ask them to review a PR
```
```
See https://github.com/reactiveui/ReactiveUI/blob/master/.github/CODEOWNERS for examples. In this PR I've made `*` to the maintainers team. It can be made more granular than that.

housekeeping: implement the codeowners convention

---

build/PackageDiffIgnore.xml
doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UWP/Media/Playback/MediaPlayer.iOS.cs

**Tries** to prevent crash: 
```
Crashed: AVAudioSession Notify Thread
0  AudioToolbox                   0x1a96762c0 AudioSessionPropertyListeners::CallPropertyListenersImp(AudioSessionPropertyListeners const&, unsigned int, unsigned int, void const*) + 456
1  AudioToolbox                   0x1a976c100 AudioSessionPropertyListeners::CallPropertyListeners(unsigned int, unsigned int, void const*) + 220
2  AudioToolbox                   0x1a97aa43c HandleCFPropertyListChange(unsigned int, unsigned int, unsigned long, unsigned char*, unsigned int) + 456
3  AudioToolbox                   0x1a97aea34 HandleAudioSessionCFTypePropertyChangedMessage(unsigned int, unsigned int, void*, unsigned int) + 268
4  AudioToolbox                   0x1a97adcf8 ProcessDeferredMessage(unsigned int, __CFData …
```

Fix possible crash with AudioToolbox

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UWP/Graphics/Display/DisplayInformation.Android.cs
src/Uno.UWP/Graphics/Display/DisplayInformation.iOS.cs

GitHub Issue (If applicable): #1209
- Bugfix
The value returned by `DisplayInformation.LogicalDpi` does not match the base value of 100% or 96.0 dpi. This makes DPI dependent algorithms incorrectly adjust size based on this value.
Both iOS and Android return properly adjusted values.

Adjust DisplayInformation.LogicalDPI value to UWP's

---

src/SamplesApp/SamplesApp.UITests/TestFramework/AutoRetry.cs
src/SamplesApp/SamplesApp.UITests/UnoSamples_Tests.Keyboard.cs

Bugfix
Tests may fail because of https://github.com/microsoft/appcenter/issues/723
Automatic retries are added.

Auto retry tests to workaround

---

src/SamplesApp/SamplesApp.UITests/UnoSamples_Tests.StaticResource.cs
src/SamplesApp/UITests.Shared/Resources/StaticResource/StaticResource_Simple.xaml
src/SamplesApp/UITests.Shared/Resources/StaticResource/StaticResource_Simple.xaml.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems

Migrate private UI Tests to public Uno
https://github.com/unoplatform/private/issues/23
- Added UI Test for StaticResource
- New Sample (StaticResource_Simple)
No sample/test for StaticResource
Sample for StaticResoucres set in xaml, C# and Converter
New Test:
StaticResource_XAML_Validation
StaticResource_CSharp_Validation
StaticResource_Converter_Validation

Migrate StaticResource UI Tests

---

build/android-uitest-wait-systemui.sh
src/SamplesApp/SamplesApp.UITests/UnoSamples_Tests.ContentControl.cs
src/SamplesApp/SamplesApp.UITests/UnoSamples_Tests.Popup.cs
src/SamplesApp/SamplesApp.UITests/UnoSamples_Tests.RadioButton.cs
src/SamplesApp/SamplesApp.UITests/UnoSamples_Tests.Touch.cs
src/SamplesApp/SamplesApp.UITests/UnoSamples_Tests.XBind.cs
src/SamplesApp/SamplesApp.UITests/Windows_ApplicationModel_Resources/ResourceLoader_Simple.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml/FocusManagerTests/UnoSamples_Tests.FocusManager.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ButtonTests/UnoSamples_Tests.Button_IsEnabled_Automated.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ButtonTests/UnoSamples_Tests.Button_Opacity_Automated.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ContentDialog/UnoSamples_Tests.ContentDialog.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TimePickerTests/UnoSamples_Tests.TimePicker.cs

- Bugfix
Try going to the android emulator home screen  as the messaging app may be brought in front.

[UITest] Adjust the android startup script

---

.azure-devops-android-tests.yml

GitHub Issue (If applicable): #1259
This PR disables build failure on Android UI Tests failures, because of unstable android builds.
See https://github.com/unoplatform/uno/issues/1259 for more details.

Disable fail build on Android UI Tests failure

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/PathTestsControl/Path_Arc.xaml
src/Uno.UI/Media/PathStreamGeometryContext.cs

None
- Bugfix
Some paths are truncated on iOS or not displayed on Android.
Paths displayed as expected
https://feedback.nventive.com/communities/1/topics/3536-androidpathcontrol-some-svg-shapes-are-not-displayed-on-android-there-are-missing-pieces-on-ios

Fix Arc command in paths

---

src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerSelector.iOS.cs

- Bugfix
Pressing done on the TimePicker does not do anything if no change was made.
Pressing done on the TimePicker should close the TimePicker even if no change was made.
cherry-picked from https://github.com/unoplatform/uno/pull/1228
Issue added to add UITests: https://github.com/unoplatform/uno/issues/1255
https://nventive.visualstudio.com/Umbrella/_workitems/edit/157504

Fixed the no date selected issue on Time Picker for IOS

---

build/android-uitest-run.sh
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ComboBoxTests/UnoSamples_Tests.ComboBoxTests.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ComboBox/ComboBox_ItemsSource.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ComboBox/ComboBox_Picker.xaml
src/Uno.UI/UI/Xaml/Controls/Picker/Picker.iOS.cs

- Bugfix
iOS initial value is the first item in the list 
iOS initial value is null
https://nventive.visualstudio.com/Umbrella/_workitems/edit/157456

Fix to iOS ComboBox initial selected value not null/empty

---

src/Uno.UI/UI/Xaml/Window.Android.cs

- Bugfix
Android app crash at launch
Android app shouldn't crash at launch
This PR is indented to fix an bug introduced in #850.
Can't invoke `Enum.HasFlag` with different enum types, even if [`View.SystemUiVisibility`](https://developer.android.com/reference/android/view/View.html#setSystemUiVisibility(int)) is meant to be used with `SystemUiFlags`.

fixed crash on android

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ListViewTests/UnoSamples_Tests.ListView.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListViewVariableItemHeightLong.xaml
src/Uno.UI/UI/Xaml/Controls/ItemsStackPanel/ItemsStackPanelLayout.iOS.cs

- Bugfix
- Refactoring
ListViews with footers and a lot of items may crash in ios
ListViews with a lot of variable items may crash from stackoverflow in ios 
ListView crashes fixed, Recursive function changed to iterative
https://nventive.visualstudio.com/Umbrella/_workitems/edit/158034

 Fix to infinite loop+refactored UpdateLayoutAttributesForItem iteratively

---

.azure-devops-wasm-uitests.yml
.github/pull_request_template.md
doc/ReleaseNotes/_ReleaseNotes.md
doc/articles/uno-development/working-with-the-samples-apps.md
src/SamplesApp/SamplesApp.UITests/Constants.cs
src/SamplesApp/SamplesApp.UITests/TestFramework/AppInitializer.cs
src/Uno.UI.TestComparer/AzureDevopsDownloader.cs
src/Uno.UI.TestComparer/Comparer/CompareResult.cs
src/Uno.UI.TestComparer/Comparer/CompareResultFile.cs
src/Uno.UI.TestComparer/Comparer/CompareResultFileRun.cs
src/Uno.UI.TestComparer/Comparer/TestFilesComparer.cs
src/Uno.UI.TestComparer/Program.cs
src/Uno.UI.TestComparer/Uno.UI.TestComparer.csproj
src/Uno.UI/Uno.UI.csproj

Screenshots comparisons are now published in the CI's output as unit test runs. Screenshot and image diffs files are also available as test attachments.

Generate and publish screenshot compare results

---

src/SamplesApp/SamplesApp.UITests/CommandBar/UnoSamples_Tests.CommandBar.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/CommandBar_LongTitle.xaml

Migrate private UI Tests to public Uno
https://github.com/unoplatform/private/issues/23
- Added UI Test for CommandBar 
No test for CommandBar 
New Test:
CommandBar_LongTitle_Validation

Migrate CommandBar UI Tests

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.RuntimeTests/Tests/Windows_Storage/Given_ApplicationDataContainer.cs
src/Uno.UWP/Storage/ApplicationDataContainer.Android.cs
src/Uno.UWP/Storage/ApplicationDataContainer.iOS.cs
src/Uno.UWP/Storage/ApplicationDataContainer.wasm.cs

GitHub Issue (If applicable): #1276 
- Bugfix
Reported problem in #1276, while investigating, found another inconsistency with UWP behavior.
Both problems now fixed and covered with unit tests

Fixed ApplicationDataContainer inconsistencies

---

gitversion.yml

`gitversion` calculates the version for `release/stable` branches as if they are "beta".
`gitversion` should now gives the correct version for each branch.
Cherry-pick of https://github.com/unoplatform/uno/pull/1297 for https://github.com/unoplatform/uno/tree/release/stable/Batman
See: https://github.com/nventive/Uno.Core/pull/54
https://nventive.visualstudio.com/Umbrella/_workitems/edit/157372

fixed gitversion

---

src/Uno.UWPSyncGenerator/Generator.cs

GitHub Issue (If applicable): #1275 
- Bugfix
**Cherry-picked the UWPSyncGenerator fixes from #1279**
Dependency properties are not correctly generated.
Also generated files differ from what the tool generates currently, so there is always a lot of changes even when user makes small change.
Generator bugs fixed, generated files aligned with latest generated code from the tool.
After running `UWPSyncGenerator` in this PR, tool should make 0 changes.

Fix for UWPSyncGenerator issues

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.Tests/Windows_UI_XAML_Controls/TextBoxTests/Given_TextBox.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs

Fix regression where a null pushed to Text via binding was being ignored, rather than clearing the Text.
GitHub Issue (If applicable): fixes #1302 
- Bugfix

TextBox - reset Text when pushing null to bound value

---

gitversion.yml

so feature branches will remain after the latest dev version in Nuget
GitHub Issue (If applicable): #1256 
* Major: Manually updated
* Minor: Manually updated
* Patch: Not used
==> Branches are ordered by nuget reverse-alphabetically based on the tag, so the feature branch versions are upper the dev version (as f > d)
* Major: Manually updated
* Minor: Manually updated
* Patch: Updated on each commit in dev branch
==> As the Patch number is incremented for each commit in dev, but not for feature branches, the dev versions should appear above the feature branch versions in nuget
- ~[ ] Tested code with current [supported SDKs](../README.md#supported)~
- ~[ ] Docs have been added/updated which fit [documentation …

Enable increment of Patch for each commit in dev branch

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Button/Button_Events.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Button/Button_Events.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Button/Overlapped_Buttons.xaml
src/Uno.UI/UI/Xaml/Controls/Primitives/ButtonBase/ButtonBase.Android.cs

GitHub Issue (If applicable): #1315
On Android, using `ButtonBase.Click` were not working properly:
it was required to register to event `.Tapped` for the click to work properly.
`.Tapped` requirement removed.

Fixed problem with ButtonBase.Click on Android

---

src/SamplesApp/SamplesApp.UITests/Toolkit/UnoSamples_Tests.Elevation.cs
src/SamplesApp/UITests.Shared/Toolkit/Elevation.xaml

Migrate private UI Tests to public Uno
https://github.com/unoplatform/private/issues/23
- Added UI Test for Elevation
No test for Elevation
New Test:
Elevation_Validation

Migrate Elevation UI Tests #1245

---

.azure-devops-wasm-uitests.yml
build/android-uitest-run.sh
src/Directory.Build.targets
src/SamplesApp/SamplesApp.Droid/SamplesApp.Droid.csproj
src/SamplesApp/SamplesApp.UITests/CommandBar/UnoSamples_Tests.CommandBar.cs
src/SamplesApp/SamplesApp.UITests/RuntimeTests.cs
src/SamplesApp/SamplesApp.UITests/SampleControlUITestBase.cs
src/SamplesApp/SamplesApp.UITests/SamplesApp.UITests.csproj
src/SamplesApp/SamplesApp.UITests/TestFramework/AppInitializer.cs
src/SamplesApp/SamplesApp.UITests/TestFramework/AutoRetry.cs
src/SamplesApp/SamplesApp.UITests/UnoSamples_Tests.Keyboard.cs
src/SamplesApp/SamplesApp.UITests/UnoSamples_Tests.StaticResource.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ComboBoxTests/UnoSamples_Tests.ComboBoxTests.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/DatePickerTests/UnoSamples_Tests.DatePicker.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ListViewTests/UnoSamples_Tests.ListView.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TimePickerTests/UnoSamples_Tests.TimePicker.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/DragCoordinates_Tests.cs
src/Uno.UI-Android-only.slnf

GitHub Issue (If applicable): Tentative fix for #1259
- Bugfix
Android tests fail randomly as the app crashes.
Android app should not crash anymore. The libmonosgen-2.0.so library is provided a local override that is coming from the binary from X.A: 9fa7775cbf9fed7d87253797f3f9c211dd94d228.
This is a tentative workaround for an unknown VS16.1 issue fixed in VS16.2 pre 4.

[UITest][Android] Adjust tests to allow for auto retry on failure

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Input/InputScopeNameValue.cs

- Feature
- partial enum implementation
- enum values not implemented
- full implementation with documentation
See https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.input.inputscopenamevalue

feature: implement all InputScopeNameValue

---

src/SamplesApp/SamplesApp.UITests/SampleControlUITestBase.cs
src/SamplesApp/SamplesApp.UITests/UnoSamples_Tests.Keyboard.cs

- Bugfix
Android UI Tests file names are not useful, now renamed to test names.

Adjust screenshots names for automated tests

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ListViewTests/UnoSamples_Tests.ListView.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/HorizontalListViewGrouped.xaml
src/Uno.UI/UI/Xaml/Controls/ItemsStackPanel/ItemsStackPanelLayout.iOS.cs

- Bugfix
https://nventive.visualstudio.com/Umbrella/_workitems/edit/158362

Fix to infinite loop with listviewHeaders

---

src/SamplesApp/SamplesApp.Shared/SamplesApp.Shared.projitems

- Bugfix
See diff.
See diff.
This was caused by a known vswin defect with shared projects.

fix: path defect caused by known vswin bug

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.UITests/UnoSamples_Tests.Keyboard.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_MaxLength.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_MaxLength.xaml.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.Android.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs

- Bugfix
**On Android**:
- After MaxLength is reached, text gets overwritten by subsequent characters. For example, if MaxLength=5, typing '123456' will result in '62345'.
- After MaxLength is reached, the BeforeTextChanging event is still called for subsequent characters. This is not the case on UWP.
**On WASM**: The MaxLength property is not respected.
**On Android and WASM**:
- The user is prevented from typing more text when MaxLength is reached.
- After MaxLength is reached, the BeforeTextChanging event is not triggered for subsequent characters (like on UWP). …

Fix MaxLength handling on Android and WASM

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/Properties/DataContextProperty.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/Properties/DataContextProperty.xaml.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/SourceGenerators/XamlGenerationTests/Grid.Test.AsRoot.xaml

GitHub Issue (If applicable): #718
Setting a collection-based property on the root of a XAML file like this
were leading to c# compilation errors:
```xml
<Grid
x:Class="XamlGenerationTests.Shared.GridAsRoot"
xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"> 
<Grid.ColumnDefinitions>
<ColumnDefinition />
</Grid.ColumnDefinitions>
</Grid>
```

Errors setting some properties on root of XAML file

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.Maps/Uno.UI.Maps.csproj

MonoAndroid uses outdated versions of Xamarin.GooglePlayServices packages
MonoAndroid uses latest stable versions of Xamarin.GooglePlayServices packages for both Android 8 and Android 9
~~- [ ] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)~~
~~- [ ] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)~~
~~- [ ] [Wasm UI Tests](doc/articles/working-with-the-samples-apps.md#running-the-webassembly-ui-tests-snapshots) are not showing unexpected any differences. Validate PR …

Update Xamarin.GooglePlayServices packages

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Input/Keyboard/Keyboard_Clickthrough_Modal.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Input/Keyboard/Keyboard_Clickthrough_Modal.xaml.cs

#1155
New Sample
The specific scenario in #1155 is not test/reproduce-able within the Samples app
Added a sample demonstrating the behavior

Added Sample for Keyboard Modal Click-through troubleshooting

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SolutionTemplate/UnoSolutionTemplate/Shared/App.xaml.cs

GitHub Issue (If applicable): #1409
- Bugfix
When navigation to a page fails (OnNavigationFailed) an exception is thrown with the name of the page that failed to load. The actual reason why the exception is thrown is swallowed. This behavior hides root causes and makes troubleshooting new applications harder, especially on the WebAssembly head.
The error message includes the root-cause of the error by providing it's exception-message.

Provide a better error-message on page-navigation-errors

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.UITests/SampleControlUITestBase.cs
src/SamplesApp/SamplesApp.UITests/TestFramework/AppInitializer.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ContentPresenter/ContentPresenter_Background.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ContentPresenter/ContentPresenter_Changing_ContentTemplate.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ContentPresenter/ContentPresenter_Changing_ContentTemplate.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ContentPresenter/ContentPresenter_Content_DataContext.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ContentPresenter/ContentPresenter_ImplicitContent.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ContentPresenter/ContentPresenter_ImplicitContent.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ContentPresenter/ContentPresenter_LocalOverride.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ContentPresenter/ContentPresenter_TextProperties.xaml.cs
src/Uno.UI/FeatureConfiguration.cs
src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.cs
src/Uno.UI/UI/Xaml/DependencyObjectExtensions.cs

GitHub Issue (If applicable): #857 Implicit template binding of ContentPresenter.Content does not work
`<ContentPresenter>` will now - as a fallback when not set - automatically bind to
`TemplatedParent`'s `Content` when this one is a `ContentControl`.

ContentPresenter fallback binding to TemplatedParent's Content

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/Controls/BindableProgressBar.Android.cs

GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/1428
- Feature
See https://github.com/unoplatform/uno/issues/1428
This is now possible:
```csharp
public partial class NativeProgressControl : BindableProgressBar
{
public NativeProgressControl() : base(ContextHelper.Current, null, Android.Resource.Attribute.ProgressBarStyleHorizontal)
{
Indeterminate = false;
}
```
Thus allowing result based progress bars:

Surface all ProgressBar constructors

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/SourceGenerators/XamlGenerationTests/ThemeResourcesTest.xaml

GitHub Issue (If applicable): #1352
- Bugfix
- `StaticResource` not working inside `ResourceDictionary.ThemeDictionaries`
- Using a `ThemeResource` on the wrong property type should fails silently (no-crash, but the property is cleared). In uno, we are trying to resolve this statically during compile-time.
- The current implementation of `ThemeDictionaries` fail to support themed resources with different types (eg: mixing `SolidColorBrush` and `LinearGradientBrush`)
Fixed the above issues.

ThemeResource bugfixes

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/Primitives/ButtonBase/ButtonBase.cs

- Bugfix
The `ButtonBase.IsPointerOver` property is now available, as it was removed incorrectly.

Restore missing ButtonBase.IsPointerOver property

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/Image/Image.cs

- Bugfix
Image using Stretch=Uniform in a vertical "Auto" context doesn't stretch properly.
i.e. the image takes it's native size rather than stretching.
Image using Stretch=Uniform in a vertical "Auto" context now stretches properly.
i.e. the image behaves like UWP.
https://nventive.visualstudio.com/Umbrella/_workitems/edit/160805

Fix layouting bug in Image for Android and iOS

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.UITests/UnoSamples_Tests.ContentControl.cs
src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.cs
src/SamplesApp/UITests.Shared/Resources/StaticResource/StaticResource_Simple.xaml.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ComboBox/ComboBox_DisplayMemberPath.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ComboBox/ComboBox_DisplayMemberPath.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ComboBox/ComboBox_ItemDataContext.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ComboBox/ComboBox_ItemDataContext.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ContentPresenter/ContentPresenter_Template.xaml.cs
src/Uno.UI/UI/Xaml/Controls/ComboBox/ComboBox.cs
src/Uno.UI/UI/Xaml/DependencyObjectStore.cs

GitHub Issue (If applicable): #1387
When using `DisplayMemberPath` on a `<ComboBox>`, the path is applied on the
_parent_ `DataContext` when there's no _selected item_.
The `DataContext` is not propagated anymore to children, even when there's no
_Selected Item_.

ComboBox: Fix DataContext Inheritance on ContentPresenter when no selected item.

---

src/SamplesApp/SamplesApp.UITests/TestFramework/AppInitializer.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ImageTests/UnoSamples_Tests.Image.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/ImageSourceWriteableBitmapInvalidate.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/ImageSourceWriteableBitmapInvalidate.xaml.cs
src/Uno.UI/UI/Xaml/Controls/Image/Image.cs
src/Uno.UI/UI/Xaml/Controls/Image/Image.wasm.cs
src/Uno.UI/UI/Xaml/Media/Imaging/WriteableBitmap.cs

GitHub Issue (If applicable): #https://github.com/unoplatform/uno/issues/1490
Add support of WriteableBitmap.Invalidate
WriteableBitmap.Invalidate does nothing
WriteableBitmap.Invalidate works

Add support of Invalidate on WriteableBitmap

---

src/Uno.UI/UI/Xaml/DependencyPropertyDescriptor.cs

- Bugfix
`FormatException` is thrown in `DependencyPropertyDescriptor.Parse`.
No exception.
```
Uno.UI.DataBinding.BindingPropertyHelper:
GetValueGetter(Windows.UI.Xaml.UnsetValue, Models:PaneState) [Reflection]
Exception:
System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
```

fixed FormatException in DependencyPropertyDescriptor

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UWP/Generated/3.0.0.0/Windows.UI.Input/PointerUpdateKind.cs
src/Uno.UWP/UI/Input/PointerUpdateKind.cs

GitHub Issue (If applicable): fixes #1492
- Feature
`[Uno.NotImplemented]`
As per https://docs.microsoft.com/en-us/uwp/api/windows.ui.input.pointerupdatekind

feature: implement PointerUpdateKind enum

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ListViewTests/UnoSamples_Tests.ListView.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_ItemsPanel_HotSwap.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_ItemsPanel_HotSwap.xaml.cs
src/Uno.UI/UI/Xaml/Controls/ItemsControl/ItemsControl.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.Android.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.iOS.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.iOSAndroid.cs

GitHub Issue (If applicable): #1354
- Bugfix
On android, when `ListView.ItemsPanel` changes, the newly created native panel doesn't have its adapter is initialized in time (or at all). This cause the `Recycler.State` to go out of sync with the actual items inside the list-view which results in an app crash.
No crash.
This app crash at launch with:
```
Java.Lang.IllegalStateException: View with id -1: md53236df40a47f0df12473f710f43d224f.NativeListViewBase#onMeasure() did not set the measured dimension by calling setMeasuredDimension()
```
The real exception is actually swallowed by: `RaiseRecoverableUnhandledExceptionOrLog` in `VirtualizingPanelLayout.OnMeasure`:
```
{System.IndexOutOfRangeException: Invalid item position (0). …
```

fixed RecyclerView.State desync

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/PopupTests/UnoSamples_Popup_Simple_Tests.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Popup/Popup_Simple.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Popup/Popup_Simple.xaml.cs
src/Uno.UI/UI/Xaml/Controls/Popup/Popup.Android.cs
src/Uno.UI/UI/Xaml/Controls/Popup/Popup.iOS.cs
src/Uno.UI/UI/Xaml/Controls/Popup/PopupBase.cs

* iOS & Android:
* Clicking outside a _dismissible popup_ were not closing it.
* Wasm:
* Clicking in the content of a _dismissible popup_ were dismissing it.
- ~~[ ] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)~~
* <https://github.com/unoplatform/private/issues/51>
* <https://github.com/unoplatform/private/issues/57>

Dismissible popup various fixes

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.Wasm/WasmScripts/Uno.UI.js
src/Uno.UI.Wasm/ts/Windows/UI.Core/SystemNavigationManager.ts
src/Uno.UWP/UI/Core/SystemNavigationManager.cs

Fix Issue Where SystemNavigationManager.enable() is called two time during navigation.uring navigation.
https://github.com/unoplatform/private/issues/60
During navigation request, the 
SystemNavigationManager.enable() is called two time, this raises SystemNavigationManager.GetForCurrentView().BackRequested, this may cause the app to lose their navigation stack.
SystemNavigationManager.enable() will be hit only if SystemNavigationManager.Disable() has been hit first for the new page in the stack.

Fix Navigation Issue Where SystemNavigationManager.enable() is called twice

---

src/Uno.UI/FeatureConfiguration.cs

It solves #1332 (at least partially) - correct font used by SymbolIcon, used by AppBarButton, on Android.
GitHub Issue (If applicable): #1332
- Bugfix
Bad font is used on Android (Symbol).
Correct font is used.
Sorry, not - too little memory on my PC, but I created small project with AppBarButton with appriopriate font name and it works.

Correction to #if condition

---

src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.wasm.cs

GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/234
ScrollViewer offsets
Offsets are parssed as `int` but we often get a `double` so parsing fails and if fallbacks to 0, leading the managed `ScrollViewer` believe that offset are at 0 while the native is much lower.
Parsing works :)

Fix WASM ScrollViewer offsets parsing

---

src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/xamarinforms-wasm/UnoQuickStart.Wasm/UnoQuickStart.Wasm.csproj

- Bugfix
Some assets are not linked properly in `dotnet new` 
Assets are now properly linked.

Add missing assets link in dotnet new template

---

src/Uno.UI/UI/Xaml/Controls/Primitives/PivotPanel.cs

`PivotPanel` were returning the `availablesize`'s `Height` as desired height, which is invalid when the available size is infinite.
This was causing a crash.

Prevent PivotPanel from returning "infinite" as desired height

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ListViewTests/UnoSamples_Tests.ListView.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_VirtualizePanelAdaptaterIdCache.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_VirtualizePanelAdaptaterIdCache.xaml.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelAdapter.wasm.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.wasm.cs

https://github.com/unoplatform/private/issues/60
In WASM the index is superior to the VirtualizePanelAdaptater Item causing a OutofRangeException.
https://gist.github.com/ghuntley/90eb1a9af59c5be87a43df33323e059b
Verify if the Index is not bigger than the list's length

Fix Index is Greater than the items available from a VirtualizePanelAdaptater for WASM

---

doc/ReleaseNotes/_ReleaseNotes.md
doc/articles/features/windows-system.md
src/Uno.UI.RuntimeTests/Tests/Windows_System/Given_Launcher.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_StartScreen/Given_JumpListItem.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.System/LaunchQuerySupportStatus.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.System/LaunchQuerySupportType.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.System/Launcher.cs
src/Uno.UWP/System/LaunchQuerySupportStatus.cs
src/Uno.UWP/System/LaunchQuerySupportType.cs
src/Uno.UWP/System/Launcher.cs

GitHub Issue (If applicable): #1511 
- Feature
API not supported
API supported on iOS and Android. WASM does not support such check at this moment.

Support for Launcher.QueryUriSupportAsync API

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.BindingHelper.Android/Uno/UI/UnoViewGroup.java

GitHub Issue (If applicable): https://github.com/unoplatform/Uno.WindowsCommunityToolkit/pull/59#issuecomment-533661254
- Bugfix
Touching an element in an `AutoSuggestBox` may crash the application.
The application does not crash.
This PR should be tested once unoplatform/Uno.UITest#19 is fixed.

[Android] Fix java NRE handing touch events on detached view

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/Clip/DoubleAnimationClipping.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/Clip/DoubleAnimationClipping.xaml.cs

GitHub Issue (If applicable): #1599
- Other... Please describe: new sample
Added a new sample to illustrate the clipping issue with `DoubleAnimation`.
This is an regression from: https://github.com/unoplatform/uno/pull/1373
https://nventive.visualstudio.com/Umbrella/_workitems/edit/160360
https://nventive.visualstudio.com/Umbrella/_workitems/edit/161730

added a sample DoubleAnimation clipping issue

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/Transform/List_With_Transformed_Ancestor.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/Transform/List_With_Transformed_Ancestor.xaml.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/NativeListViewBase.Android.cs

Setting ClipChildren to false ensures animation is still updated correctly outside of its pre-transform bounds.
- Bugfix
https://github.com/unoplatform/private/issues/35
https://github.com/unoplatform/private/issues/38

[Android] Fix glitchy animations inside list with transformed ancestor

---

src/SolutionTemplate/UnoSolutionTemplate/UWP/UnoQuickStart.Uwp.csproj

fixes https://github.com/unoplatform/uno/issues/1614#issue-498932273
Update project configuration
Project target Windows version was 10.0.16299.0.
Project target Windows version is 10.0.17763.0.

Increased target and minimum versions of Windows to 10.0.17763.0

---

.azure-devops-wasm-uitests.yml
build/android-uitest-run.sh
build/run-automated-uitests.sh

Build errors happening on *nixes are not reported properly
Build fails early at the proper location.

Fail fast on *nix script errors

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/DatePickerTests/UnoSamples_Tests.DatePicker.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/DatePicker/DatePickerFlyout_MinYear.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/DatePicker/DatePickerFlyout_MinYear.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/DatePicker/DatePicker_SampleContent.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/DatePicker/DatePicker_SampleContent.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/DatePicker/Models/DatePickerViewModel.cs
src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePickerFlyout.iOS.cs
src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePickerSelector.iOS.cs
src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml

https://github.com/unoplatform/private/issues/75
ios datepicker min and max year get reset to fallbacknull value
ios datepicker min and max year values function properly

IOS BugFix Datepicker min and max year get reset to fallbacknull value

---

.azure-devops-android-tests.yml
doc/articles/supported-features.md
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/MarkupExtensionTests/Entity.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/MarkupExtensionTests/InverseBool.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/MarkupExtensionTests/MarkupExtension.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/MarkupExtensionTests/MarkupExtensionBehaviors.cs
src/SourceGenerators/Uno.UI.SourceGenerators/Helpers/RoslynMetadataHelper.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlConstants.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/SourceGenerators/XamlGenerationTests/CustomMarkupExtensions.xaml
src/SourceGenerators/XamlGenerationTests/CustomMarkupExtensions.xaml.cs
src/Uno.UI.Tests/App/Behaviors/AttachedPropertiesBehavior.cs
src/Uno.UI.Tests/App/Xaml/Test_MarkupExtension.xaml
src/Uno.UI.Tests/App/Xaml/Test_MarkupExtension.xaml.cs
src/Uno.UI.Tests/Uno.UI.Tests.csproj
src/Uno.UI.Tests/Windows_UI_Xaml/MarkupExtensionTests/Given_MarkupExtension.cs
src/Uno.UI/UI/Xaml/Markup/IMarkupExtensionOverrides.cs
src/Uno.UI/UI/Xaml/Markup/MarkupExtensions.cs

#39 
Feature
Added support for developers to use their own custom MarkupExtensions.
- [X ] Tested code with current [supported SDKs](../README.md#supported)
- [X ] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [X ] Contains **NO** breaking changes
- [X ] Associated with an issue (GitHub or internal)

Added support for custom MarkupExtensions

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/SourceGenerators/XamlGenerationTests/CustomMarkupExtensions.xaml
src/SourceGenerators/XamlGenerationTests/CustomMarkupExtensions.xaml.cs
src/Uno.UI.Tests/App/Xaml/Test_MarkupExtension.xaml
src/Uno.UI.Tests/App/Xaml/Test_MarkupExtension.xaml.cs
src/Uno.UI.Tests/Windows_UI_Xaml/MarkupExtensionTests/Given_MarkupExtension.cs

GitHub Issue (If applicable): #39
Feature
Currently, markup extensions require the `MarkupExtensionReturnType` attribute to be specified.
Allows the `MarkupExtensionReturnType` attribute to be optional and allows a developer to be able to return different types from one markup extension.
Allows the following issue to be worked on:
https://github.com/unoplatform/Uno.WindowsCommunityToolkit/issues/60

Added a change to make the MarkupExtensionReturnType optional

---

.github/labeler.yml
.github/workflows/labeler.yml

I'm spending too much time labeling pull-requests by hand and at times they don't get labelled if I'm traveling or on leave.
Automatically label pull-requests based off filenames 
See https://github.com/actions/labeler to learn more.

housekeeping: automatically label pull-requests

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SolutionTemplate/UnoSolutionTemplate/Shared/App.xaml.cs

GitHub Issue (If applicable): Fixes #28
- Bugfix
1. File -> New "MyApp.Uno"
2. Update to latest pre-release of Uno.* packages
3. Building on WASM and Android results in
```
Error        CS0234        The type or namespace name 'Extensions' does not exist in the namespace 'MyApp.Uno' (are you missing an assembly reference?)        MyApp.Uno.Droid, MyApp.Uno.UWP, MyApp.Uno.Wasm, MyApp.Uno.iOS        C:\code\unoplatform\MyApp.Uno\MyApp.Uno\MyApp.Uno.Shared\App.xaml.cs        32        Active
```
4. Adding `global:: namespace` to ConfigureFilters resolves
```
public App()
{
ConfigureFilters(global::Uno.Extensions.LogExtensionPoint.AmbientLoggerFactory);
this.InitializeComponent();
this.Suspending += OnSuspending;
}
```
4. After adjusting Android, …

fix: ".Uno" in project names results in build errors

---

src/SolutionTemplate/UnoSolutionTemplate/Wasm/UnoQuickStart.Wasm.csproj

- Feature
People need to find the information and do things manually to enable debugging support.
Debugging support is enabled by default.
Opening up pull-request for discussion. Is there any reason why this hasn't been enabled by default? Do we want to ship these specific defaults?

feature: enable wasm debugging by default

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/samples-request.md

Adjusts GitHub -> New Issue templates.
- Added Xamarin.Forms
- Standardized platforms across issue types

housekeeping: adjusted github issue templates

---

src/Uno.UI/Controls/BindableSearchBar.iOS.cs
src/Uno.UI/Controls/BindableUIActivityIndicatorView.iOS.cs
src/Uno.UI/Controls/BindableUIButton.iOS.cs
src/Uno.UI/Controls/BindableUISlider.iOS.cs
src/Uno.UI/Controls/BindableUIView.iOS.cs
src/Uno.UI/Controls/RootViewController.iOS.cs
src/Uno.UI/Controls/UnoNavigationBar.iOS.cs

GitHub Issue (If applicable): Fixes #1430
- Feature
Multiple UIKit controls constructors are currently unsupported
Now possible to utilize additional available base constructors such as:
```csharp
public RootViewController(UIViewController rootViewController)
: base(rootViewController)
```
Successfully built against target framework xamarinios10

#1430 Surface multiple iOS constructors 

---

gitversion.yml

The next version will be bumped to 2.0.512 to compensate for the previous versioning technique introduced for canary testing, which turned out to be removed in favor of azure devops the new public artifacts feeds.

Bump minor version to 2.0.512

---

.github/labeler.yml

GitHub Issue: #1788
- Bugfix
As of now, some of the rules that should enforce automatic assignment of Android, iOS, WASM, build and documentation labels to pull requests are not working. See #1787 
With my fixes, all of the automatic labeling rules work as intended, except on hidden files and folders. From my tests, it looks like the [labeler](https://github.com/actions/labeler) doesn't parse them unless they're specifically mentioned, so if it's important to include hidden folders I can add specific rules for them. I also see from the `.gitignore` that only the `.github` folder is not ignored, so if you wanted I could also add specific rules for that one only (just tell me the desired behavior).
Please check if your PR fulfills the …

Fix the labeling issues with Android, iOS and WASM

---

doc/articles/contributing/guidelines/updating-dependencies.md

There's certain dependencies that are typically safe to update and some that are not. This gets this tribal knowledge down on paper. If you have any to add to the 'potentially incompatible with wasm' list please comment on the PR.

docs: created guidelines for updating dependencies

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.Shared/App.xaml
src/SamplesApp/SamplesApp.UITests/SamplesApp.UITests.csproj
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml/UIElementTests/AppXamlResourcesTests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/ThemeResources/AppXamlDefinedResources.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/ThemeResources/AppXamlDefinedResources.xaml.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs

GitHub Issue (If applicable): fixes #1237
- Bugfix
Static and Theme Resources defined in App.xaml, when defined in an inner `ResourceDictionary` are now discovered and registered properly.
Note that this PR might break the compilation for projects that define duplicate resources in other globally accessible resource dictionaries.

Static resources defined in App.xaml were not processed properly

---

doc/ReleaseNotes/_ReleaseNotes.md
doc/articles/features/working-with-accessibility.md
src/Directory.Build.targets
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Automation/AutomationId_Tests.cs
src/SamplesApp/SamplesApp.Wasm/SamplesApp.Wasm.csproj
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI.Xaml_Automation/AutomationProperties_AutomationId.xaml
src/SamplesApp/UITests.Shared/Windows_UI.Xaml_Automation/AutomationProperties_AutomationId.xaml.cs
src/Uno.UI/FeatureConfiguration.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Automation/AutomationProperties.cs
src/Uno.UI/UI/Xaml/Automation/AutomationProperties.cs
src/Uno.UI/UI/Xaml/FrameworkElementHelper.cs
src/Uno.UI/UI/Xaml/IFrameworkElementImplementation.Android.tt
src/Uno.UI/UI/Xaml/IFrameworkElementImplementation.iOS.tt
src/Uno.UI/UI/Xaml/IFrameworkElementImplementation.macOS.tt
src/nuget.config

Fixes #1798
- Feature
- Adds the support for `AutomationProperties.AutomationId` and related Uno.UITest support for it.
- Updates to latest Uno.UITest which updates to latest Xamarin.UITest and will tentatively fix Android UI Tests instabilities. 

Add support for AutomationProperties.AutomationId

---

README.md

Logo not at the center
logo now at the center position

docs: center logo position in the readme

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs

GitHub Issue (If applicable): Fixes #1870
- Bugfix
Fix NRE when building an app with an empty `Resources` block in `App.xaml`.
Note this cannot yet be automatically tested, but will be able to once the structure for creating samples based on `dotnet new` commands is available.

fix: App.xaml without resources NRE

---

src/Uno.UI/UI/Xaml/Controls/PasswordBox/PasswordBox.cs
src/Uno.UI/UI/Xaml/UIElement.Pointers.cs

+ Fix minor issue where the IsOver is not updated properly
GitHub Issue (If applicable): https://github.com/unoplatform/private/issues/81
- Bugfix
Once the reveal button pressed, the `PasswordNox` never goes back to hidden mode
The password is obfuscated as soon as the pointer is released / goes out of the reveal button

Fix PasswordBox reveal does not toggle back off

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.Droid/Main.cs
src/SamplesApp/SamplesApp.Shared/App.xaml.cs
src/SolutionTemplate/UnoSolutionTemplate/Droid/Main.cs
src/Uno.UI/UI/Xaml/NativeApplication.cs
src/Uno.UWP/Storage/ApplicationData.Android.cs
src/Uno.UWP/Storage/ApplicationDataContainer.Android.cs

Fixes #1741
Fixes https://github.com/unoplatform/uno/issues/1879
- Bugfix
On Android, `ApplicationData.Current.[LocalFolder|RoamingFolder]` throws a NRE exception if accessed in the constructor of App.xaml.cs.
Digging into the current implementation on Android reveals:
https://github.com/unoplatform/uno/blob/master/src/Uno.UWP/Storage/ApplicationDataContainer.Android.cs#L29
Specifically there's a dependency on `ContextHelper.Current`:
```csharp
_preferences = PreferenceManager.GetDefaultSharedPreferences(ContextHelper.Current);
```
and `ContextHelper.Current` isn't populated until an activity is created:
```csharp
protected override void OnLaunched(LaunchActivatedEventArgs e)
{ …
```

fix: ApplicationData.Current.[LocalFolder|RoamingFolder] throws a NRE exception

---

.github/workflows/labeler.yml

Doing this to avoid a long-standing bug in GitHub labeler action, which results in failure for the labeler for PRs from forks: https://github.com/actions/labeler/issues/12

automation: avoid labeling external PRs

---

doc/articles/controls/CommandBar.md
doc/articles/uno-development/Uno-UI-Debugging-Android-Studio.md
doc/articles/uno-development/Uno-UI-Layouting-Android.md
doc/articles/uno-development/Uno-UI-Layouting-iOS.md
doc/articles/uno-development/debugging-inspect-visual-tree.md

GitHub Issue (If applicable): #1893 
- Bugfix
Described in #1893, you can't see images in docs.
Fixed broken paths to images, now, they're visible
closes #1893

fix(articles): fix broken paths to images in .md files

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ButtonTests/UnoSamples_Test_NativeButtons.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Button/Buttons_Native.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Button/Buttons_Native.xaml.cs
src/Uno.UI-Android-only.slnf
src/Uno.UI/UI/Xaml/Controls/Primitives/ButtonBase/ButtonBase.Android.cs
src/Uno.UI/UI/Xaml/Controls/Primitives/ButtonBase/ButtonBase.iOS.cs
src/Uno.UI/UI/Xaml/Controls/ToggleSwitch.cs

GitHub Issue (If applicable): Fixes #1891 
- Bugfix
Native Button and ToggleSwitch templates no longer crash. UI Tests have been added.

Fix native button and ToggleSwitch templates

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.UITests/Constants.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ListViewTests/UnoSamples_Tests.ListView.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_Header_DataContextChanging.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_Header_DataContextChanging.xaml.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/NativeListViewBaseAdapter.Android.cs

GitHub Issue: #1924
- Bugfix
Bindings for views inside `ListView.HeaderTemplate` receive `null` when changing `ListView.Header`.
Bindings for views inside `ListView.HeaderTemplate` don't receive `null` when changing `ListView.Header`.

Fix ContentControl.Content binding in Android ListView Header and Footer

---

build/Uno.UI.nuspec

- Bugfix
Using Uno.UI on an uap 10.0.16299 project now ignores the netstandard 2.0 target properly.

Restore 16299 target in uno.ui.nuspec

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/SourceGenerators/XamlGenerationTests.Core/TestAttachedPropertyOwner.cs
src/SourceGenerators/XamlGenerationTests/AttachedPropertiesTest.xaml

GitHub Issue : fixes #1896
- Bugfix
Nullables types in attached properties causes an exception in XAML file generation.
Handles nullables types in XAML file generator by getting the underlying type for nullable types.

Handles nullables types in XAML file generator

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/TextBlock_TextWrapping_PR1954_EdgeCase.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/TextBlock_TextWrapping_PR1954_EdgeCase.xaml.cs
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.Android.cs

- Bugfix
Currently when the `TextBlock` changes layout to accommodate for the available height, the height measured with the old layout is returned.
The height is recalculated on layout changes.
[AB#164480](https://dev.azure.com/nventive/67eedefd-9293-4f70-a624-89ecbe8ad34f/_workitems/edit/164480)
https://github.com/unoplatform/private/issues/83

fixed a text wrapping issue caused by layout height desync

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/Picker/Picker.iOS.cs

GitHub Issue (If applicable): #2014
- Bugfix
`Picker.SelectedItem` doesn't match what the native picker displays.
`Picker.SelectedItem` matches what the native picker displays.

Fix iOS Picker selection

---

build/ios-uitest-run.sh
src/SamplesApp/SamplesApp.UITests/SampleControlUITestBase.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ButtonTests/UnoSamples_Test_NativeButtons.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ButtonTests/UnoSamples_Tests.Button_Opacity_Automated.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/DatePickerTests/UnoSamples_Tests.DatePicker.cs
src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePickerFlyout.iOS.cs
src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePickerSelector.iOS.cs

- Bugfix
- iOS DatePicker tests are not enabled
- Selecting a date outside of the bounds does not properly reset to the min or max bounds
- The Min and Max dates visual cues are not enabled properly in the native picker
- UI Tests are now enabled
- Selecting a date outside of the bounds clamps to the nearest bound
- Min and Max visual cues are enabled
- Fix for invalid iOS and Android screenshot file names
Internal Issue (If applicable): https://nventive.visualstudio.com/Umbrella/_workitems/edit/163432

[iOS] Enable and Fix DatePicker tests

---

README.md

Build status badges for release branches shows status of `master` instead.
Build status badges for release branches now shows their status correctly
regression from https://github.com/unoplatform/uno/pull/1727

fixed build status badges

---

.azure-devops-android-tests.yml

To build for Android v10 we need to set `6_4_0` bundle in ADO.
It contains Xamarin.Android 10.0 and Mono 6.4.0.
Also need to set .NET Core 3.0.100 to support latest features.
Source: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#mono

Update Xamarin.Android to 10.0 in CI

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml/ContentControlTests/ContentControlBehaviorTests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ContentControlTestsControl/ContentControlNoTemplateNoContent.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ContentControlTestsControl/ContentControlNoTemplateNoContent.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/PolylinePage.xaml.cs
src/Uno.UI/UI/Xaml/Controls/ContentControl/ContentControl.cs

When a ContentControl in the Visual Tree does not have child elements, the dataContext is displayed instead of nothing like on UWP
Now when a ContentControl does not have content, the control will be empty.

Align ContentControl Behavior with UWP behavior for empty children.

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/MediaPlayer/MediaPlayerPresenter.iOS.cs

This was previously fixed for Android, but not iOS. This is repro'ed by the MediaPlayerElement_Stretch_Fill sample.
GitHub Issue (If applicable): #977
- Bugfix

[iOS] Fix NRE from MediaPlayerPresenter when setting Stretch

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs

- Bugfix
Building an Uno app without the Uno.UI.RemoteControl package works.

Fix invalid type resolution for remote control client

---

src/SourceGenerators/Uno.UI.SourceGenerators/RemoteControl/RemoteControlGenerator.cs

- Bugfix
Fix `Uno.UI.RemoteControl` package is now not required in debug configuration.
The scenario will need to be tested with https://github.com/unoplatform/uno/issues/1876

Fix RemoteControl client invalid generation for server endpoints

---

build/ios-uitest-run.sh
src/SamplesApp/SamplesApp.UITests/SampleControlUITestBase.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/VisualState_Tests.cs
src/SamplesApp/UITests.Shared/Windows_UI_Input/VisualStatesTests/Buttons.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Input/VisualStatesTests/Buttons.xaml.cs
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.cs
src/Uno.UI/UI/Xaml/UIElement.wasm.cs

Pressed state of `Hyperlink`
When pressing over an `Hyperlink` (which is not in a `ScrollViewer`), moving pointer out it, and then release the pointer, the `Hyperlink` stays in pressed state.
Pressed state is released.
Fixes https://github.com/unoplatform/private/issues/41
Internal Issue: https://nventive.visualstudio.com/_workitems/edit/159324

Fix Hyperlink stays in pressed state when releasing pointer out

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SourceGenerators/Uno.UI.SourceGenerators/Helpers/RoslynMetadataHelper.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlConstants.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/SourceGenerators/XamlGenerationTests/CreateFromString.xaml
src/SourceGenerators/XamlGenerationTests/CreateFromString.xaml.cs
src/SourceGenerators/XamlGenerationTests/XamlGenerationTests.csproj
src/Uno.UI.Tests/App/Xaml/Test_CreateFromString.xaml
src/Uno.UI.Tests/App/Xaml/Test_CreateFromString.xaml.cs
src/Uno.UI.Tests/Uno.UI.Tests.csproj
src/Uno.UI.Tests/Windows_UI_Xaml/CreateFromStringTests/Given_CreateFromString.cs

GitHub Issue (If applicable): #2039 
*Feature*: Added support for UWP Xaml Type Conversion with CreateFromStringAttribute.
Not much documentation exists for CreateFromStringAttribute but this article explains it nicely:
[https://timheuer.com/blog/implement-type-converter-uwp-winrt-windows-10-xaml](https://timheuer.com/blog/implement-type-converter-uwp-winrt-windows-10-xaml)

Added support for the CreateFromStringAttribute for xaml type conversion

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/VisualState_Tests.cs
src/SamplesApp/UITests.Shared/Windows_UI_Input/VisualStatesTests/Buttons.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Input/VisualStatesTests/ListViewItem.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Input/VisualStatesTests/ListViewItem.xaml.cs
src/Uno.UI/FeatureConfiguration.cs
src/Uno.UI/UI/Xaml/Controls/GridView/GridViewItem.cs
src/Uno.UI/UI/Xaml/Controls/Primitives/SelectorItem.cs
src/Uno.UI/UI/Xaml/ListView/ListViewItem.cs
src/Uno.UI/UI/Xaml/UIElement.Pointers.cs

GitHub Issue: fixes https://github.com/unoplatform/uno/issues/2077
Pressed state of `ListView`
On `ListView` and `GridView` if you press an item, move pointer out, then release the press, the `<List|Grid>ViewItem` state in **pressed** visual state.
Goes back to the **Normal** (or **Selected**) as soon as the pointer goes out of the bounds of the item.

Fix pressed state of ListView items

---

doc/articles/features/routed-events.md
src/Uno.UI/UI/Xaml/Input/PointerRoutedEventArgs.Android.cs

GitHub Issue: fixes https://github.com/unoplatform/uno/issues/1838
Support of Android 5.x devices was broken since pointers refactor
When creating the `PointerPointProperties` in order to fulfill the `PointerUpdaterKind` [we try to use the `ActionButton`](https://github.com/unoplatform/uno/blob/master/src/Uno.UI/UI/Xaml/Input/PointerRoutedEventArgs.Android.cs#L138), which [available only since API 23 (Android 6.0)](https://developer.android.com/reference/android/view/MotionEvent.html#getActionButton())
We don't set the `PointerUpdaterKind`.

Fix pointers support of Android 5.x

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Flyout/FlyoutButtonViewModel.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Flyout/Flyout_ButtonInContent.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Flyout/Flyout_ButtonInContent.xaml.cs
src/Uno.UI/UI/Xaml/Controls/Popup/PopupBase.cs

- Bugfix
When a PopupBase Child has  it's DataContextProperty set to null it is considered a valid value.
Both null and UnsetValue are considered empty values
[164452](https://nventive.visualstudio.com/Umbrella/_workitems/edit/164452)

Fixing DataContext checks in PopupBase

---

.azure-devops-android-tests.yml
.azure-devops-docs.yml
.azure-devops-ios-tests.yml
.azure-devops-macos.yml
.azure-devops-wasm-uitests.yml
.azure-devops-windows.yml
build/android-uitest-build.sh
build/android-uitest-run.sh
build/ios-uitest-run.sh
doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.UITests/RuntimeTests.cs
src/SamplesApp/SamplesApp.UITests/SampleControlUITestBase.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/DatePickerTests/UnoSamples_Tests.DatePicker.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/FlyoutTests/UnoSamples_Tests.Flyout.cs
src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.cs
src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.xaml
src/SamplesApp/SamplesApp.iOS/SamplesApp.iOS.csproj
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/DatePicker/DatePickerFlyout_Automated.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/DatePicker/DatePickerFlyout_Automated.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/DatePicker/DatePickerFlyout_Unloaded.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/DatePicker/DatePickerFlyout_Unloaded.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Flyout/Flyout_Target.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Flyout/Flyout_Target.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Flyout/Flyout_Unloaded.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Flyout/Flyout_Unloaded.xaml.cs
src/Uno.UI.RemoteControl/Uno.UI.RemoteControl.csproj
src/Uno.UI/UI/Xaml/Controls/Button/Button.cs
src/Uno.UI/UI/Xaml/Controls/Popup/PlacementPopupPanel.cs

GitHub Issue (If applicable): fixes #1708 
- Bugfix
- Fixes the initial popup and window resize placement of a flyout
- Fixes flyout should close the button that opened it is closed
- Add test failure screenshot
- Fix android tests should use signed APK

Flyout Fixes, UI Tests stabilization

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/SourceGenerators/XamlGenerationTests/GlobalStaticResources02.xaml

- Bugfix
Using a theme resource in a custom theme builds properly.

Fix invalid error message when using custom themes

---

src/SolutionTemplate/UnoSolutionTemplate/Wasm/UnoQuickStart.Wasm.csproj

the Wasm solution template had a tiny typo, small first PR whilst I get to grips with Uno :)
- Bugfix
When projects are generated via the VSIX extension the Wasm project has a small typo in a comment
Correct spelling :)

corrected a tiny typo in the solution template

---

doc/ReleaseNotes/_ReleaseNotes.md
doc/articles/features/routed-events.md
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml/UIElementTests/UIElementTests.cs
src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/UIElementTests/TransformToVisual_ScrollViewer.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/UIElementTests/TransformToVisual_ScrollViewer.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/UIElementTests/TransformToVisual_Transform.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/UIElementTests/TransformToVisual_Transform.xaml.cs
src/Uno.UI.Wasm/WasmScripts/Uno.UI.d.ts
src/Uno.UI.Wasm/WasmScripts/Uno.UI.js
src/Uno.UI.Wasm/ts/WindowManager.ts
src/Uno.UI.Wasm/tsBindings/WindowManagerScrollToOptionsParams.ts
src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/IScrollContentPresenter.wasm.cs
src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.wasm.cs
src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.wasm.cs
src/Uno.UI/UI/Xaml/UIElement.wasm.cs
src/Uno.UI/UI/Xaml/WindowManagerInterop.wasm.cs
src/Uno.UI/Uno.UI.csproj

GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/2035
Add full support of the `RenderTransform` in the `UIElement.TransformToVisual`
The `UIElement.TransformToVisual` only request the current bounds of the UIElements and makes a diff to get an approximation of the offsetX and offsetY, but does not take in consideration the possible scale in between, nor the rotation.
On WASM this impacts the pointers coordinates as they are [computed from absolute coordinates](https://github.com/unoplatform/uno/blob/master/src/Uno.UI/UI/Xaml/Input/PointerRoutedEventArgs.wasm.cs#L53) and should be "scaled down" in order to remain in the bounds of the control.
The returned transform is now including scale and rotation applied by any parent control.

[WASM] Add full support of RenderTransform in TransformToVisual

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/CheckBoxTests/UnoSamples_CheckBox.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CheckBoxTests/CheckBox_Automated.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CheckBoxTests/CheckBox_Automated.xaml.cs
src/Uno.UI.Tests/Windows_UI_XAML_Controls/CheckBoxTests/Given_CheckBox.cs
src/Uno.UI.Wasm/WasmScripts/Uno.UI.js
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls.Primitives/ToggleButton.cs
src/Uno.UI/UI/Xaml/Controls/Primitives/ToggleButton.cs

GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/2109
- Feature
ToggleButton and derivatives are now supporting Three States mode.

Add support for ToggleButton.IsThreeState and Indeterminate

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Shapes/Shapes_Tests.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/PolygonPage.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/PolygonPage.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/PolylinePage.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/PolylinePage.xaml.cs
src/Uno.UI/UI/Xaml/Shapes/Polygon.cs
src/Uno.UI/UI/Xaml/Shapes/Polyline.cs

Polyline and Polygon was not affecting measurement on parent container when points collection change.
Polyline and Polygon affect measurement on their parent container

Fix missing measurement option for polyline and polygon

---

src/SamplesApp/SamplesApp.UITests/SampleControlUITestBase.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/VisualState_Tests.cs
src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Input/VisualStatesTests/TextBox_VisualStates.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Input/VisualStatesTests/TextBox_VisualStates.xaml.cs
src/Uno.UI/Mixins/Android/VisualStatesMixins.tt
src/Uno.UI/Mixins/Wasm/VisualStatesMixins.tt
src/Uno.UI/Mixins/iOS/VisualStatesMixins.tt
src/Uno.UI/Mixins/macOS/VisualStatesMixins.tt
src/Uno.UI/Mixins/net461/VisualStatesMixins.tt
src/Uno.UI/UI/Xaml/Controls/Button/Button.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.Android.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.iOS.cs
src/Uno.UI/UI/Xaml/Controls/VisualStatesImplementation.tt

GitHub Issue (If applicable): fixes #2021 
Visual states of `TextBox`
The `TextBox` had 2 way to trigger a visual state, one by the generated "VisualStateMixin" which was configured to handle pointer events; and a second directly in the code of the control which handle the *Normal*, *Disabled* and *Focused* states.
When we clicked on a `TextBox` the first logic was enabling the *PointerOver*, then the second was activating the *Focused* state as expected. Then when was the pointer was released, as the first trigger was not aware of the *Focused* state, it was reseting to *Normal*.
All "common states" are managed by the "Visual states mixins"

Merge TextBox "common" visual state handling

---

src/Uno.UI.Tests/Windows_UI_XAML_Controls/GridTests/Given_Grid_And_Min_Max.cs
src/Uno.UI/UI/Xaml/Controls/Grid/Grid.Layout.cs

GitHub Issue (If applicable): Fixes #2125
- Bugfix
The grid computation does not return `-Infinity` when measuring the following xaml:
```
<Grid x:Name="TopNavGrid">
<Grid.ColumnDefinitions>
<ColumnDefinition Width="Auto" />
<ColumnDefinition Width="*" MinWidth="48" />
</Grid.ColumnDefinitions>
<ListView x:Name="TopNavMenuItemsHost" Grid.Column="0">
</ListView>
</Grid>
```
When the child takes the whole width.
No release notes as this feature has not been released stable yet.

Fix invalid Grid layout when using Row/Column MinWidth/MaxHeight

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Shapes/Mesaure_Tests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/MeasurePage.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/MeasurePage.xaml.cs
src/Uno.UI.Wasm/WasmCSS/Uno.UI.css

GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/2111
A visibility collapsed shape may enable the scrolling
SVG elements that are not arranged (like a `Rectangle` used by the "Selected" visual state of a `GridViewItem`) are implicitly measured to 300x150 by web browser (cf. comment in `Uno.UI.css`)
While not arranged, SVG element are forced to be (0, 0).
This was a "regression" introduced by #1726, but which was actually only revealing the real issue.

[WASM] Fix possible invalid scrolling

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TextBoxTests/TextBoxTests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_DeleteButton_Automated.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_DeleteButton_Automated.xaml.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.wasm.cs

GitHub Issue (If applicable): Fixes #2132 
- Bugfix
Tapping on the TextBox clear button on Wasm fails to clear the content of the TextBox.
The original behavior is restored for Wasm, though tapping twice on the button is required. See https://github.com/unoplatform/uno/issues/2138 for more information.
Tests have been added to validated the clear button behavior.

[Wasm] Fix support for TextBox clear button and header focus

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.Android.cs

GitHub Issue (If applicable): fixes #2147
- Bugfix
Settings the `TextBox.ImeOptions` when InputScope is null may fail.

Fix NRE in android-specific TextBox.ImeOptions

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Shapes/Shapes_Tests.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/Clipping/Transform_Ellipse_in_Two_Canvas_in_Grid.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/Clipping/Transform_Ellipse_in_Two_Canvas_in_Grid.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/ImageInStackPanel.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/EllipsePage.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/EllipsePage.xaml.cs
src/Uno.UI/UI/Xaml/Shapes/ArbitraryShapeBase.Android.cs
src/Uno.UI/UI/Xaml/Shapes/ArbitraryShapeBase.cs
src/Uno.UI/UI/Xaml/Shapes/ArbitraryShapeBase.iOSmacOS.cs
src/Uno.UI/UI/Xaml/Shapes/Ellipse.Android.cs
src/Uno.UI/UI/Xaml/Shapes/Ellipse.iOSmacOS.cs
src/Uno.UI/UI/Xaml/Shapes/Ellipse.wasm.cs

Ellipse were not using the `LayoutSlot` to draw itself on any platform.
Instead of trying to calculate the bounds of shape, the LayoutSlot is used to determine the measurements of the ellipse.
- ~~[ ] Updated the [Release Notes](https://github.com/unoplatform/uno/tree/master/doc/ReleaseNotes)~~

Fix ellipse on all platform

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml/FrameworkElementTests/UnoSamples_Test_FrameworkElement.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/FrameworkElementTests/FrameworkElement_NativeLayout.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/FrameworkElementTests/FrameworkElement_NativeLayout.xaml.cs
src/Uno.UI/UI/Xaml/Controls/Layouter/Layouter.cs

GitHub Issue (If applicable): Fixes unoplatform/private#104
- Bugfix
Fixes native elements layout regression introduced in #1726, where native elements may not have size constraints applied properly.

Restore layout constraints in measure for native elements

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TextBoxTests/TextBoxTests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/PasswordBox_Reveal_Scroll.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/PasswordBox_Reveal_Scroll.xaml.cs
src/Uno.UI/UI/Xaml/Controls/PasswordBox/PasswordBox.cs

GitHub Issue (If applicable): fixes #2156
The `PasswordBox` might stay in reveal state when used in a `ScrollViewer`
When a `PasswordBox` is used in a `ScrollViewer`, if you press the reveal button with a finger or a pen, move the pointer up / down far enough to trigger the scroll, and then release the pointer, the password remain visible.
The password is hidden as soon as the scroll starts

Fix reveal of PasswordBox in ScrollViewer

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_FrameworkElement.cs
src/Uno.UI/UI/Xaml/Controls/Layouter/Layouter.cs

GitHub Issue (If applicable): unoplatform/private#93
- Bugfix
Restores the ability for a FrameworkElement to measure its children using `[NaN;NaN]` on Android.

[Android] Fix MeasureOverride taking NaN;Nan is input failure

---

src/Uno.UI/UI/Xaml/Controls/Layouter/Layouter.cs

Layouter measure exception give little or no context about the problematic control:
> without `x:Name`: [.Layouter] Invalid measured size ... 
> with `x:Name`: [BarPath.Layouter] Invalid measured size ... (note: there is no such class...)
The type name and `x:Name` (if there is) of the control breaking the `MeasureOverride(size)` are in the exception message.
With recent changes related to clipping, we saw a large number of `Layouter` crashes happening. However, the exception message often itself lack the pertinent info to help pinpoint the origin of exception, requiring one to nuget override just …

minor cosmetic fix for Layouter.ToString()

---

src/Uno.UI.Wasm/WasmScripts/Uno.UI.js
src/Uno.UI.Wasm/ts/WindowManager.ts

GitHub Issue (If applicable): fixes https://github.com/unoplatform/private/issues/106
Text might be wrapped
In some unclear circumstances, the width return by a chromium based browser for text measure is 1 pixel lower than the effective width needed to render the text. The result is that the text content will wrap, even if we already add half a pixel to the width.
Instead of adding half a pixel to the width on each measure text, we now add a full pixel.
This bug was present since a while, but was hidden by the aggressive clipping that was removed by https://github.com/unoplatform/uno/pull/1726

Fix possible invalid text wrapping on WASM in Chromium based browsers

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.wasm.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.wasm.cs
src/Uno.UI/UI/Xaml/Documents/UIElementTextHelper.wasm.cs

GitHub Issue (If applicable): fixes #2181, fixes #2185
- Bugfix
The TextBlock properties synchronization to the native HtmlParagraph are done synchronously, and the measure pass is performed a dispatcher loop later. This creates a window where the textblock properties are desynchronized, and shows an invalid resizing visual effect.
TextBlock properties update in fast path (without inlines at this time) are delayed and applied during the measure phase, removing the invalid state that can appear visually.
**Note:** This update only delays the application of the properties, and while a performance improvement may be visible, most of the updates invocations to javascript could be batched into a single call that applies differences in html styles. …

[Wasm] Move textblock updates to measure phase

---

build/ios-uitest-run.sh
src/SamplesApp/SamplesApp.UITests/QueryExtensions.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TextBlockTests/TextBlockTests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/TextBlock_Foreground_While_Collapsed.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/TextBlock_Foreground_While_Collapsed.xaml.cs
src/Uno.UI/UI/Xaml/UIElement.iOS.cs

Calling this method instead of SetNeedsLayout means that OnInvalidateMeasure() is called for types that override it.
This fixes a bug introduced by #1726 (somehow) whereby changing TextBlock.Foreground and setting the TextBlock to Collapsed in the same synchronous pass would not result in the new Foreground showing when the TextBlock was made visible again.
GitHub Issue (If applicable): fixes #2162 

[iOS] Call UIElement.InvalidateMeasure() when Visibility changes

---

build/Uno.UI.Build.csproj
doc/qa/remotecontrol-qa.md
src/Uno.UI-iOS-hotreload-vsix-only.slnf
src/Uno.UI.RemoteControl.VS/EntryPoint.cs
src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.cs
src/Uno.UI.RemoteControl/LinkerDefinition.Xamarin.xml
src/Uno.UI.RemoteControl/Uno.UI.RemoteControl.csproj

- Bugfix
- Fix XAML Hot Reload not working in projects located in solution folders
- Fix possible null reference for solution folders
- Start the RC server early for android and iOS projects
- Fix template-less ContentControl control lookup
- Fix linker issue for RC client

[VSIX] Fix Folder recursion to apply port properties

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UWP/Graphics/Display/DisplayInformation.Android.cs

GitHub Issue (If applicable): #2230 
- Bugfix
Memory leaks when `DisplayInformation` properties are re-initialized
Memory no longer leaks when `DisplayInformation` properties are re-initialized

Fix memory leaks in Android DisplayInformation

---

build/ios-uitest-run.sh
src/SamplesApp/SamplesApp.UITests/QueryExtensions.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Media/Animation_Tests/SequentialAnimations_Tests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/Animation/SequentialAnimationsPage.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/Animation/SequentialAnimationsPage.xaml.cs
src/Uno.UI/Extensions/TimelineExtensions.iOS.cs

GitHub Issue (If applicable): #2148 
Bugfix
iOS has an animation crash when animating an element in code-behind, with a target property such as ((UIElement.RenderTransform).(TranslateTransform.X))
No crash on iOS, the target property is retrieved correctly.

Applied a fix for an animation crash on iOS

---

src/Uno.UWP/System/Launcher.cs

GitHub Issue (If applicable): fixes #2239 
- Bugfix
Fixes a binary breaking change introduced because of a missing check in https://github.com/unoplatform/Uno.PackageDiff/pull/6. 
Will need to be adjusted when addressing https://github.com/unoplatform/uno/issues/2240

Restore original signature for Launcher.LaunchUriAsync

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.Wasm/ts/CoreDispatcher.ts

- Bugfix
Running a WebAssembly application on Safari for macOS or iOS automatically adds 5 second arbitrary delay to work around stack size issues using the interpreter.
See https://github.com/mono/mono/issues/12357

Add arbitrary delay in Safari macOS to avoid StackOverflow issues

---

build/ios-uitest-run.sh
doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ControlTests/Control_Tests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ControlTests/Control_IsEnabled_Inheritance.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ControlTests/Control_IsEnabled_Inheritance.xaml.cs
src/Uno.UI/UI/Xaml/FrameworkElement.Interface.wasm.cs

Remove coercion on IsEnabled. In the best case, this coercion wasn't doing anything:
- if there was no value set at a higher precedence, it was just &&-ing the new value with itself
- if IsEnabled was already set 'false' at a higher precedence, the coercion was unnecessary because the existing value would still take precedence
In the worst case it was preventing IsEnabled ever being set to true:
- if a control is materialized with IsEnabled=False, and then put in the tree with a parent with IsEnabled=True, then on entering the tree the coercion callback would set False with precedence Coercion. Since this is the highest precedence, setting IsEnabled=true locally on the control will now have no effect.
- Bugfix …

[WASM] Fix Control can't be re-enabled

---

doc/articles/debugging-wasm.md

Added an additional tip for debugging with Chrome

Added additional tip for debugging with Chrome

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SourceGenerators/Uno.UI.SourceGenerators/Helpers/SymbolExtensions.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlConstants.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/SourceGenerators/XamlGenerationTests/NamedColorsTest.xaml
src/SourceGenerators/XamlGenerationTests/XamlGenerationTests.csproj

GitHub Issue (If applicable): #2227
- Bugfix
The xaml source generation doesn't properly handle literal values for `Color` and `SolidColorBrush` which is accepted by uwp.
The xaml source generation should handle literal values for `Color` and `SolidColorBrush` properly.

Add support for XAML literal Color and SolidColorBrush

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.Wasm/WasmScripts/Uno.UI.d.ts
src/Uno.UI.Wasm/WasmScripts/Uno.UI.js
src/Uno.UI.Wasm/ts/WindowManager.ts
src/Uno.UI/Helpers/Automation.wasm.cs
src/Uno.UI/UI/Xaml/IFrameworkElementImplementation.iOS.tt
src/Uno.UI/UI/Xaml/IFrameworkElementImplementation.macOS.tt
src/Uno.UI/UI/Xaml/UIElement.Android.cs
src/Uno.UI/UI/Xaml/UIElement.cs

- Feature
Adds the ability for Uno.UITest to set `DependencyProperty` values.
Testing will be included in TBD

Add support for Automation SetDependencyPropertyValue

---

.azure-devops-ios-tests.yml
build/ios-uitest-run.sh
src/Directory.Build.targets
src/SamplesApp/SamplesApp.UITests.Generator/SnapShotTestGenerator.cs
src/SamplesApp/SamplesApp.UITests/SampleControlUITestBase.cs
src/SamplesApp/SamplesApp.UITests/TestFramework/TestAppMode.cs
src/SamplesApp/SamplesApp.UITests/Toolkit/UnoSamples_Tests.Elevation.cs
src/SamplesApp/SamplesApp.UITests/Windows_Devices/GyrometerTests.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Automation/AutomationId_Tests.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/FlyoutTests/UnoSamples_Tests.Flyout.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ListViewTests/UnoSamples_Tests.ListView.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ToggleSwitchTests/UnoSamples_Tests.ToggleSwitch.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/Capture_Tests.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/DragCoordinates_Tests.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/EventSequence_Tests.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/Manipulation_Tests.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/VisualState_Tests.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/UIElementTests/TransformToVisual_ScrollViewer.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_CacheLength_Slow_Load.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Progress/ProgressRing.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/Transform/Transformed_Ancestor_And_UI_Blocked.xaml.cs
src/Uno.UI.TestComparer/Comparer/TestFilesComparer.cs
src/Uno.UI.TestComparer/Program.cs
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.iOS.cs
src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml

Fixes #2051
- Bugfix
- [iOS] Fix NRE in TextBlock
- Disable time-dependent screenshots
- Add missing XamlDefaultComboBox
- Restore iOS Snapshot tests, split in two groups for build performance
- Disable PR comment posting for PR from forks
- Restore missing AutoRetry attribute on tests
- Update to latest bootstrapper
- Fix Image decoding for iOS in test comparer

Restore iOS Snapshot Tests

---

.azure-devops-ios-tests.yml
src/Uno.UI.TestComparer/Comparer/TestFilesComparer.cs

- Bugfix
iOS images weigh 85MB, which impacts the available memory on hosted agents. Force GC collections after every comparison.
**WARNING** This PR disables the support for iOS ui testing until it is restored with a newer Xamarin.UITest package.

Allocate less during image comparison

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/UIElementTests/UIElement_Layout_Constrains.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/UIElementTests/UIElement_Layout_Constrains.xaml.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_FrameworkElement.cs
src/Uno.UI/UI/Xaml/Controls/Layouter/Layouter.cs
src/Uno.UI/UI/Xaml/FrameworkElement.Layout.wasm.cs

This is to align with the UWP/WinUI behavior.
The Width/MinWidth restrictions are applied by the control itself,
not the layouting process.
The `Layouter` (and the equivalent for Wasm) was applying the `minSize` (calculated from `Width`, `MinWidth`, `Height`, `MinHeight`) on the `availableSize` during the `Arrange()` phase.
This was allowing the `availableSize` to grow when smaller than `minSize`.
The `availableSize` passed to the `ArrangeOverride()` of a control won't apply the `minSize` anymore.
* https://nventive.visualstudio.com/Umbrella/_workitems/edit/168813 (this is the reference for the sample)
* https://nventive.visualstudio.com/Umbrella/_workitems/edit/1688 …

Remove "min size" constrains to available size in layouter

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UWP/UI/Composition/CoreAnimation.iOS.cs

Animation might run twice
When we start a native animation on iOS, we also start a managed faked animation which only updates the target DP. For some unknown (?!) reasons, the 2 animations might become out-of sync, resulting in a double animation (first the managed, then the native). After investigation, this is because the native animation starts with a delay.
Apparently on iOS each layer might have its own "relative time", and when we configure the `BeginTime` we used a kind-of absolute time. 
We know don't set the `BegingTime` when not needed (avoids useless interop), and if needed, we make sure to convert the absolute time to the target layer's relative time.
Internal Issue: …

[iOS] Fix animation might run twice

---

src/Uno.UI.Wasm/ts/WindowManager.ts
src/Uno.UI/Helpers/Automation.wasm.cs
src/Uno.UI/UI/Xaml/IFrameworkElementImplementation.iOS.tt
src/Uno.UI/UI/Xaml/IFrameworkElementImplementation.macOS.tt
src/Uno.UI/UI/Xaml/UIElement.Android.cs
src/Uno.UI/UI/Xaml/UIElement.cs

- Bugfix
The signature of the `SetDependencyProperty` method was chosen to work around a limitation of Xamarin.UITest with regards to parameters passing on iOS, where the number of parameters follows a unconventional set of rules.
Using a single parameter with a simple delimitation format fits all platforms with little overhead.
Tests will be coming with a Uno.UITest package update.

Adjust the SetDependencyPropertyValue backdoor signature

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/CanvasTests/Canvas_Measurement_Tests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Canvas/Canvas_ZIndex.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Canvas/Canvas_ZIndex.xaml.cs
src/Uno.UI/UI/Xaml/Controls/Canvas/Canvas.Android.cs
src/Uno.UI/UI/Xaml/Controls/Canvas/Canvas.Layout.cs
src/Uno.UI/UI/Xaml/Controls/Canvas/Canvas.cs
src/Uno.UI/UI/Xaml/UIElement.Android.cs

Previous implementation of Canvas.ZIndex was calling View.SetZ(), which affects draw order but also applies a shadow effect (though only for Controls for some reason - perhaps because they're doing funky stuff with ViewOutlineProvider). Switch to use GetChildDrawingOrder() instead.
- Bugfix

[Android] Fix bug where Canvas.ZIndex applies shadow

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/Uno.UI.Tests/App/Xaml/Test_CreateFromString.xaml
src/Uno.UI.Tests/App/Xaml/Test_CreateFromString.xaml.cs
src/Uno.UI.Tests/Windows_UI_Xaml/CreateFromStringTests/Given_CreateFromString.cs

Added support for handling strings from a StaticResource when performing xaml type conversions using CreateFromStringAttribute
GitHub Issue (If applicable): #2039
- Bugfix
Specifying a string from a StaticResource wasn't implemented
The conversion function for CreateFromStringAttribute will now be able to handle a string value from a StaticResource

Handling strings from a StaticResource for CreateFromStringAttribute

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/CanvasTests/Canvas_Measurement_Tests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Core/SetCursor.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Core/SetCursor.xaml.cs
src/Uno.UI.Wasm/ts/WindowManager.ts
src/Uno.UWP/UI/Core/CoreCursorTypeExtensions.wasm.cs
src/Uno.UWP/UI/Core/CoreWindow.cs
src/Uno.UWP/UI/Core/CoreWindow.wasm.cs

New version of https://github.com/unoplatform/uno/pull/629
Rebased the excellent PR from @Firefly74940.
Implemented the `Window.Current.CoreWindow.PointerCursor` on Wasm

Wasm "Set Cursor"

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.Shared/App.xaml.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml/UIElementTests/UIElementTests.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/CanvasTests/Canvas_Measurement_Tests.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ContentDialog/UnoSamples_Tests.ContentDialog.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/CommandBar_Examples.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/DateTimePicker/DateTimePicker.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TimePicker/Sample1.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TimePicker/Sample2.xaml.cs
src/Uno.UI/FeatureConfiguration.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/NativeListViewBase.Android.cs
src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.Android.cs

- Feature
- Adds support for `FeatureConfiguration.ScrollViewer.AndroidScrollbarFadeDelay`
- Remove more screenshots for changing tests
Needs #2293 to be merged.

Adds support for FeatureConfiguration.ScrollViewer.AndroidScrollbarFadeDelay

---

.azure-devops-wasm-uitests.yml

This reduces the number of storage calls (> 14K as of this commit) which can be very slow.
Images won't be accessible from the artifacts view, but are still accessible from the test results in the ADO web interface.

Zip test results before publishing the artifacts

---

src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.iOS.cs

Possible null-ref in `TextBVlock`
For some reason the `TextBlock` might invoke the `LayoutTypography` before the `UpdateTypography` has been invoked (for instance if a `TextBlock` is arranged while the measure was bypassed). In that case the null-ref is raised in the `LayoutTypography`.
We check if fields are still `null` before using them ...
This PR is an enhancement of https://github.com/unoplatform/uno/commit/149eb9ae192444e55892d0e4c8cfef4557c565e2 (Bug: https://github.com/unoplatform/uno/issues/2051).
Combined with a fix in `Image` which also prevent a null-ref in [`UpdateLayerRect` where the `Image` property can be null](https://github.com/unoplatform/uno/commit/cfcf58fd0e8496598adce28f113b03e3a4b8f80a#diff-de5d4ca4935e2e3 …

Fix possible null-ref in TextBlock

---

src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.iOS.cs

`TextBlock` might stay blank
Since https://github.com/unoplatform/uno/pull/2312 `TextBlock` might stay blank
`TextBlock` appears
This is an enhancement of https://github.com/unoplatform/uno/pull/2312, same comment applies for UI tests.
Internal Issue: https://dev.azure.com/nventive/_workitems/edit/168675

Fix TextBlock might stay blank

---

src/Uno.UI/UI/Xaml/Shapes/ArbitraryShapeBase.iOSmacOS.cs

GitHub Issue (If applicable): #2140
Application using `<Path>` was crashing on iOS 11
Works fine.

Fixed possible Nan/Infinity measurement on iOS 11

---

src/Directory.Build.targets
src/SamplesApp/SamplesApp.UITests/SampleControlUITestBase.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ImageTests/UnoSamples_Tests.Image.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/Image_Stretch_Alignment_SizeOnControl.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/Image_Stretch_Alignment_SizeOnControl.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/Image_Stretch_Alignment_Smaller.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/Image_Stretch_Modes_Picker.xaml.cs
src/Uno.Foundation/Point.cs
src/Uno.Foundation/Rect.cs
src/Uno.Foundation/Size.cs
src/Uno.UI.Tests/Windows_UI_XAML_Controls/ImageTests/Given_ImageSizeHelper.cs
src/Uno.UI/UI/LayoutHelper.cs
src/Uno.UI/UI/Xaml/Controls/Image/Image.Android.cs
src/Uno.UI/UI/Xaml/Controls/Image/Image.cs
src/Uno.UI/UI/Xaml/Controls/Image/Image.iOS.cs
src/Uno.UI/UI/Xaml/Controls/Image/Image.wasm.cs
src/Uno.UI/UI/Xaml/Controls/Image/ImageSizeHelper.cs
src/Uno.UI/UI/Xaml/Controls/MediaPlayer/MediaPlayerPresenter.cs
src/Uno.UI/UI/Xaml/UIElement.iOS.cs

On iOS, when a size restriction (`MinWidth`, `Width`, `MaxWidth`, `MinHeight`, `Height` or `MaxHeight`) were specified directly on the `<Image />` tag itself, the result alignment were wrong.
Behave like UWP and the same way as when the constraints is applied on a parent element.
- #2311
- #2295
- https://dev.azure.com/nventive/Umbrella/_workitems/edit/170280
- https://dev.azure.com/nventive/Umbrella/_workitems/edit/168856

iOS image alignment were incorrect when size was specified directly on the <Image> control

---

src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/Uniform100x100.xaml
src/Uno.UI/UI/Xaml/Controls/Image/Image.Android.cs

- Bugfix
Images may not load properly when cached.
Update the loading of cached images, after the layout passes changes in #2316 and #2252.
UI Tests in `src\SamplesApp\UITests.Shared\Windows_UI_Xaml_Controls\ImageTests\UniformToFill100x100.xaml` and `src\SamplesApp\UITests.Shared\Windows_UI_Xaml_Controls\ImageTests\Uniform100x100.xaml` were not reloading if the image was already cached.

[Android] Adjust for synchronous image loading

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/Uno.UI.Tests/App/Xaml/Test_CreateFromString.xaml
src/Uno.UI.Tests/App/Xaml/Test_CreateFromString.xaml.cs
src/Uno.UI.Tests/App/Xaml/Test_Dictionary.xaml
src/Uno.UI.Tests/Windows_UI_Xaml/CreateFromStringTests/Given_CreateFromString.cs

GitHub Issue (If applicable): #2039
- Feature
CreateFromStringAttribute supports Xaml Type conversions using string values or local StaticResources, but not global StaticResources (ex: App.xaml).
CreateFromStringAttribute should support all three cases: string values, local StaticResources, as well as global StaticResources.

Applied a change to also support global StaticResources

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/Image_Margin.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/Image_Margin.xaml.cs
src/Uno.UI/UI/Xaml/Controls/Layouter/Layouter.cs

- Bugfix
Fix regression when applying a margin on an Image control on iOS.

[iOS] Fix double margin on Image

---

src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs

In some cases when inserting a `TextBox` in the visual tree while already data-bound to a VM, the `TextBox` will push an empty string when initializing its template, **BUT** will still keep the value initial value visible. This is because we init the unfocused state.
It updates the binding on focus lost, only it it's not due to template init.
Internal Issue: https://dev.azure.com/nventive/_workitems/edit/167304

Fix TextBox might erase prefilled value

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Button/Button_IsEnabled.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/Image_Margin.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/Image_Margin.xaml.cs
src/Uno.UI/UI/Xaml/Controls/Image/Image.iOS.cs
src/Uno.UI/UI/Xaml/Controls/Layouter/Layouter.cs

- Bugfix
Fixed sized image may apply margin to already constrained size, resulting in an image smaller that it should.

[iOS] Fix margin constraint applied to fixed sized Image control

---

src/SamplesApp/SamplesApp.Shared/App.xaml.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_Margin_On_Container.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_Margin_On_Container.xaml.cs
src/SolutionTemplate/UnoSolutionTemplate/Shared/App.xaml.cs
src/Uno.UI/Extensions/CGSizeExtensions.iOSmacOS.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBaseSource.iOS.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.iOS.cs
src/Uno.UI/UI/Xaml/FrameworkElement.iOS.cs

When a view requires measure in LayoutSubviews(), add its Margin to its Bounds to determine the available size. This fixes a bug where the contents of a ListViewItem could be squished by the size of its Margin.
This is required because of recent changes where Margin is handled by views themselves, rather than their parent layouter.
It probably manifests itself in the case of ListViewItem because (a) its parent is a non-Uno view and/or because (b) the ListView intercepts layout requests, so only a portion of the view tree gets rearranged.
GitHub Issue (If applicable): fixes #2339, fixes #2188 
- Bugfix

[iOS] Fix bug with ListViewItem.Margin application

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/WebView/WebView_Animated_Opacity.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/WebView/WebView_Animated_Opacity.xaml.cs
src/Uno.UI/UI/Xaml/Controls/WebView/WebView.Android.cs

Force WebView to always clip its child (namely, the inner native WebView).
GitHub Issue (If applicable): fixes #2006
- Bugfix

[Android] Fix WebView clipping issue

---

src/Uno.UWP/System/Launcher.cs

- Bugfix
Fixed LaunchUriAsync fails on Wasm.
This kind of code cannot yet be validated because of the opening of an external tab. Will need to be adjusted once threading support is enabled (https://github.com/unoplatform/uno/issues/2302).

[Wasm] Fix LaunchUriAsync should not validate dispatcher

---

src/Uno.UI/Controls/BindableDrawerLayout.Android.cs

When using `<BindableDrawerLayout />` (native Android control), the `Pane` is measured at a wrong size (but the arrange is correct). This could lead to strange result when the `desiredSize` is used in the layouting logic.  This could happen with the following XAML code is used in the `Pane`:
``` xml
<ContentControl>
<StackPanel Orientation="Horizontal" HorizontalAlignment="Center">
<Image Width="150" Height="150" />
<TextBlock Text="Some text..." />
</StackPanel>
</ContentControl>
```
The _arrange size_ of the `<StackPanel>` will be `100px`, leading to a clipping of its content.
The content of the `<StackPanel>` shouldn't be clipped when the `LeftPaneOpenLength` is enough for its content.

Fix problem with Measure size in DrawerLayout's Pane

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/documentation-request.md
.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/samples-request.md

GitHub Issue (If applicable): #2427
- Other... GitHub templates
GitHub templates don't include macOS
GitHub templates include macOS

Added macOS to GitHub issue templates

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Data/UpdateSourceTrigger.cs

GitHub Issue (If applicable): #2033 
- Bugfix
Compile errors when referencing the 'LostFocus' Attribute of the UpdateSourceTrigger Enum.
The LostFocus Attribute of the UpdateSourceTrigger Enum can be used as expected without errors.

Add Missing LostFocus Value to UpdateSourceTrigger

---

src/AddIns/Uno.UI.Lottie/Uno.UI.Lottie.csproj
src/SourceGenerators/Uno.UI.SourceGenerators/Uno.UI.SourceGenerators.csproj
src/SourceGenerators/Uno.UI.Tasks/Uno.UI.Tasks.csproj
src/Uno.UI.Maps/Uno.UI.Maps.csproj
src/Uno.UI.Toolkit/Uno.UI.Toolkit.csproj
src/Uno.UI.Wasm/Uno.UI.Wasm.csproj
src/Uno.UI.WpfHost/Uno.UI.WpfHost.csproj

https://dev.azure.com/nventive/Umbrella/_workitems/edit/169052
- Bugfix
Debugging Uno on a project does not work because the xbf files are not generated when building Uno
The xbf files are generated.

Fix xbf files generation

---

build/PackageDiffIgnore.xml
doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_ProportionalPanel.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_ProportionalPanel.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ProportionalPanel.cs
src/Uno.UI/UI/Xaml/Controls/ItemsStackPanel/ItemsStackPanelLayout.iOS.cs
src/Uno.UI/UI/Xaml/Controls/ItemsWrapGrid/ItemsWrapGridLayout.iOS.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBaseSource.iOS.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.iOS.cs

When measuring the unbound template of the list, supply the actual available breadth (rather than infinity), as some panels rely on it to measure themselves correctly.
GitHub Issue (If applicable): fixes #2361
- Bugfix

[iOS] Fix ListView children measured with infinite breadth

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/TextBlock_Layout.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/TextBlock_Layout.xaml.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.cs
src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.iOS.cs

GitHub Issue: https://github.com/unoplatform/uno/issues/2358
Putting a TextBlock into a list were creating extra spacing.
The bug was caused by a double application of a margin in the `ScrollContentPresenter`.
The margin needs to be applied only on non-managed (native) controls.
Internal issues:
* https://nventive.visualstudio.com/Umbrella/_workitems/edit/169216

[iOS] ScrollViewer was uselessly applying its content's margin

---

src/SamplesApp/SamplesApp.UITests/FileInfoExtensions.cs
src/SamplesApp/SamplesApp.UITests/SampleControlUITestBase.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TextBoxTests/TextBoxTests.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_IsReadOnly.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_IsReadOnly.xaml.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.wasm.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.wasm.cs

GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/2408
Using `IsReadOnly` were not working when set directly in XAML.
The `readonly` _html attribute_ were not (re)applied after the `OnApplyTemplate()`, causing this bug.
`IsReadOnly` and `IsEnabled` has been unified to use the same patterns.

[WASM] IsReadOnly was not working when set directly in XAML

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml/UIElementTests/UIElementTests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/UIElementTests/NativeView.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/UIElementTests/UIElement_Native_Child.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/UIElementTests/UIElement_Native_Child.xaml.cs
src/Uno.UI/Extensions/ViewExtensions.Android.cs
src/Uno.UI/FeatureConfiguration.cs
src/Uno.UI/UI/Xaml/UIElement.Android.cs

Native Android views typically expect to be clipped, and display incorrectly otherwise. Ensure they're always clipped.
This allows native controls defined outside the framework to display correctly without additional adjustments.
- Bugfix
Internal Issue (If applicable): https://github.com/unoplatform/private/issues/117

[Android] Always clip non-UIElements

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/Picker/Picker.iOS.cs

Don't call Select() to change the spinner selection when there are no Items present. This avoids a crash under certain hard-to-reproduce circumstances with the following error:
```
Exception Type:  EXC_BAD_ACCESS (SIGKILL)
Exception Subtype: KERN_INVALID_ADDRESS at 0xfffffffffffffffc
...
Thread 0 Crashed:
0   UIKitCore                      0x00000001b3d932e8 0x1b3147000 + 12894952
1   UIKitCore                      0x00000001b3d98770 0x1b3147000 + 12916592
2   UIKitCore                      0x00000001b3d98770 0x1b3147000 + 12916592
3   UIKitCore                      0x00000001b3d99fcc 0x1b3147000 + 12922828
4   UIKitCore                      0x00000001b3d5887c 0x1b3147000 + 12654716
5   UIKitCore                      0x00000001b3d5874c 0x1b3147000 + 12654412
6   UIKitCore …
```

[iOS] Fix Picker crash

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.Wasm/ts/Windows/Storage/StorageFolder.ts

- Bugfix
Fail gracefully if IDBFS support is not enabled in emscripten.

Add fallback condition if IDBFS is not available

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UWP/ApplicationModel/DesignMode.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel/DesignMode.cs

GitHub Issue (If applicable): #2506 
- Bugfix
`DesignMode2Enabled` throws.
`DesignMode2Enabled` always returns `false`

Support DesignMode2Enabled

---

doc/ReleaseNotes/_ReleaseNotes.md
doc/articles/features/windows-system.md
src/Uno.UWP/Generated/3.0.0.0/Windows.System/Launcher.cs
src/Uno.UWP/System/Launcher.cs
src/Uno.UWP/System/Launcher.iOSmacOS.cs
src/Uno.UWP/System/Launcher.macOS.SpecialUris.cs

GitHub Issue (If applicable): #2499
- Feature
Launcher API is not supported on macOS.
Launcher API is supported on macOS and on par with iOS/Android. Includes support for Query and many special preference URIs.

Support for Windows.System.Launcher on macOS

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.UITests/TestFramework/ImageAssert.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Media/Transform_Tests/Basics_Automated.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/Transform/Basics_Automated.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/Transform/Basics_Automated.xaml.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Media/TransformGroup.cs
src/Uno.UI/UI/Xaml/Media/Transform.cs
src/Uno.UI/UI/Xaml/Media/TransformGroup.cs

GitHub Issue: fixes https://github.com/unoplatform/uno/issues/2513
`TransformGroup` are not working
When the `Children` collection of `TransfromGroup` is updated, it invokes the base `Transform.NotifyChanged()` but this won't update the `MatrixCore`.
`MatrixCore` is now updated by the `NotifyChanged()`.

Fix TransformGroup

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.UITests/TestFramework/ImageAssert.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/BorderTests/Border_Tests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/BorderTests/Border_CornerRadius_Toggle.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/BorderTests/Border_CornerRadius_Toggle.xaml.cs
src/Uno.UI/UI/Xaml/Controls/BorderLayerRenderer.Android.cs

When calculating the fill path for a control with a non-zero CornerRadius, ensure to adjust the fill area for the BorderThickness. This adjustment was erroneously removed when CornerRadius handling was refactored in #2190.
GitHub Issue (If applicable): fixes #2263
- Bugfix

[Android] BorderLayerRenderer - restore BorderThickness adjustment

---

build/ci/.azure-devops-windows.yml

Tentative workaround for https://developercommunity.visualstudio.com/content/problem/891803/vstestconsoleadapter-fails-with-outofmemory.html?childToView=896206#comment-896206

Apply workaround for CI VSTest out of memory

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_ViewManagement/IsScreenCaptureEnabledTests.xaml
src/SamplesApp/UITests.Shared/Windows_UI_ViewManagement/IsScreenCaptureEnabledTests.xaml.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.UI.ViewManagement/ApplicationView.cs
src/Uno.UWP/UI/ViewManagement/ApplicationView.Android.cs

GitHub Issue (If applicable): #2524 
- Feature
`IsScreenCaptureEnabled` is not supported.
`IsScreenCaptureEnabled` is supported on Android.

[Android] Added support for IsScreenCaptureEnabled

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TextBoxTests/TextBoxTests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_Formatting_Flicker.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_Formatting_Flicker.xaml.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.Overrides.Android.cs

- Bugfix
We have a custom attached property for `TextBox` that adds an `IInputFilter` and hooks on `TextChanged` to apply custom constraint and formatting to the text. With a `MaxLength` set and `InputScope="Number"`, upon reaching max length, the text would flicker/toggle between "(12345)" and "12345" as you type.
No flickering.
https://nventive.visualstudio.com/Umbrella/_workitems/edit/164249 (issue 1 of 2)
https://github.com/unoplatform/private/issues/116

fixed TextBox.Text flickering when using custom IInputFilter with MaxLength set

---

build/ios-uitest-run.sh
doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.UITests/QueryExtensions.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TextBoxTests/TextBoxTests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_Binding_Null.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_Binding_Null.xaml.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs

GitHub Issue (If applicable): fixes #2294
Upon losing focus, only push a new value to the two-way binding if user edits have occurred, in alignment with UWP behavior. This avoids overwriting null with an empty string if the user focuses and then defocuses the TextBox.
- Bugfix

TextBox - only update binding after edits, fix iOS UI tests whitelist

---

build/ci/.azure-devops-android-tests.yml
build/ci/.azure-devops-ios-tests.yml
build/ios-uitest-run.sh
src/SamplesApp/SamplesApp.UITests.Generator/SnapShotTestGenerator.cs
src/SamplesApp/SamplesApp.UITests/TestFramework/ImageAssert.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/PopupTests/UnoSamples_Popup_Simple_Tests.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Media_Animation/DoubleAnimation_Tests.FinalState_Opacity.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Media_Animation/DoubleAnimation_Tests.FinalState_Transforms.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media_Animation/DoubleAnimation_FinalState_Opacity.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media_Animation/DoubleAnimation_FinalState_Opacity.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media_Animation/DoubleAnimation_FinalState_Transforms.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media_Animation/DoubleAnimation_FinalState_Transforms.xaml.cs
src/Uno.UWP/UI/Composition/CoreAnimation.iOS.cs

This fixes a regression introduced by https://github.com/unoplatform/uno/pull/2532 and invalidates the revert did in https://github.com/unoplatform/uno/pull/2543
Animations are not reaching their final state
In order to prevent any conflict between animations, in `animation<Started|Completed>` events we are validating that the animation that raises the callback is indeed the current animation.
The issue is that this comparison is achieved by comparing managed instance of proxy to native objects, and those proxies might change under certain circumstances (to determine)
We make sure to capture the managed animation instance in the event handler, so we are able to properly compare it with the "current" when the events are raised.

Fix animations are not reaching their final state on iOS

---

src/Uno.UWP/UI/Composition/CoreAnimation.iOS.cs

Prevent flicker of animation on iOS when animating multiple properties of the same target
At the end of a storyboard that animates multiple properties of a `Transform`, we can notice a flicker
No flicker
Fixes regression introduced by https://github.com/unoplatform/uno/pull/2532

Prevent flicker of animation on iOS 

---

src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/Input_InputScope_Number.xaml

- Other: Sample
The "TextBox -> Input_InputScope_Number" sample doesn't have `InputScope` assigned.
Added `InputScope=Number` to the sample.

fixed sample for TextBox InputScope=Number

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.UITests/TestFramework/ImageAssert.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TextBlockTests/TextBlockTests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/TextBlock_Decorations.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/TextBlock_Decorations.xaml.cs
src/Uno.UI.Wasm/WasmScripts/Uno.UI.js
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.Android.cs

- Bugfix
- Updating the `TextBlock.TextDecorations` property does not update the TextBlock visually.
- Fixed UITests ImageAssert.NotEqual` without a rectangle not working
The TextBlock is updated.

[Android] Adjust TextBlock.TextDecorations is not updating properly

---

doc/ReleaseNotes/_ReleaseNotes.md
doc/articles/features/routed-events.md
src/Uno.UI.Wasm/WasmScripts/Uno.UI.js
src/Uno.UI.Wasm/ts/WindowManager.ts

GitHub issue: https://github.com/unoplatform/uno/issues/2423
Disable the context menu on WASM
Application has to disable it themselves, or has to handle proper pointer events.
Context menu is disabled by default

Prevent the context menu on wasm while not in a TextBox

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/FeatureConfiguration.cs

- Bugfix
Native popups are restored to be used by default until the non-native behavior is working properly.

[Android] Restore native popups by default

---

src/SolutionTemplate/UnoSolutionTemplate/UWP/Package.appxmanifest
src/SolutionTemplate/UnoSolutionTemplate/UWP/Uwp.vstemplate

GitHub Issue (If applicable): #2624
- Bugfix
Warning generated by an out of date application certificate for UWP
A new certificate is created on project creation with 1 year expiration from today's date.
Publisher name in app manifest also set to user name and matches the generated manifest

Generate an updated project certificate with the correct publisher name

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/Flyout/FlyoutBase.iOSmacOS.cs
src/Uno.UI/UI/Xaml/Controls/Popup/Popup.macOS.cs
src/Uno.UI/UI/Xaml/Style/Generic/GenericStyles.iOSmacOS.cs
src/Uno.UI/UI/Xaml/Window.macOS.cs

GitHub Issue (If applicable): #626 
- Feature
`Flyout` is not supported.
`Flyout` is supported. There are still issues with its layout when the default presenter is used, but that is caused by some `ScrollViewer` layout issues.

[macOS] Support for Flyout

---

doc/ReleaseNotes/_ReleaseNotes.md
doc/articles/features/windows-applicationmodel-chat.md
doc/articles/toc.yml
src/Uno.UWP/ApplicationModel/Chat/ChatMessageManager.macOS.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Chat/ChatMessageManager.cs

GitHub Issue (If applicable): #2640 
- Feature
`ShowComposeSmsMessageAsync` is not implemented.
Implemented.

[macOS] Support for ShowComposeSmsMessageAsync

---

doc/articles/uno-development/working-with-the-samples-apps.md

Documentation is not up to date for the UI Tests
Documentation is up to date, UI Tests can be run on iOS.

Documentation is not up to date, UI Tests can be run on iOS.

---

.vsts-ci.yml
build/ci/.azure-devops-unit-tests.yml
build/ci/.azure-devops-windows.yml
build/ios-uitest-run.sh
src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.cs
src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.csproj
src/Uno.UI.Tests/BinderTests/Given_Binder.DynamicObject.cs
src/Uno.UI.Tests/BinderTests/Given_Binder.Expando.cs
src/Uno.UI.Tests/BinderTests/Given_Binder.TargetNullValue.cs
src/Uno.UI.Tests/BinderTests/Given_Binder.cs
src/Uno.UI.Tests/DependencyProperty/Given_DependencyProperty.Propagation.cs
src/Uno.UI.Tests/Global.cs
src/Uno.UI.Tests/Windows_UI_XAML_Controls/BorderTests/Given_Border.cs
src/Uno.UI.Tests/Windows_UI_XAML_Controls/GridTests/Given_Grid_And_Min_Max.cs
src/Uno.UI.Tests/Windows_UI_Xaml/FrameworkElementTests/Given_FrameworkElement.cs
src/Uno.UI/Mock/Layouter.net.cs
src/Uno.UI/UI/Xaml/FrameworkElement.Layout.wasm.cs
src/Uno.UI/UI/Xaml/FrameworkElement.net.cs

Included more Unit Tests in Runtime Tests
GitHub Issue (If applicable): Fixes #2637
- Bugfix
- Arranged elements with margins are not getting double margins during the Arrange phase (introduced here https://github.com/unoplatform/uno/commit/28d78c7c5f50cb7b9b5fd017dba58448e63785f4#diff-1e50ceb3ff0d84d3d58ddd3548fcfb41R58)
- Add missing support for LayoutUpdated
- Cross-include Unit Tests as Runtime Tests

[Wasm] Fix double arrange margin

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Media_Animation/DoubleAnimation_Tests.TransformGroup.cs
src/Uno.UI.Wasm/WasmScripts/Uno.UI.js
src/Uno.UI.Wasm/ts/WindowManager.ts
src/Uno.UI/UI/Xaml/Controls/Primitives/Thumb.cs
src/Uno.UI/UI/Xaml/Controls/ToggleSwitch.cs
src/Uno.UI/UI/Xaml/Input/PointerRoutedEventArgs.Android.cs

GitHub Issue: _private_
1. Handling of the `PointerPressed` event by the `Thumb` 
1. [Android] Pointer's location relative to another element
1. [WASM] z-order of elements
1. `Thumb` does not handle the `PointerPressed` event when it raises the `DragStarted`, while WinUI does
1. When we get the location of a pointer relative to another element, the `Location` is invalid
1. When we insert an element at index 0 of a `Children` collection of `Panel` the element is appended at the end
1. As WinUI `Thumb` handles the `PointerPressed`, and the `ToggleSwitch` now also listen for handled event in order to update its visual state (for the pressed state)
1. We no longer use the X twice ... d'oh 🤦‍♂️!
1. In `WindowManager` we check for `index != null` instead of `if (index)` which was considered as …

Misc fixes

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ComboBox/ComboBox_CornerRadius.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ComboBox/ComboBox_CornerRadius.xaml.cs
src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml

GitHub Issue (If applicable): #2710 
- Bugfix
Default `ComboBox` style does not apply `CornerRadius`
Default `ComboBox` style does apply `CornerRadius` (`TemplateBinding`, same as in UWP).

Support ComboBox CornerRadius

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml

GitHub Issue (If applicable): #2710 
- Feature
Noticed some other control styles were missing `CornerRadius` handling, too.
The following controls now respect `CornerRadius`:
- `Button`
- `ToggleButton`
- `HyperlinkButton`
- `RadioButton`
- `ScrollViewer`
- `ListView`
- `GridView`
- `ListViewHeaderItem`
- `GridViewHeaderItem`
- `ListViewItem`
- `GridViewItem`
- `ProgressBar`
- `ProgressRing`
- `ToggleSwitch`
- `FlipViewItem`
- `Frame`
- `ComboBoxItem`
- `TextBox`
- `PasswordBox`
`ComboBox` support was added in #2711 

Added CornerRadius support to more default styles to match UWP

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml

GitHub Issue (If applicable): Fixes #1401, Fixes #2710
- Bugfix
`CornerRadius` doesn't currently apply to `Button` properly, as Uno's style has an additional `Grid` to wrap the content and add `Background`.
Now the `CornerRadius` is applied to the `Grid` as well, so that it is applied.

Fixed CornerRadius for Button

---

build/ci/.azure-devops-screenshot-compare.yml
src/SourceGenerators/Uno.UI.SourceGenerators/Helpers/SymbolExtensions.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/Uno.UI.Tests/Windows_UI_XAML_Controls/GridTests/GivenGrid_And_Alignment.cs
src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_NamespaceCollision.xaml
src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_NamespaceCollision.xaml.cs
src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_Primitive_DataTemplate.xaml
src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_Primitive_DataTemplate.xaml.cs
src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_TwoWay_InheritedProperty.xaml
src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_TwoWay_InheritedProperty.xaml.cs
src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_TwoWay_NamedElement.xaml
src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_TwoWay_NamedElement.xaml.cs
src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Given_xBind_Binding.cs

- Bugfix
- TwoWay x:Bind on named elements
- DataTemplate x:Bind on system types
- TwoWay x:Bind on inherited property

Fix TwoWay x:Bind on named elements

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ContentDialog/UnoSamples_Tests.ContentDialog.cs
src/Uno.UI/UI/Xaml/Controls/ContentDialog/ContentDialog.cs
src/Uno.UI/UI/Xaml/Controls/ContentDialog/ContentDialog.md
src/Uno.UI/UI/Xaml/Style/Generic/SystemResources.xaml

GitHub Issue (If applicable): #2107, #2108
- Bugfix
iOS: ContentDialog doesn't block touch for background elements.
iOS/Android: ContentDialog overlay background cannot be changed.
ContentDialog overlay blocks touch.
ContentDialog overlay background can be changed via application resource key: `ContentDialogLightDismissOverlayBackground` (Brush)
closes: #2107, #2108

Fix ContentDialog overlay bugfixes

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_Margin.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_Margin.xaml.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.iOS.cs

Margin were wrongly calculated on TextBox on iOS because of legacy code.
Fixes https://github.com/unoplatform/uno/issues/2705
The `TextBox.SizeThatFits` was using an old legacy pattern causing problem with margins calculations.

[iOS] Fix for margin on TextBox

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ScrollViewerTests/ScrollViewer_Options.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ScrollViewerTests/ScrollViewer_Padding.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ScrollViewerTests/ScrollViewer_Padding.xaml.cs
src/Uno.UI/Extensions/UIViewExtensions.iOSmacOS.cs
src/Uno.UI/UI/Xaml/Controls/Layouter/Layouter.iOS.cs

GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/2703
If the `generic.xaml` of Uno, the `<ScrollViewer>` control template will convert the `Padding` into a `Margin` applied to the inner `<ScrollContentPresenter>`: https://github.com/unoplatform/uno/blob/3e231f1db2d4be5f7334d1bb74adf6ffa758c53d/src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml#L4716
But this `Margin` is not getting included in the `DesiredSize` as the output of the _Measure_ phase. This happend because `<ScrollContentPresenter>` is **NOT** a `FrameworkElement`, on iOS, it's a `UIScrollView` (native control). So there's no layouter in it and the _desired size_ must be calculated by the parent element's layouter.
After calling `.SizeThatFits()` on a native, non-`FrameworkElement` control, the `.Margin` is …

[iOS] Fix bug with padding on ScrollViewer

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Image.cs
src/Uno.UI/UI/Xaml/Controls/Image/ImageSizeHelper.cs

This fixes bug where image requests all available size, even when it has a fixed dimension and aspect ratio.
GitHub Issue (If applicable): fixes #2541 
- Bugfix

[Android] Ensure Image scaling takes Width/Height into account

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TextBoxTests/TextBoxTests.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/DoubleTappedTapped_Tests.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/RightTapped_Tests.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Image.cs

GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/2739
The UI Test When_InListViewWithItemClick is unstable and is temporarily disabled.

Temporarily disable When_InListViewWithItemClick

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ComboBoxTests/UnoSamples_Tests.ComboBoxTests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ComboBox/ComboBox_Stretch.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ComboBox/ComboBox_Stretch.xaml.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.wasm.cs

GitHub Issue (If applicable): Fixes #2680
- Bugfix
A `ComboBox` with `HorizontalAlignment` set to `Stretch` stretches the content of its drop down to the width of the screen.
The ComboBox dropdown does not stretch.

[Wasm] Fix ComboBox should not stretch to the full window width

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ScrollViewerTests/UnoSamples_Tests.ScrolViewer.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ScrollViewerTests/ScrollViewer_Clipping.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ScrollViewerTests/ScrollViewer_Clipping.xaml.cs
src/Uno.UI.BindingHelper.Android/Uno/UI/UnoTwoDScrollView.java
src/Uno.UI/Mixins/Android/FrameworkElementMixins.tt
src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.Android.cs
src/Uno.UI/UI/Xaml/IFrameworkElementImplementation.Android.tt

Fixes https://github.com/unoplatform/uno/issues/2714
- Bugfix
ScrollViewer content may be clipped incorrectly when updated.

Fix android ScrollViewer invalid clipping on update

---

src/Uno.UI/Media/NativeRenderTransformAdapter.Android.cs
src/Uno.UI/Media/NativeRenderTransformAdapter.iOSmacOS.cs
src/Uno.UI/UI/Xaml/Media/Transform.Android.cs
src/Uno.UI/UI/Xaml/Media/Transform.iOSmacOS.cs

GitHub Issue:
fixes https://github.com/unoplatform/uno/issues/2695
fixes https://github.com/unoplatform/uno/issues/2723
The managed `RenderTransform` was not properly cleared before starting a native animation of the `Transform`.
We invoked the `NotifyChanged()` method on the `Transform` right after setting the `IsAnimating` flag, but the `NotifyChanged()` was aborted while `IsAnimating` (in order to not update itself on each frame of an animation)
We bypass the `NotifyChanged()` and we directly invoke the `Changed`  event, so the `RenderTransformAdapter` receives the update and disables itself.
Internal Issue:
https://dev.azure.com/nventive/Umbrella/_workitems/edit/175311
https://dev.azure.com/nventive/Umbrella/_workitems/edit/175740

Fix erratic animations on Android and iOS

---

build/ios-uitest-run.sh
doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/BorderTests/Border_LinearGradientBrush.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/BorderTests/Border_LinearGradientBrush.xaml.cs
src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.iOSmacOS.cs
src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.cs

Fixed the clipping mask calculation when non-zero CornerRadius is set on a border.
Enabled the existing `Border_CornerRadius_Toggle` UI test for iOS, which covers this case.
GitHub Issue (If applicable): fixes #2746 
- Bugfix

[iOS] Fix border thickness with corner radius set

---

src/Uno.UI/UI/Xaml/UIElement.Pointers.Android.cs
src/Uno.UI/UI/Xaml/UIElement.Pointers.cs
src/Uno.UI/UI/Xaml/UIElement.Pointers.iOS.cs
src/Uno.UI/UI/Xaml/UIElement.Pointers.macOS.cs

GitHub Issue: 
https://github.com/unoplatform/uno/issues/2656
Make sure to not crash if receiving a pointer event for a disposed `UIElement`
If a `UIElement` is explicitly disposed by application code, we might receive pointer events on non-initialized element, which causes `NullRefException`
We silently dismiss all native event received on non initialized `UIElement`

Make sure to not crash if receiving a pointer event for a disposed UIElement

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/CommandBarTests/UnoSamples_Tests.NativeCommandBar.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/CommandBar_Native_With_Content.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/CommandBar_Native_With_Content.xaml.cs
src/Uno.UI/Controls/CommandBarRenderer.Android.cs

GitHub Issue (If applicable): Fixes #2763 
- Bugfix
Custom content in a CommandBar is stretching the CommandBar to the available space.
The Content is properly sized to the CommandBar height.

[Android] Fix toolbar height with custom content

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ProgressRing.cs
src/Uno.UI/Mixins/Android/FrameworkElementMixins.tt
src/Uno.UI/Mixins/iOS/FrameworkElementMixins.tt
src/Uno.UI/Mixins/macOS/FrameworkElementMixins.tt
src/Uno.UI/UI/Xaml/Controls/Layouter/Layouter.Android.cs
src/Uno.UI/UI/Xaml/Controls/Layouter/Layouter.cs
src/Uno.UI/UI/Xaml/Controls/Layouter/Layouter.iOS.cs
src/Uno.UI/UI/Xaml/FrameworkElement.cs
src/Uno.UI/UI/Xaml/FrameworkElement.net.cs
src/Uno.UI/UI/Xaml/FrameworkElement.wasm.cs
src/Uno.UI/UI/Xaml/IFrameworkElementImplementation.Android.tt
src/Uno.UI/UI/Xaml/IFrameworkElementImplementation.iOS.tt
src/Uno.UI/UI/Xaml/IFrameworkElementImplementation.macOS.tt
src/Uno.UI/UI/Xaml/IFrameworkElementInternal.cs

ProgressRing inside a StackPanel was failing to display because its desired size wasn't set. Fix this by introducing a flag to distinguish between managed views that have their own Layouter, and those that don't (like ProgressRing).
GitHub Issue (If applicable): fixes #2762 
- Bugfix

[Android] Fix ProgressRing fails to display

---

src/Uno.UI.Tests/Windows_UI_Xaml/FrameworkElementTests/Given_FrameworkElement.cs
src/Uno.UI/UI/Xaml/Controls/StackPanel/StackPanel.Layout.cs
src/Uno.UI/UI/Xaml/FrameworkElement.cs

GitHub Issue (If applicable): Fixes #2767
- Bugfix
[Android] Fix elements may not be arranged properly, caused by a missing Arrange pass. There is no clear repro case that could be created at this time.
Related Issue : https://github.com/unoplatform/uno/issues/2769

[Android] Fix elements may not be arranged properly

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs
src/Uno.UI/UI/Xaml/Controls/Primitives/Selector.cs

When changing SelectedItem to an invalid value, if the current value had already become invalid, an infinite ping-pong from one value to the other would ensue.
This change interrupts the process by setting the value to null instead, which is a little different from Windows where the original value is retained even if invalid.
GitHub Issue (If applicable): fixes #2797 
- Bugfix

ListView - fix stack overflow when changing SelectedItem

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_FrameworkElement.cs
src/Uno.UI/Services/LayoutManager.Android.cs

The LayoutManager is used when `AreDimensionsConstrained = true` for a particular view, which can be set manually as an optimization if it's known that a view's size will never change. It wasn't taking the Margin into account when measuring the view, which was causing errors after layouting changes.
GitHub Issue (If applicable): fixes #2761
- Bugfix

[Android] Include Margin when measuring from LayoutManager

---

src/Uno.UI/UI/Xaml/Controls/Layouter/Layouter.cs

Changed how the IsLessThanAndNotCloseTo is calculated
The EPSILON is replaced by something dynamic
* Internal issue, no link available here.

fix: [Android/iOS] Layouter - Clipping were not properly applied.

---

src/SolutionTemplate/UnoSolutionTemplate/UWP/UnoQuickStart.Uwp.csproj

GitHub Issue (If applicable): closes #2820
- Feature
ARM64 configuration is missing in UWP
ARM64 configuration part of solution template.

Added ARM64 configuration to UWP head

---

doc/articles/controls/CommandBar.md

CommandBar documentation is not up to date for the elevation property
CommandBar documentation is not up to date for the elevation property

Fixed CommandBar doc for the elevation property

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ImageTests/UnoSamples_Tests.Margins.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/Image_Margins.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/Image_Margins.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/Image_Stretch.xaml.cs
src/Uno.UI/UI/Xaml/Controls/Image/Image.Android.cs
src/Uno.UI/UI/Xaml/Controls/Layouter/Layouter.Android.cs
src/Uno.UI/UI/Xaml/Controls/Layouter/Layouter.iOS.cs

In situations where the measured size is required in the arranged phase, the measure value was reported without the margins, leading to broken layout in some situations.
* https://dev.azure.com/nventive/Umbrella/_workitems/edit/177045 Android / Button is cut off
* https://dev.azure.com/nventive/Umbrella/_workitems/edit/177339 /#2836 iOS / Button content is cut off

[Android/iOS] Images with margins were returning wrong measure size.

---

doc/articles/controls/CommandBar.md
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/CommandBarTests/UnoSamples_Tests.NativeCommandBar.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/CommandBar_Native_With_TextBox.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/CommandBar_Native_With_TextBox.xaml.cs
src/Uno.UI/Controls/CommandBarRenderer.Android.cs

GitHub Issue (If applicable): Fixes #2838, Fixes #2837
- Bugfix
Horizontal alignment for custom `CommandBar` content is not possible.
`CommandBar.HorizontalContentAlignment` is now supported to change the alignment.

feat(commandbar): Fix support for CommandBar content horizontal alignment on Android

---

src/Uno.UI.Tests/Windows_UI_XAML_Controls/ListViewBaseTests/Given_ListViewBase.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.cs

GitHub Issue: fixes https://github.com/unoplatform/uno/issues/2839
Invalid visual state when changing a `ListView`'s selectuion mode while one or more items are selected.
When the `SelectionMode` is changed to `None` while at least on item is selected, the `ListView` tries to un-select them, but doing this it alter the collection that it is enumerating.
We create a clone of the selected items collection.

Fix ListView selection mode changed

---

src/SamplesApp/SamplesApp.Wasm/WasmScripts/AppManifest.js
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/xamarinforms-wasm/UnoQuickStart.Wasm/WasmScripts/AppManifest.js
src/SolutionTemplate/UnoSolutionTemplate/Wasm/WasmScripts/AppManifest.js

GitHub Issue (If applicable): fixes #2857 
- Feature
Pure blue used for WASM splash screen.
Default Uno accent color (#0078D7) used for WASM splash screen.

feat: [WASM] Using Uno blue accent color for splash

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ContentDialog/UnoSamples_Tests.ContentDialog.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ContentDialogTests/ContentDialog_Closing.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ContentDialogTests/ContentDialog_Closing.xaml.cs
src/Uno.UI/UI/Xaml/Controls/ContentDialog/ContentDialog.cs

GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/2805
- Bugfix
When a `ContentDialog.Closing` is canceled, using the dialog's button now properly handle actions.

fix(ContentDialog): Content dialog can be closed if Closing event was canceled

---

src/Directory.Build.targets
src/SamplesApp/SamplesApp.Shared/App.xaml.cs
src/SamplesApp/SamplesApp.Wasm/SamplesApp.Wasm.csproj
src/Uno.UWP/UI/Core/CoreDispatcher.wasm.cs

Related issues:
- https://github.com/unoplatform/Uno.Wasm.Bootstrap/issues/128
- https://github.com/WebAssembly/binaryen/issues/2180
- Bugfix
- Feature
- Improved WebAssembly debugging
- Uses emscripten latest
- Add preliminary support for `CoreDispatcher` threading

feat(wasm): Add CoreDispatcher support for Threading

---

src/Uno.Foundation/Point.cs
src/Uno.UI.Tests/Foundation/Given_Point.cs

- Bugfix
Comparing a `Point` with null does not fail with an NRE.

fix(point): Fix comparing a Point to null NRE

---

src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.wasm.cs
src/Uno.UI/UI/Xaml/FrameworkElement.Interface.wasm.cs

- Bugfix
Fix ContentPresenter background not appearing after #2750

fix(ContentPresenter): [Wasm] ContentPresenter background is not applied properly

---

src/Uno.UI.Toolkit/ElevatedView.cs
src/Uno.UI.Toolkit/Themes/Generic.xaml

Occurs when the `TemplateParent` binding could be confused and bind to the wrong parent. It should be resolved at parse time, but it's resoved at runtime, so a required context is lost, leading to this problem.
Has been fixed by renaming the content property from `Content` to `ElevatedContent`.
Fix #2853
Unblock https://nventive.visualstudio.com/Umbrella/_workitems/edit/168664

fix(elevatedview): Patch a TemplateBinding problem.

---

build/android-uitest-run.sh

When install the android SDK adb (in the `platform-tools` 29.0.6 package) is installed in an incorrect folder by the sdk-manager
This update moves the incorrect directory to the correct location

ci: Fix invalid android platform-tools path

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/Clipping/ButtonClipping652.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/UIElementTests/UIElement_Layout_Bug2879.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/UIElementTests/UIElement_Layout_Bug2879.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/GridTestsControl/Grid_with_MinWidthColumns.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/ImageAlignment2541.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/EllipseAlignment2542_2547.xaml.cs
src/Uno.UI/UI/Xaml/Controls/Layouter/Layouter.Android.cs
src/Uno.UI/UI/Xaml/FrameworkElement.cs
src/Uno.UI/UI/Xaml/FrameworkElement.iOS.cs
src/Uno.UI/UI/Xaml/FrameworkElement.macOS.cs
src/Uno.UI/UI/Xaml/Shapes/Polygon.Android.cs
src/Uno.UI/UI/Xaml/Shapes/Polyline.Android.cs

The problem was caused by a cache in Android layout system. Was appearing when the `DesiredSize` is required to layout an element, like in the `<StackPanel>`. In this case, the `Measure()` were not properly called at the right time, causing the panel (`<StackPanel>` here) to use the previous (wrong) measured/desired size.
The fix is to call `ForceLayout()`, causing Android to bypass the cache during the `Measure()` phase.
* Fix #2879 
* Fix https://nventive.visualstudio.com/Umbrella/_workitems/edit/177488

fix(android): Fix for bug #2879

---

src/Uno.UI.Toolkit/ElevatedView.cs

When the `ElevatedView` itself was placed into an `ControlTemplate`, the `TemplatedParent` were not the right one, leading to unexpected behavior in the result.
This is a patch and reproduce a behavior already patched in `ContentControl`. A better fix would required architectural changes in Uno, which is not is the scope of this bug fix.
* fix https://github.com/unoplatform/uno/issues/2891

fix(elevatedview): Make sure the `ElevatedView` propagates its `TemplatedParent`.

---

build/PackageDiffIgnore.xml
doc/articles/features/windows-devices-sensors.md
src/SamplesApp/SamplesApp.Droid/Properties/AndroidManifest.xml
src/SamplesApp/SamplesApp.iOS/Info.plist
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_Devices/PedometerTests.xaml
src/SamplesApp/UITests.Shared/Windows_Devices/PedometerTests.xaml.cs
src/Uno.UWP/Devices/Sensors/Accelerometer.Android.cs
src/Uno.UWP/Devices/Sensors/Barometer.Android.cs
src/Uno.UWP/Devices/Sensors/Gyrometer.Android.cs
src/Uno.UWP/Devices/Sensors/Helpers/SensorHelpers.Android.cs
src/Uno.UWP/Devices/Sensors/Helpers/SensorHelpers.iOS.cs
src/Uno.UWP/Devices/Sensors/Magnetometer.Android.cs
src/Uno.UWP/Devices/Sensors/Pedometer.Android.cs
src/Uno.UWP/Devices/Sensors/Pedometer.cs
src/Uno.UWP/Devices/Sensors/Pedometer.iOS.cs
src/Uno.UWP/Devices/Sensors/PedometerReading.cs
src/Uno.UWP/Devices/Sensors/PedometerReadingChangedEventArgs.cs
src/Uno.UWP/Devices/Sensors/PedometerStepKind.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Devices.Sensors/Pedometer.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Devices.Sensors/PedometerReading.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Devices.Sensors/PedometerReadingChangedEventArgs.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Devices.Sensors/PedometerStepKind.cs

GitHub Issue (If applicable): #2069
- Feature
`Pedometer` is not supported.
`Pedometer` is supported for active step-counting :-) .
This PR also unifies the default `ReportInterval` of other sensors on Android (previously it was not adjustable)

feat: Windows.Devices.Sensors.Pedometer

---

src/Uno.UI/LinkerDefinition.Wasm.xml

- Bugfix
`dotnet.js:1 Uncaught Error: Could not find method: ReceiveFocusNative`
The ReceiveFocusNative is excluded from the wasm linker.

fix: [Wasm] Adjust linker settings for FocusManager.ReceiveFocusNative

---

src/SourceGenerators/Uno.UI.SourceGenerators/DependencyObject/DependencyObjectGenerator.cs
src/SourceGenerators/Uno.UI.SourceGenerators/NativeCtor/NativeCtorsGenerator.cs
src/Uno.UI/DataBinding/BinderCollector.iOSmacOS.cs
src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.macOS.cs
src/Uno.UI/UI/Xaml/Controls/Image/Image.macOS.cs
src/Uno.UI/UI/Xaml/Controls/MenuBar/NativeMenuBarPresenter.macOS.cs
src/Uno.UI/UI/Xaml/Controls/Panel/Panel.macOS.cs
src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.macOS.cs
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.macOS.cs
src/Uno.UI/UI/Xaml/FrameworkElement.macOS.cs
src/Uno.UI/UI/Xaml/IFrameworkElement.cs
src/Uno.UI/UI/Xaml/IFrameworkElementImplementation.macOS.tt
src/Uno.UI/UI/Xaml/Shapes/Path.iOSmacOS.cs
src/Uno.UI/Uno.UI.csproj

- Bugfix
Slow layout performance.
This change removes the reliance on NSView.NeedsLayout to invalidate the measure/arrange phases for self and parents. NeedsLayout is set to true when NSView.Frame is changed, causing a chain of multiple unneeded updates for the element and its parents.
Related to #626

[macOS] Update measure/arrange passes

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_UIElement.TransformToVisual.cs
src/Uno.UI/UI/Xaml/UIElement.cs

fixes https://github.com/unoplatform/uno/issues/2913
The `TransformOrigin` was not taken in consideration by `TransformToVisual` 
You you click on a button that is rotated by 90 degrees, the click event it not fired. 
That's because before raising the `click` event, the `ButtonBase` checks if the pointer is over the button in the `OnPointerReleased`, but as the `RenderOrigin` was ignored the computed pointer location was invalid.
The pointer's location is computed properly, so the click event is fired.

fix: Transform to visual ignores render origin

---

src/SamplesApp/UITests.Shared/Windows_Graphics_Display/DisplayInformation/DisplayInformation_Properties.xaml
src/SamplesApp/UITests.Shared/Windows_Graphics_Display/DisplayInformation/DisplayInformation_Properties.xaml.cs
src/Uno.UWP/Graphics/Display/DisplayInformation.macOS.cs

https://github.com/unoplatform/uno/issues/2907
- Feature
macOS does not support the `DisplayInformation`
macOS does support the `DisplayInformation`

feat: (macOS) Add support for DisplayInformation

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_FrameworkElement.cs
src/Uno.UI/UI/Xaml/Controls/Layouter/Layouter.cs
src/Uno.UI/UI/Xaml/FrameworkElement.Layout.wasm.cs

Bring influence of negative Margin on DesiredSize in line with Windows: it reduces the DesiredSize, but never below 0.
This fixes a bug on Android where setting a negative native MeasuredDimension overflows to a very large desired size, causing an empty view with negative margins to request all available space.
GitHub Issue (If applicable): fixes unoplatform/private#129
- Bugfix

fix(layouting): Ensure negative Margin doesn't push DesiredSize below 0

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/Manipulation_Tests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Input/GestureRecognizerTests/Manipulation_WithNestedElement.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Input/GestureRecognizerTests/Manipulation_WithNestedElement.xaml.cs
src/Uno.UI/UI/Xaml/UIElement.PointerCapture.cs

GitHub Issue: fixes#https://github.com/unoplatform/uno/issues/2843
Fix pointers event for elements that are nested in an element that has enabled manipulations.
When a manipulation stars on an element, it will implicitly capture the pointer to make sure to receive all updates even when pointer moves out of the range of this element. But this will prevent any nested child to receive pointer events (instead they will receive a 'pointerleave' on capture and a 'pointerenter' when releasing capture ... for mouse).
For implicit captures we use the `OriginalSource` (if possible) instead of the element that is actually capturing the pointer, so event will still bubble up from the lowest layer.

[WASM] Fix pointers for elt nested in manip aware content

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Shapes/Shapes_Tests.ClearData.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Shapes/Shapes_Tests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/Path_ClearData.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/Path_ClearData.xaml.cs
src/Uno.UI/UI/Xaml/Shapes/Path.wasm.cs

GitHub Issue: _private, see below_
WASM: Impossible to clear the Data of a Path
When you set `null` on a `Path.Data` the path remains visible
The `d` property of the native svg element is now clear

fix: [WASM] Fix clearing the Data of a Path

---

src/Uno.UWP/Generated/3.0.0.0/Windows.System.Display/DisplayRequest.cs
src/Uno.UWP/Helpers/IOKit.macOS.cs
src/Uno.UWP/System/Display/DisplayRequest.cs
src/Uno.UWP/System/Display/DisplayRequest.macOS.cs

GitHub Issue (If applicable): #626, closes #2987 
- Feature
`DisplayRequest` is not supported on macOS.
`DisplayRequest` supported on macOS.

feat(DisplayRequest): macOS support

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/Uno.UI.Tests/Windows_UI_Xaml/FrameworkElementTests/Given_FindName.cs
src/Uno.UI/UI/Xaml/Controls/Flyout/FlyoutBase.cs
src/Uno.UI/UI/Xaml/IFrameworkElement.cs

GitHub Issue (If applicable): #2995
- Bugfix
`FindName` for MenuItems in a ContextFlyout cannot be found

Fix FindName cannot dig into UIElement.ContextFlyout and Button.Flyout

---

src/Uno.UI.Wasm/WasmScripts/Uno.UI.d.ts
src/Uno.UI.Wasm/WasmScripts/Uno.UI.js
src/Uno.UI.Wasm/ts/WindowManager.ts
src/Uno.UI/UI/Xaml/UIElement.Pointers.wasm.cs

Minor fixes for the `PointerWheelChanged` event for WASM
1. The `PointerWheelChanged` event is not raised on Firefox
2. When scrolling down, the content is scrolling up
🙃

fix(pointers): [WASM] Misc PointerWheelChanged fixes

---

src/Uno.UI/UI/Xaml/Controls/SymbolIcon/SymbolIcon.cs

GitHub Issue : #2834
- Bugfix
The symbol icon **Home** is not shown in WASM (**Home** is set as the default symbol in the **Symbol** dependency property but the inner **FontIcon.Glyph** property is not set).
The symbol icon **Home** is now shown in WASM, and the default symbol is now **Emoji** (like in UWP **SymbolIcon** class).

fix: [Wasm] Fixes #2834 -Symbol icon Home not shown

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TextBoxTests/TextBoxTests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_IsReadOnly_AcceptsReturn.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_IsReadOnly_AcceptsReturn.xaml.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.Android.cs

GitHub Issue (If applicable): #2700
- Bugfix
`TextBox IsReadOnly="true"` ignores line changes in text.
`TextBox IsReadOnly="true"` makes TextBox read-only (and nothing else).

[Android] TextBox.IsReadOnly bugfixes

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/SourceGenerators/XamlGenerationTests/InheritingPageTest.xaml
src/SourceGenerators/XamlGenerationTests/InheritingPageTest.xaml.cs

GitHub Issue (If applicable): Fixes #2830
- Bugfix
All types generated using XAML get sealed automatically, which is not aligned with WinUI.
Generated types are not automatically sealed.

fix: Remove the sealed attribute from generated code (#2830)

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ToolTipTests/ToolTip_Tests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ToolTip/ToolTip_Long_Text.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ToolTip/ToolTip_Long_Text.xaml.cs
src/Uno.UI/UI/Xaml/Controls/Popup/Popup.cs
src/Uno.UI/UI/Xaml/Controls/ToolTip/ToolTip.cs
src/Uno.UI/UI/Xaml/Controls/ToolTip/ToolTipPositioning.cs
src/Uno.UI/UI/Xaml/Controls/ToolTip/ToolTipService.cs
src/Uno.UWP/Extensions/RectExtensions.cs

Tooltip was previously only being placed relative to the owner view, which could cause the tooltip to immediately flick out of view if it appeared over the mouse (hence causing the owner view to lose focus). This change correctly positions it relative to the mouse pointer location.
GitHub Issue (If applicable): resolves #2980
- Bugfix

fix(tooltip): Place tooltip relative to mouse pointer

---

src/Uno.UWP/Graphics/Display/DisplayInformation.macOS.cs

https://github.com/unoplatform/uno/issues/2907
- Feature
macOS does not support Orientation on the 
Basic orientation will be supported to match with other platforms.
closes #2907 

feat: (macOS) Add support for Orientation on DisplayInformation

---

src/Uno.UI/UI/Xaml/Controls/MediaPlayer/MediaPlayerElement.cs
src/Uno.UI/UI/Xaml/Controls/MediaPlayer/MediaPlayerPresenter.cs

Fixes #3066 
- Bugfix
MediaPlayer's playback is restarted when toggling the fullscreen mode.
MediaPlayer's playback continues when toggling the fullscreen mode.

Prevents stopping the player when going to fullscreen.

---

build/Uno.UI.Build.csproj
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.UWP/Package.appxmanifest

- Bugfix
- The Uno.UI package reference is no updated during CI.
- The publisher name is incorrect in the Prism template

Update `dotnet new` templates to use CI versions for uno references

---

src/Uno.UI/UI/Xaml/Controls/MediaPlayer/MediaPlayerPresenter.cs

- Bugfix
Media player is not shown because it can't calculate it's video ratio without being arranged first.
This issue was introduced in 3fd116dc
Media player is arranged without a video ratio then the ratio is calculated. This also fixes the infinity measure exception.

fix(mediaplayer): Arranges the player even if the video ratio is of 0 as this will lead to a real video ratio.

---

doc/articles/get-started-vscode-wasm.md

- Documentation content changes 
The template version to install was incorrect and did not contain `unoapp`
Updated to the latest stable version.
-
-

docs: Update template version to latest stable

---

src/UnoItemTemplate/BlankPage/BlankPage.vstemplate

GitHub Issue (If applicable): #3075 
- Bugfix
Explicit `DependentUpon` attribute generates invalid `<DependentUpon>` declaration.
Removed `DependentUpon` attribute, now matches the UWP `BlankPage.xaml` template.

fix: Remove explicit DependentUpon from BlankPage.vstemplate

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MediaPlayerElement/MediaPlayerElement_Sources.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MediaPlayerElement/MediaPlayerElement_Sources.xaml.cs
src/Uno.UWP/Media/Playback/Internal/VideoSurface.Android.cs
src/Uno.UWP/Media/Playback/MediaPlayer.Android.cs
src/Uno.UWP/Media/Playback/MediaPlayer.iOS.cs

Fixes #3073 
GitHub Issue (If applicable): #3073
- Bugfix
MediaPlayer is not reset when its source is set to null.
MediaPlayer is reset when its source is set to null.

fix(mediaplayer): Resets the MediaPlayer and its surface when setting its source to null.

---

src/Directory.Build.targets
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/DoubleTappedTapped_Tests.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/TappedTapped_Tests.cs
src/Uno.UI/UI/Xaml/Input/PointerRoutedEventArgs.iOS.cs
src/Uno.UI/UI/Xaml/UIElement.Pointers.iOS.cs
src/Uno.UI/UI/Xaml/UIElement.Pointers.wasm.cs

fixes https://github.com/unoplatform/uno/issues/2813
The `UIElement.DoubleTapped` event is not fired
On iOS, each time a pointer is pressed down, it has a new ID. The issue is that ID is needed to track and detect double tap.
We now generates a managed pointer ID which is reset only once all pointers are release. So a pointer will always have the same ID for single touch, and we don't have conflicting pointer ID (like we used to have before using the `UITouch.Handle`)

fix(pointers): [iOS] Fix the DoubleTap

---

src/SamplesApp/SamplesApp.Droid/Properties/AndroidManifest.xml
src/SamplesApp/SamplesApp.Droid/Properties/AssemblyInfo.cs
src/Uno.UWP/Devices/Geolocation/Geolocator.Android.cs

- Bugfix
GeoLocator on android does not request permissions for location.

fix(android-geolocator): Request and validate permissions

---

src/Uno.UWP/Media/Playback/MediaPlayer.Android.cs

GitHub Issue (If applicable): #3073
- Bugfix
NRE when the surface is destroyed after the player was released.
Don't set the display on a null object.

fix(mediaplayer): NRE when the surface is destroyed but the player has already been released.

---

src/Uno.Foundation/Runtime.wasm.cs

- Bugfix
OSPlatform for WebAssemnly after Bootstrapper 1.2.0-dev.29 is "BROWSER" where is previously was "WEBASSEMBLY".
Uno will treat both values as a WebAssembly environment for backward compatibility.

fix: Adjust WebAssembly detection after a breaking change in `RuntimeInformation`

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileParser.cs
src/SourceGenerators/XamlGenerationTests/XBindIgnorableLess.xaml
src/SourceGenerators/XamlGenerationTests/XBindIgnorableLess.xaml.cs

- Bugfix
Fix x:Bind parsing when ignorable directive is not present in a XAML file.

fix(xBind): Fix x:Bind parsing when ignorable directive is not present

---

src/Uno.UI/Controls/NativeFramePresenter.iOS.cs
src/Uno.UI/UI/Xaml/Controls/Frame/Frame.cs

- Bugfix
The application crashes you press the back button on a native `CommandBar` then immediately call `Frame.Navigate()`.
The `Frame.Navigating` gets cancelled when you press the back button on a native `CommandBar` just before calling `Frame.Navigate()`.
180990

Improve NativeFramePresenter.iOS to fix concurrency issues.

---

src/SamplesApp/UITests.Shared/Windows_UI_Core/SetCursor.xaml.cs
src/Uno.UWP/UI/Core/CoreWindow.cs
src/Uno.UWP/UI/Core/CoreWindow.macOS.cs

GitHub Issue (If applicable): closes #3105 
- Feature
`PointerCursor` can't be set on macOS
`PointerCursor` can be set on macOS

[macOS] PointerCursor

---

src/Directory.Build.targets
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.Wasm/BlankApp.Wasm.csproj
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/xamarinforms-wasm/UnoXFQuickStart.Wasm/UnoXFQuickStart.Wasm.csproj
src/SolutionTemplate/UnoSolutionTemplate/Wasm/UnoQuickStart.Wasm.csproj

Fixes #1947
- Bugfix
Fixes the Uno templates for Wasm to run properly on macOS, Linux.

chore: Update Wasm.Bootstrapper is to 1.2.0-dev.37

---

src/Uno.UI/UI/Xaml/Shapes/Shape.wasm.cs

GitHub Issue: _private_
The `StrokeDashArray` is not applied on WASM
The DP callback is validating the `Stroke` instead of the `StrokeDashArray`, so if set later (e.g. with a `StaticRessource`), the value won't be pushed to the native element.
🙃

fix(shapes): [WASM] StrokeDashArray is not published to native element

---

src/SamplesApp/SamplesApp.macOS/SamplesApp.macOS.csproj

GitHub Issue: Fixes https://github.com/unoplatform/uno/issues/3118
Make sure that test runner can be started
The `UserControl` are not inserted in the visual tree, so they can be garbage collected, so event handler defined in the code behind are no longer invoked.
'UserControl` are now inserted in the visual tree.

fix: [MacOS] Fix event handler not invoked in the sample app

---

src/SourceGenerators/Uno.UI.SourceGenerators.Tests/Given_XBindRewriter.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/Utils/XBindExpressionParser.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_TypeMismatch.xaml
src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_TypeMismatch.xaml.cs
src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_TypeMismatch_DataTemplate.xaml
src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_TypeMismatch_DataTemplate.xaml.cs
src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/DataTemplate_StaticProperty_Control.xaml
src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/DataTemplate_StaticProperty_Control.xaml.cs
src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Given_xBind_Binding.cs
src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Given_xBind_DataTemplate.cs

Fixes #3098
- Bugfix
- x:Bind to a static property in a DataBinding is failing
- TwoWay x:Bind to a mismatched property type results in no update

Fix x:Bind invalid type cast, static properties in DataTemplates

---

src/Uno.UI/UI/Xaml/Application.macOS.cs

closes #3129 
- Feature
Applications are not aware of the user default OS Language.
If handling different languages, a Uno macOS application should pick and use the right string resources based on the user OS Language.

feat: (macOS) Add support for Localization

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_TypeMismatch.xaml
src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_TypeMismatch_DataTemplate.xaml
src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Given_xBind_Binding.cs

- Bugfix
TwoWay x:Bind does not create invalid C# when converting from int to string. 

fix(reg): Use XamlBindingHelper.ConvertValue for TwoWay x:Bind

---

src/Uno.Foundation/LinkerDefinition.Wasm.xml
src/Uno.Foundation/Runtime.wasm.cs
src/Uno.Foundation/Uno.Foundation.csproj
src/Uno.UI.RuntimeTests/Tests/Uno_Foundation/Given_WebAssemblyRuntime.cs
src/Uno.UI.Wasm/WasmScripts/Uno.UI.d.ts
src/Uno.UI.Wasm/ts/Interop/AsyncInteropHelper.ts

Implements #3084
It is now possible to await javascript/TypeScript execution when it's returning a `Promise<string>`.

feat(wasm): Added ability to call async javascript `Promise<string>` and await it.

---

build/Uno.UI.Build.csproj
src/Uno.UWPSyncGenerator/Generator.cs

Fixes the vsix publication which uses WinUI transformed tree, instead of the UWP original tree.

Fix the vsix publication

---

.github/pull_request_template.md
doc/articles/features/routed-events.md
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Input/Keyboard/Keyboard_Events.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Input/Keyboard/Keyboard_Events.xaml.cs
src/Uno.UI/Controls/BindableNSView.macOS.cs
src/Uno.UI/UI/Xaml/UIElement.macOS.cs
src/Uno.UWP/System/VirtualKeyHelper.macOS.cs
src/Uno.UWP/System/VirtualKeyHelper.wasm.cs

fixes https://github.com/unoplatform/uno/issues/3167
Add keyboard events support
`UIElement.KeyDown` and `UIElement.KeyUp` are not raised on mac.
🙃

feat: [MacOS] Add keyboard events support

---

src/Uno.UI.RemoteControl.Host/HotReload/ServerHotReloadProcessor.cs
src/Uno.UI.RemoteControl.Host/Uno.UI.RemoteControl.Host.csproj

GitHub Issue (If applicable): Fixes #2829
- Bugfix
Changed XAML Files may not be reloaded properly, depending on how the files are changed.
Files are now observed through renames, to detect the WriteTemporary->DeleteOriginal->RenameToOriginal sequence that Visual Studio uses when saving files.

fix(hotreload): Adjust FileSystemWatcher for updated xaml files

---

src/Uno.UI/System/DispatcherQueue.cs
src/Uno.UI/System/DispatcherQueueTimer.Android.cs
src/Uno.UI/System/DispatcherQueueTimer.cs
src/Uno.UI/System/DispatcherQueueTimer.iOSmacOS.cs
src/Uno.UI/System/DispatcherQueueTimer.net.cs
src/Uno.UI/System/DispatcherQueueTimer.wasm.cs

Fixes https://github.com/unoplatform/uno/issues/3199
Removed `Microsoft.System` namespace.
Fix #3199

fix(winui3): Removed Microsoft.System namespace for non-WinUI3 output.

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/FlyoutTests/UnoSamples_Tests.Flyout.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Flyout/Flyout_TemplatedParent.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Flyout/Flyout_TemplatedParent.xaml.cs
src/Uno.UI/UI/Xaml/Controls/Flyout/FlyoutBase.cs

- Bugfix
The `TemplatedParent` propagation in `Flyout` instances is restored.

fix(reg): Restore Flyout TemplatedParent propagation

---

doc/articles/howto-migrate-existing-code.md

The link was pointing to a dummy file.
The link is pointing to the migrating apps article.

docs: Fixed link to migrating apps

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/SplitViewTests/SplitViewTests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/SplitView/SplitViewClip.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/SplitView/SplitViewClip.xaml.cs
src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml

GitHub Issue (If applicable): fixes #3174
- Bugfix
Right pane in `SplitView` was not properly clipped.
Right pane in `SplitView` is properly clipped.

fix(SplitView): Clipping of right pane

---

src/Uno.UI/UI/Xaml/UIElement.Pointers.wasm.cs

Twitter Issue https://twitter.com/geolite_livejp/status/1264765429810991105?s=20
Fixes https://github.com/unoplatform/uno/issues/3233
Pointer events might not work on safari for iOS (WASM)
Pointer ID is parsed as `uint`, but the on iOS for Safari in some cases it might be negative.
It's marshaled as double (as the `Number` for JS is a double precision value), and then cats as `uint` to match the WinUI contract.

fix(pointers): [WASM] Fix negative pointer id on safari for iOS prevents pointers events

---

src/Uno.UI.Wasm/ts/CoreDispatcher.ts

- Bugfix
This workaround was introduced for https://github.com/mono/mono/issues/12357, and got fixed in recent Safari builds.

fix: Remove arbitrary 5 seconds delay workaround for iOS

---

src/Uno.UI/UI/Xaml/FrameworkElement.iOS.cs
src/Uno.UI/UI/Xaml/FrameworkElement.iOSmacOS.cs
src/Uno.UI/UI/Xaml/FrameworkElement.macOS.cs

fix closes #3198 
- Bugfix
When having a `Grid` with a MinWidth assigned to at least one of **ColumnDefinition** the internal UI controls whose **FontSize** is small (less than 12) and have an **HorizontalAlignment** other than Stretch are not displayed.
UIControls will display inside a `Grid` even when such Grid has any ColumnDefinition set with MinWidth Value.

fix (macOS): Grid inner control display text

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ComboBoxTests/UnoSamples_Tests.ComboBoxTests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ComboBox/ComboBox_Disabled.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ComboBox/ComboBox_Disabled.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ComboBox/ComboBox_ToggleDisabled.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ComboBox/ComboBox_ToggleDisabled.xaml.cs
src/Uno.UI/UI/Xaml/Controls/ComboBox/ComboBox.cs

GitHub Issue: 
Closes unoplatform/Uno.Material#51
- Bugfix
When IsEnabled="False", the ComboBox is correctly disabled but the disabled visual state doesn't appear for iOS, Android and WASM.
When IsEnabled="False", the ComboBox is correctly disabled and the disabled visual state is visible on all platforms.

fix(ComboBox): Correctly update CommonStates on apply template to fix disabled ComboBox visual state not appearing (for all platforms)

---

src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Controls/StarStackPanel.cs
src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Helper/GridLengthHelper2.cs
src/SamplesApp/SamplesApp.UnitTests.Shared/SamplesApp.UnitTests.Shared.projitems

GitHub Issue (If applicable): Fixes #3217 
- Bugfix
In UWP (non-WinUI) GridLengthHelper.Auto fails with MethodAccessException, this is a UWP-only workaround. This update uses a helper to adjust for the appropriate calls, only for the sample app.

fix: Adjust UWP sample head

---

src/Uno.UI.Wasm/WasmScripts/Uno.UI.d.ts
src/Uno.UI.Wasm/WasmScripts/Uno.UI.js
src/Uno.UI.Wasm/ts/MonoSupport.ts
src/Uno.UI.Wasm/ts/Windows/Storage/ApplicationDataContainer.ts
src/Uno.UI.Wasm/tsBindings/ApplicationDataContainer_ClearParams.ts
src/Uno.UI.Wasm/tsBindings/ApplicationDataContainer_ContainsKeyParams.ts
src/Uno.UI.Wasm/tsBindings/ApplicationDataContainer_ContainsKeyReturn.ts
src/Uno.UI.Wasm/tsBindings/ApplicationDataContainer_GetCountParams.ts
src/Uno.UI.Wasm/tsBindings/ApplicationDataContainer_GetCountReturn.ts
src/Uno.UI.Wasm/tsBindings/ApplicationDataContainer_GetKeyByIndexParams.ts
src/Uno.UI.Wasm/tsBindings/ApplicationDataContainer_GetKeyByIndexReturn.ts
src/Uno.UI.Wasm/tsBindings/ApplicationDataContainer_GetValueByIndexParams.ts
src/Uno.UI.Wasm/tsBindings/ApplicationDataContainer_GetValueByIndexReturn.ts
src/Uno.UI.Wasm/tsBindings/ApplicationDataContainer_RemoveParams.ts
src/Uno.UI.Wasm/tsBindings/ApplicationDataContainer_RemoveReturn.ts
src/Uno.UI.Wasm/tsBindings/ApplicationDataContainer_SetValueParams.ts
src/Uno.UI.Wasm/tsBindings/ApplicationDataContainer_TryGetValueParams.ts
src/Uno.UI.Wasm/tsBindings/ApplicationDataContainer_TryGetValueReturn.ts
src/Uno.UWP/Storage/ApplicationDataContainer.wasm.cs

Fixes #2923
- Bugfix
The change is required to allow for synchronous access to local container values, where the previous implementation was relying on IDBFS. IDBFS is asynchronous and may require the app to be temporarily stalled a startup for the data to be available.

fix(ApplicationDataContainer): Update WebAssembly storage to use javascript `localStorage`

---

src/Uno.UI.Tests/Windows_UI_XAML_Controls/ListViewBaseTests/Given_ListViewBase.cs
src/Uno.UI/UI/Xaml/Controls/Primitives/Selector.cs

GitHub Issue (If applicable): Fixes #534
- Bugfix
BREAKING CHANGE: The `Selector.SelectionChanged` event is now raised after the `SelectedValue`, `SelectedItem` and `SelectedIndex` properties are updated. The original behavior was incorrect.

fix(Selector): Fix SelectionChanged / SelectedItem ordering to align with UWP

---

build/PackageDiffIgnore.xml
doc/articles/features/windows-ui-xaml-application.md
src/SamplesApp/SamplesApp.Shared/App.xaml.cs
src/Uno.UI.Wasm/WasmScripts/Uno.UI.d.ts
src/Uno.UI.Wasm/WasmScripts/Uno.UI.js
src/Uno.UI.Wasm/ts/WindowManager.ts
src/Uno.UI/LinkerDefinition.Wasm.xml
src/Uno.UI/UI/Xaml/Application.wasm.cs
src/Uno.UWP/ApplicationModel/SuspendingDeferral.cs
src/Uno.UWP/ApplicationModel/SuspendingOperation.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel/SuspendingDeferral.cs

GitHub Issue (If applicable): Fixes #1165, Fixes #3120
- Feature
Enables the use of `Application.Suspending` for WebAssembly

feat(suspension): [Wasm] Add support for `Application.Suspending`

---

doc/articles/controls/MenuFlyout.md
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MenuFlyoutTests/MenuFlyout_IosNative.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MenuFlyoutTests/MenuFlyout_IosNative.xaml.cs
src/Uno.UI.Toolkit/MenuFlyoutExtensions.cs
src/Uno.UI/UI/Xaml/Controls/MenuFlyout/MenuFlyout.iOS.cs
src/Uno.UI/UI/Xaml/Controls/MenuFlyout/MenuFlyout.iOS7.iOS.cs
src/Uno.UI/UI/Xaml/Controls/MenuFlyout/MenuFlyout.iOS8.iOS.cs

GitHub Issue (If applicable): #3270
- Feature
Cancel button text can be customized with:
```xml
xmlns:toolkit="using:Uno.UI.Toolkit"
<MenuFlyout UseNativePopup="True"
toolkit:MenuFlyoutExtensions.OverrideIosCancelText="Custom cancel text">
```

feat(ios): customizable MenuFlyout cancel text

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/SourceGenerators/XamlGenerationTests/InlineElementsTest.xaml
src/SourceGenerators/XamlGenerationTests/XamlGenerationTests.csproj

GitHub Issue (If applicable): #3272
- Bugfix
Invalid code is generated when implicit content are localized.
Valid code is generated when implicit content are localized.

fix(codegen): double assignments from implicit content+localization

---

src/SamplesApp/SamplesApp.Droid/SamplesApp.Droid.csproj
src/SamplesApp/SamplesApp.Wasm/SamplesApp.Wasm.csproj
src/SamplesApp/SamplesApp.iOS/SamplesApp.iOS.csproj
src/SamplesApp/SamplesApp.macOS/SamplesApp.macOS.csproj
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/VisualStateTests/VisualState_ComplexSetters_Automated.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ScrollViewerTests/ScrollViewer_UpdatesMode.xaml
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/Uno.UI.Tests/Uno.UI.Tests.csproj
src/Uno.UI.Tests/Windows_UI_XAML_Controls/UserControlTests/Given_UserControl.cs
src/Uno.UI.Tests/Windows_UI_XAML_Controls/UserControlTests/UserControl_TopLevelBinding.xaml
src/Uno.UI.Tests/Windows_UI_XAML_Controls/UserControlTests/UserControl_TopLevelBinding.xaml.cs
src/Uno.UI.Tests/Windows_UI_XAML_Controls/UserControlTests/UserControl_TopLevelBinding_UserControl.xaml
src/Uno.UI.Tests/Windows_UI_XAML_Controls/UserControlTests/UserControl_TopLevelBinding_UserControl.xaml.cs

GitHub Issue (If applicable): Fixes #3243, Fixes #61, Fixes #3218, Fixes #153
- Bugfix
- Feature
`UserControl` instances are now placed in the visual tree by default.

UserControl fixes

---

src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/xamarinforms-wasm/.template.config/template.json

GitHub Issue (If applicable): Fixes #3285 
- Bugfix
The generated WebAssemblyhead is properly included in the existing solution.

fix(dotnet_new): Fix wasm head is not added to the existing solution

---

build/Uno.WinUI.nuspec

- Bugfix
The Uno.UI.Toolkit dependency is now defined for macOS.

fix(macOS): Uno.UI.Toolkit file is missing in nuspec

---

.vsts-ci.yml
build/ci/.azure-devops-project-template-tests.yml
build/run-template-tests.ps1

GitHub Issue (If applicable): #1876
N/A
We now do dotnet templates integration tests as part of the ci

ci: Add dotnet templates integration tests

---

src/SolutionTemplate/UnoLibraryTemplate/CrossTargetedLibrary.csproj
src/SolutionTemplate/UnoSolutionTemplate/UWP/UnoQuickStart.Uwp.csproj

GitHub Issue (If applicable): fixes #2822
- Feature
The UWP project head does not reference Uno.UI in the solution template. However, Uno.UI for UWP target contains only the Uno.UI.Toolkit reference, which is very useful to get `VisibleBoundsPadding` and other extensions, which are very commonly used and should be accessible out of the box.
From my own experience, I thought Uno.UI.Toolkit was referenced by Uno.Core, which is why I reported #2822 a while back. Referencing Uno.UI manually is a bit counterintuitive if it is not done by the template in the first place.
UWP project head and library template reference Uno.UI NuGet package.

feat: Add Uno.UI package to UWP in templates

---

build/Uno.UI.Build.csproj
src/AddIns/Uno.UI.Lottie/WasmScripts/uno-lottie.d.ts
src/AddIns/Uno.UI.Lottie/WasmScripts/uno-lottie.js
src/AddIns/Uno.UI.Lottie/ts/Uno.UI.Lottie.ts
src/Directory.Build.targets
src/Uno.UI.RuntimeTests/Tests/Windows_Storage/Given_StorageFile2.cs
src/Uno.UI.Wasm.Tests/WasmScripts/UnitTests.js
src/Uno.UI.Wasm.Tests/ts/TSBindingsTests.ts
src/Uno.UI.Wasm/WasmCSS/Uno.UI.css
src/Uno.UI.Wasm/WasmScripts/Uno.UI.d.ts
src/Uno.UI.Wasm/WasmScripts/Uno.UI.js
src/Uno.UI.Wasm/ts/WindowManager.ts
src/Uno.UI/UI/Xaml/Controls/Image/Image.wasm.cs
src/Uno.UWPSyncGenerator/DocGenerator.cs
src/Uno.UWPSyncGenerator/Generator.cs
src/Uno.UWPSyncGenerator/Helpers/ProjectLoader.cs
src/Uno.UWPSyncGenerator/Program.cs
src/Uno.UWPSyncGenerator/Uno.UWPSyncGenerator.csproj

- Bugfix
This update deals with the bootstrapper 1.3 changes to move all app content files to a versioned subfolder to avoid caching issues when deployed from a CDN. This change mainly impacts the images and splash screen resources.

fix: [Wasm] Adjust for newer bootstrapper update to include app base path

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/NavigationViewTests/NavigationView_Tests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/NavigationViewTests/Item1Page.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/NavigationViewTests/Item2Page.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/NavigationViewTests/NavigationView_BasicNavigation.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/NavigationViewTests/NavigationView_BasicNavigation.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/NavigationViewTests/SettingsPage.xaml
src/Uno.UI/UI/Xaml/Controls/ItemsControl/ItemsControl.cs

GitHub Issue (If applicable): #3148
- Bugfix
When selecting the navigationview settings item and then selecting the top menu item nothing happens and the ItemInvoked is not fired on Android. If first selecting the settings item and then the second menu item everything works as expected.
When selecting the navigationview settings item and then any menu item ItemInvoked is fired on Android.
- [X ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [X ] Contains **NO** breaking changes
- [X ] Associated with an issue (GitHub …

fix(NavigationView): unable to select first menuitem after selecting

---

build/PackageDiffIgnore.xml
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TextBlockTests/TextBlockTests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/TextBlock_FontWeight_Dynamic.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/TextBlock_FontWeight_Dynamic.xaml.cs
src/Uno.UWP/UI/Text/FontWeight.cs

fixes #3273
- Bugfix
#3273
`FontWeight.Weight` is now read/write as well as a ushort instead of an int.

fix(FontWeight): changed UI.Text.FontWeight to better reflect uwp definition

---

src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml

`ScrollBar` might not show properly
A bug in animations on WASM might cause the `ScrollBar` to be unusable in some cases, especially the WCT's `DataGrid`.
All animations are disable on WASM in the default `ScrollBar` template.
Linked issue https://github.com/unoplatform/uno/issues/3378

fix(scrollBar): Disable Animation on WASM

---

src/SamplesApp/Benchmarks.Shared/Benchmarks.Shared.projitems
src/SamplesApp/Benchmarks.Shared/Suite/Windows_UI_Xaml_Controls/DependencyPropertyBench/SimpleDPBenchmark.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/Performance/Performance_Dopes.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/Performance/Performance_Dopes.xaml.cs
src/Uno.UI/UI/Xaml/Controls/Border/Border.wasm.cs
src/Uno.UI/UI/Xaml/Controls/Canvas/Canvas.Layout.cs
src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.wasm.cs
src/Uno.UI/UI/Xaml/Controls/Grid/Grid.Layout.cs
src/Uno.UI/UI/Xaml/Controls/Panel/Panel.wasm.cs
src/Uno.UI/UI/Xaml/DependencyObjectStore.Binder.cs
src/Uno.UI/UI/Xaml/DependencyObjectStore.cs
src/Uno.UI/UI/Xaml/DependencyPropertyDetailsCollection.cs
src/Uno.UI/UI/Xaml/FrameworkElement.Layout.wasm.cs
src/Uno.UI/UI/Xaml/FrameworkElement.cs

-- Refactoring (no functional changes, no api changes)
- Move DependencyObjectStore to C# 8.0 nullable
- Change `DependencyPropertyDetailsCollection` to use an O(1) lookup
- Other minor performance updates

Improve DepencencyProperty R/W performance

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/SourceGenerators/XamlGenerationTests/CornerRadiusParse.xaml
src/SourceGenerators/XamlGenerationTests/CornerRadiusParse.xaml.cs.cs

GitHub Issue (If applicable): #3386 
- Bugfix
`CornerRadius` property with spaces can't be parsed.
`CornerRadius` property with spaces can be parsed.

fix: Corner radius parsing with spaces

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/WebView/WebView_Video_Bug546.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/WebView/WebView_Video_Bug546.xaml
src/Uno.UI/FeatureConfiguration.cs
src/Uno.UI/UI/Xaml/Controls/WebView/WebView.Android.cs

Only the sound were played in a WebView on Android, no image. The cause was the WebView control itself which were forced to render using software:
Faulty code:
``` csharp
//SetLayerType disables hardware acceleration for a single view.
//This is required to remove glitching issues particularly when having a keyboard pop-up with a webview present.
//http://developer.android.com/guide/topics/graphics/hardware-accel.html
//http://stackoverflow.com/questions/27172217/android-systemui-glitches-in-lollipop
_webView.SetLayerType(LayerType.Software, null);
```
The software mode is now opt-in using the following code:
``` csharp
#if __ANDROID__
// Use the old WebView mode
FeatureConfiguration.WebView.ForceSoftwareRendering = true;
#endif
```
Please check if your PR fulfills the following …

[Android] Remove forced software rendering for WebView

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ProgressRing/WindowsProgressRing_GH1220.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ProgressRing/WindowsProgressRing_GH1220.xaml.cs
src/Uno.UI/UI/Xaml/Controls/ProgressRing/ProgressRing.iOS.cs

Fix https://github.com/unoplatform/uno/issues/1220
When setting `Visibility=Collapsed` directly on a `<ProgressRing>` control in Xaml, it was still visible.
This was caused by the fact the `Visibility` property callback were not implemented properly.

[iOS] ProgressRing were still visible on Visibility=Collapsed

---

build/PackageDiffIgnore.xml
src/Uno.UI.RuntimeTests/Tests/Windows_Storage/Given_StorageFolder.cs
src/Uno.UWP/Storage/StorageFolder.cs

Fixes #1067, Fixes #3123
- Bugfix
- StorageFolder.CreateFileAsync(String) throws ArgumentOutOfRangeException if file already exists.
- StorageFolder.CreateFileAsync(String, CreationCollisionOption.ReplaceExisting) behaves like OpenIfExists
- StorageFolder.CreateFileAsync(String) throws Exception if file already exists. (As per UWP)
- StorageFolder.CreateFileAsync(String, CreationCollisionOption.ReplaceExisting) behaves correctly

StorageFolder.CreateFileAsync(...) fixes

---

doc/articles/features/progressring.md
doc/articles/toc.yml
src/Uno.UI/Microsoft/UI/Xaml/Controls/ProgressRing/ProgressRing.cs

GitHub Issue (If applicable): #3196 
Documentation of ProgressRing.
Also added a visual notification when `Uno.UI.Lottie` is not present.

docs(progressring): Improve the documentation of ProgressRing (WinUI)

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_CornerRadiusConverter.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_ThicknessConverter.cs
src/Uno.UI/UI/Xaml/CornerRadiusConverter.cs
src/Uno.UI/UI/Xaml/ThicknessConverter.cs

GitHub Issue (If applicable): closes #3386 
- Feature
Spaces are not supported for splitting values in thickness/corner radius type converter.
- Spaces are supported
- XAML parser uses general whitespace splitting for thickness/corner radius.

Support spaces in Thickness and CornerRadius type converters

---

src/Uno.UI.Tests/DependencyProperty/Given_DependencyProperty.cs
src/Uno.UI/UI/Xaml/DependencyObjectStore.cs

Setting a DP within the property changed callback of another DP that was set by a Style, was causing the first DP to also be set with style-level precedence. Fix so that nested DP changes are applied with the usual precedence, per UWP.
GitHub Issue (If applicable): fixes #3398 
- Bugfix

fix(style): Fix property set not applied within callback from style application

---

doc/articles/features/windows-storage.md
doc/articles/toc.yml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/Basic_Shapes.xaml.cs
src/Uno.UI.Wasm/WasmScripts/Uno.UI.d.ts
src/Uno.UI.Wasm/WasmScripts/Uno.UI.js
src/Uno.UI.Wasm/ts/Windows/Storage/StorageFolder.ts
src/Uno.UI/LinkerDefinition.Wasm.xml
src/Uno.UWP/Storage/StorageFolder.cs
src/Uno.UWP/Storage/StorageFolder.wasm.cs

GitHub Issue (If applicable): fixes #3389, fixes #3384
- Bugfix
This PR fixes:
- Fix invalid multiple IDBFS initialization for persisted folders
- Fix synchronize StorageFolder async operations with IDBFS initialization

[Wasm] Adjust IDBFS implementation

---

src/SolutionTemplate/UnoSolutionTemplate/Droid/Properties/AndroidManifest.xml
src/SolutionTemplate/UnoSolutionTemplate/Droid/UnoQuickStart.Droid.csproj

GitHub Issue (If applicable): closes #3457
- Feature
SDK 26 is referenced in Android project template manifest
- SDK 29 in manifest
- TargetFrameworkVersion set to 10.0

feat: Update Android project template to SDK 29

---

build/run-template-tests.ps1
src/SolutionTemplate/UnoSolutionTemplate/Droid/MainActivity.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs

Fix: #1120
- Bugfix
- DotNet templates integration tests now validate MSBuild exit codes
- UnoSolutionTemplate.Droid fully qualifies Uno.UI.ActivityHelper.AllConfigChanges
- XamlGenerator fully qualifies more symbols

fix: Fully qualify some symbols

---

build/PackageDiffIgnore.xml
src/Uno.UWP/Devices/Sensors/Accelerometer.unsupported.cs
src/Uno.UWP/Devices/Sensors/Barometer.unsupported.cs
src/Uno.UWP/Devices/Sensors/Gyrometer.unsupported.cs
src/Uno.UWP/Devices/Sensors/HingeAngleSensor.unsupported.cs
src/Uno.UWP/Devices/Sensors/Magnetometer.unsupported.cs
src/Uno.UWP/Devices/Sensors/Pedometer.unsupported.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Devices.Sensors/Accelerometer.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Devices.Sensors/Barometer.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Devices.Sensors/Gyrometer.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Devices.Sensors/HingeAngleSensor.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Devices.Sensors/Magnetometer.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Devices.Sensors/Pedometer.cs

GitHub Issue (If applicable): closes #3450 
- Feature
All sensor methods throw on unsupported platforms.
`GetDefault` and `GetDefaultAsync` static methods of various sensors now return `null` when the sensor is not supported on target platform (mainly macOS, NET461, but also WASM and iOS in some cases). This way it is easier to write code that uses sensors, as the behaviour matches the case when the device does not have the given sensor available on UWP, and such check must be part of the consuming code anyway.

feat: Sensors return null on unsupported platforms

---

src/Uno.UI/UI/Xaml/Media/CompositionTarget.Android.cs
src/Uno.UI/UI/Xaml/Media/CompositionTarget.iOS.cs

Possible source changed while enumerating exception in the `CompositionTarget.Rendering` event
If you remove an handler while the  `CompositionTarget.Rendering` event is raised, you will get an exception.
We clone the list of handler before raising the event

fix: Prevent possible collection changed while enumerating in CompositionTarget.Rendering

---

doc/articles/Uno-UI-Performance.md
src/SamplesApp/SamplesApp.Droid/MainActivity.cs
src/SamplesApp/SamplesApp.Shared/App.xaml.cs
src/SamplesApp/SamplesApp.UITests/SampleControlUITestBase.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TextBlockTests/TextBlockTests.cs
src/SamplesApp/SamplesApp.Wasm/WasmScripts/TestRunner.js
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/TextBlock_BrushColorChanging.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/TextBlock_BrushColorChanging.xaml.cs
src/Uno.UI/Mock/Brush.net.cs
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.cs
src/Uno.UI/UI/Xaml/Media/Brush.iOSmacOS.cs
src/Uno.UI/UI/Xaml/Media/Brush.wasm.cs

- Feature
The following block now updates the color of the TextBlock properly:
```xaml
<TextBlock Text="My Text">
<TextBlock.Foreground>
<SolidColorBrush Color="{x:Bind Color, Mode=OneWay, FallbackValue=Red}" />
</TextBlock.Foreground>
</TextBlock>
```

feat: Add support for TextBlock.Foreground update on SolidColorBrushColor changes

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/TextBlock_HorizontalTextAlignment.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/TextBlock_HorizontalTextAlignment.xaml.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/TextBlock.cs
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.cs

Fix https://github.com/unoplatform/uno/issues/3471
`HorizontalTextAlignment` were not supported by Uno, only `TextAlignment`.

TextBlock: Added support for HorizontalTextAlignment

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/TextBlock_BrushColorChanging.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/Path_Geometries.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/Path_Geometries.xaml.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/GridViewHeaderItem.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/ProgressRing.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/ScrollViewer.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/TextBlock.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/WebView.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Media.Animation/CircleEase.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Media.Animation/ColorAnimationUsingKeyFrames.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Media.Animation/ColorKeyFrame.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Media.Animation/ColorKeyFrameCollection.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Media.Animation/DiscreteColorKeyFrame.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Media.Animation/EasingColorKeyFrame.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Media.Animation/FadeInThemeAnimation.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Media.Animation/FadeOutThemeAnimation.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Media.Animation/LinearColorKeyFrame.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Media.Animation/PointKeyFrame.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Media.Animation/SplineColorKeyFrame.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Resources/CustomXamlResourceLoader.cs
src/Uno.UI/UI/Xaml/Media/Animation/CircleEase.cs
src/Uno.UI/UI/Xaml/Media/Animation/EasingFunctionBase.cs
src/Uno.UI/UI/Xaml/Media/Animation/SineEase.cs
src/Uno.UI/UI/Xaml/Shapes/Path.wasm.cs
src/Uno.UI/Uno.UI.csproj
src/Uno.UWP/Generated/3.0.0.0/Windows.Devices.Input/KeyboardCapabilities.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Networking/HostNameType.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.UI.Input/RightTappedEventArgs.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.UI.Input/TappedEventArgs.cs

When using geometries in a Path on Wasm, they are getting serialized as a _path data_ string by [this code](https://github.com/unoplatform/uno/blob/a97622505cea5180d9943965e73b099ca028264d/src/Uno.UI/UI/Xaml/Shapes/Path.wasm.cs#L51_L97). It was generating code using culture-dependant decimal separator.
The fix was to generate the string using culture-independant serialization.
- [X ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

[WASM] Fixed path with geometries

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/HitTest_Shapes_Tests.cs
src/SamplesApp/UITests.Shared/Windows_UI_Input/PointersTests/HitTest_Shapes.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Input/PointersTests/HitTest_Shapes.xaml.cs
src/Uno.UI.Wasm/WasmScripts/Uno.UI.js
src/Uno.UI.Wasm/ts/WindowManager.ts

GitHub Issue: _private cf. below_
On WASM the `PointerRoutedEventArgs.OriginalSource` is a Uno's internal element.
On WASM, when interacting with a `Shape` the `PointerRoutedEventArgs.OriginalSource` is the internal `SvgElement`.
We are now navigating up to the `<svg />` elemnt which is the XAML `Shape`

fix(pointers): [WASM] Fix the original source of the pointer events on shapes

---

.vsts-ci.yml
build/Uno.WinUI.RemoteControl.nuspec
src/Uno.UI.RemoteControl.Host/Uno.UI.RemoteControl.Host.csproj

GitHub Issue (If applicable): Fixes #3469
- Bugfix
Updates the dependency on .NET Core 2.2 to .NET Core 3.1 for the RemoteControl server for Hot Reload support.

fix: Update RemoteControl server to netcoreap 3.1

---

build/gitpod/serve-sampleapp-wasm.sh

- Bugfix
Launching `build/gitpod/serve-sampleapp-wasm.sh` now serves the application properly in GitPod.

fix: Adjust gitpod serve script

---

src/Uno.UI.Tests/BinderTests/Given_Binder.inpc.cs
src/Uno.UI/DataBinding/BindingPath.cs
src/Uno.UI/FeatureConfiguration.cs

GitHub Issue (If applicable): Fixes #3447, Fixes #773
- Bugfix
- Feature
- Adds support for INPC update if the notified property has not changed (but some of its children did)
- Adds support for all properties updated through INPC(String.Empty)

Fix INPC equality comparison, add support for INPC(String.Empty)

---

build/android-uitest-run.sh
build/ci/.azure-devops-ios-tests.yml
build/ci/templates/nuget-cache.yml
build/ios-uitest-run.sh
src/SamplesApp/SamplesApp.UITests.Generator/SnapShotTestGenerator.cs
src/SamplesApp/SamplesApp.UITests/SamplesApp.UITests.csproj

Adds an explicit timeout for the test runner on iOS and Android.

ci: Add explicit timeout for all UI tests

---

src/SolutionTemplate/UnoSolutionTemplate/Shared/UnoQuickStart.Shared.projitems

The default template produces a warning on the Droid project: @(Content) build action is not supported ... Shared\Assets\SharedAssets.md
This fixes the issue by changing the build action on SharedAssets.md from Content to None.
GitHub Issue (If applicable): #3095 
- Bugfix
The default template sets the build action on SharedAssets.md to Content.
The default template sets the build action on SharedAssets.md to None.
- [n/a] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [n/a] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-dev …

fix: SharedAssets.md build action is not supported

---

doc/articles/features/windows-system-display.md
doc/articles/toc.yml
src/Uno.UI.Wasm/WasmScripts/Uno.UI.d.ts
src/Uno.UI.Wasm/WasmScripts/Uno.UI.js
src/Uno.UI.Wasm/ts/Windows/System/Display/DisplayRequest.ts
src/Uno.UWP/Generated/3.0.0.0/Windows.System.Display/DisplayRequest.cs
src/Uno.UWP/System/Display/DisplayRequest.cs
src/Uno.UWP/System/Display/DisplayRequest.wasm.cs

GitHub Issue (If applicable): closes #3452 
- Feature
`DisplayRequest` not supported on WASM
`DisplayRequest` supported on WASM.

feat: DisplayRequest on WASM

---

build/ci/.azure-devops-screenshot-compare.yml
src/SamplesApp/SamplesApp.UITests.Generator/SnapShotTestGenerator.cs
src/SamplesApp/SamplesApp.UITests/SampleControlUITestBase.cs
src/SamplesApp/SamplesApp.UITests/TestFramework/AutoRetry.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/MenuFlyoutTests/MenuFlyoutTests.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TextBlockTests/TextBlockTests.cs
src/Uno.UI.TestComparer/Program.cs

- Bugfix
UI Tests failing on timeout are properly restarted using the provided timeout for each retry.

Adjust UI Tests timeout handling

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/TextBlock_IsTextSelectionEnabled.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/TextBlock_IsTextSelectionEnabled.xaml.cs
src/Uno.UI.Wasm/WasmCSS/Uno.UI.css
src/Uno.UI.Wasm/WasmScripts/Uno.UI.d.ts
src/Uno.UI.Wasm/WasmScripts/Uno.UI.js
src/Uno.UI.Wasm/ts/WindowManager.ts
src/Uno.UI.Wasm/tsBindings/WindowManagerSetUnsetClassesParams.ts
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/TextBlock.cs
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.cs
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.wasm.cs
src/Uno.UI/UI/Xaml/UIElement.wasm.cs
src/Uno.UI/UI/Xaml/WindowManagerInterop.wasm.cs

Fix https://github.com/unoplatform/uno/issues/3446
`IsTextSelectionEnabled` is not working for `<TextBlock />` on WASM.

[WASM] Support for TextBlock.IsTextSelectionEnabled

---

src/Uno.UWP/Storage/StorageFolder.wasm.cs

GitHub Issue (If applicable): fixes #3521
- Bugfix
The initialization may fail using AOT, which validates against native interop invocations of static methods, which the interpreter does not do.
Related mono issue https://github.com/mono/mono/issues/20104

[Wasm] Fix AOT StorageFolder incorrect initialization

---

.vsts-ci.yml
build/ci/templates/nuget-cache.yml
build/ios-uitest-run.sh
src/SamplesApp/SamplesApp.Shared/App.xaml.cs
src/SamplesApp/SamplesApp.UITests/Constants.cs
src/SamplesApp/SamplesApp.UITests/SamplesApp.UITests.csproj

- Update to latest Xcode, mono (Xcode 11.5, Mono 6.10)
- Disable package caching (It takes more time than restoring the files using a normal nuget restore)
- Restarting iOS simulator before retrying failed tests (Clean environment for Xamarin.UITest)
- Downgrade Xamarin.,UITest to 3.0.7 to work around a timing issue (3.0.8-dev1 issue)
- Add an iOS dispatcher WatchDog for the SamplesApp (Auto kill for https://github.com/unoplatform/uno/issues/3363)

ci: Update to latest Xcode, mono.

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/Ellipse_StrokeThickness.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/Ellipse_StrokeThickness.xaml.cs
src/Uno.UI/UI/Xaml/Shapes/ArbitraryShapeBase.wasm.cs
src/Uno.UI/UI/Xaml/Shapes/Ellipse.wasm.cs

Rendering of `<Ellipse>` on Wasm when a `StrockThickness` were used were producing strange results.
As illustrated in the snippet on the Playground: https://playground.platform.uno/#49ff79fb
Same code on XAML Studio (on UWP):

[Wasm] Fixed rendering of Ellipses when the Stroke is used

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/HitTest_Image_Tests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Input/PointersTests/HitTest_Image.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Input/PointersTests/HitTest_Image.xaml.cs
src/Uno.UI.Wasm/WasmScripts/Uno.UI.js
src/Uno.UI.Wasm/ts/WindowManager.ts

GitHub Issue: _private, cf. below_
The `PointerRoutedEventArgs.OriginalSource` is an internal element while over an `Image`
The `PointerRoutedEventArgs.OriginalSource` is the internal `HtmlImage` instead of the `Image`
The `PointerRoutedEventArgs.OriginalSource` is now the `Image` as WinUI

fix(pointers): [WASM] Fix the OriginalSource of pointer events for Image

---

src/Uno.UI/UI/Xaml/Media/PointCollection.cs
src/Uno.UI/UI/Xaml/Media/PointCollection.wasm.cs
src/Uno.UI/UI/Xaml/Shapes/Polygon.cs
src/Uno.UI/UI/Xaml/Shapes/Polygon.wasm.cs
src/Uno.UI/UI/Xaml/Shapes/Polyline.cs
src/Uno.UI/UI/Xaml/Shapes/Polyline.wasm.cs

GitHub Issue: _private, cf. below_
Fix support of `null` in the `Poly<gon|line>.Points` property.
Causes a `NullReferenceException`.
🙃

fix(shapes): [WASM] Fix to properly support null Points in Poly[gon|line]

---

src/Uno.UI/UI/Xaml/Controls/Grid/Grid.Layout.cs

The `stackalloc` clauses has been move out of loops to prevent leaks, per Standard ECMA-334 Standard december 2001, section 25.7.

Wasm-Perf: Removed usage of `stackalloc` in loops

---

src/Uno.UI.Toolkit/ElevatedView.cs

Fixes https://github.com/unoplatform/uno/issues/3563
When the background were changed from `null` to a value, the elevation were not updated properly.

fix(elevatedview): ElevatedView were not working all the time

---

src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePicker.md
src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml

GitHub Issue (If applicable): #3606
- [IOS] Timepicker is not visible in dark mode
- [IOS] Timepicker is now visible in dark mode

fix(timePicker): [IOS] Timepicker is now visible in dark mode

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/BrushesTests/Brushes_ImplicitConvert.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/BrushesTests/Brushes_ImplicitConvert.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/BrushesTests/ColorPresenter.cs
src/Uno.UI.Toolkit/Uno.UI.Toolkit.csproj
src/Uno.UI/DataBinding/BindingPropertyHelper.FastConvert.cs

Fix https://github.com/unoplatform/uno/issues/3558
Using a `<Color>` resource in a `<Style>` setter on a `SolidColorBrush` property were not supported on Uno, but works on UWP.
I works.

Style resources now auto-convert Color to SolidColorBrush

---

src/SamplesApp/UITests.Shared/Toolkit/ElevationView_Clipping.xaml
src/SamplesApp/UITests.Shared/Toolkit/ElevationView_Clipping.xaml.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/Uno.UI.Toolkit/ElevatedView.cs
src/Uno.UI.Toolkit/UIElementExtensions.cs
src/Uno.UI.Toolkit/Uno.UI.Toolkit.Wasm.csproj
src/Uno.UI/UI/Xaml/Controls/ContentControl/ContentControl.Layout.cs

Fix https://github.com/unoplatform/uno/issues/3563 (wasm part)
The multi-targetted code to handle the clipping in the `ContentControl` were not properly compiled on all platforms.

[Wasm] ContentControl Clipping were not incorrect

---

src/Uno.UI/UI/Xaml/UIElement.macOS.cs

GitHub Issue: _private, cf. below_
Implement clipping for MacOS
`SplitView` in compact mode does hide the content
Content is visible!

feat(macos): [MacOS] Add clipping support

---

src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.macOS.cs

GitHub Issue: _private, cf. below_
Add support of the reveal button for macOS
Reveal button does nothing
🙃

feat(passwordBox): [MacOS] Add support of the reveal button

---

build/android-uitest-run.sh
src/SamplesApp/SamplesApp.UITests/RuntimeTests.cs
src/Uno.UI.RuntimeTests/Tests/Windows_Storage/Streams/Given_DataReader.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml/FrameworkElement.cs
src/Uno.UI/UI/Xaml/FrameworkElement.cs
src/Uno.UI/UI/Xaml/IFrameworkElementImplementation.Android.tt
src/Uno.UI/UI/Xaml/IFrameworkElementImplementation.iOS.tt
src/Uno.UI/UI/Xaml/IFrameworkElementImplementation.macOS.tt

GitHub Issue (If applicable): fixes #3616
- Bugfix
Mark `FrameworkElement.Tag` as implemented, it's a simple property that was already working properly.

fix: Mark FrameworkElement.Tag as implemented

---

src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Helper/ThicknessHelper2.cs
src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.cs
src/SamplesApp/SamplesApp.UnitTests.Shared/SamplesApp.UnitTests.Shared.projitems

GitHub Issue (If applicable): fixes #3487 
- Bugfix
RuntimeTests crash on UWP.
RuntimeTests don't crash on UWP.

fix: ThicknessHelper crash in UWP runtime tests

---

src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/ProgressRing.cs
src/Uno.UI/UI/Xaml/Controls/ProgressRing/ProgressRing.cs

- Bugfix
`ProgressRing.TemplateSettings` does not raise an exeption on `netstandard2.0` platforms.

fix(reg): ProgressRing TemplateSettings was incorrectly removed from netstd2.0

---

src/Uno.UI.Tests/Windows_UI_XAML_Controls/GridTests/Given_Grid.cs
src/Uno.UI.Tests/Windows_UI_XAML_Controls/TextBlockTests/Given_TextBlock.cs
src/Uno.UI/UI/Xaml/Controls/Grid/Grid.Layout.cs
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.cs

- Bugfix
`RowSpan` calculation was incorrect, leading to incorrect layout for `ToggleSwitch` templates.

fix(reg): Restore grid spans reset

---

src/Uno.UI/UI/Xaml/Application.macOS.cs
src/Uno.UWP/Helpers/DeviceHelper.macOS.cs

GitHub Issue (If applicable): fixes #3619
- Bugfix
Theme changes at runtime crash macOS app.
Theme observing works.

fix: macOS ApplicationTheme observing

---

.mergify.yml

Disable strict mode for mergify, as it's quite rare that build issues happen as a result of a non-conflicting merge. 
`Ready to merge` PRs will be merged as soon as checks are passed.

ci: Disable strict merge

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Media/GeometryTests/UnoSamples_Tests.ClosedFigurePage.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Media/GeometryTests/UnoSamples_Tests.LineSegmentPage.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/Geometry/ClosedFigurePage.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/Geometry/ClosedFigurePage.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/Geometry/LineSegmentPage.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/Geometry/LineSegmentPage.xaml.cs
src/Uno.UI/UI/Xaml/Media/GeometryHelper.cs
src/Uno.UI/UI/Xaml/Shapes/ArbitraryShapeBase.wasm.cs
src/Uno.UI/UI/Xaml/Shapes/Path.wasm.cs

GitHub Issue (If applicable): partially #3561
- Feature
- `PathFigure.IsClosed` is not respected on Android, iOS and macOS
- Runtime changes to `PathSegment` on WASM are not applied
- `PathFigure.IsClosed` is respected on Android, iOS and macOS
- Runtime changes to `PathSegment` on WASM are applied

Path - close on Android/iOS/macOS, react to changes on WASM

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TimePicker/TimePicker_TimePickerFlyoutStyle.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TimePicker/TimePicker_TimePickerFlyoutStyle.xaml.cs
src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePicker.cs
src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerFlyout.iOS.cs
src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml

GitHub Issue (If applicable): fixes #3606
- Bugfix
- Feature
- To update the TimePickerFlyoutPresenter Style in IOS it is necessary to change the default style affecting all TimePicker in app
- Fix-Light mode ios timepicker's background is black
- TimePickerFlyoutPresenter Style can now be set in IOS, allowing for customization of a specific TimePicker's flyout
- Fix-Light mode ios timepicker's background is appropriate to app theme

feat: IOS TimePicker flyout styling

---

src/Uno.UI.Toolkit/ElevatedView.cs
src/Uno.UI.Toolkit/Themes/Generic.xaml
src/Uno.UI.Toolkit/UIElementExtensions.cs
src/Uno.UI.Toolkit/Uno.UI.Toolkit.csproj

Using `<ElevatedView />` on UWP with Rounded Corners were producing strange results.
Fixed

Added support for Round Corners on UWP for ElevatedView

---

src/Uno.UWP/UI/Core/CoreDispatcher.cs

- Bugfix
`RunAsync` with cancellation token may fail because of a null reference.
The race condition has been addressed.

fix: Race condition in CoreDispatcher.RunAsync

---

build/Uno.WinUI.Lottie.nuspec
build/Uno.WinUI.RemoteControl.nuspec
build/Uno.WinUI.Skia.Gtk.nuspec
build/Uno.WinUI.Skia.Wpf.nuspec
build/Uno.WinUI.WebAssembly.nuspec
build/Uno.WinUI.nuspec

- Bugfix
Builds may fail with dependency object implementation not being found:
```
##[error]InteractionEffectBase.cs(9,59): Error CS0535: 'InteractionEffectBase' does not implement interface member 'DependencyObject.GetValue(DependencyProperty)'
```
Nuget version 5.0 is now required since the introduction of the `buildTransitive` nuget folder.

ci: Set nuspec min version to 5.0

---

src/SamplesApp/SamplesApp.Skia.Gtk/Properties/launchSettings.json
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Native_View.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/NativeViewPage/NativeViewIFrameworkElement.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/NativeViewPage/NativeView_Page.xaml
src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.cs
src/Uno.UI/UI/Xaml/Media/VisualTreeHelper.cs

- Bugfix
Internal Native elements hosted in `ContentPresenter` do not get the templated parent propagated properly.
Native elements are now managed in a specific way in `ContentPresenter` for templated parent propagation
Internal Issue (If applicable): fixes https://github.com/unoplatform/private/issues/160

Fix invalid templated parent for wrapped internal native views

---

build/android-uitest-build.sh
build/ci/.azure-devops-ios-tests.yml
build/ci/.azure-devops-screenshot-compare.yml
build/ios-uitest-build.sh
build/ios-uitest-run.sh
doc/articles/uno-development/building-uno-macos.md
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Shapes/Basics_Shapes_Tests.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/Basic_Shapes.xaml.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Shapes/When_Rectangle.cs
src/Uno.UI/UI/Xaml/Shapes/Shape.layout.cs

GitHub Issue (If applicable): fixes https://github.com/unoplatform/private/issues/163
- Bugfix
Slider, and other controls using shapes without constraints are displayed using their parent's given available size, where it should be zero.
The new measured size respects the original behavior.

fix: Adjust unbounded relative shapes measure

---

src/Uno.UI.Tests/Windows_UI_XAML_Controls/CanvasTests/Given_Canvas.cs
src/Uno.UI/UI/Xaml/Controls/Canvas/Canvas.cs

GitHub Issue (If applicable): Fixes https://github.com/unoplatform/uno/issues/3622
- Bugfix
`Canvas.[Top|Left|ZIndex]` property auto convert incoming values to the `double`.
- [x ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)

fix(reg): missing auto-convert in Canvas properties

---

doc/articles/interop/wasm-javascript-1.md
src/Uno.UI.Runtime.WebAssembly/Xaml/UIElementWasmExtensions.cs
src/Uno.UI/UI/Xaml/WindowManagerInterop.wasm.cs

Added the ability to do `.GetHtmlAttribute()` on an UIElement on Wasm. This feature has been lost in the recent changes to create new _uno runtimes_.

feat(wasm): Added .GetHtmlAttribute() for an Element on Wasm.

---

build/ci/.azure-devops-ios-tests-run.yml
build/ci/.azure-devops-ios-tests.yml
build/ci/.azure-devops-screenshot-compare.yml
build/ci/templates/optimize-roslyn-mono.yml
build/ios-uitest-run.sh
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ListViewTests/UnoSamples_Tests.ListView.cs

Splits the iOS UI Tests in three groups to lower the execution time in case of UI test automation failure.

Split iOS Automated tests

---

src/Directory.Build.props

- Bugfix
This change will remove the untracked sources in SourceLink support, as this causes significant build performance issues. (https://github.com/mono/linker/issues/1409)

fix(perf):  Disable SourceLink untracked sources

---

src/SamplesApp/SamplesApp.UITests/Toolkit/UnoSamples_Tests.ElevatedView.cs
src/SamplesApp/UITests.Shared/Toolkit/ElevatedView_Dimensions.xaml
src/SamplesApp/UITests.Shared/Toolkit/ElevatedView_Dimensions.xaml.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/Uno.UI.Toolkit/ElevatedView.cs

Fixes https://github.com/unoplatform/uno/issues/3564
`<ElevatedView>` constrained size were not applied properly.
Size constains is not applied on the `.Arrange()` phage.

[Wasm] Fixed ElevatedView with constrained size

---

src/SamplesApp/UITests.Shared/Toolkit/ElevatedViewTests.xaml
src/Uno.UI.Toolkit/ElevatedView.cs

The default shadowcolor property of ElevatedView on Android 9+ is too light
The default shadowcolor property of ElevatedView on Android 9+ is now a bit darker to match on the other platforms and android 8 and lower

fix: Change default ShadowColor Property on ElevatedView for Android 9+

---

src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/ImageBrushTests/ImageBrush_WriteableBitmap.xaml.cs
src/Uno.UI/UI/Xaml/FrameworkElement.Interface.wasm.cs
src/Uno.UI/UI/Xaml/Media/ImageBrush.wasm.cs
src/Uno.UI/UI/Xaml/Media/ImageSource.cs

Fixes https://github.com/unoplatform/private/issues/168
Better support for `<ImageBrush />` on Wasm. Not 100% accurate with UWP/WinUI, but the stretch will behave.

[Wasm] Slightly improved ImageBrush image positionning on Wasm.

---

src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerFlyout.iOS.cs

GitHub Issue (If applicable): #3541 
- Bugfix
`TimePicker.ClockIdentifier` is getting overwritten by os default once the flyout is shown.
`TimePicker.ClockIdentifier` doesnt get overwritten by os default once the flyout is shown.
`TimePickerSelector.ClockIdentifier`'s default value is getting sync onto `TimePickerFlyout` because of the two-way binding.

fix(ios): TimePicker ClockIdentifier getting overwritten

---

src/Uno.UI/UI/Xaml/Media/AcrylicBrush/AcrylicBrush.cs

- Bugfix
Acrylic is by default applied.
Acrylic is by default not applied.

chore: Use fallback on Acrylic on non-WASM targets

---

src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/AutoSuggestBoxTests/BasicAutoSuggestBox.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/AutoSuggestBoxTests/BasicAutoSuggestBox.xaml.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/AutoSuggestBoxTextChangedEventArgs.cs
src/Uno.UI/UI/Xaml/Controls/AutoSuggestBox/AutoSuggestBox.cs
src/Uno.UI/UI/Xaml/Controls/AutoSuggestBox/AutoSuggestBoxTextChangedEventArgs.cs

* Using `TextMemberPath` were causing internal exceptions in the `<AutoSuggestBox>`
* The `.CheckCurrent()` method on `AutoSuggestBoxTextChangedEventArgs` were not implemented.

Fixed bugs in AutoSuggestBox when using TextMemberPath

---

build/ios-uitest-run.sh
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ScrollBarTests/UnoSamples_Tests.ScrollBar.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ScrollViewerTests/Hosted_ScrollViewer.Automated.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ScrollViewerTests/Hosted_ScrollViewer.xaml
src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.cs

fixes https://github.com/unoplatform/uno/issues/3704
fixes https://github.com/unoplatform/private/issues/167
This commit removes a fix (https://github.com/unoplatform/uno/commit/fe83e99a  - https://github.com/unoplatform/uno/pull/607) that was made to avoid adding the same element twice in the visual tree.
We tried to run the sample that was made to validte this fix, and apprently it is no longer relevant.
When we set the `Content` of a `ScrollViewer` we make sure to **not** propagate the `TemplatedParent` (so it can have its own `TemplatedParent`). This results to reset the `Parent` property to `null` which causes the view to be recycled under certain circumstances.
But some controls like the `CheckBox` are self-cleaning themselves on recyling (for the `CheckBox` for instance they …

fix: Some controls might be recycled on creation

---

src/Uno.UI/WasmCSS/Uno.UI.css

Setting a `Padding` on a `<TextBlock>` on Wasm were not applied because of [an `!important` clause in the Uno.UI.css](https://github.com/unoplatform/uno/blob/a795eb779cd672c8d34c88ea65d921d0075889dc/src/Uno.UI/WasmCSS/Uno.UI.css#L29).
Just removed that `!important` clause.
https://nventive.visualstudio.com/Uno%20Gallery/_workitems/edit/191222

[Wasm] Setting a Padding on TextBlock on Wasm were not working

---

src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml

The default style of the `SplitView` result in invalid states when switching between Compact and Normal mode 
If you 
1. Launch app with `NavigationView`
1. Resize window to minimum width
1. Close the `NavigationView`
1. Maximize the window
1. Open the `NavigationView`
1. Notice that the `NavigationView` is blank
OR
1. Launch app
1. Close the `NavigationView`
1. Resize window to minimum width
1. Maximize the window
1. Notice that the compact `NavigationView` is blank
It works ... at least when displayed on left.
This is only a temporary fix. The real fix is to fully support the WinUI `SPlitView` style: https://github.com/unoplatform/uno/issues/3747
Internal Issue: https://nventive.visualstudio.com/_workitems/edit/190689

fix(splitView): SplitViewStyle

---

src/Uno.UI/WasmScripts/Uno.UI.d.ts
src/Uno.UI/WasmScripts/Uno.UI.js
src/Uno.UI/ts/WindowManager.ts

Possible null ref when dispatching **deferred** pointer leave on FF
We defer the dispatch of the pointer leave on FF under certain circumstances, but we relly on the `evt.currentTarget` which is available only while in the pointer handler.
We manually keep a reference on the `currentTarget` and make sure to dispatch to it.

fix(pointers): Fix possible null ref on FF when defering leave

---

src/Uno.UI/Media/NativeRenderTransformAdapter.iOSmacOS.cs

The `RenderTransform` is not applied on macOS views when they are set before rendering the elment.
When a `RenderTransform` is set on a `NSView` it's synchronously set on the `NSView.Layer.Transform`. But this cause a bug on Mac OS and the transform is never applied to the view.
We wait for the next dispatcher loop after the control has been loaded to set the `NSView.Layer.Transform`.
Note: We hide the control while deferring in order to avoid flickers.
Internal Issue: https://nventive.visualstudio.com/_workitems/edit/191447

fix(transform): [MacOS] Fix transform not applied

---

src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.cs

Fix regression introduced by https://github.com/unoplatform/uno/pull/3738
When starting the Gallery project at commit 932e368, the app is stuck on the splashscreen on iOS
This is only a temporary fix to unblock project, but we should investigate to properly understand the root cause https://github.com/unoplatform/uno/issues/3762

fix(reg): [iOS] Fix possible cyclic visual tree

---

src/Uno.UI/UI/Xaml/Controls/NavigationView/NavigationView.cs

GitHub Issue https://github.com/unoplatform/uno/issues/3774
The back button of the `NavigationView` stays hidden when the menu is light dismissed
Using the `NavigationView`, when you navigate to a page the back button appears.
If you open the menu, then **light dismiss** it (clicking the burger menu button again does not reproduce the issue), then the back button stays hidden.
This is because when the OnSplitViewClosedCompactChanged callback is invoked (registered on SplitView.IsPaneOpen), the two-way binding between SplitView.IsOpen and NavView.IsPaneOpen has not been updated yet, the the local NavView.IsPaneOpen is still == true.
The button is re-updated when the local `IsPaneOpen` is updated by the 2-way binding.
This is only a workaround to hide the real bug …

fix(navView): Back button visiblity not updated properly

---

src/Uno.Foundation/Metadata/ApiInformation.cs
src/Uno.UI/UI/Xaml/Application.cs

GitHub Issue (If applicable): Fixes https://github.com/unoplatform/uno/issues/3801
- Bugfix
This change avoids relying on APIs performing stack crawling on Wasm AOT.
- [x ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).

fix: [Wasm] Don't use Assemly.Load in ApiInformation

---

src/SourceGenerators/Uno.UI.SourceGenerators/BindableTypeProviders/BindableTypeProvidersGenerationTask.cs

- Bugfix
The `XamlControlsResources` is referenced by the Metadata generation tool, because the type inherits from `DependencyObject`.
All `ResourceDictionary` inheriting types are removed from the Metadata Generation pass; those are databound.

fix: Exclude ResourceDictionary to improve linkability of `XamlControlsResources`

---

src/Uno.UI/Media/NativeRenderTransformAdapter.iOSmacOS.cs

Fix support of `RenderTransformOrigin` on macOS.
When configuring a `RenderTransformOrigin` different of (0,0) before the load, the element was misaligned.
The origin is deferred with the transform itself.

fix(transforms): [MacOS] Fix support of RenderTransformOrigin

---

src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.Droid/BlankApp.Droid.csproj
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.Droid/Properties/AndroidManifest.xml
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.Shared/App.xaml
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.UWP/BlankApp.Uwp.csproj
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.Wasm/BlankApp.Wasm.csproj
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.iOS/BlankApp.iOS.csproj
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.macOS/BlankApp.macOS.csproj

this is just a fix to the templates for Prism
Updates Prism Templates
- Android project csproj and manifest target different API versions
- Android project for Prism template is still targeting Android 9, where the standard template targets Android 10
- Prism template still targeting old CI package. 
- Android project csproj and manifest target the same API versions
- Android project for the Prism template now targets Android 10 like the standard template
- Prism Package References updated to use the latest preview on NuGet.org
n/a
n/a

Prism template update

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/Uno.UWP/ApplicationModel/Resources/ResourceLoader.cs

- Bugfix
```
g_log_disabled    @    goutput.c:189
mono_arch_unwind_frame    @    exceptions-wasm.c:47
arch_unwind_frame    @    mini-exceptions.c:462
mono_find_jit_info_ext    @    mini-exceptions.c:650
unwinder_unwind_frame    @    mini-exceptions.c:771
mono_walk_stack_full    @    mini-exceptions.c:1331
mono_walk_stack_with_ctx    @    mini-exceptions.c:1192
mono_runtime_walk_stack_with_ctx    @    mini-exceptions.c:1169
mono_stack_walk_no_il    @    loader.c:1719
mono_runtime_get_caller_from_stack_mark    @    icall.c:1802
ves_icall_System_AppDomain_LoadAssembly    @    appdomain.c:2905
ves_icall_System_AppDomain_LoadAssembly_raw    @    icall-def.h:198 …
```

fix: Reduce the use of `Assembly.Load` during startup

---

src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml
src/Uno.UI/UI/Xaml/Style/Generic/SystemResources.xaml

GitHub Issue (If applicable): #3556
Dark mode textbox background is white and foreground is black, when focused
Dark mode textbox background and foregorund remain the proper background color

fix(textBox): Fixed Dark mode for textbox (default and fluent)

---

doc/articles/get-started.md

Update doc since Rider 2020.2 is no more EAP and is published now.

chore(doc): Update doc since Rider 2020.2 is no more EAP and is published now

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_CornerRadius.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_CornerRadius.xaml.cs
src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml

Fix https://github.com/unoplatform/uno/issues/3110

On WASM, the CornerRadius is not applied on the TextBox's border element

---

src/Uno.UI/Controls/Window.macOS.cs
src/Uno.UI/UI/Xaml/Window.macOS.cs
src/Uno.UWP/UI/ViewManagement/ApplicationView.macOS.cs

- Bugfix
When application view title is set before it becomes key, null reference exception is thrown.
Title is retrospectively when window is ready.

fix: [macOS] Allow setting title before window becomes key

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_Storage/FilePickerTests.xaml
src/SamplesApp/UITests.Shared/Windows_Storage/FilePickerTests.xaml.cs
src/SamplesApp/UITests.Shared/Windows_Storage/FolderPickerTests.xaml
src/SamplesApp/UITests.Shared/Windows_Storage/FolderPickerTests.xaml.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Storage.Pickers/FolderPicker.cs
src/Uno.UWP/Storage/Pickers/FolderPicker.macOS.cs

GitHub Issue (If applicable): closes #3843
- Feature
Not supported.
Supported.

[macOS] FolderPicker

---

src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.Shared/Strings/en/Resources.resw

GitHub Issue: closes #3478 
- Bugfix
Creating a new app through `dotnet new unoapp-prism -n MyApp` will leave a $ext_safeprojectname$ in the Resource.resw file
Creating a new app through `dotnet new unoapp-prism -n MyApp` will properly set the ApplicationName resource to MyApp.

[Prism-dotnetnew] Use template SourceName instead of old template parameters

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/documentation-request.md
.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/samples-request.md

Add Skia to the issue templates

docs: Add Skia to the issue templates

---

doc/articles/uno-fluent-assets.md

GitHub Issue (If applicable): Fix #3863
Documentation to update the fonts was hard to read. Platforms were separated in a table and android image was missing.
Documentation is cleaner. The image link is fix.

fix(doc): updating font doc is easier to read

---

src/SamplesApp/SamplesApp.iOS/Info.plist
src/Uno.UWP/Devices/Geolocation/Geolocator.iOSmacOS.cs

When the permission is denied and GetGeopositionAsync is called, then a NullReferenceException is thrown.
When the permission is denied and GetGeopositionAsync is called, then the method throws a helpful exception, as in UWP and Android.

feat: Throw appropriate exception when obtaining location without permission

---

src/Uno.UI/WasmCSS/Uno.UI.css

GitHub Issue (If applicable): Fix #3756
- Bugfix
Splashscreen does not keep its aspect ratio
Aspect ratio is now kept

fix(wasm): splash screen now respects aspect ratio

---

src/Uno.UI/Extensions/UIImageExtensions.iOS.cs
src/Uno.UI/Extensions/UIImageExtensions.iOSmacOS.cs
src/Uno.UI/Extensions/UIImageExtensions.macOS.cs
src/Uno.UI/UI/Xaml/Controls/Image/Image.iOSmacOS.cs

GitHub Issue (If applicable): fixes #3680 
- Bugfix
- Feature
Black images get whiped on iOS on monochrome recolor, thus also making the Foreground property break bitmapicons.
Images do not get recolored at all on macOS.
AsMonochrome recolors for images work as intended on ios and macOS.

fix(NSUImageExtensions): fixed image monochrome recoloring on ios

---

src/Uno.UWP/Devices/Geolocation/Geopoint.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Devices.Geolocation/Geopoint.cs

When using Geolocator to obtain a Geocoordinate position, Geocoordinate.Latitude and Geocoordinate.Longitude are correct but Geocoordinate.Point.Latitude and Geocoordinate.Point.Longitude (which are the correct way to obtain those values according to MSDN doc) are all set to 0, because we use a ctor which is not implemented.
Geocoordinate.Point is correctly set.

fix: Correctly initialize value of GeoCoordinate.Point on Android

---

build/PackageDiffIgnore.xml
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/CalendarDatePickerDateChangedEventArgs.cs
src/Uno.UI/UI/Xaml/Controls/CalendarDatePicker/CalendarDatePickerDateChangedEventArgs.cs

GitHub Issue (If applicable): #3750
- Feature
CalendarDatePickerDateChangedEventArgs is not supported.
CalendarDatePickerDateChangedEventArgs is supported (for all platforms).
It is required step for (re)implementing CalendarDatePicker control.
Part of #2079, that can be accepted/merged while rest of PR still waits for help.

feat: implementation of CalendarDatePickerDateChangedEventArgs

---

doc/articles/uno-development/debugging-uno-ui.md

Fix #3918
We have dead links in the Building and Debugging Uno.UI Documentation
No more dead links in the Building and Debugging Uno.UI Documentation

chore(doc): Fix dead links for debugging-uno-ui.md

---

src/Uno.UI.RemoteControl/LinkerDefinition.Wasm (2).xml

N/A
There is an extra `LinkerDefinition.Wasm (2).xaml` file in Uno.UI.RemoteControl. It is the exact same file as `LinkerDefinition.Wasm.xaml` but has the worryingly-named '(2)' suffix. This file isn't referenced anywhere in the code.
The unnecessary file is removed.

Remove extra 'LinkerDefinition.Wasm (2).xml' file

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Automation/Given_AutomationPeer.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Automation.Peers/AutomationPeer.cs
src/Uno.UI/UI/Xaml/Automation/Peers/AutomationPeer.cs

GitHub Issue (If applicable): closes #3931
- Feature
Many overridable methods in `AutomationPeer` throw.
Added default return values for many `AutomationPeer` methods.

feat: AutomationPeer methods

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ComboBoxTests/UnoSamples_Tests.ComboBoxTests.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ComboBox/ComboBox_PlaceholderText.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ComboBox/ComboBox_PlaceholderText.xaml.cs
src/Uno.UI/UI/Xaml/Controls/ComboBox/ComboBox.cs
src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.cs

GitHub Issue (If applicable): #3358
- Bugfix
ComboBox.PlaceholderText is now displaying correctly.
https://dev.azure.com/nventive/Uno%20Gallery/_queries/edit/191190

fix(combobox): PlaceholderText not displaying

---

src/SolutionTemplate/UnoLibraryTemplate/CrossTargetedLibrary.csproj

GitHub Issue (If applicable): #3925 
- Bugfix
The cross targeted library UWP SDK version is aligned with the current app template version.

fix: Update cross-target library uap version to 17763

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/DatePickerTests/UnoSamples_Tests.DatePicker.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TimePickerTests/UnoSamples_Tests.TimePicker.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/DatePicker/DatePickerFlyout_Date_Binding.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/DatePicker/DatePickerFlyout_Date_Binding.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TimePicker/TimePicker_Flyout_Automated_Reload.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TimePicker/TimePicker_Flyout_Automated_Reload.xaml.cs
src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePickerFlyout.iOS.cs
src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerFlyout.iOS.cs

GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/3930, fixes https://github.com/unoplatform/uno/issues/3511
- Bugfix
- Fixes `DatePickerFlyout.Date` property not updating properly
- Fixes `TimePickerFlyout` unloaded state NRE

TimePicker and DatePickerFlyout fixes

---

build/uno.winui.targets
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/Uno.CrossTargetting.props
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/XamlEvent_Leak_UserControl.xaml
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/XamlEvent_Leak_UserControl.xaml.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/XamlEvent_Leak_UserControl_xBind.xaml
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/XamlEvent_Leak_UserControl_xBind.xaml.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/XamlEvent_Leak_UserControl_xBind_Event.xaml
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/XamlEvent_Leak_UserControl_xBind_Event.xaml.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement_And_Leak.cs
src/Uno.UI/UI/Xaml/Data/Binding.cs

GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/3914
- Bugfix
Using x:Bind on iOS/macOS will not keep UIElement instances alive.
- [x ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

fix(xbind): [iOS/macOS] Fix memory leak when using x:Bind

---

.vsts-ci.yml

- Bugfix
Adjust Docs build as part of a separate build.

ci: Restore build the documentation as part of the main build

---

src/SourceGenerators/Uno.UI.SourceGenerators.Tests/Given_XBindRewriter.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/Utils/XBindExpressionParser.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileParser.cs
src/Uno.UI/UI/Xaml/Data/Binding.cs

- Bugfix
Delegates generated for `x:Bind` may get collected too early as they are not pinned to a long-lived object. Unit tests fail randomly as a consequence.
Delegates are now pinned to the `Binding` instance, but the context is now provided as a parameter of the bind and bind-back functions to avoid closing on `this`.

fix(reg): Fix invalid lifetime for generated delegates on x:Bind

---

src/SamplesApp/UITests.Shared/Windows_Devices/HingeAngleSensorTests.xaml.cs
src/Uno.UI.DualScreen/DuoHingeAngleSensor.cs

GitHub Issue (If applicable): fixes #3927
- Bugfix
`HingeAngleSensor` did not listen properly on Android.
`HingeAngleSensor` listens properly on Android.

fix: Listen to hinge angle sensor properly

---

doc/docfx.json

- Other: Website documentation related content
Gif files are not used for the site generation
Gif files are included in docfx output

docs: Ensure gif files are included in docfx output

---

src/Uno.UWP/Devices/Geolocation/Geolocator.Android.cs

https://github.com/unoplatform/uno/issues/3970
When we call Geolocator.RequestAccessAsync and the call is successful, StatusChanged is still not raised. That event is only raised when we call GetGeopositionAsync.
When we call Geolocator.RequestAccessAsync, StatusChanged is raised - the same as UWP and iOS.

[Android] Broadcast status after requesting access

---

src/Uno.CrossTargetting.props

GitHub Issue (If applicable): closes #3971 
- Feature
`HAS_UNO` is not defined withing Uno solution.
`HAS_UNO` is defined for non-uap targets

Add HAS_UNO for non uap targets

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/SymbolIconTests/SymbolIcon_Generic.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/SymbolIconTests/SymbolIcon_Generic.xaml.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/Symbol.cs
src/Uno.UI/UI/Xaml/Controls/Symbol.cs
src/Uno.UI/UI/Xaml/Controls/SymbolIcon/SymbolIcon.cs

GitHub Issue (If applicable): fixes #3510
- Feature
A few members of the `Symbol` enum were added in UWP, but were not present in Uno.
Symbols are added. They were already in our icon font.

Add missing Symbols

---

src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/NativeScrollContentPresenter.macOS.cs

- Bugfix
Creating a Templated Control and adding an event to one of the children, ex: `Click` event on a Button, the event is not attached.
The events added to the Children of a Templated Control will work as expected.

fix(macOS): Templated control not attaching events properly

---

src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/WebView.cs
src/Uno.UI/UI/Xaml/Controls/WebView/WebView.Android.cs
src/Uno.UI/UI/Xaml/Controls/WebView/WebView.iOSmacOS.cs

closes #3518 
- Feature
One of the signatures for WebView.InvokeScriptAsync is not supported.
WebView.InvokeScriptAsync is now supported for iOS, macOS and Android
There was a method with another signature implemented:
`Task<string> InvokeScriptAsync(CancellationToken ct, string script, string[] arguments);`
And this was definitely an option for the users. Unfortunately, the method that was not implemented was the first one to show on the IntelliSense making the users believe that none of the methods were implemented.

feat: Add Support for WebView.InvokeScriptAsync

---

src/Uno.UWP/ApplicationModel/Background/IBackgroundTrigger.cs
src/Uno.UWP/ApplicationModel/Background/TimeTrigger.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Background/IBackgroundTrigger.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Background/TimeTrigger.cs

Encouraged by davidjohnoliver's answer to question in #2079, and quick merge of resulting #3906... Part of #2655 - seems like TimeTrigger should not be platform dependent (in 2655, it was only for Android).
- Feature
TimeTrigger is not implemented.
Implemented.

feat: TimeTrigger (struct)

---

src/SamplesApp/SamplesApp.iOS/Info.plist
src/Uno.UWP/Devices/Geolocation/Geolocator.iOSmacOS.cs

https://github.com/unoplatform/uno/issues/4009
When the geolocator's constructor is invoked on iOS, the location permission is immediately requested from the user. This is inconsistent with UWP, where the permission is not asked in the constructor, but rather upon RequestAccessAsync.
When the geolocator's constructor is invoked on iOS, the location permission is not requested from the user.

fix: [iOS] Do not ask permission in Geolocator.ctor

---

src/Uno.UWP/Devices/Geolocation/Geolocator.Android.cs
src/Uno.UWP/Devices/Geolocation/Geolocator.iOSmacOS.cs

GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/4029
On Android: when we call GetGeopositionAsync on a background thread, a native exception is raised.
On iOS: when we call GetGeopositionAsync or RequestAccessAsync on a background thread, a native exception is raised.
These restrictions do not apply in UWP.
We can call GetGeopositionAsync and RequestAccessAsync  on any thread on iOS or Android, without error.

fix: Geolocator methods invoked on Dispatcher when necessary

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/Uno.UI.Tests/App/Xaml/Subclassed_Dictionary.xaml
src/Uno.UI.Tests/App/Xaml/Subclassed_Dictionary.xaml.cs
src/Uno.UI.Tests/Windows_UI_Xaml/Given_ResourceDictionary.cs

- Bugfix
Nested resources use in a resource dictionary.
The following XAML is now supported.
```xaml
<SolidColorBrush x:Key="PerilousColorBrush"
Color="WhiteSmoke" />
<DataTemplate x:Key="UproariousTemplate">
<CheckBox x:Name="TemplateRoot" />
</DataTemplate>
<local:MyConverter x:Key="InnerResourceConverter" Value="{StaticResource ProblemFreePhilosophy}">
<local:MyConverter.Values>
<local:MyConverterItem Value="{StaticResource PerilousColorBrush}" />
</local:MyConverter.Values>
</local:MyConverter>
```
Internal Issue (If applicable): fixes https://github.com/unoplatform/nventive-private/issues/11

fix(reg): Fix invalid component generation for nested resources

---

src/Uno.UWP/Devices/Geolocation/Geolocator.Android.cs

#4062
- Bugfix
Geolocator.TryInitialize is called from an async void
See https://github.com/unoplatform/uno/pull/4063#discussion_r490562205
Geolocator.TryInitialize is called from an async void on the dispatcher

fix: Schedule InitializeIfPermissionIsGranted on the dispatcher

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_StackPanel.cs
src/Uno.UI/UI/Xaml/UIElement.wasm.cs

Fixes https://github.com/unoplatform/uno/issues/3543
Doing a `.Children.Insert()` on a panel on Wasm was correctly updating the DOM, but the synchronized managed visual tree were not correctly updated, so the ordering was desynchronized between the two lists.

[Wasm] Fixed DOM & visual tree synchronization issues

---

src/Uno.UWP/Devices/Geolocation/Geolocator.Android.cs

- Feature
Some fields of Windows.Devices.Geolocation.Geoposition is not filled.
More location data is placed in Geoposition struct:
heading
altitudeAccuracy
accuracy
positionSource
Non-controversial part of #2536

feat: more fields in Geoposition (on Android)

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/CanvasTests/Canvas_Measurement_Tests.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Canvas/Canvas_ZIndex.xaml
src/Uno.UI/UI/Xaml/Controls/Canvas/Canvas.cs
src/Uno.UI/UI/Xaml/Controls/Canvas/Canvas.wasm.cs

Closes https://github.com/unoplatform/uno/issues/3544
Added support for `Canvas.ZIndex` to the WASM (HTML) Platform.
At first look, implementing the [CSS `z-index`](https://developer.mozilla.org/en-US/docs/Web/CSS/z-index) [seems complicated](https://philipwalton.com/articles/what-no-one-told-you-about-z-index/) because we need to deal with [_Stacking Contexts_](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context).
But the good news is whe're already creating a new _Stacking Context_ each time we're creating a UIElement on WASM.  That means we directly map the `Canvas.ZIndex` to the `CSS z-index:` style and it's working as expected.

Added support for `Canvas.ZIndex` to Wasm platform

---

src/Uno.Foundation/Point.cs
src/Uno.Foundation/Rect.cs
src/Uno.UI.Toolkit/UIElementExtensions.cs
src/Uno.UI/Extensions/UIElementExtensions.cs
src/Uno.UI/FeatureConfiguration.cs
src/Uno.UI/UI/LayoutHelper.cs
src/Uno.UI/UI/Xaml/Controls/Control/Control.cs
src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.xaml
src/Uno.UI/UI/Xaml/Input/PointerRoutedEventArgs.Android.cs
src/Uno.UI/UI/Xaml/Input/PointerRoutedEventArgs.cs
src/Uno.UI/UI/Xaml/Input/PointerRoutedEventArgs.iOS.cs
src/Uno.UI/UI/Xaml/Input/PointerRoutedEventArgs.macOS.cs
src/Uno.UI/UI/Xaml/Input/PointerRoutedEventArgs.skia.cs
src/Uno.UI/UI/Xaml/Input/PointerRoutedEventArgs.wasm.cs
src/Uno.UI/UI/Xaml/UIElement.Pointers.Skia.cs
src/Uno.UI/UI/Xaml/UIElement.Pointers.cs
src/Uno.UI/UI/Xaml/UIElement.Pointers.wasm.cs
src/Uno.UI/UI/Xaml/UIElement.RoutedEvents.cs
src/Uno.UI/UI/Xaml/UIElement.cs
src/Uno.UI/UI/Xaml/UIElement.netstd.cs
src/Uno.UI/UI/Xaml/UIElement.netstdref.cs
src/Uno.UI/UI/Xaml/Window.Skia.cs

GitHub Issue: fixes #3817 
Refactor the pointers support for Skia
The pointers support on skia was primitive and suffer some limitations:
* didn't support `RenderTransform`;
* `OriginalSource` was often not computed properly (especially for captured pointers)
* Enter/leave events was not raised properly
Only the clipping is not supported yet.

feat(pointers): Complete support of pointers for skia

---

src/Uno.UI/UI/Xaml/NativeApplication.cs

GitHub Issue (If applicable): fixes #1309
- Bugfix
Null reference exception occurs when a non-application activity is started (e.g. splash screen activity).
Exception no longer occurs.

fix: Perform app initialization only for ApplicationActivity

---

.vsts-ci.yml
build/run-automated-uitests.sh
doc/articles/features/windows-storage.md
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ThumbTests/UnoSamples_Tests.Thumb.cs
src/SamplesApp/UITests.Shared/Asset_GetFileFromApplicationUriAsync.xml
src/SamplesApp/UITests.Shared/Assets/Asset_GetFileFromApplicationUriAsync_Nested.xml
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SourceGenerators/Uno.UI.Tasks/Assets/RetargetAssets.cs
src/SourceGenerators/Uno.UI.Tasks/Content/Uno.UI.Tasks.targets
src/T4Generator/T4Generator.csproj
src/Uno.UI.BindingHelper.Android/Uno.UI.BindingHelper.Android.csproj
src/Uno.UI.RuntimeTests/Tests/Windows_Storage/Given_ApplicationStorage.cs
src/Uno.UI.Tests/Resources/Given_AndroidResourceConverter.cs
src/Uno.UI/Uno.UI.csproj
src/Uno.UI/WasmScripts/Uno.UI.d.ts
src/Uno.UI/WasmScripts/Uno.UI.js
src/Uno.UI/ts/Windows/Storage/AssetManager.ts
src/Uno.UWP/Generated/3.0.0.0/Windows.Storage/StorageFile.cs
src/Uno.UWP/Helpers/AndroidResourceNameEncoder.cs
src/Uno.UWP/Storage/AssetsManager.wasm.cs
src/Uno.UWP/Storage/Helpers/AssetsManager.wasm.cs
src/Uno.UWP/Storage/Helpers/ConcurrentEntryManager.cs
src/Uno.UWP/Storage/NameCollisionOption.cs
src/Uno.UWP/Storage/StorageFile.android.cs
src/Uno.UWP/Storage/StorageFile.cs
src/Uno.UWP/Storage/StorageFile.iOSmacOS.cs
src/Uno.UWP/Storage/StorageFile.wasm.cs
src/Uno.UWP/Storage/ThumbnailMode.cs

GitHub Issue (If applicable): fix #3887 
- Feature
Add support for `StorageFile.GetFileFromApplicationUriAsync` for iOS/macOS, Android, and WebAssembly.

Add support for StorageFile.GetFileFromApplicationUriAsync

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/Uno.UI.Tests/App/Xaml/Test_Page_Other.xaml
src/Uno.UI.Tests/Windows_UI_Xaml/Given_ResourceDictionary.cs

This was happening specifically for inline FrameworkElement.Resources declarations.
GitHub Issue (If applicable): fixes #3753, fixes #3780
- Bugfix

fix: Fix bug where ResourceDictionary with only ThemeDictionaries would not be generated

---

build/ci/.azure-devops-skia-tests.yml

Tests are stalling builds, disabling to avoid CI slow downs.

ci: Temporarily disable Skia runtime times

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs

- Bugfix
Adds partial support for nullable reference types added in a recent Styles and Setters PR, when building an Uno solution under `net5`.
Note that this change cannot be unit tested in the solution yet, as we cannot yet include heterogenous Target Frameworks in the uno solution. This will addressed once that C# 9.0 generators can be used and the internal dependency on Uno.SourceGeneration is removed.

fix(net5): Fix for net5 source generation nullable references support

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/Uno.UI.Tests/Windows_UI_Xaml_Data/BindingTests/Controls/Binding_ElementName_In_Template.xaml
src/Uno.UI.Tests/Windows_UI_Xaml_Data/BindingTests/Controls/Binding_ElementName_In_Template.xaml.cs
src/Uno.UI.Tests/Windows_UI_Xaml_Data/BindingTests/Given_Binding.cs
src/Uno.UI/UI/Xaml/Data/BindingHelper.cs
src/Uno.UI/UI/Xaml/DependencyObjectStore.Binder.cs
src/Uno.UI/UI/Xaml/DependencyPropertyDetailsCollection.Bindings.cs

GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/4100
- Bugfix
ElementName bindings in side `DataTemplate` instances are now lazy initialized during `Loading`.

fix(reg): Fix lazy-initialized ElementName bindings

---

src/Uno.UWP/Storage/ApplicationData.skia.cs

- Bugfix
The `ApplicationData.Local` under skia does not point to the proper directory.
Uses `Environment.GetFolderPath` which points to the `XDG_DATA_HOME` standard environment variable.

fix(unix): Adjust `ApplicationData.Local` path to use proper locations under unix

---

src/SourceGenerators/Uno.UI.SourceGenerators/Helpers/HashBuilder.cs

GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/4154
- Bugfix
Building an uno app on a FIPS enable system fails because of the use of MD5 hashing.
SHA256 is used instead for collision limiting in source generators.

fix(fips): Use SHA256 for sourcegenerator path hashing

---

src/Uno.UI.Runtime.WebAssembly/buildTransitive/Uno.UI.Runtime.WebAssembly.targets

GitHub Issue (If applicable): https://github.com/unoplatform/Uno.Wasm.Bootstrap/issues/279
- Bugfix
Publishing to azure may result in locked files failure.
A second compilation is avoided by preventing a generated file to be overwritten incorrectly.

fix(publish): Fixes publish to azure may fail with locked files

---

src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/NativeScrollContentPresenter.macOS.cs

- Bugfix
macOS apps are crashing in some situations when using Controls that use `ScrollContentPresenter`
the issue that was causing the crash was fixed.
`newValue` was coming `null` at times which was causing a crash.

fix(macOS): exception on Scrollview ContentChanged

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement_And_Leak.cs
src/Uno.UI/UI/Xaml/Controls/ComboBox/ComboBox.cs
src/Uno.UI/UI/Xaml/Controls/ContentDialog/ContentDialog.cs
src/Uno.UI/UI/Xaml/Controls/ContentDialog/ContentDialogPopupPanel.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs

GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/4168
- Bugfix
Fix `ComboBox`, `ContentDialog` and `TextBox` memory leaks.

Misc memory leaks fixes

---

src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.cs
src/Uno.UI.RuntimeTests/IntegrationTests/common/TestServices.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement_And_Leak.cs
src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.xaml
src/Uno.UI/UI/Xaml/FrameworkTemplatePool.cs

GitHub Issue (If applicable): closes #4167, fixes https://github.com/unoplatform/uno/issues/3783
- Bugfix
- Feature
- Restore the managed `ScrollBar` in default`ScrollViewer`
- Adjust `WindowHelper.WaitForIdle` to actually wait for Idle on Wasm
- Adjust `SampleChooserViewModel` to run a GC collect after setting a sample
- Fix `TemplatePooling` may still be active when disabled
- Fix Leak runtime tests and wait for Idle for the GC to run properly

Fix memory issues, enable XAML ScrollBar on Wasm ScrollViewer

---

src/Uno.UWP/Helpers/DrawableHelper.Android.cs

GitHub Issue (If applicable): fixes #4204 
`InvalidOperationException` is thrown instead of `Exception` as specified in the issue.
Error message is more clear now, as it specifies why the error may have happened.

fix[Android]: Drawable error message made more clear

---

doc/articles/platform-specific-csharp.md
doc/articles/platform-specific-xaml.md

Skia is excluded from condition code and Xaml docs.
Skia is included.
* Someone needs to double check the pre-defined prefixes table for conditional Xaml. I added Skia for all entries and made some assumptions (like `xamarin` should exclude Skia).

docs: Update conditional code/Xaml to include Skia

---

src/Uno.UI.Tests/DependencyProperty/Given_DependencyProperty.cs
src/Uno.UI/UI/Xaml/DependencyObjectExtensions.cs
src/Uno.UI/UI/Xaml/DependencyObjectStore.Binder.cs
src/Uno.UI/UI/Xaml/DependencyObjectStore.cs
src/Uno.UI/UI/Xaml/DependencyPropertyDetails.cs

There's a mechanism in Uno to force all properties set during a _property changed_ callback to be set using the `Local` precedence. This is correct for all cases except one: when this property itself is the `Style`. In this case, the _property changed_ MUST apply the `ExplicitStyle` precedence.
Details: in the previous version, while manually setting the Style property (which uses Local precedence), it was setting both _precedenceOverride to ExplicitStyle and the _isSettingAProperty to true, preventing the setters from applying there values under correct explicit precedence.
- ~~[ ] Associated with an issue (GitHub or internal) and uses the [automatic close …

First <Setter> on a <Style> were potentially applying values using wrong precedence

---

doc/articles/uno-development/building-uno-ui.md
doc/articles/uno-development/debugging-uno-ui.md

This PR adds a recommendation to use a short path when cloning Uno, to avoid build errors.

Update debugging-uno-ui.md - add info about long paths

---

src/Uno.UWP/Generated/3.0.0.0/Windows.Storage.Pickers/PickerLocationId.cs
src/Uno.UWP/Storage/Pickers/PickerLocationId.cs

- Feature
No FileOpenPicker implemented.
Enum for FileOpenPicker is implemented (for all platforms)
Part of "stalled" #2896 - common for all platforms.

feat: Storage.Pickers.PickerLocationId

---

src/SourceGenerators/Uno.UI.SourceGenerators/Helpers/RoslynMetadataHelper.cs
src/SourceGenerators/Uno.UI.SourceGenerators/Helpers/SymbolExtensions.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.Reflection.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs

XAML Generation performance was significantly reduced by some uses of symbol string conversions and members enumerations. The new changes take into account the ability to lookup members by name, instead of performing a linear search.
Parallel file generation is also restored.

XAML Generation performance improvements

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.Reflection.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/Uno.UI.Tests/App/Xaml/Test_SetterTarget.xaml
src/Uno.UI.Tests/App/Xaml/Test_SetterTarget.xaml.cs
src/Uno.UI.Tests/Windows_UI_Xaml/Given_StaticResource.cs

- Feature
- Using Setter.Target is now supported
- Fixes FindPropertyByName may receive a null name.

feat: Add support Setter.Target in style declaration

---

src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePickerSelector.iOS.cs
src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerSelector.iOS.cs

closes #4131 
- Bugfix
DatePicker/TimePicker look normal like iOS 13

Set PreferredDatePickerStyle on iOS 14

---

doc/templates/uno/styles/scss/main.scss

In the previous version of the documentation there was a position typo causing the sub navigation bar to be too low, so the scrolling content peeked above through the navigation header.
In this commit, I corrected that typo (`75px`) by the correct value (`57px`).
- Documentation style bug fix
The sub navigation bar is positioned too low, so the scrolling content peeks through above the sub navigation bar:
I fixed the typo, so the sub navigation bar position matches the top navigation bar height:

Documentation: sub navigation position in main.scss amended

---

src/Directory.Build.targets
src/roslyn-override.targets

- Bugfix
Building from Visual Studio may show the `Invalid version ""` with iOS or Android.
No error.
- [xc] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

fix: Adjust roslyn override inclusion for legacy projects

---

build/ios-uitest-run.sh
src/SamplesApp/SamplesApp.UITests/TestFramework/ImageAssert.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/WUXProgressRingTests/UnoSamples_WUXProgressRing_Tests.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ProgressRing/WindowsProgressRing_GH1220.xaml
src/Uno.UI/UI/Xaml/Controls/ProgressRing/ProgressRing.iOS.cs
src/Uno.UI/UI/Xaml/Controls/ProgressRing/ProgressRing.iOSAndroid.cs

GitHub Issue (If applicable): https://github.com/unoplatform/nventive-private/issues/18
- Bugfix
The WUX progress ring should not disappear if `IsEnabled` is set to false.

fix(ProgressRing): Fixes IsEnabled should not remove the progress ring

---

build/run-template-tests.ps1
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp/UnoQuickStart.sln
src/SolutionTemplate/UnoSolutionTemplate/Shared/App.xaml.cs
src/SolutionTemplate/UnoSolutionTemplate/Skia.Gtk/UnoQuickStart.Skia.Gtk.csproj
src/SolutionTemplate/UnoSolutionTemplate/Skia.WPF.Host/MainWindow.xaml.cs

- Bugfix
The Skia WPF head is referenced properly

fix(dotnetnew): Skia WPF head is not referenced properly in sln

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml/ClippingTests/ClippingTests_Tests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/Clipping/Clipping4273.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/Clipping/Clipping4273.xaml.cs
src/Uno.UI/UI/Xaml/Controls/Border/Border.wasm.cs
src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.Android.cs
src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.Skia.cs
src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.cs
src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.iOS.cs
src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.macOS.cs
src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.net.cs
src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.netstdref.cs
src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.wasm.cs
src/Uno.UI/UI/Xaml/Controls/Page/Page.wasm.cs
src/Uno.UI/UI/Xaml/Controls/Panel/Panel.wasm.cs
src/Uno.UI/UI/Xaml/FrameworkElement.Interface.wasm.cs
src/Uno.UI/UI/Xaml/FrameworkElement.wasm.cs

Fixes #4273 
Applying rounded corners to an element were forcing the clipping to operate, but since it's only supporting rectangle clipping (UWP limitations), the CSS `overflow: hidden` is required for the corners to clip the content.

Wasm Rounded Corners were not clipping

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.Reflection.cs
src/Uno.UI.Tests/Uno.UI.Tests.csproj
src/Uno.UI.Tests/Windows_UI_XAML_Controls/UserControlTests/Given_UserControl.cs
src/Uno.UI.Tests/Windows_UI_XAML_Controls/UserControlTests/UserControl_WriteOnlyProperty.xaml
src/Uno.UI.Tests/Windows_UI_XAML_Controls/UserControlTests/UserControl_WriteOnlyProperty.xaml.cs
src/Uno.UI.Tests/Windows_UI_XAML_Controls/UserControlTests/UserControl_WriteOnlyProperty_UserControl.xaml
src/Uno.UI.Tests/Windows_UI_XAML_Controls/UserControlTests/UserControl_WriteOnlyProperty_UserControl.xaml.cs

closes #4080 
- Bugfix
Setting a public write-only property on a custom control causes the build to fail for Uno targets, though it does succeed for UWP.
Project builds and XAML code gen succeeds

Add null check for GetMethod in case of write-only property

---

src/Uno.UI/UI/Xaml/Controls/TextBlock/TextVisual.Skia.cs

GitHub Issue (If applicable): https://github.com/unoplatform/calculator/issues/319
- Bugfix
On some systems, asking for fonts by family may return null, failing to render textblocks.
The default system font is used instead.

fix(skia): FontFamily may return null and fail TextBlock rendering

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml/DragAndDropTests/DragDrop_Basics_Automated.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ScrollViewerTests/ScrollViewer_UpdatesMode.xaml.cs
src/SourceGenerators/Uno.UI.SourceGenerators/BindableTypeProviders/BindableTypeProvidersGenerationTask.cs
src/SourceGenerators/Uno.UI.SourceGenerators/Helpers/CompilationExtensions.cs
src/SourceGenerators/Uno.UI.SourceGenerators/Helpers/RoslynMetadataHelper.cs
src/SourceGenerators/Uno.UI.SourceGenerators/Uno.UI.SourceGenerators.csproj

GitHub Issue (If applicable): closes #4299 
- Bugfix
Some controls are not appearing properly when running using the nuget package.

Fix BindableType generator not detecting attributes after roslyn update

---

build/Uno.UI.Build.csproj
build/Uno.WinUI.nuspec
build/uno.winui.uap.targets

- Bugfix
UAP build including Uno.UI may fail for invalid analyzers support in previous versions of visual studio.
UAP build ignores the C# 9.0 source generators.

fix(reg): Fix UAP build should not include C# 9 source generators

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/Uno.UI.Tests/Windows_UI_Xaml/Controls/When_xLoad_Deferred_StaticCollapsed.xaml
src/Uno.UI.Tests/Windows_UI_Xaml/Controls/When_xLoad_Deferred_StaticCollapsed.xaml.cs
src/Uno.UI.Tests/Windows_UI_Xaml/Controls/When_xLoad_Deferred_VisibilityBinding.xaml
src/Uno.UI.Tests/Windows_UI_Xaml/Controls/When_xLoad_Deferred_VisibilityBinding.xaml.cs
src/Uno.UI.Tests/Windows_UI_Xaml/Controls/When_xLoad_Deferred_VisibilityxBind.xaml
src/Uno.UI.Tests/Windows_UI_Xaml/Controls/When_xLoad_Deferred_VisibilityxBind.xaml.cs
src/Uno.UI.Tests/Windows_UI_Xaml/Controls/When_xLoad_LoadSingle.xaml
src/Uno.UI.Tests/Windows_UI_Xaml/Controls/When_xLoad_LoadSingle.xaml.cs
src/Uno.UI.Tests/Windows_UI_Xaml/Controls/When_xLoad_Multiple.xaml
src/Uno.UI.Tests/Windows_UI_Xaml/Controls/When_xLoad_Multiple.xaml.cs
src/Uno.UI.Tests/Windows_UI_Xaml/Given_xLoad.cs
src/Uno.UI/UI/Xaml/FrameworkElement.net.cs

GitHub Issue (If applicable): #4323
- Bugfix
Using `x:Load` requries the use of a visibility binding, which is not in line with the original WinUI behavior.
`x:Load` can be used along with an `x:Name` to be materialized on call to `FindName`.

Adjust x:Load behavior to not require visibility binding

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/TappedTapped_Tests.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ScrollViewer.cs
src/Uno.UI/UI/Xaml/Controls/ScrollBar/ScrollBar.cs
src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.cs
src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.xaml
src/Uno.UI/UI/Xaml/Media/VisualTreeHelper.cs
src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml

GitHub Issue: fixes #4323 
* Improve performance of the `ScrollViewer` by deferring the load of is managed scrollbars, and by loading only partially the template of the `ScrollBar`
* Fix regression introduced by https://github.com/unoplatform/uno/pull/4270 which broke hit testing (used by pointers) when in a `ScrollViewer` with a non zero `<horizontal|Vertical>Offset`.
Too slow 🐢
Faster 🐇

ScrollViewer performance

---

doc/articles/uno-development/building-uno-ui.md
src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props

GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/4262
- Bugfix
Warn the user that the solution is being built in a path that may be too long, and that the build may fail.

fix: LongPath validation for build errors using generators

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/CommandBarTests/UnoSamples_Tests.NativeCommandBar.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/Background/CommandBar_Background_Frame.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/Background/CommandBar_Background_Frame.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/Background/CommandBar_Background_Page1.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/Background/CommandBar_Background_Page1.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/Background/CommandBar_Background_Page2.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/Background/CommandBar_Background_Page2.xaml.cs
src/Uno.UI/Controls/CommandBarHelper.iOS.cs
src/Uno.UI/Controls/NativeFramePresenter.iOS.cs

closes #3017 
- Bugfix
Changing the Background property on the CommandBar on Page1 while navigating to Page2 changes the CommandBar on Page2.
Changes on one Page CommandBar will not affect other page's CommandBar

fix(iOS) CommandBar updates on navigation #3017

---

build/PackageDiffIgnore.xml
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.Wasm/WasmCSS/Fonts.css
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/xamarinforms-wasm/UnoXFQuickStart.Wasm/WasmCSS/Fonts.css
src/SolutionTemplate/UnoSolutionTemplate/Wasm/WasmCSS/Fonts.css

- Bugfix
The Font.css file is silently ignored by the browser if the UTF8 BOM is present and the file is not specified as UT8.
The file is loaded properly.

fix(webassembly): [WASM] remove UTF8 BOM for CSS fonts file

---

src/SolutionTemplate/UnoSolutionTemplate/Skia.Gtk/UnoQuickStart.Skia.Gtk.csproj
src/SolutionTemplate/UnoSolutionTemplate/Skia.WPF.Host/UnoQuickStart.Skia.Wpf.Host.csproj

- Bugfix
`dotnet new` experience does not include the symbol assets properly.
Symbols are working properly.

fix(skia): Fix symbols font is not registered

---

src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/SelectionMode.cs
src/Uno.UI/UI/Xaml/Controls/SelectionMode.cs

None
- Feature
Windows.UI.Xaml.Controls.SelectionMode is not implemented.
Windows.UI.Xaml.Controls.SelectionMode is implemented. This is needed for some custom controls in an Uno app that use this enum.

feat: Add SelectionMode enum

---

build/PackageDiffIgnore.xml
src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/Given_XamlReader.cs
src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/When_IList_TabView.xamltest
src/Uno.UI/Microsoft/UI/Xaml/Controls/TabView/TabView.Properties.cs
src/Uno.UI/UI/Xaml/Markup/Reader/XamlObjectBuilder.cs

- Bugfix
Fixes the ability for `TabView` to use using in `XamlReader`.

fix(Pivot): Remove TabView.TabItems setter, not part of public API.

---

src/Uno.UWP/Generated/3.0.0.0/Windows.UI.Notifications/TileNotification.cs
src/Uno.UWP/UI/Notifications/TileNotification.cs

GitHub Issue (If applicable): #3045 (part of)
- Feature
No Live Tile implementation.
LiveTile class/struct, common for every platform, is defined.
Part of #3147 - working part :)  , and common for all platforms. Other files changed in #3147 are only for Android.

feat: TileNotification common struct

---

src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/NavigationViewPaneDisplayMode.cs
src/Uno.UI/UI/Xaml/Controls/NavigationView/NavigationViewPaneDisplayMode.cs

Relates to discussion in #4317 
- Feature
NavigationViewPaneDisplayMode enum is not implemented although modes are supported by the NavigationView
NavigationViewPaneDisplayMode enum is implemented.

feat: Add NavigationViewPaneDisplayMode enum

---

doc/articles/features/pointers-keyboard-and-other-user-inputs.md
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/DragAndDrop/DragDrop_TestPage.xaml.cs
src/Uno.UI.Runtime.Skia.Wpf/WPF/WpfDragDropExtension.cs
src/Uno.UI/Controls/Window.macOS.cs
src/Uno.UI/UI/Xaml/DragDropExtension.macOS.cs
src/Uno.UI/UI/Xaml/DragDropManager.cs
src/Uno.UI/UI/Xaml/Media/ImageSource.cs
src/Uno.UWP/ApplicationModel/DataTransfer/Clipboard.Android.cs
src/Uno.UWP/ApplicationModel/DataTransfer/DataPackage.cs
src/Uno.UWP/ApplicationModel/DataTransfer/DataPackage.macOS.cs
src/Uno.UWP/UI/Core/CoreWindow.macOS.cs

GitHub Issue fixes https://github.com/unoplatform/uno/issues/4311
Relates to Issue #1480 and PR #4270 
Adds support 
- Feature
Drag and drop is not integrated with macOS and other apps.
Drag and drop is integrated with macOS supporting inter-app drag and drop:
- Drop of external content on an Uno App is fully supported (images, files, text, etc.)
- Drag of Uno App content to external macOS apps is supported but has some limitations/issues.
ToDo:
Other open questions are commented in code.

feat(dragdrop): Drag-and-drop integration with macOS

---

src/Uno.UI/UI/Xaml/Controls/Frame/Frame.cs

Closes #4412
- Bugfix?
See issue #4412
Frame.Navigate() is more robust and will not fail to navigate to a new page if the first/previous page failed to load.

fix: Do not throw exception on navigation after first page failed to load
