doc/articles/ListViewBase.md
doc/articles/using-uno-ui.md
src/Uno.UI.Tests/DependencyProperty/Given_DependencyProperty.Propagation.cs
src/Uno.UI/UI/Xaml/Media/Animation/Timeline.cs
src/Uno.UI/UI/Xaml/VisualTransition.cs

Formatting updates for improved readability.

Documentation update

---

.gitignore
.vsts-ci.yml
src/SourceGenerators/Uno.UI.SourceGenerators/Uno.UI.SourceGenerators.csproj
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/SourceGenerators/Uno.UI.Tasks/Uno.UI.Tasks.csproj
src/SourceGenerators/XamlGenerationTests.Core/XamlGenerationTests.Core.csproj
src/SourceGenerators/XamlGenerationTests/XamlGenerationTests.csproj
src/Uno.Foundation/Uno.Foundation.csproj
src/Uno.UI.Tests.Performance/Uno.UI.Tests.Performance.csproj
src/Uno.UI.Tests/Uno.UI.Tests.csproj
src/Uno.UI.Toolkit/Uno.UI.Toolkit.csproj
src/Uno.UI.Wasm.Shell/Uno.UI.Wasm.Shell.csproj
src/Uno.UI/Controls/CommandBarRenderer.Android.cs
src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.cs
src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.iOS.cs
src/Uno.UI/UI/Xaml/DependencyObjectStore.cs
src/Uno.UI/UI/Xaml/FrameworkElement.Layout.netstd.cs
src/Uno.UI/UI/Xaml/FrameworkElement.cs
src/Uno.UI/UI/Xaml/Style/Generic/GenericStyles.cs
src/Uno.UI/UI/Xaml/Style/Generic/SystemResources.xaml
src/Uno.UI/Uno.UI.csproj
src/Uno.UWP/Uno.csproj

- Fixes ScrollViewer memory leak
- Border thickness arrange impact in WASM
- Missing generic styles application for UWP defaults (#40)
- Fix for #33 to support literal implicit text
- Revert change that adjusted defaults colors (to be revised with later changes)
- Fix for Source Generation race condition on slow build servers

Misc compatibility updates

---

src/Uno.UI.Wasm/WasmScripts/Uno.UI.d.ts
src/Uno.UI.Wasm/WasmScripts/Uno.UI.js
src/Uno.UI.Wasm/ts/Interop/ManagedObject.ts
src/Uno.UI.Wasm/ts/WindowManager.ts
src/Uno.UI/UI/Xaml/Controls/Image/Image.netstd.cs
src/Uno.UI/UI/Xaml/FrameworkElement.netstd.cs
src/Uno.UI/UI/Xaml/Media/ImageSource.cs
src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml
src/Uno.UWP/Storage/ApplicationDataContainer.iOS.cs
src/Uno.UWP/UI/ViewManagement/ApplicationView.wasm.cs

- Adjust for WASM Support for local images (#1)
- Fixes `x:Bind` support for Wasm
- Fix invalid deserialization of `ApplicationDataContainer` for iOS
- Fix error for ApplicationView.Title for WASM
- Remove glib conversion errors in WASM

Misc compatibility adjustments

---

doc/articles/faq.md
doc/articles/using-uno-ui.md

Provides details on frequently asked questions.

Add FAQ article

---

build/Uno.UI.proj
src/SolutionTemplate/UnoSolutionTemplate/UnoQuickStart.Wasm/Program.cs
src/Uno.UWP/UI/Popups/MessageDialog.netstd.cs

- Adjust for missing vsix wasm namespace 
- Add missing wasm return value for `MessageDialog.ShowAsync`
- Add build version in vsix file name

Adjust for missing vsix wasm namespace, vsix version

---

README.md

Fix a path on README

---

README.md
doc/articles/faq.md

Fixes #60 now that prism is supported.

Update the readme and FAQ

---

src/Uno.UWP/Generated/3.0.0.0/Windows.UI.Core/CoreWindow.cs
src/Uno.UWP/UI/Core/CoreWindow.cs

Implement the CoreWindow.Dispatcher property

---

src/Uno.UI/UI/Xaml/Media/Animation/Animators/NativeValueAnimatorAdapter.Android.cs

Update handlers to use proper sender, report exceptions are recoverable to avoid crashing ART.

Update for android animation reliability

---

src/Uno.UI.Tests/ItemsControlTests/Given_ItemsControl.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/ItemsControl.cs
src/Uno.UI/UI/Xaml/Controls/FlipView/FlipView.cs
src/Uno.UI/UI/Xaml/Controls/ItemsControl/ItemsControl.cs

Expose ItemsControl.OnItemsChanged properly

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
.gitignore
CONTRIBUTING.md
README.md
doc/.feature-template.md

This PR adds some structure for the PR and issues creation templates, redirects questions to stackoverflow/gitter, and adds a basic template for feature documentation articles.

Add github PR and issue templates, feature doc template.

---

build/Uno.UI.nuspec
src/SourceGenerators/Uno.UI.SourceGenerators/Uno.UI.SourceGenerators.csproj
src/SourceGenerators/Uno.UI.Tasks/Uno.UI.Tasks.csproj
src/SourceGenerators/XamlGenerationTests.Core/XamlGenerationTests.Core.csproj
src/SourceGenerators/XamlGenerationTests/XamlGenerationTests.csproj
src/Uno.Foundation/Uno.Foundation.csproj
src/Uno.UI.Tests.Performance/Uno.UI.Tests.Performance.csproj
src/Uno.UI.Tests/Uno.UI.Tests.csproj
src/Uno.UI.Toolkit/Uno.UI.Toolkit.csproj
src/Uno.UI.Wasm.Shell/Uno.UI.Wasm.Shell.csproj
src/Uno.UI.Wasm/Uno.UI.Wasm.csproj
src/Uno.UI/Uno.UI.csproj
src/Uno.UWP/Uno.csproj
src/Uno.UWPSyncGenerator/Uno.UWPSyncGenerator.csproj

Updates to latest beta.

---

src/SolutionTemplate/UnoSolutionTemplate/UnoQuickStart.Wasm/LinkerConfig.xml
src/SolutionTemplate/UnoSolutionTemplate/UnoQuickStart.Wasm/Wasm.vstemplate

Feature
Creating a project from the Wasm template fails for basing binding scenarios.
Basic binding scenarios are working properly.

VSIX Wasm template: Add linker configuration for the main assembly

---

.gitignore

Add the binlog files path to gitignore.
- Other
Change to gitignore
After build, binlog files are included in source control.
After build, binlog files are not included in source control.

Add binlogs to gitignore

---

src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/GroupStyle.cs
src/Uno.UI/UI/Xaml/Controls/GroupStyle.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBaseSource.iOS.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/NativeListViewBase.Android.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/NativeListViewBaseAdapter.Android.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.iOS.cs

Issue: #
- Feature
Adds support for GroupStyle.HeaderTemplateSelector property in grouped ListView/GridView.

[Xamarin] ListView - implement GroupStyle.HeaderTemplateSelector

---

Doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.Tests/ControlTests/Given_Control.cs
src/Uno.UI.Tests/DependencyProperty/Given_DependencyProperty.Propagation.cs
src/Uno.UI.Tests/ItemsControlTests/Given_ItemsControl.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/GroupStyle.cs
src/Uno.UI/UI/Xaml/Controls/Control/Control.cs
src/Uno.UI/UI/Xaml/Controls/GroupStyle.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBaseSource.iOS.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/NativeListViewBase.Android.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/NativeListViewBase.iOS.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/NativeListViewBaseAdapter.Android.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.Android.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.iOS.cs
src/Uno.UWP/Devices/Sensors/SimpleOrientationSensor.Android.cs

Additional fixes for beta

---

Doc/ReleaseNotes/_ReleaseNotes.md
build/Uno.UI.nuspec
doc/ReleaseNotes/_ReleaseNotes.md
gitversion.yml
src/SolutionTemplate/UnoLibraryTemplate/CrossTargetedLibrary.csproj
src/SolutionTemplate/UnoSolutionTemplate/UnoQuickStart.Droid/UnoQuickStart.Droid.csproj
src/SolutionTemplate/UnoSolutionTemplate/UnoQuickStart.Wasm/UnoQuickStart.Wasm.csproj
src/SolutionTemplate/UnoSolutionTemplate/UnoQuickStart.iOS/UnoQuickStart.iOS.csproj
src/SourceGenerators/Uno.UI.SourceGenerators/Uno.UI.SourceGenerators.csproj
src/SourceGenerators/Uno.UI.Tasks/Uno.UI.Tasks.csproj
src/SourceGenerators/XamlGenerationTests.Core/XamlGenerationTests.Core.csproj
src/SourceGenerators/XamlGenerationTests/XamlGenerationTests.csproj
src/Uno.Foundation/Uno.Foundation.csproj
src/Uno.UI.Tests.Performance/Uno.UI.Tests.Performance.csproj
src/Uno.UI.Tests/Uno.UI.Tests.csproj
src/Uno.UI.Toolkit/Uno.UI.Toolkit.csproj
src/Uno.UI.Wasm.Shell/Uno.UI.Wasm.Shell.csproj
src/Uno.UI.Wasm/Uno.UI.Wasm.csproj
src/Uno.UI/Uno.UI.csproj
src/Uno.UWP/Uno.csproj
src/Uno.UWPSyncGenerator/Uno.UWPSyncGenerator.csproj

Stable merge back

---

README.md

Adjust conditional XAML link

---

doc/articles/supported-features.md
src/Uno.UI/Extensions/PermissionsHelper.Android.cs
src/Uno.UI/UI/Xaml/Application.Android.cs
src/Uno.UWP/Extensions/PermissionsHelper.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Media.Capture/CameraCaptureUI.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Media.Capture/CameraCaptureUIMaxPhotoResolution.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Media.Capture/CameraCaptureUIMaxVideoResolution.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Media.Capture/CameraCaptureUIMode.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Media.Capture/CameraCaptureUIPhotoFormat.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Media.Capture/CameraCaptureUIVideoCaptureSettings.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Media.Capture/CameraCaptureUIVideoFormat.cs
src/Uno.UWP/Media/Capture/CameraCaptureUI.Android.cs
src/Uno.UWP/Media/Capture/CameraCaptureUI.cs
src/Uno.UWP/Media/Capture/CameraCaptureUI.iOS.cs
src/Uno.UWP/Media/Capture/CameraCaptureUI.other.cs
src/Uno.UWP/Media/Capture/CameraCaptureUIMaxPhotoResolution.cs
src/Uno.UWP/Media/Capture/CameraCaptureUIMaxVideoResolution.cs
src/Uno.UWP/Media/Capture/CameraCaptureUIMode.cs
src/Uno.UWP/Media/Capture/CameraCaptureUIPhotoCaptureSettings.cs
src/Uno.UWP/Media/Capture/CameraCaptureUIPhotoFormat.cs
src/Uno.UWP/Media/Capture/CameraCaptureUIVideoCaptureSettings.cs
src/Uno.UWP/Media/Capture/CameraCaptureUIVideoFormat.cs

Issue: #68
Adds the implementation for `Windows.Media.Capture.CameraCaptureUI`

Add support for Windows.Media.Capture.CameraCaptureUI for iOS/Android

---

doc/articles/MediaPlayerElement.md
src/Uno.UI.Wasm/WasmScripts/Uno.UI.d.ts
src/Uno.UI.Wasm/WasmScripts/Uno.UI.js
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/MediaPlayerElement.cs
src/Uno.UI/UI/Xaml/ApplicationActivity.Android.cs
src/Uno.UI/UI/Xaml/Controls/Border/Border.Android.cs
src/Uno.UI/UI/Xaml/Controls/Border/Border.iOS.cs
src/Uno.UI/UI/Xaml/Controls/MediaPlayer/MediaPlayerElement.cs
src/Uno.UI/UI/Xaml/Controls/MediaPlayer/MediaTransportControls.cs
src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml
src/Uno.UI/UI/Xaml/Window.Android.cs
src/Uno.UI/UI/Xaml/Window.iOS.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.UI.ViewManagement/ApplicationView.cs
src/Uno.UWP/Media/Playback/MediaPlayer.Android.cs
src/Uno.UWP/UI/ViewManagement/ApplicationView.Android.cs
src/Uno.UWP/UI/ViewManagement/ApplicationView.iOS.cs

Issue: #
None
Feature
MediaPlayerElement does not support fullscreen mode
MediaPlayerElement now support fullscreen mode

MediaPlayerElement now support fullscreen mode

---

doc/ReleaseNotes/_ReleaseNotes.md
doc/articles/working-with-commandbar.md
src/Uno.UI/Controls/CommandBarHelper.iOS.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.iOS.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Media.Playback/MediaPlayer.cs
src/Uno.UWP/Media/Playback/MediaPlayer.Android.cs
src/Uno.UWP/Media/Playback/MediaPlayer.iOS.cs

Bring commits from master into this beta release

Cherry pick fixes into beta

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/ApplicationActivity.Android.cs
src/Uno.UI/UI/Xaml/Window.Android.cs

- Bugfix
On some devices with rounded corners (LG G7 ThinQ for example), Bounds are based on usable metrics
Bounds are based on real metrics
https://nventive.visualstudio.com/Umbrella/_workitems/edit/132004

[Android] Use real metrics instead of usable metrics

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/ListViewBase/BufferViewCache.Android.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBaseSource.iOS.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/NativeListViewBase.Android.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/NativeListViewBase.iOS.cs

Support the MultiSelectStates visual group on ListViewItem/GridViewItem, which are set according to whether a multiple selection mode is enabled.
Internal issue:
https://nventive.visualstudio.com/Umbrella/_workitems/edit/135985

ListView - support MultiSelectStates

---

doc/articles/toc.yml
src/Uno.UI/UI/Xaml/Controls/VariableSizedWrapGrid.cs
src/Uno.UWPSyncGenerator/DocGenerator.cs
src/Uno.UWPSyncGenerator/ImplementedFor.cs

#267 
Ensures generated list of views is linked in docs, adds base class to controls info.

List of implemented views - add to TOC, add base class

---

src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.cs

Fixes regression introduced by #315

ListView - fix NRE when setting SelectionMode before template is materialized

---

src/Uno.UI/UI/Xaml/Controls/NavigationView/NavigationView.cs

- Bugfix
Adding multiple items in the `NavigationView.MenuItems` is slow, because of a naïve items collection synchronization.
Adding multiple items in the `NavigationView.MenuItems` is faster.

Improve MenuItems update performance

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.Foundation/DelegateCommand.T.cs
src/Uno.Foundation/DelegateCommand.cs
src/Uno.UI.Tests/Foundation/Given_DelegateCommand.cs

None
Feature
No DelegateCommand that take a parameter
Add DelegateCommand<T>

Add DelegateCommand<T>

---

src/Uno.UI.Wasm/ts/WindowManager.ts
src/Uno.UI/UI/Xaml/Controls/BitmapIcon.cs
src/Uno.UI/UI/Xaml/Controls/Image/Image.netstd.cs

- Feature
Add BitmapIcon.ShowAsMonochrome support for WebAssembly.

Add BitmapIcon.ShowAsMonochrome support for WebAssembly

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/Controls/NativeCommandBarPresenter.iOS.cs

- Bugfix
On certain devices, the command bar has a bad height
The command bar has the good height on every device
https://nventive.visualstudio.com/Umbrella/_workitems/edit/134573

[iOS] Update CommandBar measurement for both iPhones and iPads

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/Controls/CommandBarRenderer.iOS.cs
src/Uno.UI/Controls/NativeCommandBarPresenter.iOS.cs
src/Uno.UI/Controls/NativeFramePresenter.iOS.cs
src/Uno.UI/Controls/UnoNavigationBar.iOS.cs
src/Uno.UI/UI/Xaml/Controls/CommandBar/CommandBar.cs
src/Uno.UWP/UI/ViewManagement/ApplicationView.iOS.cs

- Bugfix
The command bar has not the good on every device
The command bar height is set to the device one
https://nventive.visualstudio.com/Umbrella/_workitems/edit/134573

[iOS] Implements custom navigation bar

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.Android.cs

- Bugfix
If an item is removed from a ListView, the two next fetched item are the same one (duplicated)
Buffers are updated and no longer duplicate item
Some notes provided by David Oliver recommend not to update buffers in the same cycle that all views are srapped. This is not the case here since we remove just one but if weird behavior is happenning with the ListView, try to remove this modification first.
https://nventive.visualstudio.com/Umbrella/_workitems/edit/138117

[Android] Update buffers if an item is removed from a ListView

---

doc/articles/using-uno-ui.md

Missing information about the use of Custom Fonts
Added more information about the use of Custom Fonts

Added more information about the use of Custom Fonts.

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SolutionTemplate/UnoSolutionTemplate.VISX/UnoSolutionTemplate.VISX.csproj
src/SolutionTemplate/UnoSolutionTemplate/UnoSolutionTemplate.csproj
src/SourceGenerators/Uno.UI.SourceGenerators/DependencyObject/DependencyObjectGenerator.cs
src/SourceGenerators/Uno.UI.SourceGenerators/Uno.UI.SourceGenerators.csproj
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Automation.Peers/FrameworkElementAutomationPeer.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/Viewbox.cs
src/Uno.UI/UI/Xaml/Automation/Peers/FrameworkElementAutomationPeer.cs
src/Uno.UI/UI/Xaml/Controls/Grid/Grid.Layout.cs
src/Uno.UI/UI/Xaml/Controls/Image/Image.wasm.cs
src/Uno.UI/UI/Xaml/Controls/ViewBox/Viewbox.android.cs
src/Uno.UI/UI/Xaml/Controls/ViewBox/Viewbox.cs
src/Uno.UI/UI/Xaml/Controls/ViewBox/Viewbox.iOSmacOS.cs
src/Uno.UI/UI/Xaml/Controls/ViewBox/Viewbox.wasm.cs
src/Uno.UI/UI/Xaml/GridLength.cs
src/Uno.UI/UI/Xaml/Shapes/Path.cs
src/Uno.UI/Uno.UI.csproj

- Bugfix
- Feature
- Add support for GridLength conversion from double 
- Raise exceptions on missing styles in debug configuration
- Don't generate the Bindable attribute if already present
- Fix element name matching existing types fails to compile (e.g. ContentPresenter)
- Add working ViewBox stub 
- Don't fail on empty grid ArrangeOverride
- `Path.Data` property now invalidates measure and arrange
- Wasm `Image` logs Opened and Failed events
- Add UpToDateCheckInput to avoid VS invalid incremental rebuilds
- Adjust .NET template projects versions to 4.6.1
- Adjust Microsoft.CodeAnalysis versions to avoid restore conflicts

Misc updates

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml
src/Uno.UI/UI/Xaml/Style/Generic/SystemResources.xaml

- Feature
NavigationViewItem was missing some resources in order to build on iOS/Android with the default UWP Style.
Added missing resources for NavigationViewItem in Uno.UI
https://nventive.visualstudio.com/Umbrella/_workitems/edit/140034

Added missing resources for NavigationViewItem in Uno.UI

---

.vsts-ci.yml
build/SignClient.json
build/sign-package.ps1
doc/ReleaseNotes/_ReleaseNotes.md

- Feature
All nuget and vsix packages are now authenticode signed.

Sign the nuget and vsix packages

---

build/Uno.UI.nuspec

- Bugfix
Fixes missing assembly not introduced properly in #427.

Adjust Cecil path for nuget integration

---

doc/articles/supported-features.md

fixed formatting

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/Image/Image.cs

- Bugfix
The app freezes if the Content of a CommandBar is an Image without specified width
The app no longer freezes
https://nventive.visualstudio.com/Umbrella/_workitems/edit/138537/

[iOS] Fix app freezes if an Image without width is set in the CommandBar

---

src/Uno.UI/UI/Xaml/Controls/FlipView/FlipView.Android.cs

- Bugfix
The FlipView doesn't load new page or has some weird issues (see work items)
The FlipView works as it should
https://nventive.visualstudio.com/Umbrella/_workitems/edit/141899
https://nventive.visualstudio.com/Umbrella/_workitems/edit/141932
https://nventive.visualstudio.com/Umbrella/_workitems/edit/142057
https://nventive.visualstudio.com/Umbrella/_workitems/edit/142161
https://nventive.visualstudio.com/Umbrella/_workitems/edit/142156

[Android][FlipView] Fix NotifyDataSetChanged call

---

.vsts-ci.yml

Publish the sample application artifacts.

Publish the wasm sample app

---

src/SamplesApp/SamplesApp.Wasm/SamplesApp.Wasm.csproj
src/SamplesApp/SamplesApp.Wasm/web.config

- Bugfix
Fix missing IIS configuration file for the SampleApp deployment

Add missing IIS configuration file for Wasm sample app.

---

Doc/Controls/ToggleSwitch.md
doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/Controls/BindableSwitchCompat.Android.cs
src/Uno.UI/Controls/BindableUISwitch.iOS.cs
src/Uno.UI/UI/Xaml/Style/Generic/Generic.Native.xaml

- Bugfix
ToggleSwitch Uno default XAML Styles was causing a regression.
ToggleSwitch Uno default XAML Styles and documentation updated.
https://nventive.visualstudio.com/Umbrella/_workitems/edit/141907

Update ToggleSwitch Uno default XAML Styles, minor code changes and documentation.

---

README.md

Added WebSockets to list of sample projects

Added WebSockets to list of sample projects

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Style/Generic/SystemResources.xaml

- Bugfix
Missing some default Button ThemeBrushes resources.
Added back missing default Button ThemeBrushes resources.
https://nventive.visualstudio.com/Umbrella/_workitems/edit/142937

Added back some missing default Button ThemeBrushes resources.

---

doc/ReleaseNotes/_ReleaseNotes.md
doc/articles/supported-features.md
src/Uno.UI.Tests/BinderTests/Given_Binder.DynamicObject.cs
src/Uno.UI.Tests/Uno.UI.Tests.csproj
src/Uno.UI/DataBinding/BindingPropertyHelper.MemberBinder.cs
src/Uno.UI/DataBinding/BindingPropertyHelper.cs
src/Uno.UI/Uno.UI.csproj

This enables support for `Elmish.Uno`.
- Feature

Add support for DynamicObject data binding

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SolutionTemplate/UnoSolutionTemplate.VISX/source.extension.vsixmanifest

GitHub Issue (If applicable): #420
- Feature
Add support for VS2019 VSIX installation.
https://nventive.visualstudio.com/Umbrella/_workitems/edit/143155

Enable vsix support for VS2019

---

src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.Android.cs

- Bugfix
The keyboard does not dismiss when a TextBox is unloaded. This is regression introduced by #456, where the unloaded event is raised earlier, making the FocusChangeListener not raising the final loss of focus.
The keyboard is dismissed properly when a TextBox is unloaded.
https://nventive.visualstudio.com/Umbrella/_workitems/edit/143163

[Android] Fix keyboard dismissal in TextBox

---

src/Uno.UI/Extensions/ObservableCollectionUpdateResultsExtensions.cs
src/Uno.UI/UI/Xaml/Controls/FlipView/FlipView.Android.cs
src/Uno.UI/UI/Xaml/Controls/FlipView/FlipView.iOS.cs
src/Uno.UI/UI/Xaml/Controls/ItemsControl/ItemsControl.cs

- Bugfix
Changing selected index with tabs on a FlipView cause it to reload data every time. The SwipeGesture does not refresh the data.
The data are not refreshed every time when a new tab is selected
https://nventive.visualstudio.com/Umbrella/_workitems/edit/143176

[Android][FlipView] Check if items have changed to notify the adapter

---

src/SolutionTemplate/UnoSolutionTemplate/Wasm/Program.cs
src/Uno.UI.Wasm/ts/Interop/ManagedObject.ts
src/Uno.UI/LinkerDefinition.Wasm.xml
src/Uno.UI/Uno.UI.csproj
src/Uno.UWP/UI/Core/CoreDispatcher.wasm.cs

- Bugfix
- Wasm Animations depending on `ManagedObject` typescript API when the linker is enabled.
- Adjust linker file visibility
- Adjust CoreDispatcher.DispatcherCallback signature for AOT builds
- Adjust Wasm template main method return value

Adjust linker definitions

---

src/Directory.Build.props
src/Directory.Build.targets
src/PlatformItemGroups.props
src/SolutionTemplate/UnoLibraryTemplate/UnoLibraryTemplate.csproj
src/SolutionTemplate/UnoSolutionTemplate.VISX/UnoSolutionTemplate.VISX.csproj
src/SolutionTemplate/UnoSolutionTemplate/UnoSolutionTemplate.csproj
src/SourceGenerators/System.Xaml/Uno.Xaml.csproj
src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props
src/SourceGenerators/Uno.UI.SourceGenerators/Uno.UI.SourceGenerators.csproj
src/SourceGenerators/Uno.UI.Tasks/Content/Uno.UI.Tasks.targets
src/SourceGenerators/XamlGenerationTests.Core/XamlGenerationTests.Core.csproj
src/SourceGenerators/XamlGenerationTests/XamlGenerationTests.csproj
src/Uno.CrossTargetting.props
src/Uno.Foundation/Uno.Foundation.csproj
src/Uno.UI.BindingHelper.Android/Uno.UI.BindingHelper.Android.csproj
src/Uno.UI.Maps/Uno.UI.Maps.csproj
src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.csproj
src/Uno.UI.Tests/Uno.UI.Tests.csproj
src/Uno.UI.Toolkit/Uno.UI.Toolkit.csproj
src/Uno.UI.sln
src/Uno.UI/Uno.UI.csproj
src/Uno.UWP/Uno.csproj
src/UnoItemTemplate/UnoItemTemplate.csproj
src/global.json

- Bugfix
- Add support for VS2019
- Adjust MSBuild extras to be used at the top level SDK
- Create fake android resgen file (removes warnings)
- Fix initial build from clean repo
- Fix warnings
- Disable SourceLink in debug builds

Multiple solution updates

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/FlyoutTests/Flyout_Events.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/FlyoutTests/Flyout_Events.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/FlyoutTests/Flyout_Simple.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/FlyoutTests/Flyout_Simple.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/FlyoutTests/Flyout_Target.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/FlyoutTests/Flyout_Target.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/FlyoutTests/Flyout_Vanilla.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/FlyoutTests/Flyout_Vanilla.xaml.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/FlyoutPresenter.cs
src/Uno.UI/UI/Xaml/Controls/Flyout/Flyout.wasm.cs
src/Uno.UI/UI/Xaml/Controls/Flyout/FlyoutPresenter.cs
src/Uno.UI/UI/Xaml/Controls/Popup/Popup.wasm.cs
src/Uno.UI/UI/Xaml/Controls/Popup/PopupRoot.cs
src/Uno.UI/UI/Xaml/Style/Generic/FlyoutPresenter.xaml
src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml
src/Uno.UI/UI/Xaml/Style/Generic/SystemResources.xaml
src/Uno.UI/UI/Xaml/UIElement.wasm.cs
src/Uno.UI/Uno.UI.csproj

- Feature
- Bugfix
- Fixed default Flyout anchor placement
- Added default FlyoutPresenter style
- Fixed UIElement.TransformToVisual with target element

[Wasm] Flyout and FlyoutPresenter updates

---

src/SamplesApp/SamplesApp.Droid/SamplesApp.Droid.csproj
src/SamplesApp/SamplesApp.Wasm/SamplesApp.Wasm.csproj
src/SamplesApp/SamplesApp.iOS/SamplesApp.iOS.csproj
src/SamplesApp/SamplesApp.macOS/SamplesApp.macOS.csproj
src/SourceGenerators/Uno.UI.SourceGenerators/Uno.UI.SourceGenerators.csproj
src/SourceGenerators/Uno.UI.Tasks/Uno.UI.Tasks.csproj
src/SourceGenerators/XamlGenerationTests.Core/XamlGenerationTests.Core.csproj
src/SourceGenerators/XamlGenerationTests/XamlGenerationTests.csproj
src/Uno.Foundation/Uno.Foundation.csproj
src/Uno.MonoAnalyzers/MonoNotSupportedAPIAnalyzer.cs
src/Uno.UI.Maps/Uno.UI.Maps.csproj
src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.csproj
src/Uno.UI.Tests.Performance/Uno.UI.Tests.Performance.csproj
src/Uno.UI.Tests/Uno.UI.Tests.csproj
src/Uno.UI.Toolkit/Uno.UI.Toolkit.csproj
src/Uno.UI.Wasm.Tests/Uno.UI.Wasm.Tests.csproj
src/Uno.UI.Wasm/Uno.UI.Wasm.csproj
src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerFlyout.Android.cs
src/Uno.UI/Uno.UI.csproj
src/Uno.UWP/Uno.csproj

- Bugfix
Add more validations against 15.9 and later only String apis.

Add more validations for 15.9 and later API usage

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/FontIcon/FontIconControlTest.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Slider/SliderViewModel.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Slider/Slider_Features.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Slider/Slider_Features.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Slider/Slider_Frequency.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Slider/Slider_Frequency.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Slider/Slider_Inside_ScrollViewer.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Slider/Slider_Inside_ScrollViewer.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Slider/Slider_Simple.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Slider/Slider_Simple.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Slider/Slider_Styled.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Slider/Slider_Styled.xaml.cs

New samples for Slider (from private repo)
- ~~Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)~~
- ~~Updated the [Release Notes](https://github.com/nventive/Uno/tree/master/doc/ReleaseNotes)~~

Added tests for Slider

---

src/Uno.UI.RuntimeTests/Tests/Windows_ApplicationModel_Resources/Given_ResourceLoader.cs

- Other: Fix invalid test
Test fails
Test succeed
The test was copy pasted from the Unit test project which does not contains the same resources setup

Fix resource UI runtime test

---

doc/Controls/ToggleSwitch.md

Wrong ToggleSwitch native style binding in the documentation for BindableUISwitch
Restore ToggleSwitch native style binding for IsOn in the documentation for BindableUISwitch

Restore ToggleSwitch native style binding for IsOn in the documentation for BindableUISwitch

---

doc/ReleaseNotes/Release-1.40.md
src/SamplesApp/SamplesApp.Droid/Resources/values/Styles.xml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Models/TimePickerViewModel.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TimePicker/Sample1.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TimePicker/Sample2.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TimePicker/Sample2_Styles.xaml
src/Uno.UI/Extensions/TimeSpanExtensions.cs
src/Uno.UI/Mixins/DependencyPropertyMixins.tt
src/Uno.UI/UI/Xaml/Controls/Flyout/FlyoutBase.cs
src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePicker.cs
src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePicker.md
src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerFlyout.Android.cs
src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerFlyout.iOS.cs
src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerFlyoutPresenter.cs
src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerSelector.Android.cs
src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerSelector.cs
src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerSelector.iOS.cs
src/Uno.UI/UI/Xaml/Controls/TimePicker/UnoTimePickerDialog.Android.cs
src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml

Added time increment to ios and android
143859

Timepicker - minute increment (ios/android)

---

src/SamplesApp/SamplesApp.Shared/Strings/en/Resources.resw
src/SourceGenerators/Uno.UI.Tasks/ResourcesGenerator/ResourcesGenerationTask.cs
src/Uno.UI.RuntimeTests/Tests/Uno_UI_Services/Given_ResourceService.cs

Add a resource fix for text resources not working on latest xamarin

Add more fixes into beta

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.Wasm/SamplesApp.Wasm.csproj
src/Uno.UI.RuntimeTests/LinkerDefinition.Wasm.xml
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Data/Given_Convert.cs
src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.csproj
src/Uno.UI.Wasm/WasmScripts/Uno.UI.js
src/Uno.UI/LinkerDefinition.Wasm.xml
src/Uno.UWP/UI/Core/CoreDispatcher.cs

- Bugfix
This fixes Uri bindings implicit conversions

[Wasm] Add linker exclusion for System.*Converters

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.Android.cs
src/Uno.UI/UI/Xaml/IFrameworkElementImplementation.iOS.tt

Add more fixes into beta
https://nventive.visualstudio.com/Umbrella/_workitems/edit/144101
https://nventive.visualstudio.com/Umbrella/_workitems/edit/146962

Merge fixes into beta

---

doc/articles/debugging-uno-ui.md

Added some pre-requisites for a proper build of the Uno.UI solution.
- ~~[ ] Tested code with current [supported SDKs](../README.md#supported)~~
- ~~[ ] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)~~
- ~~[ ] Contains **NO** breaking changes~~
- ~~[ ] Updated the [Release Notes](https://github.com/nventive/Uno/tree/master/doc/ReleaseNotes)~~
- ~~[ ] Associated with an issue (GitHub or internal)~~

Update the Uno.UI solution build documentation

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/UIElementTests/Arrange_Performance01.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/UIElementTests/Arrange_Performance01.xaml.cs
src/Uno.UI.Wasm/WasmScripts/Uno.UI.d.ts
src/Uno.UI.Wasm/WasmScripts/Uno.UI.js
src/Uno.UI.Wasm/ts/WindowManager.ts
src/Uno.UI.Wasm/tsBindings/WindowManagerArrangeElementParams.ts
src/Uno.UI.Wasm/tsBindings/WindowManagerSetElementTransformParams.ts
src/Uno.UI.Wasm/tsBindings/WindowManagerSetStyleDoubleParams.ts
src/Uno.UI/Media/NativeRenderTransformAdapter.wasm.cs
src/Uno.UI/UI/Xaml/Controls/Image/Image.wasm.cs
src/Uno.UI/UI/Xaml/FrameworkElement.Layout.wasm.cs
src/Uno.UI/UI/Xaml/Shapes/ArbitraryShapeBase.wasm.cs
src/Uno.UI/UI/Xaml/UIElement.wasm.cs
src/Uno.UI/UI/Xaml/WindowManagerInterop.Wasm.cs

- Performance
The current arrange implementation uses a lot of string formatting to send data to Javascript.
The new implementation uses TSBindings to improve the performance, and here are some results for 1000 arrange calls, using the interpreter:
- Before 590ms
- After, 360ms

[Wasm] Improve arrange and transform performance

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Progress/ProgressRing.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Progress/ProgressRing.xaml.cs

UI Sample
Added a sample for showing ProgressRings

Added ProgressRing sample

---

doc/articles/howto-use-uno-in-xamarin-forms.md

Document Uno integration with X.F

---

doc/ReleaseNotes/_ReleaseNotes.md

Update release notes for resource generation target breaking change

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media_Animation/DoubleAnimation_BeginTime.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media_Animation/DoubleAnimation_BeginTime.xaml.cs
src/SourceGenerators/System.Xaml/System.Xaml/XamlXmlReader.cs
src/SourceGenerators/Uno.UI.SourceGenerators/BindableTypeProviders/BindableTypeProvidersGenerationTask.cs
src/Uno.MonoAnalyzers/MonoNotSupportedAPIAnalyzer.cs
src/Uno.UWP/UI/Composition/CoreAnimation.iOS.cs

trimstart compatibility : https://nventive.visualstudio.com/Umbrella/_workitems/edit/147530
support uno in project namespaces https://nventive.visualstudio.com/Umbrella/_workitems/edit/147530
animation beginTime https://nventive.visualstudio.com/Umbrella/_workitems/edit/147309

Add to beta

---

src/Uno.UI.Tests/BinderTests/Given_BindingPath.cs
src/Uno.UI/Controls/Window.iOS.cs
src/Uno.UI/DataBinding/BindingPath.cs
src/Uno.UI/DataBinding/BindingPropertyHelper.cs
src/Uno.UI/UI/Xaml/Controls/SplitView/SplitView.cs
src/Uno.UI/UI/Xaml/Controls/SplitView/SplitView.iOS.cs
src/Uno.UI/UI/Xaml/Media/Animation/DoubleAnimation.cs

https://nventive.visualstudio.com/Umbrella/_workitems/edit/147416
https://nventive.visualstudio.com/Umbrella/_workitems/edit/147515
https://nventive.visualstudio.com/Umbrella/_workitems/edit/146335
https://nventive.visualstudio.com/Umbrella/_workitems/edit/147766

Add to beta : SplitView fix and a fix for end of animations

---

src/SolutionTemplate/UnoSolutionTemplate/UWP/Package.appxmanifest

Fix recent regression in Uno app template by restore closing Package tag.

[SolutionTemplate] Repair UWP package manifest

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.Wasm/WasmCSS/Uno.UI.css

- Bugfix
The root element can scroll on touch devices, and shows a boucing effect when scrolling at the bounds.
This removes the bouncing effect of the root element.

Disable root scrolling on touch devices

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Automation/AutomationProperty.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml/Application.cs
src/Uno.UI/UI/Xaml/Application.cs
src/Uno.UI/UI/Xaml/Application.wasm.cs
src/Uno.UI/UI/Xaml/Automation/AutomationProperty.cs
src/Uno.UI/UI/Xaml/Automation/ScrollPatternIdentifiers.cs
src/Uno.UI/UI/Xaml/Style/Generic/SystemResources.xaml
src/Uno.UI/UI/Xaml/UIElement.cs
src/Uno.UI/UI/Xaml/Window.Android.cs
src/Uno.UI/UI/Xaml/Window.Desktop.cs
src/Uno.UI/UI/Xaml/Window.cs
src/Uno.UI/UI/Xaml/Window.iOS.cs
src/Uno.UI/UI/Xaml/Window.macOS.cs
src/Uno.UI/UI/Xaml/Window.wasm.cs
src/Uno.UI/UI/Xaml/WindowCreatedEventArgs.cs

- Bugfix
- Feature
* Add support for `Application.OnWindowCreated`
* Added non-throwing stubs for `AutomationProperty`
* Add missing system resources
* Make `UIElement.IsPointerPressed` and `IsPointerOver` internal, as those are not part of the UWP API.

Misc updates and alignments

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SolutionTemplate/UnoSolutionTemplate/UnoSolutionTemplate.csproj
src/SolutionTemplate/UnoSolutionTemplate/iOS/UnoQuickStart.iOS.csproj
src/SolutionTemplate/UnoSolutionTemplate/iOS/iOS.vstemplate

Redo part of this PR into stable 
https://github.com/nventive/Uno/pull/671

Fix iOS Assets

---

src/Uno.UI.Wasm/WasmScripts/Uno.UI.js
src/Uno.UI.Wasm/ts/WindowManager.ts

- Bugfix
When installed as PWA on iOS, applications does not resize properly when rotating the device
It works 😜 (at least on my phone)
https://nventive.visualstudio.com/Umbrella/_workitems/edit/149381

Fix applications not resizing properly when installed as PWA on iOS

---

src/Uno.UI/Controls/NavigationBarHelper.Android.cs
src/Uno.UI/KeyboardRectProvider.Android.cs
src/Uno.UI/UI/ViewManagement/InputPane/InputPane.Android.cs
src/Uno.UI/UI/ViewManagement/InputPane/InputPane.cs
src/Uno.UI/UI/ViewManagement/InputPane/InputPaneVisibilityEventArgs.cs
src/Uno.UI/UI/Xaml/ApplicationActivity.Android.cs
src/Uno.UI/UI/Xaml/Window.Android.cs

- Bugfix
KeyboardRectProvider doesn't consider NavigationBar visibility causing extra spaces or elements behind keyboard depending of the case
It's all aligned in any configuration
https://nventive.visualstudio.com/Umbrella/_workitems/edit/145370
https://nventive.visualstudio.com/Umbrella/_workitems/edit/145363
https://nventive.visualstudio.com/Umbrella/_workitems/edit/145379
Related UI Tests :
https://dev.azure.com/nventive/Umbrella/_git/Uno.UI/pullrequest/20242

[Android] Review InputPane / KeyboardRectProvider measurment

---

doc/ReleaseNotes/_ReleaseNotes.md
gitversion.yml

Bump version to 1.45

---

build/Uno.UI.nuspec
build/uno.ui.targets

- Bugfix
HAS_UNO is defined for legacy iOS/Android projects

Remove uap10.0 nuget msbuild targets

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_FrameworkElement.cs
src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.csproj
src/Uno.UI/UI/Xaml/Controls/Pivot/Pivot.cs
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.cs
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.wasm.cs
src/Uno.UI/UI/Xaml/DependencyObjectStore.cs
src/Uno.UI/Uno.UI.csproj

- Bugfix
- Performance
- Wasm TextBlocks are measure multiple times with the known sizes, mainly caused by Grid algorithm.
- Pivot is now using template pooling for PivotItem

Performance improvements

---

doc/Controls/Pivot.md

https://nventive.visualstudio.com/Umbrella/_workitems/edit/150068

Add documentation about native Pivot styles

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/ListViewBase/BufferViewCache.Android.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.Android.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.Android.cs

Bugfix
Fixes several issues causing incorrect/stale item views to be reused in the ListView.
https://nventive.visualstudio.com/Umbrella/_workitems/edit/140946

[Android] Fix ListView duplicate items issues

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.BindingHelper.Android/Uno/UI/UnoViewGroup.java

Ensure that RequestLayout() calls during OnLoaded are repeated once the view is fully natively loaded. This fixes bug where ListView items were showing incorrect data in some cases (because TextBlock doesn't visually update until it's been through a Measure+Arrange pass).
Bugfix
https://nventive.visualstudio.com/Umbrella/_workitems/edit/146790

[Android] Ensure RequestLayout() gets propagated correctly during managed loading

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.cs
src/Uno.UI/UI/Xaml/Controls/Primitives/SelectorItem.cs
src/Uno.UI/UI/Xaml/VisualStateManager.cs

Check actual current state rather than using flag on SelectorItem, since the flag may get out-of-sync if the SelectorItem's template changes.
Bugfix
https://nventive.visualstudio.com/Umbrella/_workitems/edit/150469

ListView - fix MultiSelect state not always applied

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/IScrollContentPresenter.iOS.cs
src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/IUIScrollView.iOS.cs
src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.iOS.cs
src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.cs
src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.iOS.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/MultilineTextBoxView.iOS.cs

Redirect the method to inner MultilineTextView to allow the text to scroll correctly.
Feature
https://nventive.visualstudio.com/Umbrella/_workitems/edit/145203

[iOS] Support ScrollViewer.ChangeView() inside TextBox

---

doc/ReleaseNotes/_ReleaseNotes.md
doc/articles/ListViewBase.md
src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.iOS.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/NativeListViewBase.iOS.cs

Allows native insert/delete animations to be disabled when undesired or as a workaround when they're glitchy.
https://nventive.visualstudio.com/Umbrella/_workitems/edit/150793

[iOS] Add ListView.UseCollectionAnimations flag

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ToggleSwitchControl/Models/ToggleSwitchViewModel.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ToggleSwitchControl/Native_ToggleSwitch.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ToggleSwitchControl/Native_ToggleSwitch.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ToggleSwitchControl/ToggleSwitchUnloadReload.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ToggleSwitchControl/ToggleSwitchUnloadReload.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ToggleSwitchControl/ToggleSwitch_Custom.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ToggleSwitchControl/ToggleSwitch_Custom.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ToggleSwitchControl/ToggleSwitch_Default_Style.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ToggleSwitchControl/ToggleSwitch_Default_Style.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ToggleSwitchControl/ToggleSwitch_IsOn.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ToggleSwitchControl/ToggleSwitch_IsOn.xaml.cs
src/Uno.UI.BindingHelper.Android/Uno/UI/UnoViewGroup.java
src/Uno.UI.Tests/RoutedEventTests/Given_TappedRoutedEvent.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/ToggleSwitch.cs
src/Uno.UI/UI/Xaml/Controls/ToggleSwitch.cs
src/Uno.UI/UI/Xaml/UIElement.RoutedEvents.cs

Add toggleswitch fix and pointercanceled fix to beta 1.44

---

THIRD-PARTY-NOTICES.md
doc/articles/toc.yml
doc/articles/uno-toolchain-telemetry.md
src/Directory.Build.props
src/SourceGenerators/Uno.UI.SourceGenerators/Helpers/HashBuilder.cs
src/SourceGenerators/Uno.UI.SourceGenerators/Telemetry/PersistenceChannel/BaseStorageService.cs
src/SourceGenerators/Uno.UI.SourceGenerators/Telemetry/PersistenceChannel/FixedSizeQueue.cs
src/SourceGenerators/Uno.UI.SourceGenerators/Telemetry/PersistenceChannel/FlushManager.cs
src/SourceGenerators/Uno.UI.SourceGenerators/Telemetry/PersistenceChannel/PersistenceChannel.cs
src/SourceGenerators/Uno.UI.SourceGenerators/Telemetry/PersistenceChannel/PersistenceChannelDebugLog.cs
src/SourceGenerators/Uno.UI.SourceGenerators/Telemetry/PersistenceChannel/PersistenceTransmitter.cs
src/SourceGenerators/Uno.UI.SourceGenerators/Telemetry/PersistenceChannel/Sender.cs
src/SourceGenerators/Uno.UI.SourceGenerators/Telemetry/PersistenceChannel/SnapshottingCollection.cs
src/SourceGenerators/Uno.UI.SourceGenerators/Telemetry/PersistenceChannel/SnapshottingDictionary.cs
src/SourceGenerators/Uno.UI.SourceGenerators/Telemetry/PersistenceChannel/StorageService.cs
src/SourceGenerators/Uno.UI.SourceGenerators/Telemetry/PersistenceChannel/StorageTransmission.cs
src/SourceGenerators/Uno.UI.SourceGenerators/Telemetry/TelemetryClient.cs
src/SourceGenerators/Uno.UI.SourceGenerators/Telemetry/TelemetryCommonProperties.cs
src/SourceGenerators/Uno.UI.SourceGenerators/Uno.UI.SourceGenerators.csproj
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.Telemetry.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGenerator.cs

- Feature
The XAML build time feature generates telemetry data for the purpose of determining if the build tooling is working well.
https://nventive.visualstudio.com/Umbrella/_workitems/edit/150049

Add XAML build time generation telemetry feature

---

src/Uno.UI.BindingHelper.Android/Uno/UI/UnoViewGroup.java

The new dispatchTouchEvent() code to handle children with StaticTransformations calls child.dispatchTouchEvent() for all children, unlike ViewGroup.dispatchTouchEvent() which only calls for children for whom the touch lies in bounds. At least one consequence of this is requestFocus() wrongly getting called in some circumstances.
As a narrow workaround, we block requestFocus() from being propagated in this specific case.
Bugfix
https://nventive.visualstudio.com/Umbrella/_workitems/edit/150674

[Android] Prevent sibling of transformed view stealing focus

---

build/Uno.UI.nuspec
src/SourceGenerators/Uno.UI.SourceGenerators/Properties/AssemblyInfo.cs
src/SourceGenerators/Uno.UI.SourceGenerators/Uno.UI.SourceGenerators.csproj

- Bugfix
- Including the Uno.ui nuget package fails the xaml generation
A missing nuget package dependency is now added

Adjust nuget package missing dependencies

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props

GitHub Issue (If applicable): #784 
Bugfix 
`not_wasm` prefix in XAML wasn't taken into account.
Now taken into account.

XamlGeneration - exclude 'not_wasm' from WASM

---

src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.Android.cs

Prevent integer overflow in UnoTwoDScrollView.clamp() erroneously permitting very large scrolls.
Bugfix
https://nventive.visualstudio.com/Umbrella/_workitems/edit/145203

[Android] Fix ScrollViewer.ChangeView(double.MaxValue,...)

---

src/Uno.UI/Extensions/TimelineExtensions.iOS.cs

Bugfix
https://nventive.visualstudio.com/Umbrella/_workitems/edit/151209

[iOS] Fix crash from access to collected view in animation

---

src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerSelector.iOS.cs

- Bugfix
When time was saved on TimePicker, it set it to the UTC TimeZone
When time is saved on TimePicker, it set it to the local TimeZone
https://nventive.visualstudio.com/Umbrella/_workitems/edit/151966

[iOS] Set save time to the local time instead of the UTC one

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/Transform/AnimatedContentControl.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/Transform/Animated_View_With_Transformed_Ancestor.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/Transform/Animated_View_With_Transformed_Ancestor.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/Transform/ProgressRing_With_Transformed_Ancestor.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/Transform/ProgressRing_With_Transformed_Ancestor.xaml.cs
src/Uno.UI.BindingHelper.Android/Uno/UI/UnoViewGroup.java
src/Uno.UI/Media/NativeRenderTransformAdapter.Android.cs
src/Uno.UI/UI/Xaml/Controls/ProgressRing/ProgressRing.Android.cs
src/Uno.UI/UI/Xaml/Media/Animation/Animators/AnimatorFactory.Android.cs

Bugfix
https://nventive.visualstudio.com/Umbrella/_workitems/edit/151547

[Android] Fix animations within transformed hierarchy

---

src/Uno.UI.TestComparer/AzureDevopsDownloader.cs

- Bugfix 
Fixed non-PR builds screenshot comparison

Skip existing files in test comparer extraction

---

src/Uno.UI.Tests/RoutedEventTests/Given_TappedRoutedEvent.cs
src/Uno.UI/UI/Xaml/Controls/Slider/Slider.cs
src/Uno.UI/UI/Xaml/UIElement.RoutedEvents.cs

Fixes from : https://github.com/nventive/Uno/pull/792

Include video player fixes

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/HorizontalListViewGrouped.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListViewEmptyGroups.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListViewGrouped.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListViewGroupedChanging.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListViewGroupedEmpty.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListViewGroupedEmptyHeader.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListViewGrouped_ItemContainerStyleSelector.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListViewGrouped_ItemContainerStyleSelector.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_ItemTemplateSelector_And_ItemContainerStyleSelector.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_WithFlipView.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/RandomDataTemplateSelector.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Models/ListViewGroupedViewModel.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Models/ListViewViewModel.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Models/ListViewWithFlipViewViewModel.cs

UI samples
https://nventive.visualstudio.com/Umbrella/_workitems/edit/151997

Restore grouped ListView samples

---

.azure-devops-wasm-uitests.yml

The build may for for path too long in the tests comparer
Disabled the comparsion job for the time benig

Disable screenshot comparison

---

src/Uno.UI.BindingHelper.Android/Uno/UI/UnoViewGroup.java
src/Uno.UI/Media/NativeRenderTransformAdapter.Android.cs
src/Uno.UI/UI/Xaml/Controls/ProgressRing/ProgressRing.Android.cs

Ensure ProgressRing invalidates itself (since it's not an UnoViewGroup), and ensure it's invalidated when transform is applied.
Bugfix
https://nventive.visualstudio.com/Umbrella/_workitems/edit/151547

[Android] Ensure ProgressRing updates correctly inside transformed hierarchy

---

.azure-devops-wasm-uitests.yml
.gitignore
src/Uno.UI.TestComparer/AzureDevopsDownloader.cs
src/Uno.UI.TestComparer/Program.cs
src/Uno.UI.TestComparer/Properties/launchSettings.json

Place tests results in a separate artifact

---

doc/ReleaseNotes/_ReleaseNotes.md
doc/articles/PasswordVault.md
src/SamplesApp/SamplesApp.iOS/Entitlements.plist
src/SamplesApp/SamplesApp.iOS/SamplesApp.iOS.csproj
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_Security_Credentials/PasswordVaultTests/CredentialsPersistence.xaml
src/SamplesApp/UITests.Shared/Windows_Security_Credentials/PasswordVaultTests/CredentialsPersistence.xaml.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Security.Credentials/PasswordCredential.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Security.Credentials/PasswordVault.cs
src/Uno.UWP/Security.Credentials/PasswordCredential.cs
src/Uno.UWP/Security.Credentials/PasswordVault.Android.cs
src/Uno.UWP/Security.Credentials/PasswordVault.Wasm.cs
src/Uno.UWP/Security.Credentials/PasswordVault.cs
src/Uno.UWP/Security.Credentials/PasswordVault.iOS.cs

- Feature
`PasswordVault` is not implemented
`PasswordVault` is implemented
https://nventive.visualstudio.com/_workitems/edit/151403

Add PasswordVault for supported platforms.

---

src/Uno.UI.BindingHelper.Android/Uno/UI/UnoViewGroup.java
src/Uno.UI/Media/NativeRenderTransformAdapter.Android.cs
src/Uno.UI/UI/Xaml/Media/Animation/Animators/AnimatorFactory.Android.cs

- Refactoring (no functional changes, no api changes) 
During build the created methods based on the java ones were automatically given names that conflicted with other methods
Builds properly
Methods only called internally so no breaking changes
https://nventive.visualstudio.com/Umbrella/_workitems/edit/152538

Fixed methods with conflicting names

---

src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.iOS.cs

Scroll container was not being set properly (regression from changes to support ChangeView inside TextBox).
Bugfix
https://nventive.visualstudio.com/Umbrella/_workitems/edit/152301

[iOS] Fix ChangeView

---

src/Uno.UI/UI/Xaml/Controls/ProgressRing/ProgressRing.Android.cs

This is necessary for the ProgressRing to redraw correctly when inside a transformed hierarchy.
Bugfix
https://nventive.visualstudio.com/Umbrella/_workitems/edit/151547

[Android] Invalidate ProgressRing when visibility changes

---

gitversion.yml
src/Uno.UI.Tests/RoutedEventTests/Given_TappedRoutedEvent.cs
src/Uno.UI/Extensions/NSDateExtensions.iOS.cs
src/Uno.UI/Extensions/TimelineExtensions.iOS.cs
src/Uno.UI/Media/NativeRenderTransformAdapter.Android.cs
src/Uno.UI/Media/NativeRenderTransformAdapter.cs
src/Uno.UI/Media/NativeRenderTransformAdapter.iOSmacOS.cs
src/Uno.UI/Media/NativeRenderTransformAdapter.wasm.cs
src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePicker.cs
src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePickerSelector.iOS.cs
src/Uno.UI/UI/Xaml/Controls/Slider/Slider.cs
src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePicker.cs
src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerFlyout.iOS.cs
src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerSelector.iOS.cs
src/Uno.UI/UI/Xaml/UIElement.RoutedEvents.cs

Release stable AA hotfix

---

README.md
doc/articles/get-started.md
doc/articles/getting-started-tutorial-1.md
doc/articles/intro.md

Updates readme to align somewhat with the rest of the docs, plus a few tweaks to wording elsewhere.

Docs - update readme

---

build/_HOW-TO-BUILD-AND-DEBUG-APPS.md

docs: corrected "tweating" -> "tweaking"

---

doc/articles/Uno.UI.Toolkit.md
doc/articles/getting-started-tutorial-1.md

Docs - update tutorial link

---

gitversion.yml

GitHub Issue (If applicable): #865 
- Other: Configure GitVersion for feature branches
~~- [ ] Tested code with current [supported SDKs](../README.md#supported)~~
~~- [ ] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)~~
~~- [ ] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)~~
~~- [ ] [Wasm UI Tests](doc/articles/working-with-the-samples-apps.md#running-the-webassembly-ui-tests-snapshots) are not showing unexpected any differences~~
~~- [ ] Contains **NO** breaking …

Setup GitVersion for feature branches

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/UIElement.iOS.cs

… as it introduce multiple other issues and it was only a temp work around
cf. discussion https://github.com/nventive/Uno/pull/865

Revert raise of PointerRelease in TouchesCancelled

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UWP/Generated/3.0.0.0/Windows.Globalization/Calendar.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Globalization/CalendarIdentifiers.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Globalization/DayOfWeek.cs
src/Uno.UWP/Globalization/Calendar.cs
src/Uno.UWP/Globalization/CalendarIdentifiers.cs
src/Uno.UWP/Globalization/ClockIdentifiers.cs
src/Uno.UWP/Globalization/DayOfWeek.cs

- Feature
Not implemented
Can use (at least partially) `Windows.Globalization.Calendar`
Internal Issue (If applicable): https://nventive.visualstudio.com/_workitems/edit/154396

Add `Windows.Globalization.Calendar`

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/MarkupExtensionTests/MarkupExtension.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/MarkupExtensionTests/MarkupExtension.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/MarkupExtensionTests/Simple.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/xBindTests/XBindviewModel.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/xBindTests/xBind.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/xBindTests/xBind.xaml.cs

https://github.com/nventive/Uno/issues/347
Feature
Added samples for x:Bind and MarkupExtension

 Added two samples to demonstrate x:Bind and MarkupExtension features

---

src/Uno.UI.TestComparer/AzureDevopsDownloader.cs

- Bugfix
The test comparer may fail if a build does not have the proper artifacts
Builds are skipped when artifacts are missing

Ignore builds missing the wasm screenshots artifacts

---

src/Uno.UI/UI/Xaml/Controls/NavigationView/NavigationViewList.cs
src/Uno.UWP/Globalization/Calendar.cs

- Bugfix
- Feature
- Possible null ref when opening the `NavigationView`
- Some properties of `Windows.Globalization.Calendar` are not implemented
The opposite
- https://nventive.visualstudio.com/_workitems/edit/154506
- https://nventive.visualstudio.com/_workitems/edit/154562

Minors fixes for calc

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Button/RadioButton_Pressed.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Button/RadioButton_Pressed.xaml.cs

Demonstrate radiobuttons with a pressed states and changing style
[152993](https://nventive.visualstudio.com/Umbrella/_workitems/edit/152993)

Demonstrate radiobuttons with a pressed states and changing style

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Flyout/Flyout_Attached.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Flyout/Flyout_Attached.xaml.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls.Primitives/FlyoutBase.cs
src/Uno.UI/UI/Xaml/Controls/Flyout/FlyoutBase.cs
src/Uno.UI/UI/Xaml/Controls/Popup/Popup.iOS.cs
src/Uno.UI/UI/Xaml/FrameworkTemplate.cs
src/Uno.UI/UI/Xaml/UIElement.iOS.cs

Implement FlyoutBase.AttachedFlyout, fix iOS Popup bug

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.Shared/Strings/en-US/Resources.resw
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/Localization/CustomTextControl.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/Localization/Localization_Implicit.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/Localization/Localization_Implicit.xaml.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.Reflection.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/SourceGenerators/XamlGenerationTests/CustomTextControl.cs
src/SourceGenerators/XamlGenerationTests/Localization_Implicit.xaml
src/SourceGenerators/XamlGenerationTests/Localization_Implicit.xaml.cs
src/SourceGenerators/XamlGenerationTests/Resources.resw
src/SourceGenerators/XamlGenerationTests/XamlGenerationTests.csproj

Ensure properties localized with x:Uid are applied even if set explicitly or implicitly in Xaml. (Xaml values are overridden)
#921 
Bugfix

Fix localization not applied if property is not set in Xaml

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/xBindTests/xBind_Field.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/xBindTests/xBind_Field.xaml.cs
src/Uno.UI.Tests/BinderTests/Given_Binder.cs
src/Uno.UI/DataBinding/BindingPropertyHelper.cs

Support x:Bind to fields

---

src/Uno.UWP/System/VirtualKeyHelper.wasm.cs

- Bugfix 
Some key of keypad on WASM are not mapped properly
They are mapped
https://nventive.visualstudio.com/_workitems/edit/154384

Fix keypad keys mapping

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs

Note: this still requires the property to be set in Xaml.
Bugfix

Fix localized attached properties

---

doc/articles/getting-started-tutorial-1.md

Docs - amend VS 2019 requirement in tutorial

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MediaPlayerElement/MediaPlayerElement_Stretch_Fill.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MediaPlayerElement/MediaPlayerElement_Stretch_Fill.xaml.cs
src/Uno.UI/UI/Xaml/Controls/MediaPlayer/MediaPlayerElement.cs
src/Uno.UI/UI/Xaml/Controls/MediaPlayer/MediaPlayerPresenter.Android.cs
src/Uno.UI/UI/Xaml/Controls/MediaPlayer/MediaPlayerPresenter.iOS.cs
src/Uno.UWP/Media/Playback/MediaPlayer.Android.cs

Fixes various issue with Stretch property, plus NRE at end of playback.
#977 
Bugfix

MediaPlayerElement fixes

---

src/SamplesApp/SamplesApp.Droid/Properties/AndroidManifest.xml
src/SamplesApp/SamplesApp.Droid/SamplesApp.Droid.csproj
src/SamplesApp/SamplesApp.iOS/SamplesApp.iOS.csproj
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MapPresenter/MapControl.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MapPresenter/MapControl.xaml.cs

Other... Please describe:
Add a MapControl Sample in Ui Test.
The MapIcon (PushPin) Work only in UWP and IOS.
- [ x] Tested code with current [supported SDKs](../README.md#supported)

Add a MapControl in Uno UI Test Sample

---

README.md

Dead link replaced in README.md

---

doc/articles/feature-flags.md

Does not reader heading
Heading now renders

corrected markdown formatting issue

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListViewResizableText.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListViewResizableText.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_Infinite_Breadth.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_Infinite_Breadth.xaml.cs
src/Uno.UI/UI/Xaml/Controls/ItemsStackPanel/ItemsStackPanelLayout.wasm.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelAdapter.wasm.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.wasm.cs
src/Uno.UI/UI/Xaml/Controls/Primitives/SelectorItem.cs

GitHub Issue (If applicable): #234 
Bugfix
The ListView in WASM now performs a lightweight rebuild whenever Measure() is called. This replaces the previous approach of completely recycling items, which caused problems. (Eg, when pressing an element in the list, it would be reycled and rebound to a different item, causing the newly-bound item to be incorrectly sent to ItemClick.)
https://nventive.visualstudio.com/Umbrella/_workitems/edit/154815

[WASM] ListView - implement lightweight layout rebuild

---

src/Uno.UI.Tests/DependencyProperty/DependencyProperty_Owner.cs
src/Uno.UI/UI/Xaml/Controls/Grid/RowDefinition.cs

Fixes 'The Dependency Property [MinHeight] is owned by [Windows.UI.Xaml.Controls.ColumnDefinition] and cannot be used on [Windows.UI.Xaml.Controls.RowDefinition]' exception.
GitHub Issue (If applicable): #1032 
Bugfix

Fix RowDefinition property owners

---

src/Uno.UI/UI/Xaml/DispatcherConditionalDisposable.cs

Add documentation to DispatcherConditionalDisposable.

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Button/RadioButton_Combined_Style.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Button/RadioButton_Combined_Style.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Button/VisualStateProbeControl.cs
src/Uno.UI/UI/Xaml/Controls/VisualStatesImplementation.tt

Support the case where, pace the default Style, Checked/Unchecked and Pressed/etc states are mixed in the same VisualStateGroup. In this case UWP always reapplies Checked/Unchecked last after any other state is applied.
Bugfix 
https://github.com/nventive/calculator/issues/106

RadioButton - support non-standard style

---

README.md

Adjust readme title

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.Wasm/WasmScripts/Uno.UI.d.ts
src/Uno.UI.Wasm/WasmScripts/Uno.UI.js
src/Uno.UI.Wasm/ts/WindowManager.ts
src/Uno.UI.Wasm/tsBindings/WindowManagerGetClientViewSizeParams.ts
src/Uno.UI.Wasm/tsBindings/WindowManagerGetClientViewSizeReturn.ts
src/Uno.UI.Wasm/tsBindings/WindowManagerSetAttributeParams.ts
src/Uno.UI.Wasm/tsBindings/WindowManagerSetAttributesParams.ts
src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.wasm.cs
src/Uno.UI/UI/Xaml/WindowManagerInterop.wasm.cs

GitHub Issue (If applicable): fixes #871
- Bugfix
Touch events in the scrollbars bubble up to the parent, making popups being dismissed where they should not.
The ScrollContentPresenter now handles the pointer events in the html scroll bars, preventing the bubbling to the parents.

[Wasm] Fix support for ScrollBar touch events

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.Wasm/WasmScripts/Uno.UI.d.ts
src/Uno.UI.Wasm/WasmScripts/Uno.UI.js
src/Uno.UI.Wasm/ts/WindowManager.ts
src/Uno.UI/Helpers/Automation.cs
src/Uno.UI/Helpers/Automation.wasm.cs
src/Uno.UI/UI/Xaml/UIElement.wasm.cs
src/Uno.UI/Uno.UI.csproj

- Feature
Add `Uno.UI.Helpers.Automation` for UI Testing support

[Wasm]  Add Uno.UI.Helpers.Automation for UI Testing

---

src/Uno.UWPSyncGenerator/DocGenerator.cs

GitHub Issue (If applicable): #267
Tweak implemented views output in response to feedback.
- Tentative fix to remove spurious event add/remove methods (only happens on build server)
- Make supported on column clearer (see below)

Docs - tidy up implemented view in docs

---

build/Uno.UI.Build.csproj

Will log failing API changes to build output, to save having to download artifacts.
Note: Added breaking change for testing, will be removed
Build or CI related changes

Update Uno.PackageDiff for easier-to-access errors

---

README.md

Added ReactiveUI official support

Update readme to include official ReactiveUI support

---

.github/pull_request_template.md

Some 💄 to correct some very minor things that were irking me.

docs: updated pull-request template

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/StyleTests/Style_Inline.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/StyleTests/Style_Inline.xaml.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs

GitHub Issue (If applicable): fixes #1085 
Add support for the following:
```xaml
<TextBlock Text="This text should be pink">
<TextBlock.Style>
<Style TargetType="TextBlock">
<Setter Property="Foreground"
Value="Pink" />
<Setter Property="Margin"
Value="20" />
</Style>
</TextBlock.Style>
</TextBlock>
```
- Feature

Support setting inline Style

---

src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Styles/Controls/ListViewItem.xaml
src/SamplesApp/UITests.Shared/Toolkit/Elevation.xaml
src/SamplesApp/UITests.Shared/Toolkit/Elevation.xaml.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems

Added small sample for elevation and changed the color for mouse over and press state of the navigation's list items (Pure blue was a bit too intense).

Add Elevation sample

---

build/Uno.UI.nuspec
src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.csproj
src/Uno.UI.Toolkit/Uno.UI.Toolkit.csproj
src/Uno.UI/Controls/BindableImageSource.Android.cs
src/Uno.UI/Extensions/NSDateExtensions.iOS.cs
src/Uno.UI/UI/Xaml/Controls/Border/Border.Android.cs
src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.Android.cs
src/Uno.UWP/Uno.csproj

- Build
Build compatibility changes for VS16.2 Preview 3

Adjust dependencies for VS16.2 pre compatibility

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.UITests/UnoSamples_Tests.Keyboard.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_TextChanged.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_TextChanged.xaml.cs
src/Uno.UI.Tests/BinderTests/Given_Binder.TwoWay.cs
src/Uno.UI.Tests/BinderTests/Given_Binder.cs
src/Uno.UI.Tests/DependencyProperty/Given_DependencyProperty.Inversion.cs
src/Uno.UI.Tests/Windows_UI_XAML_Controls/ListViewBaseTests/Given_ListViewBase.cs
src/Uno.UI.Tests/Windows_UI_XAML_Controls/TextBoxTests/Given_TextBox.cs
src/Uno.UI/DataBinding/BindingExpression.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs
src/Uno.UI/UI/Xaml/DependencyObjectStore.cs

GitHub Issue (If applicable): fixes #1087 
Move guards on 2-way binding infinite loop to BindingExpression, this allows DPs to be modified from property-changed callbacks and [X]Changed event handlers.
Feature

 Enable DependencyProperties to be set reentrantly

---

doc/articles/getting-started/requirements.md
doc/articles/toc.yml

Documented the question raised by @ngame1 over at https://github.com/nventive/Uno/issues/1076#issuecomment-503564670
> "could you please let me know the minimum Android version supported by Uno?"

documented the Uno Platform requirements

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/WebView/WebViewControl_JavaScript_Alert_Confirm_Prompt.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/WebView/WebViewControl_JavaScript_Alert_Confirm_Prompt.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/WebView/WebViewObserverBehavior.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/WebView/WebViewSampleBehavior.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/WebView/WebViewStaticViewModel.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/WebView/WebViewViewModel.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/WebView/WebView_Alert.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/WebView/WebView_Alert.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/WebView/WebView_ChromeClient.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/WebView/WebView_ChromeClient.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/WebView/WebView_Events.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/WebView/WebView_Events.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/WebView/WebView_JavascriptInvoke.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/WebView/WebView_JavascriptInvoke.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/WebView/WebView_Mailto.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/WebView/WebView_Mailto.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/WebView/WebView_NavigateToString.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/WebView/WebView_NavigateToString.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/WebView/WebView_NavigateToUri.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/WebView/WebView_NavigateToUri.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/WebView/WebView_Static.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/WebView/WebView_Static.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/WebView/WebView_WithHeaders.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/WebView/WebView_WithHeaders.xaml.cs
src/Uno.UI/UI/Xaml/Controls/WebView/UnoWKWebView.iOS.cs

Bugfix 
Crash when OnRunJavaScriptAlertPanel is called 
No Crash

Adjusted OnRunJavaScriptAlertPanel according to the WKUIDelegate recipe

---

doc/ReleaseNotes/_ReleaseNotes.md

#1117 was cherry-pick'd into beta; the release notes have been updated to reflect this.
cherry-pick'd #1117 into [beta](https://github.com/unoplatform/uno/tree/release/beta/Batman) via 9ce34a99

updated release notes

---

.github/invite-contributors.yml

- Community automation changes
- Maintainers cannot assign issues to people who are not part of an organisation.
- No rewards (being able to wear the uno badge on their GitHub profile) for contribution.
- All of above is resolved via automation.
- When a pull-request is merged the robot will invite the author to join the GitHub organisation into the team defined in the configuration file.
- They are added to the community group which has no permissions.
- Maintainers can assign issues to the community.
https://help.github.com/en/articles/repository-permission-levels-for-an-organization
nb. The organization is configured to disable access to all private repositories (admins need to manually whitelist teams on a per repo basis)
Please check if …

automation: automatically invite contributors to the github organization

---

doc/articles/toc.yml

docs: removed incorrect prefix hyphen from toc

---

src/Uno.UWP/Media/Playback/MediaPlayer.iOS.cs

This PR is the same as https://github.com/unoplatform/uno/pull/1190, it only adds missed callbacks

Complete the tentative to avoid crash in AudioToolBox

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/DragCoordinates_Tests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Input/Pointers/DragCoordinates_Automated.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Input/Pointers/DragCoordinates_Automated.xaml.cs

GitHub Issue (If applicable): #1257 
- UI Tests
See #1257 for more details

[Android] Add UI Tests for pointer events failure

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_Inside_ListView.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_TextBox.xaml
src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBaseSource.iOS.cs

Use double.PositiveInfinity rather than .MaxValue for available dimensions. This is in general more correct and fixes bug where multiline TextBox incorrectly requests infinite height, causing the app to crash or hang when list is laid out.
- Bugfix
fixes https://github.com/unoplatform/private/issues/20

[iOS] ListView - improve template measurement

---

src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Models/TimePickerViewModel.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TimePicker/Sample1.xaml
src/Uno.UI.Tests/BinderTests/Given_Binder.cs
src/Uno.UI/DataBinding/BindingExpression.cs

TimePicker defaults to now time fix into Beta

---

doc/articles/concepts/overview/philosophy-of-uno.md
doc/articles/toc.yml

Lifting out existing content into a separate document so that it is more discoverable.

docs: create concepts/philosophy-of-uno

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/Flyout/FlyoutPopupPanel.cs

cherry-pick of https://github.com/unoplatform/uno/pull/987 into beta
internal work-item:
https://nventive.visualstudio.com/Umbrella/_workitems/edit/153874

fixed button flyout placement for android (#987)

---

src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ParallaxListView/ParallaxListView.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TimePicker/Sample2_Styles.xaml

- Other: Code cleanup
Unnecessary content in UITests.Shared
Removed unnecessary content in UITests.Shared

Removed unnecessary content in UITests.Shared

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/DatePickerTests/UnoSamples_Tests.DatePicker.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TimePickerTests/UnoSamples_Tests.TimePicker.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/DatePicker/DatePickerSample.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/DatePicker/DatePickerSample.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/DatePicker/DatePicker_SampleContent.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/DatePicker/DatePicker_SampleContent.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/DatePicker/Models/DatePickerViewModel.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TimePicker/Model/TimePickerViewModel.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TimePicker/Sample1.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TimePicker/Sample1.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TimePicker/Sample2.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TimePicker/Sample2.xaml.cs
src/Uno.UI.sln

Added Unittests for timePicker/datePicker datacontext and content

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ButtonTests/UnoSamples_Test_Button_Click.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ButtonTests/UnoSamples_Tests.Button_IsEnabled_Automated.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Button/Button_Events.xaml

This is UI tests missing for the previous PR #1316

UI Test for button events

---

gitversion.yml

so the version will be automatically incremented at each commit as expected by commit e965e265
This PR is the same as  #1314

Update the GitVersion to use the Mainline mode

---

doc/articles/contributing/guidelines/breaking-changes.md
doc/articles/toc.yml
doc/articles/uno-development/debugging-uno-ui.md

GitHub Issue (If applicable): # https://github.com/unoplatform/uno/pull/1300
roughly documented
thoroughly documented
Documented my learnings whilst working on  https://github.com/unoplatform/uno/pull/1300

docs: guidelines for breaking changes

---

src/Uno.UI.BindingHelper.Android/Uno/UI/UnoViewGroup.java
src/Uno.UI/LayoutProvider.Android.cs
src/Uno.UI/UI/Xaml/ApplicationActivity.Android.cs

- Bugfix
Translucent and nav and status bar that overlaps page
Scrolling issues due to requestLayout() in an infinite loop
Keyboard Flys out on nav bar change
Proper status and nav bar behaviour
No scrolling issues
No Keyboard flyout
https://nventive.visualstudio.com/Umbrella/_workitems/edit/158376
https://nventive.visualstudio.com/Umbrella/_workitems/edit/158363
https://nventive.visualstudio.com/Umbrella/_workitems/edit/158377
https://nventive.visualstudio.com/Umbrella/_workitems/edit/158567

Fix to Issues caused by TopNotch on Android

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.UITests/UnoSamples_Tests.Keyboard.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_Disabled.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_Disabled.xaml.cs
src/Uno.UI.Wasm/WasmScripts/Uno.UI.js
src/Uno.UI.Wasm/ts/WindowManager.ts
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.wasm.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.wasm.cs

GitHub Issue (If applicable): #1167
- Bugfix
Disabled TextBox could be tabbed to.
Disabled TextBox is really, truly disabled

[WASM] Apply TextBox.IsEnabled correctly

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/GridView/GridView.cs
src/Uno.UI/UI/Xaml/Controls/ListView/ListView.cs

- Bugfix
Scrolling lag
No scroll lag 
https://nventive.visualstudio.com/Umbrella/_workitems/edit/159050

Fix to groupedlistviewheaders performance issue

---

build/Uno.UI.Lottie.nuspec
build/Uno.UI.WpfHost.nuspec
build/Uno.UI.nuspec
src/AddIns/Uno.UI.Lottie/Uno.UI.Lottie.csproj
src/Directory.Build.targets
src/SamplesApp/SamplesApp.Droid/SamplesApp.Droid.csproj
src/SamplesApp/SamplesApp.UWP/SamplesApp.UWP.csproj
src/SamplesApp/SamplesApp.Wasm/SamplesApp.Wasm.csproj
src/SamplesApp/SamplesApp.macOS/SamplesApp.macOS.csproj
src/SolutionTemplate/UnoLibraryTemplate/CrossTargetedLibrary.csproj
src/SolutionTemplate/UnoSolutionTemplate/Droid/UnoQuickStart.Droid.csproj
src/SolutionTemplate/UnoSolutionTemplate/UWP/UnoQuickStart.Uwp.csproj
src/SolutionTemplate/UnoSolutionTemplate/Wasm/UnoQuickStart.Wasm.csproj
src/SolutionTemplate/UnoSolutionTemplate/iOS/UnoQuickStart.iOS.csproj
src/Uno.UWPSyncGenerator/Uno.UWPSyncGenerator.csproj

updated dependencies to latest dev
https://nventive.visualstudio.com/Umbrella/_workitems/edit/156093

updated to latest dev

---

build/PackageDiffIgnore.xml
doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/Transform/Transformed_Ancestor_And_UI_Blocked.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/Transform/Transformed_Ancestor_And_UI_Blocked.xaml.cs
src/Uno.UI.BindingHelper.Android/Uno/UI/UnoViewGroup.java
src/Uno.UI/Media/NativeRenderTransformAdapter.Android.cs
src/Uno.UI/UI/Xaml/Controls/ProgressRing/ProgressRing.Android.cs
src/Uno.UI/UI/Xaml/Media/Animation/Animators/AnimatorFactory.Android.cs

GitHub Issue (If applicable): fixes #1333
- Bugfix
Animations translated outside their bounds by an ancestor transform update in a software-bound manner, prone to glitches.
The animations update normally.

[Android] Improved fix for animation cut off within transformed view hierarchy

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UWP/ApplicationModel/Core/CoreApplication.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Core/CoreApplication.cs

- Feature
Add basic support for `CoreApplication.MainView` and `CoreApplication.Views`.

Add basic support for MainView and Views in CoreApplication

---

doc/articles/faq.md

docs: corrected hyperlink

---

src/Uno.UI/FeatureConfiguration.cs

Disable Feature flag for implicit binding Content of a ContentPresenter for internal purpose.
https://dev.azure.com/nventive/Umbrella/_workitems/edit/160419
https://dev.azure.com/nventive/Umbrella/_workitems/edit/160421
https://dev.azure.com/nventive/Umbrella/_workitems/edit/160422
https://dev.azure.com/nventive/Umbrella/_workitems/edit/160354
https://dev.azure.com/nventive/Umbrella/_workitems/edit/160316

Disable Feature flag for implicit binding Content of a ContentPresenter

---

build/Uno.UI.nuspec
src/Directory.Build.targets

GitHub Issue (If applicable): https://github.com/unoplatform/private/issues/10
Update Uno.SourceGeneration tasks to support the AdditionalProperty feature.

Update Uno.SourceGeneration to latest to support AdditionalProperties

---

src/SourceGenerators/Uno.UI.SourceGenerators/DependencyObject/DependencyObjectGenerator.cs

GitHub Issue (If applicable): #1462 
- Bugfix
Compile error when building project that contains "Uno" as part of it's namespace.
Build succeeds.

Use `global::` to prefix Uno namespace.

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_ChangeView.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_ChangeView.xaml.cs
src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.iOS.cs

Changeview does not work when used in a list view on iOS.
ChangeView works when used in a list view on iOS.
https://nventive.visualstudio.com/Umbrella/_workitems/edit/159659

Fixed iOS issue with ChangeView and created a sample for it

---

doc/templates/uno/layout/_master.tmpl
doc/templates/uno/partials/google-tag-manager.tmpl.partial

Right now we don't have any visibility to analytics in our documentation which makes content planning hard. This PR adds in the same code that is used on the main website.
I did this edit using the GitHub editor and have not validated locally.

docs: add google tag manager

---

doc/articles/feature-flags.md

Inxternal Issue (If applicable):

Fix incorrect property name in FeatureConfiguration doc

---

.azure-devops-wasm-uitests.yml

Update invalid screenshot compare tool invalid condition.

Restore screenshot compare step

---

doc/articles/debugging-wasm.md

docs: clarity improvements for debugging wasm

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ContentDialog/UnoSamples_Tests.ContentDialog.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ContentDialogTests/ContentDialog_Closing.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ContentDialogTests/ContentDialog_Closing.xaml.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/Uno.UI/UI/Xaml/Controls/ContentDialog/ContentDialog.cs
src/Uno.UI/UI/Xaml/Controls/ContentDialog/ContentDialogClosingDeferral.cs
src/Uno.UI/UI/Xaml/Controls/ContentDialog/ContentDialogClosingEventArgs.cs
src/Uno.UI/UI/Xaml/Controls/ContentDialog/DeferralManager.cs
src/Uno.UI/UI/Xaml/Controls/ContentDialog/IDeferral.cs
src/Uno.UI/UI/Xaml/FrameworkElementHelper.cs
src/Uno.UI/UI/Xaml/IFrameworkElementImplementation.Android.tt
src/Uno.UI/UI/Xaml/IFrameworkElementImplementation.iOS.tt

GitHub Issue (If applicable): fixes #1495
- Feature
`ContentDialog.Closing` and `ContentDialog.Closed` events are not raised
They're raised, and corresponding event args are correctly supported.

Implement ContentDialog.Closing and ContentDialog.Closed

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ContentDialog/UnoSamples_Tests.ContentDialog.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ContentDialogTests/ContentDialog_Closing.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ContentDialogTests/ContentDialog_Closing.xaml.cs
src/Uno.UI/UI/Xaml/Controls/ContentDialog/ContentDialog.cs
src/Uno.UI/UI/Xaml/Controls/ContentDialog/ContentDialogClosingEventArgs.cs

Previously it was only sent with Closed event.
GitHub Issue (If applicable): fixes #1545 

ContentDialog - add Result to Closing event args

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TextBlockTests/TextBlockTests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/TextBlock_Visibility_Arrange.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/TextBlock_Visibility_Arrange.xaml.cs
src/Uno.UI.Tests/Windows_UI_XAML_Controls/ItemsControlTests/Given_ItemsControl.cs
src/Uno.UI/UI/Xaml/Controls/ItemsControl/ItemsControl.cs
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.Android.cs

- fix NRE from TextBlock on Android
- fix ItemsControl.OnItemsChanged sending null parameter
https://github.com/unoplatform/private/issues/70

Misc fixes

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.Tests/Windows_UI_XAML_Controls/GridTests/Given_Grid_Def_ActualSize.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/ColumnDefinition.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/RowDefinition.cs
src/Uno.UI/UI/Xaml/Controls/Grid/ColumnDefinition.cs
src/Uno.UI/UI/Xaml/Controls/Grid/Grid.Layout.FastPaths.cs
src/Uno.UI/UI/Xaml/Controls/Grid/Grid.Layout.cs
src/Uno.UI/UI/Xaml/Controls/Grid/RowDefinition.cs

Preliminary implementation for ColumnDefinition.ActualWidth and RowDefinition.ActualHeight. Only validated for a limited range of scenarios, and only after the arrange pass has run.
- Feature
https://github.com/unoplatform/private/issues/70

Implement Actual[Size] properties for Grid definitions

---

README.md
gitversion.yml

- Feature
Update the current version to 2.0.

Update to Version 2.0

---

.all-contributorsrc

Resolves https://github.com/unoplatform/uno/pull/1563#issuecomment-533645546

fix: resolved build by removing dangling comma

---

README.md

I'm sitting at the UnoConf workshop, and I hear some colleagues pronouncing it 'Euno'.
Maybe it'd be a good idea to include this information in the docs to make that obvious.

Pronunciation of the name Uno

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/Extensions/UIViewExtensions.iOSmacOS.cs
src/Uno.UI/Extensions/ViewExtensions.Android.cs

- Feature
show VisualTree of an app with more info.
show VisualTree of an app with Visibility for each items.
~~- [ ] Tested code with current [supported SDKs](../README.md#supported)~~
~~- [ ] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)~~
~~- [ ] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)~~
~~- [ ] [Wasm UI Tests](doc/articles/working-with-the-samples-apps.md#running-the-webassembly-ui-tests-snapshots) are not showing unexpected any differences. Validate PR …

added items visibility

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ContentDialog/UnoSamples_Tests.ContentDialog.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ContentDialogTests/ComboBoxContentDialog.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ContentDialogTests/ComboBoxContentDialog.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ContentDialogTests/ContentDialog_ComboBox.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ContentDialogTests/ContentDialog_ComboBox.xaml.cs
src/Uno.UI.Tests/Windows_UI_XAML_Controls/ContentDialogTests/Given_ContentDialog.cs
src/Uno.UI/UI/Xaml/Controls/Popup/PopupBase.cs
src/Uno.UI/UI/Xaml/Controls/Popup/PopupRoot.wasm.cs

- ContentDialog with explicit DataContext isn't overwritten
- [WASM] Support multiple popups (eg ComboBox inside of ContentDialog)
GitHub Issue (If applicable): fixes #1557 
- Bugfix

ContentDialog fixes for WASM

---

build/Uno.UI.nuspec

NuGet uses the same tagline as is used on GitHub.

housekeeping: use same tagline as github

---

.azure-devops-wasm-uitests.yml
src/SolutionTemplate/UnoLibraryTemplate/CrossTargetedLibrary.csproj
src/global.json

Support for VS 16.3 for the Uno.UI solution

Support for VS 16.3 for the Uno.UI solution

---

doc/articles/faq.md

links syntax is messed up
links look beauuuuutiful

fixed links syntax

---

doc/articles/intro.md

Added additional support information.

Added additional support information.

---

doc/articles/controls/CommandBar.md

Signed-off-by: Ranadeep Polavarapu <ranadeep@icloud.com>
resolves #1515
GitHub Issue (If applicable): #1515 
Doesn't have docs on how to use the two implementations of the `CommandBar`.
Added how to change the `CommandBar` modes to the docs.

docs: add changing `CommandBar` modes

---

README.md

Fix contributors badge link

---

doc/ReleaseNotes/_ReleaseNotes.md

- Grammar in documentation
There is a small grammatical inconsistency in the documentation.
The inconsistency has been corrected.
Please check if your PR fulfils the following requirements:

Fixed Grammatical Inconsistency ReleaseNotes.md

---

doc/articles/getting-started-tutorial-1.md
doc/articles/intro.md

Added some commas to improve phrasing
GitHub Issue (If applicable): Not applicable, just a suggestion
Docs Changes
No behavior associated, just markdown changes.
Better phrasing :smile: 
Doesn't change code!
No additional information
Not applicable

Minor phrasing fix suggestion

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.UITests/QueryExtensions.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml/UIElementTests/UIElementTests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/UIElementTests/TransformToVisual_Transform.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/UIElementTests/TransformToVisual_Transform.xaml.cs
src/Uno.UI.BindingHelper.Android/Uno/UI/UnoViewGroup.java

Override View.getLocationInWindow() to ensure it takes StaticTransformation (which Uno is using for RenderTransforms) into account.
This fixes:
- placement of MenuFlyout anchored to view in transformed hierarchy
- return of TransformToVisual for view in transformed hierarchy
- Bugfix
https://github.com/unoplatform/private/issues/37

[Android] Take RenderTransform into account when calculating screen position

---

.github/pull_request_template.md

Broken links in pull_request_template.md
Fixed links in pull_request_template.md

Fix broken links in pull_request_template

---

doc/articles/controls/ListViewBase.md
doc/articles/controls/MediaPlayerElement.md

GitHub Issue (If applicable): None

Fixes typos in docs (articles section)

---

doc/articles/uno-toolchain-telemetry.md

GitHub Issue (If applicable): #1702
fix repository user name in uno-toolchain-telemetry.md

fix: repository user name

---

doc/articles/getting-started-tutorial-1.md

GitHub Issue (If applicable): #1698
In the getting started tutorial (https://platform.uno/docs/articles/getting-started-tutorial-1.html), the link to the xamarin installation instructions returns 404 (https://docs.microsoft.com/en-us/xamarin/get-started/installation/index.md)
The new link (https://docs.microsoft.com/en-us/xamarin/get-started/installation/) is a landing page where you can see the instructions for the main three xamarin installation flavors (Mac, 2017  and 2019 on Windows). Note: That new link automatically "pivots" (changes to the tab) to the right OS installation.
- [ x ] Contains **NO** breaking changes

docs: fix xamarin installation broken url

---

CONTRIBUTING.md
doc/articles/controls/ToggleSwitch.md
doc/articles/features/PasswordVault.md
doc/articles/features/routed-events.md
doc/articles/uno-development/working-with-the-samples-apps.md
doc/blog/201906-porting-windows-calculator.md

GitHub Issue (If applicable): None

Improve docs

---

doc/articles/controls/CommandBar.md

Documentation was outdated since #966

Update localization of BackButtonTitle FAQ

---

doc/articles/uno-development/debugging-uno-ui.md

Added troubleshooting steps to view generated code from a CI build

Added troubleshooting steps to view generated code

---

doc/articles/uno-hot-reload.md

Small sentence correction

---

.github/pull_request_template.md

GitHub Issue (If applicable): None
Fix typo in pull request template

Fix typo in pull_request_template

---

README.md

Stars Badge Added on README.md

---

doc/articles/faq.md

GitHub Issue (If applicable): NA

faq.md: Update LICENSE link

---

README.md

README.md file missing build status badges
Added build process summaries in README.md

Add build process summaries in README.md

---

doc/articles/using-uno-ui.md

Add links to visual studio

---

doc/index.md

Add missing question mark

---

doc/articles/faq.md

changed few links of old repo "nventive/uno" to "unoplatform/uno" and changed outdated answer of NavigationView question.

fix: updated answer in faq.md

---

build/_HOW-TO-BUILD-AND-DEBUG-APPS.md

Fixed grammatical errors in _HOW-TO-BUILD-AND-DEBUG-APPS.md

---

doc/articles/using-uno-ui.md

Corrected line breaks and updated for consistency
https://github.com/unoplatform/uno/issues/1719

Maintained consistency in uno-ui.md fixed line breaks

---

doc/articles/contributing/guidelines/issue-triage.md

Correct spelling

---

doc/articles/api-differences.md
doc/articles/concepts/overview/philosophy-of-uno.md
doc/articles/using-uno-ui.md

There were some typing errors like 'an' instead of 'and' , 'clas' instead of 'class' , etc.
Fixed the above mentioned typos.

Rectified some typos.

---

doc/articles/faq.md

No behavior associated, just markdown changes.
Better grammar and phrasing, removed duplicated words followed by each other.

Minor grammar and phrasic fixes

---

.github/config.yml

- Community automation
- Maintainers/contributors may not realise if someone is contributing for the first time (PRs)
- Maintainers/contributors may not realise if someone is brand new to the project (issues) and is having problems or has an idea.
- Warm feelings and awareness
- Automated as per the configuration attached to this PR.
I'm raising this PR early for discussion to see what folks think. I haven't customised the language/configuration yet. What do you think should go in the yaml? Add your comments as discussions on the yaml please :)
See https://github.com/behaviorbot/welcome for configuration options.

automation: welcome and thank new folks automatically

---

CODE_OF_CONDUCT.md

Fixed typo in CODE_OF_CONDUCT.md

---

README.md

Added  missing period( . ) in many places.
Added missing colon ( : ) in some places.
Observed some missing punctuation in README.md file 
Fixed all missing punctuation in README.md file 

updated missing punctuation in the README file.

---

doc/articles/api-differences.md
doc/articles/debugging-wasm.md
doc/articles/features/routed-events.md

Fixed some typos

---

doc/blog/201808-UnoUnderTheHoodIntro.md

Hyperlinks and bullet points are a mix of quoted and unquoted text, this aims to make them uniform across the document
Move bullet points and hyperlinks into quoted text 

Update Under the Hood Intro

---

CONTRIBUTING.md

https://github.com/unoplatform/uno/issues/1677
https://github.com/unoplatform/uno/issues/1677
Linked url is incorrect
When user click on bug template in contributing.md it redirects to 404 page

Bug Fix :1677

---

doc/articles/howto-migrate-existing-code.md

A few instances of incorrect spelling and grammar in docs for migration of existing code
Corrections made to docs
Please check if your PR fulfills the following requirements (some are not relevant; documentation change only):

Fix spelling/grammar in docs for existing code migration

---

doc/blog/201901-WebAssembly-Projects-and-debugging.md

Fix typo in 201901-WebAssembly-Projects-and-debugging.md

---

doc/articles/api-differences.md
doc/articles/controls/Pivot.md
doc/articles/features/SpeechRecognition.md
doc/articles/features/working-with-assets.md
doc/articles/uno-development/debugging-inspect-visual-tree.md

Improve documentation quality and fixes typos

---

doc/articles/Uno.UI.Toolkit.md

- Documentation content changes (minor typo) 
N/A - documentation change only 
N/A - documentation change only 

Fixed minor documentation typo

---

doc/articles/debugging-wasm.md

- Minor documentation proofreading
<hr/>

Minor improvements to docs

---

doc/articles/Uno-UI-Performance.md

Fix typo on Uno-UI-Performance.md

---

doc/articles/faq.md

Fix some typos on faq.md

---

doc/articles/uno-development/working-with-the-samples-apps.md

docs: link to UnitTestControl and UnitTestsPage

---

doc/articles/api-differences.md

Broken link in docs.
Correct link in docs.

fixed broken link to ListViewBase

---

doc/articles/contributing/guidelines/creating-a-new-release.md
doc/articles/toc.yml

Undocumented.
Documented and additional insights shared.
Opening early for feedback. Here's what I've learned so far through various conversations with folks. Let me know if I got anything wrong.

docs: guidelines for releasing uno

---

.github/ISSUE_TEMPLATE/documentation-issue.md
.github/ISSUE_TEMPLATE/feedback.md
.github/ISSUE_TEMPLATE/samples-issue.md

docs: fixed types in github issue templates

---

README.md

Inconsistent style.
Consistent style.

housekeeping: improved styling of the README.md

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml
src/Uno.UI/UI/Xaml/Style/Generic/SystemResources.xaml

- Feature
The `CheckBox` style is aligned with Windows SDK 10.0.17763, so that resources from this version are available.

feature: update CheckBox style to 10.0.17763

---

doc/articles/platform-specific-xaml.md

https://github.com/unoplatform/uno/blob/master/doc/articles/platform-specific-xaml.md
This PR removes very minor capitalization error.
'place' is showing instead of 'Place' in platform-specific-xaml.md
Now 'Place' is showing instead of 'place'.

docs: minor capitalization error

---

README.md

To motivate contributor, for more.

docs: add thank-you to README

---

src/SourceGenerators/README.md
src/Uno.UI.Wasm/WasmCSS/Uno.UI.css
src/Uno.UI.Wasm/WasmScripts/Uno.UI.js

I updated the documentation by fixing spelling/grammar/capitalisation errors which I noticed while reading the documentation.
Hope this helps!

Updated Uno+WASM documentation for Uno.Ui

---

src/SolutionTemplate/UnoSolutionTemplate/Shared/MainPage.xaml

GitHub Issue (If applicable): #1895 
There is a space between Hello world and exclamation point. 
There is no space between Hello world and exclamation point. 

docs: removed space from Hello world!

---

doc/articles/platform-specific-xaml.md

Very Minor capitalization and grammer fixes required #1904

---

doc/articles/features/VisibleBoundsPadding.md
doc/articles/features/shapes-and-brushes.md
doc/articles/features/windows-applicationmodel-calls.md
doc/articles/features/windows-system.md
doc/articles/features/working-with-themes.md

Updated some pages with grammar/capitalization fixes that I noticed while reading the docs.
Thanks!

docs: misc fixes

---

src/Uno.UI/FeatureConfiguration.cs

docs: spelling mistake

---

doc/articles/controls/map-control-support.md

The documentation in [map-control-support.md](https://github.com/unoplatform/blob/master/doc/articles/controls/map-control-support.md) has several grammatical issues such as the use of participles when normal verbs would function and be more clear. Also, a few issues with specifying names of projects such as NuGet exist.
All awkward portions of the documentation have been fixed.
Although this pull request has no associated issue or feature improvement, it does fall under the specifications on the [Hacktoberfest announcement](https://platform.uno/uno-is-joining-hacktoberfest-2019/). This is because it makes vague and …

Fix grammatical errors in map-control-support.md

---

doc/articles/features/routed-events.md

The spelling was wrong at line 40.

routed-events.md

---

doc/blog/201708-Importing-SL-Toolkit-part-1.md

Signed-off-by: doomswatter <44559839+doomswatter@users.noreply.github.com>
Replaced seven incorrect words, added four missing words, and added one missing comma.

docs: grammar corrections

---

README.md

Signed-off-by: Binit Ghimire <thebinitghimire@gmail.com>
GitHub Issue: None
Currently, there are few grammatical and linguistic issues in the _README.md_ file
I have made changes to fix the existing grammatical and linguistic issues in the file.

docs: resolve grammatical and linguistic issues

---

src/SourceGenerators/Uno.UI.SourceGenerators/BindableTypeProviders/BindableTypeProvidersGenerationTask.cs

GitHub Issue (If applicable): # 1688
unoplatform#1688
Improve error message when a Bindable attribute is missing
The message is not clear enough to provide the user a better understanding of what has to be done or what´s happening.
The error message was updated with more details concerning the error.
- [x ] Tested code with current [supported SDKs](https://github.com/unoplatform/uno/blob/master/README.md#uno-features)
- [x ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [x ] [Unit Tests and/or UI …

Update error message in the BindableTypeProvidersGenerationTask.cs file

---

src/SourceGenerators/Uno.UI.SourceGenerators/BindableTypeProviders/BindableTypeProvidersGenerationTask.cs

- Bugfix
Update debug only issue for typo in generated code.

Fix invalid debug generated code

---

doc/blog/201906-porting-windows-calculator.md

fixed some typos
```
./doc/blog/201906-porting-windows-calculator.md:114: Funtion -> "Function"
```

Fix some typos on Blog article

---

.azure-devops-ios-tests.yml
.azure-devops-windows.yml
build/ios-uitest-run.sh
src/SamplesApp/SamplesApp.UITests/RuntimeTests.cs
src/SamplesApp/SamplesApp.UITests/UnoSamples_Tests.Keyboard.cs
src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.cs
src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.xaml
src/Uno.UI.RuntimeTests/IntegrationTests/dxaml/controls/grid/GridIntegrationTests.cs
src/Uno.UWP/Extensions/CoreDispatcherExtensions.cs
src/Uno.UWP/System/Launcher.cs

- Enabled additional validation for https://github.com/unoplatform/uno/pull/1829
- Enable iOS Tests failing the build on test failure

Enable iOS Runtime Tests validation

---

build/PackageDiffIgnore.xml
doc/ReleaseNotes/_ReleaseNotes.md
doc/articles/features/windows-system-profile.md
doc/articles/toc.yml
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_System/Profile/AnalyticsInfoTests.xaml
src/SamplesApp/UITests.Shared/Windows_System/Profile/AnalyticsInfoTests.xaml.cs
src/Uno.UI.RuntimeTests/Tests/Windows_System/Profile/Given_AnalyticsInfo.cs
src/Uno.UI.Wasm/WasmScripts/Uno.UI.d.ts
src/Uno.UI.Wasm/WasmScripts/Uno.UI.js
src/Uno.UI.Wasm/ts/Windows/System/Profile/AnalyticsVersionInfo.ts
src/Uno.UWP/Generated/3.0.0.0/Windows.System.Profile/AnalyticsInfo.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.System.Profile/AnalyticsVersionInfo.cs
src/Uno.UWP/System/Profile/AnalyticsInfo.Android.cs
src/Uno.UWP/System/Profile/AnalyticsInfo.cs
src/Uno.UWP/System/Profile/AnalyticsInfo.iOS.cs
src/Uno.UWP/System/Profile/AnalyticsInfo.wasm.cs
src/Uno.UWP/System/Profile/AnalyticsVersionInfo.Android.cs
src/Uno.UWP/System/Profile/AnalyticsVersionInfo.iOS.cs
src/Uno.UWP/System/Profile/AnalyticsVersionInfo.wasm.cs
src/Uno.UWP/System/Profile/Internal/DeviceForm.cs
src/Uno.UWP/System/Profile/Internal/UnoDeviceForm.cs

GitHub Issue (If applicable): #1468 
- Feature
`AnalyticsInfo` properties are not implemented
`AnalyticsInfo` properties are implemented on Android, iOS, WASM

Implemented AnalyticsInfo properties

---

README.md
doc/articles/faq.md

docs: minor fix

---

src/Uno.UI/UI/Xaml/Controls/Grid/Grid.Layout.cs

Warning was erroneously being shown in the trivial case of only one star row.
The equivalent fix was already made for the star columns calculation.
Internal Issue (If applicable): https://nventive.visualstudio.com/Umbrella/_workitems/edit/158995

Eliminate Grid 'Star measurements failed to stabilize' log spam

---

src/SamplesApp/SamplesApp.Wasm/Program.cs
src/Uno.UI/FeatureConfiguration.cs
src/Uno.UI/UI/Xaml/Controls/Layouter/Layouter.cs
src/Uno.UI/UI/Xaml/FrameworkElement.cs
src/Uno.UI/UI/Xaml/UIElement.Android.cs
src/Uno.UI/UI/Xaml/UIElement.wasm.cs

A bug was remaining in previous PR #1726 where clipping on Android were not applied properly.

Fixed clipping regression on Android

---

doc/articles/get-started-next-steps.md
doc/articles/get-started.md
doc/articles/getting-started-tutorial-1.md
doc/articles/getting-started/requirements.md
doc/articles/toc.yml

- Create dedicated section, split material across three pages, remove duplicated content
- Move min platform versions to About Uno

Rearrange Getting Started material

---

doc/articles/getting-started-tutorial-1.md

GitHub Issue (If applicable): #2013

Fix remaining Refractored typo in tutorial

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ProgressRing.cs
src/Uno.UI/Extensions/ViewExtensions.Android.cs
src/Uno.UI/UI/Xaml/Controls/Layouter/Layouter.cs
src/Uno.UI/UI/Xaml/FrameworkElementExtensions.cs

This is required to correctly handle collapsed IFrameworkElement children that don't have their own Layouter (eg ProgressRing on Android).
GitHub Issue (If applicable): fixes #2073 
- Bugfix

Restore check for Visibility in Layouter.MeasureChild

---

src/Uno.UI.Tests/Windows_UI_XAML_Controls/FlyoutTests/Given_Flyout.cs
src/Uno.UI.Tests/Windows_UI_Xaml/FrameworkElementTests/Given_FrameworkElement.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml/FrameworkElement.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml/UIElement.cs
src/Uno.UI/Mock/Popup.net.cs
src/Uno.UI/UI/LayoutHelper.cs
src/Uno.UI/UI/Xaml/Controls/Flyout/FlyoutBase.net.cs
src/Uno.UI/UI/Xaml/Controls/Flyout/PickerFlyoutPopupPanel.iOS.cs
src/Uno.UI/UI/Xaml/Controls/Popup/PlacementPopupPanel.cs
src/Uno.UI/UI/Xaml/FrameworkElement.Interface.net.cs
src/Uno.UI/UI/Xaml/IFrameworkElement.cs
src/Uno.UI/UI/Xaml/IFrameworkElementImplementation.Android.tt
src/Uno.UI/UI/Xaml/IFrameworkElementImplementation.iOS.tt
src/Uno.UI/UI/Xaml/IFrameworkElementImplementation.macOS.tt
src/Uno.UI/UI/Xaml/UIElement.net.cs
src/Uno.UWP/UI/ViewManagement/ApplicationView.net.cs

GitHub Issue (If applicable): fixes #2009
- FlyoutPresenter takes up all available size up to MaxSize when placement mode is Full
- fix exception when MaxHeight/MaxWidth=NaN
- Bugfix

Flyout - set correct size in Full placement mode

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ComboBoxTests/UnoSamples_Tests.ComboBoxTests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ComboBox/ComboBox_VisibleBounds.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ComboBox/ComboBox_VisibleBounds.xaml.cs
src/Uno.UI/UI/Xaml/Controls/ComboBox/ComboBox.cs
src/Uno.UI/UI/Xaml/Controls/Popup/PopupBase.cs
src/Uno.UI/UI/Xaml/Controls/Popup/PopupPanel.cs
src/Uno.UI/UI/Xaml/Window.Android.cs
src/Uno.UWP/ApplicationModel/Core/CoreApplicationView.cs
src/Uno.UWP/ApplicationModel/Core/CoreApplicationViewTitleBar.Android.cs
src/Uno.UWP/ApplicationModel/Core/CoreApplicationViewTitleBar.cs
src/Uno.UWP/Uno.csproj

GitHub Issue (If applicable): fixes #2007
- Bugfix
- Feature
- On Android, `CoreApplication.GetCurrentView().TitleBar.ExtendViewIntoTitleBar` can now be used to programmatically draw under the status bar (Lollipop and higher).
- Fix the position of the combo box flyout.

Add support for ExtendViewIntoTitleBar, fix ComboBox flyout android position

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TextBoxTests/TextBoxTests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_RoundedCorners.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_RoundedCorners.xaml.cs
src/Uno.UI.Wasm/WasmScripts/Uno.UI.d.ts
src/Uno.UI.Wasm/WasmScripts/Uno.UI.js
src/Uno.UI.Wasm/ts/WindowManager.ts
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.wasm.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.wasm.cs

GitHub Issue (If applicable): fixes #2034, fixes #2095
- Bugfix
- Feature
- Fixes the measure of a TextBoxView where the content may be collapsed
- Adds the ability to focus a TextBox by clicking its header

[Wasm] Fixes the measure of a TextBoxView

---

.azure-devops-wasm-uitests.yml

Fixes transient conditions such as this one:
```
/usr/lib/mono/msbuild/15.0/bin/NuGet.targets(114,5): error :   Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED [/__w/1/s/src/SamplesApp/SamplesApp.UITests/SamplesApp.UITests.csproj]
```

Update the SSL trusted certs during Linux builds

---

doc/articles/controls/CommandBar.md

Fixes the usage example
Incorrect BasedOn example
Correct BasedOn example

Update CommandBar documentation

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Directory.Build.targets
src/SolutionTemplate/UnoSolutionTemplate/Wasm/UnoQuickStart.Wasm.csproj

GitHub Issue (If applicable): Fixes #2129
- Bugfix
- Fixes .NET 4.6.2 missing dependencies
- Fixes long path names issues

[Wasm] Update the bootstrapper to 1.0.3

---

build/ios-uitest-run.sh
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ListViewTests/UnoSamples_Tests.ListView.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_With_ListViews_Count_Measure.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_With_ListViews_Count_Measure.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/MeasureDetectorControl/MeasureDetectorControl.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/MeasureDetectorControl/MeasureDetectorControl.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/MeasureDetectorControl/MeasureDetectorInner.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/StringToHeightConverter.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.iOS.cs

Fix bug where list would not take all available space if item sizes were dynamically updated repeatedly.
Add list measure test.
- Bugfix
fixes https://github.com/unoplatform/private/issues/90

[iOS] ListView - fix list not taking all available space

---

src/Directory.Build.targets
src/SolutionTemplate/UnoSolutionTemplate/Wasm/UnoQuickStart.Wasm.csproj

- Bugfix
Fixes mixed path file copy

Update to Wasm Bootstrapper 1.0.5

---

doc/articles/get-started-next-steps.md

Docs - Add workshop link to Next Steps

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ListViewTests/UnoSamples_Tests.ListView.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_ObservableCollection_Unused_Space.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_ObservableCollection_Unused_Space.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_Weird_Measure.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_Weird_Measure.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/WeirdMeasureSequenceControl.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.iOS.cs

GitHub Issue (If applicable): fixes #2131, fixes #2146
Fix bugs where iOS ListView fails to take extra available space when its desired dimensions change.
- Bugfix

[iOS] Fix ListView measure bugs

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/CanvasTests/Canvas_Measurement_Tests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Canvas/Measure_Children_In_Canvas.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Canvas/Measure_Children_In_Canvas.xaml.cs
src/Uno.UI.Tests/Windows_UI_XAML_Controls/CanvasTests/Given_Canvas.cs
src/Uno.UI/UI/Xaml/Controls/Canvas/Canvas.Layout.cs

Align Canvas measurement with UWP Behavior

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/PathTestsControl/Path_LinearGradientBrush.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/PathTestsControl/Path_LinearGradientBrush.xaml.cs
src/Uno.UI/UI/Xaml/Shapes/ArbitraryShapeBase.iOSmacOS.cs

Should also work for other ArbitraryShapeBase-derived shapes.
- Feature

[iOS] Path - support Fill = LinearGradientBrush

---

src/SolutionTemplate/UnoSolutionTemplate/Droid/UnoQuickStart.Droid.csproj
src/SolutionTemplate/UnoSolutionTemplate/Wasm/UnoQuickStart.Wasm.csproj
src/SolutionTemplate/UnoSolutionTemplate/iOS/UnoQuickStart.iOS.csproj

- Bugfix
- Update template packages to 2.0.512-dev.4178 (unknown package was referenced)
- Fix duplicate content wwwroot in wasm template

Template fixes

---

doc/ReleaseNotes/_ReleaseNotes.md
gitversion.yml

Adjust for next version

---

build/Uno.UI.Build.csproj

- Bugfix
- Update Uno.UI.RemoteControl in app template
- Adjust vsix path for authenticode signing

Adjust vsix publishing

---

doc/articles/contributing/guidelines/creating-tests.md
doc/articles/toc.yml
doc/articles/uno-development/working-with-the-samples-apps.md

Docs - add overview of Uno's test strategies

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.UITests/SampleControlUITestBase.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Shapes/Shapes_Tests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/Rectangle_Color_Bound.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/Rectangle_Color_Bound.xaml.cs
src/Uno.UI/UI/LayoutHelper.cs
src/Uno.UI/UI/Xaml/Media/Brush.wasm.cs
src/Uno.UI/UI/Xaml/Shapes/Rectangle.Android.cs
src/Uno.UI/UI/Xaml/Shapes/Rectangle.wasm.cs
src/Uno.UI/UI/Xaml/Shapes/Shape.cs

[WASM] Update Shape when Fill.Color changes

---

doc/articles/faq.md

The link to the VisibleBoundsPadding from FAQ is wrong
The link is working

Correct the link to the VisibleBoundsPadding

---

doc/articles/roadmap.md

GitHub Issue (If applicable): #2205
currently empty document (Just a heading)
Adding link to where the current roadmap can now be found.

Add link to current road map

---

src/Uno.UI/UI/Xaml/FrameworkElement.Interface.wasm.cs
src/Uno.UI/UI/Xaml/FrameworkElement.wasm.cs
src/Uno.UI/UI/Xaml/UIElement.Pointers.wasm.cs
src/Uno.UI/UI/Xaml/UIElement.wasm.cs

Make additional Xaml properties available as DOM attributes to aid debugging.
- Debug utility

[WASM] Set more properties when AssignDOMXamlProperties is set

---

src/Uno.UI.TestComparer/AzureDevopsDownloader.cs
src/Uno.UI.TestComparer/Comparer/TestFilesComparer.cs
src/Uno.UI.TestComparer/Program.cs

- Fix image comparer stride
- Long paths fixes
- Don't compare with failed builds
- Skip PR comments on non-PR builds

Adjust image comparer

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/CanvasTests/Canvas_Measurement_Tests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Canvas/Canvas_With_Outer_Clip.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Canvas/Canvas_With_Outer_Clip.xaml.cs
src/Uno.UI/Extensions/ViewExtensions.Android.cs
src/Uno.UI/UI/Xaml/UIElement.Android.cs

Previously, if Clip was set, it wouldn't be applied unless the layouting also 'implicitly' clipped the content. Now it will be consistently applied.
- Bugfix

[Android] Always apply non-zero native clip

---

src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.cs
src/Uno.UI.RuntimeTests/Helpers/RunsOnUIThreadAttribute.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_FrameworkElement.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBlock.cs
src/Uno.UI/UI/Xaml/Controls/Canvas/Canvas.cs
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.cs
src/Uno.UI/UI/Xaml/FrameworkElement.wasm.cs
src/Uno.UI/UI/Xaml/IFrameworkElementImplementation.Android.tt
src/Uno.UI/UI/Xaml/IFrameworkElementImplementation.iOS.tt
src/Uno.UI/UI/Xaml/IFrameworkElementImplementation.macOS.tt
src/Uno.UI/UI/Xaml/UIElement.Layout.wasm.cs
src/Uno.UI/UI/Xaml/UIElement.wasm.cs

Return DesiredSize dimensions as ActualWidth/Height even before TextBlock has been arranged, this approximates UWP's behavior.
- Bugfix

TextBlock - return non-zero ActualWidth and ActualHeight after measurement

---

src/Directory.Build.targets
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/xamarinforms-wasm/UnoQuickStart.Wasm/UnoQuickStart.Wasm.csproj
src/SolutionTemplate/UnoSolutionTemplate/Wasm/UnoQuickStart.Wasm.csproj

[Wasm] Update boostrapper to 1.0.10

---

src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.cs
src/Uno.UI.RuntimeTests/IntegrationTests/dxaml/controls/grid/GridIntegrationTests.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_FrameworkElement.cs

Exceptions from failing asynchronous tests in `Uno.UI.RuntimeTests` were not being rethrown, causing failures to be swallowed.
- Bugfix

Fail failing asynchronous RuntimeTests

---

build/ci/.azure-devops-screenshot-compare.yml

Fix screenshot compare results are not published properly

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/GridTestsControl/Grid_Spacing_Adjustable.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/GridTestsControl/Grid_Spacing_Adjustable.xaml.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Grid.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/Grid.cs
src/Uno.UI/UI/Xaml/Controls/Grid/Grid.Layout.cs
src/Uno.UI/UI/Xaml/Controls/Grid/Grid.Properties.cs

GitHub Issue (If applicable): fixes #1513 
- Feature

Implement Grid.ColumnSpacing and RowSpacing

---

src/Uno.UI/UI/Xaml/Controls/FlipView/FlipView.wasm.cs

This allows the code analyzer and the doc generation to correctly report the implementation status of this control (implemented it is not).
GitHub Issue (If applicable): #2320 

[WASM] Mark FlipView not implemented

---

src/Uno.UI.TestComparer/AzureDevopsDownloader.cs
src/Uno.UI.TestComparer/Comparer/TestFilesComparer.cs
src/Uno.UI.TestComparer/Program.cs

- Write PR comment to console if no PAT was provided
- Keep the current build last
- Use only the last comparison for the PR report

Improve screenshot comparer tool

---

doc/articles/getting-started-tutorial-1.md

Adjust the tutorial for nuget feed selection

---

src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/xamarinforms-wasm/UnoQuickStart.Wasm/UnoQuickStart.Wasm.csproj

Update X.F templates version to stable 4.3.4

Update X.F templates version to 4.3.4

---

build/local-ios-uitest-run.sh
doc/articles/uno-development/working-with-the-samples-apps.md

Added shell scripts to run iOS UI Tests in simulators on macOS.

[iOS] Add shell tests scripts for iOS Simulator on macOS

---

doc/articles/getting-started-tutorial-1.md

Adjust steps for clearer walk through.

Update getting started tutorial

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI.Tests/Windows_UI_XAML_Controls/GridTests/Given_Grid.cs
src/Uno.UI/UI/Xaml/Controls/Grid/Grid.Layout.cs

GitHub Issue (If applicable): fixes #2130
- Bugfix

Grid - fix invalid measure when total star size is 0

---

src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/Geometry/ArcSegmentPage.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/Geometry/ArcSegmentPage.xaml.cs

Exclude non-supported feature from Android and iOS.
GitHub Issue (If applicable): fixes #2261 
- Sample

Fix ArcSegmentPage sample crashes

---

doc/articles/getting-started-tutorial-1.md

Missing information for the getting started tutorial
Added some correct branding and clarified what is being created - a simple Bug Tracking app (based on customer feedback)

Update getting-started-tutorial.md to add some correct branding and clarified what is being created

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/Manipulation_Tests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Input/GestureRecognizerTests/Manipulation_Basics.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Input/GestureRecognizerTests/Manipulation_Basics.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Input/GestureRecognizerTests/Manipulation_WhenInScrollViewer.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Input/GestureRecognizerTests/Manipulation_WhenInScrollViewer.xaml.cs
src/Uno.UI.BindingHelper.Android/Uno/UI/UnoMotionHelper.java
src/Uno.UI/Extensions/UIEventExtensions.iOSmacOS.cs
src/Uno.UI/UI/Xaml/Controls/FlipView/NativePagedView.Android.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/NativeListViewBase.Android.cs
src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.Android.cs
src/Uno.UI/UI/Xaml/Input/PointerRoutedEventArgs.Android.cs
src/Uno.UI/UI/Xaml/Input/PointerRoutedEventArgs.iOS.cs
src/Uno.UI/UI/Xaml/UIElement.Pointers.Android.cs
src/Uno.UI/UI/Xaml/UIElement.Pointers.iOS.cs
src/Uno.UWP/UI/Input/GestureRecognizer.Manipulation.cs

GitHub Issue:
fixes https://github.com/unoplatform/uno/issues/2092
fixes https://github.com/unoplatform/uno/issues/2219
- Fix horizontal scrolling in `ListView`
- Pointer capture
Add support of multi-touch
- Multi touch was not supported
- The fix https://github.com/unoplatform/uno/pull/2338 broke the manipulations event while in `ScrollViewer` ...
- ... and underlined a bug were capture (and manipulations) was released prematurely
- Synchronous multiple pointers are now properly differentiated, so multi-touch manipulations are now detected properly
- The captures are now longer released too early, so the horizontal scroll in SV work properly

Add support for multi touches

---

build/PackageDiffIgnore.xml

Adjust DiffIgnore for 2.0.530 release

---

build/android-uitest-run.sh

Stabilizes the installed Android SDK version for Android UI Test builds.

Install explicit android-sdk version

---

build/ci/.azure-devops-windows.yml

- Use msbuild automatic worker count 
- Use latest vstest

Adjust build stability

---

doc/articles/get-started.md

Update the getting started template

---

build/Uno.UI.nuspec
src/SourceGenerators/Uno.UI.SourceGenerators/Telemetry/TelemetryCommonProperties.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.Telemetry.cs

- Bugfix
- Use the InformationalVersion for the product version
- Add missing dependency following https://github.com/unoplatform/uno/pull/1917
- Adjust IsRunningCI to be present in all events

Telemetry updates

---

build/uno.ui.targets

Adjust the nuget package dev override detection condition after #2515

Adjust package override detection condition

---

build/ci/.azure-devops-windows.yml
doc/ReleaseNotes/_ReleaseNotes.md
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ListViewTests/UnoSamples_Tests.ListView.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Button/ComboBox_Simple.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListViewSelectedItems.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListViewSelectedItems.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_SelectedItem.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_VirtualizePanelAdaptaterIdCache.xaml.cs
src/Uno.UI.Tests/Windows_UI_XAML_Controls/ListViewBaseTests/Given_ListViewBase.cs
src/Uno.UI.Tests/Windows_UI_XAML_Controls/SelectorTests/Given_Selector.cs
src/Uno.UI/UI/Xaml/Controls/ComboBox/ComboBox.cs
src/Uno.UI/UI/Xaml/Controls/FlipView/FlipView.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.cs
src/Uno.UI/UI/Xaml/Controls/Primitives/Selector.cs
src/Uno.UI/UI/Xaml/Controls/Primitives/SelectorItem.cs
src/Uno.UI/UI/Xaml/Media/Animation/Animators/NotSupportedAnimator.cs

GitHub Issue (If applicable): Fixes https://github.com/unoplatform/uno/issues/1606, Fixes #2538, Fixes #2475
- Bugfix
Changing the `Selector.IsSelected` property is not reflecting to the hosting `Selector` instance.
The `Selector.IsSelected` is now properly reflected

Fix Selector support for IsSelected

---

src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Automation.Peers/AutomationPeerAnnotation.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Automation/AutomationAnnotation.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls.Maps/MapTileSource.cs
src/Uno.UI/UI/Xaml/ControlTemplate.cs
src/Uno.UI/UI/Xaml/Controls/ItemsPanelTemplate.cs
src/Uno.UI/UI/Xaml/Data/BindingBase.cs
src/Uno.UI/UI/Xaml/DataTemplate.cs
src/Uno.UI/UI/Xaml/GridLength.cs

Minor alignments with the UWP contract.
- Bugfix

UWP alignments - add ctors, equality comparison, make BindingBase non-abstract

---

build/ci/.azure-devops-windows.yml
build/ci/templates/gitversion.yml
gitversion.yml

All PR generated nuget packages will be published to https://dev.azure.com/uno-platform/Uno%20Platform/_packaging?_a=feed&feed=uno-pullrequests for easier automated consumption from nuget during canaries creation.

Include build ID in PR tag

---

build/Uno.UI.Build.csproj
build/ci/.azure-devops-windows.yml
build/ci/templates/gitversion.yml
src/Directory.Build.props
src/SamplesApp/SamplesApp.Droid/SamplesApp.Droid.csproj
src/SamplesApp/SamplesApp.UITests/Microsoft_UI_Xaml_Controls/NumberBoxTests/Given_NumberBox.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TextBoxTests/TextBoxTests.cs
src/SourceGenerators/Uno.UI.SourceGenerators/Uno.UI.SourceGenerators.csproj

- Remove unused doc generation in vs build
- Move unit test runner to separate job for reduced memory pressure and faster retries
- Add references assemblies to all projects to enhance hard linking
- Disable PR package publication for forks
- Add job attempt to generated PR nuget packages to avoid conflicts

Adjust build pipelines

---

README.md

Adjust the gitter target audience to be for contributors, and use stackoverflow for general questions.

Adjust Gitter target audience

---

doc/articles/uno-development/debugging-uno-ui.md

Links are taking to 404 pages on Github.
Links will take to the right resource within the repository

Fix broken links on documentation

---

doc/ReleaseNotes/_ReleaseNotes.md
src/SolutionTemplate/UnoLibraryTemplate/CrossTargetedLibrary.vstemplate
src/SolutionTemplate/UnoSolutionTemplate/UnoApp.vstemplate

GitHub Issue (If applicable): #2620
Added missing project template tags:
https://docs.microsoft.com/en-us/visualstudio/ide/template-tags?view=vs-2019
- Bugfix
Templates now display tags and you can filter your way to them. Also added a convenient "Uno Platform" tag so you can easily show all platform uno templates with a single filter.

Add template tags to project templates

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ButtonTests/UnoSamples_Tests.Button_IsEnabled_Automated.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TextBoxTests/TextBoxTests.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Button/Nested_Buttons.xaml

- Other... Please describe: UI Tests
No UI Tests
Added new UI tests for nested buttons and textbox before changing text
https://nventive.visualstudio.com/Umbrella/_sprints/taskboard/Umbrella%20Team/Umbrella/2020/Sprint%203?workitem=173212

UI Tests Nested Buttons and Radio button pressed

---

doc/ReleaseNotes/_ReleaseNotes.md
src/Uno.UI/UI/Xaml/Controls/Flyout/Flyout.md
src/Uno.UI/UI/Xaml/Controls/Popup/Popup.md

The documentation contains informations about adding a LightDismissOverlayMode but not about adding a background color to the Flyout and Popup
Adding information for customizing the background color of the Flyout and Popup LightDismissOverlay

Adding to the documentation for changing the color of LightDismissOverlayBackground

---

src/Uno.Foundation/Uno.Foundation.csproj
src/Uno.UI/UI/Xaml/Media/Animation/Animators/NotSupportedAnimator.cs
src/Uno.UI/Uno.UI.csproj
src/Uno.UWP/Uno.csproj

GitHub Issue (If applicable): #626 
- Remove visible duplicate items in VSmac
- Don't AOT the t4 generator when already done
- Don't fail on `NotSupportedAnimator`

[macOS] Misc updates

---

src/Uno.UI.RuntimeTests/Tests/System/Given_DispatcherQueueTimer.cs
src/Uno.UWP/System/DispatcherQueueTimer.cs

- Bugfix
The timer in the test may be executed more than once, raising an InvalidOperationException.

Adjust DispatcherQueueTimer runtime test

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ImageTests/UnoSamples_Tests.Image.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/ImageWithLateSourceFixedDimensions.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/ImageWithLateSourceFixedDimensions.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/ImageWithLateSourceUniformToFill.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/ImageWithLateSourceUniformToFill.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/Image_Margin_Large.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/Image_Margin_Large.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/Image_UseTargetSize.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/Image_UseTargetSizeLate.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/Image_UseTargetSizeLate.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/Models/ImageWithLateSourceViewModel.cs
src/Uno.UI/UI/Xaml/Controls/Image/Image.Android.cs
src/Uno.UI/UI/Xaml/Controls/Image/Image.cs

GitHub Issue (If applicable): fixes #2545
fixes  #2676
fixes https://github.com/unoplatform/private/issues/121
Fixes for various regressions in Image display on Android related to adjusting the layouting logic.
- Bugfix

[Android] Fix Image bugs

---

build/ci/.azure-devops-screenshot-compare.yml
src/Uno.UI.Tests/Global.cs
src/Uno.UI.Tests/Windows_UI_XAML_Controls/ListViewBaseTests/Given_ListViewBase.cs
src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/Given_XamlReader.cs
src/Uno.UI/UI/Xaml/Style/Generic/GenericStyles.cs

- Bugfix
- Tests fail on CI with out of memory (too much logging)
- CI build may continue when canceled

Adjust unit test silent errors

---

src/SamplesApp/SamplesApp.UITests/SamplesApp.UITests.csproj

To see if it's improving performance with `.FastTap()`

Try Xamarin.UITests v3.0.7-dev2

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/DoubleTappedTapped_Tests.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_FrameworkElement.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/MyLinearLayout.cs
src/Uno.UI/Controls/CommandBarRenderer.Android.cs
src/Uno.UI/UI/Xaml/FrameworkElement.Android.cs

GitHub Issue (If applicable): fixes #2721 
Reverts incorrect fix for CommandBar display issues and applies a better fix. 
- Bugfix

[Android] Fix CommandBar misalignment bug

---

.dependabot/config.yml

Dependabot commit message are compatible.

chore: adjust dependabot commit message structure

---

src/Uno.UWP/ApplicationModel/DataTransfer/DataPackage.cs
src/Uno.UWP/ApplicationModel/DataTransfer/DataPackageOperation.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.DataTransfer/DataPackage.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.DataTransfer/DataPackageOperation.cs

- Feature
Windows.ApplicationModel.DataTransfer.DataPackage.RequestedOperation is not implemented.
It is partly implemented - it allows setting it to `copy` operation (and this is operation that is currently supported). It doesn't change how Uno implementation of clipboard works, but this small change allows to build apps that implicite states copy as requested operation.

Implement DataPackageOperation (partly)

---

doc/articles/get-started-next-steps.md

Added one link on forks

---

build/ios-uitest-run.sh
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/CommandBarTests/UnoSamples_Tests.NativeCommandBar.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/CommandBarTests/UnoSamples_Tests.XamlCommandBar.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/CommandBar_Native_Frame.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/CommandBar_Native_Frame.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/Native_Frame/Page_Detail.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/Native_Frame/Page_Detail.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/Native_Frame/Page_With_CommandBar_TextBlock.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/Native_Frame/Page_With_CommandBar_TextBlock.xaml.cs
src/Uno.UI/Controls/CommandBarNavigationItemRenderer.iOS.cs
src/Uno.UI/Extensions/UIViewExtensions.iOSmacOS.cs

GitHub Issue (If applicable): fixes #2908
- Bugfix
Fix a bug arising from strange native behaviour when navigating back to a page, which could cause a vertically-centred TextBlock inside a CommandBar to be laid out with zero height.

[iOS] Fix text in CommandBar title not appearing after navigation

---

build/Uno.UI.nuspec
src/Uno.CrossTargetting.props
src/Uno.UI.Toolkit/Uno.UI.Toolkit.csproj

GitHub Issue (If applicable): Fixes #2924
- Bugfix
The ElevatedView control can be used in UWP. The Generic.xaml file was not being generated and packaged in the nupkg.

fix: [uap10] Fix ElevatedView Generic.xaml packaging

---

src/Directory.Build.targets
src/SourceGenerators/Uno.UI.SourceGenerators/Uno.UI.SourceGenerators.csproj
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.Reflection.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlRedirection/NamespaceDeclaration.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlRedirection/XamlMember.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlRedirection/XamlSchemaContext.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlRedirection/XamlType.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlRedirection/XamlXmlReader.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlRedirection/XamlXmlReaderSettings.cs
src/SourceGenerators/Uno.UI.Tasks/Uno.UI.Tasks.csproj
src/Uno.UI.Tests/Uno.UI.Tests.csproj

Source generators and tasks are depending on binaries not available on .NET Core.
It's now possible to build a Wasm app using .NET Core. No testing of this scenario yet, will be enabled with the addition of cli templates creation.

Adjust dependencies for .NET Core compatibility

---

src/Uno.UI/UI/Xaml/Input/PointerRoutedEventArgs.macOS.cs

GitHub Issue (If applicable): #626, fixes #2989
- Bugfix

fix(Slider): macOS vertical thumb movement is flipped

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/DropDownButton/DropDownButtonPage.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/DropDownButton/DropDownButtonPage.xaml.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Automation/ExpandCollapsePatternIdentifiers.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/DropDownButton.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/DropDownButtonAutomationPeer.cs
src/Uno.UI/Helpers/WinUI/SharedHelpers.cs
src/Uno.UI/UI/Xaml/Automation/ExpandCollapsePatternIdentifiers.cs
src/Uno.UI/UI/Xaml/Controls/DropDownButton/DropDownButton.cs
src/Uno.UI/UI/Xaml/Controls/DropDownButton/DropDownButton.xaml
src/Uno.UI/UI/Xaml/Controls/DropDownButton/DropDownButtonAutomationPeer.cs
src/Uno.UI/Uno.UI.csproj

GitHub Issue (If applicable): closes #2715 
- Feature
`DropDownButton` not supported.
`DropDownButton` supported

feat: Add DropDownButton

---

.gitpod.yml
build/gitpod/build-wasm.sh

Update the image use for gitpod reviews and pre-builds, which adds a workaround for .NET Core 3.1 WinFX file casing issue.

chore: Update container for gitpod to support C# 8.0

---

src/Uno.UI/UI/Xaml/Controls/Page/Page.cs

GitHub Issue (If applicable): #1514
- Feature
The `Page.TopAppBar` and `Page.BottomAppBar` is not implemented and only works on UWP
Added the `[Uno.NotImplemented]` attribute over the `Page.TopAppBar` and `Page.BottomAppBar` to clearly communicate that the feature is not implemented in 
* macOS
* Android
* iOS
* WASM
Adding the attribute is following the recommendation in issue #1514

feat: Added NotImplemented Attribute for Page.TopAppBar and Page.BottomAppBar

---

doc/articles/getting-started-tutorial-1.md

GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/3049

docs: Add workaround for ConverterParameter issue

---

README.md

Update documentation to mention you need VS2019

Update documentation to mention you need VS2019

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media_Animation/Given_DoubleAnimation.cs
src/Uno.UI/UI/Xaml/Media/Animation/Timeline.animation.cs

Fixes regression introduced by https://github.com/unoplatform/uno/pull/2921
- Bugfix

fix(animation): [iOS] Fix InvalidCastException when app resumes while animation is active

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Flyout.cs
src/Uno.UI/Controls/CommandBarRenderer.iOS.cs
src/Uno.UI/Controls/NativeCommandBarPresenter.iOS.cs
src/Uno.UI/Controls/NativeFramePresenter.iOS.cs
src/Uno.UI/Extensions/UIViewExtensions.iOSmacOS.cs
src/Uno.UI/UI/Xaml/Controls/Flyout/FlyoutBase.cs
src/Uno.UI/UI/Xaml/Controls/MediaPlayer/MediaPlayerPresenter.cs

Fixes bug where CommandBar position wouldn't be adjusted properly in a sequence involving collapsing the CommandBar, hiding the status bar, rotating the screen to landscape and back to portrait, showing the status bar, and finally showing the CommandBar again.
GitHub Issue (If applicable): fixes #2775 (tentative)
- Bugfix

[iOS] fix(commandbar): Update CommandBar layout when Visibility changes, misc fixes

---

src/Uno.UI/UI/Xaml/Controls/ComboBox/ComboBox.cs
src/Uno.UI/UI/Xaml/Controls/ItemsControl/ItemsControl.macOS.cs
src/Uno.UI/UI/Xaml/Controls/ItemsControl/ItemsPresenter.cs
src/Uno.UI/UI/Xaml/Controls/Popup/Popup.macOS.cs
src/Uno.UI/UI/Xaml/FrameworkElement.macOS.cs

GitHub Issue (If applicable): closes #2972 
- Feature
ComboBox shows up, but does not display items.
ComboBox works properly.

feat: [macOS] ComboBox

---

src/SamplesApp/SamplesApp.macOS/Info.plist
src/Uno.UWP/ApplicationModel/Package.Other.cs
src/Uno.UWP/ApplicationModel/Package.cs
src/Uno.UWP/ApplicationModel/Package.iOSmacOS.cs
src/Uno.UWP/ApplicationModel/PackageId.cs
src/Uno.UWP/ApplicationModel/PackageId.iOSmacOS.cs

GitHub Issue (If applicable): #3051
- Feature
Not supported on macOS
Supported on macOS.

feat: [macOS] Support for Package and PackageId

---

build/android-uitest-run.sh

Updates the SDK CLI tools to the latest to fix possible download issue.

chore: Update android CLI tools to latest

---

build/Uno.UI.Lottie.nuspec

Lottie NuGet package were not referencing dependencies properly.

fix(lottie): Fixed missing dependencies in NuGet package.

---

src/Uno.UI/Media/PathStreamGeometryContext.cs
src/Uno.UI/UI/Xaml/Shapes/Ellipse.iOSmacOS.cs
src/Uno.UI/UI/Xaml/Shapes/Rectangle.iOSmacOS.cs
src/Uno.UI/UI/Xaml/Shapes/Shape.iOSmacOS.cs

closes #2961 
- Feature
Shapes are not supported in macOS
Shapes are supported in macOS

feat: (macOS) Support for Shapes

---

build/Uno.UI.RemoteControl.nuspec
build/Uno.UI.WpfHost.nuspec
build/Uno.UI.nuspec
src/AddIns/Uno.UI.Lottie/Uno.UI.Lottie.csproj
src/Directory.Build.targets
src/SamplesApp/SamplesApp.UWP.Design/SamplesApp.UWP.Design.csproj
src/SamplesApp/SamplesApp.UWP/SamplesApp.UWP.csproj
src/SamplesApp/SamplesApp.iOS/SamplesApp.iOS.csproj
src/SamplesApp/SamplesApp.macOS/SamplesApp.macOS.csproj
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.Droid/BlankApp.Droid.csproj
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.UWP/BlankApp.Uwp.csproj
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.Wasm/BlankApp.Wasm.csproj
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.iOS/BlankApp.iOS.csproj
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.macOS/BlankApp.macOS.csproj
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/xamarinforms-wasm/UnoXFQuickStart.Wasm/UnoXFQuickStart.Wasm.csproj
src/SolutionTemplate/UnoLibraryTemplate/CrossTargetedLibrary.csproj
src/SolutionTemplate/UnoSolutionTemplate/Droid/UnoQuickStart.Droid.csproj
src/SolutionTemplate/UnoSolutionTemplate/UWP/UnoQuickStart.Uwp.csproj
src/SolutionTemplate/UnoSolutionTemplate/Wasm/UnoQuickStart.Wasm.csproj
src/SolutionTemplate/UnoSolutionTemplate/iOS/UnoQuickStart.iOS.csproj
src/SolutionTemplate/UnoSolutionTemplate/macOS/UnoQuickStart.macOS.csproj
src/Uno.UI.RemoteControl.Host/Uno.UI.RemoteControl.Host.csproj
src/Uno.UI/Uno.UI.csproj
src/Uno.UWPSyncGenerator/Uno.UWPSyncGenerator.csproj

chore: Bump uno packages to latest stable

---

src/SolutionTemplate/UnoLibraryTemplate/CrossTargetedLibrary.csproj

- Bugfix
The user experience with Uno Cross Targeted Library in visual studio is using the first listed target framework. Using uap10 first makes for a better user experience.

fix(vsix): Adjust Library targets frameworks order to improve intellisense

---

src/Directory.Build.targets

chore: Update Uno.UITest to latest stable

---

src/Uno.UI.Toolkit/ElevatedView.cs
src/Uno.UI.Toolkit/Themes/Generic.xaml
src/Uno.UI.Toolkit/UIElementExtensions.cs

What kind of change does this PR introduce
- Feature
-->
- There is no implementation for uwp
- ElevatedView implemented for uwp
Sample is already available for this control

feat: ElevatedView implementation for Uwp

---

build/PackageDiffIgnore.xml

chore: Adjust diffignore file for 2.4.4 release

---

doc/articles/features/windows-ui-xaml-xbind.md
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlConstants.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_Event.xaml
src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_Event.xaml.cs
src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_Event_DataTemplate.xaml
src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_Event_DataTemplate.xaml.cs
src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Given_xBind_Binding.cs

GitHub Issue (If applicable): Fixes #3172
- Feature
Adds support for x:Bind to events.

feat: Add x:Bind support for events

---

build/Uno.WinUI.nuspec

- Bugfix
Fix `ElevatedView` on UWP not showing content.

fix(ElevatedView): Fix ElevatedView not showing in UWP

---

CONTRIBUTING.md
README.md
doc/articles/contributing/guidelines/issue-triage.md
doc/articles/faq.md
doc/articles/features/working-with-gitpod.md
doc/articles/get-started-next-steps.md

docs: Adjust for discord links

---

build/Uno.WinUI.RemoteControl.nuspec

- Bugfix
Referencing Uno.UI.RemoteControl in a UWP projects can fail with the following error:
```
##[error]C:\Users\VssAdministrator\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): Error : Error: NUTC3036:Internal Compiler Error: Method 'static System.String WebAssembly.Runtime.InvokeJS(System.String, System.Int32&)' on type 'WebAssembly.Runtime' from assembly 'Uno.Wasm.WebSockets' is missing the System.Runtime.RuntimeImportAttribute custom attribute while loading type 'WebAssembly.Runtime'. while computing compilation roots.
```
The Uno.UI.RemoteControl can be referenced safely from a UWP project, even though it's not going to have any effect.
Please check if your PR fulfills the …

fix(remotecontrol): Failsafe for Uno.UI.RemoteControl when referenced in UWP projects

---

build/Uno.UI.Build.csproj
build/ci/.azure-devops-windows.yml
build/ci/templates/nuget-cache.yml
src/Directory.Build.targets

- Bugfix
The Nuget folder is now compressed to reduce the disk space usage on agents.

ci: Compress the nuget folder on Windows

---

build/Uno.UI.Build.csproj
build/ci/.azure-devops-windows.yml
src/Directory.Build.targets
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/Uno.UI.Tests/Uno.UI.Tests.csproj
src/Uno.UI.Tests/Windows_UI_Xaml/EventsTests/Controls/FrameworkElement_ControlTemplate_Event.xaml
src/Uno.UI.Tests/Windows_UI_Xaml/EventsTests/Controls/FrameworkElement_ControlTemplate_Event.xaml.cs
src/Uno.UI.Tests/Windows_UI_Xaml/EventsTests/Controls/FrameworkElement_DataTemplate_Event.xaml
src/Uno.UI.Tests/Windows_UI_Xaml/EventsTests/Controls/FrameworkElement_DataTemplate_Event.xaml.cs
src/Uno.UI.Tests/Windows_UI_Xaml/EventsTests/Controls/FrameworkElement_ItemsPanelTemplate_Event.xaml
src/Uno.UI.Tests/Windows_UI_Xaml/EventsTests/Controls/FrameworkElement_ItemsPanelTemplate_Event.xaml.cs
src/Uno.UI.Tests/Windows_UI_Xaml/EventsTests/Given_FrameworkElement_Event.cs

GitHub Issue (If applicable): fixes #3332 
- Bugfix
Events specified in a `ControlTemplate` or `ItemsPanelTemplate` are not registered properly.

fix(reg): Fix invalid XAML events registration in ControlTemplate and ItemsPanelTemplate

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/Uno.UI.Tests/Windows_UI_Xaml/Given_ResourceDictionary.cs
src/Uno.UI/UI/Xaml/DependencyObjectStore.cs
src/Uno.UI/UI/Xaml/Markup/Reader/XamlObjectBuilder.cs
src/Uno.UI/UI/Xaml/ResourceDictionary.cs
src/Uno.UI/UI/Xaml/ResourceResolver.cs

Fixes regression introduced by #1766.
GitHub Issue (If applicable): fixes #3331 
- Bugfix

fix(resources): Restore retrieval of system resources from ResourceDictionary

---

src/Uno.UI/UI/Xaml/Controls/PersonPicture/InitialsGenerator.cs

GitHub Issue (If applicable): #3318
- Code comment changes
Code comment includes a term with negative racial connotations.
Code comment now uses a term without negative racial connotations.
closes #3318

docs: replace the term "whitelist"

---

.vsts-ci.yml
build/run-template-tests.ps1

GitHub Issue (If applicable): #1876
Add more template integration tests

ci: Add more template integration tests

---

src/Uno.UI.Wasm/WasmCSS/Uno.UI.css
src/Uno.UI.Wasm/WasmScripts/Uno.UI.d.ts
src/Uno.UI.Wasm/WasmScripts/Uno.UI.js
src/Uno.UI.Wasm/ts/WindowManager.ts
src/Uno.UI.Wasm/tsBindings/WindowManagerRegisterPointerEventsOnViewParams.ts
src/Uno.UI/UI/Xaml/DependencyProperty.cs
src/Uno.UI/UI/Xaml/DependencyPropertyDetails.cs
src/Uno.UI/UI/Xaml/Shapes/Shape.wasm.cs
src/Uno.UI/UI/Xaml/UIElement.EventRegistration.wasm.cs
src/Uno.UI/UI/Xaml/UIElement.Pointers.wasm.cs
src/Uno.UI/UI/Xaml/WindowManagerInterop.wasm.cs
src/Uno.UWP/UI/Color.wasm.cs

Minor optimization regarding performance of the WCT DataGrid
Perf is not optimal ...
Perf is still not optimal, but slightly better.

perf: Minor perf improvements for WASM

---

doc/articles/features/windows-ui-xaml-application.md

docs: Update Application.Suspending documentation

---

build/ci/.azure-devops-ios-tests-run.yml

ci: Adjust iOS UITest build definitions parameters

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/Uno.UI.Tests.ViewLibrary/MyExtControl.cs
src/Uno.UI.Tests.ViewLibrary/Themes/MyExtControl.xaml
src/Uno.UI.Tests/Windows_UI_Xaml/Given_ThemeResource.cs
src/Uno.UI/Helpers/Xaml/SetterExtensions.cs
src/Uno.UI/Mock/ArbitraryShapeBase.net.cs
src/Uno.UI/UI/Xaml/Controls/Control/Control.cs
src/Uno.UI/UI/Xaml/Data/ResourceBinding.cs
src/Uno.UI/UI/Xaml/DependencyObjectStore.Binder.cs
src/Uno.UI/UI/Xaml/DependencyObjectStore.cs
src/Uno.UI/UI/Xaml/FrameworkElement.cs
src/Uno.UI/UI/Xaml/ResourceResolver.cs
src/Uno.UI/UI/Xaml/Setter.cs
src/Uno.UI/UI/Xaml/Style/Style.cs

GitHub Issue (If applicable): fixes #3300 
- Feature

Update theme resource values when system theme changes

---

src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml
src/Uno.UI/UI/Xaml/Style/Generic/SystemResources.xaml

Adds system resource values that are available in UWP but missing in Uno.
GitHub Issue (If applicable): fixes #3382, fixes #3350 
- Bugfix

Add missing system resources

---

src/Uno.UI.Tests/Windows_UI_Xaml/Given_ResourceDictionary.cs
src/Uno.UI/UI/Xaml/XamlFilePathHelper.shared.cs

GitHub Issue (If applicable): fixes #3361
- Bugfix (regression)

fix(reg): Restore support for leading slash in ResourceDictionary Source path

---

doc/templates/uno/styles/main.js

fix(Documentation): double table of content

---

src/Uno.UI/UI/Xaml/FrameworkElement.wasm.cs

Fixes regression introduced by https://github.com/unoplatform/uno/pull/3395
- set ChangedCallbackName correctly
- adjust OnGenericPropertyUpdated() signature to match that expected by DependencyPropertyGenerator
GitHub Issue (If applicable): fixes #3431
- Bugfix

fix(reg): [WASM] Fix breaking debug build after DependencyPropertyGenerator changes

---

License.md

docs: Update License for missing company name

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ListViewTests/UnoSamples_Tests.ListView.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/CounterGrid.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_ObservableCollection_CreationCount.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_ObservableCollection_CreationCount.xaml.cs
src/Uno.UI/UI/Xaml/Controls/ItemsStackPanel/ManagedItemsStackPanel.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/CollectionChangedOperation.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.iOS.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.iOSAndroid.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.managed.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelGenerator.managed.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.managed.cs
src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.cs

GitHub Issue (If applicable): resolves #3258 
- Feature

[WASM] Add proper observable collection support

---

src/Uno.UI/UI/Xaml/Controls/NavigationView/NavigationView.Properties.cs

GitHub Issue (If applicable): #2875
- Bugfix
- AlwaysShowHeader property defaults to false
- AlwaysShowHeader property defaults to true, to follow uwp 
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.navigationview.alwaysshowheader?view=winrt-19041 default behavior

fix: NavigationView AlwaysShowHeader property default as true

---

src/SolutionTemplate/UnoSolutionTemplate/UWP/UnoQuickStart.Uwp.csproj

GitHub Issue (If applicable): closes #3455 
- Feature
6.2.2 is used.
Using 6.2.9 to match MSBuild.Extras

feat: Update Microsoft.NETCore.UniversalWindowsPlatform to 6.2.9

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ToggleSwitchTests/UnoSamples_Tests.ToggleSwitch.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ToggleSwitchControl/ToggleSwitch_Header.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ToggleSwitchControl/ToggleSwitch_Header.xaml.cs
src/Uno.UI/UI/Xaml/Controls/ToggleSwitch.cs

GitHub Issue (If applicable): #3437
- Bugfix
ToggleSwitch.Header.Visibility is always Collapsed and thus non-functional in non-UWP platforms
ToggleSwitch.Header functions across all platforms

fix: ToggleSwitch.Header is never visible

---

doc/articles/using-uno-ui.md

docs: Add missing constructor in Control Template sample

---

doc/articles/features/Lottie.md

docs: Add missing namespaces for the AnimatedVisualPlayer

---

build/uno.winui.targets
src/SourceGenerators/Uno.UI.SourceGenerators/BindableTypeProviders/BindableTypeProvidersGenerationTask.cs
src/SourceGenerators/Uno.UI.SourceGenerators/DependencyObject/DependencyObjectGenerator.cs
src/SourceGenerators/Uno.UI.SourceGenerators/Helpers/RoslynMetadataHelper.cs
src/SourceGenerators/Uno.UI.SourceGenerators/Helpers/SymbolExtensions.cs
src/SourceGenerators/Uno.UI.SourceGenerators/NativeCtor/NativeCtorsGenerator.cs
src/SourceGenerators/Uno.UI.SourceGenerators/TSBindings/TSBindingsGenerator.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlConstants.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.Reflection.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/SourceGenerators/Uno.UI.Tasks/Content/Uno.UI.Tasks.targets
src/Uno.Foundation.Skia/Uno.Foundation.Skia.csproj
src/Uno.Foundation/Uno.Foundation.csproj
src/Uno.UI.Runtime.Skia.Gtk/buildTransitive/Uno.UI.Runtime.Skia.Gtk.targets
src/Uno.UI.Runtime.Skia.Wpf/buildTransitive/Uno.UI.Runtime.Skia.Wpf.targets
src/Uno.UI.Runtime.Wasm/buildTransitive/Uno.UI.Runtime.Wasm.targets
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/DatePickerFlyout.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/TimePickerFlyout.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Documents/InlineCollection.cs
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextVisual.Skia.cs
src/Uno.UI/UI/Xaml/DependencyPropertiesImplementation.tt
src/Uno.UI/UI/Xaml/FrameworkElement.Interface.Skia.cs
src/Uno.UI/UI/Xaml/FrameworkElement.Interface.netstdref.cs
src/Uno.UI/UI/Xaml/FrameworkElement.Skia.cs
src/Uno.UI/UI/Xaml/UIElement.Skia.cs
src/Uno.UWP/ApplicationModel/Resources/ResourceLoader.cs

- Bugfix / refactorings
Misc adjustments for the reference implementation and wasm split.

Refactor SourceGenerators to use proper equality

---

build/Uno.WinUI.Skia.Gtk.props
build/Uno.WinUI.Skia.Gtk.targets
build/Uno.WinUI.Skia.Wpf.props
build/Uno.WinUI.Skia.Wpf.targets
build/Uno.WinUI.WebAssembly.props
build/Uno.WinUI.nuspec
build/uno.winui.cross-runtime.targets
build/uno.winui.targets
src/AddIns/Uno.UI.Lottie/buildTransitive/Uno.UI.Lottie.targets
src/AddIns/Uno.UI.MSAL/Uno.UI.MSAL.csproj
src/AddIns/Uno.UI.MSAL/buildTransitive/Uno.UI.MSAL.targets
src/SamplesApp/SamplesApp.Skia/SamplesApp.Skia.csproj
src/SamplesApp/SamplesApp.Wasm/SamplesApp.Wasm.csproj
src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props
src/Uno.UI.RemoteControl/buildTransitive/Uno.UI.RemoteControl.targets
src/Uno.UI.Runtime.Skia.Gtk/buildTransitive/Uno.UI.Runtime.Skia.Gtk.props
src/Uno.UI.Runtime.Skia.Wpf/buildTransitive/Uno.UI.Runtime.Skia.Wpf.props
src/Uno.UI.Runtime.Skia.Wpf/buildTransitive/Uno.UI.Runtime.Skia.Wpf.targets
src/Uno.UI.Runtime.WebAssembly/buildTransitive/Uno.UI.Runtime.WebAssembly.props
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextVisual.Skia.cs
src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml
src/Uno.UI/UI/Xaml/Style/Generic/SystemResources.xaml
src/Uno.UWP/ApplicationModel/Package.Other.cs

- Feature
Add support for `UnoRuntimeProjectReference` to ease the creation of cross-runtime packages.

feat: Add support for msbuild UnoRuntimeProjectReference

---

build/Uno.UI.Build.csproj
build/ci/.azure-devops-android-tests.yml

- Fixes invalid template replacement
- Fail android tests only on second run

fix(reg): Adjust missing cross-runtime project template replace

---

build/convert-sourcetree-to-winui.cmd
build/run-sync-generator.cmd
doc/articles/uno-development/debugging-uno-ui.md
src/Uno.UI/Helpers/WinUI/SharedHelpers.cs
src/Uno.UWPSyncGenerator.Reference/Uno.UWPSyncGenerator.Reference.csproj
src/Uno.UWPSyncGenerator/Generator.cs
src/Uno.UWPSyncGenerator/Program.cs

- Feature
Updates to WinUI 3.0 Preview 2

feat: Update to WinUI 3.0 Preview 2

---

doc/articles/uno-development/building-uno-macos.md

doc: Update vs4mac build instructions

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TextBlockTests/TextBlockTests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/SimpleText_MaxLines_Different_Font_Size.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/SimpleText_MaxLines_Different_Font_Size.xaml.cs
src/Uno.UI/UI/Xaml/Documents/UIElementTextHelper.wasm.cs

GitHub Issue (If applicable): closes #2751
- Feature
MaxLines is not implemented on wasm
MaxLines is implemented on wasm

feat(TextBlock): Added TextBlock MaxLines implementation for WASM

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.gitignore
build/gitpod/build-wasm.sh
build/gitpod/serve-remote-control.sh
build/gitpod/serve-sampleapp-wasm.sh

Fix Gitpod, Add CodeSpaces support

---

src/Uno.UI.RemoteControl.VS/EntryPoint.cs

GitHub Issue (If applicable): fixes #3601 
- Bugfix
HotReload does not work on systems where the Nuget-Cache is within a directory containing spaces - most probably the username. HotReload cannot start as a dotnet-command cannot run as the command ends at the first space found in the path.
The path to the command is enclosed with paranthesis (") so that it is recognized as one string.

Fix "spaces in username"-issue with HotReload

---

src/Uno.UI/UI/Xaml/Media/Animation/Animators/GPUFloatValueAnimator.iOSmacOS.cs

- Bugfix
macOS apps crash when rapidly clicking on a Button or Checkbox.
macOS apps will __not__ crash when rapidly clicking on a Button or Checkbox.
https://github.com/unoplatform/Uno.Material/issues/229

fix(macOS): crash when finishing animation

---

doc/articles/api-differences.md
doc/articles/native-views.md
doc/articles/toc.yml

Update native views documentation

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockButton/Simple_TextBlockButton.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockButton/Simple_TextBlockButton.xaml.cs
src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml

to unify platforms
- Only uwp has the generic style applied
- All Platforms have the generic style applied

fix(textBlockButtonStyle): Introduced uwp generic TextBlockButtonStyle

---

src/Uno.UI/UI/Xaml/Controls/Image/NativeImage.Android.cs

GitHub Issue (If applicable): fixes #3533
- Bugfix
Images on android do not use the MonochromeColor property, and thus by extension BitmapIcons do not get recolored when changing the Foreground property.
Images are recolored as needed.

fix(Image): images now use the MonochromeColor property on Android

---

src/Uno.UI/Media/PathStreamGeometryContext.cs

None but has been an issue for a while now. Already notified in discord.
- Bugfix
-->
The radialprogressbar from the community toolkit is simply broken. 
It works now.

fix: [macOS] Fix PathStreamGeometryContext Arc support

---

src/Uno.UI.Tests/Windows_UI_Xaml/Given_ThemeResource.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml/FrameworkElement.cs
src/Uno.UI/UI/Xaml/Application.cs
src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.cs
src/Uno.UI/UI/Xaml/Controls/Control/Control.cs
src/Uno.UI/UI/Xaml/Controls/Panel/Panel.iOS.cs
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.cs
src/Uno.UI/UI/Xaml/DependencyObjectStore.cs
src/Uno.UI/UI/Xaml/FrameworkElement.cs
src/Uno.UI/UI/Xaml/ResourceDictionary.cs
src/Uno.UI/UI/Xaml/UIElement.cs
src/Uno.UI/UI/Xaml/Window.cs

Various theme update fixes and tweaks
- Bugfix

Theme update fixes

---

src/SamplesApp/SamplesApp.Shared/App.xaml
src/Uno.UI/UI/Xaml/Controls/AppBar/AppBar.cs
src/Uno.UI/UI/Xaml/Controls/MenuFlyout/MenuFlyoutPresenter.cs
src/Uno.UI/UI/Xaml/Controls/NavigationView/NavigationView.cs
src/Uno.UI/UI/Xaml/Markup/Reader/XamlObjectBuilder.cs
src/Uno.UI/UI/Xaml/ResourceResolver.cs

GitHub Issue (If applicable): https://github.com/unoplatform/private/issues/169
- Bugfix
Application crashes with AOT issues.
- The application no longer crashes with AOT issues.
- Fix iOS theme style issues

fix(reg): PG-AOT issues

---

src/AddIns/Uno.UI.Lottie/LottieVisualSource.wasm.cs

GitHub Issue (If applicable): Fixes #3727
- Bugfix

fix(wasm): Fix invalid path for Lottie assets

---

src/Uno.UI/UI/Xaml/Style/Generic/SystemResources.xaml

Occurs when using Fluent style. The bug occurred because the underlying resource was only defined for Dark theme, causing a null Brush to be set to the Fill.
GitHub Issue (If applicable): fixes #3720
- Bugfix

fix(reg): [WASM] Fix knob disappears in ToggleSwitch on mouseover

---

src/Uno.UI/UI/Xaml/Media/Imaging/BitmapImage.wasm.cs

GitHub Issue (If applicable): Fixes unoplatform/private#171
- Bugfix

fix(wasm): Correctly resolve assets when app is in a subdirectory

---

build/run-template-tests.ps1
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/Uno.ProjectTemplates.Dotnet.csproj
src/Uno.UI/Uno.UI.Wasm.csproj

GitHub Issue (If applicable): fixes https://github.com/unoplatform/private/issues/170
Fix the WinUI 3.0 `dotnet new` template

Fix WinUI template, add build automation

---

doc/articles/interop/wasm-javascript-1.md
doc/articles/interop/wasm-javascript-2.md
doc/articles/interop/wasm-javascript-3.md
src/Uno.UI.Runtime.WebAssembly/Xaml/UIElementWasmExtensions.cs

Fixed compilation errors with most recent version of Uno 3.0+
- ~~[ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).~~

Documentation fixes for Wasm-JS w/Uno 3.0

---

src/Uno.UI/UI/Xaml/DependencyObjectStore.cs

Particularly on Android, updating theme bindings on items inside a ResourceDictionary may trigger callbacks registered by disposed views, causing ObjectDisposedExceptions that will otherwise disrupt further theme updates.
- Bugfix

fix(theme): Catch exceptions from disposed objects when updating themes

---

doc/articles/interop/wasm-javascript-3.md
doc/articles/toc.yml

Minor fixes to documentation for Wasm-JS Integration
- ~~[ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).~~

docs: adjust indentation

---

src/Uno.UI.FluentTheme/XamlControlsResources.cs

- Bugfix
Adjust XamlControlsResources initialization order.

fix(reg): Adjust XamlControlsResources for registered dictionaries

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/PlatformHelper.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGenerator.cs
src/Uno.UI.FluentTheme/Uno.UI.FluentTheme.csproj

fix(reg): [Wasm] Fix default styles not referenced

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/Uno.UI.RuntimeTests/Resources/en-US/Resources.resw
src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.Skia.csproj
src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.Wasm.csproj
src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.csproj
src/Uno.UWP/ApplicationModel/Resources/ResourceLoader.cs

GitHub Issue (If applicable): https://github.com/mono/mono/issues/20256

fix(reg): Adjust assembly loading for Wasm AOT issue

---

doc/articles/get-started.md

Anchors links don't working in the get-started.md
Anchors links are working in the get-started.md

Fix anchors links for get-started.md

---

src/Uno.UI/UI/Xaml/Controls/ItemsControl/ItemsControl.cs
src/Uno.UI/UI/Xaml/Controls/Pivot/Pivot.Properties.cs
src/Uno.UI/UI/Xaml/Controls/Pivot/Pivot.cs

fixes #3809 
- Bugfix
When a Pivot's page changes, the SelectionChanged event is not invoked.
When a Pivot's page changes, the SelectionChanged event will be invoked.

fix: Pivot SelectionChanged not invoked

---

src/Uno.UI/UI/Xaml/Controls/RichTextBlock/RichTextBlock.cs

Add missing attribute. This ensures that the generated docs and Intellisense warnings are correct.

Mark RichTextBlock not implemented

---

doc/articles/features/fluent-styles.md
doc/articles/toc.yml

Also some fixes to the docs TOC

Document Fluent styles upgrade

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/Uno.UI.Tests/App/Xaml/Test_Page_Other.xaml
src/Uno.UI.Tests/Windows_UI_Xaml/Given_ResourceDictionary.cs
src/Uno.UI.Tests/Windows_UI_Xaml/Given_ThemeResource.cs
src/Uno.UI/UI/Xaml/DependencyObjectStore.cs
src/Uno.UI/UI/Xaml/DependencyPropertyDetailsCollection.cs
src/Uno.UI/UI/Xaml/IAdditionalChildrenProvider.cs
src/Uno.UI/UI/Xaml/INeedsThemeBindingUpdates.cs
src/Uno.UI/UI/Xaml/Media/Animation/Storyboard.cs
src/Uno.UI/UI/Xaml/ResourceDictionary.cs
src/Uno.UI/UI/Xaml/ResourceResolver.cs

- fix regression: Propagate resource binding updates top-down when theme changes
- Ensure resources backed by StaticResource aliases update correctly
Note: there are known issues with updates remaining (potentially where animated values are involved).
- Bugfix

Further fixes for runtime theme changing

---

src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.Droid/BlankApp.Droid.csproj
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.UWP/BlankApp.Uwp.csproj
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.Wasm/BlankApp.Wasm.csproj
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.iOS/BlankApp.iOS.csproj
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.macOS/BlankApp.macOS.csproj

n/a
Update DotNet Templates for Prism with reference to Prism 8 preview 2
Targets Preview 1
Targets Preview 2

update Prism 8 - preview 2

---

doc/articles/migrating-apps.md

docs: Updated a lot of typos

---

.github/ISSUE_TEMPLATE/bug-report.md

Add default package list to the bug report template in order to help users to provide more information

docs: Add default package list to bug report

---

doc/articles/getting-started-tutorial-1.md

docs: Corrected Uno Platform branding inconsistencies

---

README.md
doc/articles/get-started.md

Fixes misimpression that older versions of .NET Core must be used

docs: Update .NET Core refs

---

src/Uno.UI/UI/Xaml/Controls/Pivot/Pivot.cs

closes #2370 
- Bugfix
A Pivot bound to a collection of Items via ItemsSource won't show any header.
A Pivot can bound a collection of Items via ItemsSource and headers will show.

fix: Pivot ItemsSource binding

---

src/Uno.UWP/ApplicationModel/Activation/LaunchActivatedEventArgs.cs

- Bugfix
Warnings.
No warnings.

chore: Avoid false-positive warnings for LaunchActivatedEventArgs

---

doc/articles/faq.md

Correct package location of WasmHttpHandler

---

src/Uno.Analyzers.Tests/UnoNotImplementedTests.cs
src/Uno.Analyzers/UnoNotImplementedAnalyzer.cs
src/Uno.Foundation/NotImplementedAttribute.cs

GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/3905
- Bugfix
APIs defined as not implemented partially in netstandard reference APIs are now properly reported as not implemented in libraries.

fix(analyzers): Analyzers may not show the proper status using the reference API

---

src/SolutionTemplate/UnoLibraryTemplate/CrossTargetedLibrary.csproj
src/SolutionTemplate/UnoSolutionTemplate/Droid/UnoQuickStart.Droid.csproj

GitHub Issue (If applicable): Fixes https://github.com/unoplatform/uno/issues/3897, Fixes https://github.com/unoplatform/uno/issues/2464
- Bugfix
- Add documentation a reference to a cross-targeted project does not work
- Intellisense does not report high number of errors in Xamarin.Android

Fix Intellisense does not report high number of errors in Xamarin.Android

---

doc/articles/migrating-from-previous-releases.md

docs: Clarify the Uno.UI.WebAssembly package upgrade

---

src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unolib-crossruntime/UnoCrossRuntimeLib/UnoCrossRuntimeLib.Skia.csproj
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unolib-crossruntime/UnoCrossRuntimeLib/UnoCrossRuntimeLib.Wasm.csproj

- Bugfix
This will ensure that static resources generation uses the proper namespace on all targets.

fix(dotnetnew): Add default root namespace for cross-runtime libraries

---

doc/articles/api-differences.md
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media_Animation/Given_ObjectAnimationUsingKeyFrames.cs
src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.Skia.csproj
src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.Wasm.csproj
src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.csproj
src/Uno.UI.Tests/Windows_UI_Xaml/Given_ThemeResource.cs
src/Uno.UI/UI/Xaml/DependencyObjectStore.Binder.cs
src/Uno.UI/UI/Xaml/DependencyObjectStore.cs
src/Uno.UI/UI/Xaml/DependencyProperty.cs
src/Uno.UI/UI/Xaml/IThemeChangeAware.cs
src/Uno.UI/UI/Xaml/Media/Animation/Storyboard.cs
src/Uno.UI/UI/Xaml/ResourceBindingCollection.cs
src/Uno.UI/UI/Xaml/ResourceResolver.cs

GitHub Issue (If applicable): fixes #3902 
- update properties currently being set by an animation properly
- take precedence into account when storing theme-update bindings
- Bugfix

Further theme change update fixes

---

src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp/.template.config/template.json
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp/.template.config/vs-2017.3.host.json

- Bugfix
Added additional updates based on https://devblogs.microsoft.com/dotnet/net-cli-templates-in-visual-studio, to enable VS 2019 integration of the dotnet new tempaltes/

dotnet new templates updates

---

src/Uno.UI-Android-only.slnf
src/Uno.UI-Skia-only.slnf

GitHub Issue (If applicable): Fixes https://github.com/unoplatform/uno/issues/3950
Adds a missing project in the android filtered solution for clean desktop builds.

fix(slnf): Fix missing project in solution filters

---

.vsts-ci-docs.yml
.vsts-ci.yml

GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/1486
- General changes are building everything, docs included
- Docs only changes are building the docs jobs only.

ci: Split documentation and source build definitions

---

src/Uno.UWP/ApplicationModel/Background/BackgroundAccessStatus.cs
src/Uno.UWP/ApplicationModel/Background/IBackgroundCondition.cs
src/Uno.UWP/ApplicationModel/Background/SystemCondition.cs
src/Uno.UWP/ApplicationModel/Background/SystemConditionType.cs
src/Uno.UWP/ApplicationModel/Background/SystemTriggerType.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Background/BackgroundAccessStatus.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Background/IBackgroundCondition.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Background/SystemCondition.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Background/SystemConditionType.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Background/SystemTriggerType.cs

Encouraged by davidjohnoliver's answer to question in #2079, and quick merge of resulting #3906... Part of #2655 - applicable to all platforms.
- Feature
Not implemented structs for SystemTrigger and Background processing.
Implemented.

feat: AppModel-Background-struct

---

build/Uno.WinUI.Skia.Gtk.targets
build/Uno.WinUI.Skia.Wpf.targets
build/uno.winui.targets
src/AddIns/Uno.UI.Lottie/buildTransitive/Uno.UI.Lottie.targets
src/AddIns/Uno.UI.MSAL/buildTransitive/Uno.UI.MSAL.targets
src/Uno.UI.RemoteControl/buildTransitive/Uno.UI.RemoteControl.targets

- Bugfix
All content files are now copied to the output folder, unless explicitly marked as never copy.

fix(skia): Assets may not be copied properly to the output or publish folder

---

doc/articles/concepts/overview/philosophy-of-uno.md

docs: Update philosophy page with branding and supported platforms

docs: Update philosophy page with branding and supported platforms

---

doc/articles/getting-started-tutorial-1.md

docs: Adjust the getting started documentation for UWP

---

src/Uno.UI/UI/Xaml/Controls/PersonPicture/InitialsGenerator.cs
src/Uno.UI/UI/Xaml/Controls/PersonPicture/PersonPicture.Properties.cs
src/Uno.UI/UI/Xaml/Controls/PersonPicture/PersonPicture.cs
src/Uno.UI/UI/Xaml/Controls/PersonPicture/PersonPictureTemplateSettings.cs

GitHub Issue (If applicable): #3591
- Bugfix
-
Updated PersonPicture to the latest WinUI source, fixed small bugs

chore: Align PersonPicture with latest WinUI source

---

src/Uno.UWP/Devices/Geolocation/Geolocator.Android.cs

GitHub Issue (If applicable): fixes #3992
If we subscribe to PositionChanged before requesting location permissions, then a native error is raised.
If we subscribe to PositionChanged before requesting location permissions, no error is raised. The geolocator will raise the PositionChanged events as needed after the permissions are granted.

fix: [Android] Permit geolocator subscription before permission

---

src/Uno.UI/UI/Xaml/Shapes/Shape.wasm.cs
src/Uno.UI/UI/Xaml/UIElement.wasm.cs

fix(wasm): Some CSS values were not using culture independant serialization

---

src/Uno.UI.Tests/App/Xaml/Test_Page_Other.xaml
src/Uno.UI.Tests/Windows_UI_Xaml/Given_ResourceDictionary.cs
src/Uno.UI/UI/Xaml/ResourceResolver.cs

Matches UWP behavior.
GitHub Issue (If applicable): fixes #3928
- Bugfix

fix(xaml): Make ResourceDictionary.Source lookups case-insensitive

---

doc/articles/get-started-dotnet-new.md

docs: Remove version pinning for dotnet new

---

doc/articles/supported-features.md

docs: Updated branding on features list

---

build/Uno.UI.Build.csproj
src/SolutionTemplate/UnoSolutionTemplate/Skia.Gtk/Program.cs

- Bugfix
- Fix package version in dotnet new templates for Skia WPF Host
- Remove unused Skia head statement

Adjust Skia dotnet new templates

---

src/SolutionTemplate/UnoSolutionTemplate.VISX/UnoPlatformPackage.cs
src/SolutionTemplate/UnoSolutionTemplate.VISX/UnoSolutionTemplate.VISX.csproj
src/SolutionTemplate/UnoSolutionTemplate.Wizard/UnoSolutionTemplate.Wizard.csproj

GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/3991
- Bugfix
A solution for which a project does not load properly may keep visual studio from closing properly.
Solution loading and cancellation is supported.

fix(vsix): Properly support solution unload and timeout on nuget failure

---

src/Uno.UWP/UI/Core/CoreWindow.cs

GitHub Issue (If applicable): #4021 
- Bugfix
The property is implemented on macOS and WebAssembly, and was incorrect flagged as not implemented.

fix: Fix incorrect implemented list for `CoreWindow.PointerCursor`

---

src/Uno.CrossTargetting.props

Duplicate usings can be produced by the WinUI code-transformation step which runs on the CI build. This can produce annoying and hard-to-diagnose CI errors.
Duplicate usings are aesthetically offending only, so this shouldn't pose a risk of uncaught bugs.

chore: Suppress CS0105 'using directive appeared previously'

---

doc/articles/features/windows-ui-xaml-xbind.md
src/SourceGenerators/Uno.UI.SourceGenerators/DependencyObject/DependencyObjectGenerator.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/NameScope.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGenerator.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/Uno.UI.Tests/BinderTests/Given_Binder.cs
src/Uno.UI.Tests/DependencyProperty/Given_DependencyProperty.ManualPropagation.cs
src/Uno.UI.Tests/DependencyProperty/Given_DependencyProperty.cs
src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_OneTime_PocoObject_Static.xaml
src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_OneTime_PocoObject_Static.xaml.cs
src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_OneWay_PocoObject.xaml
src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_OneWay_PocoObject.xaml.cs
src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_StateTrigger.xaml
src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Given_xBind_Binding.cs
src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Given_xBind_Binding_Poco.cs
src/Uno.UI/DataBinding/BindingExpression.cs
src/Uno.UI/Extensions/ViewExtensions.netstd.cs
src/Uno.UI/UI/Xaml/AttachedDependencyObject.cs
src/Uno.UI/UI/Xaml/Data/BindingHelper.cs
src/Uno.UI/UI/Xaml/DependencyObjectExtensions.cs
src/Uno.UI/UI/Xaml/DependencyObjectStore.Binder.cs
src/Uno.UI/UI/Xaml/DependencyObjectStore.cs
src/Uno.UI/UI/Xaml/DependencyProperty.cs
src/Uno.UI/UI/Xaml/FrameworkElement.Skia.cs
src/Uno.UI/UI/Xaml/FrameworkElement.net.cs
src/Uno.UI/UI/Xaml/FrameworkElement.wasm.cs
src/Uno.UI/UI/Xaml/IFrameworkElementImplementation.Android.tt
src/Uno.UI/UI/Xaml/IFrameworkElementImplementation.iOS.tt
src/Uno.UI/UI/Xaml/IFrameworkElementImplementation.macOS.tt

GitHub Issue (If applicable): Fixes https://github.com/unoplatform/uno/issues/3240, Fixes https://github.com/unoplatform/uno/issues/3598, Fixes https://github.com/unoplatform/uno/issues/3597
- Feature
This change adds support for:
- x:Bind to POCO
- `Binding.Update()`
- Removes tree traversal for x:Bind and resources updates

feat(xbind): Add support for x:Bind to POCO, performance improvements

---

src/SourceGenerators/Uno.UI.SourceGenerators/DependencyObject/DependencyObjectGenerator.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs

x:Bind Style and documentation upate

---

src/SamplesApp/Benchmarks.Shared/Benchmarks.Shared.projitems
src/SamplesApp/Benchmarks.Shared/Suite/Windows_UI_Xaml/ResourceDictionaryBench/XamlControlsResourcesCreationBenchmark.cs
src/SamplesApp/Benchmarks.Shared/Suite/Windows_UI_Xaml/ResourceDictionaryBench/XamlControlsResourcesCreationRetrievalBenchmark.cs

test: Add benchmarks for XamlControlsResources

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/PageTests/UnoSamples_Page_Tests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/PageTests/Page_Automated.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/PageTests/Page_Automated.xaml.cs
src/Uno.UI/UI/Xaml/Controls/Page/Page.Android.cs
src/Uno.UI/UI/Xaml/Controls/Page/Page.Skia.cs
src/Uno.UI/UI/Xaml/Controls/Page/Page.cs
src/Uno.UI/UI/Xaml/Controls/Page/Page.iOS.cs
src/Uno.UI/UI/Xaml/Controls/Page/Page.macOS.cs
src/Uno.UI/UI/Xaml/Controls/Page/Page.net.cs
src/Uno.UI/UI/Xaml/Controls/Page/Page.netstdref.cs
src/Uno.UI/UI/Xaml/Controls/Page/Page.wasm.cs

GitHub Issue (If applicable): fixes #1674, fixes https://github.com/unoplatform/uno/issues/2210
- Bugfix
Using the Background on `Page` does not work.
`Page` is the only `UserControl` which renders its own background.

fix(page): Page is the only UserControl which draws its own Background

---

src/Uno.UI.Tests/Windows_Globalization/When_Calendar.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.System.Profile/AnalyticsInfo.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.System.Profile/AnalyticsVersionInfo.cs
src/Uno.UWP/Globalization/Calendar.cs
src/Uno.UWP/System/Profile/AnalyticsInfo.cs
src/Uno.UWP/System/Profile/AnalyticsInfo.skia.cs
src/Uno.UWP/System/Profile/AnalyticsVersionInfo.skia.cs

- Feature
Add implementation for more `Calendar` features.
- [x ] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

Update support for Windows.Globalization.Calendar

---

doc/articles/platform-specific-xaml.md

N/A
Added an additional example.

docs: Add additional example in platform-specific-xaml.md

---

src/Uno.UWP/Devices/Geolocation/Geolocator.Android.cs

https://github.com/unoplatform/uno/issues/4062
When the user first denies the location permission but then grants it while the app is in background (from the device's settings), then the location and permission are not updated.
When the user first denies the location permission but then grants it while the app is in background (from the device's settings), then the location and permission are automatically updated (as is the case on UWP and iOS).

fix: [Android] Geolocator should detect permission when app resumes

---

src/Directory.Build.targets
src/Uno.UI/UI/Xaml/Media/Imaging/WriteableBitmap.skia.cs
src/Uno.UI/Uno.UI.Skia.csproj
src/Uno.UWP/UI/Composition/SkiaCompositionSurface.skia.cs
src/Uno.UWP/Uno.Skia.csproj

GitHub Issue (If applicable): Fixes https://github.com/unoplatform/uno/issues/4059
- Feature
Add support for `WriteableBitmap` for skia

[Skia] Add support for `WriteableBitmap`

---

doc/articles/getting-started-tutorial-1.md
doc/articles/getting-started-tutorial-2.md

Update getting started tutorials with the latest up to date info.

docs: Update getting started tutorials

---

doc/articles/features/fluent-styles.md

The process of updating an existing Uno Platform solution to use Fluent design styles may not be clear.
Clarifies the process as discussed here: https://github.com/unoplatform/uno/pull/3732#discussion_r487345138

docs: Update fluent-styles.md with more details

---

doc/articles/getting-started-tutorial-1.md
doc/articles/getting-started-tutorial-2.md

Getting Started Tutorial touchs-up

docs: Getting Started Tutorial touchs-up

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/PlatformHelper.cs

fix(sourcegen): Correctly evaluate UseWPF

---

src/Uno.UWP/ApplicationModel/Core/CoreApplicationView.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Core/CoreApplicationView.cs
src/Uno.UWP/UI/Core/CoreWindow.cs

GitHub Issue (If applicable): closes #4076
- Feature
Not supported.
Supported.

feat: CoreApplicationView.CoreWindow property

---

build/PackageDiffIgnore.xml
src/Uno.UWP/ApplicationModel/Contacts/ContactAddressKind.cs
src/Uno.UWP/ApplicationModel/Contacts/ContactEmail.cs
src/Uno.UWP/ApplicationModel/Contacts/ContactEmailKind.cs
src/Uno.UWP/ApplicationModel/Contacts/ContactPhone.cs
src/Uno.UWP/ApplicationModel/Contacts/ContactPhoneKind.cs
src/Uno.UWP/ApplicationModel/Contacts/ContactQueryDesiredFields.cs
src/Uno.UWP/ApplicationModel/Contacts/ContactQuerySearchFields.cs
src/Uno.UWP/ApplicationModel/Contacts/ContactStoreAccessType.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Contacts/ContactAddressKind.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Contacts/ContactEmail.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Contacts/ContactEmailKind.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Contacts/ContactPhone.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Contacts/ContactPhoneKind.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Contacts/ContactQueryDesiredFields.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Contacts/ContactQuerySearchFields.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Contacts/ContactStoreAccessType.cs

- Feature
Contacts are not supported at all.
Basic structs (enums, classes) are supported.
Non-controversial part of #2544; all enums and classes that are common to all platforms.
Internal Issue (If applicable): #3045

feat: Contact support struct/enums

---

src/SolutionTemplate/UnoSolutionTemplate/Wasm/UnoQuickStart.Wasm.csproj

- Bugfix
Fixes build issues on macOS and Linux adjusted in recent builds of Uno.Wasm.Bootstrap.

fix: Bump Wasm Bootstrap for uno-app default

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.Telemetry.cs

- Feature
Adjust telemetry to include recent netstandard2.0 flavors.

chore: Adjust telemetry for reference targets

---

doc/articles/get-started-vscode.md

"Getting started with VSCode" is not completed
Update "Getting Started with VsCode" 

docs: Update getting started with VsCode

---

build/ci/.azure-devops-skia-tests.yml
src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.cs
src/Uno.UI/UI/Xaml/FrameworkElement.Interface.Skia.cs
src/Uno.UI/UI/Xaml/UIElement.Pointers.Skia.cs
src/Uno.UI/UI/Xaml/UIElement.Skia.cs

- Bugfix
Items removed from a Panel or UIElement are not getting their visual removed, causing visual issues of lingering content.
Items are removed properly.

fix(skia): Remove inner visual from panel on element removal

---

src/Uno.UWP/Generated/3.0.0.0/Windows.UI.Notifications/NotificationMirroring.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.UI.Notifications/ToastNotification.cs
src/Uno.UWP/UI/Notifications/NotificationMirroring.cs
src/Uno.UWP/UI/Notifications/ToastNotification.cs

- Feature
ToastNotification and NotificationMirroring are not defined.
ToastNotification and NotificationMirroring are defined.
NotificationMirroring- enum
ToastNotification - defined only this fields that are required for Toast to have any sense.
Non-controversial part of #2585

feat: ToastNotification and NotificationMirroring definitions

---

src/Uno.UI/UI/Xaml/Controls/ToolTip/ToolTip.cs
src/Uno.UI/WasmScripts/Uno.UI.js

GitHub Issue (If applicable): fixes https://github.com/unoplatform/nventive-private/issues/25
- Bugfix
Improves tooltip creation performance, fixes iOS 11/12 crash.

fix(tooltip): Fix tooltip popup panel created too early

---

doc/articles/get-started-with-linux.md

docs: Update getting started for linux

---

src/Uno.UI.Runtime.Skia.Gtk/GTK/Extensions/CursorExtensions.cs
src/Uno.UI.Runtime.Skia.Gtk/GTK/GtkHost.cs
src/Uno.UI.Runtime.Skia.Gtk/GTK/GtkUIElementPointersSupport.cs
src/Uno.UI.Runtime.Skia.Tizen/Tizen/TizenUIElementPointersSupport.cs
src/Uno.UI.Runtime.Skia.Wpf/WPF/Extensions/CursorExtensions.cs
src/Uno.UI.Runtime.Skia.Wpf/WPF/WpfUIElementPointersSupport.cs
src/Uno.UWP/UI/Core/CoreWindow.cs
src/Uno.UWP/UI/Core/CoreWindow.skia.cs

GitHub Issue (If applicable): closes #4078 
- Feature
Not supported.
Supported.

feat(PointerCursor): Support for WPF & GTK

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Slider.cs
src/Uno.UI/UI/Xaml/Controls/Slider/Slider.cs
src/Uno.UI/UI/Xaml/DependencyObjectStore.cs
src/Uno.UI/UI/Xaml/DependencyPropertyValuePrecedences.cs
src/Uno.UI/UI/Xaml/ResourceBindingCollection.cs
src/Uno.UI/UI/Xaml/Style/Generic/SystemResources.xaml
src/Uno.UI/UI/Xaml/UIElement.cs

GitHub Issue (If applicable): fixes #3998
- Bugfix

Fix Slider not displaying in ColorPicker

---

src/Uno.UWP/ApplicationModel/Calls/PhoneCallHistoryEntry.cs
src/Uno.UWP/ApplicationModel/Calls/PhoneCallHistoryEntryAddress.cs
src/Uno.UWP/ApplicationModel/Calls/PhoneCallHistoryEntryRawAddressKind.cs
src/Uno.UWP/ApplicationModel/Calls/PhoneCallHistoryStoreAccessType.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Calls/PhoneCallHistoryEntry.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Calls/PhoneCallHistoryEntryAddress.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Calls/PhoneCallHistoryEntryRawAddressKind.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Calls/PhoneCallHistoryStoreAccessType.cs

- Feature
PhoneCallHistory is not implemented at all.
Basic structs of PhoneCallHistory are implemented (for all platforms, although PhoneCallHistory cannot be accessed on iOS).
Uncontroversial part of #2575.

feat: PhoneCallHistory common structs

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/XamlEvent_Leak_TextBox.xaml
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/XamlEvent_Leak_TextBox.xaml.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement_And_Leak.cs

GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/4168
- Other.
No new behavior, adding a TextBox no-leak validation.

test: Add TextBox leak validation runtime test

---

build/Uno.WinUI.Skia.Gtk.targets
build/Uno.WinUI.Skia.Tizen.targets
build/Uno.WinUI.Skia.Wpf.targets

- Bugfix
Deployment from visual studio copies all files, regardless of their copy mode (aligned with the WinUI behavior).

fix(skia): Fix content file deployment from VS

---

src/SourceGenerators/Uno.UI.SourceGenerators/BindableTypeProviders/BindableTypeProvidersGenerationTask.cs
src/Uno.UI/DataBinding/BindableProperty.cs
src/Uno.UI/DataBinding/BindableType.cs
src/Uno.UI/DataBinding/BindingPropertyHelper.cs
src/Uno.UI/DataBinding/IBindableProperty.cs
src/Uno.UI/DataBinding/IBindableType.cs

GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/3867
- Bugfix
- Performance
- Fully qualify the property types, including nested generics
- Reduce the size of generated code by removing generated delegates for get/set of Dependency Propertie

Misc BindableMetadataGenerator improvements

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.cs

GitHub Issue (If applicable): fixes #4165 
- Bugfix
Not working.
Working (at least for my TreeView scenario 😂)

Repair ListView container indices on item insert

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Media/GradientBrushTests/LinearGradientBrush_Tests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/GradientBrushTests/LinearGradientBrush_Change_Stops.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/GradientBrushTests/LinearGradientBrush_Change_Stops.xaml.cs
src/Uno.UI/UI/Xaml/Media/GradientBrush.cs
src/Uno.UI/UI/Xaml/Media/GradientStopCollection.cs
src/Uno.UI/UI/Xaml/Shapes/Shape.cs

Change GradientStopCollection to inherit from DependencyObjectCollection, to invalidate parent view when collection is changed.
- Bugfix

fix: Update Shape.Fill when LinearGradientBrush gradient stops change

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/DragAndDrop/DragDrop_TestPage.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/DragAndDrop/DragDrop_TestPage.xaml.cs
src/Uno.UI/UI/Xaml/DragRoot.cs
src/Uno.UI/UI/Xaml/DragView.cs

Relates to https://github.com/unoplatform/uno/issues/1480. Depends on the drag-n-drop branch. **DO NOT MERGE BY ITSELF**.
- Feature
Drag and drop isn't supported on the mac.
- Drag and drop is supported on macOS (eventually)
- A new DragAndDrop test page is added:
This is still heavily WIP. PR created to help @dr1rrb use the sample app page for development.

WIP: feat(dragdrop): Add macOS support for drag and drop

---

build/ci/.azure-devops-skia-tests.yml
src/SamplesApp/SamplesApp.UITests/RuntimeTests.cs

ci: Restore Skia samples app testing

---

src/SamplesApp/SamplesApp.UITests/SampleControlUITestBase.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/PageTests/UnoSamples_Page_Tests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/PageTests/Page_Update_Background.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/PageTests/Page_Update_Background.xaml.cs
src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.wasm.cs
src/Uno.UI/UI/Xaml/Controls/Page/Page.wasm.cs
src/Uno.UI/UI/Xaml/FrameworkElement.Interface.wasm.cs

- Bugfix
fixes https://github.com/unoplatform/private/issues/201

fix(reg): [WASM] Re-render Page background when SolidColorBrush.Color changes

---

src/Uno.UI.RuntimeTests/Helpers/StyleHelper.cs
src/Uno.UI.RuntimeTests/IntegrationTests/common/TestServices.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/FramePages/Page_With_AppBarButton_Visibility_Bound.xaml
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/FramePages/Page_With_AppBarButton_Visibility_Bound.xaml.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_AppBarButton.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Border.cs
src/Uno.UI/Controls/AppBarButtonRenderer.iOS.cs
src/Uno.UI/Controls/Renderer.cs
src/Uno.UI/FeatureConfiguration.cs
src/Uno.UI/UI/Xaml/Controls/Border/Border.cs

Restore the Uno 2.x behaviour whereby Border.ChildProperty doesn't propagate inherited values (including DataContext) to the property value. The inheritance is handled by the visual tree in the normal case (since Child is always a view).
This restores the ability for the framework to call SetParent() to simulate a different inheritance hierarchy than the actual visual tree configuration, eg for AppBarButton using the native style.
fixes https://github.com/unoplatform/nventive-private/issues/23

fix: Don't propagate DataContext via Border.Child

---

src/Uno.UI-Android-only.slnf
src/Uno.UI-Skia-only.slnf
src/Uno.UI-Wasm-only.slnf
src/Uno.UI-iOS-only.slnf
src/Uno.UI-macOS-only.slnf

Adds missing `Uno.UI.RemoteControl.VS` project in solution filters.

ci: Adjust solution filters to include Uno.UI.RemoteControl.VS

---

doc/articles/get-started-vs.md

docs: Adjust base .NET Core version

---

src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.Skia.cs
src/Uno.UI/UI/Xaml/UIElement.Layout.netstd.cs
src/Uno.UI/UI/Xaml/UIElement.Skia.cs
src/Uno.UWP/UI/Composition/Compositor.Skia.cs
src/Uno.UWP/UI/Composition/Visual.cs

- Bugfix
- ScrollViewer content is now clipped properly
- Zero sized or invisible visuals are not visible anymore

ScrollViewer, Layout Skia updates

---

src/SolutionTemplate/UnoSolutionTemplate.Wizard/UnoSolutionWizard.cs

- Feature
- Set the UWP project and Debug|x86 as the default project and configuration
- Open the getting started 1 as default documentation

feat: Add welcome page for vsix, set UWP as startup project

---

doc/articles/features/working-with-accessibility.md
src/Uno.UI/UI/Xaml/Automation/AutomationProperties.cs

closes #1141 
- Feature
WASM target did not support screen reader capabilities.
WASM target does support A11y screen reader capabilities 

feat(WASM): Enable A11y voice over capabilities

---

doc/articles/uno-fluent-assets.md

Clarify that the Uno FluentUI Assets font should be placed in a `Fonts` folder, in case the old project doesn't have that.

chore: Update Uno Fluent Assets Article

---

doc/articles/features/custom-fonts.md

Clarify and recommend that fonts should get placed in their own Fonts folder within the Resources folder. Also clarify that you should include that folder name in the declaration. (iOS)

chore: Update Custom Fonts Article

---

build/PackageDiffIgnore.xml
src/Uno.UWP/ApplicationModel/Activation/IToastNotificationActivatedEventArgs.cs
src/Uno.UWP/ApplicationModel/Activation/ToastNotificationActivatedEventArgs.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Activation/IToastNotificationActivatedEventArgs.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Activation/ToastNotificationActivatedEventArgs.cs

- Feature
No ToastNotificationActivatedEventArgs implementation.
ToastNotificationActivatedEventArgs implemented.
Two more structs/classes from my #2585 - these structs/classes are defined for all platforms.

feat: ToastNotificationActivatedEventArgs structs for all

---

src/SamplesApp/UITests.Shared/Windows_UI_Xaml/DragAndDrop/DragDrop_TestPage.xaml.cs
src/Uno.UI/UI/Xaml/Media/Imaging/WriteableBitmap.Android.cs
src/Uno.UI/UI/Xaml/Media/Imaging/WriteableBitmap.iOSmacOS.cs
src/Uno.UI/UI/Xaml/Media/Imaging/WriteableBitmap.wasm.cs
src/Uno.UI/UI/Xaml/UIElement.Pointers.cs
src/Uno.UWP/ApplicationModel/DataTransfer/Clipboard.iOS.cs
src/Uno.UWP/ApplicationModel/DataTransfer/Clipboard.macOS.cs
src/Uno.UWP/ApplicationModel/DataTransfer/DataPackage.macOS.cs
src/Uno.UWP/Storage/StorageFile.iOSmacOS.cs
src/Uno.UWP/UI/Popups/MessageDialog.macOS.cs
src/Uno.UWP/Uno.csproj

WIP: feat(dragdrop): Update drag and drop macOS support

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TextBoxTests/TextBoxTests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_CharacterCasing.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_CharacterCasing.xaml.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/CharacterCasing.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/TextBox.cs
src/Uno.UI/UI/Xaml/Controls/CharacterCasing.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.Android.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs
src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.iOS.cs

closes #1574 
- Feature
The CharacterCasing was not implemented 
The CharacterCasing is implemented. A TextBox will follow the CharacterCasing (Upper, Lower, Normal) indicated.

feat(droid): Enable Textbox.CharacterCasing

---

src/SamplesApp/SamplesApp.iOS/SamplesApp.iOS.csproj

- Bugfix
Removes build warnings such as :
```
1>  No way to resolve conflict between "System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Choosing "System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" arbitrarily.
1>  No way to resolve conflict between "System.Collections, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Collections, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Choosing "System.Collections, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" arbitrarily.
1>  No way to resolve conflict between …
```

fix(iOS): Remove warnings when building the iOS head

---

src/Uno.UWP/ApplicationModel/Chat/ChatMessage.cs
src/Uno.UWP/ApplicationModel/Chat/ChatMessageKind.cs
src/Uno.UWP/ApplicationModel/Chat/ChatMessageOperatorKind.cs
src/Uno.UWP/ApplicationModel/Chat/IChatItem.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Chat/ChatMessage.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Chat/ChatMessageKind.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Chat/ChatMessageOperatorKind.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Chat/IChatItem.cs

- Feature
No ChatMessageStore implemented.
Common (= for all platforms) structs/enums/classes related to ChatMessageStore are implemented.
"non-controversial" (and common) parts of #3055. 
#3055 would be rebased, and modified, after this PR would be accepted/merged.

feat: ChatMessage - common structs

---

build/PackageDiffIgnore.xml

Update PackageDiff file for incorrect publication of Uno.UI 3.1.0 package

ci: Adjust for temporary publication of Uno.UI 3.1.0 package

---

doc/articles/native-views.md

docs: Fix formatting in native views

---

build/PackageDiffIgnore.xml
doc/articles/features/windows-devices-haptics.md
doc/articles/toc.yml
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_Devices/Haptics/VibrationDeviceTests.xaml
src/SamplesApp/UITests.Shared/Windows_Devices/Haptics/VibrationDeviceTests.xaml.cs
src/Uno.UI.Runtime.Skia.Tizen/Tizen/Devices/Haptics/TizenSimpleHapticsControllerExtension.cs
src/Uno.UI.Runtime.Skia.Tizen/Tizen/Devices/Haptics/TizenVibrationDeviceExtension.cs
src/Uno.UI.Runtime.Skia.Tizen/Tizen/TizenHost.cs
src/Uno.UWP/Devices/Haptics/KnownSimpleHapticsControllerWaveforms.cs
src/Uno.UWP/Devices/Haptics/SimpleHapticsController.Android.cs
src/Uno.UWP/Devices/Haptics/SimpleHapticsController.Skia.cs
src/Uno.UWP/Devices/Haptics/SimpleHapticsController.cs
src/Uno.UWP/Devices/Haptics/SimpleHapticsController.iOS.cs
src/Uno.UWP/Devices/Haptics/SimpleHapticsController.macOS.cs
src/Uno.UWP/Devices/Haptics/SimpleHapticsController.wasm.cs
src/Uno.UWP/Devices/Haptics/SimpleHapticsControllerFeedback.cs
src/Uno.UWP/Devices/Haptics/VibrationAccessStatus.cs
src/Uno.UWP/Devices/Haptics/VibrationDevice.Android.cs
src/Uno.UWP/Devices/Haptics/VibrationDevice.Skia.cs
src/Uno.UWP/Devices/Haptics/VibrationDevice.cs
src/Uno.UWP/Devices/Haptics/VibrationDevice.iOS.cs
src/Uno.UWP/Devices/Haptics/VibrationDevice.macOS.cs
src/Uno.UWP/Devices/Haptics/VibrationDevice.unsupported.cs
src/Uno.UWP/Devices/Haptics/VibrationDevice.wasm.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Devices.Haptics/KnownSimpleHapticsControllerWaveforms.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Devices.Haptics/SimpleHapticsController.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Devices.Haptics/SimpleHapticsControllerFeedback.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Devices.Haptics/VibrationAccessStatus.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Devices.Haptics/VibrationDevice.cs

GitHub Issue (If applicable): closes #4250 
- Feature
Not supported.
Supported.

feat: VibrationDevice & SimpleHapticsController

---

doc/articles/how-to-host-a-webassembly-app.md

Resolves #1544.
Signed-off-by: Ranadeep Polavarapu <ranadeep@icloud.com>
GitHub Issue (If applicable): #1544.
- Documentation content changes (New documentation)
Adds documentation on how to configure a web server for reverse proxying a WASM application, specifically for Uno.

docs: add WASM config for Apache and Nginx

---

src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props

- Bugfix
Building on non-.NET 5 targets may fail with the following: 
```
7>CSC : error CS8032: An instance of analyzer Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator cannot be created from C:\Users\VssAdministrator\.nuget\packages\uno.ui\3.2.0-dev.79\analyzers\dotnet\cs\Uno.UI.SourceGenerators.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.. 
```
The build does not fail.

fix(reg): Fix incorrect reference of roslyn generators when LangVersion preview is not selected

---

doc/articles/contributing/guidelines/pull-requests.md

docs: Update pull request instructions with squash/rebase

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ButtonTests/UnoSamples_Tests.Button_IsEnabled_Automated.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/DatePickerTests/UnoSamples_Tests.DatePicker.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ListViewTests/UnoSamples_Tests.ListView.cs

GitHub Issue (If applicable): closes #1634, fixes #1632

test: Reenable previously-failing UI tests

---

doc/articles/Uno-UI-Performance.md

Fixed some grammar errors, added some dots etc.
Just fixed some grammar issues and added some missing dots.
- [x ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [x ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [x ] Validated PR `Screenshots Compare Test Run` results.
- [x ] Associated with an issue (GitHub or internal) and uses …

docs: Fix grammar and typos in Uno-UI-Performance

---

doc/articles/features/using-il-linker-webassembly.md
doc/articles/toc.yml
doc/articles/using-uno-ui.md

docs: Add linker configuration documentation

---

build/Uno.WinUI.nuspec
src/Directory.Build.targets

- Bugfix
Fixes UWP duplicate items issues, where generation may fail for complex projects.

chore: Update to Uno.SourceGeneration 3.0.0-dev.18

---

src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.Droid/BlankApp.Droid.csproj
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.UWP/BlankApp.Uwp.csproj
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.Wasm/BlankApp.Wasm.csproj
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.iOS/BlankApp.iOS.csproj
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.macOS/BlankApp.macOS.csproj
src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/global.json

n/a
Updates the Prism template to use the freshly released Prism 8 build
template targets Prism 8 pre 2
template targets Prism 8.0
n/a
n/a

chore: update to Prism 8.0 stable

---

src/SamplesApp/SamplesApp.UITests/Extensions/AppExtensions.cs
src/SamplesApp/SamplesApp.UITests/Extensions/RectExtensions.cs
src/SamplesApp/SamplesApp.UITests/SampleControlUITestBase.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/ScrollViewer_Pointer_Tests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Input/PointersTests/ScrollViewer_PointerMoved.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Input/PointersTests/ScrollViewer_PointerMoved.xaml.cs
src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.Android.cs

- Bugfix
Internal Issue (If applicable): fixes https://github.com/unoplatform/nventive-private/issues/3

[Android] ScrollViewer shouldn't pass PointerMoved to parents

---

doc/articles/get-started-with-linux.md

docs: Adjust Linux templates version

---

doc/toc.yml

Get Started link was not up to date.
Get Started link is now updated

docs: Update Get Started link

---

src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml/Application.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml/ApplicationRequiresPointerMode.cs
src/Uno.UI/UI/Xaml/Application.cs
src/Uno.UI/UI/Xaml/ApplicationRequiresPointerMode.cs

GitHub Issue (If applicable): closes #4371
- Feature
Throws.
Does not throw.

feat: Implement Application.RequiresPointerMode

---

build/ci/.azure-devops-unit-tests.yml
src/Common.targets
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGenerator.cs
src/Uno.UI.FluentTheme/FluentMerge.targets
src/Uno.UI.FluentTheme/Uno.UI.FluentTheme.csproj
src/Uno.UI.Tests.ViewLibrary/Uno.UI.Tests.ViewLibrary.csproj
src/Uno.UI.Tests/Uno.UI.Tests.csproj
src/Uno.UI/Uno.UI.csproj

- ci
Build and run Unit Tests using C# 9.0

ci: Enable Unit Tests validation for C# 9.0

---

build/PackageDiffIgnore.xml
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_XamlRoot.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml/UIElement.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml/XamlRoot.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml/XamlRootChangedEventArgs.cs
src/Uno.UI/UI/Xaml/UIElement.cs
src/Uno.UI/UI/Xaml/Window.cs
src/Uno.UI/UI/Xaml/XamlRoot.cs
src/Uno.UI/UI/Xaml/XamlRootChangedEventArgs.cs

GitHub Issue (If applicable): closes #4356 
- Feature
Not supported.
Supported.

Support for UIElement.XamlRoot

---

src/Uno.UWP/ApplicationModel/Appointments/Appointment.cs
src/Uno.UWP/ApplicationModel/Appointments/AppointmentOrganizer.cs
src/Uno.UWP/ApplicationModel/Appointments/AppointmentProperties.cs
src/Uno.UWP/ApplicationModel/Appointments/AppointmentStoreAccessType.cs
src/Uno.UWP/ApplicationModel/Appointments/FindAppointmentsOptions.cs
src/Uno.UWP/ApplicationModel/Appointments/IAppointmentParticipant.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Appointments/Appointment.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Appointments/AppointmentOrganizer.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Appointments/AppointmentProperties.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Appointments/AppointmentStoreAccessType.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Appointments/FindAppointmentsOptions.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Appointments/IAppointmentParticipant.cs

GitHub Issue (If applicable): #3045
- Feature
No calendar (appointment store) implementation.
Supporting classes/structs for AppointmentStore, valid for every platform, are implemented.
full implementation: IAppointmentParticipant, AppointmentStoreAccessType, AppointmentOrganizer.
Partial implementation: FindAppointmentsOptions, AppointmentProperties, Appointment (only this properties that seems to be "a must").
Non-controversial part of #3087.

feat: Appointment (Calendar) common structs

---

src/Uno.UWP/Devices/Geolocation/Geocircle.cs
src/Uno.UWP/Devices/Geolocation/Geofencing/GeofenceMonitorStatus.cs
src/Uno.UWP/Devices/Geolocation/Geofencing/GeofenceRemovalReason.cs
src/Uno.UWP/Devices/Geolocation/Geofencing/GeofenceState.cs
src/Uno.UWP/Devices/Geolocation/Geofencing/MonitoredGeofenceStates.cs
src/Uno.UWP/Devices/Geolocation/IGeoshape.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Devices.Geolocation.Geofencing/GeofenceMonitorStatus.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Devices.Geolocation.Geofencing/GeofenceRemovalReason.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Devices.Geolocation.Geofencing/GeofenceState.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Devices.Geolocation.Geofencing/MonitoredGeofenceStates.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Devices.Geolocation/Geocircle.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Devices.Geolocation/IGeoshape.cs

- Feature
No support of GeoFencing.
GeoFencing supporting enums/classes are implemented.
As I'm trying to make some app with GeoFencing, I would need these structs ready (to convert my app from UWP to Uno).

feat: GeoFencing - supporting classes/enums

---

build/PackageDiffIgnore.xml
src/Uno.UWP/Foundation/GuidHelper.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Foundation/GuidHelper.cs

GitHub Issue (If applicable): closes #4366 
- Feature
Not supported.
Supported.

feat: Support for GuidHelper

---

src/Uno.UI/Microsoft/UI/Xaml/Controls/ColorPicker/ColorSpectrum.xaml

- Bugfix
Updated to capture bug fixes from win UI.

chore(ColorPicker): Update to WinUI at 607b6de4

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs
src/Uno.UI.Runtime.Skia.Gtk/buildTransitive/Uno.UI.Runtime.Skia.Gtk.targets
src/Uno.UI.Runtime.Skia.Tizen/buildTransitive/Uno.UI.Runtime.Skia.Tizen.targets
src/Uno.UI.Runtime.Skia.Wpf/buildTransitive/Uno.UI.Runtime.Skia.Wpf.targets
src/Uno.UI.Runtime.WebAssembly/buildTransitive/Uno.UI.Runtime.WebAssembly.targets

GitHub Issue (If applicable): fixes #4408 
- Bugfix
Path defined in XAML files may not appear properly. This was introduced when adding #3948 
Path appear properly.

fix(shapes): [Wasm] Fix invalid generation of Shapes caused by missing Wasm detection

---

src/Uno.UI/Controls/CommandBarHelper.iOS.cs

- Refactoring (no functional changes, no API changes)
Using `null!` because forced by the method signature
Method signature was updated to allow `null` values
The method is currently being used only internally within the same helper class hence the no breaking changes.

feat(iOS): Update method signature for null

---

build/ci/.azure-devops-ios-tests-run.yml

ci: Apply workaround for https://github.com/actions/virtual-environments/issues/1932

---

src/Uno.Foundation.Runtime.WebAssembly/Interop/NetCoreJSInterop.cs
src/Uno.Foundation.Runtime.WebAssembly/Interop/PlatformHelper.cs
src/Uno.Foundation.Runtime.WebAssembly/Interop/Runtime.wasm.cs
src/Uno.Foundation.Runtime.WebAssembly/Interop/WebAssembly.Runtime.cs

- Feature
Adjusts the compatibility of the JS Interop with newer versions of the runtime.

feat: [Wasm] Adjust netcore compatiblity

---

src/Uno.UWP/Devices/Geolocation/PositionSource.cs
src/Uno.UWP/Generated/3.0.0.0/Windows.Devices.Geolocation/PositionSource.cs

- Feature
No enum implemented.
Enum implemented.
Very simple enum, missing from my previous geolocator-related PRs.

feat: Geolocation.PositionSource enum

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml/ClippingTests/ClippingTests_Tests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/Clipping/CornerRadiusControls.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml/Clipping/CornerRadiusControls.xaml.cs
src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.Android.cs
src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.Skia.cs
src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.Uno.cs
src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.cs
src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.iOS.cs
src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.macOS.cs
src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.wasm.cs
src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewerExtensions.cs
src/Uno.UI/UI/Xaml/Controls/ToolTip/ToolTip.xaml

Closes https://github.com/unoplatform/Uno.Gallery/issues/37
Closes https://github.com/unoplatform/Uno.Gallery/issues/55
Added new UI Tests for corner radius

New UI Tests for CornerRadius

---

build/ci/.azure-devops-windows.yml

ci: Disable PR nuget feed

---

doc/articles/get-started-wizard.md
src/SolutionTemplate/UnoSolutionTemplate.Wizard/UnoSolutionWizard.cs

GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/4321

docs: Add wizard getting started documentation

---

src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlGlobalStaticResourcesMap.cs

If the shared project Import was placed after the Xamarin.iOS.CSharp.targets import, the AssignLinkMetadata task was not setting the Link metadata for shared project items correctly, causing confusion and consternation. This ensures the task will always be run. (XF does the same: https://github.com/xamarin/Xamarin.Forms/commit/bf86534eafcef76988032bc422a6c1d35b65ffd2)
- Bugfix
fixes https://github.com/unoplatform/nventive-private/issues/47

fix(resourcedictionary): Fix Source path not registered correctly

---

src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/xamarinforms-wasm/UnoXFQuickStart.Wasm/UnoXFQuickStart.Wasm.csproj

chore: Update to Uno.Xamarin.Forms 4.8.0-uno.1322

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TimePickerTests/UnoSamples_Tests.TimePicker.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TimePicker/TimePicker_Header.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TimePicker/TimePicker_Header.xaml.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/TimePicker.cs
src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePicker.cs

GitHub Issue (If applicable): closes #4480
- Feature
Not supported.
Supported.

TimePicker Header & HeaderTemplate

---

build/Uno.WinUI.RemoteControl.nuspec
src/Directory.Build.targets

- Bugfix
Fixes hot reload for net5 target

chore: Update to latest Uno.Wasm.WebSockets

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/SourceGenerators/XamlGenerationTests/CustomMarkupExtensions.xaml
src/SourceGenerators/XamlGenerationTests/CustomMarkupExtensions.xaml.cs
src/Uno.UI.Tests/App/Xaml/Test_MarkupExtension.xaml
src/Uno.UI.Tests/App/Xaml/Test_MarkupExtension.xaml.cs
src/Uno.UI.Tests/Windows_UI_Xaml/MarkupExtensionTests/Given_MarkupExtension.cs

GitHub Issue (If applicable): fixes #2918
- Bugfix
- Feature
Allows the use of a custom MarkupExtension only with fullname
Allows the use of a custom MarkupExtension with or without the suffix "Extension"
Example:
```csharp
public class SimpleExtension : MarkupExtension
{
protected override object ProvideValue()
{
return null;
}
}
```
you can use:
```xaml
<TextBlock Text="{l:SimpleExtension}"/>
```
or
```xaml
<TextBlock Text="{l:Simple}"/>
```

Allows the use of a custom MarkupExtension with or without the suffix "Extension"

---

src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/NumberBoxTests/MUX_Test.xaml
src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/NumberBoxTests/MUX_Test.xaml.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/NumberBox/NumberBox.Properties.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/NumberBox/NumberBox.cs

GitHub Issue (If applicable): part of #3851
- Feature
Header and HeaderTemplate not supported
Header and HeaderTemplate supported

feat(NumberBox): Header and HeaderTemplate support

---

src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls.Maps/MapInputEventArgs.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls.Maps/MapStyle.cs
src/Uno.UI/UI/Xaml/Maps/MapInputEventArgs.cs
src/Uno.UI/UI/Xaml/Maps/MapStyle.cs

- Feature
not implemented.
implemented.
Only for less UNO0001 warnings in my apps :)

feat: MapStyle and MapInputEventArgs

---

build/PackageDiffIgnore.xml
src/Uno.UI/Graphics/IGeometrySource2D.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/ItemsSourceView.cs
src/Uno.UWP/UI/Composition/CompositionClip.cs
src/Uno.UWP/UI/Composition/RectangleClip.cs
src/Uno.UWPSyncGenerator/Generator.cs
src/Uno.UWPSyncGenerator/Program.cs

refactor: Adjust WinUI support

---

doc/articles/controls/map-control-support.md
src/SamplesApp/SamplesApp.Droid/Properties/AndroidManifest.xml
src/SamplesApp/SamplesApp.Shared/App.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MapPresenter/MapControl.xaml.cs
src/Uno.UI.Maps/GoogleMapView.Android.cs
src/Uno.UI.Maps/MapPresenter.Android.cs
src/Uno.UI.Maps/MapPresenter.cs
src/Uno.UI.Maps/MapPresenter.iOS.cs
src/Uno.UI.Maps/Uno.UI.Maps.csproj
src/Uno.UI.Maps/themes/Generic.xaml
src/Uno.UI.Maps/themes/MapResources.xaml
src/Uno.UI.Maps/themes/MapResources.xaml.cs
src/Uno.UI.Toolkit/MapResources.cs
src/Uno.UI/UI/Xaml/Maps/MapControl.cs

GitHub Issue (If applicable): #3741
Updates to MapControl for breaking changes introduced by Uno 3.0.
- Bugfix

Fix MapControl support for Uno 3.0

---

doc/articles/get-started-rider.md

Fixes #4544 
Added more precise information to use Rider on different platforms.

doc(rider): Added matrix of supported platforms for Rider

---

doc/articles/get-started-wizard.md

docs: Update wizard doc to include InitializeComponent issue

---

src/SourceGenerators/System.Xaml/System.Xaml/ParsedMarkupExtensionInfo.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.Reflection.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/Uno.UI.Tests/App/Behaviors/AttachedPropertiesBehavior.cs
src/Uno.UI.Tests/App/Xaml/Test_MarkupExtension.xaml
src/Uno.UI.Tests/Windows_UI_Xaml/MarkupExtensionTests/Given_MarkupExtension.cs

GitHub Issue (If applicable): fixes #4528
Take the namespace into account when testing for a MarkupExtension declaration in Xaml. This brings behavior closer to UWP, and fixes a regression in Uno 3.2 where usage of a different type could be mistaken as the shortened form of a markup extension (eg FontIcon for FontIconExtension).
- Bugfix

fix(xaml): Resolve markup extensions in Xaml correctly

---

doc/templates/uno/styles/main.js

Fix for nav menu in doc

---

.vsts-ci.yml
build/android-uitest-run.sh
build/ci/.azure-devops-android-tests.yml
build/ci/.azure-devops-docs.yml
build/ci/.azure-devops-ios-tests-run.yml
build/ci/.azure-devops-ios-tests.yml
build/ci/.azure-devops-macos.yml
build/ci/.azure-devops-project-template-tests.yml
build/ci/.azure-devops-samplesapp-uitests-build.yml
build/ci/.azure-devops-screenshot-compare.yml
build/ci/.azure-devops-skia-tests.yml
build/ci/.azure-devops-uap.yml
build/ci/.azure-devops-unit-tests.yml
build/ci/.azure-devops-wasm-cs9-preview-validation.yml
build/ci/.azure-devops-wasm-uitests.yml
build/ci/.azure-devops-windows.yml
build/ios-uitest-run.sh
build/run-automated-uitests.sh

ci: Adjust UI Tests pipeline retries to only failed tests

---

src/Uno.UI/UI/Xaml/Maps/MapControl.cs

GitHub Issue (If applicable): #3741

chore(mapcontrol): Add warning when MapControl template not found

---

src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_Devices/OrientationTests.xaml
src/SamplesApp/UITests.Shared/Windows_Devices/OrientationTests.xaml.cs
src/Uno.UWP/Devices/Sensors/SimpleOrientationSensor.Android.cs

- Bugfix
Currently in android 7/7.1 the orientation sensor takes very long (5+ seconds) to detect an orientation change.
It no longer takes long to change orientation. Android 7 devices are now forced to use accelerometer instead of the gravity sensor.
fixes https://github.com/unoplatform/nventive-private/issues/100

fix(OrientationSensor): fixed orientation sensor not working properly with android versions older than oreo

---

doc/articles/faq.md

docs: Update FAQ

---

src/Uno.UI.Tests/Windows_UI_XAML_Controls/Frame/Given_Frame.cs
src/Uno.UI/UI/Xaml/Controls/Frame/Frame.cs

GitHub Issue (If applicable): fixes #4587
- Feature
`SourcePageType` & `CurrentSourcePageType`  return null.
`SourcePageType` & `CurrentSourcePageType` return correct type, added unit tests.

feat(Frame): SourcePageType & CurrentSourcePageType 

---

doc/articles/features/working-with-accessibility.md

docs: Update working-with-accessibility.md

---

doc/articles/get-started-wizard.md

docs: Tweak wizard page title

---

src/Uno.Foundation.Runtime.WebAssembly/Interop/TSInteropMarshaller.wasm.cs
src/Uno.Foundation.Runtime.WebAssembly/Uno.Foundation.Runtime.WebAssembly.csproj
src/Uno.UI/UI/Xaml/DependencyPropertyDescriptor.cs
src/Uno.UI/WasmScripts/Uno.UI.js
src/Uno.UI/ts/WindowManager.ts

- Bugfix
Fix invalid interop type used when registering for pointer events.

fix(wasm): Invalid deserialization in registerPointerEventsOnView

---

src/AddIns/Uno.UI.Lottie/Uno.UI.Lottie.Skia.csproj
src/AddIns/Uno.UI.Lottie/Uno.UI.Lottie.Wasm.csproj
src/AddIns/Uno.UI.Lottie/Uno.UI.Lottie.csproj
src/AddIns/Uno.UI.MSAL/Uno.UI.MSAL.Skia.csproj
src/AddIns/Uno.UI.MSAL/Uno.UI.MSAL.Wasm.csproj
src/AddIns/Uno.UI.MSAL/Uno.UI.MSAL.csproj
src/Uno.UI.Maps/Uno.UI.Maps.csproj
src/Uno.UI.RemoteControl.Host/Uno.UI.RemoteControl.Host.csproj
src/Uno.UI.RemoteControl/Uno.UI.RemoteControl.csproj
src/Uno.UI.Toolkit/Uno.UI.Toolkit.csproj

- Bugfix
When building with `UnoNugetOverrideVersion` enabled on macOS there are some errors trying to create some directories.
With `UnoNugetOverrideVersion` enabled there is no error at building time on macOS.
**Error log before the fix**
```
"/Users/apineda/code/uno/uno/src/Uno.UI-vs4mac-iOS-only.sln" (default target) (1:2) ->
"/Users/apineda/code/uno/uno/src/Uno.UI.Toolkit/Uno.UI.Toolkit.csproj" (default target) (9:14) ->
"/Users/apineda/code/uno/uno/src/Uno.UI.Toolkit/Uno.UI.Toolkit.csproj" (Build target) (9:16) ->
(_UnoToolkitOverrideNuget target) -> 
/Users/apineda/code/uno/uno/src/Uno.UI.Toolkit/Uno.UI.Toolkit.csproj(124,3): error MSB3191: Unable …
```

chore: Update Target Nuget folder

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/Uno.UI.RuntimeTests/IntegrationTests/common/TestServices.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/CounterGrid.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ItemsControl.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.Items.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/GroupingObservableCollection.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/ListViewPages/ListViewCollectionViewSourcePage.xaml
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/ListViewPages/ListViewCollectionViewSourcePage.xaml.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/TestsResources.xaml
src/Uno.UI.Tests/Windows_UI_Xaml/Controls/When_xName_In_Dictionary_Reference_Equality.xaml
src/Uno.UI.Tests/Windows_UI_Xaml/Controls/When_xName_In_Dictionary_Reference_Equality.xaml.cs
src/Uno.UI.Tests/Windows_UI_Xaml/Given_ResourceDictionary.cs
src/Uno.UI/UI/Xaml/Controls/ItemCollection.cs
src/Uno.UI/UI/Xaml/Controls/ItemsControl/ItemsControl.cs
src/Uno.UI/UI/Xaml/Data/CollectionView.cs

GitHub Issue (If applicable): fixes #1045 , fixes #2347
- Feature
- Bugfix

 feat(itemscontrol): Sync Items with ItemsSource

---

doc/articles/uno-development/troubleshooting-source-generation.md
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.Reflection.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/Uno.UI.Runtime.WebAssembly/Uno.UI.Runtime.WebAssembly.csproj
src/Uno.UI.Tests/Windows_UI_Xaml/Controls/When_NonFrameworkElement_Event.xaml
src/Uno.UI.Tests/Windows_UI_Xaml/Controls/When_NonFrameworkElement_Event.xaml.cs
src/Uno.UI.Tests/Windows_UI_Xaml/Given_NonFrameworkElement_TopLevel.cs

GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/4429
- Bugfix
- Feature
- Fixes top-level properties for non-framework element
- Adds an msbuild property to debug generators with source link

fix: Adjust non-FrameworkElement support for top-level properties generation

---

src/Uno.Foundation/Point.cs
src/Uno.Foundation/Size.cs
src/Uno.UI.RuntimeTests/Extensions/FrameworkElementExtensions.cs
src/Uno.UI.RuntimeTests/Extensions/RectExtensions.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Flyout.cs
src/Uno.UI/UI/LayoutHelper.cs

Flyout placement was using target.RenderSize, which is appropriate in most cases but not for TextBlock. Use ActualWidth/Height instead which gives results matching UWP for TextBlock.
GitHub Issue (If applicable): #3582
- Bugfix

fix(flyout): [WASM/Skia] Place Flyout correctly when attached to TextBlock

---

.vsts-ci.yml
build/ci/.azure-devops-android-tests.yml
build/ci/.azure-devops-ios-tests.yml
build/ci/templates/ios-build-select-version.yml
src/SamplesApp/SamplesApp.UITests/SamplesApp.UITests.csproj
src/Uno.UI/FeatureConfiguration.cs
src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePicker.md
src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePickerSelector.cs
src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePickerSelector.iOS.cs
src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePicker.md
src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerSelector.cs
src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerSelector.iOS.cs
src/Uno.UI/UI/Xaml/Media/ImageSource.macOS.cs
src/Uno.UI/UI/Xaml/Style/Generic/Generic.Native.xaml

- Feature
Apps running on iOS14 devices always display "old" DatePicker and TimePicker
Apps running on iOS14 devices will be able to use the newly added DatePicker 
https://github.com/unoplatform/nventive-private/issues/41

feat(iOS): Enable iOS14 Pickers

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/FlyoutTests/UnoSamples_Tests.Flyout.cs
src/Uno.UI.RuntimeTests/Helpers/NumberAssert.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Flyout.cs
src/Uno.UI/UI/Xaml/Controls/Flyout/FlyoutBase.PreferredJustification.cs
src/Uno.UI/UI/Xaml/Controls/Flyout/FlyoutBase.cs
src/Uno.UI/UI/Xaml/Controls/Flyout/FlyoutPlacementMode.cs
src/Uno.UI/UI/Xaml/Controls/Popup/PlacementPopupPanel.cs

fixes #3582
fixes #4629 
closes #4659 (superset of that PR)
- Implement all `FlyoutPlacementMode` options
- fix fallback application
- Feature
- Bugfix

Additional Flyout placement modes

---

doc/articles/get-started-vs.md
doc/articles/get-started-vscode.md
doc/articles/get-started-vsmac.md
doc/articles/get-started-with-linux.md
doc/articles/toc.yml
src/SolutionTemplate/UnoSolutionTemplate/Skia.Gtk/UnoQuickStart.Skia.Gtk.csproj

feat: Update GTK template to .NET 5

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_NavigationView.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.iOS.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelGenerator.managed.cs

List was not getting properly refreshed, leading to undefined behavior, including containers for previous items incorrectly being reused. In the case of NavigationView, this was causing a crash.
GitHub Issue (If applicable): fixes #4661
- Bugfix

fix(listview): Fix bad state when manipulating ListView.Items

---

build/Uno.WinUI.nuspec
src/Directory.Build.targets

GitHub Issue (If applicable): Fixes https://github.com/unoplatform/uno/issues/4621
- Bugfix

chore: Update Uno.Core to 2.1.0

---

src/SamplesApp/Benchmarks.Shared/Benchmarks.Shared.projitems
src/SamplesApp/Benchmarks.Shared/Controls/BenchmarkDotNetControl.xaml
src/SamplesApp/Benchmarks.Shared/Controls/BenchmarkDotNetControl.xaml.cs
src/SamplesApp/Benchmarks.Shared/Controls/BenchmarkUIHost.cs
src/SamplesApp/Benchmarks.Shared/Suite/Windows_UI_Xaml_Controls/UIElementPerf/LoadUnloadPerf.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement_And_Leak.cs
src/Uno.UI.Tests/DependencyProperty/Given_DependencyObject.cs
src/Uno.UI/FeatureConfiguration.cs
src/Uno.UI/UI/Xaml/Application.cs
src/Uno.UI/UI/Xaml/ApplicationHelper.cs
src/Uno.UI/UI/Xaml/DependencyObjectExtensions.cs
src/Uno.UI/UI/Xaml/DependencyObjectStore.cs
src/Uno.UI/UI/Xaml/FrameworkElement.Interface.net.cs
src/Uno.UI/UI/Xaml/FrameworkElement.cs
src/Uno.UI/UI/Xaml/FrameworkElement.netstd.cs
src/Uno.UI/UI/Xaml/ResourceDictionary.cs

GitHub Issue (If applicable): https://github.com/unoplatform/nventive-private/issues/102
- Refactoring
- Visual Tree traversal is improved by using parent weak reference materialization while UIElement instances are materialized
- Improvement in current applied theme selection
- Improve tree traversal algorithm by reducing type checking

perf: Improve performance by creating temporary hard references in DependencyObjectStore

---

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs
src/Uno.UI/UI/Xaml/Controls/Primitives/Selector.cs

GitHub Issue (If applicable): fixes #4652
- Bugfix

fix(selector): Support setting SelectedValue when SelectedValuePath is set

---

src/Uno.UI.RuntimeTests/IntegrationTests/common/TestServices.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ContentControl.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/TestsResources.xaml
src/Uno.UI/UI/Xaml/Controls/ContentControl/ContentControl.cs
src/Uno.UI/UI/Xaml/DependencyObjectExtensions.cs

GitHub Issue (If applicable): fixes #4626
- Bugfix

fix(contentcontrol): [macOS/iOS] Support binding DataContext in ContentTemplate

---

src/Uno.UI.FluentTheme/FluentMerge.targets
src/Uno.UI.FluentTheme/Resources/PriorityDefault/TabView.xaml
src/Uno.UI.FluentTheme/Resources/PriorityDefault/TabView_themeresources.xaml
src/Uno.UI.FluentTheme/themeresources.xaml
src/Uno.UI/Microsoft/UI/Xaml/Controls/TabView/TabView.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/TabView/TabView.xaml
src/Uno.UI/Microsoft/UI/Xaml/Controls/TabView/TabViewListView.cs
src/Uno.UI/UI/Xaml/Controls/ItemsStackPanel/ItemsStackPanelLayout.iOS.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.iOSAndroid.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.Android.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.cs
src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.iOS.cs

GitHub Issue (If applicable): #3874 
- Feature
Not supported
Supported. **iOS not working properly yet.**

TabView support on Android, macOS and iOS

---

src/SamplesApp/SamplesApp.UITests/Microsoft_UI_Xaml_Controls/RadioButtonsTests/Given_RadioButtons.cs
src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/RadioButtonsTests/RadioButtonsBasicPage.xaml
src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/RadioButtonsTests/RadioButtonsBasicPage.xaml.cs
src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/RadioButtonsTests/RadioButtonsFocusPage.xaml
src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/RadioButtonsTests/RadioButtonsFocusPage.xaml.cs
src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/RadioButtonsTests/RadioButtonsPage.xaml
src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/RadioButtonsTests/RadioButtonsPage.xaml.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/RadioButtons/RadioButtonTests.cs
src/Uno.UI/Helpers/WinUI/SharedHelpers.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/RadioButtons/ColumnMajorUniformToLargestGridLayout.Properties.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/RadioButtons/ColumnMajorUniformToLargestGridLayout.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/RadioButtons/RadioButton.xaml
src/Uno.UI/Microsoft/UI/Xaml/Controls/RadioButtons/RadioButtons.Header.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/RadioButtons/RadioButtons.Properties.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/RadioButtons/RadioButtons.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/RadioButtons/RadioButtons.xaml
src/Uno.UI/Microsoft/UI/Xaml/Controls/RadioButtons/RadioButtonsElementFactory.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/RadioButtons/RadioButtonsTestHooks.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/RadioButtons/RadioButtons_themeresources.xaml
src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/ItemTemplateWrapper.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/ViewportManagerWithPlatformFeatures.cs

- Feature
Not supported.
Supported.

WinUI RadioButtons

---

src/Uno.UI/Microsoft/UI/Xaml/Controls/TabView/TabView.cs

GitHub Issue (If applicable): #3874 
Methods are not public.
Methods are public as per WinUI.

fix(TabView): Surface container-related methods

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.Reflection.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/Uno.UI.Tests/Windows_UI_Xaml/EventsTests/Controls/FrameworkElement_DataTemplate_Event_OtherControl.xaml
src/Uno.UI.Tests/Windows_UI_Xaml/EventsTests/Controls/FrameworkElement_DataTemplate_Event_OtherControl.xaml.cs
src/Uno.UI.Tests/Windows_UI_Xaml/EventsTests/Controls/FrameworkElement_DataTemplate_Event_OtherControl_DataTemplate.xaml
src/Uno.UI.Tests/Windows_UI_Xaml/EventsTests/Controls/FrameworkElement_DataTemplate_Event_OtherControl_DataTemplate.xaml.cs
src/Uno.UI.Tests/Windows_UI_Xaml/EventsTests/Given_FrameworkElement_Event.cs
src/Uno.UI/UI/Xaml/ControlTemplate.cs
src/Uno.UI/UI/Xaml/Controls/ItemsPanelTemplate.cs
src/Uno.UI/UI/Xaml/DataTemplate.cs
src/Uno.UI/UI/Xaml/FrameworkTemplate.cs
src/Uno.UI/UI/Xaml/FrameworkTemplatePool.cs

GitHub Issue (If applicable): Fixes https://github.com/unoplatform/uno/issues/4724
- Bugfix
Code-behind events defined in a DataTemplate are now raised properly, even if the visual parent is not the control that defined the DataTemplate.

fix(events): Fix XAML event registration in DataTemplate

---

build/PackageDiffIgnore.xml
src/Uno.UI/Microsoft/UI/Xaml/Controls/InfoBar/InfoBar.xaml
src/Uno.UI/Microsoft/UI/Xaml/Controls/InfoBar/InfoBarPanel.Properties.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/InfoBar/InfoBarPanel.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/InfoBar/InfoBar_themeresources.xaml

GitHub Issue (If applicable): #4426 
- Feature
`InfoBar` is at initial version from WinUI.
`InfoBar` is at latest WinUI version.

InfoBar: Update to latest WinUI

---

build/ci/.azure-devops-ios-tests.yml
build/ios-uitest-run.sh
build/local-ios-uitest-run.sh
src/SamplesApp/SamplesApp.UITests/RuntimeTests.cs
src/SamplesApp/SamplesApp.UITests/TestFramework/AutoRetry.cs
src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.cs
src/SamplesApp/SamplesApp.iOS/SamplesApp.iOS.csproj
src/SamplesApp/SamplesApp.macOS/SamplesApp.macOS.csproj
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Button/Buttons.xaml.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/ResourceOwner.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement_And_Leak.cs
src/Uno.UI/DataBinding/BinderReferenceHolder.cs
src/Uno.UI/UI/Xaml/Controls/ItemCollection.cs
src/Uno.UI/UI/Xaml/Controls/ItemsControl/ItemsControl.cs
src/Uno.UI/UI/Xaml/Controls/Popup/Popup.iOS.cs
src/Uno.UI/UI/Xaml/Controls/Popup/PopupPanel.cs
src/Uno.UI/UI/Xaml/Data/ElementNameSubject.cs
src/Uno.UI/UI/Xaml/FrameworkElementHelper.cs
src/Uno.UI/UI/Xaml/FrameworkTemplatePool.cs
src/Uno.UI/UI/Xaml/ResourceDictionary.cs
src/Uno.UI/UI/Xaml/Setter.cs
src/Uno.UI/UI/Xaml/TargetPropertyPath.cs
src/Uno.UI/UI/Xaml/WeakResourceInitializer.cs

- Bugfix
- Ensure that `ItemCollection` is unregistering from `ItemSource`
- Use weak references for `ElementNameSubject` and `TargetPropertyPath`
- Pin the generated instance for `DataTemplate` holder for `x:Name` to allow for `ElementNameSubject` and `TargetPropertyPath` weak references.
- Improve the memory leak runtime tests by tracking children instances and properties
- Fix FrameworkTemplate resource owner leak (explicit weak propagation through FrameworkTemplate)
- Move iOS RuntimeTests to their own job to reduce timeout impact

Misc memory leaks fixes

---

src/SamplesApp/SamplesApp.Skia.Tizen/SamplesApp.Skia.Tizen.csproj
src/SolutionTemplate/UnoSolutionTemplate/Skia.Tizen/UnoQuickStart.Skia.Tizen.csproj
src/global.json

Removes multiple inclusions warnings

ci: Bump MSBuild.SDK.Extras to 3.0.22

---

src/SamplesApp/SamplesApp.UITests/RuntimeTests.cs
src/SamplesApp/SamplesApp.UITests/TestFramework/AutoRetry.cs
src/SourceGenerators/Uno.UI.SourceGenerators/DependencyObject/DependencyPropertyGenerator.cs
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/ResourceOwner.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/_Tracing.cs

Adjust tests retry count to be 3 for all tests, except RuntimeTests. RuntimeTests cannot be retried individually and do not benefit from larger retries. Automatic retry from the CI pipeline is better suited.

Adjust RuntimeTests retry count

---

build/ci/.azure-devops-skia-tests.yml
src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/Repeater/PhasingTests.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement_And_Leak.cs
src/Uno.UI/UI/Xaml/Style/Generic/SystemResources.xaml

GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/4747
- Bugfix
```
warn: Uno.UI.ResourceResolver[0]
Couldn't statically resolve resource ScrollViewerSeparatorContractDuration
warn: Uno.UI.ResourceResolver[0]
Couldn't statically resolve resource ScrollViewerSeparatorContractBeginTime
warn: Uno.UI.ResourceResolver[0]
Couldn't statically resolve resource ScrollViewerSeparatorExpandDuration
warn: Uno.UI.ResourceResolver[0]
Couldn't statically resolve resource ScrollViewerSeparatorExpandBeginTime
warn: Uno.UI.ResourceResolver[0]
Couldn't statically resolve resource ScrollViewerSeparatorExpandBeginTime
warn: Uno.UI.ResourceResolver[0]
Couldn't statically resolve resource ScrollViewerSeparatorContractBeginTime
```
No more …

ScrollViewer, RuntimeTests fixes

---

build/ci/.azure-devops-android-tests.yml
src/SamplesApp/SamplesApp.UWP/SamplesApp.UWP.csproj
src/SourceGenerators/Uno.UI.SourceGenerators/RemoteControl/RemoteControlGenerator.cs
src/Uno.UI.BindingHelper.Android/Uno.UI.BindingHelper.Android.csproj
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement_And_Leak.cs

Applied workaround to build Android sample app only, and not the full solution.
This change reduces 20 minutes of build time for the android samples.

Adjust the Android UI Tests build

---

src/AddIns/Uno.UI.Lottie/ts/Uno.UI.Lottie.ts
src/Uno.UI/Uno.UI.Wasm.csproj
src/Uno.UI/Uno.UI.csproj

Addressing comments from https://github.com/unoplatform/uno/pull/4788
- Addressing PR Comments

Determinate ProgressRing: Address PR comments

---

src/SolutionTemplate/UnoSolutionTemplate/macOS/UnoQuickStart.macOS.csproj

Added missing Properties folder and AssemblyInfo.cs file to macOS template

---

src/SolutionTemplate/UnoSolutionTemplate/UWP/UnoQuickStart.Uwp.csproj

as long as MSBuildExtras 3.0.22 supports it
- Other... Please describe: dependency update

feat(templates): Updated Microsoft.NETCore.UniversalWindowsPlatform to 6.2.11

---

src/SolutionTemplate/UnoSolutionTemplate/UWP/UnoQuickStart.Uwp.csproj

GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/4808
- Bugfix
Bumps Uno.Core dependency in Uno.UI UWP project template to avoid conflicts.

fix(templates): Bump Uno.Core to 2.1 in UWP template

---

.vsts-ci.yml

Use Azure Devops Windows2019-20201210-0 scaled set to allow for C# 9.0 builds.

ci: Upgrade to ScaledSet Windows2019-20201210-0

---

src/SamplesApp/SamplesApp.UITests/Microsoft_UI_Xaml_Controls/ProgressRingTests/Given_DeterminateProgressRings.cs
src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/ProgressRing/WinUIDeterminateProgressRing.xaml
src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/ProgressRing/WinUIProgressRing_Slider.xaml
src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/ProgressRing/WinUIProgressRing_Slider.xaml.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems

Add UI tests for Determinate ProgressRing

---

src/SamplesApp/SamplesApp.Shared/App.xaml.cs
src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/NavigationViewTests/NavigationViewBasicPage.xaml
src/Uno.Foundation/Metadata/ApiInformation.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_UIElement.TransformToVisual.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_UIElement.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/NavigationView/NavigationView.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/NavigationView/NavigationViewItemPresenter.cs
src/Uno.UI/UI/Xaml/UIElement.Layout.netstd.cs

GitHub Issue (If applicable): fixes #4794 fixes #4809 
- Bugfix
- Selected item is not indicated after load
- NavigationView crashes on Skia when on the main page due to layout loop
- Settings item (and other dynamically added items) do not show selection indicator
Fixed.

fix: NavigationView item selection, load on Skia

---

doc/articles/uno-development/building-uno-ui.md

docs: Adjust filtered build instructions for Wasm/Skia

---

doc/articles/features/working-with-assets.md

**None**
**Correct minor typo in docs**
**Not relevant**
**Not relevant**
**None**
**None**

docs: correct minor typo in working-with-assets.md

---

src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-winui/UnoWinUIQuickStart.Windows.Package/build/Microsoft.WinUI.AppX.targets

- Bugfix
Fixes the following error:
```
(myapp.Windows.Desktop.deps.json) was not found:
package: 'Microsoft.VCRTForwarders.140', version: '1.0.6'
path: 'runtimes/win10-x64/native/debug/concrt140d_app.dll'
```

fix(winui): Fix the WinUI desktop app template

---

src/SolutionTemplate/UnoSolutionTemplate.Wizard/UnoSolutionWizard.cs

GitHub Issue (If applicable): fixes #4892
- Feature
UWP project does not build nor deploy under AnyCPU.
UWP project builds and deploys its x86 version under AnyCPU.

feat: UWP buildable and deployable under Any CPU

---

doc/articles/uno-development/debugging-uno-ui.md

docs: Update package override instructions

---

doc/articles/Uno-UI-Performance.md

docs: Update performance hints for animations

---

src/Uno.UI/UI/Xaml/Controls/Popup/Popup.iOS.cs
src/Uno.UI/UI/Xaml/Controls/Popup/PopupPanel.cs

GitHub Issue (If applicable): Fixes https://github.com/unoplatform/nventive-private/issues/152
- Bugfix
Partial backport of https://github.com/unoplatform/uno/pull/4748/commits/fdf821ef6e6e4bd95622aaa691558306e5f76ae6, part of https://github.com/unoplatform/uno/pull/4748

fix(Leak): iOS Popup is leaking through the popup panel

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/BorderTests/Border_Tests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/BorderTests/Border_CornerRadius_BorderThickness.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/BorderTests/Border_CornerRadius_BorderThickness.xaml.cs
src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.Android.cs
src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.iOSmacOS.cs
src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.skia.cs
src/Uno.UI/UI/Xaml/CornerRadius.Android.cs

closes #4877
- Feature
Cannot set variable BorderThickness on a Border while setting CornerRadius

Allow variable BorderThickness while using CornerRadius on Border

---

src/Common_ViewLibraryProps/Globbing.props
src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props
src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs
src/Uno.UI-UnitTests-only.slnf
src/Uno.UI.Tests.ViewLibraryProps/Themes/Button.xaml
src/Uno.UI.Tests.ViewLibraryProps/Uno.UI.Tests.ViewLibraryProps.csproj
src/Uno.UI.Tests/Uno.UI.Tests.csproj
src/Uno.UI.Tests/Windows_UI_Xaml/Controls/When_Source_And_Globbing_From_Included_File.xaml
src/Uno.UI.Tests/Windows_UI_Xaml/Controls/When_Source_And_Globbing_From_Included_File.xaml.cs
src/Uno.UI.Tests/Windows_UI_Xaml/Given_ResourceDictionary.cs
src/Uno.UI.sln

GitHub Issue (If applicable): fixes #4790
- Bugfix

Fix ResourceDictionary.Source resolution when globbed includes are defined in an included file

---

doc/articles/get-started-next-steps.md
doc/articles/get-started-with-linux.md
doc/articles/get-started-wizard.md
doc/articles/toc.yml
doc/articles/uno-builds-troubleshooting.md

Misc docs updates

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/BorderTests/Border_Tests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/BorderTests/Border_CornerRadius_Clipping.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/BorderTests/Border_CornerRadius_Clipping.xaml.cs
src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.iOSmacOS.cs
src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.skia.cs

fix(Border): Ensure Border content is clipped by CornerRadius

---

src/Uno.UI/UI/Xaml/Shapes/Polygon.Android.cs

- Bugfix
```xml
<StackPanel Spacing="5">
<Polygon x:Name="DPolygon" Points="300,200 400,125 400,275" Stroke="black" StrokeThickness="5" />
</StackPanel>
```

fix(Polygon): Close Polygon shape on Android

---

src/Uno.UI.FluentTheme/Resources/PriorityDefault/PersonPicture.xaml
src/Uno.UI/UI/Xaml/Controls/PersonPicture/PersonPicture.xaml

GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/4911
- Bugfix

fix(personpicture): Fix invalid image positioning after ImageBrush fixes

---

src/SamplesApp/SamplesApp.UITests/Microsoft_UI_Xaml_Controls/NumberBoxTests/Given_NumberBox.Uno.cs
src/SamplesApp/SamplesApp.UITests/Microsoft_UI_Xaml_Controls/NumberBoxTests/Given_NumberBox.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/SliderTests/Given_Slider.cs
src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/NumberBoxTests/NumberBox_Header.xaml
src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/NumberBoxTests/NumberBox_Header.xaml.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Slider/Slider_Header.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Slider/Slider_Header.xaml.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/NumberBox/NumberBox.cs
src/Uno.UI/UI/Xaml/Controls/Slider/Slider.cs

GitHub Issue (If applicable): fixes #4572, fixes #4974 
- Bugfix
Not working
Working

Slider and NumberBox Header support

---

src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerSelector.iOS.cs

- Bugfix
ClockIdentifier Should be set at first Open of the flyout
https://user-images.githubusercontent.com/1330995/104875984-f1940000-5956-11eb-8673-deb0b9ed6dac.mp4
ClockIdentifier is set allways
https://user-images.githubusercontent.com/1330995/104876034-138d8280-5957-11eb-8902-d8bde2acf5c2.mp4

fix(TimePicker): Make Sure ClockIdentifier is set on iOS

---

src/SamplesApp/SamplesApp.Shared/App.xaml
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/CommandBarTests/UnoSamples_Tests.NativeCommandBar.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/BackButtonTitle/CommandBar_Frame.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/BackButtonTitle/CommandBar_Frame.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/BackButtonTitle/CommandBar_Page1.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/BackButtonTitle/CommandBar_Page1.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/BackButtonTitle/CommandBar_Page2.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/BackButtonTitle/CommandBar_Page2.xaml.cs
src/Uno.UI/Controls/CommandBarHelper.iOS.cs

- Bugfix
In iOS when setting a Global Style for the `CommandBar` to remove the Back Button Title this is not working correctly. Some pages still show the Back Button Text.
The Back Button Title for iOS will disappear from all Pages

fix(iOS): CommandBar BackButtonTitle

---

doc/articles/get-started-wizard.md

docs: Add CORS common issue

---

doc/articles/get-started-with-linux.md

and other distributions that are based on archlinux: Manjaro

docs: dotnet Uno in ArchLinux

---

src/Uno.UI/Extensions/VectorExtensions.cs

closes #4860 
- Feature
No support for Vector2.ToSize()
Uno.Extension to support for Vector2.ToSize()
This extension is part of the System.Numerics.Vectors.WindowsRuntime nuget =>  https://www.nuget.org/packages/System.Numerics.Vectors.WindowsRuntime/
Unfortunately, this one is only available for the target uap

feat: Add vector2.ToSize Extension

---

doc/articles/using-uno-ui.md

docs: Point DependencyProperty documentation to UWP

---

.vsts-ci.yml

ci: Adjust for xCode 12.3 on Xamarin 6.12.2

---

src/SolutionTemplate/UnoSolutionTemplate/Droid/Android.vstemplate
src/SolutionTemplate/UnoSolutionTemplate/Droid/UnoQuickStart.Droid.csproj
src/SolutionTemplate/UnoSolutionTemplate/Shared/App.xaml.cs
src/SolutionTemplate/UnoSolutionTemplate/Shared/UnoQuickStart.Shared.projitems
src/SolutionTemplate/UnoSolutionTemplate/Shared/UnoQuickStart.Shared.shproj
src/SolutionTemplate/UnoSolutionTemplate/Skia.Gtk/SkiaGtk.vstemplate
src/SolutionTemplate/UnoSolutionTemplate/Skia.Tizen/Program.cs
src/SolutionTemplate/UnoSolutionTemplate/Skia.Tizen/SkiaTizen.vstemplate
src/SolutionTemplate/UnoSolutionTemplate/Skia.Tizen/tizen-manifest.xml
src/SolutionTemplate/UnoSolutionTemplate/Skia.WPF.Host/UnoQuickStart.Skia.Wpf.Host.csproj
src/SolutionTemplate/UnoSolutionTemplate/Skia.WPF/SkiaWpf.vstemplate
src/SolutionTemplate/UnoSolutionTemplate/Skia.WPF/UnoQuickStart.Skia.WPF.csproj
src/SolutionTemplate/UnoSolutionTemplate/UWP/UnoQuickStart.Uwp.csproj
src/SolutionTemplate/UnoSolutionTemplate/UWP/Uwp.vstemplate
src/SolutionTemplate/UnoSolutionTemplate/Wasm/UnoQuickStart.Wasm.csproj
src/SolutionTemplate/UnoSolutionTemplate/Wasm/Wasm.vstemplate
src/SolutionTemplate/UnoSolutionTemplate/iOS/Properties/AssemblyInfo.cs
src/SolutionTemplate/UnoSolutionTemplate/iOS/iOS.vstemplate
src/SolutionTemplate/UnoSolutionTemplate/macOS/UnoQuickStart.macOS.csproj

refactor: Untabified and removed unnecessary white spaces from templates

---

src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/PagerControlTests/PagerControlPage.xaml
src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/PagerControlTests/PagerControlPage.xaml.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/Uno.UI-Android-only.slnf
src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/PagerControl/PagerControlTests.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Automation.Peers/AutomationLandmarkType.cs
src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Automation/AutomationProperties.cs
src/Uno.UI/Helpers/WinUI/ResourceAccessor.ResourceKeys.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/PagerControl/PagerControl.Header.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/PagerControl/PagerControl.Properties.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/PagerControl/PagerControl.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/PagerControl/PagerControlAutomationPeer.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/PagerControl/PagerControlButtonVisibility.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/PagerControl/PagerControlDisplayMode.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/PagerControl/PagerControlSelectedIndexChangedEventArgs.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/PagerControl/PagerControlTemplateSettings.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/PagerControl/PagerControl_themeresources_v2.5.xaml
src/Uno.UI/Microsoft/UI/Xaml/Controls/PagerControl/PagerControl_v2.5.xaml
src/Uno.UI/UI/Xaml/Automation/AutomationProperties.cs
src/Uno.UI/UI/Xaml/Automation/Peers/AutomationLandmarkType.cs
src/Uno.UI/UI/Xaml/Automation/Peers/FrameworkElementAutomationPeer.cs

GitHub Issue (If applicable): closes #5003 
- Feature
Not supported

WinUI PagerControl

---

.vsts-ci.yml
build/ci/.azure-devops-project-template-tests.yml
build/run-template-tests-linux.ps1
build/run-template-tests.ps1
src/SolutionTemplate/UnoSolutionTemplate/UWP/Uwp.vstemplate

ci: Add template tests for Linux

---

doc/articles/uno-fluent-assets.md

feat(doc): Update to include ways to download Uno fonts

---

src/SamplesApp/SamplesApp.UITests/RuntimeTests.cs

ci: Bump runtime tests runtime

---

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
src/Uno.UI.RuntimeTests/Helpers/StyleHelper.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/App_Level_Resources.xaml
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/App_Level_Resources.xaml.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/Inner_ThemeResource_Control.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/Inner_ThemeResource_Control.xaml
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/When_ThemeResource_Binding_In_Template_UserControl.xaml
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/When_ThemeResource_Binding_In_Template_UserControl.xaml.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_ThemeResource.cs

Handle case where ThemeResource binding is inside of a top-level resource dictionary.
GitHub Issue (If applicable): fixes #4881, fixes #4874
- Bugfix

fix(xaml): Fix ThemeResource binding in style template doesn't update

---

src/Uno.UI.RuntimeTests/Helpers/FeatureConfigurationHelper.cs
src/Uno.UI.RuntimeTests/Helpers/NumberAssert.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ComboBox.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/MeasureCountCarouselPanel.cs
src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/TestsResources.xaml
src/Uno.UI/FeatureConfiguration.cs
src/Uno.UI/UI/Xaml/Controls/Primitives/CarouselPanel.netstd.cs

GitHub Issue (If applicable): resolves #4991 
Reduce ComboBox cache size to a more reasonable value, so that dropdown takes less time to open.
- Bugfix

[WASM] Improve ComboBox dropdown open time

---

build/ios-uitest-run.sh
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/MenuFlyoutTests/MenuFlyoutTests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MenuFlyoutTests/MenuFlyoutItem_Hierarchy.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MenuFlyoutTests/MenuFlyoutItem_Hierarchy.xaml.cs
src/Uno.UI/UI/Xaml/Controls/Popup/Popup.iOS.cs

GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/5104
- Bugfix
iOS App may freeze when using nested MenuItem

fix(popup): [iOS] Nested popup results in NRE

---

src/Uno.UI.FluentTheme/Resources/PriorityDefault/ScrollBar_themeresources.xaml
src/Uno.UI.FluentTheme/themeresources.xaml

Exclude the template from the Fluent ScrollBar style, since it's incompatible with the performance optimizations made in Uno, and it's visually very similar to the UWP style anyway.
**Note:** UI test will be added in a follow-up PR.
GitHub Issue (If applicable): fixes #5034
- Bugfix

fix(scrollviewer): Show ScrollBar when Fluent styles are used

---

doc/articles/get-started-rider.md

docs: Rider get started update

---

doc/articles/get-started-with-linux.md

docs: update getting started linux - gettinghelp

---

doc/articles/get-started-vsmac.md

docs: update get-started-vsmac.md

---

doc/articles/get-started-vs.md

docs: Updates for troubleshooting issues

---

doc/articles/get-started-dotnet-new.md

-
- [x ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)

docs: getstarted-dotnetnew-gethelp

---

src/Uno.UI/UI/Xaml/Documents/Hyperlink.cs
src/Uno.UI/UI/Xaml/Documents/Hyperlink.macOS.cs

fixes https://github.com/unoplatform/Uno.Gallery/issues/124
- Bugfix

fix(Hyperlink): Add hyperlink foreground color for macOS

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml/UIElementTests/UIElementTests.cs
src/Uno.UI/UI/Xaml/UIElement.cs
src/Uno.UI/UI/Xaml/UIElement.iOS.cs

Fix scroll offset being double-applied to TransformToVisual offset. This fixes Flyouts not being positioned properly when attached to an anchor in scrolled content.
GitHub Issue (If applicable): fixes #5107
- Bugfix

fix(uielement): [iOS] Fix TransformToVisual output inside ScrollViewer

---

src/Uno.UI.FluentTheme/Resources/PriorityDefault/PersonPicture.xaml
src/Uno.UI.FluentTheme/themeresources.xaml
src/Uno.UI.RuntimeTests/MUX/Windows_UI_Xaml_Controls/PersonPictureTests.cs
src/Uno.UI/UI/Xaml/Controls/PersonPicture/PersonPicture.xaml

fix(PersonPicture): Use SymbolThemeFontFamily instead of Segoe MDL2 Assets

---

src/SolutionTemplate/UnoSolutionTemplate/Droid/UnoQuickStart.Droid.csproj
src/SolutionTemplate/UnoSolutionTemplate/UWP/UnoQuickStart.Uwp.csproj
src/SolutionTemplate/UnoSolutionTemplate/UnoApp.vstemplate
src/SolutionTemplate/UnoSolutionTemplate/iOS/UnoQuickStart.iOS.csproj
src/SolutionTemplate/UnoSolutionTemplate/macOS/UnoQuickStart.macOS.csproj

GitHub Issue (If applicable): fixes #5151 
- Bugfix
Applies workaround suggested in https://developercommunity2.visualstudio.com/t/legacy-projects-are-not-present-in-the-xaml-editor/1324898

fix(msix): Adjust project creation ordering

---

src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props
src/Uno.UI/Microsoft/UI/Xaml/Controls/InfoBar/InfoBarAutomationPeer.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/InfoBar/InfoBarClosedEventArgs.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/InfoBar/InfoBarClosingEventArgs.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/PagerControl/PagerControlAutomationPeer.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/PagerControl/PagerControlSelectedIndexChangedEventArgs.cs
src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml
src/Uno.UWPSyncGenerator/Generator.cs
src/Uno.UWPSyncGenerator/Program.cs

chore: Forward compatibility updates

---

src/Uno.UI/Mock/Brush.net.cs
src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.Android.cs
src/Uno.UI/UI/Xaml/Controls/Panel/Panel.Android.cs
src/Uno.UI/UI/Xaml/Controls/Panel/Panel.wasm.cs
src/Uno.UI/UI/Xaml/Media/Brush.Android.cs
src/Uno.UI/UI/Xaml/Media/Brush.cs
src/Uno.UI/UI/Xaml/Media/Brush.wasm.cs
src/Uno.UI/UI/Xaml/Shapes/Shape.cs
src/Uno.UI/UI/Xaml/UIElement.cs

GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/5133, and partially https://github.com/unoplatform/uno/issues/5166
Note: UI tests will be added in a subsequent PR.
- Bugfix

[Android] [WASM] Fixes for SolidColorBrush.Color changes not respected

---

src/Uno.UI.Toolkit/Uno.UI.Toolkit.Skia.csproj

GitHub Issue (If applicable): fixes Material part of #5186
- Bugfix
Make ElevatedView show up on Skia (at least without Elevation)

fix: ElevatedView does not show up on Skia

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ScrollViewerTests/UnoSamples_Tests.ScrolViewer.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ScrollViewerTests/ScrollViewer_Fluent.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ScrollViewerTests/ScrollViewer_Fluent.xaml.cs
src/Uno.UI/UI/Xaml/VisualStateManager.cs
src/Uno.UI/UI/Xaml/VisualStateManager.wasm.cs

GitHub Issue (If applicable): #5034

Add test for Fluent style scroll bar bug

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/Enability_Tests.cs
src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/RoutedEventIsEnabled_Tests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Input/PointersTests/Enability.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Input/PointersTests/Enability.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListViewItem_IsEnabled.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListViewItem_IsEnabled.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Input/RoutedEvents/RoutedEvent_IsEnabled.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Input/RoutedEvents/RoutedEvent_IsEnabled.xaml.cs
src/Uno.UI/UI/Xaml/Controls/Control/Control.cs
src/Uno.UI/UI/Xaml/Controls/Primitives/SelectorItem.cs
src/Uno.UI/UI/Xaml/FrameworkElement.Interface.Skia.cs
src/Uno.UI/UI/Xaml/UIElement.RoutedEvents.cs
src/Uno.UI/UI/Xaml/UIElement.Skia.cs
src/Uno.UI/UI/Xaml/UIElement.cs
src/Uno.UI/UI/Xaml/UIElement.wasm.cs

GitHub Issue (If applicable): fixes #4184, fixes #4183 

IsEnabled fixes, Routed Events fixes

---

build/Uno.WinUI.nuspec
src/Directory.Build.targets

chore: Update Uno.Core and Uno.SourceGeneration stable

---

src/SamplesApp/UITests.Shared/Windows_System/LauncherTests.xaml.cs
src/Uno.UI.Runtime.Skia.Tizen/Tizen/System/TizenLauncherExtension.cs
src/Uno.UI.Runtime.Skia.Tizen/Tizen/TizenHost.cs
src/Uno.UWP/System/ILauncherExtension.skia.cs
src/Uno.UWP/System/Launcher.Skia.cs
src/Uno.UWP/System/Launcher.cs

GitHub Issue (If applicable): fixes #5191
- Feature
Launcher not supported.
A basic version of Launcher is supported.

Support for Launcher on GTK, WPF and Tizen

---

src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.macOS.cs

- Bugfix
Difficulties to get the focus point on the macOS TextBox.

fix(macOS): Textbox Focus

---

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Media/SolidColorBrushTests/SolidColorBrush_Tests.cs
src/SamplesApp/UITests.Shared/UITests.Shared.projitems
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/BrushesTests/SolidColorBrush_Color_Changed.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/BrushesTests/SolidColorBrush_Color_Changed.xaml.cs

GitHub Issue (If applicable): #5133

test(brush): Add UI tests for SolidColorBrush.Color changes for BorderBrush and Stroke

---

src/Uno.UI/UI/Xaml/UIElement.Pointers.macOS.cs

fixes https://github.com/unoplatform/uno/issues/5109
Significantly improve perf of pointers on macOS
The tracking area is changed on each layouting phase
It's automatically updated by the system

fix: Improve performance of pointers on macOS

---

src/SolutionTemplate/UnoSolutionTemplate/UWP/UnoQuickStart.Uwp.csproj

- Bugfix
Remove the warning when restoring nuget packages.

fix: Adjust the Uno.Core version for UWP template

---

doc/articles/get-started-next-steps.md

docs: updated with Ch9

---

src/SamplesApp/UITests.Shared/Windows_Media/MediaPlayerTests.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MediaPlayerElement/MediaPlayerElement_3gp_Extension.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MediaPlayerElement/MediaPlayerElement_Avi_Extension.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MediaPlayerElement/MediaPlayerElement_Flv_Extension.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MediaPlayerElement/MediaPlayerElement_Full.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MediaPlayerElement/MediaPlayerElement_Minimal.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MediaPlayerElement/MediaPlayerElement_Mkv_Extension.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MediaPlayerElement/MediaPlayerElement_Mov_Extension.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MediaPlayerElement/MediaPlayerElement_Ogg_Extension.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MediaPlayerElement/MediaPlayerElement_Original.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MediaPlayerElement/MediaPlayerElement_Sources.xaml
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MediaPlayerElement/MediaPlayerElement_Sources.xaml.cs
src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MediaPlayerElement/MediaPlayerElement_Stretch_Fill.xaml
src/Uno.UI.FluentTheme/Resources/PriorityDefault/MediaTransportControls_themeresources.xaml
src/Uno.UI.FluentTheme/themeresources.xaml
src/Uno.UI.Tests/Windows_UI_Xaml/Given_Implicit_Style.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/Expander/ExpanderCollapsedEventArgs.cs
src/Uno.UI/Microsoft/UI/Xaml/Controls/Expander/ExpanderExpandingEventArgs.cs
src/Uno.UI/UI/Xaml/Controls/MediaPlayer/MediaPlayerElement.cs
src/Uno.UI/UI/Xaml/Controls/MediaPlayer/MediaPlayerElement.net.cs
src/Uno.UI/UI/Xaml/Controls/MediaPlayer/MediaPlayerPresenter.Android.cs
src/Uno.UI/UI/Xaml/Controls/MediaPlayer/MediaPlayerPresenter.Others.cs
src/Uno.UI/UI/Xaml/Controls/MediaPlayer/MediaPlayerPresenter.cs
src/Uno.UI/UI/Xaml/Controls/MediaPlayer/MediaPlayerPresenter.iOSmacOS.cs
src/Uno.UI/UI/Xaml/Controls/MediaPlayer/MediaTransportControls.MediaPlayer.cs
src/Uno.UI/UI/Xaml/Controls/MediaPlayer/MediaTransportControls.Properties.cs
src/Uno.UI/UI/Xaml/Controls/MediaPlayer/MediaTransportControls.cs
src/Uno.UI/UI/Xaml/Controls/MediaPlayer/MediaTransportControlsHelper.cs
src/Uno.UWPSyncGenerator.Reference/Uno.UWPSyncGenerator.Reference.csproj

WinUI3 preview update

---

src/AddIns/Uno.UI.Lottie/WasmScripts/uno-lottie.js
src/Uno.Foundation.Runtime.WebAssembly/AssemblyInfo.cs
src/Uno.Foundation.Runtime.WebAssembly/Interop/TSInteropMarshaller.wasm.cs
src/Uno.UI.Wasm.Tests/Tests/TSBindingsTests.cs
src/Uno.UI/UI/Xaml/UIElement.netstd.cs
src/Uno.UI/UI/Xaml/WindowManagerInterop.wasm.cs
src/Uno.UWP/Storage/ApplicationDataContainer.wasm.cs
src/Uno.UWP/Storage/StorageFolder.wasm.cs

- Adjust performance for children enumeration
- Remove generics from Wasm/JS interop

[Wasm] Performance improvements

---

src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/DateTimePicker/DateTimePicker_Styles.xaml
src/Uno.UI.Tests/Windows_UI_XAML_Controls/TextBlockTests/Given_TextBlock.cs
src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.cs
src/Uno.UI/UI/Xaml/Controls/Control/Control.cs
src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.cs
src/Uno.UI/UI/Xaml/Documents/TextElement.cs
src/Uno.UI/UI/Xaml/Style/Generic/Generic.Native.xaml
src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml

closes #2609 
- Feature
FontSize matches UWP FontSize

chore: Update Controls Default FontSize
