src/Uno.UI.Runtime.Skia.MacOS/MacOSWindowHost.cs, src/Uno.UI.Runtime.Skia.MacOS/NativeUno.cs, src/Uno.UI.Runtime.Skia.MacOS/UnoNativeMac/UnoNativeMac/UNOCursor.h, src/Uno.UI.Runtime.Skia.MacOS/UnoNativeMac/UnoNativeMac/UNOCursor.m
- Feature
The wait cursor is not animated (like it is normally on macOS).
Some non-available cursors are not mapped to the closest ones available.
Switching to Gtk strategy which is simpler and give us the animated wait cursor.
Also return the closest approximation if the cursor is not available.
Better logging if we can't set the exact requested cursor.
=> chore: animated wait cursor and better approx for missing ones on macOS/skia

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Grid.cs, src/Uno.UI/UI/Xaml/Controls/Canvas/Canvas.skia.cs, src/Uno.UI/UI/Xaml/Media/VisualTreeHelper.cs, src/Uno.UWP/Collections/MaterializableList.cs
=> fix(skia): Canvas.Zindex hit testing

src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/TimePicker/TimePickerIntegrationTests.cs
GitHub Issue (If applicable): closes #15810
=> test: fix system-dependent logic in SelectingTimeSetsSelectedTime

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBlock.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.skia.cs, src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.cs, src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.skia.cs, src/Uno.UI/UI/Xaml/Documents/InlineCollection.skia.cs, src/Uno.UI/UI/Xaml/Documents/TextFormatting/IBlock.skia.cs, src/Uno.UI/UI/Xaml/Documents/TextFormatting/RenderSegmentSpan.skia.cs
=> fix(textblock): on Skia, improve TextBlock selection on DoubleTap + account for surrogate pairs in TextBlock and TextBox

src/Uno.UI.Runtime.Skia.MacOS/MacOSFileOpenPickerExtension.cs, src/Uno.UI.Runtime.Skia.MacOS/MacOSFileSavePickerExtension.cs, src/Uno.UI.Runtime.Skia.MacOS/MacOSFolderPickerExtension.cs, src/Uno.UI.Runtime.Skia.MacOS/NativeUno.cs, src/Uno.UI.Runtime.Skia.MacOS/UnoNativeMac/UnoNativeMac/UNOPickers.h, src/Uno.UI.Runtime.Skia.MacOS/UnoNativeMac/UnoNativeMac/UNOPickers.m, src/Uno.UWP/Storage/Pickers/FileSavePicker.skiaiOS.cs, src/Uno.UWP/Storage/Pickers/FolderPicker.skia.cs, src/Uno.UWP/Storage/Pickers/IFileSavePickerExtension.skiaiOS.cs, src/Uno.UWP/Storage/Pickers/Internal/IFolderPickerExtension.skia.cs
- Feature
The extension interface for `FileOpenPicker`, `FolderOpenPicker` and `FileSavePicker` are limited and several properties were ignored.
A new `Customize` method is added (with an empty body for other existing implementations) that allows extension to read the managed properties of the pickers and set them, as closely as possible, on the target platform.
=> feat: more complete file/folder pickers for macOS/skia

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Flyout.cs, src/Uno.UI/UI/Xaml/Controls/Flyout/FlyoutBase.cs
GitHub Issue (If applicable): closes #15770
- Bugfix
=> `Flyout` open on `GotFocus`

doc/articles/common-issues-ioscatalyst.md, doc/articles/common-issues.md, doc/articles/faq.md, doc/articles/get-started.md
No information about supported release of environment when getting started on macOS.
Include solution proposed for older Mac hardware when latest macOS & Xcode releases are needed.
The proposed solution to upgrade older Mac hardware might need to be cleared by someone more knowledgable about the policy implications: @jeromelaban or @ajpinedam
=> docs: Developing on older Mac hardware

src/Uno.UWP/Collections/MaterializableList.cs
=> perf: Correct caching check for reverse enumerator

src/Uno.UI/FeatureConfiguration.cs
=> chore: Fix DisableThreadingCheck missing setter

doc/import_external_docs.ps1
In order to make sure latest documentation is up to date
=> docs: Update documentation to latest commits

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_DependencyProperty.cs, src/Uno.UI/UI/Xaml/DispatcherConditionalDisposable.cs
=> fix: PropertyChanged subscriptions delayed heavily on WASM

build/ci/.azure-devops-package-skia.yml
=> fix: Adjust native mac binaries path for packaging

.github/labeler.yml, src/SolutionTemplate/5.1/uno51blank/Directory.Packages.props, src/SolutionTemplate/5.1/uno51recommended/Directory.Packages.props, src/Uno.Sdk/ImplicitPackagesResolver.cs, src/Uno.Sdk/ImplicitPackagesResolverBase.cs, src/Uno.Sdk/PackageReference.cs, src/Uno.Sdk/Sdk/Sdk.props, src/Uno.Sdk/Sdk/Sdk.targets, src/Uno.Sdk/UnoFeature.cs, src/Uno.Sdk/targets/Uno.Common.Wasm.targets, src/Uno.Sdk/targets/Uno.Common.targets, src/Uno.Sdk/targets/Uno.Default.PackageVersions.targets, src/Uno.Sdk/targets/Uno.DefaultItems.Resizetizer.targets, src/Uno.Sdk/targets/Uno.DefaultItems.targets, src/Uno.Sdk/targets/Uno.Features.props, src/Uno.Sdk/targets/Uno.Implicit.Packages.targets, src/Uno.Sdk/targets/Uno.SingleProject.Desktop.targets, src/Uno.Sdk/targets/Uno.SingleProject.WinAppSdk.targets
- unoplatform/uno.templates#585
- Bugfix
Issues with loading Android dependencies for MAUI Embedding
Fixes Implicit Packages for MAUI Embedding.
=> Sdk Updates

src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.Xaml.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/15918
=> fix: Disable C# HR on iOS/Catalyst, use XAML Reader instead

src/Uno.UI.Runtime.Skia.X11/X11WindowWrapper.cs, src/Uno.UI.Runtime.Skia.X11/X11XamlRootHost.cs, src/Uno.UI.Runtime.Skia.X11/X11_Bindings/X11Helper.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/393
=> fix: x11 crashing when a scaled window icon is needed

src/Uno.UI/UI/Xaml/Controls/Panel/Panel.Android.cs, src/Uno.UI/UI/Xaml/Controls/Panel/Panel.crossruntime.cs, src/Uno.UI/UI/Xaml/Controls/Panel/Panel.cs, src/Uno.UI/UI/Xaml/Controls/Panel/Panel.iOSmacOS.cs, src/Uno.UI/UI/Xaml/Controls/Panel/Panel.unittests.cs, src/Uno.UI/UI/Xaml/Controls/Panel/PanelScrollingDirection.cs
=> refactor: Simplify `Panel` by moving shared logic to shared file

src/Uno.UI.Composition/Composition/SkiaCompositionSurface.skia.cs, src/Uno.UI/UI/Xaml/Media/ImageSource.crossruntime.cs, src/Uno.UI/UI/Xaml/Media/Imaging/BitmapImage.skia.cs, src/Uno.UI/UI/Xaml/Media/Imaging/BitmapImage.wasm.cs, src/Uno.UI/UI/Xaml/Media/Imaging/ImageSourceHelpers.cs, src/Uno.UI/UI/Xaml/Media/Imaging/SvgImageSource.Android.cs, src/Uno.UI/UI/Xaml/Media/Imaging/SvgImageSource.skia.cs, src/Uno.UWP/Helpers/AssetResolver.wasm.cs, src/Uno.UWP/Helpers/PlatformImageHelpers.cs, src/Uno.UWP/Helpers/PlatformImageHelpers.reference.cs, src/Uno.UWP/Helpers/PlatformImageHelpers.skia.cs, src/Uno.UWP/Helpers/PlatformImageHelpers.wasm.cs
=> refactor: Images refactor part 2

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls_Primitives/Given_Popup.cs, src/Uno.UI/UI/Xaml/Controls/Popup/Popup.cs, src/Uno.UI/UI/Xaml/Controls/Popup/PopupRoot.cs, src/Uno.UI/UI/Xaml/Controls/Popup/PopupRoot.mux.cs
GitHub Issue (If applicable): closes #15935
=> fix: popups should call OnClosing before actually closing

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Repeater/Given_ItemsRepeater.cs
=> test: Skip flaky test on Wasm

src/Uno.UI/UI/Xaml/Media/ImageSource.Android.cs, src/Uno.UI/UI/Xaml/Media/ImageSource.crossruntime.cs, src/Uno.UI/UI/Xaml/Media/ImageSource.cs, src/Uno.UI/UI/Xaml/Media/ImageSource.iOSmacOS.cs, src/Uno.UI/UI/Xaml/Media/ImageSource.unittests.cs
=> refactor: Cleanup ImageSource

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement_And_Leak.cs
=> test: Fix potential race in When_Add_Remove

src/Uno.UI/UI/Xaml/FrameworkElement.Layout.crossruntime.cs, src/Uno.UI/UI/Xaml/UIElement.cs, src/Uno.UI/UI/Xaml/UIElement.skia.cs
GitHub Issue (If applicable): Coupled with #15875
=> Fix and refactor clipping to work better with hittesting

src/Uno.UI.RemoteControl.VS/DebuggerHelper/ProfilesObserver.cs, src/Uno.UI.RemoteControl.VS/EntryPoint.cs, src/Uno.UI.RemoteControl.VS/Helpers/DTEHelper.cs, src/Uno.UI.RemoteControl.VS/Uno.UI.RemoteControl.VS.csproj
=> feat: Adjust automatic profile selection

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBlock.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.skia.cs, src/Uno.UI/UI/Xaml/Documents/InlineCollection.skia.cs
=> fix(textblock): fix selection when CRLF is present

src/AddIns/Uno.UI.MediaPlayer.Skia.Gtk/GtkMediaPlayer.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MediaPlayerElement/MediaPlayerElement_ManualTest.xaml.cs
GitHub Issue (If applicable): closes #15511
=> fix(mpe): hide video window on unload

doc/articles/get-started-wizard.md, doc/articles/includes/getting-help.md
Changes based on the discussion [here](https://teams.microsoft.com/l/message/19:787ad1de1af24252b9041bcbd4ec1ca3@thread.tacv2/1710786271926?tenantId=a297d6c0-b635-41a3-b1e3-558efe71e413&groupId=f55cdec8-036b-4efa-8e1a-c4129ba9bf12&parentMessageId=1710786271926&teamName=Uno%20Platform&channelName=Docs%20and%20Getting%20Started&createdTime=1710786271926)
=> docs: Update next steps after the creation of a new Uno Platform app

build/nuget/Uno.WinUI.nuspec
=> fix: Include net8.0-windows toolkit for net8 dependencies

src/Uno.UI.Runtime.Skia.X11/X11OpenGLRenderer.cs, src/Uno.UI.Runtime.Skia.X11/X11PointerInputSource.cs, src/Uno.UI.Runtime.Skia.X11/X11SoftwareRenderer.cs, src/Uno.UI.Runtime.Skia.X11/X11WindowWrapper.cs, src/Uno.UI.Runtime.Skia.X11/X11XamlRootHost.cs, src/Uno.UI.Runtime.Skia.X11/X11XamlRootHost.x11events.cs, src/Uno.UWP/Graphics/Display/DisplayInformation.cs
=> fix: scaling support for X11

src/SamplesApp/SamplesApp.Skia.Generic/Program.cs, src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/FramebufferHost.cs, src/Uno.UI.Runtime.Skia.MacOS/MacSkiaHost.cs, src/Uno.UI.Runtime.Skia.Wpf/WpfHost.cs, src/Uno.UI.Runtime.Skia.X11/X11ApplicationHost.cs, src/Uno.UI.Runtime.Skia/SkiaHost.cs
=> refactor: Make SkiaHost Task-based

build/nuget/Uno.WinUI.nuspec, src/Directory.Build.targets, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.Android.cs, src/Uno.UI/Uno.UI.netcoremobile.csproj
GitHub Issue (If applicable): closes #15994
=> fix: Add transitive dependency to Xamarin.AndroidX.SwipeRefreshLayout

src/Uno.Sdk/targets/Uno.Common.Wasm.targets
Ensure duplicate usings are properly removed.
=> fix: Ensure duplicate usings are removed properly

src/Uno.UI/UI/Xaml/UIElement.RoutedEvents.cs
GitHub Issue (If applicable): related to https://github.com/unoplatform/uno/issues/15629#issuecomment-2018014438
- Bugfix
=> fix: Adjust not implemented for `PointerWheelChanged`

src/SourceGenerators/Uno.UI.SourceGenerators/BindableTypeProviders/BindableTypeProvidersGenerationTask.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Data/BindableNullableValueTypeTestPage.xaml, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Data/BindableNullableValueTypeTestPage.xaml.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Data/Given_BindableNullableValueType.cs
GitHub Issue (If applicable): closes #16004
=> fix: Handle nullable value types correctly in BindableTypeProvidersSourceGenerator

src/Uno.UI.Runtime.Skia.X11/Builder/X11HostBuilder.cs, src/Uno.UI.Runtime.Skia.X11/X11XamlRootHost.cs
GitHub Issue (If applicable): closes [uno/unoprivate/#402](https://github.com/unoplatform/uno-private/issues/402)
=> chore: cleanly exit on X11 when no X server is running

build/nuget/Uno.WinUI.nuspec, src/Directory.Build.targets
GitHub Issue (If applicable): Follow-up to #16013
=> build: Downgrade Xamarin.AndroidX.SwipeRefreshLayout

src/Uno.UI.Runtime.Skia.MacOS/MacOSBadgeUpdaterExtension.cs, src/Uno.UI.Runtime.Skia.MacOS/MacSkiaHost.cs
- Bugfix
The macOS host code for badge notification was (mostly) included but not enabled.
Enable badge notification support on macOS.
=> fix(macOS): enable code for badge notification

src/Uno.Sdk/Sdk/Sdk.targets, src/Uno.Sdk/targets/Uno.Sdk.After.targets, src/Uno.UI.RemoteControl.VS/DebuggerHelper/ProfilesObserver.cs, src/Uno.UI.RemoteControl.VS/EntryPoint.cs, src/Uno.UI.RemoteControl.VS/Helpers/DTEHelper.cs, src/Uno.UI.RemoteControl.VS/Uno.UI.RemoteControl.VS.csproj
=> fix: Reload project when going from/to browserwasm

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ComboBox.cs, src/Uno.UI/UI/Xaml/Controls/Primitives/SelectorItem.cs
GitHub Issue (If applicable): closes #16009
=> fix: Fix selector item incorrectly going to Normal visual state

src/SolutionTemplate/5.2/uno52blank/uno52blank/uno52blank.csproj, src/Uno.Sdk/targets/Uno.Common.WinAppSdk.targets, src/Uno.Sdk/targets/Uno.SingleProject.WinAppSdk.targets
closes https://github.com/unoplatform/uno-private/issues/408
=> feat: Ensure that uno.sdk winappsdk apps include all Assets by default

src/SamplesApp/UITests.Shared/UITests.Shared.projitems, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_BeforeTextChanging_NumbersOnly.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_BeforeTextChanging_NumbersOnly.xaml.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.skia.cs
GitHub Issue (If applicable): closes #15372
=> fix(textbox): fix BeforeTextChanging cancelling on Wpf

doc/articles/controls/ContentDialog.md, doc/articles/features/clipboard.md, doc/articles/features/windows-networking.md
=> docs: Reference Tech Bites videos in docs

src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.cs
=> test: Run snapshot tests in dark mode

src/Uno.Foundation/WindowsFoundationDateTime.cs, src/Uno.UI.RuntimeTests/Helpers/DateTimeOffsetExtensions.cs, src/Uno.UI.RuntimeTests/Helpers/TimeZoneModifier.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/DatePickerIntegrationTests.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_DatePicker.cs, src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePicker.cs, src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePickerFlyoutPresenter_Partial.cs
GitHub Issue (If applicable): closes #15976
=> fix: Fix DatePicker crashing and not having correct initial date

build/nuget/Uno.WinUI.nuspec, src/Directory.Build.targets
=> build: Downgrade SwipeRefreshLayout package once again

build/nuget/uno.winui.common.targets, build/nuget/uno.winui.single-project.targets, build/nuget/uno.winui.targets, build/nuget/uno.winui.winappsdk.targets, src/SolutionTemplate/5.2/uno52blank/uno52blank/uno52blank.csproj, src/Uno.Sdk/Sdk/Sdk.props, src/Uno.Sdk/targets/Uno.Build.targets, src/Uno.Sdk/targets/Uno.Common.Android.targets, src/Uno.Sdk/targets/Uno.Common.Desktop.targets, src/Uno.Sdk/targets/Uno.Common.MacCatalyst.targets, src/Uno.Sdk/targets/Uno.Common.MacOS.targets, src/Uno.Sdk/targets/Uno.Common.Wasm.targets, src/Uno.Sdk/targets/Uno.Common.WinAppSdk.targets, src/Uno.Sdk/targets/Uno.Common.iOS.targets, src/Uno.Sdk/targets/Uno.Common.targets, src/Uno.Sdk/targets/Uno.DefaultItems.Resizetizer.targets, src/Uno.Sdk/targets/Uno.DefaultItems.targets, src/Uno.Sdk/targets/Uno.Implicit.Packages.targets, src/Uno.Sdk/targets/Uno.ProjectCapabilities.WinAppSdk.targets, src/Uno.Sdk/targets/Uno.ProjectCapabilities.targets, src/Uno.Sdk/targets/Uno.Sdk.After.targets, src/Uno.Sdk/targets/Uno.SingleProject.Android.targets, src/Uno.Sdk/targets/Uno.SingleProject.MacCatalyst.targets, src/Uno.Sdk/targets/Uno.SingleProject.MacOS.targets, src/Uno.Sdk/targets/Uno.SingleProject.iOS.targets
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno.studio/issues/571
=> fix: Remove legacy singleproject when uno.sdk is present

src/Uno.Sdk/targets/Uno.Common.Wasm.targets
- Bugfix
Adjust for incorrect wasm interactions for HR.
=> fix: Adjust HR interactions with wasm

src/Uno.UI.RuntimeTests/Tests/Uno_UI_Xaml_Core/Given_InputManager.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.skia.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.skia.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.skia.cs, src/Uno.UI/UI/Xaml/Documents/InlineCollection.skia.cs, src/Uno.UI/UI/Xaml/UIElement.cs
GitHub Issue (If applicable): closes #16026
=> fix(passwordbox): reveal button not working

src/Uno.UWP/Storage/Pickers/FolderPicker.iOS.cs
GitHub Issue (If applicable): closes #15547
- Bugfix
=> fix(catalyst): FolderPicker not opening

doc/import_external_docs.ps1
- Related doc changes: https://github.com/unoplatform/uno.extensions/pull/2197
- Related backport: https://github.com/unoplatform/uno.extensions/pull/2226
=> docs: Add Uno.Extensions latest docs updates

src/SamplesApp/SamplesApp.Shared/App.Tests.cs, src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.cs, src/SamplesApp/UITests.Shared/Helpers/ViewModelBase.cs, src/SamplesApp/UnoIslandsSamplesApp.Skia.Wpf/MainWindow.xaml, src/Uno.UI.Runtime.Skia.Wpf/Extensions/WpfDisplayInformationExtension.cs, src/Uno.UI.Runtime.Skia.Wpf/UI/Controls/UnoWpfWindow.cs, src/Uno.UI.RuntimeTests/IntegrationTests/common/TestServices.DispatchHelper.cs, src/Uno.UI.RuntimeTests/IntegrationTests/common/TestServices.WindowHelper.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FlowDirection.cs, src/Uno.UI.Tests/App/App.xaml.cs, src/Uno.UI.XamlHost.Skia.Wpf/UnoXamlHost.cs, src/Uno.UI/UI/Xaml/Internal/ContentManager/ContentManager.cs, src/Uno.UWP/Graphics/Display/DisplayInformation.cs, src/Uno.UWP/Microsoft/UI/Windowing/AppWindow.cs
=> fix: prevent Uno Islands from crashing

src/Uno.UI.Runtime.Skia.Gtk/UI/Controls/UnoGtkWindowHost.cs
GitHub Issue (If applicable): closes #16093
=> fix: read gtk window height correctly on WSL

src/Uno.UI/UI/Xaml/Documents/InlineCollection.skia.cs
=> perf: Avoid boxing StringRuneEnumerator

src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Given_Parser.cs, src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.Reflection.cs
GitHub Issue (If applicable): closes #15927
=> fix: Fix System.Type handling with xmlns

src/SamplesApp/Directory.Build.targets, src/SamplesApp/SamplesApp.UnitTests.Shared/SamplesApp.UnitTests.targets, src/SamplesApp/SamplesApp.Wasm/SamplesApp.Wasm.csproj
=> build: Fix SamplesApp.Wasm not building with AOT

doc/articles/uno-build-error-codes.md, src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props, src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.Telemetry.cs, src/Uno.Sdk/targets/Uno.Sdk.After.targets, src/Uno.UI.RemoteControl.VS/EntryPoint.ActiveProfileSync.cs
=> Adjust profile sync log level

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_UIElementCollection.cs, src/Uno.UI/UI/Xaml/UIElement.skia.cs, src/Uno.UI/UI/Xaml/UIElementCollection.cs
GitHub Issue (If applicable): closes #16068
=> feat: Support for `UIElementCollection.Move` on Skia

doc/articles/features/using-skia-desktop.md, src/Uno.Sdk/targets/Uno.Implicit.Packages.ProjectSystem.Desktop.targets
closes https://github.com/unoplatform/uno-private/issues/427
=> fix: Enable HW Accel over RDP for Skia Desktop

src/Uno.UI.RuntimeTests/Tests/Microsoft_UI_Xaml_Controls/Given_TreeView.cs, src/Uno.UI/UI/Xaml/Controls/Primitives/SelectorItem.cs
GitHub Issue (If applicable): closes #15950
=> fix(selectoritem): dragging wouldn't work if the pointer was pressed near the edge of the item

src/Uno.UI.Composition/Composition/Visual.cs
=> chore: Cleanup unused `Visual.HasThemeShadow` property

src/SamplesApp/UITests.Shared/UITests.Shared.projitems, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Repeater/ItemsRepeaterManyItems.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Repeater/ItemsRepeaterManyItems.xaml.cs, src/Uno.UI.Runtime.Skia.Gtk/Rendering/GLRenderSurfaceBase.cs
=> fix: Ensure rendering happens when measure/arrange is not dirty

src/Uno.UI/UI/Xaml/Documents/Inline.skia.cs, src/Uno.UI/UI/Xaml/Documents/InlineCollection.skia.cs, src/Uno.UI/UI/Xaml/Documents/Run.skia.cs, src/Uno.UI/UI/Xaml/Documents/TextFormatting/Segment.skia.cs
See https://github.com/mono/SkiaSharp/commit/ae94748eaebfcc669c470c34073276a650ce4f79.
SKPaint will no longer have font-related stuff. There is no need to replace this with anything else as we will be still using the right font for drawing text because we're still using the right SKFont when calling `_textBlobBuilder.AllocatePositionedRunFast`
=> refactor: Cleanup SKPaint used for text rendering

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_CalendarView.cs, src/Uno.UI/UI/Xaml/Controls/CalendarView/Primitives/CalendarPanel.ModernCollectionBasePanel.cs
GitHub Issue (If applicable): closes #16123
=> fix: Clean ContainersCache properly when MaxDate changes

src/Directory.Build.props
=> chore(deps): Update NetAnalyzers to 9.0.0-preview.24122.1

build/ci/.azure-devops-skia-tests.yml
=> ci: Fail CI properly when app crashes

doc/articles/features/using-skia-desktop.md, doc/articles/features/using-skia-macos.md, doc/articles/toc.yml, src/Uno.UI.Runtime.Skia.MacOS/README.md
* README.md was out-of-date.
* Exception could show `https://aka.platform.uno/skia-macos` but the doc is not available
* Updated READMD.md
* Doc to match `https://aka.platform.uno/skia-macos`
=> docs: update README and add aka refered doc

src/Uno.UI.RuntimeTests/Tests/HotReload/Frame/HRApp/AppHead.xaml.cs
=> fix: Fix formatting in HRApp

src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/TimePicker/TimePickerIntegrationTests.cs
=> test: Ignore flaky test on Wasm

build/Uno.UI.Build.csproj, src/Uno.Sdk/targets/Uno.Implicit.Packages.targets
- Bugfix
Properly updates the tasks versions when building on linux agents
=> ci: Enable UpdateTasksSHA on linux

src/Uno.UI.Runtime.Skia.Gtk/Rendering/GLRenderSurfaceBase.cs
GitHub Issue (If applicable): closes #16190
The fix from #15811 is unfortunately causing side effects that are breaking NavigationView 😕 
=> fix: Revert "Ensure rendering happens when measure/arrange is not dirty"

doc/articles/features/using-skia-gtk.md
GitHub Issue (If applicable): closes #16146
https://github.com/unoplatform/uno/discussions/16146
There is no information about this topic.
Add more info about this topic.
- [X ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
=> docs: Remote debugging using VS Code requires exporting DISPLAY in launch.json

src/Uno.UI/DataBinding/BindingExpression.cs, src/Uno.UI/DataBinding/BindingPath.BindingItem.cs, src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.cs, src/Uno.UI/UI/Xaml/DependencyObjectStore.cs, src/Uno.UI/UI/Xaml/DependencyPropertyDetails.cs, src/Uno.UI/UI/Xaml/DependencyPropertyFactory.cs, src/Uno.UI/UI/Xaml/UIElement.TextHelper.wasm.cs
=> perf: Avoid type checks against UnsetValue

src/Uno.Sdk/targets/Uno.Common.WinAppSdk.targets
- fixes unoplatform/uno-private#425
- Bugfix
=> fix: NETSDK1206

src/Uno.UI/UI/Xaml/FrameworkElement.Layout.crossruntime.cs, src/Uno.UI/UI/Xaml/UIElement.cs, src/Uno.UI/UI/Xaml/UIElement.skia.cs
Reverts #15970 
closes https://github.com/unoplatform/uno-private/issues/440
=> Revert "refactor: simplify clipping specifically on skia"

src/Uno.Sdk/targets/Uno.Sdk.After.targets, src/Uno.UI.RemoteControl.VS/DebuggerHelper/ProfilesObserver.cs, src/Uno.UI.RemoteControl.VS/EntryPoint.ActiveProfileSync.cs, src/Uno.UI.RemoteControl.VS/EntryPoint.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/439
- Bugfix
Adjust warnings on tfms reordering, adjust startup project on reload.
=> Misc vsix updates

build/nuget/uno.winui.common.targets, src/Uno.Sdk/targets/xamarin-ios-maccatalyst-workarounds.targets
closes https://github.com/unoplatform/uno-private/issues/423
=> fix(ios): Adjust for duplicate gcparams

build/cSpell.json, build/test-scripts/run-netcore-mobile-template-tests.ps1, doc/articles/features/upri-trimming.md, doc/articles/toc.yml, src/SolutionTemplate/MyAppXamlTrim/MyAppXamlTrim.Shared/Strings/fr/Resources.resw, src/SolutionTemplate/MyAppXamlTrim/MyAppXamlTrim.Wasm/MyAppXamlTrim.Wasm.csproj, src/SourceGenerators/Uno.UI.Tasks/Content/Uno.UI.Tasks.targets, src/SourceGenerators/Uno.UI.Tasks/LinkerHintsGenerator/LinkerDefinitionMergerTask.cs, src/SourceGenerators/Uno.UI.Tasks/ResourcesGenerator/ResourcesGenerationTask.cs, src/SourceGenerators/Uno.UI.Tasks/ResourcesGenerator/UpriFeaturesGeneratorTask.cs, src/SourceGenerators/Uno.UI.Tasks/ResourcesGenerator/UpriSubstitutionsGeneratorTask.cs, src/Uno.ResourceTrimmingValidator/Program.cs, src/Uno.ResourceTrimmingValidator/Properties/launchSettings.json, src/Uno.ResourceTrimmingValidator/Uno.ResourceTrimmingValidator.csproj, src/Uno.UI.Wasm.Tests/Uno.UI.Wasm.Tests.csproj
=> feat: Upri resources trimming

doc/articles/toc.yml
related https://github.com/unoplatform/Uno.Themes/issues/1378
related https://github.com/unoplatform/uno.toolkit.ui/issues/1096
=> docs: fixes for header page references

src/Uno.Sdk/Sdk/Sdk.props.buildschema.json
- n/a
- Other... Please describe: Adding intellisense schema file
=> chore: adding intellisense file for the SDK

doc/articles/get-started-vscode-devkit.md, doc/articles/migrating-from-net7-to-net8.md
=> docs: Fix misc broken links

src/Uno.Sdk/Sdk/Sdk.props.buildschema.json
Based on changes made for https://github.com/unoplatform/uno.resizetizer/pull/237
=> chore: Adjust Sdk.props.buildschema.json based on changes made for uno.resizetizer/pull/237

src/Uno.UI/UI/Xaml/FrameworkElement.reference.cs
=> refactor: Minor cleanup to FrameworkElement.reference.cs

doc/articles/get-started-vscode.md
https://github.com/unoplatform/uno-private/issues/444
Linux tab is always selected.
Linux tab is now selected when user click on it.
=> docs: remove solo Linux tab, fix selected tab.

src/SamplesApp/UITests.Shared/ItemExclusions.props, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Repeater/FlowLayout_Simple.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Repeater/StackLayout_Simple.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Repeater/UniformGridLayout_Simple.xaml.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/Repeater/TestUI/Samples/AnimationSamples/DefaultElementAnimator.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Repeater/Given_ItemsRepeater.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/StackLayout.cs
This reverts commit 15a8de8acd7404ad3534befd532ae1a82688e0fe, reversing changes made to 2569bb1fb25c480070f715a9baa75c274c50e152.
Revert https://github.com/unoplatform/uno/pull/15946 due to https://github.com/unoplatform/uno/issues/16176
=> Revert "Merge pull request #15946 from unoplatform/dev/dr/irVirIssue"

doc/articles/includes/use-uno-check-inline-windows-noheader.md
https://github.com/unoplatform/uno-private/issues/445
Text is duplicated.
Remove duplicated text.
=> docs: remove duplicated text

src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.cs
Fix possible null-ref in selection handling
Possible null-ref in few cases
null check!
=> fix(ListView): Fix possible null-ref in selection handling

src/Uno.Sdk/targets/Uno.SingleProject.VS.Build.targets
- Bugfix
Use `IsUnoHead` instead of `_IsExecutable` as the latter is not defined properly before the inner builds.
=> fix: Adjust condition for tf-specific VS debug build

src/Uno.UI.RemoteControl.VS/EntryPoint.cs
- Bugfix
Allow for devserver to notify when global properties change.
=> fix: Adjust global properties publication

src/Uno.Sdk/packages.json
- closes unoplatform/uno-private#452
- Other... Please describe: package update
=> chore: update implicit packages

src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props
Now that we are .NET 7+, I'd expect people to be on C# 11+.
C# 7.3 is way too old and we should no longer need to support it.
=> build: Cleanup UnoForceHotReloadCodeGen value needed only for old C# versions

src/Uno.Sdk/targets/Uno.Sdk.After.targets, src/Uno.UI.RemoteControl.VS/EntryPoint.ActiveProfileSync.cs, src/Uno.UI.RemoteControl.VS/EntryPoint.cs
=> fix: Move to rewrite the csproj until vs first-TFM issues are fixed

src/Uno.UI.Runtime.Skia.Gtk/UI/Controls/GtkWindowWrapper.cs, src/Uno.UI.Runtime.Skia.Gtk/UI/Controls/UnoGtkWindow.cs, src/Uno.UI.Runtime.Skia.Wpf/UI/Controls/UnoWpfWindow.cs, src/Uno.UI.Runtime.Skia.Wpf/UI/Controls/WpfWindowWrapper.cs, src/Uno.UI.Runtime.Skia.X11/X11WindowWrapper.cs, src/Uno.UI.Runtime.Skia.X11/X11XamlRootHost.cs, src/Uno.UI/Generated/3.0.0.0/Microsoft.UI.Xaml/Window.cs, src/Uno.UI/UI/Xaml/Window/Native/INativeWindowWrapper.cs, src/Uno.UI/UI/Xaml/Window/Native/NativeWindowWrapperBase.cs, src/Uno.UI/UI/Xaml/Window/Window.cs, src/Uno.UWP/ApplicationModel/Core/CoreApplicationViewTitleBar.skia.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/10874 , closes https://github.com/unoplatform/uno/issues/10368
=> feat: add support for ExtendIntoTitleBar on WPF

src/Uno.UI.RuntimeTests/Tests/Microsoft_UI_Xaml_Controls/Given_TreeView.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs, src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelGenerator.managed.cs
GitHub Issue (If applicable): closes #16041
=> fix(Treeview): throwing NRE on Dragging

doc/import_external_docs.ps1
Update import_external_docs.ps1 to have the latest doc updates
=> docs: Update import_external_docs.ps1 to have the latest doc updates

src/Uno.Sdk/Sdk/Sdk.props.buildschema.json
- related #16300 
- Other... Please describe: Intellisense schema update
=> Add new UnoFeatures to intellisense

src/SamplesApp/UITests.Shared/Windows_Storage/Pickers/FileOpenPickerTests.xaml.cs, src/Uno.UWP/Storage/Pickers/FileOpenPicker.iOS.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/16096
- Bugfix
=> fix(iOS): multiple videos picker

doc/import_external_docs.ps1
Update documentation for Uno.Themes, Figma, and Workshops with latest changes
=> docs: Update documentation for Uno.Themes, Figma, and Workshops with latest changes

src/Uno.UI/Generated/3.0.0.0/Microsoft.Windows.ApplicationModel.Resources/IResourceContext.cs, src/Uno.UI/Generated/3.0.0.0/Microsoft.Windows.ApplicationModel.Resources/IResourceManager.cs, src/Uno.UI/Generated/3.0.0.0/Microsoft.Windows.ApplicationModel.Resources/MrtCoreContract.cs, src/Uno.UI/Generated/3.0.0.0/Microsoft.Windows.ApplicationModel.Resources/ResourceCandidateKind.cs, src/Uno.UI/Generated/3.0.0.0/Microsoft.Windows.ApplicationModel.Resources/ResourceLoader.cs, src/Uno.UI/Microsoft/Windows/ApplicationModel/Resources/IResourceContext.cs, src/Uno.UI/Microsoft/Windows/ApplicationModel/Resources/IResourceManager.cs, src/Uno.UI/Microsoft/Windows/ApplicationModel/Resources/MrtCoreContract.cs, src/Uno.UI/Microsoft/Windows/ApplicationModel/Resources/ResourceCandidateKind.cs, src/Uno.UI/Microsoft/Windows/ApplicationModel/Resources/ResourceLoader.cs, src/Uno.UWP/ApplicationModel/Resources/Core/ResourceCandidate.cs, src/Uno.UWP/ApplicationModel/Resources/Core/ResourceQualifier.cs, src/Uno.UWP/ApplicationModel/Resources/ResourceLoader.cs
GitHub Issue (If applicable): closes #16286
- Feature
Not supported
Basic support
=> feat: Simplified implementation of MRT Core `ResourceLoader`

src/Uno.UI.FluentTheme.v2/themeresources_v2.xaml
=> chore: Unmerged themeresources change

src/Uno.Sdk/targets/Uno.Sdk.After.targets, src/Uno.Sdk/targets/Uno.SingleProject.VS.Build.targets, src/Uno.UI.RemoteControl.VS/DebuggerHelper/ProfilesObserver.cs, src/Uno.UI.RemoteControl.VS/EntryPoint.ActiveProfileSync.cs, src/Uno.UI.RemoteControl.VS/EntryPoint.cs
=> Adjust in-memory TargetFrameworks reordering

doc/articles/features/using-the-uno-sdk.md, src/Uno.Sdk/Sdk/Sdk.props.buildschema.json, src/Uno.Sdk/Tasks/ImplicitPackagesResolver.cs, src/Uno.Sdk/UnoFeature.cs, src/Uno.Sdk/targets/Uno.Extensions.Implicit.Packages.ProjectSystem.targets
- related #16330 
- Bugfix
WinUI Condition for SkiaSharp Views does not match the conditions for the SkiaSharp Views for Uno.WinUI
The conditions now match
=> Windows SkiaSharp Views condition should match Uno condition

src/SamplesApp/UITests.Shared/UITests.Shared.projitems, src/SamplesApp/UITests.Shared/Windows_Devices/GeolocatorPositionChangedTest.xaml, src/SamplesApp/UITests.Shared/Windows_Devices/GeolocatorPositionChangedTest.xaml.cs, src/Uno.UWP/Devices/Geolocation/Geolocator.Android.cs, src/Uno.UWP/Devices/Geolocation/Geolocator.iOSmacOS.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/discussions/16079
- Bugfix
=> fix(Geolocator): when requested in non-ui thread

src/Uno.UI.RemoteControl.VS/EntryPoint.ActiveProfileSync.cs
closes https://github.com/unoplatform/private/issues/426
=> fix(vsix): preserve the selected profile when chosen first

src/Uno.Sdk/targets/Uno.Common.Wasm.targets
=> fix: Ensure ILLinkPack is used on WASM NET8

src/Uno.UI.Runtime.Skia.Wpf/Uno.UI.Runtime.Skia.Wpf.csproj
=> build: Cleanup unneeded package references

src/Uno.Sdk/targets/Uno.Common.targets
closes https://github.com/unoplatform/private/issues/429
=> fix: Ensure all platform files are visible by default in VS

src/Uno.UI.RuntimeTests/Tests/BindingTests/BindingShouldBeAppliedOnPropertyChangedEvent.xaml, src/Uno.UI.RuntimeTests/Tests/BindingTests/BindingShouldBeAppliedOnPropertyChangedEvent.xaml.cs, src/Uno.UI.RuntimeTests/Tests/BindingTests/BindingTests.cs, src/Uno.UI.Tests/BinderTests/Given_Binder.inpc.cs, src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Given_xBind_DataTemplate.cs, src/Uno.UI/DataBinding/BindingPath.BindingItem.cs
GitHub Issue (If applicable): closes #16297
=> fix: Always raise binding value changed when PropertyChanged event is raised

doc/import_external_docs.ps1
Update doc with latest changes for Uno.Resizetizer and Uno.Extensions
=> docs: Update doc with latest changes for Uno.Resizetizer and Uno.Extensions

src/SourceGenerators/SourceGeneratorHelpers/Helpers/GeneratorExecutionContextExtensions.cs, src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs, src/Uno.Sdk/targets/Uno.DefaultItems.targets
GitHub Issue (If applicable): closes https://github.com/unoplatform/private/issues/433
=> Handle duplicate XAML files in codegen

src/Uno.UI/UI/Xaml/UIElement.RoutedEvents.cs
=> fix: Invert `Debug.Assert`s in RoutedEvents

src/Uno.UI.Runtime.Skia.X11/X11KeyboardInputSource.cs, src/Uno.UI.Runtime.Skia.X11/X11_Bindings/x11bindings_X11KeyTransform.cs
=> fix(textbox): fix enter not working in multiline textbox on X11

doc/import_external_docs.ps1
Update to latest documentation changes
=> docs: Update to latest changes

src/Uno.UI.Composition/Composition/CompositionClip.skia.cs, src/Uno.UI.Composition/Composition/CompositionGeometricClip.skia.cs, src/Uno.UI.Composition/Composition/CompositionViewBox.cs, src/Uno.UI.Composition/Composition/CompositionViewBox.skia.cs, src/Uno.UI.Composition/Composition/InsetClip.skia.cs, src/Uno.UI.Composition/Composition/RectangleClip.skia.cs, src/Uno.UI.Composition/Composition/ShapeVisual.skia.cs, src/Uno.UI.Composition/Composition/Visual.skia.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_UIElement.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Border.cs, src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.skia.cs, src/Uno.UI/UI/Xaml/FrameworkElement.EffectiveViewport.cs, src/Uno.UI/UI/Xaml/FrameworkElement.Layout.crossruntime.cs, src/Uno.UI/UI/Xaml/Media/VisualTreeHelper.cs, src/Uno.UI/UI/Xaml/UIElement.cs, src/Uno.UI/UI/Xaml/UIElement.skia.cs
=> Clip improvements

doc/articles/platform-specific-xaml.md
=> docs: Update platform-specific-xaml.md

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Control_Visibility.cs, src/Uno.UI/UI/Xaml/Controls/AppBar/AppBar.Partial.cs, src/Uno.UI/UI/Xaml/Controls/AppBar/AppBarSeparator.Partial.cs
GitHub Issue (If applicable): closes #16369
=> fix: Add missing base.OnVisibilityChanged call in AppBar and AppBarSeparator

src/Uno.UI/DataBinding/BindingPropertyHelper.FastConvert.cs, src/Uno.UI/Helpers/WinUI/SharedHelpers.cs, src/Uno.WinUIRevert/Program.cs
=> refactor: Do generic replacement of Microsoft.UI.Text

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement_EffectiveViewport.cs
=> test: Fix typo in EVPListener

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ScrollViewer.cs, src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.Managed.cs
GitHub Issue (If applicable): closes #16372
=> fix: Fix ScrollViewer with touch on Skia causing children to get clicked

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_FlipView.cs, src/Uno.UI/UI/Xaml/Controls/FlipView/FlipView.managed.cs, src/Uno.UI/UI/Xaml/Controls/FlipView/FlipView.managed.uno.cs
GitHub Issue (If applicable): closes #16360
=> fix: Fix mouse wheel not changing FlipView selected item

doc/articles/getting-started/counterapp/get-started-counter-csharp-mvux.md, doc/articles/getting-started/counterapp/get-started-counter-csharp-mvvm.md, doc/articles/getting-started/counterapp/get-started-counter-xaml-mvux.md, doc/articles/getting-started/counterapp/get-started-counter-xaml-mvvm.md
=> docs: Update counter repo links

src/Uno.CrossTargetting.targets, src/Uno.Foundation/CI.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.skia.cs, src/Uno.UI/UI/Xaml/Documents/InlineCollection.skia.cs
=> ci: Add CI.Assert helpers

src/SamplesApp/UITests.Shared/Helpers/WaitableSampleImageHelpers.cs, src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/ProgressRing/ProgressRingHeightTest.xaml.cs, src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/ProgressRing/WinUIProgressRingPage.xaml.cs, src/SamplesApp/UITests.Shared/UITests.Shared.projitems, src/SamplesApp/UITests.Shared/Windows_Media/MediaPlayerTests.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/ImageInStackPanel.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/ImageInStackPanel.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/SvgImageSource_Icons.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/SvgImageSource_Icons.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/Uniform100x100.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/Uniform100x100.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/UniformAlignmentCenterInDoubleStackPanelWebUri.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/UniformAlignmentCenterInDoubleStackPanelWebUri.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MediaPlayerElement/MediaPlayerElement_3gp_Extension.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MediaPlayerElement/MediaPlayerElement_Mp3_Extension.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MediaPlayerElement/MediaPlayerElement_Sources.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/ImageBrushTests/BorderImageBrush.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/ImageBrushTests/BorderImageBrush.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/ImageBrushTests/BorderImageBrushRelativeTransform.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/ImageBrushTests/BorderImageBrushRelativeTransform.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/ImageBrushTests/EllipsemaskingEllipseSuperpositionPanel.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/ImageBrushTests/EllipsemaskingEllipseSuperpositionPanel.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/ImageBrushTests/Rectangle.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/ImageBrushTests/Rectangle.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/Transform/TransformToVisual_Translate2d.xaml.cs, src/Uno.UI/UI/Xaml/Controls/Image/Image.skia.cs
GitHub Issue (If applicable): closes #16415
=> ci: Stabilize snapshot tests more

build/ci/.azure-devops-project-template-tests.yml, build/test-scripts/run-netcore-mobile-template-tests.ps1
=> ci: Adjust regression testing

build/test-scripts/run-netcore-mobile-template-tests.ps1, src/Uno.Sdk/targets/Uno.Implicit.Packages.ProjectSystem.Uno.targets
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/16428
- Bugfix
Don't include Svg in wasm targets.
=> fix: Remove svg package from wasm head

.github/ISSUE_TEMPLATE/bug-report.yml
=> chore: Adjust issue template for Skia platforms

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement_EffectiveViewport.cs
=> test: Fix EVP tests on WinAppSDK

build/ci/.azure-devops-wasm-uitests.yml
=> ci: Adjust Wasm CI to fail properly when there are failures

doc/articles/features/using-the-uno-sdk.md
Improve the "Using the Uno.Sdk" documentation
=> docs: Improve the "Using the Uno.Sdk" documentation

src/Uno.UI.Composition/Composition/SkiaCompositionSurface.skia.cs
=> fix: Flag image load failures as non-successful

src/Uno.UWP/ApplicationModel/Activation/ActivationKind.cs, src/Uno.UWP/ApplicationModel/Activation/ApplicationExecutionState.cs, src/Uno.UWP/ApplicationModel/Activation/IActivatedEventArgs.cs, src/Uno.UWP/ApplicationModel/Activation/IProtocolActivatedEventArgs.cs, src/Uno.UWP/ApplicationModel/Activation/IToastNotificationActivatedEventArgs.cs, src/Uno.UWP/ApplicationModel/Activation/LaunchActivatedEventArgs.cs, src/Uno.UWP/ApplicationModel/Activation/ProtocolActivatedEventArgs.cs, src/Uno.UWP/ApplicationModel/Activation/SearchActivatedEventArgs.cs, src/Uno.UWP/ApplicationModel/Activation/SplashScreen.cs, src/Uno.UWP/ApplicationModel/Activation/ToastNotificationActivatedEventArgs.cs, src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Activation/IProtocolActivatedEventArgs.cs
- Enum values were missing docs
- Some members acted as if they were implemented while they were not
- Adjustments made
=> refactor: Small cleanup and docs in ApplicationModel.Activation namespace

.github/workflows/uwp-autoconvert.yml, build/ci/.azure-devops-docs.yml, build/ci/.azure-devops-macos.yml, build/ci/.azure-devops-package-netcoremobile.yml, build/ci/.azure-devops-package-reference.yml, build/ci/.azure-devops-package-skia.yml, build/ci/.azure-devops-package-wasm.yml, build/ci/.azure-devops-project-template-tests.yml, build/ci/net7/global.json, build/ci/net8/global.json, build/ci/templates/dotnet-install.yml, global.json
=> build: Separate CI global.json files from local global.json

doc/import_external_docs.ps1
Update documentation with latest changes
=> docs: Update documentation with latest changes

src/Directory.Build.props, src/SamplesApp/SamplesApp.Shared/App.xaml.cs, src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.cs, src/SamplesApp/UITests.Shared/Windows_UI_Composition/InteractionTrackerAndExpressionAnimationSample.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Core/WindowActivationTests.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Input/GestureRecognizerTests/ManipulationEvents.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Input/GestureRecognizerTests/Manipulation_Basics.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Input/GestureRecognizerTests/Manipulation_Inertia.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Input/GestureRecognizerTests/Manipulation_WhenInScrollViewer.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Input/GestureRecognizerTests/PointersEvents.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Input/SetProtectedCursor.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml/DragAndDrop/DragDrop_Basics.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml/DragAndDrop/DragDrop_Nested.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Input/XamlUICommandTests.xaml.cs, src/Uno.CrossTargetting.targets, src/Uno.UI.RuntimeTests/Tests/Microsoft_UI_Xaml_Controls/Given_LayoutPanel.cs, src/Uno.UI.RuntimeTests/Tests/Microsoft_UI_Xaml_Controls/Given_PipsPager.cs, src/Uno.UI.RuntimeTests/Tests/Microsoft_UI_Xaml_Controls/Given_RatingControl.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Composition/Given_InteractionTracker.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement_LayoutSlot.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_CalendarView.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_MenuFlyout.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_NavigationView.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TreeView.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_WebView.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Repeater/Given_ItemsRepeater.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Repeater/UniformGridLayout/Given_UniformGridLayout.cs, src/Uno.UI/Extensions/PrettyPrint.cs
=> build: Don't include HAS_UNO_WINUI for Windows builds

src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/ColorPicker/ColorPickerTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/IconSource/IconSourceApiTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/InfoBadge/InfoBadgeTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/ItemsView/ItemsViewTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/NavigationView/NavigationViewTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/NumberBox/NumberBoxTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/PagerControl/PagerControlTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/RadioButtons/RadioButtonTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/Repeater/Common/SharedHelpers.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/Repeater/EffectiveViewportScrollViewerTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/Repeater/ElementAnimatorTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/Repeater/FlowLayoutCollectionChangeTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/Repeater/RepeaterFocusTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/Repeater/RepeaterTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/Repeater/ViewManagerTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/Repeater/ViewportTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/ScrollPresenter/ScrollControllerTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/ScrollPresenter/ScrollPresenterAnchoringTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/ScrollPresenter/ScrollPresenterLayoutTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/ScrollPresenter/ScrollPresenterSnapPointTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/ScrollPresenter/ScrollPresenterTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/ScrollView/ScrollViewTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/TeachingTip/TeachingTipTests.cs, src/Uno.UI.RuntimeTests/MUX/Utilities/IdleSynchronizer.cs, src/Uno.UI.RuntimeTests/MUX/Utilities/MUXApiTestBase.cs, src/Uno.UI.RuntimeTests/MUX/Utilities/TestHelpers.cs, src/Uno.UI.RuntimeTests/MUX/Windows_UI_Xaml_Controls/SwipeControl/SwipeControl_APITests.cs
On Wasm, `IdleSynchronizer.Wait` is currently no-op as we don't have threading.
https://github.com/unoplatform/uno/blob/df5929ab80d13eaaa03a1fc62756440d65d3d253/src/Uno.UI.RuntimeTests/MUX/Utilities/IdleSynchronizer.cs#L11-L25
This is functionally incorrect. It may be the root cause of some test failures that are specific to Wasm, and is a bigger problem for enhanced lifecycle because in some cases we really need to wait for idle whereas previously it would have been okay.
Use `await TestServices.WindowHelper.WaitForIdle` instead.
=> test: Avoid the use of IdleSynchronizer.Wait in runtime tests

src/Uno.UI.RuntimeTests/MUX/Helpers/CompositionPropertySpy.cs, src/Uno.UI.RuntimeTests/MUX/Helpers/EventTester.cs, src/Uno.UI.RuntimeTests/MUX/Input/Focus/FocusTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/ColorPicker/ColorPickerTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/ItemsView/ItemsViewTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/Repeater/EffectiveViewportScrollViewerTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/Repeater/ElementAnimatorTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/Repeater/FlowLayoutCollectionChangeTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/Repeater/RepeaterFocusTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/Repeater/RepeaterTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/Repeater/ViewManagerTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/Repeater/ViewportTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/ScrollPresenter/ScrollControllerTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/ScrollPresenter/ScrollPresenterAnchoringTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/ScrollPresenter/ScrollPresenterLayoutTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/ScrollPresenter/ScrollPresenterSnapPointTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/ScrollPresenter/ScrollPresenterTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/ScrollPresenter/ScrollPresenterViewChangeTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/ScrollView/ScrollViewTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/TeachingTip/TeachingTipTests.cs, src/Uno.UI.RuntimeTests/MUX/Utilities/MUXApiTestBase.cs, src/Uno.UI.RuntimeTests/MUX/Utilities/TestHelpers.cs, src/Uno.UI.RuntimeTests/MUX/Utilities/UnoManualOrAutoResetEvent.cs, src/Uno.UI.RuntimeTests/MUX/Windows_UI_Xaml_Controls/SwipeControl/SwipeControl_APITests.cs
=> test: Avoid the use of AutoResetEvent and ManualResetEvent

src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/ItemsViewTests/ItemsViewSummaryPage.xaml.cs
Not sure how/why this started happening on master suddenly.
=> test: Ignore ItemsViewSummaryPage snapshot

src/Uno.UI/Extensions/ViewExtensions.Android.cs, src/Uno.UI/Extensions/ViewExtensions.crossruntime.cs, src/Uno.UI/Extensions/ViewExtensions.iOSmacOS.cs, src/Uno.UI/Extensions/ViewExtensions.unittests.cs, src/Uno.UI/UI/Xaml/IFrameworkElement.cs
GitHub Issue (If applicable): closes #16406
=> perf: Fix performance regression in FindName

src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/ItemsView/ItemsViewTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/PagerControl/PagerControlTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/Repeater/RepeaterTests.cs, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/TabView/TabViewTests.Uno.cs
The `RunOnUIThread.Execute` overloads don't (and can't) await the given lambda as the type is just `System.Action`. So, the task is invoked in a fire-and-forget manner and assertion failures will NOT be caught by the test. So the tests can *fakely* pass.
Use `ExecuteAsync`
=> test: Fix fire-and-forget tests

src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/Repeater/ItemTemplateTests.cs
=> test: Add missing await in IR tests

src/SamplesApp/SamplesApp.Shared/App.xaml.cs
GitHub Issue (If applicable): closes #16532
=> fix: Fix WinUI SamplesApp not setting main window correctly

src/Uno.UI.Composition/Composition/CompositionEffectBrush.skia.cs, src/Uno.UI.Composition/Composition/ShadowState.skia.cs, src/Uno.UI.Composition/SkiaCompat.skia.cs, src/Uno.UI/UI/Xaml/Media/Imaging/RenderTargetBitmap.skia.cs
=> feat: Support for SkiaSharp 3

global.json
=> build: Set allowPrerelease to false

src/Uno.UI.Composition/Composition/InteractionTracker/InteractionTracker.cs
=> fix(reg): Fix InteractionTracker regression when it has null Owner

src/Uno.UI.Composition/Composition/CompositionSurfaceBrush.skia.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Image.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media/Given_ImageBrushStretch.cs
GitHub Issue (If applicable): closes #16519
=> fix: Fix images being pixelated in some cases

src/Directory.Build.targets, src/SamplesApp/UnoIslandsSamplesApp.Skia.Wpf/UnoIslandsSamplesApp.Skia.Wpf.csproj, src/Uno.UI.Composition/SkiaCompat.skia.cs
=> fix: Fix SkiaCompat crashing with SkiaSharp 3

src/Uno.UI.RuntimeTests/Helpers/ConditionalTestAttribute.cs
I think it makes more sense that we pass the platforms we want to ignore
=> test: Adjust ConditionalTestAttribute to be passed the ignored platforms

src/SamplesApp/UITests.Shared/UITests.Shared.projitems, src/SamplesApp/UITests.Shared/Windows_UI_Composition/VisualRotationSample.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Composition/VisualRotationSample.xaml.cs, src/Uno.UI.Composition/Composition/Uno/TransformableObjectExtensions.cs
=> fix: Respect CenterPoint when applying rotation

src/SamplesApp/UITests.Shared/Windows_UI_Composition/InteractionTrackerAndExpressionAnimationSample.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Composition/InteractionTrackerAndExpressionAnimationSample.xaml.cs, src/Uno.UI/UI/Xaml/Internal/InputManager.Pointers.Composition.cs, src/Uno.UI/UI/Xaml/UIElement.Pointers.cs
GitHub Issue (If applicable): closes #16550
=> fix: GestureRecognizer should be aborted when InteractionTracker takes over

src/Uno.UI.Composition/Composition/RectangleClip.skia.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Border.cs
Extracted from #16474 to get it merged faster
=> fix: Fix RectangleClip ignoring TransformMatrix

src/Uno.UI/UI/Xaml/UIElement.Pointers.cs
For some reason, `GetVisualAncestry` doesn't always return all the parents.
=> fix: Use EnumerateAncestors in CompleteGesturesOnTree

src/SamplesApp/UITests.Shared/UITests.Shared.projitems, src/SamplesApp/UITests.Shared/Windows_UI_Xaml/VisualStateTests/VisualState_ReturnPreviousValue2.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml/VisualStateTests/VisualState_ReturnPreviousValue2.xaml.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_CommandBar.cs, src/Uno.UI/DataBinding/BindingPath.cs, src/Uno.UI/UI/Xaml/Setter.cs, src/Uno.UI/UI/Xaml/VisualStateGroup.cs
=> Roll back storyboarded animations in a visual state when moving to another

src/Uno.UI.Runtime.Skia.X11/X11ApplicationHost.cs, src/Uno.UI.Runtime.Skia.X11/X11KeyboardInputSource.cs
GitHub Issue (If applicable): closes #16515
=> chore: remove a misleading error message when entering non-ascii characters on X11

src/Uno.UI.Composition/Composition/Compositor.skia.cs, src/Uno.UI.Dispatching/AssemblyInfo.skia.cs, src/Uno.UI.Dispatching/Native/NativeDispatcher.Android.cs, src/Uno.UI.Dispatching/Native/NativeDispatcher.cs, src/Uno.UI.Dispatching/Native/NativeDispatcher.iOSmacOS.cs, src/Uno.UI.Dispatching/Native/NativeDispatcher.skia.cs, src/Uno.UI.Dispatching/Native/NativeDispatcher.wasm.cs, src/Uno.UI.Runtime.Skia.Gtk/Rendering/GtkRendererProvider.cs, src/Uno.UI.Runtime.Skia.Gtk/UI/GtkDispatch.cs, src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/FramebufferHost.cs, src/Uno.UI.Runtime.Skia.MacOS/MacOSDispatcher.cs, src/Uno.UI.Runtime.Skia.Wpf/WpfHost.cs, src/Uno.UI.Runtime.Skia.X11/X11ApplicationHost.cs, src/Uno.UI.XamlHost.Skia.Wpf/UnoXamlHostBase.cs, src/Uno.UWP/Helpers/EventLoop.cs, src/Uno.UWP/UI/Core/CoreDispatcher.skia.cs, src/Uno.UWP/UI/Core/CoreDispatcher.wasm.cs
GitHub Issue (If applicable): This will fix the failures for https://github.com/unoplatform/uno/pull/15630
=> fix(WPF): Repetitive dispatching on Idle shouldn't block rendering

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ScrollViewer.cs, src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.cs
=> fix(scrollviewer): trim overscrolling after SizeChanged

src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Out/SOSLIIOFDOTAFE/XamlCodeGenerator_MainPage_d6cd66944958ced0c513e0a04797b51d.cs, src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Out/SOSLIOFPLR/XamlCodeGenerator_MainPage_d6cd66944958ced0c513e0a04797b51d.cs, src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Out/SOSLIOFPLS/XamlCodeGenerator_MainPage_d6cd66944958ced0c513e0a04797b51d.cs, src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Out/SOSLIOFRT/XamlCodeGenerator_MainPage_d6cd66944958ced0c513e0a04797b51d.cs, src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Out/TAA/XamlCodeGenerator_MainPage_d6cd66944958ced0c513e0a04797b51d.cs, src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Out/TBTNSICB/XamlCodeGenerator_MainPage_d6cd66944958ced0c513e0a04797b51d.cs, src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Out/TIM/XamlCodeGenerator_MainPage_d6cd66944958ced0c513e0a04797b51d.cs, src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Out/TPXBRXLE/XamlCodeGenerator_MainPage_d6cd66944958ced0c513e0a04797b51d.cs, src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Out/TRDAAPSSTP/XamlCodeGenerator_MainPage_d6cd66944958ced0c513e0a04797b51d.cs, src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Out/TTW/XamlCodeGenerator_MainPage_d6cd66944958ced0c513e0a04797b51d.cs, src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Out/TXBRXLE/XamlCodeGenerator_MainPage_d6cd66944958ced0c513e0a04797b51d.cs, src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Out/WOPADNE/XamlCodeGenerator_MainPage_d6cd66944958ced0c513e0a04797b51d.cs, src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Out/WOPAE__name/XamlCodeGenerator_MainPage_d6cd66944958ced0c513e0a04797b51d.cs, src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Out/WOPAE_m_name/XamlCodeGenerator_MainPage_d6cd66944958ced0c513e0a04797b51d.cs, src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Out/WOPAE_name/XamlCodeGenerator_MainPage_d6cd66944958ced0c513e0a04797b51d.cs, src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Out/WXOWCP/XamlCodeGenerator_Binding_Xaml_Object_With_Common_Properties_4891310bc693a433ba9a8e9f5113f94f.cs, src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Out/WXOWXOP/XamlCodeGenerator_Binding_Xaml_Object_With_Xaml_Object_Properties_5147419e44d1bc3e3f86860ad528476f.cs, src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs, src/Uno.UI.RuntimeTests/Directory.Build.targets, src/Uno.UI.RuntimeTests/Tests/BindingTests/BindingTests.cs, src/Uno.UI.RuntimeTests/Tests/BindingTests/XBindInWindow.xaml, src/Uno.UI.RuntimeTests/Tests/BindingTests/XBindInWindow.xaml.cs, src/Uno.UI/UI/Xaml/Window/Implementations/BaseWindowImplementation.cs
GitHub Issue (If applicable): closes #16520
=> fix: Fix sender argument in Window events and x:Bind in Window when it's root of XAML

build/test-scripts/run-netcore-mobile-template-tests.ps1, src/AddIns/Uno.UI.Lottie/Uno.UI.Lottie.Wasm.csproj, src/AddIns/Uno.UI.MSAL/Uno.UI.MSAL.Wasm.csproj, src/AddIns/Uno.UI.MediaPlayer.WebAssembly/Uno.UI.MediaPlayer.WebAssembly.csproj, src/SourceGenerators/Uno.UI.Tasks/Content/Uno.UI.Tasks.targets, src/SourceGenerators/Uno.UI.Tasks/EmbeddedResourceInjector/EmbeddedResourceInjectorTask.cs, src/SourceGenerators/Uno.UI.Tasks/ResourcesGenerator/UpriSubstitutionsGeneratorTask.cs, src/Uno.UI.Wasm.Tests/Uno.UI.Wasm.Tests.csproj, src/Uno.UI/Uno.UI.Wasm.csproj
=> fix: Breakpoints don't hit in SamplesApp

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs, src/Uno.UI.RuntimeTests/Tests/BindingTests/BindingTests.cs, src/Uno.UI.RuntimeTests/Tests/BindingTests/FallbackValueThemeResource.xaml, src/Uno.UI.RuntimeTests/Tests/BindingTests/FallbackValueThemeResource.xaml.cs, src/Uno.UI.RuntimeTests/Tests/BindingTests/TargetNullValueThemeResource.xaml, src/Uno.UI.RuntimeTests/Tests/BindingTests/TargetNullValueThemeResource.xaml.cs, src/Uno.UI/Helpers/BindingExtensions.cs, src/Uno.UI/UI/Xaml/Data/Binding.cs, src/Uno.UI/UI/Xaml/DependencyObjectStore.cs, src/Uno.UI/UI/Xaml/DependencyPropertyDetailsCollection.Bindings.cs
GitHub Issue (If applicable): closes #16505
=> feat: Support ThemeResource in TargetNullValue and FallbackValue

src/SamplesApp/SamplesApp.UITests/Microsoft_UI_Xaml_Controls/RadioButtonsTests/Given_RadioButtons.cs
=> chore: Mark `SelctionTest` as flaky on iOS

build/cSpell.json, doc/articles/uno-build-error-codes.md, src/Uno.UI/Microsoft/UI/Xaml/Controls/ProgressRing/ProgressRing.cs
- Bugfix
- Adjusts the error message showing when ProgressRing is showing up, adding UNOX0001.
- Reduced font size to enhance visual fit
=> fix: Adjust lottie error code for missing package

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Slider.cs, src/Uno.UI/UI/Xaml/Controls/Slider/Slider.mux.cs
GitHub Issue (If applicable): closes #16609
- Bugfix
=> fix: `Slider` tooltip contains "f" for decimal values

doc/import_external_docs.ps1
Update Uno.Extensions documentation to latest
=> docs: Update Uno.Extensions documentation to latest

src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.cs
GitHub Issue (If applicable): closes #16612
=> test: Fix TestCleanup to properly be awaited when it returns a Task

doc/import_external_docs.ps1
Update Uno.Samples documentation to the latest
=> docs: Update Uno.Samples documentation to the latest

build/cSpell.json, doc/articles/uno-development/ways-to-contribute.md
=> docs: Update ways-to-contribute.md

src/SamplesApp/UITests.Shared/UITests.Shared.projitems, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_KeyboardInterception.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_KeyboardInterception.xaml.cs, src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.cs
closes https://github.com/unoplatform/uno/issues/16655
=> fix: Fix space and enter keys in TB while in ListView

src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml/XamlRoot/XamlRoot_Properties.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/ImagesInlineInFlipView.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/ImagesInlineInFlipView.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/StretchNoneBoundingBoxInDoubleStackPanel.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/StretchNoneBoundingBoxInDoubleStackPanel.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/SvgImageSource_NoSize.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/SvgImageSource_NoSize.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MediaPlayerElement/MediaPlayerElement_Avi_Extension.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MediaPlayerElement/MediaPlayerElement_Flv_Extension.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MediaPlayerElement/MediaPlayerElement_Mkv_Extension.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MediaPlayerElement/MediaPlayerElement_Mov_Extension.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MediaPlayerElement/MediaPlayerElement_Stretch_Fill.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/ImageBrushTests/Ellipse.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/ImageBrushTests/Ellipse.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/ImageBrushTests/ImageBrushAlignmentXY2.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/ImageBrushTests/ImageBrushAlignmentXY2.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/ImageBrushTests/ImageBrush_StreamSource.xaml.cs
=> test: Stabilize snapshot comparison more

src/Uno.Foundation.Runtime.WebAssembly/Interop/Runtime.wasm.cs, src/Uno.Foundation/Uno.Core.Extensions/Uno.Core.Extensions.Compatibility/Collections/ImmutableList.cs, src/Uno.UI/Extensions/CGSizeExtensions.iOSmacOS.cs, src/Uno.UI/Extensions/DoubleExtensions.cs, src/Uno.UI/UI/Input/GestureRecognizer.Manipulation.cs, src/Uno.UI/UI/Input/ManipulationDelta.cs, src/Uno.UI/UI/Input/ManipulationVelocities.cs, src/Uno.UI/UI/LayoutHelper.Android.cs, src/Uno.UI/UI/LayoutHelper.cs, src/Uno.UI/UI/LayoutHelper.iOS.cs, src/Uno.UI/UI/Xaml/Controls/Image/ImageSizeHelper.cs, src/Uno.UI/UI/Xaml/Controls/Layouter/Layouter.cs, src/Uno.UI/UI/Xaml/Media/Brush.cs, src/Uno.UI/UI/Xaml/RoutedEvent.cs, src/Uno.UI/UI/Xaml/RoutedEventFlag.cs, src/Uno.UWP/UI/Input/GestureRecognizer.Manipulation.cs, src/Uno.UWP/UI/Input/ManipulationDelta.cs, src/Uno.UWP/UI/Input/ManipulationVelocities.cs
`Pure` attribute is used in many places.
As the .NET team decided to drop the attribute for their usages in collections, we can follow them, as the attribute is mostly useless. See https://github.com/dotnet/runtime/pull/35118#discussion_r410679735
=> chore: Drop PureAttribute

.vsts-ci-docs.yml
=> ci: Bump to latest scaled agent (docs)

src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/PathTestsControl/Path_With_DashStrokeArray.xaml.cs, src/Uno.UI.Composition/Composition/CompositionSpriteShape.skia.cs, src/Uno.UI.Composition/Composition/CompositionStrokeDashArray.cs, src/Uno.UI.Composition/Generated/3.0.0.0/Microsoft.UI.Composition/CompositionStrokeDashArray.cs, src/Uno.UI/UI/Xaml/Shapes/Shape.skia.cs
GitHub Issue (If applicable): Skia part of #16686
=> feat(skia): Support Shape.StrokeDashArray and CompositionStrokeDashArray

src/Uno.Sdk/targets/Uno.Sdk.After.targets
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/16692
- Bugfix
Don't rewrite target frameworks for libraries, it's not required and causes invalid TFMs values.
=> fix: Don't rewrite the target frameworks list on a class library

src/Uno.Sdk/packages.json
closes https://github.com/unoplatform/uno.resizetizer/issues/254
=> chore: Bump to latest resizetizer

src/Uno.UI.Dispatching/Native/UIAsyncOperation.cs
=> fix: Fix UIAsyncOperation threading issue

src/SourceGenerators/Uno.UI.Tasks/Content/Uno.UI.Tasks.targets
=> fix: Fix illinkerpath

build/nuget/Uno.WinUI.nuspec, src/Directory.Build.targets
Related issue #15794
Update Uno.Fonts.Fluent to latest stable
=> chore: Update Uno.Fonts.Fluent to latest stable

doc/articles/guides/localization.md
=> docs: Update localization.md

src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/FramebufferHost.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/16719
- Bugfix
Ensures that a FB app can run without a pty.
=> fix(framebuffer): Don't read console input if redirected

build/ci/.azure-devops-package-native-assets.yml, build/ci/.azure-devops-package-skia-native-assets.yml, build/ci/.azure-devops-package-skia.yml, build/ci/.azure-devops-skia-tests.yml, src/SamplesApp/SamplesApp.Skia.Generic/SamplesApp.Skia.Generic.csproj
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/16744
- Bugfix
Properly publish native macos assets for the skia-desktop samples app
=> fix: Publish native macos assets for the samplesapp

doc/articles/uno-development/building-uno-ui.md
PR #11205 renamed the `Uno.CrossTargetting.props` files to be `Uno.CrossTargetting.targets`. This PR adjusts sources to changes.
=> docs: update reference to Uno CrossTargetting file

build/nuget/Uno.WinUI.nuspec
=> chore: Fix typo in Uno.WinUI nuspec

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.skia.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.skia.cs, src/Uno.UI/UI/Xaml/Documents/InlineCollection.skia.cs
=> Textbox paste history

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.skia.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.skia.cs
GitHub Issue (If applicable): closes #16789
=> fix(textbox): textbox vertical scrolling not following the caret

build/ci/.azure-devops-package-netcoremobile.yml, build/ci/templates/dotnet9-mobile-install-windows.yml
GitHub Issue (If applicable): closes #16786
=> ci: Build packages with .NET 9 SDK

src/SourceGenerators/SourceGeneratorHelpers/Helpers/PlatformHelper.cs
=> refactor: Cleanup PlatformHelper to remove no longer relevant checks

build/nuget/uno.winui.common.targets
=> build: Cleanup uno.winui.common.targets

doc/articles/getting-started/counterapp/get-started-counter-csharp-mvux.md, doc/articles/getting-started/counterapp/get-started-counter-xaml-mvux.md, doc/articles/getting-started/counterapp/includes/include-mvux.md
GitHub Issue (If applicable): #https://github.com/unoplatform/private/issues/446
see https://github.com/unoplatform/Uno.Samples/pull/693 for changes
=> docs: update MVUX counter

doc/articles/features/using-the-uno-sdk.md, src/Uno.Sdk/Sdk/Sdk.props.buildschema.json, src/Uno.Sdk/targets/Uno.Common.targets, src/Uno.Sdk/targets/Uno.Extensions.Implicit.Packages.ProjectSystem.targets, src/Uno.Sdk/targets/Uno.Features.targets, src/Uno.Sdk/targets/Uno.Implicit.Packages.ProjectSystem.Uno.targets, src/Uno.Sdk/targets/Uno.Implicit.Packages.ProjectSystem.Wasm.targets, src/Uno.Sdk/targets/Uno.Implicit.Packages.ProjectSystem.WinAppSdk.targets, src/Uno.Sdk/targets/Uno.Implicit.Packages.ProjectSystem.targets
- closes #16470
- Feature
UnoFeature selection is case sensitive
UnoFeatures now ignore the case and cast everything ToLower
=> Make UnoFeatures ignore casing

build/test-scripts/run-netcore-mobile-template-tests.ps1, src/Uno.Sdk/targets/Uno.Sdk.After.targets
=> fix(sp): Rewrite `TargetFrameworks` using exact TF matching

src/Directory.Build.targets, src/SamplesApp/SamplesApp.netcoremobile/SamplesApp.netcoremobile.csproj
=> fix: adjust local ios solution build

build/nuget/Uno.WinUI.nuspec
=> chore: Cleanup Uno.WinUI dependencies for net8.0/net9.0

doc/articles/features/upri-trimming.md, src/SourceGenerators/Uno.UI.Tasks/Content/Uno.UI.Tasks.targets
=> perf: Enable UPRI trimming everywhere ILLink runs

src/crosstargeting_override.props.sample
=> chore: use as sample a more recent version

src/Uno.UI.RemoteControl/buildTransitive/Uno.UI.DevServer.targets
- Bugfix
Ensure that the devserver ports file is recognized during incremental builds.
=> fix: Adjust incremental build for devserver

src/Uno.UI/UI/Xaml/Internal/Scaling/RootScale.mux.cs
=> chore: Fix comment typo in RootScale

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.skia.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.skia.cs
GitHub Issue (If applicable): closes #16867
=> fix(textbox): add ctrl+ins and shift+ins to copy/paste

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.skia.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.skia.cs
GitHub Issue (If applicable): closes #16802
=> Textbox caret column retention

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.skia.cs, src/Uno.UI/UI/Xaml/Documents/InlineCollection.skia.cs, src/Uno.UI/UI/Xaml/Documents/Run.skia.cs, src/Uno.UI/UI/Xaml/Documents/TextFormatting/Segment.skia.cs
GitHub Issue (If applicable): closes #16806
=> feat(textbox): variable Tab widths i.e. Tab stops

build/ci/.azure-devops-uwp-convert.yml, src/Uno.UWPSyncGenerator/Generator.cs
=> ci: Publish binlogs from sync generator

doc/articles/guides/profiling-applications.md
=> docs: Update Android profiling documentation

src/Uno.UI/UI/Xaml/Documents/Run.skia.cs
GitHub Issue (If applicable): closes #16788, closes #15528
=> fix(textbox): textbox selection with ligatures

doc/articles/Uno-UI-Performance.md
=> docs: Update performance tips for Android

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement_And_Leak.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement_Layouting.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ContentPresenter.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/ProgressBar/ProgressBar.cs, src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.cs, src/Uno.UI/UI/Xaml/Controls/FocusVisual/SystemFocusVisual.cs, src/Uno.UI/UI/Xaml/Controls/MediaPlayerElement/MediaTransportControls.cs, src/Uno.UI/UI/Xaml/Controls/ScrollBar/ScrollBar.cs, src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/CompositorScrollStrategy.cs, src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.wasm.cs, src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.cs, src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.skia.cs, src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.wasm.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.skia.cs, src/Uno.UI/UI/Xaml/FrameworkElement.EffectiveViewport.Interface.cs, src/Uno.UI/UI/Xaml/FrameworkElement.EffectiveViewport.cs, src/Uno.UI/UI/Xaml/FrameworkElement.Layout.crossruntime.cs, src/Uno.UI/UI/Xaml/FrameworkElement.crossruntime.cs, src/Uno.UI/UI/Xaml/FrameworkElement.cs, src/Uno.UI/UI/Xaml/Internal/EventManager.cs, src/Uno.UI/UI/Xaml/Internal/EventManager.uno.cs, src/Uno.UI/UI/Xaml/Media/ImageBrush.wasm.cs, src/Uno.UI/UI/Xaml/UIElement.cs
GitHub Issue (If applicable): Skia and Wasm side of #7002
=> fix: Fix LayoutUpdated/SizeChanged on Skia and Wasm

build/cSpell.json, doc/articles/toc.yml, doc/articles/uno-publishing-android.md, doc/articles/uno-publishing-desktop.md, doc/articles/uno-publishing-ios.md, doc/articles/uno-publishing-maccatalyst.md, doc/articles/uno-publishing-overview.md, doc/articles/uno-publishing-webassembly.md, doc/import_external_docs.ps1
=> More publishing docs

src/Uno.UI/Microsoft/UI/Input/InputFocusController.cs
GitHub Issue (If applicable): related to #16939
=> chore: Add back unintentionally removed internal constructor

build/cSpell.json, doc/articles/toc.yml, doc/articles/uno-publishing-android.md, doc/articles/uno-publishing-desktop.md, doc/articles/uno-publishing-ios.md, doc/articles/uno-publishing-maccatalyst.md, doc/articles/uno-publishing-overview.md, doc/articles/uno-publishing-webassembly.md, doc/import_external_docs.ps1
=> chore: Backport #16903

src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.MetadataUpdate.cs, src/Uno.UI.RuntimeTests/Tests/HotReload/Frame/HRApp/Tests/Given_TypeReplacement.cs, src/Uno.UI.RuntimeTests/Tests/HotReload/Frame/HRApp/Tests/Pages/HR_DPUpdates_Binding_Component.xaml, src/Uno.UI.RuntimeTests/Tests/HotReload/Frame/HRApp/Tests/Pages/HR_DPUpdates_Binding_Component.xaml.cs, src/Uno.UI.RuntimeTests/Tests/HotReload/Frame/HRApp/Tests/Pages/HR_DPUpdates_Binding_PageUsingComponent.xaml, src/Uno.UI.RuntimeTests/Tests/HotReload/Frame/HRApp/Tests/Pages/HR_DPUpdates_Binding_PageUsingComponent.xaml.cs, src/Uno.UI.RuntimeTests/Tests/HotReload/Frame/HRApp/Tests/Pages/HR_DPUpdates_Component.xaml, src/Uno.UI.RuntimeTests/Tests/HotReload/Frame/HRApp/Tests/Pages/HR_DPUpdates_Component.xaml.cs, src/Uno.UI.RuntimeTests/Tests/HotReload/Frame/HRApp/Tests/Pages/HR_DPUpdates_PageUsingComponent.xaml, src/Uno.UI.RuntimeTests/Tests/HotReload/Frame/HRApp/Tests/Pages/HR_DPUpdates_PageUsingComponent.xaml.cs, src/Uno.UI/UI/Xaml/DependencyObjectStore.cs, src/Uno.UI/UI/Xaml/DependencyPropertyDetails.cs, src/Uno.UI/UI/Xaml/DependencyPropertyDetailsCollection.cs
GitHub Issue (If applicable): closes #16723
=> fix: Support preserving DP values when type replacement happens in HR

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.skia.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.skia.cs
GitHub Issue (If applicable): closes #16808
=> fix(textbox): pasting should scroll the textbox to the end of the pasted content

src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.skia.cs
GitHub Issue (If applicable): closes #16800
=> fix(textbox): dancing textbox selection

src/Uno.Sdk/targets/Uno.Common.MacCatalyst.targets
- Bugfix
Base version for Catalyst SDK is 15.0.
=> fix(net9): Adjust base version for catalyst

src/SamplesApp/SamplesApp.Shared/App.xaml.cs
=> chore: make SamplesApp feature flag cli-parsing work with nullable types

src/Uno.UI.Runtime.Skia.Wpf/UI/Controls/WpfWindowWrapper.cs
=> fix(wpf): going fullscreen then exiting doesn't go back to the previous window state

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs, src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.managed.cs
GitHub Issue (If applicable): closes #16799
=> Listview reordering updatelayout

doc/articles/uno-publishing-windows-packaged-signed.md
Suggestion for commands for the CLI to create msix packages and then bundle them into a msixbundle for store (or multiplatform) upload.
Additional guidance for creating a msix package and bundle for submittal to the Microsoft Store or to create a multiplatform installation.
=> docs: Update uno-publishing-windows-packaged-signed.md

.github/workflows/uwp-autoconvert.yml
This probably can make it more stable?
=> ci: Don't use manifest for uno.check

src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.skia.cs, src/Uno.UI/UI/Xaml/DependencyObjectStore.cs, src/Uno.UI/UI/Xaml/DependencyPropertyDetailsCollection.cs, src/Uno.UI/UI/Xaml/Internal/EventManager.uno.cs
GitHub Issue (If applicable): closes #17063
=> fix: Avoid using DependencyObjectStore after it has been disposed

src/Uno.UI.Composition/Composition/SkiaCompositionSurface.skia.cs
GitHub Issue (If applicable): closes #17041
=> fix: Updating SkiaCompositionSurface's image should invalidate render

src/Uno.Foundation/Metadata/ApiInformation.cs
GitHub Issue (If applicable): closes #17025
=> fix!: Change default NotImplementedLogLevel to Debug instead of Error

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/ConstructorCounterControl.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_Control.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/OnApplyTemplateCounterContentControl.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ItemsControl.cs, src/Uno.UI/UI/Xaml/Controls/Control/Control.cs, src/Uno.UI/UI/Xaml/Controls/FlipView/FlipView.managed.cs, src/Uno.UI/UI/Xaml/FrameworkElement.Layout.crossruntime.cs
GitHub Issue (If applicable): Wasm and Skia part of #190
=> fix: Properly apply template during measure after Loading

doc/articles/features/windows-ui-xaml-window.md
GitHub Issue (If applicable): internal 14-17
https://github.com/unoplatform/uno.toolkit.ui/pull/1153
Backport this PR when merged.
=> docs: Add videos on Windowing

src/Uno.UWP/UI/Colors.cs
GitHub Issue (If applicable): closes #11229
=> fix: Throw exception on invalid color instead of falling back to Red

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement.cs
GitHub Issue (If applicable): Part of https://github.com/unoplatform/uno/issues/7271
=> test: Remove conditional assert in When_MinWidth_SmallerThan_AvailableSize

src/Uno.UI.RemoteControl.VS/Helpers/VsHierarchyExtensions.HierarchyId.cs, src/Uno.UI.RemoteControl.VS/Helpers/VsHierarchyExtensions.cs
=> fix(vsix): Import HierarchyId for proper well known values alignment

doc/articles/logging.md
GitHub Issue (If applicable): closes #17038
Add Extensions Logging link when using Uno.Extensions:
=> docs: Add Extensions Logging link when using recommended

src/SourceGenerators/Uno.UI.SourceGenerators/Telemetry/TelemetryClient.cs, src/SourceGenerators/Uno.UI.SourceGenerators/Telemetry/TelemetryCommonProperties.cs
- Bugfix
Adjust hash persistence.
=> fix: Adjust telemetry persistence

src/Uno.UI.Runtime.Skia.MacOS/MacOSNativeWindowFactoryExtension.cs, src/Uno.UI.Runtime.Skia.MacOS/MacOSWindowNative.cs, src/Uno.UI.Runtime.Skia.MacOS/MacOSWindowWrapper.cs, src/Uno.UI.Runtime.Skia.Wpf/UI/Controls/UnoWpfWindow.cs, src/Uno.UI.Runtime.Skia.Wpf/UI/Controls/WpfWindowWrapper.cs, src/Uno.UI.Runtime.Skia.X11/X11WindowWrapper.cs, src/Uno.UI.Runtime.Skia.X11/X11XamlRootHost.cs, src/Uno.UI/UI/Xaml/Window/Native/NativeWindowWrapperBase.cs
GitHub Issue (If applicable): closes #16881
=> fix(skia): not activating the window shouldn't prevent the application from loading

src/Uno.UI.RuntimeTests/Tests/Microsoft_UI_Xaml_Controls/Given_TabView.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs, src/Uno.UI/UI/Xaml/Controls/Primitives/Selector.cs
GitHub Issue (If applicable): closes #17010
=> fix(selector): removing an item sometimes clear the current selection

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_NavigationView.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/NavigationView/NavigationViewItem.cs
GitHub Issue (If applicable): closes #15608
=> fix(navview): reflect changes when NavigationViewItem.MenuItems changes

src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/Breadcrumb/BreadcrumbTests.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/Breadcrumb/BreadcrumbBar.Header.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/Breadcrumb/BreadcrumbBar.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/Breadcrumb/BreadcrumbBar.properties.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/Breadcrumb/BreadcrumbBar.xaml, src/Uno.UI/Microsoft/UI/Xaml/Controls/Breadcrumb/BreadcrumbBarElementFactory.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/Breadcrumb/BreadcrumbBarItem.Header.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/Breadcrumb/BreadcrumbBarItem.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/Breadcrumb/BreadcrumbBarItemAutomationPeer.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/Breadcrumb/BreadcrumbBarItemClickedEventArgs.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/Breadcrumb/BreadcrumbBar_themeresources.xaml, src/Uno.UI/Microsoft/UI/Xaml/Controls/Breadcrumb/BreadcrumbIterable.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/Breadcrumb/BreadcrumbIterator.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/Breadcrumb/BreadcrumbLayout.Header.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/Breadcrumb/BreadcrumbLayout.cs
GitHub Issue (If applicable): related to #14275
- Bugfix
- Feature
Uses some static `FocusManager` code.
Avoids using the static `FocusManager` code.
=> feat: Update `BreadcrumbBar` to winui3/release/1.5.3

src/Uno.Analyzers.Tests/UnoInitializeComponentAnalyzerTests.cs, src/Uno.Analyzers/UnoInitializeComponentAnalyzer.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/private/issues/457
=> fix: Ignore constructor parameters in UnoInitializeComponentAnalyzer

doc/articles/features/windows-storage-pickers.md
related to https://github.com/unoplatform/uno/issues/16587
=> docs: uno target fileopen picker path information

src/SamplesApp/SamplesApp.Shared/App.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ToolTip/TextOnlyToolTipSample.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ToolTip/ToolTip_CollapsedHost.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ToolTip/ToolTip_DynamicContent.xaml.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Slider.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ToolTip.cs
GitHub Issue (If applicable): part of https://github.com/unoplatform/uno/issues/10791
Test
=> Enable tooltips on all targets for samples and tests

doc/articles/features/windows-storage-pickers.md, src/SamplesApp/UITests.Shared/Windows_Storage/Pickers/FileOpenPickerTests.xaml, src/SamplesApp/UITests.Shared/Windows_Storage/Pickers/FileOpenPickerTests.xaml.cs, src/Uno.UWP/Storage/Pickers/FileOpenPicker.cs, src/Uno.UWP/Storage/Pickers/FileOpenPicker.iOS.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/kahua-private/issues/145
=> feat(iOS): Add FileOpenPicker limit for multiple selection

src/Uno.UI.Runtime.Skia.X11/X11XamlRootHost.cs
GitHub Issue (If applicable): closes #17087
=> chore: set app icon in a background thread on X11

src/Uno.Sdk/targets/Uno.SingleProject.Wasm.targets
Related to https://github.com/unoplatform/uno.resizetizer/issues/288
- Cleanup
=> chore: Don't include PWA manifest in WASM layout

src/Uno.UI.Tests/Windows_Storage/Given_DataTypeSerializer.cs, src/Uno.UWP/Storage/ApplicationDataContainer.skia.cs, src/Uno.UWP/Storage/ApplicationDataContainer.wasm.cs, src/Uno.UWP/Storage/DataTypeSerializer.cs
GitHub Issue (If applicable): part of #1285
- Bugfix
=> Handle non-Uno settings in `DataTypeSerializer` gracefully, add tests

src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/TwoPaneView/TwoPaneViewTests.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TwoPaneView.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/TwoPaneView/TwoPaneView.cs
GitHub Issue (If applicable): closes #16839
=> fix: Workaround XamlRoot being null in OnApplyTemplate on Android

doc/articles/features/windows-storage-pickers.md
related to https://github.com/unoplatform/uno/issues/16587
=> docs: (fileopenpicker) refer how to get file information

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/ContentPresenter/ContentPresenter_Inside_ContentControl_Template.xaml, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/ContentPresenter/ContentPresenter_Inside_ContentControl_Template.xaml.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ContentPresenter.cs, src/Uno.UI/Controls/CommandBar/CommandBarRenderer.Android.cs, src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.cs, src/Uno.UI/UI/Xaml/DependencyObjectStore.Binder.cs, src/Uno.UI/UI/Xaml/DependencyPropertyDetailsCollection.Bindings.cs, src/Uno.UI/UI/Xaml/Media/VisualTreeHelper.cs
GitHub Issue (If applicable): closes #14662, closes #857, closes #7446, closes #6452
=> fix(contentpresenter): inherit Content, ContentTemplate and ContentTemplateSelector when inside a ContentControl template

src/Uno.UI.RuntimeTests/Tests/Windows_Storage/Given_ApplicationDataCompositeValue.cs, src/Uno.UI.RuntimeTests/Tests/Windows_Storage/Given_ApplicationDataContainer.cs, src/Uno.UI.Tests/Windows_Storage/Given_DataTypeSerializer.cs, src/Uno.UWP/Generated/3.0.0.0/Windows.Storage/ApplicationDataCompositeValue.cs, src/Uno.UWP/Storage/ApplicationData/ApplicationDataCompositeValue.cs, src/Uno.UWP/Storage/ApplicationDataContainer.Android.cs, src/Uno.UWP/Storage/ApplicationDataContainer.iOSmacOS.cs, src/Uno.UWP/Storage/DataTypeSerializer.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/11495
=> feat: Support for `ApplicationDataCompositeValue`

src/Uno.CrossTargetting.targets
- Bugfix
Local Android build is failing due to not method found.
=> chore: fix local build target override

src/Uno.UI/UI/Xaml/UIElement.cs
=> docs: Update exception message for layout cycle

src/Uno.UI.Runtime.Skia.X11/X11DisplayInformationExtension.cs, src/Uno.UI.Runtime.Skia.X11/X11XamlRootHost.cs, src/Uno.UI.Runtime.Skia.X11/X11XamlRootHost.x11events.cs, src/Uno.UI.Runtime.Skia.X11/X11_Bindings/X11Helper.cs, src/Uno.UI.Runtime.Skia.X11/X11_Bindings/x11bindings_XLib.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/478
=> chore: read DPI scaling from X resources

src/Uno.UWP/Storage/Pickers/FileOpenPicker.Android.cs
=> fix(droid): fileopenpicker ui thread

doc/articles/guides/solution-building-single-targetframework.md
GitHub Issue (If applicable): https://github.com/unoplatform/uno/discussions/15948#discussioncomment-9818421
=> docs: Adjust tfm restrictions for 5.2+ single project

doc/import_external_docs.ps1
Update Uno Extensions documentation to latest
=> docs: Update Uno Extensions documentation to latest

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Image.cs, src/Uno.UI/UI/Xaml/Media/Imaging/BitmapImage.skia.cs
GitHub Issue (If applicable): closes #17285
=> fix: Set PixelWidth and PixelHeight after decoding the image

src/Uno.UI/UI/Xaml/Documents/TextFormatting/FontDetailsCache.skia.cs
GitHub Issue (If applicable): closes #17287
=> fix: Fix NRE in FontDetailsCache

doc/articles/common-issues-uwp.md, doc/articles/common-issues.md, doc/articles/toc.yml
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno.extensions/issues/1606
=> docs: UWP Common issues

doc/articles/features/custom-fonts.md
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/17283
=> docs: Adjust custom font path for class libraries

build/ci/.azure-devops-skia-tests.yml
=> ci: Cleanup .azure-devops-skia-tests.yml

src/Uno.UI/Helpers/TypeMappings.cs
=> fix: Ensure `TypeMappings.CreateInstance` is linker friendly

src/Uno.UI.sln
=> fix: Deploy in iPhone configuration

src/SamplesApp/SamplesApp.netcoremobile/SamplesApp.netcoremobile.csproj, src/SolutionTemplate/5.1/uno51blank/Directory.Packages.props, src/SolutionTemplate/5.1/uno51recommended/Directory.Packages.props, src/SolutionTemplate/MyAppXamlTrim/MyAppXamlTrim.Mobile/MyAppXamlTrim.Mobile.csproj, src/SolutionTemplate/UnoAppAll/UnoAppAll.Mobile/UnoAppAll.Mobile.csproj, src/SolutionTemplate/UnoAppWinUI/UnoAppWinUI.Mobile/UnoAppWinUI.Mobile.csproj, src/Uno.Sdk/packages.json
GitHub Issue (If applicable): closes #16611
=> fix: Update UniversalImageLoader to respect Exif on Android

doc/articles/common-issues-all-ides.md
=> docs: Extend layout cycle docs

src/Uno.UI/DataBinding/BindingExpression.cs, src/Uno.UI/UI/Xaml/Controls/SplitView/SplitView.cs, src/Uno.UI/UI/Xaml/Controls/SplitView/SplitViewTemplateSettings.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs, src/Uno.UI/UI/Xaml/FrameworkPropertyMetadata.cs
=> refactor: Cleanup unnecessary GetMetadata calls

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.skia.cs, src/Uno.UI/UI/Xaml/Documents/InlineCollection.skia.cs, src/Uno.UI/UI/Xaml/Documents/TextFormatting/Segment.skia.cs
=> fix: Fix InlineCollection measure

src/Uno.UI.Dispatching/Dispatching/DispatcherQueue.cs, src/Uno.UI.Dispatching/Native/NativeDispatcher.cs, src/Uno.UI.Dispatching/Native/NativeDispatcher.unittests.cs, src/Uno.UI.Dispatching/Native/NativeDispatcher.wasm.cs, src/Uno.UI.RuntimeTests/IntegrationTests/common/TestServices.KeyboardHelper.cs, src/Uno.UI.RuntimeTests/IntegrationTests/common/TestServices.cs, src/Uno.UI.RuntimeTests/MUX/Utilities/RunOnUIThread.cs, src/Uno.UI.RuntimeTests/Tests/Windows_System/Given_DispatcherQueueTimer.cs, src/Uno.UI/UI/Xaml/DependencyProperty.cs, src/Uno.UI/UI/Xaml/DispatcherConditionalDisposable.cs, src/Uno.UI/UI/Xaml/DragDrop/DragDropManager.cs, src/Uno.UWP/System/DispatcherQueue.cs, src/Uno.UWP/UI/Core/CoreDispatcher.unittests.cs, src/Uno.UWP/UI/Core/CoreDispatcher.wasm.cs
=> fix: HasThreadAccess should be true on Wasm when threading not supported

src/Uno.UI.Composition/Composition/ContainerVisual.skia.cs, src/Uno.UI.Composition/Composition/Visual.skia.cs, src/Uno.UI/UI/Xaml/Controls/Control/Control.mux.cs, src/Uno.UI/UI/Xaml/Media/VisualTreeHelper.cs
GitHub Issue (If applicable): closes #17389, closes #17388, closes #17390
=> perf: Misc performance improvements

build/PackageDiffIgnore.xml, src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs, src/Uno.UI.RuntimeTests/Helpers/UITestHelper.cs, src/Uno.UI.RuntimeTests/IntegrationTests/common/TestServices.WindowHelper.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Markup/Given_MarkupExtension.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Markup/MarkupExtension_ParserContext.xaml, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Markup/MarkupExtension_ParserContext_RD.xaml, src/Uno.UI/Helpers/MarkupHelper.cs, src/Uno.UI/UI/Xaml/Markup/XamlServiceProviderContext.cs
- Feature
Added support for `IRootObjectProvider` in `MarkupExtensions.ProvideValue(IXamlServiceProvider)`
=> feat(markup): IRootObjectProvider

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Markup/Given_XamlReader.cs, src/Uno.UI/DataBinding/BindingPropertyHelper.FastConvert.cs
=> fix: Add missing support for DoubleCollection and PointCollection to FastConvert

src/Uno.UI.Composition/Composition/CompositionBrushWrapper.skia.cs, src/Uno.UI.Composition/Composition/CompositionSpriteShape.skia.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/ScrollPresenter/ScrollPresenter.Uno.cs, src/Uno.UI/Microsoft/UI/Xaml/Media/RadialGradientBrush.skia.cs, src/Uno.UI/UI/Xaml/BorderHelper.skia.cs, src/Uno.UI/UI/Xaml/Controls/Border/Border.IBorderInfoProvider.cs, src/Uno.UI/UI/Xaml/Controls/Border/Border.cs, src/Uno.UI/UI/Xaml/Controls/Border/IBorderInfoProvider.cs, src/Uno.UI/UI/Xaml/Controls/CalendarView/CalendarViewBaseItem.IBorderInfoProvider.cs, src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.IBorderInfoProvider.cs, src/Uno.UI/UI/Xaml/Controls/Page/Page.IBorderInfoProvider.cs, src/Uno.UI/UI/Xaml/Controls/Panel/Panel.IBorderInfoProvider.cs, src/Uno.UI/UI/Xaml/Media/AcrylicBrush/AcrylicBrush.skia.cs, src/Uno.UI/UI/Xaml/Media/Brush.cs, src/Uno.UI/UI/Xaml/Media/Brush.skia.cs, src/Uno.UI/UI/Xaml/Media/ImageBrush.skia.cs, src/Uno.UI/UI/Xaml/Media/LinearGradientBrush.skia.cs, src/Uno.UI/UI/Xaml/Media/SolidColorBrush.skia.cs, src/Uno.UI/UI/Xaml/Media/XamlCompositionBrushBase.skia.cs, src/Uno.UI/UI/Xaml/Shapes/Shape.cs, src/Uno.UI/UI/Xaml/Shapes/Shape.skia.cs
GitHub Issue (If applicable): closes #8891
=> refactor: Refactor Skia brushes

src/Uno.UI/UI/Xaml/Internal/ContentRootCoordinator.cs
GitHub Issue (If applicable): closes #15804
=> perf: Avoid enumerator boxing

src/Uno.UI/UI/Xaml/Media/XamlCompositionBrushBase.skia.cs
=> build: Fix master build

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_UIElement.cs
GitHub Issue (If applicable): closes #13299
=> test: Add test for DesiredSize after removing UIElement from visual tree

src/Uno.UI/UI/Xaml/VisualStateGroup.cs
=> perf: Avoid OfTypeIterator allocations

src/Uno.UI.Composition/Composition/CompositionStrokeDashArray.cs, src/Uno.UI/UI/Xaml/Shapes/Shape.skia.cs
=> fix: Pass Compositor to CompositionStrokeDashArray

src/Uno.UI.Tests/Windows_UI_Xaml_Media/Given_FontMatching.cs, src/Uno.UI/UI/Xaml/FontManifestHelpers.cs
GitHub Issue (If applicable): closes #17394
=> feat: Implement font matching spec

doc/articles/features/windows-ui-xaml-window.md, src/Uno.UI.Runtime.Skia.X11/X11WindowWrapper.cs
GitHub Issue (If applicable): closes #17194
=> chore: expose the NativeWindow as a X11NativeWindow instead of the internal X11Window

src/Uno.UI.RuntimeTests/Tests/Microsoft_UI_Xaml_Controls/Given_TreeView.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_UIElement.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs, src/Uno.UI/UI/Xaml/DragDrop/DragOperation.cs, src/Uno.UI/UI/Xaml/UIElement.Pointers.cs
GitHub Issue (If applicable): closes #17342
=> fix(treeview): fix dragging in some cases causing an NRE

src/Uno.UI/UI/Xaml/UIElement.Layout.crossruntime.cs
=> chore: Extend layout cycle tracing logging

src/AddIns/Uno.UI.Lottie/Uno.UI.Lottie.netcoremobile.csproj, src/AddIns/Uno.UI.MSAL/Uno.UI.MSAL.netcoremobile.csproj, src/AddIns/Uno.UI.Svg/Uno.UI.Svg.netcoremobile.csproj, src/Uno.CrossTargetting.targets, src/Uno.UI.Foldable/Uno.UI.Foldable.netcoremobile.csproj, src/Uno.UI.Toolkit/Uno.UI.Toolkit.netcoremobile.csproj
=> build: Fix NuGet override for Android

src/Uno.UI.FluentTheme.v1/Resources/Version1/PriorityDefault/MediaTransportControls_themeresources.xaml, src/Uno.UI.FluentTheme.v1/themeresources_v1.xaml, src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault/MediaTransportControls_themeresources.xaml, src/Uno.UI.FluentTheme.v2/themeresources_v2.xaml, src/Uno.UI/Controls/CommandBar/CommandBarHelper.iOS.cs
- Bugfix
The MPE in iOS, when used in combination with NativeFrameNavigation, does not display the Player Controls correctly, preventing the user from using them.
=> fix(iOS): MediaPlayerElement controls visibility

doc/articles/features/working-with-xaml-hot-reload.md
GitHub Issue (If applicable): https://github.com/unoplatform/uno-private/issues/501
- Documentation content changes (bugfix)
Caused by #17435, indicator section is only visible in the WinAppSDK tab:
The HotReload Indicator section is not part of the tabs anymore, it is part of the root page.
=> docs: fix hotreload tabs

doc/articles/getting-started/wizard/includes/framework.md
The description mentions Net 7.0, and it does not match the available versions listed below.
The description mentions Net 9.0 preview, which matches the available versions listed below.
=> docs: Update framework.md to fix description

doc/articles/features/custom-fonts.md, src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props, src/SourceGenerators/Uno.UI.SourceGenerators/UseOpenSansGenerator.cs, src/Uno.Sdk/Sdk/Sdk.props.buildschema.json, src/Uno.Sdk/UnoFeature.cs, src/Uno.Sdk/packages.json, src/Uno.Sdk/targets/Uno.Common.targets, src/Uno.Sdk/targets/Uno.Features.targets, src/Uno.Sdk/targets/Uno.Implicit.Packages.ProjectSystem.targets
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/515
=> chore: Follow-up on OpenSans

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBlock.cs, src/Uno.UI/UI/Xaml/Documents/TextFormatting/FontDetailsCache.skia.cs
GitHub Issue (If applicable): closes #17471
=> fix(skia): Fix FontFamily support when ms-appx file contains "#"

doc/articles/uno-build-error-codes.md, src/Uno.Sdk/targets/Uno.Sdk.After.targets, src/Uno.UI.RemoteControl.VS/DebuggerHelper/ProfilesObserver.cs, src/Uno.UI.RemoteControl.VS/EntryPoint.ActiveProfileSync.cs, src/Uno.UI.RemoteControl.VS/EntryPoint.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/17475, closes https://github.com/unoplatform/private/issues/484, closes https://github.com/unoplatform/private/issues/486, closes https://github.com/unoplatform/private/issues/485
- Bugfix
- Include a debouncing mechanism to avoid competing with VS's own profile changes
- Warn when net8.0 is the first TFM
=> Misc TFM synchronization issues

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ComboBox.cs, src/Uno.UI/UI/Xaml/Controls/ComboBox/ComboBox.cs, src/Uno.UI/UI/Xaml/Controls/Primitives/Selector.cs
GitHub Issue (If applicable): closes #17491
=> fix(combobox): Fix pointer wheel not working on ComboBox

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Button.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.cs
GitHub Issue (If applicable): related to #7621
Additional test for linked issue
=> test: Ensure `BorderThickness` is taken into account for Fluent controls

doc/articles/uno-build-error-codes.md
=> docs: Fix build error codes

src/Uno.UI.RemoteControl.VS/EntryPoint.ActiveProfileSync.cs
- Bugfix
- Adjust the reload behavior to debounce iOS updates, to avoid invalid changes when VS auto adjusts the active profile.
- Remove Startup project adjustment which is not needed now that we can do in-place reloads.
=> fix: Adjust target/profile de-bouncing for WASDK to iOS/Android

src/Uno.UI.Runtime.Skia.Gtk/UI/Controls/UnoGtkWindowHost.cs, src/Uno.UI.Runtime.Skia.Wpf/UI/Controls/UnoCompositeWindowHost.cs
GitHub Issue (If applicable): closes #17478
=> chore: remove warning if Window.Background is null

src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.MetadataUpdate.cs, src/Uno.UI.RemoteControl/Uno.UI.RemoteControl.Wasm.csproj, src/Uno.UI/WasmCSS/Uno.UI.css
closes https://github.com/unoplatform/uno-private/issues/523
closes https://github.com/unoplatform/uno-private/issues/516
Fix double flicker + double notif on wasm
=> fix(hrui): Fix double flicker + double notif on wasm

doc/articles/create-an-app-rider.md, doc/articles/uno-build-error-codes.md, src/Uno.Sdk/targets/Uno.Build.targets
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno.rider/issues/54
- Bugfix
Provide an explicit error when building a solution with Rider.
=> fix: Fail build on Rider IDE using unsupported targets

src/Uno.UI.RemoteControl/HotReload/HotReloadStatusView.xaml
closes https://github.com/unoplatform/uno-private/issues/524#top
=> fix(hrui): Fix invalid layout on iOS

doc/articles/includes/how-tos-and-tutorials-inline-toc.md
GitHub Issue (If applicable): closes #16783
- Bugfix
=> docs: Fix Uno.Samples linking issue

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBlock.cs, src/Uno.UI/UI/Xaml/Documents/Run.skia.cs
GitHub Issue (If applicable): closes #16676
=> fix: Fix text shaping when using font fallback on Skia

src/Uno.UI/UI/Xaml/Media/Animation/Timeline.cs
=> chore: Cleanup unused method

build/PackageDiffIgnore.xml
=> build: Update PackageDiffIgnore

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_UIElement.cs, src/Uno.UI/UI/Xaml/UIElement.cs
GitHub Issue (If applicable): closes #17642
=> fix: Fix Clip changes during arrange causing layout cycle

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_UIElement.cs
=> build: Fix failing build

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI/Given_FontWeight.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI/PageContainingNumericFontWeight.xaml, src/Uno.UI.RuntimeTests/Tests/Windows_UI/PageContainingNumericFontWeight.xaml.cs
GitHub Issue (If applicable): closes #17536
=> fix(xamlgen): Fix numeric FontWeight not working

doc/articles/migrating-from-previous-releases.md
Migrating documentation: Document VS extension update for 5.3
=> docs(Migrating): Document VS extension update for 5.3

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Data/Given_BindingExpression.cs, src/Uno.UI/UI/Xaml/Data/Binding.cs
=> fix: Fix parameterless Binding constructor not having correct defaults

src/Uno.UI.RemoteControl.VS/EntryPoint.cs
- Bugfix
Adds more guards around devserver startup to avoid duplicate calls and potentially orphaned server ports.
=> fix(rc): Potential race condition when starting the dev server

src/Uno.UI/UI/Xaml/Documents/TextFormatting/FontDetailsCache.skia.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/604
=> fix: Improve font caching logic

src/Uno.UI/UI/Xaml/Input/Internal/FocusProperties.cs
GitHub Issue (If applicable): closes #17627
=> fix: Avoid checking for focus on non-live elements

NuGet.Config, src/Directory.Build.props
=> chore(deps): Use Roslyn 4.11 from NuGet.org instead of Azure feed

build/PackageDiffIgnore.xml, build/nuget/Uno.WinUI.nuspec
GitHub Issue (If applicable): closes #17694
=> build: Cleanup Uno.Foundation.Logging binaries from Uno.WinUI package

src/SourceGenerators/Uno.UI.SourceGenerators/BindableTypeProviders/BindableTypeProvidersGenerationTask.cs
=> fix: Fix invalid code gen if project has System namespace

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBlock.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Documents/Given_Run.cs, src/Uno.UI/UI/Xaml/Documents/Run.skia.cs, src/Uno.UI/UI/Xaml/Documents/TextFormatting/Segment.skia.cs
Code is hard to follow and maintain
More easier to follow the code
=> refactor: Refactor GetSegments

doc/articles/common-issues-vscode.md
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/17732
=> docs: Adjust vscode troubleshooting

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs, src/Uno.UI.RuntimeTests/Resources/en-US/Resources.resw, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/When_xUid_On_Root.xaml, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/When_xUid_On_Root.xaml.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_xUid.cs
GitHub Issue (If applicable): closes #17749
=> fix: Fix missing `x:Uid` generation for the root of XAML

src/SamplesApp/SamplesApp.UITests/TestFramework/ImageAssert.cs, src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TextBoxTests/TextBoxTests.cs, src/SamplesApp/UITests.Shared/UITests.Shared.projitems, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_VerticalAlignment.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_VerticalAlignment.xaml.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.wasm.cs, src/Uno.UI/UI/Xaml/Window/WindowManagerInterop.wasm.cs, src/Uno.UI/WasmCSS/Uno.UI.css, src/Uno.UI/ts/WindowManager.ts
GitHub Issue (If applicable): closes #16568
=> fix(wasm): Fix TextBox default alignment

src/Uno.UI/UI/Xaml/Media/Animation/Animators/GPUFloatValueAnimator.iOSmacOS.cs, src/Uno.UI/UI/Xaml/Media/Transform.cs
- Bugfix
A few crashes on iOS apps have been reported when navigating. We saw in the logs this crash is related to animations. We could not reproduce the error, but after enabling nullable, we found a few places where we could prevent a crash.
=> Workaround: (iOS) animation crash when navigating

src/Uno.UI.Composition/Composition/KeyFrameAnimations/ScalarKeyFrameAnimation.cs
=> chore: Remove dead net7.0 code

src/Uno.UI.Composition/SkiaCompat.skia.cs
=> chore: Cleanup SkiaCompat

src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.cs
GitHub Issue (If applicable): Part of #17773
=> fix: Fix incorrect DP inheritance for ScrollViewer properties

build/nuget/Uno.WinUI.XamlHost.nuspec
=> fix: Place Uno.WinUI.XamlHost.props buildTransitive

src/SamplesApp/UITests.Shared/UITests.Shared.projitems, src/SamplesApp/UITests.Shared/Windows_UI_ViewManagement/AndroidWindowInsets.xaml, src/SamplesApp/UITests.Shared/Windows_UI_ViewManagement/AndroidWindowInsets.xaml.cs, src/Uno.UI/UI/Xaml/Window/Native/NativeWindowWrapper.Android.cs
=> fix(android): inset calculations in landscape mode when the device has a notch

src/Uno.UWP/ApplicationModel/Resources/ResourceLoader.static.cs
=> perf(memory): Span-ify ResourceLoader

src/Uno.UI/UI/Xaml/UIElement.cs
GitHub Issue (If applicable): Related to #17773
=> fix: Remove incorrect inheritance from XYFocusKeyboardNavigation

src/Uno.UI.Composition/Composition/CompositionSpriteShape.skia.cs
=> perf: Avoid double dictionary lookup in SkiaSharp

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_ResourceDictionary.cs, src/Uno.UI/UI/Xaml/Controls/CalendarView/CalendarViewBaseItem.cs, src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.cs, src/Uno.UI/UI/Xaml/Controls/FlipView/FlipView.managed.cs, src/Uno.UI/UI/Xaml/Controls/Primitives/ButtonBase/ButtonBase.mux.cs, src/Uno.UI/UI/Xaml/FrameworkElement.Layout.crossruntime.cs, src/Uno.UI/UI/Xaml/ResourceDictionary.cs, src/Uno.UI/UI/Xaml/UIElement.crossruntime.cs, src/Uno.UI/UI/Xaml/UIElement.mux.cs
=> refactor: Refactor Enter/Leave

src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Button/AppBar_KeyBoard.xaml, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/ContentDialog_Leak.xaml.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/ItemsControl_ItemsSource_Leak.xaml.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement_And_Leak.cs
=> test: Run When_Add_Remove on WinAppSDK

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_DependencyProperty.cs, src/Uno.UI/DataBinding/BindingPath.BindingItem.cs, src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.cs, src/Uno.UI/UI/Xaml/DependencyPropertyDetails.cs
GitHub Issue (If applicable): closes #17825
=> fix: Fix GetValueUnderPrecedence logic when only local value is set

doc/articles/toc.yml
=> docs: Move Why use Uno in toc

src/Uno.UI.Runtime.Skia.Wpf/Builder/WpfHostBuilder.cs
=> feat: Add WPF SelfContained support

build/ci/.azure-devops-ios-tests.yml
RuntimeIdentifier is set globally during build, causing it to flow to non-iOS-related projects like Uno.UI.Tasks, which is unnecessary, and currently causes some vulnerability warnings. The vulnerability warnings are already false positives (i.e, bug) from NuGet side. We can workaround those warnings differently, but it makes more sense to not pull iOS-related stuff for Uno.UI.Tasks build.
Note that we already set RuntimeIdentifier here:
https://github.com/unoplatform/uno/blob/34d96b195c7e79db84bffce9ba00d9a627e80f59/src/SamplesApp/SamplesApp.netcoremobile/SamplesApp.netcoremobile.csproj#L74-L81
Internal Issue (If …
=> build: Fix iOS test flight build

doc/articles/contributing/guidelines/code-style.md
=> docs: Fix the format in code-style.md

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBlock.cs, src/Uno.UI/UI/Xaml/Documents/Run.skia.cs
=> fix: Ensure tabs are their own segment

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement_And_Leak.cs
GitHub Issue (If applicable): related to #9080
=> test: Disable flaky `BreadcrumbBar` leak test on iOS (#9080)

src/SamplesApp/SamplesApp.Shared/App.xaml, src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Controls/SampleChooserControl.xaml, src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Styles/Controls/Button.xaml, src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Styles/Controls/Path.xaml, src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Styles/Controls/RadioButton.xaml, src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Styles/Controls/TextBlock.xaml, src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Styles/Controls/TextBox.xaml, src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Styles/Controls/ToggleButton.xaml
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/17801
- Feature
- Bugfix
- App looks very iOSy
- Dark theme does not work for the app's shell
- Improved!
=> feat: Support dark theme in Samples app list, update iconography

src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.iOS.cs
GitHub Issue (If applicable): closes #17682
Warning always happens on first use of any `TextBox` on iOS
- The initial value of both IsTextPredictionEnabled and IsSpellCheckEnabled is true, so it is not useful to warn the user.
- When user changes IsTextPredictionEnabled explicitly to a value which does not match IsSpellCheckEnabled, we warn that it will have no effect and suggest IsSpellCheckEnabled instead.
- We only display the warning when the level is enabled
=> fix: Make `IsTextPredictionEnabled` warnings less frequent

doc/articles/get-started.md
Links should open in a separate tab so users don't lose track of the current get started guide details.
=> docs: Update get-started.md to adjust the Quick Start section

src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CalendarView/CalendarView_Theming.xaml.cs, src/Uno.UWP/Helpers/Theming/SystemThemeHelper.Android.cs, src/Uno.UWP/Helpers/Theming/SystemThemeHelper.iOS.cs, src/Uno.UWP/Helpers/Theming/SystemThemeHelper.macOS.cs, src/Uno.UWP/Helpers/Theming/SystemThemeHelper.others.cs, src/Uno.UWP/Helpers/Theming/SystemThemeHelper.skia.cs, src/Uno.UWP/Helpers/Theming/SystemThemeHelper.wasm.cs
GitHub Issue (If applicable): This got broken in https://github.com/unoplatform/uno/commit/1e1e91d9778e3716fd107e5396019eb97e6be9df
Closes #17830
=> fix(sample): Fix CalendarView_Theming sample on Wasm

README.md
PROPOSAL: We could update the badges for visual consistency, as they currently use different styles and colors. With this change, all badges will adopt the same style, and the colors will be updated to match similar functions and use Uno colors where possible. Feel free to discuss/propose changes. 
- README update
=> chore: Update README.md badges for visual consistency

src/Uno.Sdk/targets/Uno.DefaultItems.Resizetizer.targets
=> fix: Adjust the default icon scale

src/Uno.UI.RuntimeTests/Tests/Microsoft_UI_Xaml_Controls/Given_TreeView.cs, src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.cs, src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml
GitHub Issue (If applicable): closes #11942
=> fix(treeview): an ItemTemplateSelector with DataTemplates that don't have a TreeViewItem as the root failed to work

doc/articles/features/working-with-xaml-hot-reload.md
=> docs: Add info to refresh dev-server port

src/Uno.UI.Runtime.Skia.X11/X11WindowWrapper.cs, src/Uno.UI.Runtime.Skia.X11/X11XamlRootHost.x11events.cs
GitHub Issue (If applicable): closes #17816
=> fix: WSL not starting up

build/nuget/uno.winui.winappsdk.targets
=> build: Copy WinAppSDK fix

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs, src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.DragDrop.cs
GitHub Issue (If applicable): closes #17517
=> fix(listview): dragging when ItemsSource is a subclass of ObservableCollection

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ScrollViewer.cs, src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.cs
=> fix(ScrollViewer): Fix margin included twice in Extent[Width/Height] when Actual[Width/Height] is zero

src/Uno.UI.Runtime.Skia.Gtk/GtkHost.cs, src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/FramebufferHost.cs, src/Uno.UI.Runtime.Skia.MacOS/MacSkiaHost.cs, src/Uno.UI.Runtime.Skia.Wpf/WpfHost.cs, src/Uno.UI.Runtime.Skia.X11/X11ApplicationHost.cs, src/Uno.UI/UI/Xaml/Application.skia.cs
=> refactor: Refactor Application.Start

src/Uno.UI/UI/Xaml/Application.cs
=> fix(android): Avoid multiple calls to InitializationCompleted

src/Uno.UI/UI/Xaml/Input/PointerRoutedEventArgs.Managed.cs
=> perf: Make GetCurrentPoint allocation-less

src/SamplesApp/SamplesApp.Shared/App.xaml.cs, src/Uno.UI/UI/Xaml/Application.skia.cs
=> fix: OnLaunched should be called synchronously with app initialization

doc/articles/create-an-app-rider.md
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno.rider/issues/89
Adjust link and details for the Rider issue on macOS for WebAssembly.
=> docs: Update create-an-app-rider.md for Rider issue link

src/Uno.UI.Runtime.Skia.X11/X11PointerInputSource.Mouse.cs, src/Uno.UI.Runtime.Skia.X11/X11PointerInputSource.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_UIElement.cs, src/Uno.UI/UI/Xaml/Internal/InputManager.Pointers.Managed.cs
GitHub Issue (If applicable): closes #16801
=> fix(pointers): do not respond to multiple mouse button presses at the same time

src/Uno.UI.Composition/Composition/ColorBrushTransitionState.skia.cs, src/Uno.UI.Composition/Composition/Compositor.skia.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_BackgroundTransition.cs, src/Uno.UI/UI/Xaml/BorderHelper.skia.cs, src/Uno.UI/UI/Xaml/Controls/Border/Border.cs, src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.cs, src/Uno.UI/UI/Xaml/Controls/Panel/Panel.cs, src/Uno.UI/UI/Xaml/DependencyPropertyDetails.cs
=> BackgroundTransition fixes

src/Uno.UI/Uno.UI.Reference.csproj, src/Uno.UI/Uno.UI.Skia.csproj, src/Uno.UI/Uno.UI.Tests.csproj, src/Uno.UI/Uno.UI.netcoremobile.csproj, src/Uno.UWP/Uno.netcoremobile.csproj
=> build: Remove outdated workarounds

build/ci/.azure-devops-unit-tests.yml, src/SourceGenerators/Uno.UI.SourceGenerators.Tests/DependencyObjectGeneratorTests/Given_DependencyObjectGenerator.cs
=> test: Adjust Given_DependencyObjectGenerator

src/SamplesApp/SamplesApp.Shared/App.xaml.cs
=> fix(samplesapp): Adjust assert relevant only to Skia

src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TextBoxTests/TextBoxTests.cs
=> test: Disable flaky test

src/Uno.UI.Runtime.WebAssembly/buildTransitive/Uno.UI.Runtime.WebAssembly.targets
GitHub Issue (If applicable): closes #17852
=> fix: Skip _ForceUnoUIRuntimeWasm when it will result in an error

src/Uno.UI.Tests/DependencyProperty/Given_DependencyProperty.AttachedPropagation.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/LayoutPanel/LayoutPanel.Properties.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/LayoutPanel/LayoutPanel.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/UniformGridLayout/UniformGridLayout.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/UniformGridLayout/UniformGridLayout.properties.cs, src/Uno.UI/UI/Xaml/Controls/Primitives/LoopingSelector/LoopingSelector.Properties.cs, src/Uno.UI/UI/Xaml/Controls/Primitives/LoopingSelector/LoopingSelector_Partial.cs, src/Uno.UI/UI/Xaml/DependencyObjectStore.cs, src/Uno.UI/UI/Xaml/DependencyProperty.cs
=> fix: Fix inherited attached DP propagation and refactor few RegisterPropertyChangedCallback callsites

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_AutoSuggestBox.cs, src/Uno.UI/UI/Xaml/Controls/AutoSuggestBox/AutoSuggestBox.cs, src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.managed.cs
GitHub Issue (If applicable): closes #11876, closes #17907
=> fix(autosuggestbox): bring selected item from popup into view + resize popup to match the size of the ASB changes

src/Uno.UI/UI/Xaml/DependencyObjectStore.cs
=> perf: Simplify inherited DP check

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Border.cs, src/Uno.UI/UI/Xaml/Controls/Border/Border.cs, src/Uno.UI/UI/Xaml/Media/VisualTreeHelper.cs
GitHub Issue (If applicable): closes #17972
=> fix: Maximizing causes the app to not be responsive

src/Uno.UI/UI/Xaml/Media/Animation/ObjectKeyFrame.cs
=> perf: Don't use null default DP for value types to avoid Activator.CreateInstance

src/Uno.UI.Runtime.Skia.Wpf/Input/WpfCorePointerInputSource.cs
GitHub Issue (If applicable): closes #16769
=> fix(wpf): queue pointer Exited when it happens during ReleaseMouseCapture

doc/articles/guides/localization.md, doc/articles/splash-screen.md
=> docs: Fix typo

doc/articles/feature-flags.md, src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewMode.Properties.cs, src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Controls/SampleChooserControl.xaml, src/Uno.UI/FeatureConfiguration.cs, src/Uno.UI/UI/Xaml/Controls/Popup/PopupRoot.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/17979
Debugging controls and UI with light-dismiss is painful as everything is closed when debugger breakpoint is hit.
Setting the new flag to `true` makes it easier to debug light-dismiss UI.
=> feat: Prevent light-dismiss on window deactivation flag

doc/import_external_docs.ps1
Update Uno.Extensions documentaton to latest to fix typo
Related PRs:
- https://github.com/unoplatform/uno.extensions/pull/2519
- https://github.com/unoplatform/uno/pull/17989
=> docs: Update Uno.Extensions to latest to fix typo

doc/articles/features/windows-networking.md
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/17962
The information on subscribing to changes is not valid
=> docs: Adjust Networking information

src/Uno.UI.RuntimeTests/IntegrationTests/dxaml/Event.cs, src/Uno.UI.RuntimeTests/IntegrationTests/dxaml/controls/appbar/AppBarIntegrationTests.cs, src/Uno.UI.RuntimeTests/IntegrationTests/dxaml/controls/calendarview/CalendarViewIntegrationTests.cs, src/Uno.UI.RuntimeTests/IntegrationTests/dxaml/controls/commandbar/CommandBarIntegrationTests.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ContentDialog.cs
=> fix: Correctly throw for `Event.WaitFor` timeouts

src/Uno.UI/UI/Xaml/UIElement.mux.cs
=> chore: Fix Uno-specific comment

README.md
- Feature
The widget needs to be first enabled by admin on Discord. CC @mtmattei 
=> chore: Add Discord badge

src/Uno.UI/UI/Xaml/Media/Imaging/RenderTargetBitmap.cs
GitHub Issue (If applicable): related to https://github.com/unoplatform/uno/discussions/18016
- Bugfix
Ctor does not have correct NotImplemented
Adjusted
=> fix: Correct NotImplemented on RenderTargetBitmap ctor

build/PackageDiffIgnore.xml, doc/articles/features/unhandled-exceptions.md, doc/articles/toc.yml, src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs, src/Uno.UI/Generated/3.0.0.0/Microsoft.UI.Xaml/UnhandledExceptionEventHandler.cs, src/Uno.UI/UI/Xaml/UnhandledExceptionEventArgs.cs, src/Uno.UI/UI/Xaml/UnhandledExceptionEventHandler.cs
- Feature
Currently some issues go unnoticed quietly under the rader
In debug, the issues are always logged and debugger breaks in case `DISABLE_XAML_GENERATED_BREAK_ON_UNHANDLED_EXCEPTION` is not defined (in-line with WinUI)
=> feat: Add a generic `Application.UnhandledException` handler

doc/articles/common-issues-all-ides.md
docs: Add "delete Uno.Sdk` from NuGet global-packages store as action for "Could not resolve Uno.Sdk"
Experienced this issue and none of the recommended approaches worked.
Arter deleting the `Uno.Sdk` folder from my dev machine's NuGet global-packages store, I was able to load Uno projects.
=> docs: Add "delete Uno.Sdk` from NuGet global-packages store as action for "Could not resolve Uno.Sdk"

src/Uno.UI.Runtime.Skia.X11/X11NativeElementHostingExtension.cs, src/Uno.UI.Runtime.Skia.X11/X11NativeElementHostingExtension.helper.cs, src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/private/issues/513
=> fix: startup issues on WSL

doc/articles/getting-started/counterapp/get-started-counter-csharp-mvux.md, doc/articles/getting-started/counterapp/get-started-counter-xaml-mvux.md
GitHub Issue (If applicable): closes # https://github.com/unoplatform/uno.extensions-private/issues/208
=> docs: update docs for MVUX generated class

doc/articles/create-an-app-rider.md, doc/articles/get-started-rider.md
GitHub Issue (If applicable): related to https://github.com/unoplatform/uno.rider/issues/100
Update Rider plugin documentation to prioritize version 2024.2 now that it is the current stable release of Rider IDE
=> Docs: Update Rider plugin documentation to prioritize version 2024.2 now that it is the current stable release of Rider IDE

doc/articles/supported-libraries.md
GitHub Issue (If applicable): related to https://github.com/unoplatform/private/issues/470
Add ScottPlot to the 3rd-party libraries list
=> docs: Add ScottPlot to the 3rd-party libraries list

doc/articles/getting-started/requirements.md
=> docs: Adjust Supported platforms page

src/Uno.UWPSyncGenerator/Uno.UWPSyncGenerator.csproj
=> build: Fix build failing due to vulnerabilities

doc/README.md
Changed wording to avoid using "here" for link text. 
GitHub Issue (If applicable): part of #15048
The link that directs you to the setup guide for DocFx is named as "here".
Changed the word to a more descriptive link name as well as the entire sentence.
- [ x] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ x] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ …
=> Docs: Update README.md change "here" link text

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_DependencyProperty.cs, src/Uno.UI/Generated/3.0.0.0/Microsoft.UI.Xaml/PropertyMetadata.cs, src/Uno.UI/UI/Xaml/DependencyProperty.cs, src/Uno.UI/UI/Xaml/FrameworkPropertyMetadata.cs, src/Uno.UI/UI/Xaml/PropertyMetadata.cs
GitHub Issue (If applicable): closes #4347, closes #9989
=> feat: Implement CreateDefaultValueCallback and PropertyMetadata factory methods

src/SourceGenerators/Uno.UI.SourceGenerators/BindableTypeProviders/BindableTypeProvidersGenerationTask.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Data/BindableNullableValueTypeTestPage.xaml.cs
GitHub Issue (If applicable): closes #18076
=> fix: Consider init-only properties as not settable in bindable type generator

build/ci/.azure-devops-ios-tests.yml, build/test-scripts/ios-uitest-build.sh
=> build: Fix TestFlight build

src/Uno.UI.Composition/Composition/ContainerVisual.skia.cs
Very minor allocations, but fix is small enough to take :)
=> perf: Avoid unnecessary boxing enumeration in ResetRenderOrder

doc/articles/controls/WebView.md, doc/articles/feature-flags.md, src/Uno.UI/FeatureConfiguration.cs, src/Uno.UI/UI/Xaml/Controls/WebView/Native/iOSmacOS/UnoWKWebView.iOSmacOS.cs
related to https://github.com/unoplatform/uno/discussions/18041
- Bugfix
Developers can use a feature flag to enable the `Inspectable` feature on WebView2 for iOS and Catalyst apps.
=> feat: ios inspectable on webview2

src/Uno.UI/UI/Xaml/DependencyObjectStore.cs, src/Uno.UI/UI/Xaml/DependencyPropertyDetails.cs, src/Uno.UI/UI/Xaml/DependencyPropertyDetailsCollection.Bindings.cs, src/Uno.UI/UI/Xaml/DependencyPropertyDetailsCollection.cs
=> perf: Remove no-longer-used fields

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_DependencyProperty.cs, src/Uno.UI/UI/Xaml/Controls/Control/Control.cs, src/Uno.UI/UI/Xaml/Controls/UserControl/UserControl.cs, src/Uno.UI/UI/Xaml/DependencyProperty.cs, src/Uno.UI/UI/Xaml/UIElement.cs
=> fix: Make GetMetadata aware of IsTabStop default value

src/Uno.Sdk/packages.json
=> chore(deps): Update Uno.Resizetizer

build/ci/.azure-devops-project-template-tests.yml
=> ci: Increase template tests timeout

src/Uno.UI/UI/Xaml/DependencyObjectStore.Binder.cs
=> refactor: Remove unused delegate types

src/Uno.UI/UI/Xaml/Documents/TextFormatting/FontDetailsCache.skia.cs
=> fix: Compare the right font in OnFontLoaded when FontFamily contains '#'

doc/import_external_docs.ps1
Update Uno.Extensions documentation to latest
=> docs: Update Uno.Extensions to latest

doc/articles/guides/how-to-create-control-libraries.md
There is a typo. 
`Generic.xaml` file has to be added to the `Themes` folder instead of the `Generic` folder.
- 
=> docs: Update how-to-create-control-libraries

src/Uno.UI/UI/Xaml/DependencyObjectExtensions.cs, src/Uno.UI/UI/Xaml/DependencyObjectStore.Binder.cs, src/Uno.UI/UI/Xaml/DependencyObjectStore.cs
GitHub Issue (If applicable): closes #18163
=> perf: Remove ObjectId from DependencyObjectStore

src/Uno.UI/UI/Xaml/Controls/TextBox/SinglelineTextBoxDelegate.iOS.cs
related to https://github.com/unoplatform/kahua-private/issues/196
=> chore(iOS): TextBox shouldReturn capture exception

src/Uno.UI.Tests/BinderTests/Given_BindingPath.cs, src/Uno.UI.Tests/DependencyProperty/Given_DependencyProperty.cs, src/Uno.UI/DataBinding/BindingExpression.cs, src/Uno.UI/DataBinding/BindingPath.BindingItem.cs, src/Uno.UI/DataBinding/BindingPath.cs, src/Uno.UI/DataBinding/BindingPropertyHelper.CacheKeys.cs, src/Uno.UI/DataBinding/BindingPropertyHelper.cs, src/Uno.UI/UI/Xaml/Controls/AutoSuggestBox/AutoSuggestBox.cs, src/Uno.UI/UI/Xaml/DependencyObjectExtensions.cs, src/Uno.UI/UI/Xaml/DependencyObjectStore.cs, src/Uno.UI/UI/Xaml/Media/Animation/Timeline.cs, src/Uno.UI/UI/Xaml/Setter.cs
=> refactor: DP cleanup

doc/articles/guides/creating-custom-controls.md, doc/articles/toc.yml
GitHub Issue (If applicable): closes https://github.com/unoplatform/private/issues/505
No specific information on custom controls with Uno in docs.
=> docs: Add Creating Custom Controls page

src/Uno.UI.RemoteControl.Host/RemoteControlServer.cs
GitHub Issue (If applicable): closes #18185
- Bugfix
Assembly resolve location isn't tracked per load context, which may result in assembly load failures if the location is altered
Assembly resolve location is tracked per load context
=> fix: Tracking assembly resolve location by load context

src/Uno.UI/UI/Xaml/Controls/Border/Border.cs, src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.cs, src/Uno.UI/UI/Xaml/Controls/Panel/Panel.cs, src/Uno.UI/UI/Xaml/DependencyObjectStore.cs
=> refactor: More DP-related cleanup

build/nuget/Uno.WinUI.DevServer.nuspec
=> build: Fix DevServer package

build/ci/.azure-devops-docs.yml
=> ci: Fix CI failure

src/Uno.UI/UI/Xaml/Controls/WebView/Native/iOSmacOS/UnoWKWebView.iOSmacOS.cs
GitHub Issue (If applicable): follow up to #18074
- Bugfix
Inspectable was applied only Uno.UI was built with DEBUG flag
Apply the flag always
=> chore: Inspectable WebView not applied correctly

src/Uno.UI.RuntimeTests/Tests/Uno_Helpers/Given_DependencyPropertyHelper.cs, src/Uno.UI/UI/Xaml/DependencyProperty.Dictionary.PropertiesRegistry.cs, src/Uno.UI/UI/Xaml/DependencyProperty.cs, src/Uno.UI/UI/Xaml/Internal/DependencyPropertyHelper.cs
GitHub Issue (If applicable): Fixes #18197
=> chore: follow-up on DependencyPropertyHelper

src/Uno.UI/UI/Xaml/FrameworkElement.Layout.crossruntime.cs, src/Uno.UI/UI/Xaml/ResourceDictionary.cs, src/Uno.UI/UI/Xaml/UIElement.mux.cs
=> perf: Avoid boxing resources enumerators when entering/leaving visual tree

src/Uno.UI.Composition/Composition/SystemBackdrops/DesktopAcrylicController.cs, src/Uno.UI.Composition/Composition/SystemBackdrops/MicaController.cs, src/Uno.UI.Composition/Generated/3.0.0.0/Microsoft.UI.Composition.SystemBackdrops/DesktopAcrylicController.cs, src/Uno.UI.Composition/Generated/3.0.0.0/Microsoft.UI.Composition.SystemBackdrops/MicaController.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/17274
- Feature
The `IsSupported` methods throw.
They return `false`
=> feat: Correctly indicate support for `DesktopAcrylicController` and `MicaController`

src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.iOS.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/kahua-private/issues/194
- Bugfix
=> fix(iOS): null pointer exception when calculating panel offset

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_BackgroundTransition.cs
=> test: Attempt to stabilize background transition test

src/Uno.UWP/Generated/3.0.0.0/Windows.Services.Store/StoreContext.cs, src/Uno.UWP/Generated/3.0.0.0/Windows.Services.Store/StoreRateAndReviewResult.cs, src/Uno.UWP/Generated/3.0.0.0/Windows.Services.Store/StoreRateAndReviewStatus.cs, src/Uno.UWP/Services/Store/StoreContext.Android.cs, src/Uno.UWP/Services/Store/StoreContext.cs, src/Uno.UWP/Services/Store/StoreContext.iOS.cs, src/Uno.UWP/Services/Store/StoreProduct.cs, src/Uno.UWP/Services/Store/StoreProductResult.cs, src/Uno.UWP/Services/Store/StoreRateAndReviewResult.cs, src/Uno.UWP/Services/Store/StoreRateAndReviewStatus.cs
GitHub Issue (If applicable): closes #9998 
- Feature
Not supported
- Supported on iOS
- Android TODO - requires Google Play addin
=> feat: In-app rating on iOS

doc/import_external_docs.ps1
To be able to release [docs: Add Tech Bites video for lightweight styling #1480](https://github.com/unoplatform/Uno.Themes/pull/1480#top) change
=> docs: Update Uno Themes documentation to latest

build/nuget/Uno.WinUI.nuspec, src/SamplesApp/Directory.Build.targets, src/Uno.Sdk/packages.json
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno.fonts/issues/47, closes https://github.com/unoplatform/uno/issues/18148
- Feature
=> feat: Bump Uno.Fonts to 2.4.5

src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.iOS.cs
related to https://github.com/unoplatform/kahua-private/issues/194
=> chore: iOS VirtualizingPanel enable nullable

doc/import_external_docs.ps1
Update Uno.Toolkit doc to latest to fix Material Toolkit Upgrading doc to be at the correct level
Related PR: https://github.com/unoplatform/uno.toolkit.ui/pull/1251
=> docs: Update Uno.Toolkit doc to fix Material Toolkit Upgrading doc to be at the correct level

src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.ClientApi.cs
Make UpdateFile API accessible to all tragets
Only on skia
🙃
=> fix: Make UpdateFileAsync API accesible on all platforms

build/test-scripts/ios-uitest-run.sh
=> test: Update ios testing to 17.5

src/SamplesApp/SamplesApp.Skia/SamplesApp.Skia.csproj
=> fix: Adjust AddIn path

src/SamplesApp/UITests.Shared/UITests.Shared.projitems, src/SamplesApp/UITests.Shared/Windows_ApplicationModel/ClipboardTests.xaml, src/SamplesApp/UITests.Shared/Windows_ApplicationModel/ClipboardTests.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml/DragAndDrop/DragDrop_Files.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml/DragAndDrop/DragDrop_Files.xaml.cs, src/Uno.UI.Runtime.Skia.X11/X11ClipboardExtension.cs, src/Uno.UI.Runtime.Skia.X11/X11DragDropExtension.cs
GitHub Issue (If applicable): https://github.com/unoplatform/brain-products-private/issues/3
=> fix(drag&drop): X11 file dropping support

src/SamplesApp/UITests.Shared/Helpers/WaitableSampleImageHelpers.cs
=> chore: Fail safe in SamplesApp `IWaitableSample` samples

src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Styles/Controls/Button.xaml, src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Styles/Controls/ListView.xaml, src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Styles/Controls/ListViewItem.xaml, src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Styles/Controls/Path.xaml, src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Styles/Controls/RadioButton.xaml, src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Styles/Controls/TextBlock.xaml, src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Styles/Controls/TextBox.xaml, src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Styles/Controls/ToggleButton.xaml, src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Styles/Controls/_Controls.xaml
=> chore: Cleanup non-existing xmlns that shows as IDE-only error

src/SamplesApp/SamplesApp.UITests/SamplesApp.UITests.csproj
Fixed build from https://github.com/unoplatform/uno/pull/18036
=> chore: Fix build

src/SamplesApp/SamplesApp.UITests/SamplesApp.UITests.csproj
=> ci: Fix iOS tests build

src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.Android.cs, src/Uno.UI/UI/Xaml/UIElement.cs
GitHub Issue (If applicable): Related to https://github.com/unoplatform/kahua-private/issues/212
=> chore: Adjust Android's layouting workaround

doc/articles/features/debugging-troubleshooting.md, doc/articles/toc.yml
=> docs: Add Troubleshooting Debugging

src/SamplesApp/SamplesApp.UITests/SamplesApp.UITests.csproj
=> build: Adjust SamplesApp.UITests

src/SamplesApp/SamplesApp.netcoremobile/Android/AndroidManifest.xml
- Bugfix
The target version is low, which triggers a warning on latest versions of Android
Updated
=> fix: Adjust the target SDK version of Samples app on Android

doc/articles/features/using-the-uno-sdk.md, doc/articles/migrating-from-previous-releases.md
=> docs: Remove non-existing uno feature

doc/articles/controls/GLCanvasElement.md, src/SamplesApp/UITests.Shared/Windows_UI_Composition/RotatingCubeGlCanvasElement.cs, src/SamplesApp/UITests.Shared/Windows_UI_Composition/SimpleTriangleGlCanvasElement.cs
=> chore: glsl comments use //, not #

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.skia.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.skia.cs
GitHub Issue (If applicable): closes #18371
=> fix(textbox): BeforeTextChanging crashing ing in specific cases

src/AddIns/Uno.UI.MediaPlayer.Skia.Gtk/Uno.UI.MediaPlayer.Skia.Gtk.csproj, src/AddIns/Uno.WinUI.Graphics3DGL/Uno.WinUI.Graphics3DGL.csproj, src/SamplesApp/SamplesApp.UITests/SamplesApp.UITests.csproj, src/Uno.Sdk/Uno.Sdk.csproj, src/Uno.UI.RemoteControl.Server.Processors/Uno.UI.RemoteControl.Server.Processors.csproj, src/Uno.UI.RemoteControl.VS/Uno.UI.RemoteControl.VS.csproj, src/Uno.UI.Runtime.Skia.Gtk/Uno.UI.Runtime.Skia.Gtk.csproj, src/Uno.UI.TestComparer/Uno.UI.TestComparer.csproj, src/Uno.UWPSyncGenerator/Uno.UWPSyncGenerator.csproj
=> chore(deps): Update STJ to 8.0.5 due to 8.0.4 vulnerability

build/ci/.azure-devops-package-netcoremobile.yml, build/ci/templates/copy-package-assets.yml, build/filters/Uno.UI-packages-skia.slnf, src/AddIns/Uno.WinUI.Graphics3DGL/Uno.WinUI.Graphics3DGL.csproj
=> build: Fix Graphics3DGL packaging

src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.cs
=> chore: Remove TemplatedParent workaround

build/ci/.azure-devops-package-netcoremobile.yml
=> ci: Fix Graphics3DGL version publishing

src/Uno.UI.RemoteControl.Host/Extensibility/Uno.Utils.DependencyInjection/ServiceAttribute.cs, src/Uno.UI.RemoteControl.Host/Extensibility/Uno.Utils.DependencyInjection/ServiceCollectionServiceExtensions.cs, src/Uno.UI.RemoteControl.Host/RemoteControlServer.cs
=> feat: All server processors to get services from DI

src/Uno.UI.RemoteControl.VS/EntryPoint.cs, src/Uno.UI.RemoteControl.VS/IDEChannel/IDEChannelClient.cs, src/Uno.UI.RemoteControl.VS/Notifications/InfoBar.cs
- Feature
We do not have the Notification on the Visual Studio/DevServer
To be able to add notification bar on the VS.
=> Add InfoBar Notification Requested

build/cSpell.json, doc/articles/uno-publishing-desktop.md
=> docs: Update desktop publishing article

src/Uno.UI.RemoteControl.Host/Extensibility/AddIns.cs
=> fix: Allow properties to be multi-lines

src/Uno.UWP/Storage/Pickers/FileOpenPicker.iOS.cs
=> fix: Dismiss the photo picker view controller earlier

src/Uno.UI.RemoteControl.VS/EntryPoint.ActiveProfileSync.cs
- Bugfix
Ensure that the .user file is properly updated when the target framework changes
=> fix: Adjust .user value even when not reloading

src/Uno.Foundation/PropertyValue.Internal.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ComboBox.cs
=> fix: Fix potential crash in PropertyValue.AreEqualImpl

src/Uno.UWP/Storage/Helpers/AssetsPathBuilder.wasm.cs
GitHub Issue (If applicable): closes #18358
Duplicate slash
Adjusted
=> fix: Adjust AssetsPathBuilder

src/Uno.Sdk/Sdk/Sdk.props, src/Uno.Sdk/targets/Uno.IsPlatform.Before.props, src/Uno.Sdk/targets/Uno.IsPlatform.props
=> fix(sdk): Ensure IsPlatform defaults are always defined

src/Uno.UI/UI/Xaml/DependencyObjectStore.cs, src/Uno.UI/UI/Xaml/Input/Internal/FocusProperties.cs, src/Uno.UI/UI/Xaml/Input/Internal/XYFocus.TreeWalker.cs, src/Uno.UI/UI/Xaml/Markup/Reader/XamlTypeResolver.cs, src/Uno.UI/UI/Xaml/Media/Imaging/WriteableBitmap.cs, src/Uno.UI/UI/Xaml/UIElement.mux.cs, src/Uno.UI/UI/Xaml/XamlScope.cs
=> perf: misc refactoring to reduce allocations

src/Directory.Build.targets, src/Uno.UI.RemoteControl.VS/Commands/DynamicItemMenuCommand.cs, src/Uno.UI.RemoteControl.VS/Commands/UnoMenuCommand.cs, src/Uno.UI.RemoteControl.VS/EntryPoint.cs, src/Uno.UI.RemoteControl.VS/IDEChannel/IDEChannelClient.cs
Related to 
https://github.com/unoplatform/uno.studio/pull/684 and https://github.com/unoplatform/uno.licensing/issues/34
- Feature
DevServer does not have the ability to add menus in Visual Studio.
To be able to test, i added some calls (with some delay)
```csharp
_proxy?.SendToIde(new CommandRequestIdeMessage(10, "Command 1", "Message Parameter 1"));
await Task.Delay(2000);
_proxy?.SendToIde(new CommandRequestIdeMessage(10, "Command 2", "Message Parameter 2"));
await Task.Delay(2000);
_proxy?.SendToIde(new CommandRequestIdeMessage(10, "Command 3", "Message Parameter 3"));
await Task.Delay(20000);
```
https://github.com/user-attachments/assets/961d72de-0acf-4316-8312-196d9ce5502b
There is now a specific message to do this. Include menus in …
=> [Visual Studio] Settings UI 

doc/articles/controls/GLCanvasElement.md, doc/articles/controls/SKCanvasElement.md, src/AddIns/Uno.WinUI.Graphics2DSK/SKCanvasElement.cs, src/SamplesApp/UITests.Shared/Windows_UI_Composition/SKCanvasElement_Simple.xaml
=> docs: minor adjustments to GLCanvasElement and SKCanvasElement docs

src/Uno.UI.TestComparer/Uno.UI.TestComparer.csproj, src/Uno.UWPSyncGenerator/Uno.UWPSyncGenerator.csproj
- Bugfix
Building SkiaOnly Sln falling for wrong target on these two projects
=> chore: fix skia only solution

doc/articles/features/windows-storage-pickers.md
GitHub Issue (If applicable): closes #18341
=> docs: Update support matrix for file and folder pickers

src/Uno.UI.Composition/Composition/BorderVisual.skia.cs, src/Uno.UI.Composition/Composition/Uno/DrawingFilter.skia.cs, src/Uno.UI.Composition/Composition/Uno/UnoSkiaApi.skia.cs
=> Composition misc perf

src/crosstargeting_override.props.sample
=> chore: update crosstarget override sample

src/SamplesApp/SamplesApp.Windows/SamplesApp.Windows.csproj
=> fix: Avoid type conflicts in `SamplesApp.Windows`

src/Uno.UI.RemoteControl.Messaging/IDEChannel/CommandRequestIdeMessage.cs, src/Uno.UI.RemoteControl.VS/Commands/UnoMenuCommand.cs, src/Uno.UI.RemoteControl.VS/EntryPoint.cs
=> Backport Settings app opening on top - Change to ProcessID 

src/Uno.UWP/Storage/Pickers/StorageSerializationContext.wasm.cs
- Bugfix
Fixes file save experience on wasm net9.
=> fix(wasm): Adjust for missing type info for file pickers

doc/articles/features/working-with-assets.md
=> docs: update working with assets

src/Uno.Sdk/packages.json
=> chore: Consistent indentation in packages.json

doc/articles/controls/WebView.md
=> docs: `WebView` on WebAssembly

src/SolutionTemplate/5.3/uno53net9blank/uno53net9blank/ControlWithXamlEverywhereExceptDesktop.xaml.cs, src/SolutionTemplate/5.3/uno53net9blank/uno53net9blank/Platforms/Android/ControlWithXamlEverywhereExceptDesktop.xaml, src/SolutionTemplate/5.3/uno53net9blank/uno53net9blank/Platforms/MacCatalyst/ControlWithXamlEverywhereExceptDesktop.xaml, src/SolutionTemplate/5.3/uno53net9blank/uno53net9blank/Platforms/WebAssembly/ControlWithXamlEverywhereExceptDesktop.xaml, src/SolutionTemplate/5.3/uno53net9blank/uno53net9blank/Platforms/iOS/ControlWithXamlEverywhereExceptDesktop.xaml, src/Uno.Sdk/targets/Uno.Build.targets, src/Uno.Sdk/targets/Uno.Common.targets, src/Uno.Sdk/targets/Uno.Sdk.After.targets, src/Uno.Sdk/targets/Uno.SingleProject.Desktop.targets
GitHub Issue (If applicable): closes #18538
=> fix(uno.sdk): ignore xaml files in Platforms folders

doc/articles/getting-started/counterapp/get-started-counter-xaml-mvvm.md, doc/articles/getting-started/counterapp/includes/include-mainpage-xaml.md, doc/articles/getting-started/counterapp/includes/include-mvvm.md
Clarify the steps when running the MVVM-XAML tutorial to make it clearer for beginners.
=> docs: clarify xaml-mvvm tutorial

src/Uno.UI.TestComparer/Comparer/TestFilesComparer.cs
=> feat: Use SIMD to compage images in a test to accelerate builds.

src/SamplesApp/UITests.Shared/UITests.Shared.projitems, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/NavigationViewTests/NavigationView_Tapped.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/NavigationViewTests/NavigationView_Tapped.xaml.cs, src/Uno.UI/UI/Xaml/Input/PointerRoutedEventArgs.Android.cs
GitHub Issue (If applicable): closes #18024
=> fix(android): PointerRoutedEventArgs.GestureEventsAlreadyRaised was reset while bubbling events up

src/SourceGenerators/Uno.UI.Tasks/Content/Uno.UI.Tasks.targets
=> fix: mofidying .ts files only should embed the newly generated .js files

src/Uno.UI.Runtime.Skia.MacOS/UnoNativeMac/UnoNativeMac/UNOWindow.m
GitHub Issue (If applicable): closes #16399
- Bugfix
Events, like mouse move, on other windows on top of the app would be considered.
Events are only received when the current application is active.
=> fix(macOS): Prevent pointer over event originating from other window

doc/articles/getting-started/counterapp/get-started-counter-csharp-mvux.md
The class after the code sample was referring to the generated code, not the user code.
=> docs: adjust MVUX doc for proper class name

doc/articles/getting-started/counterapp/get-started-counter-csharp-mvux.md, doc/articles/getting-started/counterapp/get-started-counter-csharp-mvvm.md, doc/articles/getting-started/counterapp/includes/include-mainpage-csharp.md, doc/articles/getting-started/counterapp/includes/include-mvux.md, doc/articles/getting-started/counterapp/includes/include-mvvm.md
remove misleading or incorrect namespaces in tutorials samples
=> Docs: remove invalid namespaces in code samples

src/Uno.UI.RuntimeTests/Tests/Microsoft_UI_Xaml_Controls/Given_WebView2.cs
- Other... Please describe: Tests
No tests were validating what happens when an unsupported scheme was used.
Added tests for handled/non-handled cases where an unsupported scheme is used.
=> test: add tests for more coverage of WebView2

src/Uno.UI.RemoteControl.VS/Commands/UnoMenuCommand.cs
GitHub Issue (If applicable): Closes license 373
- Bugfix
When the UnoMenuCommand are Dispose, we disable and hidden the Uno Platform Menu.
To repro.
I was able to reproduce this, 
when i am running the project using a version that enable the Extension Menu.
And than rebase to the same project using a different sdk 
and without the HR trigger to enable the Extension. (the UnoMenuCommand  are diposed)
and When returned to the branch with the HR feature that add the Extension menu, the menu was enabled again.
Now we are removing the Menu from the CommandService.
When the UnoMenuCommand started again the Main Menu will be created again.
=> Disabled menu in VS - Remove to not be visible.

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Composition/Given_ShapeVisual.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/18752
=> ci: Disable When_ShapeVisual_ViewBox_Shape_Combinations

doc/articles/features/unhandled-exceptions.md
=> docs: Correct closing tag

doc/articles/getting-started/counterapp/get-started-counter-xaml-mvux.md
=> docs: proper class name

doc/articles/get-started-licensing.md
GitHub Issue (If applicable): related to https://github.com/unoplatform/uno.licensing/issues/346
Add migration guide details to the licensing related documentation
=> docs: Add migration guide details to the licensing related documentation

src/Uno.Sdk/targets/Uno.Common.WinAppSdk.targets
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/18552
- Bugfix
Properly set `PlatformTarget` when using `AnyCPU`
=> fix(webview2): Adjust target platform selection for windows builds

src/SamplesApp/UITests.Shared/UITests.Shared.projitems, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ScrollViewerTests/ScrollViewer_IsIntermediate.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ScrollViewerTests/ScrollViewer_IsIntermediate.xaml.cs, src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.wasm.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/kahua-private/issues/230
=> fix(scrollviewer): fix scrollArgs.IsIntermediate on WASm

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Composition/Given_ShapeVisual.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/18752
=> chore: fix When_ShapeVisual_ViewBox_Shape_Combinations flakiness

doc/articles/uno-development/uno-internals-hotreload.md
=> docs: Hide await HotReload UI updates example

src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media_Animation/ColorAnimationUsingKeyFrames_Fill.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media_Animation/ColorAnimationUsingKeyFrames_Fill.xaml.cs, src/Uno.UI/UI/Xaml/Media/Animation/Animators/AnimatorFactory.skia.cs, src/Uno.UI/UI/Xaml/Media/Animation/Animators/DispatcherAnimator.cs, src/Uno.UI/UI/Xaml/Media/Animation/Animators/DispatcherColorAnimator.cs, src/Uno.UI/UI/Xaml/Media/Animation/Animators/DispatcherDoubleAnimator.cs, src/Uno.UI/UI/Xaml/Media/Animation/ColorAnimation.cs
GitHub Issue (If applicable): closes #18802
=> fix(skia): support color animations

build/test-scripts/android-uitest-run.sh, build/test-scripts/ios-uitest-run.sh, build/test-scripts/wasm-run-automated-uitests.sh
Previously when the second attempt to run tests failed and produced no `TestResult-original.xml`, the `list-failed` was still executed and just emptied the failed test file. This means that even though tests did not run successfully, the next run is just skipped, as there was an empty list waiting for it.
`list-failed` is executed conditionally:
- If UI tests run is successful, `TestResult-original.xml` is produced successfully and the whole attempt will be green ✅
- If some tests fail, `TestResult-original.xml` is produced successfully, `test-failed` will execute and next attempt will be able to continue ✅
- If the tests run itself crashes, `TestResult-original.xml` is not …
=> ci: Fail before listing failed tests

src/Uno.UI/Controls/RootViewController.iOS.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/19049
- Bugfix
It is now required to specify trait types to listen to
Now specific to style changes (dark/light)
=> fix: Observe specific trait on RootViewController

doc/articles/get-started.md
=> docs: Update get-started.md

src/Uno.UI.RuntimeTests/Tests/Windows_UI/Given_WeakEventHelper.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_ResourceDictionary.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Pivot.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/ItemsRepeater.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/Layout.cs, src/Uno.UI/UI/Xaml/Application.cs, src/Uno.UI/UI/Xaml/Controls/CommandBar/CommandBar.Partial.cs, src/Uno.UI/UI/Xaml/DependencyObjectStore.cs, src/Uno.UI/UI/Xaml/FrameworkElement.Layout.crossruntime.cs, src/Uno.UI/UI/Xaml/FrameworkElement.cs, src/Uno.UI/UI/Xaml/ResourceDictionary.cs, src/Uno.UI/UI/Xaml/ResourceResolver.cs, src/Uno.UI/UI/Xaml/SpecializedResourceDictionary.cs, src/Uno.UI/UI/Xaml/UIElement.Layout.crossruntime.cs, src/Uno.UI/UI/Xaml/UIElement.mux.cs, src/Uno.UWP/UI/Core/WeakEventHelper.cs
=> perf: Resources resolution and layout improvements

build/ci/.azure-devops-unit-tests.yml, src/Uno.UI.Tests/Windows_UI_Xaml/Input/Focus/Given_XYFocusTreeWalker.cs, src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/Given_XamlReader.cs
=> test: Stabilize unit tests

src/Directory.Build.targets
=> chore(deps): Update MSTest to 3.7

src/Uno.UI.Dispatching/Native/NativeDispatcher.cs, src/Uno.UI/UI/Xaml/Controls/Frame/Frame.legacy.cs, src/Uno.UI/UI/Xaml/Internal/EventManager.uno.cs, src/Uno.UI/UI/Xaml/Style/Style.cs, src/Uno.UI/UI/Xaml/UIElement.Pointers.cs
Related to https://github.com/dotnet/runtime/issues/111281
=> perf(wasm): Split methods containing try/catch/finally blocks

src/SourceGenerators/Uno.UI.SourceGenerators.Tests/Uno.UI.SourceGenerators.Tests.csproj, src/Uno.Analyzers.Tests/Uno.Analyzers.Tests.csproj
=> test: Use OutputType Exe for MTP projects

src/Uno.UI.Tests/Helpers/ThemeHelper.cs, src/Uno.UI.Tests/HotReload/Windows_UI_Xaml/Given_ThemeResource.hotreload.cs, src/Uno.UI.Tests/Windows_UI_Xaml/Given_ResourceDictionary.cs, src/Uno.UI.Tests/Windows_UI_Xaml/Given_ThemeResource.cs, src/Uno.UI.Tests/Windows_UI_Xaml/Theming/Given_Element_Theme.cs, src/Uno.UI.Tests/Windows_UI_Xaml_Markup/VisualStateManager_Lazy_Tests/VisualStateManager_Lazy.cs, src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/Given_XamlReader.cs
=> test: Ensure unit tests that change theme will reset it back

src/Uno.UI.RuntimeTests/Tests/Windows_UI/Given_WeakEventHelper.cs
fixes https://github.com/unoplatform/uno/issues/19244
=> test: Adjust When_Many_Targets_Collected

doc/articles/features/working-with-themes.md
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/19216
- Bugfix
=> docs: Update Working with Themes

src/SourceGenerators/Uno.UI.SourceGenerators.Tests/MetadataUpdateTests/Given_HotReloadService.cs
=> chore: Add issue link to IgnoreAttribute for HR failure

src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.xaml, src/SamplesApp/UITests.Shared/Microsoft_UI/ColorHelperTests.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CheckBoxTests/CheckBox_Automated.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CheckBoxTests/CheckBox_States.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/Simple_Contrained_Horizontal_Center_Wrap.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/Simple_Text_Arabic.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/CompositionTargetTests/CompositionTarget_Rendering.xaml.cs
- Refactoring
Reducing number of categories and duplicates
=> refactor: Cleanup samples

doc/articles/other/rider-eula.md
- Other: License
Update [End-User License Agreement (EULA) for Uno Platform for Rider Plugin ](https://platformuno.sharepoint.com/:w:/r/sites/UnoPlatform/Shared%20Documents/Marketing%20(Public)/EULAs%20-%20extensions/EULA%20Rider%20AFTER%20Uno%20Platform%20Studio.docx?d=w33936aa5ff164c4f90b8da255d683d27&csf=1&web=1&e=KxLHCe) to add more information (collection and use of data for example).
=> chore: Update rider-eula.md

doc/articles/uno-community-toolkit-v8.md
Manual backport of https://github.com/unoplatform/uno/pull/19212 for **release/stable/5.5**
=> docs(CTK8): Added converters usage sample (Backport #19212)

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.skia.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.pointers.skia.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/19317
=> fix(textbox): extend selection when on tapping when shift is held

src/SamplesApp/UITests.Shared/UITests.Shared.projitems, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_PointerOutOfWindow.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_PointerOutOfWindow.xaml.cs, src/Uno.UI.Runtime.Skia.X11/X11XamlRootHost.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/19310
=> fix(x11): make keyboard inputs work even when the pointer is outside the window

src/Uno.UI.RuntimeTests/Tests/Windows_Globalization/Given_DateTimeFormatter.cs
GitHub Issue (If applicable): related to https://github.com/unoplatform/uno/issues/19346
=> test: assert day and year only on date formatting

src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.cs, src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Controls/SampleChooserControl.xaml, src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Styles/Controls/Path.xaml
=> feat: Order Samples app favorites at the top of category

src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.Common.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/private/issues/610, closes https://github.com/unoplatform/uno-private/issues/821, closes https://github.com/unoplatform/private/issues/611, closes https://github.com/unoplatform/private/issues/612
- Bugfix
Native elements on iOS/Android need to be enumerator for HR to work properly.
=> fix(hr): Enumerate through native elements

build/Install-WindowsSdkISO.ps1
- Bugfix
The old URL "https://software-download.microsoft.com/download/pr/19041.1.191206-1406.vb_release_WindowsSDK.iso" returns 404.
New URL: https://software-static.download.prss.microsoft.com/pr/download/19041.685.201201-2105.vb_release_svc_prod1_WindowsSDK.iso
=> fix: new URL for Windows SDK in build script

src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.Agent.cs, src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.Common.cs, src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.MetadataUpdate.cs, src/Uno.UI.RemoteControl/RemoteControlClient.cs
1. Improve logging
2. Fix HR handlers:
- Might not being invoked if multiple handlers registered for a type
- Invoked handler is not the same depending of platform (x64 vs. ARM64)
3. Fix typo that prevents enumeration of native elements on android for HR updates
=> fix(hr): Misc updates on HR

src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/GradientBrushTests/GradientsPage.xaml, src/Uno.UI/UI/Xaml/Documents/InlineCollection.skia.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/19193
=> fix(textblock): use FallBackColor when the Foreground Brush is a GradientBrush

src/Uno.UI/ts/Clipboard.ts
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/19365
=> fix(wasm): crashing on clipboard reads when access is denied

src/Uno.UI.RemoteControl.VS/DebuggerHelper/ProfilesObserver.cs, src/Uno.UI.RemoteControl.VS/EntryPoint.ActiveProfileSync.cs, src/Uno.UI.RemoteControl.VS/EntryPoint.cs
Closes https://github.com/unoplatform/private/issues/619
=> fix(vs): Adjust for initialization delay and skipped synchronization

src/Uno.UI/UI/Xaml/Controls/PasswordBox/PasswordBox.cs
=> fix: PasswordRevealMode

src/Uno.Sdk/targets/Uno.Build.targets
Related to https://github.com/dotnet/maui/issues/27612
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno.hotdesign/issues/3299
=> fix(hr): Remove unrelated assemblies from other TFMs for Hot Reload

src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/Geometry/ArcSegmentPage.xaml
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/19199
=> chore: fix ArcSegmentPage to correctly display on Skia

src/Uno.UI/UI/Xaml/DragDrop/DragView.xaml
=> fix: CaptionVisibility typo

src/Uno.Sdk/targets/Uno.Build.targets
Related to https://github.com/dotnet/maui/issues/27612, closes https://github.com/unoplatform/uno.hotdesign/issues/3299
=> fix(hr): Properly detect android for HR workaround

src/SourceGenerators/Uno.UI.SourceGenerators.Tests/XamlCodeGeneratorTests/Verifiers/CSGenerator.cs
=> fix: Avoid `WRITE_EXPECTED` by default

src/Uno.UI/UI/Xaml/Application.Android.cs, src/Uno.UI/UI/Xaml/Application.cs, src/Uno.UI/UI/Xaml/Window/Native/NativeWindowWrapper.Android.cs, src/Uno.UWP/UI/ViewManagement/StatusBar/StatusBar.Android.cs
=> Android insets handling continued

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_AutoSuggestBox.cs, src/Uno.UI/UI/Xaml/Controls/AutoSuggestBox/AutoSuggestBox.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/ziidms-private/issues/54
=> fix(autosuggestbox): events getting unsubscribed when unloading and loading

src/Uno.Sdk/Sdk/Sdk.props, src/Uno.Sdk/Uno.Sdk.csproj
Related to https://github.com/unoplatform/uno.hotdesign/issues/3274
=> feat: Add UnoSdkVersion MSBuild property

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs, src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.managed.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/kahua-private/issues/257
=> fix(listview): unloading and reloading a ListView should keep the scroll position

doc/articles/uno-publishing-desktop.md
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/19377
=> docs: Adjust desktop publishing

src/Uno.Sdk/Sdk/Sdk.props.buildschema.json, src/Uno.Sdk/Services/PackageManifest.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/add-private/issues/27
- Bugfix
Overriding `MicrosoftLoggingVersion` does not work on .NET9. 
=> fix(UnoSDK): implicit package override

doc/articles/supported-libraries.md
Add Shiny .NET to supported 3rd-party libraries list
=> docs: Add Shiny .NET to supported 3rd-party libraries list

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_CalendarDatePicker.cs, src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/NativeScrollContentPresenter.iOS.cs, src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.iOS.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/19505
- Bugfix
Does not work
Works
=> fix: Ensure current date is applied in `CalendarDatePicker` on iOS

doc/articles/getting-started/wizard/includes/framework.md
- Documentation content update
- preset .net version is told to be .net 8
- Descriptions of the .NET Versions is outdated and telling about .NET 9 to be preview
- using the `-tfm 8.0` or `-tfm 9.0` in dotnet new resulting in:
- updated the preset version description in the documentation to current state
- updated available .NET versions descriptions with the official .NET version short description and added the end-of-support time as date, because no one will check when the documentation has been edited if we are telling "in 8 months", so it is clear now at any time from this.
- updated the `-tfm` to match the cli told values, to improve user expirience with not having to face confusing output while the …
=> docs(dotnet-new): Updated Framework tfm values

src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/ContentPresenter/ContentPresenter_ContentBindingPath.xaml, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/ContentPresenter/ContentPresenter_ContentBindingPath.xaml.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ContentPresenter.cs, src/Uno.UI/DataBinding/BindingExpression.cs, src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.cs
GitHub Issue (If applicable): closes unoplatform/ziidms-private#67
- Bugfix
todo
todo
=> fix(ContentPresenter): Content binding resolution

build/ci/.azure-devops-unit-tests.yml
=> ci: Publish binlogs from unit test builds and runs

doc/articles/studio/Hot Design/hot-design-getstarted-counter-tutorial.md, doc/articles/studio/Hot Design/hot-design-getstarted-guide.md, doc/articles/studio/Hot Design/hot-design-overview.md, doc/articles/studio/hot-design-beta-feedback.md
Include known issues link in documentation for Hot Design
=> docs(HotDesign): Include known issues link in documentation

build/ci/.azure-devops-wasm-uitests.yml
=> ci: Clarify testRunTitle for Wasm

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_AutoSuggestBox.cs, src/Uno.UI/UI/Xaml/Controls/AutoSuggestBox/AutoSuggestBox.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/898
=> fix(autosuggestbox): adjust popup layout after suggestions list changes

src/AddIns/Uno.UI.Lottie/WasmScripts/uno-lottie.js, src/AddIns/Uno.UI.Lottie/ts/Uno.UI.Lottie.ts
GitHub Issue (If applicable): closes https://github.com/unoplatform/kahua-private/issues/268
- Bugfix
=> fix: uno lottie animation exception

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.skia.cs, src/Uno.UI/UI/Xaml/Documents/InlineCollection.skia.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/19321
=> fix(textbox): correctly set selection when clicking past the end in a TextBox that ends with spaces

src/Directory.Build.targets
=> Update MSTest to 3.8.3

src/Directory.Build.props, src/Uno.Sdk/targets/Uno.Implicit.Packages.ProjectSystem.Android.targets, src/Uno.Sdk/targets/Uno.Implicit.Packages.ProjectSystem.targets
GitHub Issue (If applicable): part of https://github.com/unoplatform/uno-private/issues/1004
=> fix: Include GooglePlay package on Android only

build/PackageDiffIgnore.xml, src/Uno.UI/Generated/3.0.0.0/Microsoft.UI.Xaml.Automation/AutomationProperties.cs, src/Uno.UI/UI/Xaml/Automation/AutomationProperties.cs
- Bugfix
Typo was causing "SetAccessibilityView(DependencyObject, AccessibilityView) is not implemented in Uno".
https://github.com/unoplatform/uno/blob/41d18b5c509ca6e8347fa5e5f10a0928881064bb/src/Uno.UI/Generated/3.0.0.0/Microsoft.UI.Xaml.Automation/AutomationProperties.cs#L309-L317
`SetAccessibilityView` with no typo and is implemented.
=> fix: correct SetAccessibilityView misspelled name

doc/articles/studio/Hot Design/hot-design-getstarted-counter-tutorial.md, doc/articles/studio/Hot Design/hot-design-getstarted-guide.md, doc/articles/studio/Hot Design/hot-design-overview.md, doc/articles/studio/hot-design-beta-feedback.md, doc/articles/studio/studio-overview.md
Update trademark symbol for Hot Design
=> docs: Update trademark symbol for Hot Design

THIRD-PARTY-NOTICES.md, src/AddIns/Uno.UI.Svg/External/SKPictureExtensions.cs, src/AddIns/Uno.UI.Svg/External/SKSvg.Model.cs, src/AddIns/Uno.UI.Svg/External/SKSvgSettings.cs, src/AddIns/Uno.UI.Svg/External/SkiaAssetLoader.cs, src/AddIns/Uno.UI.Svg/External/SkiaModel.cs, src/AddIns/Uno.UI.Svg/External/TypefaceProviders/CustomTypefaceProvider.cs, src/AddIns/Uno.UI.Svg/External/TypefaceProviders/DefaultTypefaceProvider.cs, src/AddIns/Uno.UI.Svg/External/TypefaceProviders/FontManagerTypefaceProvider.cs, src/AddIns/Uno.UI.Svg/External/TypefaceProviders/ITypefaceProvider.cs, src/AddIns/Uno.UI.Svg/SvgProvider.cs, src/AddIns/Uno.UI.Svg/Uno.UI.Svg.Reference.csproj, src/AddIns/Uno.UI.Svg/Uno.UI.Svg.Skia.csproj, src/AddIns/Uno.UI.Svg/Uno.UI.Svg.netcoremobile.csproj, src/Directory.Build.targets, src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/InfoBadge/InfoBadgeTests.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Image.cs, src/Uno.UI/UI/Xaml/Media/Imaging/SvgImageSource.skia.cs
closes https://github.com/unoplatform/uno-private/issues/1031
=> fix: Adjust SVG for SkiaSharp 3 support

src/Uno.UWP/Uno.Wasm.csproj
closes https://github.com/unoplatform/uno-private/issues/725
=> fix: Adjust ts generation ordering

src/Uno.UI.Runtime.Skia.Android/Microsoft/UI/Xaml/TextInputPlugin.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/private/issues/684, closes https://github.com/unoplatform/private/issues/682
=> fix(android): Don't recurse on unhandled key events

src/SamplesApp/SamplesApp.Skia.WebAssembly.Browser/SamplesApp.Skia.WebAssembly.Browser.csproj, src/SamplesApp/SamplesApp.Skia.netcoremobile/SamplesApp.Skia.netcoremobile.csproj
=> chore: add PreBuildUnoUITasks

src/Uno.UWP/ApplicationModel/Email/EmailManager.UIKit.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/kahua-private/issues/281
- Bugfix
=> fix(iOS): email compose

src/Uno.UI/UI/Xaml/Media/ImageSource.crossruntime.cs, src/Uno.UI/UI/Xaml/Media/Imaging/BitmapImage.skia.cs, src/Uno.UI/UI/Xaml/Media/Imaging/RenderTargetBitmap.cs, src/Uno.UI/UI/Xaml/Media/Imaging/SvgImageSource.cs, src/Uno.UI/UI/Xaml/Media/Imaging/SvgImageSource.skia.cs
GitHub Issue (If applicable): closes  https://github.com/unoplatform/uno-private/issues/989
=> [Skia] image loading off UI thread

src/Uno.UI.Runtime.Skia.WebAssembly.Browser/BrowserInvisibleTextBoxViewExtension.cs, src/Uno.UI.Runtime.Skia.WebAssembly.Browser/ts/Runtime/BrowserInvisibleTextBoxViewExtension.ts
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/1086
=> fix(wasm): fix selection with soft keyboards on Android

src/Uno.UI/Microsoft/UI/Xaml/Controls/SwipeControl/SwipeControl.Uno.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/909
=> fix(SwipeControl): improve render transforms when swiping

src/Uno.UI.FluentTheme.v1/themeresources_v1.xaml
=> refactor: Generated XAML update

src/AddIns/Uno.UI.MediaPlayer.Skia.Win32/Uno.UI.MediaPlayer.Skia.Win32.csproj, src/SamplesApp/SamplesApp.Skia.Generic/SamplesApp.Skia.Generic.csproj, src/Uno.Sdk/Services/PackageManifest.cs, src/Uno.Sdk/Tasks/ImplicitPackagesResolver.cs, src/Uno.Sdk/packages.json, src/Uno.Sdk/targets/Uno.Implicit.Packages.ProjectSystem.Desktop.targets, src/Uno.UI.Runtime.Skia.Win32/buildTransitive/Uno.WinUI.Runtime.Skia.Win32.targets
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/1088
=> feat(uno.sdk): include LibVLC binaries on Windows

doc/articles/uno-development/building-uno-ui.md
Remove unnecessary ` (backtick).
=> docs: Update building-uno-ui.md

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media_Imaging/Given_BitmapSource.cs, src/Uno.UWP/Storage/Streams/InMemoryRandomAccessStream.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/kahua-private/issues/287
=> fix(InMemoryRandomAccessStream): cloning sets the wrong position

doc/articles/features/windows-media-capture.md
GitHub Issue (If applicable): related to #19716 
=> docs: improve CameraCaptureUI

src/Uno.UWP/ApplicationModel/Email/EmailManager.UIKit.cs, src/Uno.UWP/FeatureConfiguration/WinRTFeatureConfiguration.EmailManager.cs
GitHub Issue (If applicable): related to https://github.com/unoplatform/kahua-private/issues/281
- Feature
=> chore: (iOS) enable mailapp as feature

doc/articles/features/using-the-uno-sdk.md
GitHub Issue (If applicable): closes [internal](https://teams.microsoft.com/l/message/19:c857d68e0be84cfba6ff9a8611200680@thread.tacv2/1744039294432?tenantId=a297d6c0-b635-41a3-b1e3-558efe71e413&groupId=f55cdec8-036b-4efa-8e1a-c4129ba9bf12&parentMessageId=1744039294432&teamName=Uno%20Platform&channelName=Collab%20Lounge&createdTime=1744039294432)
This pull request includes an update to the documentation in the `doc/articles/features/using-the-uno-sdk.md` file. The change involves modifying the list of tracked Visual Studio issues to ensure clarity and relevance.
Documentation update:
* [`doc/articles/features/using-the-uno-sdk.md`](diffhunk://#diff-5000f45fc55f434ad3a4439846e7ca2bf435e919eb198e4ae16405df868354d0L24 …
=> docs: Update fixed Microsoft issues

build/nuget/uno.winui.common.targets, doc/articles/platform-specific-csharp.md, src/Uno.UI.Runtime.Skia.Android/buildTransitive/Uno.WinUI.Runtime.Skia.Android.props, src/Uno.UI.Runtime.Skia.AppleUIKit/buildTransitive/Uno.WinUI.Runtime.Skia.AppleUIKit.props, src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/buildTransitive/Uno.WinUI.Runtime.Skia.Linux.FrameBuffer.targets, src/Uno.UI.Runtime.Skia.MacOS/buildTransitive/Uno.WinUI.Runtime.Skia.MacOS.targets, src/Uno.UI.Runtime.Skia.WebAssembly.Browser/buildTransitive/Uno.WinUI.Runtime.Skia.WebAssembly.Browser.targets, src/Uno.UI.Runtime.Skia.Win32/buildTransitive/Uno.WinUI.Runtime.Skia.Win32.targets, src/Uno.UI.Runtime.Skia.Wpf/buildTransitive/Uno.WinUI.Runtime.Skia.Wpf.targets, src/Uno.UI.Runtime.Skia.X11/buildTransitive/Uno.WinUI.Runtime.Skia.X11.targets, src/Uno.UI.Runtime.WebAssembly/buildTransitive/Uno.WinUI.Runtime.WebAssembly.targets
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/790
=> fix: Adjust compilation constants

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media/Given_AcrylicBrush.cs, src/Uno.UI/UI/Xaml/Media/ImageSource.crossruntime.cs, src/Uno.UI/UI/Xaml/Media/Imaging/BitmapImage.skia.cs, src/Uno.UI/UI/Xaml/Media/Imaging/RenderTargetBitmap.cs
=> Uno islands ci fix

src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/WebView2Tests/WebView2ViewModel.cs, src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/WebView2Tests/WebView2_Alert.xaml, src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/WebView2Tests/WebView2_Alert.xaml.cs, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/WebView/WebView_Alert.xaml, src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/WebView/WebView_Alert.xaml.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/1030
=> chore: update WebView_Alert to include script stopping

src/crosstargeting_override.props.sample
=> chore: update crosstarget sample for targets

src/Uno.UI.Composition/Composition/FrameProviderFactory.skia.cs, src/Uno.UI.RuntimeTests/IntegrationTests/common/TestServices.WindowHelper.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media_Imaging/Given_BitmapSource.cs, src/Uno.UI/FeatureConfiguration.cs, src/Uno.UI/UI/Xaml/Media/Imaging/BitmapImage.Cache.skia.cs, src/Uno.UI/UI/Xaml/Media/Imaging/BitmapImage.skia.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/1089
=> feat(BitmapImage): image caching

src/Uno.UI.Composition/Composition/ShadowState.skia.cs, src/Uno.UI.Toolkit/ElevatedView.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/1100
=> perf(Shadows): dramatically speed up the rendering of shadows on Skia

src/Uno.UI.RuntimeTests/Tests/Microsoft_UI_Xaml_Controls/Given_NavigationView.cs, src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.skia.cs, src/Uno.UI/UI/Xaml/Documents/TextElement.skia.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/1091
=> fix(textblock): invalidate when the foreground changes

src/Uno.UI.Runtime.Skia.WebAssembly.Browser/WebAssemblyBrowserHost.cs, src/Uno.UI/DirectUI/DXamlCore.cs, src/Uno.UI/UI/Xaml/Controls/Popup/Popup.Base.cs, src/Uno.UI/UI/Xaml/Controls/Popup/Popup.WithPopupRoot.cs, src/Uno.UI/UI/Xaml/Input/FocusManager.mux.static.cs, src/Uno.UI/UI/Xaml/Internal/ContentRoot.cs, src/Uno.UI/UI/Xaml/Internal/ContentRootCoordinator.cs, src/Uno.UI/UI/Xaml/Internal/CoreServices.cs, src/Uno.UI/UI/Xaml/Internal/Scaling/RootScale.mux.cs, src/Uno.UI/UI/Xaml/Internal/VisualTree.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/1107
- Bugfix
This commit renames the `CoreWindowContentRoot` property to `Unsafe_IslandsIncompatible_CoreWindowContentRoot` to align with WinUI and validates all usages to perform `null` checking
Key changes include:
- Removal of event handling code in `WebAssemblyBrowserHost.cs` for simplification.
- Updates in `DXamlCore.cs` to reference the new property in `OnCompositionContentStateChangedForUWP`.
- Modifications in `Popup` class files to use the new property for determining `XamlRoot`.
- Adjustments in the `FocusManager` class to ensure correct focus management with the new property.
- Updates in …
=> refactor: Rename `CoreWindowContentRoot` for compatibility

src/Uno.UI-Skia-only.slnf
- Bugfix
Red squiggles on Composition APIs 
No more
=> fix: Include `Uno.UI.Composition.Reference` in Skia `.slnf`

src/AddIns/Uno.UI.MediaPlayer.Skia.Win32/Win32MediaPlayerPresenterExtension.cs, src/AddIns/Uno.UI.MediaPlayer.Skia.X11/SharedMediaPlayerExtension.cs, src/SamplesApp/SamplesApp.Skia.Generic/Program.cs, src/Uno.UI.Runtime.Skia.Win32/Win32Host.cs
=> fix: avoid crashing on Windows when the MediaElement uno feature is present

src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.skia.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/private/issues/683
=> fix(TextBox): fix touch knob positioning when TextBox is scrolled

build/nuget/Uno.WinUI.Lottie.nuspec
closes https://github.com/unoplatform/private/issues/695
=> fix: Adjust for skiasharp 3 lottie reference

src/Uno.UI.Composition/Composition/CompositionVisualSurface.skia.cs, src/Uno.UI.Composition/Composition/Compositor.skia.cs, src/Uno.UI.Composition/Composition/RedirectVisual.skia.cs, src/Uno.UI.Composition/Composition/ShadowState.skia.cs, src/Uno.UI.Composition/Composition/Uno/Visual.PaintingSession.skia.cs, src/Uno.UI.Composition/Composition/Visual.skia.cs, src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/Renderer.cs, src/Uno.UI/Helpers/SkiaRenderHelper.skia.cs, src/Uno.UI/UI/Xaml/Media/Imaging/RenderTargetBitmap.skia.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/1112
=> perf(shadows): avoid SaveLayer calls in shadows

src/Uno.UI.Runtime.Skia.Win32.Support/NativeMethods.txt, src/Uno.UI.Runtime.Skia.Win32/Win32EventLoop.cs, src/Uno.UI.Runtime.Skia.Win32/Win32Host.cs
=> perf: use GetMessage instead of busy waiting with PeekMessage

src/Uno.UI.Runtime.Skia.Android/Microsoft/UI/Xaml/TextInputConnection.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/1121
- Bugfix
Backspace not working on certain phones 
=> fix(Droid): TextBox backspace

src/Uno.Sdk/targets/Uno.Common.Wasm.targets
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/1136
=> fix(wasm): Enable idbfs by default

src/Uno.UI/UI/Xaml/Media/Imaging/SvgImageSource.skia.cs
- Bugfix
The temporary reflection invocation uses the proper parameters.
=> fix: Fix invalid sk3 svg decoding

src/Uno.UI.Composition/Composition/Uno/UnoSkiaApi.skia.cs, src/Uno.UI/FeatureConfiguration.cs, src/Uno.UI/UI/Xaml/Documents/InlineCollection.skia.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno-private/issues/1124
=> fix(text): revert text rendering changes on non-WASM

src/Uno.Foundation/AssemblyInfo.cs, src/Uno.UI.Runtime.Skia.WebAssembly.Browser/WebAssemblyWindowWrapper.Interop.cs, src/Uno.UI.Runtime.Skia.WebAssembly.Browser/WebAssemblyWindowWrapper.cs, src/Uno.UI.Runtime.Skia.WebAssembly.Browser/ts/Runtime/WebAssemblyWindowWrapper.ts, src/Uno.UI/UI/Xaml/Window/Native/NativeWindowWrapper.wasm.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/1151
- Feature
=> feat: Adjust full screen mode support

src/Uno.UI/UI/Input/GestureRecognizer.Manipulation.InertiaProcessor.cs, src/Uno.UI/UI/Input/GestureRecognizer.Manipulation.cs, src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.Managed.cs, src/Uno.UI/UI/Xaml/Input/ManipulationInertiaStartingRoutedEventArgs.cs
Attempts:
closes https://github.com/unoplatform/uno-private/issues/1098
closes https://github.com/unoplatform/uno-private/issues/1034
closes https://github.com/unoplatform/uno-private/issues/1035
Improve touch scrolling experience
=> feat(scrolling): Scrolling experience

doc/articles/logging.md, src/Uno.Sdk/targets/Uno.SingleProject.iOS.targets
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/19878
- Bugfix
Work around linker issue in debug on physical devices.
=> fix: Adjust debug logging for iOS devices

build/nuget/Uno.WinUI.Svg.nuspec, src/AddIns/Uno.UI.Svg/External/SKSvg.Model.cs, src/AddIns/Uno.UI.Svg/External/SkiaAssetLoader.cs, src/AddIns/Uno.UI.Svg/External/SkiaModel.cs, src/Directory.Build.targets
Bump skia.svg base packages to 3.0
=> fix: Adjust svg.skia dependencies

src/Uno.UI.Runtime.Skia.AppleUIKit/UI/Xaml/Controls/TextBox/InvisibleTextBoxViewExtension.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.skia.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/914, closes https://github.com/unoplatform/uno-private/issues/1156
- Bugfix
=> fix: Initial focus on iOS, carets not disappearing

build/ci/.azure-devops-ios-tests.yml, src/Uno.UI.Runtime.Skia.AppleUIKit/UI/Xaml/RootViewController.cs, src/Uno.UI.Runtime.Skia.AppleUIKit/UI/Xaml/UnoSKMetalView.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/1109
=> chore: Adjust iOS rendering

src/Uno.UI.Composition/Composition/Visual.skia.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/1165
=> perf(skia): reduce SKCanvas.SetMatrix calls

src/Uno.UI/FeatureConfiguration.cs, src/Uno.UI/UI/Xaml/Documents/InlineCollection.skia.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/1148
=> chore: revert previous WASM text workaround

src/Uno.UI.Composition/Composition/Visual.skia.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/1176
=> chore: fix assert

src/Uno.UI/UI/Xaml/Application.Android.cs, src/Uno.UI/UI/Xaml/Application.cs, src/Uno.UI/UI/Xaml/Window/Native/NativeWindowWrapper.Android.cs
=> fix: Update status bar on theme change Android

src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/ScrollPresenter/ScrollPresenterTests.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/NavigationView/NavigationView.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/RadioButtons/RadioButtons.cs, src/Uno.UI/UI/Xaml/Controls/CommandBar/CommandBar.Partial.cs, src/Uno.UI/UI/Xaml/Input/FocusManager.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/1149
- Feature
=> feat: Mark legacy `FocusManager` methods as `Obsolete` and non-editor browsable

src/Uno.UI.Runtime.Skia.Android/Microsoft/UI/Xaml/ApplicationActivity.cs, src/Uno.UI.Runtime.Skia.WebAssembly.Browser/BrowserNativeElementHostingExtension.cs, src/Uno.UI.Runtime.Skia.Win32/Win32NativeElementHostingExtension.cs, src/Uno.UI.Runtime.Skia.Win32/Win32WindowWrapper.Rendering.cs, src/Uno.UI.Runtime.Skia.X11/X11AirspaceRenderHelper.cs, src/Uno.UI.Runtime.Skia.X11/X11SoftwareRenderer.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/1172
=> perf(airspace): do not set the native clip path if it did not change

doc/articles/common-issues-android.md, doc/articles/common-issues.md, doc/articles/toc.yml
- [xx] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.
=> docs: add error ADB0020 to android common issues

doc/articles/features/focus-management.md
=> docs: Specifying visual tree for focus operations

doc/articles/getting-started/wizard/includes/extensions.md
GitHub Issue (If applicable): closes https://github.com/unoplatform/private/issues/704
=> docs: add new http options

doc/articles/features/using-the-uno-sdk.md
GitHub Issue (If applicable): closes https://github.com/unoplatform/private/issues/706
=> docs: kiota and refit http feature

src/Uno.UI.Runtime.Skia.AppleUIKit/Extensions/CharacterExtensions.cs, src/Uno.UI.Runtime.Skia.AppleUIKit/UI/Xaml/Controls/TextBox/SinglelineInvisibleTextBoxDelegate.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno.chefs/issues/1471
- Bugfix
=> fix(iOS): input text commands

src/Uno.UI.Runtime.Skia.Win32/Win32EventLoop.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/1159
=> chore: catch TaskCanceledException in Win32's message loop

src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBlock.cs, src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.cs, src/Uno.UI/UI/Xaml/Documents/InlineCollection.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/19988
=> fix(InlineCollection): return up to date PreorderTree values

src/Uno.UI.Runtime.Skia.Win32/Win32WindowWrapper.Rendering.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/1194
=> fix: avoid crashing in software rendering when minimizing

src/Uno.UI.Composition/Composition/Compositor.skia.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/1103
=> fix(BackgroundTransition): keep rendering frames as long as a transition is active

src/SamplesApp/UITests.Shared/UITests.Shared.projitems, src/SamplesApp/UITests.Shared/Windows_Storage/Pickers/FileOpenPicker_Bitmap.xaml, src/SamplesApp/UITests.Shared/Windows_Storage/Pickers/FileOpenPicker_Bitmap.xaml.cs, src/Uno.UI/UI/Xaml/Media/ImageSource.crossruntime.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/962
- Bugfix
=> fix: Bitmap image loading on WASM

doc/articles/toc.yml
- Bugfix in TOC of Documentation
404 File not found
Page link updated to xref so it will be working again properly
=> fix(xBind): Fix TOC link that has been leading to a 404 file not found

src/Uno.UI.Runtime.Skia.AppleUIKit/UI/Xaml/AppleUIKitWindowWrapper.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/793
- Bugfix
Adjust for synchronous extended splash screen.
=> fix: Adjust splashscreen for delayed window.activate

src/Uno.UWP/UI/StartScreen/Extensions/JumpListItemExtensions.Android.cs, src/Uno.UWP/UI/StartScreen/Extensions/ShortcutInfoExtensions.Android.cs, src/Uno.UWP/UI/StartScreen/JumpList.Android.cs
=> feat: Use `ShortcutManagerCompat`

src/Uno.UI.Runtime.Skia.Android/Microsoft/UI/Xaml/ApplicationActivity.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/private/issues/717
=> fix: fix native element clipping on android when the clip is empty

src/Uno.Sdk/targets/Uno.DefaultItems.Resizetizer.targets
GitHub Issue (If applicable): closes unoplatform/private/issues/708
- Bugfix
[](fix: blurry splashscreen logo)
=> fix: blurry splashscreen logo

src/Uno.UI.Runtime.Skia.WebAssembly.Browser/ts/Runtime/ImageLoader.ts, src/Uno.UI/UI/Xaml/Media/Imaging/ImageSourceHelpers.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/1168
=> perf(wasm): load images using the browser Canvas API

src/Uno.UI/UI/Xaml/Controls/Popup/Popup.WithPopupRoot.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.skia.cs
=> Revert "feat: Propagate `Popup` `ZIndex` to `PopupPanel` (backport #20110)"

src/Uno.UI/UI/Xaml/Controls/Popup/Popup.WithPopupRoot.cs, src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.skia.cs
=> Revert "feat: Propagate `Popup` `ZIndex` to `PopupPanel`"

src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.skia.cs, src/Uno.UI/UI/Xaml/Internal/VisualTree.uno.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/1187
=> fix(textbox): keep textbox knob popups above all other popups

src/Uno.UI.Composition/Composition/AnimationController.cs, src/Uno.UI.Composition/Composition/KeyFrameAnimation.cs, src/Uno.UI.Composition/Composition/KeyFrameAnimations/IKeyFrameEvaluator.cs, src/Uno.UI.Composition/Composition/KeyFrameAnimations/KeyFrameEvaluator.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_FlipView.cs, src/Uno.UI/UI/Input/GestureRecognizer.Manipulation.InertiaProcessor.cs, src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/CompositorScrollStrategy.cs, src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.Managed.cs, src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.SnapPoints.cs, src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.cs
closes https://github.com/unoplatform/uno-private/issues/1178
Fix FlipView not considering velocity/inertia to flip items
=> fix(flipView): Fix FlipView not considering velocity/inertia to flip items

src/Uno.UI.Runtime.Skia.Android/AndroidSkiaWindowFactory.cs, src/Uno.UI.Runtime.Skia.AppleUIKit/UI/Xaml/AppleUIKitWindowWrapper.cs, src/Uno.UI.Runtime.Skia.AppleUIKit/UI/Xaml/UnoSKMetalView.cs, src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/UI/FrameBufferWindowWrapper.cs, src/Uno.UI/UI/Xaml/Window/Native/Factory/NativeWindowFactory.cs, src/Uno.UI/UI/Xaml/Window/Native/NativeWindowWrapper.UIKit.cs, src/Uno.UI/UI/Xaml/Window/Native/NativeWindowWrapperBase.cs
=> fix: Add missing `Window` and `XamlRoot` setters

src/SamplesApp/SamplesApp.Skia/SamplesApp.Skia.csproj, src/SourceGenerators/Uno.UI.SourceGenerators/BindableTypeProviders/BindableTypeProvidersGenerationTask.cs, src/SourceGenerators/Uno.UI.SourceGenerators/BindableTypeProviders/DependencyObjectAvailabilityGenerator.cs, src/SourceGenerators/Uno.UI.Tasks/Content/Uno.UI.Tasks.targets
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/1140, closes https://github.com/unoplatform/uno-private/issues/1141
- Bugfix
Adjust linker hints generation for `BindableMetadataProvider` to it can be externally removed, use proper assemblies list as generated by the linker preparation.
=> fix(skia): Adjust xaml trimming sequencing

src/Uno.UI.Runtime.Skia.MacOS/UnoNativeMac/UnoNativeMac/UNOWindow.m
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/20116
- Bugfix
Keyboard modifiers changes on macOS were not detected.
Keyboard modifiers changes on macOS are now detected.
Can be tested with `UITests.Windows_UI_Xaml_Input.Keyboard.Keyboard_Modifiers` inside SamplesApp
=> fix(macOS): Route keyboard modifiers changes from native to managed

src/Uno.UI.Runtime.Skia.Win32/Win32Helper.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/1229
=> fix: make wglMakeCurrent checks log errors instead of throwing

doc/articles/features/Lottie.md
Updated branding so google and AI can find accurate answer
=> docs: Update Lottie.md

src/Uno.UI.Runtime.Skia.Android/Microsoft/UI/Xaml/ApplicationActivity.cs, src/Uno.UI.Runtime.Skia.Android/Microsoft/UI/Xaml/UnoSKCanvasView.cs
- Bugfix
Pause the render thread when the app is idle.
=> fix(android): Pause drawing when not rendering

src/SamplesApp/SamplesApp.Shared/App.xaml.cs, src/Uno.UI.Runtime.Skia.Android/Microsoft/UI/Xaml/ApplicationActivity.cs, src/Uno.UI/UI/Xaml/ApplicationActivity.Android.cs, src/Uno.UI/UI/Xaml/Internal/ContentManager/ContentManager.Android.cs, src/Uno.UI/UI/Xaml/NativeApplication.cs, src/Uno.UI/UI/Xaml/Window/Native/NativeWindowWrapper.Android.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/1171
- Bugfix
- Feature
Black screen shows up when initialization is asynchronous on Android
No black screen
=> Support for async initialization on Android

src/Uno.UI.Composition/Composition/Visual.cs, src/Uno.UI.Composition/Composition/Visual.skia.cs, src/Uno.UI.RuntimeTests/Tests/Windows_UI_Composition/Given_ContainerVisual.cs
=> fix: invalidate Visual.TotalMatrix when changing parents

src/Uno.UI.Runtime.Skia.WebAssembly.Browser/ts/Runtime/ImageLoader.ts, src/Uno.UI/UI/Xaml/Media/Imaging/ImageSourceHelpers.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/1249
=> fix(wasm): images are sometimes corrupted

src/Uno.UI.Runtime.Skia.AppleUIKit/UI/Xaml/AppleUIKitWindowWrapper.cs, src/Uno.UI.Runtime.Skia.AppleUIKit/Uno.UI.Runtime.Skia.AppleUIKit.csproj, src/Uno.UI/UI/Xaml/Window/Native/NativeWindowWrapper.UIKit.cs, src/Uno.UI/UI/Xaml/Window/Native/UIKit/NativeWindowHelpers.UIKit.cs
=> fix: Delayed splash screen on UIKit

src/Uno.UI.Runtime.Skia.WebAssembly.Browser/BrowserPointerInputSource.cs, src/Uno.UI/Microsoft/UI/Xaml/Controls/PullToRefresh/RefreshContainer/RefreshContainer.mux.cs, src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.cs
=> chore: Misc non functional fixes

doc/articles/features/using-skia-hosting-native-controls.md, src/AddIns/Uno.UI.MediaPlayer.Skia.Win32/Win32MediaPlayerPresenterExtension.cs, src/AddIns/Uno.UI.MediaPlayer.Skia.X11/X11MediaPlayerPresenterExtension.cs, src/AddIns/Uno.UI.WebView.Skia.X11/X11NativeWebView.cs, src/Uno.UI.Runtime.Skia.Win32/Win32DragDropExtension.cs, src/Uno.UI.Runtime.Skia.Win32/Win32NativeElementHostingExtension.cs, src/Uno.UI.Runtime.Skia.Win32/Win32NativeWebView.cs, src/Uno.UI.Runtime.Skia.Win32/Win32WindowWrapper.cs, src/Uno.UI.Runtime.Skia.X11/X11NativeElementHostingExtension.cs, src/Uno.UI.Runtime.Skia.X11/X11NativeElementHostingExtension.helper.cs, src/Uno.UI.Runtime.Skia.X11/X11WindowWrapper.cs, src/Uno.UI/NativeElementHosting/Win32NativeWindow.cs, src/Uno.UI/NativeElementHosting/X11NativeWindow.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/private/issues/745
=> docs: rewrite docs for skia native element hosting

build/ci/.azure-devops-android-tests.yml, build/ci/.azure-devops-ios-testflight.yml, build/ci/.azure-devops-ios-tests-run.yml, build/ci/.azure-devops-ios-tests.yml, build/ci/.azure-devops-project-template-tests.yml, build/ci/.azure-devops-skia-tests-android.yml, build/ci/.azure-devops-skia-tests-browser.yml, build/ci/.azure-devops-skia-tests-build-android.yml, build/ci/.azure-devops-skia-tests-build-browser.yml, build/ci/.azure-devops-skia-tests-build-ios.yml, build/ci/.azure-devops-skia-tests-build.yml, build/ci/.azure-devops-skia-tests-ios.yml, build/ci/.azure-devops-skia-tests-linux.yml, build/ci/.azure-devops-skia-tests-macos.yml, build/ci/.azure-devops-skia-tests-windows.yml, build/ci/.azure-devops-skia-tests.yml, build/ci/.azure-devops-stages.yml, build/ci/.azure-devops-unit-tests.yml, build/ci/.azure-devops-wasdk.yml, build/ci/.azure-devops-wasm-uitests.yml
=> ci: Adjust stage names

doc/articles/uno-publishing-overview.md
Fitting title with marketecture
=> doc:s Update uno-publishing-overview.md

build/ci/.azure-devops-ios-tests-run.yml, build/ci/.azure-devops-wasm-uitests.yml
=> ci: TestRunName not resolving
