- src/SamplesApp/SamplesApp.UITests/TestFramework/ImageAssert.ExpectedPixels.cs
- src/SamplesApp/SamplesApp.UITests/TestFramework/ImageAssert.cs
- src/SamplesApp/SamplesApp.UITests/Toolkit/UnoSamples_Tests.ElevatedView.cs
- src/SamplesApp/UITests.Shared/Toolkit/ElevatedViewTests.xaml
- src/SamplesApp/UITests.Shared/Toolkit/ElevatedView_CornerRadius.cs
- src/SamplesApp/UITests.Shared/Toolkit/ElevatedView_CornerRadius.xaml
- src/SamplesApp/UITests.Shared/Toolkit/ElevatedView_Corners.xaml
- src/SamplesApp/UITests.Shared/Toolkit/ElevatedView_Corners.xaml.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/Uno.UI.Toolkit/ElevatedView.cs
- src/Uno.UI.Toolkit/UIElementExtensions.cs
- src/Uno.UI.Toolkit/Uno.UI.Toolkit.Wasm.csproj
- src/Uno.UI.Toolkit/Uno.UI.Toolkit.csproj
- src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/NativeScrollContentPresenter.Android.cs
Fixes https://github.com/unoplatform/nventive-private/issues/31
[Android] `NativeScrollViewerPresenter` were clipping its children. This is the role of the `ScrollViewer` itself, not the presenter.
> [Android] NativeScrollViewerPresenter was clipping its children.

- src/Uno.UI/UI/Xaml/Shapes/Shape.layout.cs
GitHub Issue (If applicable): https://github.com/unoplatform/nventive-private/issues/39
- Bugfix
Shapes using 1px thickness may get an invalid origin and get clipped.
Shapes are not clipped.
> fix(shapes): Invalid shape positioning for 1px thickness

- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.wasm.cs
- src/Uno.UI/UI/Xaml/ElementStub.cs
- src/Uno.UI/WasmCSS/Uno.UI.css
- src/Uno.UI/WasmScripts/Uno.UI.d.ts
- src/Uno.UI/WasmScripts/Uno.UI.js
- src/Uno.UI/ts/WindowManager.ts
GitHub Issue: fixes https://github.com/unoplatform/uno/issues/4354
Fix a regression introduced by managed scroll bars where 2 vertical scrollbars appears in `TextBox` when configured to allow returns.
Previously the scrolling was handled by the native `textarea`.
The `textarea` is stretched to match its content size and the scrolling is delegated to its parent managed `ScrollViewer`.
> Fix multiline TextBox scrollbars

- doc/articles/platform-specific-xaml.md
GitHub Issue (If applicable): #3656
The modification to the prefix was not documented
Now it is.
> doc: Document prefix differences for cross target libraries.

- src/Uno.UI.RuntimeTests/Tests/Uno_Helpers/Given_StartStopEventWrapper.cs
- src/Uno.UWP/Helpers/StartStopEventWrapper.cs
GitHub Issue (If applicable): closes #3310 
Code duplication of event handlers which need to start/stop a native platform action on first/last subscriber.
Avoided code duplication with a custom event wrapper.
> StartStopEventWrapper

- src/SamplesApp/SamplesApp.UITests/RuntimeTests.cs
Android RuntimeTests are often timing out.
Increased the limit to 500000.
> Bump runtime tests timeout

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Functions_Control.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Functions_Control.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Given_xBind_Functions.cs
closes #4247 
- Bugfix
Using x:Bind against a constant is raising an error:
`error CS7000: Unexpected use of an aliased name`
Using x:Bind against a constant shouldn't raise an error
> Handle const fields in XAML code generation

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ContentDialog/UnoSamples_Tests.ContentDialog.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ContentDialogTests/ContentDialog_Async.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ContentDialogTests/ContentDialog_Async.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ContentDialogTests/ContentDialog_Closing.xaml.cs
- src/Uno.UI/UI/Xaml/Controls/ContentDialog/ContentDialog.cs
GitHub Issue (If applicable): fixes #4428
- Bugfix
On Android and iOS, awaiting `ContentDialog.ShowAsync()` didn't return with `ContentDialogResult.None` if `ContentDialog.Hide()` was called to dismiss it.
It now does.
I don't think this PR contains any breaking changes.
> Make ContentDialog.ShowAsync awaitable return result on Hide() call

- src/Uno.UI.Tests/BinderTests/Given_Binder.cs
- src/Uno.UI/DataBinding/BindingExpression.cs
GitHub Issue (If applicable): Closes #4469
- Bugfix
We believe this is a legacy part of code, probably prior to being able to use a StaticResource reference as the source.  The new behavior matches UWP.
Unit Test Results
Before:
After:
> fix: BindingExpression failed to apply string explicit source.

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/ListViewPages/ListViewTemplateOuterBindingPage.xaml
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/ListViewPages/ListViewTemplateOuterBindingPage.xaml.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBaseSource.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/Primitives/SelectorItem.iOS.cs
Bindings by ElementName to an element outside of a ListViewItem template were getting detached in some cases after the list was unloaded from the window and reloaded, because the ListViewItem's logical Parent was incorrectly getting set to the visual-tree parent (which is a native UIView imposed by UICollectionView). Ensure the logical Parent is correctly restored.
- Bugfix
fixes https://github.com/unoplatform/nventive-private/issues/82
> fix(listview): [iOS] Fix outer ElementName bindings not available on reload

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_FrameworkElement.cs
- src/Uno.UI/UI/Xaml/UIElementCollectionExtensions.Xamarin.cs
- Bugfix
`UIElementCollection.Add` no longer adding view twice when the view is both an UIElement and a native view
https://github.com/unoplatform/nventive-private/issues/84
> fix: UIElementCollection adding the view twice

- src/SamplesApp/SamplesApp.Shared/App.xaml.cs
- src/SamplesApp/SamplesApp.UITests/Extensions/AppExtensions.cs
- src/SamplesApp/SamplesApp.UITests/Extensions/AppRect.cs
- src/SamplesApp/SamplesApp.UITests/Extensions/AppRectExtensions.cs
- src/SamplesApp/SamplesApp.UITests/Extensions/FluentExtensions.cs
- src/SamplesApp/SamplesApp.UITests/Extensions/QueryExtensions.cs
- src/SamplesApp/SamplesApp.UITests/SampleControlUITestBase.cs
- src/SamplesApp/SamplesApp.UITests/TestFramework/ImageAssert.ExpectedPixels.cs
- src/SamplesApp/SamplesApp.UITests/TestFramework/ImageAssert.cs
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TextBlockTests/TextBlockTests.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/ImageUniformWithinScrollViewer.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/ImageUniformWithinScrollViewer.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/SimpleText_MaxLines_Two.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/SimpleText_MaxLines_Two_With_Wrap.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/SimpleText_MaxLines_Two_With_Wrap.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/Simple_Contrained_Horizontal_Center_Wrap.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/Simple_Contrained_Horizontal_Center_Wrap.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/TextBlock_ConstrainedByContainer.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/TextBlock_LineHeight_TextTrimming.xaml
- src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.Android.cs
Fixes #4414 
Fix measurement bug on Android.
Result from `.Measure()` were capped to `availableSize`, preventing the layout engine from applying clipping when required.
`.Measure()` now returns actual text size.
> Fix for Android .Measure() bug on TextBlock

- src/Uno.UI.Runtime.Skia.Gtk/GTK/GtkCoreWindowExtension.Keyboard.cs
- Bugfix
Adjust for missing operator keys for GTK.
> fix(keyboard): [Gtk] Add missing operators mapping

- src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/FrameworkElementTests/FrameworkElement_Sizes.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/FrameworkElementTests/FrameworkElement_Sizes.xaml.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_FrameworkElement.cs
- src/Uno.UI/DataBinding/BindingPropertyHelper.FastConvert.cs
Fixes #4403
It is now possible to set bound values (and style setters) as 'Auto' in dependency properties.
> Add support for "Auto" for control size

- src/Uno.UI.Toolkit/ElevatedView.cs
- src/Uno.UI/UI/Xaml/Controls/Border/Border.iOSmacOS.cs
- src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.iOSmacOS.cs
- Bugfix
On iOS, there are some timing issues between when the ElevatedView draw itself and when its nested Border has its BoundsPath calculated. In rare situations, ElevatedView could end up painting the elevation before the BoundsPath is re-calculated causing nothing to be painted.
Ensure the ElevatedView is repainted after its Border.BoundsPath is updated.
Due to complexity of the situation, I have not been able to produce a ui-test.
https://github.com/unoplatform/nventive-private/issues/60
> fix(elevatedview): UpdateElevation timing issue

- src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.Items.cs
GitHub Issue (If applicable): #1045
-
New tests that can be used to verify `ListView` `Items` - `ItemsSource` sync.
Also allows ignoring a whole `TestClass` in runtime tests.
> Items - ItemsSource sync tests

- src/SourceGenerators/Uno.UI.SourceGenerators.Tests/Given_SymbolExtension.cs
- src/SourceGenerators/Uno.UI.SourceGenerators.Tests/Uno.UI.SourceGenerators.Tests.csproj
- src/SourceGenerators/Uno.UI.SourceGenerators/BindableTypeProviders/BindableTypeProvidersGenerationTask.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/Helpers/SymbolExtensions.cs
- Bugfix
Using a public property that uses tuples fails at compile time when Roslyn is 3.5 or later.
The build does not fail.
> fix(generation): Fixes invalid Tuples expansion using Roslyn 3.5 and later

- src/SolutionTemplate/UnoSolutionTemplate.Wizard/UnoSolutionWizard.cs
- src/Uno.UI/Uno.UI.Skia.csproj
- src/Uno.UWP/Helpers/Theming/SystemThemeHelper.wasm.cs
- Bugfix
The UWP project is set as startup by default when creating a project from the VSIX template.
> fix(wizard): UWP project is not set as startup by default

- src/Uno.UWP/Helpers/Theming/SystemThemeHelper.wasm.cs
Fixes #4552 
- Bugfix
Fixes the Themeing support when running withing the WinUI converted source tree.
> fix(winui): Adjust WebAssembly support for WinUI 3 dotnet new template

- src/Uno.UI/UI/Xaml/Controls/ItemCollection.cs
GitHub Issue (If applicable): #1045
- Feature
`ItemCollection` is a standalone collection.
`ItemCollection` can be set to be in sync with an `ItemsSource`. However, the method is **not called anywhere**, which means the changes do not affect any behavior of `ItemsControl` or `ListView` yet.
> Sync ItemCollection with ItemsSource

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/Uno.UI.Tests/Windows_UI_Xaml/Controls/When_xLoad_DataTemplate.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml/Controls/When_xLoad_DataTemplate.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml/Controls/When_xLoad_Multiple.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml/Given_xLoad.cs
GitHub Issue (If applicable): #4557
- Bugfix
Fix invalid generated code when x:Load, StaticResource and Visibility are used simultaneously.
> fix(xLoad): Fix invalid generated code when x:Load, StaticResources and Visibility are used

- doc/articles/platform-specific-xaml.md
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/InfoBarTests/InfoBarPage.xaml
- src/SamplesApp/UITests.Shared/Windows_Devices/Midi/MidiDeviceOutput.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/GradientBrushTests/GradientsPage.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/GradientBrushTests/RadialGradientBrushPage.xaml
- Bugfix
Missing slash character in namespaces declarations referring to Uno URIs
Added missing slash character in namespaces declarations referring to Uno URIs in the documentation and xaml files.
> fix: Add missing slash character in namespaces declarations referring to Uno URIs

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/Uno.UI/UI/Xaml/UIElement.wasm.cs
- Bugfix
.NET 5 FullAOT builds are starting properly.
> fix: [Wasm] Adjust assembly loading for .NET 5

- src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePicker.cs
- Bugfix
TimePicker LightDismissOverlayBackgroundProperty was being set a wrong resource
Using the right resource for the TimePicker LightDismissOverlayBackgroundProperty
> fix: TimePicker LightDismissOverlayBackgroundProperty

- src/Uno.UI/Extensions/ViewHelper.Android.cs
- Bugfix
Setting `IgnoreTextScaleFactor = true` doesn't prevent Android app from changing text scale when device's text size is changed while the app is running.
Setting `IgnoreTextScaleFactor = true` always prevents Android app from changing text scale.
> fix: ViewHelper.Android not considering IgnoreTextScaleFactor at runtime

- src/Uno.UI.Tests/BinderTests/Given_Binder.Converter.cs
- src/Uno.UI/DataBinding/BindingExpression.cs
GitHub Issue (If applicable): Closes #4458
- Bugfix
When using a Converter that returns DependencyProperty.UnsetValue, the BindingExpression will currently throw an exception, output to the log, then apply the FallbackValue.
The BindingExpression will apply the FallbackValue without throwing the exception which helps performance as well as not outputting errors to the log.
No unit test can be written, since the outcome is the same aside from the internal exception and log output.
> fix: BindingExpression will now apply the FallbackValue when a Converter returns DependencyProperty.UnsetValue

- src/Uno.CrossTargetting.props
- src/Uno.UI/UI/Xaml/UIElement.Pointers.Skia.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.cs
fixes #4603
Buttons are not responding properly, especially if we don't move the pointer when double clicking a button the second click event won't be raised.
When raising the pointer release event, we raise it either on the element which captured the pointer, either on the current "original source". But the "original source" element that was pressed might not be in the hierarchy and might stay flagged as pressed.
In particular, when captured on pressed (`ButtonBase`) the sub-elements won't receive the release.
On pointer press, we store the "original source" then on pointer release we make sure to walk the tree up from this element to reset the pressed state.
> fix(pointers): Make sure to clear the pressed state

- src/Directory.Build.targets
Raise an error when building the uno.ui solution from a path containing spaces.
> build: Fail solution build on path with spaces

- src/Uno.UI.Runtime.WebAssembly/Xaml/UIElementWasmExtensions.cs
- src/Uno.UI/UI/Xaml/Controls/Image/Image.wasm.cs
- src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.wasm.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.wasm.cs
- src/Uno.UI/UI/Xaml/FrameworkElement.wasm.cs
- src/Uno.UI/UI/Xaml/UIElement.EventRegistration.wasm.cs
- src/Uno.UI/UI/Xaml/UIElement.GenericEventHandlers.wasm.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.wasm.cs
- src/Uno.UI/UI/Xaml/UIElement.wasm.cs
- Bugfix
Workaround .NET 6 memory corruption issue https://github.com/dotnet/runtime/issues/45304, but removing the use of `Delegate.DynamicInvoke` and also improve performance as a result.
> perf: [Wasm] Improve DOM routed events dispatch performance

- build/Uno.WinUI.nuspec
- src/Directory.Build.targets
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/4574
- Bugfix
Removes the dependency on `DOTNET_PATH` to detect .NET Core/5.
> chore: Update to Uno.SourceGeneration 3.0.0-dev.21

- src/SamplesApp/SamplesApp.UITests/Wasm/Given_CustomEvents.cs
- src/SamplesApp/UITests.Shared/Wasm/Wasm_CustomEvent.xaml
- src/SamplesApp/UITests.Shared/Wasm/Wasm_CustomEvent.xaml.cs
- src/Uno.UI.Runtime.WebAssembly/Xaml/UIElementWasmExtensions.cs
Fixes https://github.com/unoplatform/uno/issues/4650
Casting of handler + EventArgs was wrong in refactoring. There was no automated tests to prevent this.
Regression fixed.
> [Wasm] Fixed Html custom event regression

- src/Uno.UI/Controls/CommandBarHelper.iOS.cs
- Bugfix
iOS throwing exception when setting a NavigationBar to null.
No exception is raised when the NavigationBar is set to null since this is commonly used in the code.
> fix(iOS): [Commandbar] SetNavigationBar throwing exception when null

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/xBind_UserControl.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/xBind_UserControl.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Given_xBind_UserControl.cs
GitHub Issue (If applicable): fixes #4680 
- Bugfix
`x:Bind` is now working properly for controls that omit the specification of the base class in code-behind.
> fix(xBind): Invalid xBind initialization on controls without code-behind base class

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/TappedTapped_Tests.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Input/GestureRecognizerTests/TappedTest.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Input/GestureRecognizerTests/TappedTest.xaml.cs
- src/Uno.UI/UI/Xaml/RoutedEvent.cs
- src/Uno.UI/UI/Xaml/RoutedEventFlag.cs
- src/Uno.UI/UI/Xaml/UIElement.RoutedEvents.cs
`Tapped` event is bubbling even if the args are marked as `Handled = true`.
When a gesture and manipulation events bubbles to the parent, it will disable the local gesture recognizer of the parent in order to avoid double event. But if the event args is flagged as `Handled = true` the bubbling stops, so the parent's recognizer still detects a "tapped gesture" so it will fire the `Tapped` event again on it's own.
Manipulation and gesture events are flagged "always bubbling" so even if handled, they will bubble to the parent and disable the local `GestureRecognizer`
> Fix tapped event bubbling when handled

- src/SourceGenerators/Uno.UI.SourceGenerators/BindableTypeProviders/BindableTypeProvidersGenerationTask.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/DependencyObject/DependencyObjectGenerator.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/DependencyObject/DependencyPropertyGenerator.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/Helpers/RoslynMetadataHelper.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/Helpers/SymbolExtensions.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/NativeCtor/NativeCtorsGenerator.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/TSBindings/TSBindingsGenerator.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/Telemetry/TelemetryClient.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/Uno.UI.SourceGenerators.csproj
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.Reflection.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- Makes Uno.UI.SourceGenerators fail with warnings as errors
- Fix roslyn type comparisons
- Fix possible null references
> refactor: Remove roslyn warnings for types comparisons

- src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.DragDrop.cs
Fixes https://github.com/unoplatform/uno/issues/4725
Fix possible null ref
Even if flagged as not possible by the nullable check we can get a `null` `itemContainer` 
🙃
> fix(dragdrop): Fix possible null ref in Drag and Drop

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml/DragAndDropTests/DragDrop_ListViewReorder_Automated.cs
- src/Uno.UI/UI/Xaml/Controls/ItemsStackPanel/ItemsStackPanelLayout.managed.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.DragDrop.cs
Fixes https://github.com/unoplatform/uno/issues/4274
Tabs reorder is not working properly on WASM + tests are disabled
When dragging a tab in WASM (or skia) it will always be placed at the end of the list
🙃
> fix(dragdrop): Add missing file for ListView drag and drop support

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_NativeFrame.cs
- src/Uno.UI/FeatureConfiguration.cs
- src/Uno.UI/NativeFramePresenter.Android.cs
The behavior is now similar to the one from the iOS NativeFramePresenter, which keeps all pages loaded and stacked on top of each other.
GitHub Issue (If applicable): https://github.com/unoplatform/nventive-private/issues/102
- Bugfix
The android native frame presenter detaches pages that are in the backstack. This causes the pages to be unloaded, then reloaded on back navigation, causing implicit styles to be reevaluated.
The pages are now kept attached and stacked on top of each other. The behavior can be altered by using `FeatureConfiguration.NativeFramePresenter.AndroidUnloadInactivePages`, which is set to false by default.
> perf(NativeFramePresenter): [Android] Don't detach pages in the backstack

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- Bugfix
Fixes the generated code for Xamarin.Forms renderers and fully qualify the use of ResourceDictionary.
> fix(reg): Fully qualify resource dictionary for generated `GetResourceDictionary`

- build/ci/.azure-devops-skia-tests.yml
GitHub Issue (If applicable): #4317 
Because the GTK3 runtime installation sometimes takes longer, the test may get cancelled due to timeout.
Increased timeout to 40 minutes.
> ci: Increase timeout for Skia UI tests

- build/ci/templates/gitversion.yml
Pins gitversion to 5.5.1 to avoid updating to .NET 5 for all pipelines.
> ci: Pin GitVersion to 5.5.1

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/FramePages/FirstPage.xaml
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/FramePages/FirstPage.xaml.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/FramePages/SecondPage.xaml
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/FramePages/SecondPage.xaml.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_NativeFrame.cs
- src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.csproj
- src/Uno.UI/UI/Xaml/Controls/Frame/Frame.cs
Closes https://github.com/unoplatform/nventive-private/issues/137
- Bugfix
Setting `Frame.Content` to `null` and then navigating using `Frame.Navigate` causes the page we just navigated from to not be added to the `Frame.BackStack`. Also causes iOS to not navigate at all when using the Native Frame Presenter
`Frame`'s `BackStack` is intact after navigation and navigation is performed properly.
> fix: Keep track of current view type even if content is set to null

- doc/articles/how-to-host-a-webassembly-app.md
- src/SamplesApp/SamplesApp.Wasm/wwwroot/web.config
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.Wasm/wwwroot/web.config
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/xamarinforms-wasm/UnoXFQuickStart.Wasm/wwwroot/web.config
- src/SolutionTemplate/UnoSolutionTemplate/Wasm/wwwroot/web.config
- Bugfix
Adjust mime types for .NET 5 support (`icudt.dat` needs to have its extension allowed in the web.config file)
> fix: Missing mime type for icudt.dat for .NET5 support

- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/TabViewTests/TabViewBasicPage.xaml
- src/Uno.Foundation/Metadata/ApiInformation.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_Foundation/Metadata/Given_ApiInformation.cs
- src/Uno.UI/UI/Xaml/Controls/BitmapIcon.cs
GitHub Issue (If applicable): fixes #4803
- Bugfix
Querying `ApiInformation.IsPropertyPresent` twice for the same existing property returns `true` and `false`.
API returns the same result each time.
> fix: Double query of ApiInformation.IsPropertyPresent returns different results

- src/Uno.UI.Tests/Windows_Globalization/When_Calendar.cs
- src/Uno.UWP/Globalization/Calendar.cs
- Bugfix
Fixes invalid dependency on DateTimeOffset.Now in Calendar.
> fix(Calendar): Fix `Calendar.YearAsString()` and `Calendar.YearAsTruncatedString()`

- src/Uno.Foundation/Metadata/ApiInformation.shared.cs
- src/Uno.UI.FluentTheme/Resources/PriorityDefault/TabView.xaml
- src/Uno.UI.FluentTheme/themeresources.xaml
- src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/Repeater/EffectiveViewportScrollViewerTests.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/TabView/TabView.xaml
- Fixes #4793 where Content top padding was not correctly applied due to the fact that API information reported API availability matching SDK 17134, while Uno supports 19041
- Updates TabView FluentStyles style to be buildable with new contract support, because {Binding} is not supported in Style Setters yet (#4826)
- Bugfix
Padding not correct.
Padding matches WinUI.
> fix(NavigationView): Content top padding is not correct

- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/.template.config/template.json
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-winui/.template.config/template.json
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp/.template.config/template.json
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unolib-crossruntime/.template.config/template.json
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unolib/.template.config/template.json
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/xamarinforms-wasm/.template.config/template.json
This change disambiguates from VS 2019 vsix templates visually.
- Bugfix
This change disambiguates from VS 2019 vsix templates from dotnet new templates visually.
> fix(dotnetnew): Add `dotnet-new` classification to dotnet new templates

- src/Uno.UI.Tests/Windows_UI_XAML_Controls/PasswordBoxTests/Given_PasswordBox.cs
- src/Uno.UI/UI/Xaml/Controls/PasswordBox/PasswordBox.cs
GitHub Issue (If applicable): https://github.com/unoplatform/nventive-private/issues/142
- Bugfix
Databinding null to `PasswordBox.Password` won't raise an exception and rely on coercion to set an empty string.
> fix(passwordbox): Don't fail on setting null on PasswordBox.Password

- src/SolutionTemplate/UnoSolutionTemplate/UWP/Package.appxmanifest
The moniker is substituted by MSBuild on build
If you decide to rename UWP assembly name you will get a weird error without any clue how to fix it.
Unless you know the trick you will spend hours if ever find it.
The error will not occur if you rename UWP assembly
> Fixed UWP manifest to use project executable as app automatically by setting substitution moniker

- src/SourceGenerators/Uno.UI.SourceGenerators/DependencyObject/DependencyPropertyGenerator.cs
- src/Uno.UI.Tests/BinderTests/Given_Binder.LocalCache.cs
- src/Uno.UI.Tests/Windows_UI_Xaml/FrameworkElementTests/Given_FrameworkElement.cs
- src/Uno.UI/UI/Xaml/FrameworkElement.Interface.net.cs
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/4834
- Bugfix
Setting null to `FrameworkElement.IsEnabled` through SetValue does not fail.
> fix(DependencyObject): Fix invalid cast in generated DependencyProperty coerce

- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_PropertyChangedAll.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_PropertyChangedAll.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Given_xBind_Binding.cs
- src/Uno.UI/DataBinding/BindingPath.cs
GitHub Issue (If applicable): fixes #4576
- Feature
Not supported
`PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(null));` updates all bindings on that object.
> PropertyChangedEventArgs.PropertyName null updates all bindings

- src/Uno.UWP/Storage/StorageFile.cs
- src/Uno.UWP/Storage/StorageFile.skia.cs
closes #4832 
- Feature
Skia based apps cannot use `StorageFile.GetFileFromApplicationUri()`
`StorageFile.GetFileFromApplicationUri()` is available for Skia based Apps
> feat(skia): Enable StorageFile.GetFileFromApplicationUri

- doc/articles/uno-fluent-assets.md
Fluent symbol docs missing info on usage (see https://stackoverflow.com/questions/65456676/how-to-use-font-icon-on-uno-platform)
Added samples
> docs: Add more info to Fluent symbol font usage

- src/Uno.UI/UI/Xaml/Application.cs
- Bugfix
The first resolution of `ThemeDictionary` may return the light theme incorrectly.
There are no tests for this specific change as it impacts the `Application.Current`. 
The validation for this change can be done through the Uno Gallery at https://github.com/unoplatform/Uno.Gallery/commit/9fbf14903b7ca0d3d3cac48c8bc51e5790590c51. The background should be dark when system settings are dark.
> fix(ResourceDictionary): Default theme may not be valid on first call

- src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerSelector.iOS.cs
- Bugfix
On iOS the flyout  of the TimePicker does not open
Make sure iOS flyout opens
> fix(TimePicker): Make sure iOS flyout opens

- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/xBindTests/xBind.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/xBindTests/xBind_Field.xaml.cs
- src/Uno.UI.Tests/BinderTests/Given_Binder.cs
- src/Uno.UI/DataBinding/BindingPath.cs
- src/Uno.UI/DataBinding/BindingPropertyHelper.cs
- src/Uno.UI/UI/Xaml/DependencyObjectStore.Binder.cs
GitHub Issue (If applicable): fixes #4883
- Bugfix
Does not work.
Does work 🚀
> fix: x:Bind to fields with non-OneTime mode

- src/Uno.UI/UI/Xaml/Controls/TextBox/MultilineTextBoxView.iOS.cs
GitHub Issue (If applicable): Fixes https://github.com/unoplatform/nventive-private/issues/145
- Bugfix
Single line:
https://user-images.githubusercontent.com/5839577/104464725-4283ad00-5581-11eb-9c26-0f84ffff898c.png
Multiline:
https://user-images.githubusercontent.com/5839577/104464759-4b747e80-5581-11eb-9c8c-3f83a32174c0.png
The default 8px top padding of the multiline textbox is now removed.
> fix(TextBox): [iOS] Remove the top margin of the MultilineTextBox

- src/Uno.UI/FeatureConfiguration.cs
- src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerSelector.iOS.cs
closes #4611 
- Bugfix
Issues on TimePicker with iOS14+ style not allowing to select a new time because the keyboard was dismissing the Picker Dialog.
Preventing the keyboard from showing allows the users to pick the new Time "scrolling".
> Fix(iOS) TimePicker bug selecting new Time

- src/SourceGenerators/Uno.UI.SourceGenerators/Telemetry/TelemetryClient.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/Uno.UI.SourceGenerators.csproj
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/4902
- Bugfix
The Telemetry client is now released after each use of the generator instance.
> fix: memory leak in telemetry

- src/Uno.UI/UI/Xaml/Media/Animation/Animators/GPUFloatValueAnimator.iOSmacOS.cs
- src/Uno.UWP/UI/Composition/CoreAnimation.iOSmacOS.cs
- src/Uno.UWP/UI/Composition/SpriteVisual.iOS.cs
GitHub Issue (If applicable): Fixes https://github.com/unoplatform/nventive-private/issues/139, Fixes https://github.com/unoplatform/nventive-private/issues/123.
- Bugfix
This change cancels repeatable animations to avoid being stuck in a very tight loop when trying to animate a detached layer. This can happen when Storyboards are running, and animating an unloaded control.
> fix(animations): [iOS] Cancel animators on detached layers

- src/SolutionTemplate/UnoSolutionTemplate/Shared/App.xaml.cs
- src/SolutionTemplate/UnoSolutionTemplate/Shared/UnoQuickStart.Shared.projitems
GitHub Issue (If applicable): closes #4928, fixes #4927
- Bugfix
- Feature
-
- Shared suffix removed from `Shared` project root namespace
- No warning/error under `nullable` context
> Solution template improvements

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement_And_Leak.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/4953
The `When_Add_Remove(Windows.UI.Xaml.Controls.Primitives.ScrollBar, 15)` runtime test is temporarily disabled until the issue is fixed.
> ci: Temporarily disable ScrollBar leak tests

- src/SourceGenerators/Uno.UI.SourceGenerators/BindableTypeProviders/BindableTypeProvidersGenerationTask.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/BindingTests/Controls/Binding_ElementName_In_Template_ItemsControl.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/BindingTests/Controls/Binding_ElementName_In_Template_ItemsControl.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/BindingTests/Controls/Binding_ElementName_In_Template_Resource.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/BindingTests/Controls/Binding_ElementName_In_Template_Resource.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/BindingTests/Controls/Binding_ElementName_In_Template_Resource_In_Dictionary.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/BindingTests/Controls/Binding_ElementName_In_Template_Resource_In_Dictionary.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/BindingTests/Given_Binding.cs
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/4505
- Bugfix
`ElementName` bindings created in non-toplevel ResourceDictionary are applied properly.
> fix: ElementName binding in non-toplevel ResourceDictionary

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TextBlockTests/TextBlockTests.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/SimpleText_MaxLines_Two_With_Wrap.xaml
- src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.wasm.cs
Fixes #4910 
The size reported by the `<TextBlock />` during `Arrange()` phase were incorrect when `MaxLines` were specified. The correct size should always be the available width for a `<TextBlock />`, because the default `HorizontalAlignement` for any control (that includes `<TextBlock />`) is `Stretch`. And this mode (`Stretch`) will cause the layout to behave like `Center` when the control is not filling its parent's size.
The fix was to return the available width during the `Arrange()` phase when the `HorizontalAlignment` is set to `Stretch`.
> [WASM] Fixed a problem with TextBlock alignment when used with MaxLines

- src/SamplesApp/SamplesApp.UITests/Microsoft_UI_Xaml_Controls/TabViewTests/Given_TabView_Uno.cs
- src/SamplesApp/SamplesApp.UITests/RuntimeTests.cs
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/TabViewTests/TabViewItemsSourceTests.xaml
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/TabViewTests/TabViewItemsSourceTests.xaml.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/TabView/TabViewTests.Uno.cs
- src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/TabView/TabViewTests.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/TabView/TabView.cs
GitHub Issue (If applicable): fixes #4895, fixes #4899, fixes #4875, fixes #4907
- Bugfix
Content is not rendered.
Content is rendered.
> fix: TabView does not render item content with bindings

- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/Given_XamlReader.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/When_StateTrigger_PropertyPath.xamltest
- src/Uno.UI/UI/Xaml/TargetPropertyPath.cs
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/4917
- Bugfix
No exception when a `TargetPropertyPath.Target` gets assigned multiple times.
> fix: TargetPropertyPath is not releasing its WeakReference properly

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TextBlockTests/TextBlockTests.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/TextBlock_MeasureCache.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/TextBlock_MeasureCache.xaml.cs
- src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlockMeasureCache.MeasureKey.cs
Fixes https://github.com/unoplatform/uno/issues/4945
> [Wasm] Padding were not part of the key used for the measurement caching

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Shapes/Shapes_Tests.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/Shapes_Default_StrokeThickness.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/Shapes_Default_StrokeThickness.xaml.cs
- src/Uno.UI/UI/Xaml/Shapes/ArbitraryShapeBase.Android.cs
- src/Uno.UI/UI/Xaml/Shapes/ArbitraryShapeBase.wasm.cs
- src/Uno.UI/UI/Xaml/Shapes/Shape.Android.cs
- src/Uno.UI/UI/Xaml/Shapes/Shape.Skia.cs
- src/Uno.UI/UI/Xaml/Shapes/Shape.cs
- src/Uno.UI/UI/Xaml/Shapes/Shape.layout.cs
- src/Uno.UI/UI/Xaml/Shapes/Shape.wasm.cs
- src/Uno.UWP/UI/Composition/CompositionSpriteShape.Skia.cs
closes #4509 
closes #4688 
- Bugfix
Shapes are being drawn and measured with a StrokeThickness of 1 instead of 0 by default
New behaviour matches UWP, where explicitly setting `StrokeThickness=0` in XAML will not draw a Stroke. 
> fix(Shapes): Match UWP StrokeThickness behaviour

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_Control.cs
- src/Uno.UI/UI/Xaml/Controls/Control/Control.cs
GitHub Issues:
fixes https://github.com/unoplatform/uno/issues/4786
fixes https://github.com/unoplatform/uno/issues/4739
The selected item is not visible.
As the template of the `NavigationViewItemPresenter` is dynamically set by a `VisualState` of its parent `NavigationView`, it's  set while the presenter is already flagged as `IsLoading` driving the template to never be applied (i.e. `OnApplyTemplate`).
When the `Template` is set on a `Control` flagged as `IsLoading`, it's applied synchronously.
> fix: Selection state not visible in NavigationView

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ScrollViewerTests/UnoSamples_Tests.ScrolViewer.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ScrollViewerTests/ScrollViewer_Add_Remove.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ScrollViewerTests/ScrollViewer_Add_Remove.xaml.cs
- src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.wasm.cs
This was most obvious for ComboBox, which would appear blank the second time it was opened, if an item deep in the list was selected.
GitHub Issue (If applicable): fixes #4852
- Bugfix
> fix(scrollviewer): [WASM] Fix reloaded ScrollViewer has scroll reset

- src/Uno.UWP/ApplicationModel/Activation/ProtocolActivatedEventArgs.cs
- src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Activation/ProtocolActivatedEventArgs.cs
- Bugfix
Accessing the `SplashScreen` property on `ProtocolActivatedEventArgs` causes exception.
Accessing the `SplashScreen` property on `ProtocolActivatedEventArgs` returns `null` to match `LaunchActivatedEventArgs`.
> fix: Match ProtocolActivated property support with Launch

- build/Uno.UI.Build.csproj
This avoids the addition of `+x` that is not generated by nuget.exe in the filename.
> build: Use SemVer instead of FullSemVer

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media_Imaging/Given_BitmapSource.cs
- src/Uno.UI/UI/Xaml/Media/Imaging/BitmapImage.skia.cs
- src/Uno.UI/UI/Xaml/Media/Imaging/BitmapImage.wasm.cs
- src/Uno.UI/UI/Xaml/Media/Imaging/BitmapSource.cs
fixes https://github.com/unoplatform/uno/issues/4878
Make sure to always clone the source stream before completing the `BitmapSource.SetSource[Async]` method.
It might be clone asynchronously, especially when using the `SetSourceAsync` (clone was dispatch on next dispatcher loop).
🙃
>  fix(imagesource): Fix the SetSource[Async] must clone the provided stream before returning

- build/Uno.UI.Build.csproj
- gitversion.yml
Recent gitversion updates have changed the default branch mode to not be `mode: ContinuousDelivery` causing stable builds to be incorrectly versioned.
> ci: Adjust versioning for stable releases

- src/Uno.UI.Tests/BinderTests/Given_Binder.PocoBinding.cs
- src/Uno.UI/UI/Xaml/DependencyObjectStore.Binder.cs
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/5022
- Bugfix
This fix addresses native-registered lazy initialization issue causing SetBindingValue to fail dependending on whether SetBinding was not called previously.
This issue can impact native controls for (BindableSwitchCompat) which gets its `Text` property updated before any binding has been created, failing a call to SetBindingValue.
> fix: Native-registered DPs lazy initialization

- doc/articles/features/windows-ui-xaml-xbind.md
- src/SourceGenerators/Uno.UI.SourceGenerators.Tests/Given_XBindRewriter.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/Utils/XBindExpressionParser.cs
GitHub Issue (If applicable): fixes #4855
- Feature
Support for the x:Bind type casting feature:
```
FontSize="{x:Bind (x:Double)Combo3.SelectedValue, Mode=OneWay}"
```
> feat: Add support for x:Bind type cast syntax

- build/PackageDiffIgnore.xml
- src/Uno.Foundation/Rect.cs
- src/Uno.Foundation/Size.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_UIElement.cs
- src/Uno.UI/Controls/BindableUIView.iOS.cs
- src/Uno.UI/Extensions/UIElementExtensions.cs
- src/Uno.UI/Extensions/UIViewExtensions.iOSmacOS.cs
- src/Uno.UI/Extensions/ViewExtensions.Android.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/NavigationView/NavigationView.cs
- src/Uno.UI/UI/Xaml/FrameworkElement.EffectiveViewport.cs
- src/Uno.UI/UI/Xaml/UIElement.cs
fixes https://github.com/unoplatform/uno/issues/4798
1. [iOS] Children collection is out of sync while raising `child.Loaded` 
2. [iOS] `NavigationView` does not render footer elements
1. The `ChildrenShadow` collection is updated only after the child has been added, so we cannot walk the visual tree up and down.
2. The `NativationView` is using the `ActualHeight` of the `ItemsRepeater`s before they have been arranged
1. We manually pre-update the `ChildrenShadow` collection right before effective modification (we still re-clone it after).
2. The `NativationView` is using the `DesireSize` to apply constraints
> Fix NavigationView not appearing properly on iOS

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TextBlockTests/TextBlockTests.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/TextBlock_LayoutAlignment.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/TextBlock_LayoutAlignment.xaml.cs
- src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.Android.cs
Affected issues:
* fixes https://github.com/unoplatform/nventive-private/issues/149
* fixes https://github.com/unoplatform/nventive-private/issues/151
* fixes https://github.com/unoplatform/nventive-private/issues/150
* fixes https://github.com/unoplatform/nventive-private/issues/154
* fixes https://github.com/unoplatform/nventive-private/issues/155
* fixes https://github.com/unoplatform/nventive-private/issues/159
Text on Android were wrongly layouted when the content were set after the loading of the `<TextBlock>` (usually by using a binding), the layout alignment is `Stretch` (which is the default) and text-alignment were not to left.
- ~~[ ] Docs have been added/updated which fit [documentation …
> [Android] Fix text layout problem

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/TabView/TabView.cs
- src/Uno.UI/UI/Xaml/Controls/ItemsControl/ItemsControl.cs
GitHub Issue (If applicable): fixes #4978, fixes #4721
- Bugfix
The `ContainerFromIndex` and `IndexFromContainer` methods return wrong results
- The methods support the case when item is its own container
- The methods return correct results when the items collection is currently modified
> fix: ContainerFromIndex and IndexFromContainer return wrong results

- src/Uno.UI/UI/Xaml/ApplicationActivity.Android.cs
- src/Uno.UI/UI/Xaml/NativeApplication.cs
GitHub Issue (If applicable): fixes #5076
- Bugfix
For `SingleTask` activity, the protocol activation fails.
In case the application activity is in SingleTask mode, OnNewIntent is called to set the intent. This occurs after Activity OnStarted, so we need to check whether the intent should be handled (by OnActivated for example)
> fix: Ensure protocol activation is handled

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Flyout.cs
- src/Uno.UI.Tests/DependencyProperty/Given_DependencyProperty.DataContext.cs
- src/Uno.UI/UI/Xaml/DependencyObjectStore.Binder.cs
closes #4922
- Bugfix
Binding to Flyout from within the Flyout itself causes the wrong DataContext to be set on the Flyout
Example: 
- Button A contains a Flyout with Button B inside of it
- Button B has a binding to the Flyout itself
- We should not propagate Button B's DataContext to the Flyout since its real parent is actually Button A 
Binding value is not propagated to child unless you are the actual Parent of that child
> fix(Bindings): Avoid propagating DataContext if you are not the child's parent

- src/Uno.UI/UI/Xaml/Media/Animation/Animators/RenderingLoopAnimator.wasm.cs
- src/Uno.UI/UI/Xaml/Media/Animation/Animators/RenderingLoopAnimatorMetadataIdProvider.cs
closes #3736
closes #5038
- Bugfix
`Error #1 "TypeError: Cannot read property 'DisableFrameReporting' of undefined`
Sometimes animations on WASM are not stopped properly
We used to get some annoying messages in the log, now we have to put a breakpoint in the onFrame
No error. Animations fully stop on the JS side
> fix(Animations): Fix issue with multiple animators holding the same handle to their JS counterparts

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/CommandBarTests/UnoSamples_Tests.NativeCommandBar.cs
- src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.cs
- src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.xaml
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/UIElementTests/UIElement_Transform_And_Clipping.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/UIElementTests/UIElement_Transform_And_Clipping.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ViewBoxTests/ViewBox_Alignment.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ViewBoxTests/ViewBox_Dynamic.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ViewBoxTests/Viewbox_Behavior.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ViewBoxTests/Viewbox_Behavior.xaml.cs
- src/Uno.Foundation/Rect.cs
- src/Uno.UI.RuntimeTests/IntegrationTests/common/TestServices.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs
- src/Uno.UI/Extensions/UIViewExtensions.iOSmacOS.cs
- src/Uno.UI/UI/Xaml/Controls/ViewBox/Viewbox.cs
- src/Uno.UI/UI/Xaml/FrameworkElement.iOS.cs
Fixes https://github.com/unoplatform/uno/issues/4918
Fixes https://github.com/unoplatform/uno/issues/4976
On iOS, the wrong coordinates were used to provide the `availableSize` for the _arrange_ phase. The correct iOS value to use is `.Bounds`, but `.Frame` were used.
`<ViewBox>` were the most affected control because it was often triggering a clipping with wrong measurements on the content control.
Another related fix is to disable clipping on controls when transforms are used.
> [iOS] Fixed a clipping bug with RenderTransform, mostly affecting <ViewBox>

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ScrollViewerTests/UnoSamples_Tests.ScrolViewer.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ScrollViewerTests/ScrollViewer_Margin.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ScrollViewerTests/ScrollViewer_Margin.xaml.cs
- src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/NativeScrollContentPresenter.iOSmacOS.cs
Fixes https://github.com/unoplatform/private/issues/177
Any `Margin` directly on the child element of a `<ScrollViewer />` on macOS were used to measure the element, but were ignored during the arrange phase, leading to a forced Top/Left alignment without the applied margin.
**STILL DRAFT: UI TESTS STILL MISSING**
> [MacOS] Margin directly on the child element of a <ScrollViewer /> were ignored

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/PopupTests/UnoSamples_Popup_HVAlign_Tests.cs
- src/Uno.Foundation/Point.Android.cs
- src/Uno.UI/UI/Xaml/Controls/Popup/PopupPanel.cs
GitHub Issue (If applicable): #4761
- Bugfix
Popup doesnt open at the right location in android. It is offset'd by the height of status bar.
Should behave like UWP now.
> fix(popup): placement issue for android

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/Manipulation_Tests.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Input/GestureRecognizerTests/ManipulationEvents.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Input/GestureRecognizerTests/ManipulationEvents.xaml.cs
- src/Uno.UWP/UI/Input/GestureRecognizer.Manipulation.cs
GitHub Issue (If applicable): #4700
- Bugfix
`ManipulationDelta` event on macos has its `e.Delta.Translation.Y` inverted, as compared to other platforms.
> fix(macos): ManipulationDelta translateY being inverted

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement_And_Leak.cs
- src/Uno.UI/UI/Xaml/Media/Animation/Animators/CPUBoundAnimator.cs
- src/Uno.UI/UI/Xaml/Media/Animation/Animators/DiscreteFloatValueAnimator.cs
- src/Uno.UI/UI/Xaml/Media/Animation/Animators/DisplayLinkValueAnimator.iOSmacOS.cs
- src/Uno.UI/UI/Xaml/Media/Animation/Animators/GPUFloatValueAnimator.iOSmacOS.cs
- src/Uno.UI/UI/Xaml/Media/Animation/Animators/IValueAnimator.cs
- src/Uno.UI/UI/Xaml/Media/Animation/Animators/ImmediateAnimator.cs
- src/Uno.UI/UI/Xaml/Media/Animation/Animators/NativeValueAnimatorAdapter.Android.cs
- src/Uno.UI/UI/Xaml/Media/Animation/Animators/NotSupportedAnimator.cs
- src/Uno.UI/UI/Xaml/Media/Animation/ITimeline.cs
- src/Uno.UI/UI/Xaml/Media/Animation/Storyboard.cs
- src/Uno.UI/UI/Xaml/Media/Animation/Timeline.animation.cs
- src/Uno.UI/UI/Xaml/Media/Animation/Timeline.cs
GitHub Issue (If applicable): fix #4953 
- Bugfix
iOS GPU failed animations are now releasing resources properly.
> fix(memory): [iOS] Propagate GPU animation failures up to Storyboard to fix memory leak

- src/Uno.UWP/ApplicationModel/Package.Other.cs
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/4840
- Bugfix
The `Package.InstalledLocation` may fail when using Single-File packaging.
The Package class does not rely on assembly location to determine the intallation path.
> fix(linux): Package base path resolution for single-file .NET 5 packaging

- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/Path_Custom.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/Path_Custom.xaml.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_UIElement.wasm.cs
- src/Uno.UI/UI/Xaml/UIElement.wasm.cs
GitHub Issue (If applicable): Fixes #3654, closes https://github.com/unoplatform/uno/pull/5100
- Bugfix
Fixes the `HtmlElementAttribute` inheritance for non-uno.ui types.
> Fixes the HtmlElementAttribute inheritance for non-uno.ui types

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_UIElement.cs
- src/Uno.UI/UI/Xaml/Controls/Layouter/Layouter.cs
- src/Uno.UI/UI/Xaml/UIElement.Layout.netstd.cs
- src/Uno.UI/UI/Xaml/UIElement.cs
- src/Uno.UI/UI/Xaml/Window.Android.cs
- src/Uno.UI/UI/Xaml/Window.Desktop.cs
- src/Uno.UI/UI/Xaml/Window.Skia.cs
- src/Uno.UI/UI/Xaml/Window.cs
- src/Uno.UI/UI/Xaml/Window.iOS.cs
- src/Uno.UI/UI/Xaml/Window.macOS.cs
- src/Uno.UI/UI/Xaml/Window.wasm.cs
fixes https://github.com/unoplatform/uno/issues/5069
`NavigationView` is crashing if `SelectedItem` is set before first layouting pass.
When an item is realized by the `ItemsRepeater` the navigation forces a `UpdateLayout` which causes the `ItemsRepeater` to re-measure itself ... which throws an exception.
We are now considering the "native" layouting passes in the `UpdateLayout` and ignore the requests if layouting is already in progress.
> fix(navigationview): Prevent crash when selecting item too early

- src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.skia.cs
> fix(Border): [Skia] Ensure only the outer border shape is inserted as the first child

- src/Uno.CrossTargetting.props
- src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/PagerControl/PagerControlTests.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Repeater/Given_ItemsRepeater.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/ViewportManagerWithPlatformFeatures.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBaseSource.iOS.cs
fixes https://github.com/unoplatform/uno/issues/4742
fixes https://github.com/unoplatform/uno/issues/4935
fixes https://github.com/unoplatform/uno/issues/5030
* `ItemsRepeater` does not render its items properly
* First tab of `TabView` is not rendered properly on iOS
* If there is no `ScrollViewer` in the parent visual tree of an `ItemsRepeater` then it "viewport" will remain to 0,0,0,0 usually leading the repeater to render only it first item. This issues has already been reported on the WinUI repo (https://github.com/microsoft/microsoft-ui-xaml/issues/2349), and the commit only workarounds it.
* If the root element of the `ItemTemplate` of the `TabView` is the "container" (i.e. `TabViewItem`)  then on iOS, the `ContentTemplate` of this container is replaced by that `ItemTemplate` (the …
> fix: Misc issues with items repeater

- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.macOS.cs
closes #5152
- Bugfix
Unable to Copy/Paste/Select All/Redo/Undo/Cut using keyboard
Able to Copy/Paste/Select All/Redo/Undo/Cut using keyboard
> feat(TextBox): Add keyboard command capability to macOS TextBox

- src/Uno.UI/UI/Xaml/UIElement.cs
- src/Uno.UI/UI/Xaml/UIElement.macOS.cs
closes #123
closes #119
- Bugfix
- Feature
TransformToVisual on macOS does not take CollectionView or ScrollViews into account when calculating the offset
TransformToVisual on macOS **does** take CollectionView or ScrollViews into account when calculating the offset
> feat(TransformToVisual): Add TransformToVisual logic for macOS

- build/PackageDiffIgnore.xml
- src/Uno.UI.Tests/Windows_UI_XAML_Controls/ListViewBaseTests/Given_ListViewBase.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Media_Animation/Given_BounceEase.cs
- src/Uno.UI/UI/Xaml/Media/Animation/BounceEase.cs
fixes https://github.com/unoplatform/uno/issues/5141
Animations are invalid when using `BounceEase` on netstandard platforms
The algorithm used for the bounce effect was producing out of range values.
🙃
> fix: Fix bounce ease producing invalid final value

- src/Uno.UI/Controls/BindableNSView.macOS.cs
closes https://github.com/unoplatform/Uno.Gallery/issues/120
- Bugfix
Rectangle is clipped during rotation:
No clipping by default
> fix(BindableNSView): Set MasksToBounds to false on init

- src/Uno.UI/UI/Xaml/IFrameworkElementImplementation.macOS.tt
closes https://github.com/unoplatform/Uno.Gallery/issues/129
closes https://github.com/unoplatform/Uno.Gallery/issues/130
- Bugfix
Bindings are not propagated properly when using a ScrollViewer since the FrameworkElement Implementation of `ViewDidMoveToWindow` tries to set the 
Bindings are properly propagated 
> fix(FrameworkElement): [macOS] Ensure we set parent to a DependencyObject

- src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props
- src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml
- Bugfix
Avoids the use of common namespace name for winui3 exclusion. (Breaks X.F canary)
> fix(reg): Avoid common namespace name conflict

- src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.skia.cs
GitHub Issue (If applicable): fixes part of #5186
- Bugfix
Fallback on `AcrylicBrush` is not working on Skia.
Fallback now properly uses the fallback color with opacity.
> fix: Properly fallback on Skia AcrylicBrush

- src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/ViewportManagerWithPlatformFeatures.cs
- src/Uno.UI/UI/Xaml/Controls/Border/Border.cs
- src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.cs
- src/Uno.UI/UI/Xaml/Controls/Grid/Grid.Layout.cs
- src/Uno.UI/UI/Xaml/Controls/Panel/Panel.cs
fixes https://github.com/unoplatform/uno/issues/5172
#5109 
`NavigationView` is slow on Uno.Gallery
Slightly more performant
> fix: Perf of NavView/ItemsRepeater

- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/Input_Multiline.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/Input_Multiline.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/PasswordBox_Simple.xaml
- src/Uno.UI/UI/Xaml/Controls/PasswordBox/SecureTextBoxView.macOS.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.macOS.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.macOS.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxViewDelegate.macOS.cs
Fixes https://github.com/unoplatform/Uno.Gallery/issues/148
As described in issue https://github.com/unoplatform/Uno.Gallery/issues/148, the text was behaving as _single line_ when not focused.
This is fixed + AcceptReturns is not working on MacOS.
> [MacOS] Multiline TextBox were displayed as single line when not focused.

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TextBoxTests/TextBoxTests.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/Input_Multiline_AutoHeight.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/Input_Multiline_AutoHeight.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/PasswordBox_Simple.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_Wrapping.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_Wrapping.xaml.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.wasm.cs
- src/Uno.UI/UI/Xaml/Documents/UIElementTextHelper.wasm.cs
- src/Uno.UI/ts/WindowManager.ts
Fixes https://github.com/unoplatform/uno/issues/5142
The measurement of `<TextBox>` on wasm were not correct when wrapping were used.
This was caused by the forced `white-space: pre;` CSS style when measuring the content.
Measurement is now very close to what UWP/WinUI is doing.
> [Wasm] Incorrect TextBox measurement when Wrap mode were used

- src/SolutionTemplate/UnoSolutionTemplate/UWP/UnoQuickStart.Uwp.csproj
fixes https://github.com/unoplatform/Uno.Material/issues/427
- Bugfix
Uno.Material needs UWP 10.0.18362.0 or higher to work properly.
> fix: Bump UWP min version to 10.0.18362.0

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TimePicker.cs
- src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePickerFlyout.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePickerSelector.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePicker.cs
- src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerFlyout.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerSelector.iOS.cs
fixes https://github.com/unoplatform/nventive-private/issues/173
- Bugfix
iOS devices with OS versions lower than iOS14 crashing when opening the Picker Flyout Selector
> fix(iOS): Time and DatePicker Flyout Selector

- doc/articles/get-started-vs.md
This is just an extremely small update to fix the incorrect Discord link that I assume nobody has noticed yet. The original link had 4 `w's` making the link "https://wwww.platform....." instead of only 3, which is the global standard abbreviation for a World Wide Web link. Love the Uno Platform, please keep up the amazing work everyone, and hopefully now more people can join the Discord to discuss this project and platform more as well as give and receive more support instantly!
Thanks for your time,
-Nathan Tuttle
P.S. Please also read the "More Information" section in this Pull Request, as it might be an even better solution that works just the same, but additionally adds an extra feature to joining the Discord server that makes the process much easier for users who have Discord …
> Fix for Incorrect Discord Redirector Link

- src/Uno.UI.Runtime.Skia.Gtk/GTK/GtkCoreWindowExtension.cs
- src/Uno.UI.Runtime.Skia.Tizen/Tizen/TizenCoreWindowExtension.cs
Reduce log level about the fact that capture is not supported on GTK and Skia
Polluating log on each button click
Muted by default
> fix: Disable anoying log for pointer capture not supported on GTK and Tizen

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Pivot.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/TestsResources.xaml
- src/Uno.UI/UI/Xaml/Controls/Pivot/Pivot.cs
closes #5144 
- Bugfix
Content of different PivotITems are being squashed together when using BIndings
Content is  rendered correctly
> fix(wasm): Pivot content when using bindings

- src/SourceGenerators/System.Xaml.Tests/Test/System.Xaml/XamlSchemaContextTest.cs
- src/SourceGenerators/System.Xaml/System.Xaml/XamlSchemaContext.cs
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/5284
- Bugfix
The `XamlSchemaContext` does not leak when created without an assemblies list.
> fix(xamlreader): XamlSchemaContext leaks when hooking on AppDomain.AssemblyLoad

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/CommandBarTests/UnoSamples_Tests.NativeCommandBar.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/CustomContent/CommandBar_Frame.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/CustomContent/CommandBar_Frame.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/CustomContent/CommandBar_Page1.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/CustomContent/CommandBar_Page1.xaml.cs
- src/Uno.UI/Controls/CommandBarNavigationItemRenderer.iOS.cs
- Bugfix
iOS CommandBar when using custom Content this is not displayed
- [] Validated PR `Screenshots Compare Test Run` results.
> fix(iOS): CommandBar TitleView Content Display

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/CommandBarTests/UnoSamples_Tests.NativeCommandBar.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/LongTitle/CommandBar_Frame.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/LongTitle/CommandBar_Frame.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/LongTitle/CommandBar_Page1.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/LongTitle/CommandBar_Page1.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/LongTitle/CommandBar_Page2.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/LongTitle/CommandBar_Page2.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/LongTitle/CommandBar_Page3.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/LongTitle/CommandBar_Page3.xaml.cs
- src/Uno.UI/Controls/CommandBarNavigationItemRenderer.iOS.cs
fixes https://github.com/unoplatform/nventive-private/issues/179
- Bugfix
iOS CommandBar.Title when it's too long it's overlapping any AppBarButton on the page.
> fix(iOS): CommandBar.Title overlapping AppBarButtons

- src/Uno.UI/UI/Xaml/Documents/Hyperlink.wasm.cs
https://github.com/unoplatform/Uno.Gallery/issues/177
- Bugfix
Hyperlink text color is unreadable in dark mode for WASM
Hyperlink text color is readable in dark mode for WASM
> fix(Hyperlink): Use dark/light mode friendly color for WASM Hyperlink foreground

- src/SamplesApp/SamplesApp.UITests/Constants.cs
- src/SamplesApp/SamplesApp.UITests/SamplesApp.UITests.csproj
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/WebViewTests/UnoSamples_Test_NavigateToString.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/WebView/WebView_AnchorNavigation.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/WebView/WebView_AnchorNavigation.xaml.cs
- src/Uno.UI/UI/Xaml/Controls/WebView/UnoWKWebView.iOSmacOS.cs
GitHub Issue (If applicable): Fixes https://github.com/unoplatform/nventive-private/issues/187
- Bugfix
`WebView.NavigationStarting` and `WebView.NavigationCompleted` **are not** raised when clicking on anchors in a WebView.
`WebView.NavigationStarting` and `WebView.NavigationCompleted` **are** raised when clicking on anchors in a WebView.
> fix(WebView): Raise NavigationStarting and NavigationCompleted when doing anchor navigation on iOS.

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Media/ImageBrushTests/ImageBrush_Shape_Fill_StretchAndAlignment.cs
- src/Uno.UI/UI/Xaml/Media/Brush.Android.cs
- src/Uno.UI/UI/Xaml/Media/Brush.iOSmacOS.cs
- src/Uno.UI/UI/Xaml/Shapes/Shape.cs
closes #5271
- Bugfix
Having an ImageBrush as the Fill for a Shape would not re-draw if Stretch/AlignmentX/AlignmentY were changed
Having an ImageBrush as the Fill for a Shape will re-draw if Stretch/AlignmentX/AlignmentY were changed
> fix(ImageBrush): [iOS/Android] subscribe to ImageBrush property changes

- src/SamplesApp/SamplesApp.UITests/Constants.cs
- src/SamplesApp/SamplesApp.UITests/Microsoft_UI_Xaml_Controls/NavigationViewTests/NavigationView_Tests.cs
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/NavigationViewTests/FluentStyle/Item1Page.xaml
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/NavigationViewTests/FluentStyle/Item1Page.xaml.cs
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/NavigationViewTests/FluentStyle/Item2Page.xaml
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/NavigationViewTests/FluentStyle/Item2Page.xaml.cs
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/NavigationViewTests/FluentStyle/Item3Page.xaml
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/NavigationViewTests/FluentStyle/Item3Page.xaml.cs
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/NavigationViewTests/FluentStyle/NavigationViewSample.xaml
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/NavigationViewTests/FluentStyle/NavigationViewSample.xaml.cs
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/NavigationViewTests/FluentStyle/SettingsPage.xaml
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/NavigationViewTests/FluentStyle/SettingsPage.xaml.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/Uno.UI.FluentTheme/Resources/PriorityDefault/SplitView_themeresources.xaml
- src/Uno.UI.FluentTheme/themeresources.xaml
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/5265
- Bugfix
The MUX `NavigationView` now displays properly when fluent styles are imported.
> fix(fluent): Exclude SplitView fluent style to fallback on UWP's version

- src/Uno.UI.Tests/DependencyProperty/Given_DependencyProperty.DataContext.cs
- src/Uno.UI/UI/Xaml/DependencyObjectStore.Binder.cs
GitHub Issue (If applicable): fixes https://github.com/unoplatform/nventive-private/issues/183
- Bugfix
A dependency property propagating the DataContext will not enumerate using `GetEnumerator` if the value is an `IList`.
> fix(DepdendencyObject): Don't use IEnmerable when propagating the DataContext

- src/SamplesApp/SamplesApp.Shared/App.xaml.cs
- src/Uno.UI/Controls/NativeCommandBarPresenter.iOS.cs
- src/Uno.UI/FeatureConfiguration.cs
closes https://github.com/unoplatform/nventive-private/issues/186
- Bugfix
Fixes an edge case found when doing Multi Frame navigation and using NativePresenter and the CommandBar.Titles of two pages get overlapped.
Could not find a way to UI/Runtime test this. 
> fix(iOS): NativePresenter CommandBar.Title overlapped

- src/SamplesApp/SamplesApp.UITests/RuntimeTests.cs
- src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.iOSmacOS.cs
- src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.skia.cs
closes https://github.com/unoplatform/nventive-private/issues/176
- Bugfix
> fix(BorderLayerRenderer): [iOS/Skia] Adjust corner radius when drawing inner path of border to account of stroke thickness offset

- src/SolutionTemplate/UnoSolutionTemplate.VISX/UnoPlatformPackage.cs
- src/Uno.UI.RemoteControl.VS/EntryPoint.cs
- Bugfix
- When  Remote Control service has invalid ctor print message `The loaded solution contains an Uno.UI Remote Control service.`
- When VS closing is throwing System.Runtime.InteropServices.COMException HRESULT: 0x80004005 (E_FAIL)
- When the solution contains unloaded project is trowing System.NotImplementedException HRESULT: 0x80004001 (E_NOTIMPL) and UpdateProjectsAsync is stopped
- When  Remote Control service has invalid ctor print message `Unable to load {unoNuGetPackage.Id} Remote Control service ({unoNuGetPackage.VersionString}) (The constructor is invalid).`
- When VS closing is not throwing System.Runtime.InteropServices.COMException HRESULT: 0x80004005 (E_FAIL)
- When the solution contains …
> Fixes vsix issue

- src/Uno.UI/UI/Xaml/Controls/Popup/Popup.macOS.cs
- Bugfix
On macOS under certain circumstances the `PopupPanel.SuperView` is null and it's making the app crash when trying to access that property.
Saw this behavior while opening a `DateTimePicker`.
> fix(macOS): Null pointer opening popup

- build/Uno.WinUI.nuspec
- build/ci/.azure-devops-unit-tests.yml
- src/Directory.Build.targets
- src/SamplesApp/Benchmarks.Shared/Benchmarks.Shared.projitems
- src/SamplesApp/Benchmarks.Shared/Suite/Windows_UI_Xaml/ResourceDictionaryBench/XamlControlsResourcesReadBenchmark.cs
- src/SamplesApp/SamplesApp.Droid/SamplesApp.Droid.csproj
- src/SamplesApp/SamplesApp.Shared/App.xaml.cs
- src/SamplesApp/SamplesApp.Skia/SamplesApp.Skia.csproj
- src/SamplesApp/SamplesApp.Wasm/SamplesApp.Wasm.csproj
- src/SamplesApp/SamplesApp.iOS/SamplesApp.iOS.csproj
- src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props
- src/SourceGenerators/Uno.UI.SourceGenerators/Helpers/DependenciesInitializer.cs
- src/Uno.UI.BindingHelper.Android/Uno.UI.BindingHelper.Android.csproj
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/DatePickerIntegrationTests.cs
- src/Uno.UI/UI/Xaml/Application.cs
- src/Uno.UI/UI/Xaml/Controls/Pivot/PivotAdapter.Android.cs
- src/Uno.UI/UI/Xaml/Data/ResourceBinding.cs
- src/Uno.UI/UI/Xaml/ResourceDictionary.cs
- src/Uno.UI/UI/Xaml/ResourceResolver.cs
- src/Uno.UI/UI/Xaml/SpecializedResourceDictionary.cs
- src/Uno.UI/Uno.UI.Skia.csproj
- src/Uno.UI/Uno.UI.Wasm.csproj
- src/Uno.UI/Uno.UI.csproj
- Improves the `ResourceDictionary` lookup performance by:
- Caching key hash code, using pre-computed cache keys whenever possible during XAML materialization
- Custom implementation of Dictionary based on .NET 6 `Dictionary<,>` to remove unused parts
- Use of `(string, bool)` to discriminate types in the inner dictionary
- Use of in parameters to avoid unnecessary copies
- Depending on the platforms, the worst-case read improvements range from 30% to 300%.
- Restores Samples App logging for non-wasm targets
- Bumps AndroidX dependency versions to fix invalid VTable errors on recent VS builds
> perf: Improve ResourceDictionary performance

- src/Uno.UI/Uno.UI.csproj
- Bugfix
Referencing Uno.WinUI.DualScreen fails with :
```
error : An item with the same key has already been added.
```
> fix: DualScreen, Maps invalid Uno.WinUI dependency

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TextBoxTests/TextBoxTests.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_UIElement.wasm.cs
- src/Uno.UI/UI/Xaml/UIElement.wasm.cs
Avoid flicker in SV when an hidden element is taller than viewport on WASM
If a child of a `ScrollViewer` is taller than the managed viewport and is `Visibility=Collapsed` (`hidden` in DOM), the native computed viewport will include it.
We moved those elements out of the bounds of the `ScrollViewer`
> fix: [WASM] Avoid flicker in SV when an hidden element is taller than viewport

- build/Uno.WinUI.nuspec
- src/Directory.Build.targets
- Bugfix
An app build may fail with the following error:
```
MMP : error MM2002: Failed to resolve "Uno.Disposables.RefCountDisposable" reference from "Uno.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" [/Users/runner/work/1/s/XamlControlsGallery.macOS/XamlControlsGallery.macOS.csproj]
```
Uno.Core dependencies are now aligned.
> fix: Adjust nuspec dependencies for Uno.Core

- src/Uno.UI/Microsoft/UI/Xaml/Controls/NavigationView/NavigationViewItem.Uno.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/NavigationView/NavigationViewItem.cs
Use deferred over and pressed for `NavigationViewItem` only for Android where the lag is really noticeable and where the `ScrollViewer` does not capture the pointer.
Pressed and over state are deferred for all platforms.
🙃
> fix: Defer NavViewItem pressed and over states only for Android

- build/Uno.WinUI.nuspec
- src/Directory.Build.targets
- Bugfix
The original changes introduces an incorrect set of dependencies, letting the head decide which version to get is more stable.
related to https://github.com/unoplatform/Uno.WindowsCommunityToolkit/issues/132
> fix(reg): Restore original AndroidX dependencies

- build/Uno.WinUI.nuspec
- src/SamplesApp/SamplesApp.Wasm/SamplesApp.Wasm.csproj
- src/Uno.UI/UI/Xaml/SpecializedResourceDictionary.cs
- src/Uno.UI/Uno.UI.Skia.csproj
- src/Uno.UI/Uno.UI.Wasm.csproj
- src/Uno.UI/Uno.UI.csproj
- Bugfix
Avoid adding a dependency on `System.Runtime.CompilerServices.Unsafe` by using a simple copy of `Unsafe.NullPtr` that is compatible with current Xamarin targets.
This will avoid errors like this one:
```
System.MissingMethodException: Method not found: bool System.Runtime.CompilerServices.Unsafe.IsNullRef<!0>(!!0&)
```
> fix(reg): Use internal copy of Unsafe.IsNullRef for Xamarin targets

- src/Uno.UI/UI/Xaml/Controls/Primitives/LoopingSelector/LoopingSelector_Partial.cs
By clicking/tapping on an element in a LoopingSelector (in the DatePicker), sometimes the selection were _jumping_ few items and produce a selection for another item, usually the double distance from the previous selection.
The bug was caused by the way Uno is producing events on ScrollIViewer, which are not totally like WinUI/UWP.
> fix(loopingselector): Fix a glitch in LoopingSelector related to way ScrollViewer events are raised.

- src/Uno.UI/Controls/NativeFramePresenter.iOS.cs
fixes https://github.com/unoplatform/nventive-private/issues/137
- Bugfix
Native Frame navigation on iOS gets wrong when clearing the Frame Stack
> fix(iOS): NavigationController resetting ViewController stack

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/PlatformHelper.cs
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/5468
- Bugfix
Uno Source generators are skipped when running on uap targets, as those are not needed.
> fix: VS 16.9 uap build should not run roslyn source generators

- src/Uno.UI/Controls/NativeFramePresenter.iOS.cs
…ould log errors when displayed.
- Bugfix
Displaying a pre-populated `Frame` using `NativeFramePresenter` on iOS results in errors being logged.
Displaying a pre-populated `Frame` using `NativeFramePresenter` on iOS works without logging any error.
I discovered this bug by displaying a `Frame` inside a modal `UIViewController`.
> fix(NativeFramePresenter.iOS): Fix a bug where pre-populated frames would log errors when displayed

- build/android-uitest-wait-systemui.sh
Adds a max start time for the android simulator.
> ci: Add max startup time for android simulator

- doc/articles/features/web-authentication-broker.md
- doc/articles/guides/open-id-connect.md
- src/SamplesApp/SamplesApp.Droid/WebAuthBrokerActivity.cs
- src/SamplesApp/UITests.Shared/Windows_Security_Authentication_Web/AuthenticationBroker_Demo.xaml.cs
- src/Uno.UI/UI/Xaml/ApplicationActivity.Android.cs
- src/Uno.UWP/Security/Authentication/Web/WebAuthenticationBrokerActivityBase.Android.cs
- src/Uno.UWP/Security/Authentication/Web/WebAuthenticationBrokerProvider.Android.cs
- src/Uno.UWP/Security/Authentication/Web/WebAuthenticationBrokerProvider.Skia.cs
- src/Uno.UWP/Security/Authentication/Web/WebAuthenticationBrokerProvider.cs
- src/Uno.UWP/Security/Authentication/Web/WebAuthenticationBrokerProvider.iOSmacOS.cs
- src/Uno.UWP/Security/Authentication/Web/WebAuthenticationBrokerProvider.net.cs
- src/Uno.UWP/Security/Authentication/Web/WebAuthenticationBrokerProvider.netstdref.cs
- src/Uno.UWP/Security/Authentication/Web/WebAuthenticationBrokerProvider.wasm.cs
This PR is adding support for WebAuthenticationBroker on Android. It's using the system browser with a callback using a custom scheme. In the documentation there's instructions to replace it by the _Chrome Custom Tabs_ instead, but since it's requiring dependencies on AndroidX, it was decided to not put that dependency in Uno.
- ~[ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)~
> WebAuthenticationBroker: Added support for Android.

- doc/.howto-template.md
- Bugfix
fix broken discord link in howto-template.md
> docs: fixed broken link

- src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.cs
- src/Uno.UI/UI/Xaml/Shapes/Shape.cs
Wrap the callbacks from TextBlock.Foreground and Shape.Fill Brush changes in try/catch. 
This fixes a bug on Android where system light/dark theme changes were only partially completing because they were interrupted by ObjectDisposedExceptions from calling InvalidateMeasure() on a disposed view.
GitHub Issue (If applicable): fixes https://github.com/unoplatform/Uno.Themes/issues/508
- Bugfix
> fix: Handle errors from Brush callbacks for disposed views

- src/SamplesApp/SamplesApp.Skia.Gtk/SamplesApp.Skia.Gtk.csproj
- src/SamplesApp/SamplesApp.Skia.WPF/SamplesApp.Skia.WPF.csproj
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ImageTests/UnoSamples_Tests.Image.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/ImageSourceWriteableBitmapInvalidate.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/WriteableBitmap_MultiInvalidate.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/WriteableBitmap_MultiInvalidate.xaml.cs
- src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.skia.cs
GitHub Issue (If applicable): related to #4309, #4713
- Bugfix
The `BorderLayoutRenderer` accumulates visual layers when the control changes and has no border set. This means that changes are not visible, as they are hidden below previously rendered layers.
Fixed, added UI tests.
> fix: WriteableBitmap.Invalidate on Skia

- src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props
- src/SourceGenerators/Uno.UI.SourceGenerators/Telemetry/TelemetryClient.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.Telemetry.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/5628
- Bugfix
VS may freeze under unknown conditions when generating design-time source.
VS does not freeze anymore.
> fix: Adjust incorrect generation behavior during roslyn design-time build

- src/Uno.UWP/ApplicationModel/Contacts/Contact.cs
GitHub Issue (If applicable): #5658
- Bugfix
Contact.FullName returns concatenated FirstName, LastName etc. even when DisplayNameOverride is set.
DisplayNameOverride overrides both DisplayName and FullName (as in UWP).
I don't know if it is breaking change or not.
While updating #2544 (rebase, after part of it, #5577, was merged), I encounter a problem - reading contact from Android returns DisplayName. But now it is read-only. It leads to some checking, and discovery of bug in current Uno implementation.
This code:
```
Dim oCon = New Windows.ApplicationModel.Contacts.Contact
oCon.HonorificNamePrefix = "dr"
oCon.HonorificNameSuffix = "honSuf"
oCon.FirstName = "Piotr"
oCon.MiddleName = …
```
> fix: Contact FullName fix

- doc/articles/composition.md
- src/Uno.UI/FeatureConfiguration.cs
- src/Uno.UI/UI/Xaml/ApplicationActivity.Android.cs
- src/Uno.UWP/UI/Composition/Uno/CompositionConfiguration.cs
- src/Uno.UWP/UI/Composition/Uno/CompositorThread.android.cs
- src/Uno.UWP/UI/Composition/Uno/ICompositionRoot.android.cs
Epic: https://github.com/unoplatform/uno/issues/5586
Add compositor thread on Android
Composition is done on UI thread
🙃
> feat(animations): Add compositor thread on Android

- src/Uno.UI/UI/Xaml/Controls/Flyout/FlyoutBase.cs
- src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerFlyout.cs
- Bugfix
On Android the flyout of the TimePicker does not open
Make sure Android flyout opens
> fix(TimePicker): Make sure Android flyout opens

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/SourceGenerators/XamlGenerationTests/XBindNullable.xaml
- src/SourceGenerators/XamlGenerationTests/XBindNullable.xaml.cs
GitHub Issue (If applicable): fixes #5084
- Bugfix
Nullable reference type caused `typeof(XYZ?)` which is not valid.
Generating valid `typeof`
> fix: x:Bind typeof expression for nullable reference

- src/SamplesApp/SamplesApp.UITests/TestFramework/ImageAssert.ExpectedPixels.cs
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TextBlockTests/TextBlockTests.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/SimpleText_MaxLines_One.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/TextBlock_TextTrimming.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/TextBlock_TextTrimming.xaml.cs
- src/Uno.UI/WasmCSS/Uno.UI.css
Fixes https://github.com/unoplatform/uno/issues/5662
Setting `TextTrimming="CharacterEllipsis"` on a `<TextBlock />` on wasm were not producing the asked ellipsis on overflowed text, because the CSS `overflow: hidden` were required for it to work.
> Fix TextTrimming="CharacterEllipsis" were not working on Wasm

- src/Uno.UI.RuntimeTests/Tests/Windows_System_Threading/Given_ThreadPoolTimer.cs
- src/Uno.UWP/System.Threading/ThreadPoolTimer.cs
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/5741
- Bugfix
`ThreadPoolTimer.CreatePeriodicTimer` is not raising events properly
> fix: TheadPoolTimer.CreatePeriodicTimer raises events properly

- src/Uno.UWP/Storage/Pickers/FileSavePicker.wasm.cs
GitHub Issue (If applicable): fixes #5685
- Bugfix
Some file type extensions, added by `FileTypeChoices.Add` are missing.
Code: 
```
picker.FileTypeChoices.Add("C/C++ source files", new List<string>() { ".cpp", ".c", ".cc", ".cxx", ".c++", ".cp" });
```
Result:
Only shows `.cp` extension, and also some other irrelevant `.com`, `.exe`, and `.bin`.
Shows all included extensions, as well as the irrelevant extensions `.com`, `.exe`, and `.bin`.
> fix(FileSavePicker.wasm): FileSavePicker dialog now shows all file type extensions.

- src/SourceGenerators/Uno.UI.Tasks/BatchMergeXaml/MergedDictionary.cs
- src/Uno.UI/Extensions/UIElementExtensions.cs
- src/Uno.UI/WasmCSS/Uno.UI.css
GitHub Issue (If applicable): #5707 
The scrollbars are missing on wasm and skia as soon as fluent style is used.
The resource disctionnary merge task does not includes the `win:` XML namespace (as the same URL has already be defined by another xmlns - the default in that case), but keeps the `win:` prefix where defined. 
Then the XAML generator, when reading the merged dictionary is not able to fine the namespace for node defined with the `win:`, so it tries to generate the content (even explicitly instructed to ignore the "win" prefix).
So the specific exclusion of the `ScrollBar` template of fluent styles (https://github.com/unoplatform/uno/commit/726923a0a788277c7cd039a8893c8ae35f1a2bb4) is not respected and the fluent template is used instead of the default UWP one ... causing the …
> Fix scrollbars not appearing on wasm and skia

- build/Uno.UI.Build.csproj
- build/Uno.WinUI.nuspec
- src/Uno.UI.Toolkit/CommandBarExtensions.cs
- src/Uno.UI.Toolkit/ElevatedView.cs
- src/Uno.UI.Toolkit/MapResources.cs
- src/Uno.UI.Toolkit/MenuFlyoutExtensions.cs
- src/Uno.UI.Toolkit/MenuFlyoutItemExtensions.cs
- src/Uno.UI.Toolkit/SplitViewExtensions.cs
- src/Uno.UI.Toolkit/UIElementExtensions.cs
- src/Uno.UI.Toolkit/Uno.UI.Toolkit.csproj
- Feature
Enable support for `net5.0-windows` for `Uno.UI.Toolkit` classes.
> feat: Add Uno.WinUI compatibility for net5-windows

- src/Uno.UI.RuntimeTests/Tests/Windows_Storage/Given_StorageFile_Native.base.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_Storage/Streams/Given_RandomAccessStreamReference.cs
- src/Uno.UWP/Generated/3.0.0.0/Windows.Storage.Pickers/FileOpenPicker.cs
- src/Uno.UWP/Generated/3.0.0.0/Windows.Storage.Pickers/FileSavePicker.cs
- src/Uno.UWP/Generated/3.0.0.0/Windows.Storage.Pickers/FolderPicker.cs
- src/Uno.UWP/Storage/Streams/Internal/NativeReadStream.wasm.cs
- src/Uno.UWP/Storage/Streams/StreamOverInputStream.cs
GitHub Issue (If applicable): fixes #5751, fixes #5766
- Bugfix
- Some read-only streams in Storage APIs throw on Flush.
- Analyzers report file pickers as not implemented even though they are
- Some of the read-only streams in Storage APIs no longer throw on Flush calls to match UWP behavior.
- Adjust `NotImplemented` attributes on file pickers
> Read-only streams should not throw on Flush, adjust NotImplemented on Pickers

- src/Uno.UI/WasmScripts/Uno.UI.js
- src/Uno.UI/ts/Windows/Storage/Streams/NativeFileReadStream.ts
GitHub Issue (If applicable): fixes #5749
- Bugfix
In case the underlying stream has reached end, JS `streamReader.releaseLock()` causes `Promise.reject()` which is observed in the developer console and there is no way to prevent this. This is a weird behavior which is discussed here - https://bugs.chromium.org/p/chromium/issues/detail?id=465666.
`releaseLock` is no longer called if we finished reading the whole stream (in such case the release is not needed anyway).
> fix: Do not close JS stream reader if closed

- src/Uno.UI.Runtime.Skia.Gtk/GtkCoreWindowExtension.cs
GitHub Issue (If applicable): fixes #5764
- Bugfix
Clicking buttons takes multiple tries.
One try!
> fix(Pointers): Ignore GTK ungrab mode for window leave notification

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml/UIElementTests/UIElementTests.cs
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml/UIElementTests/WasmTests.cs
- src/SamplesApp/UITests.Shared/Wasm/Wasm_CustomEvent.xaml
- src/SamplesApp/UITests.Shared/Wasm/Wasm_CustomEvent.xaml.cs
- src/Uno.UI.Runtime.WebAssembly/Xaml/UIElementWasmExtensions.cs
Fixes https://github.com/unoplatform/uno/issues/5721
When registering multiple handlers for the same custom html event (Wasm platform), the second handler were never getting called because of a hard-coded exception.
> [Wasm] Removed hard-coded exception in handler for Html Custom Event

- src/Uno.UI/WasmCSS/Uno.UI.css
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/5754
Sometimes a Scrollbar could appear on the TextBlock, on Wasm:
(visible on the Calculator)
> fix(textblock): [WASM]Removed a useless scrollbar appearing sometimes on TextBlock

- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/FocusManager/Focus_FocusVisual.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/FocusManager/Focus_FocusVisual.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/FocusManager/Focus_FocusVisual_Properties.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/FocusManager/Focus_FocusVisual_Properties.xaml.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement_FocusVisuals.cs
- src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.Skia.csproj
- src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml/FrameworkElement.cs
- src/Uno.UI/UI/Xaml/Controls/FocusVisual/SystemFocusVisual.cs
- src/Uno.UI/UI/Xaml/Controls/FocusVisual/SystemFocusVisual.xaml
- src/Uno.UI/UI/Xaml/DependencyObjectStore.Binder.cs
- src/Uno.UI/UI/Xaml/FrameworkElement.cs
- src/Uno.UI/UI/Xaml/Input/FocusManager.cs
- src/Uno.UI/UI/Xaml/ResourceResolver.cs
- src/Uno.UI/UI/Xaml/Setter.cs
- src/Uno.UI/UI/Xaml/Window.Android.cs
- src/Uno.UI/UI/Xaml/Window.Skia.cs
- src/Uno.UI/UI/Xaml/Window.cs
- src/Uno.UI/UI/Xaml/Window.iOS.cs
- src/Uno.UI/UI/Xaml/Window.wasm.cs
GitHub Issue (If applicable): #3093 
- Feature
Keyboard/Gamepad focus is not recognizable
Initial support for Focus visuals.
> Initial Focus Visuals support

- doc/articles/splash-screen.md
GitHub Issue (If applicable): resolved: #5507
- minor changes to splash screen docs and updated it according to the new how-to template
related sample is in another PR: unoplatform/Uno.Samples#58
> docs: updated doc on splash screen

- doc/articles/features/uno-material-controls-extra-setup.md
- doc/articles/features/uno-material.md
- doc/articles/guides/uno-material-walkthrough.md
- doc/articles/toc.yml
GitHub Issue (If applicable): closing #5334
- expanded the existing overview doc for Uno.Material , and
- added related how-to guide
Related sample code is in another PR: unoplatform/Uno.Samples#52
> docs: added uno.material docs

- src/Uno.UI/UI/Xaml/Controls/SwipeControl/SwipeControl.Uno.cs
Accept null args in `OnManipulationCompleted` + move check in the `try/catch`
Crashes the app in release
Does not crash
We need to refactor the `SwipeControl` to remove `async void` (https://github.com/unoplatform/uno/issues/5813).
> fix(reg): Fix possible null ref in SwipeControl

- src/Uno.UI.Runtime.Skia.Gtk/GtkCoreWindowExtension.cs
- src/Uno.UI.Runtime.Skia.Gtk/GtkHost.cs
- src/Uno.UI.Runtime.Skia.Gtk/UI/Xaml/Controls/TextBoxViewExtension.cs
For GTK applications using Wayland the title bar is rendered by the
window itself and not by the composer. And it seems to me that GTK
counts the title bar as part of the window and uses it to trigger the
window events, leading to erroneous considerations about the size and
location of pointers in the area where it is used to draw the
components.
The fix adds a GtkEventBox in the window, instead of use the window
events we will be based on the events of the GtkEventBox which we can
assure that the GTK will take into account the title bar.
Related-to: #5706
Signed-off-by: Matheus Castello <matheus@castello.eng.br>
> fix(GTK): pointer events in wrong locations using Wayland

- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_In_ContentDialog.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_In_ContentDialog.xaml.cs
- src/Uno.UI.Runtime.Skia.Gtk/UI/Xaml/Controls/TextBoxViewExtension.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.Skia.cs
GitHub Issue (If applicable): fixes #5817
- Bugfix
- Stack overflow exception occurs when multiline TextBox is edited in Skia, because GTK triggers an additional TextChanged event with empty string and causes infinite loop
- When TextBox is unfocused and the entry was not visible, it should not be removed
Fixed.
> fix: Avoid StackOverflow for multiline TextBox, fail on remove

- src/Uno.UI.Toolkit/Themes/Generic.xaml
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/5809
- Bugfix
ElevatedView Is tab stop
ElevatedView Is not tab stop
> fix: ElevatedView should not be tab stop

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/Uno.UI.Tests/Global.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_xLoad_Setter.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_xLoad_Setter.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_xLoad_Setter_Order.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_xLoad_Setter_Order.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_xLoad_StaticResources.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_xLoad_StaticResources.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Given_xBind_Binding.cs
- src/Uno.UI/UI/Xaml/ElementStub.cs
- src/Uno.UI/UI/Xaml/Markup/ComponentHolder.cs
- src/Uno.UI/UI/Xaml/Setter.cs
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/5801, fixes https://github.com/unoplatform/uno/issues/5801, fixes https://github.com/unoplatform/uno/issues/5248, fixes https://github.com/unoplatform/uno/issues/5392.
- Bugfix
- Ensure re-evaluation of StaticResource markup
- Ensure `Setter` is being refreshed on ElementNameSubject … …
- Don't set bindings on x:Load on the actual element
> fix(xLoad): Ensure re-evaluation of StaticResource markup

- src/Uno.UI/UI/Xaml/Controls/Primitives/LoopingSelector/LoopingSelector_Partial.cs
This PR is a workaround for the following bug: https://github.com/unoplatform/uno/issues/5845
This will fix https://github.com/unoplatform/uno/issues/5471
When selecting a date using the datePicker, sometimes the internally selected date were properly updated.
This was happening when clicking **DIRECTLY** on the choosen date. Doesn't occurs when the picker is scrolled to the desired position.
Fixed
- ~~[ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes …
> fix(datepicker): Fix datePicker .Date is not correctly updated.

- src/Uno.UI.RuntimeTests/Tests/Windows_Globalization/Given_ApplicationLanguages.cs
- src/Uno.UWP/Globalization/ApplicationLanguages.cs
This PR will fix https://github.com/unoplatform/uno/issues/5657
Setting a _Script Subtag_ on `ApplicationLanguages.PrimaryLanguage` were producing a `CultureNotFoundException` when the runtime is mono.
The bug were also happening when the application's manifest were set to `zh-Hans-CN` on iOS.
When the culture is not found in the runtime, another try is done after removing the _Script Subtag_.
> fix(applicationlanguages): Added support for _Script Subtag_ for ApplicationLanguages.PrimaryLanguageOverride

- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/DatePicker/DatePicker_DatePartVisibility.xaml
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/DatePickerIntegrationTests.cs
- src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePicker.cs
- src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePickerFlyoutPresenter_Partial.cs
- src/Uno.UI/UI/Xaml/Controls/DatePicker/NativeDatePickerFlyout.Android.cs
- src/Uno.UI/UI/Xaml/Controls/DatePicker/NativeDatePickerFlyout.iOS.cs
This was due to a wrong refactoring during the conversion of DatePicker from WinUI code.
Fix https://github.com/unoplatform/uno/issues/5510
Default date for `DatePicker` were not properly set.
Set to today by default, as Windows is doing.
> fix(datepicker): Default date were not set when the control were created.

- src/Uno.UI.Runtime.Skia.Wpf/Extensions/UI/Xaml/Controls/TextBoxViewExtension.cs
- Bugfix
Setting `IsReadOnly` to `true` on `TextBox` on Skia/WPF doesn't have the desired effect.
`IsReadOnly` should work.
> fix:TextBox.IsReadOnly on Skia/Wpf

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ContentDialog.cs
- src/Uno.UI/UI/Xaml/Controls/ContentDialog/ContentDialog.cs
GitHub Issue (If applicable): fixes #5702
- Bugfix
```C#
private async void Dialog_Closing(object sender, ContentDialogClosingEventArgs args)
{
var deferral = args.GetDeferral();
await Task.Delay(5000);
System.Diagnostics.Debug.WriteLine("Done handling event.");
deferral.Complete();
}
private async void Button_Tapped(object sender, TappedRoutedEventArgs args)
{
var dialog = new SampleContentDialog();
dialog.Closing += Dialog_Closing;
await dialog.ShowAsync();
System.Diagnostics.Debug.WriteLine("Dialog returned.");
}
private async void Button1_Tapped(object sender, TappedRoutedEventArgs args)
{
var dialog = new SampleContentDialog();
await dialog.ShowAsync();
System.Diagnostics.Debug.WriteLine("Dialog returned.");
}
```
`Button_Tapped` output:
> …
> fix: ContentDialog bugfixes

- src/Uno.UI/UI/Xaml/Controls/Grid/ColumnDefinitionCollection.cs
- src/Uno.UI/UI/Xaml/Controls/Grid/DefinitionCollectionBase.cs
- src/Uno.UI/UI/Xaml/Controls/Grid/Grid.cs
- src/Uno.UI/UI/Xaml/Controls/Grid/RowDefinitionCollection.cs
- src/Uno.UI/UI/Xaml/DependencyObjectCollection.cs
The recent refactoring of `<Grid />` were causing problem because both `ColumnDefinitionCollection` and `RowDefinitionCollection` were implementing twice the `IEnumerable<T>` interface, causing a resolution problem for the compilator in application code.
> Grid: Fixed Definitioncollectionbase breaking change

- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/SwipeControlTests/SwipeControlPage.xaml.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ScrollViewer.cs
Ensure a non-scrollable scroller does not matrialize its scrollbars.
Works
Still works
> Ensure a non-scrollable scroller does not matrialize its scrollbars.

- src/Uno.UWP/ApplicationModel/Activation/ActivationKind.cs
- Feature
Not all values of ActivationKind is defined, especially CommandLineLaunch is missing. And I'm using it in my code inside OnActivated() to differentiate between activation from Toast (#2585) and CommandLine.
All values are defined.
> feat: missing ActivationKind values

- src/Uno.UI.RuntimeTests/Tests/Windows_Storage/Given_FileIO.cs
- src/Uno.UWP/Storage/Streams/Internal/NativeWriteStreamAdapter.wasm.cs
GitHub Issue (If applicable): fixes #5911
- Bugfix
The write `Position` did not update properly, so for writes beyond the default buffer size of 128 KB the stream just kept overwriting from the start.
File writing now properly updates the position.
> fix: Large file write in WASM 

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/Subclass.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/Uno.UI.Tests/Uno.UI.Tests.csproj
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_DefaultBindMode_DataTemplate.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_DefaultBindMode_DataTemplate.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Given_xBind_Binding.cs
GitHub Issue (If applicable): fixes #5857
- Bugfix
`x:DefaultBindMode` is now flowing properly to `DataTemplate` contents
- [c] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
> Propagate x:DefaultBindMode to DataTemplate definitions

- src/Uno.UI/UI/Xaml/UIElement.PointerCapture.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.Managed.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.cs
- src/Uno.UI/UI/Xaml/UIElement.RoutedEvents.cs
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/5882
When an element is nested in a `ScrollViewer` on skia, it's not able to receive the `PointerReleased` events.
The `GestureRecognizer` of the `ScrolViewer` is tracking pointer to detect if a manipulation can be detected (for touch scrolling), to acheive that it requires an "implicit capture".
But once a pointer is captured, the Skia's dispatch algorithm send the event to the element which did the capture, no matter it was an explicit or an implicit capture.
So only the `ScrollViewer` and its parents were receiving event like move and release as soon as the pointer was pressed.
In case of an implicit capture only, we first dispatch event to the "original source" as if it was not captured, then we send it on …
> [Skia][macOS] Fix some pointers event not being dispatched properly

- src/Uno.UI/UI/Xaml/Media/Brush.cs
Improve `Brush.Opacity` and `RelativeTransform` DPs read performance
> perf: Generate `Brush.Opacity` and `RelativeTransform` DPs

- src/Uno.UI/UI/Xaml/Controls/Grid/Grid.cs
Removed a potential `NullReferenceException` while calling `.Arrange()` on `<Grid>` before calling first `.Measure()` on it.
> fix(grid): Removed the possibility of a NullRefException when .Arrange() is called before calling .Measure() first.

- src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.wasm.cs
- src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.cs
GitHub Issue: fixes #5943 
Vertical native scrollbar could appears if the extent is smaller or as tall as the viewport on a chromium based browser.
When the `scrollable` size is 0, we let the "native scrollbars" in "Auto" which can cause the chromium based browsers to show them due to an invalid measure (they are considering items that are clipped - and has `Opacity=0` -  in the computation of the the extent)
If `scrollable` is 0 we are explicitly requesting to the browser to hide the native scrollbars.
> fix(scrollviewer): [WASM] Vertical native scrollbar could appears

- src/Uno.UI/FeatureConfiguration.cs
- src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.cs
GitHub Issue: fixes #5844 
Add ability to configure scrollbar's auto-hide delay, and fully disbale auto-hide
We now have the ability to change the auto-hide delay in Uno's `FeatureConfiguration.ScrollViewer.DefaultAutoHideDelay`.
Setting it to `TimeSpan.MaxValue` will make sure to display the scrollbars at load, and to never hide them.
> Add ability to configure scrollbar's auto-hide delay, and fully disable auto-hide

- src/SamplesApp/SamplesApp.UITests/Microsoft_UI_Xaml_Controls/RadioButtonsTests/Given_RadioButtons.cs
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/RadioButtonsTests/RadioButtonsInitialLoadSelected.xaml
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/RadioButtonsTests/RadioButtonsInitialLoadSelected.xaml.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/Uno.UI/Microsoft/UI/Xaml/Controls/RadioButtons/RadioButtons.cs
closes https://github.com/unoplatform/uno/issues/5917
closes https://github.com/unoplatform/uno/issues/5886
- Bugfix
Is SelectedItem is set before the RadioButtons control is loaded, the SelectedItem/SelectedIndex properties are properly set but the ToggleButton itself is not checked
The actual ToggleButton within RadioButtons' ItemsRepeater is set to Checked when it is loaded and matches SelectedIndex
> fix(RadioButtons): Ensure RadioButton is selected on initial load

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/ListViewPages/ListViewBoundSelectionPage.xaml
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/ListViewPages/ListViewBoundSelectionPage.xaml.cs
- src/Uno.UI/UI/Xaml/DependencyObjectStore.Binder.cs
- src/Uno.UI/UI/Xaml/DependencyObjectStore.cs
When a Selector (eg ListView or ComboBox) is removed from the visual tree, if its DataContext is inherited and ItemsSource and SelectedItem are both bound, the UWP behavior is that the ItemsSource will be set to null, which will set SelectedItem to null, but the null selection won't be pushed through the two-way binding.
This change approximates the same behavior under Uno's binding system by detecting that scenario and not updating two-way bindings when an inherited DataContext is being cleared.
GitHub Issue (If applicable): partially addresses https://github.com/unoplatform/uno/issues/5852
- Bugfix
> fix(selector): Don't push null selection to binding when unloading Selector

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/WebViewTests/UnoSamples_Test_NavigateToString.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/WebView/WebView_AnchorNavigation.xaml.cs
None, WebView_NavigateToAnchor now use a stable uri.
> fix: Use stable uri for WebView_NavigateToAnchor

- src/Uno.UI.DualScreen/DuoApplicationViewSpanningRect.cs
- src/Uno.UWP/Devices/Sensors/Helpers/INativeDualScreenProvider.cs
- src/Uno.UWP/Generated/3.0.0.0/Windows.UI.ViewManagement/ApplicationView.cs
- src/Uno.UWP/UI/ViewManagement/ApplicationView.cs
- src/Uno.UWP/UI/ViewManagement/ViewModePreferences.cs
GitHub Issue (If applicable): closes #5965
- Feature
Calling the ViewMode-related methods of `ApplicationView` currently throws.
The APIs have now a basic implementation.
> feat(ApplicationView): IsViewModeSupported, TryEnterViewModeAsync

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/Manipulation_Tests.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Input/GestureRecognizerTests/ManipulationEvents.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Input/GestureRecognizerTests/Manipulation_WhenInScrollViewer.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Input/GestureRecognizerTests/Manipulation_WhenInScrollViewer.xaml.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.cs
GitHub Issue: #5929 
`ManipulationCompleted` might not be raised for each `ManipulationStarted`.
When a `ScrollViewer` kicks-in (and stole the pointer) the `PointerCancelled` event is not propagated to elements which are not under the pointer, preventing the `GestureRecognizer` to complete.
Pointer cancelled events are sent to `GestureRecognizer` in any cases.
> ManipulationCompleted might not be raised for each ManipulationStarted

- src/Uno.UI.Tests/Windows_UI_XAML_Controls/RadioButtonsTests/Controls/When_RadioButtons_TemplateBinding.xaml
- src/Uno.UI.Tests/Windows_UI_XAML_Controls/RadioButtonsTests/Controls/When_RadioButtons_TemplateBinding.xaml.cs
- src/Uno.UI.Tests/Windows_UI_XAML_Controls/RadioButtonsTests/Given_RadioButtons.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/ItemsRepeater.Properties.cs
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/5918
- Bugfix
The `ItemsRepeater.LayoutProperty` in now considered a Logical Child, which makes receive `DataContext` and `TemplatedParent` updates.
> fix: Make ItemsRepeater.LayoutProperty logical child

- src/SamplesApp/SamplesApp.UITests/SampleControlUITestBase.cs
- src/SamplesApp/SamplesApp.UITests/TestFramework/ActivePlatformsAttribute.cs
UI tests using `[TestCase]` were not properly following `[ActivePlatform]` attributes
Fixed this behavior.
> fix(test): Ensure `[ActivePlatform]` in UI Tests works with NUnit's `[TestCase]`

- src/SourceGenerators/Uno.UI.SourceGenerators/RemoteControl/RemoteControlGenerator.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/5953
- Bugfix
For some unknown conditions, the directory search list may be empty, and will generate invalid C#. This change works around the invalid code generation, but will not build a proper directory list for the remote control server to work properly.
> fix(remotecontrol): safe fallback when directories search list is empty

- src/SamplesApp/SamplesApp.iOS/SamplesApp.iOS.csproj
- Bugfix
The Samples App on iOS fails to build due to https://github.com/xamarin/xamarin-macios/issues/10884, even for debug mode.
Now builds properly.
> fix: Build fails Samples App on iOS

- src/Uno.UWP/ContextHelper.cs
- src/Uno.UWP/Graphics/Display/DisplayInformation.Android.cs
- src/Uno.UWP/Graphics/Display/DisplayInformation.cs
- src/Uno.UWP/Graphics/Display/DisplayInformation.iOS.cs
- src/Uno.UWP/Graphics/Display/DisplayInformation.macOS.cs
- src/Uno.UWP/Graphics/Display/DisplayInformation.skia.cs
- src/Uno.UWP/Graphics/Display/DisplayInformation.unsupported.cs
- src/Uno.UWP/Graphics/Display/DisplayInformation.wasm.cs
On Android, `DisplayInformation` relies on `ContextHelper.Current` which may not be available when called to early during the app's lifecycle. This change will make the exception more explicit.
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/6019
- Bugfix
Fail with a more explicit error message when using `DisplayInformation` too early in the app.
> fix(DisplayInformation): [Android] DisplayInformation cannot be used too early

- src/Uno.UI.Tests/DependencyProperty/Given_DependencyProperty.cs
- src/Uno.UI/DataBinding/WeakReferencePool.cs
- src/Uno.UI/UI/Xaml/DependencyObjectExtensions.cs
- src/Uno.UI/UI/Xaml/DependencyObjectStore.Binder.cs
- src/Uno.UI/UI/Xaml/DependencyObjectStore.cs
- src/Uno.UI/UI/Xaml/DependencyPropertyComparer.cs
- src/Uno.UI/UI/Xaml/DependencyPropertyDetails.cs
- src/Uno.UI/UI/Xaml/DependencyPropertyDetailsCollection.cs
- src/Uno.UI/UI/Xaml/ResourceResolver.cs
- src/Uno.UI/UI/Xaml/UIElement.Skia.cs
- src/Uno.UI/UI/Xaml/UIElement.cs
- src/Uno.UI/UI/Xaml/VisualState.cs
- fix: Possible NRE when applying visual state setters on unknown targets
- perf: Remove unused WeakReference read-back on creation
- refactor: Remove unused RegisterInheritedPropertyChangedCallback
- perf(VisualState): Create VisualState.Setters and StateTriggers backing collections lazily
- perf: Improve DependencyPropertyDetails performance
- Don't create a full stack when either `DefaultValue` or `Local`
- Don't materialize the default value until requested
- Make `CallbackManager` lazy
- Make `Bindings` list lazy
- Use flags for `WeakStorage` and `DefaultValue`
- Precompute IsUnsetValue in `SetValue`
- perf: misc performance improvements on DependencyObjectStore
- Don't materialize …
> Misc DependencyObject performance improvements

- src/Uno.UI.Tests/Global.cs
- src/Uno.UI/UI/Xaml/Controls/Grid/Grid.Definitions.cs
This change moves `Grid.RowDefinitions` and `ColumnDefinitions` to improve `Grid` control creation performance, particularly column and row-less intances.
> perf: Make `Grid.RowDefinitions` and `ColumnDefinitions` lazy initialized

- doc/articles/guides/uno-material-walkthrough.md
GitHub Issue (If applicable): #5334
added the missing step to "uno material: color palette override" section
> docs: add uno material color override missing step

- src/Uno.UI.Runtime.Skia.Gtk/GtkHost.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_UIElement.TransformToVisual.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls_Primitives/Given_Popup.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls_Primitives/PopupPages/ReachMainTreePage.xaml
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls_Primitives/PopupPages/ReachMainTreePage.xaml.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBaseSource.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/Popup/PopupPanel.cs
- src/Uno.UI/UI/Xaml/DependencyObjectExtensions.cs
- src/Uno.UI/UI/Xaml/FrameworkElement.EffectiveViewport.cs
- src/Uno.UI/UI/Xaml/FrameworkElement.cs
- src/Uno.UI/UI/Xaml/FrameworkElement.iOS.cs
- src/Uno.UI/UI/Xaml/FrameworkElement.net.cs
- src/Uno.UI/UI/Xaml/FrameworkElement.netstdref.cs
- src/Uno.UI/UI/Xaml/UIElement.Android.cs
- src/Uno.UI/UI/Xaml/UIElement.iOS.cs
- src/Uno.UI/UI/Xaml/UIElement.macOS.cs
- src/Uno.UI/UI/Xaml/UIElementExtensions.cs
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/5852
Set Popup as Parent of PopupPanel. This emulates UWP behavior that the Popup is a Parent of one of the parents of the Child content, which is relied upon in some cases (eg WCT DataGrid relies upon this for focus management).
- Bugfix
> fix(popup): Put Popup in Parent hierarchy of its Child content

- src/Uno.UI/UI/Xaml/WindowManagerInterop.wasm.cs
GitHub Issue (If applicable): # 
closes #5848 
- Bugfix
in WASM when using double.MaxValue in order to scroll to the end of the page the scroll does not happen.
> fix(WASM): SrollViewer.ChangeView to end of page

- src/Uno.UI/FeatureConfiguration.cs
- src/Uno.UI/UI/Xaml/DependencyObjectStore.cs
- src/Uno.UI/UI/Xaml/DependencyPropertyDetailsCollection.Bindings.cs
- src/Uno.UI/UI/Xaml/DependencyPropertyDetailsCollection.cs
Avoids resolving owner instance through weak references for `DependencyObjectStore` by enabling Load/Unload materialization of the reference.
This feature was disabled for Wasm on .NET 5 because of memory corruptions that have since been fixed.
> perf: [Wasm] Restore conditional DependencyObject hard references

- src/Uno.UI/UI/Xaml/FrameworkPropertyMetadata.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.Managed.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.wasm.cs
- src/Uno.UI/UI/Xaml/UIElement.netstd.cs
- src/Uno.UI/UI/Xaml/UIElement.netstdref.cs
- src/Uno.UI/WasmCSS/Uno.UI.css
Skip the processing of pointers if the control has not yet been initialized as it cannot have received pointers yet.
> perf: Skip ClearPointersStateIfNeeded during ctor

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Media/RevealBrushTests/RevealBrush_Tests.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/BrushesTests/RevealBrush_Fallback.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/BrushesTests/RevealBrush_Fallback.xaml.cs
- src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.Android.cs
- src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.iOSmacOS.cs
- src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.skia.cs
- src/Uno.UI/UI/Xaml/FrameworkElement.Interface.wasm.cs
- src/Uno.UI/UI/Xaml/Media/Brush.Android.cs
- src/Uno.UI/UI/Xaml/Media/Brush.Skia.cs
- src/Uno.UI/UI/Xaml/Media/Brush.iOSmacOS.cs
- src/Uno.UI/UI/Xaml/Media/Brush.wasm.cs
When a RevealBrush is set, use its FallbackColor for Panel.Background and Border.Background, since the actual reveal effect is not yet implemented.
This fixes TreeView selection background not being displayed (because, surprise, it's using RevealBrush).
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/6000
Also related:
https://github.com/unoplatform/uno/issues/5724
https://github.com/unoplatform/uno/issues/408
- Bugfix
> fix(revealbrush): Use RevealBrush FallbackColor for background

- src/Uno.UI.Runtime.Skia.Gtk/Uno.UI.Runtime.Skia.Gtk.csproj
- src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/Uno.UI.Runtime.Skia.Linux.FrameBuffer.csproj
GitHub Issue (If applicable): https://github.com/mono/SkiaSharp/pull/1704
- Bugfix
Removes unused and invalid dependency to `SkiaSharp.Views` for Gtk and Framebuffer support.
> fix(skiagtk): Remove unused incorrect dependency in `Uno.UI.Runtime.Skia.Gtk` and `FrameBuffer`

- build/PackageDiffIgnore.xml
- src/Uno.UI.FluentTheme/ControlsResourcesVersion.cs
- src/Uno.UI.FluentTheme/XamlControlsResources.cs
GitHub Issue (If applicable): closes #6059
- Feature
Not supported.
Supported (but has no effect yet).
> feat: Add ControlsResourcesVersion property for WinUI 2.6 compatability

- src/Uno.UI/DataBinding/BindingPropertyHelper.cs
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/6063, fixes https://github.com/unoplatform/uno/issues/6051
- Bugfix
The binding helper falls back on reflection based lookup if a property cannot be found in the generated bindings helper.
> BindingHelper may not provide properties when using WinUI

- src/SourceGenerators/Uno.UI.SourceGenerators/BindableTypeProviders/BindableTypeProvidersGenerationTask.cs
- Bugfix
Generation does not fail when used within C# delta application
> fix: Update BindableTypeProvidersSourceGenerator to be stateless per generation

- src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/SymbolIcon.cs
GitHub Issue (If applicable): fix https://github.com/unoplatform/uno/issues/5635
- Bugfix
Incorrect `NotImplemented` attribute platform list on `SymbolIcon`.
> fix: Incorrect SymbolIcon NotImplemented attribute platform list

- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Input/PointersTests/ScrollHandled.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Input/PointersTests/ScrollHandled.xaml.cs
- src/Uno.UI/WasmScripts/Uno.UI.js
- src/Uno.UI/ts/WindowManager.ts
GitHub Issue (If applicable): #6078
- Feature
Browser processes `Handled` events.
Using `preventDefault()` to prevent the browser from processing `Handled` events.
> feat: Use preventDefault for Handled events

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGenerator.cs
- Bugfix
No warning when building the UWP project.
> fix: Invalid warning when building with UWP and referencing the Uno.UI package

- src/SolutionTemplate/UnoSolutionTemplate/Droid/UnoQuickStart.Droid.csproj
- src/SolutionTemplate/UnoSolutionTemplate/Shared/UnoQuickStart.Shared.projitems
- src/SolutionTemplate/UnoSolutionTemplate/Shared/UnoQuickStart.Shared.shproj
- src/SolutionTemplate/UnoSolutionTemplate/Skia.WPF.Host/UnoQuickStart.Skia.Wpf.Host.csproj
- src/SolutionTemplate/UnoSolutionTemplate/Skia.WPF/UnoQuickStart.Skia.WPF.csproj
- src/SolutionTemplate/UnoSolutionTemplate/UWP/UnoQuickStart.Uwp.csproj
- src/SolutionTemplate/UnoSolutionTemplate/Wasm/UnoQuickStart.Wasm.csproj
- src/SolutionTemplate/UnoSolutionTemplate/iOS/UnoQuickStart.iOS.csproj
- src/SolutionTemplate/UnoSolutionTemplate/macOS/UnoQuickStart.macOS.csproj
@MartinZikmund 
According to @jeromelaban answer in Twitch from today
Xamarin.iOS template has wrong build action on `Entitelments.plist`
Some files in the template use spaces instead of tabs contrary to `.editorconfig`
Defined as in original Xamarin template https://github.com/xamarin/ios-samples/blob/56aa9e2ea1e5e6236b588e37223a78539f7c9477/FontList/FontList/FontList.csproj#L114-L115
```
<ItemGroup>
<None Include="Info.plist" />
<None Include="Entitlements.plist" />
</ItemGroup>
```
Tabified all spaces in csproj files
> Templates as xamarin fix

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/Uno.UI.Tests/Uno.UI.Tests.csproj
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_xNull.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_xNull.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Given_xBind_Binding.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/Given_XamlReader.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/When_Brush_And_StringColor.xamltest
- src/Uno.UI/UI/Xaml/Markup/Reader/XamlObjectBuilder.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/5377
- Bugfix
Add support `{x:Null}` syntax
> fix(xBind): Add support `{x:Null}` syntax

- src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.cs
- src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.xaml
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CalendarView/CalendarDatePicker_Basics.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CalendarView/CalendarDatePicker_Basics.xaml.cs
- src/Uno.UI.RuntimeTests/IntegrationTests/common/CalendarHelper.h.cs
- src/Uno.UI.RuntimeTests/IntegrationTests/common/CommonTestSetupHelper.cs
- src/Uno.UI.RuntimeTests/IntegrationTests/common/TestServices.InputHelper.cs
- src/Uno.UI.RuntimeTests/IntegrationTests/common/TestServices.KeyboardHelper.cs
- src/Uno.UI.RuntimeTests/IntegrationTests/common/TestServices.WindowHelper.cs
- src/Uno.UI.RuntimeTests/IntegrationTests/common/TestServices.cs
- src/Uno.UI.RuntimeTests/IntegrationTests/dxaml/BaseDxamlTestClass.cs
- src/Uno.UI.RuntimeTests/IntegrationTests/dxaml/controls/calendardatepicker/CalendarDatePickerIntegrationTests.cs
- src/Uno.UI.RuntimeTests/IntegrationTests/dxaml/controls/calendarview/CalendarViewAutomationPeerIntegrationTests.cs
- src/Uno.UI.RuntimeTests/IntegrationTests/dxaml/controls/calendarview/CalendarViewIntegrationTests.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Core/Given_CoreDispatcher.cs
- src/Uno.UI.Tests/Windows_Globalization/When_Calendar.cs
- src/Uno.UI/UI/Xaml/Controls/CalendarView/CalendarDatePicker.Properties.cs
- src/Uno.UWP/Globalization/Calendar.cs
The `<CalendarDatePicker />` were sometimes waiting for pointer events (mousemove, enter, exit...) before opening properly.
This was caused by an exception occurring during the opening of the flyout, delaying its opening to the next event handling.
> [Wasm] CalendarDatePicker not opening properly

- src/Uno.UWP/Networking/Connectivity/ConnectionProfile.Android.cs
GitHub Issue (If applicable): #5659
a) Setting IsWlanConnectionProfile / IsWwanConnectionProfile used API marked as obsolete.
b) GetConnectionCost() uses API available > 16, without checking Android version.
a) For newer Android (>22), setting these fields use other API.
b) For early Androids, returns NetworkCostType.Unknown (instead of exception).
> chore: ConnectionProfile de-obsoleting

- src/Uno.UI.FluentTheme/Resources/Priority02/TextBox_themeresources.xaml
GitHub Issue (If applicable): fixes #6070
- Bugfix
The clear/delete sign(X) is not displaying in dark mode for the Fluent TextBox Style and the resources/style are not up to date with the latest WinUI source code.
The clear/delete sign(X) is displaying in dark mode for the Fluent TextBox Style and the resources/style are up to date with the latest WinUI source code [Reunion 0.5].
> fix(TextBox): Update fluent textbox resources and style to match the latest WinUI source code [Reunion 0.5] and fix resources for dark theme

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/VisualStateManager_Lazy_Tests/Controls/When_VisualStateManager_Lazy.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/VisualStateManager_Lazy_Tests/Controls/When_VisualStateManager_xName.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/VisualStateManager_Lazy_Tests/Controls/When_VisualStateManager_xName.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/VisualStateManager_Lazy_Tests/VisualStateManager_Lazy.cs
GitHub Issue (If applicable): fixes https://github.com/unoplatform/nventive-private/issues/216, fixes https://github.com/unoplatform/nventive-private/issues/206
- Bugfix
VisualStates containing `x:Name` in nested members are now materialized eagerly, avoiding issues where visual states are referenced from the code behind, causing NREs.
> fix(reg): Don't make lazy visual states with descendants containing x:Name

- build/PackageDiffIgnore.xml
- src/Uno.UI/UI/Xaml/UIElement.EventRegistration.wasm.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.wasm.cs
- src/Uno.UI/WasmScripts/Uno.UI.d.ts
- src/Uno.UI/WasmScripts/Uno.UI.js
- src/Uno.UI/ts/HtmlEventDispatchResult.ts
- src/Uno.UI/ts/WindowManager.ts
Scrolling using mouse wheel does not works anymore while in popup
The `PopupPanel` is handling all pointer events to avoid interaction with content below, but now flagging a routed event as `Handled = true` is also doing `preventDefault` in native.
But the `preventDefault` not only impacts the element that request and its parent, but also its children (the "default behavior"is applied only once the event has bubbled up to the root element).
This means that when the `PopupPanel` is flagging the `PointerWheel` event as handled, it will also prevent native scrolling for its children.
Managed code can now customize if the native event should be flagged as `stopPropagation()` and/or `preventDefault()`, and pointers events never request a `preventDefault()`
The `UIElement.DispatchEvent` now …
> fix(reg): Fix mousewheel support in popup

- src/Uno.UI/UI/Xaml/Controls/CalendarView/CalendarViewBaseItemChrome.uno.cs
fixes https://github.com/unoplatform/uno/issues/6154
Clear the over state when control is hidden / unloaded
cf. linked bug
🙃
> fix(calendarpicker): Make sure to clear the over visual state when closing and re-opening the picker

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_StartScreen/Given_JumpListItem.cs
- src/Uno.UWP/UI/StartScreen/Extensions/ShortcutInfoExtensions.Android.cs
GitHub Issue (If applicable): fixes #1418
- Bugfix
`null` is not allowed
Allowed
> JumpListItem.Description should allow `null`

- src/Uno.UI.FluentTheme/Resources/PriorityDefault/CalendarView_themeresources.xaml
- src/Uno.UI.FluentTheme/themeresources.xaml
- src/Uno.UI/UI/Xaml/Controls/CalendarView/CalendarView_themeresources.xaml
- src/Uno.UI/UI/Xaml/Controls/CalendarView/Primitives/CalendarPanel.ModernCollectionBasePanel.cs
Avoid flicker when changing `DisplayMode` of `CalendarView` 
We briefly see the "year view" before transitioning from "month view" to "year view"
🙃
> fix(calendar): Avoid flicker when changing DisplayMode

- src/Uno.UWP/Globalization/ApplicationLanguages.cs
GitHub Issue (If applicable): fixes #6156 
- Bugfix
On Android, GetManifestLanguages raises a NullReferenceException, preventing the languages override to work properly
No exception raised
> fix(ApplicationLanguages): Prevent NullReferenceException for ManifestLanguages

- src/Uno.UI/UI/Xaml/Controls/CalendarView/CalendarLayoutStrategy_Partial.cs
- src/Uno.UI/UI/Xaml/Controls/CalendarView/CalendarViewGeneratorHost.cs
- src/Uno.UI/UI/Xaml/Controls/CalendarView/CalendarViewGeneratorMonthViewHost.cs
- src/Uno.UI/UI/Xaml/Controls/CalendarView/CalendarViewGeneratorYearViewHost.cs
- src/Uno.UI/UI/Xaml/Controls/CalendarView/CalendarView_Partial.cs
- src/Uno.UI/UI/Xaml/Controls/CalendarView/CalendarView_Partial_Selection.cs
- src/Uno.UI/UI/Xaml/Controls/DatePicker/DateTimePickerFlyoutHelper.cs
Some parts of the code `Calendar<View|DatePicker>` was wrongly translated from C++
* `IsGroupLabelVisible` is inverted
* `IsTodayHighlighted` is inverted when changed while `Calendar` is already loaded
* ...
🙃
> fix(calendar): Fix few C++ translation issues

- src/Uno.UI/UI/Xaml/Controls/CalendarView/CalendarView_Partial.cs
- src/Uno.UI/UI/Xaml/UIElement.MuxInternal.cs
Fixes https://github.com/unoplatform/uno/issues/6214
fixes https://github.com/unoplatform/uno/issues/6229
Sometimes the header of the `<CalendarView />` were not updated properly when the user what scrolling the content, on Android.
A patch has been done.  The issue https://github.com/unoplatform/uno/issues/6236 should fix the problem.
- ~~[ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)~~ -- …
> Fix(CalendarView): Fix header not updating while scrolling

- src/Uno.Foundation/Size.cs
- src/Uno.UI/UI/Xaml/Controls/CalendarView/Primitives/CalendarPanel.ModernCollectionBasePanel.cs
- src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/NativeScrollContentPresenter.Android.cs
- src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.Android.cs
https://github.com/unoplatform/uno/issues/6231
fixes https://github.com/unoplatform/uno/issues/6217
Initial scrolling on first navigation to year and decades views is invalid
- In the picker, the items was still at 1x1, so requested offset was invalid
- The `ScrollViewer` was not supporting to scroll before being being arranged with sufficient extent size
🙃
> fix(calendar): Fix year and decade view initial scrolling on Android

- src/Uno.UI/UI/Xaml/Controls/CalendarView/Primitives/CalendarPanel.ModernCollectionBasePanel.cs
fixes https://github.com/unoplatform/uno/issues/6228
Day items aren't correctly resized while changing the calendar Height or Width
If not stretch, we use hard coded size
We make sure to also validate if Width and/or Height are set
> fix(calendar): Fix setting Width and Height on Calendar does nothing

- src/Uno.UI.Tests/DependencyProperty/Given_DependencyProperty.DefaultValueProvider.cs
- src/Uno.UI/UI/Xaml/DependencyPropertyDetails.cs
- src/Uno.UI/UI/Xaml/DependencyPropertyDetailsCollection.cs
GitHub Issue (If applicable): fixes #6157
- Bugfix
Only a single default value provider can be registered.
Multiple can be registered.
> fix: Allow multiple default value providers

- src/Uno.UWP/Storage/Helpers/AssetsPathBuilder.wasm.cs
GitHub Issue (If applicable): Fixes https://github.com/unoplatform/uno/issues/6277
- Bugfix
Lottie assets path are containing doubled path separators, making IIS hosted resource location fail. 
This change avoids this double separator.
> fix(reg): Fix double path separator for lottie assets

- doc/articles/features/windows-storage-pickers.md
- src/SamplesApp/UITests.Shared/Windows_Storage/Pickers/FolderPickerTests.xaml.cs
- src/Uno.UI.Runtime.Skia.Gtk/Extensions/Storage/Pickers/FileOpenPickerExtension.cs
- src/Uno.UI.Runtime.Skia.Gtk/Extensions/Storage/Pickers/FolderPickerExtension.cs
- src/Uno.UI.Runtime.Skia.Gtk/GtkHost.cs
GitHub Issue (If applicable): #6127 
- Feature
Currently, developers wanting to limit their storage picker experience only to folder selection have limited options when targeting GTK.
Developers targeting Gtk can now utilize the WinRT FolderPicker API as they would with other supported targets.
Closing #6127 
N/A
> feat: Initial implementation of FolderPicker for Gtk

- src/Uno.UI/DataBinding/BindingPropertyHelper.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/6267
- Bugfix
This change reduces the number of false positives for debugging messages on bindable metadata provider types.
```
The Bindable attribute is missing and the type [XXXX] is not known by the MetadataProvider. Reflection was used instead of the binding engine and generated static metadata. Add the Bindable attribute to prevent this message and performance issues.
```
> fix(binding): Don't try metadata lookups on internal and struct types

- src/AddIns/Uno.UI.MSAL/Uno.UI.MSAL.Wasm.csproj
- src/SamplesApp/SamplesApp.Skia.WPF/SamplesApp.Skia.WPF.csproj
- src/Uno.Foundation/AssemblyInfo.cs
- src/Uno.UI.Runtime.Skia.Gtk/System/LauncherHelpers/DesktopFile.cs
- src/Uno.UI.Runtime.Skia.Gtk/System/LauncherHelpers/MimeAppsList.cs
- src/Uno.UI.Runtime.Skia.Wpf/Uno.UI.Runtime.Skia.Wpf.csproj
- src/Uno.UWP/AssemblyInfo.cs
GitHub Issue (If applicable): fixes #6249
- Bugfix
- Failures
- VS does not fail to restore packages for the full solution
- GTK compiles for netstandard 2.0
- Using `IsTrimmable` instead of `LinkerSafe` on iOS
> fix: VS restore, netstandard build of GTK, use IsTrimmable instead of LinkerSafe on iOS

- src/SamplesApp/SamplesApp.Shared/SamplesApp.Shared.projitems
- src/SamplesApp/SamplesApp.Shared/Strings/sr/Resources.resw
- src/Uno.UI.RuntimeTests/Tests/Windows_ApplicationModel_Resources/Given_ResourceLoader.cs
- src/Uno.UI.Tests/ResourceLoader/Strings/sr/Resources.resw
GitHub Issue (If applicable): fixes #6297 
- Bugfix
The test fails on WASM .NET 5 due to https://github.com/dotnet/runtime/pull/47301 - 
https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/src/libraries/System.Globalization/tests/CultureInfo/CultureInfoCtor.cs#L303
No longer fails.
> fix: Use sr instead of sr-Cyrl-BA

- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/.template.config/vs-2017.3.host.json
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-winui/.template.config/vs-2017.3.host.json
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unolib-crossruntime/.template.config/vs-2017.3.host.json
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/xamarinforms-wasm/.template.config/vs-2017.3.host.json
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/6288
- Bugfix
`dotnet new` templates are hiddent from VS as the creation process is significantly different from the CLI. Specifically, the IDE does not use the SLN file provided by the template and includes projects that may not be configured properly.
> fix: Hide `dotnet new` templates from VS 2019 new projects dialog

- src/Uno.UI.FluentTheme/AssemblyInfo.cs
- Bugfix
Warning treated as error on iOS.
No warning, no error.
> fix: Avoid LinkerSafe deprecated warning on iOS

- doc/articles/intro.md
- doc/templates/uno/styles/scss/main.scss
- Bugfix
Alert boxes change style on hover everywhere in the documentation
Hover style now has it's own class which is only used in the intro
before
after
> docs: changed alert hover to only display in intro

- src/Uno.UI/DirectUI/DXamlCore.cs
- src/Uno.UI/UI/Xaml/Internal/CoreServices.cs
GitHub Issue (If applicable): fixes #6409, fixes https://github.com/unoplatform/nventive-private/issues/229, fixes https://github.com/unoplatform/nventive-private/issues/228, fixes https://github.com/unoplatform/nventive-private/issues/225
- Bugfix
Apps fail to startup with linker enabled.
Previously DXamlCore and CoreServices used Lazy without explicit initializer parameter. While this worked for debug build, linker removed the "unused" parameterless constructors for these types and reflection then could not find and use them. Using the explicit initializer ensures the constructor is explicitly used and is not linked away.
> fix: Use explicit Lazy initializer

- doc/templates/uno/styles/docfx.js
- Bugfix
In-doc anchors do not set the target properly, making it appear under the menu
In-doc anchors display targets in the right spot
before 
after
> docs: fix for anchor target being displayed under the menu

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/SourceGenerators/XamlGenerationTests/GlobalStaticResources02.xaml
closes https://github.com/unoplatform/nventive-private/issues/227
- Bugfix
```xml
<Duration x:Key="MaterialTextBoxAnimationDuration">0:0:0.25</Duration>
```
Would result in the following generated code:
```csharp
["MaterialTextBoxAnimationDuration"] = 
new global::Windows.UI.Xaml.Duration
{
}
```
```xml
<Duration x:Key="MaterialTextBoxAnimationDuration">0:0:0.25</Duration>
```
Results in the following generated code:
```csharp
["MaterialTextBoxAnimationDuration"] = 
new Duration(global::System.TimeSpan.FromTicks(2500000 /* 0:0:0.25 */))
```
> fix(SourceGenerators): Use custom initializer for Duration

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/SplitViewTests/BindableDrawerLayoutTests.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/SplitView/BindableDrawerLayout_ChangePane.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/SplitView/BindableDrawerLayout_ChangePane.xaml.cs
- src/Uno.UI/Controls/BindableDrawerLayout.Android.cs
GitHub Issue (If applicable): _(private)_
- Bugfix
Attempting to set `SplitView.Pane` (with `LeftDrawerSplitViewStyle`) to null and then restoring it back cause the control to stop working.
The _leftPane was removed, but its parent was not cleared, 
causing the 2nd part of 1st condition to fail when adding it back.
resolved unoplatform/nventive-private#224
> fix(BindableDrawerLayout): unable to add removed pane back

- build/PackageDiffIgnore.xml
- doc/articles/features/windows-storage-pickers.md
- doc/articles/features/windows-storage.md
- src/Uno.UI/Resources/Strings/cs-CZ/Resources.resw
- src/Uno.UI/Resources/Strings/en/Resources.resw
- src/Uno.UWP/Generated/3.0.0.0/Windows.Storage.Provider/FileUpdateStatus.cs
- src/Uno.UWP/Generated/3.0.0.0/Windows.Storage/CachedFileManager.cs
- src/Uno.UWP/Storage/CachedFileManager.cs
- src/Uno.UWP/Storage/CachedFileManager.other.cs
- src/Uno.UWP/Storage/CachedFileManager.wasm.cs
- src/Uno.UWP/Storage/Internal/StorageProviders.cs
- src/Uno.UWP/Storage/Pickers/FileSavePicker.wasm.cs
- src/Uno.UWP/Storage/Provider/FileUpdateStatus.cs
- src/Uno.UWP/Storage/StorageFile.cs
- src/Uno.UWP/Storage/StorageFile.native.wasm.cs
- src/Uno.UWP/Storage/StorageFolder.native.wasm.cs
GitHub Issue (If applicable): closes #5920, closes #6075
- Feature
- `CachedFileManager` throws on non-WASM targets
- Docs on `FileSavePicker` are not clear
- `CachedFileManager` works everywhere (no-op on non-WASM targets)
- `CachedFileManager` on WASM transparently handles native file save picker vs. download picker
- Docs on `FileSavePicker` are improved
> CachedFileManager for all targets, improved docs for WASM pickers

- src/Uno.UI.Runtime.Skia.Gtk/GtkCoreWindowExtension.Keyboard.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/5000
- Feature
Enter key on number pads isn't mapped to VirtualKey.Enter
Map the key in hopes it fixes the issue.
I have no way to verify whether this fixes the reported issue or not.
> feat: Map Key.KP_Enter to VirtualKey.Enter

- src/SolutionTemplate/UnoSolutionTemplate.VISX/source.extension.vsixmanifest
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/6386
- Bugfix
Workaround version selection for vsix when VS2022 is installed
> fix: Adjust vsix installer when 2022 is installed

- build/PackageDiffIgnore.xml
- src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.cs
- src/Uno.Foundation/Rect.cs
- src/Uno.UI.RuntimeTests/IntegrationTests/common/TestServices.WindowHelper.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media/Given_Geometry.cs
- src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.csproj
- src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Media/Geometry.cs
- src/Uno.UI/Mock/ViewExtensions.netstdref.cs
- src/Uno.UI/UI/Xaml/Media/Geometry.cs
- src/Uno.UI/UI/Xaml/Media/GeometryGroup.cs
- src/Uno.UI/UI/Xaml/Media/RectangleGeometry.cs
Fixes https://github.com/unoplatform/uno/issues/6413
Implementation of `.Bounds` on 2 simple _geometries_: `RectangleGeometry` & `GeometryGroup`.
> Implemented `.Bounds` for Geometry

- src/Uno.UI/ts/WindowManager.ts
- Bugfix
This fixes an issue where the splashscreen image may not appear properly when the uno bootstrapper already rewrites the uri to include the package path.
> fix: Adjust for invalid splashscreen uri

- src/Uno.UI.Runtime.Skia.Wpf/Extensions/Networking/Connectivity/ConnectionProfileExtension.cs
- src/Uno.UI.Runtime.Skia.Wpf/Extensions/Networking/Connectivity/WindowsConnectionProfileExtension.cs
- src/Uno.UI.Runtime.Skia.Wpf/WpfHost.cs
- src/Uno.UWP/Networking/Connectivity/ConnectionProfile.skia.cs
- src/Uno.UWP/Networking/Connectivity/Internal/IConnectionProfileExtension.skia.cs
GitHub Issue (If applicable): #6435
- Feature
Retrieving the `NetworkConnectivityLevel` on any Skia target always returns `NetworkConnectivityLevel.None` as it is not implemented.
Now in the WPF Skia target when you request the `NetworkConnectivityLevel` it will return either
- `NetworkConnectivityLevel.InternetAccess`
- `NetworkConnectivityLevel.None`
**No Internet**
**Internet**
```c#
var currentConnectivity = NetworkConnectivityLevel.None;
var profile = NetworkInformation.GetInternetConnectionProfile();
if (profile != null)
currentConnectivity = profile.GetNetworkConnectivityLevel();
```
In this example we can now retrieve the correct connectivity level and `currentConnectivity` will either be `None` or `InternetAccess`.
Please check if your …
> feat: [WPF] Adds support for ConnectionProfile

- src/Uno.UI.Tests/Resources/Given_ResourceCandidate.cs
- src/Uno.UWP/ApplicationModel/Resources/Core/ResourceQualifier.cs
GitHub Issue (If applicable): fixes #6302
- Bugfix
Fixes partial matching of three-parts culture info, like `sr-Cyrl-BA` when generating resource files.
> fix: Fix sr-Cyrl resources loading

- src/Uno.UI.Runtime.WebAssembly.Compatibility/Uno.UI.Runtime.WebAssembly.Compatibility.csproj
- Build changes
Override Uno.UI nuget package for building wasm (netstandard 2.0)
- **error MSB4023: Cannot evaluate the item metadata "%(Filename)". The item metadata "%(Filename)" cannot be applied to the path "@(TargetPathWithTargetPlatformMoniker->'.pdb)". Illegal characters in path.**
-  **error MSB3030: Could not copy the file "Uno.UI.Wasm.pdb" because it was not found.**
No more building errors.
Removed redundant pdb copy for WebAssembly Compatibility since the first copy task already copies the Uno.UI.Wasm.pdb to the nuget override folder.
> fix: Remove redundant pdb copy for WebAssembly Compatibility

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileParser.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlParsingException.cs
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/6373
- Feature
XAML Parsing errors when running with roslyn-hosted generators (without Uno.SourceGenerationTasks) are now minimally reported using the diagnostics API instead of aggregate exceptions. The line/column information is also tentatively added to improve IDE navigation.
This change also avoid raising exceptions that the Microsoft telemetry will incorrect track.
> feat: Improve error reporting with Roslyn-hosted generators

- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/BrushesTests/DynamicBrushes_On_Shapes.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/BrushesTests/DynamicBrushes_On_Shapes.xaml.cs
- src/Uno.UI/Controls/AppBarButtonRenderer.Android.cs
- src/Uno.UI/Controls/CommandBarRenderer.Android.cs
- src/Uno.UI/Controls/NSStringAttributesHelper.macOS.cs
- src/Uno.UI/UI/Xaml/Controls/ProgressRing/ProgressRing.iOS.cs
- src/Uno.UI/UI/Xaml/Media/Brush.Android.cs
- src/Uno.UI/UI/Xaml/Media/ImageBrush.wasm.cs
* On WASM, dynamically changing the properties of an `<ImageBrush />` were leading to strange result
* A new sample for dynamic brushes
* Unify the way the fallback color is applied throughout the platform.
> Various improvements around brushes

- src/Uno.UI.RuntimeTests/Tests/Microsoft_UI_Xaml_Controls/Given_NavigationView.cs
- src/Uno.UI/UI/Xaml/Controls/Layouter/Layouter.Android.cs
- src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.Android.cs
Certain paths, such as a combination of infinite-width containers and calling the UpdateLayout() method, could result in parts of the visual tree falling into a bad layout state where IsLayoutRequested=true is interleaved with IsLayoutRequested=false, resulting in the bad subtrees never updating. To prevent this, check for this state and repair it by setting the layout request on the parent of the affected view.
This ensures that TextBlock will update correctly when its Foreground color changes (since it relies on a measure+arrange pass to be redrawn).
GitHub Issue (If applicable): fixes #5939
- Bugfix
> fix(textblock): [Android] Fix TextBlock color not updating

- src/Uno.UI/Microsoft/UI/Xaml/Controls/NavigationView/NavigationView.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/NavigationView/NavigationViewBackButtonVisible.cs
GitHub Issue (If applicable): fixes #6495 
- Bugfix
Back button is always shown on all Uno targets.
Back button will be hidden by default on `NavigationView` when visibility is set to `Auto`, to match Android design guidelines.
> fix: Hide NavigationView back button on Android by default

- src/Uno.UI.Runtime.Skia.Gtk/ApplicationModel/DataTransfer/ClipboardExtensions.cs
- src/Uno.UI.Runtime.Skia.Gtk/GtkHost.cs
- src/Uno.UI.Runtime.Skia.Wpf/Extensions/ApplicationModel/DataTransfer/ClipboardExtensions.cs
- src/Uno.UI.Runtime.Skia.Wpf/Extensions/ApplicationModel/DataTransfer/ClipboardNativeFunctions.cs
- src/Uno.UI.Runtime.Skia.Wpf/WpfHost.cs
- src/Uno.UI.Tests/Windows_ApplicationModel_DataTransfer/Given_FileUriHelper.cs
- src/Uno.UWP/ApplicationModel/DataTransfer/Clipboard.cs
- src/Uno.UWP/ApplicationModel/DataTransfer/Clipboard.skia.cs
- src/Uno.UWP/ApplicationModel/DataTransfer/FileUriHelper.cs
- src/Uno.UWP/ApplicationModel/DataTransfer/IClipboardExtension.skia.cs
- src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.DataTransfer/Clipboard.cs
GitHub Issue (If applicable): a part of #6179
- Feature
Clipboard does nothing on Skia.Wpf and Skia.Gtk targets.
Clipboard should copy data.
Some more details:
- `ContentChanged` event: Invokes properly, however, on both platforms, the functions may be invoke multiple times as many data targets are set.
- Text, Bitmap, and Html data: Works properly on both platforms.
- Rtf data: Works properly on WPF, can be detected on Linux if somehow Rtf data is set (for example when sharing clipboard using VMWare), although Rtf data is not natively found on Linux.
- Files: Works properly on WPF, should (theoretically) work on Gtk, however does ~~**not** work on popular distros using Nautilus (which stores copied files as _text_)~~. GNOME 40 [fixed the …
> feat: Support for Clipboard on WPF and Gtk

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/NestedHandling_Tests.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Input/PointersTests/NestedHandling.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Input/PointersTests/NestedHandling.xaml.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.iOS.cs
fixes https://github.com/unoplatform/nventive-private/issues/220
Add support of proper bublling of handled events
If a control handles the pressed event, parents won't receive any subsequent event
We no longer prevent bubbling of native pressed event, we instead filter them out on parents
> fix(pointers): [iOS] Add support of proper bubbling of handled events

- src/Uno.UI.RuntimeTests/Tests/Windows_Storage/Given_ApplicationDataContainer.cs
- src/Uno.UWP/Storage/ApplicationDataContainer.Android.cs
- src/Uno.UWP/Storage/ApplicationDataContainer.iOSmacOS.cs
- src/Uno.UWP/Storage/ApplicationDataContainer.skia.cs
- src/Uno.UWP/Storage/ApplicationDataContainer.wasm.cs
GitHub Issue (If applicable): fixes #6419
- Feature
Cannot enumerate over ApplicationData.Current.LocalSettings.Values
Can enumerate over ApplicationData.Current.LocalSettings.Values
> Enumeration over ApplicationDataContainer

- src/SolutionTemplate/UnoSolutionTemplate.net6/Shared/App.xaml.cs
WinUI project has incorrect build, because target framework version is .NET 6, but preprocessor directives still refers to .NET 5.
As the result, WinUI project trying to create UWP window, rather than Win32.
- Bugfix
WinUI build just crushes on Window creating.
> fix(template): Preprocessor directives refers to .NET 6

- build/PackageDiffIgnore.xml
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_Devices/LightSensorTests.xaml
- src/SamplesApp/UITests.Shared/Windows_Devices/LightSensorTests.xaml.cs
- src/Uno.UI/LinkerDefinition.Wasm.xml
- src/Uno.UI/WasmScripts/Uno.UI.d.ts
- src/Uno.UI/WasmScripts/Uno.UI.js
- src/Uno.UI/ts/Windows/Devices/Sensors/LightSensor.ts
- src/Uno.UWP/Devices/Sensors/LightSensor.Android.cs
- src/Uno.UWP/Devices/Sensors/LightSensor.cs
- src/Uno.UWP/Devices/Sensors/LightSensor.unsupported.cs
- src/Uno.UWP/Devices/Sensors/LightSensor.wasm.cs
- src/Uno.UWP/Devices/Sensors/LightSensorReading.cs
- src/Uno.UWP/Devices/Sensors/LightSensorReadingChangedEventArgs.cs
- src/Uno.UWP/Generated/3.0.0.0/Windows.Devices.Sensors/LightSensor.cs
- src/Uno.UWP/Generated/3.0.0.0/Windows.Devices.Sensors/LightSensorReading.cs
- src/Uno.UWP/Generated/3.0.0.0/Windows.Devices.Sensors/LightSensorReadingChangedEventArgs.cs
- src/Uno.UWP/Helpers/StartStopEventWrapper.cs
GitHub Issue (If applicable): closes #6315
- Feature
`LightSensor` is not supported.
Supported on WASM and Android
> Support for `LightSensor`

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_Style.cs
- src/Uno.UI/UI/Xaml/Style/Style.cs
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/5096
- Bugfix
Avoids raising `Error while unstacking precedence. Should be ExplicitStyle, got .` when an exception happens during a style application.
This change will allow for the underlying exception to be visible in the application logs.
> fix(Style): [Wasm] don't hide exceptions happening during style application

- build/uno.winui.targets
GitHub Issue (If applicable): #6532 
- Bugfix
- Feature
When a project with target Uno.UI adds a nuget package that implicitly depends on Uno.WinUI, SourceCodeGenerator throws "An item with the same key has already been added".
The build system generate an error indicating that the Uno.UI and Uno.WinUI libraries cannot be mixed.
Fixes #6532
> feat: detect the mixing of the Uno.UI and Uno.WinUI libraries.

- src/Uno.UI/UI/Xaml/Controls/Primitives/ButtonBase/ButtonBase.cs
- src/Uno.UI/UI/Xaml/Controls/Primitives/ToggleButton.cs
fixes https://github.com/unoplatform/nventive-private/issues/231
- Bugfix
- 
On iOS When using RadioButton with VoiceOver on, the Command is not executed on a RadioButton button when the CheckedChanged.
- [] Validated PR `Screenshots Compare Test Run` results.
**Note:** Please use the sample app attached to the Ticket to manually test this fix. Not possible to test using Unit Test/ UITest / 
> fix(iOS): RadioButton Command when VoiceOver is On

- src/Uno.UI.Toolkit/ElevatedView.cs
- Bugfix
fixed ElevatedView drop shadow not appearing on uwp.
The shadow mark was previously calculated from the content of elevated view which may be smaller than the border.
And because the drop shadow is applied to a canvas below the border, it is being blocked.
fixes https://github.com/unoplatform/nventive-private/issues/233
> fix(elevatedview): shadow not appearing on uwp

- src/Uno.UWP/ApplicationModel/Background/BackgroundTaskDeferral.Android.cs
- src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Background/BackgroundTaskDeferral.cs
- Feature
No `BackgroundTaskDeferral` implementation, so in `App.OnBackgroundActivated` using `#if` is required.
`BackgroundTaskDeferral` is implemented.
(although for Android it is empty implementation, as Android doesn't kill background tasks)
See also #2655.
> feat: BackgroundTaskDeferral for Android

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/FlyoutTests/UnoSamples_Tests.Flyout.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Flyout/Flyout_Namescope.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Flyout/Flyout_Namescope.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/BindingTests/Controls/Binding_ElementName_In_Template_In_Template.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/BindingTests/Controls/Binding_ElementName_In_Template_In_Template.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/BindingTests/Given_Binding.cs
- src/Uno.UI/UI/Xaml/Controls/Flyout/Flyout.cs
- Bugfix
Ensure `NameScope` propagation for flyout content, so that `ElementName` bindings can reach the flyout and its ancestors. 
> fix(flyout): Ensure namescope propagation for flyout content

- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/GradientBrushTests/GradientsPage.xaml
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.Reflection.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
GitHub Issue (If applicable): fixes #6565
- Bugfix
Explicitly using `GradientStopCollection` with `LinearGradientBrush` fails source generation.
Removed specific handling for `LinearGradientBrush` as the source generator already correctly handles it even without this (verified on `RadialGradientBrush`)
> fix: Can't use `GradientStopCollection` in XAML with `LinearGradientBrush`

- src/Uno.UWP/ApplicationModel/Background/SystemTrigger.Android.cs
- src/Uno.UWP/ApplicationModel/Background/SystemTrigger.cs
- src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Background/SystemTrigger.cs
GitHub Issue (If applicable): part #3045
- Feature
SystemTrigger is not implemented.
SystemTrigger is implemented.
This is part of #2655, and continuation of #3965.
Android implementation of SystemTrigger struct/class (some of trigger types, because not all have analogs in Android system).
Also, part of my app SmogMeter, published in Google Play and Amazon.
> feat: SystemTrigger struct implementation

- src/SamplesApp/SamplesApp.Droid/SamplesApp.Droid.csproj
- src/SamplesApp/SamplesApp.Skia/SamplesApp.Skia.csproj
- src/SamplesApp/SamplesApp.UITests.Generator/CategoryBucketGenerator.cs
- src/SamplesApp/SamplesApp.UITests.Generator/SamplesListGenerator.cs
- src/SamplesApp/SamplesApp.UITests.Generator/SnapShotTestGenerator.cs
- src/SamplesApp/SamplesApp.UITests.Generator/Uno.Samples.UITest.Generator.csproj
- src/SamplesApp/SamplesApp.UITests/SamplesApp.UITests.csproj
- src/SamplesApp/SamplesApp.UWP/SamplesApp.UWP.csproj
- src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.cs
- src/SamplesApp/SamplesApp.UnitTests.Shared/SamplesApp.UnitTests.Shared.projitems
- src/SamplesApp/SamplesApp.UnitTests.Shared/SamplesApp.UnitTests.targets
- src/SamplesApp/SamplesApp.Wasm/SamplesApp.Wasm.csproj
- src/SamplesApp/SamplesApp.iOS/SamplesApp.iOS.csproj
- src/SamplesApp/SamplesApp.macOS/SamplesApp.macOS.csproj
- src/SamplesApp/SamplesApp.net6mobile/SamplesApp.net6mobile.csproj
This brings the load time from 10s to 2s in debug wasm interpreted.
This is the cause of some UI/Runtime tests failures as the app takes a longer time to start.
> refactor: Move samples app list to be generated

- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_xLoad_FallbackValue.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_xLoad_FallbackValue.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_xLoad_FallbackValue_Converter.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_xLoad_FallbackValue_Converter.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Given_xBind_Binding.cs
- src/Uno.UI/DataBinding/BindingExpression.cs
Fixes https://github.com/unoplatform/uno/issues/6142
- Bugfix
Ensures that `FallbackValue` is applied properly when using `x:Bind`.
> fix(xBind): Fix support for FallbackValue

- build/Uno.UI.Build.csproj
- build/ci/templates/copy-package-assets.yml
GitHub Issue (If applicable): fixes #6581 
- Bugfix
Fixes a regression introduced with the .NET 6 packaging, where the UWP pri file is missing.
> fix: Ensure PRI file is included in the nuget package

- src/Uno.UI/UI/Xaml/Controls/ComboBox/ComboBox.cs
- src/Uno.UI/UI/Xaml/Internal/RootVisual.cs
GitHub Issue (If applicable): fixes #6553
- Bugfix
Focus is not lost when clicking outside app content.
Top level handles focus if pointer release bubbles to it.
fixes unoplatform/nventive-private#230
> fix: Ensure focus is lost when clicking outside app content

- build/Uno.UI.Build.csproj
- build/Uno.WinUI.MSAL.nuspec
- build/ci/.azure-devops-package.yml
- src/AddIns/Uno.UI.MSAL/Uno.UI.MSAL.csproj
- src/AddIns/Uno.UI.MSAL/Uno.UI.MSAL.net6.csproj
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/6596
- Bugfix
Restores the non-net6 targets in the Uno.UI.MSAL nuget package
> fix(msal): Move package generation to nuspec for net6 compatibility

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/SourceGenerators/XamlGenerationTests/WithInternalAccessModifier.xaml
- src/SourceGenerators/XamlGenerationTests/WithInternalAccessModifier.xaml.cs
GitHub Issue (If applicable): #5411
- Bugfix
Code is always generated with `public` modifier causing a compile-time error.
Code is now generated with the correct modifier so the code compiles successfully.
Fixes #5411
> Fix Xaml code generator to account for access modifier

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/SourceGenerators/XamlGenerationTests/EscapeContentString.xaml
GitHub Issue (If applicable): closes #4584
- Bugfix
Quotes are not escaped in generated code, causing compile-time errors.
Generate string literals using Roslyn API to mostly guarantee a valid syntax.
> fix: Properly generate string literals using Roslyn API

- src/SamplesApp/SamplesApp.Shared/App.xaml.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.Reflection.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/BindingTests/Controls/Binding_ElementName_In_Template_ItemsControl_NonUINested.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/BindingTests/Controls/Binding_ElementName_In_Template_ItemsControl_NonUINested.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/BindingTests/Controls/Binding_ElementName_NonUINested_GlobalResources.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/BindingTests/Controls/Binding_ElementName_NonUINested_GlobalResources.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/BindingTests/Controls/Binding_ElementName_NonUINested_GlobalResources_Dictionary.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/BindingTests/Given_Binding.cs
- src/Uno.UI/UI/Xaml/Markup/INameScope.cs
- src/Uno.UI/UI/Xaml/NameScope.cs
- Bugfix
- `ElementName` bindings hosted in a Global `ResourceDictionary` are now taken into account
- Non-UIElement `ElementName` bindings can not walk the tree to find elements outside of their immediate `NameScope`
> fix: Support for non-UIElement ElementName binding in global ResourceDictionary

- src/Uno.UI.Tests/BinderTests/Given_Binder.cs
- src/Uno.UI/UI/Xaml/DependencyObjectStore.Binder.cs
- Bugfix
The `DataContext` now propagates properly to non-`UIElement` `DependencyObject`-typed values in dependency properties. This behavior is generally used to data bind dependency objects in XAML for advanced configurations.
> feat: Add support for DataContext inheritance for non-UIElement

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ToolTipTests/ToolTip_Tests.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ToolTip/ToolTip_CollapsedHost.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ToolTip/ToolTip_CollapsedHost.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ToolTip/ToolTip_DynamicContent.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ToolTip/ToolTip_DynamicContent.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ToolTip/ToolTip_LeakTest.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ToolTip/ToolTip_LeakTest.xaml.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement_And_Leak.cs
- src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/ToolTipService.cs
- src/Uno.UI/UI/Xaml/Controls/ToolTip/ToolTip.cs
- src/Uno.UI/UI/Xaml/Controls/ToolTip/ToolTipService.cs
GitHub Issue (If applicable): #internal, fixes #6200
- Bugfix
Tooltip remains opened when the host control is no longer visible
Tooltip should be closed in that case.
Internal Issue (If applicable): see cross-linked issue.
> fix: tooltip remains opened when host control is no longer visible

- src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml
- src/Uno.UI/UI/Xaml/UIElement.Pointers.cs
- src/Uno.UI/UI/Xaml/UIElement.macOS.cs
- src/Uno.UI/UI/Xaml/Window.macOS.cs
closes #6418 
- Bugfix
ContentControl in a Window is intercepting the pointer events
> fix(macOS): contentControl intercepts pointer events

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Core/SystemNavigationManagerTests.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Core/SystemNavigationManagerTests/HardwareBackButton.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Core/SystemNavigationManagerTests/HardwareBackButton.xaml.cs
- src/Uno.UI/UI/Xaml/ApplicationActivity.Android.cs
GitHub Issue (If applicable): fixes #6617
- Bugfix
Hardware back button on Android does not work
Works
> fix: Android back button not working

- src/SourceGenerators/XamlGenerationTests/Grid.Test.xaml
- src/Uno.UI/UI/Xaml/GridLength.cs
GitHub Issue (If applicable): closes #5081
- Bugfix
A trailing `px` suffix in grid length throws an exception.
A trailing `px` suffix is now allowed.
> fix: Allow trailing 'px' for grid length

- .github/pull_request_template.md
It's sometimes missed, causing the relevant issue to not be closed automatically.
> docs: Update PR template to have a closing issue keyword

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ComboBoxTests/ComboBox_Pointers.cs
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TimePickerTests/UnoSamples_Tests.TimePicker.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ComboBox/ComboBox_Pointers.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ComboBox/ComboBox_Pointers.xaml.cs
- src/Uno.UI/UI/Xaml/Controls/ComboBox/ComboBox.cs
- src/Uno.UI/UI/Xaml/UIElement.EventRegistration.wasm.cs
- src/Uno.UI/UI/Xaml/UIElement.PointerCapture.cs
- src/Uno.UI/UI/Xaml/UIElement.RoutedEvents.cs
fixes https://github.com/unoplatform/uno/issues/5638
Make sure combo always handles `PointerPressed` and `PointerRelease` events
The `PointerPressed` is handled only on Android, so if used nested in a control which captures the pointer on pressed (like a `Button`) the `ComboBox` will never open.
`PointerPressed` and `PointerRelease` events are handled like on UWP
> fix: Make sure combo always handles pressed and release events

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ListViewTests/UnoSamples_Tests.ListView.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_Selection_Events.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_Selection_Events.xaml.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs
- src/Uno.UI.Tests/DependencyProperty/Given_DependencyProperty.cs
- src/Uno.UI.Tests/Windows_UI_XAML_Controls/ListViewBaseTests/Given_ListViewBase.cs
- src/Uno.UI/UI/Xaml/Controls/Primitives/Selector.cs
- src/Uno.UI/UI/Xaml/DependencyObjectStore.cs
GitHub Issue (If applicable): fixes #5792, fixes #6496
- Bugfix
SelectionChanged event were being fired before SelectedItem binding could be updated.
SelectedItem binding will be updated before the SelectionChanged event is fired.
> fix(Selector): firing order of data-bound dp & event

- src/Uno.UWP/Generated/3.0.0.0/Windows.UI.Notifications/ToastNotification.cs
- src/Uno.UWP/UI/Notifications/ToastNotification.Android.cs
- Feature
Not implemented.
Implemented.
This is part of #2585, Android implementation of toasts.
Also, part of my app SmogMeter, published in Google Play and Amazon.
Common parts of code was already merged (#4187, #4074). This PR adds two fields for ToastNotification - only for Android. I don't know if this functionality is implementable on other platforms, so I added it to Android only.
> feat: fields for Android ToastNotification

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/SwipeControlTests/SwipeControlTests.cs
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TimePickerTests/UnoSamples_Tests.TimePicker.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/SwipeControlTests/SwipeControl_Automated.xaml
- src/Uno.UI/System/DispatcherQueueTimer.cs
- src/Uno.UI/UI/Xaml/Controls/SwipeControl/SwipeControl.Uno.cs
- src/Uno.UI/UI/Xaml/Controls/SwipeControl/SwipeControl.cs
- src/Uno.UI/UI/Xaml/Input/ManipulationCompletedRoutedEventArgs.cs
- src/Uno.UI/UI/Xaml/Input/ManipulationDeltaRoutedEventArgs.cs
- src/Uno.UI/UI/Xaml/Input/ManipulationInertiaStartingRoutedEventArgs.cs
- src/Uno.UI/UI/Xaml/Input/ManipulationStartedRoutedEventArgs.cs
- src/Uno.UI/UI/Xaml/Input/ManipulationStartingRoutedEventArgs.cs
- src/Uno.UI/UI/Xaml/Input/Pointer.cs
- src/Uno.UI/UI/Xaml/Input/PointerRoutedEventArgs.iOS.cs
- src/Uno.UI/UI/Xaml/Media/Animation/Animators/NativeValueAnimatorAdapter.Android.cs
- src/Uno.UI/UI/Xaml/Media/Animation/Timeline.cs
- src/Uno.UI/UI/Xaml/UIElement.PointerCapture.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.iOS.cs
- src/Uno.UWP/Devices/Input/PointerIdentifier.cs
- src/Uno.UWP/System/DispatcherQueueTimer.cs
- src/Uno.UWP/UI/Input/GestureRecognizer.Manipulation.cs
- src/Uno.UWP/UI/Input/ManipulationCompletedEventArgs.cs
- src/Uno.UWP/UI/Input/ManipulationInertiaStartingEventArgs.cs
- src/Uno.UWP/UI/Input/ManipulationStartedEventArgs.cs
- src/Uno.UWP/UI/Input/ManipulationStartingEventArgs.cs
- src/Uno.UWP/UI/Input/ManipulationUpdatedEventArgs.cs
- src/Uno.UWP/UI/Input/PointerPoint.cs
* Pointers: Manipulations events are not raised for "fast gesture" (like a flick) on iOS
* `SwipeControl`: Speed computation is invalid when only few pointers data (like for "fast gesture")
* On iOS for fast gestures like a flick, we can have only 'down' and 'up' but no pointer moves, but `GestureRecognizer` requires at least one move to start a manipulation;
* `SwipeControl` has it's own logic to compute pointer speed which is now duplicated with the `ManipulationVelocities` provided by the manipulation events, but this computation expects to get more than a single move, which is not the case for a "flick" on iOS
* On iOS we simulate a 'move' before the 'up' if none has been raised since last 'down'
* `SwipeControl` now uses the speed provided by manipulation events
> Fix "fast" flick on SwipeControl

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.wasm.cs
GitHub Issue (If applicable): part of #5834
- Bugfix
When template with `TextBox` is recycled, it automatically gives the `TextBox` focus.
Does not happen anymore.
> fix: WASM TextBox getting focus when part of recycled template

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/Uno.UI.Tests/Windows_UI_Xaml/Controls/When_xLoad_DataTemplate_In_ResDict.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml/Controls/When_xLoad_DataTemplate_In_ResDict.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml/Controls/When_xLoad_DataTemplate_In_ResDict_Global.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml/Given_xLoad.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/6700, https://github.com/unoplatform/nventive-private/issues/238#issuecomment-895189012
- Bugfix
The build fails when load-time bound `{StaticResource}` is used in `x:Load` marked control.
The build does not fail any more, but the static resource is not yet properly updated, see https://github.com/unoplatform/uno/issues/6700 for details.
> fix: Don't generate invalid code when x:Load and StaticResource markup is used

- src/Uno.UI/Controls/AppBarButtonRenderer.iOS.cs
- src/Uno.UI/Extensions/UIBarButtonItemExtensions.iOS.cs
Fixes bug which occurs in narrow circumstances* where AppBarButton icon would disappear after navigating away from page then back.
*The bug occurs when properties of the AppBarButton are modified, causing Render() to be called, after navigating away; setting CustomView to null triggers a native exception similar to this one: https://stackoverflow.com/questions/53219042/self-navigationitem-rightbarbuttonitem-customview-nil-crash
The bug surfaced after recent changes to MenuFlyout (https://github.com/unoplatform/uno/pull/6571), but seems more a timing issue rather than directly related to those changes. The bug didn't occur in a standalone repro mimicking the configuration of the app for which it was reported.
GitHub Issue (If applicable): closes …
> fix(appbarbutton): [iOS] Fix AppBarButton icon sometimes disappearing

- doc/articles/roadmap.md
GitHub Issue (If applicable): closes #6560
Link is 404.
Working link.
> docs: Fix 404 link

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlConstants.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/SourceGenerators/XamlGenerationTests/MarkupExtensionReturnTypeShouldBeIgnored.xaml
- src/SourceGenerators/XamlGenerationTests/MarkupExtensionReturnTypeShouldBeIgnored.xaml.cs
GitHub Issue (If applicable): closes #2919
- Bugfix
Cast is made to the type specified in the attribute, resulting in a compile-time error, while UWP don't error for this.
The attribute is now ignored.
> fix: Ignore MarkupExtensionReturnType to match UWP behavior

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/SourceGenerators/XamlGenerationTests/Issue5054.xaml
- src/SourceGenerators/XamlGenerationTests/XamlGenerationTests.csproj
GitHub Issue (If applicable): closes #5054
- Bugfix
When the source generator is generating a property with name "Content", it shadows the base `Content` property, which causes issues when it's meant to access the base "Content" property.
Access the property with `base.` prefix to make sure we access the desired property.
> fix: Add 'base.' to make sure we not access generated property with same base name

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/SourceGenerators/XamlGenerationTests/SeparatingMatrixTransformBySpaces.xaml
- src/Uno.UI/DataBinding/BindingPropertyHelper.FastConvert.cs
GitHub Issue (If applicable): closes #4564
- Bugfix
The following isn't allowed and generates invalid code.
```xml
<MatrixTransform Matrix="1.1048446 0 0 1.1959561 -67.035883 -96.098854"/>
```
It's now allowed.
> fix: Allow separating by spaces and/or commas

- src/Uno.UWP/Devices/Radios/RadioAccessStatus.cs
- src/Uno.UWP/Devices/Radios/RadioKind.cs
- src/Uno.UWP/Devices/Radios/RadioState.cs
- src/Uno.UWP/Generated/3.0.0.0/Windows.Devices.Radios/RadioAccessStatus.cs
- src/Uno.UWP/Generated/3.0.0.0/Windows.Devices.Radios/RadioKind.cs
- src/Uno.UWP/Generated/3.0.0.0/Windows.Devices.Radios/RadioState.cs
GitHub Issue (If applicable): #3176, part #3045
- Feature
Windows.Devices.Radios is not implemented.
Structs/enums for Windows.Devices.Radios are implemented.
First part of Windows.Devices.Radios.Radio.GetRadiosAsync() implementation.
Enums defined for all platforms.
> feat: Windows.Devices.Radios common structs/enums

- src/Uno.UI/UI/Xaml/Input/Internal/FocusProperties.cs
- src/Uno.UI/UI/Xaml/UIElement.mux.cs
GitHub Issue (If applicable): closes #6667 
- Bugfix
NRE
No NRE :-) 
> fix: Null-check focus children in tab order

- src/Uno.UI/Controls/Window.iOS.cs
related to https://github.com/unoplatform/nventive-private/issues/238
- Bugfix
App crashes (NPE) on iOS when using VoiceOver and navigating back and forth between views when a popup window is open.
Avoid the crash by checking for null.
> fix(iOS): [Window] Null pointer exception

- src/Uno.UI.Tests/Windows_UI_Xaml/Theming/Given_Element_Theme.cs
- src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml/FrameworkElement.cs
- src/Uno.UI/UI/Xaml/Application.cs
- src/Uno.UI/UI/Xaml/FrameworkElement.cs
GitHub Issue (If applicable): closes #6620
- Bugfix
- Feature
- `ActualTheme` can be `ElementTheme.Default`
- `ActualThemeChanged` is not implemented
- `ActualTheme` is never default
- `ActualThemeChanged` is triggered
> feat: ActualTheme and ActualThemeChanged

- src/SourceGenerators/Uno.UI.SourceGenerators/NativeCtor/NativeCtorsGenerator.cs
GitHub Issue (If applicable): closes #6733
- Bugfix
Invalid documentation comment for generic symbols.
Don't generate `<see cref="" />` at all.
> fix: Don't include type name in doc comment due to roslyn bug

- src/Uno.UI.Tests/Windows_UI_XAML_Controls/ComboBoxTests/Given_ComboBox.cs
- src/Uno.UI/UI/Xaml/Controls/Primitives/Selector.cs
GitHub Issue (If applicable): closes #6739
- Bugfix
Adding/removing item before SelectedIndex doesn't affect the value of SelectedIndex
It's now changing properly (matching UWP behavior)
> fix: Handle SelectedIndex properly when removing/adding before the selected index

- build/uno.winui.single-project.targets
- src/Directory.Build.props
- src/Uno.Foundation/Collections/ObservableVectorEnumerableWrapper.cs
- src/Uno.Foundation/Collections/ObservableVectorListWrapper.cs
- src/Uno.Foundation/Collections/ObservableVectorWrapper.cs
- src/Uno.Foundation/LinkerDefinition.net6.xml
- src/Uno.Foundation/Uno.Foundation.net6.csproj
- src/Uno.UI.Toolkit/CommandBarExtensions.cs
- src/Uno.UI.Toolkit/LinkerDefinition.net6.0.xml
- src/Uno.UI.Toolkit/MenuFlyoutExtensions.cs
- src/Uno.UI.Toolkit/MenuFlyoutItemExtensions.cs
- src/Uno.UI.Toolkit/SplitViewExtensions.cs
- src/Uno.UI.Toolkit/UIElementExtensions.cs
- src/Uno.UI.Toolkit/Uno.UI.Toolkit.net6.csproj
- src/Uno.UI/BaseActivity.Android.cs
- src/Uno.UI/LinkerDefinition.net6.0-android.xml
- src/Uno.UI/UI/Xaml/ApplicationActivity.Android.cs
- src/Uno.UI/UI/Xaml/Controls/Flyout/FlyoutBase.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.Android.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/Popup/Popup.cs
- src/Uno.UI/UI/Xaml/Controls/ProgressRing/ProgressRing.cs
- src/Uno.UI/UI/Xaml/Controls/ProgressRing/ProgressRing.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/WebView/WebView.iOSmacOS.cs
- src/Uno.UI/UI/Xaml/NativeApplication.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.iOS.cs
- src/Uno.UI/UI/Xaml/UIElement.cs
- src/Uno.UI/Uno.UI.net6.csproj
- Bugfix
- Add support for net6 compilation in VS 17.0 Preview 3 (partials signatures includes names)
- Disable implicit global usings (to be removed in .NET 6 RC1)
- Adjust project capabilities for net6-ios/android detection
- Remove usage of deprecated `[Preserve]` in favor of linker definition file
> VS 17.0 Preview 3 fixes

- src/SamplesApp/UITests.Shared/Windows_UI_ViewManagement/ApplicationViewSizing.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_ViewManagement/ApplicationViewSizing.xaml.cs
- src/Uno.UI.Runtime.Skia.Gtk/GtkApplicationViewExtension.cs
- src/Uno.UI.Runtime.Skia.Gtk/GtkHost.cs
- src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/ApplicationViewExtension.cs
- src/Uno.UI.Runtime.Skia.Tizen/TizenApplicationViewExtension.cs
- src/Uno.UI.Runtime.Skia.Wpf/WpfApplicationViewExtension.cs
- src/Uno.UI.Runtime.Skia.Wpf/WpfHost.cs
- src/Uno.UI/UI/Xaml/Window.macOS.cs
- src/Uno.UWP/Generated/3.0.0.0/Windows.UI.ViewManagement/ApplicationView.cs
- src/Uno.UWP/UI/ViewManagement/ApplicationView.cs
- src/Uno.UWP/UI/ViewManagement/ApplicationView.macOS.cs
- src/Uno.UWP/UI/ViewManagement/ApplicationView.skia.cs
GitHub Issue (If applicable): closes #6136
- Feature
Following methods had no effect:
- ApplicationView.TryResizeView
- ApplicationView.SetPreferredMinSize
- ApplicationView.PreferredLaunchViewSize
Windows sizing methods now work for Skia and macOS platforms.
> feat: Implement sizing methods for ApplicationView

- src/Uno.UI.Runtime.Skia.Gtk/UI/Xaml/Controls/TextBoxViewExtension.cs
- src/Uno.UI.Runtime.Skia.Wpf/Extensions/UI/Xaml/Controls/TextBoxViewExtension.cs
- src/Uno.UI/UI/Xaml/Controls/PasswordBox/PasswordBox.skia.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/ITextBoxExtension.skia.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.skia.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.skia.cs
GitHub Issue (If applicable): closes #6396, closes #5767
- Feature
No support for PasswordBox on Skia GTK
Supported
> feat: Support PasswordBox on Skia

- src/Uno.UI/Extensions/ViewHelper.Android.cs
- src/Uno.UI/UI/Xaml/Window.Android.cs
- src/Uno.UWP/Graphics/Display/DisplayInformation.Android.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/6752
- Peformance
Improved general performance for Android implementation of `DisplayInformation`.
Note that we may need to add a configuration change flag here:
https://github.com/unoplatform/uno/blob/54ad32f85c75fb2e09af0045cf6820e58cdb8255/src/Uno.UI/UI/Xaml/ApplicationActivity.Android.cs#L23
to follow changes for scaling, and maybe others.
> perf: [Android] Improve DisplayInformation performance

- build/PackageDiffIgnore.xml
- src/Uno.UI.Tests/Windows_UI_Xaml/VisualStateManagerTests/Given_VisualStateManager.cs
- src/Uno.UI/FeatureConfiguration.cs
- src/Uno.UI/UI/Xaml/Media/Animation/ObjectAnimationUsingKeyFrames.cs
- src/Uno.UI/UI/Xaml/Media/Animation/Storyboard.cs
- src/Uno.UI/UI/Xaml/Media/Animation/Timeline.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.Managed.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.cs
- src/Uno.UI/UI/Xaml/VisualStateGroup.cs
- src/Uno.UI/UI/Xaml/VisualStateManager.cs
fixes https://github.com/unoplatform/uno/issues/6744
Multiple fixes about transition to fix `ScrollBar` disappearing from `ScrollViewer`
* When we define a `VisualTransition` between states, its `Storyboard` is not cancelled when changing to another state (driving the `VerticalScrollBar` to be set to `None` with a delay even if the scrollbars are needed again)
* When stopped, the `DoubleAnimationUsingKeyFrame` does not cancel its frames
* When using a `VisualTransition`, the `VisualState.Setters` of the target state are applied synchronously in the `GoToState` while they should be be applied only once the `VisualTransition.Storyboard` completes, if any.
* On skia, when the pointer leaves a control we propagate a silent pointer up to update the internal state (like UWP), but this also …
> Fix visual transition support

- src/Uno.UI.Runtime.Skia.Gtk/UI/Xaml/Controls/TextBoxViewExtension.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.skia.cs
GitHub Issue (If applicable): Addresses regression introduced in #6768, and also fixes the implementation of the same PR
- Bugfix
- TextBox was incorrectly obscuring text.
- PasswordBox wasn't correctly accounting for programmatically changes of reveal mode
Fix both problems.
> Correctly check if the TextBox is PasswordBox before obscuring text

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_UIElement.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/CounterGrid.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.Measure.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/TestsResources.xaml
- src/Uno.UI/UI/Xaml/Controls/Layouter/Layouter.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.Android.cs
GitHub Issue (If applicable): closes #6754
When a property of an item in the list changes, ensure that only that item container is remeasured.
- Bugfix
> fix(listview): [Android] Improve performance when updating list items

- doc/articles/features/windows-storage-pickers.md
- src/SamplesApp/UITests.Shared/Windows_Storage/Pickers/FileSavePickerTests.xaml
- src/Uno.UI/WasmScripts/Uno.UI.d.ts
- src/Uno.UI/WasmScripts/Uno.UI.js
- src/Uno.UI/ts/Windows/Storage/Pickers/FileOpenPicker.ts
- src/Uno.UI/ts/Windows/Storage/Pickers/FileSavePicker.ts
- src/Uno.UI/ts/Windows/Storage/Pickers/FolderPicker.Native.ts
- src/Uno.UI/ts/types/wicg-file-system-access/index.d.ts
- src/Uno.UWP/Storage/Pickers/FileOpenPicker.wasm.cs
- src/Uno.UWP/Storage/Pickers/FileSavePicker.wasm.cs
- src/Uno.UWP/Storage/Pickers/FolderPicker.wasm.cs
- src/Uno.UWP/Storage/Pickers/Internal/PickerLocationIdExtensions.wasm.cs
GitHub Issue (If applicable): closes #6612, closes #6513
- Feature
Not supported
Added support for the following properties on native WASM file pickers
- `SuggestedStartLocation`
- `SuggestedFileName`
- `SettingsIdentifier`
> Support for additional WASM file picker features

- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/GradientBrushTests/GradientsPage.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/ImageBrushTests/ImageBrushWithRotateTransform.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/ImageBrushTests/ImageBrushWithScaleTransform.xaml
- src/Uno.UI/Extensions/Matrix3x2Extensions.Android.cs
- src/Uno.UI/Microsoft/UI/Xaml/Media/RadialGradientBrush.Android.cs
- src/Uno.UI/UI/Xaml/Media/ImageBrush.Android.cs
- src/Uno.UI/UI/Xaml/Media/LinearGradientBrush.Android.cs
- src/Uno.UI/UI/Xaml/Media/Transform.Android.cs
GitHub Issue (If applicable): closes #6748, closes #1359
- Feature
- `LinearGradientBrush` on Android does not work with `RenderTrasnfrom`
- `LinearGradientBrush` on Android does not work with a single stop
- `ImageBrush` with `RenderTransform` throws `NotImplementedException`
Works.
> Support for `RenderTransform` with Android `LinearGradientBrush`

- src/SolutionTemplate/UnoSolutionTemplate.net6/UWP/Properties/Default.rd.xml
- src/SolutionTemplate/UnoSolutionTemplate/UWP/Properties/Default.rd.xml
GitHub Issue (If applicable): closes #5590
- Bugfix
After updating the Microsoft.Extensions.Logging libraries to latest in UWP head, the .NET Native release build of apps crashes at startup with:
> System.Reflection.MissingMetadataException: ''Microsoft.Extensions.Options.IPostConfigureOptions<>' is missing metadata.
The issue is discussed here: dotnet/runtime#44697
No crash.
> fix: Fix .NET Native Logging missing metadata

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Shapes/Path_Tests.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/PathTestsControl/Path_Dynamic_Geometries.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/PathTestsControl/Path_Dynamic_Geometries.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/PathTestsControl/Path_FillRule.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/PathTestsControl/Path_FillRule.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/PathTestsControl/Path_Geometries.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/PathTestsControl/Path_Geometries.xaml.cs
- src/Uno.UI/UI/Xaml/Media/EllipseGeometry.wasm.cs
- src/Uno.UI/UI/Xaml/Media/Geometry.wasm.cs
- src/Uno.UI/UI/Xaml/Media/GeometryData.wasm.cs
- src/Uno.UI/UI/Xaml/Media/GeometryGroup.wasm.cs
- src/Uno.UI/UI/Xaml/Media/LineGeometry.wasm.cs
- src/Uno.UI/UI/Xaml/Media/PathGeometry.wasm.cs
- src/Uno.UI/UI/Xaml/Media/RectangleGeometry.wasm.cs
Fixes https://github.com/unoplatform/uno/issues/6782
`FillRule` were not properly implemented when a `<GeometryGroup />` were used in a `<Path />` element.
> [Wasm] Added proper support for FillRule on Path Geometries

- src/Uno.UI.Tests/Uno_UI_Core/Given_KeyboardStateTracker.cs
- src/Uno.UI/UI/Xaml/UIElement.RoutedEvents.cs
- src/Uno.UWP/UI/Core/CoreWindow.cs
- src/Uno.UWP/UI/Core/Internal/KeyboardStateTracker.cs
GitHub Issue (If applicable): part of #5834 
- Feature
Key state is not tracked.
Key state is tracked for keyboard routed events (working on WASM and Skia currently).
> feat: Initial support for CoreWindow.GetKeyState

- src/SamplesApp/SamplesApp.UITests/Microsoft_UI_Xaml_Controls/TabViewTests/Given_TabView.cs
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/TabViewTests/TabViewPage.xaml
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/TabViewTests/TabViewPage.xaml.cs
- src/Uno.UI/UI/Xaml/Controls/Primitives/SelectorItem.cs
GitHub Issue (If applicable): closes #4722
- Bugfix
Disabled tab doesn't get the correct visual state
It now has the correct visual state.
> fix: Fix visual state for disabled selector items

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/SourceGenerators/XamlGenerationTests/NullableProperty.xaml
- src/SourceGenerators/XamlGenerationTests/NullableProperty_GridExtensions.cs
GitHub Issue (If applicable): closes #6688, closes #5829, closes #4591
- Bugfix
`string?` not matched as `string`.
Both are considered the same via the check of `SpecialType`
> fix: Fix checking symbol type when it's nullable ref type

- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/DatePicker/DatePicker_Features.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/DatePicker/DatePicker_Features.xaml.cs
- src/Uno.Foundation/UnoOnlyAttribute.cs
- src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePicker.Flyout.cs
- src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePicker.cs
- src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePickerSelector.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/DatePicker/NativeDatePickerFlyout.Android.cs
- src/Uno.UI/UI/Xaml/Controls/DatePicker/NativeDatePickerFlyout.iOS.cs
Fixes https://github.com/unoplatform/uno/issues/5575
Added a new UseNativeMinMaxDates property on DatePicker & NativeDatePickerFlyout to allow the picker to be restricted to some date instead of just the year.  Properties `MinYear` and `MaxYear` are still used for that since they are already of type `DateTimeOffset`.
> [iOS][Android] DatePicker: Added a new UseNativeMinMaxDates property

- doc/articles/features/pointers-keyboard-and-other-user-inputs.md
- src/SourceGenerators/Uno.UI.SourceGenerators/TSBindings/TSBindingsGenerator.cs
- src/Uno.Foundation.Runtime.WebAssembly/Interop/Runtime.wasm.cs
- src/Uno.Foundation.Runtime.WebAssembly/Interop/TSInteropMarshaller.HandleRef.wasm.cs
- src/Uno.Foundation.Runtime.WebAssembly/Interop/TSInteropMarshaller.wasm.cs
- src/Uno.UI/UI/Xaml/Application.wasm.cs
- src/Uno.UI/UI/Xaml/DragDrop/DragDropExtension.wasm.cs
- src/Uno.UI/UI/Xaml/DragDrop/DragRoot.cs
- src/Uno.UI/UI/Xaml/Input/PointerRoutedEventArgs.wasm.cs
- src/Uno.UI/UI/Xaml/UIElement.EventRegistration.wasm.cs
- src/Uno.UI/UI/Xaml/Window.cs
- src/Uno.UI/WasmScripts/Uno.UI.d.ts
- src/Uno.UI/WasmScripts/Uno.UI.js
- src/Uno.UI/ts/Interop/AsyncInteropHelper.ts
- src/Uno.UI/ts/MonoSupport.ts
- src/Uno.UI/ts/Windows/ApplicationModel/DataTransfer/DragAndDropExtension.ts
- src/Uno.UI/ts/Windows/Storage/NativeStorageFile.ts
- src/Uno.UI/ts/Windows/Storage/NativeStorageFolder.ts
- src/Uno.UI/ts/Windows/Storage/NativeStorageItem.ts
- src/Uno.UI/ts/Windows/Storage/Streams/NativeFileReadStream.ts
- src/Uno.UI/ts/Windows/Storage/Streams/NativeFileWriteStream.ts
- src/Uno.UI/tsBindings/DragDropExtensionEventArgs.ts
- src/Uno.UWP/ApplicationModel/DataTransfer/DataPackage.cs
- src/Uno.UWP/ApplicationModel/DataTransfer/DragDrop/Core/CoreDragDropManager.cs
- src/Uno.UWP/Storage/StorageFile.native.wasm.cs
fixes https://github.com/unoplatform/uno/issues/6293
Add ability to drop external content into wasm app
We cannot drop external content into app on WASM
🙃
> Add ability to drop external content into wasm app

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/CommandBarTests/UnoSamples_Tests.NativeCommandBar.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/CommandBar_Native_With_AppBarButton_With_Foreground.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/CommandBar_Native_With_AppBarButton_With_Foreground.xaml.cs
- src/Uno.UI/Controls/AppBarButtonRenderer.Android.cs
- src/Uno.UI/Controls/AppBarButtonRenderer.iOS.cs
GitHub Issue (If applicable): #6732 (Android only is fixed)
- Bugfix
Icons inside AppBarButton don't get their color correctly.
Correctly set their color.
> fix: Apply icon color correctly inside native AppBarButton

- src/SamplesApp/SamplesApp.UITests/UnoSamples_Tests.Keyboard.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.cs
- src/Uno.UI.Tests/DependencyProperty/Given_DependencyProperty.cs
- src/Uno.UI.Tests/Windows_UI_XAML_Controls/FlyoutTests/Given_Flyout.cs
- src/Uno.UI/UI/Xaml/Controls/Flyout/Flyout.cs
- src/Uno.UI/UI/Xaml/Controls/Flyout/FlyoutBase.cs
- src/Uno.UI/UI/Xaml/Controls/Flyout/FlyoutPresenter.cs
- src/Uno.UI/UI/Xaml/Controls/Popup/PopupBase.cs
- src/Uno.UI/UI/Xaml/DependencyObjectStore.cs
- Bugfix
`ApplyCoercion` is called after `SetValueInternal`. This causes issues for example in case of `TextBox`, which calls `BeforeTextChanging` during coercion - in the event handler, the `TextBox.Text` would already return the newly set `Text` instead of the old one.
Coercion is performed before `SetValueInternal`.
> fix: Apply coercion before value is set, propagate focus properties from flyout

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Shapes/Basics_Shapes_Tests.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/Offscreen_Shapes.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/Offscreen_Shapes.xaml.cs
- src/Uno.UI/WasmScripts/Uno.UI.js
- src/Uno.UI/ts/WindowManager.ts
Offscreen `.Measure()` of shapes on WASM were leading to a crash.
(note: internal issue)
> Fixed a potential crash with GetBBox() on WASM

- doc/articles/features/bluetoothdevice.md
- The page is in "Doc" folder instead of "doc" folder. On Unix-based systems, they are different and hence the page isn't published since the docfx.json file in "doc" won't pick up this file.
- A normal statement appears as a code block.
Fixed both.
> docs: Fix bluetoothdevice documentation page

- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/BorderTests/Border_CornerRadius_BorderThickness.xaml
GitHub Issue: https://github.com/unoplatform/Uno.Themes/issues/616
Related to: https://github.com/unoplatform/uno/pull/6898
- Adjust UI Test snapshots differences
UI Test was updated but not the associated xaml for the test
Adjust UI Test snapshots differences after changes for pull request #6898 (Related to Uno.Themes - #616)
> Fix(Border): Adjust UI Test snapshots differences after changes for pull request 6898 (Related to Uno.Themes - #616)

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileParser.cs
- Bugfix
XAML Source generators running in a .NET 5/6 context are now honoring cancellation requests.
> fix: Add XAML source generator cancellation support

- src/Directory.Build.targets
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/Given_XamlReader.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/When_ThemeResource.xamltest
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/When_ThemeResource_Lazy.xamltest
- src/Uno.UI/UI/Xaml/Markup/Reader/XamlObjectBuilder.cs
GitHub Issue (If applicable): closes #6639
- Bugfix
This change ensures that `ThemeResource` instances are loaded through the common flow for resource loading, so that the values coming from actual theme dictionaries, and parent element lazy dictionaries are applied properly.
> fix(xamlreader): Load ThemeResources properly

- src/Uno.UI.FluentTheme/Resources/.editorconfig
- src/Uno.UI.FluentTheme/Resources/Priority02/MenuFlyout_themeresources.xaml
- src/Uno.UI.FluentTheme/Resources/Priority06/RevealBrush_themeresources.xaml
- src/Uno.UI.FluentTheme/Resources/PriorityDefault/DropDownButton.xaml
- src/Uno.UI.FluentTheme/Resources/PriorityDefault/RatingControl.xaml
- src/Uno.UI.FluentTheme/Resources/PriorityDefault/RatingControl_themeresources.xaml
- src/Uno.UI.FluentTheme/Resources/PriorityDefault/SplitButton.xaml
- src/Uno.UI.FluentTheme/themeresources.xaml
- src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/SplitButton/SplitButtonTests.cs
- src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/ToggleSplitButton/ToggleSplitButtonTests.cs
- src/Uno.UI.RuntimeTests/MUX/Windows_UI_Xaml_Controls/DropDownButtonTests.cs
- src/Uno.UI/UI/Xaml/Controls/MenuFlyout/MenuFlyout_19h1_themeresources.xaml
GitHub Issue (If applicable): closes #6638
- Bugfix
Chevron glyph doesn't show correctly when using fluent theme.
Shows correctly.
> fix: Use SymbolThemeFontFamily instead of hard-coded Segoe MDL2 Assets

- src/Directory.Build.targets
- src/Uno.UI.Tests/Windows_UI_Xaml_Media/Given_LinearGradientBrush.cs
- src/Uno.UI/UI/Xaml/Media/LinearGradientBrush.cs
GitHub Issue (If applicable): closes #6950
- Bugfix
Not reflected.
Reflected, matching UWP.
> `LinearGradientBrush` angle should be reflected in `EndPoint`

- src/crosstargeting_override.props.sample
- Bugfix
The netstd 2.0 override needs to be used for debugging, net5 does not work properly. This will be adjusted when going to net6.
> fix: Remove net5.0 nuget override target option for skia/wasm

- src/Uno.UI.Runtime.WebAssembly/Xaml/UIElementWasmExtensions.cs
- src/Uno.UI/UI/Xaml/UIElement.wasm.cs
- src/Uno.UI/UI/Xaml/WindowManagerInterop.wasm.cs
- src/Uno.UI/WasmScripts/Uno.UI.d.ts
- src/Uno.UI/WasmScripts/Uno.UI.js
- src/Uno.UI/ts/WindowManager.ts
- src/Uno.UI/tsBindings/WindowManagerMeasureViewParams.ts
Added the ability to call .MeasureHtmlView() in Wasm applications. Useful to implement .MeasureOverride() in Wasm applications.
> feat(wasm_measureview): Added the ability to call .MeasureHtmlView() from Wasm applications

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media/Given_RevealBrush.cs
- src/Uno.UI/UI/Xaml/Media/Brush.skia.cs
Fall back on FallbackColor when RevealBrush is assigned, instead of trying to use unimplemented CompositionBrush property which throws an exception.
fixes https://github.com/unoplatform/uno.ui.toolkit/issues/58
> fix: [Skia] Fix layout when RevealBrush is used

- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_Selection.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_Selection.xaml.cs
- src/Uno.UI.Runtime.Skia.Gtk/UI/Xaml/Controls/TextBoxViewExtension.cs
- src/Uno.UI.Runtime.Skia.Wpf/Extensions/UI/Xaml/Controls/TextBoxViewExtension.cs
- src/Uno.UI.Tests/Windows_UI_XAML_Controls/TextBoxTests/Given_TextBox.cs
- src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/TextBox.cs
- src/Uno.UI/UI/Xaml/Controls/PasswordBox/SecureTextBoxView.macOS.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/ITextBoxExtension.skia.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/ITextBoxView.iOSmacOS.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/MultilineTextBoxView.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/SinglelineTextBoxView.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.Android.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.macOS.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.net.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.netstdref.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.skia.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.wasm.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.macOS.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.skia.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.wasm.cs
- src/Uno.UI/WasmScripts/Uno.UI.d.ts
- src/Uno.UI/WasmScripts/Uno.UI.js
- src/Uno.UI/ts/WindowManager.ts
GitHub Issue (If applicable): closes #6822
- Feature
- TextBox.Select and TextBox.SelectAll not implemented on all platforms.
- TextBox.SelectionStart, TextBox.SelectionLength not implemented on Skia.
Implemented
> Implement TextBox.Select, TextBox.SelectAll on all platforms, and SelectionStart, SelectionLength on Skia

- build/ios-uitest-run.sh
- src/SamplesApp/SamplesApp.UITests/Constants.cs
- src/SamplesApp/SamplesApp.UITests/MessageDialogTests/MessageDialogTest.cs
- src/SamplesApp/SamplesApp.UITests/SamplesApp.UITests.csproj
- src/SamplesApp/UITests.Shared/MessageDialogTests/MessageDialogTest.xaml
- src/SamplesApp/UITests.Shared/MessageDialogTests/MessageDialogTest.xaml.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/Uno.UWP/UI/Popups/MessageDialog.Android.cs
GitHub Issue (If applicable): closes #1950
- Bugfix
MessageDialog can be light-dismissed
MessageDialog can't be light-dismissed.
> fix: Disable light-dismissing MessageDialog

- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.Android.cs
GitHub Issue: closes #6240
- Fix
Error changing cursor color in API 29+
Fix cursor color change for Android 29+
> fix: fixes TextBox cursor color for Android 29+

- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/TextBlock_JustifiedText.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/TextBlock_JustifiedText.xaml.cs
- src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.Android.cs
GitHub Issue (If applicable): closes #5218
- Bugfix
Justified text not handled on Android.
It's now handled.
> fix: Handle justified text for TextBlock on Android

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Flyout.cs
- src/Uno.UI/UI/Xaml/Controls/ComboBox/ComboBox.cs
- src/Uno.UI/UI/Xaml/Controls/Popup/Popup.cs
- src/Uno.UI/UI/Xaml/Controls/Popup/PopupBase.cs
GitHub Issue (If applicable): partially #6852
- Bugfix
When a flyout gets focused and closes, no element is focused.
When flyout hides, focus is returned to previously focused element if it still exists.
> Flyout should return focus to previously focused element

- src/Uno.UI/DataBinding/BindingExpression.cs
- src/Uno.UI/DataBinding/BindingPropertyHelper.cs
- src/Uno.UI/UI/Xaml/Controls/Frame/Frame.cs
- src/Uno.UI/UI/Xaml/Controls/Grid/Grid.cs
- src/Uno.UI/UI/Xaml/Controls/Page/Page.mux.cs
- src/Uno.UI/UI/Xaml/DependencyObjectStore.cs
- src/Uno.UI/UI/Xaml/FrameworkElement.wasm.cs
- src/Uno.UI/UI/Xaml/SpecializedResourceDictionary.cs
- src/Uno.UI/UI/Xaml/UIElement.EventRegistration.wasm.cs
- src/Uno.UI/UI/Xaml/UIElement.Layout.netstd.cs
- src/Uno.UI/UI/Xaml/UIElement.PointerCapture.cs
- src/Uno.UI/UI/Xaml/UIElement.cs
- src/Uno.UI/WasmScripts/Uno.UI.d.ts
- src/Uno.UI/WasmScripts/Uno.UI.js
- src/Uno.UWP/UI/Core/CoreDispatcher.cs
GitHub Issue (If applicable): https://github.com/dotnet/runtime/issues/56309
These changes are required to reduce the interpreter performance hit.  The AOT compiler detects try/catch/finally containing methods and forces the interpreter, even if the try/catch is not in the execution path.
Inner methods are created to reduce the size of the interpreter-executed code, and return to AOT as soon as possible.
> perf: Apply various workarounds to mitigate PG-AOT dotnet/runtime issue #56309

- src/SolutionTemplate/UnoSolutionTemplate.net6/UWP/UnoQuickStart.Uwp.csproj
- src/SolutionTemplate/UnoSolutionTemplate/UWP/UnoQuickStart.Uwp.csproj
- Other... template update
Uses WinUI 2.5
Use WinUI 2.6 to match design.
> chore: Bump WinUI to 2.6.2 in template

- src/Uno.UI.FluentTheme/Resources/Version2/PriorityDefault/CheckBox_themeresources.xaml
- src/Uno.UI.FluentTheme/Resources/Version2/PriorityDefault/ComboBox_themeresources.xaml
- src/Uno.UI.FluentTheme/Resources/Version2/PriorityDefault/ToggleButton_themeresources.xaml
- src/Uno.UI.FluentTheme/themeresources_v2.xaml
GitHub Issue (If applicable): part of #6747
- Bugfix
`ComboBox` & `ToggleButton`  don't have rounded corners and elevation. `CheckBox` glyph visible even if unchecked.
`ComboBox` & `ToggleButton` & `CheckBox` look correctly.
> `ComboBox` & `ToggleButton` WinUI 2.6 border workaround, `CheckBox` glyph hiding

- src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault/CalendarView_themeresources.xaml
- src/Uno.UI.FluentTheme.v2/themeresources_v2.xaml
fixes https://github.com/unoplatform/uno/issues/7051
Use the WinUI 2.6 style for `CalendarDatePicker`
* The default `CalendarView` style's was not re-using the patches made for the 2.5
* On wasm the `CalendarDatePicker` is using the `CalendarViewCrippledAnimationStyle` style, which was still using the old design
🙃
The `CalendarView` style (picker or not) is still suffering some issue regarding text alignment on wasm: https://github.com/unoplatform/uno/issues/7064
> feat: Apply CalendarView specific style patches

- src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault/ProgressBar.xaml
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/7050
The template for `<ProgressBar />` on FluentV2 were displaying weird animation when put on indeterminated mode.
It has been reverted to _fluent v1_ until the [animation system](https://github.com/unoplatform/uno/issues/3919) has been refactored.
> Reverted to "v1" template for ProgressBar because the "fluent v2" is causing animation problems.

- src/SamplesApp/SamplesApp.UITests/RuntimeTests.cs
Retry determining if tests ended, in case DOM elements get detached while being changed.
> fix: Retry on detached DOM element

- src/Uno.UI/FeatureConfiguration.cs
- src/Uno.UI/UI/Xaml/FrameworkElement.netstd.cs
- fix
Previous related changes in https://github.com/unoplatform/uno/pull/7079 changed the behavior significantly and using a flag will allow for gradual exceptions resolution on the app side.
> perf(wasm): Place loaded/unloaded exception handling behind a flag

- build/PackageDiffIgnore.xml
- src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewerViewChangedEventArgs.cs
GitHub Issue (If applicable): closes #6682
- Bugfix
Public API not matching UWP
Make the setter internal so there is no public setter as in UWP.
> fix: Make IsIntermediate setter internal

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs
GitHub Issue (If applicable): closes #6134
- Bugfix
XamlGeneratorAnalyzerSuppressions not working.
Working.
`GetMSBuildItems("XamlGeneratorAnalyzerSuppressions")` was always empty. The correct values were assigned few lines before the deleted one:
```csharp
_analyzerSuppressions = context.GetMSBuildPropertyValue("XamlGeneratorAnalyzerSuppressionsProperty").Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries);
```
I'm not 100% sure why the deleted line didn't work, but maybe a missing `CompilerVisibleItemMetadata`? That's not needed anyway.
> fix: Generate analyzer suppressions properly

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TimePickerTests/UnoSamples_Tests.TimePicker.cs
GitHub Issue (If applicable): closes #6668, closes #7030
- Test
~~There is really weird behavior with some of these tests. Let's see if this change will do it for now, and I'll open a new issue shortly.~~
> test: Enable TimePicker tests

- build/PackageDiffIgnore.xml
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media_Animation/Given_ObjectAnimationUsingKeyFrames.cs
- src/Uno.UI/UI/Xaml/Media/Animation/IKeyFrame.cs
- src/Uno.UI/UI/Xaml/Media/Animation/KeyFrameComparer.cs
- src/Uno.UI/UI/Xaml/Media/Animation/KeyFrameScheduler.cs
- src/Uno.UI/UI/Xaml/Media/Animation/KeyTime.cs
- src/Uno.UI/UI/Xaml/Media/Animation/ObjectAnimationUsingKeyFrames.cs
- src/Uno.UI/UI/Xaml/Media/Animation/ObjectKeyFrame.cs
- src/Uno.UI/UI/Xaml/Media/Animation/RepeatBehavior.cs
- src/Uno.UI/UI/Xaml/Media/Animation/RepeatBehaviorType.cs
fixes https://github.com/unoplatform/uno/issues/7072
Improve perf of the `ObjectAnimationUsingKeyFrame`
All frames of the `ObjectAnimationUsingKeyFrame` are scheduled on start, and cancelled if the animation is stop before the end
Frames are scheduled one by one
> feat(perf): Improve perf of the ObjectAnimationUsingKeyFrame

- src/Uno.Foundation.Runtime.WebAssembly/Interop/TSInteropMarshaller.wasm.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_Window.cs
- src/Uno.UI/UI/Xaml/Application.wasm.cs
- src/Uno.UI/UI/Xaml/DragDrop/DragDropExtension.wasm.cs
fixes https://github.com/unoplatform/uno/issues/7091
Improve reliability of D&DExtension on wasm
Crashes if your try to create a new Window as it tries to create a second instance of D&DExtension .... which is not allowed
Re-use the same instance
> Improve reliability of D&D extension

- src/SamplesApp/SamplesApp.UITests/Constants.cs
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TextBlockTests/TextBlockTests.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/TextBlock_IsTextSelectionEnabled.xaml
- src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.cs
- src/Uno.UI/UI/Xaml/Input/FocusManager.wasm.cs
- src/Uno.UI/UI/Xaml/UIElement.FocusMixins.cs
GitHub Issue (If applicable): closes #7068
- Bugfix
`TextBlock` selection is not working.
Working again.
> fix: Text selection on WASM

- doc/articles/controls/map-control-support.md
- doc/articles/features/using-winui2.md
- doc/articles/getting-started-tutorial-1.md
- doc/articles/getting-started-tutorial-2.md
- doc/articles/guides/silverlight-migration/03-review-app-startup.md
- doc/articles/guides/status-bar-theme-color.md
- doc/articles/howto-consume-webservices.md
- doc/articles/interop/wasm-javascript-3.md
- doc/articles/native-styles.md
- doc/articles/native-views.md
- doc/blog/201907-SkiaSharp-for-wasm-support.md
- src/SolutionTemplate/UnoSolutionTemplate.net6/Shared/MainPage.xaml
- src/SolutionTemplate/UnoSolutionTemplate/Shared/MainPage.xaml
GitHub Issue (If applicable): closes #7102
- Bugfix
`Background` is set on `Grid` in default `MainPage.xaml`
`Background` is set on `Page`. Documentation updated too.
> fix: Move Background in default app template to Page

- src/Uno.UI/UI/Xaml/Controls/Page/Page.mux.cs
- src/Uno.UI/UI/Xaml/Input/FocusManager.Android.cs
- src/Uno.UI/UI/Xaml/Input/FocusManager.iOS.cs
- src/Uno.UI/UI/Xaml/Input/FocusManager.macOS.cs
- src/Uno.UI/UI/Xaml/Input/FocusManager.wasm.cs
- src/Uno.UI/UI/Xaml/Window.macOS.cs
GitHub Issue (If applicable): fixes #6650
- Bugfix
Previously, the first focusable child was focused on Page, even if the Page itself was focusable. 
Now the Page can be focused itself, which matches UWP. In addition, on initial focus we avoid opening the InputPane in case the initial focused element is a TextBox.
> fix: Initial focus on Page

- doc/articles/debugging-wasm.md
- src/SolutionTemplate/UnoSolutionTemplate.net6/Wasm/UnoQuickStart.Wasm.csproj
- src/SolutionTemplate/UnoSolutionTemplate/Wasm/UnoQuickStart.Wasm.csproj
- Feature
- Updated debugging documentation
- Updated templates to disable the linker in debug configuration by default
- Bump boostrapper to 3.0.0
> Update WebAssembly debugging documentation, adjust templates

- src/Uno.UI.RemoteControl.VS/Uno.UI.RemoteControl.VS.csproj
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/When_xLoad_Visibility_While_Materializing.xaml
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/When_xLoad_Visibility_While_Materializing.xaml.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_xLoad.cs
- src/Uno.UI/UI/Xaml/ElementStub.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/6998
- Bugfix
x:Load with Visibility binding does not fail with android.
> fix(xLoad): [Android] Fix invalid x:Load reentrancy issue

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBlock.cs
- src/Uno.UI/UI/Xaml/Extensions/FontHelper.Android.cs
- src/Uno.UI/UI/Xaml/Extensions/FontHelper.Lookup.Android.cs
- Bugfix
Ensure that a `null` TextBlock.FontFamily fallsback to the default system font
> fix(Android): Fix NRE when TextBlock.FontFamily is null

- build/ci/.azure-devops-unit-tests.yml
- src/Uno.UI-UnitTests-only.slnf
Don't build unused wasm projects for unit tests job, avoids race condition unused wsam projects.
> ci: Remove wasm tests from unit tests build

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/HitTest_GeometryGroup_Tests.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Input/PointersTests/HitTest_GeometryGroup.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Input/PointersTests/HitTest_GeometryGroup.xaml.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.wasm.cs
- Bugfix
`Path` whose `.Data` is injected later are unable to receive pointer events.
> fix(wasm): geometry not receiving pointer events

- src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault/GridViewItem_themeresources.xaml
- src/Uno.UI.FluentTheme.v2/themeresources_v2.xaml
GitHub Issue (If applicable): closes #7146 
- Bugfix
`GridViewItems` are not visible.
Are visible again, reverted the WinUI 2.6 style using `ListViewItemPresenter` and using `GridViewItemExpanded` style instead.
> fix: GridViewItems are not visible

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_AutoSuggestBox.cs
- src/Uno.UI/UI/Xaml/Controls/AutoSuggestBox/AutoSuggestBox.cs
GitHub Issue (If applicable): closes #6321
- Bugfix
- Changing `AutoSuggestBox.Text` doesn't propagate to the underlying `TextBox`
- Suggestion list is opened even if the control isn't focused.
- Suggestion list isn't opened on text change.
- Changing `AutoSuggestBox.Text` now propagates to the underlying `TextBox`
- Suggestion list is opened only if the control is focused.
- Suggest list is opened on text change (only when focused too).
> fix: Open suggestion list when focus, reflect text changes

- src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.DragDrop.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.Android.cs
Fix bug where drag-to-reorder would sometimes not be applied if item was dragged quickly, specifically in the case were the timing of events runs DragOver (pointer moved) -> Drop (pointer up) -> measure+arrange.
Fix an additional bug where an exception would occur if an item was dragged very rapidly from one end of the list to the other.
- Bugfix
Internal Issue (If applicable): fixes https://github.com/unoplatform/nventive-private/issues/255
> fix(listview): [Android] Fix drag-to-reorder not applying

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/When_xLoad_xBind_xLoad_Initial.xaml
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/When_xLoad_xBind_xLoad_Initial.xaml.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_xLoad.cs
- src/Uno.UI.Tests/Windows_UI_Xaml/Controls/When_xLoad_xBind_xLoad_Initial.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml/Controls/When_xLoad_xBind_xLoad_Initial.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Given_xBind_Binding.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/7161
- Bugfix
`x:Bind` evaluation is performed explicitly if the control being swapped is not yet loaded.
> fix(xbind): x:bind may not be evaluated if x:Load is true during Loading

- src/Uno.UI.Tests/Windows_UI_Xaml/Given_ResourceDictionary.cs
- src/Uno.UI/UI/Xaml/ResourceDictionary.cs
GitHub Issue (If applicable): Part of #7123
- Bugfix
Cached value doesn't get properly updated when needed.
Update cached value properly.
> Invalidate cached theme dictionary when theme dictionaries are added/removed

- src/Uno.UI/UI/Xaml/Media/VisualTreeHelper.cs
GitHub Issue (If applicable): closes #7157
- Bugfix
`VisualTreeHelper.HitTest` [ignores Clip](https://github.com/unoplatform/uno/blob/e5febdcfd7321713dc20091b9bf0481a84636af6/src/Uno.UI/UI/Xaml/Media/VisualTreeHelper.cs#L363-L367) completely, assumes that Clip is **always** null, and always use an Infinite `Rect` for `HitTest`ing. This may cause problems with some translated `WinUI` controls, such as in #7157.
`VisualTreeHelper.HitTest` uses `Clip?.Bounds` when it is non-null.
> fix(HitTest): Check for Clip property for ClippingBounds

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/When_xLoad_xBind_xLoad_While_Loading.xaml
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/When_xLoad_xBind_xLoad_While_Loading.xaml.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_xLoad.cs
- src/Uno.UI/Mock/ElementStub.net.cs
- src/Uno.UI/UI/Xaml/ElementStub.Android.cs
- src/Uno.UI/UI/Xaml/ElementStub.cs
- src/Uno.UI/UI/Xaml/ElementStub.iOSmacOS.cs
- src/Uno.UI/UI/Xaml/ElementStub.netstd.cs
GitHub Issue (If applicable): closes #7189
- Bugfix
Changing the `x:Load` state during the `Loaded` event handler works properly.
> fix(xLoad): Adjust x:Load and x:Bind loading sequence

- doc/articles/features/native-frame-nav.md
- src/Uno.UI/Helpers/FrameNavigationHelper.cs
Relevant to NavigationBar work
- Feature
Add a FrameNavigationHelper to expose:
- [`CurrentEntry` property on `Frame` ](https://github.com/unoplatform/uno/blob/e5febdcfd7321713dc20091b9bf0481a84636af6/src/Uno.UI/UI/Xaml/Controls/Frame/Frame.cs#L45)
- [`Instance` property on `PageStackEntry`](https://github.com/unoplatform/uno/blob/e5febdcfd7321713dc20091b9bf0481a84636af6/src/Uno.UI/UI/Xaml/Navigation/PageStackEntry.cs#L48)
- [A creation method for `NavigationEventArgs`](https://github.com/unoplatform/uno/blob/e5febdcfd7321713dc20091b9bf0481a84636af6/src/Uno.UI/UI/Xaml/Navigation/NavigationEventArgs.cs#L10)
This is helpful when apps are defining their own Frame navigation logic. We can see how these are currently being used within the Uno …
> feat: Add a FrameNavigationHelper to allow apps to access helper properties on Frame and its PackStackEntries

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Media/GradientBrushTests/LinearGradientBrush_Tests.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/GradientBrushTests/LinearGradientBrush_Opacity.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media/GradientBrushTests/LinearGradientBrush_Opacity.xaml.cs
- src/Uno.UI/Microsoft/UI/Xaml/Media/RadialGradientBrush.Android.cs
- src/Uno.UI/Microsoft/UI/Xaml/Media/RadialGradientBrush.iOSmacOS.cs
- src/Uno.UI/UI/Xaml/Media/LinearGradientBrush.Android.cs
- src/Uno.UI/UI/Xaml/Media/LinearGradientBrush.iOSmacOS.cs
GitHub Issue (If applicable): closes #1448
- Bugfix
Opacity isn't respected.
It's now respected.
> fix: Respect Opacity when rendering gradient brushes

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Popups/Given_MessageDialog.cs
- src/Uno.UI/UI/Xaml/Application.cs
- src/Uno.UWP/Helpers/DispatcherTimerProxy.cs
- src/Uno.UWP/Helpers/VisualTreeHelperProxy.cs
- src/Uno.UWP/UI/Popups/MessageDialog.cs
- src/Uno.UWP/UI/Popups/MessageDialog.wasm.cs
GitHub Issue (If applicable): closes #1929
- Bugfix
flyouts not closed when a MessageDialog is shown.
They are now closed, matching UWP behavior.
> fix: Hide open flyouts when MessageDialog is shown

- src/SamplesApp/SamplesApp.UITests/Extensions/QueryExtensions.cs
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/MenuFlyoutTests/MenuFlyoutTests.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MenuFlyoutTests/MenuFlyout_Nested_5639.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MenuFlyoutTests/MenuFlyout_Nested_5639.xaml.cs
- src/Uno.UI/UI/Xaml/Controls/MenuFlyout/CascadingMenuHelper.cs
Fix bug where nested submenus could be shown offscreen on the 2nd and later times they appeared.
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/5639 , fixes #6928 
- Bugfix
> fix(menuflyout): Ensure MenuFlyout nested submenus stay on screen

- build/PackageDiffIgnore.xml
- src/Uno.UI.RemoteControl/RemoteControlClient.cs
- src/Uno.UI.Runtime.Skia.Gtk/GtkCoreWindowExtension.cs
- src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/CoreWindowExtension.cs
- src/Uno.UI.Runtime.Skia.Tizen/TizenCoreWindowExtension.cs
- src/Uno.UI.Runtime.Skia.Wpf/WpfCoreWindowExtension.cs
- src/Uno.UI/Extensions/UIElementExtensions.cs
- src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.Managed.cs
- src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.cs
- src/Uno.UI/UI/Xaml/Input/PointerRoutedEventArgs.cs
- src/Uno.UI/UI/Xaml/UIElement.PointerCapture.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.Managed.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.cs
- src/Uno.UI/UI/Xaml/UIElement.RoutedEvents.cs
- src/Uno.UWP/UI/Core/CoreWindow.Pointers.Managed.cs
- src/Uno.UWP/UI/Core/CoreWindow.cs
- src/Uno.UWP/UI/Core/CoreWindow.macOS.cs
- src/Uno.UWP/UI/Core/ICoreWindowExtension.cs
- src/Uno.UWP/UI/Input/GestureRecognizer.Gesture.cs
- src/Uno.UWP/UI/Input/GestureRecognizer.Manipulation.cs
- src/Uno.UWP/UI/Input/GestureRecognizer.cs
- src/Uno.UWP/UI/Input/ManipulationCompletedEventArgs.cs
- src/Uno.UWP/Uno/DeviceHelper.cs
fixes https://github.com/unoplatform/uno/issues/7198
Misc fixes for pointers
We have to double tap on buttons when they are nested in `ScrollViewer` on skia
* Managed `SCP` (Skia/MacOS) aborts drag manipulation in `MnaipulationStarting` when not a mouse (Avoids useless implicit captures)
* Manipulation cancelled in `ManipulationStarting` are properly cleaned-up (was staying active until next `PointerDown` causing some noise in the log)
* Implicit captures (Skia/MacOS) are properly released on `PointerReleased` (Only explicit captures was released)
* Implicit captures (Skia/MacOS) are released on `ManipulationCompleted` which might be much earlier than `PointerRelease` if manipulation is programmatically completed
* Native pointer capture is now supported on GTK
* Misc: Reduce number of …
> Misc fixes for pointers

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_UIElement.TransformToVisual.cs
- src/Uno.UI/UI/Xaml/UIElement.cs
When calling scrollViewer.TransformToVisual(), its scroll offsets were incorrectly being included in the returned transform, giving strange values.
This fix should improve the behaviour of VisibleBoundsPadding when used on elements nested inside a ScrollViewer.
- Bugfix
fixes https://github.com/unoplatform/nventive-private/issues/284
> fix(transformtovisual): Fix TransformToVisual on scrolled ScrollViewer

- src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewMode.Properties.cs
- src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Controls/SampleChooserControl.xaml
GitHub Issue (If applicable): closes #7196
- Feature
Not supported.
Basic support for dark theme in Samples app added,
> feat: Support Dark theme in Samples app

- doc/articles/controls/ListViewBase.md
Tabs were replaced with 2 spaces. More than 2 spaces make docs very hard to read in docs layout
> Improved XAML readability in ListViewBase.md

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/Animation_Leak.xaml
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/Animation_Leak.xaml.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement_And_Leak.cs
- src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.csproj
- src/Uno.UWP/UI/Composition/CoreAnimation.iOSmacOS.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/nventive-private/issues/272
Fixed a problematic case where a native animation can be _lost_ if the GC is run during the duration of the animation, preventing the animation from being removed and leaving the UI in an undetermined undesired state.
> [iOS] Fixed potential native animation not terminating

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_xLoad.cs
- src/Uno.UI/UI/Xaml/ElementStub.cs
GitHub Issue (If applicable): closes #7244
- Bugfix
Under webassembly, as try/finally blocks are removed, ElementStub is now properly maintaining its internal state to avoid update loops.
> fix(xBind): [Wasm] Fix invalid internal ElementStub state

- src/Uno.UI.RuntimeTests/Extensions/FrameworkElementExtensions.cs
- src/Uno.UI.RuntimeTests/Helpers/TestsResourceHelper.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_UIElement.TransformToVisual.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.Measure.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs
- src/Uno.UI/UI/Xaml/Controls/ItemsControl/ItemsPresenter.cs
- src/Uno.UI/UI/Xaml/Controls/ItemsControl/ItemsPresenter.iOSAndroid.cs
- src/Uno.UI/UI/Xaml/Controls/Layouter/Layouter.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBaseSource.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/NativeListViewBase.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.Android.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.iOS.cs
- src/Uno.UI/UI/Xaml/FrameworkElement.iOS.cs
- src/Uno.UI/UI/Xaml/ILayoutOptOut.cs
- src/Uno.UI/UI/Xaml/UIElement.iOS.cs
Match Windows' behavior when ItemsPresenter.MinHeight (or MinWidth for horizontal-scrolling list) is set inside of a ListView or GridView. Since the ItemsPresenter is actually outside the scrollable container (NativeListViewBase), this is implemented by mapping the MinHeight value to the native layout calculated by VirtualizingPanelLayout.
This supports scenarios where a minimal scrollable extent, regardless of number of items, is desired.
Additionally fixes a regression on iOS when calling TransformToVisual from within a ListView.
- Bugfix
- Feature
closes https://github.com/unoplatform/nventive-private/issues/303
> Support ItemsPresenter.MinHeight in ListView, fix TTV regression

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement_EffectiveViewport.cs
- src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.wasm.cs
- src/Uno.UI/UI/Xaml/FrameworkElement.EffectiveViewport.cs
closes https://github.com/unoplatform/uno/issues/7355
Fix miscs scrolling issues in `CalendarView` and `CalendarDatePicker`
* The `SV.ViewChanged` might be missed when scrolling has been requested before the SV is loaded
* When we subscribe to the `EVPChanged` event on an element that has already been layouted, the element remains flags `_isLayouted = false` driving the event to not being fired . That's the case when we re-open a `CalendarDatePicker`: scrolling does not update the EVP.
🙃
> fix(calendar): Fix miscs scrolling issues

- src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/Repeater/LayoutTests.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement.cs
- src/Uno.UI/UI/Xaml/UIElement.Layout.netstd.cs
Make sure that an element can invalidate itself (and its parents) while it's being measured / arranged
The `Is<Measure|Arrange>Dirty` flags are reset **after** the actual measure / arrange, so if the element or one of its children do `Invalidate<Measure|Arrange>` (or alters the visual tree in a way which cause an invalidate), the flag is reset immediately after, preventing any new layouting phase.
The `Is<Measure|Arrange>Dirty` flags are reset **before** the actual measure.
> fix: Make sure that an element can invalidate itself in Measure/Arrange

- src/Uno.UI.Tests/Windows_UI_Xaml/Given_ResourceDictionary.cs
- src/Uno.UI/UI/Xaml/ResourceDictionary.cs
- src/Uno.UI/UI/Xaml/SpecializedResourceDictionary.cs
GitHub Issue (If applicable): closes #7044
- Bugfix
Adding a resource with a System.Type key then retrieving it will result in a string being produced.
Correctly retrieve it as System.Type.
There was two issues here:
1. `ConvertKey(k.Key)`, this was resulting in an implicit conversion from string to `ResourceKey`, resulting in losing the information of the original `ResourceKey`.
2. Usage of `Type.GetType`, which only works in the current assembly or mscorlib (or System.Private.CoreLib).
> fix: Handle types correctly in ResourceDictionary

- src/Uno.UI.Runtime.Skia.Gtk/UI/Xaml/Controls/TextBoxViewExtension.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.cs
GitHub Issue (If applicable): Part of #7271
- Bugfix
`Select` not working on Skia
`Select` is now working properly.
> fix: Fix TextBox selection in Skia

- .vsts-ci.yml
- build/android-uitest-build.sh
- build/ci/.azure-devops-android-tests.yml
- build/ci/.azure-devops-package-generic.yml
- build/ci/.azure-devops-samplesapp-uitests-build.yml
- build/ci/.azure-devops-skia-tests.yml
- build/ci/.azure-devops-unit-tests.yml
- build/ci/.azure-devops-vs2022-vsix.yml
- build/ci/.azure-devops-wasm-cs9-preview-validation.yml
- build/ci/.azure-devops-wasm-uitests.yml
- build/ci/templates/dotnet-install.yml
- build/ios-uitest-build.sh
- build/run-automated-uitests.sh
- src/Directory.Build.props
- src/Directory.Build.targets
- src/SamplesApp/SamplesApp.Skia.WPF/SamplesApp.Skia.WPF.csproj
- src/SolutionTemplate/UnoSolutionTemplate/Skia.Tizen/UnoQuickStart.Skia.Tizen.csproj
- src/Uno.Foundation/AsyncAction.cs
- src/Uno.UI.RemoteControl.VS/Uno.UI.RemoteControl.VS.csproj
- src/Uno.UI.Runtime.Skia.Wpf/Uno.UI.Runtime.Skia.Wpf.csproj
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement.cs
- src/Uno.UI/UI/Xaml/Shapes/Shape.layout.cs
- src/Uno.WinUIRevert/Uno.WinUIRevert.csproj
- src/roslyn-override.targets
- Move to C# 10 for all Uno solution projects, including macOS ones
- Use .NET 6 wherever possible
- Use stable VS2022 for VSIX creation
- Use hosted pool for skia tests (latest hosted agents seem to introduce some memory corruption)
> ci: Use C# 10 inside the Uno solution

- src/Uno.UI/UI/Xaml/Controls/Frame/Frame.cs
closes #7478 
- Bugfix
When navigating within a Frame that is in a Popup, the Popup will be force closed
Popups will remain open while their inner Frame navigates
> Don't call CloseAllPopups on Frame navigation

- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/Given_XamlReader.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/When_Brush_And_StringColor.xamltest
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/When_Color_Thickness_GridLength_As_String.xamltest
- src/Uno.UI/UI/Xaml/Markup/Reader/XamlConstants.cs
- src/Uno.UI/UI/Xaml/Markup/Reader/XamlObjectBuilder.cs
- src/Uno.UI/UI/Xaml/Markup/Reader/XamlTypeResolver.cs
- Feature
`XamlReader` Support for in Resources or explicit inlines for:
- Brush
- olidColorBrush
- Color
- Thickness
- CornerRadius
- Media.FontFamily
- GridLength
- Media.Animation.KeyTime
- Duration
- Matrix
- FontWeight
> feat: Add support for multiple XamlReader types conversions

- src/Uno.UI.Runtime.Skia.Gtk/GtkCoreWindowExtension.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.wasm.cs
GitHub Issue (If applicable): closes #7382
- Bugfix
- `IsInContact` is always `true` for WASM `PointerMoved`, false for `PointerEntered`/`Exited`
- `IsInRange` is `false` in GTK
- `IsInContact` on WASM based on the actual pressed state of the pointer
- `IsInRange` is `true` in GTK
> Align `IsInContact` and `IsInRange` pointer properties

- build/PackageDiffIgnore.xml
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/InfoBarTests/InfoBarPage.xaml
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/InfoBarTests/InfoBarPage.xaml.cs
- src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault/InfoBar.xaml
- src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault/InfoBar_themeresources.xaml
- src/Uno.UI.FluentTheme.v2/themeresources_v2.xaml
- src/Uno.UI/Microsoft/UI/Xaml/Controls/InfoBar/InfoBar.Properties.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/InfoBar/InfoBar.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/InfoBar/InfoBarAutomationPeer.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/InfoBar/InfoBarCloseReason.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/InfoBar/InfoBarClosedEventArgs.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/InfoBar/InfoBarClosingEventArgs.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/InfoBar/InfoBarPanel.Properties.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/InfoBar/InfoBarPanel.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/InfoBar/InfoBarSeverity.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/InfoBar/InfoBarTemplateSettings.cs
- Bugfix
- Feature
- `InfoBarPanel` has wrong namespace
- `InfoBar` is not up to date
- `InfoBarPanel` now has correct namespace
- `InfoBar` is updated to latest WinUI sources
- All `InfoBar` properties and classes have documentation
> Fix `InfoBarPanel` namespace, update `InfoBar` to latest WinUI

- src/Uno.UI/Microsoft/UI/Xaml/Controls/NavigationView/NavigationViewItem.Properties.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/NavigationView/NavigationViewItemPresenter.Properties.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/NavigationView/NavigationViewTemplateSettings.Properties.cs
- Bugfix
The property was missing, resulting in error in logs
No longer missing.
> fix: Add missing `NavigationViewItemPresenter.InfoBadge` property

- src/Uno.UI.Tests/Windows_UI_Xaml/VisualStateManagerTests/Given_VisualStateManager.cs
- src/Uno.UI/UI/Xaml/VisualStateManager.cs
Fix support of the CustomVisualStateMamager
The custom VSM is resolved on the control itself
It's resolved on the template root of the control like on UWP
> fix: Fix support of the CustomVisualStateMamager

- doc/articles/uno-app-solution-structure.md
"Platform" word is missing in front of Uno.
Uno is now Uno Platform
> docs: Added Platform in front of Uno in the article "Uno app solution structure"

- src/Uno.UI.Runtime.Skia.Gtk/UI/Xaml/Controls/TextBoxViewExtension.cs
- src/Uno.UI.Runtime.Skia.Wpf/Extensions/UI/Xaml/Controls/Extensions.cs
- src/Uno.UI.Runtime.Skia.Wpf/Extensions/UI/Xaml/Controls/TextBoxViewExtension.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/ITextBoxExtension.skia.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.skia.cs
GitHub Issue (If applicable): closes #7172
- Bugfix
- On Skia, we update `Foreground` only for the `DisplayBlock` (appears only when unfocused)
- On Skia WPF, we only support SolidColorBrush
- Update `Foreground` properly for both the input widget and the `DisplayBlock`.
- Support more brushes on WPF.
> fix: Fix TextBox.Foreground on Skia

- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/Uno.ProjectTemplates.Dotnet.csproj
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-net6/.template.config/template.json
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-winui-net6/.template.config/template.json
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-winui/.template.config/template.json
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp/.template.config/template.json
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/7277
- Bugfix
No more invalid solution filter in the dotnet-new app template
> fix(dotnetnew): Remove invalid solution filters in `dotnet new unoapp`

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/VisualState_Tests.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_Focus_In_ScrollViewer.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_Focus_In_ScrollViewer.xaml.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs
GitHub Issue (If applicable): closes #7289 
- TextBox was previously getting focused when an ancestor ScrollViewer was being manipulated, because the focus was set on pointer press
- In UWP/WinUI, TextBox is only getting focus on pointer press for mouse and pen inputs, but not for touch. This now matches our behavior as well.
> fix: TextBox should not get focused while manipulating ScrollViewer

- src/Uno.UI.RuntimeTests/MUX/Given_SharedHelpers.cs
- src/Uno.UI/Helpers/WinUI/SharedHelpers.cs
GitHub Issue (If applicable): closes #7513
- Bugfix
Orignal WinUI code caches the values using local static variables. However, as it is inside of a template function, compilation results in multiple copies of the function with separate cache values. Our code did not handle it this way.
Using static dictionary to cache the values. Added tests to prevent regressions.
> Ensure `IsApiContractAvailable` does not cache only one value for all requested versions

- src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.cs
GitHub Issue (If applicable): closes #7514
- Bugfix
In Skia the `ScrollViewer` `ExtentHeight` and `ExtentWidth` are based on the `ActualHeight` and `ActualWidth` value of a child. For `TextBlock` there is a special case where these values match the `DesiredSize`, which may can contain values with rounding errors (e.g. 18.0013324). This then causes issues for `TextBox` for example, as `ExtentHeight` - `ViewPortHeight` will resurt in a very small number like `0.0013324`, which is however enough to make the `ScrollBar` visibility toggle between `Collapsed` and `Visible` and it can happen repeatedly.
We check whether the `Extent` - `Viewport` subtraction actually yields a significant value, otherwise we just zero it out.
Please check if your PR …
> fix: Avoid jumpy ScrollViewer visibility on Skia by avoiding rounding errors in `ScrollViewer`

- src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Automation.Peers/RatingControlAutomationPeer.cs
- src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/RatingControl.cs
- src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/SplitButton.cs
- src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/SplitButtonAutomationPeer.cs
- src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/ToggleSplitButton.cs
- src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/ToggleSplitButtonAutomationPeer.cs
- src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/TreeView.cs
- src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/TwoPaneView.cs
- src/Uno.UI/UI/Xaml/Automation/Peers/RatingControlAutomationPeer.cs
- src/Uno.UI/UI/Xaml/Controls/Unsupported/RatingControl.cs
- src/Uno.UI/UI/Xaml/Controls/Unsupported/SplitButton.cs
- src/Uno.UI/UI/Xaml/Controls/Unsupported/SplitButtonAutomationPeer.cs
- src/Uno.UI/UI/Xaml/Controls/Unsupported/ToggleSplitButton.cs
- src/Uno.UI/UI/Xaml/Controls/Unsupported/ToggleSplitButtonAutomationPeer.cs
- src/Uno.UI/UI/Xaml/Controls/Unsupported/TreeView.cs
- src/Uno.UI/UI/Xaml/Controls/Unsupported/TwoPaneView.cs
- src/Uno.WinUIRevert/Program.cs
GitHub Issue (If applicable): closes #7501, related to #3886
- Feature
- WUX controls implemented in MUX namespace are not easily recognizable and they just fail to show up at runtime
- The controls throw a `NotImplementedException` with clear explanation to transition to MUX namespace
- Generated docs for "implemented-views" show the controls as "supported" which is more in line with reality
> feat: Point users to implemented versions of obsolete WUX controls

- doc/articles/platform-specific-xaml.md
Made the headers consistent throughout the page
- Changed the *Examples 1* header to be an h4 (the next level)
- Added a line break after *XAML prefixes in cross-targeted libraries*
Cleaned up the documentation.
Cleaned up the documentation.
> docs: Made the headers consistent throughout the page

- src/Uno.UI.Runtime.Skia.Gtk/UI/Xaml/Controls/TextBoxViewExtension.cs
- Bugfix
Skia GTK multiline input is laggy
Avoiding text changed loop avoids this lag.
> fix: Avoid TextChanged loop in GTK

- build/ci/.azure-devops-commitsar.yml
- src/SourceGenerators/Uno.UI.SourceGenerators/DependencyObject/DependencyObjectGenerator.cs
- Bugfix
Reading DependencyObject.DispatcherQueue from another thread now returns the proper instance.
> fix(winui): Capture the DispatcherQueue on DependencyObject creation

- doc/articles/features/VisibleBoundsPadding.md
- src/Uno.UI.Toolkit/Uno.UI.Toolkit.csproj
- src/Uno.UI/Behaviors/VisibleBoundsPadding.cs
- Bugfix
`VisibileBoundsPadding` depends on the `Bounds` and `VisibleBounds` properties which are not available on WinAppSDK desktop APIs. The implementation now acts as a noop on WinUI 3.
> fix: Disable `VisibleBoundsPadding` on Windows/WinUI3

- src/Uno.UWP/Graphics/Display/DisplayInformation.wasm.cs
GitHub Issue (If applicable): closes #7498
- [Bugfix] 
`TryReadJsFloat` is updated to correctly parse values with decimal places like 1.25
whenever `window.devicePixelRatio` is has decimal places the current parsing via `float.TryParse(WebAssemblyRuntime.InvokeJS(property), out value);` return 0
with the changes from this PR `window.devicePixelRatio` is correctly parsed and values like `1.25` are handled properly
easily testable by setting a different scale factor for the display
> fix: `TryReadJsFloat` updated to support decimal places

- src/Uno.UI/UI/Xaml/Application.cs
- src/Uno.UI/UI/Xaml/ApplicationHelper.cs
Added the ability to reapply application theme to be used when the colors are manually changed in ResourceDictionary, to force the reevaluation of the ApplicationTheme without having to toggle.
> feat(reapply_theme): Added the ability to reapply application theme

- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-winui-net6/UnoWinUIQuickStart.Windows.Desktop/UnoWinUIQuickStart.Windows.Desktop.csproj
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-winui-net6/UnoWinUIQuickStart.Windows.Package/UnoWinUIQuickStart.Windows.Package.wapproj
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-winui/UnoWinUIQuickStart.Windows.Desktop/UnoWinUIQuickStart.Windows.Desktop.csproj
- Bugfix
Bumps WinUI `winui-net6` and `winui` templates to use WinAppSDK 1.0 and latest sdk runtimes.
> fix(net6): Adjust versions for net6-winui templates

- src/SourceGenerators/Uno.UI.SourceGenerators/BindableTypeProviders/BindableTypeProvidersGenerationTask.cs
- Bugfix
Fixes the `The Bindable attribute is missing` message showing up in debug only configuration, reporting that types are not present in the generated bindable metadata.
> fix: Invalid debug-only message

- src/Uno.UI.Runtime.Skia.Gtk/UI/Xaml/Controls/TextBoxViewExtension.cs
- src/Uno.UI.Runtime.Skia.Gtk/UnoDrawingArea.cs
- src/Uno.UI.Runtime.Skia.Wpf/Extensions/UI/Xaml/Controls/TextBoxViewExtension.cs
- src/Uno.UI.Runtime.Skia.Wpf/WpfHost.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/ITextBoxExtension.skia.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.skia.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.skia.cs
GitHub Issue (If applicable): related to #7514
- Bugfix
- Feature
See below
- Previously we were using LayoutChanged and SizeChanged, but that was not completely reliable. Now we do the invalidation before render, which is much more accurate
- To prevent unnecessary operations we short-circuit as soon as possible - only computing when a TextBoxView is actually focused
> feat: Improve Skia TextBoxView overlay positioning and sizing

- src/Directory.Build.targets
- src/Uno.UI.Tests/App/App.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml/Given_Style.cs
- src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml/SetterBase.cs
- src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml/SetterBaseCollection.cs
- src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml/Style.cs
- src/Uno.UI/UI/Xaml/DependencyObjectCollection.cs
- src/Uno.UI/UI/Xaml/Setter.cs
- src/Uno.UI/UI/Xaml/SetterBase.cs
- src/Uno.UI/UI/Xaml/SetterBaseCollection.cs
- src/Uno.UI/UI/Xaml/Style/Style.cs
Closes https://github.com/unoplatform/uno/issues/7577
- Performance
- Applying styles now relies on caching based on the use of `Style.IsSealed` which is set when a style is applied to a Control. 
- Setters enumeration now relies on an arrray instead of a dictionary
- Setters application does not use delegates anymore
> perf(Style): Implement `Style.IsSealed` to allow for flattened lists caching

- src/Uno.UWP/UI/ViewManagement/StatusBar/StatusBar.iOS.cs
GitHub Issue (If applicable): closes #4992 
- Bugfix
iOS is not changing correctly the statusbar color
> fix(iOS): StatusBar Foreground for Dark Theme

- src/SolutionTemplate/UnoSolutionTemplate/Wasm/UnoQuickStart.Wasm.csproj
- Bugfix
Duplicate NuGet reference with different versions.
Not duplicated.
> chore: Remove duplicate PackageReference in template

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/PasswordBoxTests/PasswordBoxTests.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/PasswordBoxTests/PasswordBoxPage.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/PasswordBoxTests/PasswordBoxPage.xaml.cs
- src/Uno.UI.Runtime.Skia.Gtk/UI/Xaml/Controls/TextBoxViewExtension.cs
GitHub Issue (If applicable): closes #7623
**Test wasn't validated locally due to issues with building the solution.**
- Bugfix
- Test
- Foreground doesn't always take effect on Skia, depending on whether we had already created the widget or not.
- No test for the recently fixed bug about PasswordBox shows non-obscured text on Android.
- Set Foreground just after we create the widget.
- Test added
> fix: Fix TextBox/PasswordBox Foreground and add test for obscuring password

- build/uno.winui.targets
- Bugfix
Display the following message when Android 10 SDK or below is used:
```
error : This version of the Android SDK (10.0) is not supported by Uno.UI. You must change the "Compile using Android version:" field in the android project property with at least version 11.0.
```
> ci: Adjust android 10 and below build error

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml/DragAndDropTests/DragDrop_ListViewReorder_Automated.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/DragAndDrop/DragDrop_ListView.xaml
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.DragDrop.cs
- src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.Managed.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.Managed.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.cs
closes https://github.com/unoplatform/nventive-private/issues/326
* Drag and drop support on skia
* Drag and drop in SV
* Ordering items with multi-select in LV
Items are re-ordered using the selection order when multiple items are selected instead of using the current order of items in source list.
We re-order dragged items before applying the reorder.
> fix(dragdrop): Fix reordering items with multi-select in LV

- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Popup/MessageDialog.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Popup/MessageDialog.xaml.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Popups/Given_MessageDialog.cs
- src/Uno.UWP/UI/Popups/MessageDialog.iOS.cs
GitHub Issue (If applicable): closes # https://github.com/unoplatform/nventive-private/issues/324
- Bugfix
Programatically dismissing MessageDialog on iOS causes a native crash
Not crashing
> [iOS] fix programatically dismiss MessageDialog

- src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/7598
- Bugfix
Building with a non-C# target is restored.
> fix: Don't generate reload cookie for non-C# targets

- src/Uno.UI/UI/Xaml/Input/FocusManager.wasm.cs
GitHub Issue (If applicable): closes #7676, closes #7406
- Bugfix
`FocusManager` may be used before the app is initialized, which causes NRE.
Avoiding usage of `FocusManager` before the app is fully initialized.
> fix: Avoid FocusManager usage before WASM app is fully initialized

- src/Uno.UI.RemoteControl/RemoteControlClient.cs
- Bugfix
When on https: only wss: connections are allowed, but we try to perform ws: connections
Uses wss: when https: is used.
> fix: Use wss for RemoteControlClient when on https

- src/Uno.UI/UI/Xaml/Controls/TextBox/SinglelineTextBoxView.iOS.cs
fixes https://github.com/unoplatform/uno/issues/7400
Text is cleared on first key stroke after reveal
When we press the reveal button of a `PasswordBox` we toggle the `SecureTextEntry` flag on the native `UITextField`. Doing this, on next key-stroke the system we clear the current text before inserting the new text.
When we detect a such behavior, we manually restore the text before.
> fix: [iOS] Do not clear text on next key stroke after reveal

- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/CreateFromString.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/Given_XamlReader.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/NonDefaultXamlNamespace.cs
- src/Uno.UI/UI/Xaml/Markup/Reader/XamlObjectBuilder.cs
- src/Uno.UI/UI/Xaml/Markup/Reader/XamlTypeResolver.cs
- src/Uno.UWP/Foundation/Metadata/CreateFromStringAttribute.cs
- src/Uno.UWP/Generated/3.0.0.0/Windows.Foundation.Metadata/CreateFromStringAttribute.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/7536
- Bugfix
- Feature
Not supported.
- When `XamlReader` loads XAML with non-default `xmlns` with "using:" or "clr-namespace:", it can handle it porperly.
- When string value of a property of type annotated with `ConvertFromStringAttribute` is read, it is properly handled in `XamlReader`.
> Support non-default `xmlns` and `ConvertFromStringAttribute` in `XamlReader`

- src/Uno.UI.RuntimeTests/IntegrationTests/dxaml/controls/commandbar/CommandBarIntegrationTests.cs
- src/Uno.UI/UI/Xaml/Controls/AppBar/AppBarToggleButton.Partial.cs
closes 7703
- Bugfix
Setting IsChecked programatically on an AppBarToggleButton does not change its VisualState
Setting IsChecked programatically on an AppBarToggleButton does change its VisualState
> fix: Ensure that AppBarToggleButton's base.OnPropertyChanged is called

- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/WindowTests/Window_ContentIsFullyVisible.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/WindowTests/Window_ContentIsFullyVisible.xaml.cs
- src/Uno.UI.Runtime.Skia.Gtk/GtkHost.cs
GitHub Issue (If applicable): closes #5666 
[ScrollViewer ScrollBar not shown #5666](https://github.com/unoplatform/uno/issues/5666)
which is part of the larger epic
[Skia Rendering Backend Support #4309](https://github.com/unoplatform/uno/issues/4309)
- Bugfix
In Skia.Gtk, the ActualWidth and ActualHeight of the window are set to the width and height values for the Gtk.Window.
When compiled and run on Windows using Gtk for Windows everything appears correct.
On WSL and Linux, likely specific to Wayland-based windowing, the values for the Gtk.Window's width and height includes the window's title bar and other non client area parts that are outside of the drawable area. This causes the Uno MainWindow to report and do layout, etc., using …
> fix: [GTK] Incorrect window ActualWidth and ActualHeight on WSL and Linux

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ItemsControl/ItemsControlTests.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ItemsControl/ItemsControl_AppendItem.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ItemsControl/ItemsControl_AppendItem.xaml.cs
- src/Uno.UI.Tests/Windows_UI_XAML_Controls/ItemsControlTests/Given_ItemsControl.cs
- src/Uno.UI/UI/Xaml/UIElementCollection.iOS.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/nventive-private/issues/319
- Bugfix
Fixes `UIElementCollection` to insert items at a specific location on iOS.
> fix(ItemsControl): [iOS] Invalid native insert sequence in UIElementCollection

- src/SamplesApp/SamplesApp.Droid/SamplesApp.Droid.csproj
- src/SamplesApp/UITests.Shared/Windows_Devices/GeolocatorTests.xaml
- src/SamplesApp/UITests.Shared/Windows_Devices/GeolocatorTests.xaml.cs
related: #2536, #5349
- Feature
Current test checks only GetGeopositionAsync(), without timeout and maximumAge parameters.
Test can check also timeout and maximumAge parameters
This modified test can prove that current implementation of  GetGeopositionAsync(maximumAge, timeout) for Android platform is erroneously (it ignores both parameteras), and maybe this test would be reminder of promise about "fast track" for #2536 (promise given in July 2021).
> feat: more detailed GeoLocator UI test

- doc/articles/get-started.md
docs: update status of Jetbrains Rider development for Android on linux. Keeps in line with changes to master/doc/articles/get-started-rider.md
syncing docs with previous pull request Update get-started-rider.md #7429
documentation update
documentation update
> docs: update get-started.md

- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MenuFlyoutTests/MenuFlyout_DroidAltTab.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/MenuFlyoutTests/MenuFlyout_DroidAltTab.xaml.cs
- src/Uno.UI/UI/Xaml/Controls/Popup/Popup.Android.cs
GitHub Issue (If applicable): closes unoplatform/nventive-private#306
- Bugfix
Once a popup has been initialized (when it is first shown) and you alt-tab out the app and comes back,
this popup can no longer be opened again:
> Java.Lang.RuntimeException: 'Unable to add window -- token null is not valid; is your activity running?'
It should work now.
The `PopupWindow` was previously created using the current instance of AppBarButton as the context provider, 
however that provided context becomes stale once you alt-tab out and back to the app. 
Trying to show a popup on a, now, stale context will not work, hence the error:
> Java.Lang.RuntimeException: 'Unable to add window -- token null …
> fix(popup): not working after alt-tabbing

- src/Uno.UWP/Storage/Pickers/FileOpenPicker.wasm.cs
GitHub Issue (If applicable): Fixes #6487
- Bugfix
Code: 
```C#
var picker = new Windows.Storage.Pickers.FileOpenPicker();
picker.ViewMode = Windows.Storage.Pickers.PickerViewMode.Thumbnail;
picker.SuggestedStartLocation = Windows.Storage.Pickers.PickerLocationId.PicturesLibrary;
picker.FileTypeFilter.Add(".jpg");
picker.FileTypeFilter.Add(".jpeg");
picker.FileTypeFilter.Add(".png");
```
`FileOpenPicker` shows unrelated file types when it encounters a known MIME type, on Chrome and Edge, and unintentionally groups `jpg` and `jpeg` together.
`FileOpenPicker` shows each file type on one line, and another line shows the superset of all file types specified.
> fix: FileOpenPicker should show file extensions similar to UWP

- build/ci/.azure-devops-android-tests.yml
Setting the `AndroidUseLatestPlatformSdk` property is required to avoid issues when Visual Studio removes the property (it assumes that android 12 is latest, and AndroidUseLatestPlatformSdk is not needed as it's already the latest). This property is required to build for Android 12 on macOS.
> ci: Adjust macOS-Android build for Android 12 support

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/NestedHandling_Tests.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Input/PointersTests/NestedHandling.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Input/PointersTests/NestedHandling.xaml.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.wasm.cs
fixes https://github.com/unoplatform/uno/issues/3007
Make sure to never raise pointer entered/exited on parents
When flagged as handled, the enter/exit events are bubbling in managed code. During that process handlers that are registered with the `handledEventsToo` flag are invoked.
On each element, we make sure to mute local event when receiving a a such event.
> fix(pointers): Make sure to never raise pointer entered/exited on parents

- .mergify.yml
Remove deprecated mergify option:
> ci: Remove deprecated strict more for mergify

- doc/articles/controls/TimePicker.md
- src/Uno.UI/FeatureConfiguration.cs
- src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePicker.md
- src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePickerSelector.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerSelector.iOS.cs
GitHub Issue (If applicable): closes #7589 
- Bugfix
As of iOS15, users are unable to update the initial value of the TimePicker
> fix(iOS): Time and Date Picker

- src/SamplesApp/SamplesApp.Skia.WPF/SamplesApp.Skia.WPF.csproj
- src/SolutionTemplate/UnoSolutionTemplate.net6/Skia.WPF.Host/SkiaWpfHost.net6.vstemplate
- src/SolutionTemplate/UnoSolutionTemplate.net6/Skia.WPF.Host/UnoQuickStart.Skia.Wpf.Host.csproj
- src/SolutionTemplate/UnoSolutionTemplate.net6/Skia.WPF.Host/app.manifest
- src/SolutionTemplate/UnoSolutionTemplate.net6/UnoSolutionTemplate.net6.csproj
- src/SolutionTemplate/UnoSolutionTemplate/Skia.WPF.Host/SkiaWpfHost.vstemplate
- src/SolutionTemplate/UnoSolutionTemplate/Skia.WPF.Host/UnoQuickStart.Skia.Wpf.Host.csproj
- src/SolutionTemplate/UnoSolutionTemplate/Skia.WPF.Host/app.manifest
- src/SolutionTemplate/UnoSolutionTemplate/UnoSolutionTemplate.csproj
- src/Uno.UI.Runtime.Skia.Wpf/WpfHost.cs
GitHub Issue (If applicable): closes #7764
- Bugfix
Skia.WPF DPI scaling is not screen-aware.
Skia.WPF DPI scaling is screen aware and can update at runtime.
> feat: Per-monitor DPI scaling on Skia.WPF

- src/Uno.UI/UI/Xaml/Controls/CommandBar/CommandBar.Partial.cs
GitHub Issue (If applicable): closes unoplatform/nventive-private#304
- Bugfix
Changing the app theme will now affect the AppBarButton icon's color if its Foreground has been set to a theme-dependent resource, which previously was not the case on iOS+Android.
note: on android, `FeatureConfiguration.AppBarButton.EnableBitmapIconTint` needs to be set to `true` for `NavigationCommand` use to its icon's Foreground property
> fix(appbarbutton): icon color not changing with app theme

- build/PackageDiffIgnore.xml
- src/SourceGenerators/Uno.UI.SourceGenerators.Tests/Given_PathMarkupParser.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlPathParser/GeneratedStreamGeometryContext.cs
- src/Uno.UI/Media/PathMarkupParser.cs
- src/Uno.UI/Media/PathStreamGeometryContext.cs
- src/Uno.UI/Media/StreamGeometryContext.cs
- src/Uno.UI/UI/Xaml/Media/GeometryHelper.cs
- src/Uno.UI/UI/Xaml/Shapes/Line.iOSmacOS.cs
- src/Uno.UI/UI/Xaml/Shapes/Line.skia.cs
- src/Uno.UI/UI/Xaml/Shapes/Polygon.iOSmacOS.cs
- src/Uno.UI/UI/Xaml/Shapes/Polygon.skia.cs
- src/Uno.UI/UI/Xaml/Shapes/Polyline.iOSmacOS.cs
- src/Uno.UI/UI/Xaml/Shapes/Polyline.skia.cs
fixes #3280 
~~## Bug fix~~
~~* Validate that setting a Transform on shapes is working properly with latest refactor of `Shapes` and `Transform` on iOS~~
~~* The `PathFigure.IsClosed` is now working even when written in C#~~
Complete the `PathFigure.IsClosed` support made by https://github.com/unoplatform/uno/pull/3658
Cf. #3280 
Fixed
> fix(shapes): Fix shapes not closing when written in C#

- src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.Android.cs
Take the ItemsPresenter.MinHeight into account when calculating content extent in all contexts, not just scrolling. This fixes a bug where the scroll would be incorrectly reset by UpdateScrollPositionForPaddingChanges() when ItemsPresenter.MinHeight was set.
- Bugfix
fixes https://github.com/unoplatform/nventive-private/issues/323
> fix(listview): [Android] Fix calculations when ItemsPresenter.MinHeight set

- src/Uno.UI/UI/Xaml/Input/FocusManager.wasm.cs
- src/Uno.UI/UI/Xaml/Internal/RootVisual.cs
GitHub Issue (If applicable): closes #7742 
- Feature
When tabbing from address bar in browser, the root scroll viewer gets focused.
When tabbing from address bar in browser, the first actual focusable element is focused (based on the managed focus rules).
> feat: Initial page focus on WASM using browser keyboard navigation

- src/Uno.UI.Tests/DependencyProperty/Given_DependencyProperty.DefaultValueProvider.cs
- src/Uno.UI.Tests/DependencyProperty/Given_DependencyProperty.cs
- src/Uno.UI/UI/Xaml/Controls/CalendarView/CalendarDatePicker.Properties.cs
- src/Uno.UI/UI/Xaml/Controls/CalendarView/calendardatepicker_partial.cs
- src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePicker.cs
- src/Uno.UI/UI/Xaml/Controls/ToggleSwitch/ToggleSwitch.cs
- src/Uno.UI/UI/Xaml/Controls/ToggleSwitch/ToggleSwitch.mux.cs
- src/Uno.UI/UI/Xaml/DependencyObjectExtensions.cs
- src/Uno.UI/UI/Xaml/DependencyObjectStore.Binder.cs
- src/Uno.UI/UI/Xaml/DependencyPropertyDetailsCollection.cs
- src/Uno.UI/UI/Xaml/UIElement.cs
Uses method override instead of delegate invocation for performance and less allocations during UIElement instanciation.
Note that this change removes internal support for `DependencyObject.GetDefaultValue2`, though this is not used anywhere in Uno at this point. We'll add it back as needed through generated code.
> perf(memory): Remove `RegisterDefaultValueProvider` delegate in favor of `UIElement` cast

- src/SamplesApp/SamplesApp.Shared/App.xaml.cs
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml/FocusManagerDirectionTests/UnoSamples_Tests.FocusManagerDirection.cs
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml/FocusManagerTests/UnoSamples_Tests.FocusManager.cs
- src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/FocusManager/FocusManager_GetFocus_Automated.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_IsTabStop.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_IsTabStop.xaml.cs
- src/Uno.UI/UI/Xaml/Controls/Primitives/SelectorItem.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/MultilineTextBoxDelegate.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/SinglelineTextBoxDelegate.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.Android.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.wasm.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.macOS.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.wasm.cs
- src/Uno.UI/UI/Xaml/Input/FocusManager.wasm.cs
GitHub Issue (If applicable): closes #2115, closes #6471
- Bugfix
- `IsTabStop` had weird behavior for input fields on most platforms
- `AllowFocusOnInteraction` did not work reliably on WASM
- `IsTabStop` is properly respected by input fields
- `AllowFocusOnInteraction = false` properly stops propagation of native focus on WASM
> fix: `IsTabStop` everywhere and `AllowFocusOnInteraction` on WASM

- doc/articles/feature-flags.md
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_AutoSuggestBox.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls_Primitives/Given_Popup.cs
- src/Uno.UI/FeatureConfiguration.cs
- src/Uno.UI/UI/Xaml/Controls/AutoSuggestBox/AutoSuggestBox.cs
- src/Uno.UI/UI/Xaml/Controls/Popup/Popup.cs
GitHub Issue (If applicable): closes #7675
- Bugfix
`AutoSuggestBox` loses focus when its popup opens because `IsLightDismissEnabled` defaults to `true` on Uno instead of `false` as in UWP (and `IsLightDismissEnabled` popups may capture focus when opened)
- `Popup.IsLightDismissEnabled` is now `false` by default to match UWP
- Added `FeatureConfiguration.Popup.EnableLightDismissByDefault` that allows turning the legacy behavior back on where needed
- Added tests to cover the default, and the text change behavior of `AutoSuggestBox`
> fix: `AutoSuggestBox` should keep focus when popup is opened

- src/Uno.UI/UI/Xaml/UIElement.Pointers.Android.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.iOS.cs
Reduce UIElement memory pressure by removing an unnecessary `Lazy<T>` holding `GestureRecognizer`.
> perf(memory): Remove delegate for UIElement GestureRecognizer

- build/ci/.azure-devops-ios-tests.yml
- src/Uno.UI.Runtime.Skia.Gtk/UI/Xaml/Controls/TextBoxViewExtension.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs
GitHub Issue (If applicable): closes #7644, closes #7643, closes #7209
- Bugfix
- Input controls may attempt to add their native controls to UI multiple times in succession, causing critical errors in app log
- Select method causes focus on input fields, which causes issues for `NumberBox`
- Native overlay positioning is not working reliably on GTK
Fixed.
> fix: TextBox positioning and selection on GTK

- src/SourceGenerators/Uno.UI.SourceGenerators/DependencyObject/DependencyObjectGenerator.cs
- src/Uno.Foundation/Uno.Core.Extensions/Uno.Core.Extensions.Disposables/Disposables/ConditionalDisposable.cs
- src/Uno.UI/AssemblyInfo.cs
- src/Uno.UI/UI/Xaml/Controls/DropDownButton/DropDownButton.cs
- src/Uno.UI/UI/Xaml/Controls/Grid/ColumnDefinition.cs
- src/Uno.UI/UI/Xaml/Controls/Grid/RowDefinition.cs
- src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs
- src/Uno.UI/UI/Xaml/DependencyObjectExtensions.cs
- src/Uno.UI/UI/Xaml/DependencyObjectStore.cs
- src/Uno.UI/UI/Xaml/DispatcherConditionalDisposable.cs
- src/Uno.UI/UI/Xaml/IDependencyObjectInternal.cs
- src/Uno.UI/UI/Xaml/StateTriggerBase.cs
- src/Uno.UI/UI/Xaml/UIElement.cs
- src/Uno.UI/UI/Xaml/VisualStateGroup.cs
- Remove indirect delegates created from `ConditionalDisposable`
- Use strong references for property changes registrations to avoid the creation of `ConditionalDisposable` instances
- If `RegisterPropertyChangedCallback` is used and is registered on self, don't use `DispatcherConditionalDisposable`
- Generate `OnPropertyChanged2` for all uno-internal DependencyObject to avoid delegates creation. DependencyObject now invokes this method through `IDependencyObjectInternal`.
> perf(memory): Reduce `ConditionalDisposable` pressure

- build/PackageDiffIgnore.xml
- src/Uno.UI/UI/Xaml/Media/Animation/ITimeline.cs
- src/Uno.UI/UI/Xaml/Media/Animation/ITimelineListener.cs
- src/Uno.UI/UI/Xaml/Media/Animation/Storyboard.cs
- src/Uno.UI/UI/Xaml/Media/Animation/Timeline.cs
Removes the use of events and disposable to reduce the memory footprint when observing timeline events from a storyboard.
> perf(timeline): Remove the use of events and disposables

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml/DragAndDropTests/DragDrop_ListViewReorder_Automated.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/DragAndDrop/DragDrop_ListView_WithPadding.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/DragAndDrop/DragDrop_ListView_WithPadding.xaml.cs
- src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.iOSmacOS.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.DragDrop.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.Stub.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.managed.cs
- src/Uno.UI/UI/Xaml/DragDrop/DropUITarget.cs
- src/Uno.UWP/Extensions/RectExtensions.cs
closes https://github.com/unoplatform/nventive-private/issues/329
Reordering items before or after the bounds of items on the LV has no effect.
* When we leave the bounds of a drop target, we don't reset the `dragUIOverride` object, so the accepted operation (i.e. `None`) is not updated in the `DragView`.
* In a `ListView` when reordering items after the bounds of the last item, the accepted operation remains to `Move` (as expected)  but drop has no effect.
* On pointer move, if we are over a new drop target, or if we are not able to find a drop target, we clear the `dragUIOvwerride`
* If we are not able to find an item under the pointer when reordering items of a `ListView`, we are selecting the last one.
> fix(dragdrop): Reordering item out of LV items bounds

- src/Uno.UI.Runtime.Skia.Gtk/Extensions/Storage/Pickers/FileSavePickerExtension.cs
- src/Uno.UI.Runtime.Skia.Wpf/Extensions/Storage/Pickers/FileSavePickerExtension.cs
GitHub Issue (If applicable): closes #7783
- Bugfix
File is not created when save picker selects a non-existing file.
File is created.
> fix: FileSavePicker should create target file on GTK and WPF

- src/Uno.UI/UI/Xaml/DependencyObjectStore.cs
- src/Uno.UI/UI/Xaml/DispatcherConditionalDisposable.cs
This change:
- Removes the use of delegates when interacting with `DispatcherConditionalDisposable`, which the original version required to deal with `Action` instances.
- Removes the use of Action in `CreateWeakDelegate` in favor a specialized dispose struct
> perf: Reduce memory indirect allocations from the use of `DispatcherConditionalDisposable`

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/ContentDialog_Leak.xaml.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/ItemsControl_ItemsSource_Leak.xaml
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/ItemsControl_ItemsSource_Leak.xaml.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement_And_Leak.cs
- src/Uno.UI/UI/Xaml/Controls/ItemCollection.cs
- src/Uno.UI/UI/Xaml/Controls/ItemsControl/ItemsControl.cs
- Bugfix
`ItemsControl` does not create a strong reference to observable collections when set from `ItemsSource`.
> fix(ItemsControl): Don't hold a strong reference on ItemsSource INCC/VectorChanged

- src/Uno.UI/WasmCSS/Uno.UI.css
GitHub Issue (If applicable): closes #7569
- Bugfix
Mobile browsers add a blue highlight on interactive elements when tapped.
Blue highlight removed.
> fix: Remove blue tap highlight on mobile browsers

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Button.cs
- src/Uno.UI/UI/Xaml/Controls/Control/Control.cs
- src/Uno.UI/UI/Xaml/FrameworkElement.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/nventive-private/issues/309
- Bugfix
Previously when `CanExecute()` on `Command` bound to `ButtonBase` became `false` caused the control to lose focus.
No longer losing focus.
> fix: Suppress `IsEnabled` for focus purposes when `Command.CanExecuteChanged` becomes `false`

- src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props
GitHub Issue (If applicable): #7872 
- Bugfix
Removes unused `AdditionalFiles` inclusion which fails the build following a restriction in Roslyn, where additional files cannot be binary.
This particular change was included most likely as the result of investigation of up-to-date checks, but is not used as part of any   `GeneratorExecutionContext.GetMSBuildItems()` invocation.
> fix: Remove incompatible (and unused) `AdditionalFiles` containing binary files in VS 17.1 Preview 3

- src/Uno.Foundation/Collections/StackVector.cs
- src/Uno.UI/UI/Xaml/Controls/Grid/Grid.cs
GitHub Issue (If applicable): closes #7824
Reduces memory allocations during `Grid`'s measure pass.
> perf: Use `ArrayPool<T>` for `Grid`'s `CellCacheStackVector` inner storage

- doc/articles/uno-development/creating-runtime-tests.md
The documentation regarding the Runtime Tests filter option is not quite clear
Added more details regarding the Runtime Tests filter option
> docs: Add more details regarding the Runtime Tests filter option

- doc/articles/interop/wasm-javascript-3.md
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_UIElement.wasm.cs
- src/Uno.UI/UI/Xaml/HtmlElementHelper.wasm.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.wasm.cs
- src/Uno.UI/UI/Xaml/UIElement.wasm.cs
fixes https://github.com/unoplatform/uno/issues/7848
Regression: [WASM] External components does not allow pointers interaction
Since https://github.com/unoplatform/uno/pull/7571, setting the `Background` on `FrameworkElement` is no longer sufficient for an element to be hit testable. This breaks HTML external components which was (wrongly) relying on this to be hit testable (as stated in doc [here]( https://github.com/unoplatform/uno/blob/f8bd42650d69a41b4360f3e533e21c7e789984ae/doc/articles/interop/wasm-javascript-3.md?plain=1#L105)) and has no other way to enable pointers.
WASM external component are now always considered as hit testable.
```
*******************
* BREAKING CHANGE *
*******************
```
This was actually introduced by https://github.com/unoplatform/uno/pull/7571 …
> fix(reg): Fix wasm external components are not hit testable

- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Utilities/RainbowMeasures.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/UIElementTests/UIElement_MeasurePerf.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/UIElementTests/UIElement_MeasurePerf.xaml.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs
- src/Uno.UI/Extensions/ViewExtensions.netstd.cs
- src/Uno.UI/FeatureConfiguration.cs
- src/Uno.UI/UI/Xaml/Controls/ContentControl/ContentControl.cs
- src/Uno.UI/UI/Xaml/FrameworkPropertyMetadataOptions.cs
- src/Uno.UI/UI/Xaml/UIElement.Android.cs
- src/Uno.UI/UI/Xaml/UIElement.Layout.netstd.cs
- src/Uno.UI/UI/Xaml/UIElement.cs
- src/Uno.UI/UI/Xaml/UIElement.iOS.cs
- src/Uno.UI/UI/Xaml/UIElement.macOS.cs
- src/Uno.UI/UI/Xaml/UIElement.net.cs
- src/Uno.UI/UI/Xaml/UIElement.netstdref.cs
- src/Uno.UI/UI/Xaml/UIElement.skia.cs
- src/Uno.UI/UI/Xaml/UIElement.wasm.cs
- src/Uno.UI/UI/Xaml/Window.skia.cs
- src/Uno.UI/UI/Xaml/Window.wasm.cs
Closes https://github.com/unoplatform/uno/issues/7827
Implementation of "Dirty Measure Path", inspired from the WinUI's way of doing layout.
The method `.MeasureOverride()` on elements is called only when required. Any of the 2 following conditions will call it:
1. The `availableSize` is different from the previous measure phase
2. The `.InvalidateMeasure()` has been called explicitly on this element.
> [WASM/Skia] Ensure the .MeasureOverride() in only called when required

- src/SourceGenerators/Uno.UI.SourceGenerators/BindableTypeProviders/BindableTypeProvidersGenerationTask.cs
- Bugfix
Don't warn on `VirtualizingPanelLayout` in debug `BindableTypeProvider` as it is abstract.
> fix: Don't warn on abstract members in generated Bindable Type Providers

- src/Uno.UI/WasmScripts/Uno.UI.js
- src/Uno.UI/ts/Windows/Storage/Streams/NativeFileWriteStream.ts
GitHub Issue (If applicable): closes #7935
- Bugfix
> fix: Disposing WASM stream twice should not fail

- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Canvas/Grid_ZIndex.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Canvas/Grid_ZIndex.xaml.cs
- src/Uno.UI.Composition/Composition/Compositor.skia.cs
- src/Uno.UI.Composition/Composition/ContainerVisual.skia.cs
- src/Uno.UI.Composition/Composition/Visual.skia.cs
- src/Uno.UI.Composition/Composition/VisualCollection.cs
- src/Uno.UI/UI/Xaml/Controls/Canvas/Canvas.skia.cs
- src/Uno.UI/UI/Xaml/UIElement.skia.cs
GitHub Issue (If applicable): closes #5644, part of #325
- Feature
Not supported.
`Canvas.ZIndex` is supported and applied irrespective of parent panel
> feat: Support for `Canvas.ZIndex` on Skia

- src/Uno.UI/WasmScripts/Uno.UI.d.ts
- src/Uno.UI/WasmScripts/Uno.UI.js
- src/Uno.UI/ts/Windows/Storage/StorageFolder.ts
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/7725
- Bugfix
Removed `FS.syncfs operations in flight at once` warning by having only one synchronization operation at once.
> fix(wasm): Avoid multiple FS.syncfs causing emscripten warning

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Input/Given_FocusManager.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Input/TestPages/FocusNavigationPage.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Input/TestPages/TwoButtonFirstPage.xaml
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Input/TestPages/TwoButtonFirstPage.xaml.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Input/TestPages/TwoButtonSecondPage.xaml
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Input/TestPages/TwoButtonSecondPage.xaml.cs
- src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.csproj
- src/Uno.UI/UI/Xaml/Controls/Frame/Frame.cs
- src/Uno.UI/UI/Xaml/Controls/Page/Page.cs
- src/Uno.UI/UI/Xaml/Controls/Page/Page.mux.cs
- src/Uno.UI/UI/Xaml/UIElement.cs
- src/Uno.UI/UI/Xaml/UIElement.mux.cs
- src/Uno.UI/WasmScripts/Uno.UI.js
GitHub Issue (If applicable): closes https://github.com/unoplatform/nventive-private/issues/313, partially #7900
- Bugfix
-  In some cases focus can stay on page which is being navigated from.
- When navigating, focus may move frantically from element to element as they are being unloaded.
When page is navigated away, focus will move away from it directly to some outer element or `null`. When the next page is navigated to, the focus will in case of `null` move to this new page.
> fix: Move focus from page which is navigated away in `Frame`

- src/Uno.Foundation/Uno.Core.Extensions/Uno.Core.Extensions.Compatibility/Reflection/DefaultReflectionExtensions.cs
- src/Uno.Foundation/Uno.Core.Extensions/Uno.Core.Extensions.Compatibility/Reflection/FieldDescriptor.cs
- Bugfix
Fixes invalid configuration for fields reflection: 
```
Failed to apply binding to property [DependencyPropertyDetails(TextAlignment)] on [Windows.UI.Xaml.Controls.TextBlock] (Not Supported)
dotnet.js:2310 System.ArgumentException: Not Supported
dotnet.js:2310    at Uno.Reflection.DefaultReflectionExtensions.GetDescriptor(MemberInfo mi) in C:\a\1\s\src\Uno.Foundation\Uno.Core.Extensions\Uno.Core.Extensions.Compatibility\Reflection\DefaultReflectionExtensions.cs:line 198
```
> fix(reg): Restore reflection extension support for fields

- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/XamlRoot/XamlRoot_Properties.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/XamlRoot/XamlRoot_Properties.xaml.cs
- src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml/XamlRoot.cs
- src/Uno.UI/UI/Xaml/XamlRoot.cs
GitHub Issue (If applicable): closes #7944
- Bugfix
Adds support for `XamlRoot.RasterizationScale`
> feat: Add support for `XamlRoot.RasterizationScale`

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Shapes/Shapes_Tests.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/Shape_StrokeTest.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/Shape_StrokeTest.xaml.cs
- src/Uno.UI/UI/Xaml/Shapes/Shape.cs
GitHub Issue (If applicable): closes #7097
- Bugfix
`Shape.Stroke` update not triggering re-render of the `Shape`.
`Shape.Stroke` update will cause the `Shape` to re-render.
re: unoplatform/private#239
> fix(shape): Stroke update not triggering re-render

- src/SamplesApp/Benchmarks.Shared/Benchmarks.Shared.projitems
- src/SamplesApp/Benchmarks.Shared/Suite/Windows_UI/ColorBench/XamlControlsResourcesCreationBenchmark.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI/Given_Color.cs
- src/Uno.UWP/UI/Color.cs
Use field aliasing for improved color performance for GetHashCode and Equals.
> perf: Use field aliasing to improve Color.GetHashCode and Color.Equals

- src/Uno.UI.BindingHelper.Android/Uno/UI/UnoViewGroup.java
- src/Uno.UI/UI/Xaml/Controls/Layouter/Layouter.Android.cs
Reduces android interop calls by moving some Measure-specific code to java.
> perf: Reduce interop invocations during MeasureChildOverride

- src/SolutionTemplate/UnoSolutionTemplate.net6/Mobile/Android/AndroidManifest.xml
- Bugfix
Fixes the following warning:
```
warning XA4211: AndroidManifest.xml //uses-sdk/@android:targetSdkVersion '30' is less than $(TargetFrameworkVersion) ''. Using API-31 for ACW compilation.
```
> fix(net6): Bump current android version in template

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/TestsResources.xaml
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.Android.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.wasm.cs
GitHub Issue (If applicable): closes #7791 
- Bugfix
Changing the `IsEnabled` property is not refreshing the VisualState
> fix(wasm): Textbox VisualState udpate

- doc/articles/get-started-vscode.md
Added mention of GTK requirement for Windows
Getting started did not work correctly on Windows
Link to prerequirement of GTK
~~Not yet, I think I can't change the github UI, I will check it out on my machine and make a chang it ther when there is a general OK for this request.~~ Updated commit message
If the docs should not contain platform specific conditions, skia-gtk could be removed instead to make it cleaner. It may also reduce the barrier for people just want to try it out. Disclamer I personally did not installed GTK, since there is a high chance it will never leave the system again.
If platform specific conditions would be ok, Instead for …
> docs: Mention requirement for gtk under Windows in getting started

- src/SamplesApp/SamplesApp.UITests/Extensions/AppRectExtensions.cs
- src/SamplesApp/SamplesApp.UITests/Extensions/AppScalingExtensions.cs
- src/SamplesApp/SamplesApp.UITests/Extensions/QueryExtensions.cs
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/SwipeControlTests/SwipeControlTests.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/DragAndDrop/DragDrop_ListViewMultiSelect.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/DragAndDrop/DragDrop_ListViewMultiSelect.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/SwipeControlTests/SwipeControl_ListView.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/SwipeControlTests/SwipeControl_ListView.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/SwipeControlTests/SwipeControl_ScrollViewer.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/SwipeControlTests/SwipeControl_ScrollViewer.xaml.cs
- src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/NativeScrollContentPresenter.Android.cs
- src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.cs
closes https://github.com/unoplatform/uno.extensions/issues/204
Support of `SwipeControl` nested in scrollable container (`ScrollViewer` or native `ListView`)
When using native scroll bars, the `ScrollViewer` might report that it's can scroll horizontally. This drives our pointers engine on Android [to detect a conflicting gesture](https://github.com/unoplatform/uno/blob/f4ca959678fbea27e9ac810addeac851c00ffeb8/src/Uno.UI/UI/Xaml/UIElement.Pointers.Android.cs#L183) between the `SwipeControl` and `ScrollViewer` so it prevent the `ScrollViewer` to kick in **on any direction** (currently we cannot prevent scroll to start only on a given direction).
The `ScrollViewer` report `CanHorizontallyScroll = false`
> fix: support of SwipeControl nested in scrollable container

- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.macOS.cs
- Feature
`SelectedRange` on TextBox.macOS is not implemented.
> feat(macOS): Add SelectedRange on TextBox

- src/SolutionTemplate/UnoSolutionTemplate.net6/Mobile/MacCatalyst/Info.plist
- src/SolutionTemplate/UnoSolutionTemplate.net6/Mobile/UnoQuickStart.Mobile.csproj
- src/SolutionTemplate/UnoSolutionTemplate.net6/Mobile/macOS/Info.plist
- Bugfix
Adjust base versions running net6 mobile templates on macOS/Catalyst.
> fix: Adjust macOS and Catalyst versions

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TextBoxTests/TextBoxTests.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_Binding_Null.xaml
GitHub Issue (If applicable): closes #8015
- Bugfix
The TextBox_No_Text_Entered test is failing on iOS due to the fact that the text input in the text field by the test was not a real word which made the system show a autocorrect popup above the text field, which appeared right on top of the button the test was trying to tap :-)
Not failing anymore.
> fix: `TextBox_No_Text_Entered` test failing on iOS 15

- src/SamplesApp/SamplesApp.UITests/TestFramework/AutoRetry.cs
- Test
This changes removes `IWrapSetUpTearDown` from `AutoRetryAttribute` in order to remove the useless retries added (6 total) because of the wrapping of setup and teardown methods. The test method itself already can retry on setup/teardown failures.
> test: Don't wrap setup and teardown on UI tests auto retry

- src/Uno.UI.Tests/DependencyProperty/Given_DependencyProperty.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/xBind_NullableRecordStruct.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/xBind_NullableRecordStruct.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Given_xBind_Binding.cs
- src/Uno.UI/DataBinding/BindingPropertyHelper.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/7486
- Bugfix
x:Bind and Binding to a nullable struct is now supported.
> fix(xBind): Fix support for nullable struct binding

- doc/articles/features/focus-management.md
GitHub Issue (If applicable): closes #7185
No docs
Docs!
> docs: IsTabStop on Page to disable initial focus

- build/ci/templates/dotnet6-install-mac.yml
- build/ci/templates/dotnet6-install-windows.yml
- doc/articles/get-started-dotnet-new.md
- doc/articles/get-started-vs-2022.md
- src/AddIns/Uno.UI.MSAL/AcquireTokenInteractiveParameterBuilderExtensions.cs
- src/SolutionTemplate/UnoSolutionTemplate.net6/Mobile/iOS/Info.plist
- src/Uno.UI/Extensions/Matrix3x2Extensions.iOSmacOS.cs
- src/Uno.UI/Services/ResourceService.iOSmacOS.cs
- src/Uno.UI/UI/Xaml/Application.macOS.cs
- src/Uno.UI/UI/Xaml/Controls/MenuFlyout/MenuFlyout.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.macOS.cs
- src/Uno.UI/UI/Xaml/Media/Animation/Animators/GPUFloatValueAnimator.iOSmacOS.cs
- src/Uno.UI/UI/Xaml/Media/ImageSource.macOS.cs
- src/Uno.UWP/ApplicationModel/Contacts/ContactPicker.iOS.cs
- src/Uno.UWP/Security/Authentication/Web/WebAuthenticationBrokerProvider.iOSmacOS.cs
**BREAKING CHANGE:** This update contains binary breaking changes to follow .NET 6 Mobile iOS/macOS/Catalyst API changes. It requires Visual Studio 2022 17.2 Preview 1 or later and cannot work on previous VS 2022 releases.
> feat!: Bump to net6 preview 13.2, VS 2022 17.2 Preview 1

- src/Uno.UI/ts/Windows/Storage/StorageFolder.ts
GitHub Issue (If applicable): closes #8157
- Bugfix
Initialization of the IDBFS provider is populating from the persisted `IndexedDB`. Caused by https://github.com/unoplatform/uno/pull/7876.
> fix(storage): [wasm] Fix invalid IBFS initialization

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/Uno.UI.Tests/Windows_UI_Xaml/Controls/When_NameScope.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml/Controls/When_NameScope.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml/Controls/When_NameScope_DataTemplate.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml/Controls/When_NameScope_DataTemplate.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml/Controls/When_NameScope_Inner.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml/Controls/When_NameScope_Inner.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml/Given_Namescope.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/BindingTests/Controls/Binding_ElementName_In_Template_ItemsControl_Nested.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/BindingTests/Controls/Binding_ElementName_In_Template_ItemsControl_Nested.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/BindingTests/Controls/Binding_ElementName_In_Template_ItemsControl_Nested_Outer.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/BindingTests/Controls/Binding_ElementName_In_Template_ItemsControl_Nested_Outer.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/BindingTests/Given_Binding.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/8077
- Bugfix
Namespace should not be overriden for template root elements if one already exists.
> fix(NameScope): Ensure NameScope is not overriden for XAML backed controls

- src/Uno.UI/Controls/CommandBar/CommandBarRenderer.iOS.cs
closes https://github.com/unoplatform/nventive-private/issues/351
- Bugfix
> fix(CommandBar): Remove 1px "shadow" from iOS native CommandBar

- src/Uno.UI.Tests/DependencyProperty/Given_DependencyObject.cs
- src/Uno.UI/UI/Xaml/DependencyObjectStore.cs
GitHub Issue (If applicable): closes #8165
- Bugfix
- Break layout cycles for inherited `DependencyProperty` propagation with a maximum depth
- Exit ancestor search loop when the ancestor is found
> fix(DependencyObject): Fix possible infinite loop on ancestor lookup

- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/TreeView/TreeViewBasics.xaml
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/TreeView/TreeViewBasics.xaml.cs
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/TreeView/TreeView_ItemInvoked.xaml
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/TreeView/TreeView_ItemInvoked.xaml.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/Uno.UI/UI/Xaml/Controls/Primitives/SelectorItem.cs
- src/Uno.UI/UI/Xaml/UIElement.PointerCapture.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.cs
GitHub Issue (If applicable): closes #8030
- Bugfix
Clicking expand chevron on `TreeView` item invokes item
- ✅ Clicking chevron no longer invokes item
- ⛔ Items cannot be invoked at all 👀
> `TreeView` expand chevron should not invoke item

- src/Uno.UI/UI/Xaml/UIElement.macOS.cs
GitHub Issue (If applicable): closes #7312
- Bugfix
Since #6645, macOS started [respecting](https://github.com/unoplatform/uno/blob/f56230cea1e55d5c4f723b845e835f69d8535997/src/Uno.UI/UI/Xaml/UIElement.Pointers.cs#L220-L222) the `HitTestVisibility` property. However, unlike the other two platforms with managed pointers that are respecting this property (Skia and Wasm), macOS does not make the required calls to `UpdateHitTest` in relevant events.
This obstructs the propagation of `HitTestVisibilityProperty`, causing issues such as #7312.
macOS now calls `UpdateHitTest` three places: Constructor, `OnIsHitTestVisibleChangedPartial`, and `OnVisibilityChangedPartial`, similar to Skia and Wasm.
Please check if your PR fulfills the following …
> fix(macOS): UpdateHitTest in some events.

- src/Uno.UI.Runtime.Skia.Wpf/Uno.UI.Runtime.Skia.Wpf.csproj
GitHub Issue (If applicable): closes #6842
- Bugfix
`WpfHost` `xaml` styles are not included in .NET Framework assemblies.
.NET Framework support seemed to have much less attention from Uno Platform maintainers long ago, since .NET Core 3.1 support [was added](https://github.com/unoplatform/uno/commit/e2d4eb209a5dece76eed28b0c01e8956ffe9f403). [At that time](https://github.com/unoplatform/uno/tree/4f02e17310a2af1d18bd7707aaa7ad4d00d6e60d/src/Uno.UI.Runtime.Skia.Wpf), there weren't much support for WPF, and no `xaml` files were used, and directly referencing WPF assemblies seemed enough for .NET Framework.
Way after .NET core support was the `TextBox` support, but at that time, nobody seemed to spare any thought for .NET Framework anymore, and …
> fix(WPF): Also use WPF for net47

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml/FocusManagerTests/UnoSamples_Tests.FocusManager.cs
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ListViewTests/UnoSamples_Tests.ListView.cs
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/VisualState_Tests.cs
- src/Uno.UI.Runtime.Skia.Tizen/TizenCoreWindowExtension.cs
- src/Uno.UI.Runtime.Skia.Wpf/WpfCoreWindowExtension.cs
- src/Uno.UI/Controls/Window.macOS.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs
- src/Uno.UI/UI/Xaml/Input/ManipulationCompletedRoutedEventArgs.cs
- src/Uno.UI/UI/Xaml/Input/ManipulationDeltaRoutedEventArgs.cs
- src/Uno.UI/UI/Xaml/Input/ManipulationInertiaStartingRoutedEventArgs.cs
- src/Uno.UI/UI/Xaml/Input/ManipulationStartedRoutedEventArgs.cs
- src/Uno.UI/UI/Xaml/Input/ManipulationStartingRoutedEventArgs.cs
- src/Uno.UI/UI/Xaml/Input/PointerRoutedEventArgs.Android.cs
- src/Uno.UI/UI/Xaml/Input/PointerRoutedEventArgs.iOS.cs
- src/Uno.UI/UI/Xaml/Internal/RootVisual.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.Android.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.iOS.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.wasm.cs
- src/Uno.UWP/UI/Input/PointerPointPropertiesExtensions.cs
fixes https://github.com/unoplatform/uno/issues/7820
fixes https://github.com/unoplatform/uno/issues/8011
We need to double click to remove focus on an element that modifies its visual tree on pointer release
When a `ComboxBoxItem` gets a `PointerRelease` it closes the drop down synchronously, which stop bubbling of the event. This drives the `RootVisual` to not receive it and believe that pointer is still pressed (internal state of the pointers handling of `UIElement` --which is still an issue-- **and** private local flag maintained of the `RootVisual` itself). We then need to double tap to reset that invalid state.
We no longer maintain a local private flag in the `RootVisual` but we are instead using the `PointerUpdateKind` to remove focus. Doing this we have only one state to clear so …
> fix(pointers): Make sure to set the UpdateKind on all platforms and use it handle focus

- doc/articles/splash-screen.md
- src/SamplesApp/SamplesApp.Wasm/WasmScripts/AppManifest.js
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.Wasm/WasmScripts/AppManifest.js
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/xamarinforms-wasm/UnoXFQuickStart.Wasm/WasmScripts/AppManifest.js
- src/SolutionTemplate/UnoSolutionTemplate.net6/Wasm/WasmScripts/AppManifest.js
- src/SolutionTemplate/UnoSolutionTemplate/Wasm/WasmScripts/AppManifest.js
GitHub Issue (If applicable): related to #8096
- Feature
Splash screens are white by default.
- Splash screens are dark or light based on system theme by default.
- Docs added for theme-aware splash screens.
> [WASM] Use theme-aware splash screens by default

- src/Uno.UI.Tests/Windows_UI_Xaml/Given_FrameworkTemplate.cs
- src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.cs
GitHub Issue (If applicable): closes unoplatform/nventive-private#352
- Bugfix
Recycled items would sometimes not have its template applied, and use the placeholder ImplicitTextBlock as template.
Template should be correctly applied to recycled items.
> fix(templatepool): template not being applied on recycled item

- src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestEngineConfig.cs
- src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.cs
- src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.xaml
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_NativeFrame.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ScrollViewer.cs
GitHub Issue (If applicable): closes #8182
- Bugfix
`UnitTestsControl` crashes on UWP
`UnitTestsControl` does not crash on UWP
> fix: `UnitTestsControl` crashes on UWP

- src/Uno.UI.Tests/Windows_UI_Input/Given_GestureRecognizer.cs
- src/Uno.UWP/UI/Input/GestureRecognizer.Manipulation.cs
fixes https://github.com/unoplatform/nventive-private/issues/353
Fix gesture recognizer not completing drag manipulations internally.
When the pointer is release the Drag & Drop is completed, but the internal state of the `GestureRecognizer` is not cleaned. This prevent the dragged element to be drag a second time / forces user to tap element before being able to re-drag it.
We make sure to properly clean the internal state of the `GestureRecognizer` on pointer up.
> fix(pointers): Fix gesture recognizer not completing drag manipulations internally.

- src/Uno.UI/UI/Xaml/Controls/ComboBox/ComboBox.cs
- src/Uno.UI/UI/Xaml/Controls/ComboBox/ComboBoxItem.cs
GitHub Issue (If applicable): closes #7759
- Feature
`ComboBox` does not support key events
Basic support for key navigation on `ComboBox` - Enter, Space and Escape
> feat: Support Enter, Space, Escape and Up/Down on `ComboBox`

- src/Uno.UI.Tests/Windows_UI_XAML_Controls/ItemsControlTests/Given_ItemsControl.cs
- src/Uno.UI/UI/Xaml/Controls/ItemsControl/ItemsControl.cs
fixes https://github.com/unoplatform/uno/issues/8203
Internal indexes were not properly reassigned after an operation (Add/Delete) on the ItemsSource.
> ItemsControls: Fixed internal assignment of indexes to generated containers

- src/SolutionTemplate/UnoSolutionTemplate.net6/Shared/App.xaml
- src/SolutionTemplate/UnoSolutionTemplate/Shared/App.xaml
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/pull/8223
Default `App.xaml` template is misleading for new developers.
Improved documentation, wrapping `XamlControlsResources` in `MergedDictionaries`
> refactor: Improve default App.xaml template

- src/Uno.ReferenceImplComparer/Program.cs
- src/Uno.UI-Tools.slnf
GitHub Issue (If applicable): closes #8219
Error output is not written in DevOps
Output is written in DevOps (I hope!)
> refactor: Write `ReferenceImplComparer` error messages to Error output

- src/Uno.UI/FeatureConfiguration.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.Android.cs
closes https://github.com/unoplatform/nventive-private/issues/328
`ListView` flicker when we re-order items in few projects.
When we re-order item, we request a `RecycleLayout` in order to fully redraw the `ListView`, but if the feature flag `NativeListViewBase.RemoveItemAnimator` has been turn to `false` (default is `true`) then the native animator will animate exit and re-entrance of items in the view, driving to a flicker of the whole `ListView`.
Since https://github.com/unoplatform/uno/pull/8227 it seems that we can only `RequestLayout` (instead of **recycle**) which properly re-draw the whole list.
If this causes an issue, a feature flag `NativeListViewBase.ForceRecycleOnDrop` (default to `false`) has been added on Android to restore the previous behavior on drop (i.e. …
> fix(listview): Fix flickering when reordering items on Android

- build/uno.winui.single-project.targets
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/8252
- Bugfix
Assets located in the shared project `Assets` folder are not included in the android package for net6 mobile projects.
`Assets` folder located at the root are now automatically included in net6.0-android target. Tests are included in the existig runtime tests, which are not yet enabled until net6 gets stabilized.
> fix: Adjust `MonoAndroidAssetsPrefix` to use Assets from shared project

- build/ci/.azure-devops-android-tests.yml
- build/test-scripts/android-uitest-run.sh
- build/test-scripts/android-uitest-wait-systemui.sh
Reverts unoplatform/uno#8168
```
[Waiting for device to boot] timeout 500 sec
/Users/runner/work/1/s/build/test-scripts/android-uitest-wait-systemui.sh: line 18: timeout: command not found
Attempt 1 failed! Waiting 1 seconds...
/Users/runner/work/1/s/build/test-scripts/android-uitest-wait-systemui.sh: line 18: timeout: command not found
Attempt 2 failed! Waiting 2 seconds...
/Users/runner/work/1/s/build/test-scripts/android-uitest-wait-systemui.sh: line 18: timeout: command not found
Last attempt 3 failed, exiting.
```
> Revert "test: Android Emulator wait boot timeout"

- src/Uno.UI/Microsoft/UI/Xaml/Controls/TreeView/TreeViewItem.Properties.cs
GitHub Issue (If applicable): closes #7757
- Bugfix
`TreeView` item glyph size is larger than in WinUI and overflows.
Matches WinUI
> fix: Decrease default `TreeViewItem` glyph size

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TextBlockTests/TextBlockTests.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ContentDialogTests/ContentDialog_TextBox.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/TextBlock_RelativeTextSize.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/TextBlock_RelativeTextSize.xaml.cs
- src/Uno.UI/Controls/NSFontHelper.macOS.cs
- src/Uno.UI/Controls/NSStringAttributesHelper.macOS.cs
- src/Uno.UI/FeatureConfiguration.cs
- src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.macOS.cs
Fixes https://github.com/unoplatform/Uno.Gallery/issues/159
Related to https://github.com/unoplatform/uno/issues/4740
Fixes #5934
Text size on MacOS were too small, relatively to the logical resolution in the app.
A configureable ratio of `1.5` has been found to be required for font to appear correctly on this platform.
> Fix text size on MacOS

- src/Uno.UI/UI/Xaml/Window.iOS.cs
Relates to #7554
- Bugfix
White background appears while rotating:
> fix: Set iOS Window background to Clear instead of White

- src/Uno.UI/Microsoft/UI/Xaml/Controls/NavigationView/NavigationView.cs
GitHub Issue (If applicable): closes #5704
- Bugfix
Selection indicator for `NavigationView` is not behaving correctly for some scenarios.
Selection indicator behaving correctly.
> fix: `NavigationView` selection indicator reliability improvements

- src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/ColorPicker.cs
- src/Uno.UI/UI/Xaml/Controls/Unsupported/ColorPicker.cs
- src/Uno.WinUIRevert/Program.cs
GitHub Issue (If applicable): closes #8305
- Bugfix
WUX `ColorPicker` is normally usable
WUX `ColorPicker` throws and notifies user to use MUX `ColorPicker`.
> fix: Point users to MUX version of ColorPicker

- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_SelectedText.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_SelectedText.xaml.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.cs
- src/Uno.UI.Tests/Windows_UI_XAML_Controls/TextBoxTests/Given_TextBox.cs
- src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/TextBox.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs
GitHub Issue (If applicable): closes #7588 
- Feature
Feature SelectedText doesn't exist.
Added support to feature SelectedText
Gets or sets the content of the current selection in the text box.
> feat: Implemented feature SelectedText on TextBox

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/Manipulation_Tests.cs
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/VisualState_Tests.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Input/GestureRecognizerTests/Manipulation_Basics.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Input/GestureRecognizerTests/Manipulation_Basics.xaml.cs
- src/Uno.UI/UI/Xaml/Controls/Primitives/SelectorItem.cs
- src/Uno.UI/UI/Xaml/Controls/Primitives/VisualStatesHelper.h.mux.cs
- src/Uno.UI/UI/Xaml/Input/PointerRoutedEventArgs.wasm.cs
- src/Uno.UI/UI/Xaml/Internal/RootVisual.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.wasm.cs
- src/Uno.UI/WasmCSS/Uno.UI.css
- src/Uno.UI/WasmScripts/Uno.UI.d.ts
- src/Uno.UI/WasmScripts/Uno.UI.js
- src/Uno.UI/ts/Windows/Devices/Input/PointerDeviceType.ts
- src/Uno.UI/ts/Windows/UI/Xaml/UIElement.Pointers.ts
- src/Uno.UI/tsBindings/Windows_UI_Xaml_NativePointerEventArgs.ts
- src/Uno.UWP/Devices/Input/PointerDeviceType.cs
- src/Uno.UWP/UI/Input/GestureRecognizer.Gesture.cs
- src/Uno.UWP/UI/Input/PointerPointProperties.cs
closes https://github.com/unoplatform/uno/issues/2905
closes https://github.com/unoplatform/uno/issues/8073
closes https://github.com/unoplatform/nventive-private/issues/350
Multiple fixed regarding pointerExit
* Make sure to always raise and bubble exit if pointer is leaving the detection range (touch and pen)
* Manually track element bounds crossing while pointer is captured (mouse) or even just pressed (touch and pen) and raise enter/exit accordingly
* Prevent browser from stealing touch and pen after few moves for its internal gesture recognition
General fix regarding pointer captures:
* Fix possible enumeration of a modified collection
`pointerout` is not raised as expected by the browser or filtered out on some invalid criteria, resulting in the `Pointer<Entered|Exited>` not being …
> Misc pointer fixes for wasm

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Image.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ImageSource.cs
- src/Uno.UI/UI/Xaml/Media/ImageSource.iOS.cs
- src/Uno.UI/UI/Xaml/Media/ImageSource.macOS.cs
GitHub Issue: closes #8133 
What kind of change does this PR introduce? 
- Bugfix  
BitmapImage needs an escaped string when loading from URL, on macOS and iOS. 
BitmapImage (ImageSource) class now works with any string that is passed to the constructor. Like other platforms do. 
> fix: [iOS][macOS] fixed BitmapImage needs encoding when loading from url

- src/Uno.UI/UI/Xaml/FrameworkElement.iOS.cs
- src/Uno.UI/UI/Xaml/IFrameworkElementImplementation.iOS.tt
- src/Uno.UI/UI/Xaml/ILayouterElement.cs
- src/Uno.UI/UI/Xaml/ILayouterElement.iOSmacOS.cs
- src/Uno.UI/UI/Xaml/UIElement.Layout.netstd.cs
Fixes https://github.com/unoplatform/nventive-private/issues/367
Fixes https://github.com/unoplatform/nventive-private/issues/368
Fixed a regression on iOS caused by a refactoring done while implementing the Measure Dirty Path feature on Android.
Was unable to reproduce the problem using an automated test, but this contains the fix.
> [iOS] Fixed a regression caused by Measure Dirty Path

- doc/articles/feature-flags.md
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Popups/Given_MessageDialog.cs
- src/Uno.UI/UI/Xaml/Application.cs
- src/Uno.UI/UI/Xaml/Controls/ContentDialog/ContentDialog.cs
- src/Uno.UI/UI/Xaml/Media/VisualTreeHelper.cs
- src/Uno.UI/Uno.UI.Skia.csproj
- src/Uno.UI/WinRT/Extensions/UI/Popups/MessageDialogContentDialog.cs
- src/Uno.UI/WinRT/Extensions/UI/Popups/MessageDialogExtension.cs
- src/Uno.UWP/Generated/3.0.0.0/Windows.UI.Popups/MessageDialog.cs
- src/Uno.UWP/UI/Popups/IUICommand.cs
- src/Uno.UWP/UI/Popups/Internal/IMessageDialogExtension.cs
- src/Uno.UWP/UI/Popups/MessageDialog.Android.cs
- src/Uno.UWP/UI/Popups/MessageDialog.cs
- src/Uno.UWP/UI/Popups/MessageDialog.iOS.cs
- src/Uno.UWP/UI/Popups/MessageDialog.macOS.cs
- src/Uno.UWP/UI/Popups/MessageDialog.wasm.cs
- src/Uno.UWP/UI/Popups/MessageDialogOptions.cs
- src/Uno.UWP/UI/Popups/UICommand.cs
- src/Uno.UWP/UI/Popups/UICommandSeparator.cs
- src/Uno.UWP/WinRTFeatureConfiguration.MessageDialog.cs
GitHub Issue (If applicable): closes #4810
- Feature
- `MessageDialog` looks different on each platform
- `MessageDialog` is not supported on Skia targets
- `MessageDialog` by default displays using `ContentDialog` provided by Uno.UI.
- Feature flag `WinRTFeatureConfiguration.MessageDialog.UseNativeDialog` was added to make it possible to show the native OS dialog instead
> feat: `ContentDialog`-based `MessageDialog`

- doc/articles/features/using-skia-gtk.md
- doc/articles/toc.yml
- src/SamplesApp/SamplesApp.Skia.Gtk/Properties/launchSettings.json
- src/Uno.UI.Composition/Composition/CompositionShape.skia.cs
- src/Uno.UI.Composition/Composition/CompositionSpriteShape.skia.cs
- src/Uno.UI.Composition/Composition/Compositor.skia.cs
- src/Uno.UI.Composition/Composition/ShapeVisual.skia.cs
- src/Uno.UI.Composition/Composition/SpriteVisual.skia.cs
- src/Uno.UI.Composition/Composition/Visual.skia.cs
- src/Uno.UI.Runtime.Skia.Gtk/GLRenderSurface.cs
- src/Uno.UI.Runtime.Skia.Gtk/GtkHost.cs
- src/Uno.UI.Runtime.Skia.Gtk/IRenderSurface.cs
- src/Uno.UI.Runtime.Skia.Gtk/RenderSurfaceType.cs
- src/Uno.UI.Runtime.Skia.Gtk/SoftwareRenderSurface.cs
- src/Uno.UI.Runtime.Skia.Gtk/Uno.UI.Runtime.Skia.Gtk.csproj
- src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/Renderer.cs
- src/Uno.UI.Runtime.Skia.Tizen/UnoCanvas.cs
- src/Uno.UI.Runtime.Skia.Wpf/WpfHost.cs
- src/Uno.UI/UI/Xaml/Controls/TextBlock/TextVisual.skia.cs
GitHub Issue (If applicable): #4309
- Feature
Adds support for hardware acceleration for Gtk heads on Linux and Windows. 
Note: macOS is not working properly yet for some unknown Gtk+3 issue where the drawn surface is incorrectly scaled on window resize.
> feat(gtk): Add OpenGL acceleration

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/BorderTests/Border_Tests.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/BorderTests/BorderAntiAlias.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/BorderTests/BorderAntiAlias.xaml.cs
- src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.Android.cs
- src/Uno.UI/UI/Xaml/Media/AcrylicBrush/Android/AcrylicBrush.Android.cs
- src/Uno.UI/UI/Xaml/Media/Brush.Android.cs
closes https://github.com/unoplatform/uno/issues/8324
- Bugfix
> fix: Avoid disabling Paint AntiAlias when drawing rounded corners

- build/ci/.azure-devops-ios-tests.yml
- src/Uno.UI.FluentTheme.v2/themeresources_v2.xaml
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelGenerator.managed.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.managed.cs
- src/Uno.UI/UI/Xaml/Style/mergedstyles.xaml
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/8312
- Bugfix
When scrolling for larger delta than the current ScrollViewer view port size, the list will materialize all items in the delta, instead of materializing the items at the end of the scroll.
The ListView (managed for Skia, Wasm and macOS) will now materialize only the items at the scroll's final position, improving the scrolling performance, as well as the interaction with the `ScrollViewer.ChangeView` method.
> fix(ListView): Reduce the number of materialized items on large scrolls

- build/ci/.azure-devops-ios-tests.yml
- build/test-scripts/ios-uitest-run.sh
Scale down runtime tests timeout after stabilization. Current runtime is between 30 to 40 minutes.
> ci: reduce runtime tests timeout

- build/test-scripts/android-uitest-build.sh
- src/SamplesApp/SamplesApp.Droid/SamplesApp.Droid.csproj
- Bugfix
This flag is needed for Android build on macOS, where the use of VS's internal msbuild does not automatically select Android 12. In VS 2022 17.2 Preview 2, the use of API Level 32 causes issues where the IDE automatically upgrades the csproj and manifest file, causing build issues.
> fix: Remove SampleApp AndroidUseLatestPlatformSdk use

- src/SamplesApp/SamplesApp.Droid/SamplesApp.Droid.csproj
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.Droid/BlankApp.Droid.csproj
- src/SolutionTemplate/UnoSolutionTemplate/Droid/UnoQuickStart.Droid.csproj
- Bugfix
Easy to forget to correctly check the proper architecture depending on the Android simulator
Making sure all the Android Supported ABIs are checked and validate the target list
> fix: Adjust AndroidSupportedAbis and add proper validation for the target list

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media_Animation/Given_ColorAnimationUsingKeyFrames.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media_Animation/TestPages/ColorAnimationPage.xaml
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media_Animation/TestPages/ColorAnimationPage.xaml.cs
- src/Uno.UI/UI/Xaml/Media/Animation/ColorAnimationUsingKeyFrames.Android.cs
- src/Uno.UI/UI/Xaml/Media/Animation/ColorAnimationUsingKeyFrames.cs
- src/Uno.UI/UI/Xaml/Media/Animation/ColorKeyFrameCollection.cs
- src/Uno.UI/UI/Xaml/Media/Animation/Storyboard.cs
- src/Uno.UI/UI/Xaml/Media/Animation/Timeline.cs
GitHub Issue (If applicable): closes #7096, closes #8214
- Bugfix
ColorAnimationUsingKeyFrame now properly supports theme changing.
Fixed an issue where gpu-bound color animation doesn't set value on droid.
> color animation theming fix

- src/SourceGenerators/System.Xaml.Tests/Test/System.Xaml/ParsedMarkupExtensionInfoTests.cs
- src/SourceGenerators/System.Xaml.Tests/Uno.Xaml.Tests.csproj
- src/SourceGenerators/System.Xaml/Assembly/AssemblyInfo.cs
- src/SourceGenerators/System.Xaml/System.Xaml/ParsedMarkupExtensionInfo.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/SourceGenerators/XamlGenerationTests/MarkupExtensionTests.xaml
- src/SourceGenerators/XamlGenerationTests/MarkupExtensionTests.xaml.cs
GitHub Issue (If applicable): closes #7947
- Bugfix
- Feature
- Binding with MarkupExtension block that contains separator `,` are now parsed correctly
- Custom markup can be used in binding
```
{Binding Converter={StaticResource SomeNotImplementedConverter}, ConverterParameter={ext:MarkupWithArgs Prop1=1, Prop2=2}}
```
^ This was previously split into 3 parameters:
```
Converter={StaticResource SomeNotImplementedConverter}
ConverterParameter={ext:MarkupWithArgs Prop1=1
Prop2=2}
```
> add support for inline MarkupExtension with named parameters

- src/SamplesApp/SamplesApp.UITests/TestFramework/ImageAssert.ExpectedPixels.cs
- src/SamplesApp/SamplesApp.UITests/TestFramework/ImageAssert.cs
- src/SamplesApp/SamplesApp.UITests/TestFramework/IsExternalInit.cs
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml/DragAndDropTests/DragDrop_ListView_Selection_Automated.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/DragAndDrop/DragDrop_ListView_Selection.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/DragAndDrop/DragDrop_ListView_Selection.xaml.cs
- src/Uno.Foundation/Collections/VectorChangedEventArgs.cs
- src/Uno.Foundation/Extensions/NotifyCollectionChangedEventArgsExtensions.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.Android.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.DragDrop.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.cs
fixes https://github.com/unoplatform/nventive-private/issues/362
fixes https://github.com/unoplatform/uno/issues/4741
When we re-order a selected item in a LV, the item above or below drop location might appears as selected.
When the moved item is being drop, we are doing remove+add which drives the LV to wrongly updates internal indices, which drives the selected state to be applied on the wrong item.
* On collection add/remove we are computing indices properly
* On Android, while reordering an item we no longer rely on the non-yet-updated native collection of items.
> Fix item wrongly appears selected when reordering selected item in LV

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/Nested_Sequence_Tests.cs
- src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Input/PointersTests/Nested_Sequence.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Input/PointersTests/Nested_Sequence.xaml.cs
- src/Uno.UI.RuntimeTests/Helpers/InjectedPointerAttribute.cs
- src/Uno.UI.RuntimeTests/Tests/Uno_UI_Toolkit/Given_VisibleBoundsPadding.cs
- src/Uno.UI.RuntimeTests/UITests/_Engine/SampleControlUITestBase.cs
- src/Uno.UI.RuntimeTests/UITests/_Engine/SkiaApp.MouseHelper.cs
- src/Uno.UI.RuntimeTests/UITests/_Engine/SkiaApp.cs
- src/Uno.UI.RuntimeTests/UITestsImport.props
- src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.Skia.csproj
- src/Uno.UI.Tests/RoutedEventTests/Given_TappedRoutedEvent.cs
- src/Uno.UI/Extensions/UIViewExtensions.iOSmacOS.cs
- src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/NativeScrollContentPresenter.iOS.cs
- src/Uno.UI/UI/Xaml/Input/FocusManager.mux.cs
- src/Uno.UI/UI/Xaml/Internal/RootVisual.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.iOS.cs
- src/Uno.UI/UI/Xaml/UIElement.RoutedEvents.cs
- src/Uno.UI/WasmCSS/Uno.UI.css
- src/Uno.UWP/UI/Input/Preview.Injection/InjectedInputMouseInfo.cs
- src/Uno.UWP/UI/Input/Preview.Injection/InputInjector.cs
closes https://github.com/unoplatform/uno/issues/8289
`PointerEntered` and `PointerExited` might not be raise nor bubble properly, especially when moving pointer while pressed from an element to another element.
1. When moving from an element to another element while pressed, on platform with "implicit capture" (iOS, Android, wasm-touch-chromium), when we try to "re-dispatch" up and exited, as the element is no longer considered pressed/hovered, we are filtering out the events instead of bubbling them as we should.
2. On iOS, the SCP (`UIScrollView`) might stop bubbling of native events for an unknown reason
3. When an event reach the top of the tree, the `RaiseEvent` method returns `true` which is interpreted has "handled" which alter the re-dispatching of exited event.
1. Either we make …
> fix(pointers): Enter/Exit bubbling when crossing boundaries of OriginalSource

- doc/articles/feature-flags.md
- src/Uno.UI/WinRT/Extensions/UI/Popups/MessageDialogContentDialog.cs
- src/Uno.UWP/UI/Popups/MessageDialog.cs
- src/Uno.UWP/WinRTFeatureConfiguration.MessageDialog.cs
GitHub Issue (If applicable): closes #8415
- Bugfix
- Feature
- `MessageDialog` UI defaults to `ContentDialog` everywhere
- - `MessageDialog` style cannot be customized
- `MessageDialog` UI defaults to native dialog on Android, iOS and macOS
- `MessageDialog` style can be customized
> Use native `MessageDialog` UI on Android, iOS and macOS; allow overriding style

- build/Uno.WinUI.Lottie.nuspec
- Bugfix
Lottie for apple targets is not yet supported, this change remove the nuget dependency from the nuspec file.
> fix(net6): remove unsupported lottie support for apple targets

- src/Uno.Foundation/Deferral.cs
- src/Uno.Foundation/Generated/2.0.0.0/Windows.Foundation/Deferral.cs
- src/Uno.UI.RuntimeTests/Tests/Uno_Helpers/Given_DeferralManager.cs
- src/Uno.UWP/Helpers/DeferralManager.cs
GitHub Issue (If applicable): closes #8456 
- Bugfix
- `CompletedSynchronously` is set after `Completed` execution, which gives listeners incorrect information about the event state.
- `Deferral.Dispose` does not close the deferral
- `CompletedSynchronously` set early.
- `Deferral.Dispose` completes the deferral
- Multiple tests to cover `DeferralManager` behavior
> fix: Ensure `DeferralManager.CompletedSynchronously` is set correctly before `Completed` event, feat: `Deferral.Dispose`

- doc/articles/uno-development/docfx.md
- doc/templates/uno/partials/scripts.tmpl.partial
GitHub Issue (If applicable): closes #8297
There is no support for Mermaid for DocFX
- Added Mermaid support to DocFX
- Updated the documentation to run locally the generated doc with a local server (dotnet-serve)
- Updated the documentation to run the generated doc performance test (`run-doc-generation.cmd` script)
There is additional whitespace above and below the flowchart diagrams.
Mermaid version will need to be bumped here when this issue is fixed : https://github.com/mermaid-js/mermaid/issues/1984.
As of right now with this PR, it's using the version [**8.14.0**](https://github.com/mermaid-js/mermaid/releases/tag/8.14.0)
Related internal issue: …
> docs(DocFX): Add Mermaid support to DocFX and update the documentation to run the doc locally with a local server

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/FlyoutTests/UnoSamples_Tests.Flyout.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Flyout/Flyout_Simple.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Flyout/Flyout_Simple.xaml.cs
- src/Uno.UI/UI/Xaml/Controls/Popup/PlacementPopupPanel.cs
GitHub Issue (If applicable): closes unoplatform/uno.extensions#196
- Bugfix
Flyout with full placement are constrained within the visible bounds.
Flyout with full placement can take up the space below the visible bounds (eg: curved edge bottom on iPhone Max Pro 13), as needed.
> fix(flyout): full placement not taking entire screen

- src/Uno.Foundation/Uno.Core.Extensions/Uno.Core.Extensions/StringExtensions.cs
- src/Uno.Foundation/UriExtensions.cs
- src/Uno.UI.RuntimeTests/Tests/Extensions/Given_Uri.cs
- src/Uno.UWP/Security/Authentication/Web/WebAuthenticationBrokerProvider.cs
…slash which is not handled by Android
GitHub Issue (If applicable): closes #6485
- Bugfix
WebAuthenticationBroker.GetCurrentApplicationCallbackUri() does return trailing slash for Android
WebAuthenticationBroker.GetCurrentApplicationCallbackUri() does not return trailing slash for Android
- [ x] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [ x] Commits must be following the [Conventional …
> fix: WebAuthenticationBroker returns canonical URL with the trailing

- src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/Repeater/IndexPathTests.cs
- src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/Repeater/SelectionModelTests.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/CustomProperty.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/SelectedItems.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/SelectionModel.cs
GitHub Issue (If applicable): part of #8261
- Bugfix
- Tests
`IndexPath` and `SelectionModel` tests are disabled.
- Tests are enabled
- Fixes for invalid `SelectedItems` enumeration
> Enable `IndexPath` and `SelectionModel` runtime tests

- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/Given_XamlReader.cs
- src/Uno.UI/UI/Xaml/Markup/Reader/XamlObjectBuilder.cs
- src/Uno.UI/UI/Xaml/Markup/Reader/XamlTypeResolver.cs
GitHub Issue (If applicable): closes #8510
- Bugfix
`XamlReader.Load` would throw when:
1. Adding an item to a collection type with an appropriate `Add(item)` method, but without `[ContentPropertyAttribute]`
2. Adding a collection to a collection property
^ will both work now.
Internal Issue (If applicable): closes: unoplatform/Uno.Figma#515
> fix(XamlReader): collection parsing issues

- build/Uno.UI.Build.csproj
- build/uno.winui.cross-runtime.targets
- build/uno.winui.runtime-replace.targets
- build/uno.winui.single-project.targets
- build/uno.winui.targets
- build/uno.winui.win.targets
- src/SolutionTemplate/UnoLibraryTemplate.net6/CrossTargetedLibrary.csproj
- src/SolutionTemplate/UnoLibraryTemplate/CrossTargetedLibrary.csproj
- src/SolutionTemplate/UnoSolutionTemplate.Wizard/UnoSolutionWizard.cs
- src/SolutionTemplate/UnoSolutionTemplate.net6/Wasm/UnoQuickStart.Wasm.csproj
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/8455
- Bugfix
- Adjust whitespace for some xaml files
- Adds support VS 2022 Intellisense for non-WinAppSDK files
- Fix exception when creating projects
> Misc VS 2022 updates: Intellisense for non-WinAppSDK projects, exception when creating projects

- src/Uno.UI/UI/Xaml/UIElement.skia.cs
- src/Uno.UI/UI/Xaml/UIElement.wasm.cs
GitHub Issue (If applicable): closes #8540
- Bugfix
On skia.gtk & wasm, when the app is launched, this warning message is shown in the console log:
warn: Windows.UI.Xaml.UIElement[0] The BorderThicknessProperty dependency property does not exist on Uno.UI.Xaml.Core.RootVisual
No longer happening.
> fix: BorderThicknessProperty warning on skia/wasm

- src/Uno.UI/UI/Xaml/Application.iOS.cs
- Bugfix
`CultureInfo.CurrentCulture` and `CultureInfo.CurrentUICulture` are now properly set based on the OS's settings for the main thread.
Related to https://github.com/xamarin/xamarin-macios/issues/14740
> fix(net6): [iOS] Ensure current culture is set at Application startup

- src/Uno.UI/UI/Xaml/Controls/FlipView/FlipView.managed.cs
- src/Uno.UI/UI/Xaml/FrameworkElement.cs
GitHub Issue (If applicable): closes #8352 
- Feature
- `FlipView` focus commented out
- `FlipView` focus uncommented
- Some unused methods now properly called
> feat: Focus support in managed `FlipView`

- src/SamplesApp/SamplesApp.Skia.Gtk/Properties/launchSettings.json
- src/Uno.UI.Runtime.Skia.Gtk/GtkHost.cs
- src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/FramebufferHost.cs
- src/Uno.UI.Runtime.Skia.Tizen/TizenHost.cs
- src/Uno.UI.Runtime.Skia.Wpf/WpfHost.cs
- src/Uno.UI/UI/Xaml/Application.cs
- src/Uno.UI/UI/Xaml/Application.macOS.cs
- src/Uno.UI/UI/Xaml/Application.skia.cs
- src/Uno.UWP/ApplicationModel/Activation/LaunchActivatedEventArgs.cs
GitHub Issue (If applicable): closes #8449
- Bugfix
- Feature
- Command-line arguments are not passed to macOS app's `LaunchActivatedEventArgs`
- Multiple arguments are separated by `;`
- Command-line arguments are passed to macOS app's `LaunchActivatedEventArgs`
- Multiple arguments are separated by to match UWP/WinUI this applies to Skia GTK/WPF too
Instead of using semi-color args are now properly separated by space, which is technically a breaking change for those who are expecting semi-colon between multiple args.
> fix!: Args separator on Skia, feat: Pass arguments to `LaunchActivatedEventArgs` on macOS

- src/SamplesApp/SamplesApp.UITests/ScreenshotInfo.cs
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/FlyoutTests/UnoSamples_Tests.Flyout.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Flyout/Flyout_ShowAt_Window_Content.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Flyout/Flyout_ShowAt_Window_Content.xaml.cs
- src/Uno.UI/UI/Xaml/Controls/Flyout/FlyoutBase.cs
- src/Uno.UI/UI/Xaml/Controls/Popup/PlacementPopupPanel.cs
- src/Uno.UI/UI/Xaml/Controls/TextBlock/TextVisual.skia.cs
GitHub Issue (If applicable): closes #5716
- Bugfix
`ShowAt` may position popups and flyouts outside of visible bounds
The popup or flyout position will be clamped within visible bounds.
> Clamp `Popup` and `Flyout` positioning to visible bounds

- src/Uno.UI.Runtime.Skia.Wpf/Extensions/UI/Xaml/Controls/TextBoxViewExtension.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.Android.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.wasm.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.skia.cs
GitHub Issue (If applicable): closes #7016
- Bugfix
[Issue](https://github.com/unoplatform/uno/pull/6995#issuecomment-916392149)
When the developer set an invalid range in SelectionStart and SelectionLength the caret reset to the beginning
- [ x] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ x] Associated with an issue (GitHub or internal) and uses the [automatic close …
> fix(Wasm): Changing TextBox.Text in code should reset the caret to the beginning

- src/Uno.UI/Media/PathMarkupParser.cs
Uno has first fixed a bug here, diverging from Avalonia implementation. But later, Avalonia was fixed in the same way. So this comment no longer applies
> chore: Remove outdated comment

- src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.cs
GitHub Issue (If applicable): closes #8585
- Bugfix
When run this code
https://github.com/unoplatform/uno/blob/a926d5d8e1e678df41fff7a76a980f6952901455/src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.cs#L355-L362
ContentPhone is set up twice 
first https://github.com/unoplatform/uno/blob/a926d5d8e1e678df41fff7a76a980f6952901455/src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.cs#L358
second on https://github.com/unoplatform/uno/blob/a926d5d8e1e678df41fff7a76a980f6952901455/src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.cs#L468-L482 called from ContentPhone PropertyChanged
Please check if your PR fulfills …
> fix: The parent of FrameworkElement is always null in GenerateBitmap

- build/PackageDiffIgnore.xml
- src/Uno.UWP/ApplicationModel/Background/BackgroundTaskRegistration.cs
- src/Uno.UWP/ApplicationModel/Background/IBackgroundTaskRegistration.cs
- src/Uno.UWP/ApplicationModel/Background/IBackgroundTaskRegistration2.cs
- src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Background/BackgroundTaskRegistration.cs
- src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Background/IBackgroundTaskRegistration.cs
- src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Background/IBackgroundTaskRegistration2.cs
GitHub Issue (If applicable): #2406, #3045
- Feature
No background processing at all.
Some structs are defined for all platforms.
No real code - code for Android is in #2655.
Part of #2655 - files that are valid for all platforms.
As #2655 is still waiting, maybe part of it can be merged much sooner. And I would get less Uno0001 messages when building my apps.
Part of my apps
* https://github.com/pkar70/EnviroStatus
* https://github.com/pkar70/BackupSMS
> feat: some Background structs for all platforms

- build/PackageDiffIgnore.xml
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_Devices/Power/Battery.xaml
- src/SamplesApp/UITests.Shared/Windows_Devices/Power/Battery.xaml.cs
- src/Uno.UWP/Devices/Power/Battery.Android.cs
- src/Uno.UWP/Devices/Power/BatteryReport.Android.cs
- src/Uno.UWP/Generated/3.0.0.0/Windows.Devices.Power/Battery.cs
- src/Uno.UWP/Generated/3.0.0.0/Windows.Devices.Power/BatteryReport.cs
- Feature
No class in Windows.Devices.Power is implemented.
Windows.Devices.Power.AggregateBattery and Windows.Devices.Power.BatteryReport is implemented.
Required for two of my apps: 
https://github.com/pkar70/AccuMon
and
https://github.com/pkar70/Waga/tree/master/WeedQbPlug
> feat: [droid] BatteryReport and AggregateBattery

- src/SourceGenerators/Uno.UI.Tasks/Content/Uno.UI.Tasks.targets
- Bugfix
Assets generation is incorrectly processed after the iOS tooling generates the assets items.
Assets items are properly populated.
> fix(net6): Adjust assets generation of iOS/Catalyst

- src/SolutionTemplate/UnoSolutionTemplate.net6/Mobile/UnoQuickStart.Mobile.csproj
- Bugfix
Improve iOS/Catalyst performance, related to https://github.com/xamarin/xamarin-macios/issues/14812.
This change restores the original xamarin exception marshaling behavior to improve runtime performance.
> fix(net6): restore xamarin-like ios exception marshaling for performance

- src/Uno.Foundation/Metadata/ApiInformation.shared.cs
- src/Uno.UWPSyncGenerator/Program.cs
GitHub Issue (If applicable): closes #8537 
- Bugfix
- Version information in `IsApiContractPresent` is not up to date
- Additional supported contracts are not reported correctly
- Updated to 22000
- Additional contracts are correctly reported
> fix: Improve `IsApiContractPresent` accuracy

- src/SamplesApp/UITests.Shared/Windows_Storage/Pickers/FileSavePickerTests.xaml.cs
- src/Uno.UWP/Storage/Pickers/FileSavePicker.Android.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/8419
- Bugfix
await picker.PickSaveFileAsync(); does not return and continues to wait indefinitely.
await picker.PickSaveFileAsync(); Returns the file selected by the user.
- [ x] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ x] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a- …
> fix: FileSavePicker does not return the picked file in Android

- src/SamplesApp/SamplesApp.net6mobile/SamplesApp.net6mobile.csproj
- src/Uno.UI.Toolkit/ElevatedView.cs
- src/Uno.UI.Toolkit/UIElementExtensions.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/8701, closes https://github.com/unoplatform/uno/issues/8690, closes https://github.com/unoplatform/uno/issues/8691, closes https://github.com/unoplatform/uno/issues/8705, closes https://github.com/unoplatform/uno/issues/8700, closes https://github.com/unoplatform/uno/issues/8692, closes https://github.com/unoplatform/uno/issues/8709
- Bugfix
Restores TemplatedParent support for ElevatedView content.
> fix(net6): Restore ElevatedView templated parent support

- src/Uno.UWP/Storage/Pickers/FileSavePicker.macOS.cs
`NSFileManager.DefaultManager.GetUrls` can return an empty array, which
leads to an `IndexOutOfRangeException`. I get this when I run Uno's
SamplesApp.macOS using the default **ComputerFolder** start location and
clicking on `Pick save file`.
If an empty array is returned then the code will fallback to the user
home directory using a different API `NSHomeDirectory`.
- Bugfix
A `IndexOutOfRangeException` is thrown, on macOS when I run Uno's
SamplesApp.macOS using the default **ComputerFolder** start location and
clicking on `Pick save file`.
No exception, the file dialog is shown.
That result is a bit unexpected but
```csharp
var url = …
```
> fix(filesavepicker): Avoid possible `IndexOutOfRangeException` on macOS

- build/uno.winui.single-project.targets
- src/SourceGenerators/Uno.UI.Tasks/Assets/RetargetAssets.cs
- src/SourceGenerators/Uno.UI.Tasks/Content/Uno.UI.Tasks.targets
- src/Uno.UWP/Helpers/AndroidResourceNameEncoder.cs
- Bugfix
Properly sets the android base path for content files. The testing for this is implicitly done in the android runtime tests, which are currently disabled until stabilized in net6-andoid.
> fix(net6): [Android] Adjust for proper assets base path

- src/Uno.UI.Runtime.Skia.Gtk/Extensions/Storage/Pickers/FileOpenPickerExtension.cs
- src/Uno.UI.Runtime.Skia.Gtk/Extensions/Storage/Pickers/FileSavePickerExtension.cs
- src/Uno.UI.Runtime.Skia.Gtk/Extensions/Storage/Pickers/FolderPickerExtension.cs
GitHub Issue (If applicable): #6334
- Bugfix
After interacting with a picker dialog on Skia.GTK and dismissing them with one of the action buttons (Cancel, Save, Open, Select Folder), GTK crashes with the exception:
```
An unhandled exception of type 'System.AccessViolationException' occurred in GLibSharp.dll
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
```
Exception does't appear, storage picker works fine
Fixes #6334
> fix: Fixed AccessViolationException that occurs in GLibSharp.dll after storage picker interaction

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml/DragAndDropTests/DragDrop_ListViewReorder_Automated.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/DragAndDrop/DragDrop_ListView.xaml
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.DragDrop.cs
- src/Uno.UI/UI/Xaml/DragDrop/DragDropManager.cs
closes https://github.com/unoplatform/nventive-private/issues/383
Make sure to disable dragging on LV's ItemContainer
If we disable the `LV.CanReorder` while list has been loaded, trying to drag item might break the UI
We make sure to effectively set the `CanDrag` to false on all items containers
> fix(dragdrop): Make sure to disable dragging on LV's ItemContainer

- src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props
- src/SourceGenerators/Uno.UI.SourceGenerators/DependencyObject/DependencyObjectGenerator.cs
- Bugfix
Disposable private fields in XAML-generated classes are now excluded from CA1001.
> fix(codegen): Don't warn on CA1001 by default (disposable fields) for generated code

- src/Uno.UI.RemoteControl/RemoteControlClient.cs
- Bugfix
Remote Control errors will now be less verbose when debug logging is not enabled.
> fix: Reduce logging verbosity for remote control connection errors

- .mergify.yml
- Other: Clean up for automation
Remove the need to automatically merge PR's from allcontributors bot
> chore: Remove the need to automatically merge PR's from allcontributors bot

- src/PlatformItemGroups.props
- Bugfix
Removes the CA1416 warnings when building net6 mobile apps.
> fix(net6): Add supported platforms attributes for CA1416

- doc/articles/features/windows-storage-pickers.md
- src/Uno.UI.Runtime.WebAssembly/Storage/Pickers/PickerSupportInformation.cs
- src/Uno.UWP/AssemblyInfo.cs
- src/Uno.UWP/Storage/Pickers/FileOpenPicker.wasm.cs
- src/Uno.UWP/Storage/Pickers/FileSavePicker.wasm.cs
- src/Uno.UWP/Storage/Pickers/FolderPicker.wasm.cs
- Feature
- There is no API to detect whether WASM File System Access API is available
- Docs don't explain `CachedFileManager` well
- API added
- Docs improved
> WASM `Storage.Pickers` improvements

- build/ci/.azure-devops-ios-tests-run.yml
- build/ci/.azure-devops-ios-tests.yml
- build/test-scripts/ios-uitest-run.sh
- src/SamplesApp/SamplesApp.UITests/RuntimeTests.cs
- src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/8167
Splits iOS runtime tests in smaller groups to make retries faster. This is needed because of the iOS issue https://github.com/unoplatform/uno/issues/8167.
> ci: Split iOS runtime tests in groups for faster retries

- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-winui-net6/.template.config/template.json
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/8775
- Bugfix
Fixes invalid `dotnet new unoapp-winui-net6` restore targets
> fix: Adjust net6-winui dotnet new

- doc/articles/features/winapp-sdk-specifics.md
- doc/articles/get-started-wizard.md
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-winui-net6/UnoWinUIQuickStart.Windows/UnoWinUIQuickStart.Windows.csproj
- src/SolutionTemplate/UnoSolutionTemplate.WinUI.net6/WinUI/UnoQuickStart.Windows.csproj
- Bugfix
Adds in-projects hints to fix this error message:
```
error NETSDK1148: A referenced assembly was compiled using a newer version of Microsoft.Windows.SDK.NET.dll. Please update to a newer .NET SDK in order to reference this assembly.
```
> fix: Add FrameworkReference to winui projects

- README.md
- chore: remove obsolete Dependabot README badge
_**Context:**_
Fixes the broken link/image at the top of README
There isn't currently a replacement for the badge feature in the native GitHub Dependabot.
https://github.com/dependabot/dependabot-core/issues/1912 tracks the request to add it but hasn't seen activity in some time.
- docs: Update readme with small fixes
> chore: remove obsolete Dependabot README badge & docs: Update readme with small fixes

- doc/articles/features/PasswordVault.md
- doc/articles/features/windows-applicationmodel-calls.md
- doc/articles/toc.yml
- Non UI docs are hidden under WinRT features, which most people won't check, plus the article names don't make sense
- Better ToC
- `PasswordVault` docs rewritten
- `PhoneCallManager` docs rewritten
> docs: Non-UI APIs ToC, improved docs

- src/AddIns/Uno.UI.Lottie/LottieVisualSource.iOSmacOS.cs
- src/AddIns/Uno.UI.Lottie/LottieVisualSourceBase.Android.cs
- src/AddIns/Uno.UI.Lottie/Uno.UI.Lottie.net6.csproj
- src/SamplesApp/SamplesApp.net6mobile/SamplesApp.net6mobile.csproj
- src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.Diagnostics.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs
- src/Uno.UI.TestComparer/Program.cs
- Bugfix
Show the native progress ring in place of the MUX progressring.
> fix(net6): Restore partial support for MUX progressring

- src/Uno.UI.Runtime.Skia.Gtk/SoftwareRenderSurface.cs
- Bugfix
When the DPI scaling is not 1, the scale applied to the skia canvas can accumulate and make the surface rendering unuseable.
The software renderer works on a high dpi screen.
> fix(skia): Restore original canvas state for Software renderer

- build/Uno.UI.Build.csproj
- Bugfix
VSIX WinUI templates now have the proper versions.
> fix(template): Adjust versioning in vsix templates

- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/Uno.ProjectTemplates.Dotnet.csproj
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-winui/.template.config/template.json
- src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props
- Bugfix
`dotnet new unoapp-winui` does not show error messages.
> fix(dotnetnew): Fix incorrect restore in unoapp-winui

- src/Uno.UI/UI/Xaml/Input/PointerRoutedEventArgs.Android.cs
GitHub Issue (If applicable): closes #8702
- Bugfix
Pointer events lead to crashing apps under Android prior to SDK 23.
Works
> fix: missing guarding leads to crashes under Android prior to API 23

- src/SourceGenerators/Uno.UI.SourceGenerators/DependencyObject/DependencyObjectGenerator.cs
- avoid generating disabled `Dispose` code for Android
- inline `RequestCollect` method (if only to reduce metadata)
- reuse the `Count` check to avoid the enumerator (iOS)
- use the macOS r/w `Subviews` property to avoid multiple native calls
Refactoring (no functional changes, no api changes)
Applications can display warnings like `Tried to create a managed reference from an object that already has a managed reference`, see https://github.com/unoplatform/uno/issues/8688
This warning should not be seen, on macOS, with the changes included in the PR as it avoid the `RemoveFromSuperview` call, inside with Xamarin.Mac would call `Superview` and expose a bug inside the Xamarin runtime leading to the warning. …
> refactor: Tweak generated `Dispose(bool)` to make #8688 less common

- src/SamplesApp/SamplesApp.UITests/UnoSamples_Tests.ContentControl.cs
- src/Uno.UI/UI/Xaml/Input/PointerRoutedEventArgs.iOS.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.iOS.cs
closes https://github.com/unoplatform/nventive-private/issues/253
The `PointerRoutedEventArgs.FrameId` caps to `uint.MaxValue` after about 10 days after last reboot of the device.
With latest versions of iOS, 10 days after last system reboot, the computed frame ID was overflowing the `uint` capacity, and cast was not resetting to 0 as expected.
The visible effect was to break Drag and Drop with latest versions of iOS.
- The `FrameId` resolution has been reduced to 120 frames per seconds (120Hz, 8.33 ms per frame)
- It's not computed relative to the first frame since the app launch (was relative to system up-time)
- We are explicitly ensure a reset to 0 in case of overflow of `uint`.
Note: `FrameId` will now be reset to 0 after 1.13 of application run-time.
> fix(pointers): [iOS] Fix frame id capping to uint.MaxValue

- build/test-scripts/android-uitest-run.sh
- build/test-scripts/ios-uitest-run.sh
- build/test-scripts/wasm-run-automated-uitests.sh
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/AutoSuggestBoxTests/AutoSuggestBoxTests.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/AutoSuggestBoxTests/AutoSuggestBox_Reason.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/AutoSuggestBoxTests/AutoSuggestBox_Reason.xaml.cs
- src/Uno.UI/UI/Xaml/Controls/AutoSuggestBox/AutoSuggestBox.cs
GitHub Issue (If applicable): closes #7957
- Bugfix
Default value was UserInput when should be Programmaticaly 
Now it works exactly like Windows
> fix: AutoSuggestBox Reason with inconsistency

- src/Uno.UI.Runtime.Skia.Gtk/Uno.UI.Runtime.Skia.Gtk.csproj
- Bugfix
Adds missing SkiaSharp.Harfbuzz dependency on Skia.Gtk packages.
> fix(reg): Add missing harfbuzz dependency

- src/SourceGenerators/Uno.UI.SourceGenerators/DependencyObject/DependencyObjectGenerator.cs
- src/Uno.UI/Controls/DisposeHelper.iOSmacOS.cs
- This unsafe operation is kind of _safe'ish_ as
- `NSObject` has a `[StructLayout (LayoutKind.Sequential)]` attribute
- Its layout is known to the xamarin native runtime
- IOW any changes would be breaking changes and well advertised.
- net6-macos uses CoreCLR (not mono) and this issue does not happen
GitHub Issue (If applicable): closes #8688
- Bugfix
On iOS `Tried to create a managed reference from an object that already has a managed reference` warnings appears at runtime.
That meant a new, short-lived, managed instance was created when trying to dispose of the first one.
There's no more warnings (and no more extra managed instance created).
This second PR (first was [1]) is meant …
> fix: Reset NSObject InFinalizerQueue after calling ReRegisterForFinalize

- src/SolutionTemplate/UnoLibraryTemplate.net6/CrossTargetedLibrary.csproj
GitHub Issue (If applicable): https://github.com/unoplatform/uno/discussions/8880
- Bugfix
Adjust the default net6 library vsix template.
> fix: Adjust new net6 library from vsix

- src/SamplesApp/SamplesApp.Shared/App.xaml.cs
- src/Uno.UI.Runtime.Skia.Gtk/UI/Xaml/Controls/TextBoxViewExtension.cs
- src/Uno.UI.Runtime.Skia.Wpf/Extensions/UI/Xaml/Controls/TextBoxViewExtension.cs
- src/Uno.UI.Runtime.Skia.Wpf/WpfHost.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/ITextBoxExtension.skia.cs
GitHub Issue (If applicable): closes #8641 
- Bugfix
When initial app page has an input field as first focusable element, exception is thrown.
- Exception is no longer thrown
- Enabled app settings test during Samples app startup
> fix: WPF Skia input on initial page load

- src/Uno.UI.RuntimeTests/Tests/Uno_UI_Xaml_Controls/Given_SystemFocusVisual.cs
- src/Uno.UI/LinkerDefinition.Wasm.xml
- src/Uno.UI/UI/Xaml/Controls/FocusVisual/SystemFocusVisual.cs
- src/Uno.UI/UI/Xaml/Controls/FocusVisual/SystemFocusVisual.wasm.cs
- src/Uno.UI/WasmScripts/Uno.UI.d.ts
- src/Uno.UI/WasmScripts/Uno.UI.js
- src/Uno.UI/ts/Windows/UI/Xaml/Input/FocusVisual.ts
GitHub Issue (If applicable): closes #6404
- Bugfix
- System focus visual position does not change when focused element is scrolled on WASM
- `SystemFocusVisual` position is calculated relative to Window content
- When scrolling, focus visual position changes accordingly
- `SystemFocusVisual` position is calculated relative to Window root element - handles the case when Window content is centered within the window and does not fully stretch
> [WASM] fix: Sync system focus visual with the focused element on scroll

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TextBoxTests/TextBoxTests.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_Wrap.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_Wrap.xaml.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.Android.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.Android.cs
GitHub Issue (If applicable): closes #3648 
- Bugfix
When the user sets TextWrapping="Wrap" the text is never wrapped on the Android Platform.
When the user sets TextWrapping="Wrap" the text is wrapped.
> fix: TextWrapping="Wrap" does not seem to work for TextBox on Android

- src/Uno.UI.Tests/BinderTests/Given_Binder.TwoWay.cs
- src/Uno.UI/DataBinding/BindingExpression.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/7696
- Bugfix
Aligns `x:Bind` source update bind back behavior with WinUI, which is allows the target update (while a normal binding does not).
> fix(xbind): Ensure source updates update the target during a two-way binding

- src/Uno.UWP/ApplicationModel/DataTransfer/Clipboard.wasm.cs
GitHub Issue (If applicable): closes #8884
- Bugfix
Previously we were executing the GetClipboardText method on UI thread which was unnecessary, and as it was executed asynchronously, it did not necessarily wait for the actual promise on JS side to finish executing. Therefore in most cases just the initial empty string content was returned.
Reliable!
> fix: Make `Clipboard.GetContentAsync` reliable

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_CoreWindow.cs
- src/Uno.UWP/Generated/3.0.0.0/Windows.UI.Core/CoreWindow.cs
- src/Uno.UWP/UI/Core/CoreWindow.cs
GitHub Issue (If applicable): closes #7630
- Feature 
CoreWindow Bounds property wasn't implemented.
Implemented like Windows Bounds property.
> feat: implement CoreWindows.Bounds

- build/ci/.azure-devops-unit-tests.yml
- src/Uno.Foundation.Runtime.WebAssembly/AssemblyInfo.cs
- src/Uno.Foundation.Runtime.WebAssembly/Interop/WebAssembly.Runtime.cs
- src/Uno.UI.Dispatching/Core/CoreDispatcher.wasm.cs
- src/Uno.UI.RemoteControl.Host/Startup.cs
- src/Uno.UI/WasmScripts/Uno.UI.d.ts
- src/Uno.UI/WasmScripts/Uno.UI.js
- src/Uno.UI/ts/MonoSupport.ts
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/5469
- Feature
Adds support for .NET 7 WebAssembly threads.
> feat(wasm): Add support for threads

- src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePickerSelector.iOS.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/nventive-private/issues/393
- Bugfix
Applies a best-effort UIDatePicker theme adjustment when the app's theme overrides the system theme.
System Dark Theme on App Dark theme:
System Dark Theme on App Light theme:
> fix(DatePicker): Ensure proper native picker readability when the system theme is overriden

- src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/Uno.UI.Runtime.Skia.Linux.FrameBuffer.csproj
- src/Uno.UI.Runtime.Skia.Tizen/Uno.UI.Runtime.Skia.Tizen.csproj
- src/Uno.UI.Runtime.Skia.Wpf/Uno.UI.Runtime.Skia.Wpf.csproj
- Bugfix
Fixes the following issue when using Skia.WPF:
```
System.IO.FileNotFoundException: 'Could not load file or assembly 'HarfBuzzSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756'. The system cannot find the file specified.'
```
> fix(skia): Add missing Harfbuzz dependencies for Wpf, Tizen and Framebuffer

- build/ci/.azure-devops-unit-tests.yml
- src/SamplesApp/SamplesApp.Skia.Gtk/SamplesApp.Skia.Gtk.csproj
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media_Imaging/Given_BitmapSource.cs
- src/Uno.UI/UI/Xaml/Media/Imaging/BitmapImage.skia.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/8909
- Feature
- `BitmapImage` now supports `ms-appdata://` sources
- `BitmapImage.ImageOpened` and `ImageFailed` are now raised.
> feat(BitmapImage): [Skia] Add support for ms-appdata, BitmapImage.ImageOpened/ImageFailed

- src/Uno.UI/Extensions/ViewHelper.iOSmacOS.cs
- Bugfix
At application startup an ugly warning is printed on macOS because a deprecated API is called.
```
2022-06-11 11:35:32.259 DopeTestUno.macOS[79018:2398769] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 
```
No warning is printed when starting an app on macOS
For its usage here the deprecated API can be replaced with `backingScaleFactor`, instead of the proposed (inside the warning message) `convertRectToBacking:`.
https://developer.apple.com/documentation/appkit/nsscreen/1388385-backingscalefactor?language=objc …
> fix(macOS): Remove warning/usage for deprecated `userSpaceScaleFactor`

- src/SourceGenerators/Uno.UI.SourceGenerators/DependencyObject/DependencyObjectGenerator.cs
- src/Uno.UI/Extensions/UIViewExtensions.iOSmacOS.cs
Calling `Subviews` creates a managed `NSView[]` array and fill it with `NSView` instances - most of them should already exists in managed land, but still need to be retrieved with `GetNSObject`.
This is costly **when** the only thing we want is to know if any items are present in the array. IOW **when** we do not care about the element themselves (which is why this optimization cannot, as is, be applied to iOS).
Note: Unseen here is the GC time spent to collect the temporary `NSView` managed arrays.
Adding a specialized utility method that gets the `NSArray` handle out of `Subviews` and query the number of elements using `CFArray` p/invokes (faster than …
> perf(macOS): Avoid calling `Subviews` getter inside `Dispose`

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ItemsControl.cs
- src/Uno.UI/UI/Xaml/UIElementCollection.cs
GitHub Issue (If applicable): closes unoplatform/nventive-private#388
- Bugfix
ItemsPresenter of an recycled ItemsControl are not marked as measure dirty when its data-context changes, causing it to keep its old size before being recycled.
Should not happen.
> fix(measure_dirty_path): recycled ItemsControl not re-measuring

- src/Uno.UI.Runtime.Skia.Wpf/WpfHost.cs
Need to correct the Visual Studio Template to add the Package.appxmanifest to the WPF.
GitHub Issue (If applicable): closes #8356
- Bugfix 
Wasn't working on SKIA WPF.
Now works fine on both platforms.
**Attention!!!!**
The VS template must be updated to include the Package.appxmanifest inside the SKIA.WPF project!!
> fix: Window Title by Manifest in SKIA WPF 

- src/Uno.UI.Runtime.Skia.Gtk/GtkHost.cs
- src/Uno.UI/UI/Xaml/Documents/Inline.skia.cs
- Bugfix
The application crashes on startup when running on Linux.
The application starts up properly.
https://github.com/mono/SkiaSharp/issues/2113
> fix(linux): Adjust harbuzz initialization to avoid Gtk3 interference

- src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.cs
GitHub Issue (If applicable): closes #9083
- Bugfix
UWP Runtime tests fail immediately as test enumeration attempts to retrieve dependency properties from non-UI thread
Value of DPs is cached to fields which are accessed instead of DPs during the enumeration.
> fix: UWP Samples app runtime tests attempt to use DP from non-UI thread

- src/Uno.UWP/UI/Color.iOS.cs
- src/Uno.UWP/UI/Color.macOS.cs
- Avoid creating a temporary `NSColor` on macOS
- Avoid creating a temporary `UIColor` on iOS
Converting a `Color` to `CGColor` creates an intermediary `NSColor` (macOS) or `UIColor` (iOS).
In addition of requiring extra allocations and disposal both `NSColor` and `UIColor` are `NSObject` subclasses and uses ObjC calls (slower than p/invokes) while `CGColor` uses C-based API (p/invokes).
Direct conversion of `Color` into `CGColor`.
The following results (on coreclr) shows the cost of both creating and disposing the instances needed to convert a `Color` into a `CGColor` instance.
``` …
```
> perf(iOSmacOS): Directly convert from `Color` to `CGColor`

- src/SourceGenerators/System.Xaml/System.Xaml/XamlSchemaContext.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/Helpers/IsExternalInit.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/Helpers/Nullable.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.Reflection.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_SameClassName.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_SameClassName.xaml.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/9013
- Bugfix
Uses fully qualified type for `x:Class` resolution and avoid ambiguities on names uses with xBind types.
> fix: Use fully qualified name lookup for xClass resolution

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/Uno.UI.Tests/ResourceLoader/Given_ResourceLoader.cs
- src/Uno.UI.Tests/ResourceLoader/Strings/en/Resources.Designer.cs
- src/Uno.UI.Tests/ResourceLoader/Strings/en/Resources.resw
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XUidTests/Controls/When_Empty_XUid.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XUidTests/Controls/When_Empty_XUid.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XUidTests/Given_xUid.cs
- src/Uno.UI/Helpers/MarkupHelper.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/8800
- Bugfix
x:Uid assigned string empty values are now returning null to align with the WinUI behavior.
> fix: Align resource conversion for empty values

- src/Uno.UI/UI/Xaml/Documents/Inline.skia.cs
- src/Uno.UI/UI/Xaml/Documents/TextElement.skia.cs
GitHub Issue (If applicable): closes #9090
- Bugfix
Changing font properties (i.e. FontFamily, Weight, Stretch, Style) after the TextBlock is rendered has no effect.
Font properties result in rendering being updated.
> fix(Skia): [TextBlock] Fix rendering when font properties change

- src/SolutionTemplate/UnoSolutionTemplate.WinUI.net6/Mobile/UnoQuickStart.Mobile.csproj
- src/SolutionTemplate/UnoSolutionTemplate.net6/Mobile/UnoQuickStart.Mobile.csproj
GitHub Issue (If applicable): closes #9093
- Bugfix
The **Mono** interpreter gets enabled in templates for `net6.0-macos`.
Never enable the interpreter for `net6.0-macos` as it's based on CoreCLR (not Mono).
> fix: Never enable the interpreter on net6.0-macos

- src/Uno.UWP/Graphics/Display/DisplayInformation.iOS.cs
- src/Uno.UWP/Graphics/Display/DisplayInformation.macOS.cs
GitHub Issue (If applicable): closes #9098
Calling `DisplayInformation` properties requires several, slow native (ObjC) calls.
Subscribe to notifications to let us know the `NSWindow` (macOS) or `UIScreen` (macOS) have changed screen (or resolution) so we can cache the values between calls.
> perf(macOS): Cache DisplayInformation properties

- src/Uno.UI/Extensions/UIViewExtensions.iOSmacOS.cs
- src/Uno.UI/Extensions/ViewHelper.iOSmacOS.cs
GitHub Issue (If applicable): closes #9027
- Bugfix
`ViewHelper` has C# `readonly` fields for `MainScreenScale` and `IsRetinaDisplay` that are evaluated only once. IOW they are set to the current screen when the evaluation is done and moving the window to a different screen will not update the values.
Both `readonly` fields are now decorated with `[Obsolete]` attributes giving update instructions to directly use (now cached) `DisplayInformation` properties. This ensure the current (screen) values will be given for every call during the app lifetime.
> fix(iOSmacOS): Obsolete the use of readonly fields

- src/Uno.UI.RemoteControl/RemoteControlClient.cs
- Bugfix
Fixes socket selection for net6 mobile hot reload on windows.
> fix(rc): Adjust socket selection for non-faulted connections on net6 mobile

- src/Uno.UI/UI/Xaml/FrameworkElement.iOSmacOS.cs
Sometimes `var` and `implicit` conversions can play tricks behind our backs...
Here's the code decompiled:
```csharp
protected Size SizeFromUISize(CGSize P_0)
{
NFloat nFloat = (NFloat.IsNaN(P_0.Width) ? ((NFloat)float.PositiveInfinity) : P_0.Width);
NFloat nFloat2 = (NFloat.IsNaN(P_0.Height) ? ((NFloat)float.PositiveInfinity) : P_0.Height);
return ViewHelper.PhysicalToLogicalPixels(new Size(nFloat, nFloat2));
}
```
So `var` is... `nfloat` and `PositiveInfinity` gets casted, twice.
Also the `Size` arguments are implicitely casted from `nfloat` to `double` - but that's basically free on 64bits platforms (so almost everywhere).
- Explicit (instead of implicit) `nfloat` to `double` making the `var` …
> perf(iOSmacOS): Reduce nfloat / float / double conversions

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.Android.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.Android.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/9158
- Bugfix
- Restores the ability for TextBox on Android to have text on multiple lines when AcceptsReturn is set to true. 
- Enables TextBox height validation on all platforms.
> fix(TextBox): [Android] restores AcceptsReturn ability to display text on multiple lines

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlConstants.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/9167
- Bugfix
Ensures that Automation namespaces types get considered first when resolving XAML types.
> fix: Add Automation namespace to avoid fuzzy matching issue in single-project WPF

- src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.iOSmacOS.cs
- src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.macOS.cs
Both iOS and macOS _identical_ versions of `GetDrawRect` are calling 6 times `get_Padding`.
```cil
.method private hidebysig 
instance valuetype [Microsoft.macOS]CoreGraphics.CGRect GetDrawRect (
valuetype [Microsoft.macOS]CoreGraphics.CGRect ''
) cil managed 
{
// Method begins at RVA 0xb6740
// Code size 180 (0xb4)
.maxstack 4
.locals init (
[0] valuetype Windows.UI.Xaml.Thickness
)
// P_0.Width -= (NFloat)(Padding.Left + Padding.Right);
IL_0000: ldarga.s 1
IL_0002: dup
IL_0003: call instance valuetype [System.Private.CoreLib]System.Runtime.InteropServices.NFloat [Microsoft.macOS]CoreGraphics.CGRect::get_Width()
IL_0008: ldarg.0
IL_0009: call instance …
```
> perf(iOSmacOS):  calls  getter too many times

- src/Uno.UI/UI/Xaml/Window.wasm.cs
- src/Uno.UI/WasmScripts/Uno.UI.d.ts
- src/Uno.UI/WasmScripts/Uno.UI.js
- src/Uno.UI/ts/WindowManager.ts
GitHub Issue (If applicable): closes #9194
- Bugfix
Previously the root element of a WASM Window was "loaded" each time its content was set. This is unnecessary, as the root element should load only once initially and then only its actual content should load and unload. Additionally, setting null content caused WASM window to get into an inconsistent state that prevented the user to set the content back.
Adjusted to match the logic in other targets.
> fix: WASM root element loading logic

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_FlipView.cs
- src/Uno.UI.Tests/Windows_UI_XAML_Controls/SelectorTests/Given_Selector.cs
- src/Uno.UI/UI/Xaml/Controls/Primitives/Selector.cs
GitHub Issue (If applicable): closes #8104 
- Bugfix 
When a page is loaded with a FlipView, it appears to be scrowled to the last item. Actually, the SelectedIndex has the same value as Items.Count. 
As soon at is loaded, the FlipView must have a SelectedIndex = 0, showing the first item of the collection.
During the test it was observed other Android issue not specific related to this issue. 
It will be provided a new issue with more details.
> fix: [iOS][Android] fix FlipView first load selecteditem above limit

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Media/ImageBrushTests/ImageBrush_Shape_Fill_StretchAndAlignment.cs
This test often fails, most likely because the successful runs finish just below 7 minutes. Increasing the timeout to 8 so that there is higher chance the test will manage to succeed in time.
> chore: Break-down the `When_StretchAndAlignment` test to four batches

- src/Uno.UI/UI/Xaml/Shapes/Ellipse.Android.cs
- src/Uno.UI/UI/Xaml/Shapes/Line.Android.cs
- src/Uno.UI/UI/Xaml/Shapes/Polygon.Android.cs
- src/Uno.UI/UI/Xaml/Shapes/Polyline.Android.cs
- src/Uno.UI/UI/Xaml/Shapes/Rectangle.Android.cs
- src/Uno.UI/UI/Xaml/Shapes/Shape.Android.cs
GitHub Issue (If applicable): closes #6896
- Bugfix
Native Android path object is created on each Arrange.
The path element is only created once, on subsequent calls it will be reused and resetted instead.
For rectangle and ellipse it will furthermore ensure that the rendering area actually changed before it triggers rendering again.
Checked shapes with SamplesApp.Android before and after applying the code changes. The visual results seem to be identical.
> fix: re-use of native path instances and further optimizations

- src/Uno.UI.Tests/Windows_UI_XAML_Controls/Frame/Given_Frame.cs
- src/Uno.UI/UI/Xaml/Controls/Frame/Frame.cs
GitHub Issue (If applicable): closes #9251
- Bugfix
Order of events is incorrect.
Order of events is in line with WinUI
> fix: `Frame.Navigated` should occur before `Page.NavigatedFrom` and `Page.NavigatedTo`

- src/Uno.UI.RuntimeTests/Tests/Windows_UI/Given_Color.cs
- src/Uno.UWP/UI/ViewManagement/UISettings.cs
GitHub Issue (If applicable): closes #6767
- Bugfix 
Uno Apps were not able to detect custom color changes made by the user. 
Now, the app can detect the custom changes using using UISettings.ColorValuesChanged
and retry the colors by UISettings.GetColorValue().
Valid to know: AppKit doesn't have all UITypes available on uno. So, some are still hardcoded on SystemResources.xaml.
> fix: [macOS] follow system colors changes

- doc/articles/get-started.md
Linked the preferred experience in the first sentence. No need to make the user seek the link below.
Visual studio 2022 link is in list
Link for Visual Studio 2022 is in the beginning to improve UX 
> docs: Visual studio link moved up

- build/PackageDiffIgnore.xml
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ContentDialog/UnoSamples_Tests.ContentDialog.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_Storage/Streams/Given_DataWriter.cs
- src/Uno.UWP/Storage/Streams/DataWriter.cs
- src/Uno.UWP/Storage/Streams/DataWriterStoreOperation.cs
- Bugfix
In its original form, the `StoreAsync` test finished before the assert was actually checked.
- Using `await` for async calls
- Checking the file contents after writing.
- Delegating async logic to `AsyncOperation`
> fix: Adjust `DataWriter.StoreAsync`

- doc/articles/guides/uno-material-walkthrough.md
- src/SamplesApp/SamplesApp.UITests/TestFramework/IsExternalInit.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/AutoSuggestBoxTests/AutoSuggestBoxChosenSuggestion.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/AutoSuggestBoxTests/AutoSuggestBoxChosenSuggestion.xaml.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_AutoSuggestBox.cs
- src/Uno.UI/UI/Xaml/Controls/AutoSuggestBox/AutoSuggestBox.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.DragDrop.cs
GitHub Issue (If applicable): closes #7778
- Bugfix
Please see attached sample - which is a modified version of what I posted at https://github.com/unoplatform/uno/issues/4382 - and search for '!!!': in the QuerySubmitted event "e.ChosenSuggestion == null" when selection an option from the drop down. This is wrong
Should work as in WindowsAppSDK desktop
> fix: AutoSuggestBox.QuerySubmitted ChosenSuggestion should not be null, patch.

- src/SourceGenerators/Uno.UI.Tasks/LinkerHintsGenerator/LinkerHintGeneratorTask.cs
- Bugfix
Reference Paths were written with the string "Skia" or "WebAssembly" in the path. This causes issues for builds on *nix environment since the file system may be case-sensitive.
Example: `/__w/1/s/.nuget/uno.ui/4.5.0-dev.328/uno-runtime/WebAssembly/Uno.Foundation.dll` does not match the actual path of `/__w/1/s/.nuget/uno.ui/4.5.0-dev.328/uno-runtime/webassembly/Uno.Foundation.dll`
> fix: case-insensitive linker ref paths

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ComboBox.cs
- src/Uno.UI/UI/Xaml/Controls/Primitives/Selector.cs
- src/Uno.UI/UI/Xaml/FrameworkPropertyMetadata.cs
- Bugfix
When `SelectedIndex` is set to invalid value before items are present, the request is ignored and selection does not work.
Selected index is set properly when requested item is added.
> Allow pre-selecting invalid selection on `Selector` when items are empty

- src/SamplesApp/UITests.Shared/Windows_UI_Input/PointersTests/EventsSequences.xaml.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.cs
- src/Uno.UWP/UI/Input/GestureRecognizer.cs
closes https://github.com/unoplatform/uno/issues/7951
Make sure to update manipulation first before raising pointer released event
`PointerReleased` event is raised before the `Manipulation<InertiaStarting|Completed>`.
🙃
> fix(pointers): Make sure to update manipulation first before raising pointer released event

- src/SamplesApp/UITests.Shared/Windows_UI_Input/PointersTests/EventsSequences.xaml.cs
- src/Uno.UI/UI/Xaml/RoutedEvent.cs
Fix CI not passing due to flaky test in pointers
Depending of the load of the build server, the inertia might kick-in driving to an invalid code path (we were validating the inertia of another test)
> fix(pointers): Fix tests randomly failing on CI

- src/SourceGenerators/System.Xaml/System.Xaml/ParsedMarkupExtensionInfo.cs
GitHub Issue (If applicable): closes #9273
- Bugfix
misleading error message is shown when binding expression contains trailing space:
\<Example Binding="{Binding} " />
^ Expected '}' in the markup extension attribute: '{Binding} '
a more appropriate message (same as uwp) is shown: White space is not allowed after end of markup extension: "{Binding} "
Both source generator and XamlReader.Load goes through `ParsedMarkupExtensionInfo`.
> fix(xaml): binding trailing space error message

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/SourceGenerators/XamlGenerationTests/RawNumericalEnumValue.xaml
- src/SourceGenerators/XamlGenerationTests/RawNumericalEnumValue.xaml.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Markup/Given_XamlReader.cs
- src/Uno.UI/DataBinding/BindingPropertyHelper.FastConvert.cs
GitHub Issue (If applicable): closes #9067
- Feature
Raw numerical enum values (ex: `<StackPanel Orientation="2" />`) are not supported in xaml.
Added support for raw numerical enum values
It is only the fast path (FastStringToXYZ; no reflection) code that doesn't support numerical values, so we only need to fix these.
Everything else that isn't optimized uses Enum.Parse which handles numerical value already, like `<ListView SelectionMode="2" />` works without this fix.
> feat(xaml): add support for raw numerical enum values

- src/Uno.UI.Foldable/FoldableApplicationViewSpanningRects.Android.cs
- src/Uno.UI.Foldable/FoldableHingeAngleSensor.Android.cs
- src/Uno.UWP/Devices/Sensors/Helpers/INativeDualScreenProvider.cs
- src/Uno.UWP/UI/ViewManagement/ApplicationView.cs
- Bugfix
When running on Surface Duo `ApplicationView.IsViewModeSupported(ApplicationViewMode.Spanning)` returns `false`
To detect foldable we check both `HasFoldFeature` and `HasHinge`.
> fix: Fallback for foldable detection

- src/Uno.UI/UI/Xaml/Controls/FlipView/NativePagedView.Android.cs
GitHub Issue (If applicable): closes #8637
- Bugfix
When using the `FlipVliew` (or Selector and swiping to change the selected item, the new item selected is not displayed correctly.
> fix(droid): FlipView not displaying items correctly

- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/Simple_Text_Arabic.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/Simple_Text_Arabic.xaml.cs
- src/Uno.UI/UI/Xaml/Documents/InlineCollection.skia.cs
- src/Uno.UI/UI/Xaml/Documents/TextFormatting/RenderLine.skia.cs
GitHub Issue (If applicable): closes #6783
- Bugfix
Runs of RTL text segments render in reverse order.
RTL segments render in the correct order.
> fix(TextBlock): [Skia] Fix RTL segment ordering

- src/SamplesApp/UITests.Shared/Windows_Devices/LampTests.xaml.cs
For an unclear reason the Windows.Devices.Lamp test page often fails in Snapshot tests. it is possible that the root cause is one of the previous pages in some way, as there is nothing special about this sample.
Ignoring sample in snapshot tests 🤷‍♂️
> chore: Ignore Lamp test page in snapshot tests

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ContentPresenter.cs
- src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.cs
GitHub Issue (If applicable): closes #9361
Previously content alignement properties on ContentPresenter were overriding the alignment of the child, which did not work properly in many cases (especially when the alignment was directly set on the content element). Instead ContentPresenter should arrange the content based on the content alignment properties.
Content presenter alignment behaves correctly.
> fix: `ContentPresenter` content alignment

- src/Uno.UI.Runtime.Skia.Gtk/GtkCoreWindowExtension.cs
- src/Uno.UI.Runtime.Skia.Gtk/GtkHost.cs
- src/Uno.UI.Runtime.Skia.Gtk/UnoEventBox.cs
closes https://github.com/unoplatform/uno/issues/8465
Improve support of touch screens on linux (Skia GTK)
On touch devices which are sending event through the "touch handler" we are receiving touch events twice (first as "emulated mouse" and then as real "touch"). So in "mouse events handlers", we are filtering out events issued by touch input device.
The issue is that on some devices (like Raspberry PI), we are getting only the "emulated" events through the "mouse handlers", driving touch pointers to be completely ignored.
We have updated the subscription to native events, in order get touch event only once, so are no longer filtering-out events issued by touch devices in the "mouse events handlers".
> fix(pointers): Improve support of touch screens on linux (Skia GTK)

- doc/articles/features/using-linux-framebuffer.md
- src/Uno.UI.Runtime.Skia.Gtk/GtkDisplayInformationExtension.cs
- src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/CoreWindowExtension.Touch.cs
- src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/DisplayInformationExtension.cs
- src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/FrameBufferDevice.cs
- src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/FramebufferHost.cs
- src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/Renderer.cs
- src/Uno.UI.Runtime.Skia.Tizen/TizenDisplayInformationExtension.cs
- src/Uno.UI.Runtime.Skia.Wpf/WpfDisplayInformationExtension.cs
- src/Uno.UWP/Graphics/Display/DisplayInformation.skia.cs
- src/Uno.UWP/Graphics/Display/DisplayInformation.unsupported.cs
- src/Uno.UWP/Graphics/Display/IDisplayInformationExtension.skia.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/pull/9395, closes https://github.com/unoplatform/uno/issues/9394, https://github.com/unoplatform/uno/discussions/8737
- Feature
- Adds Framebuffer DPI scaling support, overridable from an environment variable
- Adds Framebuffer 16 Bits RGB565 color depth.
> [Framebuffer] Support for DPI scaling and 16 bits RGB565 color depth

- README.md
The link for https://dotnet.microsoft.com/ doesn't render properly in the [README.md](https://github.com/unoplatform/uno/blob/master/README.md) markdown.
> [.NET] (https://dotnet.microsoft.com/)
The link for https://dotnet.microsoft.com/ is rendered properly in the [README.md](https://github.com/unoplatform/uno/blob/master/README.md) markdown.
> [.NET](https://dotnet.microsoft.com/)
N/A
N/A
> docs: fixed malformed link in README.md

- doc/articles/get-started-dotnet-new.md
Currently in the "Get Started" guide the `dotnet new` command has invalid parameters:
```sh
dotnet new unoapp-uwp-net6 -o MyApp -mobile=false
```
`-mobile` does not exist. Either `-m` or `--Mobile`. For the sake of introduction the long form is preferred.
The new version takes `--Mobile` as argument.
> fix: Wrong CLI command for exlcuding mobile in get started

- src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/FrameBufferDevice.cs
- src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/Renderer.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/9422
- Bugfix
- The Framebuffer renderer now takes into account the possible padding of scanlines
- Fixes invalid 32bits pixel format
> fix(framebuffer): Use scanline copy to adjust for padding when required

- src/Uno.UI.Tests/WeakReferencePool/Given_WeakReferencePool.cs
`When_WeakReferenceProvider_Collected` is now passing properly, with scoped testing of collected references updated.
> test: Adjust weak reference testing for implicit capture change in behavior

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/ButtonControls/Button_Flyout_TemplateBinding.xaml
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/ButtonControls/Button_Flyout_TemplateBinding.xaml.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Button.cs
- src/Uno.UI/UI/Xaml/Controls/Flyout/FlyoutBase.cs
- src/Uno.UI/UI/Xaml/Controls/MenuFlyout/MenuFlyoutPresenter.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/1884
- Bugfix
Manually propagates the `TemplatedParent` to the children of `MenuFlyoutPresenter`
> fix(MenyFlyoutPresenter): Fix TemplatedParent propagation in MenuFlyoutPresenter

- src/SamplesApp/SamplesApp.net6mobile/MacCatalyst/Info.plist
- src/Uno.UI/Controls/Window.iOS.cs
- src/Uno.UI/UI/Xaml/Window.iOS.cs
- src/Uno.UWP/Generated/3.0.0.0/Windows.UI.Core/CoreWindow.cs
- src/Uno.UWP/Generated/3.0.0.0/Windows.UI.Core/ICoreWindow.cs
- src/Uno.UWP/System/VirtualKeyHelper.iOS.cs
- src/Uno.UWP/UI/Core/CoreWindow.iOS.cs
- src/Uno.UWP/UI/Core/ICoreWindow.cs
- src/Uno.UWP/UI/Core/ICoreWindowsEvents.iOS.cs
GitHub Issue (If applicable): closes #9071
- Feature
Mac Catalyst apps do not support Keyboard Events
> (Catalyst) Add KeyEvent Support

- build/PackageDiffIgnore.xml
- src/Uno.UI/FeatureConfiguration.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/SinglelineTextBoxView.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.iOS.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/9430
- Bugfix
This change is needed to make the `SinglelineTextBoxView.SelectedTextRange` conditional, and avoid changing the value provided to UIKit. This breaks the use of `TextBox.SelectionChanged`, but can be restored by using the `FeatureConfiguration.TextBox.IOS16EnableSelectionSupport` feature flag if the issue ends up being fixed in UIKit. 
See https://github.com/unoplatform/uno/issues/9430 for more details.
> fix(TextBox): [iOS] Add temporary workaround for iOS 16 on selection with UITextField

- build/uno.winui.common.targets
- src/Common.targets
- src/Uno.UI.Runtime.Skia.Gtk/buildTransitive/Uno.UI.Runtime.Skia.Gtk.targets
- src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/buildTransitive/Uno.UI.Runtime.Skia.Linux.FrameBuffer.targets
- src/Uno.UI.Runtime.Skia.Tizen/buildTransitive/Uno.UI.Runtime.Skia.Tizen.targets
- src/Uno.UI.Runtime.Skia.Wpf/buildTransitive/Uno.UI.Runtime.Skia.Wpf.targets
- src/Uno.UI.Runtime.WebAssembly/buildTransitive/Uno.UI.Runtime.WebAssembly.targets
According this discussion: https://github.com/unoplatform/uno/discussions/9145
The first PR for this, while fixing the name collision, didn't fix the availability of the constants and led to new research.
Feature
At the moment, constants are added after the .editorconfig file with visible properties is generated, which generators use to access values. Here is the relevant code that shows which Targets are executed and in what order to allow generators to access properties.
https://github.com/dotnet/roslyn/blob/1c3cdb0b85a8496a8f5108faab046924360b6017/src/Compilers/Core/MSBuildTask/Microsoft.Managed.Core.targets#L155-L196
Based on this, I believe that the optimal place to add constants would be …
> feat: Targets with constants moved to an earlier stage.

- src/SamplesApp/SamplesApp.Shared/App.xaml.cs
- Feature
When debugging Uno in multiple instances, it is sometimes hard to tell which window belongs to which instance.
Samples app shows path in its title bar when debugging.
> feat: Include repository path in Samples app title bar

- doc/articles/features/using-linux-framebuffer.md
- src/SamplesApp/SamplesApp.Shared/App.xaml.cs
- src/SamplesApp/SamplesApp.Skia.Linux.FrameBuffer/Program.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/ApplicationTests/Given_Application.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/ApplicationTests/Given_Application.xaml.cs
- src/SolutionTemplate/UnoSolutionTemplate.WinUI.net6/Skia.Linux.FrameBuffer/Program.cs
- src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/ApplicationExtension.cs
- src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/FramebufferHost.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_ViewManagement_ApplicationView/Given_Control.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/discussions/9473
- Bugfix
- Adds support for `Application.Exit`
- Support for terminal keyboard interception to avoid characters to be visible
> [Framebuffer] Support Application.Exit and terminal console interception

- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/Given_XamlReader.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/When_StaticResource_In_ResourceDictionary.xamltest
- src/Uno.UI/UI/Xaml/Markup/Reader/XamlObjectBuilder.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/9524
- Bugfix
Ensures that inline StaticResources markup in a ResourceDictionary gets resolved property.
> feat: Add support for StaticResource loading inside a ResourceDictiomary

- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/Given_XamlReader.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/TestCodedResourceDictionary.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/When_StaticResource_In_Explicit_ResourceDictionary.xamltest
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/When_StaticResource_In_Explicit_ResourceDictionary_And_MergedDictionaries.xamltest
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/When_StaticResource_In_Explicit_ResourceDictionary_And_ThemeResources.xamltest
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/When_StaticResource_MergedDictionaries_Fluent.xamltest
- src/Uno.UI/UI/Xaml/Markup/Reader/XamlObjectBuilder.cs
- src/Uno.UI/UI/Xaml/Markup/Reader/XamlTypeResolver.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/9548
- Feature
- Adds `XamlReader` support for `ThemeDictionaries`
- Adds `XamlReader` support for `MergedDictionaries`
> XamlReader support for `ThemeDictionaries` and `MergedDictionaries`

- src/Uno.UI/Extensions/CGRectExtensions.iOSmacOS.cs
- src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.Android.cs
- src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.cs
- src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.iOSmacOS.cs
- src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.net.cs
- src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.netstdref.cs
- src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.skia.cs
- src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.wasm.cs
GitHub Issue (If applicable): closes #9208
- Bugfix
iOS border can only be drawn with perfect circles, not ellipses.
iOS border should support most of the scenarios.
re: #5440, #6891
> fix(ios): border + corner rendering

- src/SourceGenerators/System.Xaml/System.Windows.Markup/StaticResourceExtension.cs
- src/Uno.UI/XmlnsDefinitionAttribute.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/982
- Feature
Improve intellisense support for `StaticResource` and `Color` starting from VS 17.4 Preview 1.
> feat: Add missing StaticResourceExtensions for VS intellisense

- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/RefreshContainerTests/RefreshContainerScrollTop.xaml
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/RefreshContainerTests/RefreshContainerScrollTop.xaml.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/Uno.UI/Microsoft/UI/Xaml/Controls/PullToRefresh/Native/NativeRefreshControl.Android.cs
GitHub Issue (If applicable): closes #9578
- Bugfix
Currently the `RefreshContainer` starts refreshing regardless of `ScrollViewer` offset.
Fixed.
> fix: Handle `ScrollViewer` scroll to top in Android `RefreshContainer`

- src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props
GitHub Issue (If applicable): https://github.com/unoplatform/uno/discussions/9562
- Bugfix
Applies a workaround for duplicate analyzers issue introduced around https://github.com/dotnet/wpf/issues/6792
> fix: Remove duplicate analyzers

- build/PackageDiffIgnore.xml
- src/SamplesApp/SamplesApp.iOS/SamplesApp.iOS.csproj
- src/Uno.UI/Controls/Window.iOS.cs
- src/Uno.UI/FeatureConfiguration.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/MultilineTextBoxView.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/SinglelineTextBoxView.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.iOS.cs
- Bugfix
`UITextInput.SelectedTextRange` crashes on iOS 16 betas
Updated workaround to avoid the runtime crash while keeping the `UITextInput.SelectedTextRange` functionality available.
Pro: It does not break app compatibility, selection works
Con: This does not work _currently_ with the dynamic registrar [1] which is the default when building for iOS simulators. OTOH there's a workaround for that [2].
[1] Unless building with the iOS SDK for Xcode 14 (currently only previews) once https://github.com/xamarin/xamarin-macios/pull/15712 is merged
[2] Adding `--registrar=static` to the simulator builds will fix this, sadly build times will be longer …
> fix: Updated workaround for iOS 16 `UITextInput.SelectedTextRange` crashes

- .vsts-ci.yml
- build/Uno.UI.Build.csproj
- src/SamplesApp/SamplesApp.iOS/SamplesApp.iOS.csproj
- src/Uno.UI/Controls/Window.iOS.cs
- src/Uno.UI/FeatureConfiguration.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/MultilineTextBoxView.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/SinglelineTextBoxView.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.iOS.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/9430
> Backport #9559 and #9484 for 3.11.x

- src/Uno.UI.RuntimeTests/Tests/Windows_Storage/Streams/Given_InMemoryRandomAccessStream.cs
- src/Uno.UWP/Generated/3.0.0.0/Windows.Storage.Streams/InMemoryRandomAccessStream.cs
- src/Uno.UWP/Storage/Streams/InMemoryRandomAccessStream.cs
> feat: InMemoryRandomAccessStream

- build/uno.winui.common.targets
- src/SamplesApp/SamplesApp.net6mobile/SamplesApp.net6mobile.csproj
- src/SolutionTemplate/UnoSolutionTemplate.WinUI.net6/Mobile/UnoQuickStart.Mobile.csproj
- src/SolutionTemplate/UnoSolutionTemplate.net6/Mobile/UnoQuickStart.Mobile.csproj
- src/SolutionTemplate/UnoSolutionTemplate/iOS/UnoQuickStart.iOS.csproj
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/9430
- Bugfix
- Fail the build when the static registrar is not detected when building for the iPhone Simulator.
- Adjusted templates to include static registrar requirement
> fix: Ensure static registrar is enabled when the iOS simulator is used

- src/SourceGenerators/Uno.UI.SourceGenerators/BindableTypeProviders/BindableTypeProvidersGenerationTask.cs
- Feature
Known missing types validation can be disabled by defining the `UNO_DISABLE_KNOWN_MISSING_TYPES` constant.
> feat: Add the ability to disable `_knownMissingTypes` validation

- src/Uno.UI.FluentTheme.v1/Uno.UI.FluentTheme.v1.net6.csproj
- src/Uno.UI.FluentTheme.v2/Uno.UI.FluentTheme.v2.net6.csproj
- src/Uno.UI.FluentTheme/Uno.UI.FluentTheme.net6.csproj
- src/Uno.UI.Toolkit/Uno.UI.Toolkit.net6.csproj
- src/Uno.UI/Uno.UI.net6.csproj
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/9632
Disabled because of a performance issue, where the `LinkerDefinitionMergerTask` take about 4 minutes to run on CI.
> ci: Disable trimming generation for net6 mobile targets

- doc/articles/feature-flags.md
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs
- src/Uno.UI/FeatureConfiguration.cs
- src/Uno.UI/Helpers/ListViewHelper.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/Legacy/ListViewBase.Legacy.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.Android.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/NativeListViewBase.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.Android.cs
GitHub Issue (If applicable): unoplatform/uno.toolkit.ui#283
- Bugfix
On Android, calling `NativeListViewBase.SmoothScrollToPosition` throws a silent native error.
You can now programmatically scroll `ListView` with animation on android.
iOS and Android `ListViewBase.NativePanel` has been made `public`ly accessible.
> feat(droid): ListView smooth scrolling

- src/Uno.UWP/Globalization/ApplicationLanguages.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/9652
- Bugfix
Failure do detect current culture does raise an exception, uses invariant culture instead.
> fix(skia): Fail safe on invariant culture

- src/SourceGenerators/Uno.UI.Tasks/Content/Uno.UI.Tasks.targets
Use the .NET linker to improve the performance, as the embedded linker was an earlier build which has performance issues.
> feat: Use dotnet SDK linker when available

- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/RefreshContainerTests/RefreshContainerNavigation.xaml
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/RefreshContainerTests/RefreshContainerNavigation.xaml.cs
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/RefreshContainerTests/RefreshContainerNavigationFirstPage.xaml
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/RefreshContainerTests/RefreshContainerNavigationFirstPage.xaml.cs
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/RefreshContainerTests/RefreshContainerNavigationSecondPage.xaml
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/RefreshContainerTests/RefreshContainerNavigationSecondPage.xaml.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/Uno.UI/Microsoft/UI/Xaml/Controls/PullToRefresh/Native/RefreshContainer.iOS.cs
- Bugfix
After unloading `RefreshContainer`, reloading it again does not allow refreshing.
Refreshing is possible even after unloading and reloading.
> fix: Retain refresh-ability of `RefreshContainer` through navigation

- src/Uno.UI.FluentTheme.v1/Resources/Version1/PriorityDefault/ToggleSwitch_themeresources.xaml
- src/Uno.UI.FluentTheme.v1/themeresources_v1.xaml
- src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault/ToggleSwitch_themeresources.xaml
- src/Uno.UI.FluentTheme.v2/themeresources_v2.xaml
GitHub Issue (If applicable): closes #9507, closes #8636
- Bugfix
fluent style ToggleSwitch doesnt properly reset its visual when transitioned from "On" to "Off" visual-states.
the visual should now properly resets.
> fix(ToggleSwitch): add workaround for visual states

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement.cs
- src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml/FrameworkElement.cs
- src/Uno.UI/UI/Xaml/FrameworkElement.skia.cs
- src/Uno.UI/UI/Xaml/FrameworkElement.wasm.cs
- src/Uno.UI/UI/Xaml/UIElement.skia.cs
- src/Uno.UI/UI/Xaml/UIElement.wasm.cs
GitHub Issue (If applicable): closes #8633
- Feature
Previously `NameProperty` was not used on Skia and WASM, so setting `Name` did not change its value.
`NameProperty` is used as backing store for `Name` and their changes also affect `AutomationIdProperty`
> feat: Use `NameProperty` in Skia and WASM

- doc/articles/features/custom-fonts.md
- src/Uno.UI.Runtime.WebAssembly/Xaml/Media/FontFamilyHelper.cs
- src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.wasm.cs
- src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlockMeasureCache.MeasureEntry.cs
- src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlockMeasureCache.MeasureKey.cs
- src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlockMeasureCache.cs
- src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlockMeasureCache.wasm.cs
- src/Uno.UI/UI/Xaml/FontFamilyLoader.wasm.cs
- Bugfix
- Ensures that TextBlock measure cache gets cleared when a font is loaded
- Adds missing `FontHelper` visible from Wasm apps
> [Wasm] Ensures that TextBlock measure cache gets cleared when a font is loaded

- build/uno.winui.common.targets
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/9723
- Bugfix
When some publish targets are invoked, the targets defining `_AndroidApiLevel ` may not be executed, causing `ValidateUnoUIAndroid` to fail. We can ignore this execution as for normal build scenarios, the property is defined properly.
> fix: Don't fail on missing `_AndroidApiLevel` for min API level validation

- src/Uno.UI.Runtime.Skia.Gtk/OpenGLESRenderSurface.cs
GitHub Issue (If applicable): #9099
- Bugfix
Avoids native exceptions raised during opengl detection to terminate the app.
> fix(gtk): [Linux] Ensure that missing libGLESv2.so does not break the runtime

- src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props
- Bugfix
Restores compatibility with VS 16.x
> fix: remove vs17 specific use of `[MSBuild]::VersionGreaterThan`

- src/Directory.Build.props
- src/SourceGenerators/Uno.UI.SourceGenerators/BindableTypeProviders/BindableTypeProvidersGenerationTask.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/DependencyObject/DependencyObjectGenerator.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/DependencyObject/DependencyPropertyGenerator.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/Helpers/SymbolExtensions.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/Uno.UI.SourceGenerators.csproj
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/Utils/XBindExpressionParser.PathRewrite.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.Reflection.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileParser.cs
- src/SourceGenerators/Uno.UI.Tasks/Content/Uno.UI.Tasks.targets
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/7506
- Perf
- perf: Remove unused Uno.CodeGen from SamplesApp.Skia
- perf: Use GetXXWithName for members lookups
- fix: Don't use static storage for errors on invalid properties 
- perf: Enable Roslyn-based generators for internal Uno-Skia build
- perf: Don't copy roslyn binaries to the output to enable VBCSCompiler… 
- perf: Enhance lookups in FindSubElementByName 
- ci: use GetMethodsWithName
- perf: Reduce memory allocations when parsing XAML files
> Misc performance improvements in XAML generation

- src/SamplesApp/SamplesApp.Shared/App.xaml.cs
- src/Uno.UI.Runtime.Skia.Gtk/GLValidationSurface.cs
- src/Uno.UI.Runtime.Skia.Gtk/GtkHost.cs
- src/Uno.UI.Runtime.Skia.Gtk/OpenGLRenderSurface.cs
GitHub Issue (If applicable): #9099 
- Bugfix
fix(gtk): Align validation surface to the OpenGLRender surface version
fix(gtk): Pre-validate OpenGL support to avoid initializing on macOS
fix(gtk): Show an error message when GL_ARB_vertex_array_object is not available.
> [Gtk] macOS and GL additional validations

- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.wasm.cs
- src/Uno.UI/WasmCSS/Uno.UI.css
It looks like ***all*** `TextBox`es have `cursor: text;` styling. This PR adds it to `Uno.UI.css` to avoid `SetStyle` calls.
FYI @Xiaoy312 
- Performance
`SetStyle("cursor", "text")` is called for every `TextBox`
Now `cursor: text;` is set for all `TextBox`es via `Uno.UI.css` and unnecessary `SetStyle` calls are eliminated.
> perf: Avoid unnecessary `SetStyle` call for TextBox

- src/T4Generator/T4Generator.csproj
Analyzers are not run on T4Generator project.
Analyzers are now run on T4Generator project
> build: Remove workaround to remove analyzers

- src/Uno.UI.Runtime.Skia.Wpf/Extensions/UI/Xaml/Controls/TextBoxViewExtension.cs
- src/Uno.UI.Runtime.Skia.Wpf/Themes/Generic.xaml
GitHub Issue (If applicable): closes #9544
https://user-images.githubusercontent.com/31348972/186964932-e1424a30-28ad-4976-8da7-59cdec15a299.mp4
Needs a bit of improvement. @MartinZikmund Since you worked on something similar, can you help with what's remaining?
- Bugfix
WPF is not obscuring password in PasswordBox.
WPF is now obscuring password in PasswordBox.
> fix: Fix PasswordBox on WPF

- src/Uno.UI.RuntimeTests/Tests/Microsoft_UI_Xaml_Controls/Given_RefreshContainer.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/PullToRefresh/Native/NativeRefreshControl.Android.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/PullToRefresh/RefreshContainer/RefreshContainer.xaml
- src/Uno.UI/UI/Xaml/Style/mergedstyles.xaml
GitHub Issue (If applicable): closes #9761
- Bugfix
`RefreshContainer` content alignment is broken by native android layouting repeated after our arrange.
- Avoid second native layout after our arrange
- Ensure `ContentTemplate` and `ContentTemplateSelector` are properly applied.
> fix: RefreshContainer content alignment

- build/PackageDiffIgnore.xml
- build/Uno.UI.Build.csproj
- doc/articles/uno-development/building-uno-ui.md
- src/Directory.Build.props
- src/Directory.Build.targets
- src/PlatformItemGroups.props
- src/SourceGenerators/System.Xaml/Uno.Xaml.csproj
- src/SourceGenerators/System.Xaml/Uno.Xaml.net6.csproj
- src/SourceGenerators/XamlGenerationTests.Core/XamlGenerationTests.Core.csproj
- src/SourceGenerators/XamlGenerationTests/XamlGenerationTests.csproj
- src/Uno.CrossTargetting.props
- src/Uno.UI.BindingHelper.Android/Uno.UI.BindingHelper.Android.csproj
- src/Uno.UI.BindingHelper.Android/Uno.UI.BindingHelper.Android.net6.csproj
- src/Uno.UI.Composition/Uno.UI.Composition.csproj
- src/Uno.UI.Composition/Uno.UI.Composition.net6.csproj
- src/Uno.UI.Dispatching/Uno.UI.Dispatching.csproj
- src/Uno.UI.Dispatching/Uno.UI.Dispatching.net6.csproj
- src/Uno.UI.RemoteControl/Uno.UI.RemoteControl.Skia.csproj
- src/Uno.UI.RemoteControl/Uno.UI.RemoteControl.Wasm.csproj
- src/Uno.UI.RemoteControl/Uno.UI.RemoteControl.csproj
- src/Uno.UI.RemoteControl/Uno.UI.RemoteControl.net6.csproj
- src/Uno.UI.XamlHost/Uno.UI.XamlHost.net6.csproj
- src/Uno.UI/Resources/Resource.designer.g.Android.cs
- src/Uno.UI/Uno.UI.csproj
- src/Uno.UI/Uno.UI.net6.csproj
- src/Uno.UWP/Uno.csproj
- src/Uno.UWP/Uno.net6.csproj
The Uno.UI build now skips the creation of android resources designer classes, which are not used by uno itself (or in very rare occasions), therefore making the build significantly faster, but also reduces the size of the app and provides better startup time.
> Improve android build time and assembly size

- src/Uno.UI/UI/Xaml/Application.skia.cs
GitHub Issue (If applicable): closes #8661
- Bugfix
Under WSL, the default locale is set to invariant UTF-8:
Under this configuration, the `CurrentUICulture` is set to a culture with same attributes as `InvariantCulture` (but not the same instance, `==` returns `false`). This leads to most WinUI controls resources not being loaded (as they are specific culture, e.g. `en-US`).
During Skia application initialization, we check whether `CurrentUICulture` is invariant, and if yes, we fall back to English.
> fix: Ensure culture is not set to invariant culture in WSL

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media_Animation/Given_ObjectAnimationUsingKeyFrames.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/9282
Disable often failing runtime tests for macOS specifically.
> ci: Disable often faiing macOS runtime tests

- doc/articles/get-started-vscode.md
* Introduction only mention WebAssembly (not Gtk+)
* Mention net6 but links to net5 download page
* Introduction mention both WebAssembly and Gtk+
* Fixed URL to download net6
> docs: Update app scope and dotnet link

- src/Uno.UI.Runtime.Skia.Gtk/GLRenderSurfaceBase.cs
- src/Uno.UI/UI/Xaml/XamlRoot.netstd.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/9813
- Bugfix
Ensures that Visuals rendering happens only when requested.
> fix(skia): Ensure that visuals rendering happens in the correct order

- src/crosstargeting_override.props.sample
- Bugfix
double-dashes `--` are not permitted within comments
updated the table with different "border" characters
regression from #9829
> fix: invalid xml syntax in crosstargeting_override.props.sample

- src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault/ToggleButton_themeresources.xaml
- src/Uno.UI.FluentTheme.v2/themeresources_v2.xaml
GitHub Issue (If applicable): https://github.com/unoplatform/uno/discussions/9863, closes #8988
- Bugfix
Adjust ToggleButton invalid visual state syntax for fluent v2.
> fix(fluent): Adjust ToggleButton invalid visual state

- src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBaseSource.iOS.cs
GitHub Issue (If applicable): closes #9416
- Bugfix
When Scrolling over a ListView some items are not properly measured (not visible because of their size)
> fix(iOS): ListView empty items when scrolling

- build/Uno.UI.Build.csproj
- src/SolutionTemplate/UnoSolutionTemplate.WinUI.net6/Mobile/UnoQuickStart.Mobile.csproj
- src/SolutionTemplate/UnoSolutionTemplate.WinUI.net6/Skia.Gtk/UnoQuickStart.Skia.Gtk.csproj
- src/SolutionTemplate/UnoSolutionTemplate.WinUI.net6/Skia.Linux.FrameBuffer/UnoQuickStart.Skia.Linux.FrameBuffer.csproj
- src/SolutionTemplate/UnoSolutionTemplate.WinUI.net6/Skia.WPF/UnoQuickStart.Skia.WPF.csproj
- src/SolutionTemplate/UnoSolutionTemplate.WinUI.net6/Wasm/UnoQuickStart.Wasm.csproj
- src/SolutionTemplate/UnoSolutionTemplate.WinUI.net6/WinUI/UnoQuickStart.Windows.csproj
GitHub Issue (If applicable): closes #9812
Adds the Uno.UI.Lottie package in all template projects.
Controls like ProgressRing not working by default.
Controls like ProgressRing working by default.
> Chore: Add Uno.UI.Lottie package in template projects

- src/SamplesApp/SamplesApp.UITests/Toolkit/VisibleBoundsPadding_Tests.cs
- src/SamplesApp/UITests.Shared/Toolkit/VisibleBoundsPadding_Modal.xaml
- src/SamplesApp/UITests.Shared/Toolkit/VisibleBoundsPadding_Modal.xaml.cs
- src/SamplesApp/UITests.Shared/Toolkit/VisibleBoundsPadding_Modal_Test.xaml
- src/SamplesApp/UITests.Shared/Toolkit/VisibleBoundsPadding_Modal_Test.xaml.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/Uno.UI/Behaviors/VisibleBoundsPadding.cs
closes https://github.com/unoplatform/nventive-private/issues/412
- Bugfix
VisibleBoundsPadding calculates improper offsets when the control is within a native iOS Modal window. We were using `TransformToVisual` relative to `Windows.Current.Content` which results in an offset of X=16, Y=47 since the Window.Content (white background) is no longer at position 0,0 while a modal (red background) is being displayed
Use `TransformToVisual(null)` to ensure that the root of the XAML tree is used for the transformation
> fix(VisibleBoundsPadding): Ensure the proper root is used to compute relative bounds

- src/Uno.UI.Tests/Resources/Given_ResourceCandidate.cs
- src/Uno.UWP/ApplicationModel/Resources/Core/ResourceCandidate.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/7431
- Bugfix
This change avoids parts leading to the resource file that contain culture-compatible string to be used instead of the appropriate culture name.
> fix: Parse cultures from last to first

- build/ci/templates/dotnet6-install-mac.yml
- build/ci/templates/dotnet6-install-windows.yml
- src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props
- Bugfix
This issue got fixed in .NET 6.0.401.
> fix: Remove WPF issue #6792 workaround

- .github/workflows/winui-autoconvert.yml
The change uses a forced overwrite of the branch instead of trying a merge. This branch will keep using the latest conversion at this time, until we can find a better synchronization solution and keep the history.
> ci: Adjuts winui-generated branch

- src/SolutionTemplate/UnoSolutionTemplate.WinUI.net6/Mobile/UnoQuickStart.Mobile.csproj
- src/SolutionTemplate/UnoSolutionTemplate.net6/Mobile/UnoQuickStart.Mobile.csproj
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/9822
- Bugfix
Don't define default `RuntimeIdentifier` to let Visual Studio specify it through the debug target selector UI.
> fix(vsix): Adjust net6 templates to avoid defining default RuntimeIdentifier

- build/uno.winui.single-project.targets
- src/SamplesApp/SamplesApp.net6mobile/SamplesApp.net6mobile.csproj
GitHub Issue (If applicable): https://github.com/unoplatform/uno/discussions/9513
- Bugfix
Additional capabilities are required for the debugging tooling to be available in VS 17.4 Preview 1 and later.
> fix: Adjust for net6/7 debugging in VS 2022 17.4 Preview 1

- src/Uno.UI/Controls/CommandBar/CommandBarHelper.iOS.cs
- src/Uno.UI/Controls/NativeFramePresenter.iOS.cs
- src/Uno.UI/Extensions/ViewExtensions.visual-tree.cs
- src/Uno.UI/NativeFramePresenter.Android.cs
GitHub Issue (If applicable): re: unoplatform/uno.toolkit.ui#307
- Bugfix
When navigating to an external view/controller and back, the NavigationBar re-initializes with the UIViewController (native concept) with the wrong instance of NavigationBar (toolkit control). This desync prevents the NavigationBar from updating.
^ not happening anymore.
> fix(ios): nested page's CommandBar desync when returning from controller

- src/Uno.UI/UI/Xaml/Controls/Popup/PopupPanel.cs
https://github.com/unoplatform/uno/issues/9943
- Bugfix
ComboBox Popup will not display on iOS as a result of a null ref within the layout logic of PopupPanel
PopupPanel does not crash and the combobox popup is displayed
> fix: Avoid null-ref, fallback to VisibleBounds is XamlRoot is null

- src/SamplesApp/SamplesApp.Droid/SamplesApp.Droid.csproj
- src/SamplesApp/SamplesApp.UITests.Generator/SnapShotTestGenerator.cs
- src/SamplesApp/SamplesApp.UITests.Generator/Uno.Samples.UITest.Generator.csproj
The generator was crashing, and the exception was turning into a compiler warning. Since we don't yet treat all warnings as errors, this was missed.
It was likely broken due to version mismatch described here https://github.com/unoplatform/uno/blob/2738b04461e4e798a77afce8afd4d2fb8065b795/src/SamplesApp/SamplesApp.UITests.Generator/Uno.Samples.UITest.Generator.csproj#L17-L21
This commit (4a0580d) turns the exception into an error diagnostic, so that CI fails if any exception is thrown.
In the next commits, I'll get rid of the Workspaces dependency completely.
------
This commit moves us away from using Workspaces APIs.
------
This commit is minor code cleanup.
> fix(gen): Report error diagnostic on SnapShotTestGenerator exceptions and avoid Workspaces dependency

- src/Uno.UI/Microsoft/UI/Xaml/Controls/Breadcrumb/BreadcrumbBarItem.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/PipsPager/PipsPager.cs
- Bugfix
The WinUI revert branch cannot be built locally as there are duplicate namespaces.
Avoid duplicate namespaces.
> chore: Avoid duplicate usings for WinUI build

- src/Uno.UI.Tests/Windows_UI_Xaml/Given_Window.cs
- src/Uno.UI/UI/Xaml/Window.Android.cs
- src/Uno.UI/UI/Xaml/Window.Desktop.cs
- src/Uno.UI/UI/Xaml/Window.cs
- src/Uno.UI/UI/Xaml/Window.iOS.cs
- src/Uno.UI/UI/Xaml/Window.macOS.cs
- src/Uno.UI/UI/Xaml/Window.skia.cs
- src/Uno.UI/UI/Xaml/Window.wasm.cs
- Bugfix
In case user uses WinUI-style initialization of `Window`, `Window.Current` will remain `null`, even though Uno currently supports only single-window scenarios. Some internal APIs still rely on `Window.Current`.
When a `Window` is activated and no "current" window is yet set, this window will become `Current`
> fix: Ensure `Window.Current` is set when `Window` is newed up

- .vsts-ci.yml
- build/Uno.UI.Build.csproj
- build/ci/.azure-devops-package-generic.yml
- build/ci/.azure-devops-package-net6-win.yml
- build/ci/.azure-devops-package.yml
- build/ci/.azure-devops-winui-convert.yml
- build/ci/templates/download-winui-converted-tree.yml
- src/SamplesApp/SamplesApp.UWP.Design/SamplesApp.UWP.Design.csproj
- src/SourceGenerators/Uno.UI.Tasks/Content/Uno.UI.Tasks.targets
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/9986, closes #9951
- Bugfix
- Adjust the generation of javascript helpers for WinUI
- Move WinUI tree generation to a separate step for reuse
> fix: Generated javascript content is not embedded at the right place

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/enhancement.md
- .github/ISSUE_TEMPLATE/samples-request.md
- Removed XF WebAssembly Renderers (not supported)
- Added Linux Framebuffer
> Issue templates update

- doc/articles/features/windows-ui-xaml-xbind.md
- src/SourceGenerators/Uno.UI.SourceGenerators.Tests.Shared/Given_XBindRewriter.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/Utils/XBindExpressionParser.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/xBind_PathLessCasting.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/xBind_PathLessCasting.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/xBind_PathLessCasting_Template.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/xBind_PathLessCasting_Template.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Given_xBind_Binding.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/7893
- Feature
Adds support for https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/x-bind-markup-extension#pathless-casting
> feat(xbind): Add pathless casting support

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/BorderTests/Border_Tests.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/BorderTests/Border_CornerRadius.xaml
- src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.wasm.cs
GitHub Issue (If applicable): The Wasm part of #5440. Other platforms still need a fix. I'll take a look to see if I'm able to.
- Bugfix
If the CornerRadius is larger than half of element width or larger than half of element height, the clipping is done as a circular shape, which doesn't match UWP/WinUI behavior.
The CornerRadius is now applied correctly as an elliptic shape.
> fix(Wasm): Fix BorderRadius not rendering properly when it's greater than half of width or height

- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/Given_XamlReader.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/When_Empty_ResourceDictionary_As_Resources.xamltest
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/When_Empty_ThemeDictionaries.xamltest
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/When_StaticResource_In_Themed_ResourceDictionary.xamltest
- src/Uno.UI/UI/Xaml/Markup/Reader/XamlObjectBuilder.cs
Providing the following XAML were crashing the `XamlReader`:
``` xml
<Border>
<Border.Resources>
<ResourceDictionary />
</Border.Resources>
</Border>
```
Repro in Playground: https://playground.platform.uno/#b7f828c1
Fixed
- ~~[ ] Docs have been added/updated which fit [documentation template]~~
- ~~[ ] Associated with an issue (GitHub or internal) and uses the [automatic close keywords]~~
> Fixed a potential NullRef exception in XamlReader

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Media/ImageBrushTests/ImageBrush_Stretch.cs
- src/Uno.UI.RuntimeTests/Helpers/ImageAssert.cs
- src/Uno.UI.RuntimeTests/Helpers/RawBitmap.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement_Opacity.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media/Given_ImageBrushStretch.cs
Issue  #9811
The test Was in Sample app test. The test is broken in different subtests according to the stretch tested.
The test did not work on Android du to failing Stretch.None  section of the test.
The test is now in Runtime app test. The test doe not work on WASM anymore du to the lack of an equivalent of screenshot.
Stretch.Uniform does not work on skia anymore since it is making a mosaic pattern. 
I included MACOS in functioning build but I could not test it. 
I did not includes Android since it was already failing on of the test previously and I was not able to test it, my build was running in a not enough memory exception.  
I did not move the images from Sample App folder in case it would be important for other tests. 
In order to make …
> chore(test): Move ImageBrush_Stretch to runtime test

- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unolib-crossruntime/UnoCrossRuntimeLib/UnoCrossRuntimeLib.Skia.csproj
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unolib-crossruntime/UnoCrossRuntimeLib/UnoCrossRuntimeLib.Wasm.csproj
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unolib-crossruntime/UnoCrossRuntimeLib/UnoCrossRuntimeLib.csproj
GitHub Issue (If applicable): https://github.com/unoplatform/uno/discussions/10015
- Bugfix
Cross-runtime libraries are now using the right assembly name when packaged.
> fix(dotnetnew): Ensure Wasm and Skia runtime libraries are using the same name

- src/Uno.UI/WasmScripts/Uno.UI.d.ts
- src/Uno.UI/WasmScripts/Uno.UI.js
- src/Uno.UI/ts/Windows/Graphics/Display/DisplayInformation.ts
- src/Uno.UWP/Graphics/Display/DisplayInformation.wasm.cs
Supports setting the screen orientation through the `DisplayInformation.AutoRotationPreferences` on supported browsers.
Internally the implementation calls the JavaScript `screen.orientation.lock` API.
GitHub Issue (If applicable): closes #3177
- Feature
Uno WASM applications ignore the `DisplayInformation.AutoRotationPreferences` property.
Uno WASM applications attempts to use the `screen.orientation.lock` JavaScript API to set the screen orientation on supported devices.
> feat(WASM): Support setting the screen orientation

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/documentation-request.md
- .github/ISSUE_TEMPLATE/enhancement.md
- .github/ISSUE_TEMPLATE/samples-request.md
- Mac Catalyst was missing in issue templates
- Mac Catalyst is included
- Reordered targets slightly to put Apple in one spot
- Added Linux Framebuffer to documentation request template
> Add Mac Catalyst to issue templates

- build/ci/.azure-devops-winui-convert.yml
- src/Uno.UI/MixinGeneration.targets
- CI
- Ensures no obj folders are kept in the winui converted artifacts, which avoids cross-OS dotnet-t4 installation issues
- Ensures the dotnet-t4 is installed before the parallelization of cross-targeted build
> ci: Adjust t4 installation and WinUI pre-conversion

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/SourceGenerators/XamlGenerationTests/LiteralEnumValue.xaml
- src/SourceGenerators/XamlGenerationTests/LiteralEnumValue.xaml.cs
GitHub Issue (If applicable): closes #10047
- Bugfix
Passing enum value to binding properties like "ConverterParameter,FallbackValue,TargetNullValue" are processed like string by the XamlSourceGenerator:
```
<Binding>
</Binding.ConverterParameter>
<local:SomeEnum>SomeValue</local:SomeEnum>
```
These enum would be properly parsed and then casted to its underlying enum value, like on windows.
> fix(xaml): binding option value type being ignored

- .vsts-ci.yml
- build/ci/.azure-devops-project-template-tests.yml
- build/test-scripts/run-template-tests.ps1
GitHub Issue (If applicable): https://developercommunity.visualstudio.com/t/XamarinMac-binaries-are-missing-in-173/10164443
Disables `dotnet new` xamarin.mac validations.
> ci: Disable macOS dotnet new template validation

- doc/articles/features/native-frame-nav.md
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_NativeFrame.cs
- src/Uno.UI/Controls/NativeFramePresenter.iOS.cs
- src/Uno.UI/Helpers/FrameNavigationHelper.cs
- src/Uno.UI/UI/Xaml/Controls/Frame/Frame.cs
Relates to https://github.com/unoplatform/uno.toolkit.ui/issues/346
- Bugfix
Manually editing the Frame.BackStack while use the NativeFramePresenter on iOS leads to navigation problems. ViewControllers in the NavigationController stack will not contain references to the proper Page instances. This is causing the Frame BackStack and the NavigationController's ViewControllers to become out of sync with one another
Upon any change to the Frame's BackStack, the iOS NativeFramePresenter will attempt to instantiate Pages that have been added to the BackStack through an insertion of a new `PageStackEntry`.
We are also introducing a new Helper method for the `FrameNavigationHelper` that will allow the NativeFramePresenter within Toolkit, or any other …
> fix(NativeFramePresenter): Create Page instances at time of insertion into the Frame.BackStack

- src/Uno.Foundation.Logging/LoggerFactory.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/nventive-private/issues/415
- Bugfix
The internal `LoggerFactory` is now thread safe.
> fix(logger): Ensure thread safety of `LoggerFactory`

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ContentDialog.cs
- src/Uno.UI/UI/Xaml/Controls/ContentDialog/ContentDialog.cs
closes https://github.com/unoplatform/uno.extensions/issues/768
- Bugfix
A back navigation or app closure will occur when tapping the back button while a contentdialog is being displayed
while dialog is open, back should just close the dialog and do nothing else
> fix(ContentDialog): Handle back button being pressed

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ContentDialog.cs
- src/Uno.UI/UI/Xaml/Controls/ContentDialog/ContentDialog.cs
closes #10038
- Bugfix
The ContentDialog's popup may be forcibly closed by things such as the app moving to the background, when this happens, the ShowAsync method never returns
> fix: Ensure ShowAsync returns if popup is forcibly closed

- doc/articles/logging.md
Fixed #if indentation in md file for a better reading
GitHub Issue (If applicable): closes #10099
Corrected the indentation
The #if markdows is not correct for displaying
The #if markdows is now correct
> docs: Fix logging indentation for markdown formatting

- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/xBind_ValueType.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/xBind_ValueType.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Given_xBind_Binding.cs
- src/Uno.UI/DataBinding/BindingExpression.cs
- src/Uno.UI/UI/Xaml/Data/Binding.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/9918
- Bugfix
An x:Bind expression with `FallbackValue={x:Null}` now sets the target to null explicitly.
> fix(xBind): Adjust FallbackValue behavior to explicitly support setting null to the target

- build/ci/.azure-devops-package-generic.yml
- build/ci/.azure-devops-package-net6-win.yml
- build/ci/.azure-devops-package-reference.yml
- build/ci/.azure-devops-package-skia.yml
- build/ci/.azure-devops-package-wasm.yml
- build/ci/.azure-devops-package.yml
Artifacts download fail with:
`Possibly unsupported ZIP platform type, 251`
Avoids having a single download to go over 4.5GB.
> ci: Split build artifacts into smaller pieces
