unoplatform/uno

- src/Uno.Foundation/Buffer/ArrayPool.cs
- src/Uno.Foundation/Buffer/DefaultArrayPool.cs
- src/Uno.Foundation/Buffer/DefaultArrayPoolBucket.cs
- src/Uno.UI.Tests/BinderTests/Given_BindingPath.cs
- src/Uno.UI/DataBinding/BindingPath.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/NavigationView/NavigationViewItem.Uno.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/NavigationView/NavigationViewItem.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/FlowLayout.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/StackLayout.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/ViewportManagerWithPlatformFeatures.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/VirtualizingLayout.cs
- src/Uno.UI/UI/Xaml/CornerRadius.cs
https://github.com/unoplatform/uno/issues/5172
Improve global performance of hierarchical NavigationView
Perf when scrolling the NavigationView of the Uno.Gallery is really bad on Android especially.
It's  a bit better
> fix: Improve perf of hierarchical NavigationView

- src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Media/Brush.cs
- src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.skia.cs
- src/Uno.UI/UI/Xaml/Media/Brush.cs
- src/Uno.UI/UI/Xaml/Media/Imaging/WriteableBitmap.cs
- src/Uno.UI/UI/Xaml/Media/Imaging/WriteableBitmap.skia.cs
- src/Uno.UWP/Storage/Streams/Buffer.cs
- src/Uno.UWP/UI/Composition/SkiaCompositionSurface.skia.cs
- Bugfix
- fix(WriteableBitmap): [Skia] Fix invalid pixel format
- fix(WriteableBitmap): [Skia] Fix Invalidate not working
- fix(ImageBrush): [Skia] Apply ImageBrush.Transform
> [Skia] WriteableBitmap and ImageBrush fixes

- build/ci/.azure-devops-wasm-uitests.yml
- build/ci/templates/dotnet-sdks.yml
- build/ci/templates/gitversion.yml
- gitversion.yml
- src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.xaml
- src/Uno.NUnitTransformTool/Uno.NUnitTransformTool.csproj
- src/Uno.ReferenceImplComparer/Uno.ReferenceImplComparer.csproj
- src/Uno.WinUIRevert/Uno.WinUIRevert.csproj
Restore mainline versioning for stable branch specification after gitversion update.
> ci: Update to latest gitversion, adjust mainline mode for stable

- CONTRIBUTING.md
GitHub Issue (If applicable): # n/a
Link uses back-slashes instead of forward-slashes and so results in encoded values in the generated path which leads to a broken link: https://github.com/unoplatform/uno/blob/master/doc%5Carticles%5Cuno-development%5Cgit-conventional-commits.md
link works correctly.
> docs: fix broken internal link

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/documentation-issue.md
- .github/ISSUE_TEMPLATE/documentation-request.md
- .github/ISSUE_TEMPLATE/enhancement.md
- .github/ISSUE_TEMPLATE/samples-issue.md
- .github/ISSUE_TEMPLATE/samples-request.md
- doc/articles/uno-development/working-with-the-samples-apps.md
- src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.cs
- src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Controls/SampleChooserContent.cs
- src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Controls/SampleControlInfoAttribute.cs
- docs
- feature
New attribute property to flag manual tests
> Manual testing additions

- src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.xaml
- src/Uno.UI.RuntimeTests/Helpers/NumberAssert.cs
- src/Uno.UI.RuntimeTests/IntegrationTests/common/TestServices.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Flyout.cs
- src/Uno.UI/UI/Xaml/Controls/Popup/PlacementPopupPanel.cs
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/4915
- Bugfix
> Fix flyout doesn't fall back to preferred position

- src/SourceGenerators/Uno.UI.SourceGenerators/ApiInformation.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileParser.cs
- src/Uno.UI.Tests/Windows_UI_Xaml/Controls/When_Conditional_IsTypePresent_Page.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml/Controls/When_Conditional_IsTypePresent_Page.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml/Given_Conditional_Xaml.cs
- src/Uno.UI/UI/Xaml/Controls/ItemsWrapGrid/ItemsWrapGrid.macOS.cs
- src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml
GitHub Issue (If applicable): fixes https://github.com/unoplatform/Uno.Gallery/issues/161
- Bugfix
- Feature
> Implement IsTypeChanged in conditional Xaml, fix macOS GridView display

- doc/articles/get-started-with-linux.md
> docs: Update the WSL debugger installation procedure

- doc/articles/guides/silverlight-migration/98-timeentry-samples.md
> chore: Deeplink to Silverlight migration sample code

- build/ci/.azure-devops-macos.yml
- CI
Apply workaround for https://github.com/xamarin/xamarin-macios/issues/10652
> ci: Apply xamarin.mac build fixes

- src/Uno.UI/UI/Xaml/Controls/WebView/WebView.Android.cs
https://github.com/unoplatform/uno/issues/4446 
- Bugfix
Android 10's Webview does not display html content from string properly. But work fine on Android 9
The content is properly displayed from html string for Android 9 and upper
Ref: https://developer.android.com/reference/android/webkit/WebView#loadData(java.lang.String,%20java.lang.String,%20java.lang.String)
> [Webview] Fix load HTML from string for Android 10

- doc/.feature-template-uno-only.md
- doc/.feature-template.md
- doc/.howto-template.md
- doc/articles/toc.yml
- doc/articles/uno-development/doc-on-docs.md
- doc/articles/uno-development/docfx.md
- src/Uno.UWPSyncGenerator/DocGenerator.cs
> Add docs templates, guidelines

- src/SourceGenerators/Uno.UI.SourceGenerators/Telemetry/TelemetryClient.cs
GitHub Issue (If applicable): #5326
- Bugfix
> fix: NullReferenceException when setting UnoPlatformTelemetryOptOut to true 

- .github/config.yml
> docs: update bot message

- src/Uno.UI/Media/PathStreamGeometryContext.cs
- src/Uno.UI/UI/Xaml/Shapes/Shape.Android.cs
closes https://github.com/unoplatform/nventive-private/issues/191
- Bugfix
> fix(Path): [Android] fix certain paths being skewed

- src/SamplesApp/SamplesApp.Skia.Gtk/SamplesApp.Skia.Gtk.csproj
- src/SamplesApp/SamplesApp.Skia.WPF/SamplesApp.Skia.WPF.csproj
- src/netcore-build-windows.props
> build: Fix netstandard2.0 override

- src/Uno.UI/UI/Xaml/Controls/DatePicker/NativeDatePickerFlyout.Android.cs
- src/Uno.UI/UI/Xaml/Controls/DatePicker/NativeDatePickerFlyout.iOS.cs
> fix(DatePicker): Set default date to Today's Date

- src/SourceGenerators/Uno.UI.Tasks/Helpers/TaskLoggerProvider.cs
- Bugfix
The build may fail with the following exception:
```
uno.ui\3.6.0-dev.294\buildTransitive\netstandard2.0\Uno.UI.Tasks.targets(36,5): error MSB4018: The "ResourcesGenerationTask_v6db4ebd186357665270df03f4b550eb460ebc898" task failed unexpectedly. 
uno.ui\3.6.0-dev.294\buildTransitive\netstandard2.0\Uno.UI.Tasks.targets(36,5): error MSB4018: System.MissingMethodException: Method not found: 'Void Uno.Extensions.LogExtensionPoint.set_AmbientLoggerFactory(Microsoft.Extensions.Logging.ILoggerFactory)'.
uno.ui\3.6.0-dev.294\buildTransitive\netstandard2.0\Uno.UI.Tasks.targets(36,5): error MSB4018:    at Uno.UI.Tasks.Helpers.TaskLoggerProvider.<>c.<Register>b__5_0() 
uno.ui\3.6.0-dev.294\buildTransitive\netstandard2.0\Uno.UI.Tasks.targets(36,5): …
```
> fix(reg): Fallback on reflection for loggers cleanup

- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp/.template.config/template.json
-wasm=false should not create the folder template for webassembly.
Apparently we are excluding the folder with the .Gtk instead of .Wasm
Signed-off-by: Matheus Castello <matheus@castello.eng.br>
- Bugfix
Creating a project with the flag `-wasm=false` continues creating a folder with the Webassembly template.
Creating a project with the flag `-wasm=false` exclude a new folder with the Webassembly template.
> fix(dotnetnew): -wasm=false exclude UnoQuickStart.Wasm

- src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePickerSelector.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerSelector.iOS.cs
- Feature
Set the correct version for the iOS `preferredDatePickerStyle` on the `DatePicker` and `TimePicker`.  Correct version is **13.4**  as can be seen [here]( https://developer.apple.com/documentation/uikit/uidatepicker/3526124-preferreddatepickerstyle)
> chore: Update iOS feature version validation

- src/Uno.UI.Runtime.Skia.Gtk/GTK/GtkCoreWindowExtension.cs
- src/Uno.UI.Runtime.Skia.Gtk/GTK/GtkHost.cs
- src/Uno.UI/UI/Xaml/Input/PointerRoutedEventArgs.skia.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.Skia.cs
- src/Uno.UWP/UI/Core/CoreWindow.skia.cs
- src/Uno.UWP/UI/Core/PointerEventArgs.cs
- src/Uno.UWP/UI/Input/PointerPoint.cs
GitHub Issue: https://github.com/unoplatform/uno/issues/4936
Add support of touch on skia GTK
Touches are handled as mouse
🙃
> feat(pointers): Add support of touch inputs on skia GTK

- doc/articles/controls/CommandBar.md
- src/Uno.UI/Controls/NavigationAppBarButtonRenderer.Android.cs
- src/Uno.UI/FeatureConfiguration.cs
closes #5167 
- Bugfix
The CommandBar.Foreground color should not affect any of the CommandBar.AppBarButton Tint
As a part of the change, we added a FeatureConfiguration flag that users can use to get the previous behavior.
> fix(droid): CommandBar's Foreground property affecting AppBarButton Tint

- doc/articles/uno-development/ways-to-contribute.md
docs: contribution guide updates
> docs: contribution guide updates

- src/Uno.UI/UI/Xaml/Window.macOS.cs
- src/Uno.UWP/UI/ViewManagement/ApplicationView.macOS.cs
> fix(macOS): NSWindow minimize button

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/DatePickerIntegrationTests.cs
- src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePicker.Flyout.cs
- src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePickerFlyout.Properties.cs
- src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePickerFlyoutPresenter_Partial.cs
- src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePickerFlyout_Partial.cs
GitHub Issue (If applicable): https://github.com/unoplatform/Uno.Themes/issues/470
- Feature
> feat: Add ability to style DatePickerFlyoutPresenter

- src/SamplesApp/SamplesApp.Droid/SamplesApp.Droid.csproj
- src/Uno.UI/UI/Xaml/Controls/Border/Border.cs
- src/Uno.UI/UI/Xaml/Controls/Grid/ColumnDefinition.cs
- src/Uno.UI/UI/Xaml/Controls/Grid/RowDefinition.cs
Use generated property caching for:
- Border.Padding
- Border.BorderThickness
- Border.BorderBrush
- ColumnDefinition.MaxWidth and MinWidth
- RowDefinition.MinHeight and MaxHeight
> Misc Performance improvements

- src/Uno.APISurfaceValidator/Program.cs
- src/Uno.APISurfaceValidator/Properties/launchSettings.json
- src/Uno.APISurfaceValidator/Uno.APISurfaceValidator.csproj
- src/Uno.UI.sln
- Feature
unoplatform/private#219
> feat: Initial API surface validator

- src/SamplesApp/SamplesApp.Shared/App.xaml.cs
- Bugfix
Wasm sample app can now start in debug configuration properly
> test: [Wasm] Fix SamplesApp logging in debug

- build/android-uitest-run.sh
- build/ci/.azure-devops-ios-tests.yml
- build/ci/.azure-devops-wasm-uitests.yml
- build/ios-uitest-run.sh
- build/run-automated-uitests.sh
- src/Directory.Build.targets
- src/SamplesApp/Benchmarks.Shared/Controls/BenchmarkDotNetControl.xaml
- src/SamplesApp/Benchmarks.Shared/Controls/BenchmarkDotNetControl.xaml.cs
- src/SamplesApp/SamplesApp.Droid/SamplesApp.Droid.csproj
- src/SamplesApp/SamplesApp.Skia/SamplesApp.Skia.csproj
- src/SamplesApp/SamplesApp.UITests/BenchmarkDotNetTests.cs
- src/SamplesApp/SamplesApp.UITests/SampleControlUITestBase.cs
- src/SamplesApp/SamplesApp.Wasm/SamplesApp.Wasm.csproj
- src/Uno.UI-Android-only.slnf
- src/Uno.UI-iOS-only.slnf
- src/Uno.UI.sln
- Feature
Enable performance testing during UI Testing for Wasm.
> ci: Add Benchmark.NET suite

- doc/articles/get-started-dotnet-new.md
fixes https://github.com/unoplatform/uno/issues/5486
> docs: Adjust WinUI resources for `unoapp-winui`

- build/run-template-tests-linux.ps1
- build/run-template-tests.ps1
- src/SamplesApp/SamplesApp.UITests/Microsoft_UI_Xaml_Controls/NavigationViewTests/NavigationView_Tests.cs
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/Uno.ProjectTemplates.Dotnet.csproj
- src/SolutionTemplate/UnoSolutionTemplate/Droid/UnoQuickStart.Droid.csproj
- src/SolutionTemplate/UnoSolutionTemplate/Shared/App.xaml.cs
- src/SolutionTemplate/UnoSolutionTemplate/Skia.Gtk/UnoQuickStart.Skia.Gtk.csproj
- src/SolutionTemplate/UnoSolutionTemplate/Skia.Tizen/UnoQuickStart.Skia.Tizen.csproj
- src/SolutionTemplate/UnoSolutionTemplate/Skia.WPF/UnoQuickStart.Skia.WPF.csproj
- src/SolutionTemplate/UnoSolutionTemplate/UWP/UnoQuickStart.Uwp.csproj
- src/SolutionTemplate/UnoSolutionTemplate/Wasm/LinkerConfig.xml
- src/SolutionTemplate/UnoSolutionTemplate/Wasm/UnoQuickStart.Wasm.csproj
- src/SolutionTemplate/UnoSolutionTemplate/iOS/UnoQuickStart.iOS.csproj
- src/SolutionTemplate/UnoSolutionTemplate/macOS/UnoQuickStart.macOS.csproj
GitHub Issue (If applicable): fixes #3624, fixes https://github.com/unoplatform/uno/issues/4767, fixes https://github.com/unoplatform/uno/issues/3624, fixes https://github.com/unoplatform/uno/issues/2013
- Feature
Templates now use updated Microsoft loggers to 5.0.0.
> feat: Update templates to use Microsoft Logging 5.0.0

- build/ci/.azure-devops-android-tests.yml
> ci: Bump android tests timeout

- build/Uno.WinUI.nuspec
- src/Directory.Build.targets
- src/SamplesApp/SamplesApp.Wasm/SamplesApp.Wasm.csproj
- src/SamplesApp/SamplesApp.macOS/SamplesApp.macOS.csproj
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.UWP/BlankApp.Uwp.csproj
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-winui/UnoWinUIQuickStart.Windows.Desktop/UnoWinUIQuickStart.Windows.Desktop.csproj
- src/SolutionTemplate/UnoSolutionTemplate/UWP/UnoQuickStart.Uwp.csproj
- src/SolutionTemplate/UnoSolutionTemplate/Wasm/UnoQuickStart.Wasm.csproj
- src/SolutionTemplate/UnoSolutionTemplate/iOS/UnoQuickStart.iOS.csproj
- src/Uno.UI.RemoteControl.Host/Uno.UI.RemoteControl.Host.csproj
- src/Uno.UI/Uno.UI.csproj
- src/Uno.UWPSyncGenerator/Uno.UWPSyncGenerator.csproj
> chore: Bump Uno.Core and Uno.Extensions.Logging dependencies to stable

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Image.cs
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/5390
- Bugfix
Stabilized When_Fixed_Height_And_Stretch_Uniform test by ensuring desired size is read updated during retries.
> test: [Wasm] Fix When_Fixed_Height_And_Stretch_Uniform

- doc/articles/migrating-from-previous-releases.md
> docs: Add loggers upgrade docs

- doc/articles/features/native-frame-nav.md
- doc/articles/guides/native-frame-nav-tutorial.md
- doc/articles/toc.yml
resolves #3660
added guide on frame navigation & docs on native frame navigation
Related sample code is in another PR: unoplatform/Uno.Samples#44
> docs: added feature doc & tutorial for native frame navigation

- src/Uno.UWP/ApplicationModel/Chat/ChatMessage.cs
- src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Chat/ChatMessage.cs
- Feature
Three fields are not implemented.
Implemented.
This is part of #3055.
And this fields are required for ChatMessageReader.
> feat: ChatMessage, fields for ChatMessageReader

- doc/articles/guides/hotswap-app-language.md
- doc/articles/guides/localization.md
- doc/articles/toc.yml
resolve #5437
added docs on localization & culture hotswapping
Related sample code is in another PR: unoplatform/Uno.Samples#47
> docs: added docs on localization & culture hotswapping

- doc/articles/get-started-dotnet-new.md
- doc/articles/get-started-vsmac.md
- doc/articles/get-started-with-linux.md
- doc/articles/intro.md
- doc/articles/uno-community-toolkit.md
- src/Uno.UI/UI/Xaml/DependencyObject.cs
> docs: Add top questions about Uno to intro page, misc tweaks

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_NativeFrame.cs
- src/Uno.UI/NativeFramePresenter.Android.cs
fixes https://github.com/unoplatform/nventive-private/issues/188
- Bugfix
> fix(droid): Blank Page when Back navigation

- src/Uno.UI/UI/Xaml/ApplicationActivity.Android.cs
- src/Uno.UI/UI/Xaml/NativeApplication.cs
GitHub Issue (If applicable): #5076 
> chore: Expand logging for Android intent handling

- src/SourceGenerators/Uno.UI.SourceGenerators/Helpers/SymbolExtensions.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/NameScope.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_Event_Nested.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_Event_Nested.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_Event_Nested_DataTemplate.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_Event_Nested_DataTemplate.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_xLoad_Event.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_xLoad_Event.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Given_xBind_Binding.cs
GitHub Issue (If applicable): fixes unoplatform/uno#5565, fixes https://github.com/unoplatform/uno/issues/4478
- Bugfix
x:Bind to sub-classes in top level controls and DataTemplate are now working properly.
> fix(xbind): Support nested expression x:Bind events

- build/PackageDiffIgnore.xml
- doc/.howto-template.md
- doc/articles/features/native-frame-nav.md
- doc/articles/get-started-dotnet-new.md
- doc/articles/get-started.md
- doc/articles/guides/hotswap-app-language.md
- doc/articles/guides/localization.md
- doc/articles/guides/native-frame-nav-tutorial.md
- doc/articles/guides/status-bar-theme-color.md
- doc/articles/toc.yml
- doc/articles/uno-development/docfx.md
- doc/articles/updating-to-winui3.md
- doc/articles/winui-doc-links-design.md
- doc/articles/winui-doc-links-development.md
- doc/articles/winui-doc-links-tutorials.md
> docs: Tweak Get Started page, fix broken links, misc minor adjustments

- src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml
closes #4909
related to #857 
- Bugfix
> fix: Add ContentTemplate Binding to TextBlockButtonStyle

- src/Uno.UWP/Devices/Geolocation/Geofencing/Geofence.cs
- src/Uno.UWP/Generated/3.0.0.0/Windows.Devices.Geolocation.Geofencing/Geofence.cs
- Feature
Not implemented.
Implemented.
It is continuation of #4390, effort to implement Geofencing.
> feat: Geofence for all platforms

- build/PackageDiffIgnore.xml
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-winui/UnoWinUIQuickStart.Windows.Desktop/UnoWinUIQuickStart.Windows.Desktop.csproj
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-winui/UnoWinUIQuickStart.Windows.Package/UnoWinUIQuickStart.Windows.Package.wapproj
- src/SolutionTemplate/UnoSolutionTemplate/Shared/App.xaml.cs
- src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Media/RevealBrush.cs
- src/Uno.UI/UI/Xaml/Media/RevealBrush.cs
- src/Uno.UWPSyncGenerator.Reference/Uno.UWPSyncGenerator.Reference.csproj
> Reunion 0.5 update

- build/PackageDiffIgnore.xml
- src/Uno.UWP/ApplicationModel/Contacts/ContactBatch.cs
- src/Uno.UWP/ApplicationModel/Contacts/ContactQueryOptions.cs
- src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Contacts/ContactBatch.cs
- src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Contacts/ContactQueryOptions.cs
- Feature
ContactQueryOptions and ContactBatch are not implemented.
ContactQueryOptions and ContactBatch are implemented (for Android).
Part of #2544, and continuation of #4081.
Also part of my app, CallsStat, published on Amazon.
> feat: ContactQueryOptions and ContactBatch (Android)

- src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.iOSmacOS.cs
- src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.skia.cs
> fix(Border): Adjust max radius for inner border shape

- build/run-template-tests-linux.ps1
- build/run-template-tests.ps1
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/.template.config/dotnetcli.host.json
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/.template.config/template.json
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/.template.config/vs-2017.3.host.json
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.sln
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-winui/.template.config/dotnetcli.host.json
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-winui/.template.config/template.json
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-winui/.template.config/vs-2017.3.host.json
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp/.template.config/dotnetcli.host.json
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp/.template.config/template.json
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp/.template.config/vs-2017.3.host.json
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp/UnoQuickStart.sln
- src/SolutionTemplate/UnoSolutionTemplate/Shared/App.xaml.cs
> fix(templates): Make UWP head mandatory

- src/SolutionTemplate/UnoSolutionTemplate.VISX/source.extension.vsixmanifest
- Feature
Before installing the Uno Platform Solution Templates, you must manually install the prerequisites.
Automatic fetch and installation of prerequisites when installing Uno Platform Solution Templates.
> feat(vsix): Automatic installing prerequisites.

- doc/articles/get-started-dotnet-new.md
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/5668
> docs: Add instructions to uninstall the dotnet new template

- build/ci/.azure-devops-docs.yml
- build/ci/.azure-devops-project-template-tests.yml
- build/ci/templates/gitversion.yml
- src/SourceGenerators/Uno.UI.SourceGenerators/BindableTypeProviders/BindableTypeProvidersGenerationTask.cs
The build does not fail randomly with :
```
Error NU1101: Unable to find package XXX. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
```
> ci: force add nuget.org as upstream source

- src/Uno.UI.FluentTheme/Resources/PriorityDefault/Button_themeresources.xaml
- src/Uno.UI.FluentTheme/Resources/PriorityDefault/CheckBox_themeresources.xaml
- src/Uno.UI.FluentTheme/Resources/PriorityDefault/DropDownButton.xaml
- src/Uno.UI.FluentTheme/Resources/PriorityDefault/ListViewItem_themeresources.xaml
- src/Uno.UI.FluentTheme/Resources/PriorityDefault/RadioButton_themeresources.xaml
- src/Uno.UI.FluentTheme/Resources/PriorityDefault/RepeatButton_themeresources.xaml
- src/Uno.UI.FluentTheme/Resources/PriorityDefault/ToggleButton_themeresources.xaml
- src/Uno.UI.FluentTheme/themeresources.xaml
- src/Uno.UI.RuntimeTests/IntegrationTests/common/TestServices.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ContentControl.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/TestsResources.xaml
- src/Uno.UI/UI/Xaml/Controls/DropDownButton/DropDownButton.xaml
- src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml
GitHub Issue (If applicable):  fixes #5622, fixes #5650, closes #5646
- Bugfix
> Apply ContentTemplateSelector with Fluent styles

- src/SamplesApp/Benchmarks.Shared/Benchmarks.Shared.projitems
- src/SamplesApp/Benchmarks.Shared/Suite/Windows_UI_Xaml_Controls/BorderBench/BorderBenchmark.cs
- src/SamplesApp/Benchmarks.Shared/Suite/Windows_UI_Xaml_Controls/DependencyPropertyBench/PropagationDPBenchmark.cs
- src/SamplesApp/Benchmarks.Shared/Suite/Windows_UI_Xaml_Controls/DependencyPropertyBench/SpecializedDPBenchmark.cs
- src/SamplesApp/Benchmarks.Shared/Suite/Windows_UI_Xaml_Controls/FrameworkElementBench/FrameworkElementBenchmark.cs
- Feature
New benchmarks for dependency properties
> perf: Add DependencyObject benchmarks

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Flyout.cs
- src/Uno.UI/UI/Xaml/Controls/Popup/PopupBase.cs
fixes https://github.com/unoplatform/nventive-private/issues/198
- Bugfix
Flyout items stop responding 
> fix(popup): [iOS/Droid] not responding

- src/SamplesApp/SamplesApp.Skia.Gtk/SamplesApp.Skia.Gtk.csproj
- src/Uno.Foundation.Runtime.WebAssembly/Interop/MarshalSizeOfHelper.cs
- src/Uno.Foundation.Runtime.WebAssembly/Interop/TSInteropMarshaller.wasm.cs
- src/Uno.Foundation/Collections/HashtableEx.cs
- src/Uno.UI/Helpers/FastTypeComparer.cs
- src/Uno.UI/UI/Xaml/DependencyObjectStore.Binder.cs
- src/Uno.UI/UI/Xaml/DependencyProperty.Dictionary.FrameworkPropertiesForType.cs
- src/Uno.UI/UI/Xaml/DependencyProperty.Dictionary.NameToProperty.cs
- src/Uno.UI/UI/Xaml/DependencyProperty.Dictionary.PropertiesRegistry.cs
- src/Uno.UI/UI/Xaml/DependencyProperty.Dictionary.TypeToProperties.cs
- src/Uno.UI/UI/Xaml/DependencyProperty.cs
- src/Uno.UI/UI/Xaml/DependencyPropertyCacheEntry.cs
- src/Uno.UI/UI/Xaml/PropertyMetadataDictionary.cs
- Improve dictionary lookups for `DependencyObject` and `DependencyProperty`
> perf: Enhance various lookups performance

- src/Uno.Foundation.Runtime.WebAssembly/Interop/TSInteropMarshaller.wasm.cs
- src/Uno.UI.Wasm.Tests/Tests/TSBindingsTests.cs
- src/Uno.UI/DataBinding/BindingExpression.cs
- src/Uno.UI/DataBinding/BindingPath.cs
- src/Uno.UI/UI/Xaml/Controls/ItemsControl/ItemsControl.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs
- src/Uno.UI/UI/Xaml/DependencyObjectExtensions.cs
- src/Uno.UI/UI/Xaml/DependencyObjectStore.Binder.cs
- src/Uno.UI/UI/Xaml/DependencyObjectStore.cs
- src/Uno.UI/UI/Xaml/FrameworkElement.cs
- src/Uno.UI/UI/Xaml/Media/Brush.Android.cs
- src/Uno.UI/UI/Xaml/Media/Brush.Skia.cs
- src/Uno.UI/UI/Xaml/Media/Brush.iOSmacOS.cs
- src/Uno.UI/UI/Xaml/Media/Brush.wasm.cs
- src/Uno.UI/UI/Xaml/WindowManagerInterop.wasm.cs
- src/Uno.UI/WasmScripts/Uno.UI.js
- src/Uno.UI/ts/WindowManager.ts
- src/Uno.UWP/Storage/ApplicationDataContainer.wasm.cs
- Improve Brush.AssignAndObserveBrush performane by removing the generic delegate
- Improve ResourceDictionary implicit style resolution by caching the current type style key
- Don't create Attached DependencyObject store on inherited properties propagation
- Remove foreach/using statements from hot paths
- Wasm: Don't remove already removed class on arrange
- Don't rely on reflection for Marshal.PtrToStructure
> Misc perf updates

- src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.cs
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/5710
- Bugfix
Add the panel to the generated bindable to improve binding performance.
> fix: Add Bindable attribute on VirtualizingPanelLayout

- doc/articles/migrating-from-previous-releases.md
> docs: [Wasm] Add documentation to migrate to .NET5

- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_Converter_TwoWay.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_Converter_TwoWay.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/BoolToIntegerConverter.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/InverseBoolConverter.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Given_xBind_Binding.cs
- src/Uno.UI/DataBinding/BindingPath.cs
Fix NRE when accessing ValueType property in this binding scenario. (Also probably a couple of other would-be NREs as well.)
GitHub Issue (If applicable): fixes #5615
- Bugfix
> fix: Fix NRE from x:Bind two-way through converter

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TextBoxTests/TextBoxTests.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_Foreground_Changing.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_Foreground_Changing.xaml.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/MultilineTextBoxView.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/SinglelineTextBoxView.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.Android.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.macOS.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.wasm.cs
- src/Uno.UI/UI/Xaml/UIElement.debugging.cs
GitHub Issue (If applicable): fixes #5580, resolves #5491
- Bugfix
> React to TextBox.Foreground.Color changes

- src/Uno.Foundation.Runtime.WebAssembly/Interop/TSInteropMarshaller.wasm.cs
- src/Uno.UI.Wasm.Tests/Tests/TSBindingsTests.cs
- src/Uno.UI/UI/Xaml/WindowManagerInterop.wasm.cs
- src/Uno.UWP/Storage/ApplicationDataContainer.wasm.cs
GitHub Issue (If applicable): #5744
- Bugfix
This reverts commit 20ea231ee5706353cf8a255271585190643d1dd2.
The error raised looks like this:
```
Attempting to JIT compile method '(wrapper other) void Uno.Foundation.Interop.TSInteropMarshaller/WrapperBoolean_Return:PtrToStructure (intptr,object)' while running in aot-only mode.
```
> fix: FullAOT may fail for missing generated marshaller

- doc/articles/logging.md
- src/Uno.Foundation/Metadata/ApiInformation.cs
- src/Uno.UI/FeatureConfiguration.cs
ApiInformation.NotImplementedLogLevel can be overridden to set the log level of messages when not implemented members are used at runtime. If set to LogLevel.Debug, not implemented messages will be hidden under the default logging filters.
- Feature
> feat: Add feature flag to configure NotImplemented log level

- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-winui/UnoWinUIQuickStart.Windows.Desktop/UnoWinUIQuickStart.Windows.Desktop.csproj
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-winui/UnoWinUIQuickStart.Windows.Package/UnoWinUIQuickStart.Windows.Package.wapproj
- Feature
Update the winui template to use Reunion 0.5.5
> feat: Upgrade template to Reunion 0.5.5

- doc/articles/logging.md
> docs: add guidance for setting NotImplementedLogLevel

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/ContentControlPages/BoundContentApplicator.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/ContentControlPages/When_Template_Applied_On_Loading_DataContext_Propagation_Page.xaml
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/ContentControlPages/When_Template_Applied_On_Loading_DataContext_Propagation_Page.xaml.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ContentControl.cs
- src/Uno.UI/UI/Xaml/Controls/ContentControl/ContentControl.cs
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/5736
- Bugfix
> fix: Fix spurious DataContext propagation in ContentControl

- doc/articles/features/protocol-activation.md
- doc/articles/features/windows-storage-pickers.md
- src/Uno.UWP/Storage/Pickers/FileOpenPicker.cs
GitHub Issue (If applicable): fixes #4525
- Bugfix
N/A
- Improved docs for file pickers on macOS and iOS
- Improved docs for protocol handling
- Fix exception message for `FileOpenPicker`
> Improve protocol activation and picker docs

- src/Uno.UI/UI/Xaml/Application.iOS.cs
GitHub Issue (If applicable): fixes #5756 
- Feature
Not properly supported.
Supported
> feat: Support for iOS universal links

- src/SolutionTemplate/UnoSolutionTemplate/Shared/App.xaml.cs
GitHub Issue (If applicable): resolves #5785
- Bugfix
As described in #5785, on WinUI, the Window is scoped to the the `OnLaunched()` function, causing it to be marked for deletion after the function returns. This leads to memory access violations once the memory is reallocated.
The Window is now stored in the Application to prevent it from being marked for deletion until the Application is exited.
> Fix Window losing scope in WinUI in Template App.xaml.cs

- src/SamplesApp/Benchmarks.Shared/Controls/BenchmarkDotNetControl.xaml.cs
- src/SamplesApp/Benchmarks.Shared/Suite/Windows_UI_Xaml_Controls/GridBench/SimpleGridBenchmark.cs
Reverts #5804, the tests lead to memory issues
> chore: Revert "perf(grid): Added more cases to Grid benchmark"

- build/Uno.UI.Build.csproj
- doc/articles/get-started-dotnet-new.md
- src/SolutionTemplate/UnoSolutionTemplate/Wasm/WasmScripts/AppManifest.js
- src/Uno.UI.RemoteControl/buildTransitive/Uno.UI.RemoteControl.targets
> Misc 3.7 adjustments

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/BorderTests/Border_Tests.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/BorderTests/Border_CornerRadius_BorderThickness.xaml
- src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.iOSmacOS.cs
closes https://github.com/unoplatform/nventive-private/issues/193
- Bugfix
> fix(Border): Fix EvenOdd winding paths when drawing corner radii

- build/Uno.UI.Build.csproj
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-winui/UnoWinUIQuickStart.Windows.Desktop/UnoWinUIQuickStart.Windows.Desktop.csproj
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-winui/UnoWinUIQuickStart.Windows.Package/UnoWinUIQuickStart.Windows.Package.wapproj
- src/Uno.UI.Toolkit/Uno.UI.Toolkit.csproj
- src/Uno.UWPSyncGenerator.Reference/Uno.UWPSyncGenerator.Reference.csproj
> Update Microsoft.ProjectReunion to 0.5.6

- build/Uno.WinUI.nuspec
- src/Directory.Build.targets
- src/SamplesApp/SamplesApp.macOS/SamplesApp.macOS.csproj
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.UWP/BlankApp.Uwp.csproj
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-winui/UnoWinUIQuickStart.Windows.Desktop/UnoWinUIQuickStart.Windows.Desktop.csproj
- src/SolutionTemplate/UnoSolutionTemplate/UWP/UnoQuickStart.Uwp.csproj
- src/Uno.UI.RemoteControl.Host/Uno.UI.RemoteControl.Host.csproj
- src/Uno.UI.RemoteControl.Server.Processors/Uno.UI.RemoteControl.Server.Processors.csproj
- src/Uno.UI.RemoteControl.Server/Uno.UI.RemoteControl.Server.csproj
- src/Uno.UI/Uno.UI.csproj
- src/Uno.UWPSyncGenerator/Uno.UWPSyncGenerator.csproj
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/5843
- Bugfix
- 
Fixes memory leak during management of weak even registration
> Update to latest Uno.Core to fix memory issue

- src/SamplesApp/Benchmarks.Shared/Controls/BenchmarkDotNetControl.xaml.cs
- src/SamplesApp/Benchmarks.Shared/Suite/Windows_UI_Xaml_Controls/GridBench/SimpleGridBenchmark.cs
> test(grid): Reintroduce Grid benchmark with less impact on the CI

- build/ci/templates/gitversion.yml
- doc/templates/uno/partials/navbar.tmpl.partial
Same as https://github.com/unoplatform/uno/pull/5828 before the rebase,
updated branch name
Fix for the nav menu not displaying in docs
> docs: fix for navigation menu not being displayed

- build/PackageDiffIgnore.xml
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/ButtonUserControl.xaml
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Controls/ButtonUserControl.xaml.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement_ThemeResources.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_UIElement.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/ContentControlPages/Template_Loading_DataContext_Page.xaml
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/ContentControlPages/Template_Loading_DataContext_Page.xaml.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ContentControl.cs
- src/Uno.UI/UI/Xaml/Application.cs
- src/Uno.UI/UI/Xaml/Controls/Popup/Popup.cs
- src/Uno.UI/UI/Xaml/Controls/Popup/PopupPanel.cs
- src/Uno.UI/UI/Xaml/DependencyObjectStore.cs
- src/Uno.UI/UI/Xaml/FrameworkElement.cs
- src/Uno.UI/UI/Xaml/Media/Brush.debugging.cs
- src/Uno.UI/UI/Xaml/ResourceDictionary.cs
- src/Uno.UI/UI/Xaml/ResourceDictionary.debugging.cs
- src/Uno.UI/UI/Xaml/UIElement.debugging.cs
- src/Uno.UI/UI/Xaml/UIElementExtensions.cs
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/5580
- Bugfix
> fix(themeresource): Update ComboBox when theme changes

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/Uno.UI.RuntimeTests/Helpers/ThemeHelper.cs
- src/Uno.UI.Tests/Uno.UI.Tests.csproj
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/VisualStateManager_Lazy_Tests/Controls/When_VisualStateManager_Lazy.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/VisualStateManager_Lazy_Tests/Controls/When_VisualStateManager_Lazy.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/VisualStateManager_Lazy_Tests/Controls/When_VisualStateManager_Lazy_ThemeChanges.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/VisualStateManager_Lazy_Tests/Controls/When_VisualStateManager_Lazy_ThemeChanges.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/VisualStateManager_Lazy_Tests/VisualStateManager_Lazy.cs
- src/Uno.UI/Helpers/MarkupHelper.cs
- src/Uno.UI/UI/Xaml/DependencyObjectCollection.cs
- src/Uno.UI/UI/Xaml/DependencyObjectExtensions.cs
- src/Uno.UI/UI/Xaml/UIElement.PointerCapture.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.cs
- src/Uno.UI/UI/Xaml/VisualState.cs
- src/Uno.UI/UI/Xaml/VisualTransition.cs
- Make VisualState and VisualTransition lazy loaded
- Reduce foreach/linq usage in pointers management
- Use for loops in DependencyObjectCollection
> perf: Lazy VisualState and VisualTransition

- src/Uno.UI/UI/Xaml/UIElement.wasm.cs
- src/Uno.UI/UI/Xaml/WindowManagerInterop.wasm.cs
- src/Uno.UI/WasmCSS/Uno.UI.css
- src/Uno.UI/WasmScripts/Uno.UI.d.ts
- src/Uno.UI/WasmScripts/Uno.UI.js
- src/Uno.UI/ts/WindowManager.ts
- src/Uno.UI/tsBindings/WindowManagerSetVisibilityParams.ts
Use specialized call and CSS style to hide UIElement DOM representation, for faster performance.
> perf: [Wasm] Improve `UIElement.Visibility` set to `Collapsed`

- src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.wasm.cs
Don't register on pointer events in `ScrollContentPresenter` to improve `ScrollViewer` creation performance.
> perf: [Wasm] Register on ScrollContentPresenter pointer events only when native

- src/SamplesApp/Benchmarks.Shared/Benchmarks.Shared.projitems
- src/SamplesApp/Benchmarks.Shared/Controls/BenchmarkDotNetControl.xaml
- src/SamplesApp/Benchmarks.Shared/Controls/BenchmarkDotNetControl.xaml.cs
- src/SamplesApp/Benchmarks.Shared/Suite/Windows_UI_Xaml_Controls/UIElementPerf/ControlCreationBenchmark.cs
- src/SamplesApp/SamplesApp.UITests/BenchmarkDotNetTests.cs
Additional benchmarks for common controls creation.
> perf: Add various controls creation benchmarks

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/Uno.UI.Tests/ResourceLoader/Controls/When_Collection_And_InlineProperty.xaml
- src/Uno.UI.Tests/ResourceLoader/Controls/When_Collection_And_InlineProperty.xaml.cs
- src/Uno.UI.Tests/ResourceLoader/Given_ResourceLoader.cs
- src/Uno.UI.Tests/ResourceLoader/Strings/en/Resources.Designer.cs
- src/Uno.UI.Tests/ResourceLoader/Strings/en/Resources.resw
- src/Uno.UI.Tests/Uno.UI.Tests.csproj
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/5881
- Bugfix
Fixed code generation for inline collections when using x:Uid
> fix(xUid): Ensure proper collection termination when using x:Uid

- build/Uno.WinUI.nuspec
- src/Directory.Build.targets
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/WebViewTests/UnoSamples_Test_NavigateToString.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/WebView/WebView_AnchorNavigation.xaml.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/5996
> fix: Update to Uno.SourceGenerationTasks for VS16.10 compatibility

- build/Uno.WinUI.nuspec
- src/Directory.Build.targets
- src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props
- src/SourceGenerators/Uno.UI.SourceGenerators/RemoteControl/RemoteControlGenerator.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/5953, fixes https://github.com/unoplatform/uno/issues/5996
- Bugfix
- Show a warning when building using .NET 5 when the path for the project contains a `#` character
- Bump Uno.SourceGenerationTasks to add compatibility with VS 16.9 Preview 3
> Misc generation fixes

- build/PackageDiffIgnore.xml
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/5996
> ci: Adjust PackageDiff file after 3.7.4 release

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls_Primitives/Given_ScrollBar.cs
- src/Uno.UI/UI/Xaml/Controls/ScrollBar/ScrollBar.cs
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/5800
- Bugfix
> fix(scrollbar): Fix ValueChanged event not raised

- src/Uno.UI.RuntimeTests/IntegrationTests/common/TestServices.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Grid.cs
- src/Uno.UI/UI/Xaml/Controls/Grid/ColumnDefinition.cs
- src/Uno.UI/UI/Xaml/Controls/Grid/ColumnDefinitionCollection.cs
- src/Uno.UI/UI/Xaml/Controls/Grid/DefinitionBase.cs
- src/Uno.UI/UI/Xaml/Controls/Grid/Grid.h.cs
- src/Uno.UI/UI/Xaml/Controls/Grid/RowDefinition.cs
- src/Uno.UI/UI/Xaml/Controls/Grid/RowDefinitionCollection.cs
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/6009
Fix regression where changing ColumnDefinition.Width (or another property) would immediately set ActualWidth to 0. This is now returned to UWP behavior, where ActualWidth will stay at the old value and be updated once the Grid is re-measured.
- Bugfix
> fix(grid): Fix regression when setting ColumnDefinition.Width

- src/Uno.UI/UI/Xaml/Application.cs
- src/Uno.UI/UI/Xaml/ResourceDictionary.cs
- src/Uno.UI/UI/Xaml/Style/Style.cs
- src/Uno.UI/UI/Xaml/WindowManagerInterop.wasm.cs
- perf: Build only one logger for static style methods
- perf: Push active system theme to ResourceDictionary
- perf: [Wasm] Don't deserialize unused TS interop output
> perf: Misc improvements

- src/Uno.UI.Runtime.Skia.Gtk/GtkApplicationExtension.cs
- src/Uno.UI.Runtime.Skia.Gtk/GtkHost.cs
- src/Uno.UI.Runtime.Skia.Wpf/WpfApplicationExtension.cs
- src/Uno.UI.Runtime.Skia.Wpf/WpfHost.cs
- src/Uno.UI/UI/Xaml/Application.Skia.cs
- src/Uno.UI/UI/Xaml/Application.cs
- src/Uno.UI/UI/Xaml/IApplicationExtension.cs
GitHub Issue (If applicable: closes #6029
- Feature
Not supported.
Supported.
> feat: Application.Exit on GTK and WPF

- doc/articles/get-started-vscode.md
Modify the text to clarify requirements
docs: Update getting started docs dotnet requirements
Unintentionally vague requirements
Clarifies the need for both .NET SDK versions to be installed.
> docs: Update VSCode getting started docs dotnet requirements

- src/Uno.UI.RuntimeTests/Helpers/GridLengthHelper2.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Grid.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/GridPages/GridAdder.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/GridPages/GridWithColumns.xaml
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/GridPages/GridWithColumns.xaml.cs
- src/Uno.UI/UI/Xaml/Controls/Grid/Grid.cs
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/5959
Fix regression introduced by recent fix for NRE from Grid (https://github.com/unoplatform/uno/pull/5933). The NRE arises when some exotic layout sequence causes Grid to be Arranged without already having been Measured. The workaround for this was wrongly being applied to the case where the Grid doesn't have any column or row definitions, resulting in some Grids never arranging their children.
- Bugfix
> fix(reg): Fix Grid regression

- build/run-template-tests.ps1
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.Droid/BlankApp.Droid.csproj
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.Shared/Views/Shell.xaml
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.UWP/BlankApp.Uwp.csproj
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.Wasm/BlankApp.Wasm.csproj
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.iOS/BlankApp.iOS.csproj
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.macOS/BlankApp.macOS.csproj
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/6042
- Bugfix
- Fixes a typo in the prism template
- Build the template in CI for validation
- Update to latest prism public bits (FYI @dansiegel)
> Misc prism updates

- doc/articles/how-to-host-a-webassembly-app.md
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/1423
> docs: Add basic IIS configuration support

- src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.cs
- src/Uno.UI.RuntimeTests/Helpers/RequiresFullWindowAttribute.cs
- src/Uno.UI.RuntimeTests/IntegrationTests/common/TestServices.cs
GitHub Issue (If applicable): closes #6116
- Feature
Test run only embedded in Unit tests page
Runtime tests can run full-screen by using an attribute.
> Full-window runtime tests

- build/PackageDiffIgnore.xml
> ci: Update package diff ignore for 3.7.6

- src/Uno.UI/UI/Xaml/Controls/PasswordBox/SecureTextBoxView.macOS.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.macOS.cs
https://github.com/unoplatform/uno/issues/5937
- Bugfix
> fix(TextBox): Remove FocusRing on macOS

- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CalendarView/CalendarDatePicker_Features.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CalendarView/CalendarView_Basics.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CalendarView/CalendarView_Features.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CalendarView/CalendarView_ScrollingRegion.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CalendarView/CalendarView_SmallRange.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/DatePicker/DatePickerFlyout_Automated.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/DatePicker/DatePickerFlyout_Date_Binding.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/DatePicker/DatePickerFlyout_MinYear.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/DatePicker/DatePickerFlyout_Unloaded.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/DatePicker/DatePickerSample.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/DatePicker/DatePicker_DatePartVisibility.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/DatePicker/DatePicker_Features.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/DatePicker/DatePicker_Header.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/DatePicker/DatePicker_Placement.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/DatePicker/DatePicker_SampleContent.xaml.cs
> test(calendar): Ignore Calendar<View|DatePicker> in all screenshot tests

- src/SolutionTemplate/UnoLibraryTemplate/CrossTargetedLibrary.csproj
- Feature
- Update the  cross-targeted library template to use the first WinUI 2.x compatible UWP SDK build.
- Upgrade MSBuild,SDK.Extras to latest to remove warnings appearing in recent VS builds
> feat: Upgrade cross-platform library template to uwp 18362

- src/Uno.UI/UI/Xaml/Controls/CalendarView/CalendarView.Properties.cs
- src/Uno.UI/UI/Xaml/Controls/CalendarView/CalendarView.h.cs
- src/Uno.UI/UI/Xaml/Controls/CalendarView/CalendarViewBaseItemChrome.cs
- src/Uno.UI/UI/Xaml/Controls/CalendarView/CalendarViewBaseItemChrome.uno.cs
- src/Uno.UI/UI/Xaml/Controls/CalendarView/CalendarView_Partial.cs
https://github.com/unoplatform/Uno.Themes/issues/577
- Feature
> feat(CalendarView): Add Uno specific properties to make styling easier

- src/Uno.UI.Runtime.Skia.Gtk/GtkHost.cs
- src/Uno.UI.Runtime.Skia.Gtk/System/LauncherExtension.cs
- src/Uno.UI.Runtime.Skia.Gtk/System/LauncherHelpers/DesktopFile.cs
- src/Uno.UI.Runtime.Skia.Gtk/System/LauncherHelpers/MimeAppsList.cs
- src/Uno.UI.Runtime.Skia.Tizen/System/TizenLauncherExtension.cs
- src/Uno.UI.Runtime.Skia.Wpf/Extensions/System/LauncherExtension.cs
- src/Uno.UI.Runtime.Skia.Wpf/WpfHost.cs
- src/Uno.UWP/Generated/3.0.0.0/Windows.System/Launcher.cs
- src/Uno.UWP/System/ILauncherExtension.skia.cs
- src/Uno.UWP/System/Launcher.cs
- src/Uno.UWP/System/Launcher.skia.cs
GitHub Issue (If applicable): closes #5770
- Feature
`Launcher.QueryUriSupportAsync` throws `NotImplementedException` on WPF and Gtk platforms.
`Launcher.QueryUriSupportAsync` tries to query for support by using the Registry (on Windows) and by using `xdg-settings` (on Linux).
> Support for Launcher.QueryUriSupportAsync on Skia.Gtk and Skia.Wpf

- src/Uno.UI.Runtime.Skia.Gtk/GtkHost.cs
- src/Uno.UI.Runtime.Skia.Gtk/UI/Core/CursorExtensions.cs
- src/Uno.UI.Runtime.Skia.Gtk/UI/Core/Cursors.cs
GitHub Issue (If applicable): closes #5851
- Feature
Many `CoreCursorTypes` aren't supported. They use the default `Arrow`, which may be confusing sometimes.
All cursor types are supported, except Arrow with Pin and Arrow with People symbols.
> feat: Cursors loaded from Gtk display theme. Support for more cursors on Gtk.

- doc/articles/features/uno-material.md
- doc/articles/guides/uno-material-walkthrough.md
> docs(Material): Update Material docs for new XAML init method

- src/AddIns/Uno.UI.Lottie/LottieVisualSourceBase.wasm.cs
- src/AddIns/Uno.UI.Lottie/Uno.UI.Lottie.Wasm.csproj
- src/Uno.UI/UI/Xaml/Media/Imaging/BitmapImage.wasm.cs
- src/Uno.UI/UI/Xaml/Media/Imaging/SvgImageSource.wasm.cs
- src/Uno.UWP/Storage/Helpers/AssetsManager.wasm.cs
- src/Uno.UWP/Storage/Helpers/AssetsPathBuilder.wasm.cs
- Bugfix
Fixes assets uris when path-based deep-linking is used.
> fix: Use UNO_BOOTSTRAP_WEBAPP_BASE_PATH to support path-based deep-linking

- doc/articles/features/uno-cupertino.md
- doc/articles/guides/uno-cupertino-walkthrough.md
- doc/articles/supported-libraries.md
- doc/articles/toc.yml
- doc/articles/using-uno-ui.md
No Cupertino docs
Cupertino docs
> docs(Cupertino): Add documentation for Uno.Cupertino

- src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.cs
- src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.xaml
- src/Uno.UI.RuntimeTests/IntegrationTests/common/CalendarHelper.h.cs
- src/Uno.UI.RuntimeTests/IntegrationTests/common/TestServices.cs
- src/Uno.UI.RuntimeTests/IntegrationTests/dxaml/BaseDxamlTestClass.cs
- src/Uno.UI.RuntimeTests/IntegrationTests/dxaml/Event.cs
- src/Uno.UI.RuntimeTests/IntegrationTests/dxaml/controls/calendardatepicker/CalendarDatePickerIntegrationTests.cs
- src/Uno.UI.RuntimeTests/IntegrationTests/dxaml/controls/calendarview/CalendarViewAutomationPeerIntegrationTests.cs
- src/Uno.UI.RuntimeTests/IntegrationTests/dxaml/controls/calendarview/CalendarViewIntegrationTests.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/DatePickerIntegrationTests.cs
- src/Uno.UI/UI/Xaml/Controls/CalendarView/CalendarDatePicker.Events.cs
- src/Uno.UI/UI/Xaml/Controls/CalendarView/CalendarViewGeneratorHost.cs
- src/Uno.UI/UI/Xaml/Controls/CalendarView/CalendarViewGeneratorMonthViewHost.cs
- src/Uno.UI/UI/Xaml/Controls/CalendarView/CalendarView_Partial.cs
- src/Uno.UI/UI/Xaml/Controls/CalendarView/CalendarView_Partial_Selection.cs
- src/Uno.UI/UI/Xaml/Markup/Reader/XamlObjectBuilder.cs
This PR introduce missing unit tests that should has been introduced in PR #6098 
> CalendarView Leftovers

- src/Uno.UI/UI/Xaml/Window.macOS.cs
- Bugfix
FocusVisualLayer is available for macOS and does not fail with an NRE.
> fix(reg): Add missing FocusVisualLayer

- build/Uno.WinUI.nuspec
- src/Directory.Build.targets
- src/SamplesApp/SamplesApp.macOS/SamplesApp.macOS.csproj
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.UWP/BlankApp.Uwp.csproj
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-winui/UnoWinUIQuickStart.Windows.Desktop/UnoWinUIQuickStart.Windows.Desktop.csproj
- src/SolutionTemplate/UnoSolutionTemplate/UWP/UnoQuickStart.Uwp.csproj
> chore: Bump Uno.Core and Uno.SourceGenerationTasks

- src/Uno.UWP/Storage/Helpers/AssetsPathBuilder.wasm.cs
> docs: Add doc for deep-linking internal support

- src/Uno.UI/WasmScripts/Uno.UI.js
- src/Uno.UI/ts/WindowManager.ts
- Bugfix
Fixed "broken image" visual temporarily appearing when loading an application.
> fix(wasm): Fix invalid splash screen path resolution

- doc/articles/Uno-UI-Performance.md
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/6251
> docs: Update documentation performance for ItemsRepeater/ItemsControl

- src/Uno.UWP/Generated/3.0.0.0/Windows.Security.Authentication.Web/WebAuthenticationBroker.cs
Fixes https://github.com/unoplatform/uno/issues/6252
> fix: Fix WebAuthenticationBroker wrongly reported as NotImplemented.

- src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/CalendarDatePicker.cs
Fixes https://github.com/unoplatform/uno/issues/6268
> fix(calendardatepicker): The type `CalendarDatePicker` were wrongly marked as not implemented.

- doc/articles/Uno-UI-Performance.md
fixes: https://github.com/unoplatform/uno/issues/6267
> docs: Add BindableAttribute performance details

- .github/ISSUE_TEMPLATE/bug-report.md
> chore: Update bug template

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Native_View.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/NativeViewPage/NativeView_Grid_Page.xaml
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/NativeViewPage/NativeView_Grid_Page.xaml.cs
- src/Uno.UI/UI/Xaml/Controls/Grid/Grid.Properties.cs
- src/Uno.UI/UI/Xaml/Media/VisualTreeHelper.cs
Propagate attached properties (Grid.Row etc) set on native views to the managed wrapper, so that the parent Grid properly takes them into account.
GitHub Issue (If applicable): fixes https://github.com/unoplatform/nventive-private/issues/207
- Bugfix
> fix(grid): Support Grid attached properties on native views

- src/Uno.Foundation/Extensions/NotifyCollectionChangedEventArgsExtensions.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs
- src/Uno.UI/UI/Xaml/Controls/Primitives/Selector.cs
GitHub Issue (If applicable): fixes #6276
- Bugfix
> fix(selector): Fix support for ObservableCollection.Move

- doc/articles/uno-community-toolkit.md
> docs: Adjust community toolkit docs for cross-target libraries

- .github/ISSUE_TEMPLATE/bug-report.md
> docs: Adjust bug template

- doc/articles/uno-builds-troubleshooting.md
> docs: Update the binlog creation docs

- src/SolutionTemplate/UnoSolutionTemplate/Shared/Assets/SharedAssets.md
> fix(templates): fixed minor typo

- src/Directory.Build.targets
GitHub Issue (If applicable): fixes #6352
- Bugfix
Tests fail to run locally in Uno.UI.Tests due to various errors
Tests run
> fix: Update MSTest to fix local runs

- doc/articles/features/working-with-accessibility.md
- src/Uno.UWP/Generated/3.0.0.0/Windows.UI.ViewManagement/AccessibilitySettings.cs
- src/Uno.UWP/UI/ViewManagement/AccessibilitySettings.cs
- src/Uno.UWP/UI/ViewManagement/UISettings.cs
- src/Uno.UWP/WinRTFeatureConfiguration.Accessibility.cs
GitHub Issue (If applicable): closes #6355
- Feature
Not supported
Supported for purposes of Community toolkit controls.
> feat: AccessibilitySettings class

- doc/templates/uno/styles/scss/main.scss
- Bugfix
get-started button is purple
Get started button is green and transitions to blue, like on platform.uno
before
after
> docs: updated get started button style to match platform.uno

- src/Uno.UWP/Devices/Haptics/SimpleHapticsController.Android.cs
GitHub Issue (If applicable): fixes #6368
- Bugfix
Haptics are not available everywhere.
Haptics fallback to vibration if not available on the device
> fix: Auto fallback to vibration on Android haptics

- src/Uno.UI/LayoutProvider.Android.cs
- src/Uno.UI/UI/Xaml/ApplicationActivity.Android.cs
fixes https://github.com/unoplatform/nventive-private/issues/83
- Bugfix
Android 11 keyboard is overlapping controls
> fix(droid): Keyboard overlapping controls

- src/Uno.Foundation/Generated/2.0.0.0/Windows.Foundation.Metadata/WebHostHiddenAttribute.cs
- src/Uno.Foundation/Metadata/WebHostHiddenAttribute.cs
- src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Markup/MarkupExtensionReturnTypeAttribute.cs
- src/Uno.UI/Microsoft/UI/Xaml/Markup/MarkupExtensionReturnTypeAttribute.cs
GitHub Issue (If applicable): Fixes #6335
- Feature
WebHostHiddenAttribute and MarkupExtensionReturnTypeAttribute are not implemented and throw when used.
WebHostHiddenAttribute and MarkupExtensionReturnTypeAttribute are implemented and can be used.
> Implementation of WebHostHiddenAttribute and MarkupExtensionReturnTypeAttribute

- build/PackageDiffIgnore.xml
> ci: Bump PackageDiff ignore version

- doc/articles/toc.yml
- doc/articles/uno-development/debugging-templates.md
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/5988
> docs: Add solution templates debugging steps

- src/Uno.Foundation.Runtime.WebAssembly/Interop/JSObjectMetadataProvider.wasm.cs
GitHub Issue (If applicable): fixes #6429
- Bugfix
JSObjectMetadataProvider uses a dictionary to store available methods, which fails when a method is overloaded or method hiding is used. This is the case for focus-related properties on Control, where the getters and setters are then duplicated - once for Control, once for UIElement
Duplicate methods are ignored and a warning is logged for those which don't come from Uno directly.
> fix: JSObjectMetadataProvider throws due to duplicate method names

- src/Uno.UWP/Devices/Geolocation/Geolocator.iOSmacOS.cs
GitHub Issue (If applicable): resolved #4853
- Bugfix
The `Geolocator.RequestAccessAsync()` method never returns after permission is denied or granted, be promptless or after the user has responded to the permission prompt.
The `Geolocator.RequestAccessAsync()` method should return as soon as the location permission is updated.
The issue was with `CLLocationManager.AuthorizationChanged` never being called. We had to use the same/similar method from `CLLocationManagerDelegate` which actually works.
> fix: Geolocator.RequestAccessAsync() not returning on ios14

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Shapes/Rectangle_Rounding.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/Rectangle_Rounding.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/Rectangle_Rounding.xaml.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Shapes/Given_Android_Relative_Shape_Rounding.cs
- src/Uno.UI/Extensions/ViewHelper.Android.cs
- src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.Android.cs
- src/Uno.UI/UI/Xaml/Controls/Layouter/Layouter.Android.cs
- src/Uno.UI/UI/Xaml/Shapes/Ellipse.Android.cs
- src/Uno.UI/UI/Xaml/Shapes/Rectangle.Android.cs
- src/Uno.UI/UI/Xaml/Shapes/Shape.Android.cs
- src/Uno.UI/UI/Xaml/UIElement.Android.cs
fixes https://github.com/unoplatform/nventive-private/issues/214
- Bugfix
> fix(Layout): [Android] Properly round values when converting logical to physical pixels. Apply rounding offsets for Path rendering

- src/Uno.UI/UI/Xaml/Shapes/Shape.cs
- src/Uno.UI/UI/Xaml/Shapes/Shape.iOSmacOS.cs
- src/Uno.UI/UI/Xaml/Shapes/Shape.skia.cs
Fixes https://github.com/unoplatform/uno/issues/6445
The layout was invalidated when a brush was changed on a shape.
The layout is no more invalidated.  Only the rendered result.
> Improve perf with brushes on shapes

- src/Uno.UWP/Security/Credentials/PasswordVault.Android.cs
Android API level under 
When an device bellow API 23 try to use the PasswordVault, it crash with the error: 
{Java.Security.NoSuchAlgorithmException: KeyGenerator AES implementation not found
at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <212d71eb7ebe48a08a28594a6b73aa4b>:0
at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeObjectMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x00018] in <212d71eb7ebe48a08a28594a6b73aa4b>:0
KeyStore in < API 23 can only store asymmetric keys, specifically only RSA/ECB/PKCS1Padding.
Conditional …
> Support of PassworVault for API Level inferior to 23

- doc/articles/get-started-winui3.md
Reunion swapped for WindowsAppSDK
> docs: Update WinUI-get started

- doc/articles/get-started-winui3.md
> docs: Adjust uno-winui startup documentation

- README.md
Added supported Windows 11 and augmented how Uno works on those platforms.
> docs: Update About Uno Platform

- doc/articles/features/uno-material.md
Part of: https://github.com/unoplatform/Uno.Themes/pull/594
GitHub Issue (If applicable): https://github.com/unoplatform/Uno.Themes/issues/580
Docs don't include the new styles that will be added with the PR to Uno.Themes Material button
The styles added are now specified 
Please DO NOT merge this until https://github.com/unoplatform/Uno.Themes/pull/594 is through code review. This PR is merely the doc update to accompany it.
> docs: Update docs to reflect added Material button styles

- src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/Repeater/FlowLayoutCollectionChangeTests.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/ElementManager.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/FlowLayoutAlgorithm.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/ItemsRepeater.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/UniformGridLayout/UniformGridLayout.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/ViewportManager.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/ViewportManagerWithPlatformFeatures.cs
- Feature
Some parts not updated.
Up to date.
> chore: Update ItemsRepeater to latest WinUI sources

- build/Uno.WinUI.nuspec
- build/uno.winui.runtime-replace.targets
- build/uno.winui.single-project.targets
- build/uno.winui.targets
- build/uno.winui.uap.targets
- doc/articles/get-started-vs-2022.md
- doc/articles/toc.yml
- src/SolutionTemplate/UnoSolutionTemplate.net6/Mobile/Mobile.vstemplate
- Bugfix
- Bump source generators for net6 preview 6 compat
- Adjust runtime targets for net6-windows
- Fix missing macOS files
> Misc net6 template fixes

- src/Uno.UI/Microsoft/UI/Xaml/Controls/NavigationView/NavigationView.Header.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/NavigationView/NavigationView.cs
GitHub Issue (If applicable): fixes #6517
- Bugfix
- Feature
`NavigationView` fails when top pane title is missing in a custom template.
No longer fails.
> `NavigationView` startup fix when top pane title is missing, update to latest WinUI

- src/Uno.UWP/Storage/Pickers/FileOpenPicker.Android.cs
GitHub Issue (If applicable): #5893 (partly)
- Bugfix
- Feature
SettingsIdentifier  is ignored.
SettingsIdentifier  is used by FileOpenPicker.
Copied from #2896.
> feat: FileOpenPicker SettingsIdentifier (for Android)

- .vsts-ci.yml
- build/ci/.azure-devops-docs.yml
- build/ci/.azure-devops-project-template-tests.yml
- build/ci/.azure-devops-samplesapp-uitests-build.yml
- build/ci/.azure-devops-screenshot-compare.yml
- build/ci/.azure-devops-skia-tests.yml
- build/ci/.azure-devops-unit-tests.yml
> ci: Use more scaled sets agents

- build/Uno.WinUI.nuspec
- build/uno.winui.win.targets
- Bugfix
Adjust Skia+WPF targeting
> fix(reg): Adjust wpf+skia target

- src/Uno.Analyzers.Tests/UnoNotImplementedTests.cs
- src/Uno.Analyzers/UnoNotImplementedAnalyzer.cs
GitHub Issue (If applicable): #6548
- Bugfix
False negatives with new language features like target-typed new (aka implicit object creation)
Analysis is now done using IOperation instead.
Fixes #6548
> Write UnoNotImplementedAnalyzer using IOperation

- build/ios-uitest-run.sh
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml/DragAndDropTests/DragDrop_ListViewReorder_Automated.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/DragAndDrop/DragDrop_ListView_Custom_States.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/DragAndDrop/DragDrop_ListView_Custom_States.xaml.cs
- src/Uno.UI/Extensions/GeneratorDirectionExtensions.cs
- src/Uno.UI/UI/Xaml/Controls/ItemsControl/ItemsControl.cs
- src/Uno.UI/UI/Xaml/Controls/ItemsStackPanel/ItemsStackPanelLayout.Android.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/BufferViewCache.Android.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.DragDrop.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.DragDrop.mux.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.h.mux.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.Android.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.Containers.Android.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.managed.cs
- src/Uno.UI/UI/Xaml/Controls/Primitives/SelectorItem.cs
- src/Uno.UI/UI/Xaml/Controls/Primitives/VisualStatesHelper.h.mux.cs
- src/Uno.UI/UI/Xaml/Controls/Primitives/VisualStatesHelper.mux.cs
- src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.ConstantVelocity.cs
- src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.cs
- src/Uno.UWP/Extensions/MathEx.cs
GitHub Issue (If applicable): resolves #995
- show item visual states during reordering
- scroll list while dragging items near edge
- Feature
> Additional ListView drag-and-drop features

- src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml
- src/Uno.UI/UI/Xaml/Style/Generic/SystemResources.xaml
GitHub Issue (If applicable): fixes #6394 
- Feature
The thumb control now has a default style defined.
> feat: Add Thumb control default style

- src/Uno.UI/Controls/Window.macOS.cs
fixes #5979, fixes #6330 
- Bugfix
Unable to resize Window from the bottom edges
> fix(macOS): Window sizing

- src/Uno.UI/Behaviors/VisibleBoundsPadding.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/5274
- Bugfix
Fail safe on `Window.Current` being null in `VisibleBoundsPadding`
> fix(visibleboundspadding): Adjust for Window.Current being null

- src/Uno.UI/UI/Xaml/Internal/VisualTree.cs
- Bugfix
Reduce logging level for focus search message `Visual Tree was not found.`
> fix: Reduce focus search logging level

- src/SamplesApp/SamplesApp.UITests/Extensions/QueryExtensions.cs
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/CanvasTests/Canvas_Measurement_Tests.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Canvas/Canvas_In_Canvas.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Canvas/Canvas_In_Canvas.xaml.cs
- src/Uno.UI/UI/Xaml/UIElement.Layout.netstd.cs
GitHub Issue (If applicable): fixes #5115
- Bugfix
Canvas in a Canvas does not display its content.
> fix: [Wasm][Skia] Canvas in Canvas rendering

- src/Uno.Analyzers.Tests/Uno.Analyzers.Tests.csproj
- src/Uno.Analyzers.Tests/UnoNotImplementedTests.cs
- src/Uno.Analyzers.Tests/Verifiers/CSCodeFix+Test.cs
- src/Uno.Analyzers.Tests/Verifiers/CSCodeFix.cs
- src/Uno.Analyzers.Tests/Verifiers/CSHelper.cs
GitHub Issue (If applicable): #6549
- Test enhancement
Inability to write tests for a specific language version.
Ability to write tests for a specific language version.
Fixes #6549
> Move to Microsoft.CodeAnalysis.CSharp.CodeFix.Testing.MSTest

- build/ci/templates/dotnet6-install-mac.yml
- build/ci/templates/dotnet6-install-windows.yml
> ci: Freeze dotnet check manifest version

- src/Uno.UI/WasmScripts/Uno.UI.js
- src/Uno.UI/ts/WindowManager.ts
cf. https://github.com/unoplatform/uno/pull/6163
fixes: https://github.com/unoplatform/uno/issues/6439
> fix: Fix merge issue which rollbakcs changes of #6163

- src/Uno.UI/WasmScripts/Uno.UI.js
Every time I build, this file gets updated automatically with the content in this PR
The file is now synced with `WindowManager.ts` and `LightSensor.ts` so building doesn't produce interrupting changes.
> chore: Update Uno.UI.js (sync with TypeScript files)

- doc/articles/splash-screen.md
> docs: Update Android splash screen instructions

- doc/articles/interop/wasm-javascript-3.md
TextBlock defaults the text color as White correctly but StackPanel background needs theme info.
> TextBlock content is not visible in browsers with the dark theme

- doc/articles/features/using-linux-framebuffer.md
- doc/articles/toc.yml
- doc/articles/uno-development/building-uno-ui.md
> .NET 6, Framebuffer docs

- doc/articles/contributing/guidelines/issue-triage.md
- Adhere to some markdownlint rules that I manually caught (will be looking into enabling that via GitHub Actions later).
- Delete doc about labels that don't exist (probably they existed in past)
> Minor changes in issue-triage.md

- src/SamplesApp/SamplesApp.Shared/App.xaml.cs
- Bugfix
Adjust for regression on gtk head.
> fix(reg): Fix missing accessibility for GTK samplesapp head

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/SourceGenerators/XamlGenerationTests/Issue3171.xaml
GitHub Issue (If applicable): #3171
- Bugfix
Invalid code is generated
Correct code is generated
Fixes #3171
> fix: Generate valid code for type in default namespace in DataTemplate

- src/Uno.UI-vs4mac-macOS-only.sln
- Bugfix
Unable to build SampleApp.macOS from VS4M.
> chore: (macOS) fix SampleApp VS4M solution

- src/SourceGenerators/XamlGenerationTests/XBindNullable.xaml
- src/SourceGenerators/XamlGenerationTests/XBindNullable.xaml.cs
GitHub Issue (If applicable): closes #5581
Test-only change.
The issue was fixed in #5725, and a test was added for nullable reference type. I extended the test for nullable value type as well.
> test: Add test for x:Bind of nullable value type

- doc/articles/guides/uno-cupertino-walkthrough.md
- doc/articles/guides/uno-material-walkthrough.md
- Bugfix
- `[TIP!]` It doesn't render correctly.
- Inconsistency in casing (`TIP` vs `Tip`)
- Renders correctly by changing to `[!TIP]`.
- Casing consistency to all uppercase.
> docs: Fix TIP syntax

- build/ci/.azure-devops-commitsar.yml
> ci: Run commitsar on PRs only

- build/ci/.azure-devops-commitsar.yml
> ci: Adjust commitsar to not skip dependents

- build/ci/.azure-devops-commitsar.yml
> ci: Adjust commitsar run

- src/Uno.UI.RuntimeTests/IntegrationTests/common/TestServices.WindowHelper.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_System/Given_DispatcherQueue.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_System/Given_DispatcherQueueTimer.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs
- src/Uno.UI.Tests/BinderTests/Given_Binder.TwoWay.cs
- src/Uno.UI.Tests/BinderTests/Given_Binder.cs
- src/Uno.UI/Mock/DispatcherTimer.net.cs
- src/Uno.UI/UI/Xaml/Controls/ItemsControl/ItemsControl.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/NativeListViewBase.iOS.cs
- src/Uno.UI/UI/Xaml/DependencyPropertyDetails.cs
- src/Uno.UI/UI/Xaml/DependencyPropertyDetailsCollection.Bindings.cs
GitHub Issue (If applicable): fixes https://github.com/unoplatform/kahua-private/issues/7
Apply a binding rather than a one-time set to the property targeted by DisplayMemberPath. This ensures items update correctly if the property value should change.
- Bugfix
> fix(itemscontrol): Bind DisplayMemberPath target

- build/PackageDiffIgnore.xml
- build/Uno.UI.Build.csproj
> ci: Restore package diff

- doc/articles/features/working-with-xaml-hot-reload.md
> docs: Update debugging VSIX documentation

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
> chore: Simplify generated #if directives

- src/Uno.UWPSyncGenerator/NamedTypeSymbolStringComparer.cs
`GetHashCode` can return different hash codes for equally-considered symbols
`GetHashCode` will return the same hash code for equally-considered symbols. There might be nothing that now depends on `GetHashCode`, but thought it's good to fix anyway.
> fix: Fix `GetHashCode` implementation of `NamedTypeSymbolStringComparer`

- src/SamplesApp/SamplesApp.Shared/App.xaml.cs
- src/SamplesApp/SamplesApp.UITests/Extensions/FluentExtensions.cs
- src/SamplesApp/SamplesApp.UITests/SampleControlUITestBase.cs
- src/SamplesApp/SamplesApp.UITests/TestFramework/ImageAssert.ExpectedPixels.cs
- src/SamplesApp/SamplesApp.UITests/TestFramework/ImageAssert.cs
- src/SamplesApp/UITests.Shared/Windows_Devices/Midi/MidiDeviceWatcher.cs
- src/SamplesApp/UITests.Shared/Windows_UI_ViewManagement/TitleBarColorTests.xaml.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/SourceGenerators/Uno.UI.Tasks/LinkerHintsGenerator/LinkerDefinitionMergerTask.cs
- src/Uno.UI.Runtime.Skia.Gtk/UI/Text/FontWeightExtensions.cs
- src/Uno.UI.RuntimeTests/Tests/Uno_Helpers/Given_AppDataUriEvaluator.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement_And_Leak.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/DatePickerIntegrationTests.cs
- src/Uno.UI/Controls/Window.macOS.cs
- src/Uno.UI/UI/Xaml/Documents/Hyperlink.cs
- src/Uno.UI/UI/Xaml/Input/Internal/FocusProperties.cs
- src/Uno.UWP/ApplicationModel/PackageId.iOSmacOS.cs
- src/Uno.UWP/Helpers/Theming/SystemThemeHelper.macOS.cs
- src/Uno.UWP/Storage/Pickers/Internal/UTTypeMapper.iOSmacOS.cs
The change doesn't affect the product. Just few compile-time warnings.
> fix: Cleanup few warnings

- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/Uno.ProjectTemplates.Dotnet.csproj
- src/SolutionTemplate/UnoSolutionTemplate.net6/Mobile/Android/Main.Android.cs
- src/SolutionTemplate/UnoSolutionTemplate.net6/Shared/App.xaml.cs
- src/SolutionTemplate/UnoSolutionTemplate.net6/Skia.WPF.Host/UnoQuickStart.Skia.Wpf.Host.csproj
- src/SolutionTemplate/UnoSolutionTemplate/Shared/App.xaml.cs
GitHub Issue (If applicable): fixes #6647
- Update project template
- Unneeded `using`s.
- Unneeded Unneeded conditional directive.
- `warning NETSDK1137: It is no longer necessary to use the Microsoft.NET.Sdk.WindowsDesktop SDK. Consider changing the Sdk attribute of the root Project element to 'Microsoft.NET.Sdk'.`
- NetAnalyzers diagnostics around using the general purpose `Exception` type and parameter name in override method being different from the one in the overridden method
Fix all of these.
> chore: Update .NET 6 template

- src/AddIns/Uno.UI.MSAL/Uno.UI.MSAL.csproj
- src/AddIns/Uno.UI.MSAL/Uno.UI.MSAL.net6.csproj
- Bugfix
Avoids the UWP tooling from picking it up and add it as part of the app layout
> fix: Don't mark buildTransitive files in Uno.UI.MSAL as content

- src/Uno.Analyzers.Tests/UnoNotImplementedTests.cs
GitHub Issue (If applicable): closes #5029
- Test only
> test: Add analyzer test for object initializer syntax

- build/android-uitest-wait-systemui.sh
Retry adb commands when waiting for the android emulator startup
> ci: Adjust adb to be retried for emulator startup

- src/Uno.UI/Controls/Window.iOS.cs
Backport for unoplatform/nventive-private#238
> Backport for #6720 on release/stable/3.1

- src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.Android.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.Containers.Android.cs
Address issues when dragging, particularly when there are too few items to fill the available viewport.
GitHub Issue (If applicable): #995
- Bugfix
> fix(listview): [Android] Fix glitches during drag-and-drop

- src/Uno.UI/Microsoft/UI/Xaml/Controls/Materials/Backdrop/BackdropMaterial.Properties.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/Materials/Backdrop/BackdropMaterial.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/Materials/Backdrop/MicaController.cs
GitHub Issue (If applicable): closes #6614
- Feature
Not supported.
Supported.
> feat: BackdropMaterial fallback support

- src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.cs
- src/Uno.UI-iOS-only.slnf
- [iOS] Fix SamplesApp build with solution filter enabled
- Don't retry runtime tests while debugging
> chore: Misc solution fixes

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ComboBox.cs
GitHub Issue (If applicable): Related to #4686
- Test only
Supersedes #6775 
> test: Add ignored tests for handling SelectedIndex

- src/Uno.UI.RuntimeTests/Helpers/RectAssert.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/NativeContainer.Android.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/NativeContainer.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/NativeContainer.iOS.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/NativeContainer.managed.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/NativeContainer.xamarin.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media/Given_VisualTreeHelper.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media/VisualTreeHelperPages/Native_View_Page.xaml
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media/VisualTreeHelperPages/Native_View_Page.xaml.cs
- src/Uno.UI/UI/Xaml/Media/VisualTreeHelper.cs
GitHub Issue (If applicable): closes #995 
Search within native views when global hit-testing. This allows DragOver, DragEnter etc to work properly when target view has a native view in its ancestry (eg for native Frame navigation on iOS, using a native SplitView style on Android, etc).
- Bugfix
> fix(dragdrop): [iOS] [Android] Support drag over events when native view in hierarchy

- doc/templates/uno/styles/docfx.js
- Bugfix
The recently updated logo image path is incorrect in testing/prod environements
The logo image path should now be working in testing/prod environements
Before
After
> docs: updated logo image path to be correct in prod/testing environments

- src/Directory.Build.targets
- src/SamplesApp/SamplesApp.Skia.WPF/SamplesApp.Skia.WPF.csproj
- src/Uno.UI.Runtime.Skia.Wpf/Uno.UI.Runtime.Skia.Wpf.csproj
GitHub Issue (If applicable): closes #4036 (please someone make sure this should actually be closed by this change)
> fix: Use SkiaSharp.Views.WPF for .NET Core target

- src/Uno.UWP/Generated/3.0.0.0/Windows.UI.Notifications/ScheduledToastNotification.cs
- src/Uno.UWP/UI/Notifications/ScheduledToastNotification.cs
GitHub Issue (If applicable): #5890 (partly)
- Feature
No ScheduledToastNotification implementation.
Fields that are "the must" are implemented for all platforms, and two more fields for Android.
For all platforms, I implemented fields that seems to be required (without any of it, ScheduledToastNotification has no sense).
For Android, I implemented two more fields, as I know that these fields can be implemented (because I implemented it over year ago in non-scheduled Toasts, see #2585).
Implementing toast scheduler is more tricky. 
> feat: ScheduledToastNotification

- build/ci/templates/dotnet-install.yml
- build/ios-uitest-run.sh
> ci: Fix nuget restore validation error

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase_Items.cs
- src/Uno.UI/UI/Xaml/Controls/Primitives/Selector.cs
Fixes regression introduced in https://github.com/unoplatform/uno/pull/6742 arising from 'double dipping' the collection changed event, both directly on the ItemsSource and via ItemsControl.Items. Adds a test to catch this.
- Bugfix
fixes https://github.com/unoplatform/kahua-private/issues/17
> fix(reg): Fix SelectedIndex update when ItemsSource is ObservableCollection

- doc/articles/uno-development/debugging-uno-ui.md
> docs: Add tips on nuget package override

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Shapes/Path_Tests.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/PathTestsControl/Path_Dynamic_Geometries.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/PathTestsControl/Path_Dynamic_Geometries.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/PathTestsControl/Path_FillRule.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/PathTestsControl/Path_FillRule.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/PathTestsControl/Path_Geometries.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/PathTestsControl/Path_Geometries.xaml.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlPathParser/GeneratedStreamGeometryContext.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlPathParser/Parsers.cs
- src/Uno.UI/Media/GeometryHelper.cs
- src/Uno.UI/Media/StreamGeometry.Android.cs
- src/Uno.UI/UI/Xaml/Media/EllipseGeometry.wasm.cs
- src/Uno.UI/UI/Xaml/Media/FillRuleExtensions.Skia.cs
- src/Uno.UI/UI/Xaml/Media/FillRuleExtensions.iOSmacOS.cs
- src/Uno.UI/UI/Xaml/Media/Geometry.wasm.cs
- src/Uno.UI/UI/Xaml/Media/GeometryData.wasm.cs
- src/Uno.UI/UI/Xaml/Media/GeometryGroup.wasm.cs
- src/Uno.UI/UI/Xaml/Media/GeometryHelper.cs
- src/Uno.UI/UI/Xaml/Media/LineGeometry.wasm.cs
- src/Uno.UI/UI/Xaml/Media/PathGeometry.wasm.cs
- src/Uno.UI/UI/Xaml/Media/RectangleGeometry.wasm.cs
- src/Uno.UI/UI/Xaml/Shapes/Path.iOSmacOS.cs
- src/Uno.UI/UI/Xaml/Shapes/Path.skia.cs
- src/Uno.UI/UI/Xaml/Shapes/Shape.iOSmacOS.cs
- src/Uno.UI/UI/Xaml/Shapes/Shape.layout.cs
Closes https://github.com/unoplatform/uno/issues/6703
~~TO BE MERGED AFTER https://github.com/unoplatform/uno/pull/6817~~ (merged)
`FillRule` property were not properly supported on iOS & Android.
> Finish implementation of FillRule

- src/Uno.UI/UI/Xaml/Controls/Pivot/Pivot.cs
GitHub Issue (If applicable): closes #2171
- Bugfix
Visual states not applied on hover/press
Visual states are correctly applied.
> fix: Apply pointer visual states of pivot items

- src/Uno.UI/BannedSymbols.txt
- src/Uno.UI/Behaviors/VisibleBoundsPadding.cs
- src/Uno.UI/Directory.Build.targets
- src/Uno.UI/Microsoft/UI/Xaml/Controls/AnimatedIcon/AnimatedIcon.Properties.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/Materials/Backdrop/BackdropMaterial.Properties.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/Materials/Backdrop/BackdropMaterial.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/RecyclePool.Properties.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/RecyclePoolFactory.cs
- src/Uno.UI/MixinGeneration.targets
- src/Uno.UI/UI/Xaml/Controls/ScrollViewer/ScrollViewer.Uno.cs
- src/Uno.UI/UI/Xaml/Controls/ToolTip/ToolTipService.cs
- src/Uno.UI/UI/Xaml/DependencyProperty.cs
- src/Uno.UI/UI/Xaml/ResourceDictionary.debugging.cs
GitHub Issue (If applicable): Followup to #6630 (see #5984)
> chore: Make sure attached DPs use FrameworkPropertyMetadata

- doc/articles/get-started-winui3.md
> docs:Fix WindowsAppSDK url markup

- src/SamplesApp/SamplesApp.Shared/SamplesApp.Shared.projitems
- src/SamplesApp/SamplesApp.Shared/Strings/es-ES/Resources.resw
- src/SamplesApp/SamplesApp.Shared/Strings/es-MX/Resources.resw
- src/Uno.UI.RuntimeTests/Tests/Windows_ApplicationModel_Resources/Given_ResourceLoader.cs
- src/Uno.UWP/ApplicationModel/Resources/ResourceLoader.cs
GitHub Issue (If applicable): closes #6469
- Bugfix
Specific cultures are not used if neutral culture isn't found.
Fallback to specific cultures.
> fix: Fallback to specific regional culture if neutral culture isn't found

- doc/articles/Uno-UI-Performance.md
> docs: Adjust performance docs layout

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/BorderTests/Border_Tests.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/BorderTests/Border_LinearGradientBrush.xaml
- src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.wasm.cs
Hide whitespace changes for easier review of the test
- Bugfix
Linear gradient border not working
Working:
> fix: Fix linear gradient border not working on Wasm

- build/PackageDiffIgnore.xml
- src/SamplesApp/SamplesApp.Skia.Tizen/tizen-manifest.xml
- src/SamplesApp/UITests.Shared/Windows_UI_Notifications/BadgeNotificationTests.xaml
- src/Uno.UI.Runtime.Skia.Tizen/TizenHost.cs
- src/Uno.UI.Runtime.Skia.Tizen/UI/Notifications/TizenBadgeUpdaterExtension.cs
- src/Uno.UI/WasmScripts/Uno.UI.d.ts
- src/Uno.UI/WasmScripts/Uno.UI.js
- src/Uno.UI/ts/Windows/UI/Notifications/BadgeUpdater.ts
- src/Uno.UWP/Generated/3.0.0.0/Windows.UI.Notifications/BadgeNotification.cs
- src/Uno.UWP/Generated/3.0.0.0/Windows.UI.Notifications/BadgeTemplateType.cs
- src/Uno.UWP/Generated/3.0.0.0/Windows.UI.Notifications/BadgeUpdateManager.cs
- src/Uno.UWP/Generated/3.0.0.0/Windows.UI.Notifications/BadgeUpdater.cs
- src/Uno.UWP/UI/Notifications/BadgeNotification.cs
- src/Uno.UWP/UI/Notifications/BadgeTemplateType.cs
- src/Uno.UWP/UI/Notifications/BadgeUpdateManager.cs
- src/Uno.UWP/UI/Notifications/BadgeUpdater.cs
- src/Uno.UWP/UI/Notifications/BadgeUpdater.iOS.cs
- src/Uno.UWP/UI/Notifications/BadgeUpdater.macOS.cs
- src/Uno.UWP/UI/Notifications/BadgeUpdater.skia.cs
- src/Uno.UWP/UI/Notifications/BadgeUpdater.wasm.cs
- src/Uno.UWP/UI/Notifications/IBadgeUpdaterExtension.skia.cs
GitHub Issue (If applicable): closes #4404
- Feature
Not supported.
Supported.
> `BadgeNotification` on WASM and Tizen

- src/Uno.Analyzers/UnoNotImplementedAnalyzer.cs
GitHub Issue (If applicable): For cases like https://github.com/unoplatform/uno/issues/6027, it's better to inform the developer that something isn't supported when used in XAML.
- Bugfix
No diagnostic is reported if unsupported member is used in XAML due to the C# code being auto-generated and is not analyzed.
A diagnostic is reported.
> fix: Report not implemented diagnostics for generated code

- src/Uno.UI/UI/Xaml/UIElement.Android.cs
- Removes the computation of native-only children based clipping
- Don't set clip bounds if unset and unchanged
> perf(android): Adjust clipping computation performance

- doc/articles/uno-development/creating-ui-tests.md
- src/Directory.Build.props
- src/SamplesApp/SamplesApp.UITests/Constants.cs
> chore: Detect test CurrentPlatform based on TFM override

- src/Uno.UI/BaseActivity.Android.cs
- src/Uno.UI/UI/Xaml/Controls/Canvas/Canvas.Android.cs
- src/Uno.UI/UI/Xaml/Extensions/FontHelper.Android.cs
- src/Uno.UI/UI/Xaml/Extensions/FontHelper.Lookup.Android.cs
- src/Uno.UI/UI/Xaml/Media/Brush.Android.cs
- src/Uno.UWP/Devices/Sensors/SimpleOrientationSensor.Android.cs
Fixes https://github.com/unoplatform/uno/issues/6873
Fixes https://github.com/unoplatform/uno/issues/6871
Fixes https://github.com/unoplatform/uno/issues/6874
Fixes https://github.com/unoplatform/uno/issues/6876
- perf(android): Use `HashTableEx` in `FontHelper` (JIT Reduction)
- perf(android): Cache Stroke/Fill system style to reduce interop (Interop reduction)
- perf(android): Don't sort Canvas children below 2 (computation reduction)
- perf(android): Simplify Activity instances tracking (computation / JIT reduction)
- perf(android): Move SimpleOrientationSensor off the UI thread (off-UI Thread)
> Misc Android-specific performance updates

- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/CommandBar/CommandBar_Examples.xaml.cs
GitHub Issue (If applicable): closes #2593
- Test
> test: Enable CommandBar snapshot test

- src/Uno.UI.Tests/Windows_UI_XAML_Controls/TextBoxTests/Given_TextBox.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/6993
- Bugfix
> test: Disable failing range selection unit tests

- doc/articles/contributing/guidelines/pull-requests.md
chore: fixed different upstream names
> docs(pull-requests.md): fixed different upstream names

- doc/articles/Uno-UI-Performance.md
- doc/articles/guides/profiling-applications.md
- doc/articles/toc.yml
> docs: Add net6 and wasm profiling guide

- src/Uno.UI/LinkerDefinition.Wasm.xml
- Bugfix
DragDropExtension is now linker compatible
> fix(dragdrop): Preserve DragDropExtension JS entrypoint

- src/Uno.Foundation.Runtime.WebAssembly/Interop/Runtime.wasm.cs
- src/Uno.UI/DataBinding/BindingExpression.cs
- src/Uno.UI/UI/Xaml/DependencyObjectStore.Binder.cs
- src/Uno.UI/UI/Xaml/DependencyObjectStore.cs
- src/Uno.UI/UI/Xaml/FrameworkElement.Layout.netstd.cs
Additional changes to mitigate dotnet/runtime#56309 in a PG-AOT context.
> perf: Additional changes to mitigate PG-AOT dotnet/runtime issue #56309 

- src/Uno.UI/Controls/CommandBarNavigationItemRenderer.iOS.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/7012, closes https://github.com/unoplatform/nventive-private/issues/249
- Bugfix
```
========================================
Managed Stacktrace:
=================================================================
at <unknown> <0xffffffff>
at Foundation.NSObject:xamarin_release_managed_ref <0x00007>
at Foundation.NSObject:ReleaseManagedRef <0x00017>
at NSObject_Disposer:Drain <0x00173>
at System.Object:runtime_invoke_dynamic <0x0010f>
at <unknown> <0xffffffff>
at UIKit.UIApplication:UIApplicationMain <0x00007>
at UIKit.UIApplication:Main <0x0002f>
at UIKit.UIApplication:Main <0x00043>
at UIKit.UIApplication:Main <0x000af>
at CommandBarBinding.iOS.Application:Main …
```
> fix(commandbar): [iOS] Don't fetch the internal TitleView parent on invalidate measure

- build/ci/templates/dotnet6-install-mac.yml
- build/ci/templates/dotnet6-install-windows.yml
- src/AddIns/Uno.UI.Lottie/LottieVisualSourceBase.Android.cs
- src/AddIns/Uno.UI.Lottie/Uno.UI.Lottie.net6.csproj
- src/AddIns/Uno.UI.MSAL/Uno.UI.MSAL.net6.csproj
- src/Directory.Build.props
- src/Directory.Build.targets
- src/SamplesApp/SamplesApp.net6mobile/Android/MainActivity.Android.cs
- src/SamplesApp/SamplesApp.net6mobile/SamplesApp.net6mobile.csproj
- src/Uno.CrossTargetting.props
- src/Uno.Foundation/Uno.Foundation.net6.csproj
- src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.net6.csproj
- src/Uno.UI/BaseActivity.Android.cs
- src/Uno.UI/UI/Xaml/Media/AcrylicBrush/Android/AndroidStockBlur.Android.cs
- src/Uno.UI/UI/Xaml/UIElement.Android.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.iOS.cs
- src/Uno.UWP/ApplicationModel/Calls/Internal/CallStateListener.Android.cs
- src/Uno.UWP/ApplicationModel/Calls/PhoneCallManager.Android.cs
- src/Uno.UWP/Graphics/Display/DisplayInformation.Android.cs
- src/Uno.UWP/Networking/Connectivity/ConnectionProfile.Android.cs
- src/Uno.UWP/Phone/Devices/Notification/VibrationDevice.Android.cs
- src/Uno.UWP/Uno.net6.csproj
- Feature
Upgrade to .NET 6 RC1
> Upgrade to .NET 6 RC1

- src/Uno.UI/UI/Xaml/ResourceResolver.cs
- src/Uno.UI/UI/Xaml/Style/Style.cs
- Performance
See #7005 for additional details
> perf: Additional changes to mitigate PG-AOT dotnet/runtime issue #56309

- src/Uno.UI.RuntimeTests/Helpers/ConfigHelper.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Flyout.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_MenuFlyout.cs
- src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Automation.Peers/MenuBarItemAutomationPeer.cs
- src/Uno.UI/UI/Xaml/Automation/Peers/MenuBarItemAutomationPeer.cs
- src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePickerFlyout_Partial.cs
- src/Uno.UI/UI/Xaml/Controls/Flyout/FlyoutBase.Pickers.cs
- src/Uno.UI/UI/Xaml/Controls/Flyout/FlyoutBase.cs
- src/Uno.UI/UI/Xaml/Controls/Flyout/FlyoutPopupPanel.cs
- src/Uno.UI/UI/Xaml/Controls/MenuBar/MenuBarItem.cs
- src/Uno.UI/UI/Xaml/Controls/MenuFlyout/MenuFlyout.cs
- src/Uno.UI/UI/Xaml/Controls/Popup/PlacementPopupPanel.cs
- src/Uno.UI/UI/Xaml/Controls/ToolTip/ToolTipPopupPanel.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/6897
- Bugfix
> Fix Flyout position handling

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_MenuFlyout.cs
- src/Uno.UI/UI/Xaml/Controls/Grid/Grid.cs
- src/Uno.UI/UI/Xaml/Media/Animation/Storyboard.cs
- src/Uno.UI/UI/Xaml/UIElementCollection.cs
- src/Uno.UI/UI/Xaml/VisualStateGroup.cs
- Refactoring
See #7005 for additional details
> perf: Adjust Grid, StoryBoard and VisualStatGroup enumerations

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_MenuFlyout.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/7058
- Bugfix
Disables unstable test Verify_MenuBarItem_Bounds_Managed_Popups https://github.com/unoplatform/uno/issues/7058
> test: Disable unstable test Verify_MenuBarItem_Bounds_Managed_Popups

- src/SamplesApp/SamplesApp.UWP/SamplesApp.UWP.csproj
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/InfoBadgeTests/InfoBadgePage.xaml
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/InfoBadgeTests/InfoBadgePage.xaml.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/Uno.UI/Microsoft/UI/Xaml/Controls/InfoBadge/InfoBadge.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/InfoBadge/InfoBadge.properties.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/InfoBadge/InfoBadge.xaml
- src/Uno.UI/Microsoft/UI/Xaml/Controls/InfoBadge/InfoBadgeTemplateSettings.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/InfoBadge/InfoBadge_themeresources.xaml
GitHub Issue (If applicable): #6952
- Feature
InfoBadge doesn't work.
InfoBadge works.
> feat: WinUI InfoBadge

- src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault/ProgressRing.xaml
- src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault/ProgressRing_themeresources.xaml
- src/Uno.UI.FluentTheme.v2/themeresources_v2.xaml
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/7037
- Fix
Fix missing ProgressRing fluent style
> fix: Add missing ProgressRing v2 style

- build/Uno.WinUI.nuspec
- src/Directory.Build.targets
> chore: Upgrade to Uno.Core and SourceGeneration stable

- src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault/PersonPicture.xaml
> Fix(PersonPicture): Add v1 WASM workarounds to v2 style. Remove negative margin for clipping

- src/Uno.UI.FluentTheme.v2/themeresources_v2.xaml
- Bugfix
Restores a missing merged file including the v1 style copy to v2 for ProgressBar.
> fix: add missing progressbar changes in resources v2

- src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault/NavigationView_rs1_themeresources.xaml
- src/Uno.UI.FluentTheme.v2/themeresources_v2.xaml
- src/Uno.UI/Extensions/ViewExtensions.Android.cs
Remove right margin on ContentGrid inside NavViewItemPresenter left pane style. This works around a bug on Android where the NVI icon gets cut off. The root cause of the bug seems to be a complex layouting interaction involving Viewbox not updating when its available width is reduced.
GitHub Issue (If applicable): closes #7049
- Bugfix
> fix(reg): [Android] Fix icon cut off in NavViewItem in compact mode

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.cs
- src/Uno.UI.Tests/Windows_UI_XAML_Controls/TextBoxTests/Given_TextBox.cs
GitHub Issue (If applicable): closes #6993
> test: Move TextBox selection tests to runtime tests

- src/Uno.UI/DataBinding/BindingExpression.cs
- src/Uno.UI/FeatureConfiguration.cs
- src/Uno.UI/UI/Xaml/Controls/ItemsControl/ItemsControl.cs
- src/Uno.UI/UI/Xaml/FrameworkElement.netstd.cs
- src/Uno.UI/UI/Xaml/FrameworkTemplatePool.cs
See #7005 for additional details
> Additional PG-AOT performance updates

- src/Uno.UI/UI/Xaml/Controls/Pivot/Pivot.cs
> fix: Fix Selected state in PivotHeaderItem

- src/Uno.UI.RuntimeTests/Helpers/ColorAssert.cs
- src/Uno.UI.RuntimeTests/Tests/Microsoft_UI_Xaml_Controls/Given_NavigationView.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_MenuFlyout.cs
- src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.csproj
GitHub Issue (If applicable): closes #7058 
> Restore MenuFlyout and NavView tests

- build/Uno.WinUI.RemoteControl.nuspec
- src/SolutionTemplate/UnoSolutionTemplate.VSIX.2022/source.extension.vsixmanifest
- src/SolutionTemplate/UnoSolutionTemplate.VSIX/UnoPlatformPackage.cs
- src/SolutionTemplate/UnoSolutionTemplate.VSIX/UnoStaticGlobalPropertiesProvider.cs
- src/Uno.UI.RemoteControl.VS/EntryPoint.cs
- src/Uno.UI.RemoteControl.VS/Uno.UI.RemoteControl.VS.csproj
- Feature
Add support for remote control (XAML Hot Reload) for VS 2022
> feat(VS2022): Add support for uno remote control

- build/ci/.azure-devops-ios-tests.yml
- src/SolutionTemplate/UnoSolutionTemplate.net6/UWP/UnoQuickStart.Uwp.csproj
- src/SolutionTemplate/UnoSolutionTemplate/UWP/UnoQuickStart.Uwp.csproj
> chore: Bump uno.core to latest

- src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.Skia.csproj
- src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.Wasm.csproj
- src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.csproj
- src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.net6.csproj
- src/Uno.UI.Tests/Windows_Globalization/Given_IncrementNumberRounder.cs
- src/Uno.UI.Tests/Windows_Globalization/Given_Rounder.cs
- src/Uno.UI.Tests/Windows_Globalization/Given_SignificantDigitsNumberRounder.cs
- src/Uno.UWP/Generated/3.0.0.0/Windows.Globalization.NumberFormatting/INumberRounder.cs
- src/Uno.UWP/Generated/3.0.0.0/Windows.Globalization.NumberFormatting/IncrementNumberRounder.cs
- src/Uno.UWP/Generated/3.0.0.0/Windows.Globalization.NumberFormatting/RoundingAlgorithm.cs
- src/Uno.UWP/Globalization/NumberFormatting/INumberRounder.cs
- src/Uno.UWP/Globalization/NumberFormatting/IncrementNumberRounder.cs
- src/Uno.UWP/Globalization/NumberFormatting/Rounder.cs
- src/Uno.UWP/Globalization/NumberFormatting/RoundingAlgorithm.cs
- src/Uno.UWP/Globalization/NumberFormatting/SignificantDigitsNumberRounder.cs
GitHub Issue (If applicable): part of #6908
SignificantDigitsNumberRounder rounds double in a wrong way.
RoundDouble is not implement for IncrementNumberRounder.
Rounds correctly as UWP does for both SignificantDigitsNumberRounder and IncrementNumberRounder.
> feat: Implement SignificantDigitsNumberRounder and IncrementNumberRounder RoundDouble Method

- doc/articles/features/ElevatedView.md
> docs(ElevatedView): Clarify the use of the ElevatedView.Background property

- src/SourceGenerators/Uno.UI.SourceGenerators/Helpers/SymbolExtensions.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/SourceGenerators/XamlGenerationTests/ImageSource_With_Implicit_Content.xaml
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Image.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ImageSource.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/ImageSource_TargetNullValue.xaml
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/ImageSource_TargetNullValue.xaml.cs
- src/Uno.UI/UI/Xaml/Media/ImageSource.cs
- src/Uno.UI/UI/Xaml/Media/Imaging/BitmapImage.cs
GitHub Issue (If applicable): closes #5989
- Bugfix
- Properties with type having TypeConverterAttribute not working as expected.
- TargetNullValue not handled
These are handled now.
> fix: Handle converters and TargetNullValue in source generator

- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/NumberBoxTests/MUX_Test.xaml
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/NumberBoxTests/MUX_Test.xaml.cs
- src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/NumberBox/NumberBoxTests.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/NumberBox/NumberBox.Properties.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/NumberBox/NumberBox.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/NumberBox/NumberBox.xaml
- src/Uno.UI/Microsoft/UI/Xaml/Controls/NumberBox/NumberBoxAutomationPeer.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/NumberBox/NumberBox_themeresources.xaml
- src/Uno.UI/Microsoft/UI/Xaml/Controls/NumberBox/NumberBox_themeresources_v1.xaml
- src/Uno.UI/Microsoft/UI/Xaml/Controls/NumberBox/NumberBox_v1.xaml
GitHub Issue (If applicable): closes #5543, closes #6401
- Bugfix
CommonStates don't exist and hence not applied.
Added CommonStates and applied them (port from https://github.com/microsoft/microsoft-ui-xaml/pull/3005)
> fix: Add and apply NumberBox CommonStates

- src/SourceGenerators/Uno.UI.SourceGenerators/DependencyObject/DependencyObjectGenerator.cs
- Bugfix
Fixes invalid merge between two recent PRs.
> fix: Invalid sourcegen update

- doc/articles/features/shapes-and-brushes.md
GitHub Issue (If applicable): closes #6919
- Bugfix
Docs don't contain important information for fallback.
Docs expanded with further information.
> docs: Expand explanation of AcrylicBrush usage

- src/SolutionTemplate/UnoSolutionTemplate.Wizard/UnoSolutionTemplate.Wizard.csproj
- src/SolutionTemplate/UnoSolutionTemplate.net6/Wasm/UnoQuickStart.Wasm.csproj
- src/SolutionTemplate/UnoSolutionTemplate/Wasm/UnoQuickStart.Wasm.csproj
- Bugfix
Add missing embedded resources for .vsconfig causing template creation failure
> fix(vsix): Add missing embedded resources

- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/DatePicker/DatePicker_VisualStates.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/DatePicker/DatePicker_VisualStates.xaml.cs
- src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePicker.cs
GitHub Issue (If applicable): closes #6256
- Bugfix
> fix: Apply visual states on date change

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml/FocusManagerTests/UnoSamples_Tests.FocusManager.cs
GitHub Issue (If applicable): fixes #1244
Test
Tests disabled on Android
Enabled
> test: Enable Focus UI tests on Android

- src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.iOSmacOS.cs
- src/Uno.UI/UI/Xaml/Media/LinearGradientBrush.iOSmacOS.cs
#6457
- Feature
Still has an issue where the native Linear Gradient does not match that of WinUI: #7160
> feat(Border): Add ability to use GradientBrushes for BorderBrush

- .editorconfig
- .vsts-ci.yml
- src/Uno.UI/UI/Xaml/FrameworkElement.Interface.skia.cs
GitHub Issue (If applicable): closes #7106
> fix: Promote RS0030 (banned API) diagnostic to error

- src/Uno.UI/UI/Xaml/UIElement.netstd.cs
Fixes https://github.com/unoplatform/uno/issues/6988
> Reduced the severity of the inconsistency message while adding/removing elements in Visual Tree on WASM.

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Shapes/Shapes_Tests.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/Setting_ImageBrush_In_Code_Behind.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Shapes/Setting_ImageBrush_In_Code_Behind.xaml.cs
- src/Uno.UI/UI/Xaml/Media/Brush.Android.cs
GitHub Issue (If applicable): closes #6460
- Bugfix
ImageBrush isn't assigned properly.
It's now assigned properly
> fix: Assign ImageBrush on Android properly

- build/ci/.azure-devops-uap.yml
Publish UAP artifacts for easier testing
> ci: Publish UAP artifact

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml/DragAndDropTests/DragDrop_ListViewReorder_Automated.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/DragAndDrop/DragDrop_ListView.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/DragAndDrop/DragDrop_ListView.xaml.cs
- src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Media.Imaging/RenderTargetBitmap.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.DragDrop.cs
- src/Uno.UI/UI/Xaml/DragDrop/DragOperation.cs
- src/Uno.UI/UI/Xaml/DragDrop/DragUI.cs
- src/Uno.UI/UI/Xaml/DragDrop/DragUIOverride.cs
- src/Uno.UI/UI/Xaml/DragDrop/DragView.xaml
- src/Uno.UI/UI/Xaml/Media/Imaging/RenderTargetBitmap.Android.cs
- src/Uno.UI/UI/Xaml/Media/Imaging/RenderTargetBitmap.cs
- src/Uno.UI/UI/Xaml/Media/Imaging/RenderTargetBitmap.iOS.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.cs
- src/Uno.UWP/ApplicationModel/DataTransfer/DragDrop/Core/CoreDragUIOverride.cs
fixes: https://github.com/unoplatform/nventive-private/issues/254
fixes: https://github.com/unoplatform/uno/issues/6948
Fix ListView reordeing items UI
When reordering items, D&D UI shows 🚫
Shows "Move"
> Fix ListView reordeing items UI

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlConstants.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.Reflection.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/Uno.UI.Tests/Windows_UI_Xaml/Controls/SomeNotImplType.cs
- src/Uno.UI.Tests/Windows_UI_Xaml/Controls/When_Resource_NotImplemented_Dict.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml/Controls/When_Resource_NotImplemented_Page.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml/Controls/When_Resource_NotImplemented_Page.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml/Given_ResourceDictionary.cs
Don't eagerly materialize types marked NotImplemented, since these may costly and can't ever be usefully used in any case.
GitHub Issue (If applicable): closes #6878
> fix(resourcedictionary): Improve performance of ResourceDictionary with not-implemented types

- doc/articles/getting-started-tutorial-2.md
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/7242
> docs: Adjust missing binding mode in getting started 2

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/Uno.UI.RuntimeTests/Tests/Uno_UI/Given_ResourceResolver.cs
- src/Uno.UI.RuntimeTests/Tests/Uno_UI/Resolve_String_Resources.xaml
- src/Uno.UI.RuntimeTests/Tests/Uno_UI/Resolve_String_Resources.xaml.cs
- src/Uno.UI/UI/Xaml/ResourceResolver.cs
- src/Uno.UI/UI/Xaml/ResourceResolverSingleton.cs
GitHub Issue (If applicable): closes #7168, closes #7169
> fix: Convert resources to target property type in generated code

- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unolib-crossruntime/.template.config/template.json
GitHub Issue (If applicable): closes #5695
- Bugfix
> fix: include Skia project condiction

- src/SamplesApp/SamplesApp.UITests/Microsoft_UI_Xaml_Controls/RadioMenuFlyoutItemTests/Given_RadioMenuFlyoutItem.cs
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/RadioMenuFlyoutItemTests/RadioMenuFlyoutItemPage.xaml
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/RadioMenuFlyoutItemTests/RadioMenuFlyoutItemPage.xaml.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/Uno.UI/Microsoft/UI/Xaml/Controls/RadioMenuFlyoutItem/RadioMenuFlyoutItem.Properties.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/RadioMenuFlyoutItem/RadioMenuFlyoutItem.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/RadioMenuFlyoutItem/RadioMenuFlyoutItem_rs1_themeresources_v1.xaml
- src/Uno.UI/Microsoft/UI/Xaml/Controls/RadioMenuFlyoutItem/RadioMenuFlyoutItem_rs2_themeresources_v1.xaml
- src/Uno.UI/Microsoft/UI/Xaml/Controls/RadioMenuFlyoutItem/RadioMenuFlyoutItem_rs4_themeresources_v1.xaml
- src/Uno.UI/Microsoft/UI/Xaml/Controls/RadioMenuFlyoutItem/RadioMenuFlyoutItem_rs5_themeresources_v1.xaml
- src/Uno.UI/Microsoft/UI/Xaml/Controls/RadioMenuFlyoutItem/RadioMenuFlyoutItem_themeresources.xaml
- src/Uno.UWPSyncGenerator/Generator.cs
GitHub Issue (If applicable): closes #3256
- Feature
`RadioMenuFlyoutItem` not supported.
Supported.
> feat: Port RadioMenuFlyoutItem

- doc/articles/features/windows-storage-pickers.md
- src/Uno.UI.Runtime.Skia.Gtk/Extensions/Storage/Pickers/FileSavePickerExtension.cs
- src/Uno.UI.Runtime.Skia.Gtk/GtkHost.cs
GitHub Issue (If applicable): #6126
- Feature
`FileSavePicker` is not implemented for Gtk
`FileSavePicker` is now implemented for Gtk
Fixes #6126
> Implement FileSavePicker for Gtk

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Media_Animation/SetTarget_After_Start.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media_Animation/SetTargetProperty.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Media_Animation/SetTargetProperty.xaml.cs
- src/Uno.UI/UI/Xaml/Media/Animation/Timeline.cs
GitHub Issue (If applicable): closes #6960
- Bugfix
> fix: Don't use cached value when it's no longer valid

- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/PersonPictureTests/PersonPicturePage.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/PersonPictureTests/PersonPicturePage.xaml.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/IconSource/FontIconSource.cs
- src/Uno.UI/UI/Xaml/Controls/FontIcon/FontIcon.cs
- src/Uno.UI/UI/Xaml/Controls/Icon/FontIconSource.cs
- src/Uno.UI/UI/Xaml/Controls/PersonPicture/PersonPicture.cs
- src/Uno.UI/UI/Xaml/IFrameworkElement.cs
- Bugfix
- Sample test
- `PersonPicture` sample doesn't exist.
- `PersonPicture` can crash.
- Add the sample in projitems (it was deleted, likely unintentional, in https://github.com/unoplatform/uno/pull/2252), and update the sample from WinUI.
- Fix crashes in the sample due to incorrect default (null) values of string fields.
> Add back missing `PersonPicture` sample to projitems and fix crashes

- build/ci/.azure-devops-screenshot-compare.yml
- build/ci/.azure-devops-skia-tests.yml
- build/ci/templates/gtk-install.yml
- src/SamplesApp/SamplesApp.Shared/App.xaml.cs
- src/SamplesApp/SamplesApp.Skia.WPF/Properties/launchSettings.json
- src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.cs
- src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.cs
- src/Uno.UI.RuntimeTests/IntegrationTests/dxaml/controls/calendarview/CalendarViewIntegrationTests.cs
- src/Uno.UI.RuntimeTests/IntegrationTests/dxaml/controls/grid/GridIntegrationTests.cs
- src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/Repeater/FlowLayoutCollectionChangeTests.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_Storage/Given_TemporaryFile.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Popups/Given_MessageDialog.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_UIElement.TransformToVisual.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_FrameworkElement.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ProgressRing.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_TextBox.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Data/Given_Convert.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media/Given_VisualTreeHelper.cs
Enables Skia runtime tests validation during CI
> test(skia): Enable runtime tests validation

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Pivot.cs
- src/Uno.UI/UI/Xaml/Controls/Pivot/Pivot.cs
- src/Uno.UI/UI/Xaml/Controls/Pivot/PivotItem.cs
GitHub Issue (If applicable): closes #2391, closes #4796
- Bugfix
> Few fixes around setting some Pivot properties not correctly reflecting on UI

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_xLoad.cs
- src/Uno.UI/UI/Xaml/Controls/AppBar/AppBar.Partial.cs
> fix(reg): Fix WinUI build

- src/Uno.UI/UI/Xaml/Controls/ItemsStackPanel/ItemsStackPanelLayout.managed.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.managed.cs
Fixes error that could occur when removing an item from collection while it was being dragged.
GitHub Issue (If applicable): closes #7008 
- Bugfix
> fix(listview): [WASM] Support removing item while dragging

- build/ci/.azure-devops-android-tests.yml
- build/ci/.azure-devops-ios-tests-run.yml
- build/ci/.azure-devops-ios-tests.yml
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-net6/UnoQuickStart.sln
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp/UnoQuickStart.sln
- src/SourceGenerators/Uno.UI.SourceGenerators/BindableTypeProviders/BindableTypeProvidersGenerationTask.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props
- Bugfix
- Fix invalid duplicates configuration when running `dotnet new unoapp`
- Fix race condition during design time and normal builds
- Ignore not implemented types in bindable metadata generator
> Misc source generation features

- build/ci/.azure-devops-android-tests.yml
- build/ci/.azure-devops-ios-tests-run.yml
- build/ci/.azure-devops-ios-tests.yml
> ci: Bump iOS runtime tests timeout, don't rerun runtime tests

- doc/articles/supported-libraries.md
Updated Syncfusion capitalization and added LightningChart
Updated 3rd-Party Libraries
> docs: Updated 3rd-Party Libraries

- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/Given_XamlReader.cs
- src/Uno.UI/UI/Xaml/DependencyObjectStore.cs
- src/Uno.UI/UI/Xaml/Markup/Reader/XamlObjectBuilder.cs
Fix error when loading with empty Resources declaration, which would incorrectly set Resources to null and cause an exception during styles resolution. This allows XAML Hot Reload to support this scenario properly.
- Bugfix
https://github.com/unoplatform/private/issues/244
> fix(xamlreader): Fix exception when loading with empty Resources

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/NameScope.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
GitHub Issue (If applicable): closes #6198
- Bugfix
No error on duplicate x:Name
Error on duplicate x:Name
> fix: Error properly on invalid and duplicate x:Name

- doc/articles/intro.md
Fixed brand capitalization for Syncfusion and added LightningChart
> docs. 3rd party support update

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml/VisualStateManagerTests/VisualStateManagerTest.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/VisualStateTests/VisualState_Forever_Events.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/VisualStateTests/VisualState_Forever_Events.xaml.cs
- src/Uno.UI/UI/Xaml/VisualStateGroup.cs
GitHub Issue (If applicable): closes #3160
> fix: Fix CurrentStateChanged raised in incorrect time

- doc/articles/guides/uno-cupertino-walkthrough.md
- doc/articles/guides/uno-material-walkthrough.md
closes https://github.com/unoplatform/uno/issues/7447
Update Themes documentation to reflect changes from https://github.com/unoplatform/Uno.Themes/pull/654
> docs: Update docs to reflect changes in Uno.Themes

- src/Uno.UI/Microsoft/UI/Xaml/Controls/NavigationView/NavigationView.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/NavigationView/NavigationViewItemPresenter.cs
> fix: Port IsPaneVisible fix from WinUI

- src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/TextBox.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs
- src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml
GitHub Issue (If applicable): closes #7381 
- Feature
There is an inconsistency between our TextBox Generic.xaml and that of the Windows platform. Description is not supported.
Sync with the latest Style for TextBox and add the necessary codebehind. Also, try to fix inconsistent (mixed) formatting of TextBox.cs and Generic.xaml
Tested on WASM. The markup changes should work fine elsewhere, but I'll be happy to test Android too if needed.
> Implement TextBox Description Property

- doc/articles/guides/raspberry-pi/raspberry-pi-intro.md
Fixed grammatical error
**Documentation content changes** - made correction with duplicate wording
> doc. Fixed repeated word

- build/Uno.WinUI.nuspec
- Bugfix
Fix the location of logging assemblies
> fix(reg): Invalid location for android30 logging nuspec

- build/Uno.WinUI.nuspec
- src/Directory.Build.targets
> chore: Update to latest Uno.SourceGeneration

- README.md
- doc/articles/uno-builds-troubleshooting.md
> docs: Adjust build troubleshooting docs links

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/PopupTests/UnoSamples_Popup_HVAlign_Tests.cs
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/PopupTests/UnoSamples_Popup_LightDismiss_Tests.cs
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/PopupTests/UnoSamples_Popup_Simple_Tests.cs
Makes existing tests visible to the unit-testing framework.
> test: Enable existing Popup tests

- src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/FramebufferHost.cs
- Bugfix
Fixes framebuffer dispatcher initialization sequence.
> fix: Adjust framebuffer host initialization sequence

- src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.Xaml.cs
- src/Uno.UI/UI/Xaml/Media/VisualTreeHelper.Android.cs
- src/Uno.UI/UI/Xaml/Media/VisualTreeHelper.iOSmacOS.cs
- src/Uno.UI/UI/Xaml/Media/VisualTreeHelper.net.cs
- src/Uno.UI/UI/Xaml/Media/VisualTreeHelper.netstd.cs
Create an instance of the same type as the element being reloaded, and replace the old element in the visual tree rather than nesting inside of it.
GitHub Issue (If applicable): closes https://github.com/unoplatform/private/issues/259
> [Hot Reload] Replace Page with correct type when reloaded

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/BorderTests/Border_Tests.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/BorderTests/Border_CornerRadius_Gradient.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/BorderTests/Border_CornerRadius_Gradient.xaml.cs
- src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.iOSmacOS.cs
closes https://github.com/unoplatform/uno/issues/7538
- Bugfix
> fix(Border): Adjust layering logic when using a GradientBrush as BorderBrush

- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/Given_XamlReader.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/When_xBind_Simple.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/When_xBind_Simple.xamltest
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/When_xBind_TwoWay.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/When_xBind_TwoWay.xamltest
- src/Uno.UI/UI/Xaml/Markup/Reader/XamlObjectBuilder.cs
- Feature
closes https://github.com/unoplatform/private/issues/246
> feat(hotreload): Support x:Bind to properties in hot reload scenarios

- doc/articles/migrating-from-previous-releases.md
> docs: Add android 12 upgrade docs

- doc/articles/features/protocol-activation.md
- doc/articles/features/web-authentication-broker.md
- doc/articles/guides/open-id-connect.md
- src/SamplesApp/SamplesApp.Droid/MainActivity.cs
- src/SamplesApp/SamplesApp.Droid/SamplesApp.Droid.csproj
- Bugfix
Can't deploy to A12 Emulators
Can deploy
> fix: Android Samples app deployment to Android 12

- doc/articles/uno-development/building-uno-ui.md
> docs: Update uno solution build requirements

- doc/articles/native-styles.md
Document additional step required now that Fluent styles are part of the default app template.
GitHub Issue (If applicable): closes #7653
> docs: Update native styles guidance

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_FlipView.cs
- src/Uno.UI/UI/Xaml/Controls/FlipView/FlipView.iOSAndroid.cs
- src/Uno.UI/UI/Xaml/Controls/FlipView/FlipView.managed.cs
Fix FlipView.SelectedIndex being reset to 0 whenever OnItemsChanged() is raised. This was a hangover from a much earlier state of the code where the method was only raised the first time the Items property was set; aside from being incorrect,  it was causing exceptions on Android due to trying to scroll the native pager control before updating its state.
- Bugfix
fixes https://github.com/unoplatform/nventive-private/issues/260
> fix(flipview): [Android] Fix IllegalStateException from FlipView

- build/ios-uitest-run.sh
- src/SamplesApp/SamplesApp.UITests/Constants.cs
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ItemsControl/ItemsControlTests.cs
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/RatingControlTests/RatingControlPage.xaml.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ItemsControl/ItemsControl_ReplaceItem.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ItemsControl/ItemsControl_ReplaceItem.xaml.cs
- src/Uno.UI.RuntimeTests/UnitTestsImport.props
- src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.Skia.csproj
- src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.Wasm.csproj
- src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.csproj
- src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.net6.csproj
- src/Uno.UI.Tests/Windows_UI_XAML_Controls/ItemsControlTests/Given_ItemsControl.cs
- src/Uno.UI/UI/Xaml/Media/VisualTreeHelper.cs
- src/Uno.UI/UI/Xaml/UIElement.MuxInternal.cs
- src/Uno.UI/UI/Xaml/UIElement.netstdref.cs
- src/Uno.UI/UI/Xaml/UIElement.skia.cs
- src/Uno.UI/UI/Xaml/UIElement.wasm.cs
- src/Uno.UI/UI/Xaml/UIElementCollection.iOS.cs
- src/Uno.UI/UI/Xaml/UIElementCollection.netstd.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/nventive-private/issues/331
> fix: [iOS][Skia] Invalid UIElementCollection replace operation

- doc/articles/interop/wasm-javascript-1.md
> docs: Adjusted documentation for WebAssemblyRuntime

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/PopupTests/UnoSamples_Popup_LightDismiss_Tests.cs
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/HitTest_Tests.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Input/PointersTests/HitTest_Control.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Input/PointersTests/HitTest_Control.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Input/PointersTests/HitTest_LightDismiss.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Input/PointersTests/HitTest_LightDismiss.xaml.cs
- src/Uno.UI/FeatureConfiguration.cs
- src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls.Primitives/FlyoutBase.cs
- src/Uno.UI/Mixins/DependencyPropertyMixins.tt
- src/Uno.UI/UI/Xaml/Controls/AutoSuggestBox/AutoSuggestBox.cs
- src/Uno.UI/UI/Xaml/Controls/Border/Border.cs
- src/Uno.UI/UI/Xaml/Controls/Border/Border.skia.cs
- src/Uno.UI/UI/Xaml/Controls/Border/Border.wasm.cs
- src/Uno.UI/UI/Xaml/Controls/ComboBox/ComboBox.cs
- src/Uno.UI/UI/Xaml/Controls/ContentDialog/ContentDialogPopupPanel.cs
- src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.cs
- src/Uno.UI/UI/Xaml/Controls/Flyout/FlyoutBase.cs
- src/Uno.UI/UI/Xaml/Controls/Flyout/FlyoutPopupPanel.cs
- src/Uno.UI/UI/Xaml/Controls/Flyout/FlyoutPresenter.cs
- src/Uno.UI/UI/Xaml/Controls/MenuFlyout/MenuFlyout.cs
- src/Uno.UI/UI/Xaml/Controls/Panel/Panel.cs
- src/Uno.UI/UI/Xaml/Controls/Popup/Popup.Base.cs
- src/Uno.UI/UI/Xaml/Controls/Popup/Popup.cs
- src/Uno.UI/UI/Xaml/Controls/Popup/Popup.mux.cs
- src/Uno.UI/UI/Xaml/Controls/Popup/PopupPanel.cs
- src/Uno.UI/UI/Xaml/FrameworkElement.cs
GitHub Issue (If applicable): closes #2677, closes #7534, closes https://github.com/unoplatform/uno/issues/7636
- Bugfix
> Improve Flyout and Popup light-dismiss handling

- doc/articles/wpf-migration.md
- Image doesn't show (or more precisely shows on Windows only)
- Some links contain en-us locale, which isn't good if the user has set docs.microsoft.com to another language.
- Image shows properly.
- Let docs.microsoft.com handles the redirection to whatever suitable locale for the user.
> docs: Fix image and localized links in wpf-migration

- doc/articles/uno-development/building-uno-ui.md
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/7693
> docs: Adjust uno build directions for VS2022

- doc/articles/toc.yml
With PR #7658 , I forgot to update the toc.yml for this new addition.
Fixed the missing doc page problem. Apologies!
> docs: Update toc.yml for WPF to Web

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_GridView_Items.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/TestsResources.xaml
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBaseSource.iOS.cs
> fix: adjust frame coords for LayoutSlot in ListView/GridView

- doc/articles/faq.md
(Discussed with @sasakrsmanovic internally)
We get asked about this quite often and lack an official FAQ section for it.
Add a FAQ section to designate direct VB.NET project creation as unsupported.
Discussed with @sasakrsmanovic internally
> docs: Add FAQ section about VB.NET

- src/Uno.UI/UI/Xaml/Application.skia.cs
- src/Uno.UI/UI/Xaml/Controls/Image/Image.skia.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.skia.cs
- src/Uno.UI/UI/Xaml/Controls/WebView/WebView.cs
- src/Uno.UI/UI/Xaml/Shapes/Path.skia.cs
- src/Uno.UI/UI/Xaml/UIElement.skia.cs
- src/Uno.UI/Uno.UI.Skia.csproj
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/7771
- Bugfix
```
System.NullReferenceException: Object reference not set to an instance of an object.
at Windows.UI.Xaml.Application.ObserveSystemThemeChanges() in C:\a\1\s\src\Uno.UI\UI\Xaml\Application.skia.cs:line 91
at Windows.UI.Xaml.Application.InitializationCompleted() in C:\a\1\s\src\Uno.UI\UI\Xaml\Application.cs:line 245
at Windows.UI.Xaml.Application.Initialize() in C:\a\1\s\src\Uno.UI\UI\Xaml\Application.skia.cs:line 81
at Uno.UI.Dispatching.CoreDispatcher.InvokeOperationSafe(UIAsyncOperation operation) in C:\a\1\s\src\Uno.UI.Dispatching\Core\CoreDispatcher.cs:line 337
````         
Execution runs properly.
Please check if your PR fulfills the following …
> Fix theming NRE in Skia Framebuffer

- src/Uno.UI.Runtime.Skia.Tizen/TizenHost.cs
- src/Uno.UI.Runtime.Skia.Wpf/WpfHost.cs
> fix: [WPF][Tizen] he local function 'EnqueueNative' is declared but never used

- doc/articles/get-started.md
docs: added Windows 11 as a target platform
> docs: added Windows 11 as a target platform

- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-net6/NuGet.config
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-winui-net6/NuGet.config
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-winui-net6/global.json
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-winui/global.json
- Bugfix
Removes legacy and unused configuration files in templates. Fixes VS 4 Mac asking for installation of .NET Core 3.1.
> fix: Remove unused configuration files in templates

- src/Uno.Foundation.Runtime.WebAssembly/Interop/Runtime.wasm.cs
- src/Uno.UI/UI/Xaml/Shapes/Shape.wasm.cs
- src/Uno.UI/UI/Xaml/WindowManagerInterop.wasm.cs
- src/Uno.UI/WasmScripts/Uno.UI.d.ts
- src/Uno.UI/WasmScripts/Uno.UI.js
- src/Uno.UI/ts/WindowManager.ts
- src/Uno.UI/tsBindings/WindowManagerSetElementFillParams.ts
- perf: Remove indented string builder from `InvokeJSWithInterop`
- perf(memory): Reduce memory pressure on shape set fill
> Wasm interop perf and memory updates

- src/Uno.UI/UI/Xaml/Controls/FocusVisual/SystemFocusVisual.xaml
- src/Uno.UI/UI/Xaml/Controls/NavigationView/NavigationBackButton_rs1_themeresources.xaml
- src/Uno.UI/UI/Xaml/Controls/NavigationView/NavigationBackButton_rs4_themeresources.xaml
- src/Uno.UI/UI/Xaml/Controls/NavigationView/NavigationBackButton_rs5_themeresources.xaml
- src/Uno.UI/UI/Xaml/Controls/NavigationView/NavigationView.xaml
- src/Uno.UI/UI/Xaml/Controls/NavigationView/NavigationView_rs1_themeresources.xaml
- src/Uno.UI/UI/Xaml/Controls/NavigationView/NavigationView_rs2_themeresources.xaml
- src/Uno.UI/UI/Xaml/Controls/NavigationView/NavigationView_rs5_themeresources.xaml
- src/Uno.UI/UI/Xaml/Controls/ProgressRing/ProgressRing.xaml
- src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml
- src/Uno.UI/UI/Xaml/Style/mergedstyles.xaml
- src/Uno.UI/XamlMerge.targets
- Bugfix
Upgrades XAML Merge tool to latest to avoid using absolute paths in generated file, as well as validation for duplicate namespaces with different uris.
> fix(reg): adjust xaml merge for stable relative path

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/TestsResources.xaml
- src/Uno.UI/UI/Xaml/Controls/ContentPresenter/ContentPresenter.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.iOS.cs
- src/Uno.UI/UI/Xaml/DependencyObjectExtensions.cs
- src/Uno.UI/UI/Xaml/DependencyObjectExtensions.debugging.cs
- src/Uno.UI/UI/Xaml/FrameworkElement.cs
- src/Uno.UI/UI/Xaml/FrameworkTemplate.debugging.cs
- src/Uno.UI/UI/Xaml/Style/Style.debugging.cs
- src/Uno.UI/UI/Xaml/UIElement.debugging.cs
- Bugfix
closes https://github.com/unoplatform/nventive-private/issues/288
> fix(listview): [iOS] Fix ItemTemplateSelector called at wrong time 

- doc/articles/uno-development/building-uno-ui.md
> docs: Add uno.ui build troubleshooting details

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ListViewTests/UnoSamples_Tests.ListView.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_Resizing.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_Resizing.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Models/ListViewViewModel.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.iOS.cs
samples for #6454, #7754
UI Test
* There are no UI Tests showing the bug with the ListView when it comes to resizing based on content.
* There are UI Tests showing the bug with the ListView when it comes to resizing based on content.
> feat: Added samples for ListView Growing and Shrinking on iOS

- src/Uno.UI/DataBinding/BindingPath.cs
- src/Uno.UI/UI/Xaml/DependencyObjectStore.Binder.cs
This change significantly reduces the number of delegates created during the propagation of property changes in bindings. This reduces the memory footprint, and improves the invocation performance under Wasm MixedAOT.
> perf: Reduce delegates use in BindingPath property changed

- src/Uno.UI.Dispatching/Uno.UI.Dispatching.csproj
- Bugfix
SampleApp.iOS build on Vs4M is failing when compiling  `Uno.UI.Dispatching` project
> fix(iOS): build SampleApp from vs4m

- src/Uno.UI.Tests/Windows_UI_XAML_Controls/ListViewBaseTests/Given_ListViewBase_CustomContainer.cs
- src/Uno.UI.Tests/Windows_UI_Xaml/Given_FrameworkTemplate.cs
- src/Uno.UI/FeatureConfiguration.cs
- src/Uno.UI/Mock/ContentControl.net.cs
- src/Uno.UI/UI/Xaml/FrameworkTemplatePool.cs
- src/Uno.UI/UI/Xaml/FrameworkTemplatePoolDefaultPlatformProvider.cs
- src/Uno.UI/UI/Xaml/IFrameworkTemplatePoolPlatformProvider.cs
- src/Uno.UI/UI/Xaml/Style/mergedstyles.xaml
- src/Uno.UI/UI/Xaml/WindowManagerInterop.wasm.cs
- src/Uno.UI/WasmScripts/Uno.UI.d.ts
- src/Uno.UI/WasmScripts/Uno.UI.js
- src/Uno.UI/ts/Windows/System/MemoryManager.ts
- src/Uno.UWP/Generated/3.0.0.0/Windows.System/MemoryManager.cs
- src/Uno.UWP/System/MemoryManager.Wasm.cs
- src/Uno.UWP/Uno.Wasm.csproj
- Feature
feat(wasm): Add `MemoryManager` support
feat: Add support for memory usage aware template pooling
> Wasm MemoryManager support,  memory aware FrameworkTemplate Pooling 

- doc/articles/guides/native-frame-nav-tutorial.md
Failure to remove angle bracket results in error code XLS0503 and XDG0048.
Removing the extra character resolves the issue.
Copying this code into an Uno Platform XAML file results in a pair of errors:
XLS0503: The specified value cannot be assigned to the collection. The following type was expected: "UIElement".
XDG0048: A value of type 'String' cannot be added to a collection or dictionary of type 'UIElementCollection'.
Removing the extra angle bracket allows the markup to be valid without errors.
> Remove extra angle backet

- doc/articles/guides/native-frame-nav-tutorial.md
Replace ConfigureFilters() with InitializeLogging() per https://platform.uno/docs/articles/migrating-from-previous-releases.html?q=ConfigureFilters#:~:text=In%20the%20constructor%2C%20remove%20this%20call
When existing code is copied into a new Uno Platform application, the following error is displayed CS0103: The name 'ConfigureFilters' does not exist in the current context .
The error is resolved.
> Update native-frame-nav-tutorial ConfigureFilters

- doc/articles/guides/localization.md
Fixed file extension typo.
Updated Logging with InitializeLogging();
Presently one of the file extensions was .xaml when it should have been .resw
Also replaced ConfigureFilters() with InitializeLogging().
Typo has been corrected and Error causing ConfigureFilters has been replaced with InitializeLogging.
> Update localization.md Errata

- doc/articles/get-started.md
docs: branch out visual studio onboarding paths
> docs: branch out visual studio onboarding paths

- src/Uno.UI/Controls/CommandBar/CommandBarRenderer.iOS.cs
- src/Uno.UI/UI/Xaml/Style/Generic/Generic.Native.xaml
closes #3892
closes #6717
closes #7803
- Bugfix
**As of iOS 13, the preferred method for styling the UINavigationBar and its components is by using the [UINavigationBarAppearance](https://developer.apple.com/documentation/uikit/uinavigationbarappearance) and [UIBarButtonItemAppearance](https://developer.apple.com/documentation/uikit/uibarbuttonitemappearance) APIs.**
The Native UINavigationBar wasn't truly having its background set. Instead, the Border that wraps the NativeNavigationBarPresenter is what determined was displaying the background color. This caused issues such as the animation of the bar's background color transition not working:
The UINavigationBar now properly displays the …
> fix(NavigationBar): Move to UINavigationAppearance APIs, fix unapplied background color

- build/test-scripts/ios-uitest-run.sh
- src/SamplesApp/SamplesApp.Droid/MainActivity.cs
- src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.cs
- src/Uno.UI.RuntimeTests/IntegrationTests/dxaml/controls/appbar/AppBarIntegrationTests.cs
- src/Uno.UI.RuntimeTests/IntegrationTests/dxaml/controls/calendardatepicker/CalendarDatePickerIntegrationTests.cs
- src/Uno.UI.RuntimeTests/IntegrationTests/dxaml/controls/calendarview/CalendarViewIntegrationTests.cs
- src/Uno.UI.RuntimeTests/IntegrationTests/dxaml/controls/commandbar/CommandBarIntegrationTests.cs
- src/Uno.UWP/Storage/Streams/Internal/NativeWriteStreamAdapter.wasm.cs
- Misc warnings removals
- Run Runtime Tests cleanup
- Fixes runtime tests failures on IOS/Wasm
- Fixes CI-only android 12 build issue with previous Xamarin issues
> Misc CI fixes and runtime tests

- src/Uno.UWP/System/MemoryManager.cs
- src/Uno.UWP/System/MemoryManager.netcore.cs
- Bugfix
Fixes invalid reflection on GC types for net6+.
> Adjust `MemoryManager` for Skia targets

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.managed.cs
Fixes bug where materialized elements would not be added to list when its size changes.
GitHub Issue (If applicable): closes #7730
- Bugfix
> fix(listview): [WASM] [Skia] Redraw list when scroll viewport changes

- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-winui-net6/.vscode/launch.json
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-winui-net6/.vscode/tasks.json
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-winui/.vscode/launch.json
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-winui/.vscode/tasks.json
GitHub Issue (If applicable): closes #7661 
- Bugfix
When using the `--vscode` flag the `launch.json` and `task.json` files created have the wrong project name.
- [*] Contains **NO** breaking changes
- [*] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [*] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.
> fix: (template) winui dotnet new for vscode

- doc/articles/uno-development/debugging-templates.md
- src/Uno.UI-SolutionTemplates.slnf
- Feature
To work with any of the SolutionTemplate projects it's required to load the Uno.UI solution 
- [*] Contains **NO** breaking changes
- [*] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.
> chore: (Template) Add slnf for the Solution Template projects

- src/Uno.UI.RuntimeTests/Helpers/RectAssert.cs
- src/Uno.UI.RuntimeTests/Helpers/ScreenHelper.cs
- src/Uno.UI.RuntimeTests/Tests/Uno_UI_Toolkit/Given_VisibleBoundsPadding.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ContentDialog.cs
- src/Uno.UI/UI/Xaml/Controls/ContentDialog/ContentDialogPopupPanel.cs
- src/Uno.UWP/UI/ViewManagement/ApplicationView.cs
GitHub Issue (If applicable): closes #7248
Measure the content dialog contents within the visible bounds, the same as it will be arranged. This allows the Margin adjustment to be correctly calculated to keep the dialog fully in view above the soft keyboard (in ContentDialog.AdjustVisualStateForInputPane()).
- Bugfix
> fix(contentdialog): [iOS] Fix dialog buttons obscured by soft keyboard

- src/Uno.UI/UI/Xaml/Controls/Primitives/SelectorItem.cs
closes https://github.com/unoplatform/uno/issues/7821
`SelectorItem` may remains in pressed stated if unloaded right after being pressed / released (e.g. closing the drop down of a `ComboBox` or navigating away on `ItemClick` of a `ListView`.
Some visual states are deferred in the `SelectorItem` to avoid flickering and perf issue while scrolling, driving to request a `GoToState` while element is unloaded. Then when element is reloaded, requetsing again a `GoToState("Normal") has no effect since the VSM believes that it's already the current state.
If element has been unloaded, we ignore the `GoToState`, so the expected state will be applied on next load.
**=> Unable to create a reliable test to validate that.**
> fix: SelectorItems may stay in pressed state when unloaded to early after state changed

- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/UIElementTests/UIElement_MeasureDirtyPath.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/UIElementTests/UIElement_MeasureDirtyPath.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/UIElementTests/UIElement_MeasurePerf.xaml
- src/Uno.UI/Extensions/ViewExtensions.netstd.cs
- src/Uno.UI/UI/Xaml/Controls/CalendarView/CalendarView_Partial.cs
- src/Uno.UI/UI/Xaml/FrameworkElementHelper.cs
- src/Uno.UI/UI/Xaml/UIElement.Layout.netstd.cs
- src/Uno.UI/UI/Xaml/UIElement.skia.cs
- src/Uno.UI/UI/Xaml/UIElement.wasm.cs
closes https://github.com/unoplatform/uno/issues/7968
> Blank calendar fix

- src/SamplesApp/SamplesApp.Droid/SamplesApp.Droid.csproj
Apply workaround for https://github.com/xamarin/xamarin-android/issues/6480
> test: Add workaround for android debugging with VS2022

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/SourceGenerators/XamlGenerationTests/Double_IgnoreStartingFromWhitespace.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/BindingHelperTests/Given_XamlBindingHelper.cs
- src/Uno.UI/DataBinding/BindingPropertyHelper.FastConvert.cs
GitHub Issue (If applicable): closes #7371
- Bugfix
> fix: Match XAML numeric literals parsing with UWP

- .github/pull_request_template.md
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/8022
> docs: Clarify PR template

- doc/articles/uno-development/troubleshooting-memory-issues.md
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/8026
> docs: Update profiling instructions

- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/PasswordBox_AutoFill.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/PasswordBox_AutoFill.xaml.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/SinglelineTextBoxView.iOS.cs
GitHub Issue (If applicable): closes #7387
- Bugfix
When password auto-fill is triggered on iOS it breaks PasswordBox input with the soft keyboard.
Auto-fill is disabled on PasswordBox.
> fix(passwordbox): Fixed iOS auto-fill interfering with PasswordBox input

- src/SamplesApp/SamplesApp.Droid/SamplesApp.Droid.csproj
- Bugfix
Additional tweaks to get debugging working properly with VS 2022 Preview (5+) and Android 12.
> fix: Android 12 debugging with VS 2022 Previews

- doc/articles/uno-development/troubleshooting-memory-issues.md
GitHub Issue (If applicable): closes #8026 
Code in documentation refers to missing NuGet package
Instruction added to add `Uno.Core` NuGet package
> Issue #8026

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/ReuseCountGrid.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/TestsResources.xaml
- src/Uno.UI/UI/Xaml/FrameworkTemplatePool.cs
Fix bug where ListView with non-virtualizing items panel inside another ListView could be blank, because the list materializes the item template to check if the root is a ListViewItem, and returning the template root to the pool was causing the native scroll content presenter to remove its content. We fix this by disabling element clean-up from the pool in this case, since it's not necessary.
- Bugfix
https://github.com/unoplatform/nventive-private/issues/343
> fix(listview): Fix blank ListView inside ListView

- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/PagerControlTests/PagerControlPage.xaml
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/PagerControlTests/PagerControlPage.xaml.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/PagerControl/PagerControl.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/PagerControl/PagerControl_themeresources_v2.5.xaml
Ports https://github.com/microsoft/microsoft-ui-xaml/pull/4121
> fix(PagerControl): Fix bug where setting button visibility would be ignored

- src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/NavigationView/NavigationViewTests.cs
GitHub Issue (If applicable): closes #7988
- Bugfix
`VerifyNavigationViewItemToolTipPaneDisplayMode` test is failing on Android
Test not failing anymore.
> fix: `VerifyNavigationViewItemToolTipPaneDisplayMode` test by adjusting for lifecycle differences

- build/convert-sourcetree-to-winui.cmd
GitHub Issue (If applicable): closes #8038
- Bugfix
> fix: Issue #8038

- doc/articles/getting-started-uno-figma.md
- doc/articles/toc.yml
Document the usage of Figma Plugin
> doc(figma): Added documentation for figma

- src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.Android.cs
- src/Uno.UI/UI/Xaml/Media/Brush.Android.cs
- Bugfix
Adds antialias pixels in Background Shape and Thickness Shape of Border
Like UWP, do no adds antialias pixels
> fix(Border): [Android] disable Antialias

- doc/articles/uno-development/themeresource-internals.md
> docs: Document resource update internals

- doc/articles/controls/ListViewBase.md
- doc/articles/uno-development/listviewbase-internals.md
> docs: Document ListView internals

- doc/articles/guides/localization.md
Change support channel from Stack to GitHub
Support points to Stack Overflow
Support points to GitHub discussions
> doc: Support/Help Channel

- doc/articles/logging.md
Mentioned in https://github.com/unoplatform/uno/issues/8026
Documenation
Documentation for https://platform.uno/docs/articles/logging.html does not work with Uno4.
Missing methods for this.Log().Error(...);
> docs : Instruct to install Uno.Core Nuget package

- doc/articles/splash-screen.md
A simple adjustment to the doc about SplashScreens. That info was missing for me as I'm not used to iOs-Storyboards in any way.
> [doc] Update splash-screen.md

- doc/articles/Uno-UI-Performance.md
- src/SolutionTemplate/UnoSolutionTemplate.net6/Shared/App.xaml.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/Uno.UI/UI/Xaml/ResourceResolver.cs
- src/Uno.UI/UI/Xaml/XamlFilePathHelper.shared.cs
- src/Uno.UWP/System/MemoryManager.Android.cs
- fix: Exclude fluent types from GlobalStaticResources automatic init
- docs: Update performance for x:Name in resource
- perf: Disable logging in release builds
- perf: Don't materialize x:Name-marked styles eargerly inside of uno
- perf(android): Don't refresh memory statistics too often
- perf: Adjust resource resolver to avoid ICU based comparisons on net6+
> Misc performance updates

- doc/articles/features/working-with-accessibility.md
GitHub Issue (If applicable): Related to https://github.com/unoplatform/uno/discussions/8125
- 
> docs: Adjust use of `AutomationProperties.AccessibilityView`

- src/SolutionTemplate/UnoSolutionTemplate.net6/Mobile/UnoQuickStart.Mobile.csproj
- src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props
- src/Uno.UI.Composition/Composition/CoreAnimation.iOSmacOS.cs
- src/Uno.UI/UI/Xaml/Media/Animation/Animators/DisplayLinkValueAnimator.iOSmacOS.cs
- src/Uno.UI/UI/Xaml/Media/CompositionTarget.iOS.cs
- Bugfix
- fix(catalyst): Include ios XAML for catalyst 
- fix(catalyst): Move to newer Preview 14 API breaking changes
- fix(catalyst): Force enable globalization and static registrar, disab...
> Misc fixes for .NET 6 Catalyst

- src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.skia.cs
GitHub Issue (If applicable): closes #8010
- Bugfix
> fix(Border): Issue #8010 BackgroundSizing

- build/ci/.azure-devops-ios-tests.yml
- build/test-scripts/ios-uitest-run.sh
- src/SamplesApp/SamplesApp.Shared/App.xaml.cs
- src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.cs
- Log running test on iOS.
- Add pre-install for simulator app to avoid https://github.com/microsoft/appcenter/issues/2389
> test: Log active tests for Runtime Tests runner

- src/AddIns/Uno.UI.MSAL/Uno.UI.MSAL.csproj
- src/AddIns/Uno.UI.MSAL/Uno.UI.MSAL.net6.csproj
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/Uno.ProjectTemplates.Dotnet.csproj
- src/Uno.Foundation.Runtime.WebAssembly/Uno.Foundation.Runtime.WebAssembly.csproj
- src/Uno.UI.Foldable/Uno.UI.Foldable.csproj
- src/Uno.UI.Foldable/Uno.UI.Foldable.net6.csproj
- src/Uno.UI.Runtime.Skia.Gtk/Uno.UI.Runtime.Skia.Gtk.csproj
- src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/Uno.UI.Runtime.Skia.Linux.FrameBuffer.csproj
- src/Uno.UI.Runtime.Skia.Tizen/Uno.UI.Runtime.Skia.Tizen.csproj
- src/Uno.UI.Runtime.Skia.Wpf/Uno.UI.Runtime.Skia.Wpf.csproj
> fix: Warnings NU5048

- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/TreeView/TreeViewBasics.xaml
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/TreeView/TreeViewBasics.xaml.cs
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/TreeView/TreeView_ItemInvoked.xaml
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/TreeView/TreeView_ItemInvoked.xaml.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SolutionTemplate/UnoSolutionTemplate.net6/Shared/App.xaml
- src/SolutionTemplate/UnoSolutionTemplate/Shared/App.xaml
- src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault/ToggleButton_themeresources.xaml
- src/Uno.UI.Runtime.Skia.Wpf/Uno.UI.Runtime.Skia.Wpf.csproj
- src/Uno.UI.Tests/DependencyProperty/Given_DependencyObject.cs
- src/Uno.UI.Tests/Windows_UI_Xaml/Given_SpecializedResourceDictionary.cs
- src/Uno.UI/UI/Xaml/Controls/Primitives/SelectorItem.cs
- src/Uno.UI/UI/Xaml/DependencyObjectStore.cs
- src/Uno.UI/UI/Xaml/SpecializedResourceDictionary.cs
- src/Uno.UI/UI/Xaml/UIElement.PointerCapture.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.cs
https://github.com/unoplatform/uno/pull/8185
https://github.com/unoplatform/uno/pull/8195
https://github.com/unoplatform/uno/pull/7141
https://github.com/unoplatform/uno/pull/8079
https://github.com/unoplatform/uno/pull/8189
https://github.com/unoplatform/uno/pull/8169
> Multiple backports

- build/ci/.azure-devops-android-tests.yml
- build/test-scripts/android-uitest-run.sh
- build/test-scripts/android-uitest-wait-systemui.sh
- Feature
waits indefinitely for the `adb wait-for-device` command to finish
waits 120 seconds for the 'adb wait-for-device' command to finish
> test: Android Emulator wait boot timeout

- doc/templates/uno/partials/_google-tag-manager.tmpl.partial
- Chore
There is no tracking in the Docs section,
the Google Tag Manager code is old
The code has been replaced with the new Google Tag Manager code
ADO User Story:  [#247478](https://dev.azure.com/nventive/UNO%20Marketing/_workitems/edit/247478)
> chore(docs): Update tag manager tracking code

- src/SamplesApp/SamplesApp.Droid/SamplesApp.Droid.csproj
GitHub Issue (If applicable): closes #8269
`BundleAssemblies` is now deprecated according to https://github.com/xamarin/xamarin-android/issues/6697#issuecomment-1034784286 and is causing deployment to fail.
Not using `BundleAssemblies` for debug
> fix: Samples app local debugging on Android

- build/PackageDiffIgnore.xml
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/8283
> ci: adjust diff ignore

- src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Media/EllipseGeometry.cs
- Bugfix
Report il log: `fail: Windows.UI.Xaml.Media.EllipseGeometry[0] The member EllipseGeometry.EllipseGeometry() is not implemented in Uno.`
do not report any messages
> fix(EllipseGeometry): [Skia] false message 'is not implemented in Uno' for  the member EllipseGeometry.EllipseGeometry()

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_Static_Event.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_Static_Event.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_Static_Event_DataTemplate.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/Binding_Static_Event_DataTemplate.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Given_xBind_Binding.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/8209
- Feature
Add support x:Bind to static event handlers
> feat: Add support x:Bind to static event handlers

- doc/articles/get-started-winui3.md
> docs: Adjust net6 winui project creation

- doc/articles/uno-development/building-uno-ui.md
> docs: Update reference assemblies build

- doc/articles/get-started-vsmac.md
- doc/articles/uno-check.md
> docs: Update vscode uno-check requirements

- build/ci/.azure-devops-ios-tests.yml
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-winui-net6/UnoWinUIQuickStart.Windows/UnoWinUIQuickStart.Windows.csproj
> chore: Update to WinAppSDK 1.0.1

- build/PackageDiffIgnore.xml
- build/ci/.azure-devops-ios-tests.yml
- build/ci/templates/dotnet6-install-mac.yml
- build/ci/templates/dotnet6-install-windows.yml
- build/test-scripts/ios-uitest-run.sh
- build/uno.winui.single-project.targets
- src/Directory.Build.targets
- src/Uno.UI/Controls/Window.macOS.cs
- src/Uno.UI/Extensions/Matrix3x2Extensions.iOSmacOS.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/NativeListViewBase.iOS.cs
- src/Uno.UI/UI/Xaml/DragDrop/DragDropExtension.macOS.cs
- src/Uno.UI/UI/Xaml/Media/Animation/Animators/GPUFloatValueAnimator.iOSmacOS.cs
- src/Uno.UI/UI/Xaml/Shapes/Shape.layout.cs
- src/Uno.UWP/ApplicationModel/DataTransfer/DataPackage.macOS.cs
- src/Uno.UWP/Devices/Midi/MidiOutPort.iOSmacOS.cs
> feat: Update to .NET 6 mobile Preview 14

- src/SamplesApp/SamplesApp.UITests/RuntimeTests.cs
- src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.cs
- src/SamplesApp/SamplesApp.iOS/SamplesApp.iOS.csproj
Improves CI runtime tests performance
> test: Disable visual update for test results when running on CI

- src/Uno.UWP/Storage/Pickers/FileOpenPicker.Android.cs
GitHub Issue (If applicable): closes #5899
- Bugfix
Bad MIME mappings - see #5899.
Correct MIME mappings.
Partly reused code from #2896
> fix: Android FileOpenPicker MIME types

- build/Uno.WinUI.nuspec
- src/Directory.Build.targets
> chore: Bump to stable Uno.SourceGeneration 4.0.2

- build/PackageDiffIgnore.xml
- build/Uno.WinUI.nuspec
- build/ci/.azure-devops-ios-tests.yml
- build/ci/templates/dotnet6-install-mac.yml
- build/ci/templates/dotnet6-install-windows.yml
- build/test-scripts/ios-uitest-run.sh
- build/uno.winui.single-project.targets
- src/Directory.Build.targets
- src/SamplesApp/SamplesApp.UITests/RuntimeTests.cs
- src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.cs
- src/SamplesApp/SamplesApp.iOS/SamplesApp.iOS.csproj
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-winui-net6/UnoWinUIQuickStart.Windows/UnoWinUIQuickStart.Windows.csproj
- src/Uno.UI/Controls/Window.macOS.cs
- src/Uno.UI/Extensions/Matrix3x2Extensions.iOSmacOS.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/NativeListViewBase.iOS.cs
- src/Uno.UI/UI/Xaml/DragDrop/DragDropExtension.macOS.cs
- src/Uno.UI/UI/Xaml/Media/Animation/Animators/GPUFloatValueAnimator.iOSmacOS.cs
- src/Uno.UI/UI/Xaml/Shapes/Shape.layout.cs
- src/Uno.UWP/ApplicationModel/DataTransfer/DataPackage.macOS.cs
- src/Uno.UWP/Devices/Midi/MidiOutPort.iOSmacOS.cs
- #8382
- #8381
- #8378
- #8373
- #8366
> Misc backports

- src/Uno.Foundation/IndexPath.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.managed.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/VirtualizingPanelLayout.managed.cs
GitHub Issue (If applicable): closes #5763
- Feature
> feat(ListView): incremental loading support for skia/wasm

- doc/articles/get-started-vs-2022.md
> docs: Adjust for 17.2 Preview 2 requirement

- src/Uno.UI.RuntimeTests/Tests/Uno_UI_Xaml_Input/Given_UnoFocusInputHandler.cs
- src/Uno.UI/UI/Xaml/Input/Internal/UnoFocusInputHandler.cs
GitHub Issue (If applicable): closes #6405
- Bugfix
Directional focus may cause infinite loop.
Infinite loop is prevented.
> fix: Directional focus can be evaluated indefinitely

- README.md
- doc/articles/contributing/guidelines/updating-dependencies.md
- doc/articles/guides/silverlight-migration/04-migrate-home-page-xaml-and-styles.md
- doc/articles/guides/silverlight-migration/09-client-auth-service.md
- doc/articles/guides/silverlight-migration/98-timeentry-samples.md
- doc/blog/201808-UnoUnderTheHoodIntro.md
- doc/blog/201906-porting-windows-calculator.md
- src/Uno.UI/FeatureConfiguration.cs
Naming and grammar corrections
Web Assembly -> WebAssembly, web assembly -> WebAssembly, webassembly -> WebAssembly, mac -> macOS, Thank-you -> Thank you
> naming corrections

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/DragCoordinates_Tests.cs
- src/SamplesApp/SamplesApp.Wasm/Properties/launchSettings.json
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/UIElementTests/UIElement_MeasurePerf.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/UIElementTests/UIElement_MeasurePerf.xaml.cs
- src/Uno.UI.RuntimeTests/Tests/Uno_UI_Toolkit/Given_VisibleBoundsPadding.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_UIElement.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.Measure.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs
- src/Uno.UI.Tests/Windows_UI_Xaml/FrameworkElementTests/Given_FrameworkElement.cs
- src/Uno.UI/Extensions/ViewExtensions.cs
- src/Uno.UI/FeatureConfiguration.cs
- src/Uno.UI/UI/Xaml/Controls/Canvas/Canvas.cs
- src/Uno.UI/UI/Xaml/Controls/Grid/Grid.Properties.cs
- src/Uno.UI/UI/Xaml/FrameworkElementHelper.cs
- src/Uno.UI/UI/Xaml/GridLength.cs
- src/Uno.UI/UI/Xaml/ILayouterElement.cs
- src/Uno.UI/UI/Xaml/UIElement.Android.cs
- src/Uno.UI/UI/Xaml/UIElement.Layout.cs
- src/Uno.UI/UI/Xaml/UIElement.Layout.netstd.cs
- src/Uno.UI/UI/Xaml/UIElement.cs
- src/Uno.UI/UI/Xaml/UIElement.iOS.cs
- src/Uno.UI/UI/Xaml/UIElement.macOS.cs
- src/Uno.UI/UI/Xaml/UIElement.net.cs
- src/Uno.UI/UI/Xaml/UIElement.netstdref.cs
- src/Uno.UI/UI/Xaml/UIElement.skia.cs
- src/Uno.UI/ts/WindowManager.ts
Implements https://github.com/unoplatform/uno/issues/8294
Added support for _Arrange Dirty Path_ for Skia & Wasm Platform.
> Arrange Dirty Path for Skia & Wasm

- src/Uno.UI/ts/Windows/Storage/StorageFolder.ts
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/8157
- Bugfix
Persisted folders need to be initialized before the VFS population is performed. The previous behavior would cause any folder but LocalFolder to be erased on synchronization.
> fix(idbfs): Fix non-LocalFolder persistence

- doc/articles/howto-consume-webservices.md
The example PostAsync method was mentioned twice, while the text referred to the PutAsync method.
> docs: Update howto-consume-webservices.md

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_UIElement.cs
- src/Uno.UI/UI/Xaml/UIElement.Layout.netstd.cs
- src/Uno.UI/UI/Xaml/UIElement.cs
> fix(layout_update): Fixed a potiential "Layout cycle detected." exception

- src/Uno.UI/UI/Xaml/ElementStub.iOSmacOS.cs
GitHub Issue (If applicable): closes #8331 
- Bugfix
NavigatinView using BurgerMenu was not working
> fix(macOS): SplitView opening action

- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-net6/global.json
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/global.json
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp/global.json
Chore
Currently, projects created using Uno templates have global.json files. They are useless and may even cause problems if the specified sdk is present on the system. In 95% of the cases they will use the roll forward policy, and simply choose the latestMajor installed version, which is the same as the default behavior (the default behavior also includes prerelease versions).
Also, projects with these files will not be built if only VS2022 Preview is installed (and, accordingly, only preview sdk)
They are removed
> chore: Removed global.json files from SolutionTemplate.

- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-winui/UnoWinUIQuickStart.Windows.Desktop/UnoWinUIQuickStart.Windows.Desktop.csproj
10.0.18362.22 -> 10.0.22000.24
> chore: Bump Microsoft.Windows.SDK.NET.Ref for WinUI template

- build/convert-sourcetree-to-winui.cmd
> fix: convert-sourcetree-to-winui.cmd

- doc/articles/get-started-with-linux.md
> docs: Remove arch linux specific templates versioning

- doc/articles/howto-consume-webservices.md
GitHub Issue (If applicable): closes #8482
> docs: Remove references to deprecated WasmHttpHandler

- doc/articles/faq.md
More detailed info about how to create Class Libraries to rescue VB code when porting app from UWP to Uno.
It is recreated #8492 , as my Uno clone was very old and has `Doc` folder, and newer Uno has `doc` folder.
> feat: more detailed ClassLib info for VB (recreated)

- build/ci/templates/dotnet6-install-mac.yml
- build/ci/templates/dotnet6-install-windows.yml
- build/ci/templates/gitversion.yml
- src/Directory.Build.targets
- src/SamplesApp/SamplesApp.Wasm/SamplesApp.Wasm.csproj
- src/SamplesApp/SamplesApp.net6mobile/SamplesApp.net6mobile.csproj
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-net6/global.json
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-winui-net6/global.json
- src/SolutionTemplate/UnoSolutionTemplate.net6/Mobile/UnoQuickStart.Mobile.csproj
- src/SolutionTemplate/UnoSolutionTemplate.net6/Wasm/UnoQuickStart.Wasm.csproj
- src/SolutionTemplate/UnoSolutionTemplate/Wasm/UnoQuickStart.Wasm.csproj
- src/SolutionTemplate/UnoSolutionTemplate/iOS/UnoQuickStart.iOS.csproj
> Misc updates for .NET 6 Mobile RC1

- build/uno.winui.single-project.targets
- src/SolutionTemplate/UnoSolutionTemplate.net6/Mobile/MacCatalyst/Info.plist
- src/SolutionTemplate/UnoSolutionTemplate.net6/Mobile/UnoQuickStart.Mobile.csproj
- src/SolutionTemplate/UnoSolutionTemplate.net6/Mobile/iOS/Info.plist
- src/SolutionTemplate/UnoSolutionTemplate.net6/Mobile/macOS/Info.plist
- src/SourceGenerators/Uno.UI.Tasks/Content/Uno.UI.Tasks.targets
- Bugfix
- fix: Adjust resources generation for net6.0-ios new targets
- fix: Adjust default plist values for net6 mobile targets
- fix(net6): Auto include BundleResources, show excluded compile items
- fix(net6): Remove unused InvariantGlobalization configuration
> Misc net6 mobile updates

- src/Uno.UI/UI/Xaml/Window.cs
- Bugfix
Window::DispatcherQueue throws NotImplementedException.
> fix(winui): implemented Window::DispatcherQueue

- src/Uno.UI.Runtime.Skia.Gtk/GLRenderSurface.cs
- src/Uno.UI.Runtime.Skia.Gtk/SoftwareRenderSurface.cs
closes https://github.com/unoplatform/uno/issues/8543
- Bugfix
For an unknown reason, matching the surface size for the SK render surface to the `GLArea` can cause render glitches. Adding a guard band avoids this flickering.
> fix(gtk): Fix OpenGL render surface flickering

- src/SolutionTemplate/UnoSolutionTemplate.net6/UWP/UnoQuickStart.Uwp.csproj
- src/SolutionTemplate/UnoSolutionTemplate/UWP/UnoQuickStart.Uwp.csproj
GitHub Issue (If applicable): https://github.com/unoplatform/uno/discussions/5007
- Bugfix
> fix: Apply workaround for VS Shared projects issue

- src/SolutionTemplate/UnoSolutionTemplate.Wizard/UnoSolutionWizard.cs
> fix(vsix): Don't fail if DTE build information cannot be found

- build/Install-WindowsSdkISO.ps1
> ci: Adjust for moved Windows SDK uri

- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.wasm.cs
Addresses a review comment from #8265.
> chore: Remove unused private method

- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/ImageSourceStream.xaml.cs
GitHub Issue (If applicable): closes #8589
- Bugfix
> fix: [SamplesApp] ImageSourceStream Error 522 Connection timeout

- build/PackageDiffIgnore.xml
> ci: fix PackageDiffIgnore.xml

- build/Uno.Foundation.Logging.nuspec
- build/Uno.UI.Adapter.Microsoft.Extensions.Logging.nuspec
- build/Uno.WinUI.Lottie.nuspec
- build/Uno.WinUI.MSAL.nuspec
- build/Uno.WinUI.RemoteControl.nuspec
- build/Uno.WinUI.Skia.Gtk.nuspec
- build/Uno.WinUI.Skia.Linux.FrameBuffer.nuspec
- build/Uno.WinUI.Skia.Tizen.nuspec
- build/Uno.WinUI.Skia.Wpf.nuspec
- build/Uno.WinUI.WebAssembly.nuspec
- build/Uno.WinUI.nuspec
- src/Uno.UI.Maps/Uno.UI.Maps.csproj
- src/Uno.UI.Runtime.Skia.Gtk/Uno.UI.Runtime.Skia.Gtk.csproj
> fix: PackageIcon

- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/ProgressRing/WinUIDeterminateProgressRing.xaml.cs
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/TabViewTests/TabViewPage.xaml.cs
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/TwoPaneViewTests/TwoPaneViewPage.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_Devices/OrientationTests.xaml
- src/SamplesApp/UITests.Shared/Windows_Devices/OrientationTests.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/UIElementTests/TransformToVisual_Transform.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListView_Explicit_Items.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBlockControl/TextBlock_MeasureCache.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/Input_Multiline.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/UIElementCollectionTests/UIElementCollection_Insert.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Input/RoutedEvents/RoutedEventsPage.xaml.cs
> misc: fixes same Samples App uwp issues

- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/SwipeControlTests/SwipeControl_Automated.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/SwipeControlTests/SwipeControl_ListView.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/SwipeControlTests/SwipeControl_ListView_ItemClick.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/SwipeControlTests/SwipeControl_ScrollViewer.xaml
- Bugfix
When run throw exception
> fix: [SamplesApp] Missing Icon Resource

- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/ImageSourceUrlMsAppDataScheme.xaml.cs
GitHub Issue (If applicable): closes #8586
- Bugfix
> fix: ImageSourceUrlMsAppDataScheme NullReferencenceException on DataContext Changed

- src/Uno.UI.Runtime.Skia.Wpf/Extensions/UI/Xaml/Controls/TextBoxViewExtension.cs
Addresses a review comment from #8265.
> chore: Cleanup `Select` implementation for Wpf

- doc/articles/uno-check.md
When searching for "uno check" , our docs engine doesn't find any matches as the search is literal. Inserting "uno check" in the body of this article should make it findable.
> docs: Update text for better uno-check discoverability

- src/Uno.UWP/Devices/Geolocation/Geolocator.iOSmacOS.cs
- src/Uno.UWP/Devices/Geolocation/GeolocatorHelper.iOS.cs
- Feature
Allow applications to set properties in the current instance of LocationManager.
Cannot set properties such as AllowsBackgroundLocationUpdates in LocationManager.
Can set additional properties within the existing LocationManager Instance
> [IOS] Add GetLocationManager to set properties

- src/Uno.UI.Runtime.Skia.Gtk/SoftwareRenderSurface.cs
- Detect macOS + arm64 and reset default `SKColorType` to `Bgra8888`
- Create the `SKBitmap` using the `SKImageInfo` instance
Addresses #8580
GitHub Issue (If applicable): closes #8580
- Bugfix
When using Skia.Gtk on a M1-based Mac computer the red and blue channels are inverted.
`SKColorType.Bgra8888` is used in the software renderer `RenderSurfaceType.Software` for macOS/arm64.
> fix(skia): SKImageInfo.PlatformColorType is incorrect on macOS/arm64

- src/SamplesApp/SamplesApp.UITests/Microsoft_UI_Xaml_Controls/NumberBoxTests/Given_NumberBox.cs
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/NumberBoxTests/NumberBoxPage.xaml
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/NumberBoxTests/NumberBoxPage.xaml.cs
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/SplitButtonTests/SplitButtonPage.xaml.cs
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/TreeView/TreeViewPage.xaml.cs
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/TwoPaneViewTests/TwoPaneViewPage.xaml.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/DropDownButton/DropDownButtonPage.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/PersonPictureTests/PersonPicturePage.xaml.cs
> fix:(SamplesApp): Mux Category

- src/AddIns/Uno.UI.Lottie/LottieVisualSourceBase.wasm.cs
- src/SamplesApp/UITests.Shared/Lottie/SampleLottieAnimation.xaml.cs
This is a re-edit of this PR : https://github.com/unoplatform/uno/pull/8535 which I seem to have broken due to a bad rebase from me.
> fix: enabling distant URIs for Lottie

- src/Uno.UI.Runtime.Skia.Gtk/SoftwareRenderSurface.cs
- Cache surfaces and bitmap between invocation
- Avoid repetitive calls ending up calling native code (transition is costly), e.g.
- successive calls to properties like `surface.Canvas` and `_bitmap.Width`
- multiple calls to `_bitmap.GetPixels(out _)`
- Dispose existing `SKBitmap` and `SKSurface` when needed (e.g. window resizing)
- Removed nullable on `float? _dpi;` is already assigned to a value (by
.ctor) and `UpdateDpi` never set it to `null`
Performance
Some surfaces and bitmaps are created for each rendering call.
Surface/bitmaps are reused between rendering calls - unless the surface size has changed.
Measuring the impact was tricky since …
> perf(skia): Reuse surfaces/bitmaps and reduce native calls

- src/Uno.UI.Composition/Composition/CompositionObject.cs
- src/Uno.UI.Composition/Generated/3.0.0.0/Windows.UI.Composition/CompositionObject.cs
> chore: removing the error message for Composition.Dispose()

- src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/Repeater/ViewportTests.cs
GitHub Issue (If applicable): part of #8261
- Bugfix
- Test
> test: Enable `ViewportTests`

- src/SourceGenerators/Uno.UI.SourceGenerators/NativeCtor/NativeCtorsGenerator.cs
GitHub Issue (If applicable): closes #8684
- Bugfix
> fix(SourceGenerators): NativeCtorsGenerator will execute after XamlCodeGenerator

- src/AddIns/Uno.UI.MSAL/LinkerDefinition.xml
> [MSAL/WASM] Added "Jwt" assembly to linker definition

- doc/articles/supported-libraries.md
> docs: add 3rd party option

- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ImageTests/LargeImageList.xaml
> test: Fix large image sample bindings

- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp/.template.config/template.json
GitHub Issue (If applicable): closes #7203
- Bugfix
format property does not work according to https://github.com/dotnet/templating/issues/1737#issuecomment-831869212 and defaultFormat must be used instead
GUIDs are formatted correctly within the template
- [ x] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [x ] Associated with an issue (GitHub or internal) and uses the [automatic close …
> fix: Invalid GUID parameter name in dotnet new template JSON

- doc/articles/feature-flags.md
- src/Uno.UI/Controls/UIFontHelper.iOS.cs
- src/Uno.UI/Extensions/ViewHelper.Android.cs
- src/Uno.UI/FeatureConfiguration.cs
> fix: added maximum text scale factor to android

- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/AutoSuggestBoxTests/BasicAutoSuggestBox.xaml.cs
- src/Uno.UI/UI/Xaml/Controls/AutoSuggestBox/AutoSuggestBox.cs
GitHub Issue (If applicable): closes #7778
- Bugfix
Please see attached sample - which is a modified version of what I posted at https://github.com/unoplatform/uno/issues/4382 - and search for '!!!': in the QuerySubmitted event "e.ChosenSuggestion == null" when selection an option from the drop down. 
e.ChosenSuggestion contains the SelectedItem from internal ListView.
- [ x] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- …
> fix: AutoSuggestBox.QuerySubmitted ChosenSuggestion should not be null

- src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.Diagnostics.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/8803
- Bugfix
- Enhance Roslyn version detection (including `10`, instead of `10.0`)
- Enhance error reporting when parsing `PRIResource`
> Misc source generation fixes

- doc/import_external_docs.ps1
> docs: Update Figma docs

- doc/import_external_docs.ps1
Update Themes and Toolkit documentation
> docs: Update Themes and Toolkit documentation

- doc/import_external_docs.ps1
> docs: Update import_external_docs.ps1

- src/Directory.Build.props
Improve compilation time by using native roslyn generators for unit tests.
> test: Enable roslyn source generation for unit tests

- doc/import_external_docs.ps1
> docs: Update import_external_docs.ps1 to latest

- src/SolutionTemplate/UnoSolutionTemplate.WinUI.net6/Mobile/UnoQuickStart.Mobile.csproj
- Bugfix
Remove conditional formatting for vsix mobile, as VS seems to reformat conditionals.
> fix: Adjust formatting in the vsix mobile template

- src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Behaviors/WebViewBehavior.cs
> fix(WebViewBehavior): Possible nre when NewValue is null

- build/ci/templates/dotnet6-install-mac.yml
- build/ci/templates/dotnet6-install-windows.yml
> ci: Build using .NET 6 Mobile RTM

- doc/articles/uno-development/building-uno-macos.md
Copy/pasting the command into the macOS shell does not work
Copy/pasting the command execute the command properly
> docs: fix small typo to ease copy/pasting the shell command

- build/ci/.azure-devops-screenshot-compare.yml
> ci: renamed screenshot compare result artifact

- doc/articles/toc.yml
> docs: Correct extension for how uno works article

- doc/import_external_docs.ps1
> docs: update Toolkit docs reference

- src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/Repeater/RepeaterFocusTests.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/Repeater/ChildrenInTabFocusOrderIterable.cs
GitHub Issue (If applicable): part of #4529
- Bugfix
- Tests
Disabled
Enabled
> test: Enable `RepeaterFocusTests`

- build/ci/.azure-devops-commitsar.yml
- build/ci/templates/generate-changelog.yml
> ci: Generate changelog in artifacts

- doc/import_external_docs.ps1
Update main documentation for Uno.Toolkit.UI
> docs: Update documentation for Uno.Toolkit.UI

- src/Uno.UI.TestComparer/Program.cs
GitHub Issue (If applicable): closes #8875 
> fix: Using long path format for Attachment

- src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/Repeater/PhasingTests.cs
GitHub Issue (If applicable): part of #4529
- Tests
Disabled
Enabled
> test: Enable `PhasingTests`

- src/SolutionTemplate/UnoSolutionTemplate.net6/Mobile/UnoQuickStart.Mobile.csproj
- Bugfix
This change is based on https://github.com/unoplatform/performance/pull/13
> fix(net6): Replicates the linker default behavior for xamarin.mac

- doc/articles/intro.md
> docs: Update Intro FAQ

- src/Directory.Build.targets
- src/Uno.UI.Runtime.Skia.Gtk/Uno.UI.Runtime.Skia.Gtk.csproj
- src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/Uno.UI.Runtime.Skia.Linux.FrameBuffer.csproj
- src/Uno.UI.Runtime.Skia.Tizen/Uno.UI.Runtime.Skia.Tizen.csproj
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/9031
- Bugfix
Adds missing dependencies for Linux for Harfbuzz.
> fix(skia): Adjust more Harfbuzz dependencies

- doc/articles/features/windows-ui-xaml-window.md
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/WindowTests/Window_SetBackground.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/WindowTests/Window_SetBackground.xaml.cs
- src/Uno.UI.Runtime.Skia.Gtk/GLRenderSurfaceBase.cs
- src/Uno.UI.Runtime.Skia.Gtk/GtkHost.cs
- src/Uno.UI.Runtime.Skia.Gtk/IRenderSurface.cs
- src/Uno.UI.Runtime.Skia.Gtk/SoftwareRenderSurface.cs
- src/Uno.UI.Runtime.Skia.Wpf/Themes/Generic.xaml
- src/Uno.UI.Runtime.Skia.Wpf/WpfHost.cs
- src/Uno.UI/UI/Xaml/Window.cs
- src/Uno.UI/UI/Xaml/Window.skia.cs
- src/Uno.UI/UI/Xaml/WindowHelper.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/discussions/8957
- Feature
Provide the ability to change the Window background color, to take into account redraw time on some platforms.
> feat: Add the ability to set the Window background color

- doc/articles/features/PasswordVault.md
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/8992
> docs: Fix invalid tabs in password vault documentation

- .github/workflows/winui-autoconvert.yml
- doc/articles/uno-development/winui-conversion.md
- src/Uno.WinUIRevert/Uno.WinUIRevert.csproj
Automatically updates a winui-converted branch on every push to master.
> ci: autogenerate winui branch

- doc/articles/features/uno-cupertino.md
- doc/articles/features/uno-material.md
- doc/articles/features/windows-storage-pickers.md
- doc/articles/toc.yml
GitHub Issue (If applicable): **N/A**
**N/A**
**N/A**
Internal Issue (If applicable): **N/A**
> Miscellaneous documentation fixes

- doc/articles/features/Lottie.md
Fixed only one but important word in a document!
> Fixed typo in Update Lottie.md

- src/AddIns/Uno.UI.Lottie/LottieVisualSource.Skottie.cs
- src/AddIns/Uno.UI.Lottie/Uno.UI.Lottie.net6.csproj
- Bugfix
- Restore proper transparency support for AnimatedVisualPlayer
- Adjust content loading for Skottie to avoid UTF8 encoding issues
> AnimatedVisualPlayer fixes

- build/Uno.WinUI.Lottie.nuspec
- doc/articles/features/Lottie.md
- src/AddIns/Uno.UI.Lottie/LottieVisualSource.Skottie.cs
- src/AddIns/Uno.UI.Lottie/buildTransitive/Uno.UI.Lottie.targets
- src/Directory.Build.targets
- src/SamplesApp/SamplesApp.Skia.WPF/SamplesApp.Skia.WPF.csproj
- src/SolutionTemplate/UnoSolutionTemplate/Skia.Tizen/UnoQuickStart.Skia.Tizen.csproj
> fix(skottie): Adjust for transparent iOS render surface

- src/SolutionTemplate/UnoSolutionTemplate.WinUI.net6/Mobile/UnoQuickStart.Mobile.csproj
- src/SolutionTemplate/UnoSolutionTemplate.WinUI.net6/Skia.Gtk/UnoQuickStart.Skia.Gtk.csproj
- src/SolutionTemplate/UnoSolutionTemplate.WinUI.net6/Skia.Linux.FrameBuffer/UnoQuickStart.Skia.Linux.FrameBuffer.csproj
- src/SolutionTemplate/UnoSolutionTemplate.WinUI.net6/Skia.WPF/UnoQuickStart.Skia.WPF.csproj
- src/SolutionTemplate/UnoSolutionTemplate.net6/Mobile/UnoQuickStart.Mobile.csproj
- src/SolutionTemplate/UnoSolutionTemplate.net6/Skia.Gtk/UnoQuickStart.Skia.Gtk.csproj
- src/SolutionTemplate/UnoSolutionTemplate.net6/Skia.Linux.FrameBuffer/UnoQuickStart.Skia.Linux.FrameBuffer.csproj
- src/SolutionTemplate/UnoSolutionTemplate.net6/Skia.WPF/UnoQuickStart.Skia.WPF.csproj
- src/SolutionTemplate/UnoSolutionTemplate.net6/UWP/UnoQuickStart.Uwp.csproj
- src/SolutionTemplate/UnoSolutionTemplate/Droid/UnoQuickStart.Droid.csproj
- src/SolutionTemplate/UnoSolutionTemplate/Skia.Gtk/UnoQuickStart.Skia.Gtk.csproj
- src/SolutionTemplate/UnoSolutionTemplate/Skia.Linux.FrameBuffer/UnoQuickStart.Skia.Linux.FrameBuffer.csproj
- src/SolutionTemplate/UnoSolutionTemplate/Skia.Tizen/UnoQuickStart.Skia.Tizen.csproj
- src/SolutionTemplate/UnoSolutionTemplate/Skia.WPF/UnoQuickStart.Skia.WPF.csproj
- src/SolutionTemplate/UnoSolutionTemplate/UWP/UnoQuickStart.Uwp.csproj
- src/SolutionTemplate/UnoSolutionTemplate/macOS/UnoQuickStart.macOS.csproj
According discussion: https://github.com/unoplatform/uno/discussions/9166
Refactoring 
The templates included PackageReference with Microsoft.Extensions.Logging which are transient dependencies of all Microsoft.Extensions.Logging.XXX packages.
They are removed
> refactor: Removed transient Microsoft.Extensions.Logging package from templates.

- src/Uno.UI/UI/Xaml/FrameworkElement.macOS.cs
On macOS `Framework.Layout` calls two times the `Bounds` getter, which is a native ObjC call. This happen inside performance-sensitive code. On my system that's 1.91 seconds for running Dope (net6).
The code is different for the iOS backend, so this PR only applies to macOS.
A single call to `get_Bounds` is made. That cuts the time it takes in half, down to about 910ms on my system.
> perf(macOS): Call Bounds propety only once inside FrameworkElement.Layout

- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
> Add missing samples

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Media/Given_RevealBrush.cs
- src/Uno.UI/Extensions/ViewHelper.iOSmacOS.cs
GitHub Issue (If applicable): closes #9131
- Bugfix
The size of the `CGRect`, `Width` and `Height`, were used like a point in the calculations.
This means a correct to `X` or `Y` was not reflected in the `Width` and `Height` properties.
Example:
Input: `{{X=451.5,Y=1865,Width=182,Height=30}}`
Output: `{{X=451,Y=1865,Width=182,Height=30}}`
Anything in the last half pixel (width) is _lost_ (as not part of the returned `CGRect`).
Calculations are done on two points (X1,Y1) and (X2,Y2). The a `CGRect` is created from those two points - IOW Width and Height are recalculated.
Example:
Input: `{{X=451.5,Y=1865,Width=182,Height=30}}`
Output: `{{X=451,Y=1865,Width=183,Height=30}}`
A width of 183 encompass all the input rect and returns an integral rectangle.
Also
* when the scale is 1.0 (default) …
> fix(iOSmacOS): Correct computation for LogicalToPhysicalPixels

- src/Uno.UI/UI/Xaml/Application.macOS.cs
- Bugfix
Compilation fail if `warnaserror` is enabled (like it is on bots). 
This makes #8130 fails to build for macOS tests.
```
/Users/runner/work/1/s/src/Uno.UI/UI/Xaml/Application.macOS.cs(16,7): error CS0105: The using directive for 'ObjCRuntime' appeared previously in this namespace [/Users/runner/work/1/s/src/Uno.UI/Uno.UI.csproj]
18 Warning(s)
1 Error(s)
Time Elapsed 00:06:40.98
##[error]Error: The process '/Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild' failed with exit code 1
```
Removed the duplicated namespace. Compilation should be fine.
> fix(macOS): Remove dupe ObjCRuntime namespace

- doc/import_external_docs.ps1
- Documentation update
Update to latest version of figma docs
> docs: Update to latest version of figma docs

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Media/ImageBrushTests/ImageBrush_Shape_Fill_StretchAndAlignment.cs
> refactor: Simplify test

- src/Uno.UI-Windows-only.slnf
- src/Uno.UI.sln
GitHub Issue (If applicable): closes #9228
- Bugfix
When run Uno.UI-Windows-only.slnf on clean repository the build failed
> fix: Uno.UI-Windows-only.slnf build dependencies

- src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/UIElementTests/InlineTextInSpan.xaml.cs
- src/Uno.UI.RuntimeTests/IntegrationTests/common/TestServices.WindowHelper.cs
- src/Uno.UI.RuntimeTests/IntegrationTests/common/TestServices.cs
GitHub Issue (If applicable): closes #9237
- Bugfix
> fix: Enable full-window runtime tests on Windows, fix: Add misssing code-behind

- src/SamplesApp/SamplesApp.Shared/App.xaml.cs
- src/SamplesApp/SamplesApp.Skia/SamplesApp.Skia.csproj
- src/Uno.UI.Runtime.Skia.Gtk/GtkHost.cs
GitHub Issue (If applicable): closes #9242
> Fixes [Skia] SamplesApp Default Windows Title

- src/SamplesApp/SamplesApp.UITests/TestFramework/IsExternalInit.cs
- src/Uno.UI/UI/Xaml/Controls/ListViewBase/ListViewBase.DragDrop.cs
Fix not addressed comments of https://github.com/unoplatform/uno/pull/8406
> chore: Fix PR comments

- doc/articles/guides/uno-material-walkthrough.md
GitHub Issue (If applicable): closes #8475
Documentation under How to use Uno.Material -> "Section 2: Using Uno.Material library" section makes reference to Chip/ChipGroup/Card/Divider which have now all been moved to the Uno.Toolkit.UI.Material package
Documentation reflects the updated package and the usages. 
> docs: Update for "How to use Uno.Material" 

- build/ci/.azure-devops-skia-tests.yml
- src/SamplesApp/SamplesApp.Shared/App.xaml.cs
- src/SamplesApp/SamplesApp.Skia.WPF/MainWindow.xaml
- src/SamplesApp/SamplesApp.Skia.WPF/SamplesApp.Skia.WPF.csproj
- src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.cs
- src/Uno.UI.Runtime.Skia.Wpf/Extensions/UI/Xaml/Controls/TextBoxViewExtension.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs
- src/Uno.UI/UI/Xaml/UIElement.XamlRoot.cs
GitHub Issue (If applicable): closes #9256, closes #9259
- Feature
> feat: Skia WPF Runtime Tests and Snapshot Tests, setting `XamlRoot` on `UIElement`

- doc/articles/use-uno-check-inline.md
added 2a/2b to Uno check process for improved experience
uno check install/update listed as one process
seperated Uno check install and update with multi level list (2a/2b)
> docs: added multi level list for uno check

- src/Uno.UI.Runtime.Skia.Gtk/Extensions/Storage/Pickers/FolderPickerExtension.cs
- src/Uno.UI.Runtime.Skia.Gtk/GtkCoreWindowExtension.cs
- src/Uno.UI.Runtime.Skia.Gtk/GtkDisplayInformationExtension.cs
- src/Uno.UI.Runtime.Skia.Gtk/GtkHost.cs
- src/Uno.UI.Runtime.Skia.Gtk/UI/Xaml/Controls/TextBoxViewExtension.cs
> Fixes runtimes skia gtk warnings

- src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.cs
- src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.skia.cs
- src/Uno.UI/UI/Xaml/Documents/Hyperlink.cs
- src/Uno.UI/UI/Xaml/Documents/Hyperlink.skia.cs
- src/Uno.UI/UI/Xaml/Documents/InlineCollection.skia.cs
closes #8956
- Bugfix
- Feature
Hyperlinks in TextBlocks are not colored correctly and cannot be clicked.
Hyperlinks in TextBlocks default to standard blue link color and can be clicked.
> [Skia] TextBlock hyperlink hit testing and color fix

- doc/articles/feature-flags.md
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ContentDialog/UnoSamples_Tests.ContentDialog.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ContentDialogTests/ContentDialog_Simple.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ContentDialogTests/ContentDialog_Simple.xaml.cs
- src/Uno.UI.RuntimeTests/Helpers/FeatureConfigurationHelper.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ContentDialog.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_MenuFlyout.cs
- src/Uno.UI/FeatureConfiguration.cs
> feat: Stop using Android native popups by default

- src/Uno.UI.Runtime.Skia.Wpf/Extensions/Storage/Pickers/FolderPickerExtension.cs
- src/Uno.UI.Runtime.Skia.Wpf/Extensions/UI/Xaml/Controls/Extensions.cs
- src/Uno.UI.Runtime.Skia.Wpf/Input/HostPointerHandler.cs
- src/Uno.UI.Runtime.Skia.Wpf/Rendering/UnoWpfRenderer.cs
- src/Uno.UI.Runtime.Skia.Wpf/WpfCoreWindowExtension.cs
- src/Uno.UI.Runtime.Skia.Wpf/WpfDragDropExtension.cs
- src/Uno.UI.Runtime.Skia.Wpf/WpfHost.cs
> Fixes runtimes skia wpf warnings

- doc/articles/uwp-vs-winui3.md
> docs: Updating WinUI options with Uno Platform

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/EventSequence_Tests.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_ThemeResource.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_UIElement.TransformToVisual.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_StackPanel.cs
- src/Uno.UI/UI/Xaml/FrameworkElement.Layout.netstd.cs
GitHub Issue (If applicable): closes #7246, partially addresses #6395
- Bugfix
> fix: Clip desired size to MaxWidth and MaxHeight

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/EventSequence_Tests.cs
> test: Re-enable TestTranslatedClick

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Viewbox.cs
- src/Uno.UI/Helpers/WinUI/MathHelpers.cs
- src/Uno.UI/UI/Xaml/Controls/Layouter/Layouter.cs
- src/Uno.UI/UI/Xaml/Controls/ViewBox/Viewbox.cs
GitHub Issue (If applicable): closes unoplatform/nventive-private#281
- Bugfix
Viewbox is not properly centered in certain situation.
fixed Viewbox alignment
> chore: port Viewbox from WinUI source

- doc/import_external_docs.ps1
> Updating the external figma doc

- src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.cs
- src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.skia.cs
- Cleanup (no functional changes)
> chore(TextBlock): [Skia] Dead code cleanup

- src/Uno.UI.FluentTheme.v2/themeresources_v2.xaml
- src/Uno.UI/UI/Xaml/Style/mergedstyles.xaml
- Feature
Style changes were not merged.
Merged.
> chore: Unmerged InfoBar style changes

- build/Uno.WinUI.nuspec
- src/Directory.Build.targets
> chore: Update uno.sourcegenerationtasks to 4.1.0-dev.9

- build/uno.winui.common.targets
- src/Common.targets
According this discussion: https://github.com/unoplatform/uno/discussions/9145
Bugfix
There are currently two Targets with the same name in the project, which seem to be causing conflicts
They are renamed, the name is chosen based on the context. The project did not have Targets that depend on them.
> fix: Fixed bug with visibility of constants for generators.

- doc/articles/features/Lottie.md
Docs update for Lottie, fixes tabs
> docs: fix tabs on Lottie docs

- src/Uno.UI.XamlHost.Skia.Wpf/UnoXamlHost.DataBinding.cs
- src/Uno.UI.XamlHost/Extensions/DesktopWindowXamlSourceExtension.cs
> fix: Avoid NRE when querying VisualTree too early for Uno Island

- src/SamplesApp/SamplesApp.Skia.Gtk/SamplesApp.Skia.Gtk.csproj
- src/Uno.UI.Runtime.Skia.Gtk/GLRenderSurfaceBase.cs
- src/Uno.UI.Runtime.Skia.Gtk/GtkDisplayInformationExtension.cs
- Bugfix
**TODO Does not support fractional scaling correctly yet.**
> [WIP] Re-enable DPI scaling on GTK

- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-winui-xamarin/UnoWinUIQuickStart.Windows.Desktop/UnoWinUIQuickStart.Windows.Desktop.csproj
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-winui-xamarin/UnoWinUIQuickStart.Windows.Package/UnoWinUIQuickStart.Windows.Package.wapproj
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp/UnoWinUIQuickStart.Windows/UnoWinUIQuickStart.Windows.csproj
- src/SolutionTemplate/UnoLibraryTemplate.net6/CrossTargetedLibrary.csproj
- src/SolutionTemplate/UnoSolutionTemplate.WinUI.net6/WinUI/UnoQuickStart.Windows.csproj
- src/Uno.UWPSyncGenerator.Reference/Uno.UWPSyncGenerator.Reference.csproj
> chore: Bump winui templates to WinAppSDK 1.1.3

- doc/articles/uno-builds-troubleshooting.md
> docs:Fix typo in documentation

- build/ci/.azure-devops-ios-tests.yml
- src/SamplesApp/SamplesApp.UITests.Generator/SnapShotTestGenerator.cs
- src/SamplesApp/SamplesApp.UITests/TestFramework/ImageAssert.cs
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml/DragAndDropTests/DragDrop_ListViewReorder_Automated.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ListViewBase.cs
- src/Uno.UI/Controls/CommandBar/CommandBarHelper.iOS.cs
- src/Uno.UWP/Storage/Pickers/FileOpenPicker.iOS.cs
- src/Uno.UWP/Storage/Pickers/FolderPicker.iOS.cs
- Bugfix
- Fixes When_Scrolled_To_End_And_Last_Item_Removed
- Increase snapshot groups count
> test: Fix unstable test When_Scrolled_To_End_And_Last_Item_Removed

- build/Uno.WinUI.nuspec
- src/Directory.Build.targets
> chore: Bump to Uno.SourceGeneration.Tasks 4.1.0

- build/run-doc-generation.cmd
- src/Directory.Build.targets
More adjustments on VS 17.3 use of System.Memory for documentation generation
> ci: Fix doc generation on 17.3

- build/ci/.azure-devops-project-template-tests.yml
> ci: Adjust template tests setup for VS 17.3

- build/ci/.azure-devops-android-tests.yml
- build/ci/.azure-devops-samplesapp-uitests-build.yml
- build/test-scripts/android-uitest-run.sh
- src/SamplesApp/SamplesApp.UITests/ScreenshotInfo.cs
- src/SamplesApp/SamplesApp.UITests/TestFramework/ImageAssert.cs
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Shapes/Basics_Shapes_Tests.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/9550
> Disable android screenshot validations in UI Tests

- src/Uno.UWP/Storage/Pickers/FileOpenPicker.Android.cs
> chore: Use 'Any()' instead of 'Count()' and remove unnecessary null check

- src/Uno.UI/Controls/Window.iOS.cs
related to https://github.com/unoplatform/uno/issues/9071
- Feature
- KeyUp support for MacCatalyst is not available
- Events are not bubbled up to the focused Element
> (MacCatalyst) Add KeyUp event support

- src/Uno.UI/UI/Xaml/Controls/Flyout/FlyoutBase.net.cs
Found the following in CI in another PR. Not sure why it doesn't fail in master, but here is the fix anyway.
> ##[error]src\Uno.UI\UI\Xaml\Controls\Flyout\FlyoutBase.net.cs(25,16): Error CS8826: Partial method declarations 'void FlyoutBase.SetPopupPositionPartial(UIElement placementTarget, Point? positionInTarget)' and 'void FlyoutBase.SetPopupPositionPartial(UIElement placementTarget, Point? position)' have signature differences.
Now I'm matching https://github.com/unoplatform/uno/blob/d0f063de40bec072a06e2f3ae7e1267ae109b91d/src/Uno.UI/UI/Xaml/Controls/Flyout/FlyoutBase.cs#L433
> chore: Update parameter name to match partial definition

- build/Uno.UI.Build.csproj
- build/ci/.azure-devops-android-tests.yml
- src/SamplesApp/UITests.Shared/Windows_Devices/AccelerometerTests.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_Devices/BarometerTests.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_Devices/BluetoothSelectors.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_Devices/GeolocatorTests.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_Devices/GyrometerTests.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_Devices/HingeAngleSensorTests.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_Devices/LightSensorTests.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_Devices/MagnetometerTests.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_Devices/OrientationTests.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_Devices/PedometerTests.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_Devices/RadioTests.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Repeater/FlowLayout_Simple.xaml.cs
- Fix for failing NPM
- Adjust android runtime tests groups invalid default value
- Remove some unneeded screenshot tests
> Misc CI fixes

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml/DragAndDropTests/DragDrop_ListViewReorder_Automated.cs
Test fails a lot.
Test is disabled until the flakiness root cause is determined and fixed.
> test: Disable flaky test When_Reorder_To_Last_2

- src/Uno.UI/UI/Xaml/VisibilityExtensions.cs
Adheres to https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1041
> Add message to obsolete attribute

- .vsts-ci.yml
- README.md
- doc/articles/get-started-vs.md
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/9573
> Misc docs adjustments

- doc/articles/get-started-with-linux.md
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/6441
- Doc
> docs: Adjust for missing microsoft ttf package

- src/SolutionTemplate/UnoLibraryTemplate.net6/CrossTargetedLibrary.Net6.vstemplate
- src/SolutionTemplate/UnoLibraryTemplate.net6/UnoLibraryTemplate.net6.csproj
- src/SolutionTemplate/UnoLibraryTemplate/CrossTargetedLibrary.vstemplate
- src/SolutionTemplate/UnoSolutionTemplate.VSIX.2022/UnoSolutionTemplate.VSIX.2022.csproj
- src/SolutionTemplate/UnoSolutionTemplate.VSIX.2022/source.extension.vsixmanifest
- src/SolutionTemplate/UnoSolutionTemplate.WinUI.net6/UnoApp.net6.vstemplate
- src/SolutionTemplate/UnoSolutionTemplate.Wizard.2019/UnoSolutionWizard.cs
- src/SolutionTemplate/UnoSolutionTemplate.Wizard.2022/UnoSolutionWizard.cs
- src/SolutionTemplate/UnoSolutionTemplate/UnoApp.vstemplate
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/9459, closes https://github.com/unoplatform/uno/issues/9508, closes https://github.com/unoplatform/uno/issues/9281
- Bugfix
- Change templates ordering in VS project creation dialog
- Bump VS nuget references
- Include UWP/Xamarin library template
- Ensure mobile and windows targets are deployable by default]
- fix(vsix): Restore default startup project and configuration for UWP
> Misc VSIX fixes

- src/SamplesApp/SamplesApp.iOS/SamplesApp.iOS.csproj
- src/Uno.UI/Controls/Window.iOS.cs
- src/Uno.UI/FeatureConfiguration.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/MultilineTextBoxView.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/SinglelineTextBoxView.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.iOS.cs
GitHub Issue (If applicable): #9559, #9484, https://github.com/unoplatform/uno/issues/9430
> Backport #9559 and #9484 for 4.4.x

- .vsts-ci.yml
- build/SignClient.json
- build/Uno.UI.Build.csproj
- build/ci/.azure-devops-wasm-uitests.yml
- src/SamplesApp/SamplesApp.iOS/SamplesApp.iOS.csproj
- src/Uno.UI/Controls/Window.iOS.cs
- src/Uno.UI/FeatureConfiguration.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/MultilineTextBoxView.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/SinglelineTextBoxView.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.iOS.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/9430
> Backport #9559 and #9484 for 3.1.x 

- .editorconfig
This forces code editors to use `\r\n` for line endings to avoid a developer pushing `\n` and then a change is made by another developer who uses `\r\n` that will cause all file lines to be changed to `\r\n` (example https://github.com/unoplatform/uno/pull/9637, https://github.com/unoplatform/uno/pull/9555, and https://github.com/unoplatform/uno/pull/6864)
I think `\r\n` (CRLF) is the most common line ending.
> chore: Add `end_of_line = crlf` in editorconfig

- src/Uno.UI/Controls/BindablePagerAdapter.Android.cs
See https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1841
> perf: Use `.ContainsKey` instead of `.Keys.Contains` (CA1841)

- src/SourceGenerators/Uno.UI.SourceGenerators/DependencyObject/DependencyObjectGenerator.cs
- src/Uno.Foundation/Uno.Core.Extensions/Uno.Core.Extensions/DisposableAction.cs
- src/Uno.UI.Tests/DependencyProperty/Given_DependencyObjectInGlobalNamespace.cs
GitHub Issue (If applicable): closes #9423
> fix: Fix DependencyObjectGenerator for global namespaces and WPF head

- src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.cs
GitHub Issue (If applicable): closes #9635
> fix: Fix `NotImplemented` for `IsTextSelectionEnabled` in Wasm

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ListViewTests/UnoSamples_Tests.ListView.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/9080
> ci: Disable ListView_ObservableCollection_Unused_Space

- src/Uno.UWP/ApplicationModel/DataTransfer/DataPackageOperation.cs
GitHub Issue (If applicable): closes #9600
> fix: Remove NotImplemented attribute from DataPackageOperation enum members

- build/ci/templates/dotnet6-install-mac.yml
- build/ci/templates/dotnet6-install-windows.yml
- src/SamplesApp/SamplesApp.net6mobile/SamplesApp.net6mobile.csproj
- src/SourceGenerators/Uno.UI.Tasks/LinkerHintsGenerator/LinkerDefinitionMergerTask.cs
- src/SourceGenerators/Uno.UI.Tasks/LinkerHintsGenerator/LinkerHintGeneratorTask.cs
- src/Uno.UI.FluentTheme.v1/Uno.UI.FluentTheme.v1.net6.csproj
- src/Uno.UI.FluentTheme.v2/Uno.UI.FluentTheme.v2.net6.csproj
- src/Uno.UI.FluentTheme/Uno.UI.FluentTheme.net6.csproj
- src/Uno.UI.Toolkit/Uno.UI.Toolkit.net6.csproj
- src/Uno.UI/Uno.UI.net6.csproj
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/9632
- Bump the runtime to 6.0.400 final
- Don't run XAML Trimming tooling when building in debug
- Don't pass java assemblies to the linker for android
> Misc XAML Trimming adjustments

- build/PackageDiffIgnore.xml
- src/Uno.UI.Tests/Windows_UI_XAML_Controls/TimePickerTests/Given_TimePicker.cs
- src/Uno.UI/FeatureConfiguration.cs
- src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/TimePickedEventArgs.cs
- src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/TimePicker.cs
- src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/TimePickerFlyout.cs
- src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/TimePickerSelectedValueChangedEventArgs.cs
- src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/TimePickerValueChangedEventArgs.cs
- src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickedEventArgs.cs
- src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePicker.cs
- src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerFlyout.Android.cs
- src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerFlyout.cs
- src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerFlyout.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerSelectedValueChangedEventArgs.cs
- src/Uno.UI/UI/Xaml/Controls/TimePicker/TimePickerValueChangedEventArgs.cs
GitHub Issue (If applicable): closes #9629, closes #8301
- Feature
- TimePicker's `SelectedTime`, `TimeChanged`, and `SelectedTimeChanged` events are not implemented.
- TimePicker behavior doesn't exactly match UWP
- `TimePickerFlyout.TimePicked` event is not implemented
- TimePicker's `SelectedTime`, `TimeChanged`, and `SelectedTimeChanged` events are now implemented.
- Misc changes to match UWP
- `TimePickerFlyout.TimePicked` event is now implemented
> feat!: Implement TimePicker's SelectedTime/TimeChanged/SelectedTimeChanged

- .vsts-ci.yml
- build/SignClient.json
- build/Uno.UI.Build.csproj
- src/SamplesApp/SamplesApp.iOS/SamplesApp.iOS.csproj
- src/Uno.UI/Controls/Window.iOS.cs
- src/Uno.UI/FeatureConfiguration.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/MultilineTextBoxView.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/SinglelineTextBoxView.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.iOS.cs
GitHub Issue: https://github.com/unoplatform/uno/issues/9430
> Backport #9559 and #9484 for 3.7.x

- .vsts-ci.yml
- build/SignClient.json
- build/Uno.UI.Build.csproj
- build/ci/.azure-devops-unit-tests.yml
- src/SamplesApp/SamplesApp.iOS/SamplesApp.iOS.csproj
- src/Uno.UI/Controls/Window.iOS.cs
- src/Uno.UI/FeatureConfiguration.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/MultilineTextBoxView.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/SinglelineTextBoxView.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.iOS.cs
GitHub Issue: https://github.com/unoplatform/uno/issues/9430
> Backport #9559 and #9484 for 3.6.x

- src/Uno.Analyzers.Tests/Uno.Analyzers.Tests.csproj
- src/Uno.Analyzers.Tests/WasmHttpHandlerDeprecatedTests.cs
- src/Uno.Analyzers/Uno.Analyzers.csproj
- src/Uno.Analyzers/WasmHttpHandlerDeprecatedAnalyzer.cs
GitHub Issue (If applicable): closes #9665
> feat: Implement analyzer for deprecated WasmHttpHandler

- doc/articles/get-started-vscode.md
GitHub Issue (If applicable): no Issue
Both [launch.json](https://github.com/unoplatform/uno/blob/master/src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-net6/.vscode/launch.json)  and
[tasks.json] (https://github.com/unoplatform/uno/blob/master/src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-net6/.vscode/tasks.json) currently  leads to a 404 page.
The new links  [launch.json](https://github.com/unoplatform/uno/blob/master/src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp/.vscode/launch.json) and [tasks.json](https://github.com/unoplatform/uno/blob/master/src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp/.vscode/tasks.json) are liked to the right documentation
Please check if your PR …
> docs: fixed vscode file links

- .vsts-ci.yml
- build/SignClient.json
- build/Uno.UI.Build.csproj
- src/Uno.UI/Controls/Window.iOS.cs
- src/Uno.UI/FeatureConfiguration.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/MultilineTextBoxView.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/SinglelineTextBoxView.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.iOS.cs
GitHub Issue: https://github.com/unoplatform/uno/issues/9430
> Backport #9559 and #9484 for 3.8.x

- .vsts-ci.yml
- build/SignClient.json
- build/Uno.UI.Build.csproj
- src/Uno.UI/Controls/Window.iOS.cs
- src/Uno.UI/FeatureConfiguration.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/MultilineTextBoxView.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/SinglelineTextBoxView.iOS.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.iOS.cs
GitHub Issue: https://github.com/unoplatform/uno/issues/9430
> Backport #9559 and #9484 for 3.10.x

- src/SamplesApp/SamplesApp.Droid/Properties/AndroidManifest.xml
AndroidManifest.xml //uses-sdk/@android:minSdkVersion '16' is less than API-19
- Bugfix
> fix(SamplesApp): warning XA4216

- src/Uno.UI/UI/Xaml/Input/FocusManager.mux.static.cs
> chore: Remove outdated TODO

- src/SamplesApp/SamplesApp.UITests/TestFramework/ImageAssert.ExpectedPixels.cs
> fix: IndexOutOfRangeException ExpectedPixels.Pixels(_Bitmap)

- src/Uno.UWP/UI/Text/FontWeights.cs
GitHub Issue (If applicable): closes #9377
> fix: Fix `FontWeights.SemiLight` and minor refactoring

- src/SamplesApp/SamplesApp.UITests/Extensions/QueryExtensions.cs
- src/SamplesApp/SamplesApp.UITests/Microsoft_UI_Xaml_Controls/NumberBoxTests/Given_NumberBox.Uno.cs
- src/SamplesApp/SamplesApp.UITests/Microsoft_UI_Xaml_Controls/NumberBoxTests/Given_NumberBox.cs
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/NumberBoxTests/NumberBoxPage.xaml
- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/NumberBoxTests/NumberBoxPage.xaml.cs
- src/Uno.UI.RuntimeTests/MUX/Microsoft_UI_Xaml_Controls/NumberBox/NumberBoxTests.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/NumberBox/MathToken.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/NumberBox/MathTokenType.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/NumberBox/NumberBox.Properties.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/NumberBox/NumberBox.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/NumberBox/NumberBoxAutomationPeer.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/NumberBox/NumberBoxParser.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/NumberBox/NumberBox_themeresources_v1.xaml
- src/Uno.UI/Microsoft/UI/Xaml/Controls/NumberBox/NumberBox_v1.xaml
GitHub Issue (If applicable): closes #7123, closes #3851
> fix: Add NumberBox updates from WinUI back

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TextBoxTests/TextBoxTests.cs
- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_Visibility.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/TextBox/TextBox_Visibility.xaml.cs
- src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs
GitHub Issue (If applicable): closes #9678
> Fix TextBox visibility not taking effect

- src/Uno.UI.RemoteControl.Server.Processors/HotReload/MetadataUpdates/CompilationWorkspaceProvider.cs
> fix: Warnings SYSLIB0012

- .editorconfig
Spaces are taken into account for file name. I also extracted the common `*.` out, but the main fix is removing spaces after `,`
> chore: Remove extra spaces in .editorconfig

- src/SamplesApp/SamplesApp.Shared/App.xaml.cs
- src/SamplesApp/SamplesApp.Skia.Gtk/Program.cs
- src/SamplesApp/SamplesApp.Skia.Gtk/SamplesApp.Skia.Gtk.csproj
- src/SamplesApp/SamplesApp.Skia/SamplesApp.Skia.csproj
- src/Uno.UI.Runtime.Skia.Gtk/GLRenderSurfaceBase.OpenGLES.cs
- src/Uno.UI.Runtime.Skia.Gtk/GLValidationSurface.cs
- src/Uno.UI.Runtime.Skia.Gtk/GtkHost.cs
- src/Uno.UI.Runtime.Skia.Gtk/OpenGLESRenderSurface.cs
- src/Uno.UI.Runtime.Skia.Gtk/OpenGLRenderSurface.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/discussions/9694, closes https://github.com/unoplatform/uno/issues/9099, closes https://github.com/unoplatform/uno/issues/9506
- Bugfix
- Feature
- ci: Disable trimming generation for net6 mobile targets
- test: Add GTK host information logging
- ci: Remove unused arm-linux dependency
- chore: Fix debug only validation for OpenGL/Gtk
- feat: Improve automatic OpenGL/ES detection
- ci: Remove unused Uno.CodeGen dependency for build performance
> feat: Improve automatic OpenGL/ES detection

- .editorconfig
- src/SourceGenerators/System.Xaml/System.Xaml/XamlSchemaContext.cs
- src/Uno.UI/DirectUI/JoltCollections.h.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/PullToRefresh/ScrollViewerIRefreshInfoProviderAdapter/RefreshInfoProviderImpl.cs
- src/Uno.UI/Microsoft/UI/Xaml/Controls/RatingControl/RatingControl.cs
- src/Uno.UI/UI/Xaml/Controls/NavigationView/NavigationView.cs
- src/Uno.UI/UI/Xaml/Controls/NavigationView/NavigationViewItem.cs
- src/Uno.UI/UI/Xaml/Controls/Primitives/LoopingSelector/LoopingSelectorItemAutomationPeer_Partial.h.cs
- src/Uno.UI/UI/Xaml/Controls/Primitives/LoopingSelector/LoopingSelectorItem_Partial.h.cs
GitHub Issue (If applicable): Part of https://github.com/unoplatform/uno/issues/6882
> perf: Enable CA1821 (Remove empty finalizers)

- src/Uno.UI/UI/Xaml/Style/mergedstyles.xaml
> chore: Merged styles for `NumberBox`

- src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Views/Controls/SampleChooserCategory.cs
Error compiling WASM locally.
No error.
> chore: Add operators for SampleChooserCategory to satisfy CA1036

- doc/articles/uno-development/troubleshooting-source-generation.md
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/9627
> docs: Add more details about `XamlGeneratorAnalyzerSuppressions`

- src/Uno.UI.Foldable/Uno.UI.Foldable.csproj
- src/Uno.UI.Toolkit/Uno.UI.Toolkit.csproj
One is already included from [Uno.CrossTargetting.props](https://github.com/unoplatform/uno/blob/09ef19fe7fabdeb5f24016fc19dc6a899a51d03b/src/Uno.CrossTargetting.props#L118-L120), second is already included unconditionally in the same csproj
> build: Fix two NU1504 (duplicate PackageReference) warnings

- doc/import_external_docs.ps1
> docs: Update Figma Documentation

- src/SourceGenerators/XamlGenerationTests.Core/XamlGenerationTests.Core.csproj
- src/SourceGenerators/XamlGenerationTests/XamlGenerationTests.csproj
- src/Uno.CrossTargetting.props
- src/Uno.UI.BindingHelper.Android/Uno.UI.BindingHelper.Android.csproj
- src/Uno.UI.BindingHelper.Android/Uno.UI.BindingHelper.Android.net6.csproj
- src/Uno.UI.Toolkit/Uno.UI.Toolkit.csproj
> fix: Warnings NU1504 The duplicate 'PackageReference' items are: Xamarin.Build.Download 0.11.3

- doc/articles/features/using-skia-gtk.md
- src/Uno.UI.Runtime.Skia.Gtk/GLValidationSurface.cs
> fix(gtk): Fallback on software rendering when GL Context is not available

- doc/articles/migrating-from-previous-releases.md
> docs: Icon font migration

- src/Uno.UI.Runtime.Skia.Gtk/UI/Xaml/Controls/TextBoxViewExtension.cs
GitHub Issue (If applicable): closes #9258
> fix(Gtk): Match TextBox caret color with foreground color

- build/ci/.azure-devops-unit-tests.yml
I'm not sure of the cause, but this fix is something I found on stackoverflow. So let's try it :)
> ci: Fix DiscoveryMessage errors on CI

- .editorconfig
- src/Directory.Build.props
- src/Uno.UI.Dispatching/Core/CoreDispatcher.wasm.cs
- src/Uno.UI/Controls/NSFontHelper.macOS.cs
- src/Uno.UI/Controls/UIFontHelper.iOS.cs
- src/Uno.UI/UI/Xaml/Media/PointCollection.cs
- src/Uno.UWP/UI/Color.wasm.cs
> build: Be more specific about code analysis rules

- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp/UnoWinUIQuickStart-vsmac.slnf
- src/SolutionTemplate/UnoSolutionTemplate.WinUI.net6/Skia.Linux.FrameBuffer/Program.cs
- Bugfix
- Adjust the mac solution filter
- Adjust for missing namespaces in vsix framebuffer template
> Misc template fixes

- src/Uno.UI.Tests/Uno.UI.Tests.csproj
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/Given_XamlReader.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/TestCustomResourceLoader.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XamlReaderTests/When_CustomResource.xamltest
- src/Uno.UI/UI/Xaml/Markup/Reader/XamlObjectBuilder.cs
GitHub Issue (If applicable): closes #749
> feat(xamlreader): Support CustomResource

- src/Uno.UWP/Storage/StorageFile.saf.Android.cs
GitHub Issue (If applicable): closes #9616
- Bugfix
> fix(StorageFile): StorageFile return path without content provider

- src/SourceGenerators/Uno.UI.SourceGenerators.net6.Tests/DependencyObjectGeneratorTests/Given_DependenyObjectGenerator.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/DependencyObject/DependencyObjectGenerator.Diagnostics.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/DependencyObject/DependencyObjectGenerator.cs
> fix: Avoid throwing in DependencyObjectGenerator when using Roslyn

- .editorconfig
- src/Directory.Build.props
- src/Uno.UI.Tests.ViewLibraryProps/Uno.UI.Tests.ViewLibraryProps.csproj
- src/Uno.UI/UI/Xaml/Media/AcrylicBrush/Android/AndroidStockBlur.Android.cs
> chore(deps): Update NetAnalyzers to latest preview and disable for test projects

- src/Uno.UI.Toolkit/ElevatedView.Android.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/9783
> fix: Properly scale shadow on Android

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml/DragAndDropTests/DragDrop_Basics_Automated.cs
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml/DragAndDropTests/DragDrop_Nested_Automated.cs
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/SwipeControlTests/SwipeControlTests.cs
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TextBlockTests/TextBlockTests.cs
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/Capture_Tests.cs
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Media_Imaging/RenderTargetBitmap_Tests.cs
GitHub Issue (If applicable): closes #9798
> test: Fix incorrect usages of ActivePlatforms

- src/Directory.Build.props
Sorry, @jeromelaban. Looks like I got the logic wrong in the previous PR
> build: Fix `UnoDisableNetAnalyzers` logic

- src/Uno.UI.RemoteControl.VS/Uno.UI.RemoteControl.VS.csproj
GitHub Issue (If applicable): The Workspaces dependency for these analyzers was removed in https://github.com/microsoft/vs-threading/pull/425/
> build: Remove workaround for issue that was fixed

- build/ci/.azure-devops-skia-tests.yml
GitHub Issue (If applicable): I'm seeing https://github.com/unoplatform/uno/issues/9788 in Skia builds. I'm not sure if it can help to get a binary log for a failing build. But I think it doesn't harm.
No binlogs in artifacts
> ci: Generate binary logs for Skia builds (Gtk & WPF)

- src/SamplesApp/UITests.Shared/Microsoft_UI_Xaml_Controls/TreeView/TreeViewPage.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_Devices/Midi/MidiDeviceInput.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ListView/ListViewChangeViewArbitrary.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/Models/ListViewViewModel.cs
> fix: Avoid build error due to Append(string)

- doc/articles/features/ElevatedView.md
- doc/articles/migrating-from-previous-releases.md
> docs: Add migration docs for `ElevatedView`, remove for icon font

- src/SamplesApp/SamplesApp.UITests/SampleControlUITestBase.cs
- src/SamplesApp/SamplesApp.UITests/TestFramework/ActivePlatformsAttribute.cs
- src/SamplesApp/SamplesApp.UITests/TestFramework/CallerArgumentExpressionAttribute.cs
- src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.Skia.csproj
- src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.Wasm.csproj
- src/Uno.UI.RuntimeTests/Uno.UI.RuntimeTests.csproj
GitHub Issue (If applicable): Related to https://github.com/unoplatform/uno/issues/9798, I expect the exceptions I added to be thrown as long as https://github.com/unoplatform/uno/pull/9799 is not yet merged
> test: Ensure tests are using ActivePlatforms correctly

- src/SourceGenerators/Uno.UI.SourceGenerators/Uno.UI.SourceGenerators.csproj
Workspaces dependency isn't needed, and actually using types from it in analyzers/generators might cause some issues.
> build: Remove MS.CA.Workspaces references from SourceGenerators project

- src/SamplesApp/UITests.Shared/UITests.Shared.projitems
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/PasswordBoxTests/PasswordBoxPage.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/PasswordBoxTests/PasswordBox_AutoFill.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/PasswordBoxTests/PasswordBox_AutoFill.xaml.cs
- src/Uno.UI/WasmCSS/Uno.UI.css
GitHub Issue (If applicable): closes #8046
> Avoid WebKit autofill highlighting

- src/Directory.Build.targets
- src/SourceGenerators/Uno.UI.SourceGenerators/Uno.UI.SourceGenerators.csproj
- src/Uno.UI/UI/Xaml/Hosting/ElementCompositionPreview.cs
- src/Uno.UWP/Devices/Sensors/SimpleOrientationSensorOrientationChangedEventArgs.cs
- src/Uno.UWP/Graphics/Display/BrightnessOverride.cs
- src/roslyn-override.targets
This is to get a baseline for generators performance to compare with https://github.com/unoplatform/uno/pull/9820/
This is how it looks in binlog:
> build: Show generator summary

- src/Uno.UI/UI/Xaml/Style/mergedstyles.xaml
Checking in some missing mergedstyles changes to avoid the file change in git
> chore: Missing mergedstyles changes

- src/Uno.UI.Runtime.Skia.Gtk/UI/Xaml/Controls/TextBoxViewExtension.cs
GitHub Issue (If applicable): closes #9851
- Bugfix
- `CssProvider` for all `TextBoxViews` is removed when not used
- `Foreground` is updated to reflect current value for multi-line `TextBox`
> fix: `TextBox.Foreground` setting on Skia GTK

- src/SourceGenerators/Uno.UI.SourceGenerators/Helpers/RoslynMetadataHelper.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileDefinition.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileParser.Cache.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileParser.cs
GitHub Issue (If applicable): closes #9716
- Performance
> perf: Cache XAML parsing

- src/SamplesApp/SamplesApp.Wasm/SamplesApp.Wasm.csproj
Wasm SamplesApp fails to build locally due to NU1504.
> build: Fix NoWarn to avoid getting NU1504

- src/Directory.Build.props
- src/SamplesApp/SamplesApp.UITests.Generator/Uno.Samples.UITest.Generator.csproj
- src/SamplesApp/SamplesApp.UITests/SamplesApp.UITests.csproj
- src/SolutionTemplate/UnoSolutionTemplate.VSIX.2022/UnoSolutionTemplate.VSIX.2022.csproj
- src/SourceGenerators/XamlGenerationTests/XamlGenerationTests.csproj
- src/Uno.UI.Tests.Performance/Uno.UI.Tests.Performance.csproj
- src/Uno.WinUIRevert/Uno.WinUIRevert.csproj
> build: Update to C# 11

- doc/articles/features/windows-ui-xaml-xbind.md
Corrected link to WinUI x:Bind documentation
Link currently points to x:Load documentation which is not related to this topic.
Link now correctly points to the x:Bind topic
> docs: fix link to WinUI x:Bind documentation

- doc/articles/debugging-wasm.md
See https://github.com/unoplatform/uno/discussions/9888#discussioncomment-3681546
> docs: Update solution templates link

- doc/import_external_docs.ps1
> docs: update figma-docs commit

- src/SourceGenerators/Uno.UI.SourceGenerators/Content/Uno.UI.SourceGenerators.props
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
GitHub Issue (If applicable): closes #9874
> chore: Cleanup unused 'OutputSourceComments'

- src/SourceGenerators/Uno.UI.SourceGenerators/Helpers/SymbolExtensions.cs
Ports https://github.com/CommunityToolkit/dotnet/pull/447 :)
> perf: Reduce string allocations in `GetFullMetadataNameForFileName`

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_ToolTip.cs
- src/Uno.UI/UI/Xaml/Controls/Popup/Popup.Base.cs
- src/Uno.UI/UI/Xaml/Controls/ToolTip/ToolTip.cs
GitHub Issue (If applicable): closes #9570
> Propagate DataContext from ToolTip to Popup

- src/Uno.UI/UI/Xaml/Internal/RootVisual.cs
- src/Uno.UI/UI/Xaml/UIElement.Pointers.wasm.cs
GitHub Issue (If applicable): closes #8042
> fix(Wasm): Fix DoubleTapped not firing with touch

- src/Directory.Build.targets
- src/SamplesApp/SamplesApp.UITests.Generator/SamplesListGenerator.cs
- src/SamplesApp/SamplesApp.UITests.Generator/Uno.Samples.UITest.Generator.csproj
- src/SamplesApp/SamplesApp.UITests/SamplesApp.UITests.csproj
GitHub Issue (If applicable): Part of #9926
> perf: Make SamplesListGenerator an incremental generator

- .editorconfig
There are lots of warnings from these analyzers. They don't break the build, but are quite annoying.
If we want to enable them back, the violations must be fixed.
> chore: Disable CA1848 and CA1838

- src/Directory.Build.props
- src/SamplesApp/SamplesApp.UITests/TestFramework/ImageAssert.ExpectedPixels.cs
- src/SolutionTemplate/UnoSolutionTemplate.Wizard.2022/UnoSolutionWizard.cs
- src/Uno.NUnitTransformTool/Program.cs
- src/Uno.UI.RemoteControl.Server.Processors/Helpers/ProcessHelper.cs
- src/Uno.UI.RemoteControl.Server.Processors/HotReload/ServerHotReloadProcessor.MetadataUpdate.cs
- src/Uno.WinUIRevert/Program.cs
> build: Treat nullable warnings as errors [including samples/test]

- build/test-scripts/ios-uitest-build.sh
> ci: Produce a binlog for iOS SamplesApp build

- src/Directory.Build.props
See https://github.com/unoplatform/uno/pull/9948#issuecomment-1258534159 for info
This warning is a serious one, and should be treated as error.
> build: Treat CS8032 as error

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.Telemetry.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs
See https://github.com/dotnet/roslyn-analyzers/issues/6185 for info why this is bad.
> build: Avoid `Console.Write` in generators

- src/Uno.CrossTargetting.props
- src/Uno.UI.Maps/MapPresenter.Android.cs
- src/Uno.UI.Maps/MapPresenter.iOS.cs
- src/Uno.UI.Runtime.Skia.Tizen/TizenCoreWindowExtension.cs
- src/Uno.UI.Runtime.Skia.Tizen/TizenHost.cs
- src/Uno.UI.Runtime.Skia.Wpf/Extensions/Storage/Pickers/FolderPickerExtension.cs
- src/Uno.UI.RuntimeTests/IntegrationTests/dxaml/SafeEventRegistration.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement_And_Leak.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_xLoad.cs
- src/Uno.UI.RuntimeTests/UITests/_Engine/SkiaApp.cs
- src/Uno.UI.Toolkit/ElevatedView.Android.cs
- src/Uno.UI/Extensions/ViewExtensions.netstd.cs
- src/Uno.UI/UI/Xaml/FontFamilyLoader.wasm.cs
- src/Uno.UI/UI/Xaml/HtmlElementHelper.wasm.cs
- src/Uno.UI/UI/Xaml/Media/GeometryGroup.wasm.cs
- src/Uno.UWP/Storage/Helpers/AssetsPathBuilder.wasm.cs
In some cases, this was re-assigning `WarningsAsErrors` from an old correct value to a new invalid value, causing some diagnostics to show as warning instead of error.
> build: Remove invalid `WarningsAsErrors` value

- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/FlipViewPages/FlipViewTemplateSelector.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/FlipViewPages/FlipView_TemplateSelectorPage.xaml
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/FlipViewPages/FlipView_TemplateSelectorPage.xaml.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_FlipView.cs
related to https://github.com/unoplatform/uno/issues/9341
> test: (FlipView) Add runtime test for template selector

- src/SourceGenerators/Uno.UI.SourceGenerators/BindableTypeProviders/BindableTypeProvidersGenerationTask.cs
GitHub Issue (If applicable): closes #9980
Review with "Hide whitespaces" for easier-to-read diff
> fix(BindableTypeProvidersGenerator): Generate suppressions

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
> perf: Use hash set for resource key lookup

- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/ApplicationTests/Given_Application.xaml
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/ApplicationTests/Given_Application.xaml.cs
- src/Uno.UI.Runtime.Skia.Gtk/Extensions/ApplicationModel/Core/CoreApplicationExtension.cs
- src/Uno.UI.Runtime.Skia.Gtk/GtkApplicationExtension.cs
- src/Uno.UI.Runtime.Skia.Gtk/GtkHost.cs
- src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/ApplicationExtension.cs
- src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/Extensions/ApplicationModel/Core/CoreApplicationExtension.cs
- src/Uno.UI.Runtime.Skia.Linux.FrameBuffer/FramebufferHost.cs
- src/Uno.UI.Runtime.Skia.Wpf/Extensions/ApplicationModel/Core/CoreApplicationExtension.cs
- src/Uno.UI.Runtime.Skia.Wpf/WpfApplicationExtension.cs
- src/Uno.UI.Runtime.Skia.Wpf/WpfHost.cs
- src/Uno.UI/UI/Xaml/Application.Android.cs
- src/Uno.UI/UI/Xaml/Application.cs
- src/Uno.UI/UI/Xaml/Application.macOS.cs
- src/Uno.UI/UI/Xaml/Application.skia.cs
- src/Uno.UI/UI/Xaml/IApplicationExtension.cs
- src/Uno.UWP/ApplicationModel/Core/CoreApplication.Android.cs
- src/Uno.UWP/ApplicationModel/Core/CoreApplication.cs
- src/Uno.UWP/ApplicationModel/Core/CoreApplication.macOS.cs
- src/Uno.UWP/ApplicationModel/Core/CoreApplication.skia.cs
- src/Uno.UWP/ApplicationModel/Core/ICoreApplicationExtension.cs
- src/Uno.UWP/Generated/3.0.0.0/Windows.ApplicationModel.Core/CoreApplication.cs
GitHub Issue (If applicable): closes #9999, closes #9994
- Feature
Not supported.
Supported.
> feat: Support for `CoreApplication.Exit` and `Exiting`

- doc/import_external_docs.ps1
> docs: update uno.check docs ref

- doc/articles/features/windows-ui-xaml-xbind.md
- src/SourceGenerators/Uno.UI.SourceGenerators.Tests.Shared/Given_XBindRewriter.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/Utils/XBindExpressionParser.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.Reflection.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/xBind_AttachedProperty.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Controls/xBind_AttachedProperty.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Data/xBindTests/Given_xBind_Binding.cs
**_This PR needs https://github.com/unoplatform/uno/pull/10013 to be merged first_**
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/7893
- Feature
Support for [attached properties path in x:Bind](https://learn.microsoft.com/en-us/windows/uwp/xaml-platform/x-bind-markup-extension#attached-properties)
> feat(xBind): Add attached properties path support

- src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewModel.cs
- Loads and saves favorites and recents list from local storage on  non-reference .NET Standard platforms. This includes WASM and Skia targets.
- Asynchronously loads the favorites and recents list on startup.
GitHub Issue (If applicable): closes #9534
- Bugfix
Favorite and recent samples in Samples app are not persisted over launches on Skia and WASM targets.
Favorite and recent samples in Samples app **are** persisted over launches on Skia and WASM targets.
The lists will start to load asynchronously on application startup.
> fix(SamplesApp): Favorites list loading

- src/Directory.Build.props
- src/SamplesApp/SamplesApp.UITests/Extensions/AppExtensions.cs
- src/SamplesApp/UnoIslands.Shared/App.xaml.cs
- src/SamplesApp/UnoIslands.WPF/MainWindow.xaml.cs
- src/Uno.UI.RemoteControl.Server.Processors/HotReload/MetadataUpdates/WatchHotReloadService.cs
- src/Uno.UI.RemoteControl.Server.Processors/HotReload/ServerHotReloadProcessor.MetadataUpdate.cs
- src/Uno.UI.XamlHost.Skia.Wpf/UnoXamlHostBase.host.cs
> build: Treat CS0169 (private field not used) as error

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/CanvasTests/Canvas_Measurement_Tests.cs
- src/Uno.UI.RuntimeTests/Helpers/ImageAssert.cs
- src/Uno.UI.RuntimeTests/Helpers/RawBitmap.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement_Opacity.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Canvas/Canvas_In_Canvas.xaml
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Canvas/Canvas_In_Canvas.xaml.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Canvas/Canvas_With_Outer_Clip.xaml
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Canvas/Canvas_With_Outer_Clip.xaml.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Canvas/Canvas_ZIndex.xaml
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Canvas/Canvas_ZIndex.xaml.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Canvas/Measure_Children_In_Canvas.xaml
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Canvas/Measure_Children_In_Canvas.xaml.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Given_Canvas_Measurement.cs
Issue: #9811
All the Canvas_Measurement tests are in Sample App  in uno\src\SamplesApp\SamplesApp.UITests\Windows_UI_Xaml_Controls\CanvasTests\Canvas_Measurement_Tests.cs
Some section of Verify_Canvas_ZIndex() are not running in Android.
The test Measure_CanvasChildren have been completely moved to Runtime Tests in 
uno\src\Uno.UI.RuntimeTests\Tests\Windows_UI_Xaml_Controls. For Wasm the other test are still running in Sample app. For the other platform it has been moved to  the same repository. The xaml files of the test have been left in Sample test shared 
uno\src\SamplesApp\UITests.Shared\Windows_UI_Xaml_Controls and have been copied and sometimes lightly modified in  
uno\src\Uno.UI.RuntimeTests\Tests\Windows_UI_Xaml_Controls/Canvas.
The …
> chore(test): Move Canvas_Mesurement test to Runtime

- doc/articles/get-started-vscode.md
Some old references into docs.
Updated the commands and text to match the current behavior of the tooling.
> Update VSCode docs

- src/Uno.UWP/Storage/StorageFile.iOS.cs
- src/Uno.UWP/Storage/StorageFolder.iOS.cs
> fix: Nullable errors on iOS

- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.Reflection.cs
- src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs
- src/Uno.UI.Tests/ResourceLoader/Strings/en/Resources.Designer.cs
- src/Uno.UI.Tests/ResourceLoader/Strings/en/Resources.resw
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XUidTests/Controls/When_XUid_And_AttachedProperty_And_Conversion.xaml
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XUidTests/Controls/When_XUid_And_AttachedProperty_And_Conversion.xaml.cs
- src/Uno.UI.Tests/Windows_UI_Xaml_Markup/XUidTests/Given_xUid.cs
- Bugfix
Fixes implicit attached property localization type conversion.
> fix(localization): Fix type conversion on attached property implicit localization

- src/Uno.UWP/Buffer/DefaultArrayPool.cs
> refactor: Simplify DefaultArrayPool

- .vsts-ci.yml
This is generally slower than a normal nuget restore, particularly around the time of this commit.
> ci: disable nuget ci cache

- .editorconfig
> chore: Specify `tab_width`  and `indent_size` for all xml-based extensions

- src/SamplesApp/SamplesApp.Wasm/SamplesApp.Wasm.csproj
- src/Uno.UI.Tests/Uno.UI.Tests.csproj
> chore: Remove unnecessary NoWarn

- src/SolutionTemplate/UnoSolutionTemplate.Wizard.2019/NuGet-netcore.config
- src/SolutionTemplate/UnoSolutionTemplate.Wizard.2022/NuGet-netcore.config
GitHub Issue (If applicable): closes #10101
I guess this is best we can do for this issue. @jeromelaban Thoughts?
Also I'm not sure why these feeds were added previously. Were we using prerelease versions from this feeds at some point and this no longer holds? Will see if CI passes.
> fix: Update nuget.config for solution templates

- doc/articles/features/windows-applicationmodel-datatransfer.md
The ``ShowShareUI`-Method is to be called on the class, not in the instance. Related to [#490](https://github.com/unoplatform/Uno.Gallery/issues/490).
GitHub Issue (If applicable): [#490](https://github.com/unoplatform/Uno.Gallery/issues/490)
> fix: Wrong sample-code for Sharing stuff

- src/Directory.Build.props
- src/SamplesApp/SamplesApp.UITests/BenchmarkDotNetTests.cs
- src/Uno.UI.RuntimeTests/IntegrationTests/dxaml/controls/calendarview/CalendarViewAutomationPeerIntegrationTests.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Core/Given_CoreDispatcher.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_FrameworkElement_EffectiveViewport.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml/Given_UIElement.TransformToVisual.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Controls/Repeater/Given_ItemsRepeater.cs
> build: Treat CS0168 (variable not used) as error

- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-uwp-net6/.template.config/template.json
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-uwp/.template.config/template.json
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-winui-xamarin/.template.config/template.json
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp/.template.config/template.json
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unolib-crossruntime/.template.config/template.json
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unolib/.template.config/template.json
- src/SolutionTemplate/UnoLibraryTemplate.net6/CrossTargetedLibrary.Net6.vstemplate
- src/SolutionTemplate/UnoLibraryTemplate/CrossTargetedLibrary.vstemplate
- src/SolutionTemplate/UnoSolutionTemplate.WinUI.net6/UnoApp.net6.vstemplate
- src/SolutionTemplate/UnoSolutionTemplate.net6/UnoApp.net6.vstemplate
- src/SolutionTemplate/UnoSolutionTemplate/UnoApp.vstemplate
- The main templates mention targeting WinUI, which may be confused with WinUI 2
- Uno Library template uses "Xamarin|UWP" and Uno App template uses "UWP|Xamarin"
- Mentioning "Windows App SDK" as target
- Keeping the same order for UWP templates
> chore: Small template adjustments

- doc/articles/features/lightsensor.md
- doc/articles/toc.yml
GitHub Issue (If applicable): [#477](https://github.com/unoplatform/Uno.Gallery/issues/477)
There is no documentation about `LightSensor`.
There is now a documentation about `LightSensor`.
> feat: Add documentation for `LightSensor`

- src/Directory.Build.props
- src/SamplesApp/SamplesApp.UITests/Extensions/QueryExtensions.cs
- src/SamplesApp/SamplesApp.UITests/SampleControlUITestBase.cs
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml/UIElementTests/UIElementTests.cs
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/BorderTests/Border_Tests.cs
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/CommandBarTests/UnoSamples_Tests.NativeCommandBar.cs
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ContentDialog/UnoSamples_Tests.ContentDialog.cs
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/TextBoxTests/TextBoxTests.cs
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ToolTipTests/ToolTip_Tests.cs
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Input/ScrollViewer_Pointer_Tests.cs
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Media_Animation/ColorAnimation_Tests.cs
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Media_Animation/DoubleAnimation_Tests.TransformGroup.cs
- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Shapes/Shapes_Tests.cs
- src/SamplesApp/UITests.Shared/Windows_ApplicationModel/DataTransfer/DataTransferManagerTests.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Input/PointersTests/HitTest_Clipping.xaml.cs
- src/SamplesApp/UITests.Shared/Windows_UI_Xaml/DragAndDrop/DragDrop_TestPage.xaml.cs
- src/SolutionTemplate/UnoSolutionTemplate.VSIX/UnoPlatformPackage.cs
- src/Uno.UI.RuntimeTests/Tests/Windows_UI_Xaml_Automation/Given_AutomationPeer.cs
GitHub Issue (If applicable): closes #10059
> test: Avoid using obsolete GetRect methods

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Media_Animation/DoubleAnimation_Tests.FinalState_Opacity.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/9080
- CI
> test: Disable flaky When_Opacity_Paused_With_FillBehaviorStop_Then_Hold on android

- .vsts-ci-docs.yml
- .vsts-ci.yml
- build/Uno.UI.Build.csproj
- build/ci/.azure-devops-docs.yml
- build/ci/.azure-devops-package-generic.yml
- build/ci/.azure-devops-package-net6-win.yml
- build/ci/.azure-devops-package-reference.yml
- build/ci/.azure-devops-package-skia.yml
- build/ci/.azure-devops-package-wasm.yml
- src/crosstargeting_override.props.sample
> ci: Apply workaround to avoid targets caching by msbuild

- src/SolutionTemplate/UnoSolutionTemplate.WinUI.net6/Server/UnoQuickStart.Server.csproj
- Bugfix
Currently the `DevServer` package was used in the `Server` template
`Server` package is used
> fix: Reference Bootstrap.Server package for Server project

- src/Uno.CrossTargetting.props
> build: More `NoWarn` adjustments

- src/SourceGenerators/Uno.UI.SourceGenerators/Uno.UI.SourceGenerators.csproj
> build: Delete incorrect `WarningsAsErrors`

- src/SamplesApp/UnoIslands.Skia/UnoIslands.Skia.csproj
- src/SamplesApp/UnoIslands.WPF/UnoIslands.Skia.Wpf.csproj
- src/Uno.UWPSyncGenerator.Reference/Uno.UWPSyncGenerator.Reference.csproj
> build: Fix MSB4011 (duplicate props import) and NU1504 (duplicate PackageReference)

- doc/articles/features/windows-phone-devices-notification-vibrationdevice.md
GitHub Issue (If applicable): Related to [472](https://github.com/unoplatform/Uno.Gallery/issues/472)
If one adds the `VibrationDevice`-class to a UWP-head it won't compile without some additions.
The documentation now mentions the necessary Extension.
> docs: Add info about necessary UWP-extension for `VibrationDevice`

- src/SolutionTemplate/UnoSolutionTemplate/Droid/UnoQuickStart.Droid.csproj
- src/SolutionTemplate/UnoSolutionTemplate/Skia.Gtk/UnoQuickStart.Skia.Gtk.csproj
- src/SolutionTemplate/UnoSolutionTemplate/Skia.Linux.FrameBuffer/UnoQuickStart.Skia.Linux.FrameBuffer.csproj
- src/SolutionTemplate/UnoSolutionTemplate/Skia.Tizen/UnoQuickStart.Skia.Tizen.csproj
- src/SolutionTemplate/UnoSolutionTemplate/Skia.WPF.Host/UnoQuickStart.Skia.Wpf.Host.csproj
- src/SolutionTemplate/UnoSolutionTemplate/Skia.WPF/UnoQuickStart.Skia.WPF.csproj
- src/SolutionTemplate/UnoSolutionTemplate/UWP/UnoQuickStart.Uwp.csproj
- src/SolutionTemplate/UnoSolutionTemplate/Wasm/UnoQuickStart.Wasm.csproj
- src/SolutionTemplate/UnoSolutionTemplate/iOS/UnoQuickStart.iOS.csproj
- src/SolutionTemplate/UnoSolutionTemplate/macOS/UnoQuickStart.macOS.csproj
On the UWP solution template users cannot use C# 10 features 
Many C# 10 features are usable in UWP too, so defaulting to `latest`
> feat: Default to C# latest on UWP app solution template

- src/Uno.UI/ts/Windows/Graphics/Display/DisplayInformation.ts
- src/Uno.UWP/Graphics/Display/DisplayInformation.unsupported.cs
- src/Uno.UWP/Graphics/Display/DisplayInformation.wasm.cs
GitHub Issue (If applicable): closes #10049
- Feature
- [This PR](https://github.com/unoplatform/uno/pull/10042/files) got merged despite unresolved Codacy warnings.
- `DisplayInformation.NativeOrientation` is marked as unimplemented on WASM.
- Fixed Codacy warnings (I could not fix as part of the previous pull request because it has already been merged).
- Implemented `DisplayInformation.NativeOrientation` for WASM.
> [WASM] More DisplayInformation improvements

- src/Uno.Docs.InlineTOCGenerator/Uno.Docs.InlineTOCGenerator.csproj
- src/Uno.ReferenceImplComparer/Uno.ReferenceImplComparer.csproj
- src/Uno.WinUIRevert/Uno.WinUIRevert.csproj
I assume this doesn't affect external consumers of Uno.
> chore(deps): Update internal tools from net5.0 to net6.0

- src/SolutionTemplate/UnoSolutionTemplate.Wizard.2022/Forms/UnoOptions.cs
- src/SolutionTemplate/UnoSolutionTemplate.Wizard.2022/Forms/UnoWasmOptions.cs
Fix after warnings as errors changes.
> ci: Adjust for template errors

- .github/labeler.yml
> ci: Fix labeler.yml labels

- src/SamplesApp/SamplesApp.Wasm/SamplesApp.Wasm.csproj
This change lets the `WarningsAsErrors` defined in `Directory.Build.props` take place:
https://github.com/unoplatform/uno/blob/7abab4d82580b9ea98d43236539d5892a77c6b05/src/Directory.Build.props#L187
> build: Remove empty `WarningsAsErrors` in `SamplesApp.Wasm`

- .github/workflows/labeler.yml
The labeler is never run and has been broken for long.
It should work properly now.
> ci: Fix PR labeler workflow

- .github/labeler.yml
All platform labels are `platform/*` except for skia which is `area/skia`
This PR fixes the label.
@jeromelaban The labeler created a new `platform/skia` label in https://github.com/unoplatform/uno/pull/10220 which should be deleted.
> build: Fix skia label in labeler.yml

- .github/labeler.yml
- doc/blog/201808-UnoUnderTheHoodButton.md
> ci: Correct documentation directory for labeler

- src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.Xaml.cs
- src/Uno.UI/UI/Xaml/Media/VisualTreeHelper.Android.cs
- Bugfix
- fix(hotreload): Propagate the data context and replace the frame content
- fix(hotreload): Use Panel APIs to propagate DO parent changes on swapping
> Misc hot reload adjustments

- build/Uno.WinUI.Lottie.nuspec
- build/Uno.WinUI.Svg.nuspec
- doc/articles/features/Lottie.md
- src/AddIns/Uno.UI.Lottie/buildTransitive/Uno.UI.Lottie.targets
- src/AddIns/Uno.UI.Svg/buildTransitive/Uno.UI.Svg.targets
- src/Directory.Build.targets
- src/SamplesApp/SamplesApp.Skia.WPF/SamplesApp.Skia.WPF.csproj
- src/SolutionTemplate/UnoSolutionTemplate.WinUI.net6/Skia.Gtk/UnoQuickStart.Skia.Gtk.csproj
- src/SolutionTemplate/UnoSolutionTemplate.WinUI.net6/Skia.Linux.FrameBuffer/UnoQuickStart.Skia.Linux.FrameBuffer.csproj
- src/SolutionTemplate/UnoSolutionTemplate.WinUI.net6/Skia.WPF/UnoQuickStart.Skia.WPF.csproj
- src/SolutionTemplate/UnoSolutionTemplate/Skia.Tizen/UnoQuickStart.Skia.Tizen.csproj
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/6973
- Bugfix
Update SkiaSharp fix many rendering issues.
> chore: Bump to skiasharp 2.88.3

- build/uno.winui.winappsdk.targets
- Bugfix
Fix incorrect path validation for WinAppSDK
> fix(reg): Typo in WinAppSDK validation target

- build/Uno.UI.Build.csproj
- src/Uno.UI/MixinGeneration.targets
- src/Uno.UI/Uno.UI.Skia.csproj
Tentative to reduce race conditions on T4 generation.
> ci: Use packagereference for t4 runner

- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp/.vscode/settings.json
- src/SolutionTemplate/UnoSolutionTemplate.WinUI.net6/Skia.Gtk/UnoQuickStart.Skia.Gtk.csproj
- src/SolutionTemplate/UnoSolutionTemplate.WinUI.net6/Skia.Linux.FrameBuffer/UnoQuickStart.Skia.Linux.FrameBuffer.csproj
- src/Uno.CrossTargetting.props
- Bugfix
- Feature
- fix(gtk): Use font assets regardless of the presence of the Windows project
- feat: Add file nesting for vscode
- ci: Adjust local override when using WinUI source tree
> Misc template updates

- .vsts-ci.yml
A separate pipeline is already processing it.
> ci: Remove docs from main build

- build/Uno.WinUI.XamlHost.nuspec
- build/Uno.WinUI.nuspec
- src/Directory.Build.targets
- src/SamplesApp/SamplesApp.Skia.WPF/SamplesApp.Skia.WPF.csproj
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.Wasm/BlankApp.Wasm.csproj
- src/SolutionTemplate/UnoLibraryTemplate.netcore/CrossTargetedLibrary.csproj
- src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/Shared/Shared.netcore.vstemplate
- src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/Wasm/UnoQuickStart.Wasm.csproj
- src/SolutionTemplate/UnoSolutionTemplate.Wizard.2019/NuGet-netcore.config
- src/SolutionTemplate/UnoSolutionTemplate.Wizard.2022/NuGet-netcore.config
- src/SolutionTemplate/UnoSolutionTemplate.netcore/Shared/Shared.netcore.vstemplate
- src/SolutionTemplate/UnoSolutionTemplate.netcore/Wasm/UnoQuickStart.Wasm.csproj
- src/SolutionTemplate/UnoSolutionTemplate/Wasm/UnoQuickStart.Wasm.csproj
- src/SourceGenerators/Uno.UI.Tasks/Content/uno.ui.tasks.assets.targets
- src/Uno.UI.Runtime.Skia.Wpf/Uno.UI.Runtime.Skia.Wpf.csproj
- src/Uno.UI.TestComparer/Comparer/TestFilesComparer.cs
- Bugfix
- Stable packages bumps
- Restored incorrect vsix template change after folder rename
- Fix typo in XamlHost nuspec
> Misc nuget upgrades, template fixes

- build/uno.winui.winappsdk.targets
- src/SourceGenerators/Uno.UI.Tasks/Uno.UI.Tasks.csproj
- Bugfix
- Adjust dependency removal for WinAppSDK
> fix(reg): Adjust winappsdk references cleanup

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Media_Animation/DoubleAnimation_Tests.FinalState_Transforms.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/9080
> ci(android): disable flaky When_Transforms_Paused_With_FillBehaviorStop_Then_Hold

- doc/articles/supported-libraries.md
Added the OxyPlot library to the list because it's on par with the others in terms of support
Test application: https://havendv.github.io/H.OxyPlot/
> docs: Added OxyPlot to supported libraries.

- src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Media_Animation/DoubleAnimation_Tests.FinalState_Transforms.cs
> ci: Adjust disable When_Transforms_Paused_With_FillBehaviorStop_Then_Hold

- src/Uno.UI.BindingHelper.Android/Uno/UI/BorderLayerRendererNative.java
- src/Uno.UI.BindingHelper.Android/Uno/UI/BrushNative.java
- src/Uno.UI.BindingHelper.Android/Uno/UI/UIElementNative.java
- src/Uno.UI/UI/Xaml/Controls/Border/BorderLayerRenderer.Android.cs
- src/Uno.UI/UI/Xaml/CornerRadius.Android.cs
- src/Uno.UI/UI/Xaml/Media/Brush.Android.cs
- src/Uno.UI/UI/Xaml/UIElement.Android.cs
> perf: Specialized bindings

- .editorconfig
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/unoapp-prism/BlankApp.Wasm/Program.cs
- src/SolutionTemplate/Uno.ProjectTemplates.Dotnet/content/xamarinforms-wasm/UnoXFQuickStart.Wasm/Program.cs
- src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/Server/Program.cs
- src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/Skia.Gtk/Program.cs
- src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/Skia.Linux.FrameBuffer/Program.cs
- src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/Wasm/Program.cs
- src/SolutionTemplate/UnoSolutionTemplate.netcore/Skia.Gtk/Program.cs
- src/SolutionTemplate/UnoSolutionTemplate.netcore/Skia.Linux.FrameBuffer/Program.cs
- src/SolutionTemplate/UnoSolutionTemplate.netcore/Wasm/Program.cs
- src/SolutionTemplate/UnoSolutionTemplate/Skia.Gtk/Program.cs
- src/SolutionTemplate/UnoSolutionTemplate/Skia.Linux.FrameBuffer/Program.cs
- src/SolutionTemplate/UnoSolutionTemplate/Skia.Tizen/Program.cs
- src/SolutionTemplate/UnoSolutionTemplate/Wasm/Program.cs
> build: Enable all perf analyzers
